<?
  $searchTabs = $this->searchtabs()->getTabConfigForParams($this->params);
?>
<? if (count($searchTabs) > 0): ?>
  <div class="info">
    <?=$this->transEsc('nohit_change_tab', array('%%activeTab%%' => $this->translate($this->recommend->getActiveTab($searchTabs)['label'])))?>
    <ul>
    <? $inactiveTabs = $this->recommend->getInactiveTabs($searchTabs); ?>
    <? foreach ($inactiveTabs as $tab): ?>
      <li>
        <a href="<?=$tab['selected'] ? '' : $this->escapeHtmlAttr($tab['url'])?>">
          <?=$this->transEsc($tab['label']); ?>
        </a>
      </li>
    <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>
