<div id="breaking_news">
  <h4 style="color: #360; margin-top: 12px; margin-bottom: 2px">Achtung:</h4>
  <p>Der Index Biblicus ist ein Teilausschnitt aus dem IxTheo. Er bietet eine Fachauswahl für die exegetischen Fächer. Die Selektion der Titel ist schon aktuell. Siehe die Auswahlkriterien <a href="https://github.com/ubtue/tuefind/wiki/Daten-Abzugs--und-Selektionskriterien#selektionskriterium-f%C3%BCr-das-subsystem-bibelwissenschaften-index-biblicus" target="_blank">hier</a>. Layout und Texte müssen noch angepasst werden, wir bitten um Geduld!</p>
</div>
