<?php
  $this->assetManager()->appendScriptLink('vendor/nouislider.min.js');
  $this->assetManager()->appendStyleLink('vendor/nouislider.min.css');
  $this->assetManager()->appendScriptLink('date_range_slider.js');
  $past = 1400;
  $future = (int)date('Y', time() + 31536000); // next year
  $low = !empty($this->values[0]) ? (int)$this->values[0] : $past;
  $high = !empty($this->values[1]) ? (int)$this->values[1] : $future;
  $min = min($low, $past);
  $max = max($high, $future);
  $sliderOptions = [
    'range' => [
      'min' => $min,
      'max' => $max,
    ],
    'start' => [$low, $high],
  ];
  $sliderAttrs = [
    'id' => $this->sliderId,
    'class' => 'range-slider',
    'data-options' => json_encode($sliderOptions),
    'data-input-min-id' => $this->inputMinId,
    'data-input-max-id' => $this->inputMaxId,
  ];
?>
<div class="slider-container" aria-hidden="true"><div<?=$this->htmlAttributes($sliderAttrs)?>></div></div>
