<?php
  $this->assetManager()->appendScriptLink('vendor/nouislider.min.js');
  $this->assetManager()->appendStyleLink('vendor/nouislider.min.css');
  $this->assetManager()->appendScriptLink('date_range_slider.js');
  $rangeMin ??= 1400;
  $rangeMax ??= (int)date('Y') + 1;
  $low = ('' !== ($this->values[0] ?? '')) ? (int)$this->values[0] : $rangeMin;
  $high = ('' !== ($this->values[1] ?? '')) ? (int)$this->values[1] : $rangeMax;
  $sliderOptions = [
    'range' => [
      'min' => min($low, $rangeMin),
      'max' => max($high, $rangeMax),
    ],
    'start' => [$low, $high],
  ];
  $sliderAttrs = [
    'id' => $this->sliderId,
    'class' => 'range-slider',
    'data-options' => json_encode($sliderOptions),
    'data-input-min-id' => $this->inputMinId,
    'data-input-max-id' => $this->inputMaxId,
  ];
?>
<div class="slider-container" aria-hidden="true"><div<?=$this->htmlAttributes($sliderAttrs)?>></div></div>
