<?php
  /**
   * Component to display a button that drops down a menu of options.
   *
   * @param ?string $href         URL to link the menu button to, as a non-Javascript fallback (optional)
   * @param array   $menuItems    Array of arrays representing menu items; each element can/should contain these keys:
   *                              - external (bool): if true, apply a target of _blank to the link (default = false)
   *                              - label (string): text of menu option link (required, will be translated)
   *                              - description (string): description displayed below the label (optional, will be translated)
   *                              - lightbox (bool): if true, open the link in a lightbox (default = false)
   *                              - selected (bool): is this the active menu item? (default = false)
   *                              - url (string): target link for menu option (required)
   *                              - setQueryParams (array): An array of query parameters to set when the menu item is
   *                                clicked instead of following the url (optional)
   * @param ?array  $toggleAttrs  Additional attributes to apply to the toggle button
   * @param string  $toggleLabel  The label for the toggle button (will be translated)
   * @param ?string $wrapperTag   Tag to use as a wrapper around the control (default = div)
   * @param ?string $wrapperClass Extra CSS class(es) to apply to the wrapper tag
   * @param ?string $menuAlign    Alignment of the drop-down. Default is alignment with the start side of its parent.
   *                              'end' aligns with the end side of its parent.
   */
  $wrapperTag = $this->wrapperTag ?? 'div';
  $wrapperClass = 'dropdown'; // Bootstrap class

  if ($this->wrapperClass ?? false) {
    $wrapperClass = $this->wrapperClass . ' dropdown'; // Bootstrap class
  }
  $wrapperClass .= ' ' . $this->_componentClass;

  $toggleTag = 'button';
  $defaultAttrs = [
    'type' => 'button', // Accessible default
    'class' => 'dropdown-toggle', // Bootstrap class
    'data-bs-toggle' => 'dropdown', // Bootstrap data-attr
    'aria-expanded' => 'false',
    'aria-haspopup' => 'true',
  ];

  // An anchor tag with an href should only be used as
  // a non-js fallback to open the menu on another page
  if ($this->href ?? false) {
    $toggleTag = 'a';
    $defaultAttrs['href'] = $this->href;
    $defaultAttrs['type'] = null;
  }

  $toggleAttrs = array_merge($defaultAttrs, $this->toggleAttrs ?? []);
?>

<?php ob_start(); ?>
  <?=$this
      ->makeTag(
          $toggleTag,
          $this->transEsc($this->toggleLabel) . $this->icon('dropdown-caret'),
          $toggleAttrs,
          ['escapeContent' => false]
      )
  ?>

  <?php
    $menuAttributes = $this->htmlAttributes(['class' => 'dropdown-menu']);
    if ('end' == ($this->menuAlign ?? null)) {
      $menuAttributes->add('class', 'dropdown-menu-end');
    }
  ?>
  <ul<?=$menuAttributes?>>
    <?php foreach ($this->menuItems as $current): ?>
      <li class="dropdown__item">
        <a class="dropdown-item dropdown__link<?=($current['selected'] ?? false) ? ' active' : ''?>"
          href="<?=$this->escapeHtmlAttr($current['url']) ?>"
          <?php if ($current['external'] ?? false): ?> target="_blank"<?php endif; ?>
          <?php if ($current['lightbox'] ?? false): ?> data-lightbox="true"<?php endif; ?>
          <?php if ($setParams = $current['setQueryParams'] ?? null): ?> data-click-set-query-params="<?=$this->escapeHtmlAttr(http_build_query($setParams))?>"<?php endif; ?>
          rel="nofollow"
        >
          <span><?=$this->transEsc($current['label']) ?></span>
          <?php if ($description = $current['description'] ?? false): ?>
            <span class="description"><?=$this->transEsc($description)?></span>
          <?php endif; ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
<?php $menuContents = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?=$this->makeTag($wrapperTag, $menuContents, $wrapperClass, ['escapeContent' => false]) ?>
