<?php
  $titleTranslated = $this->translate($this->title);
  $headerAttrs = [
    'class' => 'lightbox-header ' . $this->_componentClass,
  ];
  if ($this->inLightbox) {
    $headerAttrs['tabindex'] = '0';
  }
  $defaultLevel = $this->inLightbox ? 2 : 1;
  $level = $this->level ?: $defaultLevel;
  $tag = "h$level";
  $this->headTitle($titleTranslated);
?>
<<?=$tag?><?=$this->htmlAttributes($headerAttrs)?>><?=$this->escapeHtml($titleTranslated);?></<?=$tag?>>
