<?php
  /**
   * Component to display a star rating.
   *
   * @param ?bool  $allowClear Should the control include a clear button? (default = false)
   * @param ?array $labelAttrs Array of HTML attributes to apply to the label (optional)
   * @param ?array $inputAttrs Array of HTML attributes to apply to the input (optional)
   * @param array  $ratingData Rating data (array containing 'count' and 'rating' values)
   * @param ?bool  $readonly   Should the control be read-only? (default = false)
   */
  $id = $this->escapeHtmlAttr(uniqid());
  $labelAttrs = !empty($this->labelAttrs) ? (' ' . implode(' ', $this->labelAttrs)) : '';
  $inputAttrs = !empty($this->inputAttrs) ? (' ' . implode(' ', $this->inputAttrs)) : '';
  $rating = $ratingData['count'] ? ($ratingData['rating'] ?? 0) : null;
  // Round down to nearest 10 only if rating is not null
  $roundedRating = $rating === null
    ? null
    : (string)max(0, floor($rating / 10) * 10);
  // Unique name for the fields of read-only ratings so that displaying multiple ratings on a page works:
  $fieldName = $this->readonly ? "rating_{$id}" : 'rating';
?>
<?php if ($this->readonly): ?>
  <div class="visually-hidden">
    <?= $rating === null
      ? $this->transEsc('rating_none')
      : $this->transEsc('rating') . ': ' . $this->transEscWithPrefix('rating_', $roundedRating)
    ?>
  </div>
<?php endif; ?>
<div role="radiogroup" class="star-rating<?=$this->readonly ? ' readonly' : ''?>" <?=$this->readonly ? 'aria-hidden="true"' : 'aria-label="' . $this->transEsc('rating_instructions_screenreader') . '"'?>>
  <label inert class="rating__label hidden" for="rating_<?=$id?>_none" <?=$labelAttrs?>>
    &nbsp;
  </label>
  <input aria-hidden="true" class="rating__input" name="<?=$fieldName?>" id="rating_<?=$id?>_none" value="" type="radio"<?=null === $rating ? ' checked' : ''?><?=$inputAttrs?><?=$this->readonly ? ' disabled' : ''?>>
  <?php for ($level = 10; $level <= 100; $level += 10): ?>
    <?php
      $fieldId = "rating_{$id}_$level";
      $rangeLow = $level;
      $rangeHigh = 100 === $level ? 101 : ($level + 10);
      $class = $level % 20 === 10 ? ' rating__label--half' : '';
      $icon = $this->icon($level % 20 === 10 ? 'rating-half' : 'rating-full', 'rating__icon rating__icon--star');
    ?>
    <label class="rating__label<?=$class?>" for="<?=$fieldId?>" <?=$labelAttrs?>>
      <?=$icon?>
    </label>
    <input class="rating__input" name="<?=$fieldName?>" aria-label="<?=$this->transEsc("rating_$level")?>" id="<?=$fieldId?>" value="<?=$level ?>" type="radio"<?=$rating >= $rangeLow && $rating < $rangeHigh ? ' checked ' : ''?><?=$this->readonly ? ' disabled ' : ''?><?=$inputAttrs?>>
  <?php endfor; ?>
</div>
<?php if (!empty($this->allowClear)): ?>
  <a href="#" data-click-set-checked="rating_<?=$id?>_none"><?=$this->transEsc('Clear')?></a>
<?php endif; ?>
