<?php
    /**
     * Component to create a basic striped table.
     * - class => Class names for the component. Default is 'table table-striped vc-table-striped'
     * - contents => Same as tbody in a table. Each row of data is presented as an array containing td elements as values.
     *               Key for the row is handled as an th element.
     *
     * Available styles for the tables children:
     * - centered-start => flex aligning items into center and justifying content to start
     * - centered-end => flex aligning items into center and justifying content to end
     *
     * Example:
     * this->component('table-striped', [
     *  'contents' => [
     *      'first row' => [
     *          'Data1',
     *          'Data2',
     *       ],
     *      'second row' => [
     *          'Data3',
     *          'Data4',
     *       ],
     *  ],
     * ]);
     *
     * will result in:
     * <table class="table table-striped vc-table-striped">
     *  <tbody>
     *   <tr><th>first row</th><td>Data1</td><td>Data2</td></tr>
     *   <tr><th>second row</th><td>Data3</td><td>Data4</td></tr>
     *  </tbody>
     * </table>
     */
    $tableAttrs = [
        'class' => trim('table table-striped ' . $this->_componentClass . ' ' . ($this->class ?? '')),
    ];
    $contents = $this->contents ?? [];

    $createRow = function ($label, $row) {
        $template = '<tr>';
        if (is_string($label)) {
            $template .= "<th>$label</th>";
        }
        for ($i = 0; $i < count($row); $i++) {
            $template .= "<td>$row[$i]</td>";
        }
        $template .= '</tr>';
        return $template;
    };
?>
<table<?=$this->htmlAttributes($tableAttrs)?>>
    <?php if ($contents): ?>
        <tbody>
            <?php foreach ($contents as $label => $value): ?>
                <?=$createRow($label, $value);?>
            <?php endforeach; ?>
        </tbody>
    <?php endif; ?>
</table>
