<!-- finc: documentdeliveryservice - form -->
<?php
/**
 * Copyright (C) 2021 Leipzig University Library
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as
 * published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 *
 * @author   Gregor Gawol <gawol@ub.uni-leipzig.de>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU GPLv2
 */

use Laminas\Form\Element;
use Laminas\Form\Element\Submit;
use Laminas\Form\Form;
use Laminas\Form\View\Helper\FormElementErrors;
use Laminas\Form\View\Helper\FormLabel;
use Laminas\Form\View\Helper\FormSelect;
use Laminas\Form\View\Helper\FormSubmit;

/** @var Form $form */
/** @var FormLabel $formLabel */
/** @var FormSelect $formSelect */
/** @var FormSubmit $formSubmit */
/** @var FormElementErrors $formElementErrors */
$form = $this->form;
$formLabel = $this->formLabel();
$formSelect = $this->formSelect();
$formSubmit = $this->formSubmit();
$formElementErrors = $this->formElementErrors();
$formLabel->setTranslatorTextDomain('DDS');
$formSelect->setTranslatorTextDomain('DDS');
$formSubmit->setTranslatorTextDomain('DDS');
$formElementErrors->setTranslatorTextDomain('DDS');
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h1><?=$this->transEsc('DDS::dds_form_headline')?></h1>
  <?=$this->flashmessages()?>
  <?=$this->form()->openTag($form)?>
    <?php if ($this->department): ?>
      <input type="hidden" name="subito[hdepartment]" value="<?=$this->department?>">
    <?php endif; ?>
  <?php /* name */ ?>
  <?php
  /** @var Element\Text $elemName */
  $elemName = $form->get('username');
  $elemName->setLabelAttributes(['class' => 'control-label']);
  $elemName->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemName)?>
    <?=$this->formElement($elemName)?>
    <?=$this->formElementErrors($elemName)?>
  </div>

  <?php /* phone */ ?>
  <?php
  /** @var Element\Text $elemPhone */
  $elemPhone = $form->get('phone');
  $elemPhone->setLabelAttributes(['class' => 'control-label']);
  $elemPhone->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemPhone)?>
    <?=$this->formElement($elemPhone)?>
  </div>

  <?php /* email */ ?>
  <?php
  /** @var Element\Email $elemEmail */
  $elemEmail = $form->get('email');
  $elemEmail->setLabelAttributes(['class' => 'control-label']);
  $elemEmail->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemEmail)?>
    <?=$this->formElement($elemEmail)?>
    <?=$this->formElementErrors($elemEmail)?>
  </div>

  <?php /* userid */ ?>
  <?php
  /** @var Element\Text $elemUserid */
  $elemUserid = $form->get('userid');
  $elemUserid->setLabelAttributes(['class' => 'control-label']);
  $elemUserid->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemUserid)?>
    <?=$this->formElement($elemUserid)?>
    <?=$this->formElementErrors($elemUserid)?>
  </div>

  <?php /* division */ ?>
  <?php
  /** @var Element\Select $elemDivision */
  $elemDivision = $form->get('division');
  $elemDivision->setLabelAttributes(['class' => 'inline control-label']);
  $elemDivision->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemDivision)?>
    <?=$this->formSelect($elemDivision)?>
    <?=$this->formElementErrors($elemDivision)?>
  </div>

  <?php /* department */ ?>
  <?php
  /** @var Element\Select $elemDepartment */
  $elemDepartment = $form->get('department');
  $elemDepartment->setLabelAttributes(['class' => 'inline control-label']);
  $elemDepartment->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group input-sdepartment">
    <?=$this->formLabel($elemDepartment)?>
    <?=$this->formSelect($elemDepartment)?>
    <?=$this->formElementErrors($elemDepartment)?>
  </div>

  <?php /* department medicine */ ?>
  <?php
  /** @var Element\Text $elemMdepartment */
  $elemMdepartment = $form->get('inputdepartment');
  $elemMdepartment->setLabelAttributes(['class' => 'control-label']);
  $elemMdepartment->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group input-department">
    <?=$this->formLabel($elemMdepartment)?>
    <?=$this->formElement($elemMdepartment)?>
    <?=$this->formElementErrors($elemMdepartment)?>
  </div>

  <?php /* author */ ?>
  <?php
  /** @var Element\Text $elemAuthor */
  $elemAuthor = $form->get('author');
  $elemAuthor->setLabelAttributes(['class' => 'control-label']);
  $elemAuthor->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemAuthor)?>
    <?=$this->formElement($elemAuthor)?>
    <?=$this->formElementErrors($elemAuthor)?>
  </div>

  <?php /* title of issue */ ?>
  <?php
  /** @var Element\Text $elemArticle */
  $elemArticle = $form->get('article');
  $elemArticle->setLabelAttributes(['class' => 'control-label']);
  $elemArticle->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemArticle)?>
    <?=$this->formElement($elemArticle)?>
    <?=$this->formElementErrors($elemArticle)?>
  </div>

  <?php /* title of journal */ ?>
  <?php
  /** @var Element\Text $elemJournal */
  $elemJournal = $form->get('journal');
  $elemJournal->setLabelAttributes(['class' => 'control-label']);
  $elemJournal->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemJournal)?>
    <?=$this->formElement($elemJournal)?>
    <?=$this->formElementErrors($elemJournal)?>
  </div>

  <?php /* issn */ ?>
  <?php
  /** @var Element\Text $elemIssn */
  $elemIssn = $form->get('issn');
  $elemIssn->setLabelAttributes(['class' => 'control-label']);
  $elemIssn->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemIssn)?>
    <?=$this->formElement($elemIssn)?>
    <?=$this->formElementErrors($elemIssn)?>
  </div>

  <?php /* publish date */ ?>
  <?php
  /** @var Element\Text $elemPublishdate */
  $elemPublishdate = $form->get('publishdate');
  $elemPublishdate->setLabelAttributes(['class' => 'control-label']);
  $elemPublishdate->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemPublishdate)?>
    <?=$this->formElement($elemPublishdate)?>
    <?=$this->formElementErrors($elemPublishdate)?>
  </div>

  <?php /* journal number */ ?>
  <?php
  /** @var Element\Text $elemNumber */
  $elemNumber = $form->get('number');
  $elemNumber->setLabelAttributes(['class' => 'control-label']);
  $elemNumber->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemNumber)?>
    <?=$this->formElement($elemNumber)?>
    <?=$this->formElementErrors($elemNumber)?>
  </div>

  <?php /* pages */ ?>
  <?php
  /** @var Element\Text $elemPages */
  $elemPages = $form->get('pages');
  $elemPages->setLabelAttributes(['class' => 'control-label']);
  $elemPages->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemPages)?>
    <?=$this->formElement($elemPages)?>
    <?=$this->formElementErrors($elemPages)?>
  </div>

  <?php /* remarks */ ?>
  <?php
  /** @var Element\Textarea $elemRemarks */
  $elemRemarks = $form->get('remarks');
  $elemRemarks->setLabelAttributes(['class' => 'control-label']);
  $elemRemarks->setAttributes(['class' => 'form-control']);
  ?>
  <div class="form-group">
    <?=$this->formLabel($elemRemarks)?>
    <?=$this->formElement($elemRemarks)?>
    <?=$this->formElementErrors($elemRemarks)?>
  </div>

  <?php /* submit button */ ?>
  <?php
  /** @var Submit $elemSubmit */
  $elemSubmit = $form->get('submit');
  $elemSubmit->setAttributes(['class' => 'btn btn-primary']);
  ?>

  <div class="form-group"><?= $this->formSubmit($elemSubmit) ?></div>
  <?= $this->form()->closeTag($form)?>

  <div class="subito-pg margin-t">
    <?=$this->transEsc("DDS::dds_text_questions")?>
    <a href="mailto:info@ub.uni-leipzig.de?subject=<?=$this->transEsc("Dokumentenlieferdienst")?>">info@ub.uni-leipzig.de</a>
  </div>

  <div class="input-department subito-pg">
    <div><?=$this->transEsc("Bei eventuellen Rückfragen wenden Sie sich bitte an die Abteilung Fernleihe der Medizin")?>:</div>
    <div><?=$this->transEsc("Phone")?>: +49 (0)341 - 97 14014</div>
    <div><?=$this->transEsc("Email")?>: <a href="mailto:zbmed.fernleihe@medizin.uni-leipzig.de?subject=<?=$this->transEscAttr("Dokumentenlieferdienst")?>">zbmed.fernleihe@medizin.uni-leipzig.de</a>
    </div>
  </div>
  <div class="subito-pg">
    <p class="required">
      * <?=$this->transEsc("DDS::dds_text_mandatory_fields")?></p>
  </div>
</div>

<?php
$this->inlineScript()->captureStart();
echo <<<JS
  $(document).ready(function(){
    department.init($('select[name="division"]').val(), true);
    $('select[name="division"]').change(function() {
      department.init($(this).val(), false);
    });
  });
/**
* Show & hide of subito form elements regarding select menu status.
* Add options for department select menu
*
* @author Frank Morgner<morgnerf@ub.uni-leipzig.de>
* @see https://katalog.ub.uni-leipzig.de/Subito/Subito
**/

var department = {
  init: function ( divisionid, forceKeepOptions ) {
    addOptions = false;
    var elements = [];
    if ( divisionid == '15') {
      elements = {
        "department":"show",
        "sdepartment":"hide"
      }
    } else if (divisionid == '') {
      elements = {
        "department":"hide",
        "sdepartment":"hide"
      }
    } else {
      elements = {
        "department":"hide",
        "sdepartment":"show"
        }
        if (!forceKeepOptions) {
            var addOptions = true;
        }
    }
    department.showHideElements(elements);
    if (addOptions) {
        department.addDepartmentOptions( divisionid );
      }
    },
    addDepartmentOptions: function ( divisionid ) {
      $('select[name="department"]').empty();
      var departments = $this->departments;
      department.addOptionElement('','');
      $.each(departments[divisionid], function (index, value) {
        department.addOptionElement(value,index);
      });
    },
    addDepartmentSelect: function (departmentid, divisionid) {
      department.init ( divisionid );
      department.addSelectElement ( departmentid );
    },
    addOptionElement: function ( text, value ) {
      jQuery('<option/>', {
        text: department.htmlEntitiesDecode(text),
        value: value
      }).appendTo('select[name="department"]');
    },
    addSelectElement: function ( departmentid )  {
      $('select[name="department"] option').filter(function () {
        //console.log($(this).val() + ' == ' + departmentid);
        return $(this).val() == departmentid;
      }).prop('selected', true);
    },
    htmlEntitiesDecode: function ( value ) {
      if (value) {
        return jQuery('<div/>').html(value).text();
      }
      return value;
    },
    showHideElements: function ( elements ) {
      $.each(elements, function (index, value) {
        if (value == 'show') {
          $('.input-' + index).show(200);
        }
        if (value == 'hide') {
          $('.input-' + index).hide(200);
        }
        let control = $('.input-' + index).find('.form-control');
        if (control) {
            $('.input-' + index).find('.form-control').attr("required", value == 'show');
            $('.input-' + index).find('.form-control').attr("data-required", value == 'show');
            $('.input-' + index).find('label').attr("data-required", value == 'show');
        }
    });
  }
}
JS;
$this->inlineScript()->captureEnd();

echo $this->inlineScript();
?>
<!-- finc: documentdeliveryservice - form - END -->
