<?
  // Set page title.
  $this->headTitle($this->translate('hierarchy_tree') . ': ' . $this->driver->getBreadcrumb());
  $hierarchyTreeList = $this->tab->getTreeList();
  $activeTree = $this->tab->getActiveTree();

  $this->inlineScript(
     \Zend\View\Helper\HeadScript::SCRIPT,
     "var hierarchySettings = {\n"
     . "    lightboxMode: " . ($this->layout()->getTemplate() == 'layout/lightbox' ? 'true' : 'false') . ",\n"
     . "    fullHierarchy: " . ($this->tab->isFullHierarchyVisible() ? 'true' : 'false') . "\n"
     . "};\n",
     'SET'
  );
  $this->jsTranslations()->addStrings(
    array('showTree' => 'hierarchy_show_tree', 'hideTree' => 'hierarchy_hide_tree')
  );
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'jsTree/jquery.jstree.js');
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'jsTree/hierarchyTree.js');
  echo $this->inlineScript();
?>
<div<?=isset($this->mainTreeClass) ? ' class="' . $this->mainTreeClass . '"' : ''?>>
  <? if (count($hierarchyTreeList) > 1): ?>
    <div id="treeSelector">
      <? foreach ($hierarchyTreeList as $hierarchy => $hierarchyTitle): ?>
        <a class="tree<?=($activeTree == $hierarchy) ? ' currentTree' : ''?>" href="<?=$this->recordLink()->getTabUrl($this->driver, 'HierarchyTree')?>?hierarchy=<?=urlencode($hierarchy)?>"><?=$this->escapeHtml($hierarchyTitle)?></a>
      <? endforeach; ?>
    </div>
  <? endif; ?>
  <? if ($activeTree): ?>
    <div id="hierarchyTreeHolder">
      <? if ($this->tab->searchActive()): ?>
        <div id="treeSearch" class="form-search row-fluid">
          <input type="text" id="treeSearchText" class="search-query span6" value="">
          <select class="span3 id="treeSearchType" name="type">
            <option value="AllFields"><?=$this->transEsc('All Fields')?></option>
            <option value="Title"><?=$this->transEsc('Title')?></option>
          </select>
          <input type="submit" class="btn" value="<?=$this->transEsc('Search') ?>"/>
          <span id="treeSearchLoadingImg" class="hide"><i class="icon-spinner icon-large icon-spin"></i></span>
        </div>
        <div id="treeSearchNoResults" class="alert alert-error hide"><?=$this->transEsc('nohit_heading')?></div>
        <div id="treeSearchLimitReached" class="alert alert-error hide"><?=$this->translate('tree_search_limit_reached_html', array('%%url%%' => $this->url('search-results'), '%%limit%%' => $this->tab->getSearchLimit()))?></div>
      <? endif; ?>
      <div id="hierarchyTree" class="pad">
        <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenRecordId" />
        <input type="hidden" value="<?=$this->escapeHtml($activeTree)?>" class="hiddenHierarchyId" />
        <input type="hidden" value="<?=isset($this->treeContext) ? $this->treeContext : 'Record'?>" class="hiddenContext" />
        <? if ($this->layout()->getTemplate() != 'layout/lightbox'): ?>
          <noscript>
            <?=$this->tab->renderTree($this->url('home'))?>
          </noscript>
        <? endif; ?>
      </div>
    </div>
  <? endif; ?>
</div>
