<?
  // Set page title.
  $this->headTitle($this->translate('Comments') . ': ' . $this->driver->getBreadcrumb());
?>

<div id="commentList">
  <?=$this->render('record/comments-list.phtml')?>
</div>
<form class="comment row-fluid" name="commentRecord" id="commentRecord" action="<?=$this->recordLink()->getActionUrl($this->driver, 'AddComment')?>" method="post">
  <div class="span3 text-right">
    <strong><?=$this->transEsc("Your Comment")?>:</strong>
  </div>
  <div class="popover right span9">
    <div class="arrow"></div>
    <div class="popover-content">
      <textarea id="comment" name="comment" class="span12" rows="3" required></textarea>
      <input class="btn" data-loading-text="Submitting..." type="submit" value="<?=$this->transEsc("Add your comment")?>"/>
    </div>
  </div>
  <input type="hidden" name="id" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>"/>
  <input type="hidden" name="source" value="<?=$this->escapeHtml($this->driver->getResourceSource())?>"/>
</form>
