<?
  $this->headTitle($this->translate('Browse the Collection Alphabetically'));
  $this->layout()->breadcrumbs = '<a href="' . $this->url('alphabrowse-home') . '">' . $this->transEsc('Browse Alphabetically') . '</a>';
  $baseQuery = array('source' => $this->source, 'from' => $this->from);
?>

<? /* LOAD THE LINK INFORMATION INTO $pageLinks, similar to smarty's {capture} */ ?>
<? ob_start(); ?>
  <ul class="pager">
    <? if (isset($this->prevpage)): ?>
      <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => $baseQuery + array('page' => $this->prevpage))))?>">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>

    <? if (isset($this->nextpage)): ?>
      <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => $baseQuery + array('page' => $this->nextpage))))?>"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? $pageLinks = ob_get_contents(); ?>
<? ob_end_clean(); ?>

<form class="form-inline" method="get" action="<?=$this->url('alphabrowse-home')?>" name="alphaBrowseForm" id="alphaBrowseForm">
  <label for="alphaBrowseForm_source"><?=$this->transEsc('Browse Alphabetically') ?></label>
  <select id="alphaBrowseForm_source" name="source" class="form-control">
    <? foreach ($this->alphaBrowseTypes as $key => $item): ?>
      <option value="<?=$this->escapeHtmlAttr($key) ?>"<? if ($this->source == $key): ?> selected="selected"<? endif; ?>><?=$this->transEsc($item) ?></option>
    <? endforeach; ?>
  </select>
  <label for="alphaBrowseForm_from"><?=$this->transEsc('starting from') ?></label>
  <input type="text" name="from" id="alphaBrowseForm_from" value="<?=$this->escapeHtmlAttr($this->from) ?>" class="form-control"/>
  <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Browse') ?>"/>
</form>

<? if ($this->result): ?>
  <?=$pageLinks ?>
  <table class="table table-striped">
    <? foreach ($this->result['Browse']['items'] as $i => $item): ?>
      <? if ($i == 0): ?>
        <thead>
          <tr>
            <th class="<?=$this->source ?>"><?=$this->transEsc($this->source) ?></th>
            <? if(!empty($this->extras) || !empty($item['seeAlso']) || $item['note']): ?>
              <th><?=$this->transEsc("information") ?></th>
            <? endif; ?>
            <th><?=$this->transEsc("count") ?></th>
          </tr>
        </thead>
        <tbody>
      <? endif; ?>
        <tr>
          <td class="<?=$this->source ?>">
            <? if ($item['count'] > 0): ?>
              <?/* linking using bib ids is generally more reliable than
                doing searches for headings, but headings give shorter
                queries and don't look as strange. */?>
              <? if ($item['count'] < 5): ?>
                <? $query = array('type' => 'ids', 'lookfor' => implode(' ', $item['ids'])); ?>
              <? else: ?>
                <? $query = array('type' => ucwords($this->source) . 'Browse', 'lookfor' => '"' . addcslashes($item['heading'], '"') . '"'); ?>
              <? endif; ?>
              <a href="<?=$this->escapeHtmlAttr($this->url('search-results', array(), array('query' => $query)))?>"><?=$this->escapeHtml($item['heading'])?></a>
            <? else: ?>
              <span><?=$this->escapeHtml($item['heading'])?></span>
            <? endif; ?>
          </td>

          <? if(!empty($this->extras) || !empty($item['seeAlso']) || $item['note']): ?>
            <td>
              <? foreach ($this->extras as $extraName): ?>
                <? foreach ($item['extras'][$extraName] as $data): ?>
                  <div><?=implode(', ', $data) ?></div>
                <? endforeach; ?>
              <? endforeach; ?>

              <? if (count($item['seeAlso']) > 0): ?>
                <?=$this->transEsc('See also') ?>:
                <ul>
                  <? foreach ($item['seeAlso'] as $heading): ?>
                  <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                  <? endforeach; ?>
                </ul>
              <? endif; ?>

              <? if ($item['note']): ?>
                <?=$this->transEsc('Note') ?>:
                <ul>
                  <li><?=$this->escapeHtml($item['note'])?></li>
                </ul>
              <? endif; ?>
            </td>
          <? endif; ?>
          <td>
            <? if ($item['count'] > 0): ?>
              <?=$item['count']; ?>
            <? elseif (count($item['useInstead']) > 0): ?>
              <?=$this->transEsc('Use instead') ?>:
              <ul>
                <? foreach ($item['useInstead'] as $heading): ?>
                <li><a href="<?=$this->escapeHtmlAttr($this->url('alphabrowse-home', array(), array('query' => array('from' => $heading) + $baseQuery)))?>"><?=$this->escapeHtml($heading)?></a></li>
                <? endforeach; ?>
              </ul>
            <? endif; ?>
          </td>
        </tr>
      <? endforeach; ?>
    </tbody>
  </table>
  <?= $pageLinks ?>
<? endif; ?>
