<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<?php if (!$sessionInitiator): // display default login form if no login URL provided ?>
  <form method="post" class="form-horizontal" action="<?=$this->url('myresearch-home')?>" name="loginForm">
    <?=$this->auth()->getLoginFields()?>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>" />
    <div class="form-group">
      <div class="col-sm-offset-3 col-sm-9">
          <input class="btn btn-primary btn-lg btn-block" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">

          <div class="row pt-3">
              <div class="col-6">
              <?php if ($account->supportsCreation()): ?>
                <a class="btn btn-outline-secondary btn-sm createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
              <?php endif; ?>
              </div>
              <div class="col-6">
              <?php if ($account->supportsRecovery()): ?>
                <a class="btn btn-outline-secondary btn-sm" href="<?=$this->url('myresearch-recover') ?>?auth_method=<?=$account->getAuthMethod()?>" data-lightbox-ignore><?=$this->transEsc('Forgot Password')?></a>
             <?php endif; ?>
              </div>
          </div>
      </div>
    </div>
  </form>
<?php else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" class="btn btn-link" data-lightbox-ignore><?=$this->transEsc("Institutional Login")?></a>
<?php endif; ?>
