<div class="list-group">
  <?php foreach ($result as $i => $item): ?>
    <a class="list-group-item" href="<?=$this->url('collection', ['id' => $item['value']])?>">
      <strong><?=$this->escapeHtml($item['displayText'])?></strong>
      <span class="badge">
        <?=$item['count']?> <?=$this->transEsc('items')?>
        <?=$this->icon('page-next', ['title' => $this->translate('collection_next_page_label')]) ?>
      </span>
    </a>
  <?php endforeach; ?>
</div>
