<?php
    // Set page title.
    $this->headTitle($this->translate('auto_configure_title'));

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('auto_configure_title'), $this->url('install-home'))
        ->add($this->translate('Disabled'), active: true);
?>
<?=$this->component('page-title', ['title' => 'auto_configure_title']);?>

<p><?=$this->transEsc('auto_configure_disabled')?></p>
