<?php
    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('auto_configure_title'), $this->url('install-home'))
        ->add($this->translate('Fix Dependencies'), active: true);
?>
<?=$this->component('page-title', ['title' => $this->translate('auto_configure_title')]);?>

<?=$this->flashmessages()?>

<?php if ($this->problems == 0): ?><p><?=$this->transEsc('No dependency problems found') ?>.</p><?php endif; ?>
