<?php
    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('auto_configure_title'), $this->url('install-home'))
      ->add($this->translate('Fix SSL Certificates'), active: true);

?>
<?=$this->component('page-title', ['title' => $this->translate('auto_configure_title')]);?>

<p>VuFind® is unable to verify SSL certificates. This may adversely impact consumption of secure APIs.</p>

<p>Troubleshooting steps:</p>

<ol>
  <li>Try setting the sslcapath or sslcafile setting in the [Http] section of your config.ini file to point to your local certificate store.</li>
  <li>If you wish to disable certificate checking, you can set sslverifypeer to false in the [Http] section of config.ini. This is <b>insecure</b> and <b>not recommended</b> but may be useful for initial testing purposes.</li>
</ol>
