<?php $this->headLink()->appendStylesheet('EDS.css'); ?>
<?php
    $items = $this->driver->getItems('core');
    $dbLabel = $this->driver->getDbLabel();
    $customLinks = $this->driver->getCustomLinks();
    $accessLevel = $this->driver->getAccessLevel();
    $restrictedView = empty($accessLevel) ? false : true;
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium');
    $cover = $coverDetails['html'];
?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="media-left medium img-col">
    <?php if ($cover): ?>
      <?=$cover?>
    <?php endif; ?>

    <div class="external-links">
      <?php $pLink = $this->driver->getPLink();
          if($pLink): ?>
        <span>
          <a href="<?=$this->escapeHtmlAttr($pLink)?>">
            <?=$this->transEsc('View in EDS')?>
          </a>
        </span><br />
      <?php endif; ?>
      <?php $ftLink = $this->driver->getLinkedFullTextLink();
          if ($ftLink): ?>
        <span>
          <a href="<?=$ftLink?>" class="fulltext">
            <?=$this->transEsc('Linked Full Text')?>
          </a>
        </span><br />
      <?php endif; ?>
      <?php $pdfLink = $this->driver->getPdfLink();
          if ($pdfLink): ?>
        <span>
          <a href="<?=$pdfLink?>" class="icon pdf fulltext">
            <?=$this->transEsc('PDF Full Text')?>
          </a>
        </span><br />
      <?php endif; ?>
      <?php $epubLink = $this->driver->getEpubLink();
          if ($epubLink): ?>
        <span>
          <a href="<?=$epubLink?>" class="icon epub fulltext">
            <?=$this->transEsc('ePub Full Text')?>
          </a>
        </span><br />
      <?php endif; ?>
      <?php if ($this->driver->hasHTMLFullTextAvailable()): ?>
        <span>
          <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>#html" class="icon html fulltext">
            <?=$this->transEsc('HTML Full Text')?>
          </a>
        </span><br />
      <?php endif; ?>
    </div>
  </div>
  <div class="media-body info-col">
    <h1 property="name"><?=$this->driver->getTitle()?></h1>

    <table class="table table-striped">
      <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
      <?php foreach ($items as $key => $item): ?>
        <?php if (!empty($item['Data'])): ?>
        <tr>
          <th><?=empty($item['Label']) ? '' : $this->transEsc($item['Label']) . ':'?></th>
          <td><?=$this->driver->linkUrls($item['Data'])?></td>
        </tr>
        <?php endif; ?>
      <?php endforeach; ?>

      <?php if ($dbLabel): ?>
        <tr>
          <th><?=$this->transEsc('Database')?>:</th>
          <td><?=$this->escapeHtml($dbLabel)?></td>
        </tr>
      <?php endif; ?>

      <?php if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView): ?>
        <?php $fullText = $this->driver->getHtmlFullText(); ?>
        <tr id="html">
          <td colspan="2">
            <?=$fullText?>
          </td>
        </tr>
      <?php elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
        <tr id="html">
          <td>
            <?=$this->transEsc('Full text is not displayed to guests')?>
          </td>
          <td>
            <a class="login" href="<?=$this->url('myresearch-userlogin')?>" rel="nofollow">
              <strong><?=$this->transEsc('Login for full access')?></strong>
            </a>
          </td>
        </tr>
      <?php endif; ?>
    </table>

    <div class="resultItemLine4 custom-links">

    <?php $customLinks = array_merge($this->driver->getFTCustomLinks(), $this->driver->getCustomLinks());
    if (!empty($customLinks)): ?>
      <?php foreach ($customLinks as $customLink): ?>
        <?php
          $url = $customLink['Url'] ?? '';
          $mot = $customLink['MouseOverText'] ?? '';
          $icon = $customLink['Icon'] ?? '';
          $name = $customLink['Text'] ?? '';
        ?>
        <div>
          <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$this->escapeHtmlAttr($mot)?>" class="custom-link">
            <?php if ($icon): ?><img src="<?=$this->escapeHtmlAttr($icon)?>" /> <?php endif; ?><?=$this->escapeHtml($name)?>
          </a>
        </div>
      <?php endforeach; ?>
    <?php endif; ?>

    <?php $doi = $this->doi($this->driver, 'record'); if ($doi->isActive()): ?>
        <div><?=$doi->renderTemplate()?></div>
    <?php endif; ?>
    </div>
  </div>
</div>
