<?php
  $pageTitle = $this->translate('ReservationList::reserve_to_research_room');
  // Set up breadcrumbs:
  $this->breadcrumbs()->set(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($pageTitle, active: true);
  $user = $this->auth()->getUserObject();
?>
<?=$this->component('page-title', ['title' => $pageTitle]);?>

<?php // TODO: create a component which handles the defaulting into prettier form ?>
<?php if ($title = $listHandler->getTitle($this->layout()->userLang)): ?>
  <strong><?= $this->escapeHtml($title); ?></strong>
<?php else: ?>
  <strong><?= $this->transEscWithPrefix('source_', $listHandler->getInstitution()) . ': ' . $this->escapeHtml($listHandler->getIdentifier()); ?></strong>
<?php endif; ?>

<?php if ($description = $listHandler->getDescription($this->layout()->userLang)): ?>
  <p><?= $this->escapeHtml($description); ?></p>
<?php endif; ?>

<?php if (!empty($this->listsContaining)): ?>
  <p><?=$this->transEsc('This item is already part of the following list/lists') ?>:
  <?php foreach ($this->listsContaining as $i => $listEntity): ?>
    <a href="<?=$this->url('reservationlist-displaylist', ['listId' => $listEntity->getId()]) ?>" data-lightbox-ignore><?=$this->escapeHtml($listEntity->getTitle())?></a><?php if ($i < count($this->listsContaining) - 1): ?>, <?php endif; ?>
  <?php endforeach; ?>
  </p><hr>
<?php endif; ?>

<div>
  <?php if (!empty($this->listEntities)): ?>
    <form method="post" name="AddItemToReservationList" data-lightbox-onclose="VuFind.refreshPage" action="<?=$this->url('reservationlist-additemtolist'); ?>">
      <input type="hidden" name="recordId" value="<?=$this->escapeHtmlAttr($this->recordId)?>">
      <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->source)?>">
      <input type="hidden" name="listIdentifier" value="<?=$this->escapeHtmlAttr($this->listIdentifier)?>">
      <input type="hidden" name="institution" value="<?=$this->escapeHtmlAttr($this->institution)?>">
      <input type="hidden" name="csrf" value="<?=$this->auth()->getManager()->getCsrfHash()?>">
      <label class="form-label" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
      <div class="form-group">
        <select class="form-select" id="save_list" name="list">
          <?php foreach ($this->listEntities as $listEntity): ?>
            <option value="<?=$this->escapeHtmlAttr($listEntity->getId())?>"><?=$this->escapeHtml($listEntity->getTitle())?></option>
          <?php endforeach; ?>
        </select>
      </div>
      <div class="form-group">
        <label class="form-label" for="add_notes"><?=$this->transEsc('Description') ?></label>
        <textarea class="form-control" id="add_notes" name="desc" rows="3"></textarea>
      </div>
      <div class="form-group">
        <input class="btn btn-primary" type="submit" name="list_selected" value="<?=$this->transEsc('Save')?>">
      </div>
    </form>
  <?php endif; ?>
  <a class="btn btn-link" id="make-list" href="<?=$this->url('reservationlist-createlist', [], ['query' => ['institution' => $listHandler->getInstitution(), 'listIdentifier' => $listHandler->getIdentifier(), 'newList' => '1', 'recordId' => urlencode($this->recordId), 'source' => urlencode($this->source)]])?>"><?=$this->transEsc('ReservationList::Create new list for holds')?></a>
</div>
