<!-- START of: finna - reservationlist/displaylists.phtml -->
<?php
  $title = $this->transEsc('ReservationList::All Lists');
  // Set up page title:
  $this->headTitle($title);

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li class="breadcrumb-item"><a href="' . $this->url('reservationlist-displaylists') . '">' . $title . '</a></li> <li class="breadcrumb-item active">' . $this->transEsc('ReservationList::Reservation List') . '</li>';
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'reservationlist']); ?>


<div class="<?=$this->layoutClass('mainbody-myresearch')?> reservation-list-body">
  <h2><?=$title ?></h2>
  <?= $this->flashmessages() ?>
  <ul class="reservations-list-home-ul">
    <?php foreach ($this->lists ?? [] as $list): ?>
      <?php
        $listTranslations = $this->reservationList($this->auth()->getUserObject())->getListProperties($list->getInstitution(), $list->getListConfigIdentifier())['translation_keys'];
      ?>
      <li class="reservations-list-home-li">
        <div class="reservation-list-header">
          <div>
            <a href="<?= $this->url('reservationlist-displaylist', ['listId' => $list->getId()])?>"><?= $this->escapeHtml($list->getTitle()) ?></a>
          </div>
          <div class="pull-right">
            <?=
              $this->component(
                  'confirm-button',
                  [
                    'buttonLink' => $this->url('reservationlist-deletelist', ['listId' => $list->getId()]),
                    'buttonLabel' => 'delete_list',
                    'confirmLink' => $this->url('reservationlist-deletelist', ['listId' => $list->getId()], ['query' => ['confirm' => 1]]),
                    'header' => 'confirm_delete_list_text',
                    'align' => 'right',
                  ]
              );
            ?>
          </div>
        </div>
        <div class="reservation-list-info">
          <?php // TODO: create a component which handles the defaulting into prettier form ?>
          <div class="location">
            <?php if (!$this->translationEmpty($listTranslations['title'])): ?>
              <?= $this->transEsc($listTranslations['title']); ?>
            <?php else: ?>
              <?= $this->transEscWithPrefix('source_', $list->getInstitution()) . ': ' . $this->escapeHtml($list->getListConfigIdentifier()); ?>
            <?php endif; ?>
          </div>
          <?php if ($list->getOrdered()): ?>
            <div class="list-ordered list-info">
              <?= $this->transEsc('ReservationList::list_ordered', ['%%date%%' => $list->getOrdered()->format('d.m.Y')])?>
            </div>
          <?php endif; ?>
        </div>
      </li>
      <?php endforeach; ?>
  </ul>
</div>
<div class="mylist-mobile mobile-navigation visible-xs visible-sm hidden-print">
  <ul>
    <li class="sidebar-navigation"><?=$this->icon('sidebar-expand', 'expand-icon') ?><?=$this->icon('sidebar-collapse', 'collapse-icon hidden') ?> <?=$this->transEsc('Your Lists')?></li>
  </ul>
</div>
<!-- END of: finna - reservationlist/displaylists.phtml -->
