<!-- START of: finna - reservationlist/displaylist.phtml -->
<?php
  // Set up page title:
  $pageTitle = $this->translate('ReservationList::Reservation List') . ': ' . $this->translate($this->listEntity->getTitle());
  $this->headTitle($pageTitle);

  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate('ReservationList::All Lists'), $this->url('reservationlist-displaylists'))
    ->add($pageTitle, $this->url('reservationlist-displaylist', ['listId' => $this->listEntity->getId()]), active: true);

  $user = $this->auth()->isLoggedIn();
  $recordTotal = $this->results->getResultTotal();
  $listHandler = $this->reservationList($user)->getListHandler($this->listEntity->getInstitution(), $this->listEntity->getListConfigIdentifier());
?>

<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'reservationlist']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?> reservation-list-body">
  <div class="my-research-content">
    <div class="title-wrapper">
      <h2><?=$this->translate($pageTitle) ?></h2>
    </div>
    <?= $this->flashmessages() ?>
    <?php // TODO: create a component which handles the defaulting into prettier form ?>
    <div class="description-wrapper">
      <?php if ($title = $listHandler->getTitle($this->layout()->userLang)): ?>
        </p><?= $this->escapeHtml($title); ?></p>
      <?php else: ?>
        <p><?= $this->transEscWithPrefix('source_', $listHandler->getInstitution()) . ': ' . $this->escapeHtml($listHandler->getIdentifier()); ?></p>
      <?php endif; ?>
    </div>
    <?php if ($description = $listHandler->getDescription($this->layout()->userLang)): ?>
      <div class="description-wrapper">
        <p><?= $this->escapeHtml($description); ?></p>
      </div>
    <?php endif; ?>
    <div class="description-wrapper">
      <?php foreach ($listHandler->getAddress() as $value): ?>
        <p><?=$this->escapeHtml($value);?></p>
      <?php endforeach; ?>
    </div>
    <?php if ($this->listEntity->getDescription() ?? false): ?>
      <div class="description-wrapper">
        <p><?=$this->escapeHtml($this->listEntity->getDescription()); ?></p>
      </div>
    <?php endif; ?>
    <?php if ($this->listEntity->getCreated() ?? false): ?>
      <div class="list-info">
        <p><?= $this->transEsc('ReservationList::list_created', ['%%date%%' => $this->listEntity->getCreated()->format('d.m.Y')]) ?></p>
      </div>
    <?php endif; ?>
    <?php if ($this->listEntity->getOrdered() ?? false): ?>
      <div class="list-info">
        <p><?= $this->transEsc('ReservationList::list_ordered', ['%%date%%' => $this->listEntity->getOrdered()->format('d.m.Y')]) ?></p>
      </div>
    <?php endif; ?>
    <?php if ($this->listEntity->getPickupDate() ?? false): ?>
      <div class="list-info">
        <p><?= $this->transEsc('ReservationList::list_pickup_date', ['%%date%%' => $this->listEntity->getPickupDate()->format('d.m.Y')]) ?></p>
      </div>
    <?php endif; ?>
    <?php if ($this->listEntity->getOrdered() && $this->listEntity->getExternalId()): ?>
      <div class="list-info js-reservation-list-status pending" data-list-id="<?=$this->escapeHtmlAttr($this->listEntity->getId());?>">
      </div>
    <?php endif; ?>
    <div class="list-controls">
      <?php if ($listHandler->isEnabled() && !$this->listEntity->getOrdered() && $this->results->getResults()): ?>
        <a href="<?=$this->escapeHtmlAttr($this->url('reservationlist-placeorder', [], ['query' => ['listId' => $this->listEntity->getId()]]))?>" class="btn btn-primary" data-lightbox><?=$this->transEsc('ReservationList::Order List')?></a>
      <?php endif; ?>
      <?=
        $this->component(
            'confirm-button',
            [
              'buttonLink' => $this->url('reservationlist-deletelist', ['listId' => $this->listEntity->getId()]),
              'buttonLabel' => 'delete_list',
              'buttonClass' => 'btn btn-primary',
              'confirmLink' => $this->url('reservationlist-deletelist', ['listId' => $this->listEntity->getId()], ['query' => ['confirm' => 1]]),
              'header' => 'confirm_delete_list_text',
            ]
        );
      ?>
    </div>
    <div class="mylist-header">
    <?php if ($recordTotal > 0): ?>
      <div class="mylist-controls search-controls">
        <div class="pagination-container">
          <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results])?>
        </div>
        <div class="control-container hidden-print">
          <?=$this->render('search/controls/sort.phtml')?>
          <?=$this->render('search/controls/limit.phtml')?>
        </div>
      </div>
      <div>
        <div class="myaccount-sticky-header"></div>
          <div class="toolbar-sticky-container">
            <?php $multiPageSelection = ($this->config()->get('config')['Social']['multi_page_favorites_selection'] ?? true) ? ' multi-page-selection' : ''; ?>
            <form class="form<?= $multiPageSelection ?>" id="form-reservation-<?= $this->listEntity->getId() ?? ''?>" method="post" name="bulkActionForm" action="<?=$this->url('reservationlist-deletebulk', ['listId' => $this->listEntity->getId()])?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
              <input class="hidden all-ids-global" type="text" name="all_ids_global" value="<?= $this->escapeHtmlAttr(json_encode($this->results->getAllIds())) ?>">
              <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>">
              <div class="toolbar-sticky">
                <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', [
                  'idPrefix' => 'reservationlist_',
                  'list' => $this->listEntity,
                  'canDelete' => (!$this->listEntity->getOrdered()) && $user,
                  'cartEnabled' => false,
                  'email' => false,
                  'export' => false,
                ])?>
              </div>
              <?php foreach ($this->results->getResults() as $i => $current): ?>
                <?php
                  /** @var \Finna\View\Helper\Root\Record */
                  $recordHelper = $this->record($current);
                ?>
                <?= $recordHelper->renderTemplate('list-entry.phtml', ['driver' => $current, 'user' => $this->user, 'list' => null]) ?>
              <?php endforeach; ?>
            </form>
          </div>
        </div>
      <?php else: ?>
        <div class="useraccount-header">
          <h3><?=$this->transEsc('You do not have any saved resources')?></h3>
        </div>
      <?php endif; ?>
    </div>
  </div>
</div>
<div class="mylist-mobile mobile-navigation visible-xs visible-sm hidden-print">
  <ul>
    <li class="sidebar-navigation"><?=$this->icon('sidebar-expand', 'expand-icon') ?><?=$this->icon('sidebar-collapse', 'collapse-icon hidden') ?> <?=$this->transEsc('Your Lists')?></li>
  </ul>
</div>
<!-- END of: finna - reservationlist/displaylist.phtml -->
