<?php
  $list = $this->params->getSortList();
  if (!empty($list)) {
    echo $this->component(
        'menu-button',
        [
          'wrapperClass' => 'search__sort js-search-sort',
          'showSelectedValue' => true,
          'toggleLabel' => 'Sort',
          'menuItems' => array_map(
              function ($item, $val) {
                return [
                  'label' => $item['desc'],
                  'url' => $this->results->getUrlQuery()->setSort($val)->getParams(false),
                  'selected' => $item['selected'] ?? false,
                ];
              },
              $list,
              array_keys($list)
          ),
        ]
    );
  }
