<!-- feedback - FORM.phtml -->
<h2><?=$this->transEsc("Send us your feedback!")?></h2>
<form name="feedback" method="post" action="<?=$this->url('feedback-email')?>">
  <input type="hidden" id="formSuccess" value="<?=$this->transEsc("Form Submitted!")?>"/>
  <input type="hidden" id="feedbackSuccess" value="<?=$this->transEsc("Thank you for your feedback.")?>"/>
  <input type="hidden" id="feedbackFailure" value="<?=$this->transEsc("An error has occurred")?>"/>
  <div class="row">
    <label class="small-3 columns" for="name"><?=$this->transEsc("feedback_name")?></label>
    <div class="small-9 columns">
      <input type="text" id="name" name="name" class="auto-width"/>
    </div>
  </div>
  <div class="row">
    <label class="small-3 columns" for="email"><?=$this->transEsc("Email")?></label>
    <div class="small-9 columns">
      <input type="email" id="email" name="email" class="auto-width"/>
    </div>
  </div>
  <div class="row">
    <label class="small-12 medium-3 columns" for="comments"><?=$this->transEsc("Comments")?></label>
    <div class="small-12 medium-9 columns">
      <textarea id="comments" name="comments" class="auto-width"></textarea>
    </div>
  </div>
  <div class="row">
    <div class="small-4 small-offset-8 medium-9 medium-offset-3 columns">
      <input type="submit" class="button small" value="<?=$this->transEsc("Send")?>" />
    </div>
  </div>
</form>
<!-- feedback - FORM.phtml end -->