<!-- START of: finna - RecordDriver/SolrLrmi/core.phtml -->
<?php
  $rights = $this->driver->getAccessRestrictionsType($this->layout()->userLang);
  $summary = $this->driver->getSummary();
  $externalLink = $this->driver->getExternalLink();
  $materials = $this->driver->getMaterials($this->layout()->userLang);
  $dateCreated = $this->driver->getDateCreated();
  $dateModified = $this->driver->getDateModified();
  $img = $this->recordImage($this->record($this->driver));
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  $formats = $this->driver->getFormats();
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment?>">
    <?= $this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img, 'imageClick' => 'none']) ?>

    <?php if ($this->record($this->driver)->getOrganisationMenuPosition() === 'inline'): ?>
      <div class="organisation-menu">
        <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('record-post-thumbnail.phtml');?>
  </div>
  <?php $thumbnail = ob_get_contents(); ?>
<?php ob_end_clean(); ?>
<div class="media">
  <h1 class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
  <div class="media-body record-information">
    <h1 class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
    <?php if ($results = $this->driver->getAlternativeTitles()): ?>
      <div class="recordAltTitles record-alt-titles">
        <?=implode('<br>', array_map([$this, 'escapeHtml'], $results))?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('cached-record-warning.phtml', ['driver' => $this->driver])?>
    <?=$this->record($this->driver)->getLabelList() ?>

    <?php if (!empty($formats)): ?>
      <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
    <?php endif; ?>
    <div class="record-core-metadata">
      <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field recordAuthors">
          <span>
            <?php foreach ($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?><?php if (!empty($author['affiliation'])): ?>, <?= $this->escapeHtml($author['affiliation']) ?><?php endif;?></a>
            <?php endforeach; ?>
          </span>
        </div>
        <div class="date-created date-modified">
          <span><?= $dateCreated ? $this->transEsc('Created') . ': ' . $dateCreated : '';?><?= $dateCreated && $dateModified ? ', ' : ''?><?= $dateModified ? $this->transEsc('modified') . ': ' . $dateModified : '';?></span>
        </div>
      <?php endif; ?>
      <?php if (!empty($materials)): ?>
        <div class="learning-material">
          <h3><?= $this->transEsc('Contents'); ?></h3>
          <div class="recordURLs local-available-online-record">
            <ul class="truncate-field outer" data-rows="4">
              <?php
                $externalLinkText = $this->translate('external_link');
                $externalLinkAdditionalInfo
                  = $this->record($this->driver)->getExternalLinkAdditionalInfo();
                $linkedFormats = $this->driver->getDownloadableFileFormats();
              ?>
              <?php foreach ($materials as $material): ?>
                <?php $title = $this->escapeHtml($material['title']); ?>
                <?php $isHtml = ('html' === $material['format']); ?>
                <?php $filesize = $this->fileSize($material['filesize']); ?>
                <li class="fulltextField">
                  <?php if (in_array($material['format'], $linkedFormats)): ?>
                    <a href="<?= $this->escapeHtmlAttr($this->proxyUrl($material['url'])) ?>"
                      aria-label="<?= $this->escapeHtmlAttr($externalLinkText) ?>" target="_blank">
                      <?=$this->icon($isHtml ? 'external-link' : 'download') ?>
                      <?= $title ?>
                    </a>
                    (<?= $isHtml
                      ? $this->escapeHtml($externalLinkText)
                      : $this->escapeHtml($material['format'] . ($filesize ? (', ' . $filesize) : ''))
                    ?>)
                  <?php elseif ($externalLink): ?>
                    <a href="<?= $externalLink ?>" aria-label="<?= $this->escapeHtmlAttr($externalLinkText) ?>"
                      target="_blank"><?=$this->icon('external-link') ?><?= $title ?></a>
                    <?= $externalLinkAdditionalInfo ?>
                  <?php else: ?>
                    <?= $title ?>
                  <?php endif; ?>
                </li>
              <?php endforeach; ?>
            </ul>
          </div>
        </div>
      <?php endif; ?>
      <?= $this->record($this->driver)->getMaterialDisclaimer() ?>
      <?php if (!empty($summary)): ?>
        <div class="material-description">
          <?= implode('<br>', array_map([$this, 'escapeHtml'], $summary)) ?>
        </div>
      <?php endif; ?>
      <?php /* Display Main Details */?>
      <?=
        $this->record($this->driver)->renderTemplate(
            'core-fields.phtml',
            [
              'driver' => $this->driver,
              'rights' => $rights,
            ]
        );
      ?>
      <?php /* End Main Details */?>
    </div>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists" id="savedLists">
        <strong><?=$this->transEsc('Saved in')?>:</strong>
      </div>
    <?php endif; ?>

    <?php if ($template = $this->content()->findTemplateForLng('content/Additions/record-post-metadata')): ?>
      <div>
        <?=$this->render($template)?>
      </div>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/SolrLrmi/core.phtml -->
