<!-- START of: finna - RecordDriver/SolrLrmi/material-disclaimer-aoe.phtml -->
<p class="alert alert-aoe">
  <?= $this->transEsc('material_disclaimer_aoe') ?><?php if ($externalLink): ?>
    (<a href="<?= $externalLink ?>" aria-label="<?= $this->transEsc('external_link') ?>" target="_blank">aoe.fi</a>)<?php endif; ?>.
</p>
<!-- END of: finna - RecordDriver/SolrLrmi/material-disclaimer-aoe.phtml -->
