<!-- START of: finna - feedback/response.phtml -->
<?
    // Set page title
    $this->headTitle($this->translate('Feedback'));
    $this->layout()->finnaMainHeader = '<div><h3>' . $this->transEsc('Feedback') . '</h3></div>';
    // Get rid of the feedback tab since this uses the same variables
    $this->layout()->feedbacktab = false;
?>

<div class="feedback-content">
  <?= $this->translate('Thank you for your feedback.'); ?>
</div>
<!-- END of: finna - feedback/response.phtml -->
