<?php
  $form = $this->form;
  $form->prepare();

  $title = $form->getTitle();
  $title = !empty($title) ? $this->translate($title) : null;
  $lightbox = $this->layout()->getTemplate() === 'layout/lightbox';
?>
<?php if (!$lightbox): ?>
<div class="feedback-content">
<?php endif; ?>
  <?php if ($title): ?>
    <?php $this->headTitle($title); ?>
    <?php if (!$lightbox): ?>
      <h1><?=$this->escapeHtml($title)?></h1>
    <?php else: ?>
      <h2><?=$this->escapeHtml($title)?></h2>
    <?php endif; ?>
  <?php endif; ?>
  <p><?= $this->translate($form->getSubmitResponse()) ?></p>
<?php if (!$lightbox): ?>
</div>
<?php endif; ?>
