<?
    // Set up page title:
    $this->headTitle($this->translate('User Account'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Account') . '</li>';
?>
<div class="container">

    <h2><?=$this->transEsc('User Account')?></h2>
    <?=$this->flashmessages()?>
    <div class="col-3">
        <a class="back-to-login btn btn-link" href="<?=$this->url('myresearch-userlogin') ?>"><i class="fa fa-chevron-left" aria-hidden="true"></i> <?=$this->transEsc('Back')?></a>
    </div>

    <form method="post" name="accountForm" id="accountForm" class="form-horizontal" data-toggle="validator" role="form">
      <?=$this->auth()->getCreateFields()?>
      <?=$this->recaptcha()->html($this->useRecaptcha) ?>
      <div class="form-group">

        <div class="col-9">
          <input class="btn btn-primary btn-lg" type="submit" name="submit" value="<?=$this->transEsc('Submit')?>"/>
        </div>

      </div>
    </form>
</div>