<?
    // Set up page title:
    $this->headTitle($this->translate('Login'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Login') . '</li>';

    // Convenience variable:
    $offlineMode = $this->ils()->getOfflineMode();
?>
<? if ($offlineMode == "ils-offline"): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_login_message'])?>
<? else: ?>
  <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
  <?=$this->flashmessages()?>
  <p><?=$this->transEsc('cat_establish_account')?></p>
  <form method="post" action="<?=$this->serverUrl(true)?>" class="form-horizontal">
    <? if ($this->targets !== null): ?>
    <div class="form-group">
      <label class="col-sm-2 control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
      <div class="col-sm-10">
        <select id="login_target" name="target" class="form-control">
        <? foreach ($this->targets as $target): ?>
          <option value="<?=$this->escapeHtmlAttr($target)?>"><?=$this->transEsc("source_$target", null, $target)?></option>
        <? endforeach; ?>
        </select>
      </div>
    </div>
    <? endif; ?>
    <div class="form-group">
      <label class="col-sm-2 control-label" for="profile_cat_username"><?=$this->transEsc('Library Catalog Username')?>:</label>
      <div class="col-sm-10">
        <input id="profile_cat_username" type="text" name="cat_username" value="" class="form-control"/>
      </div>
    </div>
    <div class="form-group">
      <label class="col-sm-2 control-label" for="profile_cat_password"><?=$this->transEsc('Library Catalog Password')?>:</label>
      <div class="col-sm-10">
        <input id="profile_cat_password" type="password" name="cat_password" value="" class="form-control"/>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">
      </div>
    </div>
  </form>
<? endif; ?>
