<?php
  // Set up page title:
  $this->headTitle($this->translate('Edit') . ' : ' . $this->driver->getBreadcrumb());

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . (
        isset($listID)
          ? '<li><a href="' . $this->url('userList', ['id' => $listID]) . '">' . $this->transEsc('List') . '</a></li>'
          : '<li><a href="' . $this->url('myresearch-favorites') . '">' . $this->transEsc('saved_items') . '</a></li>'
    ) . '<li class="active">' . $this->transEsc('Edit') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <?=$this->component('show-account-menu-button')?>

  <h2><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h2>

  <form class="form-list-edit" method="post" name="editForm">
  <?php if (empty($this->savedData)): ?>
    <p class="alert alert-info">
      <?php if (isset($listID)): ?>
        <?=$this->transEsc('The record you selected is not part of the selected list.') ?>
      <?php else: ?>
        <?=$this->transEsc('The record you selected is not part of any of your lists.') ?>
      <?php endif; ?>
    </p>
  <?php else: ?>
    <div class="list-edit-container">
      <?php foreach ($this->savedData as $i => $current): ?>
        <fieldset class="list-edit-group">
          <h3><?=$this->transEsc('List') ?>: <?=$this->escapeHtml($current['listTitle'])?></h3>
          <input type="hidden" name="lists[]" value="<?=$this->escapeHtmlAttr($current['listId']) ?>">
          <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
            <div class="form-group">
              <label class="control-label" for="edit_tags<?=$current['listId'] ?>"><?=$this->transEsc('Tags') ?>:</label>
              <input type="text" name="tags<?=$current['listId'] ?>" id="edit_tags<?=$current['listId'] ?>" class="form-control" value="<?=$this->escapeHtmlAttr($current['tags'])?>">
              <span class="help-block"><?=$this->transEsc('add_tag_note') ?></span>
            </div>
          <?php endif; ?>
          <div class="form-group">
            <label class="control-label" for="edit_notes<?=$current['listId'] ?>"><?=$this->transEsc('Notes') ?>:</label>
            <textarea class="form-control" id="edit_notes<?=$current['listId'] ?>" name="notes<?=$current['listId'] ?>" rows="3"><?=$this->escapeHtml($current['notes'])?></textarea>
          </div>
          <a class="icon-link" href="<?=$this->url('userList', ['id' => $current['listId']]) ?>?delete=<?=urlencode($this->driver->getUniqueId())?>&amp;source=<?=urlencode($this->driver->getSourceIdentifier())?>" id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>delete<?=$current['listId'] ?>" data-lightbox>
            <?=$this->icon('user-list-delete', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('Delete') ?></span>
          </a>
        </fieldset>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
  <?php if (count($this->lists) > 0): ?>
    <hr>
    <div class="form-group">
      <select name="addToList" class="form-control">
        <option value="-1">- <?=$this->transEsc('Add to another list')?> -</option>
        <?php foreach ($this->lists as $listID => $listTitle): ?>
          <option value="<?=$this->escapeHtmlAttr($listID) ?>"><?=$this->escapeHtml($listTitle) ?></option>
        <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>
  <?php if (!empty($this->savedData) || count($this->lists) > 0): ?>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Save') ?>">
    </div>
  <?php endif; ?>
  </form>
</div>
<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render(empty($listID) ? 'favorites' : 'list' . $listID)?>
</div>
