<?php
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Fines') . '</li>';
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Your Fines')?></h2>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->getUserObject()]); ?>

  <?php if (empty($this->fines)): ?>
    <?=$this->transEsc('You do not have any fines')?>
  <?php else: ?>
    <?php
      // Collect the data to build the table; we process this in advance so we
      // can omit empty columns and simplify customization by separating data
      // processing from rendering.
      $tableData = [];
      $totalDue = 0;
      foreach ($this->fines as $record) {
          if (empty($record['title'])) {
              $title = $this->transEsc('not_applicable');
          } elseif (!is_object($record['driver'] ?? null)) {
              $title = $this->escapeHtml(trim($record['title'], '/:'));
          } else {
              $title = '<a href="'
                  . $this->escapeHtmlAttr($this->recordLinker()->getUrl($record['driver']))
                  . '">' . $this->escapeHtml(trim($record['title'], '/:')) . '</a>';
          }
          $tableData['Title'][] = $title;
          $tableData['Checked Out'][] = $this->escapeHtml($record['checkout'] ?? '');
          $tableData['Due Date'][] = $this->escapeHtml($record['duedate'] ?? '');
          $tableData['Fine'][] = $this->transEsc($record['fine'] ?? '');
          $tableData['Fine Description'][] = $this->transEsc($record['description'] ?? '');
          $tableData['Fine Date'][] = $this->escapeHtml($record['createdate'] ?? '');
          $tableData['Fee'][] = isset($record['amount'])
              ? $this->safeMoneyFormat($record['amount'] / 100.00) : '';
          $tableData['Balance'][] = isset($record['balance'])
              ? $this->safeMoneyFormat($record['balance'] / 100.00) : '';
          $totalDue += $record['balance'] ?? 0;
      }

      // Now empty out any unused columns:
      foreach ($tableData as $column => $values) {
          $empty = true;
          foreach ($values as $value) {
              if ('' !== (string)$value) {
                  $empty = false;
                  break;
              }
          }
          if ($empty) {
              unset($tableData[$column]);
          }
      }

      // Create the final list of columns and count of rows:
      $columns = array_keys($tableData);
      $rowCount = count($this->fines);
    ?>
    <table class="table table-striped table-responsive fines-table">
      <caption class="sr-only"><?=$this->transEsc('Your Fines')?></caption>
      <thead>
        <tr>
          <?php foreach ($columns as $header): ?>
            <th scope="col"><?=$this->transEsc($header)?></th>
          <?php endforeach; ?>
        </tr>
      </thead>
      <tbody>
        <?php for ($row = 0; $row < $rowCount; $row++): ?>
          <tr>
            <?php foreach ($columns as $column): ?>
              <?php if ('Title' == $column): ?>
                <th data-label="<?=$this->transEscAttr($column)?>" scope="row"><?=$tableData[$column][$row]?></th>
              <?php else: ?>
                <td data-label="<?=$this->transEscAttr($column)?>"><?=$tableData[$column][$row]?></td>
              <?php endif; ?>
            <?php endforeach; ?>
          </tr>
        <?php endfor; ?>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="<?=count($columns) - 1?>" scope="row"><?=$this->transEsc('Total Balance Due')?></th>
          <td data-label="<?=$this->transEscAttr('Total Balance Due')?>" class="fines-total"><?=$this->safeMoneyFormat($totalDue / 100.00) ?></td>
        </tr>
      </tfoot>
    </table>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('fines')?>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
