<?=$this->component('hide-offcanvas-button')?>
<?php foreach ($this->menu as $menuGroup): ?>
  <h3 id="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>"><?=$this->transEsc($menuGroup['label'])?></h3>
  <nav class="myresearch-menu" aria-labelledby="<?=$this->idPrefix ?? ''?><?=$menuGroup['id']?>">
    <ul<?=!empty($menuGroup['class']) ? ' class="' . $menuGroup['class'] . '"' : ''?>>
      <?php foreach ($menuGroup['MenuItems'] as $item): ?>
        <?php
          $context = [
            'sectionPlugin' => $this->{\VuFind\View\Helper\Root\Section::SECTION_PLUGIN_KEY},
            'active' => $this->active,
            ...$item,
          ];
        ?>
        <?=$this->render($item['template'] ?? 'myresearch/menu-item.phtml', $context)?>
      <?php endforeach; ?>
    </ul>
  </nav>
<?php endforeach ?>
