<?php
  // Grab list object from search results (if applicable):
  $list = $this->results->getListObject();

  // Set up page title:
  $this->headTitle(isset($list) ? $list->getTitle() : $this->translate('saved_items'));

  // Set up breadcrumbs:
  $currPage = isset($list) ? 'List' : 'saved_items';
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc($currPage) . '</li>';

  // Load Javascript dependencies into header:
  $this->headScript()->appendFile('check_item_statuses.js');

  // Load Javascript only if list view parameter is NOT full:
  if ($this->params->getOptions()->getListViewOption() != 'full') {
    $this->headScript()->appendFile('record.js');
    $this->headScript()->appendFile('embedded_record.js');
  }

  $recordTotal = $this->results->getResultTotal();

  // Convenience variable:
  $account = $this->auth()->getManager();
  $user = $this->auth()->getUserObject();
?>

<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$list ? $this->escapeHtml($list->getTitle()) : $this->transEsc('saved_items')?></h2>

  <?php if ($list && $user && $list->getUser()->getId() === $user->getId() && $list->isPublic()): ?>
    <strong>
      <?=$this->icon('user-public-list-indicator', 'user-list__public-icon') ?>
      <?=$this->transEscAttr('public_list_indicator') ?>
    </strong>
  <?php endif; ?>

  <?=$this->flashmessages()?>

  <nav class="search-header hidden-print">
    <div class="search-stats">
      <?php if ($recordTotal > 0): ?>
        <?php
          $transParams = [
            '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
            '%%end%%' => $this->localizedNumber($this->results->getEndRecord()),
            '%%total%%' => $this->localizedNumber($recordTotal),
          ];
        ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      <?php endif; ?>
    </div>
    <div class="search-controls">
      <?php if (isset($list)): ?>
        <?php if ($this->userlist()->userCanEditList($account->getUserObject(), $list)): ?>
          <a href="<?=$this->url('editList', ['id' => $list->getId()]) ?>" class="btn btn-link icon-link">
            <?=$this->icon('user-list-edit', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('edit_list')?></span>
          </a>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId()]]),
                    'buttonIcon' => 'user-list-delete',
                    'buttonLabel' => 'delete_list',
                    'confirmLink' => $this->url('myresearch-deletelist', [], ['query' => ['listID' => $list->getId(), 'confirm' => 1]]),
                    'header' => 'confirm_delete_list_text',
                ]
            )
          ?>
        <?php endif; ?>
      <?php endif; ?>
      <?php if ($recordTotal > 0): ?>
        <?=$this->render('search/controls/limit.phtml')?>
        <?=$this->render('search/controls/sort.phtml')?>
      <?php endif; ?>
    </div>
  </nav>
  <?php if ($list && !empty($listDescription = $list->getDescription())): ?>
    <p><?=$this->escapeHtml($listDescription)?></p>
  <?php endif; ?>
  <?php if (!empty($listTags)): ?>
    <div><strong><?=$this->transEsc('Tags')?>:</strong> <span class="list-tags"><?=implode(', ', array_map([$this, 'escapeHtml'], $listTags))?></span></div>
  <?php endif; ?>
  <?php if ($recordTotal > 0): ?>
    <?php $multiPageSelection = ($this->config()->get('config')['Social']['multi_page_favorites_selection'] ?? true) ? ' multi-page-selection' : ''; ?>
    <form class="form-inline<?= $multiPageSelection ?>" id="form-favorites<?=($listId = $list?->getId()) ? '-' . $listId : ''?>" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
      <?=$this->context($this)->renderInContext('myresearch/bulk-action-buttons.phtml', ['idPrefix' => '', 'list' => $list ?? null, 'account' => $this->account])?>
      <input class="hidden all-ids-global" type="text" name="all_ids_global" value="<?= $this->escapeHtmlAttr(json_encode($this->results->getAllIds())) ?>">
      <ul class="record-list">
        <?php foreach ($this->results->getResults() as $i => $current): ?>
          <?=$this->record($current)->getListEntry($list, $user)?>
        <?php endforeach; ?>
      </ul>
    </form>
    <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results])?>
  <?php else: ?>
    <p><?=$this->transEsc('You do not have any saved resources')?></p>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render(isset($list) ? 'list' . $list->getId() : 'favorites')?>
  <?php foreach ($this->results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
</div>
