<!-- START of: finna - myresearch/account.phtml -->
<?php
    $this->layout()->finnaMainHeader = $this->component('page-title', ['title' => $this->translate($this->message), 'class' => 'finna-main-header']);

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
      ->add($this->translate('Create New Account'), active: true);
?>
<?=$this->component('page-title', ['title' => $this->translate('Create New Account')]);?>
<?=$this->flashmessages()?>

<form method="post" name="accountForm" id="accountForm" class="form-user-create" data-toggle="validator">
  <?=$this->auth()->getCreateFields()?>
  <div class="form-group">
    <?=$this->captcha()->html($this->useCaptcha) ?>
  </div>
  <div class="form-group">
    <a class="back-to-login btn btn-link" href="<?=$this->url('myresearch-userlogin') ?>"><?=$this->icon('back-to-login') ?> <?=$this->transEsc('Back')?></a>
    <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Submit')?>">
  </div>
</form>

<?php
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$js = <<<JS
      if ($.isReady) {
        $('#accountForm').validator();
      } else {
        $(document).ready(function(){
          $('#accountForm').validator();
        });
      }
    JS;

echo $this->assetManager()->outputInlineScriptString($js);
?>
<!-- END of: finna - myresearch/account.phtml -->
