<!-- START of: finna - myresearch/borrowing-block.phtml -->
<?php if (!empty($blocks)): ?>
  <div class="borrowing-block-container alert alert-info">
    <?php foreach ($blocks as $block): ?>
      <span class="borrowing-block"><?=!$this->translationEmpty($block . '_html') ? $this->translate($block . '_html') : str_replace("\n", '<br>', $this->transEsc($block))?></span>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<!-- END of: finna - myresearch/borrowing-block.phtml -->
