<?php
    $manager = $this->auth()->getManager();
    $options = $manager->getSelectableAuthOptions();
    if (!in_array('ILS', $options) && !in_array('MultiILS', $options)) {
      return;
    }

    // Check if this page has been added as a part of another page
    $isPartial = $this->layout()->templateName === 'profile';

    // Set up page title:
    if (!$isPartial) {
        $this->headTitle($this->translate('Login'));
    }

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Login') . '</li>';

    // Convenience variable:
    $offlineMode = $this->ils()->getOfflineMode();
?>

<?php if (!$isPartial): ?>
  <?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => '']); ?>

  <!-- Leftside navigationbar -->
  <div class="<?=$this->layoutClass('mainbody-myresearch')?>">
<?php endif; ?>

<?php if ($offlineMode == "ils-offline"): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_login_message'])?>
<?php elseif ($this->targets === null || !empty($this->targets)): ?>
  <?php if (($user = $this->auth()->isLoggedIn()) && count($user->getLibraryCards()) >= 1): ?>
    <h3><?=$this->transEsc('catalog_login_change_card_heading') ?></h3>
    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'displaySelected' => false, 'label' => 'catalog_login_change_card_label'])?>
  <?php endif; ?>
  <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
  <?=$this->flashmessages()?>
  <p><?=$this->transEsc('cat_establish_account')?></p>
  <form method="post" autocomplete="off">
    <?php if ($this->targets !== null): ?>
    <div class="form-group">
      <label class="control-label" for="profile_cat_target"><?=$this->transEsc('login_target')?>:</label>
      <select id="profile_cat_target" name="target" class="form-control">
      <?php foreach ($this->targets as $target): ?>
        <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target === $this->defaultTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
      <?php endforeach; ?>
      </select>
    </div>
    <?php endif; ?>
    <div class="form-group">
      <?php if (null === $this->loginMethod || 'password' === $this->loginMethod): ?>
        <label class="control-label password-login" for="profile_cat_username"><?=$this->transEsc('Library Catalog Username')?>:</label>
      <?php endif; ?>
      <?php if (null === $this->loginMethod || 'email' === $this->loginMethod): ?>
        <label class="control-label email-login<?php if (null === $this->loginMethod): ?> hidden<?php endif; ?>" for="profile_cat_username"><?=$this->transEsc('Email')?>:</label>
      <?php endif; ?>
      <input id="profile_cat_username" type="text" name="cat_username" value="" class="form-control"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="profile_cat_secondary_username"></label>
      <input id="profile_cat_secondary_username" type="text" name="cat_secondary_username" value="" class="form-control"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="profile_cat_password"><?=$this->transEsc('Library Catalog Password')?>:</label>
      <input id="profile_cat_password" type="password" name="cat_password" value="" class="form-control"/>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEsc('Save')?>">
    </div>
  </form>
  <?php if (empty($this->card->id)): ?>
    <?php
      $language = $this->layout()->userLang;
      if (!in_array($language, ['fi', 'sv', 'en-gb'])) {
        $language = 'en-gb';
      }
    ?>
    <?=$this->partial("librarycards/library_card_terms_$language.phtml"); ?>
  <?php endif; ?>
<?php endif; ?>
<?php if (!$isPartial): ?>
  </div>
<?php endif; ?>

<?php
  $labels = [];
  $originalMethod = $manager->getAuthMethod();
  if (in_array('MultiILS', $options)) {
    $manager->setAuthMethod('MultiILS');
  } else {
    $manager->setAuthMethod('ILS');
  }
  $labels = [];
  if (null !== $this->targets) {
    foreach ($this->targets as $target) {
      $label = $manager->getSecondaryLoginFieldLabel($target);
      $labels[$target] = $label ? $this->translate($label) : '';
    }
  }

  $manager->setAuthMethod($originalMethod);

  $labels = json_encode($labels);
  $methods = json_encode($this->loginMethods);

  $script = <<<EOT
  setupMultiILSLoginFields($methods, 'profile_cat_');
  finna.layout.initSecondaryLoginField($labels, 'profile_cat_');
EOT;

  // Inline the script for lightbox compatibility
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
