<!-- START of: finna - myresearch/change-address-settings.phtml -->
<?php
    $user = $this->auth()->isLoggedIn();
    $updatePhone = $this->ils()->checkFunction('updatePhone', compact($user));
    $updateEmail = $this->ils()->checkFunction('updateEmail', compact($user));
    $updateAddress = $this->ils()->checkFunction('updateAddress', compact($user));
    $needsApproval = $updateAddress['needsApproval'] ?? true;
    // Set up page title:
    $title = $this->translate(($updatePhone || $updateEmail) ? 'request_address_change' : 'request_contact_information_change');
    $this->headTitle($title);

    // Set up myresearch menu
    $this->layout()->finnaMainTabs = $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile']);
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';
?>
<h2><?=$this->escapeHtml($title) ?></h2>
<?=$this->flashmessages()?>
<?php if (!isset($this->requestCompleted) || !$this->requestCompleted): ?>
  <form  name="requestAddressChange" method="post" action="<?=$this->url('myresearch-changeprofileaddress')?>" class="address-form profile-form">
    <?php foreach ($this->fields as $field => $data): ?>
      <div class="form-group">
        <label class="control-label" for="<?=$this->escapeHtmlAttr($field)?>"><?=$this->transEsc($data['label']) ?>:</label>
        <?php
          $value = isset($this->profile[$field]) ? $this->profile[$field] : '';
          if (!$value) {
            $value = isset($this->profile['full_data'][$field]) ? $this->profile['full_data'][$field] : '';
          }
        ?>
        <input id="<?=$this->escapeHtmlAttr($field)?>" name="<?=$this->escapeHtmlAttr($field)?>" type="text" value="<?=$this->escapeHtmlAttr($value) ?>" class="form-control"/>
      </div>
    <?php endforeach; ?>
    <div class="form-group">
      <input name="address_change_request" class="btn btn-primary" type="submit" value="<?=$this->transEsc('Send') ?>" />
    </div>
  </form>
<?php endif; ?>
<?php if ($needsApproval): ?>
  <div class="address-change-description">
    <?php if ('driver' === $this->config['method']): ?>
      <?=$this->transEsc('request_change_description_html') ?>
    <?php else: ?>
      <?=$this->transEsc('request_change_email_description_html') ?>
    <?php endif; ?>
  </div>
<?php endif; ?>
<!-- END of: finna - myresearch/change-address-settings.phtml -->
