<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate($pageTitle), active: true);
?>

<?=$this->flashmessages()?>

<?=$this->component('page-title', ['title' => $this->translate(empty($this->list->getId()) ? 'Create a List' : 'edit_list')]);?>

<form class="form-edit-list" method="post" name="<?=empty($this->list->getId()) ? 'newList' : 'editListForm'?>" action="<?=$this->url('editList'); ?>">
  <input type="hidden" name="id" value="<?=empty($this->list->getId()) ? 'NEW' : $this->escapeHtmlAttr($this->list->getId()) ?>">
  <?=$this->context($this)->renderInContext('cart/form-record-hidden-inputs.phtml', []); ?>
  <input type="hidden" name="followup" value="<?=$this->escapeHtmlAttr($this->followup) ?>">
  <div class="form-group">
    <label class="form-label" for="list_title"><?=$this->transEsc('List'); ?>:</label>
    <input id="list_title" class="form-control" type="text" name="title" value="<?=$this->escapeHtmlAttr($this->list->getTitle() ?? '')?>">
  </div>
  <div class="form-group">
    <label class="form-label" for="list_desc"><?=$this->transEsc('Description') ?></label>
    <textarea id="list_desc" class="form-control" name="desc" rows="3"><?=$this->escapeHtml($this->list->getDescription() ?? '')?></textarea>
  </div>
  <?php if ($this->userlist()->getMode() === 'public_only'): ?>
    <input type="hidden" name="public" value="1">
  <?php elseif ($this->userlist()->getMode() === 'private_only'): ?>
    <input type="hidden" name="public" value="0">
  <?php else: ?>
    <div class="form-group">
      <label class="form-label"><?=$this->transEsc('Access') ?></label>
      <div class="radio inline">
        <label>
          <input id="list_public_1" type="radio" name="public" value="1"<?php if ($this->list->isPublic()): ?> checked="checked"<?php endif; ?>> <?=$this->transEsc('Public') ?>
        </label>
      </div>
      <div class="radio inline">
        <label>
          <input id="list_public_0" type="radio" name="public" value="0"<?php if (!$this->list->isPublic()): ?> checked="checked"<?php endif; ?>> <?=$this->transEsc('Private') ?>
        </label>
      </div>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Save') ?>">
  </div>
</form>
