<!-- START of: finna - myresearch/fines.phtml -->
<?php
    $this->layout()->finnaUserAccountHeading = 'useraccount-content-heading';

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
      ->add($this->translate('Fines'), active: true);

    $user = $this->auth()->getUserObject();

    $currencyTemplate = $this->safeMoneyFormat(11.22);

    // Collect the data to build the table; we process this in advance so we
    // can omit empty columns and simplify customization by separating data
    // processing from rendering.
    $tableData = [];
    $totalDue = 0;
    foreach ($this->fines ?? [] as $record) {
      if (empty($record['title'])) {
          $title = '';
      } elseif (!is_object($record['driver'] ?? null)) {
          $title = $this->escapeHtml(trim($record['title'], '/:'));
      } else {
          $title = '<a href="'
              . $this->escapeHtmlAttr($this->recordLinker()->getUrl($record['driver']))
              . '">' . $this->escapeHtml(trim($record['title'], '/:')) . '</a>';
      }

      $fine = $record['fine'] ?? '';
      // Only check translations if the type doesn't contain the prefix already:
      if (!str_starts_with($fine, 'fine_status_')) {
        if (!$this->translationEmpty("fine_status_$fine")) {
          $fine = "fine_status_$fine";
        } elseif (!$this->translationEmpty("status_$fine")) {
          // Fallback to item status translations for backwards-compatibility
          $fine = "status_$fine";
        }
      }
      $balance = isset($record['balance']) ? $this->safeMoneyFormat($record['balance'] / 100.00) : '';
      if ($this->onlinePayment && !($record['payableOnline'] ?? false)) {
        // Note: `online_payment_nonpayable_fees` should be translated with transEsc, but is left unescaped
        // for historical reasons:
        $balance = '<span class="online-payment-nonpayable">' . $balance
          . '<br><span class="online-payment-remark"> ' . $this->translate('online_payment_nonpayable_fees') . '</span></span>';
      }

      // Build 'select' last, it needs $fine:
      $select = '';
      if ($this->onlinePaymentEnabled && $this->selectFees) {
        if ($record['payableOnline'] ?? false) {
          ob_start();
          ?>
            <div class="checkbox-container">
                <label>
                  <span class="visually-hidden">
                    <?=$this->transEsc('Select')?>
                    <?=$this->escapeHtml(trim($record['title'] ?? '', '/: '))?>
                    <?=isset($fine) ? ('(' . $this->transEsc($fine) . ')') : ''?>
                    <?=$this->safeMoneyFormat($record['balance'] / 100.00)?>
                  </span>
                  <input class="checkbox-select-item" type="checkbox" name="selectedIDS[]" value="<?=$this->escapeHtmlAttr($record['fineId'])?>" data-amount="<?=$this->escapeHtmlAttr($record['balance'])?>">
                </label>
            </div>
          <?php
          $select .= ob_get_clean();
        }
      }

      $tableData['Select'][] = $select;
      $tableData['Title'][] = $title;
      $tableData['fine_checkout_date'][] = $this->escapeHtml($record['checkout'] ?? '');
      $tableData['Due Date'][] = $this->escapeHtml($record['duedate'] ?? '');
      $tableData['fine_type'][] = $this->transEsc($fine);
      $tableData['fine_description'][] = $this->transEsc($record['description'] ?? '');
      $tableData['fine_creation_date'][] = $this->escapeHtml($record['createdate'] ?? '');
      $tableData['Fee'][] = isset($record['amount'])
          ? $this->safeMoneyFormat($record['amount'] / 100.00) : '';
      $tableData['Balance'][] = $balance;

      $totalDue += $record['balance'] ?? 0;
    }

    // Now empty out any unused columns:
    foreach ($tableData as $column => $values) {
        $empty = true;
        foreach ($values as $value) {
            if ('' !== (string)$value) {
                $empty = false;
                break;
            }
        }
        if ($empty) {
            unset($tableData[$column]);
        }
    }

    // Create the final list of columns and count of rows:
    $columns = array_keys($tableData);
    $rowCount = count($this->fines ?? []);
?>
<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'fines']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <?php if ($user): ?>
      <?php if (!empty($this->registerPaymentLocalIdentifier)): ?>
        <div class="alert alert-info">
          <span class="register-payment-spinner"><?=$this->icon('spinner') ?> <?=$this->translate('Registering Payment');?></span>
          <div id="online-payment-status" class="info hide"></div>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (!$this->translationEmpty('fines_instructions_html')): ?><p class="no-content-message"><?=$this->translate('fines_instructions_html')?></p><?php endif; ?>
    <div class="fines-info-area">
      <div class="useraccount-row">
        <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
      </div>
      <div id="useraccount-content-heading" class="useraccount-header">
        <?=$this->component('page-title', ['title' => $this->translate('Your Fines') . " ($rowCount)", 'headTitle' => $this->translate('My Fines')]);?>
      </div>
    </div>
    <?=$this->flashmessages()?>
    <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $this->blocks]); ?>
    <div class="fines-info-area" tabindex="0">
      <?php if (!empty($this->lastTransaction)): ?>
        <div class="last-transaction-information">
          <div>
            <?=$this->transEsc('Payment::Last Paid')?>:
            <span class="amount"><?=$this->safeMoneyFormat($this->lastTransaction->getAmount() / 100.00)?></span>
            <?=$this->lastTransaction->getPaidDate()->format($this->config()->dateTimeFormat())?>
          </div>
          <div class="text-right">
            <a href="?transactionReport=true" class="btn btn-sm btn-primary" target="_blank">
              <?=$this->transEsc('Payment::download_transaction_breakdown_pdf')?>
              <span class="visually-hidden"><?=$this->transEscAttr('Open in a new window')?></span>
            </a>
          </div>
        </div>
      <?php endif; ?>
      <div id="online_payment_total_due" data-raw="<?=$this->escapeHtmlAttr($totalDue)?>">
        <p>
          <?=$this->transEsc('Total Balance Due')?> (<?=count($this->fines ?? []);?>):
          <span class="amount"><?=$this->safeMoneyFormat($totalDue / 100.00) ?></span>
        </p>
      </div>
      <?php if ($this->onlinePayment && $this->onlinePaymentEnabled): ?>
        <div class="online-payment-info">
          <div id="online_payment_payable">
            <p>
              <?=$this->transEsc('online_payment_payable_online'); ?> (<?=$payableOnlineCnt ?>):
              <span class="amount"><?=$this->safeMoneyFormat($payableOnline / 100.00);?></span>
            </p>
          </div>
          <div id="online_payment_minimum_payment" data-raw="<?=$this->escapeHtmlAttr($minimumFee)?>" class="alert alert-warning hidden">
            <?=$this->transEsc('online_payment_minimum_fee'); ?>:
            <span class="amount"><?=$this->safeMoneyFormat($minimumFee / 100.00)?></span>
          </div>
        </div>
        <?php if (!empty($transactionFee)): ?>
          <div id="online_payment_transaction_fee" data-raw="<?=$this->escapeHtmlAttr($transactionFee)?>">
            <p>
              <?=$this->transEsc('online_payment_transaction_fee'); ?>:
              <span class="amount"><?=$this->safeMoneyFormat($transactionFee / 100.00);?></span>
            </p>
          </div>
        <?php endif; ?>
        <?php if ($this->selectFees): ?>
          <div id="online_payment_remaining_after">
            <p>
              <?=$this->transEsc('online_payment_remaining_after'); ?>:
              <span class="amount" data-template="<?=$this->escapeHtmlAttr($currencyTemplate)?>">
                <?=$this->safeMoneyFormat(($this->selectFees ? $totalDue : $totalDue - $payableOnline) / 100)?>
              </span>
            </p>
          </div>
        <?php endif; ?>
        <?php if ($this->startedTransaction): ?>
          <div class="alert alert-danger">
            <?=$this->transEsc('online_payment_in_progress_warning', ['%%startDateTime%%' => $this->startedTransaction->getCreated()->format($this->config()->dateTimeFormat())]); ?>
          </div>
        <?php endif; ?>
      <?php endif; ?>
    </div>
    <?php if ($this->onlinePayment): ?>
      <?php if ($this->onlinePaymentEnabled): ?>
        <form id="online_payment_form" class="online-payment-form" action="<?=$this->url('myresearch-fines')?>" method="post" data-lightbox data-clear-account-cache="fines" data-disable-on-submit>
          <input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
          <?php if (!$this->selectFees): ?>
            <div class="fines-info-area payment-row">
              <input type="submit" name="pay" class="btn btn-primary btn-lg" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $this->safeMoneyFormat(($payableOnline + ($transactionFee ?? 0)) / 100.00)])?>">
            </div>
          <?php endif; ?>
      <?php elseif (!empty($this->nonPayableReason) && !empty($this->fines)): ?>
        <div class="fines-info-area">
          <p><?=$this->transEsc($this->nonPayableReason); ?><?=$this->nonPayableReason == 'online_payment_minimum_fee' ? (': <span class="amount">' . $this->safeMoneyFormat($this->minimumFee / 100.00)) . '</span>' : '';?></p>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <?php if (isset($this->noSupport)): ?>
      <?php if (count($this->libraryCards()->getCardsForUser($user)) > 0): ?>
        <div class="support-notice">
          <p><?=$this->transEsc('no_ils_support_description') ?></p>
        </div>
      <?php endif; ?>
    <?php else: ?>
      <?php if ($template = $this->content()->findTemplateForLng('content/Additions/fines-pre-list')): ?>
        <div class="fines-pre-list"><?=$this->render($template)?></div>
      <?php endif; ?>
      <?php if (empty($this->fines)): ?>
        <h3><?=$this->transEsc('You do not have any fines')?></h3>
      <?php else: ?>
        <?php if ($this->onlinePaymentEnabled && $this->selectFees): ?>
          <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
          <div class="myresearch-table online-payment" aria-label="<?=$this->transEscAttr('Actions');?>">
            <div class="toolbar">
              <div class="checkbox-col">
                <div class="checkbox-container mylist-select-all">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" name="selectAll" class="checkbox-select-all">
                      <?=$this->transEsc('Select All')?>
                      <span class="selected"></span>
                    </label>
                  </div>
                </div>
              </div>
              <div class="payment-row">
                <span id="online_payment_selected_sr" class="visually-hidden" data-template="<?=$this->transEscAttr('online_payment_selected_to_pay') . ' ' . $this->transEscAttr($currencyTemplate)?>">
                  <?=$this->transEscAttr('online_payment_selected_to_pay') . ' ' . $this->safeMoneyFormat(0)?>
                </span>
                <input type="submit" id="pay_selected" name="pay" class="btn btn-primary" value="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => ''])?>" data-template="<?=$this->transEscAttr('online_payment_go_to_pay', ['%%amount%%' => $currencyTemplate])?>" disabled>
              </div>
            </div>
          </div>
        <?php endif; ?>
        <table class="table finna-table-striped useraccount-table<?=$this->onlinePayment ? ' online-payment' : ''?> table-responsive fines-table" tabindex="0">
          <caption class="visually-hidden"><?=$this->transEsc('Your Fines')?></caption>
          <thead>
            <tr class="headers">
              <?php foreach ($columns as $header): ?>
                <?php if ('Select' === $header): ?>
                  <th scope="col" class="user-account-table-select"></th>
                <?php elseif ('Balance' === $header || 'Fee' === $header): ?>
                  <th scope="col" class="balance"><?=$this->transEsc($header)?></th>
                <?php elseif ('Title' === $header): ?>
                  <th scope="col" class="user-account-table-title"><?=$this->transEsc($header)?></th>
                <?php else: ?>
                  <th scope="col"><?=$this->transEsc($header)?></th>
                <?php endif; ?>
              <?php endforeach; ?>
            </tr>
          </thead>
          <tbody>
            <?php for ($row = 0; $row < $rowCount; $row++): ?>
              <tr>
                <?php foreach ($columns as $column): ?>
                  <?php if ('Title' == $column): ?>
                    <th data-label="<?=$this->transEscAttr($column)?>" scope="row">
                      <?php if ('' === $tableData[$column][$row]): ?>
                        <span class="text-muted"><?=$this->transEsc('Title not available')?></span>
                      <?php else: ?>
                        <?=$tableData[$column][$row]?>
                      <?php endif; ?>
                    </th>
                  <?php else: ?>
                    <?php
                      $attrs = [
                          'data-label' => $this->translate($column),
                      ];
                      if ('Select' === $column) {
                        $attrs['class'] = 'user-account-table-select';
                        if ('' === $tableData[$column][$row]) {
                          unset($attrs['data-label']);
                        }
                      } elseif ('Balance' === $column || 'Fee' === $column) {
                        $attrs['class'] = 'balance';
                      }
                    ?>
                    <td<?=$this->htmlAttributes($attrs)?>><?=$tableData[$column][$row]?></td>
                  <?php endif; ?>
                <?php endforeach; ?>
              </tr>
            <?php endfor; ?>
          </tbody>
        </table>
        <?php if ($this->onlinePaymentEnabled): ?>
          </form>
        <?php endif; ?>
        <div>
          <?php if ($this->onlinePayment): ?>
            <?php if ($template = $this->content()->findTemplateForLng('content/Additions/online-payment')): ?>
              <div class="online-payment-note"><?=$this->render($template)?></div>
            <?php endif; ?>
          <?php endif; ?>
          <?php if ($template = $this->content()->findTemplateForLng('content/Additions/fines-post-list')): ?>
            <div class="fines-post-list"><?=$this->render($template)?></div>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
<?php
  if ($this->registerPaymentLocalIdentifier) {
    $identifierJson = json_encode($this->registerPaymentLocalIdentifier);
    echo $this->assetManager()->outputInlineScriptString("VuFind.fines.registerPayment($identifierJson);");
  }
?>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'fines', 'accountStatus' => $this->accountStatus]); ?>
<!-- END of: finna - myresearch/fines.phtml -->
