<!-- START of: finna - myresearch/illrequests.phtml -->
<?php
    $this->layout()->finnaUserAccountHeading = 'useraccount-content-heading';

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
      ->add($this->translate('Interlibrary Loan Requests'), active: true);

    $user = $this->auth()->getUserObject();
    $recordCount = count($this->recordList ?? []);
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'ILLRequests']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content myresearch-grid-list">
    <?php if (!$this->translationEmpty('ill_requests_instructions_html')): ?><p class="no-content-message"><?=$this->transEsc('ill_requests_instructions_html')?></p><?php endif; ?>
    <?=$this->flashmessages()?>
    <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $this->blocks]); ?>
    <div class="useraccount-row">
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
    </div>
    <div id="useraccount-content-heading" class="useraccount-header">
      <?=$this->component('page-title', ['title' => $this->translate('Interlibrary Loan Requests') . " ($recordCount)", 'headTitle' => $this->translate('Interlibrary Loan Requests')])?>
    </div>
    <?php if (isset($this->noSupport)): ?>
      <?php if (count($this->libraryCards()->getCardsForUser($user)) > 1): ?>
        <div class="support-notice">
          <p><?=$this->transEsc('no_ils_support_description') ?></p>
        </div>
      <?php endif; ?>
    <?php else: ?>
      <?php if ($template = $this->content()->findTemplateForLng('content/Additions/illrequests-pre-list')): ?>
        <div class="illrequests-pre-list"><?=$this->render($template)?></div>
      <?php endif; ?>
      <?php if (!empty($this->recordList)): ?>
        <?php if ($this->cancelForm): ?>
        <div class="myaccount-sticky-header"></div>
        <div class="toolbar-sticky-container">
        <form name="updateForm" class="inline" method="post" id="cancelILLRequest" data-clear-account-cache="illRequests">
          <div class="toolbar-sticky">
            <div class="myresearch-table ill-requests-table">
              <div class="toolbar">
                <div class="checkbox-col">
                  <div class="checkbox-container mylist-select-all">
                    <div class="checkbox">
                      <label>
                        <input type="checkbox" name="selectAll" class="checkbox-select-all" aria-label="<?=$this->transEscAttr('Select All');?>">
                        <?=$this->transEsc('Select All')?>
                        <span class="selected"></span>
                      </label>
                    </div>
                  </div>
                </div>
                <div class="list-functions">
                  <div class="toolbar-button-col">
                    <div>
                      <input type="hidden" id="submitType" name="cancelSelected" value="1">
                      <input type="hidden" id="cancelConfirm" name="confirm" value="0">
                    </div>
                    <div class="btn-group">
                      <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEscAttr('ill_request_cancel_selected') ?>" class="btn btn-primary btn-finna-toolbar dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                      <ul class="dropdown-menu useraccount-confirm">
                        <li><span class="dropdown-header"><?=$this->transEsc('confirm_ill_request_cancel_selected_text') ?></span></li>
                        <li>
                          <a class="dropdown-item" href="#" id="confirm_cancel_selected_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a>
                          <a class="dropdown-item" href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a>
                        </li>
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php else: ?>
          <div class="toolbar no-list-functions">
            <?=$this->transEsc('cannot cancel any interlibrary loan requests')?>
          </div>
        <?php endif; ?>
        <table class="myresearch-table" aria-label="<?=$this->transEscAttr('Interlibrary Loan Requests');?>" tabindex="0">
          <tr class="visually-hidden myresearch-row" aria-hidden="true">
            <th id="label-select-column"><?=$this->transEsc('Select');?></th>
            <th class="hidden-xs"></th>
            <th id="label-title-column"><?=$this->transEsc('Request Details');?></th>
            <th id="label-core-metadata" class="text-right"></th>
          </tr>
          <?php $iteration = 0; ?>
          <?php foreach ($this->recordList as $resource): ?>
            <?php $iteration++; ?>
            <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
            <tr id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result myresearch-row ill-details-row">
              <td class="checkbox-col">
              <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
                <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
                <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>">
                <div class="checkbox-container">
                  <div class="checkbox">
                    <label>
                      <span class="visually-hidden"><?=$this->transEsc('Select');?></span>
                      <input type="checkbox" name="cancelSelectedIDS[]" class="checkbox-select-item" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>">
                    </label>
                  </div>
                </div>
              <?php endif; ?>
              </td>
              <td class="text-left hidden-xs" aria-hidden="true">
                <div class="cover-image">
                  <?php if ($summThumb = $this->record($resource)->getThumbnail()): ?>
                    <img src="<?=$this->escapeHtmlAttr($summThumb)?>" class="recordcover" alt="<?=$this->transEscAttr('Cover Image')?>">
                  <?php else: ?>
                    <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEscAttr('No Cover Image')?>">
                  <?php endif; ?>
                </div>
              </td>
              <td headers="label-title-column" aria-labelledby="label-title-column">
                <?=$this->record($resource)->renderTemplate('account-entry.phtml')?>
              </td>
              <td class="text-right" headers="label-core-metadata" aria-labelledby="label-core-metadata">
                <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
                  value to display... */ ?>
                <?php $pickupDisplay = ''; ?>
                <?php $pickupTranslate = false; ?>
                <?php if (isset($ilsDetails['location'])): ?>
                  <?php if ($this->pickup): ?>
                    <?php foreach ($this->pickup as $library): ?>
                      <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                        <?php $pickupDisplay = $library['locationDisplay']; ?>
                        <?php $pickupTranslate = true; ?>
                      <?php endif; ?>
                    <?php endforeach; ?>
                  <?php endif; ?>
                  <?php if (empty($pickupDisplay)): ?>
                    <?php $pickupDisplay = $ilsDetails['location']; ?>
                  <?php endif; ?>
                <?php endif; ?>
                <?php if (!empty($pickupDisplay)): ?>
                  <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
                  <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
                  <br>
                <?php endif; ?>

                <?php if (!empty($ilsDetails['create'])): ?>
                  <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
                  <?php if (!empty($ilsDetails['expire'])): ?>|<?php endif; ?>
                <?php endif; ?>
                <?php if (!empty($ilsDetails['expire'])): ?>
                  <strong><?=$this->transEsc('ill_request_expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
                <?php endif; ?>
                <br>

                <?php if (isset($this->cancelResults['items'])): ?>
                  <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                    <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                      <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?>
                        <?php if ($cancelResult['sysMessage']) {
                          echo ' : ' . $this->transEsc($cancelResult['sysMessage']);
                        } ?>
                      </div>
                    <?php endif; ?>
                  <?php endforeach; ?>
                <?php endif; ?>

                <?php if (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
                  <div class="text-success"><?=$this->transEsc('request_in_transit') . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></div>
                <?php endif; ?>
                <?php if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
                  <div class="alert alert-success"><?=$this->transEsc('ill_request_processed') . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></div>
                <?php endif; ?>
                <?php if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
                  <div class="alert alert-success"><?=$this->transEsc('ill_request_available') ?></div>
                <?php endif; ?>
                <?php if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
                  <div class="text-success"><?=$this->transEsc('ill_request_canceled') . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></div>
                <?php endif; ?>
                <?php if (isset($ilsDetails['cancel_link'])): ?>
                  <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc('ill_request_cancel') ?></a></p>
                <?php endif; ?>
              </td>
            </tr>
          <?php endforeach; ?>
        </table>
        <h3 class="visually-hidden"><?=$this->transEsc('End of List')?></h3>
        <?php if ($this->cancelForm): ?>
              <div class="dropdown button-bottom">
                <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEscAttr('ill_request_cancel_all') ?>" class="btn btn-danger dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
                <ul class="dropdown-menu useraccount-confirm">
                  <li><span class="dropdown-header"><?=$this->transEsc('confirm_ill_request_cancel_all_text') ?></span></li>
                  <li>
                    <a class="dropdown-item" href="#" id="confirm_cancel_all_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a>
                    <a class="dropdown-item" href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a>
                  </li>
                </ul>
              </div>
            </form>
          </div>
        <?php endif; ?>
        <?php if ($template = $this->content()->findTemplateForLng('content/Additions/illrequests-post-list')): ?>
          <div class="illrequests-post-list"><?=$this->render($template)?></div>
        <?php endif; ?>
      <?php else: ?>
        <div class="useraccount-header">
          <h3><?=$this->transEsc('You do not have any interlibrary loan requests placed') ?>.</h3>
        </div>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'illRequests', 'accountStatus' => $this->accountStatus]); ?>
<!-- END of: finna - myresearch/illrequests.phtml -->
