<!-- START of: finna - myresearch/import.phtml -->
<h2><?=$this->transEsc('import_favorites') ?></h2>
<div id="favorites-import-dialog">
    <form id="favorites-import-form" method="post" enctype="multipart/form-data"  data-lightbox-ignore>
        <div class="form-group">
            <input id="filename" type="text" class="form-control" readonly>
            <label class="btn btn-primary btn-file">
                <?=$this->transEsc('import_favorites_select_file') ?>
                <input type="file" style="display: none;" name="favorites-file">
            </label>
        </div>
        <div class="form-group">
            <button class="btn btn-primary btn-upload" type="button"><?=$this->transEsc('import_favorites_upload') ?></button>
        </div>
    </form>
</div>
<?php
    $script = <<<JS
        finna.scriptLoader.load(
            {'finna-favorites': 'finna-favorites.js'},
            () => {
                document.querySelector('#favorites-import-dialog .btn-upload').addEventListener('click', finna.favorites.upload);
            }
        )
        JS;
    echo $this->assetManager()->outputInlineScriptString($script);
?>
<!-- END of: finna - myresearch/import.phtml -->
