<!-- START of: finna - Auth/myresearch/login.phtml -->
<?php
  // Set up page title:
  $this->headTitle($this->translate('Login'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Login') . '</li>';

  // Convenience variables:
  $account = $this->auth()->getManager();
  $hideLogin = !(is_object($account) && $account->loginEnabled());
  $offlineMode = $this->ils()->getOfflineMode();
?>

<?php if ($offlineMode == "ils-offline"): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_login_message'])?>
<?php endif; ?>

<h2 class="lightbox-header"><?=$this->transEsc('Login')?></h2>
<?=$this->flashmessages()?>
<?php if ($template = $this->content()->findTemplateForLng("content/Additions/login-pre")): ?>
  <div>
    <?=$this->render($template)?>
  </div>
<?php endif; ?>
<?php if ($hideLogin): ?>
  <div class="alert alert-danger"><?=$this->transEsc('login_disabled')?></div>
<?php else: ?>
  <?php if ($this->fromTermsPage): ?>
    <?php // Force lightbox login to display ?>
    <div class="flash-message alert-danger hidden"></div>
  <?php endif; ?>
  <?=$this->auth()->getLogin()?>
<?php endif; ?>
<?php if ($template = $this->content()->findTemplateForLng("content/Additions/login-post")): ?>
  <div>
    <?=$this->render($template)?>
  </div>
<?php endif; ?>
<!-- END of: finna - Auth/myresearch/login.phtml -->
