<!-- START of: finna - Auth/myresearch/login.phtml -->
<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate('Login'), active: true);

  // Convenience variables:
  $account = $this->auth()->getManager();
  $hideLogin = !(is_object($account) && $account->loginEnabled());
  $offlineMode = $this->ils()->getOfflineMode();
?>

<?php if ($offlineMode == 'ils-offline'): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_login_message'])?>
<?php endif; ?>

<?=$this->component('page-title', ['title' => $this->translate('Login')]);?>
<?=$this->flashmessages()?>
<?php if ($template = $this->content()->findTemplateForLng('content/Additions/login-pre')): ?>
  <div>
    <?=$this->render($template)?>
  </div>
<?php endif; ?>
<?php if ($hideLogin): ?>
  <div class="alert alert-danger"><?=$this->transEsc('login_disabled')?></div>
<?php else: ?>
  <?php if ($this->fromTermsPage): ?>
    <?php // Force lightbox login to display ?>
    <div class="flash-message alert alert-danger hidden"></div>
  <?php endif; ?>
  <?=$this->auth()->getLogin()?>
<?php endif; ?>
<?php if ($template = $this->content()->findTemplateForLng('content/Additions/login-post')): ?>
  <div>
    <?=$this->render($template)?>
  </div>
<?php endif; ?>
<!-- END of: finna - Auth/myresearch/login.phtml -->
