<!-- START of: finna - myresearch/menu.phtml -->
<?php
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $showLibraryTabs = $this->ils()->loginAvailable();
    $ilsOffline = 'ils-none' === $this->ils()->getOfflineMode();
    $listOpen = $this->active == 'favorites' || substr($this->active, 0, 4) == 'list';
    $activeToLower = strtolower($this->active ?? '');
    //Get the data for vertical menu to show lists on correct site
    if ($listOpen) {
      $list = $this->results->getListObject();
      $listParams = [
        'activeId' => $list['id'] ?? null,
        'lists' => $user ? $user->getLists() : null,
        'results' => $this->results,
        'user' => $user
      ];
    }

    $menuListItems = [];
    if ($showLibraryTabs && !$ilsOffline) {
      $menuListItems = [
        'checkedout' => [
          'url' => 'myresearch-checkedout',
          'translation' => 'Checked Out Items',
          'statusKey' => 'checkedout',
        ],
        'historicloans' => [
          'url' => 'myresearch-historicloans',
          'translation' => 'Loan History',
          'show' => $this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)
        ],
        'holds' => [
          'url' => 'myresearch-holds',
          'translation' => 'Holds and Recalls',
          'statusKey' => 'holds',
        ],
        'storageretrievalrequests' => [
          'url' => 'myresearch-storageretrievalrequests',
          'translation' => 'Storage Retrieval Requests',
          'show' => $this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams),
          'statusKey' => 'storageretrievalrequests',
        ],
        'illrequests' => [
          'url' => 'myresearch-illrequests',
          'translation' => 'Interlibrary Loan Requests',
          'show' => $this->ils()->checkFunction('ILLRequests', $capabilityParams),
          'statusKey' => 'illrequests',
        ],
        'fines' => [
          'url' => 'myresearch-fines',
          'translation' => 'Fines',
          'statusKey' => 'fines',
        ],
        'librarycards' => [
          'url' => 'librarycards-home',
          'translation' => 'Library Cards',
          'show' => $user && $user->libraryCardsEnabled()
        ]
      ];
    }

    $nonLibraryItems = [
      'profile' => [
        'url' => 'myresearch-profile',
        'translation' => 'Profile',
        'show' => !$ilsOffline && $this->ils()->checkCapability('getMyProfile')
      ],
      'history' => [
        'url' => 'search-history',
        'query' => '?require_login',
        'translation' => 'history_saved_searches'
      ],
      'favorites' => [
        'url' => 'myresearch-favorites',
        'translation' => 'Favorites',
        'show' => $this->userlist()->getMode() !== 'disabled'
      ],
      'logout' => [
        'url' => 'myresearch-logout',
        'translation' => 'Log Out',
        'iconClass' => 'pull-right fa fa-sign-out fa-lg',
        'desktopOnly' => true
      ]
    ];
    $menuListItems = array_merge($menuListItems, $nonLibraryItems);

    $desktopList = [
      'open-loans' => [
        'active' => in_array($activeToLower, ['checkedout', 'historicloans', 'holds', 'storageretrievalrequests', 'illrequests']),
        'url' => 'myresearch-checkedout',
        'translation' => 'checked_out_menu_heading',
        'dropdown' => true,
        'ulId' => 'myLoans',
        'show' => !$ilsOffline && $showLibraryTabs,
        'children' => [
          'checkedout',
          'historicloans',
          'holds',
          'storageretrievalrequests',
          'illrequests'
        ],
        'statusKey' => 'loans-menu',
      ],
      'fines',
      'librarycards',
      'profile',
      'history',
      'open-list' => [
        'active' => $listOpen,
        'url' => 'myresearch-favorites',
        'translation' => 'Favorites',
        'show' => $this->userlist()->getMode() !== 'disabled',
        'partial' => [
          'url' => 'myresearch/mylist-navi.phtml',
          'wrapperClass' => 'mylist-bar',
          'params' => $listParams ?? []
        ]
      ],
      'logout'
    ];

    $headerKey = substr($activeToLower, 0, 4) === 'list' ? 'favorites' : $activeToLower;
    $activeMobileTab = $menuListItems[$headerKey]['translation'] ?? 'Your Account';
?>

<div class="mobile-main-tabs visible-xs visible-sm">
  <div class="dropdown useraccount-nav-mobile" role="menu">
    <div class="dropdown-toggle" data-toggle="dropdown">
      <div class="tab-title">
        <?=$this->transEsc($activeMobileTab)?>
      </div>
      <div class="more"><?= $this->transEsc('Your Account') ?><b class="caret"></b></div>
    </div>
    <ul class="dropdown-menu">
      <?php foreach ($menuListItems as $id => $listItem) : ?>
        <?php if (isset($listItem['desktopOnly']) && $listItem['desktopOnly']) { continue; } ?>
        <?php if (!isset($listItem['show']) || $listItem['show'] !== false): ?>
          <li role="menuitem" class="<?=$id?><?= $activeToLower === $id ? ' active' : ''?>">
            <a href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" class="list-group-item" <?=$activeToLower === $id ? 'aria-current="page"' : ''?>>
            <?=$this->transEsc($listItem['translation'])?>
              <?php if (!empty($listItem['statusKey'])): ?>
                <span class="<?=$listItem['statusKey']?>-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
              <?php endif; ?>
            </a>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>
    </ul>
  </div>
</div>

<ul class="<?=$this->layoutClass('sidebar-myresearch')?> <?= $listOpen ? '' : 'move-list' ?> nav-tabs-personal list-group useraccount-nav nav-tabs" role="menu">
  <li class="menu-header hidden-xs hidden-sm">
    <h1>
      <?= $this->transEsc('Your Account') ?>
      <?php if (!$this->translationEmpty('tooltip_myaccount_html')): ?>
        <span class="tooltip-myaccount" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?= $this->transEsc("tooltip_myaccount_html") ?>"><i class="fa fa-info-big"></i></span>
      <?php endif; ?>
    </h1>
  </li>
  <?php foreach ($desktopList as $id => $value) : ?>
  <?php
    $isArray = is_array($value);
    $listItem = $isArray ? $value : $menuListItems[$value] ?? ['show' => false];
    if (isset($listItem['show']) && !$listItem['show']) {
      continue;
    }
    $name = $isArray ? $id : $value;
    $hasChildren = $listItem['children'] ?? false;
    $hasPartial = $listItem['partial'] ?? false;
    $showSpinner = $listItem['showSpinner'] ?? false;
  ?>
    <?php if ($hasChildren || $hasPartial): ?>
      <li role="menuitem" class="dropdown <?= $listItem['active'] ? ' active' : ''?>">
        <a href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" id="<?=$id?>" class="hidden-xs hidden-sm list-group-item <?= !$listItem['active'] ? 'collapsed' : '' ?>" >
          <?=$this->transEsc($listItem['translation'])?>
          <?php if ($showSpinner) : ?>
            <i class="hidden fa fa-spinner fa-spin"></i><span class="ajax-error hidden"><small> <?=$this->translate('An error has occurred'); ?></small></span>
          <?php endif; ?>
          <?php if (!empty($listItem['statusKey'])): ?>
            <span class="<?=$listItem['statusKey']?>-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
          <?php endif; ?>
          <span class="caret"></span>
        </a>
        <?php if ($hasPartial) : ?>
          <div class="<?= $value['partial']['wrapperClass'] ?? 'ajax-wrapper'?>">
            <?php if ($listItem['active']): ?>
              <?= $this->partial($value['partial']['url'], $value['partial']['params']); ?>
            <?php endif; ?>
          </div>
        <?php else: ?>
          <ul id="<?=$listItem['ulId']?>" role="presentation" class="dropdown-menu subtabs collapse <?= $listItem['active'] ? ' in' : ''?>">
            <?php foreach ($listItem['children'] as $childKey) : ?>
              <?php
                $childItem = $menuListItems[$childKey] ?? ['show' => false];
                if (isset($childItem['show']) && !$childItem['show']) { continue; }
              ?>
                <li role="menuitem" class="<?="menu-$name"?>  <?=$activeToLower === $childKey ? ' active' : ''?>">
                  <a href="<?=$this->escapeHtmlAttr($this->url($childItem['url']) . ($childItem['query'] ?? ''))?>" class="list-group-item" <?=$activeToLower === $childKey ? 'aria-current="page"' : ''?>>
                    <?=$this->transEsc($childItem['translation'])?>
                    <?php if (!empty($childItem['statusKey'])): ?>
                      <span class="<?=$childItem['statusKey']?>-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
                    <?php endif; ?>
                  </a>
                </li>
            <?php endforeach; ?>
          </ul>
        <?php endif; ?>
      </li>
    <?php else: ?>
      <li role="menuitem" class="hidden-xs hidden-sm <?="menu-$name"?> <?=$activeToLower === $name ? ' active' : ''?>">
        <a href="<?=$this->escapeHtmlAttr($this->url($listItem['url']) . ($listItem['query'] ?? ''))?>" class="list-group-item" <?=$activeToLower === $name ? 'aria-current="page"' : ''?>>
          <?=$this->transEsc($listItem['translation'])?>
          <?php if (isset($listItem['iconClass'])): ?>
            <i class="<?=$listItem['iconClass']?>" aria-hidden="true"></i>
          <?php endif; ?>
          <?php if (!empty($listItem['statusKey'])): ?>
            <span class="<?=$listItem['statusKey']?>-status status hidden"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
          <?php endif; ?>
        </a>
      </li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>

<script>
    finna.menu.init();
</script>

<!-- END of: finna - myresearch/menu.phtml -->
