<!-- START of: finna - myresearch/mylist-navi.phtml -->
<?php
  $numOfResources = $user->getNumOfResources();
  $currentLimit = 20; // default limit for favorites
  if (isset($this->results)) {
     $limitList = $this->results->getParams()->getLimitList();
     foreach ($limitList as $limitVal => $limitData) {
        if ($limitData['selected']) {
          $currentLimit = $limitVal;
          break;
        }
     }
  }
?>

  <h4><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc('Your Lists')?></h4>
  <ul class="list-group mylist-nav">
    <li>
      <a href="<?=$this->url('myresearch-favorites')?>?limit=<?=$currentLimit;?>" class="list-group-item<?=!$activeId ? ' active' : ''?>">
        <?=$this->transEsc('All Favourites')?>
        <span> (<?=$numOfResources; ?>)</span>
      </a>
    </li>
    <?php foreach ($lists as $list): ?>
    <?php $active = ($list->id === $activeId); ?>
    <li>
      <a href="<?= $active ? '#' : $this->url('userList', ['id' => $list['id']])?>?limit=<?=$currentLimit;?>" class="list-group-item<?=$list && $active ? ' active' : ''?>">
        <?php if ($list['public']): ?>
        <i class="fa fa-public public-favorite-list pull-left"></i>
        <?php endif; ?>
        <div class="favorite-list-name">
          <?=$this->escapeHtml($list['title'])?>
          <span> (<?=$list->cnt?>)</span>
        </div>
        <?php if ($active): ?>
        <span class="pull-right remove-favorite-list"><i class="fa fa-button fa-times remove"></i></span>
        <?php endif; ?>
      </a>
      <?php if ($active): ?>
      <?php $url = $this->serverUrl() . $this->url('home') . 'List/' . $list['id']; ?>
      <?= $this->partial('myresearch/list-visibility.phtml', ['listUrl' => $url, 'public' => $list['public']]); ?>
      <?php endif; ?>
    </li>
    <?php endforeach; ?>
    <li>
      <div class="list-group-item add-new-list">
        <div class="name"><?=$this->transEsc('Create a List') ?></div>
        <span class="pull-right"><i class="fa fa-plus-small icon"></i></span>
      </div>
    </li>
  </ul>
<!-- END of: finna - myresearch/mylist-navi.phtml -->
