<!-- START of: finna - myresearch/profile-my-information.phtml -->
<?php if ($user): ?>
  <form name="my_profile_form" class="inline" method="post">
    <?php if (!$this->hideProfileEmailAddress): ?>
      <div class="my-profile-row">
        <div class="my-profile-col">
          <label for="email"><?=$this->transEsc("Email") ?>:</label>
        </div>
        <div class="my-profile-col">
          <input id="email" type="email" class="form-control" name="email" value="<?=$user->email?>"/>
        </div>
        <div class="clearfix visible-xs"></div>
        <div class="my-profile-col">
          <i class="fa fa-info-circle-hollow"></i>  <?=$this->transEsc($this->hideDueDateReminder ? 'email_info_without_ddr' : 'email_info') ?>
        </div>
      </div>
      <div class="my-profile-row">
        <div class="my-profile-col">
          <label for="finna_nickname"><?=$this->transEsc("finna_nickname") ?>:</label>
        </div>
        <div class="my-profile-col">
          <input id="finna_nickname" type="text" class="form-control profileinfo-fields" name="finna_nickname" value="<?=$this->escapeHtml(trim($user->finna_nickname))?>" pattern="^(?!.*[._\-\s]{2})[A-ZÅÄÖa-zåäö0-9._\-\s]{3,50}$" title="<?=$this->transEsc('finna_nickname_restrictions')?>"/>
        </div>
        <div class="clearfix visible-xs"></div>
        <div class="my-profile-col">
          <i class="fa fa-info-circle-hollow"></i> <?=$this->transEsc("finna_nickname_info")?>
        </div>
      </div>
      <div class="my-profile-row">
          <input id="save-user-profile" name="saveUserProfile" type="submit" value="<?=$this->transEsc("Save") ?>" class="btn btn-primary" />
      </div>
    <?php endif; ?>
  </form>
  <?php if (!$this->hideDueDateReminder): ?>
    <form id="profile_due_date_form" class="inline" method="post">
      <div class="my-profile-row">
        <div class="my-profile-col profile-title">
            <label for="due-date-reminder"><?=$this->transEsc('messaging_settings_type_dueDateAlertEmail')?>:</label>
        </div>
        <div class="my-profile-col">
          <select id="due-date-reminder" name="due_date_reminder" class="jumpMenu form-control">
            <option value="0" <?= $user->finna_due_date_reminder == 0 ? 'selected="selected"' : '' ?>><?=$this->transEsc("due_date_reminder_none") ?></option>
            <option value="1" <?= $user->finna_due_date_reminder == 1 ? 'selected="selected"' : '' ?>><?=$this->transEsc("due_date_reminder_one_day") ?></option>
            <option value="2" <?= $user->finna_due_date_reminder == 2 ? 'selected="selected"' : '' ?>><?=$this->transEsc("due_date_reminder_two_days") ?></option>
            <option value="3" <?= $user->finna_due_date_reminder == 3 ? 'selected="selected"' : '' ?>><?=$this->transEsc("due_date_reminder_three_days") ?></option>
          </select>
          <?php if ($user->finna_due_date_reminder && empty($user->email)): ?>
            <span class="alert-danger"><?=$this->transEsc('no_email_address')?></span>
          <?php endif; ?>
        </div>
      </div>
    </form>
    <div class="clearfix"></div>
  <?php endif; ?>
  <div class="myresearch-profile-list">
    <?php if ($this->auth()->isLoggedIn() && !in_array($this->auth()->getManager()->getAuthClassForTemplateRendering(), ['Finna\Auth\ILS', 'Finna\Auth\MultiILS']) && $this->auth()->getManager()->supportsPasswordChange()): ?>
      <a href="<?=$this->url('myresearch-changepassword') ?>" class="btn btn-primary" data-lightbox><?=$this->transEsc('Change Password') ?></a>
    <?php endif; ?>
  </div>
<?php endif; ?>
<!-- END of: finna - myresearch/profile-my-information.phtml -->
