<!-- START of: finna - myresearch/profile.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';
    // Only display home library form if we have multiple pickup locations:
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);
    $user = $this->auth()->isLoggedIn();
    $cards = $user->getLibraryCards();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    $updateAddress = $this->ils()->checkFunction('updateAddress', $capabilityParams);
    $updatePhone = $this->ils()->checkFunction('updatePhone', $capabilityParams);
    $updateSmsNumber = $this->ils()->checkFunction('updateSmsNumber', $capabilityParams);
    $updateEmail = $this->ils()->checkFunction('updateEmail', $capabilityParams);
    $needsApproval = $updateAddress['needsApproval'] ?? true;
    $updateLoanHistory = $this->ils()->checkFunction('updateTransactionHistoryState', $capabilityParams);
    $updateAddressLink = '';
    if ($updateAddress) {
      $linkText = $this->translate(($updatePhone || $updateEmail || $updateSmsNumber) ? 'request_address_change' : 'request_contact_information_change');
      ob_start();
?>
        <?php if (in_array($updateAddress['method'], ['database', 'driver'])): ?>
          <i class="fa fa-pen"></i>
          <a class="profile-library-info-address-update" href="<?=$this->escapeHtmlAttr($this->url('myresearch-changeprofileaddress')) ?>" data-lightbox title="<?=$this->escapeHtmlAttr($linkText) ?>"><?=$this->escapeHtml($linkText) ?></a>
        <?php elseif ($updateAddress['method'] == 'url'): ?>
          <i class="fa fa-external-link"></i>
          <a class="profile-library-info-address-update" href="<?=$this->escapeHtmlAttr($this->translation()->getStringFromMixed($updateAddress['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($linkText) ?>"><?=$this->escapeHtml($linkText) ?></a>
        <?php endif; ?>
<?php
      $updateAddressLink = trim(ob_get_clean());
    }
    // Additional translations
    $this->jsTranslations()->addStrings(['new_password_success' => 'new_password_success']);
    $guarantorFullName = '';
    if (!empty($this->profile['guarantor'])) {
      $guarantor = $this->profile['guarantor'];
      $guarantorFullName = trim(
        ($guarantor['firstname'] ?? '')
        . ' '
        . ($guarantor['lastname'] ?? '')
      );
    }
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
    <div>
      <?php if (!$this->translationEmpty('profile_instructions')): ?><p class="no-content-message"><?=$this->transEsc('profile_instructions')?></p><?php endif; ?>
      <?=$this->flashmessages();?>
      <?php if (count($cards) > 1): ?>
        <div class="myresearch-profile-list library-card-holder">
          <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card'])?>
        </div>
      <?php endif; ?>
      <?= $this->partial('myresearch/borrowing-block.phtml', ['blocks' => $this->blocks]); ?>
      <?php if (is_array($this->profile)): ?>
        <div class="myresearch-profile-header"><span><?=$this->transEsc('Library Card Settings');?></span></div>
        <div class="myresearch-profile-list library-profile">
          <?php if ($showHomeLibForm): ?>
            <form id="profile_form" class="inline" method="post">
              <div class="my-profile-col profile-title"><label for="home_library"><?=$this->transEsc('preferred_pickup_location')?>:</label></div>
              <div>
                <?php
                  $selected = (isset($this->profile['home_library']) && $this->profile['home_library'] != "")
                    ? $this->profile['home_library'] : $this->defaultPickupLocation
                ?>
                <select id="home_library" name="home_library" class="jumpMenu form-control">
                  <?php foreach ($this->pickup as $lib): ?>
                    <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->transEscWithPrefix('location_', $lib['locationDisplay'])?></option>
                  <?php endforeach; ?>
                </select>
              </div>
            </form>
          <?php elseif (!empty($this->pickup)): ?>
            <div class="my-profile-col profile-title"><?=$this->transEsc('preferred_pickup_location')?>:</div>
            <div><?=$this->escapeHtml($this->pickup[0]['locationDisplay']); ?></div>
          <?php endif; ?>

          <?php if (isset($profile['messagingServices']) && !empty($profile['messagingServices'])): ?>
            <?= $this->partial('myresearch/profile-messaging.phtml', ['profile' => $profile, 'user' => $user, 'capabilityParams' => $capabilityParams]); ?>
          <?php endif; ?>

          <?php
            $selectedCard = null;
            foreach ($cards as $card) {
                if (strcasecmp($card->cat_username, $user->cat_username) === 0) {
                    $selectedCard = $card;
                    break;
                }
            }
          ?>
          <?php if ($selectedCard !== null && $this->ils()->checkFunction('changePassword', $selectedCard->toArray())): ?>
            <div>
              <span class="myresearch-profile-middle-header"><?=$this->transEsc('change_password_heading') ?></span>
            </div>
            <div>
              <span class="change-password-link">
                <a href="<?=$this->url('newLibraryCardPassword') ?>?id=<?=$this->escapeHtmlAttr($selectedCard['id']) ?>" class="btn btn-primary" data-lightbox title="<?=$this->transEsc('change_password_link')?>"><?=$this->transEsc('change_password_link') ?> &raquo;</a>
              </span>
            </div>
          <?php endif; ?>
          <div class="clearfix"></div>
          <form id="profile_library_form" class="inline" method="post">
            <div>
              <span class="myresearch-profile-middle-header"><?=$this->transEsc('Personal details maintained by the library') ?></span>
              <?php if (!$this->translationEmpty('contact_details_instructions')): ?><p class="no-content-message"><?=$this->translate('contact_details_instructions')?></p><?php endif; ?>
            </div>
            <?php if (!empty($this->profile['firstname'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('First Name') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['firstname']) ?></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['lastname'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Last Name') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['lastname']) ?></div>
            <?php endif; ?>
            <?php $addressParams = compact('updateAddress', 'updateAddressLink', 'needsApproval', 'updatePhone', 'updateEmail'); ?>
            <?php if (!empty($profile['addresses'])): ?>
              <?php $updateAddressParam = $updateAddress; ?>
              <?php foreach ($profile['addresses'] as $address): ?>
                <?php $addressParams['address'] = $address; $addressParams['updateAddress'] = $updateAddressParam; ?>
                <div class="profile-title profile-address-type">
                  <?=$this->transEsc('Address')?>
                  <?=!empty($address['preferred']) ? (' (' . $this->transEsc('address_preferred') . ')') : '' ?>
                </div>
                <div class="profile-group">
                  <?=$this->render('myresearch/profile-address.phtml', $addressParams)?>
                </div>
                <?php $updateAddressParam = false; ?>
              <?php endforeach; ?>
            <?php else: ?>
              <?php $addressParams['address'] = $this->profile; ?>
              <?=$this->render('myresearch/profile-address.phtml', ['address' => $this->profile, 'updateAddress' => $updateAddress, 'needsApproval' => $needsApproval, 'updatePhome' => $updatePhone, 'updateEmail' => $updateEmail])?>
            <?php endif; ?>
            <?php if (!empty($this->profile['phone']) || $updatePhone): ?>
              <?php if ($updatePhone): ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('Phone') ?>:</div>
                <div>
                  <input class="form-control" type="tel" name="profile_tel" value="<?=empty($this->profile['phone']) ? '' : $this->escapeHtml($this->profile['phone']) ?>" title="<?=$this->transEsc('Phone') ?>" />
                </div>
              <?php else: ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('Phone') ?>:</div>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['phone']) ?></div>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->profile['smsnumber']) || $updateSmsNumber): ?>
              <?php if ($updateSmsNumber): ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('SMS Number') ?>:</div>
                <div>
                  <input class="form-control" type="tel" name="profile_sms_number" value="<?=empty($this->profile['smsnumber']) ? '' : $this->escapeHtml($this->profile['smsnumber']) ?>" title="<?=$this->transEsc('SMS Number') ?>" />
                </div>
              <?php else: ?>
                <div class="my-profile-col profile-title"><?=$this->transEsc('SMS Number') ?>:</div>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['smsnumber']) ?></div>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->profile['email']) || $updateEmail): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Email') ?>:</div>
              <?php if ($updateEmail): ?>
                <div>
                  <input class="form-control" type="email" name="profile_email" value="<?=empty($this->profile['email']) ? '' : $this->escapeHtml($this->profile['email']) ?>" title="<?=$this->transEsc('Email') ?>" />
                </div>
              <?php else: ?>
                <div class="profile-text-value"><?=$this->escapeHtml($this->profile['email']) ?></div>
              <?php endif; ?>
            <?php endif; ?>
            <?php if (!empty($this->profile['hold_identifier'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Hold Identifier') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['hold_identifier']) ?></div>
            <?php endif; ?>
            <?php if (isset($this->profile['loan_history']) || $updateLoanHistory): ?>
              <div class="my-profile-col profile-title">
                <?php if ($updateLoanHistory): ?>
                  <label for="loan-history"><?=$this->transEsc('loan_history_retention') ?>:</label>
                <?php else: ?>
                  <?=$this->transEsc('loan_history_retention') ?>:
                <?php endif; ?>
              </div>
              <?php if ($updateLoanHistory): ?>
                <div class="my-profile-col profile-text-value">
                  <select id="loan-history" name="loan_history" class="form-control">
                    <?php foreach ($updateLoanHistory['options'] as $key => $value): ?>
                      <option value="<?=$this->escapeHtmlAttr($key)?>"<?= $this->profile['loan_history'] == $key ? ' selected="selected"' : '' ?>><?=$this->transEsc($value)?></option>
                    <?php endforeach; ?>
                  </select>
                </div>
                <?php $descriptionText = $this->translate(isset($updateLoanHistory['description'][$this->layout()->userLang]) ? $updateLoanHistory['description'][$this->layout()->userLang] : 'loan_history_description_html'); ?>
                <?php if ($descriptionText): ?>
                  <div class="my-profile-col">
                    <i class="fa fa-info-big"></i> <?=$descriptionText?>
                  </div>
                <?php endif; ?>
              <?php else: ?>
                <div class="profile-text-value"><?=$this->transEsc($this->profile['loan_history'] ? 'loan_history_forever' : 'loan_history_never') ?></div>
              <?php endif; ?>
              <div class="clearfix"></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['group'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Group') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['group']) ?></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['notes'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Notes') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['notes']) ?></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['expiration_date'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Expires') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['expiration_date']) ?></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['self_service_pin'])): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('self_service_pin') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($this->profile['self_service_pin']) ?></div>
            <?php endif; ?>
            <?php if ($guarantorFullName): ?>
              <div class="my-profile-col profile-title"><?=$this->transEsc('Guarantor') ?>:</div>
              <div class="profile-text-value"><?=$this->escapeHtml($guarantorFullName) ?></div>
            <?php endif; ?>
            <?php if (!empty($this->profile['guarantors'])): ?>
              <?php $i = 0; ?>
              <?php foreach ($this->profile['guarantors'] as $guarantor): ?>
                <div class="my-profile-col profile-title"><?=++$i == 1 ? $this->transEsc('Guarantor') . ':' : ''?></div>
                <?php
                  $guarantorFullName = trim(
                    ($guarantor['firstname'] ?? '')
                    . ' '
                    . ($guarantor['lastname'] ?? '')
                  );
                ?>
                <div class="profile-text-value"><?=$this->escapeHtml($guarantorFullName) ?></div>
              <?php endforeach; ?>
            <?php endif; ?>
            <?php if (!empty($this->profile['guarantees'])): ?>
              <?php $i = 0; ?>
              <?php foreach ($this->profile['guarantees'] as $guarantee): ?>
                <div class="my-profile-col profile-title"><?=++$i == 1 ? $this->transEsc('Guarantees') . ':' : ''?></div>
                <?php
                  $guaranteeFullName = trim(
                    ($guarantee['firstname'] ?? '')
                    . ' '
                    . ($guarantee['lastname'] ?? '')
                  );
                ?>
                <div class="profile-text-value"><?=$this->escapeHtml($guaranteeFullName) ?></div>
              <?php endforeach; ?>
            <?php endif; ?>
            <?php if ($updateAddress): ?>
              <div>
                <?=$updateAddressLink ?>
              </div>
            <?php endif; ?>
            <div class="my-profile-row">
              <?php if ($updatePhone || $updateEmail || $updateLoanHistory): ?>
                <input id="save-library-profile" name="saveLibraryProfile" type="submit" value="<?=$this->transEsc("save_my_profile") ?>" class="btn btn-primary my-profile-btn" />
              <?php endif; ?>
              <div class="clearfix"></div>
            </div>
          </form>
        </div>
      <?php endif; ?>
    </div>
    <div class="myresearch-profile-header">
      <span><?= $this->transEsc("Settings") ?></span>
    </div>
    <div class="myresearch-profile-list library-profile">
      <?= $this->partial('myresearch/profile-my-information.phtml', ['user' => $user, 'cards' => $cards, 'hideDueDateReminder' => $this->hideDueDateReminder, 'hideProfileEmailAddress' => $this->hideProfileEmailAddress]); ?>
    </div>
    <div class="myresearch-profile-header">
      <span><?= $this->transEsc("my_profile_export_import") . ' / ' . $this->transEsc('delete_account_title') ?></span>
    </div>
    <div class="myresearch-profile-list library-profile">
      <div class="my-profile-row">
        <a class="btn btn-primary my-profile-btn" href="<?=$this->url('myresearch-export') ?>" title="<?=$this->transEsc('export_favorites') ?>"><i class="fa fa-download" aria-hidden="true"></i> <?=$this->transEsc('export_favorites') ?></a>
        <a class="btn btn-primary my-profile-btn" href="<?=$this->url('myresearch-import') ?>"  data-lightbox title="<?=$this->transEsc('import_favorites') ?>"><i class="fa fa-upload" aria-hidden="true"></i> <?=$this->transEsc('import_favorites') ?> </a>
        <?php if ($this->accountDeletion): ?>
          <div class="visible-xs separator"></div>
          <a class="btn btn-danger my-profile-btn" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox><i class="fa fa-times"></i> <?=$this->transEsc('delete_account_title') ?></a>
          <?php if (!$this->translationEmpty('your_account_delete_info')): ?>
            <div class="my-profile-row">
                <i class="fa fa-info-circle-hollow" aria-hidden="true"></i> <?=$this->transEsc('your_account_delete_info');?>
            </div>
          <?php endif;?>
        <?php endif; ?>
      </div>
    </div>
    <?php if (!is_array($this->profile) && 'ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
      <?=$this->partial($this->patronLoginView);?>
    <?php endif; ?>
  </div>
</div>
<?php if (isset($this->parent)): ?>
<div>
  <div>
      <?php echo $this->parent ?>
  </div>
</div>
<?php endif; ?>
<!-- END of: finna - myresearch/profile.phtml -->