<!-- START of: finna - myresearch/recover.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('recovery_title'));
    $this->layout()->finnaMainHeader = '<div><h3 class="finna-main-header">' . $this->transEsc('recovery_title') . '</h3></div>';

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
      ->add($this->translate('recovery_title'), active: true);
?>
<h2><?=$this->transEsc('recovery_title') ?></h2>
<?=$this->flashmessages()?>
<form class="form-password-recovery" method="post">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->target)?>" name="target">

  <?=$this->auth()->getPasswordRecoveryForm() ?>
</form>
<!-- END of: finna - myresearch/recover.phtml -->
