<!-- START of: finna - myresearch/resetpassword.phtml -->
<?php
    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
      ->add($this->translate('Create New Password'), active: true);
?>
<?php if ($this->auth()->getIdentity()): ?>
  <div class="<?=$this->layoutClass('mainbody')?>">
<?php endif; ?>

<?=$this->component('page-title', ['title' => $this->translate('Create New Password')]);?>
<?=$this->flashmessages() ?>

<?php if (!$this->translationEmpty('reset_password_instructions')): ?>
  <div class="help-block"><?=$this->transEsc('reset_password_instructions') ?></div>
<?php endif; ?>

<form id="newpassword" class="form-new-password" action="<?=$this->url('myresearch-resetpassword') ?>" method="post">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth_method) ?>" name="auth_method">
  <?php if (!empty($this->target)): ?>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->target) ?>" name="target">
  <?php endif; ?>
  <?=$this->auth()->getResetPasswordForm() ?>
  <?=$this->captcha()->html($this->useCaptcha) ?>
  <div class="form-group">
    <input class="btn btn-primary" name="submitButton" type="submit" value="<?=$this->transEscAttr('Submit')?>">
  </div>
</form>
<!-- END of: finna - myresearch/resetpassword.phtml -->
