<!-- START of: finna - myresearch/unsubscribe.phtml -->
<div>
  <div class="content unsubscribe">
    <br>
    <?php if ($this->success == true): ?>
    <?= $this->translate('unsubscribe_successful'); ?>
<?php else: ?>
    <p><?= $this->translate('unsubscribe_confirmation'); ?></p><br> <a class="btn btn-primary" href="<?= $this->escapeHtml($this->unsubscribeUrl); ?>"><?= $this->translate('confirm_dialog_yes'); ?></a> <a class="btn btn-primary" href="<?= $this->url('home'); ?>"><?= $this->translate('confirm_dialog_no'); ?></a>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - myresearch/unsubscribe.phtml -->
