<!-- START of: finna - RecordDriver/SolrAipa/core.phtml -->
<?php
  $openUrl = $this->openUrl($this->driver, 'record');
  $openUrlActive = $openUrl->isActive();
  $identifierLinks = $this->identifierLinker($this->driver, 'record');

  $recordHelper = $this->record($this->driver);
  // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
  $onlineURLs = $this->driver->getOnlineURLs(false, ['image']);
  $mergedData = $this->driver->tryMethod('getMergedRecordData');
  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $img = $this->recordImage($this->record($this->driver));
  $audioUrls = [];
  $videoUrls = [];
  $otherUrls = [];
  $hasOnlineURLs = !empty($urls) || !empty($onlineURLs) || !empty($mergedData['urls']);

  if (!empty($urls)) {
    foreach ($urls as $url) {
      if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLinker()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
        array_push($videoUrls, $url);
      } elseif (!empty($url['embed']) && $url['embed'] == 'audio') {
        array_push($audioUrls, $url);
      } else {
        array_push($otherUrls, $url);
      }
    }
  }

  if (!empty($onlineURLs)) {
    $tempUrlArray = [];
    foreach ($onlineURLs as $url) {
      if (!empty($url['embed']) && $url['embed'] == 'audio') {
        array_push($audioUrls, $url);
      } else {
        array_push($tempUrlArray, $url);
      }
    }
    $onlineURLs = $tempUrlArray;
  }

  $img = $this->recordImage($this->record($this->driver));
  $thumbnail = false;
  $thumbnailAlignment = false;
?>

<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media">
  <h1 class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
  <div class="media-body record-information">
      <h1 class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getTitle())?></h1>
      <?php if ($results = $this->driver->getAlternativeTitles()): ?>
        <div class="recordAltTitles record-alt-titles">
          <?=implode('<br>', array_map([$this, 'escapeHtml'], $results))?>
        </div>
      <?php endif; ?>

      <?=$this->record($this->driver)->renderTemplate('cached-record-warning.phtml', ['driver' => $this->driver])?>
      <?=$this->record($this->driver)->getLabelList() ?>

      <?php if (!empty($urls) || $openUrlActive || $identifierLinks || !empty($onlineURLs) || !empty($mergedData['urls'])): ?>
        <?php if ($hasOnlineURLs || $openUrlActive || $identifierLinks): ?>
        <div class="recordURLs local-available-online-record">
          <div class="truncate-field">
            <?php if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
              <?php foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                <?php if (isset($images[$url['url']])) {
                  continue;
                } ?>
                <div class="fulltextField"><a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"><?=$this->icon('external-link') ?> <?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?></a>
                <?php if ($url['source']): ?>
                  <span class="online-source">(<?=is_array($url['source']) ? $this->transEsc('Multiple Organisations') : $this->transEsc('default::source_' . $url['source'], null, $url['source']) ?>)</span>
                <?php endif; ?>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
            <?php if (!empty($otherUrls)): ?>
              <?php foreach ($otherUrls as $url): ?>
                <?php if (isset($images[$url['url']])) {
                  continue;
                } ?>
                <?php $desc = $url['desc'] ?? $this->truncateUrl($url['url']); ?>
                <div class="fulltextField">
                  <a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" aria-label="<?=$this->transEscAttr('external_online_link')?>"
                    <?php if (!empty($url['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<?php endif; ?>
                  >
                    <?=$this->icon('external-link') ?> <?=$this->transEsc('default::link_' . $desc, null, $desc) ?>
                  </a>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          </div>

          <?=$identifierLinks?>
          <?php if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br>
          <?php endif; ?>
        </div>
        <?php endif; ?>
      <?php endif; ?>

      <div class="record-core-metadata">
        <?php $formats = $this->driver->getFormats();
        if (!empty($formats)): ?>
          <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
        <?php endif; ?>

        <?php
          $contents = $this->driver->getEncapsulatedContentTypeRecords();
          if (
            ($results = $this->driver->getNonPresenterAuthors())
            || (count($contents) === 1
              && ($results = reset($contents)->getNonPresenterAuthors()))
          ):
        ?>
        <div class="truncate-field recordAuthors">
          <strong><?= $this->transEsc('Aipa::Curated By') ?>:</strong>
          <span>
          <?php foreach ($results as $index => $author): ?>
            <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><?php if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><?php endif; ?><?php if (!empty($author['role'])): ?><span class="author-role">, <?=$this->escapeHtml($author['role']) ?></span><?php endif; ?>
          <?php endforeach; ?>
          </span>
        </div>
        <?php endif; ?>

        <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
          <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
        <?php endif; ?>
      </div>

      <?php /* Display Main Details */?>
      <?=
        $this->record($this->driver)->renderTemplate(
            'core-fields.phtml',
            [
              'driver' => $this->driver,
            ]
        );
      ?>
      <?php /* End Main Details */?>

      <?php if ($abstracts = $this->driver->getAbstracts()): ?>
        <div class="wide summary recordSummary">
          <?php if (isset($abstracts[$this->layout()->userLang])): ?>
            <?= $this->recordFieldMarkdown()->toHTML(($abstracts[$this->layout()->userLang]), "\n") ?>
          <?php else: ?>
            <?= $this->recordFieldMarkdown()->toHTML(implode("\n\n", $abstracts), "\n") ?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
      <?php
        if (($descriptions = $this->driver->getDescriptions())
          || (count($contents) === 1
            && ($descriptions = reset($contents)->getSummary()))
        ):
      ?>
        <div class="wide summary recordSummary">
          <?= $this->markdown()->toHTML(implode("\n\n", $descriptions)) ?>
        </div>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <?php /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc('Saved in')?>:</strong>
        </div>
      <?php endif; ?>

      <?php ob_start(); ?>
      <?= $this->record($this->driver)->renderTemplate('aipa-fields.phtml', [
          'fields' => $this->aipa($this->driver)->getAipaFieldGroup(\Finna\View\Helper\Root\Aipa::AIPA_ADDITIONAL_FIELDS),
        ]) ?>
      <?php $additionalInfo = trim(ob_get_contents()); ?>
      <?php ob_end_clean(); ?>
      <?php if (!empty($additionalInfo)): ?>
        <?= $this->component('finna-panel', [
            'attributes' => ['class' => ['finna-panel-default']],
            'heading' => $this->transEsc('Additional Information'),
            'headingLevel' => 3,
            'content' => $additionalInfo,
            'headingId' => uniqid('heading-'),
            'collapseId' => uniqid('collapse-'),
          ]); ?>
      <?php endif; ?>

      <?php if (count($contents) > 1): ?>
        <div class="record-toc">
          <p><strong><?= $this->transEsc('Contents') ?>:</strong></p>
          <ul>
            <?php foreach ($contents as $id => $record): ?>
              <li>
                <a href="#encapsulated-record-<?= $this->escapeHtmlAttr($id) ?>">
                  <?= $record->getTitle() ?>
                </a>
              </li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>

      <?= $this->record($this->driver)->renderEncapsulatedRecords(['limit' => null]) ?>

      <?php if ($template = $this->content()->findTemplateForLng('content/Additions/record-post-metadata')): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <?php endif; ?>
    </div>
  <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrAipa/core.phtml -->
