<!-- START of: finna - content/about_finna_sites.phtml -->

<div class="page-content">
  <div class="organisation-list-group">
    <h4><a id="publiclib"><?=$this->transEsc('Public Libraries')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://anders.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/anders.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'anders.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Anders/')?></p>
        <p class="organisation-list-url">anders.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://blanka.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/blanka.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'blanka.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Blanka/')?></p>
        <p class="organisation-list-url">blanka.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://eepos.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/eepos.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'eepos.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('library_eepos')?></p>
        <p class="organisation-list-url">eepos.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://heili.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/heili.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'heili.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Heili/')?></p>
        <p class="organisation-list-url">heili.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://helle.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/helle.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kirkes.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Helle/')?></p>
        <p class="organisation-list-url">helle.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kainet.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kainet.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kainet.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Kainet/')?></p>
        <p class="organisation-list-url">kainet.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kirkes.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kirkes.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kirkes.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Kirkes/')?></p>
        <p class="organisation-list-url">kirkes.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://keski.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/keski.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'keski.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Keski/')?></p>
        <p class="organisation-list-url">keski.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kuopio.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kuopio.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kuopio.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Kuopio/')?></p>
        <p class="organisation-list-url">kuopio.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kyyti.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kyyti.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kyyti.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Kyyti/')?></p>
        <p class="organisation-list-url">kyyti.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lapinkirjasto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lapinkirjasto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lapinkirjasto.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Lapinkirjasto/')?></p>
        <p class="organisation-list-url">lapinkirjasto.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://leppavirta.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/leppavirta.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lastu.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/lep/')?></p>
        <p class="organisation-list-url">leppavirta.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lastu.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lastu.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lastu.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Lastu/')?></p>
        <p class="organisation-list-url">lastu.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://louna.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/louna.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lumme.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Louna/')?></p>
        <p class="organisation-list-url">louna.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lukki.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lukki.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lukki.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Lukki/')?></p>
        <p class="organisation-list-url">lukki.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lumme.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lumme.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lumme.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Lumme/')?></p>
        <p class="organisation-list-url">lumme.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://outi.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/outi.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'outi.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Outi/')?></p>
        <p class="organisation-list-url">outi.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://satakirjastot.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/satakirjastot.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'satakirjastot.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Satakirjastot/')?></p>
        <p class="organisation-list-url">satakirjastot.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://siilinjarvenkirjasto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/siilinjarvi.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'siilinjarvenkirjasto.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/sii/')?></p>
        <p class="organisation-list-url">siilinjarvenkirjasto.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://somero.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/somero.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'somero.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Somero/')?></p>
        <p class="organisation-list-url">somero.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://sotkamo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/sotkamo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'sotkamo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Sotkamo/')?></p>
        <p class="organisation-list-url">sotkamo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tiekko.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/tiekko.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tiekko.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Tiekko/')?></p>
        <p class="organisation-list-url">tiekko.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://vaara.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/vaara.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'vaara.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Vaarakirjastot/')?></p>
        <p class="organisation-list-url">vaara.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://vaski.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/vaski.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'vaski.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Vaski/')?></p>
        <p class="organisation-list-url">vaski.finna.fi</p></a>
      </div>
    </div>
  </div>
  
  <div class="organisation-list-group">
    <h4><a id="archives"><?=$this->transEsc('Archives')?></a></h4>
      <div class="organisation-list-inner-row">
        <div class="organisation-list-item"> <a href="https://lasipalatsi.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/albumitauki.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lasipalatsi.finna.fi'])); ?>">
          <p class="organisation-list-header"><?=$this->transEsc('0/lasipalatsi/')?></p>
          <p class="organisation-list-url">lasipalatsi.finna.fi</p></a>
        </div>
        <div class="organisation-list-item"> <a href="https://kavi.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kavi.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'sls.finna.fi'])); ?>">
          <p class="organisation-list-header"><?=$this->transEsc('0/KAVI/')?></p>
          <p class="organisation-list-url">kavi.finna.fi</p></a>
        </div>
        <div class="organisation-list-item"> <a href="https://sls.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/sls.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'sls.finna.fi'])); ?>">
          <p class="organisation-list-header"><?=$this->transEsc('0/SLS/')?></p>
          <p class="organisation-list-url">sls.finna.fi</p></a>
        </div>
    </div>
  </div>
    
  <div class="organisation-list-group">
    <h4><a id="museums"><?=$this->transEsc('Museums')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://ekm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/ekm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'ekm.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/ESPOO_KAUPMUS/')?></p>
        <p class="organisation-list-url">ekm.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://hkm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hkm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hkm.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
        <p class="organisation-list-url">hkm.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://hkm.finna.fi/elanto2"><img src="<?=$this->imageLink('finnafrontpages/hkmelanto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hkm.finna.fi/elanto2/'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
        <p class="organisation-list-url">hkm.finna.fi/elanto</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://hrm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hrm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hrm.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HOTELLI- JA RAVINTOLAMUSEO/')?></p>
        <p class="organisation-list-url">hrm.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://muistaja.finna.fi/hyvinkaan_kaupunginmuseo"><img src="<?=$this->imageLink('finnafrontpages/hyvinkaankaupunginmuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'muistaja.finna.fi/hyvinkaan_kaupunginmuseo'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HYVINKAAMUSEO/')?></p>
        <p class="organisation-list-url">muistaja.finna.fi/hyvinkaan_kaupunginmuseo</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://muistaja.finna.fi/keravan_museopalvelut"><img src="<?=$this->imageLink('finnafrontpages/keravanmuseopalvelut.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'muistaja.finna.fi/keravan_museopalvelut'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/KERAVAMUSEO/')?></p>
        <p class="organisation-list-url">muistaja.finna.fi/keravan_museopalvelut</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lappeenrannanmuseot.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lappeenrannanmuseot.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lappeenrannanmuseot.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/LPRMUSEOT/')?></p>
        <p class="organisation-list-url">lappeenrannanmuseot.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://museot.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/museot.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'museot.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('Museums')?></p>
        <p class="organisation-list-url">museot.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://muistaja.finna.fi/mantsalan_museopalvelut"><img src="<?=$this->imageLink('finnafrontpages/mantsalanmuseopalvelut.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'muistaja.finna.fi/mantsalan_museopalvelut'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/MANTSALAMUSEO/')?></p>
        <p class="organisation-list-url">muistaja.finna.fi/mantsalan_museopalvelut</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://muistaja.finna.fi/nurmijarven_museo"><img src="<?=$this->imageLink('finnafrontpages/nurmijarvenmuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'muistaja.finna.fi/nurmijarven_museo'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/NURMIJARVIMUSEO/')?></p>
        <p class="organisation-list-url">muistaja.finna.fi/nurmijarven_museo</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://siida.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/siida.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'siida.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SIIDA/')?></p>
        <p class="organisation-list-url">siida.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://satakunnanmuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/satakunnanmuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'satakunnanmuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SATMUSEO/')?></p>
        <p class="organisation-list-url">satakunnanmuseo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://ilmailumuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/ilmailumuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'ilmailumuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/ilmailumuseo/')?></p>
        <p class="organisation-list-url">ilmailumuseo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kellomuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kellomuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kellomuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/KELLOMUSEO/')?></p>
        <p class="organisation-list-url">kellomuseo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://lelumuseohevosenkenka.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lelumuseohevosenkenka.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lelumuseohevosenkenka.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HEVOSENKENKA/')?></p>
        <p class="organisation-list-url">lelumuseohevosenkenka.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://rautatiemuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/rautatiemuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'rautatiemuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SRM/')?></p>
        <p class="organisation-list-url">rautatiemuseo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://urheilumuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/sum.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'urheilumuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SUM/')?></p>
        <p class="organisation-list-url">urheilumuseo.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://vantaankaupunginmuseo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/vantaankaupunginmuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'vantaankaupunginmuseo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/VANTAA/')?></p>
        <p class="organisation-list-url">vantaankaupunginmuseo.finna.fi</p></a>
      </div>
    </div>
  </div>

  <div class="organisation-list-group">
    <h4><a id="polylib"><?=$this->transEsc('Polytechnic Libraries')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://arcada.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/arcada.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'arcada.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/ARCADA/')?></p>
        <p class="organisation-list-url">arcada.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://centria.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/centria.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'centria.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/CENTRIA/')?></p>
        <p class="organisation-list-url">centria.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://diak.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/diak.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'diak.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/DIAK/')?></p>
        <p class="organisation-list-url">diak.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://haagahelia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/haagahelia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'haagahelia.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HAAGA-HELIA/')?></p>
        <p class="organisation-list-url">haagahelia.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://humak.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/humak.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'humak.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/HUMAK/')?></p>
        <p class="organisation-list-url">humak.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://hamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hamk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('source_HAMK')?></p>
        <p class="organisation-list-url">hamk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://janet.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/janet.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'janet.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/JAMK/')?></p>
        <p class="organisation-list-url">janet.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kaakkuri.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kaakkuri.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kaakkuri.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
        <p class="organisation-list-url">kaakkuri.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kamk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/KAMK/')?></p>
        <p class="organisation-list-url">kamk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://karelia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/karelia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'karelia.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/KARELIA/')?></p>
        <p class="organisation-list-url">karelia.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://luc.finna.fi/lapinamk"><img src="<?=$this->imageLink('finnafrontpages/luc_lapinamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi/lapinamk'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('library_luc_lapinamk')?></p>
        <p class="organisation-list-url">luc.finna.fi/lapinamk</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://laurea.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/laurea.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'laurea.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/LAUREA/')?></p>
        <p class="organisation-list-url">laurea.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://metropolia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/metropolia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'metropolia.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/METROPOLIA/')?></p>
        <p class="organisation-list-url">metropolia.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://oamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/oamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'oamk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/OAMK/')?></p>
        <p class="organisation-list-url">oamk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://samk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/samk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'samk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SAMK/')?></p>
        <p class="organisation-list-url">samk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://savonia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/savonia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'savonia.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SAVONIA/')?></p>
        <p class="organisation-list-url">savonia.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://seamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/seamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'seamk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SEAMK/')?></p>
        <p class="organisation-list-url">seamk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tritonia.finna.fi/vamk"><img src="<?=$this->imageLink('finnafrontpages/vamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'https://tritonia.finna.fi/vamk/'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-VAMK/')?></p>
        <p class="organisation-list-url">tritonia.finna.fi/vamk</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tritonia.finna.fi/novia"><img src="<?=$this->imageLink('finnafrontpages/novia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'https://tritonia.finna.fi/novia/'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-NOVIA/')?></p>
        <p class="organisation-list-url">tritonia.finna.fi/novia</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://turkuamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/turkuamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'turkuamk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TUAMK/')?></p>
        <p class="organisation-list-url">turkuamk.finna.fi</p></a>
      </div>
    </div>
  </div>

  <div class="organisation-list-group">
    <h4><a id="univlib"><?=$this->transEsc('University Libraries')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://aalto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/aalto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'aalto.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/AALTO/')?></p>
        <p class="organisation-list-url">aalto.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://jyu.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/jyu.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'jyu.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/JYU/')?></p>
        <p class="organisation-list-url">jyu.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://kansalliskirjasto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kansalliskirjasto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kansalliskirjasto.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/NLF/')?></p>
        <p class="organisation-list-url">kansalliskirjasto.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://luc.finna.fi/ulapland"><img src="<?=$this->imageLink('finnafrontpages/luc_ulapland.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi/ulapland'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('library_luc_ulapland')?></p>
        <p class="organisation-list-url">luc.finna.fi/ulapland</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://mpkk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/mpkk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'mpkk.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/MPKK/')?></p>
        <p class="organisation-list-url">mpkk.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://oula.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/oula.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'oula.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/OY/')?></p>
        <p class="organisation-list-url">oula.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://hanken.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hanken.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hanken.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/SHH/')?></p>
        <p class="organisation-list-url">hanken.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://uniarts.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/uniarts.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'uniarts.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TAIY/')?></p>
        <p class="organisation-list-url">uniarts.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tritonia.finna.fi/uva"><img src="<?=$this->imageLink('finnafrontpages/uva.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tritonia.finna.fi/uva'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-UVA/')?></p>
        <p class="organisation-list-url">tritonia.finna.fi/uva</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tritonia.finna.fi/abo"><img src="<?=$this->imageLink('finnafrontpages/tritonia_aboakademi.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tritonia.finna.fi/abo'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('tritonia_abo')?></p>
        <p class="organisation-list-url">tritonia.finna.fi/abo</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://abo.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/abo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'abo.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/AA/')?></p>
        <p class="organisation-list-url">abo.finna.fi</p></a>
      </div>
    </div>
  </div>

  <div class="organisation-list-group">
    <h4><a id="jointlib"><?=$this->transEsc('Joint libraries')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://luc.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/luc.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
        <p class="organisation-list-url">luc.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tritonia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/tritonia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tritonia.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA/')?></p>
        <p class="organisation-list-url">tritonia.finna.fi</p></a>
      </div>
    </div>
  </div>

  <div class="organisation-list-group">
    <h4><a id="speciallib"><?=$this->transEsc('Special libraries')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://eduskunnankirjasto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/eduskunnankirjasto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'eduskunnankirjasto.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/EKK/')?></p>
        <p class="organisation-list-url">eduskunnankirjasto.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://finlit.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/finlit.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'finlit.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/FINLIT/')?></p>
        <p class="organisation-list-url">finlit.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://tilastokeskus.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/tilastokeskus.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tilastokeskus.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/STAT/')?></p>
        <p class="organisation-list-url">tilastokeskus.finna.fi</p></a>
      </div>
      <div class="organisation-list-item"> <a href="https://vaari.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/vaari.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'vaari.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/NRL/')?></p>
        <p class="organisation-list-url">vaari.finna.fi</p></a>
      </div>
    </div>
  </div>

  <div class="organisation-list-group">
    <h4><a id="regionallib"><?=$this->transEsc('Regional views')?></a></h4>
    <div class="organisation-list-inner-row">
      <div class="organisation-list-item"> <a href="https://jyvaskyla.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/jyvaskyla.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'jyvaskyla.finna.fi'])); ?>">
        <p class="organisation-list-header"><?=$this->transEsc('0/Jyväskylän kirjastot/')?></p>
        <p class="organisation-list-url">jyvaskyla.finna.fi</p></a>
      </div>
    </div>
  </div>
</div>

<!-- END of: finna - content/about_finna_sites.phtml -->
