<!-- START of: finna - content/about_finna-login.phtml -->
<?php
$loginTargets = [];
$catalog = $this->ils();
if ($catalog->checkCapability('getLoginDrivers')) {
  $loginTargets = $catalog->getLoginDrivers();
}
?>
<?php if ($loginTargets): ?>
<ul class="about-login-targets">
  <?php foreach ($loginTargets as $target): ?>
  <li><?=$this->transEsc("source_$target", null, $target)?></li>
  <?php endforeach ?>
</ul>
<?php endif ?>
<!-- END of: finna - content/about_finna-login.phtml -->
