<!-- START of: finna - content/about_finna_sites.phtml -->
<?php
  $groups = [
    [
      'id' => 'archives',
      'heading' => 'Archives',
      'items' => [
        [
          'name' => '0/AALTOARKISTO/',
          'domain' => 'aaltoarkisto.finna.fi',
          'image' => 'aaltoarkisto.jpg',
        ],
        [
          'name' => '0/lasipalatsi/',
          'domain' => 'lasipalatsi.finna.fi',
          'image' => 'albumitauki.jpg',
        ],
        [
          'name' => '0/KAVI/',
          'domain' => 'kavi.finna.fi',
          'image' => 'kavi.jpg',
        ],
        [
          'name' => '0/SLS/',
          'domain' => 'sls.finna.fi',
          'image' => 'sls.jpg',
        ],
      ]
    ],
    [
      'id' => 'museums',
      'heading' => 'Museums',
      'items' => [
        [
          'name' => '1/Museovirasto/Arkeologian kuvakokoelma/',
          'domain' => 'museovirasto.finna.fi/arkeologia',
          'image' => 'arkeologia.jpg'
        ],
        [
          'name' => '0/ESPOO_KAUPMUS/',
          'domain' => 'ekm.finna.fi',
          'image' => 'ekm.jpg'
        ],
        [
          'name' => '0/HKM/',
          'domain' => 'hkm.finna.fi',
          'image' => 'hkm.jpg'
        ],
        [
          'name' => '0/HKM/',
          'domain' => 'hkm.finna.fi/elanto2',
          'image' => 'hkmelanto.jpg'
        ],
        [
          'name' => '0/HOTELLI- JA RAVINTOLAMUSEO/',
          'domain' => 'hrm.finna.fi',
          'image' => 'hrm.jpg'
        ],
        [
          'name' => '0/HYVINKAAMUSEO/',
          'domain' => 'muistaja.finna.fi/hyvinkaan_kaupunginmuseo',
          'image' => 'hyvinkaankaupunginmuseo.jpg'
        ],
        [
          'name' => '1/Museovirasto/JOKA Journalistinen kuva-arkisto/',
          'domain' => 'museovirasto.finna.fi/joka',
          'image' => 'joka.jpg'
        ],
        [
          'name' => '0/Suomen kansallismuseo/',
          'domain' => 'suomenkansallismuseo.finna.fi',
          'image' => 'kansallismuseo.jpg'
        ],
        [
          'name' => '0/KERAVAMUSEO/',
          'domain' => 'muistaja.finna.fi/keravan_museopalvelut',
          'image' => 'keravanmuseopalvelut.jpg'
        ],
        [
          'name' => '0/LPRMUSEOT/',
          'domain' => 'lappeenrannanmuseot.finna.fi',
          'image' => 'lappeenrannanmuseot.jpg'
        ],
        [
          'name' => 'Museums',
          'domain' => 'museot.finna.fi',
          'image' => 'museot.jpg'
        ],
        [
          'name' => '0/Museovirasto/',
          'domain' => 'museovirasto.finna.fi/',
          'image' => 'museovirasto.jpg'
        ],
        [
          'name' => '0/MANTSALAMUSEO/',
          'domain' => 'muistaja.finna.fi/mantsalan_museopalvelut',
          'image' => 'mantsalanmuseopalvelut.jpg'
        ],
        [
          'name' => '0/NURMIJARVIMUSEO/',
          'domain' => 'muistaja.finna.fi/nurmijarven_museo',
          'image' => 'nurmijarvenmuseo.jpg'
        ],
        [
          'name' => '0/RIIHIMAENMUSEO/',
          'domain' => 'muistaja.finna.fi/riihimaen_kaupunginmuseo',
          'image' => 'riihimaenmuseo.jpg'
        ],
        [
          'name' => '0/SIIDA/',
          'domain' => 'siida.finna.fi',
          'image' => 'siida.jpg'
        ],
        [
          'name' => '0/SATMUSEO/',
          'domain' => 'satakunnanmuseo.finna.fi',
          'image' => 'satakunnanmuseo.jpg'
        ],
        [
          'name' => '0/ilmailumuseo/',
          'domain' => 'ilmailumuseo.finna.fi',
          'image' => 'ilmailumuseo.jpg'
        ],
        [
          'name' => '0/KELLOMUSEO/',
          'domain' => 'kellomuseo.finna.fi',
          'image' => 'kellomuseo.jpg'
        ],
        [
          'name' => '0/HEVOSENKENKA/',
          'domain' => 'lelumuseohevosenkenka.finna.fi',
          'image' => 'lelumuseohevosenkenka.jpg'
        ],
        [
          'name' => '0/SRM/',
          'domain' => 'rautatiemuseo.finna.fi',
          'image' => 'rautatiemuseo.jpg'
        ],
        [
          'name' => '0/SUM/',
          'domain' => 'urheilumuseo.finna.fi',
          'image' => 'sum.jpg'
        ],
        [
          'name' => '0/VANTAA/',
          'domain' => 'vantaankaupunginmuseo.finna.fi',
          'image' => 'vantaankaupunginmuseo.jpg'
        ],
        [
          'name' => '0/VARKAUDENMUSEOT/',
          'domain' => 'piipunjuurella.finna.fi',
          'image' => 'piipunjuurella.jpg'
        ],
      ]
    ],
    [
      'id' => 'polylib',
      'heading' => 'Polytechnic Libraries',
      'items' => [
        [
          'name' => '0/ARCADA/',
          'domain' => 'arcada.finna.fi',
          'image' => 'arcada.jpg'
        ],
        [
          'name' => '0/CENTRIA/',
          'domain' => 'centria.finna.fi',
          'image' => 'centria.jpg'
        ],
        [
          'name' => '0/DIAK/',
          'domain' => 'diak.finna.fi',
          'image' => 'diak.jpg'
        ],
        [
          'name' => '0/HAAGA-HELIA/',
          'domain' => 'haagahelia.finna.fi',
          'image' => 'haagahelia.jpg'
        ],
        [
          'name' => '0/HUMAK/',
          'domain' => 'humak.finna.fi',
          'image' => 'humak.jpg'
        ],
        [
          'name' => 'source_HAMK',
          'domain' => 'hamk.finna.fi',
          'image' => 'hamk.jpg'
        ],
        [
          'name' => '0/JAMK/',
          'domain' => 'janet.finna.fi',
          'image' => 'janet.jpg'
        ],
        [
          'name' => '0/XAMK/',
          'domain' => 'kaakkuri.finna.fi',
          'image' => 'kaakkuri.jpg'
        ],
        [
          'name' => '0/KAMK/',
          'domain' => 'kamk.finna.fi',
          'image' => 'kamk.jpg'
        ],
        [
          'name' => '0/KARELIA/',
          'domain' => 'karelia.finna.fi',
          'image' => 'karelia.jpg'
        ],
        [
          'name' => 'library_luc_lapinamk',
          'domain' => 'luc.finna.fi/lapinamk',
          'image' => 'luc_lapinamk.jpg'
        ],
        [
          'name' => '0/LAUREA/',
          'domain' => 'laurea.finna.fi',
          'image' => 'laurea.jpg'
        ],
        [
          'name' => '0/METROPOLIA/',
          'domain' => 'metropolia.finna.fi',
          'image' => 'metropolia.jpg'
        ],
        [
          'name' => '0/OAMK/',
          'domain' => 'oamk.finna.fi',
          'image' => 'oamk.jpg'
        ],
        [
          'name' => '0/SAMK/',
          'domain' => 'samk.finna.fi',
          'image' => 'samk.jpg'
        ],
        [
          'name' => '0/SAVONIA/',
          'domain' => 'savonia.finna.fi',
          'image' => 'savonia.jpg'
        ],
        [
          'name' => '0/SEAMK/',
          'domain' => 'seamk.finna.fi',
          'image' => 'seamk.jpg'
        ],
        [
          'name' => '0/TRITONIA-VAMK/',
          'domain' => 'tritonia.finna.fi/vamk',
          'image' => 'vamk.jpg'
        ],
        [
          'name' => '0/TRITONIA-NOVIA/',
          'domain' => 'tritonia.finna.fi/novia',
          'image' => 'novia.jpg'
        ],
        [
          'name' => '0/TUAMK/',
          'domain' => 'turkuamk.finna.fi',
          'image' => 'turkuamk.jpg'
        ],
      ]
    ],
    [
      'id' => 'speciallib',
      'heading' => 'Special libraries',
      'items' => [
        [
          'name' => '0/EKK/',
          'domain' => 'eduskunnankirjasto.finna.fi',
          'image' => 'eduskunnankirjasto.jpg'
        ],
        [
          'name' => '0/FINLIT/',
          'domain' => 'finlit.finna.fi',
          'image' => 'finlit.jpg'
        ],
        [
          'name' => '0/STAT/',
          'domain' => 'tilastokeskus.finna.fi',
          'image' => 'tilastokeskus.jpg'
        ],
        [
          'name' => '0/NRL/',
          'domain' => 'vaari.finna.fi',
          'image' => 'vaari.jpg'
        ],
      ]
    ],
    [
      'id' => 'jointlib',
      'heading' => 'Joint libraries',
      'items' => [
        [
          'name' => '0/LUC/',
          'domain' => 'luc.finna.fi',
          'image' => 'luc.jpg'
        ],
        [
          'name' => '0/TRITONIA/',
          'domain' => 'tritonia.finna.fi',
          'image' => 'tritonia.jpg'
        ],
      ]
    ],
    [
      'id' => 'publiclib',
      'heading' => 'Public Libraries',
      'items' => [
        [
          'name' => '0/Anders/',
          'domain' => 'anders.finna.fi',
          'image' => 'anders.jpg'
        ],
        [
          'name' => '0/Blanka/',
          'domain' => 'blanka.finna.fi',
          'image' => 'blanka.jpg'
        ],
        [
          'name' => 'library_eepos',
          'domain' => 'eepos.finna.fi',
          'image' => 'eepos.jpg'
        ],
        [
          'name' => '0/Heili/',
          'domain' => 'heili.finna.fi',
          'image' => 'heili.jpg'
        ],
        [
          'name' => '0/Helle/',
          'domain' => 'helle.finna.fi',
          'image' => 'helle.jpg'
        ],
        [
          'name' => '0/Kainet/',
          'domain' => 'kainet.finna.fi',
          'image' => 'kainet.jpg'
        ],
        [
          'name' => '0/Kirkes/',
          'domain' => 'kirkes.finna.fi',
          'image' => 'kirkes.jpg'
        ],
        [
          'name' => '0/Keski/',
          'domain' => 'keski.finna.fi',
          'image' => 'keski.jpg'
        ],
        [
          'name' => '0/Kuopio/',
          'domain' => 'kuopio.finna.fi',
          'image' => 'kuopio.jpg'
        ],
        [
          'name' => '0/Kyyti/',
          'domain' => 'kyyti.finna.fi',
          'image' => 'kyyti.jpg'
        ],
        [
          'name' => '0/Lapinkirjasto/',
          'domain' => 'lapinkirjasto.finna.fi',
          'image' => 'lapinkirjasto.jpg'
        ],
        [
          'name' => '0/lep/',
          'domain' => 'leppavirta.finna.fi',
          'image' => 'leppavirta.jpg'
        ],
        [
          'name' => '0/Lastu/',
          'domain' => 'lastu.finna.fi',
          'image' => 'lastu.jpg'
        ],
        [
          'name' => '0/Louna/',
          'domain' => 'louna.finna.fi',
          'image' => 'louna.jpg'
        ],
        [
          'name' => '0/Lukki/',
          'domain' => 'lukki.finna.fi',
          'image' => 'lukki.jpg'
        ],
        [
          'name' => '0/Lumme/',
          'domain' => 'lumme.finna.fi',
          'image' => 'lumme.jpg'
        ],
        [
          'name' => '0/Outi/',
          'domain' => 'outi.finna.fi',
          'image' => 'outi.jpg'
        ],
        [
          'name' => '0/Satakirjastot/',
          'domain' => 'satakirjastot.finna.fi',
          'image' => 'satakirjastot.jpg'
        ],
        [
          'name' => '0/sii/',
          'domain' => 'siilinjarvenkirjasto.finna.fi',
          'image' => 'siilinjarvi.jpg'
        ],
        [
          'name' => '0/Somero/',
          'domain' => 'somero.finna.fi',
          'image' => 'somero.jpg'
        ],
        [
          'name' => '0/Sotkamo/',
          'domain' => 'sotkamo.finna.fi',
          'image' => 'sotkamo.jpg'
        ],
        [
          'name' => '0/Tiekko/',
          'domain' => 'tiekko.finna.fi',
          'image' => 'tiekko.jpg'
        ],
        [
          'name' => '0/Vaarakirjastot/',
          'domain' => 'vaara.finna.fi',
          'image' => 'vaara.jpg'
        ],
        [
          'name' => '0/Vaski/',
          'domain' => 'vaski.finna.fi',
          'image' => 'vaski.jpg'
        ],
      ]
    ],
    [
      'id' => 'univlib',
      'heading' => 'University Libraries',
      'items' => [
        [
          'name' => '0/AALTO/',
          'domain' => 'aalto.finna.fi',
          'image' => 'aalto.jpg'
        ],
        [
          'name' => '0/JYU/',
          'domain' => 'jyu.finna.fi',
          'image' => 'jyu.jpg'
        ],
        [
          'name' => '0/NLF/',
          'domain' => 'kansalliskirjasto.finna.fi',
          'image' => 'kansalliskirjasto.jpg'
        ],
        [
          'name' => 'library_luc_ulapland',
          'domain' => 'luc.finna.fi/ulapland',
          'image' => 'luc_ulapland.jpg'
        ],
        [
          'name' => '0/MPKK/',
          'domain' => 'mpkk.finna.fi',
          'image' => 'mpkk.jpg'
        ],
        [
          'name' => '0/OY/',
          'domain' => 'oula.finna.fi',
          'image' => 'oula.jpg'
        ],
        [
          'name' => '0/SHH/',
          'domain' => 'hanken.finna.fi',
          'image' => 'hanken.jpg'
        ],
        [
          'name' => '0/TAIY/',
          'domain' => 'uniarts.finna.fi',
          'image' => 'uniarts.jpg'
        ],
        [
          'name' => '0/TRITONIA-UVA/',
          'domain' => 'tritonia.finna.fi/uva',
          'image' => 'uva.jpg'
        ],
        [
          'name' => 'tritonia_abo',
          'domain' => 'tritonia.finna.fi/abo',
          'image' => 'tritonia_aboakademi.jpg'
        ],
        [
          'name' => '0/AA/',
          'domain' => 'abo.finna.fi',
          'image' => 'abo.jpg'
        ],
      ]
    ],
    [
      'id' => 'regionallib',
      'heading' => 'Regional views',
      'items' => [
        [
          'name' => '0/Jyväskylän kirjastot/',
          'domain' => 'jyvaskyla.finna.fi',
          'image' => 'jyvaskyla.jpg'
        ],
      ]
    ]
  ];
?>

<?php foreach ($groups as $group): ?>
  <div class="organisation-list-group">
    <h4 id="<?=$this->escapeHtmlAttr($group['id'])?>"><?=$this->transEsc($group['heading'])?></h4>
    <div class="organisation-list-inner-row">
      <?php foreach ($group['items'] as $current): ?>
        <div class="organisation-list-item">
          <a href="https://<?=$this->escapeHtmlAttr($current['domain'])?>"><img src="<?=$this->imageLink('finnafrontpages/' . $current['image'])?>" alt="<?=$this->transEscAttr('screenshot_alt_text', ['%%siteurl%%' => $current['domain']]); ?>">
            <p class="organisation-list-header"><?=$this->transEsc($current['name'])?></p>
            <p class="organisation-list-url"><?=$this->escapeHtml($current['domain'])?></p>
          </a>
        </div>
      <?php endforeach; ?>
    </div>
  </div>
<?php endforeach; ?>
<!-- END of: finna - content/about_finna_sites.phtml -->
