<?php return; // Delete this row to display the page below ?> 
<!-- START of: finna - content/accessibility-statement_en-gb.phtml -->
<?php $this->headTitle($this->translate('accessibility_statement'));  ?>
<div class="page-content">
    <h1>Accessibility statement of the Finna.fi website</h1>
    <p>This accessibility statement applies to the finna.fi website and it was created on 8 November 2019.</p>
    <h2>The accessibility status of the digital service</h2>
    <p>The website meets the critical accessibility requirements.</p>
    <h2>Did you notice an accessibility deficiency in our digital service? Tell us about it and we will do our best to rectify it.</h2>
    <h3>By online form</h3>
    <p><a href="<?=$this->url('feedback-home') ?>">Leave accessibility feedback on this online form</a>. Select accessibility as the topic of feedback.</p>
    <h3>By email</h3>
    <p>finna-palaute(at)helsinki.fi</p>
    <h2>Supervisory authority</h2>
    <p>If you notice accessibility issues on the website, first leave your feedback with us, the administrators of the website. It may take up to 14 days to receive an answer from us. Should you not be satisfied with the answer or you do not receive an answer from us within two weeks, you may file a complaint with the Regional State Administrative Agency for Southern Finland. The agency website has detailed instructions (in Finnish and Swedish only) on how to file a complaint and how the issue will be handled.</p>
    <h3>Contact information of the supervisory authority</h3>
    <p>Regional State Administrative Agency for Southern Finland<br>
    Accessibility supervision unit<br>
    <a href="https://www.saavutettavuusvaatimukset.fi/">www.saavutettavuusvaatimukset.fi</a><br>
    saavutettavuus(at)avi.fi<br>
    phone 0295 016 000 (switchboard)
    </p>
</div>
<!-- END of: finna - content/accessibility-statement_en-gb.phtml -->
