<?php return; // Delete this row to display the page below ?> 
<!-- START of: finna - content/accessibility-statement_sv.phtml -->
<?php $this->headTitle($this->translate('accessibility_statement'));  ?>
<div class="page-content">
    <h1>Tillgänglighetsutlåtande för Finna.fi</h1>
    <p>Detta tillgänglighetsutlåtande gäller webbplatsen finna.fi och har utarbetats den 8 november 2019.</p>
    <h2>Den digitala tjänstens tillgänglighet</h2>
    <p>Webbplatsen uppfyller de kritiska tillgänglighetskraven.</p>
    <h2>Upptäckte du bristande tillgänglighet i vår digitala tjänst? Berätta för oss så gör vi vårt bästa för att åtgärda bristen.</h2>
    <h3>Med e-blankett</h3>
    <p><a href="<?=$this->url('feedback-home') ?>">Ge respons om tillgängligheten med denna e-blankett</a>. Välj webbtillgänglighet som blankettens ämne.</p>
    <h3>Per e-post</h3>
    <p>finna-palaute(at)helsinki.fi</p>
    <h2>Tillsynsmyndigheten</h2>
    <p>Om du upptäcker tillgänglighetsproblem på webbplatsen, ge respons till oss som är webbansvariga. Vi svarar dig inom 14 dagar. Om du inte är nöjd med svaret eller inte alls får ett svar inom loppet av två veckor, kan du göra en anmälan till Regionförvaltningsverket i Södra Finland. Regionförvaltningsverket i Södra Finland har på sin webbplats ingående anvisningar om hur man gör en anmälan och hur den behandlas.</p>
    <h3>Tillsynsmyndighetens kontaktuppgifter</h3>
    <p>Regionförvaltningsverket i Södra Finland<br>
    Enheten för tillgänglighetstillsyn<br>
    <a href="https://www.tillgänglighetskrav.fi/">www.tillgänglighetskrav.fi</a><br>
    saavutettavuus(at)avi.fi<br>
    tfn 0295 016 000 (växeln)
    </p>
</div>
<!-- END of: finna - content/accessibility-statement_sv.phtml -->
