<!-- START of: finna - content/help_fi.phtml -->
<? if ($this->resolver('Content/help-tabs.phtml')): ?>
  <?=$this->render('Content/help-tabs.phtml', ['activeTab' => 'help'])?>
<? endif; ?>
<div>
  <div class="sidebar left">
    <div class="content-navigation-menu">
    </div>
  </div>
  <div class="mainbody right">
    <? if ($this->resolver('Content/Additions/helpBegin.phtml')): ?>
      <?=$this->render('Content/Additions/helpBegin.phtml')?>
    <? endif; ?>
    <div id="begin1" class="content-section">
      <h2>Miten aloitan haun Finnassa?</h2>
      <p>Hakuvaihtoehdot Finnassa:</p>
      <h3>Vapaa sanahaku ja rajaus <a href="<?=$this->url('home')?>"><i class="fa fa-external-link-square" aria-hidden="true"></i></a></h3>
      <ul class="list-bullets">
        <li>Haku on helpointa aloittaa kirjoittamalla hakusanoja hakukenttään haluamastasi aiheesta tai aineistosta.</li>
        <li>Hakukentän päässä olevasta pudotusvalikosta valitsemalla voi kohdistaa haun otsikkoon, tekijään tai aiheeseen. Vaihtoehto "Kaikki osumat" kohdistaa haun kaikkiin haettavissa oleviin tietoihin.</li>
        <li>Ensimmäisen haun jälkeen on <strong>mahdollista rajata</strong> hakutuloksia esimerkiksi käyttöoikeuksien, aineiston sisältötyypin tai valmistusvuoden mukaan.</li>
        <li>Ideoita hakujen muotoiluun saat <a href="<?=$this->url('content-page', ['page' => 'help-basic'])?>">perushaun</a> ohjeistuksesta.</li>
      </ul>
      <h3>Tarkennettu haku <a href="<?=$this->url('search-advanced')?>"><i class="fa fa-external-link-square" aria-hidden="true"></i></a></h3>
      <h3>Finna Street <a href="<?=$this->url('search-streetsearch')?>?go=1"><i class="fa fa-external-link-square" aria-hidden="true"></i></a></h3>
      <ul class="list-bullets">
        <li>Finna Street - paikkahaku etsii selaimesi antaman sijainnin perusteella kuvia Finnasta. Sijainnin perusteella tapahtuva haku toimii luotettavimmin laitteilla, jotka käyttävät GPS-tekniikaa paikannukseen, eli mobiililaitteilla. Hakutulokset ovat riippuvaisia kuvien paikkatiedoista. Voit hakea paikkoihin liittyvää aineistoa myös kirjoittamalla paikan nimen tai osoitteen hakupalkkiin. Muista sallia paikannus selaimessasi!</li>
      </ul>
    </div>
    <div id="begin2" class="content-section">
      <h2>Miten tarkastelen hakutuloksia?</h2>
      <p>Kun teet haun Finnassa, haun käynnistäminen ohjaa hakutulossivulle, josta löydät hakusanojasi vastaavaa aineistosisältöä. Hakutuloksia voi rajata hakutulossivulla (ks <a href="<?=$this->url('content-page', ['page' => 'help-basic'])?>#narrowsearch">Hakutulosten rajaaminen</a> -osio). Jos Finnasta ei löydy hakuasi vastaavaa aineistoa, ilmoittaa haku siitä erikseen.</p>
      <p>Hakutuloslistasta pääset aineiston tarkkoihin tietoihin otsikkoa napauttamalla. Hakutuloksen kuvaketta tai kuvaa klikkaamalla saat auki suuremman kuvan ja osan tiedoista esikatselunäkymässä.</p>
      <p>Osaan aineistosta  tarjotaan latausmahdollisuus. Muistathan kuitenkin tarkistaa esimerkiksi kuvien käyttöoikeudet aineiston omista tiedoista.</p>
      <p>Aineistoa voi hyödyntää esimerkiksi opetuksen ja oppimisen tukena tai harrastuskäytössä.</p>
    </div>
    <? if ($this->resolver('Content/Additions/helpEnd.phtml')): ?>
      <?=$this->render('Content/Additions/helpEnd.phtml')?>
    <? endif; ?>
  </div>
</div>
<!-- END of: finna - content/help_fi.phtml -->
