<!-- START of: finna - content/privacy_en-gb.phtml -->
<?php $this->headTitle($this->translate('Privacy'));
$this->content()->setHeading($this->translate('Privacy')); ?>

<div class="page-content">
  <h2>Finna – search services as a whole</h2>
  <p>Finna consists of Finna.fi, a site that brings all materials together, and other Finna search services. At Finna.fi, you can find the materials of all members of Finna, including archives, libraries and museums. Other Finna search services focus on specific materials and services. Further information: <a href="https://finna.fi/Content/about">Search services as a whole</a>.
  </p>
  <p>The National Library of Finland is responsible for the maintenance of Finna.fi and the general development of Finna services with its partners. CSC – IT Centre for Science also participates in the provision of Finna services. On this page, you can find information about the processing of personal data in Finna by the National Library of Finland and CSC. You can also find instructions for how to contact material providers regarding personal data in certain material.
  </p>
  <p>Cloudflare Inc., a contracting partner of The National Library of Finland, processes technical log data for the data traffic of Finna search services. More detailed information: <a href="https://finna.fi/Content/register_details" target="_blank">Data protection notice</a>.
  </p>
  <p>The members of Finna are responsible for the modification of their own Finna search services and the related processing of personal data. Additional services that are not maintained by the National Library of Finland or CSC may be offered in separate Finna search services. If the search service you use includes additional services in which personal data are processed, you can find more information on this page.
  </p>
  <h2>Processing the data of registered users in Finna</h2>
  <p>When a user logs in to Finna at Finna.fi or in other Finna search services, the following data will be stored in the service, depending on the login method:
  </p>
  <ul class="list-bullets">
    <li>When logging in with a library card, the user’s library card number, PIN code, first and last name, email address and home library are stored on the service. The data is automatically transferred to Finna from the library that issued the card.
    </li>
    <li>When logging in using Haka, the username, name and email address are stored on Finna.
    </li>
    <li>When logging in using Finna, Finna stores the information that was provided when the Finna ID was created, i.e. the email address and Finna ID. Persons under the age of 13 will need permission from a legal guardian to create an ID.
    </li>
    <li>When logging in using an email address, data about the user’s name, email address and home library is saved.
    </li>
  </ul>
  <p>Information is collected and managed for the execution of the Finna service at the National Library of Finland and CSC – IT Centre for Science (service providers).
  </p>
  <table class="content-table">
    <caption>This information is stored for the following purposes:
    </caption>
    <tr>
      <th scope="col"><strong>Information</strong></th>
      <th scope="col"><strong>Purpose</strong></th>
    </tr>
    <tr>
      <td>Finna ID</td>
      <td>User authentication</td>
    </tr>
    <tr>
      <td>Email</td>
      <td>Default address for email, can be edited by the user on Finna. When logging in with an email address: sending the login link to the email address stored in the patron information of the library.</td>
    </tr>
    <tr>
      <td>First name</td>
      <td>Showing information to a logged in user</td>
    </tr>
    <tr>
      <td>Last name</td>
      <td>Showing information to a logged in user</td>
    </tr>
    <tr>
      <td>Library card number</td>
      <td>User authentication</td>
    </tr>
    <tr>
      <td>PIN code</td>
      <td>User authentication for service interfaces</td>
    </tr>
    <tr>
      <td>Home library</td>
      <td>Default pick-up location for holds, can be edited by the user on Finna</td>
    </tr>
  </table>
  <p>In Finna search services, users can also save and modify their own data. Finna will only send emails requested by the user to the email address stored on Finna. These can include due date reminders and new entry alerts.
  </p>
  <p>In addition to the data mentioned above, Finna may store data as a consequence of the user’s activity in Finna. For example, such information includes the language(s) used, the most recent login date and time, data about payments made through Finna and their date for the investigation of any errors, receiving due date reminders and new entry alerts, records saved in your lists, library cards, comments, reviews and tags you have added.
  </p>
  <p>Other services that process data about library users, including browsing borrowed and reserved materials, making reservations, renewing loans, and registering as a customer, use the service interfaces of the library system, and do not store any information on Finna, with the exception of optional due date reminders. The ID number of the loan and the due date are stored on the service when sending out due date reminders. This information helps to ensure that each due date reminder is sent out only once.
  </p>
  <p>The Finna accounts created using a library card, a Finna ID or Haka login are separate from each other, even if they contain the same unique identifier.
  </p>
  <p>You may at any time delete your information on Finna by closing your account on the service. All data is automatically deleted once more than 18 months have passed since you last logged into the service. After your account has been removed, any comments and feedback you may have provided will remain anonymous; that is, it does not contain your personal data. If you would also like to delete your comments and reviews, you will need to do so manually before closing the account. As a Finna user, you can request information about how your personal information is used by contacting the service administrator at the National Library using the <a href="https://finna.fi/Feedback/Home">Finna.fi feedback form</a>. As a user of Finna search services, you have the right to review and correct your personal information.
  </p>
  <div class="well">For more information, please see the Finna <a href="register_details">Data Privacy Notice</a>.</div>
  <h2>Other personal data in Finna</h2>
  <p>Each organisation that provides material in the Finna service is responsible for all materials and information that it has made available through the Finna.fi site or other Finna search services. In the first instance, you should address any requests or demands concerning the materials or information to the organisation that provides them for Finna.
  </p>
  <p>The materials and their descriptive information may contain personal data such as people’s names or photographs. Additional information is given for some of the persons related to the materials, such as their authors, on a separate page. If you have any questions about personal data related to materials or their descriptive information, or you need to request the rectification or erasing of data, contact the organisation that provides the specific material or information in the Finna search services. You can contact the material or information provider on the Finna.fi website through the Contact form in connection with the page related to the material or person. If the form is unavailable, use the specific search service’s feedback form.
  </p>
  <p>If user comments about materials in the Finna search services include personal data that need to be rectified or erased, you can place your request using the feedback form available in the comment section.
  </p>
  <?php if ($template = $this->content()->findTemplateForLng('content/Additions/privacyAdditions')): ?>
    <?=$this->render($template)?>
  <?php endif; ?>
  <h2 id="cookies">Use of cookies</h2>
  <p>Cookies are small pieces of information sent by the server to your browser. In practice, they contain a small piece of information such as a brief text.
  </p>
  <p>Cookies do not affect information security, and they cannot spread any viruses or malware.
  </p>
  <p>Cookies make the use of Finna easier. Strictly necessary cookies enable Finna to run smoothly and make the site more user-friendly. Data collected by statistics cookies are used to develop the service.
  </p>
  <p>You can disable any unnecessary cookies by editing your cookie settings. If you change your mind, you can change your consent through the “Cookie settings” link at the bottom of the page or the button below.
  </p>
  <?php if ($this->cookieConsent()->isEnabled()): ?>
    <h3>Cookie Consent</h3>
    <?php if ($consent = $this->cookieConsent()->getConsentInformation()): ?>
      <p>Your current cookie consent:</p>
      <ul>
        <li>Domain: <?=$this->escapeHtml($consent['domain'] . ('/' !== $consent['path'] ? $consent['path'] : ''))?></li>
        <li>State: Allow (<?=implode(', ', array_map([$this, 'escapeHtml'], $consent['categoriesTranslated']))?>)</li>
        <li>Consent ID: <?=$this->escapeHtml($consent['consentId'])?>
        <li>Consent date: <?=$this->escapeHtml($consent['lastConsentDateTime'])?>
      </ul>
    <?php else: ?>
      <p>You have not yet given consent.</p>
    <?php endif; ?>
    <p>
      <a class="btn btn-default" href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a>
    </p>
  <?php endif; ?>

</div>
<!-- END of: finna - content/privacy_en-gb.phtml -->
