<!-- START of: finna - content/privacy_sv.phtml -->
<?php $this->headTitle($this->translate('Privacy')); $this->content()->setHeading($this->translate('Privacy')); ?>

<div class="page-content">
  <h2>Hantering av kunduppgifter i Finna</h2>
  <p>När användaren loggar in på Finna-tjänsten från webbplatsen Finna.fi, ett webbibliotek skapat på Finna-plattformen eller något annat Finna-användargränssnitt, sparas följande uppgifter i tjänsten, beroende på inloggningssätt:
  </p>
  <p>Vid inloggning med bibliotekskort sparas kortets nummer och pinkod, användarens för- och efternamn, e-postadress och hembibliotek i tjänsten. Uppgifterna överförs automatiskt till Finna-tjänsten från systemet vid biblioteket som beviljat kortet.
  </p>
  <p>Vid Haka-inloggning sparas användar-ID och användarens namn och e-postadress automatiskt i Finna.
  </p>
  <p>Vid inloggning via Finna-konto sparas uppgifterna som uppgetts när kontot skapades, dvs. e-postadress och användarnamn, i Finna. Personer under 13 år måste ha sin vårdnadshavares samtycke till att skapa ett konto.
  </p>
  <p>Uppgifterna hanteras för produktionen av Finna-tjänsten vid Nationalbiblioteket och CSC – IT-centret för vetenskap (tjänsteproducenterna).
  </p>
  <p>Uppgifterna sparas för följande ändamål:
  </p>
  <table class="content-table">
    <tr>
      <td><strong>Uppgift</strong></td>
      <td><strong>Ändamål</strong></td>
    </tr>
    <tr>
      <th>Användarnamn</th>
      <td>Identifierar användaren</td>
    </tr>
    <tr>
      <th>E-postadress</th>
      <td>Den adress som i första hand används, användaren kan ändra uppgiften i Finna</td>
    </tr>
    <tr>
      <th>Förnamn</th>
      <td>Visar information för den inloggade användaren</td>
    </tr>
    <tr>
      <th>Tillnamn</th>
      <td>Visar information för den inloggade användaren</td>
    </tr>
    <tr>
      <th>Bibliotekskortets nummer</th>
      <td>Identifierar användaren</td>
    </tr>
    <tr>
      <th>Pinkod</th>
      <td>Identifierar användaren i olika tjänstegränssnitt</td>
    </tr>
    <tr>
      <th>Hembibliotek</th>
      <td>Det ställe där beställningar i första hand avhämtas, användaren kan ändra uppgiften i Finna</td>
    </tr>
  </table>
  <p>I Finna-tjänsten kan användaren också själv spara och ändra sina personuppgifter. Till den e-postadress som sparas i Finna skickas bara sådana mejl som användaren själv önskar, t.ex. påminnelser om förfallodag och meddelanden från sökbevakningen.
  </p>
  <p>Förutom de ovan nämnda uppgifterna kan Finna-tjänsten också spara information till följd av användarens aktiviteter i Finna. Sådan information är bl.a. språk, aktiverad påminnelse om förfallodag, sökbevakningar, poster som användaren har sparat i egna listor, bibliotekskort som användaren själv lagt till och sociala metadata (kommentarer, recensioner, taggar).
  </p>
  <p>För andra funktioner som hanterar användarnas uppgifter, t.ex. för att bläddra i lån, reserveringar och avgifter samt göra reserveringar och förnya lån, används bibliotekssystemets tjänstegränssnitt och uppgifterna sparas inte i Finna, med undantag för frivilliga påminnelser om förfallodag.  I samband med att en påminnelse om förfallodag skickas till användaren sparas ID-numret och förfallodagen för lånet, detta för att varje påminnelse bara ska skickas en gång.
  </p>
  <p>Finna-konton som skapas med bibliotekskorts-, Finna- eller Haka-koder är separata, även om de innehåller samma identifikationsuppgift.
  </p>
  <p>Användaren kan när som helst radera sina uppgifter från Finna genom att avsluta sitt konto. Uppgifterna raderas automatiskt när det har gått 18 månader från den senaste inloggningen. När ett konto har avslutats, finns användarens eventuella kommentarer och recensioner kvar i tjänsten som anonyma, alltså utan användarens personuppgifter. Om användaren också vill radera kommentarerna och recensionerna, ska det göras manuellt innan kontot avslutas. Finna-tjänstens användare kan be att få information om hanteringen av personuppgifter genom att kontakta tjänstens administratör Nationalbiblioteket på <a href="https://finna.fi/Feedback/Home">Finna.fi-webbplatsens blankett för feedback</a>. Användaren har rätt att kontrollera och korrigera sina uppgifter.
  </p>
  <div class="well">Närmare information finns i <a href="register_details">dataskyddsbeskrivningen</a>.</div>
  <h2>Material och personuppgifter på Finna-tjänsten</h2>
  <p>Ansvaret för material som erbjuds via Finna-tjänsten (webbplatsen Finna.fi, ett webbibliotek skapat på Finna-plattformen eller något annat Finna-användargränssnitt) och för metadata om materialet ligger hos organisationen som har överfört materialet till tjänsten. Material och metadata kan innehålla personuppgifter, t.ex. namn eller bilder på personer. Om en Finna-användare vill ställa frågor om personuppgifter i material eller metadata, eller exempelvis korrigera uppgifter eller kräva att uppgifter raderas, kan användaren kontakta arkivet, biblioteket eller museet som tillhandahåller materialet. Det går att göra via Kontaktformuläret som finns vid respektive material på webbplatsen Finna.fi. Om formuläret saknas i sökresultaten eller annan Finna-tjänst, kan man också använda webbibliotekets eller tjänstens eget feedbackformulär.
  </p>
  <p>Om det i användarnas kommentarer till Finna-material finns personuppgifter som behöver korrigeras eller raderas, kan begäran skickas på formuläret vid kommentarerna.
  </p>
  <h2>Hantering av uppgifter om fjärrlånebeställare</h2>
  <p>Det går att beställa fjärrlån från vissa av webbiblioteken som skapats på Finna-plattformen. Biblioteket till vilket fjärrlånebeställningen lämnas får automatiskt följande uppgifter om beställaren från hembibliotekets system: namn, personbeteckning, kontaktuppgifter, informationen från bibliotekskortet och bibliotekets kund-ID. Uppgifterna överförs direkt från det ena bibliotekets system till det andras. Finna-tjänsten hanterar inte uppgifter och uppgifter sparas inte i tjänsten i samband med beställningarna. Fjärrlånebeställarens uppgifter raderas från systemet vid biblioteket som tar emot beställningen när beställaren inte längre har några aktiva reserveringar, lån eller obetalda avgifter vid det ifrågavarande biblioteket.</p>
  <h2 id="cookies">Kakor</h2>
  <p>Användningen av webbplatsen följs upp för att förbättra tjänsterna. För uppföljningen används kakor (cookies). Kakorna lagrar ingen information som gör det möjligt att identifiera användaren. Kakorna innebär ingen datasäkerhetsrisk och de kan inte sprida virus eller sabotageprogram.  När du besöker webbplatsen godkänner du användningen av kakor.
  </p>
</div>
<!-- END of: finna - content/privacy_sv.phtml -->
