<!-- START of: finna - content/privacy_sv.phtml -->
<?php $this->headTitle($this->translate('Privacy'));
$this->content()->setHeading($this->translate('Privacy')); ?>

<div class="page-content">
  <h2>Finna – en helhet av söktjänster</h2>
  <p>Finna består av Finna.fi som samlar allt material och andra Finna-söktjänster. Finna.fi innehåller material från alla de aktörer som ingår i Finna, såsom arkiv, bibliotek och museer. De övriga Finna-söktjänsterna fokuserar på visst material och vissa tjänster. Mer information: <a href="https://finna.fi/Content/about">Helheten av söktjänster</a>.
  </p>
  <p>Nationalbiblioteket svarar för förvaltningen av Finna.fi och den allmänna utvecklingen av Finna-helheten tillsammans med sina partner. Dessutom deltar CSC – IT-centret för vetenskap i att producera Finna-tjänsterna. På denna sida finns information om behandlingen av personuppgifter i anslutning till Finna på Nationalbiblioteket och vid CSC. Vi ger också anvisningar om att kontakta tillhandahållaren av materialet när det gäller personuppgifter i materialet.
  </p>
  <p>Nationalbibliotekets avtalspartner Cloudflare Inc. behandlar tekniska logguppgifter för Finna-söktjänsternas datatrafik. Närmare information: <a href="https://finna.fi/Content/register_details" target="_blank">Dataskyddsbeskrivning</a>.
  </p>
  <p>De aktörer som ingår i Finna ansvarar för redigeringen av sina Finna-söktjänster och för behandlingen av personuppgifter i samband med den. I aktörernas egna Finna-söktjänster kan de tillhandahålla sådana tilläggstjänster som inte förvaltas av Nationalbiblioteket eller CSC. Om en söktjänst du använder omfattar tilläggstjänster där det behandlas personuppgifter, får du mer information om detta på denna sida.
  </p>
  <h2>Behandling av uppgifter om en inloggad användare i Finna</h2>
  <p>När användaren loggar in i Finna-tjänsten på webbplatsen Finna.fi eller i någon annan Finna-söktjänst, sparas i tjänsten följande uppgifter beroende på inloggningssättet:
  </p>
  <ul class="list-bullets">
    <li>Vid inloggning med bibliotekskort sparas kortets nummer och pinkod, användarens för- och efternamn, e-postadress och hembibliotek i tjänsten. Uppgifterna överförs automatiskt till Finna-tjänsten från systemet vid biblioteket som beviljat kortet.
    </li>
    <li>Vid Haka-inloggning sparas användar-ID och användarens namn och e-postadress i Finna.
    </li>
    <li>Vid inloggning via Finna-konto sparas uppgifterna som uppgetts när kontot skapades, dvs. e-postadress och Finna-ID, i Finna. Personer under 13 år måste ha sin vårdnadshavares samtycke till att skapa ett konto.
    </li>
    <li>Vid inloggning med e-postadress sparas användarens namn, e-postadress och hembibliotek.
    </li>
  </ul>
  <p>Uppgifterna hanteras för produktionen av Finna-tjänsten vid Nationalbiblioteket och CSC – IT-centret för vetenskap (tjänsteproducenterna).
  </p>
  <table class="content-table">
    <caption>Uppgifterna sparas för följande ändamål:
    </caption>
    <tr>
      <th scope="col"><strong>Uppgift</strong></th>
      <th scope="col"><strong>Ändamål</strong></th>
    </tr>
    <tr>
      <td>Finna-ID</td>
      <td>Identifierar användaren</td>
    </tr>
    <tr>
      <td>E-postadress</td>
      <td>Den adress som i första hand används, användaren kan ändra uppgiften i Finna. Vid inloggning med e-postadress: sändning av inloggningslänken till den e-postadress som sparats i bibliotekets kunduppgifter.</td>
    </tr>
    <tr>
      <td>Förnamn</td>
      <td>Visar information för den inloggade användaren</td>
    </tr>
    <tr>
      <td>Tillnamn</td>
      <td>Visar information för den inloggade användaren</td>
    </tr>
    <tr>
      <td>Bibliotekskortets nummer</td>
      <td>Identifierar användaren</td>
    </tr>
    <tr>
      <td>Pinkod</td>
      <td>Identifierar användaren i olika tjänstegränssnitt</td>
    </tr>
    <tr>
      <td>Hembibliotek</td>
      <td>Det ställe där beställningar i första hand avhämtas, användaren kan ändra uppgiften i Finna</td>
    </tr>
  </table>
  <p>I Finna-söktjänsten kan användaren också själv spara och ändra sina personuppgifter. Till den e-postadress som registrerats i Finna sänds endast sådana e-postmeddelanden som användaren själv begärt, såsom påminnelser om förfallodag och meddelanden från nyhetsvakten.
  </p>
  <p>Förutom de ovan nämnda uppgifterna kan Finna-tjänsten också spara information till följd av användarens aktiviteter i Finna. Sådan information är bl.a. användningsspråk, senaste inloggningstidpunkt, uppgifter om och tidpunkt för betalningar via Finna för utredande av eventuella felsituationer, ibruktagande av påminnelser om förfallodag, nyhetsvakter, poster som användaren sparat på sina egna listor, bibliotekskort som användaren själv lagt till, kommentarer, recensioner och nyckelord.
  </p>
  <p>För andra funktioner som hanterar biblioteksanvändarnas uppgifter, t.ex. för att bläddra i lån, och reserveringar, göra reserveringar och förnya lån samt registrera sig som kund används bibliotekssystemets tjänstegränssnitt och uppgifterna sparas inte i Finna, med undantag för frivilliga påminnelser om förfallodag.  I samband med att en påminnelse om förfallodag skickas till användaren sparas ID-numret och förfallodagen för lånet, detta för att varje påminnelse bara ska skickas en gång.
  </p>
  <p>Finna-konton som skapas med bibliotekskort, Finna-användarnamn eller Haka-inloggning är separata, även om de innehåller samma identifikationsuppgift.
  </p>
  <p>Användaren kan när som helst radera sina uppgifter från Finna genom att avsluta sitt konto. Uppgifterna raderas automatiskt när det har gått 18 månader från den senaste inloggningen. När ett konto har avslutats, finns användarens eventuella kommentarer och recensioner kvar i tjänsten som anonyma, alltså utan användarens personuppgifter. Om användaren också vill radera kommentarerna och recensionerna, ska det göras manuellt innan kontot avslutas. Användaren av en Finna-söktjänst kan begära information om behandlingen av sina personuppgifter genom att kontakta Nationalbiblioteket med hjälp av <a href="https://finna.fi/Feedback/Home">responsformuläret på webbplatsen Finna.fi</a>. Användaren har rätt att kontrollera och korrigera sina uppgifter.
  </p>
  <div class="well">Närmare information finns i Finnas <a href="register_details">dataskyddsbeskrivningen</a>.</div>
  <h2>Övriga personuppgifter på Finna</h2>
  <p>För de material jämte de uppgifter som tillhandahålls på webbplatsen Finna.fi eller i de övriga Finna-söktjänsterna ansvarar den organisation som producerat materialet för tjänsten. Det lönar sig att skicka eventuella begäran om eller krav på materialen och uppgifterna till den organisation som tillhandahåller materialen och uppgifterna på Finna.
  </p>
  <p>Materialen och metadata kan innehålla personuppgifter, t.ex. namn eller bilder på personer. Det finns mer information om vissa personer i anknytning till materialen, såsom materialets upphovsmän, på en egen sida. Om det finns skäl att ställa frågor om de personuppgifter som ingår i materialet eller metadata eller om personuppgifter behöver till exempel rättas eller raderas, kan användaren av Finna-söktjänsten kontakta den organisation som tillhandahåller materialet eller uppgifterna för tjänsten. Du kan kontakta tillhandahållaren av materialet eller uppgifterna på webbplatsen Finna.fi med formuläret Ta kontakt som finns på sidan för visst material eller en viss person. Om det inte finns ett formulär för detta ändamål, kan du använda responsformuläret i söktjänsten.
  </p>
  <p>Om det finns personuppgifter som till exempel behöver rättas eller raderas i användarkommentarer om material i Finna-söktjänsten, kan begäran lämnas via formuläret i samband med kommentarerna.
  </p>
  <?php if ($template = $this->content()->findTemplateForLng('content/Additions/privacyAdditions')): ?>
    <?=$this->render($template)?>
  <?php endif; ?>
  <h2 id="cookies">Kakor</h2>
  <p>Med kakor avses uppgifter som servern sänder till den webbläsare du använder. I praktiken är det fråga om en liten datamängd, såsom en kort text.
  </p>
  <p>Kakor påverkar inte dataskyddet och de kan inte sprida virus eller skadeprogram.
  </p>
  <p>Kakor gör det lättare att använda Finna. Nödvändiga kakor säkerställer att Finna fungerar smidigt och gör webbplatsen mer användarvänlig. Information som samlas in med hjälp av statistikkakor används för att utveckla tjänsten.
  </p>
  <p>Användaren kan avstå från att använda icke-nödvändiga kakor genom att redigera inställningarna för kakor. Om du ändrar dig kan du redigera samtycket via länken ”Inställningar för kakor” nedtill på sidan eller via knappen nedan.
  </p>
  <?php if ($this->cookieConsent()->isEnabled()): ?>
    <h3>Kakinställningar</h3>
    <?php if ($consent = $this->cookieConsent()->getConsentInformation()): ?>
      <p>Dina kakinställningar:</p>
      <ul>
        <li>Verksamhetsområde: <?=$this->escapeHtml($consent['domain'] . ('/' !== $consent['path'] ? $consent['path'] : ''))?></li>
        <li>Tillstånd: Tillåt (<?=implode(', ', array_map([$this, 'escapeHtml'], $consent['categoriesTranslated']))?>)</li>
        <li>Samtyckes-ID: <?=$this->escapeHtml($consent['consentId'])?>
        <li>Samtyckesdatum: <?=$this->escapeHtml($consent['lastConsentDateTime'])?>
      </ul>
    <?php else: ?>
      <p>Du har inte gett ditt samtycke.</p>
    <?php endif; ?>
    <p>
      <a class="btn btn-default" href="#" data-cc="show-preferencesModal" aria-haspopup="dialog"><?=$this->transEsc('Cookie Settings')?></a>
    </p>
  <?php endif; ?>
</div>
<!-- END of: finna - content/privacy_sv.phtml -->
