<!-- START of: finna - content/register_details_sv.phtml -->
<?php $this->headTitle($this->translate('Register Details'));
$this->content()->setHeading($this->translate('Register Details')); ?>

<div class="page-content">
  <h3>1a. Registeransvarig</h3>
  <p>Nationalbiblioteket
    <br>PB 15 (Unionsgatan 36)
    <br>00014 Helsingfors universitet
    <br>Telefon: 02941 911
  </p>

  <h3>1b. Uppgiftsskyddsombud</h3>
  <p>Helsingfors universitets dataskyddsombud når du på adressen
    <br>tietosuoja(at)helsinki.fi
  </p>

  <h3>2. Kontaktuppgifter vid frågor om behandlingen av uppgifter</h3>
  <p>finna-palaute(at)helsinki.fi</p>

  <h3>3. Registrets namn</h3>
  <p>Finna-tjänstens register över användaruppgifter</p>

  <h3>4. Ändamålet med hanteringen av personuppgifter och grund för hanteringen</h3>
  <p>Personuppgifterna hanteras för att upprätthålla kunduppgifternas entydighet och identifiera användarna som loggar in på Finna-tjänsten. Personuppgifterna hanteras också i syfte att erbjuda användarna kundfunktioner och individualiserade tjänster med hjälp av Finna. Ett exempel på en individualiserad tjänst är nyhetsvakten, genom vilken användaren får information om nya referenser i söket per e-post. Uppgifterna hanteras för produktionen av tjänsten vid Nationalbiblioteket (registeransvarig) och CSC – IT-centret för vetenskap (uppgiftshanterare). De tekniska logguppgifterna för webbplatsens datatrafik behandlas även av Nationalbibliotekets avtalspartner Cloudflare Inc.</p>
  <p>Därtill hanteras användarnas personuppgifter för att följa upp tjänstens användning med ett analyssystem (Matomo), om användaren har gett sitt samtycke till detta. Systemet som används för användaranalyserna är konfigurerat så att användarens IP-adress anonymiseras. Analyssystemet används på servern vid CSC – IT-centret för vetenskap.</p>
  <p>När användaren besöker denna webbtjänst sparas informationen om händelsen (bl.a. IP-adressen) tillfälligt för hantering.</p>
  <p>Grunden för hanteringen är den registeransvarigas berättigade intresse och den registrerades samtycke (de personuppgifter som behandlas i analyssystemet).</p>

  <h3>5. Uppgifter i registret</h3>
  <h4>Användarens basuppgifter</h4>
  <ul class="list-bullets">
    <li>Användarnamn</li>
    <li>Användarspråk</li>
    <li>Namn</li>
    <li>Relation till läroanstalten eller organisationen</li>
    <li>E-postadress</li>
    <li>Bibliotekskortens uppgifter</li>
  </ul>
  <h4>Uppgifter som sparas för individualiserade funktioner</h4>
  <ul class="list-bullets">
    <li>Användarens personliga inställningar</li>
    <li>Favoriter</li>
    <li>Taggar</li>
    <li>Kommentarer</li>
    <li>Recensioner</li>
    <li>Reserveringar</li>
    <li>Lån</li>
    <li>Avgifter</li>
    <li>Sparade sökningar</li>
    <li>Material som sparats i favoriter</li>
  </ul>
  <h4>Uppgifter som sparas i analyssystemet för analys av användningen</h4>
  <ul class="list-bullets">
    <li>Anonymiserad IP-adress</li>
    <li>Webbläsarens typ och version</li>
    <li>Webbläsarens språkversion</li>
    <li>Operativsystem</li>
    <li>Enhetens märke, typ och modell</li>
    <li>Skärmtyp</li>
    <li>Insticksprogram</li>
    <li>URL-referens (senast besökt sida)</li>
    <li>Sidladdningar</li>
    <li>Klickningar</li>
    <li>Land, region och stad som begäran skickades från</li>
    <li>Sökord</li>
    <li>Använda filter (facetter)</li>
    <li>Sökningens typ och mål (Solr, CDI, EDS, Summon)</li>
    <li>Besökta posters format</li>
    <li>Besökta posters källa</li>
    <li>Är den besökta posten tillgänglig på nätet</li>
  </ul>
  <h4>Övriga uppgifter</h4>
  <ul class="list-bullets">
    <li>Uppgifter som sparas i cacheminnet och är nödvändiga för användningen av webbtjänsten</li>
    <li>Den platsinformation som kunden har delat eller angett</li>
  </ul>

  <h3>6. Lagenliga informationskällor</h3>
  <p>Personuppgifterna inhämtas från kundregistren för användarnas hemorganisationer eller användaren sparar själv sina uppgifter i Finna-tjänsten. Uppgifterna för individualiserade funktioner sparar användaren själv.</p>
  <p>I sökningar i Finna Street används platsinformation som sökvillkor. Denna platsinformation kan anges frivilligt eller användaren kan dela sin egen plats. Det är frivilligt att dela sin egen plats och användarens platsinformation behandlas inte utan en uttrycklig begäran av användaren.  Användaren kan också spara sökvillkoren.</p>

  <h3>7. Hantering och skydd av känsliga personuppgifter</h3>
  <p>Känsliga personuppgifter behandlas inte i Finna-tjänsten.</p>

  <h3>8. Personuppgifternas förvaringstid och radering av onödiga personuppgifter</h3>
  <p>Användarens personuppgifter sparas i Finna-tjänsten tills det har gått 18 månader från senaste inloggning eller användaren avslutar sitt konto.</p>

  <h3>9. Automatiskt beslutsfattande och profilering</h3>
  <p>Tjänsten innehåller inte automatiserat beslutsfattande eller profilering i samband med personuppgifterna.</p>

  <h3>10. Lagenlig överföring av uppgifter</h3>
  <p>Tjänsten hanterar uppgifter som överförs vid användning av bibliotekssystemets tjänstegränssnitt. Uppgifterna behandlas vid utförande av och bläddring i lån, förnyelser, reserveringar och avgifter. Personuppgifterna förmedlas till bibliotekssystemet, där bibliotekssystemets administratör ansvarar för behandlingen av dem.</p>
  <p>Anonymiserade analysdata från Finna-söktjänster som bibliotek, arkiv eller museer själva administrerar kan överlämnas till den organisation som ansvarar för administrationen.</p>

  <h3>11. Överföring av uppgifter utanför EU eller EES</h3>
  <p>De tjänster som erbjuds av avtalspartnern Cloudflare Inc. lagrar tekniska logguppgifter för Finna-webbplatsers datatrafik. Nationalbiblioteket använder Cloudflares tjänster för att säkerställa webbtjänsternas funktionsförmåga. Cloudflare behandlar datauppgifter inom EES-området och i USA. Grunden för överföringen av personuppgifter är EU-kommissionens godkända standardavtalsklausuler. Mera information on Cloudflares dataskydd finns på <a href="https://www.cloudflare.com/trust-hub/gdpr/" target="_blank">företagets egna webbsidor (på engelska)</a>.</p>
  <p>I övrigt överförs inga personuppgifter utanför EU eller EES.</p>

  <h3>12. Dataskyddsprinciper</h3>
  <p>Uppgifterna sparas enbart i elektroniskt format. Endast systemets administratörer har åtkomst till uppgifterna. Administratörerna identifieras med användarnamn och lösenord. </p>

  <h3>13. Rätt till insyn</h3>
  <p>För att kontrollera vilka personuppgifter om användaren tjänsten har insamlat, ska användaren kontakta tjänstens administratör Nationalbiblioteket på Finna.fi-webbplatsens blankett för feedback <a href="https://finna.fi/Feedback/Home">https://finna.fi/Feedback/Home</a>.</p>

  <h3>14. Rätt att kräva korrigering eller radering av uppgifter</h3>
  <p>Användaren kan när som helst radera sina uppgifter från Finna genom att avsluta sitt konto. Om det finns fel i personuppgifterna som överförts från användarens hemorganisation, ska användaren kontakta sin hemorganisation.  Vid behov kan användaren kontakta tjänstens administratör Nationalbiblioteket på Finna.fi-webbplatsens blankett för feedback <a href="https://finna.fi/Feedback/Home">https://finna.fi/Feedback/Home</a>.</p>

  <h3>15. Övriga rättigheter som gäller hanteringen av personuppgifter</h3>
  <p>Användaren har rätt att be dataombudsmannen bedöma om tjänstens funktioner är lagenliga (tietosuoja@om.fi).</p>
</div>
<!-- END of: finna - content/register_details_sv.phtml -->
