<!-- START of: finna - content/terms_sv.phtml -->
<?php $this->headTitle($this->translate('Terms')); $this->content()->setHeading($this->translate('Terms')); ?>

<div class="page-content">
  <h3>Villkor för användning av material</h3>
  <ul class="list-bullets">
    <li><strong>Digitalt material:</strong> Användningsrättigheterna för digitala bilder och annat material som finns i Finna varierar. Kontrollera informationen om användarrättigheterna som finns i samband med materialet och följ de givna anvisningarna. Om du använder materialet offentligt, ska du i regel ange upphovsman och källa.<br><br>
    <div class="example-image-area">
      <img src="<?=$this->imageLink('terms_example_sv.png')?>" alt="Example" />
      <p><small>Bild: Exempel på länk till kontaktformuläret på en materialsida i Finna. På bilden syns också länken till organisationens egen sida i Finna.</small></p>
    </div>
    Om det inte finns någon information om användarrättigheter eller om du är osäker på vilka rättigheter som gäller materialet, kontakta organisationen som ansvarar för materialet. Det går att göra via kontaktformuläret som finns vid respektive material på webbplatsen Finna.fi.<br><br>

    På organisationernas sidor i Finna finns information om rättigheter och begränsningar för materialanvändningen samt kontaktuppgifter för att få närmare information. Du kommer till organisationernas sidor t.ex. via
    delen <a href="https://finna.fi/Content/organisations?lng=sv" target="_blank">Organisationer som medverkar i Finna.</a><br><br>

    Det flesta omslagsbilder som visas i Finna är skyddade enligt lagen om upphovsrätt och användning av dem måste avtalas separat med förlaget eller materialets förmedlare.<br><br>
    </li>
    <li><strong>Metadata:</strong> Metadata som ges i samband med sökresultaten på <a href="https://finna.fi/?lng=sv" target="_blank">Finna.fi</a> kan i regel användas fritt. Undantag är sammandrag, böckers baksidestexter och metadata som producerats av Finnas användare, vilka kan omfattas av en tredje parts upphovsrätt. Metadata på Finnas övriga användargränssnitt och e-resurser kan ha användningsbegränsningar.
    </li>
  </ul>

  <p>Geokodningen av materialet har gjorts med öppna data i OpenStreetMap som har licens från <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">Open Data Commons Open Database</a>.
  </p>

  <h3>Allmänna användarvillkor</h3>
  <p>
    Det är förbjudet att använda tjänsten eller delar av den till sådana användningssyften som avviker från sedvanliga användningssyften.
    Delar av tjänsten som kräver inloggning får inte nyttjas med automatiska åtgärder (inklusive "robot", "spider", "scraper" och "offline reader" programvara).
  </p>
  <p>
    Vi förbehåller rätten att begränsa tjänstens tillgänglighet till exempel för att säkerställa underhållet, ändringsarbeten eller tjänstens funktion.
  </p>
</div>
<!-- END of: finna - content/terms_sv.phtml -->
