<!-- START of: finna - content/terms_fi.phtml -->
<?php $this->headTitle($this->translate('Terms')); $this->content()->setHeading($this->translate('Terms')); ?>

<div class="page-content">
  <h3>Aineistojen käyttöä koskevat ehdot</h3>
  <ul class="list-bullets">
    <li><strong>Digitaaliset aineistot:</strong> Finnasta löytyvien digitaalisten kuvien ja muiden aineistojen käyttöoikeudet vaihtelevat. Tarkista kyseisen aineiston yhteydestä käyttöoikeustieto ja noudata ilmoitettuja käyttöehtoja. Jos käytät aineistoa julkisesti, tekijä ja lähde on yleensä mainittava.<br><br>
    <div class="example-image-area">
      <img src="<?=$this->imageLink('terms_example_fi.png')?>" alt="Example" />
      <p><small>Kuva: Esimerkkikuva yhteydenottolomakkeeseen johtavasta painikkeesta Finnan aineistosivulla. Kuvassa näkyy myös linkki kyseisen organisaation organisaatiokohtaiselle sivulle.</small></p>
    </div>
    Jos tieto käyttöoikeuksista puuttuu, tai olet epävarma aineistoon liittyvistä käyttöoikeuksista, ota yhteys organisaatioon, joka vastaa aineistosta. Aineiston tarjoajan tavoittaminen onnistuu Finna.fi-sivustolla kunkin aineiston yhteydestä löytyvällä Ota yhteyttä -lomakkeella.<br><br>

    Finnan organisaatiokohtaisilla sivuilla on tietoa käyttöoikeuksista ja -rajoituksista sekä yhteystiedot lisätietojen saamiseksi. Organisaatiokohtaisille sivuille pääset esim. <a href="https://finna.fi/Content/organisations?lng=fi" target="_blank">Osallistuvat organisaatiot</a> -osion kautta.<br><br>

    Useimmat Finnassa näkyvät kansikuvat ovat tekijänoikeuslain alaista aineistoa, jonka käyttämisestä on sovittava erikseen esimerkiksi kustantajan tai aineiston välittäjän kanssa.<br><br>

    </li>
    <li><strong>Kuvailutiedot:</strong> <a href="https://finna.fi/?lng=fi" target="_blank">Finna.fi</a> -käyttöliittymän hakutulosten yhteydessä esitettäviä aineistojen kuvailutietoja voi pääsääntöisesti käyttää vapaasti. Poikkeuksen muodostavat kuvailutietoihin sisältyvät tiivistelmätekstit, kirjojen takakansitekstit ja Finnan käyttäjien tuottamat kuvailutiedot, joihin voi kohdistua kolmansien osapuolten tekijänoikeuksia. Muiden Finna-käyttöliittymien ja -verkkokirjastojen kuvailutietoihin voi liittyä käyttörajoituksia.
    </li>
  </ul>

  <p>Aineiston geokoodauksessa on käytetty OpenStreetMapin avointa dataa, joka on lisensoitu <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">Open Data Commons Open Database</a> -lisenssillä.
  </p>

  <h3>Palvelun käyttöä koskevat yleiset ehdot</h3>
  <p>
    Palvelua tai sen osia ei saa käyttää tavanomaisesta poikkeaviin käyttötarkoituksiin.
    Palvelun kirjautumista edellyttävien toimintojen automaattinen käyttäminen (mukaan lukien "robot-", "spider-", "scraper-" ja "offline reader-" ohjelmistot) on kielletty.
  </p>
  <p>
    Varaamme oikeuden rajata palvelun saatavuutta esimerkiksi ylläpidon, muutostöiden tai palvelun toiminnan turvaamiseksi.
  </p>
</div>
<!-- END of: finna - content/terms_fi.phtml -->
