<!-- START of: finna - content/terms_sv.phtml -->
<? $this->headTitle($this->translate('Terms')); $this->content()->setHeading($this->translate('Terms')); ?>

<div class="page-content">
  <p>För användningen av materialet gäller följande villkor:
  </p>
  <ul class="list-bullets">
    <li><strong id="image_rights">Bilder:</strong> I Finna kan det finnas bilder av t.ex. museiföremål, konstverk eller fotografier. Om du vill publicera en sådan bild eller använda bilden i offentligheten måste du följa de användningsvillkor som anges. Om du använder en bild offentligt, bör du nämna upphovsman och källa. Om informationen om användningsrättigheter saknas eller om du är osäker på om du har rätt att använda en bild, ska du kontakta organisationen som har gett tillgång till materialet via Finna. Om du vill använda pärmbilden till en bok, ska du skicka en förfrågan med Finnas <a href="<?=$this->url('feedback-home')?>">allmänna responsblanketten</a>.
    </li>
    <li><strong>Digitaliserat material:</strong> Finna ger länken till den organisation som förvaltar det digitaliserade materialet. Materialet på organisationens webbplats kan omfattas av rättigheter eller begränsningar som regleras i lag eller avtal. Information om rättigheterna och begränsningarna finns på den förvaltande organisationens webbplats.
    </li>
    <li><strong>Metadata:</strong> I regel kan metadata i anknytning till sökresultat användas fritt. Undantag är sammandrag och bakpärmstexter till böcker som ingår i metadata och metadata som producerats av Finnas användare, vilka kan omfattas av en tredje parts upphovsrätt.
    </li>
  </ul>

  <p>Geokodningen av materialet har gjorts med öppen data i OpenStreetMap, licensierad med <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">Open Data Commons Open Database</a> license.
  </p>

</div>
<!-- END of: finna - content/terms_sv.phtml -->
