<!-- START of: finna - content/terms_en-gb.phtml -->
<?php $this->headTitle($this->translate('Terms')); $this->content()->setHeading($this->translate('Terms')); ?>

<div class="page-content">
  <h3>Terms governing the use of materials</h3>
  <ul class="list-bullets">
    <li><strong>Digital material:</strong> Permission to use digital photographs and other materials on Finna vary. Please check the terms of use for the particular item you are interested in and follow the terms provided. If you are using the item publically, the author and source must generally be mentioned.<br><br>
    <div class="example-image-area">
      <img src="<?=$this->imageLink('terms_example_en-gb.png')?>" alt="Example" />
      <p><small>Screenshot: Here’s a sample screenshot of the contact button you will find on the Finna page displaying a particular item. In the screenshot you can also see a link to the organisation-specific page of the responsible organisation.</small></p>
    </div>
    If there is no information about the terms of use or if you are unsure about how particular items can be used, please contact the responsible organisation. You can contact the organisation providing the item by going to the contact form that can be found for each item on the Finna.fi website.<br><br>

    The organisation-specific pages on Finna provide information about terms of use as well as contact details if you need additional information. You can, for example, navigate to the organisation-specific pages via the <a href="https://finna.fi/Content/organisations?lng=en-gb" target="_blank">Participating organisations</a> section.<br><br>

    Many of the cover photographs shown on Finna are protected by copyright law, and arrangements for their use must be made separately, for example with the publisher or the party distributing the item(s).<br><br>
    </li>
    <li><strong>Information about material descriptions:</strong> As a general rule, you can freely use the descriptions about materials that are displayed in your search results on <a href="https://finna.fi/?lng=en-gb" target="_blank">Finna.fi</a>. There are a few exceptions: abstracts included in descriptions, back cover texts for books, and descriptions produced by Finna users, which may be under third party copyright. Restrictions on the use of descriptions in other Finna user interfaces and web libraries may apply.
    </li>
  </ul>

  <p>OpenStreetMap open data has been used to geocode materials and is licensed through the <a href="http://opendatacommons.org/licenses/odbl/" target="_blank">Open Data Commons Open Database License</a>.
  </p>

  <h3>General terms governing the use of the service</h3>
  <p>
    The service or any of its parts may not be used for any purposes out of the ordinary.
    It is forbidden to use any automated methods (including "robot", "spider", "scraper" and "offline reader" software) to access functions that require the user to log in to the service.
  </p>
  <p>
    We reserve the right to restrict access to the service for example to secure the maintenance, modification work or functioning of the service.
  </p>
</div>
<!-- END of: finna - content/terms_en-gb.phtml -->
