<? $this->headTitle($this->title) ?>
<div class="alignleft">
  <h3><?=$this->transEsc($this->title) ?></h3>

  <?=$this->flashmessages();?>

  <div id="popupDetails" class="confirmDialog">
    <form class="pull-left flip" action="<?=$this->escapeHtmlAttr($this->confirm)?>" method="post">
      <? if (isset($this->extras)): ?>
        <? foreach ($this->extras as $extra=>$value): ?>
          <? if (is_array($value)): ?>
            <? foreach ($value as $current): ?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($extra) ?>[]" value="<?=$this->escapeHtmlAttr($current) ?>" />
            <? endforeach; ?>
          <? else: ?>
            <input type="hidden" name="<?=$this->escapeHtmlAttr($extra) ?>" value="<?=$this->escapeHtmlAttr($value) ?>" />
          <? endif; ?>
        <? endforeach; ?>
      <? endif;?>
      <input class="btn btn-primary" type="submit" name="confirm" value="<?=$this->transEsc('confirm_dialog_yes') ?>" />
    </form>
    <form action="<?=$this->escapeHtmlAttr($this->cancel) ?>" method="post">
      <input class="btn btn-default" type="submit" name="cancel" value="<?=$this->transEsc('confirm_dialog_no') ?>" />
    </form>
    <div class="clearer"></div>
  </div>
</div>
