<?php
  $searchBackendId = $this->driver->getSearchBackendIdentifier();
  $searchRoute = $this->searchOptions($searchBackendId)->getSearchAction();
  if ($searchRoute === 'search-results') { // override search-results with author module
    $searchRoute = 'author-home';
    $query = ['author' => $this->lookfor];
  } else {
    $query = ['lookfor' => '"' . $this->lookfor . '"', 'type' => 'Author'];
  }
  if ($limit = $this->searchMemory()->getLastLimit($searchBackendId)) {
    $query['limit'] = $limit;
  }
  echo $this->url($searchRoute, [], compact('query'));
