<?php
  $versions = $this->driver->tryMethod('getOtherVersionCount');
  if (!$versions) {
    return;
  }
  if (isset($this->tabs['Versions'])) {
    $url = !empty($this->full)
      ? ($this->recordLinker()->getTabUrl($this->driver, 'Versions', [], ['query' => ['sid' => $this->searchId]]) . '#tabnav')
      : '#versions';
    $translationKey = 'other_versions_link';
  } else {
    $url = $this->recordLinker()->getVersionsSearchUrl($this->driver);
    $translationKey = 'other_versions_search_link';
    // Search results include this record, so increase the count
    $versions++;
  }
?>
<div class="record-versions">
  <a class="icon-link" href="<?=$this->escapeHtmlAttr($url)?>">
    <?=$this->icon('more', 'icon-link__icon') ?>
    <span class="icon-link__label"><?=$this->transEsc($translationKey, ['%%count%%' => $versions])?></span>
  </a>
</div>
