<?php $this->headTitle($this->translate('Critical Issue: Insecure database settings')) ?>

<h2>Critical Issue: Insecure database settings</h2>

<div class="alert alert-danger">
	Insecure settings and/or data have been detected in your user database.
</div>

<p><b>STRONGLY RECOMMENDED:</b> You can fix the problem by visiting the <a href="<?=$this->url('install-fixsecurity')?>">Fix Security</a> page. You should return to the Upgrade page after completing this task.</p>

<p>Alternatively, you can choose to <a class="btn btn-default" href="<?=$this->url('upgrade-criticalfixinsecuredatabase')?>?ignore=true">ignore the problem</a>.</p>

