<?
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="'.$this->url('upgrade-home').'">'.$this->transEsc('Upgrade').'</a></li> <li class="active">' . $this->transEsc('Upgrade VuFind') . '</li>';
?>
<h2><?=$this->transEsc('Upgrade VuFind')?></h2>
<?=$this->flashmessages()?>

<p>Due to a bug in earlier versions of VuFind, you have some duplicate tags
in your database.  It is recommended that you fix these.  Click Submit to proceed.</p>

<p>If you do not wish to fix the problem at this time, click the Skip button.</p>

<p>See <a target="_jira" href="http://vufind.org/jira/browse/VUFIND-805">http://vufind.org/jira/browse/VUFIND-805</a> for more details.</p>

<br />

<form method="post" action="<?=$this->url('upgrade-fixduplicatetags')?>">
  <input type="submit" name="submit" value="<?=$this->transEsc('Submit') ?>" /><br /><br />
  <input type="submit" name="skip" value="<?=$this->transEsc('skip_step') ?>." onclick="return confirm('<?=$this->transEsc('skip_confirm') ?>');"/>
</form>