<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<?php if (!$sessionInitiator): // display default login form if no login URL provided ?>
  <form method="post" action="<?=$this->url('myresearch-home')?>" name="loginForm" class="form-login">
    <?=$this->auth()->getLoginFields()?>
    <?php if ($account->supportsPersistentLogin()) : ?>
      <div class="form-group">
        <label>
          <input type="checkbox" name="remember_me"<?=$this->request->get('remember_me') ? ' checked' : ''?>>
          <?=$this->transEsc('remember_me', ['%%days%%' => $account->getPersistentLoginLifetime()])?>
        </label>
      </div>
    <?php endif; ?>
    <input type="hidden" name="auth_method" value="<?=$this->escapeHtmlAttr($account->getAuthMethod())?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>">
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEscAttr('Login')?>">
      <?php if ($account->supportsCreation()): ?>
        <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
      <?php endif; ?>
      <?php if ($account->supportsRecovery()): ?>
        <a class="btn btn-link recover-account-link" href="<?=$this->url('myresearch-recover') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Forgot Password')?></a>
      <?php endif; ?>
    </div>
  </form>
<?php else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" class="btn btn-link" data-lightbox-ignore><?=$this->transEsc('Institutional Login')?></a>
<?php endif; ?>
