<?php if ('' !== ($username = $this->recoveryData['username'] ?? '')): ?>
  <div class="form-group">
    <label class="form-label"><?=$this->transEsc('Username') ?>:</label>
    <p class="form-control-static"><?=$this->escapeHtml($username) ?></p>
  </div>
<?php endif; ?>
<div class="form-group">
  <label class="form-label" for="password"><?=$this->transEsc('new_password') ?>:</label>
  <?php
    $attrs = $this->htmlAttributes($this->passwordPolicy['inputAttrs'] ?? []);
    $attrs->merge(['id' => 'password', 'type' => 'password', 'name' => 'password', 'class' => 'form-control', 'autocomplete' => 'new-password']);
  ?>
  <input<?=$attrs?> required>
  <?php if ($hint = $this->passwordPolicy['hint'] ?? null): ?>
    <div class="help-block"><?=$this->transEsc($hint) ?></div>
  <?php endif; ?>
</div>
<div class="form-group">
  <label class="form-label" for="password2"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <input type="password" name="password2" id="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>" autocomplete="new-password">
</div>
