<div data-role="fieldcontain" class="ui-field-contain ui-body ui-br">
  <? if (isset($this->username)): ?>
    <label for="username" class="ui-input-text"><?=$this->transEsc('Username') ?>:</label>
    <input type="text" name="username" id="username" value="<?=$this->username ?>" disabled class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset"/><br/>
  <? endif; ?>
  <? if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
    <label for="oldpwd" class="ui-input-text"><?=$this->transEsc('old_password') ?>:</label>
    <input type="password" name="oldpwd" id="oldpwd" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset"/><br/>
  <? endif; ?>
  <label for="password" class="ui-input-text"><?=$this->transEsc('new_password') ?>:</label>
  <input type="password" name="password" id="password" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset"/><br/>
  <label for="password2" class="ui-input-text"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <input type="password" name="password2" id="password2" class="ui-input-text ui-body-c ui-corner-all ui-shadow-inset"/><br/>
</div>