<div class="ui-grid-b">
  <div class="ui-block-a"><label><?=$this->transEsc('recovery_by_username') ?>:</label></div>
  <div class="ui-block-b"><input type="text" name="username" style="margin-top:.5em;height:28px"/></div>
  <div class="ui-block-c"><input type="submit" name="submit" value="<?=$this->transEsc('Submit') ?>"/></div>
</div>
<div class="ui-grid-b">
  <div class="ui-block-a"><label><?=$this->transEsc('recovery_by_email') ?>:</label></div>
  <div class="ui-block-b"><input type="email" name="email" style="margin-top:.5em;height:28px"/></div>
  <div class="ui-block-c"><input type="submit" name="submit" value="<?=$this->transEsc('Submit') ?>"/></div>
</div>