<h1>Na co se to dívám?</h1>

<p>To co vidíte je <a href="http://www.cs.umd.edu/hcil/treemap/">stromová mapa</a>, typ vizuálního zobrazení běžně používaného pro data rozdělená do hierarchických kategorií.</p>

<h1>Co mi toto zobrazení může sdělit?</h1>

<p>Tato "mapa" vám může pomoci rozpoznat jak jsou knihy a další dokumenty odpovídající vašemu hledání rozděleny napříč určitými tématy (například podle signatur) a která témata jsou daným výsledkem pokryta.</p>

<p>Poznámka: většina položek v katalogu má pravděpodobně více témat a celkový počet pokrytých témat může být i větší než počet výsledků.
</p>

<h1>Jak s tímto zobrazením zacházet?</h1>

<p>Kliknutím na širší téma se "mapa" zaměří pouze na tuto oblast a zobrazí se témata této oblasti. Na tato témata je možné dále kliknout pro zobrazení konkrétních položek týkajících se daného tématu. Tento postup můžete kombinovat použitím upřesnění po levé straně jako u běžného hledání.</p>

<p>Pokud některý popisný text nevidíte celý, stačí najet myší na daný obdélník a text se zobrazí.</p>
