<?
    // Set page title.
    $this->headTitle($this->translate('auto_configure_title'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url(array('action' => 'Home')) .'">' . $this->transEsc('auto_configure_title') . '</a>';
?>
<h1><?=$this->transEsc('auto_configure_title')?></h1>

<?=$this->flashmessages()?>

<? if ($this->problems == 0): ?><p><?=$this->transEsc('No dependency problems found') ?>.</p><? endif; ?>