<!-- START of: finna - feedcontent/content.phtml -->
<?php
  $this->headScript()->appendFile('finna-content-feed.js');
  $this->headTitle($this->translate(''));
  $this->content()->setHeading($this->translate(''));
  $this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
     'content/header.phtml', ['heading' => $this->content()->getHeading()]
  );
  $this->jsTranslations()->addStrings([
    'rss_article_not_found' => 'rss_article_not_found',
    'rss_article_channel_link' => 'rss_article_channel_link'
  ]);

  if ($this->modal) {
     $setupJS = <<<JS
$(document).ready(function() {
   finna.contentFeed.loadFeed($('#modal .feed-content'), true);
});
JS;
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $setupJS, 'SET');
  }
?>
<div>
  <div class="<?= $this->modal ? '' : 'page-content'?> feed-content" data-feed="<?=$this->escapeHtmlAttr($this->feed)?>" data-element="<?=$this->escapeHtmlAttr($this->element)?>" data-feed-url="<?=$this->escapeHtmlAttr($this->feedUrl)?>">

  <?php if ($this->modal): ?>
    <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
    <div class="holder"></div>
  </div>

  <?php else: ?>
    <div>
      <div class="mainbody left">
        <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
        <div class="holder"></div>
      </div>
    </div>
  </div>
  <div class="sidebar right">
    <div><h3 class="article-navigation-header"><?=$this->translate('content-feed-navigation')?></h3></div>
    <div class="article-navigation-wrapper"></div>
  </div>
  <?php endif; ?>

</div>
<!-- END of: finna - feedcontent/content.phtml -->
