<!-- START of: finna - feedcontent/linkedevents.phtml -->
<div class="linked-event-content">
   <span role="status" class="js-loader linked-events-page-spinner hidden">
      <?=$this->icon('spinner') ?><span class="visually-hidden"> <?=$this->transEsc('loading_ellipsis')?></span>
   </span>
   <div class="linked-events-left-col">
      <h2 class="linked-event-title"></h2>
      <span class="linked-event-info">
         <span class="linked-event-field hidden"><?=$this->icon('linked-event-date') ?> <span class="linked-event-startDate"></span><span class="linked-event-endDate hidden">&nbsp;&ndash;&nbsp;</span></span>
         <span class="linked-event-field hidden"><?=$this->icon('linked-event-time') ?> <span class="linked-event-startTime"></span><span class="linked-event-endTime hidden">&nbsp;&ndash;&nbsp;</span></span>
         <span class="linked-event-field hidden"> <span class="linked-event-price"></span></span>
         <span class="linked-event-field hidden"><?=$this->icon('linked-event-audience') ?> <span class="linked-event-audience"></span></span>
      </span>
      <img class="linked-event-image" alt="">
      <b><div class="linked-event-short_description"></div></b>
      <div class="linked-event-description"></div>
      <div class="linked-event-keywords"></div>
   </div>
   <div class="linked-events-right-col">
      <div id="openlayers-canvas" class="linked-events-map"></div>
      <div class="linked-event-map-info">
         <div class="linked-event-field hidden"><?=$this->icon('linked-event-location') ?> <span class="linked-event-location-info"></span></div>
         <div class="linked-event-field hidden"><?= $this->icon('linked-event-address') ?> <span class="linked-event-address"></span></div>
         <div class="linked-event-field hidden"><?= $this->icon('linked-event-home') ?> <a class="linked-event-providerLink"><?= $this->transEsc('linked_event_homepage');?></a></div>
         <div class="linked-event-field hidden"><?=$this->icon('linked-event-phone') ?> <a class="linked-event-phone"></a></div>
         <div class="linked-event-field hidden"><?=$this->icon('linked-event-email') ?> <a class="linked-event-email"></a></div>
         <div class="linked-event-field hidden"><?=$this->transEsc('Organizer'); ?>: <span class="linked-event-provider"></span></div>
      </div>
      <div class="related-events hidden"><h3><?= $this->transEsc('linked_event_related_events'); ?></h3></div>
   </div>
</div>
<?php
  $id = $this->event['id'];
  $setupJS = <<<JS
      $(document).ready(function() {
         finna.linkedEvents.getEventContent("$id");
      });
      JS;
    echo $this->assetManager()->outputInlineScriptString($setupJS);
?>
<!-- END of: finna - feedcontent/linkedevents.phtml -->
