<!-- START of: finna - RecordTab/map.phtml -->
<?
  $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/leaflet.js');
  echo $this->inlineScript();
?>

<div class="map-canvas"></div>

<script type="text/javascript">
$(document).ready(function() {
  var tileLayer = L.tileLayer('http://map-api.finna.fi/v1/rendered/{z}/{x}/{y}.png', {
    maxZoom: 18,
    tileSize: 256,
    attribution: 'Map data &copy; <a href="http://openstreetmap.org">OpenStreetMap</a> contributors, <a href="http://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>'
  });

  var drawnItems = new L.FeatureGroup();

  var markersData = <?=$this->tab->getMapMarkers() ?>;
  for (var i = 0; i < markersData.length; i++) {
    if (markersData[i].polygon) {
      L.polygon(markersData[i].polygon).addTo(drawnItems);
    } else if (markersData[i].multipolygon) {
      var multipolygon = markersData[i].multipolygon;
      L.multiPolygon(multipolygon).addTo(drawnItems);
    } else {
      var icon = L.divIcon({
        className: 'mapMarker',
        iconSize: null,
        html: '<div class="leaflet-marker-icon leaflet-zoom-animated leaflet-interactive" style="margin-left: -5px; margin-top: -17px; width: 24px; height: 24px;"><i class="fa fa-map-marker" style="position: relative; font-size: 20px;"></i></div>'
      });
      L.marker([markersData[i].lat, markersData[i].lon], {icon: icon}).addTo(drawnItems);
    }
  }
  var map = new L.Map($('.map-canvas').get(0), {
    layers: [tileLayer, drawnItems],
    center: drawnItems.getBounds().getCenter(),
    zoom: 5
  });
  var onLoad = function() {
    fitZoom = map.getBoundsZoom(drawnItems.getBounds());
    map.setZoom(fitZoom <= 9 ? fitZoom - 1 : 9);
    tileLayer.off('load', onLoad);
  };
  tileLayer.on('load', onLoad);
});
</script>
<!-- END of: finna - RecordTab/map.phtml -->
