<!-- START of: finna - RecordTab/staffviewarray.phtml -->
<? $rawFieldData = $this->driver->getRawData(); ?>
<? if (!empty($rawFieldData['fullrecord']) && strncmp($rawFieldData['fullrecord'], '<', 1) == 0): ?>
<pre id="record-data">
<?
  $dom = new DOMDocument('1.0');
  $dom->preserveWhiteSpace = false;
  $dom->formatOutput = true;
  if ($dom->loadXML($rawFieldData['fullrecord'])) {
    echo $this->escapeHtml($dom->saveXML());
    $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/highlight.pack.js');
    echo $this->inlineScript();
    $script = <<<JS
$(document).ready(function() {
  $('#record-data').each(function(i, block) {
    hljs.highlightBlock(block);
  });
});
JS;
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
  } else {
    echo $this->escapeHtml($rawFieldData['fullrecord']);
  }
?>
</pre>
<hr>
<? endif; ?>
<table class="citation table table-striped">
  <? foreach ($rawFieldData as $field => $values): ?>
    <tr>
      <th><?=$this->escapeHtml($field)?></th>
      <td>
        <? if (!is_array($values)) { $values = array($values); } ?>
        <? foreach ($values as $value): ?>
          <?=$this->escapeHtml(is_array($value) ? print_r($value, true) : $value)?><br />
        <? endforeach; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>
<!-- END of: finna - RecordTab/staffviewarray.phtml -->
