<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings($account);
    $offlineMode = $this->ils()->getOfflineMode();

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>
<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtml($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="info">
        <a href="<?=$this->currentPath()?>?login=true&catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="info">
        <?=$this->translate("hold_profile_html", array('%%url%%' => $this->currentPath() . '?catalogLogin=true'))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold', array($account)); if (!empty($holdingTitleHold)): ?>
    <a rel="external" class="holdPlace" href="<?=$this->recordLink()->getHoldUrl($holdingTitleHold, false)?>"><?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? foreach ($holdings as $location => $holding): ?>
<h4><?=$this->transEsc($location)?></h4>
<table class="holdings" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($location)?>">
  <? if (isset($holding['items'][0]['callnumber'])): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td><?=$this->escapeHtml($holding['items'][0]['callnumber'])?></td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['summary'])): ?>
  <tr>
    <th><?=$this->transEsc("Volume Holdings")?>: </th>
    <td>
      <? foreach ($holding['summary'] as $current): ?>
        <?=$this->escapeHtml($current)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? if (!empty($holding['notes'])): ?>
  <tr>
    <th><?=$this->transEsc("Notes")?>: </th>
    <td>
      <? foreach ($holding['notes'] as $data): ?>
        <?=$this->escapeHtml($data)?><br/>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? foreach ($holding['items'] as $row): ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr>
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
          <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?>
          <? elseif (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="unknown"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="available"><?=$this->transEsc("Available")?></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <br />
                <a rel="external" class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'], false)?>"><span><?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></span></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="checkedout"><?=$this->transEsc($row['status'])?></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?> <span class="statusExtra"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                <span class="statusExtra"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <br />
                <a rel="external" class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getHoldUrl($row['link'], false)?>"><span><?=$this->transEsc($check ? "Check Recall" : "Recall This")?></span></a>
              <? endif; ?>
            <? endif; ?>
          <? endif; ?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h4><?=$this->transEsc("Most Recent Received Issues")?></h4>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>