<?
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $holdings = $this->driver->getRealTimeHoldings();
    $offlineMode = $this->ils()->getOfflineMode();

    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_holdings_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>
<? if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings)) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <? if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <? if (!$user): ?>
      <div class="info">
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'Holdings')?>?login=true&amp;catalogLogin=true"><?=$this->transEsc("Login")?></a> <?=$this->transEsc("hold_login")?>
      </div>
    <? elseif (!$user->cat_username): ?>
      <div class="info">
        <?=str_replace('href="', 'rel="external" href="', $this->translate("hold_profile_html", array('%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings') . '?catalogLogin=true')))?>
      </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
    <a rel="external" class="holdPlace" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold, false)?>"><?=$this->transEsc('title_hold_place')?></a>
<? endif; ?>
<? foreach ($holdings as $holding): ?>
<h4>
  <? $locationText = $this->transEsc('location_' . $holding['location'], array(), $holding['location']); ?>
  <? if (isset($holding['locationhref']) && $holding['locationhref']): ?>
    <a href="<?=$holding['locationhref']?>" rel="external"><?=$locationText?></a>
  <? else: ?>
    <?=$locationText?>
  <? endif; ?>
</h4>
<table class="holdings" summary="<?=$this->transEsc('Holdings details from')?> <?=$this->transEsc($holding['location'])?>">
  <? $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
  <tr>
    <th><?=$this->transEsc("Call Number")?>: </th>
    <td>
      <? foreach ($callNos as $callNo): ?>
        <?=$this->escapeHtml($callNo)?><br />
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>
  <? foreach ($this->ils()->getHoldingsTextFieldNames() as $textField): ?>
    <? if (!empty($holding[$textField])): ?>
      <tr>
        <? // Translation for summary is a special case for backwards-compatibility ?>
        <th><?=$textField == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textField))?>: </th>
        <td>
          <? foreach ($holding[$textField] as $current): ?>
            <?=$this->escapeHtml($current)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? foreach ($holding['items'] as $row): ?>
    <? $check = (isset($row['check']) && $row['check']); ?>
    <? if (isset($row['barcode']) && $row['barcode'] != ""): ?>
      <tr>
        <th><?=$this->transEsc("Copy")?> <?=$this->escapeHtml($row['number'])?></th>
        <td>
          <? if ($row['reserve'] == "Y"): ?>
            <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
          <? endif; ?>
          <? if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
            <span class="unknown"><?=$this->transEsc("status_unknown_message")?></span>
          <? else: ?>
            <? if ($row['availability']): ?>
              <? /* Begin Available Items (Holds) */ ?>
               <span class="available"><?=$this->transEsc("Available")?></span>
              <? if (isset($row['link']) && $row['link']): ?>
                <br />
                <a rel="external" class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getRequestUrl($row['link'], false)?>"><span><?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></span></a>
              <? endif; ?>
            <? else: ?>
              <? /* Begin Unavailable Items (Recalls) */ ?>
              <span class="checkedout"><?=$this->transEsc($row['status'])?></span>
              <? if (isset($row['returnDate']) && $row['returnDate']): ?> <span class="statusExtra"><?=$this->escapeHtml($row['returnDate'])?></span><? endif; ?>
              <? if (isset($row['duedate']) && $row['duedate']): ?>
                <span class="statusExtra"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($row['duedate'])?></span>
              <? endif; ?>
              <? if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
                <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($row['requests_placed'])?></span>
              <? endif; ?>
              <? if (isset($row['link']) && $row['link']): ?>
                <br />
                <a rel="external" class="holdPlace<?=$check ? ' checkRequest' : ''?>" href="<?=$this->recordLink()->getRequestUrl($row['link'], false)?>"><span><?=$this->transEsc($check ? "Check Recall" : "Recall This")?></span></a>
              <? endif; ?>
            <? endif; ?>
          <? endif; ?>
        </td>
      </tr>
    <? endif; ?>
  <? endforeach; ?>
  <? if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <? foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>
<? endforeach; ?>

<? $history = $this->driver->getRealTimeHistory(); ?>
<? if (is_array($history) && !empty($history)): ?>
<h4><?=$this->transEsc("Most Recent Received Issues")?></h4>
<ul>
  <? foreach ($history as $row): ?>
    <li><?=$this->escapeHtml($row['issue'])?></li>
  <? endforeach; ?>
</ul>
<? endif; ?>