<!-- START of: finna - Helpers/authorizationNote.phtml -->
<div class="alert alert-info authorization-notification">
  <p><?= $this->translate('authorize_user_notification') ?></p>
  <? if (!$this->auth()->isLoggedIn()): ?>
  <p><a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a></p>
  <? endif ?>
</div>
<!-- END of: finna - Helpers/authorizationNote.phtml -->
