<!-- START of: finna - Helpers/streetsearch.phtml -->
<?
    $this->headScript()->appendFile('finna-street-search.js');
    $this->jsTranslations()->addStrings(
      [
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_checking_for_geolocation' => 'street_search_checking_for_geolocation',
        'street_search_geolocation_available' => 'street_search_geolocation_available',
        'street_search_geolocation_position_unavailable' => 'street_search_geolocation_position_unavailable',
        'street_search_geolocation_other_error' => 'street_search_geolocation_other_error',
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_timeout' => 'street_search_timeout',
        'street_search_no_streetname_found' => 'street_search_no_streetname_found',
        'street_search_reversegeocode_unavailable' => 'street_search_reversegeocode_unavailable',
        'street_search_searching_for' => 'street_search_searching_for',
        'street_search_coordinates_found' => 'street_search_coordinates_found',
        'street_search_coordinates_found_accuracy_bad' => 'street_search_coordinates_found_accuracy_bad'
      ]
    );
?>
<div class="street-search-button-area">
  <button class="btn btn-primary street-search-button"><?=$this->transEsc('street_search_button') ?></button>
  <div class="alert alert-info street-search-progress hidden">
    <div class="fa fa-spinner fa-spin"></div>
    <div class="infoBox">
      <div>
        <div class="info"></div>
        <button class="street-search-terminate"><?=$this->transEsc('street_search_abort') ?></button>
      </div>
    </div>
  </div>
</div>
<!-- END of: finna - Helpers/streetsearch.phtml -->
