<div class="panel panel-top panel-default tf-panel-home-2">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'browse']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/alphabet-communication-data-256798.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Browsing</h4>
            <!--<p>Untertitel</p>-->
        </div>
    </a>
</div>