<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Discover RelBib</h4>
        <p>
            <ul>
                <li>About RelBib</li>
                <li><a href="/?subpage=search_and_browse">Searching and browsing</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'features']) ?>">RelBib features</a></li>
                <li><a href="/relbib_docs/relbib_journals.pdf">RelBib list of journals</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'discover_A-Z']) ?>">RelBib A to Z</a></li>
            </ul>
        </p>
        <!--<a href="<?=$this->url('content-page', ['page' => 'discover']) ?>#anchor" class="btn btn-default" role="button">Mehr erfahren</a>-->
    </div>
</div>
