<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Discover RelBib</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => 'discover_search_browsing']) ?>">Searching and browsing</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'discover_features']) ?>">RelBib features</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'discover_my_relbib']) ?>">My RelBib</a></li>
                <li><a href="/relbib_docs/relbib_journals.pdf">RelBib list of journals</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'discover_A-Z']) ?>">RelBib A to Z</a></li>
            </ul>
        </p>
        <!--<a href="<?=$this->url('content-page', ['page' => 'discover']) ?>#anchor" class="btn btn-default" role="button">Mehr erfahren</a>-->
    </div>
</div>
