<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Discover RelBib</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#alerting">Alerting: notifications about new content</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#availability">Availability checking</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'search']) ?>#fulltext">Full Text Search</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#share_favorites">Sharing lists with other people</a></li>
                <li><a href="/relbib_docs/relbib_journals_en.pdf">RelBib list of journals</a></li>
            </ul>
        </p>
    </div>
</div>
