<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/printing-press.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>FID Services</h4>
        <p>
            <ul>
                <li>Specialized Information Service "Religious Studies"</li>
                <li>Information for authors, editors and publishers</li>
                <li>Cooperating partners</li>
                <li>Additional resouces</li>
                <li>Platform for journals</li>
                <li>Secondary publication service</li>
            </ul>
        </p>
    </div>
</div>
