<div class="col-xs-12 col-sm-3 panel panel-top panel-inverse">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/news.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Current topics in Religious Studies</h4>
        <p>
        <ul id="rss_preview">
            <li><a target="_blank" href="http://www.remid.de/blog/feed/"><img src="<?=$this->imageLink('rss/rss.png')?>" height="16"/></a> <a target="_blank" href="http://www.remid.de/blog/2018/05/interview-religionswissenschaftler-michael-blume-wird-antisemitismus-beauftragter-baden-wuerttembergs/">01.05. - Interview: Religionswissenschaftler...</a></li>
            <li><a target="_blank" href="https://marginalie.hypotheses.org/feed"><img src="<?=$this->imageLink('rss/marginalie.hypotheses.org.png')?>" height="16"/></a> <a target="_blank" href="https://marginalie.hypotheses.org/650">29.04. - Ein Kreuz für die CSU</a></li>
            <li><a target="_blank" href="https://religiousstudiesproject.com/feed/"><img src="<?=$this->imageLink('rss/rsp.ico')?>" height="16"/></a> <a target="_blank" href="https://religiousstudiesproject.com/podcast/why-do-we-believe-evolution-primates-and-the-human-niche/">23.04. - Why do we believe?...</a></li>
            <li><a target="_blank" href="http://www.remid.de/blog/feed/"><img src="<?=$this->imageLink('rss/rss.png')?>" height="16"/></a> <a target="_blank" href="http://www.remid.de/blog/2018/04/satanismus-in-der-religionswissenschaft-interview-mit-buchautor-joachim-schmidt/">06.04. - Satanismus in der Religionswissenschaft...</a></li>
        </ul>
        </p>
        <a href="#" class="btn btn-inverse" role="button">Read more</a>
    </div>
</div>
