<div class="col-xs-12 col-sm-3 panel panel-top panel-inverse">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/news.jpg') ?>" alt="" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Religionswissenschaft aktuell</h4>
        <p>[Projektziel: News aggregiert aus verschiedenen RWBlogs]</p>
        <a href="#" class="btn btn-inverse" role="button">Weiterlesen</a>
    </div>
</div>
