<div class="panel panel-top panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Self archiving service</h4>
            <!--<p>Einzelheiten zu KrimDok</p>-->
        </div>
    </a>
</div>