<?php
// Set up page title:
$this->headTitle($this->translate('PDASubscriptions'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('PDASubscriptions') . '</li>';

// Grab list object from search results (if applicable):
$list = isset($this->results) ? $this->results->getListObject() : null;
$recordTotal = isset($this->results) ? $this->results->getResultTotal() : 0;

// Convenience variable:
$account = $this->auth()->getManager();
$user = $this->auth()->isLoggedIn();
?>

<div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc("PDASubscriptions")?></h2>

    <?=$this->flashmessages()?>

    <?php if ($recordTotal > 0): ?>
        <div class="resulthead">
            <div class="pull-right flip">
                <?=$this->render('search/controls/sort.phtml')?>
            </div>
        </div>
        <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-myresearchbulk')?>" data-lightbox data-lightbox-onsubmit="bulkFormHandler">
            <?=$this->context($this)->renderInContext('myresearch/subscriptions-bulk-action-buttons.phtml', array('idPrefix' => '', 'list' => isset($list) ? $list : null, 'account' => $this->account))?>
            <?php foreach ($this->results->getResults() as $i=>$current): ?>
                <?=$this->record($current)->getPDASubscriptionListEntry($list, $user)?>
            <?php endforeach; ?>
        </form>
        <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $this->results))?>
    <?php else: ?>
        <p><?=$this->transEsc('You do not have any saved PDA resources')?></p>
    <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'pdasubscriptions'))?>
</div>
