<?php
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Template for use by the renderArray helper:
    $arrTemplate = '<tr><th>%%LABEL%%:</th><td> %%VALUE%%</td></tr>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
    <h2><?=$this->transEsc('Your Profile')?></h2>
    <?=$this->flashmessages();?>

    <form method="post" name="accountForm" id="accountForm" class="form-horizontal" data-toggle="validator" role="form">
        <?=$this->context($this)->renderInContext('Auth/Database/create.phtml', ['only_additional_information' => true]);?>

        <div id="account-actions">

          <!-- IxTheo: This submit button belongs to the accountForm template -->
          <input class="btn btn-primary" name="submit" value="<?=$this->transEscAttr('Save')?>" type="submit">

          <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
            <a class="btn btn-default" href="<?=$this->url('myresearch-changeemail') ?>">
              <i class="fa fa-fw fa-envelope" aria-hidden="true"></i> <?=$this->transEsc('Change Email Address') ?>
            </a>
          <?php endif; ?>

          <?php if ($this->auth()->getManager()->supportsPasswordChange()): ?>
            <a class="btn btn-default" href="<?=$this->url('myresearch-changepassword') ?>">
              <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
            </a>
          <?php endif; ?>

          <?php if ($this->accountDeletion): ?>
            <a class="btn btn-default" href="<?=$this->url('myresearch-deleteaccount') ?>" data-lightbox>
              <i class="fa fa-times"></i> <?=$this->transEsc('delete_account_title') ?>
            </a>
          <?php endif; ?>
        </div>
    </form>

  <?php if (is_array($this->profile)): ?>
    <h3><?=$this->transEsc('Library Catalog Profile')?></h3>
    <p>
      <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->user]); ?>
    </p>
    <table class="table table-striped">
      <?=$this->renderArray(
        $arrTemplate, $this->profile,
        [
          $this->transEsc('First Name') => 'firstname',
          $this->transEsc('Last Name') => 'lastname',
          $this->transEsc('Address') . ' 1' => 'address1',
          $this->transEsc('Address') . ' 2' => 'address2',
          $this->transEsc('Zip') => 'zip',
          $this->transEsc('City') => 'city',
          $this->transEsc('Country') => 'country',
          $this->transEsc('Phone Number') => 'phone',
          $this->transEsc('Mobile Number') => 'mobile_phone',
          $this->transEsc('Group') => 'group',
          $this->transEsc('Expires') => 'expiration_date'
        ]
      )?>
    </table>
  <?php elseif ('ils-none' !== $this->ils()->getOfflineMode() && $this->patronLoginView && !empty($this->patronLoginView->getTemplate())): ?>
    <?=$this->partial($this->patronLoginView);?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile'])?>
</div>
