<div class="panel-group" id="accordion">
  <?foreach ($this->subscription_bundles as $bundle): ?>
  <div class="panel panel-default">
    <div class="panel-heading">
    <?$bundle_id = $bundle->getUniqueID()?>
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#<?=$bundle_id?>">
        <?=$bundle->getTitle()?></a>
      </h4>
    </div>
    <div id="<?=$bundle_id?>" class="panel-collapse collapse">
      <div class="panel-body">
        <script type="text/javascript">
          $("#<?=$bundle_id?>").on("show.bs.collapse", function() {
            getSubscriptionBundleItems('<?=$bundle_id?>');
          });
        </script>
      </div>
    </div>
  </div>
  <?endforeach;?>
</div>


