<? foreach ($checkboxFilters as $current): ?>
  <a class="checkbox-filter<? if(!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<? endif; ?>" href="<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']);?>">
    <? if ($current['selected']): ?>
      <span class="sr-only"><?=$this->transEsc('clear_tag_filter') ?></span>
    <? endif; ?>
    <i class="<?=$current['selected'] ? 'fa fa-check-square' : 'far fa-square' ?>"></i>
    <?=$this->transEsc($current['desc']) ?>
  </a>
<? endforeach; ?>
