<div class="list-group filters">
  <div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div>
  <? foreach ($filterList as $field => $filters): ?>
    <? foreach ($filters as $i => $filter): ?>
      <?
        $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
        if ($index !== false) {
          unset($collapsedFacets[$index]); // Open if we have a match
        }
        if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->replaceTerm($filter['value'], '');
        } else {
          $removeLink = $this->currentPath() . $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
        }
        if ($filter['displayText'] == '[* TO *]') {
          $filter['displayText'] = $this->translate('filter_wildcard');
        }
      ?>
      <a class="list-group-item active" href="<?=$removeLink ?>" title="<?=$this->transEsc('clear_tag_filter') ?>">
        <span class="pull-right flip"><i class="fa fa-times" aria-hidden="true"></i></span>
        <? if ($filter['operator'] == 'NOT'): ?><?=$this->transEsc('NOT') ?><? endif; ?>
        <? if ($filter['operator'] == 'OR' && $i > 0): ?><?=$this->transEsc('OR') ?><? endif; ?>
        <?=$this->transEsc($field) ?>: <?=$this->escapeHtml($filter['displayText']) ?>
      </a>
    <? endforeach; ?>
  <? endforeach; ?>
</div>
