<?php
  $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');

  // We need to pass the current URL query to the Javascript; we use substr() to
  // strip off the leading ? character. The "suppress query" option is used for
  // special search types like course reserves / new items. The AJAX handler needs
  // the real Solr query in order to process facets correctly, so we need to
  // unsuppress it here.
  $querySuppressed = $this->results->getUrlQuery()->isQuerySuppressed();
  $urlQuery = substr($this->results->getUrlQuery()->setSuppressQuery(false)->getParams(false), 1);
  $this->results->getUrlQuery()->setSuppressQuery($querySuppressed); // restore original config
  // We also need to inform the helper about any special parameters used in place
  // of the suppressed query:
  $extraUrlFields = $this->results->getUrlQuery()->getParamsWithConfiguredDefaults();
?>
<?php if (!in_array($this->title, $this->collapsedFacets)): ?>
  <?php
    $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($this->title)}'), true);
});
JS;
  ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<?php else: ?>
  <?php
  $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($this->title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($this->title)}'), true);
});
JS;
  ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<?php endif; ?>
<?php
  // If we always use the lightbox, we don't want to turn on truncation.
  $facetLightbox = $this->options->getFacetListAction();
  $alwaysUseLightbox = ($this->showMoreInLightbox && $this->showMoreInLightbox !== 'more') && $facetLightbox;
  $truncateSettings = $alwaysUseLightbox ? false : [
    'rows' => $this->facets_before_more,
    'btn-class' => 'facet',
    'more-label' => $this->transEsc('more') . ' ...',
    'less-label' => $this->transEsc('less') . ' ...',
    'wrapper-class' => false,
    'wrapper-tagname' => 'div',
  ];
?>
<div<?php if ($truncateSettings): ?> class ="truncate-hierarchy" data-truncate="<?=$this->escapeHtml(json_encode($truncateSettings))?>"<?php endif; ?>>
<li id="facet_<?=$this->escapeHtml($this->title)?>" class="jstree-facet"
    data-source="<?=$this->escapeHtml($this->searchClassId)?>"
    data-facet="<?=$this->escapeHtmlAttr($this->title)?>"
    data-path="<?=$this->currentPath()?>"
    data-exclude="<?=$this->allowExclude?>"
    data-operator="<?=$this->recommend->getFacetOperator($this->title)?>"
    data-exclude-title="<?=$this->transEscAttr('exclude_facet')?>"
    data-sort="<?=$this->sortOptions ?? ''?>"
    data-query="<?=$this->escapeHtmlAttr($urlQuery)?>"
    data-query-suppressed="<?=$querySuppressed ? '1' : '0' ?>"
    data-extra-fields="<?=$this->escapeHtml(implode(',', $extraUrlFields))?>">
</li>
<?php /* LESS and SEE MORE links */ ?>
<?php if (isset($i) && $i >= 5): ?>
  <?php if ($this->showMoreInLightbox === 'more' && $facetLightbox = $options->getFacetListAction()): ?>
    <?php
      $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams() . '&amp;facet=' . $this->title . '&amp;facetop=' . $thisFacet['operator'] . '&amp;facetexclude=' . ($this->allowExclude ? 1 : 0);
      if (!empty($this->baseUriExtra)) {
        $moreUrl .= '&amp;baseUriExtra=' . urlencode($this->baseUriExtra);
      }
    ?>
    <a class="facet narrow-toggle all-facets" data-lightbox href="<?=$moreUrl ?>" rel="nofollow">
      <span class="text"><?=$this->transEsc('see all')?> ...</span>
    </a>
  <?php endif; ?>
<?php endif; ?>
