<? $this->headScript()->appendFile('collection_record.js'); ?>
<div class="media">
  <?
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('collection-info', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = $this->record($this->driver)->getPreviews();
  ?>
  <? if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>

      <? if ($preview): ?><?=$preview?><? endif; ?>
    </div>
  <? endif; ?>
  <div class="media-body">

    <h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->escapeHtml($summary)?></p>
    <? endif; ?>

    <? /* Display the lists that this record is saved to */ ?>
    <div class="savedLists" id="savedLists">
      <strong><?=$this->transEsc("Saved in")?>:</strong>
    </div>

    <a id="moreInfoToggle" href="#" class="hidden"><?=$this->transEsc('more_info_toggle')?></a>
    <?/* Display Main Details */?>
    <?
      $formatter = $this->recordDataFormatter();
      $fields = $formatter->getData($driver, $formatter->getDefaults('collection-info'));
    ?>
    <? if (!empty($fields)): ?>
      <table id="collectionInfo" class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
        <? foreach ($fields as $key => $current): ?>
          <tr><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
        <? endforeach; ?>
      </table>
    <? endif; ?>
    <?/* End Main Details */?>
  </div>
</div>
