<? $this->headScript()->appendFile('collection_record.js'); ?>
<div class="row">
  <? $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('collection-info', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <? if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? if($cover): ?>
        <?=$cover?>
      <? endif; ?>

      <? /* Display qrcode if appropriate: */ ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? if ($preview): ?><?=$preview?><? endif; ?>
  </div>

  <div class="col-sm-6">
  <? else: ?>
  <div class="col-sm-9">
  <? endif; ?>

    <h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <p><?=$this->escapeHtml($summary)?></p>
    <? endif; ?>

    <? /* Display the lists that this record is saved to */ ?>
    <div class="savedLists hidden alert alert-info" id="savedLists">
      <strong><?=$this->transEsc("Saved in")?>:</strong>
    </div>

    <a id="moreInfoToggle" href="#" class="hidden"><?=$this->transEsc('more_info_toggle')?></a>
    <?/* Display Main Details */?>
    <table id="collectionInfo" class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
      <? if (isset($authors['main']) && !empty($authors['main'])): ?>
      <tr>
        <th><?=$this->transEsc('Main Author')?>: </th>
        <td><a href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Author')?>: </th>
        <td><a href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></td>
      </tr>
      <? endif; ?>

      <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
      <tr>
        <th><?=$this->transEsc('Other Authors')?>: </th>
        <td>
          <? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a><? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (count($summary) > 1): ?>
        <tr>
          <th><?=$this->transEsc('Summary')?>: </th>
          <td>
            <? foreach (array_slice($summary, 1) as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td><?=$this->record($this->driver)->getFormatList()?></td>
        </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <?=$this->escapeHtml($field)?><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <? foreach ($subjects as $field): ?>
          <div class="subjectLine">
            <? $subject = ''; ?>
            <? $i = 0; foreach ($field as $subfield): ?>
              <?=($i++ == 0) ? '' : ' &gt; '?>
              <? $subject = trim($subject . ' ' . $subfield); ?>
              <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" class="subjectHeading" rel="nofollow"><?=$this->escapeHtml($subfield)?></a>
            <? endforeach; ?>
          </div>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $notes = $this->driver->getGeneralNotes(); if (!empty($notes)): ?>
        <tr>
          <th><?=$this->transEsc('Notes')?>: </th>
          <td>
            <? foreach ($notes as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
        <tr>
          <th><?=$this->transEsc('Production Credits')?>: </th>
          <td>
            <? foreach ($credits as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
        <tr>
          <th><?=$this->transEsc('ISBN')?>: </th>
          <td>
            <? foreach ($isbns as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
        <tr>
          <th><?=$this->transEsc('ISSN')?>: </th>
          <td>
            <? foreach ($issns as $field): ?>
              <?=$this->escapeHtml($field)?><br/>
            <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
