<?php $this->headScript()->appendFile('collection_record.js'); ?>
<div class="row">
  <?php $QRCode = $this->record($this->driver)->getQRCode("core");
     $cover = $this->record($this->driver)->getCover('collection-info', 'medium', $this->record($this->driver)->getThumbnail('large'));
     $preview = $this->record($this->driver)->getPreviews(); ?>
  <?php if ($QRCode || $cover || $preview): ?>
  <div class="col-sm-3">
    <div class="text-center">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>
    </div>

    <?php if ($preview): ?><?=$preview?><?php endif; ?>
  </div>

  <div class="col-sm-6">
  <?php else: ?>
  <div class="col-sm-9">
  <?php endif; ?>

    <h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->escapeHtml($summary)?></p>
    <?php endif; ?>

    <?php /* Display the lists that this record is saved to */ ?>
    <div class="savedLists hidden alert alert-info" id="savedLists">
      <strong><?=$this->transEsc("Saved in")?>:</strong>
    </div>

    <a id="moreInfoToggle" href="#" class="hidden"><?=$this->transEsc('more_info_toggle')?></a>
    <?/* Display Main Details */?>
    <?php
      $formatter = $this->recordDataFormatter();
      $fields = $formatter->getData($driver, $formatter->getDefaults('collection-info'));
    ?>
    <?php if (!empty($fields)): ?>
      <table id="collectionInfo" class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
        <?php foreach ($fields as $key => $value): ?>
          <tr><th><?=$this->transEsc($key)?>:</th><td><?=$value?></td></tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
    <?/* End Main Details */?>
  </div>
</div>
