<h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>
<a href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->transEsc('View Full ' . ($this->driver->isCollection() ? 'Collection' : 'Record'))?></a>

<table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
  <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
  <? if ($summary): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Description')?>: </th>
      <td><?=$this->escapeHtml($summary)?></td>
    </tr>
  <? endif; ?>

  <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
  <? if (isset($authors['main']) && !empty($authors['main'])): ?>
  <tr>
    <th><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </th>
    <td>
      <? $i = 0; foreach ($authors['main'] as $author => $data): ?>
        <?=($i++ == 0)?'':', '?><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a>
        <? if (isset($data['role']) && count($data['role']) > 0): ?> (<? $j = 0; foreach ($data['role'] as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>

  <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
  <tr>
    <th><?=$this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Author' : 'Corporate Authors')?>: </th>
    <td>
      <? $i = 0; foreach ($authors['corporate'] as $corporate => $data): ?>
        <?=($i++ == 0)?'':', '?><a href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a>
        <? if (isset($data['role']) && count($data['role']) > 0): ?> (<? $j = 0; foreach ($data['role'] as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?>
      <? endforeach; ?>
    </td>
  </tr>
  <? endif; ?>

  <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Language')?>: </th>
      <td><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?><br/><? endforeach; ?></td>
    </tr>
  <? endif; ?>

  <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Format')?>: </th>
      <td><?=$this->record($this->driver)->getFormatList()?></td>
    </tr>
  <? endif; ?>

  <? $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Access')?>: </th>
      <td>
        <? foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <? $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <tr valign="top">
      <th><?=$this->transEsc('Related Items')?>: </th>
      <td>
        <? foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <? endforeach; ?>
      </td>
    </tr>
  <? endif; ?>
</table>