<? 
    $summaries = $this->driver->getSummary(); 
    foreach ($summaries as $summary):
        ?><?=$this->escapeHtml($summary) ?><br /><?
    endforeach;
    $isbn = $this->driver->getCleanISBN();
    $summaries = $this->summaries($isbn);
    foreach ($summaries as $provider => $list) {
        foreach ($list as $summary) {
            ?><?=$this->escapeHtml($summary) ?><br /><?
        }
    }
?>
