<? 
    $summaries = $this->driver->getSummary(); 
    foreach ($summaries as $summary):
        ?><?=$this->escapeHtml($summary) ?><br /><?
    endforeach;
    $isbn = $this->driver->getCleanISBN();
    $summaries = $this->summaries($isbn);
    foreach ($summaries as $provider => $content) {
        foreach ($content as $summary) {
            if ($provider == 'SyndeticsPlus') {
                ?><?=$summary ?><?
            } else {
                ?><?=$this->escapeHtml($summary) ?><br /><?
            }
        }
    }
?>
