<?
$formatProperty = function ($datafield, $name, $label) {
    if (count($datafield) == 0) {
        return '';
    }
    $that = $this;
    $translate = function ($str) use ($that, $label) {
        return $that->transEsc($label . $str);
    };
    return '<span class="author-property-' . $name . '">(' . implode(', ', array_unique(array_map($translate, $datafield))) . ')</span>';
};
?>
<? if (isset($data[$type]) && !empty($data[$type])): ?>
  <? $i = 0; foreach ($data[$type] as $author => $dataFields): ?>
<?ob_start()?>
    <?=($i++ == 0)?'':', '?><div class="author-data" property="<?=$this->escapeHtml($schemaLabel)?>">
      <a href="<?=$this->record($this->driver)->getLink('author', $author)?>">
        <?=$this->escapeHtml($author)?>
      </a>
      <?foreach ($requiredDataFields as $field):
        $name = $field['name'];
        $prefix = isset($field['prefix']) ? $field['prefix'] : '';
      ?>
        <?if (isset($dataFields[$name])):?>
          <?=$formatProperty($dataFields[$name], $name, $prefix)?>
        <?endif;?>
      <?endforeach;?>
    </div>
    <?$output .= trim(ob_get_contents())?>
<?ob_end_clean()?>
  <? endforeach; ?>
<? endif; ?>
<?=$output ?>
