<div class="container">
    <h1>Supporters</h1>
    <p>Lorem Ipsum Dolor S

        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.

        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Donec elementum ligula eu sapien consequat eleifend.

    </p>
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <img src="<?=$this->imageLink('logo-uni-tuebingen.png') ?>" alt="Universität T&uuml;bingen" width="260"
                 height="100"/>
        </div>
        <div class="col-xs-12 col-sm-6">
            <img src="<?=$this->imageLink('k-theologische-fak.gif') ?>" alt="Katholisch-Theologische Fakult&auml;t"
                 width="460" height="71"/>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <img src="<?=$this->imageLink('dfg_logo.gif') ?>" alt="DFG" width="250" height="31" />
        </div>
        <div class="col-xs-12 col-sm-6">
            <img src="<?=$this->imageLink('e-theologische-fak.gif') ?>" alt="Evangelisch-Theologische Fakult&auml;t" width="460" height="71" />
        </div>
    </div>
</div>
