<?php
return [
    'icons' => [
        'defaultSet' => 'FontAwesome6',
        'sets' => [
            /**
             * Define icon sets here.
             *
             * All sets need:
             * - 'template': which template the icon renders with
             * - 'src': the location of the relevant resource (font, css, images)
             * - 'prefix': prefix to place before each icon name for convenience
             *             (ie. fa fa- for FontAwesome 4, default "")
             */
            'FontAwesome6' => [
                'template' => 'font',
                'src' => 'vendor/fontawesome-free-6/css/all.min.css',
            ],
        ],
        'aliases' => [
            /**
             * Icons can be assigned or overridden here
             * Format: 'alias' => '[set:]icon[.extra.classes]'
             * Use: <?=$this->icon('alias') ?>
             *
             * Icons assigned without set will use the defaultSet (above):
             * - xmark == FontAwesome6:xmark
             *
             * You can include a set to borrow aliases from other icon sets:
             * - Unicode:cites (see root theme.config.php)
             *
             * To add extra classes, add an additional : divider:
             * - FontAwesome6:ui-trash.color-red
             */
            'addthis-bookmark' => 'fa-solid fa-circle-plus',
            'barcode' => 'fa-solid fa-barcode',
            'browzine-best' => 'fa-solid fa-list-ol',
            'browzine-concern' => 'Alias:warning',
            'browzine-delivery' => 'Alias:place-ill-request',
            'browzine-issue' => 'Alias:format-serial',
            'browzine-link-resolver' => 'Alias:place-ill-request',
            'browzine-pdf' => 'Alias:format-pdf',
            'browzine-retraction' => 'Alias:place-recall',
            'browzine-view' => 'Alias:format-online',
            'cart-add' => 'fa-solid fa-circle-plus',
            'cart-empty' => 'fa-solid fa-broom',
            'cart-remove' => 'fa-solid fa-circle-minus',
            'cart' => 'fa-solid fa-briefcase',
            'cite' => 'fa-solid fa-asterisk',
            'cited-by' => 'fa-solid fa-asterisk',
            'cites' => 'fa-solid fa-asterisk',
            'clone' => 'fa-solid fa-copy',
            'collapse-close' => 'fa-solid fa-chevron-up',
            'collapse-open' => 'fa-solid fa-chevron-down',
            'cover-replacement' => 'fa-solid fa-file-half-dashed',
            'currency-eur' => 'fa-solid fa-euro-sign',
            'currency-gbp' => 'fa-solid fa-sterling-sign',
            'currency-inr' => 'fa-solid fa-rupee-sign',
            'currency-jpy' => 'fa-solid fa-yen-sign',
            'currency-krw' => 'fa-solid fa-won-sign',
            'currency-rmb' => 'fa-solid fa-yen-sign',
            'currency-rub' => 'fa-solid fa-ruble-sign',
            'currency-try' => 'fa-solid fa-lira-sign',
            'currency-usd' => 'fa-solid fa-dollar-sign',
            'currency-won' => 'fa-solid fa-won-sign',
            'currency-yen' => 'fa-solid fa-yen-sign',
            'dropdown-caret' => 'fa-solid fa-caret-down',
            'explain' => 'fa-solid fa-circle-question',
            'export' => 'fa-solid fa-file-export',
            'external-link' => 'fa-solid fa-link',
            'facet-applied' => 'fa-solid fa-check',
            'facet-checked' => 'fa-solid fa-square-check',
            'facet-collapse' => 'fa-solid fa-caret-down',
            'facet-exclude' => 'fa-solid fa-xmark',
            'facet-expand' => 'fa-solid fa-caret-right',
            'facet-noncollapsible' => 'fa-solid fa-ban',
            'facet-unchecked' => 'fa-regular fa-square',
            'feedback' => 'fa-solid fa-envelope-open-text',
            'format-atlas' => 'fa-solid fa-map',
            'format-book' => 'fa-solid fa-book',
            'format-braille' => 'fa-solid fa-braille',
            'format-cdrom' => 'fa-solid fa-compact-disc',
            'format-chart' => 'fa-solid fa-chart-area',
            'format-chipcartridge' => 'fa-solid fa-microchip',
            'format-collage' => 'fa-solid fa-images',
            'format-default' => 'fa-solid fa-book',
            'format-disccartridge' => 'fa-solid fa-floppy-disk',
            'format-drawing' => 'fa-solid fa-pen-ruler',
            'format-ebook' => 'fa-solid fa-book-atlas',
            'format-electronic' => 'fa-solid fa-file-arrow-down',
            'format-file' => 'fa-solid fa-file',
            'format-filmstrip' => 'fa-solid fa-film',
            'format-flashcard' => 'fa-solid fa-address-card',
            'format-floppydisk' => 'fa-solid fa-floppy-disk',
            'format-folder' => 'fa-solid fa-folder-closed',
            'format-globe' => 'fa-solid fa-globe',
            'format-journal' => 'fa-solid fa-book',
            'format-kit' => 'fa-solid fa-toolbox',
            'format-manuscript' => 'fa-solid fa-file-signature',
            'format-map' => 'fa-solid fa-map',
            'format-microfilm' => 'fa-solid fa-film',
            'format-motionpicture' => 'fa-solid fa-video',
            'format-musicalscore' => 'fa-solid fa-music',
            'format-musicrecording' => 'fa-solid fa-microphone',
            'format-newspaper' => 'fa-solid fa-newspaper',
            'format-online' => 'fa-solid fa-cloud',
            'format-painting' => 'fa-solid fa-brush',
            'format-pdf' => 'fa-solid fa-file-pdf',
            'format-photo' => 'fa-solid fa-photo-film',
            'format-photonegative' => 'fa-solid fa-photo-film',
            'format-physicalobject' => 'fa-solid fa-box-archive',
            'format-print' => 'fa-solid fa-image',
            'format-sensorimage' => 'fa-solid fa-camera-retro',
            'format-serial' => 'fa-solid fa-book-open',
            'format-slide' => 'fa-solid fa-film',
            'format-software' => 'fa-solid fa-laptop-code',
            'format-soundcassette' => 'fa-solid fa-headphones-simple',
            'format-sounddisc' => 'fa-solid fa-record-vinyl',
            'format-soundrecording' => 'fa-solid fa-microphone',
            'format-tapecartridge' => 'fa-solid fa-headphones-simple',
            'format-tapecassette' => 'fa-solid fa-headphones-simple',
            'format-tapereel' => 'fa-solid fa-tape',
            'format-transparency' => 'fa-solid fa-person-chalkboard',
            'format-unknown' => 'fa-solid fa-icons',
            'format-video' => 'fa-solid fa-video',
            'format-videocartridge' => 'fa-solid fa-video',
            'format-videocassette' => 'fa-solid fa-video',
            'format-videodisc' => 'fa-solid fa-compact-disc',
            'format-videoreel' => 'fa-solid fa-tape',
            'hierarchy-collapse' => 'Alias:facet-collapse',
            'hierarchy-collection' => 'fa-solid fa-folder-open',
            'hierarchy-expand' => 'Alias:facet-expand',
            'hierarchy-noncollapsible' => 'Alias:facet-noncollapsible',
            'hierarchy-record' => 'fa-solid fa-file',
            'hierarchy-tree' => 'fa-solid fa-folder-tree',
            'keyboard' => 'fa-solid fa-keyboard',
            'lightbox-close' => 'fa-solid fa-xmark',
            'link' => 'fa-solid fa-link',
            'more' => 'fa-solid fa-chevron-right',
            'more-rtl' => 'fa-solid fa-chevron-left',
            'my-account-notification' => 'Alias:notification',
            'my-account-warning' => 'Alias:warning',
            'my-account' => 'fa-solid fa-circle-user',
            'notification' => 'fa-solid fa-bell',
            'offcanvas-hide-left' => 'fa-solid fa-angle-right',
            'offcanvas-hide-right' => 'fa-solid fa-angle-left',
            'offcanvas-show-left' => 'fa-solid fa-angles-left',
            'offcanvas-show-right' => 'fa-solid fa-angles-right',
            'options' => 'fa-solid fa-sliders',
            'overdrive-cancel-hold' => 'Alias:ui-cancel',
            'overdrive-checkout' => 'fa-solid fa-arrow-left',
            'overdrive-checkout-rtl' => 'fa-solid fa-arrow-right',
            'overdrive-download' => 'fa-solid fa-download',
            'overdrive-edit-hold-suspension' => 'fa-solid fa-hourglass',
            'overdrive-edit-hold' => 'Alias:ui-edit',
            'overdrive-help' => 'fa-solid fa-circle-question',
            'overdrive-place-hold' => 'Alias:place-hold',
            'overdrive-return' => 'fa-solid fa-backward',
            'overdrive-return-rtl' => 'fa-solid fa-forward',
            'overdrive-sign-in' => 'fa-solid fa-user',
            'overdrive-success' => 'fa-solid fa-circle-check',
            'overdrive-suspend-hold' => 'fa-solid fa-hourglass',
            'overdrive-warning' => 'Alias:warning',
            'overdrive' => 'fa-solid fa-cloud-arrow-down',
            'page-first' => 'fa-solid fa-backward-step',
            'page-prev' => 'fa-solid fa-angle-left',
            'page-next' => 'fa-solid fa-angle-right',
            'page-last' => 'fa-solid fa-forward-step',
            'page-first-rtl' => 'fa-solid fa-forward-step',
            'page-prev-rtl' => 'fa-solid fa-angle-right',
            'page-next-rtl' => 'fa-solid fa-angle-left',
            'page-last-rtl' => 'fa-solid fa-backward-step',
            'place-hold' => 'fa-solid fa-book-bookmark',
            'place-ill-request' => 'fa-solid fa-envelopes-bulk',
            'place-recall' => 'fa-solid fa-backward',
            'place-recall-rtl' => 'fa-solid fa-forward',
            'place-storage-retrieval' => 'fa-solid fa-dolly',
            'print' => 'fa-solid fa-print',
            'profile-card-delete' => 'Alias:ui-delete',
            'profile-card-edit' => 'Alias:ui-edit',
            'profile-change-password' => 'fa-solid fa-key',
            'profile-delete' => 'Alias:ui-delete',
            'profile-edit' => 'Alias:ui-edit',
            'profile-email' => 'fa-solid fa-at',
            'profile-sms' => 'fa-solid fa-mobile',
            'profile' => 'fa-solid fa-circle-user',
            'qrcode' => 'fa-solid fa-qrcode',
            'rating-full' => 'fa-solid fa-star',
            'rating-half' => 'fa-solid fa-star-half-stroke',
            'search' => 'fa-solid fa-magnifying-glass',
            'search-delete' => 'Alias:ui-delete',
            'search-filter-remove' => 'Alias:ui-remove',
            'search-reset' => 'fa-solid fa-delete-left',
            'search-reset-rtl' => 'fa-solid fa-circle-xmark',
            'search-rss' => 'fa-solid fa-square-rss',
            'search-save' => 'Alias:ui-save',
            'search-schedule-alert' => 'fa-solid fa-bell',
            'send-email' => 'fa-solid fa-envelope',
            'send-sms' => 'fa-solid fa-mobile',
            'sign-in' => 'fa-solid fa-circle-user',
            'sign-out' => 'fa-solid fa-door-closed',
            'spinner' => 'FontAwesome6:fa-solid fa-spinner:icon--spin',
            'status-available' => 'fa-solid fa-check',
            'status-pending' => 'fa-regular fa-clock',
            'status-ready' => 'fa-solid fa-bell',
            'status-unavailable' => 'fa-solid fa-xmark',
            'status-uncertain' => 'fa-regular fa-circle',
            'status-unknown' => 'fa-regular fa-circle-question',
            'tag-add' => 'Alias:ui-add',
            'tag-remove' => 'Alias:ui-remove',
            'tree-context' => 'fa-solid fa-folder-tree',
            'truncate-less' => 'fa-solid fa-arrow-up',
            'truncate-more' => 'fa-solid fa-arrow-down',
            'ui-add' => 'fa-solid fa-circle-plus',
            'ui-cancel' => 'fa-solid fa-ban',
            'ui-close' => 'fa-solid fa-xmark',
            'ui-delete' => 'fa-solid fa-trash',
            'ui-dots-menu' => 'fa-solid fa-ellipsis-h',
            'ui-edit' => 'fa-solid fa-pencil',
            'ui-failure' => 'fa-solid fa-circle-xmark',
            'ui-menu' => 'fa-solid fa-bars',
            'ui-remove' => 'fa-solid fa-xmark',
            'ui-save' => 'fa-solid fa-floppy-disk',
            'ui-success' => 'fa-solid fa-check',
            'user-checked-out' => 'fa-solid fa-book',
            'user-content' => 'fa-solid fa-comment',
            'user-favorites' => 'fa-solid fa-star',
            'user-holds' => 'fa-solid fa-book-bookmark',
            'user-ill-requests' => 'fa-solid fa-arrow-right-arrow-left',
            'user-list-add' => 'fa-solid fa-bookmark',
            'user-list-delete' => 'Alias:ui-delete',
            'user-list-edit' => 'Alias:ui-edit',
            'user-list-entry-edit' => 'Alias:ui-edit',
            'user-list-remove' => 'Alias:ui-remove',
            'user-list' => 'fa-solid fa-rectangle-list',
            'user-loan-history' => 'fa-solid fa-clock-rotate-left',
            'user-public-list-indicator' => 'fa-solid fa-eye',
            'user-storage-retrievals' => 'fa-solid fa-dolly',
            'view-grid' => 'fa-solid fa-border-all',
            'view-list' => 'fa-solid fa-list-ol',
            'view-visual' => 'fa-solid fa-border-none',
            'warning' => 'fa-solid fa-circle-exclamation',
        ],
    ],
];
