<?
    // Set page title.
    $this->headTitle($this->translate('hierarchy_tree') . ': ' . $this->driver->getBreadcrumb());
    $hierarchyTreeList = $this->tab->getTreeList();
    $activeTree = $this->tab->getActiveTree();

    $this->inlineScript(
        \Zend\View\Helper\HeadScript::SCRIPT,
        "var hierarchySettings = {\n"
        . "    lightboxMode: " . ($this->layout()->getTemplate() == 'layout/lightbox' ? 'true' : 'false') . ",\n"
        . "    fullHierarchy: " . ($this->tab->getFullHierarchySetting() ? 'true' : 'false') . "\n"
        . "};\n"
        . "vufindString.showTree = \"" . $this->transEsc('hierarchy_show_tree') . "\";\n"
        . "vufindString.hideTree = \"" . $this->transEsc('hierarchy_hide_tree') . "\";\n"
    );
    $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'jsTree/jquery.jstree.js');
    $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'hierarchyTree_JSTree.js');
    echo $this->inlineScript();
?>
<div>
  <? if (count($hierarchyTreeList) > 1): ?>
    <div id="treeSelector">
      <? foreach ($hierarchyTreeList as $hierarchy => $hierarchyTitle): ?>
        <a class="tree<?=($activeTree == $hierarchy) ? ' currentTree' : ''?>" href="<?=$this->recordLink()->getTabUrl($this->driver, 'HierarchyTree')?>?hierarchy=<?=urlencode($hierarchy)?>"><?=$this->escapeHtml($hierarchyTitle)?></a>
      <? endforeach; ?>
    </div>
  <? endif; ?>
  <? if ($activeTree): ?>
    <div id="hierarchyTreeHolder">
      <div id="hierarchyTree">
        <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenRecordId" />
        <input type="hidden" value="<?=$this->escapeHtml($activeTree)?>" class="hiddenHierarchyId" />
        <input type="hidden" value="Record" class="hiddenContext" />
        <noscript>
          <?=$this->tab->renderTree($this->url('home'))?>
        </noscript>
      </div>
    </div>
  <? endif; ?>
</div>
