<?php
  // Set page title.
  $this->headTitle($this->translate('Book Bag'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
?>
<h2><?=$this->transEsc('Book Bag') ?></h2>
<?=$this->flashmessages()?>
<form class="form-inline" action="<?=$this->url('cart-processor')?>" method="post"  name="cartForm" data-lightbox-onsubmit="cartFormHandler">
  <input type="hidden" id="dropdown_value"/>
  <?php if (!$this->cart()->isEmpty()): ?>
    <div class="cart-controls clearfix">
      <div class="checkbox pull-left flip">
        <label>
          <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
          <?=$this->transEsc('select_page')?>
        </label>
      </div>
      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <button type="submit" class="toolbar-btn btn-type-save" name="saveCart" title="<?=$this->transEscAttr('bookbag_save')?>" value="1">
          <?=$this->transEsc('Save')?>
        </button>
      <?php endif; ?>
      <button type="submit" class="toolbar-btn btn-type-email" name="email" title="<?=$this->transEscAttr('bookbag_email')?>" value="1">
        <?=$this->transEsc('Email')?>
      </button>
      <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
        <button type="submit" class="toolbar-btn btn-type-export" name="export" title="<?=$this->transEscAttr('bookbag_export')?>" value="1">
          <?=$this->transEsc('Export')?>
        </button>
      <?php endif; ?>
      <button type="submit" class="toolbar-btn btn-type-print" name="print" title="<?=$this->transEscAttr('print_selected')?>" value="1">
        <?=$this->transEsc('Print')?>
      </button>
      <div class="btn-group" id="cartDelete">
        <button type="submit" name="delete" class="toolbar-btn btn-type-delete dropdown-toggle" data-toggle="dropdown" id="cart-delete-label" value="1">
          <?=$this->transEsc('Delete')?>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="cart-delete-label">
          <li role="none">
            <a href="javascript:" id="cart-confirm-delete" title="<?=$this->transEscAttr('confirm_delete')?>" role="menuitem"><?=$this->transEsc('confirm_dialog_yes')?></a
          </li>
          <li role="none">
            <a href="javascript:" role="menuitem"><?=$this->transEsc('confirm_dialog_no')?></a>
          </li>
        </ul>
      </div>
      <div class="btn-group">
        <button type="submit" class="toolbar-btn btn-type-empty dropdown-toggle" name="empty" data-toggle="dropdown" id="cart-empty-label" value="1">
          <?=$this->transEsc('Empty Book Bag')?>
        </button>
        <ul class="dropdown-menu" role="menu" aria-labelledby="cart-empty-label">
          <li role="none">
            <a href="javascript:" id="cart-confirm-empty" title="<?=$this->transEscAttr('bookbag_confirm_empty')?>" role="menuitem"><?=$this->transEsc('confirm_dialog_yes')?></a>
          </li>
          <li role="none">
            <a href="javascript:" id="cart-refuse-empty" role="menuitem"><?=$this->transEsc('confirm_dialog_no')?></a>
          </li>
        </ul>
      </div>
    </div>
  <?php endif; ?>
  <?=$this->render('cart/contents.phtml')?>
</form>

<?php
  $script = <<<'JS'
  function submitFormWithButton(link, name) {
    $('#dropdown_value').attr('name', name).val(1);
    $(link).closest('form').submit();
  }
  $("#cart-confirm-delete").click(function($e) {
      submitFormWithButton(this, 'delete');
  });
  $("#cart-confirm-empty").click(function($e) {
      submitFormWithButton(this, 'empty');
  });
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
