<?php
    // Set page title.
    $this->headTitle($this->translate('bookbag_save_selected'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ') .
        '<li class="active">' . $this->transEsc('bookbag_save_selected') . '</li>';
?>
<h2><?=$this->transEsc('bookbag_save_selected')?></h2>

<?=$this->flashmessages()?>

<form class="form-cart-save" method="post" action="<?=$this->url('cart-save')?>" name="bulkSave">
  <?php $idParams = []; ?>
  <?php foreach ($this->records as $current): ?>
    <?php $idParams[] = urlencode('ids[]') . '=' . urlencode($current->getSourceIdentifier() . '|' . $current->getUniqueId()) ?>
    <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($current->getSourceIdentifier() . '|' . $current->getUniqueId())?>" />
  <?php endforeach; ?>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Title')?>:</label>
    <?php if(count($this->records) > 1): ?>
      <button type="button" class="btn btn-default hidden" data-toggle="collapse" data-target="#itemhide">
        <?=count($this->records) . ' ' . $this->transEsc('items') ?>
      </button>
      <div id="itemhide" class="collapse in">
        <ul>
          <?php foreach ($this->records as $current): ?>
            <li><?=$this->escapeHtml($current->getBreadcrumb())?></li>
          <?php endforeach; ?>
        </ul>
      </div>
    <?php else: ?>
      <p class="form-control-static"><?=$this->records[0]->getBreadcrumb() ?></p>
    <?php endif; ?>
  </div>

  <div class="form-group">
    <label class="control-label" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <select id="save_list" name="list" class="form-control">
      <?php if (count($this->lists) > 0): ?>
        <?php foreach ($this->lists as $list): ?>
          <option value="<?=$list['id'] ?>"<?php if ($list['id'] == $this->userlist()->lastUsed()): ?> selected="selected"<?php endif; ?>><?=$this->escapeHtml($list['title'])?></option>
        <?php endforeach; ?>
      <?php else: ?>
        <option value=""><?=$this->transEsc('My Favorites') ?></option>
      <?php endif; ?>
    </select>
    <a class="btn btn-link" id="make-list"  href="<?=$this->url('editList', ['id' => 'NEW']) . '?' . implode('&amp;', $idParams) ?>"><?=$this->transEsc('or create a new list'); ?></a>
  </div>

  <?php if ($this->usertags()->getMode() !== 'disabled'): ?>
    <div class="form-group">
      <label class="control-label" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
      <input id="add_mytags" type="text" name="mytags" value="" class="form-control"/>
      <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Save') ?>"/>
  </div>
</form>

<?php
  $script = <<<JS
  $('button.btn.hidden').removeClass('hidden');
  $('#itemhide').removeClass('in');
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
