<?php if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<?php $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls)
  || (isset($this->showBulkOptions) && $this->showBulkOptions); ?>
<?php $i = $this->indexStart; ?>
<?php foreach ($this->results->getResults() as $current): ?>
  <?php $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="row result<?=$current->supportsAjaxStatus()?' ajaxItem':''?> clearfix <?=$i%2==1?' panel-gray ':' panel-body '?>">
    <div class="col-xs-1 hidden-print">
        <?php if ($showCheckboxes): ?>
          <?=$this->record($current)->getCheckbox('', 'search-cart-form', $recordNumber)?>
        <?php endif; ?>
        <div class="record-number">
          <?=$recordNumber?>
        </div>
    </div>
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<?php endforeach; ?>
