#!/bin/sh
set -e

# Build local configurations.
php install.php --non-interactive
cp /usr/local/vufind/config/vufind/config.ini /usr/local/vufind/local/config/vufind/
sed -i -e 's/mysql:\/\/root@localhost/mysql:\/\/root@mysql/g' /usr/local/vufind/local/config/vufind/config.ini
sed -i -e 's/http:\/\/localhost:8080\/solr/http:\/\/solr:8983\/solr/g' /usr/local/vufind/local/config/vufind/config.ini
ln -s /usr/local/vufind/local/httpd-vufind.conf /etc/apache2/conf-enabled/vufind.conf
chown -R www-data:www-data /usr/local/vufind/local/cache /usr/local/vufind/local/config

exec "$@"