<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#05_2022"><b>National Licence for World Religion Database (WRD) now available!</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2021"><b>New feature: RelBib authority search and person information pages</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2021"><b>RelBib Alerting service: Now also subscribe to journal bundles!</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">archive</a>
</div>
