<?php
    $this->headTitle($this->translate('Item Fulltext Search') . ': ' . $this->driver->getBreadcrumb())
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'TueFind.ItemFullTextSearch("'.$this->url('home').'", "'.$this->driver->getUniqueID().'", "' . implode(",", $this->driver->getFulltextTypes()) . '");')?>
<span>
  <select id="itemFTTextTypeScope" class="selectpicker">
<?php $fulltext_types = $this->driver->getFulltextTypes();
      if (count($fulltext_types) > 1)
          echo '<option value="All Types">' . $this->translate('All Types') . '</option>';
      foreach ($fulltext_types as $fulltext_type):
          switch ($fulltext_type) {
            case 'Fulltext':
                echo '<option value="Fulltext">' . $this->translate('Fulltext') . '</option>';
                break;
            case 'Table of Contents':
                echo '<option value="Table of Contents">' . $this->translate('Table of Contents') . '</option>';
                break;
            case 'Abstract':
                echo '<option value="Abstract">' . $this->translate('Abstract') . '</option>';
                break;
            case 'Summary':
                echo '<option value="Summary">' . $this->translate('Summary') . '</option>';
                break;
            case 'List of References':
                echo '<option value="Summary">' . $this->translate('List of References') . '</option>';
                break;
            case 'Unknown':
                echo '<option value="Unknown">' . $this->translate('Unknown') . '</option>';
          }
       endforeach;
  ?>
  </select>
  <select id="itemFTSearchScope" class="selectpicker">
    <option value=""><?=$this->translate('Fulltext Only')?></option>
    <option value="lang"><?=$this->translate('Fulltext With Language Synonyms')?></option>
    <option value="all"><?=$this->translate('Fulltext With All Synonyms')?></option>
  </select>
</span>

<form class="searchForm form-horizontal" name="ItemFulltextSearchForm" id="ItemFulltextSearchForm" autocomplete="off">
  <div class="input-group input-group-sm" style="padding-top:10px; padding-bottom:10px">
    <input id="searchForm_fulltext" class="searchForm form-control search-query" type="text" placeholder="<?=$this->translate('Search the fulltext of this item')?>"/>
     <div class="input-group-btn">
       <button type="submit" class="btn btn-primary search-button"><i class="fa fa-search"></i></button>
     </div>
  </div>
</form>
<span id="fulltext_snippets">
  <div id="snippet_place_holder_<?=$this->driver->getUniqueID()?>"></div>
</span>
