<?php foreach ($checkboxFilters as $current): ?>
  <?php
    $parts = explode(':', $current['filter']);
    $classes = str_replace('_', '-', $parts[0]);
    if (isset($parts[1])) {
      $classes .= " $classes-" . preg_replace('/\W/', 'x', $parts[1]);
    }
  ?>
  <div class="checkbox <?=$current['selected'] ? 'checked' : ''?><?=!empty($current['disabled']) ? ' disabled' : ''?> <?=$this->escapeHtmlAttr($classes)?><?php if(!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<?php endif; ?> checkbox-filter" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>"<?=!$current['selected'] && empty($current['disabled']) && isset($counts) && false === $counts ? '' : ' data-loaded="true"'?>>
    <label>
      <span class="badge cb-facet avail-count"></span>
      <input class="checkbox-filter" type="checkbox" name="filter[]" value="<?=$this->escapeHtmlAttr($current['filter'])?>" <?=($current['selected'] ? 'checked="checked"' : '')?>
        id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"
        data-location="<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']) ?>"
        <?=!empty($current['disabled']) ? 'disabled="disabled"' : ''?>
      />
      <span><?=$this->translate($current['desc']) // Intentionally left unescaped to allow HTML in the description ?></span>
    </label>
  </div>
<?php endforeach; ?>
<?php
  $script = <<<JS
$('input.checkbox-filter').click(function() {
  document.location.href = $(this).data('location');
});
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
