<? foreach ($checkboxFilters as $current): ?>
  <?
    if (isset($counts) && false === $counts) {
      $availableRecords = '';
    } else {
      $availCount = $current['selected'] ? -1 : $this->checkboxFacetCounts($current, $results);
      $availableRecords = $availCount < 0 ? '' : $this->localizedNumber($availCount);
    }
  ?>
  <div class="checkbox <?=($current['selected'] ? 'checked' : '')?><? if(!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<? endif; ?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>"<?=!$current['selected'] && isset($counts) && false === $counts ? '' : ' data-loaded="true"'?>>
    <label>
      <span class="badge cb-facet avail-count"><?=$availableRecords?></span>
      <input type="checkbox" name="filter[]" value="<?=$this->escapeHtmlAttr($current['filter'])?>" <?=($current['selected'] ? 'checked="checked"' : '')?>
        id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"
        onclick="document.location.href='<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']) ?>'"
      />
      <?=$this->translate($current['desc']) // Intentionally left unescaped to allow HTML in the description ?>
    </label>
  </div>
<? endforeach; ?>
