<?php foreach ($checkboxFilters as $current): ?>
  <div class="checkbox <?=($current['selected'] ? 'checked' : '')?><?php if(!($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible'])): ?> hidden<?php endif; ?> checkbox-filter" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>"<?=!$current['selected'] && isset($counts) && false === $counts ? '' : ' data-loaded="true"'?>>
    <label>
      <span class="badge cb-facet avail-count"></span>
      <input type="checkbox" name="filter[]" value="<?=$this->escapeHtmlAttr($current['filter'])?>" <?=($current['selected'] ? 'checked="checked"' : '')?>
        id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"
        onclick="document.location.href='<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter']) ?>'"
      />
      <?=$this->translate($current['desc']) // Intentionally left unescaped to allow HTML in the description ?>
    </label>
  </div>
<?php endforeach; ?>
