<? if (!empty($cluster['list'])): ?>
  <? foreach ($cluster['list'] as $i => $thisFacet): ?>
     <?
      if(strlen($thisFacet['displayText']) == 0) {
        $thisFacet['displayText'] = "-";
      }
    ?>
    <? $moreClass = 'narrowGroupHidden-' . $this->escapeHtmlAttr($title) . ' hidden'; ?>
    <? if ($i == $facets_before_more): ?>
      <? $idAndClass = 'id="more-narrowGroupHidden-' . $this->escapeHtmlAttr($title) . '" class="list-group-item less-narrow-toggle"'; ?>
      <? if ($facetLightbox = $options->getFacetListAction()): ?>
        <? $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams() . '&facet=' . $title . '&facetop=' . $thisFacet['operator'] . '&facetexclude=' . ($allowExclude ? 1 : 0); ?>
      <? else: ?>
        <? $moreUrl = '#'; ?>
      <? endif; ?>
      <? if (($showMoreInLightbox && $showMoreInLightbox !== 'more') && $facetLightbox): ?>
        <a <?=$idAndClass ?> data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('more')?>...</a>
        <? break; ?>
      <? else: ?>
        <a <?=$idAndClass ?> href="<?=$moreUrl ?>" onclick="return moreFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')" rel="nofollow"><?=$this->transEsc('more')?>... <i class="fa fa-handle-open"></i></a>
      <? endif; ?>
    <? endif; ?>
    <? if ($thisFacet['isApplied']): ?>
      <a class="list-group-item active<? if ($i >= $facets_before_more): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], $thisFacet['operator']) ?>" title="<?=$this->transEsc('applied_filter') ?>">
        <? if ($thisFacet['operator'] == 'OR'): ?>
          <i class="fa fa-check-square-o" aria-hidden="true"></i>
        <? else: ?>
          <span class="pull-right"><i class="fa fa-check" aria-hidden="true"></i></span>
        <? endif; ?>
        <?=$this->escapeHtml($thisFacet['displayText'])?>
      </a>
    <? else: ?>
      <? $addURL = $results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
      <? if ($allowExclude): ?>
        <div class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
      <? else: ?>
        <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
      <? endif; ?>
      <span class="badge">
        <?=$this->localizedNumber($thisFacet['count'])?>
        <? if ($allowExclude): ?>
          <a href="<?=$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times" aria-hidden="true"></i></a>
        <? endif; ?>
      </span>
      <? if ($allowExclude): ?>
        <a href="<?=$addURL ?>">
      <? endif; ?>
      <? if($thisFacet['operator'] == 'OR'): ?>
        <i class="fa fa-square-o" aria-hidden="true"></i>
      <? endif; ?>
      <?=$this->escapeHtml($thisFacet['displayText'])?>
      <? if ($allowExclude): ?>
          </a>
        </div>
      <? else: ?>
        </a>
      <? endif; ?>
    <? endif; ?>
  <? endforeach; ?>
  <? if ($showMoreInLightbox === 'more' && $facetLightbox = $options->getFacetListAction()): ?>
    <?
      $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams() . '&amp;facet=' . $this->title . '&amp;facetop=' . $thisFacet['operator'] . '&amp;facetexclude=' . ($this->allowExclude ? 1 : 0);
      if (!empty($this->baseUriExtra)) {
        $moreUrl .= '&amp;baseUriExtra=' . urlencode($this->baseUriExtra);
      }
    ?>
    <a class="list-group-item less-narrow-toggle <?=$moreClass ?>" data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('see all')?>... <i class="fa fa-list"></i></a>
  <? endif; ?>
  <? if ($i >= $facets_before_more): ?><a class="list-group-item less-narrow-toggle <?=$moreClass ?>" href="#" onclick="return lessFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')"><?=$this->transEsc('less')?>... <i class="fa fa-handle-close"></i></a><? endif; ?>
<? else: ?>
  <div class="list-group-item"><?=$this->transEsc('facet_list_empty')?></div>
<? endif; ?>
