<!-- START of: finna - Recommend/SideFacets/facet.phtml -->
<?php $this->results = $results = $this->recommend->getResults(); ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets(); ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets(); ?>
<?php $geographicFacets = []; ?>
<?php
  if (is_callable([$this->recommend, 'getGeographicFacets'])) {
    $geographicFacets = $this->recommend->getGeographicFacets();
  }
?>
<?php $newItemsFacets = $this->recommend->getNewItemsFacets(); ?>
<?php $module = $this->layout()->templateDir; ?>
<?php $title = $this->facet; $cluster = $this->cluster; ?>
<?php
  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    $dateRangeFilter = $params->getDateRangeFilter();
  }
?>
<?php $sideFacetSet = $this->recommend->getFacetSet();
$rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<?php $allowExclude = $this->recommend->excludeAllowed($title); ?>
<?php $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>
<?php $showMoreInLightbox = $this->recommend->getShowInLightboxSetting($title); ?>
<?php $daterangeFacet = $title == $daterangeFacetField; ?>
<?php
  if ($daterangeFacet) {
    $fromVal = $toVal = $type = null;
    $queryHelper = $results->getUrlQuery();
    $queryHelper->removeDefaultParameter("{$daterangeFacetField}_type");
    $searchParams = $formParams = $queryHelper->getParamsWithoutPage(false);
    if ($dateRangeFilter) {
      $formParams = $queryHelper->removeFacet($dateRangeFilter['field'], $dateRangeFilter['value'], 'AND');
      $spatialFilter = $results->getParams()->parseDateRangeFilter($dateRangeFilter['value']);
      $from = $spatialFilter['from'] ?? null;
      $to = $spatialFilter['to'] ?? null;
      $fromVal = $from != '*' ? $from : '';
      $toVal = $to != '*' ? $to : '';
      if (isset($spatialFilter['type'])) {
        $type = $spatialFilter['type'];
      }
      if ($params->getSearchType() != 'advanced') {
        $lookfor = $params->getQuery()->getString();
        if ($lookfor == '' && $fromVal === null && $toVal === null) {
          $plotFrom = 0;
        }
      }
    }
  }
?>
<?php if (isset($newItemsFacets[$title])): ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/new-item-facet.phtml', ['results' => $results, 'title' => $title, 'newItemsFacets' => $newItemsFacets, 'datePickerLang' => $datePickerLang]); ?>
<?php elseif ($daterangeFacet): ?>
    <div class="list-group-item daterange">
      <?=$this->partial('Recommend/DateRangeVisAjax.phtml', [
        'submitLabel' => 'Update',
        'from' => $fromVal,
        'to' => $toVal,
        'formAction' => $formParams,
        'searchParams' => $searchParams,
        'baseParams' => $formParams,
        'type' => $type,
        'backend' => (null === $module || $module == 'search') ? 'solr' : $module,
        'daterangeFacet' => $daterangeFacetField,
        'plotFrom' => $plotFrom,
        'plotImmediately' => !in_array($title, $collapsedFacets) ? 'true' : 'false'
      ]);
      ?>
    </div>
<?php elseif (isset($rangeFacets[$title])): ?>
  <?=$this->context($this)->renderInContext('Recommend/SideFacets/range-facet.phtml', ['results' => $results, 'title' => $title, 'facet' => $rangeFacets[$title]]); ?>
<?php elseif ($title == 'usage_rights_str_mv'): ?>
    <?php $contextVars = [
        'options' => $options,
        'allowExclude' => $this->recommend->excludeAllowed($title),
        'facets_before_more' => $this->recommend->getShowMoreSetting($title),
        'showMoreInLightbox' => $this->recommend->getShowInLightboxSetting($title),
        'results' => $results
    ]; ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/usage-rights-facet.phtml', array_merge($contextVars, ['title' => $title, 'cluster' => $this->cluster])); ?>
<?php else: ?>
  <?php $contextVars = [
    'options' => $options,
    'allowExclude' => $this->recommend->excludeAllowed($title),
    'facets_before_more' => $this->recommend->getShowMoreSetting($title),
    'showMoreInLightbox' => $this->recommend->getShowInLightboxSetting($title),
    'title' => $title,
    'sortOptions' => $hierarchicalFacetSortOptions[$title] ?? '',
    'collapsedFacets' => $collapsedFacets,
    'results' => $results
  ]; ?>
  <?php if (in_array($title, $hierarchicalFacets)): ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/hierarchical-facet.phtml', $contextVars); ?>
  <?php elseif (in_array($title, $geographicFacets)): ?>
    <div class="geofacet-header">
      <h5 class="geofacet-title"><?=$this->translate('choose_from_list')?></h5>
    </div>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/cluster-list.phtml', array_merge($contextVars, ['title' => $title, 'cluster' => $cluster])); ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/geographic-facet.phtml', array_merge($contextVars, ['title' => $title, 'cluster' => $cluster])); ?>
  <?php else: ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/cluster-list.phtml', array_merge($contextVars, ['title' => $title, 'cluster' => $cluster])); ?>
  <?php endif; ?>
<?php endif; ?>
<!-- END of: finna - Recommend/SideFacets/facet.phtml -->
