<!-- START of: finna - Recommend/SideFacets/facet.phtml -->
<?php
  $this->results = $results = $this->recommend->getResults();
  $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions();
  $hierarchicalFacets = $this->recommend->getHierarchicalFacets();
  $collapsedFacets = $this->recommend->getCollapsedFacets();
  $geographicFacet = [];
  if (is_callable([$this->recommend, 'getGeographicFacet'])) {
    $geographicFacet = $this->recommend->getGeographicFacet();
  }
  $newItemsFacets = $this->recommend->getNewItemsFacets();
  $module = $this->layout()->templateDir;
  $facet = $this->facet;
  $cluster = $this->cluster;

  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    $dateRangeFilter = $params->getDateRangeFilter();
  }
  $sideFacetSet = $this->recommend->getFacetSet();
  $rangeFacets = $this->recommend->getAllRangeFacets();
  $allowExclude = $this->recommend->excludeAllowed($facet);
  $facets_before_more = $this->recommend->getShowMoreSetting($facet);
  $showMoreInLightbox = $this->recommend->getShowInLightboxSetting($facet);
  $daterangeFacet = $facet == $daterangeFacetField;

  if ($daterangeFacet) {
    $fromVal = $toVal = $type = null;
    $queryHelper = $results->getUrlQuery();
    $queryHelper->removeDefaultParameter("{$daterangeFacetField}_type");
    $searchParams = $formParams = $queryHelper->getParamsWithoutPage(false);
    if ($dateRangeFilter) {
      $formParams = $queryHelper->removeFacet($dateRangeFilter['field'], $dateRangeFilter['value'], 'AND');
      $spatialFilter = $results->getParams()->parseDateRangeFilter($dateRangeFilter['value']);
      $from = $spatialFilter['from'] ?? null;
      $to = $spatialFilter['to'] ?? null;
      $fromVal = $from != '*' ? $from : '';
      $toVal = $to != '*' ? $to : '';
      if (isset($spatialFilter['type'])) {
        $type = $spatialFilter['type'];
      }
      if ($params->getSearchType() != 'advanced') {
        $lookfor = $params->getQuery()->getString();
        if ($lookfor == '' && $fromVal === null && $toVal === null) {
          $plotFrom = 0;
        }
      }
    }
  }
?>
<?php if (isset($newItemsFacets[$facet])): ?>
  <?=$this->context($this)->renderInContext('Recommend/SideFacets/new-item-facet.phtml', ['results' => $results, 'title' => $facet, 'newItemsFacets' => $newItemsFacets, 'datePickerLang' => $datePickerLang]); ?>
<?php elseif ($daterangeFacet): ?>
  <div class="list-group-item daterange">
    <?=$this->partial('Recommend/DateRangeVisAjax.phtml', [
      'submitLabel' => 'Update',
      'from' => $fromVal,
      'to' => $toVal,
      'formAction' => $formParams,
      'searchParams' => $searchParams,
      'baseParams' => $formParams,
      'type' => $type,
      'backend' => (null === $module || $module == 'search') ? 'Solr' : $module,
      'daterangeFacet' => $daterangeFacetField,
      'plotFrom' => $plotFrom,
      'plotImmediately' => !in_array($facet, $collapsedFacets) ? 'true' : 'false'
    ]);
    ?>
  </div>
<?php elseif (isset($rangeFacets[$facet])): ?>
  <?=$this->context($this)->renderInContext('Recommend/SideFacets/range-facet.phtml', ['results' => $results, 'title' => $facet, 'facet' => $rangeFacets[$facet]]); ?>
<?php elseif ($facet == 'usage_rights_str_mv'): ?>
  <?php $contextVars = [
      'options' => $options,
      'allowExclude' => $this->recommend->excludeAllowed($facet),
      'facets_before_more' => $this->recommend->getShowMoreSetting($facet),
      'showMoreInLightbox' => $this->recommend->getShowInLightboxSetting($facet),
      'results' => $results
  ]; ?>
  <?=$this->context($this)->renderInContext('Recommend/SideFacets/usage-rights-facet.phtml', array_merge($contextVars, ['title' => $facet, 'cluster' => $this->cluster])); ?>
<?php else: ?>
  <?php $contextVars = [
    'options' => $options,
    'allowExclude' => $this->recommend->excludeAllowed($facet),
    'facets_before_more' => $this->recommend->getShowMoreSetting($facet),
    'showMoreInLightbox' => $this->recommend->getShowInLightboxSetting($facet),
    'title' => $facet,
    'sortOptions' => $hierarchicalFacetSortOptions[$facet] ?? '',
    'sortOptions' => $hierarchicalFacetSortOptions[$facet] ?? $hierarchicalFacetSortOptions['*'] ?? null,
    'collapsedFacets' => $collapsedFacets,
    'results' => $results
  ]; ?>
  <?php if (in_array($facet, $hierarchicalFacets)): ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/hierarchical-facet.phtml', $contextVars); ?>
  <?php elseif ($facet === 'geographic_facet' && isset($geographicFacet['map_selection']) && $geographicFacet['map_selection']): ?>
    <div class="geofacet-header">
      <h5 class="geofacet-title"><?=$this->translate('choose_from_list')?></h5>
    </div>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/cluster-list.phtml', array_merge($contextVars, ['title' => $facet, 'cluster' => $cluster])); ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/geographic-facet.phtml', array_merge($contextVars, ['title' => $facet, 'cluster' => $cluster])); ?>
  <?php else: ?>
    <?=$this->context($this)->renderInContext('Recommend/SideFacets/cluster-list.phtml', array_merge($contextVars, ['title' => $facet, 'cluster' => $cluster])); ?>
  <?php endif; ?>
<?php endif; ?>
<!-- END of: finna - Recommend/SideFacets/facet.phtml -->
