<?php
  $geoFilters = $this->params->getGeographicFilters($this->params->getFilterList());
  $mapPopupUrl = $this->url('search-mapfacet') . $results->getUrlQuery()->getParams(false);
  $removeFacetUrl = $results->getUrlQuery()->removeFacet($geoFilters[0] ?? '', '');
?>
<div class="geofacet-header">
  <h5 class="geofacet-title"><?=$this->translate('filter_by_geo_location')?></h5>
  <?php if (!empty($geoFilters)): ?>
    <a class="remove-facet" href="<?=$removeFacetUrl?>"><?=$this->translate("Remove filter");?></a>
  <?php endif;?>
  <div class="clearfix"></div>
</div>
<div aria-hidden="true" class="geographic-facet">
  <?php if (empty($geoFilters)):?>
    <div class="location-search-info alert alert-info hidden">
      <div class="fa fa-spinner fa-spin hidden"></div>
      <div class="info"></div>
    </div>
  <?php else: ?>
    <div class="map-container">
      <div class="map" style="height: 200px"></div>
      <div class="location-search-info info-map hidden">
        <a class="close-info fa fa-times"></a>
        <div class="fa fa-spinner fa-spin"></div>
        <div class="info"></div>
      </div>
    </div>
  <?php endif; ?>
  <div class="map-controls text-center">
    <a class="btn user-location-filter" href="<?=$removeFacetUrl?>"><?=$this->translate("use_my_location");?></a>
    <a tabindex="-1" class="btn map-control" href="<?=$this->escapeHtmlAttr($mapPopupUrl) ?>" data-lightbox><?=$this->translate("select_from_map");?></a>
  </div>
  <div class="clearfix"></div>
</div>
<div class="facet-info bg-info">
  <i class="fa fa-info3"></i><div class="info"><?=$this->transEsc('geographic_facet_info')?></div>
</div>

<?php
  $options = [
    'items' => []
  ];
  foreach ($geoFilters as $filter) {
    foreach (preg_split('/\s+OR\s+/', $filter) as $item) {
      $options['items'][] = $item;
    }
  }
  $options = json_encode($options);
  $script = <<<JS
  $(document).ready(function() {
    finna.MapFacet.initMapFacet($options);
  });
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
