<h2><?=$this->translate("select_area_from_map");?></h2>
<form action="<?=$this->url('search-results')?>" class="map-modal-form" data-lightbox-ignore>
  <?=$results->getUrlQuery()->asHiddenFields(['page' => "/./"])?>
  <?php $searchFilters = $results->getParams()->getFilterList(true);?>
  <div class="modal-map"></div>
  <button class="btn btn-lg btn-primary pull-right" type="submit"><?=$this->transEsc('Find')?></button>
</form>

<script>
  $(document).ready(function() {
    var options = {
      items: []
    };
    <?php foreach ($geoFilters as $filter): ?>
      <?php foreach (preg_split('/\s+OR\s+/', $filter) as $item): ?>
        options.items.push('<?=$this->escapeJs($item) ?>');
      <?php endforeach; ?>
    <?php endforeach; ?>
    finna.MapFacet.initMapModal(options);
  });
</script>
