<!-- START of: finna2 - Recommend/SideFacets/usage-rights-facet.phtml -->
<?php $usageOptions = []; ?>
<?php foreach ($cluster['list'] as $i => $thisFacet): ?>
  <?php
    $usageOptions[$thisFacet['value']] = $thisFacet;

    $toggleUrl = $thisFacet['isApplied']
      ? $results->getUrlQuery()->removeFacet($title, $thisFacet['value'], $thisFacet['operator'])
      : $results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']);

    ob_start();
  ?>
  <div class="facet js-facet-item<?php if ($thisFacet['isApplied']): ?> active<?php endif; ?>">
    <a class="text" href="<?=$toggleUrl ?>">
      <?=$this->transEsc($thisFacet['value'] . '_facet')?>
    </a>
    <?php if (!$thisFacet['isApplied']): ?>
      <span class="badge">
        <?=$this->localizedNumber($thisFacet['count'])?>
      </span>
      <?php if ($allowExclude): ?>
        <a class="exclude" href="<?=$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times" aria-hidden="true"></i></a>
      <?php endif; ?>
    <?php else: ?>
      <span class="status"><i class="fa fa-check" aria-hidden="true"></i></span>
    <?php endif; ?>
  </div>
  <?php $usageOptions[$thisFacet['value']]['html'] = ob_get_contents(); ?>
  <?php ob_end_clean(); ?>
<?php endforeach; ?>

<?=!empty($usageOptions['usage_A']) ? $usageOptions['usage_A']['html'] : ''?>
<?php if (!empty($usageOptions['usage_B']) || !empty($usageOptions['usage_D'])): ?>
  <div class="usage-right-group<?php if ($allowExclude): ?> usage-rights-excludable<?php endif; ?>">
    <span><?=$this->transEsc('usage_title_derivates')?></span>
    <?=!empty($usageOptions['usage_D']) ? $usageOptions['usage_D']['html'] : '' ?>
    <?=!empty($usageOptions['usage_B']) ? $usageOptions['usage_B']['html'] : '' ?>
  </div>
<?php endif; ?>
<?php if (!empty($usageOptions['usage_E']) || !empty($usageOptions['usage_C'])): ?>
  <div class="usage-right-group<?php if ($allowExclude): ?> usage-rights-excludable<?php endif ?>">
    <span><?=$this->transEsc('usage_title_no_derivates')?></span>
    <?=!empty($usageOptions['usage_E']) ? $usageOptions['usage_E']['html'] : '' ?>
    <?=!empty($usageOptions['usage_C']) ? $usageOptions['usage_C']['html'] : '' ?>
  </div>
<?php endif; ?>
<?=!empty($usageOptions['usage_F']) ? $usageOptions['usage_F']['html'] : '' ?>

<div class="list-group-item facet-info">
  <i class="fa fa-info3"></i><div class="info"><?=$this->transEsc('usage_rights_info')?></div><a class="more-info" href="<?=$this->url('content-page', ['page' => 'terms'])?>#terms"><?=$this->transEsc('usage_rights_info_more')?></a>
</div>
<?php if (!$this->translationEmpty('usage_rights_details')): ?>
<div class="list-group-item facet-info">
  <i class="fa fa-info3"></i><div class="info"><?=$this->transEsc('usage_rights_details')?></div>
</div>
<?php endif; ?>
<!-- END of: finna2 - Recommend/SideFacets/usage-rights-facet.phtml -->
