<?
/*********************************************
 *
 * authors.phtml
 *
 * by Benjamin Schnabel, benjamin.schnabel@uni-tuebingen.de
 *
 * Front page partial for the authors
 * page.
 *
 *************************************/
?>

<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="/themes/ixtheo2/images/frontpage/authors.jpg" alt="Bild Autoren" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Für Autoren</h4>
        <p>Wie können Autoren ihre Artikel auf IxTheo veröffentlichen?</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>