<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Content</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Monografien</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Zeitschriften/Rezensionen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Reihen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Datenbanken</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">PDA</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Wunschbuch</a></li>
            </ul>
        </p>
    </div>
</div>
