<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/repositories.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Themen</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Derivate</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Interne Sammlung</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Kuratierte Sammlungen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Andere Bibliografien</a></li>
            </ul>
        </p>
    </div>
</div>
