<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>IxTheo entdecken</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Allgemein (Erschließungskonzept)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Alerting</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Thematische Suche</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Volltextsuche</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Authorensteckbrief (Personalisierte Seiten)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Nachlässe</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => '']) ?>">Personalisierungsfunktion in VuFind</a></li>
            </ul>
        </p>
    </div>
</div>
