<div class="col-xs-3 col-sm-3 col-md-3 col-lg-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/publishers.jpg') ?>" alt="Bild Herausgeber" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Für Herausgeber</h4>
        <p>Was bietet IxTheo für Herausgeber?</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>