<div class="col-xs-12 col-sm-6 col-md-3 panel panel-bottom panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Für Herausgeber</h4>
        <p>Was bietet IxTheo für Herausgeber?</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
