<div class="col-xs-12 col-sm-6 col-md-3 panel panel-top panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/repositories.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>IxTheo Repositories</h4>
        <p>IxTheo hat verschiedene Repositories zu unterschiedlichen Themen, finden Sie heraus welche es gibt.</p>
        <a href="#" class="btn btn-default" role="button">Weiterlesen</a>
    </div>
</div>
