<div class="sidegroup">
  <h4><?=$this->transEsc('Similar Items')?></h4>
  <? $similarRecords = $this->related->getResults(); if (!empty($similarRecords)): ?>
    <ul class="similar">
      <? foreach ($similarRecords as $data): ?>
        <li>
          <? $formats = $data->getFormats(); if (count($formats) > 0): ?>
            <span class="<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>">
          <? else: ?>
            <span>
          <? endif; ?>
          <a href="<?=$this->recordLink()->getUrl($data)?>"><?=$this->escape($data->getTitle())?></a>
          </span>
          <? $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
            <br/><?=$this->transEsc('By')?>: <?=$this->escape($author);?>
          <? endif; ?>
          <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
            <?=$this->transEsc('Published')?>: (<?=$this->escape($pubDates[0])?>)
          <? endif; ?>
        </li>
      <? endforeach; ?>
    </ul>
  <? else: ?>
    <p><?=$this->transEsc('Cannot find similar records')?></p>
  <? endif; ?>
</div>