<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#KWKB">
            <h4 class="panel-title">
                Was mache ich, wenn ich ein kriminologisches Werk über keine Bibliothek erhalten kann?
            </h4>
        </A>
    </div>
    <div id="KWKB" class="panel-collapse collapse">
        <div class="panel-body">
            <p> Sie können einen Anschaffungsvorschlag an den Fachinformationsdienst Kriminologie richten. Hier finden
                Sie das
                <a href="<?=$this->url('acquisitionrequest-create')?>">Formular</a>.
                Das Erwerbungsprofil finden Sie
                <a href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk/fidkrim/erwerbungsprofil">hier</a>.
            </p>
        </div>
    </div>
</div>
