<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#SigLN">
            <h4 class="panel-title">
                Was bedeuten die Signaturen bei den einzelnen Literaturnachweisen?
            </h4>
        </A>
    </div>
    <div id="SigLN" class="panel-collapse collapse">
        <div class="panel-body">
            <p> Die Signaturen, die mit „KB“ beginnen, bezeichnen den Bestand des Fachinformationsdiensts Kriminologie,
                der in der Universitätsbibliothek Tübingen untergebracht ist. Alle anderen Signaturen verweisen auf den
                Bestand am Institut für Kriminologie der Universität Tübingen. Ist keine Signatur angegeben, so handelt
                es sich um einen bibliographischen Nachweis in der Datenbank KrimDok, für den jedoch kein physischer
                Bestand in Tübingen besteht.
            </p>
        </div>
    </div>
</div>