<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#WNMono">
            <h4 class="panel-title">
                Warum finden sich wenige Nachweise für Monografien der Bezugswissenschaften?
            </h4>
        </A>
    </div>
    <div id="WNMono" class="panel-collapse collapse">
        <div class="panel-body">
            <p>
                Hinsichtlich der Monographien bildet KrimDok zuvorderst den Bestand des Fachinformationsdiensts
                Kriminologie und des Instituts für Kriminologie der Universität Tübingen ab. In den Kategorien, die
                allgemeine und für die Kriminologie relevante, aber doch nur randständige und nicht genuin
                kriminologische Informationen enthalten (z.B. zu Drogen, Sexualität, Alkohol etc.), konnte in den
                letzten Jahren der Literaturbestand gemäß der finanziellen Ressourcen für bezugswissenschaftliche
                Literatur nur eingeschränkt erweitert werden.
            </p>
        </div>
    </div>
</div>