<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#WTueB">
            <h4 class="panel-title">
                Wie kann ich ein Werk aus den Tübinger Beständen einsehen oder ausleihen?
            </h4>
        </A>
    </div>
    <div id="WTueB" class="panel-collapse collapse">
        <div class="panel-body">
            <p>
                Sie können Bücher und Zeitschriften, die nicht an Ihrer Bibliothek vor Ort vorhanden sind in der Regel
                über die Fernleihe oder über den Lieferdienst Subito erhalten.
            </p>
            <p>
                Bei der Fernleihe handelt es sich um eine Vereinbarung zwischen Bibliotheken, wissenschaftliche
                Literatur (wie z.B. Monographien und Zeitschriftenaufsätze) untereinander auszutauschen.
            </p>
            <p>
                Als rechtliche Grundlage dienen die Bestimmungen der "Ordnung des Leihverkehrs in der Bundesrepublik
                Deutschland" (<a href="https://wiki.bsz-bw.de/lib/exe/fetch.php?media=fl-team:leihverkehrsordnung.pdf">Leihverkehrsordnung</a>).
            </p>
            <p>
                Nicht bestellt werden können:
            </p>
            <ul>
                <li>
                    Bücher und Zeitschriften, die in Ihrer Bibliothek vor Ort vorhanden sind (auch z. Zt. entliehene
                    Bücher und solche, die im Lesesaal oder in einer Teilbibliothek stehen)
                </li>
                <li>
                    Werke, die Sie für einen geringen Preis (etwa 10 €) im Buchhandel selbst erwerben können
                </li>
                <li>
                    Zeitschriftenhefte und gebundene Zeitschriftenbände neueren Datums
                </li>
            </ul>
            <p> Fernleihbestellungen geben Sie über das Bibliothekssystem Ihrer Bibliothek auf, wenn Sie vor Ort nicht
                die gewünschte Literatur gefunden haben. Das gewünschte Werk können Sie dann per Fernleihe aus einer
                anderen Bibliothek bestellen. Bei Zeitschriften haben Sie die Möglichkeit, einen Aufsatz zu bestellen.
            </p>
            <p> Pro Fernleihbestellung wird eine Bearbeitungsgebühr von 1,50 Euro fällig - unabhängig davon, ob eine
                Lieferung erfolgt. Die Erledigungsfrist liegt in der Regel bei ca. 1-3 Wochen.
            </p>
            <p> Sobald die Fernleihbestellung in Ihrer Bibliothek eingetroffen ist, werden Sie benachrichtigt und können
                das Werk am entsprechenden Ausgabeort abholen. Die Leihfrist wird von der gebenden Bibliothek
                vorgegeben, im Allgemeinen beträgt sie 4 Wochen (meistens ist eine einmalige Verlängerung der Leihfrist
                möglich).
            </p>
        </div>
    </div>
</div>