<!-- START of: finna - search/home/home-left_en-gb.phtml -->
<div class="introduction">
  <div>
    <h2>Header 1 (home-left_en-gb.phtml)</h2>
    <p>In libros De generatione et corruptione</p>
    <p>In hoc igitur libro philosophus primo ponit prooemium, demonstrans suam intentionem: secundo prosequitur propositum...</p>
  </div>
  <div>
    <div class="home-column">
      <p>Column 1</p>
    </div>
    <div class="home-column">
      <p>Column 2</p>
    </div>
  </div>
</div>
<!-- END of: finna - search/home/home-left_en-gb.phtml -->
