<!-- START of: finna - search/home/home-left.phtml -->
<div class="introduction">
  <div class="row">
    <div class="col-xs-12">
      <h2>Otsikko 1 (home-left_fi.phtml)</h2>
      <p>In libros De generatione et corruptione</p>
      <p>In hoc igitur libro philosophus primo ponit prooemium, demonstrans suam intentionem: secundo prosequitur propositum...</p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-6">
    <p>Palsta 1</p>
    </div>
    <div class="col-sm-6">
        <p>Palsta 2</p>
    </div>
  </div>
</div>
<!-- END of: finna - search/home/home-left.phtml -->
