<!-- START of: finna - search/home/home-2_en-gb.phtml -->
<div class="col-xs-12">
  <h2>home-2_en-gb.phtml</h2>
</div>
<div class="col-md-4">
  <div class="infobox">
  <h2>TODO Kokeile ulkomaisten tieteellisten aineistojen hakua</h2>
  <p>TODO Tee sinua kiinnostava haku, ja valitse haun jälkeen ulkomaisten aineistojen välilehti.<p>
  <p>TODO<small>Ulkomaiset aineistot sisältävät mm. vertaisarvioituja kokotekstejä sekä verkossa saatavilla olevia aineistoja.</small></p>
  <p><a href="<?=$this->url('primo-search');?>?lookfor=Work%20intensification&amp;type=AllFields&amp;filter%5B%5D=tlevel%3A%22online_resources%22"><i class="fa fa-search"></i> Esimerkkihaku</a>
  </div>
</div>
<div class="col-md-4">
  <div class="infobox">
    <h2>TODO Uusi lainat </h2>
    <p><a href="<?=$this->url('myresearch-checkedout')?>" class="modal-link" title="Kirjaudu sisään"><i class="fa fa-sign-in"></i> Kirjaudu sisään </a> kirjastokortilla tai Haka-tunnuksillasi.</p>
    <p>Klikkaa uusi kaikki lainat -painiketta.</p>
    <p>Kaikki uusittavissa olevat lainasi uusitaan.</p>
  </div>
</div>
            
<div class="col-md-4">
  <div class="infobox">
    <h2>Class infobox styles can be edited  variables.less file</h2>
    <ul>
      <li>@home-middle-background = background of full container</li>
      <li>@infobox-background = infobox background</li>
      <li>@infobox-border = infobox border</li>
      <li>@infobox-text-color = text default color</li>
      <li>@infobox-box-shadow = shadow of infoboxes</li>
    </ul>
  </div>
</div>
<!-- END of: finna - search/home/home-2_en-gb.phtml -->
