<!-- START of: finna - search/home/home-1.phtml -->
<? if ($template = $this->content()->findTemplateForLng('search/home/home-left')): ?>
<div class="col-sm-7 left-column-content">
  <?=$this->render($template)?>
</div>
<? endif; ?>
<? if ($template = $this->content()->findTemplateForLng('search/home/home-right')): ?>
<div class="col-sm-5 right-column-content">
  <?=$this->render($template)?>
</div>
<? endif; ?>
<!-- END of: finna - search/home/home-1.phtml -->
