<?php
return [
    'icons' => [
        'defaultSet' => 'FontAwesome6',
        'sets' => [
            /**
             * Define icon sets here.
             *
             * All sets need:
             * - 'template': which template the icon renders with
             * - 'src': the location of the relevant resource (font, css, images)
             * - 'prefix': prefix to place before each icon name for convenience
             *             (ie. fa fa- for FontAwesome, default "")
             */
            'FontAwesome6' => [
                'template' => 'font',
                'src' => 'vendor/fontawesome-free-6.6.0-web/css/all.min.css',
            ],
        ],
        'aliases' => [
            /**
             * Icons can be assigned or overridden here
             *
             * Format: 'icon' => [set:]icon[:extra_classes]
             * Icons assigned without set will use the defaultSet.
             * In order to specify extra CSS classes, you must also specify a set.
             *
             * All of the items below have been specified with FontAwesome to allow
             * for a strong inheritance safety net but this is not required.
             */
            'addthis-bookmark' => 'fa-regular fa-bookmark-o',
            'barcode' => 'fa-solid fa-barcode',
            'browzine-issue' => 'Alias:format-serial',
            'browzine-pdf' => 'fa-regular fa-file-pdf-o',
            'browzine-retraction' => 'fa-solid fa-exclamation',
            'cart' => 'fa-solid fa-briefcase',
            'cart-add' => 'fa-solid fa-plus',
            'cart-empty' => 'fa-solid fa-xmark',
            'cart-remove' => 'fa-solid fa-circle-minus',
            'cite' => 'fa-solid fa-asterisk',
            'cites' => 'fa-solid fa-asterisk',
            'cited-by' => 'fa-solid fa-asterisk',
            'collapse-close' => 'fa-solid fa-chevron-up',
            'collapse-open' => 'fa-solid fa-chevron-down',
            'cover-replacement' => 'fa-solid fa-clipboard-question',
            'currency-eur' => 'fa-solid fa-euro-sign',
            'currency-gbp' => 'fa-solid fa-sterling-sign',
            'currency-inr' => 'fa-solid fa-rupee-sign',
            'currency-jpy' => 'fa-solid fa-yen-sign',
            'currency-krw' => 'fa-solid fa-won-sign',
            'currency-rmb' => 'fa-solid fa-yen-sign',
            'currency-rub' => 'fa-solid fa-ruble-sign',
            'currency-try' => 'fa-solid fa-lira-sign',
            'currency-usd' => 'fa-solid fa-dollar-sign',
            'currency-won' => 'fa-solid fa-won-sign',
            'currency-yen' => 'fa-solid fa-yen-sign',
            'dropdown-caret' => 'fa-solid fa-caret-down',
            'export' => 'fa-solid fa-file-export',
            'external-link' => 'fa-solid fa-link',
            'facet-applied' => 'fa-solid fa-check',
            'facet-checked' => 'fa-solid fa-square-check',
            'facet-collapse' => 'fa-solid fa-caret-down',
            'facet-exclude' => 'fa-solid fa-xmark',
            'facet-expand' => 'fa-solid fa-caret-right',
            'facet-noncollapsible' => 'fa-solid fa-ban',
            'facet-unchecked' => 'fa-regular fa-square',
            'feedback' => 'fa-solid fa-envelope',
            'format-atlas' => 'fa-regular fa-map',
            'format-book' => 'fa-solid fa-book',
            'format-braille' => 'fa-regular fa-hand',
            'format-cdrom' => 'fa-regular fa-compact-disc',
            'format-chart' => 'fa-solid fa-chart-area',
            'format-chipcartridge' => 'fa-solid fa-microchip',
            'format-collage' => 'fa-regular fa-file-image',
            'format-default' => 'fa-solid fa-book',
            'format-disccartridge' => 'fa-regular fa-floppy-disk',
            'format-drawing' => 'fa-solid fa-pencil',
            'format-ebook' => 'fa-solid fa-book-atlas',
            'format-electronic' => 'fa-regular fa-file-zipper',
            'format-file' => 'fa-regular fa-file',
            'format-filmstrip' => 'fa-solid fa-film',
            'format-flashcard' => 'fa-regular fa-images',
            'format-floppydisk' => 'fa-regular fa-floppy-disk',
            'format-folder' => 'fa-regular fa-folder-closed',
            'format-globe' => 'fa-solid fa-globe',
            'format-journal' => 'fa-regular fa-newspaper',
            'format-kit' => 'fa-solid fa-toolbox',
            'format-manuscript' => 'fa-solid fa-scroll',
            'format-map' => 'fa-regular fa-map',
            'format-microfilm' => 'fa-solid fa-film',
            'format-motionpicture' => 'fa-solid fa-clapperboard',
            'format-musicalscore' => 'fa-solid fa-music',
            'format-musicrecording' => 'fa-solid fa-microphone-lines',
            'format-newspaper' => 'fa-regular fa-newspaper',
            'format-online' => 'fa-solid fa-network-wired',
            'format-painting' => 'fa-solid fa-brush',
            'format-photo' => 'fa-regular fa-image',
            'format-photonegative' => 'fa-solid fa-photo-film',
            'format-physicalobject' => 'fa-solid fa-box-archive',
            'format-print' => 'fa-regular fa-image',
            'format-sensorimage' => 'fa-solid fa-camera-retro',
            'format-serial' => 'fa fa-file-text-o',
            'format-slide' => 'fa-solid fa-film',
            'format-software' => 'fa-solid fa-laptop-code',
            'format-soundcassette' => 'fa-solid fa-headphones-simple',
            'format-sounddisc' => 'fa-solid fa-compact-disc',
            'format-soundrecording' => 'fa-solid fa-microphone-lines',
            'format-tapecartridge' => 'fa-solid fa-headphones-simple',
            'format-tapecassette' => 'fa-solid fa-headphones-simple',
            'format-tapereel' => 'fa-solid fa-tape',
            'format-transparency' => 'fa-solid fa-person-chalkboard',
            'format-unknown' => 'fa-solid fa-icons',
            'format-video' => 'fa-regular fa-circle-play',
            'format-videocartridge' => 'fa-solid fa-video',
            'format-videocassette' => 'fa-solid fa-video',
            'format-videodisc' => 'fa-solid fa-compact-disc',
            'format-videoreel' => 'fa-solid fa-tape',
            'hierarchy-collapse' => 'Alias:facet-collapse',
            'hierarchy-collection' => 'fa-regular fa-folder-open',
            'hierarchy-expand' => 'Alias:facet-expand',
            'hierarchy-noncollapsible' => 'Alias:facet-noncollapsible',
            'hierarchy-record' => 'fa-regular fa-file',
            'hierarchy-tree' => 'fa-solid fa-folder-tree',
            'lightbox-close' => 'fa-solid fa-xmark',
            'more' => 'fa-solid fa-circle-chevron-right',
            'more-rtl' => 'fa-solid fa-circle-chevron-left',
            'my-account' => 'fa-regular fa-circle-user',
            'my-account-notification' => 'Alias:notification',
            'my-account-warning' => 'Alias:warning',
            'notification' => 'fa-solid fa-bell',
            'offcanvas-hide-left' => 'fa-solid fa-angle-right',
            'offcanvas-hide-right' => 'fa-solid fa-angle-left',
            'offcanvas-show-left' => 'fa-solid fa-angles-left',
            'offcanvas-show-right' => 'fa-solid fa-angles-right',
            'options' => 'fa-solid fa-sliders',
            'overdrive' => 'fa-solid fa-cloud-arrow-down',
            'overdrive-cancel-hold' => 'Alias:ui-cancel',
            'overdrive-checkout' => 'fa-solid fa-arrow-left',
            'overdrive-checkout-rtl' => 'fa-solid fa-arrow-right',
            'overdrive-download' => 'fa-solid fa-download',
            'overdrive-edit-hold' => 'Alias:ui-edit',
            'overdrive-edit-hold-suspension' => 'fa-regular fa-hourglass-half',
            'overdrive-help' => 'fa-solid fa-circle-question',
            'overdrive-place-hold' => 'Alias:place-hold',
            'overdrive-return' => 'fa-solid fa-arrow-rotate-right',
            'overdrive-return-rtl' => 'fa-solid fa-arrow-rotate-left',
            'overdrive-sign-in' => 'fa-regular fa-user',
            'overdrive-success' => 'fa-regular fa-circle-check',
            'overdrive-suspend-hold' => 'Alias:place-hold',
            'overdrive-warning' => 'Alias:warning',
            'page-first' => 'fa-solid fa-angles-left',
            'page-first-rtl' => 'fa-solid fa-angles-right',
            'page-last' => 'fa-solid fa-angles-right',
            'page-last-rtl' => 'fa-solid fa-angles-left',
            'page-next' => 'fa-solid fa-angle-right',
            'page-next-rtl' => 'fa-solid fa-angle-left',
            'page-prev' => 'fa-solid fa-angle-left',
            'page-prev-rtl' => 'fa-solid fa-angle-right',
            'place-hold' => 'fa-solid fa-book-bookmark',
            'place-ill-request' => 'fa-solid fa-arrow-right-arrow-left',
            'place-recall' => 'fa-solid fa-arrow-right-to-bracket',
            'place-storage-retrieval' => 'fa-solid fa-dolly',
            'print' => 'fa-solid fa-print',
            'profile' => 'fa-solid fa-circle-user',
            'profile-card-delete' => 'Alias:ui-delete',
            'profile-card-edit' => 'fa-solid fa-user-pen',
            'profile-change-password' => 'fa-solid fa-key',
            'profile-delete' => 'Alias:ui-delete',
            'profile-edit' => 'fa-solid fa-user-pen',
            'profile-email' => 'fa-solid fa-at',
            'profile-sms' => 'fa-solid fa-mobile-screen',
            'qrcode' => 'fa-solid fa-qrcode',
            'rating-half' => 'fa-solid fa-star-half-stroke',
            'rating-full' => 'fa-solid fa-star',
            'search' => 'fa-solid fa-magnifying-glass',
            'search-delete' => 'Alias:ui-delete',
            'search-filter-remove' => 'fa-solid fa-xmark',
            'search-rss' => 'fa-solid fa-square-rss',
            'search-save' => 'Alias:ui-save',
            'search-schedule-alert' => 'fa-solid fa-bell',
            'send-email' => 'fa-solid fa-share-from-square',
            'send-sms' => 'fa-solid fa-paper-plane',
            'sign-in' => 'fa-solid fa-right-to-bracket',
            'sign-out' => 'fa-solid fa-person-walking-arrow-right',
            'spinner' => 'fa-solid fa-spinner:icon--spin',
            'status-available' => 'fa-solid fa-check',
            'status-pending' => 'fa-regular fa-clock',
            'status-ready' => 'fa-solid fa-bell',
            'status-unavailable' => 'fa-solid fa-xmark',
            'status-unknown' => 'fa-solid fa-circle-question',
            'tag-add' => 'Alias:ui-add',
            'tag-remove' => 'Alias:ui-remove',
            'tree-context' => 'fa-solid fa-folder-tree',
            'truncate-less' => 'fa-solid fa-arrow-up',
            'truncate-more' => 'fa-solid fa-arrow-down',
            'ui-add' => 'fa-solid fa-circle-plus',
            'ui-cancel' => 'fa-solid fa-ban',
            'ui-close' => 'fa-solid fa-xmark',
            'ui-delete' => 'fa-solid fa-trash',
            'ui-dots-menu' => 'fa-solid fa-ellipsis',
            'ui-edit' => 'fa-solid fa-pencil',
            'ui-failure' => 'fa-solid fa-xmark',
            'ui-menu' => 'fa-solid fa-bars',
            'ui-remove' => 'fa-solid fa-xmark',
            'ui-reset-search' => 'Alias:ui-remove',
            'ui-save' => 'fa-solid fa-floppy-disk',
            'ui-success' => 'fa-solid fa-check',
            'user-checked-out' => 'fa-solid fa-book',
            'user-favorites' => 'fa-solid fa-heart',
            'user-holds' => 'fa-solid fa-book-bookmark',
            'user-ill-requests' => 'fa-solid fa-arrow-right-arrow-left',
            'user-list' => 'fa-solid fa-list-check',
            'user-list-add' => 'fa-solid fa-plus',
            'user-list-delete' => 'Alias:ui-delete',
            'user-list-edit' => 'Alias:ui-edit',
            'user-list-entry-edit' => 'Alias:ui-edit',
            'user-list-remove' => 'Alias:ui-remove',
            'user-loan-history' => 'fa-solid fa-clock-rotate-left',
            'user-public-list-indicator' => 'fa-solid fa-eye',
            'user-storage-retrievals' => 'fa-solid fa-dolly',
            'view-grid' => 'fa-solid fa-border-all',
            'view-list' => 'fa-solid fa-list-ol',
            'view-visual' => 'fa-solid fa-border-none',
            'warning' => 'fa-solid fa-circle-exclamation',
        ],
    ],
];
