<!-- START of: finna - search/home/home-1.phtml -->
<?php if ($template = $this->content()->findTemplateForLng('search/home/home-left')): ?>
<div class="left-column-content">
  <?=$this->render($template)?>
</div>
<?php endif; ?>
<?php if ($template = $this->content()->findTemplateForLng('search/home/home-right')): ?>
<div class="right-column-content">
  <?=$this->render($template)?>
</div>
<?php endif; ?>
<!-- END of: finna - search/home/home-1.phtml -->
