<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2019"><b>Have you heard of our self-archiving service?</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2019"><b>Eight journals indexed in RelBib with back issues</b></a></li>
        <li><a href="https://twitter.com/rel_bib" target="_blank"><b>RelBib now on twitter:</b></a>
            <a href="https://twitter.com/rel_bib" target="_blank"><img src="<?=$this->imageLink('twitter.png')?>" height="25"></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">archive</a>
</div>
