<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2021"><b>RelBib Alerting service: Now also subscribe to journal bundles!</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2021"><b>Articles from collective works in RelBib</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#08_2020"><b>Full text search now available!</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">archive</a>
</div>
