<!-- finc: RecordDriver - SolrDico - data-license -->
<?php
/**
origin: finc/RecordDriver/SolrDico/
called by view helper/controller:
usage:
modified for finc-SolrDico:
 * finc-SolrDico specific template
configured in: {}
 */
?>
<?php /* in contrast to SolrMarc data-license.phtml, $data is an one-dimensional array and has an optional icon */ ?>
<?php $label = $this->escapeHtml($data['code']) . "&nbsp;(" . $this->escapeHtml($data['text']) . ")"; ?>
<?php ob_start() ?>
<?=$label ?>
<?php if (isset($data['icon'])): ?>
  <?php /* finc: adds alt-Tag #19697 */ ?>
  <img class="collection-data collection-licence-image" src="<?=$data['icon']?>" alt="<?=$this->transEsc('LicenseIcon')?>">
<?php endif; ?>
<?php $label = ob_get_contents();
  ob_end_clean();
?>
<?php if (isset($data['url'])): ?>
  <?= $this->externalLink($data['url'], $label, [], true) ?>
<?php else: ?>
  <?= $label ?>
<?php endif;?>
<!-- finc: RecordDriver - SolrDico - data-license - END -->
