<?php if ($this->wrapHtml):?>
  <div class="form-group">
<?php endif;?>

<?php if (count($this->captchas) == 1):?>
  <?php if ($captchaHtml = $this->captcha()->getHtmlForCaptcha($this->captchas[0])): ?>
    <label class="form-label"><?=$this->transEsc('captcha_label_single')?></label>
    <p><?=$captchaHtml?></p>
  <?php endif; ?>
<?php else:?>
  <label class="form-label"><?=$this->transEsc('captcha_label_multiple')?></label>
  <!-- nav -->
  <ul class="nav nav-tabs" role="tablist">
    <?php foreach ($this->captchas as $i => $captcha):?>
      <li class="nav-item" role="presentation">
        <button class="nav-link<?=$i == 0 ? ' active' : ''?>" type="button" role="tab" data-bs-target="#<?=$captcha->getId()?>" aria-controls="<?=$captcha->getId()?>" data-bs-toggle="tab"  aria-selected="<?=$i == 0 ? 'true' : 'false'?>">
          <?=$this->transEsc('captcha_method_' . strtolower($captcha->getId()), [], $captcha->getId())?>
        </button>
      </li>
    <?php endforeach;?>
  </ul>

  <!-- panes -->
  <div class="tab-content">
    <?php foreach ($this->captchas as $i => $captcha):?>
      <?php $active = $i == 0 ? ' active' : ''?>
      <div class="tab-content tab-pane fade show<?=$active?>" id="<?=$captcha->getId()?>">
        <?=$this->captcha()->getHtmlForCaptcha($captcha)?>
      </div>
    <?php endforeach;?>
  </div>
<?php endif;?>

<?php if ($this->wrapHtml):?>
  </div>
<?php endif;?>
