<?php
    $attribs = ['class' => 'identifierLink', 'data-instance' => $instance ?? 0];
    if (!empty($doi)) {
        $attribs['data-doi'] = $doi;
    }
    if (!empty($isbn)) {
        $attribs['data-isbn'] = $isbn;
    }
    if (!empty($issn)) {
        $attribs['data-issn'] = $issn;
    }
    echo $this->assetManager()->outputInlineScriptLink('identifierLinks.js');
?>
<span <?=$this->htmlAttributes($attribs)?>></span>
