<?php $availabilityStatus = $this->availabilityStatus(); ?>
<?php foreach ($this->locationList as $location): ?>
  <div class="groupLocation">
    <span class="<?= $this->escapeHtmlAttr($availabilityStatus->getClass($location['availability']))?>">
      <?=$this->icon($availabilityStatus->getIcon($location['availability']))?>
      <?=$this->escapeHtml($location['location'])?>
    </span>
  </div>
  <div class="groupCallnumber">
    <span><?=$location['callnumberHtml']?></span>
    <?php if (!empty($location['getThisURL'])): ?>
      <span class="getThis">
        <a rel="nofollow" data-lightbox href="<?= $location['getThisURL'] ?>"><?=$this->transEsc('Get This')?></a>
      </span>
    <?php endif; ?>
  </div>
<?php endforeach; ?>
