<?php $availabilityStatus = $this->availabilityStatus(); ?>
<?php foreach($this->locationList as $location): ?>
  <div class="groupLocation">
    <span class="<?= $availabilityStatus->getClass($location['availability'])?>">
      <?= $this->icon($availabilityStatus->getIcon($location['availability']))?>
      <?= $this->escapeHtml($location['location'])?>
    </span>
  </div>
  <div class="groupCallnumber">
    <?= $location['callnumber']?>
  </div>
<?php endforeach; ?>