<table class="table table-condensed">
  <tr>
    <th><?=$this->transEsc('Location')?></th>
    <th><?=$this->transEsc('Call Number')?></th>
    <th><?=$this->transEsc('Status')?></th>
  </tr>
  <?php $i = 0; ?>
  <?php foreach ($this->statusItems as $item): ?>
    <?php
      if (++$i == 5) {
        // Show no more than 5 items
        break;
      }
      $callNumPrefix = !empty($item['callnumber_prefix']) ? $item['callnumber_prefix'] . ' ' : '';
    ?>
    <tr>
      <td class="fullLocation">
        <?php $locationText = $this->transEscWithPrefix('location_', $item['location']); ?>
        <?php if ($item['locationhref'] ?? false): ?>
          <a href="<?=$item['locationhref']?>" target="_blank"><?=$locationText?></a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
      </td>
      <td class="fullCallnumber">
        <?php if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($item['callnumber']) ?>"><?=$this->escapeHtml($callNumPrefix)?><?=$this->escapeHtml($item['callnumber'])?></a>
        <?php else: ?>
          <?=$this->escapeHtml($callNumPrefix)?><?=$this->escapeHtml($item['callnumber'])?>
        <?php endif; ?>
      </td>
      <td class="fullAvailability">
        <?php $availabilityStatus = $item['availability']; ?>
          <?php
            $statusClass = $this->availabilityStatus()->getClass($availabilityStatus);
            if ($availabilityStatus->isAvailable() && $item['reserve'] === 'Y') {
              $statusDescription = 'On Reserve';
            } else {
              $statusDescription = $availabilityStatus->getStatusDescription();
            }
          ?>
          <span class="<?=$this->escapeHtmlAttr($statusClass)?>"><?=$this->transEsc($statusDescription)?></span>
      </td>
    </tr>
  <?php endforeach; ?>
<?php if (count($this->statusItems) > 5): ?>
  <tr><td colspan="3"><a href="<?=$this->url('record', ['id' => $this->statusItems[0]['id']], ['query' => ['sid' => $this->searchId]])?>"><?=count($this->statusItems) - 5?> <?=$this->transEsc('more_ellipsis')?></a></td></tr>
<?php endif; ?>
</table>
