<?php
  $databases = $this->recommend->getResults();
  $useGroupedResults = $this->recommend->useGroupedResults();
  $linkToAll = $this->recommend->getLinkToAllDatabases();
?>
<div class="databases">
  <?php if (!empty($databases)): ?>
    <h2><?=$this->transEsc('databases_recommend_heading')?></h2>
    <?php if ($this->transEsc('databases_recommend_intro', [], '')): ?>
      <p><?=$this->transEsc('databases_recommend_intro')?></p>
    <?php endif; ?>
    <?php if ($useGroupedResults): ?>
      <?php foreach ($databases as $group => $databasesGroup): ?>
        <?php if (!empty($databasesGroup)): ?>
          <h3><?=$this->transEsc('databases_recommend_group_' . $group, ['%%query%%' => $params->getQuery()->getAllTerms()])?></h3>
          <?=$this->render('Recommend/Databases/database-list.phtml', ['databases' => $databasesGroup]); ?>
        <?php endif; ?>
      <?php endforeach; ?>
    <?php else: ?>
      <?=$this->render('Recommend/Databases/database-list.phtml', compact('databases')); ?>
    <?php endif; ?>
    <?php if ($linkToAll): ?>
      <li class="list-group-item">
        <span>
          <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($linkToAll))?>" class="title icon-link" target="_blank">
            <?=$this->icon('external-link', 'icon-link__icon') ?>
            <span class="icon-link__label"><?=$this->transEsc('databases_recommend_link_to_all')?></span>
          </a>
        </span>
      </li>
    <?php endif; ?>
  <?php endif ?>
</div>
