<?php
    // Set up Javascript for use below:
    $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
        . "VuFind.loadHtml(\$('#EuropeanaDeferredRecommend'), url);";
?>
<div id="EuropeanaDeferredRecommend">
    <p><?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?></p>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
