<?php
    $expandFacetSet = $this->recommend->getExpandedSet();
    // Get empty search object to use as basis for parameter generation below:
    $blankResults = $this->recommend->getEmptyResults();
    $cloudLimit = $this->recommend->getFacetLimit();
?>
<?php if ($expandFacetSet): ?>
  <div class="sidegroup">
    <?php foreach ($expandFacetSet as $title => $facets): ?>
      <dl class="narrowList navmenu">
        <dt><?=$this->transEsc($facets['label']) ?></dt>
        <?php
        foreach ($facets['list'] as $i => $facetItem) {
            if ($i < $cloudLimit) {
                echo(($i == 0) ? '' : ', ')
                    . '<a href="' . $blankResults->getUrlQuery()->addFacet($title, $facetItem['value']) . '">'
                    . $this->escapeHtml($facetItem['displayText'])
                    . '</a> (' . $this->escapeHtml($facetItem['count']) . ')';
            } else {
                echo ', ' . $this->transEsc('eol_ellipsis');
                break;
            }
        }
        ?>
      </dl>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
