<h1>IxTheo-Classification</h1>
<a rel="license"
   href="http://creativecommons.org/publicdomain/zero/1.0/">
  <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
</a>
Index Theologicus (IxTheo) provides the IxTheo classification for free use using the <a href="http://creativecommons.org/publicdomain/zero/1.0/" target="_blank">CC0 1.0</a> licence</p>

<a href="/classification" target="_blank">IxTheo Classification</a> is a facet classification system consisting of 13 main groups and 139 classes, that are used for the classification in IxTheo since 1995 (c.f. <a href=/docs/ixtheo-erschliessungskonzept.pdf target="_blank">Erschließungskonzept</a> [in German]):</p>

<? $helper = $this->getHelperPluginManager()->get('IxTheo');
   $translator = $this->plugin('translate')->getTranslator();
   $list = $helper->getNestedIxtheoClassificationArray($translator);
   echo $this->htmlList($list, false, false, false);
?>




