<!-- START of: finna - Auth/Database/login.phtml -->
<?php $account = $this->auth()->getManager(); ?>
<div>
  <form method="post" class="form-vertical" action="<?=$this->url('myresearch-home')?>" name="loginForm">
    <div class="login-col">
      <?=$this->auth()->getLoginFields()?>
      <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
      <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>" />
      <div class="form-group">
        <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">
      </div>
      <div class="form-group">
        <?php if ($account->supportsCreation()): ?>
          <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
        <?php endif; ?>
        <?php if ($account->supportsRecovery()): ?>
          <a class="btn btn-link" href="<?=$this->url('myresearch-recover') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Forgot Password')?></a>
        <?php endif; ?>
      </div>
    </div>
  </form>
  <div class="login-col">
    <i class="fa fa-info3" aria-hidden="true"></i>
    <div class="login-description">
      <p class="login-info">
        <?=$this->translate('login_desc_local_html') ?>
      </p>
    </div>
    <div class="clearfix"></div>
    <?php
      $language = $this->layout()->userLang;
      if (!in_array($language, ['fi', 'sv', 'en-gb'])) {
        $language = 'en-gb';
      }
    ?>
    <?=$this->partial("Auth/Database/terms_$language.phtml") ?>
  </div>
</div>
<div class="clearfix"></div>
<!-- END of: finna - Auth/Database/login.phtml -->
