<!-- START of: finna - Auth/Database/newpassword.phtml -->
<?php if (isset($this->username)): ?>
  <?php $parts = explode(':', $this->username);
  $displayName = end($parts); ?>
  <div class="form-group">
    <label class="form-label"><?=$this->transEsc('Username') ?>:</label>
    <p class="form-control-static"><?=$this->escapeHtmlAttr($displayName) ?></p>
  </div>
<?php endif; ?>
<?php if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <div class="form-group">
    <label class="form-label"><?=$this->transEsc('old_password') ?>:</label>
    <input type="password" name="oldpwd" class="form-control">
    <div class="help-block with-errors"></div>
  </div>
<?php endif; ?>
<div class="form-group">
  <label class="form-label"><?=$this->transEsc('new_password') ?>:</label>
  <?php
    $attrs = $this->htmlAttributes($this->passwordPolicy['inputAttrs'] ?? []);
    $attrs->merge(['id' => 'password', 'type' => 'password', 'name' => 'password', 'class' => 'form-control', 'autocomplete' => 'new-password']);
  ?>
  <input <?=$attrs?> required>
  <?php if ($hint = $this->passwordPolicy['hint'] ?? null): ?>
    <div class="help-block"><?=$this->transEsc($hint) ?></div>
  <?php endif; ?>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="form-label"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <input type="password" name="password2" id="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>" autocomplete="new-password">
  <div class="help-block with-errors"></div>
</div>
<!-- END of: finna - Auth/Database/newpassword.phtml -->
