<?php if (!$this->translationEmpty('recovery_help_html')): ?>
  <p><?=$this->translate('recovery_help_html') ?></p>
<?php endif; ?>
<div class="form-group">
  <label class="form-label" for="recovery_username"><?=$this->transEsc('recovery_by_username') ?>:</label>
  <input type="text" name="username" id="recovery_username" class="form-control">
</div>
<div class="form-group">
  <label class="form-label" for="recovery_email"><?=$this->transEsc('recovery_by_email') ?>:</label>
  <input type="email" name="email" id="recovery_email" class="form-control">
</div>
<div class="form-group">
<?=$this->captcha()->html($this->useCaptcha) ?>
</div>
<div class="form-group">
  <input class="btn btn-primary" name="submitButton" type="submit" value="<?=$this->transEscAttr('Recover Account') ?>">
</div>