<h1>Hilfe zum Alphabetischen Browsen</h1>
<p>Hier können Sie bestimmen, an welcher Stelle des Alphabets Sie in das Browsen einsteigen wollen.
   Nach der Auswahl des Browsing-Aspektes geben Sie den Buchstaben ein, ab dem das Browsen starten soll.</p>
<ul>
    <li>Beispiel: Wählen Sie den Aspekt „Nach Thema“ und geben Sie ein: ab „rel“. Es werden dann alle Schlagwörter 
       aufgelistet, die mit rel beginnen.
    </li>
</ul>
<p>Das alphabetische Browsen kann auch dann hilfreich sein, wenn Sie sich bei der Schreibweise eines Autorennamen nicht sicher sind.</p>
<ul>
    <li>
    Beispiel: Wählen Sie den Aspekt „Nach Verfasser“ und geben Sie ein: ab „Tr“. Es werden dann alle Verfasser 
    aufgelistet, deren Nachnamen mit der Buchstabenfolge Tr beginnen.
    </li>
</ul>
