<ul class="nav nav-pills">
    <li>
        <a href="<?=$this->advSearchUrl . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $this->hiddenFilterParams)?>"
           class="btn btn-link" role="button"
           rel="nofollow"><?= $this->transEsc("Advanced Search") ?></a>
    </li>

    <li class="dropdown">
        <a class="btn btn-light dropdown-toggle"
                type="button"
                id="dropdownMenuButton"
                data-toggle="dropdown"
                aria-haspopup="true"
                aria-expanded="false">
            <?= $this->transEsc('Browse') ?>
            <span class="caret"></span>
        </a>

        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton">
            <!-- IxTheo-specific keywordchainsearch is skipped here -->
            <li><a class="dropdown-item" href="<?= $this->url('browse-home') ?>"><?= $this->transEsc('Browse the Catalog') ?></a></li>
            <li><a class="dropdown-item" href="<?= $this->url('alphabrowse-home') ?>"><?= $this->transEsc('Browse Alphabetically') ?></a></li>
        </ul>
    </li>

    <li>
        <a href="<?=$this->url('search-history')?>"
           class="btn btn-light" role="button"
           rel="nofollow"><?=$this->transEsc('Search History')?></a>
    </li>

    <li>
        <a href="<?=$this->url('search-newitem')?>"
           class="btn btn-light" role="button"
           rel="nofollow"><?=$this->transEsc('New Items')?></a>
    </li>
</ul>
