<?php
  $consentGiven = (bool)$this->cookieConsent()->getConsentInformation();
  $consentConfigJson = json_encode($this->consentConfig);
  $cookieConsentDivAttrs = [
    'class' => 'cookie-consent js-cookie-consent',
    'role' => 'region',
    'aria-label' => $this->translate('Cookie Settings'),
    'tabindex' => '-1',
  ];
  if ($consentGiven) {
    $cookieConsentDivAttrs['class'] .= ' hidden';
  } else {
    $cookieConsentDivAttrs['class'] .= ' js-loaded';
    // Make sure we get focus even if not the first in DOM:
    $cookieConsentDivAttrs['data-focus-on-load'] = 'important';
  }
?>
<div class="cookie-consent-wrapper">
  <div<?=$this->htmlAttributes($cookieConsentDivAttrs)?>>
    <?php if (!$consentGiven): ?>
      <?=$this->render('CookieConsent/cookie-consent-overlay.phtml')?>
      <?php // Set focus for discoverability with screen readers: ?>
      <?=$this->assetManager()->outputInlineScriptString('document.querySelector(".js-cookie-consent").focus();'); ?>
    <?php else: ?>
      <div class="cookie-consent__overlay">
        <div class="load-indicator">
          <?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?>
        </div>
      </div>
    <?php endif; ?>
  </div>
</div>
<?php echo $this->assetManager()->outputInlineScriptString("window.addEventListener('load', function() { VuFind.cookie.setupConsent($consentConfigJson); });");
