<? if((isset($this->showBulkOptions)  && $this->showBulkOptions)
   || (isset($this->showCartControls) && $this->showCartControls)): ?>
  <div class="bulkActionButtons">
    <input type="checkbox" class="selectAllCheckboxes floatleft" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/> <label class="floatleft" for="<?=$this->idPrefix?>addFormCheckboxSelectAll"><?=$this->transEsc('select_page')?></label>
    <span class="floatleft">&nbsp;|&nbsp;</span>
    <? if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <input id="ribbon-email" type="submit" name="email" title="<?=$this->transEsc('bookbag_email_selected')?>" value="<?=$this->transEsc('Email')?>"/>
        <? $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
          <input id="ribbon-export" type="submit" name="export" title="<?=$this->transEsc('bookbag_export_selected')?>" value="<?=$this->transEsc('Export')?>"/>
        <? endif; ?>
        <input id="ribbon-print" type="submit" name="print" title="<?=$this->transEsc('bookbag_print_selected')?>" value="<?=$this->transEsc('Print')?>"/>
        <? if ($this->userlist()->getMode() !== 'disabled'): ?>
          <input id="ribbon-save" type="submit" name="saveCart" title="<?=$this->transEsc('bookbag_save_selected')?>" value="<?=$this->transEsc('Save')?>"/>
        <? endif; ?>
      <? endif; ?>
      <? if (isset($this->showCartControls) && $this->showCartControls): ?>
        <input id="<?=$this->idPrefix?>updateCart" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
      <? endif; ?>
    <div class="clear"></div>
  </div>
<? endif; ?>
