<?
    // Set page title.
    $this->headTitle($this->translate('Email this Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        '<em>' . $this->transEsc('Email this Search') . '</em>';
?>
<?=$this->flashmessages()?>
<form action="" method="post"  name="emailSearch">
    <input type="hidden" name="url" value="<?=$this->escapeHtml($this->url)?>" />
    <label class="displayBlock" for="email_to"><?=$this->transEsc('To')?>:</label>
    <input id="email_to" type="text" name="to" value="<?=isset($this->to) ? $this->to : ''?>" size="40" class="mainFocus <?=$this->jqueryValidation(array('required'=>'This field is required', 'email'=>'Email address is invalid'))?>"/>
    <? if (!$this->disableFrom): ?>
      <label class="displayBlock" for="email_from"><?=$this->transEsc('From')?>:</label>
      <input id="email_from" type="text" name="from" value="<?=isset($this->from) ? $this->from : ''?>" size="40" class="<?=$this->jqueryValidation(array('required'=>'This field is required', 'email'=>'Email address is invalid'))?>"/>
    <? endif; ?>
    <label class="displayBlock" for="email_message"><?=$this->transEsc('Message')?>:</label>
    <textarea id="email_message" name="message" rows="3" cols="40"><?=isset($this->message) ? $this->message : ''?></textarea>
    <br/>
    <input class="button" type="submit" name="submit" value="<?=$this->transEsc('Send')?>"/>
</form>
