<?
    // Set page title.
    $this->headTitle($this->translate('Email this Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        '<em>' . $this->transEsc('Email this Search') . '</em>';
?>
<?=$this->flashmessages()?>
<form action="" method="post"  name="emailSearch">
    <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
    <?=$this->render('Helpers/email-form-fields.phtml')?>
</form>
