<table class="datagrid" width="100%">
  <tr>
    <th width="25%"><?=$this->transEsc("history_time")?></th>
    <th width="30%"><?=$this->transEsc("history_search")?></th>
    <th width="30%"><?=$this->transEsc("history_limits")?></th>
    <th width="10%"><?=$this->transEsc("history_results")?></th>
    <th width="5%"><?=$this->transEsc($this->showSaved ? "history_delete" : "history_save")?></th>
  </tr>
  <? foreach (($this->showSaved ? array_reverse($this->saved) : array_reverse($this->unsaved)) as $iteration => $info): ?>
    <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
      <td><?=$this->escapeHtml(date("g:ia, jS M y", $info->getStartTime()))?></td>
      <td>
        <?=$this->historylabel($info->getParams()->getSearchClassId())?>
        <a href="<?=$this->url($info->getOptions()->getSearchAction()) . $info->getUrlQuery()->getParams()?>"><?
          $desc = $info->getParams()->getDisplayQuery();
          echo empty($desc) ? $this->transEsc("history_empty_search") : $this->escapeHtml($desc);
        ?></a>
      </td>
      <td>
        <? $info->getParams()->activateAllFacets(); foreach ($info->getParams()->getFilterList() as $field => $filters): ?>
          <? foreach ($filters as $filter): ?>
            <strong><?=$this->transEsc($field)?></strong>: <?=$this->escapeHtml($filter['displayText'])?><br/>
          <? endforeach; ?>
        <? endforeach; ?>
      </td>
      <td><?=$this->escapeHtml(number_format($info->getResultTotal()))?></td>
      <td>
        <? if ($this->showSaved): ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($info->getSearchId())?>&amp;mode=history" class="delete"><?=$this->transEsc("history_delete_link")?></a>
        <? else: ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($info->getSearchId())?>&amp;mode=history" class="add"><?=$this->transEsc("history_save_link")?></a>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>
