<div id="visualResults">
<p><?=$this->transEsc('A visualization of your search results should appear here. If it does not, please check to be sure that you have enabled Javascript in your browser.')?></p>

<p><?=$this->transEsc('This visualization does not work in Internet Explorer 8; if you have Internet Explorer 8, please upgrade to Internet Explorer 9 or open this page in a different browser.')?></p>
</div>

<div id="viz-instructions">
<p><strong><a href="<?=$this->url('help-home', array(), array('query' => array('topic' => 'visualization')))?>" class="visualizationHelp"><?=$this->transEsc('What am I looking at?')?></a></strong></p>
</div>

