<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId,
        isset($this->searchIndex) ? $this->searchIndex : null,
        $options
    );
    $handlerCount = count($handlers);
    $basicSearch = $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>
<div class="searchform">
  <? $searchTabs = $this->searchtabs($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType); ?>
  <? if (count($searchTabs) > 0): ?>
    <ul class="searchTabNav">
    <? foreach ($searchTabs as $tab): ?>
      <li<?=$tab['selected'] ? ' class="active"' : ''?>>
        <?
          if (!$tab['selected']) {
            echo '<a href="' . $this->escapeHtml($tab['url']) . '">';
          }
          echo $this->transEsc($tab['label']);
          if (!$tab['selected']) {
            echo '</a>';
          }
        ?>
      </li>
    <? endforeach; ?>
    </ul>
  <? endif; ?>
  <? if ($this->searchType == 'advanced'): ?>
    <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtml($this->searchId)?>" class="small"><?=$this->transEsc("Edit this Advanced Search")?></a> |
    <a href="<?=$this->url($advSearch)?>" class="small"><?=$this->transEsc("Start a new Advanced Search")?></a> |
    <a href="<?=$this->url($searchHome)?>" class="small"><?=$this->transEsc("Start a new Basic Search")?></a>
    <br/><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"
  <? else: ?>
    <form method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" id="searchForm" class="search">
      <label for="searchForm_lookfor" class="offscreen"><?=$this->transEsc("Your search terms")?></label>
      <input id="searchForm_lookfor" type="text" name="lookfor" size="40" value="<?=$this->escapeHtml($this->lookfor)?>"<?=$options->autocompleteEnabled() ? ' class="autocomplete searcher:' . $this->escapeHtml($this->searchClassId) . ' typeSelector:searchForm_type"' : ''?>/>
      <label for="searchForm_type" class="offscreen"><?=$this->transEsc("Search Type")?></label>
      <? if ($handlerCount > 1): ?>
        <select id="searchForm_type" name="type" data-native-menu="false">
          <? foreach ($handlers as $handler): ?>
            <option value="<?=$this->escapeHtml($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$this->transEsc($handler['label'])?></option>
          <? endforeach; ?>
        </select>
      <? elseif ($handlerCount == 1): ?>
        <input type="hidden" name="type" value="<?=$this->escapeHtml($handlers[0]['value'])?>" />
      <? endif; ?>
      <input type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
      <? if ($advSearch): ?>
        <a href="<?=$this->url($advSearch)?>" class="small"><?=$this->transEsc("Advanced")?></a>
      <? endif; ?>

      <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
        <?
        $selectedShards = isset($this->selectedShards)
            ? $this->selectedShards : $options->getDefaultSelectedShards();
        ?>
        <br />
        <? foreach ($shards as $shard => $val): ?>
          <? $isSelected = in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtml($shard)?>' /> <?=$this->transEsc($shard)?>
        <? endforeach; ?>
      <? endif; ?>
      <?
        $filterDetails = $this->searchbox()->getFilterDetails(
            isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
            isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
        );
      ?>
      <? if (!empty($filterDetails)): ?>
        <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
        <div class="keepFilters">
          <input type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/> <label for="searchFormKeepFilters"><?=$this->transEsc("basic_search_keep_filters")?></label>
          <div class="offscreen">
            <? foreach ($filterDetails as $current): ?>
              <input id="<?=$this->escapeHtml($current['id'])?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escapeHtml($current['value'])?>" />
              <label for="<?=$this->escapeHtml($current['id'])?>"><?=$this->escapeHtml($current['value'])?></label>
            <? endforeach; ?>
          </div>
        </div>
      <? endif; ?>
      <?
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escapeHtml($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escapeHtml($lastSort) . '" />';
      }
      ?>
    </form>
    <script type="text/javascript">$("#searchForm_lookfor").focus()</script>
  <? endif; ?>
</div>
