<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only">Toggle navigation</span>
    <i class="fa fa-bars"></i>
  </button>
  <a class="navbar-brand lang-<?=$this->layout()->userLang ?>" href="<?=$this->url('home')?>">RelBib</a>
</div>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <nav>
      <ul class="nav navbar-nav navbar-right flip">
        <li role="presentation" class="active"><a href="<?=$this->url('home')?>"><?=$this->transEsc('Home');?></a></li>
        <li role="presentation" class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown"  href="#" role="button" aria-haspopup="true" aria-expanded="false"><?=$this->transEsc('About');?> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="/Impressum"><?=$this->transEsc('Impressum');?></a></li>
            <li><a target="_blank" href="https://www.uni-tuebingen.de/impressum/datenschutzerklaerung.html"><?=$this->transEsc('Privacy Protection');?></a></li>
          </ul>
        </li>
        <li>
            <a href="/A-Z">RelBib A-Z</a>
        </li>

        <? if ($this->feedback()->tabEnabled()): ?>
          <li>
            <a id="feedbackLink" class="modal-link" href="<?=$this->url('feedback-home') ?>"><i class="fa fa-envelope"></i> <?=$this->transEsc("Feedback")?></a>
          </li>
        <? endif; ?>
        <? $cart = $this->cart(); if ($cart->isActive()): ?>
          <li id="cartSummary">
            <a id="cartItems" class="modal-link" title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-home')?>"><i class="fa fa-suitcase"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
          </li>
        <? endif; ?>

        <? if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="modal-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
          </li>
          <li class="logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
            <a href="<?=$this->url('myresearch-logout')?>" class="modal-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
          </li>
          <li id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
            <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
              <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
            <? else: ?>
              <a href="<?=$this->url('myresearch-userlogin')?>" class="modal-link" data-lightbox title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
            <? endif; ?>
          </li>
        <? endif; ?>

        <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
          <li class="dropdown">
            <form method="post" name="langForm" id="langForm">
              <input type="hidden" name="mylang"/>
            </form>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Language")?> <b class="caret"></b></a>
            <ul class="dropdown-menu">
              <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                <li<?=$this->layout()->userLang == $langCode ? ' class="active"' : ''?>><a href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()"><?=$this->displayLanguageOption($langName)?></a></li>
              <? endforeach; ?>
            </ul>
          </li>
        <? endif; ?>
      </ul>
    </nav>
  </div>
<? endif; ?>
  <section class="visible-lg section-home">
    <div class="panel-home">
      <br />
      <br />
      <h1>
        <a href="<?=$this->url('home')?>" title="<?=$this->transEsc("Religionswissenschaftliche Bibliographie")?>"><?=$this->transEsc("Religionswissenschaftliche Bibliographie")?></a>
      </h1>
      <small><?=$this->transEsc("relbib_subtitle")?></small>
      <br />
      <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
        <div class="alert alert-warning">
          <h2><?= $this->transEsc('ils_offline_title') ?></h2>

          <p><strong><?= $this->transEsc('ils_offline_status') ?></strong></p>

          <p><?= $this->transEsc('ils_offline_home_message') ?></p>
          <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
          <p><a href="mailto:<?= $supportEmail ?>"><?= $supportEmail ?></a></p>
        </div>
      <? endif; ?>
      <div class="clearfix searchbox_home" role="search">
        <?=$this->layout()->searchbox ?>
      </div>
    </div>
  </section>
