<?php
  // Set page title.
  $this->headTitle($this->translate('Email Record'));

  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($this->translate('Email Record'), active: true);
?>
<h2><?=$this->transEsc('Email Record') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
<form class="form-record-email" method="post" action="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email')) ?>" name="emailRecord">
  <?=$this->flashmessages()?>
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?=$this->render('Helpers/email-form-fields.phtml')?>
</form>
