<?php
# Usually this is displayed in a modal, but if it is not (coming back from login), we don't want the search box.
$this->globals()['searchbox'] = false;
$templates = $this->getThisLoader->getSubTemplates();
$commentTemplateName = $this->getThisLoader->commentTemplateName();

$recordTitle = $this->driver->getRawData()['title_full'] ?? '';
echo $this->component(
    'page-title',
    [
        'title' => $this->translate('Get This') . ' : <span class="title-in-heading">' . $recordTitle . '</span>',
        'level' => 1,
        'headTitle' => $this->translate('Get This') . ' : ' . $recordTitle,
        'escape' => false,
    ]
);

foreach ($templates as $template) {
    if ($commentTemplateName) {
        echo '<!-- Get-This: ' . $template . ' -->';
    }
    echo $this->context()->renderInContext(
        'record/get-this/' . $template . '.phtml',
        ['getThisParams' => $this->getThisLoader->getSubTemplateParams($template)]
    );
}
