<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($this->translate('permanent_link'), active: true);

  // Collect permalink data:
  $link = $this->serverUrl() . $this->recordLinker()->getUrl($this->driver, ['excludeSearchId' => true]);
?>
<?=
  // Set page title and heading.
  $this->component('page-title', [
    'title' => $this->translate('permanent_link'),
    'level' => 1,
  ])
?>
<div class="copy-to-clipboard-container">
  <pre id="permalink"><?=$this->escapeHtml($link)?></pre>
  <?=$this->copyToClipboardButton('#permalink');?>
</div>
