<?php
  // Set page title.
  $this->headTitle($this->translate('Text this'));
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'vendor/libphonenumber.js', 'SET');

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
    . '<li>' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Text this') . '</li>';
?>
<h2><?=$this->transEsc('Text this') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
<form method="post" name="smsRecord" class="form-record-sms">
  <?=$this->flashmessages()?>
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
  <div class="form-group">
    <label class="control-label" for="sms_to"><?=$this->transEsc('Number')?>:</label>
    <input id="sms_to" type="tel" name="to" value="<?=$this->escapeHtmlAttr($this->to)?>" placeholder="<?=$this->transEscAttr('sms_phone_number')?>" class="form-control" required<?=!empty($this->validation) ? ' data-validator-region="' . $this->escapeHtmlAttr($this->validation) . '"' : ''?>>
  </div>
  <?php if (is_array($this->carriers) && count($this->carriers) > 1): ?>
    <div class="form-group">
      <label class="control-label" for="sms_provider"><?=$this->transEsc('Provider')?>:</label>
      <select id="sms_provider" name="provider" class="form-control">
        <option selected="selected" value=""><?=$this->transEsc('Select your carrier')?></option>
        <?php foreach ($this->carriers as $val => $details): ?>
          <option value="<?=$this->escapeHtmlAttr($val)?>"<?=$val === $this->provider ? ' selected' : ''?>><?=$this->escapeHtml($details['name'])?></option>
        <?php endforeach; ?>
      </select>
    </div>
  <?php else: ?>
    <?php $keys = is_array($this->carriers) ? array_keys($this->carriers) : []; ?>
    <input type="hidden" name="provider" value="<?=$this->escapeHtmlAttr($keys[0] ?? '')?>">
  <?php endif; ?>
  <?=$this->captcha()->html($this->useCaptcha) ?>
  <div class="form-group">
    <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Send Text')?>">
  </div>
</form>
