<?php
  // Set a default page title; this will usually be overridden when a tab is
  // loaded, but it may be useful if there are no tabs, or when tabs are loaded
  // via AJAX:
  $this->headTitle($this->driver->getBreadcrumb());

  // Set up standard record scripts:
  $this->headScript()->appendFile('record.js');
  $this->headScript()->appendFile('check_save_statuses.js');
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add any extra scripts the tabs require:
  foreach ($this->tabsExtraScripts as $script) {
    $this->headScript()->appendFile($script);
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLinker()->getActionUrl($this->driver, 'RDF', options: ['excludeSearchId' => true]), 'application/rdf+xml', 'RDF Representation');
  }

  // Add canonical header link for SEO:
  $canonicalUrl = $this->recordLinker()->getUrl($this->driver, ['excludeSearchId' => true]);
  $this->headLink(['rel' => 'canonical', 'href' => $canonicalUrl]);

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ') .
    '<li class="active" aria-current="page">' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> ';
  $this->layout()->title = $this->driver->getShortTitle();
?>

<?php if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <?=$this->render('record/prev-next.phtml'); ?>
<?php endif; ?>

<?=$this->record($this->driver)->getToolbar()?>

<div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?php $sidebarList = $this->related()->getList($this->driver); ?>
  <div class="<?=$this->layoutClass('mainbody', !empty($sidebarList))?><?=empty($sidebarList) ? ' solo' : '' ?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" class="hiddenSource">
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCoreMetadata()?>

    <?php if (count($this->tabs) > 0): ?>
      <a id="tabnav"></a>
      <div class="record-tabs">
        <ul class="nav nav-tabs" role="tablist">
          <?php foreach ($this->tabs as $tab => $obj): ?>
            <?php
              $desc = $obj->getDescription();
              $tabName = preg_replace("/\W/", '-', strtolower($tab));
              $tabClasses = [ 'record-tab', $tabName ];
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tabClasses[] = 'active';
                }
                $tabClasses[] = 'initiallyActive';
                $activeTabName = $tabName;
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) {
                $tabClasses[] = 'hidden';
              }
              if (!$obj->supportsAjax()) {
                $tabClasses[] = 'noajax';
              }
            ?>
            <li role="presentation" id="record-tab-<?=$this->escapeHtmlAttr($tabName)?>" class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$this->escapeHtmlAttr($tabName)?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
              <a role="tab" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, $tab))?>#tabnav" data-bs-target=".tab-pane.<?=$this->escapeHtmlAttr($tabName)?>" data-lightbox-ignore>
                <?=$this->transEsc($desc)?>
              </a>
            </li>
          <?php endforeach; ?>
        </ul>

        <div class="tab-content">
          <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
            <div role="tabpanel" class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab" aria-labelledby="record-tab-<?=$this->escapeHtmlAttr($activeTabName ?? '')?>">
              <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
            </div>
          <?php endif; ?>
        </div>
      </div>
    <?php endif; ?>

    <?=$this->driver->supportsCoinsOpenURL() ? '<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($this->driver->getCoinsOpenURL()) . '"></span>' : ''?>
  </div>

  <?php if ($sidebarList): ?>
    <div class="<?=$this->layoutClass('sidebar')?>" role="region" aria-label="<?=$this->translate('Related Items')?>">
      <?php foreach ($sidebarList as $current): ?>
        <?=$this->related()->render($current)?>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>
</div>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET'); ?>
