<? $this->headTitle($this->translate('FAQ')); ?>
<? foreach ($topics as $topic): ?>
  <? if ($help = $this->helpText()->render($topic, ['panelClass' => 'panel-default'], "FAQTranslations")): ?>
    <? foreach ($this->helpText()->getWarnings() as $warning): ?>
      <p class="alert alert-warning"><?=$this->transEsc($warning)?></p>
    <? endforeach; ?>
    <?=$help?>
  <? else: ?>
    <p class="alert alert-danger"><?=$this->transEsc('help_page_missing')?></p>
  <? endif; ?>
<? endforeach; ?>
<?
if (empty($topics)) {
  ?><p class="alert alert-danger"><?=$this->transEsc('help_page_missing')?></p><?
}
?>
