#!/bin/bash
#
# Git hook for updating TueFind configuration
# (only if TueFind is already installed)
#
if [ -z "$TUEFIND_FLAVOUR" ]; then
    exit 0
fi

CHANGED_FILES="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
DIR="$(dirname $(readlink --canonicalize "$0"))"

# $1 - command
# $2 - grep pattern (extended regexp)
# $3 - message
run_if_file_changed() {
    echo "$CHANGED_FILES" | grep --extended-regexp --quiet "$2" && echo "$3" && eval "$1"
}

echo "Updating TueFind configuration (git hook post-merge)"
run_if_file_changed "grunt less" "\.less" "LESS files changed, rebuilding CSS files..."
run_if_file_changed "$DIR/../../update_tuefind_config.sh" "/(schema[^/]*\.xml|solrconfig[^/]*\.xml|marc[^/]*\.properties|[^/]*\.jar)" "Solr configuration changed, rebuilding config & restarting solr..."
$DIR/../../clean_vufind_cache.sh
