<?php
if ($callNumberData = $this->getThis->getCallNumber()) {
    $rawCallNumber = $callNumberData['text'] ?? '';
    $callNumber = ($callNumberData['translate'] ?? false) ? $this->translate($rawCallNumber) : $this->escapeHtml($rawCallNumber);
} else {
    $callNumber = $this->translate('data_unavailable');
}
?>
<div>
  <p>
    <strong><?= $this->transEsc('Title') ?> :</strong>
    <?=$this->escapeHtml($this->driver->getRawData()['title_full'] ?? '') ?>
  </p>
  <p>
    <strong><?= $this->transEsc('Call Number') ?> :</strong>
    <span><?= $callNumber ?></span>
    <?php if ($copyNumber = $this->getThis->getCopyNumber()): ?>
      <span> (<?= $this->transEscAttr('copy_number', ['%%number%%' => $copyNumber]) ?>)</span>
    <?php endif; ?>
  </p>
  <?php if ($location = $this->getThis->getLocation()): ?>
    <p>
      <strong><?= $this->transEsc('Location') ?> :</strong>
      <span><?=$this->escapeHtml($location) ?></span>
    </p>
  <?php endif; ?>
  <p>
    <strong><?= $this->transEsc('Status') ?> :</strong>
    <?= $this->transEsc($this->getThis->getStatus()) ?>
  </p>
  <hr/>
  <?=$this->render('record/get-this/place-request.phtml')?>
</div>
