<?php
$selectedItem = $this->getThis->getItem();
$items = $this->getThis->getItems();

$getDisplay = function ($view, $item) {
    $item['item_id'] ??= null;
    $location = $view->getThis->getLocation($item['item_id']);
    if (!empty($location)) {
        $location .= ': ';
    } else {
        $location = '';
    }
    $copyNumber = $view->getThis->getCopyNumber($item['item_id']);
    if (!empty($copyNumber)) {
        $copyNumber = $view->transEscAttr('copy_number', ['%%number%%' => $copyNumber]) . ' ';
    } else {
        $copyNumber = '';
    }
    if ($callNumberData = $view->getThis->getCallNumber($item['item_id'])) {
        $rawCallNumber = $callNumberData['text'] ?? '';
        $callNumber = ($callNumberData['translate'] ?? false) ? $view->translate($rawCallNumber) : $view->escapeHtml($rawCallNumber);
        $callNumber = '(' . $callNumber . ')';
    } else {
        $callNumber = '';
    }
    return $location . $copyNumber . $callNumber;
};

$getLink = function ($view, $item) {
    return $view->url(
        'record-getthis',
        [
            'id' => $view->driver->getUniqueId(),
            'action' => 'GetThis',
        ],
        [
            'query' => [
                'item_id' => $item['item_id'],
            ],
        ]
    );
};

?>

<strong><?= $this->transEsc('Items') ?> :</strong>
<nav role="navigation" class="get-this-dropdown" data-js-dropdown>
  <div data-js-dropdown-header>
    <a href="#" aria-expanded="false">
      <span><?= $getDisplay($this, $selectedItem) ?></span>
      <?=$this->icon('open-dropdown', 'fa-square-caret-down') ?>
      <?=$this->icon('close-dropdown', 'fa-square-caret-up') ?>
    </a>
  </div>
  <div class="dropdown" tabindex="-1">
    <ul>
      <?php
      $selectedItem['item_id'] ??= -1;
      foreach ($items as $item) {
        $item['item_id'] ??= null;
        $itemClass = ($selectedItem['item_id'] == $item['item_id']) ? 'current' : '';
        ?>
        <li>
          <a
              href="<?= $getLink($this, $item) ?>"
              class="<?= $itemClass ?>"
              rel="nofollow"
          >
            <?= $getDisplay($this, $item) ?>
          </a>
        </li>
      <?php } ?>
    </ul>
  </div>
</nav>
<br>
