<!-- Get-this: holdings -->
<?php
$selectedItem = $this->getThis->getItem();
$items = $this->getThis->getItems();

function getDisplay($view, $item)
{
    $item['item_id'] ??= null;
    $location = $view->getThis->getLocation($item['item_id']);
    if (!empty($location)) {
        $location .= ': ';
    } else {
        $location = '';
    }
    $copyNumber = $view->getThis->getCopyNumber($item['item_id']);
    if ($callNumber = $view->getThis->getCallNumber($item['item_id'])) {
        $callNumber = ' (' . $callNumber . ')';
    } else {
        $callNumber = '';
    }
    # TODO we assume we always have a copy number
    return $location . $view->transEscAttr('copy_number', ['%%number%%' => $copyNumber]) . $callNumber;
}

function getLink($view, $item)
{
    return $view->url(
        'record-getthis',
        [
            'id' => $view->driver->getUniqueId(),
            'action' => 'GetThis',
        ],
        [
            'query' => [
                'item_id' => $item['item_id'],
            ],
        ]
    );
}

?>

<strong><?= $this->transEsc('Items') ?> :</strong>
<nav role="navigation" class="get-this-dropdown">
  <div class="call-number-display">
    <a href="#" aria-expanded="false">
      <span><?= getDisplay($this, $selectedItem) ?></span>
      <?=$this->icon('open-dropdown', 'fa-square-caret-down') ?>
      <?=$this->icon('close-dropdown', 'fa-square-caret-up') ?>
    </a>
  </div>
  <div class="dropdown" tabindex="-1">
    <ul>
      <?php
      $selectedItem['item_id'] ??= -1;
      foreach ($items as $item) {
        $item['item_id'] ??= null;
        $itemClass = $selectedItem['item_id'] == $item['item_id'] ? 'current' : '';
        ?>
        <li>
          <a
              href="<?= getLink($this, $item) ?>"
              class="<?= $this->escapeUrl($itemClass) ?>"
              rel="nofollow"
          >
            <?= getDisplay($this, $item) ?>
          </a>
        </li>
      <?php } ?>
    </ul>
  </div>
</nav>
<br>
<?php
    // Resetting the item to the selected one as we looped over all of them and cache was updated
    $this->getThis->setItemById($selectedItem['item_id']);
?>