<?php
$selectedItem = $this->getThis->getItem();
$items = $this->getThis->getItems();

$getDisplay = function ($view, $item) {
    $item['item_id'] ??= null;
    $location = $view->getThis->getLocation($item['item_id']);
    if (!empty($location)) {
        $location .= ': ';
    } else {
        $location = '';
    }
    $copyNumber = $view->getThis->getCopyNumber($item['item_id']);
    if (!empty($copyNumber)) {
        $copyNumber = $view->transEscAttr('copy_number', ['%%number%%' => $copyNumber]) . ' ';
    } else {
        $copyNumber = '';
    }
    if ($callNumberData = $view->getThis->getCallNumber($item['item_id'])) {
        $rawCallNumber = $callNumberData['text'] ?? '';
        $callNumber = ($callNumberData['translate'] ?? false) ? $view->translate($rawCallNumber) : $view->escapeHtml($rawCallNumber);
        $callNumber = '(' . $callNumber . ')';
    } else {
        $callNumber = '';
    }
    return $location . $copyNumber . $callNumber;
};

$JSDropdown = $this->getThis->makeListJSDropdown();
$getLink = function ($view, $item, bool $current = false) use ($JSDropdown) {
    return $current && !$JSDropdown ?
        '#' :
        $view->url(
            'record-getthis',
            [
                'id' => $view->driver->getUniqueId(),
                'action' => 'GetThis',
            ],
            [
                'query' => [
                    'item_id' => $item['item_id'],
                ],
            ]
        );
};
?>

<strong><?= $this->transEsc('Items') ?> :</strong>
<nav role="navigation" class="get-this-dropdown" <?= $JSDropdown ? 'data-js-dropdown' : '' ?>>
<?php if ($JSDropdown): ?>
  <div data-js-dropdown-header>
    <a href="#" aria-expanded="false">
      <span><?= $getDisplay($this, $selectedItem) ?></span>
      <?=$this->icon('dropdown-open', 'dropdown-open') ?>
      <?=$this->icon('dropdown-close', 'dropdown-close') ?>
    </a>
  </div>
  <div class="dropdown" tabindex="-1">
<?php endif; ?>
    <ul>
      <?php
      $selectedItem['item_id'] ??= -1;
      foreach ($items as $item):
        $item['item_id'] ??= null;
        $current = $selectedItem['item_id'] == $item['item_id'];
        $itemClass = $current ? 'current' : '';
        ?>
        <li>
          <a
              href="<?= $getLink($this, $item, $current) ?>"
              class="<?= $itemClass ?>"
              rel="nofollow"
          >
            <?= $getDisplay($this, $item) ?>
          </a>
        </li>
      <?php endforeach; ?>
    </ul>
  <?php if ($JSDropdown): ?>
  </div>
  <?php endif; ?>
</nav>
<br>
