<!-- Get-this: micro-form -->
<?php
$link = $this->getThisParams['open_hours'] ?? '';
if (empty($link)) {
    $linkStart = '';
    $linkEnd = '';
} else {
    $linkStart = '<a href="' . $this->escapeHtml($link) . '">';
    $linkEnd = '</a>';
}
?>
<div>
  <p>
    <strong><?= $this->transEsc('viewing_request') ?> :</strong>
    <?= $this->translate('microform_viewing_request_text', [
        '%%link_start%%' => $linkStart,
        '%%link_end%%' => $linkEnd,
    ]) ?>
  </p>
</div>

