<!-- Get-this: place-request -->
<?php
$item = $this->getThis->getItem();
if (empty($item)) {
    return;
}
$check = $item['check'] ?? false;
$link = $this->getThis->getLink();
$dataLightbox = !empty($item['linkLightbox']) ? 'data-lightbox' : '';
$checkRequest = $check ? 'checkRequest ' : '';
?>
<?php if (isset($item['is_holdable']) && !empty($link)) : ?>
  <div>
    <p><strong><?= $this->transEsc('campus_pickup') ?> :</strong>
        <?= $this->transEsc('campus_pickup_place_request_text') ?>
    </p>
    <ul>
      <li>
        <a class="<?= $checkRequest ?>placehold"
          <?= $dataLightbox ?>
          href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($link))?>"
        >
          <?= $this->transEsc($check ? 'Check Hold' : 'campus_pickup_place_request') ?>
        </a>
      </li>
    </ul>
  </div>
<?php endif ?>
