<!-- Get-this: remote-delivery -->
<?php
$data = [
    '%%item%%' => $this->getThis->getItem(),
    '%%location%%' => $this->getThis->getLocation(),
    '%%status%%' => $this->getThis->getStatus(),
    '%%callNum%%' => $this->getThis->getCallNumber(),
    '%%title%%' => $this->driver->getTitle(),
    '%%author%%' => $this->driver->getPrimaryAuthor(),
    '%%isbn%%' => $this->driver->getCleanISBN(),
];
$link = $getThisParams['general_link'] ?? '';
$requestCopyLink = $this->translate($getThisParams['request_link'] ?? '', $data);
?>
<div>
  <p>
    <strong><a href="<?= $this->escapeHtml($link) ?>"
               target="_blank"><?= $this->transEsc('delivery_request_distance') ?></a> :</strong>
    <?= $this->transEsc('delivery_request_distance_text') ?>
  </p>
  <ul>
    <li>
      <a href="<?= $this->escapeHtml($requestCopyLink) ?>" target="_blank">
        <?= $this->transEsc('delivery_request_distance_user') ?>
      </a>
    </li>
  </ul>
</div>
