<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - Social Statistics'));
?>
<div class="span-5">
  <?=$this->render("admin/menu.phtml")?>
</div>

<div class="span-18 last">
  <h1><?=$this->transEsc('Social Statistics')?></h1>

  <h2>Comments</h2>
  <table>
    <tr><th>Total Users</th><th>Total Resources</th><th>Total Comments</th></tr>
    <tr><td><?=$comments['users']?></td><td><?=$comments['resources']?></td><td><?=$comments['total']?></td></tr>
  </table>

  <h2>Favorites</h2>
  <table>
    <tr><th>Total Users</th><th>Total Resources</th><th>Total Lists</th><th>Total Saved Items</th></tr>
    <tr><td><?=$favorites['users']?></td><td><?=$favorites['resources']?></td><td><?=$favorites['lists']?></td><td><?=$favorites['total']?></td></tr>
  </table>

  <h2>Tags</h2>
  <table>
    <tr><th>Total Users</th><th>Total Resources</th><th>Total Tags</th></tr>
    <tr><td><?=$tags['users']?></td><td><?=$tags['resources']?></td><td><?=$tags['total']?></td></tr>
  </table>
</div>

<div class="clear"></div>
