<?php
$user = $this->auth()->isLoggedIn();
$avail = $this->driver->getOverdriveAvailability();
$previews = $this->driver->getPreviewLinks();
$this->OverdrivePreview =false;
if($previews->url){
    $this->OverdrivePreview ="<a href=\"{$previews->url}\" target=\"_blank\" class=\"btn btn-primary\">Sample</a>";
}
$this->OverdriveAction = false;
$this->OverdriveAvail = false;
//if we didn't get availability, we can't show the proper action buttons
if($avail->code=='od_code_login_for_avail'):
    $odaction = "<p class='alert-info'><strong>".$this->transEsc('od_code_login_for_avail')."</strong></p>";
    $this->OverdriveAvail = $odaction;
elseif($avail->code=='od_account_noaccess'):
    $odaction = "<p class='alert-info'><strong>".$this->transEsc('od_code_contentnotavail')."</strong></p>";
    $this->OverdriveAvail = $odaction;
elseif($avail->data):
    $od_id = $this->driver->getOverdriveID();
    $rec_id = $this->driver->getUniqueID();
    $hold_url = $this->url ('overdrive-hold');
    $checkedOut = $isOnHold = false;

    $checkedOutResult = $this->driver->isCheckedOut();
    //if the result of the check is false and the user is logged, in that
    //probably means that there was a connection failure
    if(!$checkedOutResult->status && $user):
        $odaction = "<div class=\"hold pull-right\"><div class=\"alert alert-warning\">
                      {$this->transEsc("od_code_connection_failed")}
                      </div></div>";
    else:
        $checkedOut = $checkedOutResult->data;
        if(!$checkedOut){
            $hold = $this->driver->isHeld($user);
        }
        $odaction = '<div class="hold pull-right">';

        if($checkedOut):
            $odaction .= "<div class=\"od_status checkedout alert alert-info\">
                          {$this->transEsc("od_is_checkedout",["%%due_date%%"=>$checkedOut->expires])}
                          </div>";

            if($checkedOut->isReturnable):
                $odaction .= "<a class=\"btn btn-primary returnTitle\" 
                      data-lightbox title='{$this->transEsc("od_but_return")}' 
                      href=\"$hold_url?od_id=$od_id&rec_id=$rec_id&action=returnTitleConfirm\"><i class='fa fa arrow-to-right' aria-hidden='true'></i>
                      {$this->transEsc('od_but_return')}</a>";
            endif;

            $odaction .= "<a class=\"btn btn-primary getTitle\"
                        data-lightbox title=\"{$this->transEsc('od_but_gettitle')}\"
                        href=\"$hold_url?od_id=$od_id&rec_id=$rec_id&action=getTitleConfirm\"><i class=\"fa fa arrow-to-right\" aria-hidden=\"true\"></i>
                        {$this->transEsc('od_but_gettitle')}</a>";

            elseif($hold):

                $odaction .= "<div class=\"od_status onhold  alert alert-info\">
                             {$this->transEsc('od_is_on_hold')}";
                      if($hold->holdReadyForCheckout){
                          $odaction .=  $this->transEsc("od_hold_now_avail", ["%%expireDate%%"=>$hold->holdExpires]);
                      }else{
                          $odaction .=  $this->transEsc("od_hold_queue", ["%%holdPosition%%"=>$hold->holdListPosition, "%%numberOfHolds%%"=>$hold->numberOfHolds]);
                      }

               $odaction .= "</div>
                      
               <a class=\"btn btn-primary placehold\" 
                  data-lightbox title=\"{$this->transEsc('request_place_text')}\" 
                  href=\"$hold_url?od_id=$od_id&rec_id=$rec_id&action=cancelHoldConfirm\"><i class=\"fa fa-flag\" aria-hidden=\"true\"></i>&nbsp; 
                  {$this->transEsc('od_but_cancel_hold')}</a>";
           else:
               //user does not already have it on hold or checked out.
               /*NOTE: its possible to have no copies owned which means that the library needs to add it back to the collection */
                      if($avail->data->copiesAvailable):
                          $odaction .= "<a class=\"btn btn-primary checkout\" data-lightbox 
                            title=\"{$this->transEsc('request_place_text')}\" 
                            href=\"$hold_url?od_id=$od_id&rec_id=$rec_id&action=checkoutConfirm\">
                            <i class=\"fa fa-arrow-right\" aria-hidden=\"true\"></i>
                            {$this->transEsc('od_but_checkout')}</a>";
                      else:

                          $odaction .= "<a class=\"btn btn-primary placehold\" data-lightbox title=\"{$this->transEsc('request_place_text')}\" 
                            href=\"$hold_url?od_id=$od_id&rec_id=$rec_id&action=holdConfirm\"><i class=\"fa fa-flag\" aria-hidden=\"true\"></i>&nbsp
                            {$this->transEsc('od_but_hold')}</a>";
                     endif;

        endif;  //end if checked out
        $odaction .= "</div>";
    endif; //end no checkout error

    $this->OverdriveAction = $odaction;

    $this->OverdriveAvail .= "
       <div class=\"availability\">
         <div class=\"odbrand pull-left media-left\">
           <img  src=\"https://developerportaldev.blob.core.windows.net/media/Default/images/newLogos/OverDrive_Logo_42x42_rgb.jpg\">
         </div>
         <div class=\"copies\"><strong>{$this->transEsc("od_avail_total")}</strong> {$avail->data->copiesOwned}</div>
         <div class=\"avail\"><strong>{$this->transEsc("od_avail_avail")}</strong> {$avail->data->copiesAvailable}</div>
         <div class=\"holds\"><strong>{$this->transEsc("od_avail_holds")}</strong> {$avail->data->numberOfHolds}</div>
        </div>";
    $this->OverdriveAvail = $odaction;
endif; //end if avail

echo $this->render('RecordDriver/DefaultRecord/core.phtml');?>