<?php
$user = $this->auth()->isLoggedIn();
$avail = $this->driver->getOverdriveAvailability();
$previews = $this->driver->getPreviewLinks();
$od_id = $this->driver->getOverdriveID();
$rec_id = $this->driver->getUniqueID();
$hold_url = $this->url('overdrive-hold');

$this->previewOverride = false;
$notification = "";
$message = false;
$alert_level = "";
$button = false;
$button2 = false;

//if we didn't get availability, we can't show the proper action buttons
if ($avail->code == 'od_code_login_for_avail'):
    $message = $this->transEsc('od_code_login_for_avail');
    $alert_level = "info";
elseif ($avail->code == 'od_account_noaccess'):
    $message = $this->transEsc('od_code_contentnotavail');
    $alert_level = "info";
elseif ($avail->data):
    $checkedOut = $isOnHold = false;
    $checkedOutResult = $this->driver->isCheckedOut();
    if (!$checkedOutResult->status && $user):
        if ($checkedOutResult->code == 'od_account_noaccess'):
            $message = $this->translate("od_code_contentnotavail");
            $alert_level = "warning";

        elseif ($checkedOutResult->code == 'od_account_problem'):
            $link = "<a href=\"" . $this->url(
                'overdrive-mycontent',
                [],
                ['query' => ['redirect' => 0]]
            ) . "\">" . $this->transEsc("Your Account") . "</a>";
            $message = $this->translate(
                "od_account_problem",
                ["%%message%%" => $message]
            );
            $alert_level = "warning";

        else:
            //if the result of the check is false and the user is logged in, that
            //probably means that there was a connection failure
            $message = $this->transEsc("od_code_connection_failed");
            $alert_level = "warning";

        endif;
    else:
        $checkedOut = $checkedOutResult->data;
        if (!$checkedOut):
            $hold = $this->driver->isHeld($user);
        endif;

        //this title is checked out
        if ($checkedOut):
            $message = $this->transEsc(
                "od_is_checkedout",
                ["%%due_date%%" => $checkedOut->expires]
            );
            $alert_level = "info";

            if ($checkedOut->isReturnable):
                //early return button
                $button = new stdClass();
                $button->class = "returnTitle";
                $button->url = "$hold_url?od_id=$od_id&rec_id=$rec_id&action=returnTitleConfirm";
                $button->icon = "sign-in";
                $button->text = $this->transEsc('od_but_return');
            endif;

            //download button
            $button2 = new stdClass();
            $button2->class = "getTitle";
            $button2->url = "$hold_url?od_id=$od_id&rec_id=$rec_id&action=getTitleConfirm";
            $button2->icon = "download";
            $button2->text = $this->transEsc('od_but_gettitle');

        //this title is on hold
        elseif ($hold):
            $message = $this->transEsc('od_is_on_hold');
            $alert_level = "info";

            if ($hold->holdReadyForCheckout):
                $message .= $this->transEsc(
                    "od_hold_now_avail",
                    ["%%expireDate%%" => $hold->holdExpires]
                );
            else:
                $message .= $this->transEsc(
                    "od_hold_queue",
                    [
                        "%%holdPosition%%" => $hold->holdListPosition,
                        "%%numberOfHolds%%" => $hold->numberOfHolds
                    ]
                );
            endif;

            $button = new stdClass();
            $button->class = "cancelHold";
            $button->url = "$hold_url?od_id=$od_id&rec_id=$rec_id&action=cancelHoldConfirm";
            $button->icon = "flag";
            $button->text = $this->transEsc('od_but_cancel_hold');

        else:
            //user does not already have it on hold or checked out.
            /*NOTE: its possible to have no copies owned which means that the
            library needs to add it back to the collection */
            if ($avail->data->copiesAvailable):
                //Checkout button
                $button = new stdClass();
                $button->class = "checkout";
                $button->url = "$hold_url?od_id=$od_id&rec_id=$rec_id&action=checkoutConfirm";
                $button->icon = "arrow-left";
                $button->text = $this->transEsc('od_but_checkout');

            else:
                //Place a request button
                $button = new stdClass();
                $button->class = "placehold";
                $button->url = "$hold_url?od_id=$od_id&rec_id=$rec_id&action=holdConfirm";
                $button->icon = "flag";
                $button->text = $this->transEsc('od_but_hold');
            endif;
        endif;  //end if checked out
    endif; //end checkedout result

    if($message):
      $notification = "<div class=\"alert alert-$alert_level\">$message</div>";
    endif;

    if($button):
        $button1Markup = <<<BTN1MARKUP
            <a class="btn btn-primary {$button->class}"
               data-lightbox title="{$button->text}"
               href="{$button->url}"><?=$this->icon('{$button->icon}') ?>&nbsp;
               {$button->text}</a>
BTN1MARKUP;
    endif;

    if($button2):
        $button2Markup = <<<BTN2MARKUP
             <a class="btn btn-primary {$button2->class}"
                data-lightbox title="{$button2->text}"
                href="{$button2->url}"><?=$this->icon('{$button2->icon}') ?>&nbsp;
                {$button2->text}</a>
BTN2MARKUP;
    endif;

    $extraControls['actionControls'] = <<<ACTIONMARKUP
        <div class="pull-right">
           $notification
           $button1Markup $button2Markup
        </div>
ACTIONMARKUP;

    $extraControls['availabilityInfo'] = "
       <div class=\"availability\">
         <div class=\"odbrand pull-left media-left\">
           <img  src=\"https://developerportaldev.blob.core.windows.net/media/Default/images/newLogos/OverDrive_Logo_42x42_rgb.jpg\">
         </div>

         <div class=\"copies\"><strong>{$this->transEsc("od_avail_total")}</strong> {$avail->data->copiesOwned}</div>
         <div class=\"avail\"><strong>{$this->transEsc("od_avail_avail")}</strong> {$avail->data->copiesAvailable}</div>
         <div class=\"holds\"><strong>{$this->transEsc("od_avail_holds")}</strong> {$avail->data->numberOfHolds}</div>
        </div>";

    $this->extraControls = $extraControls;
endif; //end if avail

if ($previews->url) {
    $this->previewOverride = "<a href=\"{$previews->url}\" target=\"_blank\" class=\"btn btn-primary\">Sample</a>";
}
echo $this->render('RecordDriver/DefaultRecord/core.phtml'); ?>