<?php 
//json response. array of html strings
//todo check result first
$jsonResult = new stdClass;
$jsonResult->status="OK";
$data = array();
foreach($result->availability as $avail):
  $current['full_status'] = "<p><div class='copies'><strong>Total Copies</strong> ".$avail->copiesOwned."</div>
                        <div class='avail'><strong>Available</strong> ".$avail->copiesAvailable."</div>
                        <div class='holds'><strong>Holds</strong> ".$avail->numberOfHolds."</div></p>";
  $current['id'] = $avail->reserveId;
                        
  $data[] = $current;                      
endforeach;
$jsonResult->data = $data;
echo json_encode($jsonResult);
?>