<?php 
//json response. array of html strings
//todo check result first
$jsonResult = new stdClass;
$data = array();
$isError = false;
$loginForAvail= false;
error_log(print_r($this->result,true));
if(!$this->result->status){
    //we must have had a connection error.
    $isError = true;
}elseif($this->result->code == 'od_code_login_for_avail'){
    $loginForAvail = true;
}
foreach($ids as $id):
    $current['status'] = "OK";
    $current['id'] = $id;
    $avail = $this->result->data[$id];

    if($isError || $avail->code == 'od_code_resource_not_found') {
        $current['error'] = $this->transEsc('status_unknown_message');
        $current['full_status'] = "";
    } elseif ($loginForAvail || $avail->code == 'od_code_login_for_avail'){
        $current['full_status'] = "<p class='alert-info'>Login for availability</p>";
    } else {
        $current['full_status']
            = "<p><div class='copies'><strong>Total Copies</strong> "
            . $avail->copiesOwned . "</div>
                        <div class='avail'><strong>Available</strong> "
            . $avail->copiesAvailable . "</div>
                        <div class='holds'><strong>Holds</strong> "
            . $avail->numberOfHolds . "</div></p>";
    }
  $data[] = $current;
endforeach;
$jsonResult->data->statuses = $data;
echo json_encode($jsonResult);
?>