<div class="col-xs-12 col-sm-4 panel-buttons">
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">RelBib Journals</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">RelBib Repository</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">Kooperationspartner</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">[Weitere Services]</a>
    </div>
</div>
