<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/printing-press.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>FID Services</h4>
        <p>
            <ul>
                <li>Über den FID Religionswissenschaft</li>
                <li><a href="/?subpage=open_access_services">Open Access Services</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'cooperations']) ?>">Kooperationen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'links']) ?>">Weitere Ressourcen</a></li>
            </ul>
        </p>
    </div>
</div>
