<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/printing-press.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>FID Services</h4>
        <p>
            <ul>
                <li>Über den FID Religionswissenschaft</li>
                <li><a href="<?=$this->url('content-page', ['page' => 'open_access_services']) ?>">Open Access Services</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'cooperations']) ?>">Kooperationen</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'links']) ?>">Weitere Ressourcen</a></li>
            </ul>
        </p>
    </div>
</div>
