<div class="col-xs-12 col-sm-3 panel panel-top panel-inverse">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/news.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Religionswissenschaft aktuell</h4>
        <p>
            <?=$this->tuefind()->getRssNewsEntriesHtml('/usr/local/vufind/public/relbib_docs/news.rss', 4)?>
        </p>
        <a href="#" class="btn btn-inverse" role="button">Weiterlesen</a>
    </div>
</div>
