<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-inverse">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/news.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Newsfeeds aus der<br/>Religionswissenschaft</h4>
        <p>
            <?=$this->tuefind()->getRssNewsEntriesHtml('/usr/local/vufind/public/relbib_docs/news.rss')?>
        </p>
        <a target="_blank" href="relbib_docs/news.rss" class="btn btn-inverse" role="button">Weiterlesen</a>
    </div>
</div>
