<div class="col-xs-12 col-sm-3 panel panel-top panel-default">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/printing-press.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>RelBib Open Access</h4>
        <p>
            <ul>
                <li>Zeitschriftenplattform</li>
                <li>Zweitveröffentlichungsservice</li>
            </ul>
        </p>
        <!--<a href="#" class="btn btn-inverse" role="button">Weiterlesen</a>-->
    </div>
</div>
