<div class="panel panel-top panel-default tf-panel-home-2">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'search']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/Magnifying_glass_with_focus_on_paper.png') ?>);"></div>
        <div class="panel-content">
            <h4>Suchen</h4>
            <!--<p>Einzelheiten zu KrimDok</p>-->
        </div>
    </a>
</div>