<div class="panel panel-top panel-default tf-panel-home-2">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'search']) ?>">
        <!-- this picture needs a special title for copyright reasons -->
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/Magnifying_glass_with_focus_on_paper.png') ?>);"
             title="Der im Hintergrund verwendete Text stammt aus gemeinfreien Werk Die Baukunst, Heft 11, Seite 8, das von Max Hasak geschrieben wurde. Gerendert mit einer Entwickerversion von Cycles in Blender. CC BY-SA 3.0"></div>
        <div class="panel-content">
            <h4>Suchen</h4>
            <!--<p>Einzelheiten zu KrimDok</p>-->
        </div>
    </a>
</div>