<div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 panel panel-top panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/discover.jpg') ?>" alt="" class="img-responsive panel-image"></div>
    <div class="panel-content">
        <h4>Discover IxTheo</h4>
        <p>There are many functions in IxTheo. Discover what we offer and how it works.</p>
        <a href="#" class="btn btn-default" role="button">Read more</a>
    </div>
</div>