<div class="panel panel-top panel-default tf-panel-home-4">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Discover IxTheo</h4>
        <p>There are many functions in IxTheo. Discover what we offer and how it works.</p>
        <a href="#" class="btn btn-default" role="button">Read more</a>
    </div>
</div>
