<div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 panel panel-top panel-inverse">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/news.jpg') ?>" alt="" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>News</h4>
        <p>Read the latest news and what we are doing.</p>
        <a href="#" class="btn btn-inverse" role="button">Read more</a>
    </div>
</div>