<div class="panel panel-bottom panel-default tf-panel-home-4">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/printing-press.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>For printing presses</h4>
        <p>What does IxTheo offer for printing presses?</p>
        <a href="#" class="btn btn-default" role="button">Read more</a>
    </div>
</div>
