<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Découvrir RelBib</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => 'about_relbib']) ?>">Informations sur RelBib (en anglais)</a></li>
                <li><a href="/?subpage=search_and_browse">Rechercher et naviguer en Relbib (en anglais)</a></li>
                <li><a href="/?subpage=features">Fonctionalité en RelBib (en anglais)</a></li>
                <li><a href="/relbib_docs/relbib_journals_fr.pdf">Liste des journaux en RelBib</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'A-Z']) ?>">RelBib A-Z (en anglais)</a></li>
            </ul>
        </p>
        <!--<a href="<?=$this->url('content-page', ['page' => 'discover']) ?>#anchor" class="btn btn-default" role="button">Mehr erfahren</a>-->
    </div>
</div>
