<div class="panel panel-top panel-default tf-panel-home-3">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/business-idea-diagram-innovation-40218.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Services du FID</h4>
        <p>
            <ul>
                <li><a href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">Self archiving service (Green Open Access)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'ojs']) ?>">RelBib Open Journals (Gold Open Access)</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">Research data management</a></li>
                <li><a href="<?=$this->url('content-page', ['page' => 'cooperations_institutions']) ?>">Coopération (en anglais)</a></li>
            </ul>
        </p>
    </div>
</div>
