<?php

const APPLICATION_ENV = 'testing';
const APPLICATION_PATH = '.';
const DEFAULT_SEARCH_BACKEND = 'Solr';
const LOCAL_CACHE_DIR = './local';
const LOCAL_OVERRIDE_DIR = '.';
const VUFIND_DATABASE_DATETIME_FORMAT = 'Y-m-d H:i:s';
const VUFIND_DEFAULT_EARLIEST_YEAR = 1400;
const VUFIND_DEFAULT_LATEST_YEAR_OFFSET = 1;
