<?php
  $this->assetManager()->appendScriptLink('channels.js');
  $this->jsTranslations()->addStrings([
    'channel_browse' => 'channel_browse',
    'channel_expand' => 'channel_expand',
    'channel_search' => 'channel_search',
    'nohit_heading' => 'nohit_heading',
    'View Record' => 'View Record',
  ]);

  $finalChannels = [];
  $finalCount = 0;
  foreach ($channels as $current) {
    if (isset($current['contents'])) {
      $finalChannels[] = $current;
      $finalCount++;
    } elseif ($finalCount > 0 && isset($current['token'])) {
      $finalChannels[$finalCount - 1]['relatedTokens'][] = $current;
    }
  }
?>

<?php if (empty($token) && ($displaySearchBox ?? true)): ?>
  <form action="<?=$this->url('channels-search')?>" class="channel-search form-inline">
    <?=$this->transEsc('channel_searchbox_label')?>
    <input type="text" name="lookfor" class="form-control" value="<?=$this->escapeHtmlAttr($this->lookfor) ?>" aria-label="<?=$this->transEscAttr('search_terms') ?>">
    <input type="submit" value="<?=$this->transEscAttr('Submit')?>" class="btn btn-default">
  </form>
<?php endif; ?>

<?php foreach ($finalChannels as $channel): ?>
  <?php
    $groupId = $channel['groupId'] ?? $channel['providerId'];
    $channelID = 'channel-' . md5(serialize($channel));
        $channelRoot = $this->url('channels-home') . '?' . (empty($queryParams) ? '' : $this->escapeHtmlAttr($queryParams . '&')) . 'layout=lightbox';
  ?>
  <div class="channel">
    <div class="channel-title">
      <h2><?=$this->escapeHtml($channel['title'])?></h2>
      <?php if (!empty($channel['links'])): ?>
        <div class="dropdown">
          <button class="btn btn-default dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            <span class="visually-hidden">Channel Options</span>
            <span aria-hidden="true"><?=$this->icon('ui-dots-menu') ?></span>
          </button>
          <ul class="dropdown-menu">
            <?php foreach ($channel['links'] as $item): ?>
              <li>
                <a class="dropdown-item icon-link" href="<?=$item['url'] ?>">
                  <?=$this->icon($item['icon'], 'icon-link__icon') ?>
                  <span class="icon-link__label"><?=$item['label'] ?></span>
                </a>
              </li>
            <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>
    </div>

    <?php if (count($channel['relatedTokens'] ?? []) > 0): ?>
      <div class="channel-add-menu btn-group" data-group="<?=$this->escapeHtmlAttr($groupId) ?>">
        <button type="button" class="channel-add-more-btn btn btn-default"><?=$this->transEsc('channel_add_more') ?></button>
        <button type="button" class="btn btn-default dropdown-toggle dropdown-toggle-split" data-bs-toggle="dropdown" aria-expanded="false">
          <span class="visually-hidden"><?=$this->transEscAttr('toggle_dropdown') ?></span>
          <span aria-hidden="true"><?=$this->icon('dropdown-caret') ?></span>
        </button>
        <ul class="dropdown-menu">
          <?php foreach ($channel['relatedTokens'] as $related): ?>
            <li><a class="channel-add-link dropdown-item" href="<?=$channelRoot ?>channelProvider=<?=urlencode($related['providerId']) ?>&channelToken=<?=urlencode($related['token']) ?>" data-token="<?=$this->escapeHtmlAttr($related['token']) ?>"><?=$this->escapeHtml($this->truncate($related['title'], 100)) ?></a></li>
          <?php endforeach; ?>
        </ul>
      </div>
    <?php endif; ?>

    <ul
      class="channel-list"
      id="<?=$channelID ?>"
      data-group="<?=$groupId ?>"
      style="--limit:<?=$channel['limit'] ?>"
    >
      <?php foreach ($channel['contents'] as $item): ?>
        <?php
          $url = empty($item['routeDetails'])
            ? $this->recordLinker()->getUrl("{$item['source']}|{$item['id']}")
            : $this->url($item['routeDetails']['route'], $item['routeDetails']['params']);
        ?>
        <li
          class="channel-item"
          data-channel-id="<?=$this->escapeHtmlAttr($channelID)?>"
          data-record-id="<?=$this->escapeHtmlAttr($item['id']) ?>"
          data-record-source="<?=$item['source'] ?>"
        >
          <div class="channel-item-thumb">
            <img
              class="channel-item-img"
              src="<?=$this->escapeHtmlAttr($item['thumbnail'] ? $item['thumbnail'] : $this->url('cover-unavailable'))?>"
              alt="" loading="lazy"
            >
            <button class="channel-quick-look-btn"><?=$this->transEsc('Quick Look') ?></button>
          </div>

          <a
            class="channel-item-title"
            href="<?=$this->escapeHtmlAttr($url)?>"
            title="<?=$this->escapeHtml($item['title'])?>"
          >
            <?=$this->escapeHtml($item['title'])?>
          </a>
        </li>
      <?php endforeach; ?>
    </ul>

    <div class="channel-bottom-menu">
      <?php
        $limit = $channel['limit'] ?? 6;
        $disabled = $channel['resultTotal']
          ? $channel['resultTotal'] <= $limit
          : count($channel['contents']) < $limit;
      ?>
      <a
        class="channel-load-more-btn btn btn-default<?=$disabled ? ' disabled' : ''?>"
        href="<?=$channelRoot ?>&channelProvider=<?=urlencode($channel['providerId']) ?><?=isset($channel['token']) ? '&channelToken=' . urlencode($channel['token']) : '' ?>&page=1&limit=<?=$limit ?>"
        <?=$disabled ? 'aria-disabled="true"' : ''?>
      >
        <?=$this->translate('channel_more_items') ?>
      </a>
    </div>
  </div>
<?php endforeach; ?>

<template id="template-channels-quick-look">
  <div
    class="channels-quick-look"
    data-record-id="${record.dataset.recordId}"
    data-record-source="${record.dataset.recordSource}"
  >
    <h2 class="ql-title"></h2>

    <a class="ql-view-record-btn btn btn-primary" href="${href}" data-lightbox-ignore>
      <?=$this->translate('View Record') ?>
    </a>

    <div class="ql-btn-group btn-group">
      <button class="ql-prev-item-btn btn btn-default">
        <?=$this->translate('Prev Search Result') ?>
      </button>
      <a class="ql-expand-btn btn btn-default" href="${expandUrl}" data-lightbox-ignore>
        <?=$this->translate('channel_expand') ?>
      </a>
      <button class="ql-next-item-btn btn btn-default">
        <?=$this->translate('Next Search Result') ?>
      </button>
    </div>
  </div>
</template>
