<!-- START of: finna - organisationinfo/elements/location-quick-info.phtml -->
<?php
  $renderInterval = function (int $opens, int $closes, bool $minutes): string {
    return $this->render('organisationinfo/elements/helpers/time-interval.phtml', compact('opens', 'closes', 'minutes'));
  };
  // Use 'organisation_info_only_selfservice' if available (meaning it's customized locally) and fall back to default otherwise:
  $selfserviceTranslationKey = !$this->translationEmpty('organisation_info_only_selfservice') ? 'organisation_info_only_selfservice' : 'organisation_info_schedule_selfservice';
?>
<div class="location-basic-info"<?=$this->matomoTracking('Location Basic Info', $id . '/' . $orgInfo['name'])?>>
  <h3 class="location-title" aria-atomic="true" aria-live="polite">
    <span class="visually-hidden"><?=$this->transEsc('organisation_info_selected_service_point')?></span> <?=$this->escapeHtml($orgInfo['name'])?>
  </h3>
  <div>
    <p>
      <span class="location-links address info-element"><?=$this->escapeHtml($orgInfo['address']['displayAddress'] ?? '')?></span>
      <?php if ($orgInfo['routeUrl']): ?>
        <a href="<?=$this->escapeHtmlAttr($orgInfo['routeUrl'])?>" target="_blank" class="location-links route info-element"><?=$this->icon('route') ?> <?=$this->transEsc('organisation_info_route')?></a>
      <?php endif; ?>
    </p>
    <?php if ($orgInfo['homepage']): ?>
      <p class="location-links website info-element">
        <a href="<?=$this->escapeHtmlAttr($orgInfo['homepage'])?>" target="_blank"><?=$this->icon('homepage-link') ?> <?=$this->transEsc('organisation_info_homepage')?></a></span>
      </p>
    <?php endif; ?>
    <?php if ($orgInfo['email']): ?>
      <p class="location-links email info-element">
        <a href="mailto:<?=$this->escapeHtmlAttr($orgInfo['email'])?>">
          <?=$this->icon('email') ?> <?=$this->escapeHtml($orgInfo['email'])?>
        </a>
        <?php if ($name = $orgInfo['emailName'] ?? null): ?>
          / <?=$this->escapeHtml($name)?>
        <?php endif; ?>
      </p>
    <?php endif; ?>
    <?php foreach ($orgInfo['links'] as $link): ?>
      <?php if (str_contains($link['name'], 'Facebook')): ?>
        <p class="location-links facebook info-element">
        <a class="facebook" href="<?=$this->escapeHtmlAttr($link['url'])?>" target="_blank">
          <?=$this->icon('facebook') ?> <?=$this->escapeHtml($link['name'])?>
        </a>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
</div>
<div class="open-closed-info">
  <?php if (!$orgInfo['isAlwaysClosed']): ?>
    <h4 class="open-or-closed">
      <?php if ($orgInfo['openNow']): ?>
        <span class="location-is-open info-element"><?=$this->transEsc('organisation_info_is_open_now')?></span>
      <?php else: ?>
        <span class="location-is-closed info-element"><?=$this->transEsc('organisation_info_is_closed_now')?></span>
      <?php endif; ?>
    </h4>
    <?php foreach ($orgInfo['openTimes']['schedules'] as $schedule): ?>
      <?php if ($schedule['today']): ?>
        <div class="time-open info-element">
          <?php if ($schedule['closed']): ?>
            <span class="closed-times">
              <?=$this->icon('organisation-info-closed')?> <?=$this->transEsc('organisation_info_is_closed')?>
            </span>
          <?php else: ?>
            <span class="opening-times">
              <?=$this->icon('time-open') ?> <?=$this->transEsc('organisation_info_open_today')?>
              <?=$renderInterval($schedule['firstOpeningTime'], $schedule['lastClosingTime'], $schedule['minutePrecision'])?>
            </span>
            <?php if ($orgInfo['hasSelfServiceTimes'] || $schedule['gaps']): ?>
              <?php foreach ($schedule['times'] as $time): ?>
                <div class="time-row sub-row">
                  <div class="date-container"></div>
                  <div class="description">
                    <?php if ($time['closed']): ?>
                      <span class="closed-times">
                        <?=$this->icon('organisation-info-closed')?> <?=$this->transEsc('organisation_info_is_closed')?>
                        <?=$renderInterval($time['opens'], $time['closes'], $schedule['minutePrecision'])?>
                      </span>
                    <?php elseif ($time['selfservice']): ?>
                      <span class="selfservice-times">
                        <?=$this->transEsc($selfserviceTranslationKey)?>
                        <?=$renderInterval($time['opens'], $time['closes'], $schedule['minutePrecision'])?>
                      </span>
                    <?php else: ?>
                      <span class="staff-times">
                        <?=$this->transEsc('organisation_info_schedule_staff')?>
                        <?=$renderInterval($time['opens'], $time['closes'], $schedule['minutePrecision'])?>
                      </span>
                    <?php endif; ?>
                  </div>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    <?php endforeach; ?>
  <?php endif; ?>
</div>
<?php if ($orgInfo['slogan']): ?>
  <div class="clearfix"></div>
  <div>
    <p class="location-description info-element"><?=$this->cleanHtml($orgInfo['slogan'])?></p>
  </div>
<?php endif; ?>
<!-- END of: finna - organisationinfo/elements/location-quick-info.phtml -->
