<!-- START of: finna - organisationinfo/elements/organisation-page-link.phtml -->
<?php if ($orgInfo['logo']): ?>
  <a href="<?=$url?>">
    <img src="<?=$orgInfo['logo']?>" class="consortium-logo" alt="" title="<?=$this->transEscAttr('organisation_info_link')?>">
    <span class="visually-hidden"><?=$this->transEsc('organisation_info_link')?></span>
  </a>
<?php endif ?>
<span class="organisation-name"><?=$orgInfo['name'] ?: $parentName?></span>
<div class="link">
  <a href="<?=$url?>"><?=$this->transEsc('organisation_info_link')?></a>
</div>
<!-- START of: finna - organisationinfo/elements/organisation-page-link.phtml -->
