<label class="span-2" for="login_target"><?=$this->transEsc('login_target')?>:</label>
<?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
<select id="login_target" name="target">
<?foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
  <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
<? endforeach ?>
</select> 
<br class="clear"/>
<label class="span-2" for="login_username"><?=$this->transEsc('Username')?>:</label>
<input id="login_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" size="15" class="mainFocus <?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
<br class="clear"/>
<label class="span-2" for="login_password"><?=$this->transEsc('Password')?>:</label>
<input id="login_password" type="password" name="password" size="15" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
<br class="clear"/>
