<div class="flash-message alert alert-info" style="margin-top: 20px;">
  <?=$this->translate('shortlink_redirect', ['%%delay%%' => '<div id="redirectDelay" style="display: inline;">' . $this->redirectDelay . '</div>'])?>
</div>
<?php $this->headMeta()->prependHttpEquiv('refresh', $this->redirectDelay . '; URL=' . $this->redirectTarget); ?>
<?php
$jsSnippet = <<<EOD
  setInterval(function() {
    let field = document.getElementById("redirectDelay");
    if (field.innerHTML > 0)
      --field.innerHTML;
  }, 1000);
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
