<!-- START of: finna - RecordDriver/SolrQdc/core.phtml -->
<?

  $openUrl = $this->openUrl($this->driver, 'record');
  $openUrlActive = $openUrl->isActive();
  // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
  $onlineURLs = $this->driver->getOnlineURLs();
  $mergedData = $this->driver->tryMethod('getMergedRecordData');
  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $img = $this->recordImage($this->record($this->driver));
  $images = $img->getAllImagesAsCoverLinks(
      $this->layout()->userLang, $params
  );

  $hasOnlineURLs =
      $this->record($this->driver)->containsNonImageURL($urls, $images)
      || $this->record($this->driver)->containsNonImageURL($onlineURLs, $images)
      || !empty($mergedData['urls']) && $this->record($this->driver)->containsNonImageURL($mergedData['urls'], $images)
  ;

  if (!empty($urls)) {
    $videoUrls = [];
    $audioUrls = [];
    $otherUrls = [];
    foreach ($urls as $url) {
      if (!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLink()->getEmbeddedVideo($url['url']) == 'data-embed-iframe') {
        array_push($videoUrls, $url);
      } elseif (!empty($url['embed']) && $url['embed'] == 'audio') {
        array_push($audioUrls, $url);
      } else {
        array_push($otherUrls, $url);
      }
    }
  }

  if (!empty($onlineURLs)) {
    if (empty($audioUrls)) {
      $audioUrls = [];
    }
    $tempUrlArray = [];
    foreach ($onlineURLs as $url) {
      if (!empty($url['embed']) && $url['embed'] == 'audio') {
        array_push($audioUrls, $url);
      } else {
        array_push($tempUrlArray, $url);
      }
    }
    $onlineURLs = $tempUrlArray;
  }

  $img = $this->recordImage($this->record($this->driver));
  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment ?>">

    <div class="image-information">
      <div class="cover-wrapper">
        <? /* Display thumbnail if appropriate: */ ?>
        <? if ($img): ?>
          <?=$img->render('record', ['small' => ['w' => 50, 'h' => 50], 'large' => ['w' => 1200, 'h' => 1200]]) ?>
        <? endif;?>
        <? /* Display qrcode if appropriate: */ ?>
        <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
        <? if ($QRCode): ?>
          <div class="visible-print inline-block"><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/></div>
        <? endif; ?>
      </div>
      <? // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>

    <? if (!empty($videoUrls)): ?>
      <? foreach ($videoUrls as $url): ?>
        <? $description = isset($url['desc']) ? $url['desc'] : $this->truncateUrl($url['url']); ?>
        <? $desc = $this->recordLink()->getEmbeddedVideo($url['url']) == 'data-embed-iframe' ? $this->translate('format_Video') : $description; ?>
        <div class="video-link-container">
          <a class="videourl fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"
            <? if (!empty($url['videoSources'])): ?> data-video-sources="<?= $this->escapeHtmlAttr(json_encode($url['videoSources'])) ?>"<? endif; ?>
            <?= $this->recordLink()->getEmbeddedVideo($url['url']) ?>
            <?=!empty($url['embed']) && $url['embed'] == 'video' ? ' data-embed-video' : '' ?>
          >
            <div class="video-icon"><i class="fa fa-play-circle"></i></div>
            <div class="video-desc"><?=$this->escapeHtml($desc)?></div>
          </a>
        </div>
      <? endforeach; ?>
    <? endif; ?>
    
    <? if (!empty($audioUrls)): ?>
      <?= $this->partial('RecordDriver/SolrDefault/record-audio-player.phtml', ['audioUrls' => $audioUrls]) ?>
    <? endif; ?>

    <div class="record-rating">
      <div class="rating-stars">
        <div onclick="$('a.usercomments').click();">
          <?=$this->record($this->driver)->getRating()?>
        </div>
      </div>
    </div>

    <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-toolbar")): ?>
    <div class="record-post-toolbar">
      <?=$this->render($template)?>
    </div>
    <? endif; ?>

  </div>
  <? $thumbnail = ob_get_contents(); ?>
<? ob_end_clean(); ?>
<? $this->headScript()->appendFile("finna-record.js"); ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>
  <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <? endif; ?>
  <div class="media-body record-information">
      <h1 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>
      <div class="description">
        <span id="description_text" data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>">
          <i class="fa fa-spinner fa-spin"></i>
        </span>
      </div>

      <? if (!empty($urls) || $openUrlActive || !empty($onlineURLs) || !empty($mergedData['urls'])): ?>
        <? if ($hasOnlineURLs || $openUrlActive): ?>
        <div class="recordURLs local-available-online-record">
          <div class="truncate-field">
            <? if (!empty($otherUrls)): ?>
              <? foreach ($otherUrls as $url): ?>
                <? if (isset($images[$url['url']])) { continue; } ?>
                <? $desc = isset($url['desc']) ? $url['desc'] : $this->truncateUrl($url['url']); ?>
                <div class="fulltextField">
                  <a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"
                    <? if (!empty($url['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<? endif; ?>
                  >
                    <i class="fa fa-external-link"></i> <?=$this->transEsc('default::link_' . $desc, null, $desc) ?>
                  </a>
                </div>
              <? endforeach; ?>
            <? endif; ?>
            <? if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
              <? foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                <? if (isset($images[$url['url']])) { continue; } ?>
                <div class="fulltextField"><a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><i class="fa fa-external-link"></i> <?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?></a>
                <? if ($url['source']): ?>
                  <span class="online-source">(<?=is_array($url['source']) ? $this->transEsc('Multiple Organisations') : $this->transEsc('default::source_' . $url['source'], null, $url['source']) ?>)</span>
                <? endif; ?>
                </div>
              <? endforeach; ?>
            <? endif; ?>
          </div>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
          </div>
        <? endif; ?>
      <? endif; ?>

      <div class="record-authors">
        <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
          <span class="recordFormat"><?=$this->record($this->driver)->getFormatList()?></span>
        <? endif; ?>

        <? if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field recordAuthors">
          <span property="author">
          <? foreach($results as $index => $author): ?>
            <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><? if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><? endif; ?><? if (!empty($author['role'])): ?><span class="author-role">, <?=$this->escapeHtml($author['role']) ?></span><? endif; ?>
          <? endforeach; ?>
          </span>
        </div>
        <? endif; ?>

        <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
        <div class="recordPublications">
        <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            </span>
          <? endforeach; ?>
          </div>
        <? endif; ?>
      </div>

      <? if ($abstracts = $this->driver->getAbstracts()): ?>
        <div class="truncate-field wide recordSummary">
          <p class="summary">
          <? if (isset($abstracts[$this->layout()->userLang])): ?>
              <?=$this->escapeHtml($abstracts[$this->layout()->userLang])?>
            <? else: ?>
              <?=implode('<br><br>', array_map([$this, 'escapeHtml'], $abstracts))?>
            <? endif; ?>
          </p>
        </div>
      <? else: ?>
        <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
        <? if ($summary): ?>
        <div class="truncate-field wide recordSummary">
            <p class="summary"><?=$summary ?></p>
        </div>
        <? endif; ?>
      <? endif; ?>

      <? if ($this->userlist()->getMode() !== 'disabled'): ?>
        <? /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc("Saved in")?>:</strong>
        </div>
      <? endif; ?>

      <?/* Display Main Details */?>
      <?
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->getData(
            $driver, $formatter->filterQDCFields($formatter->getDefaults('core'))
        );
      ?>
      <? if (!empty($coreFields)): ?>
        <table class="table table-finna-record record-details">
          <? foreach ($coreFields as $key => $current): ?>
           <? $header = $this->transEsc(isset($current['context']['title']) ? $current['context']['title'] : $key); ?>
           <tr class="<?=$current['context']['class'];?>"><th><?=$header !== '' ? "$header:" : ''?></th><td><?=$current['value']?></td></tr>
          <? endforeach; ?>
        </table>
      <? endif; ?>
      <?/* End Main Details */?>

      <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <? endif; ?>
    </div>
  <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
    <?=$thumbnail ?>
  <? endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrQdc/core.phtml -->
