<?
$i=0;
$formats = $this->driver->getFormats();
$is_hybrid = $this->driver->tryMethod('isHybrid');
$media_types = $this->driver->tryMethod('getMediaTypes');
if (isset($media_types)) {

  if ($is_hybrid):
    $formats = array_merge(["Electronic/Print"], $formats);
  elseif (in_array("Electronic", $media_types)):
    $formats = array_merge(["Electronic"], $formats);
  endif;
  $i = 0;
  foreach ($formats as $format) { ?>
    <span class="iconlabel <?=$this->record($this->driver)->getFormatClass($format)?>"><?=$this->transEsc($format)?><?=(++$i < count($formats) - 1) ? " |" : ""?> </span>
  <? }
}?>
