<?
$i=0;
  $formats = $this->driver->getFormats();  
  if ($this->driver->tryMethod('getMediaType') == "Electronic"):
    $formats = array_merge(["Electronic"], $formats);
  endif;
  $i = 0;
  foreach ($formats as $format): ?>
  <span class="iconlabel <?=$this->record($this->driver)->getFormatClass($format)?>"><?=$this->transEsc($format)?><?=($i++ < count($formats) - 1) ? " |" : ""?> </span>
<? endforeach; ?>
