<?php $config = $this->config()->get('fulltextsnippet')?>
<?php if (isset($config->Elasticsearch->base_url) && $this->driver->tryMethod('hasFulltextMatch')): ?>
<span id="fulltext_snippets">
  <div style="color:grey" id="snippet_place_holder_<?=$this->driver->getUniqueID()?>"><?=$this->transEsc("Loading")?>...</div>
  <?php
    $query = $this->params->getQuery();
    $query_terms = $query->getAllTerms();
    $handler = $query instanceof \VuFindSearch\Query\Query ? $query->getHandler() :
               ($query instanceof \VuFindSearch\Query\QueryGroup ? $query->getReducedHandler() : "");
    $synonym_type = "";
    switch ($handler) {
      case "FulltextWithSynonyms":
        $synonym_type = "lang";
        break;
      case "FulltextAllSynonyms":
        $synonym_type = "all";
        break;
    }
    $fulltext_type_filters = $this->driver->getFulltextTypeFilters();
    $fulltext_types = $this->driver->getFulltextTypes();

    $jsSnippet = "TueFind.GetFulltextSnippets('" . $this->url('home') . "','" . $this->driver->getUniqueID() . "','" . addslashes($query_terms) . "', false, '" . $synonym_type . "', ";
    if (isset($fulltext_type_filters) && $fulltext_type_filters != '') {
      $jsSnippet .= "'" . implode("','", $fulltext_type_filters) . "'";
    } else {
      $jsSnippet .= "'" . implode("','", $fulltext_types) . "'";
    }
    $jsSnippet .= ');';
  ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
</span>
<?php endif; ?>
