<?php if ($id && $showInlineInfo): ?>
<div class="authority ajax-content" data-authority="<?=$this->escapeHtmlAttr($this->id)?>" data-source="<?=$this->escapeHtmlAttr($this->recordSource)?>" data-type="<?=$this->escapeHtmlAttr($this->type)?>">
<?php endif ?>
  <?php
    $linkClasses = $this->classes;
    if ($this->authorityLink) {
      $linkClasses[] = 'authority-link';
    }
    $linkClasses = implode(' ', array_map([$this, 'escapeHtmlAttr'], $linkClasses));
    $linkClassesAttr = $linkClasses ? " class=\"{$linkClasses}\"" : '';
    $titleAttr = $this->title ? (' title="' . $this->escapeHtmlAttr($this->title) . '"') : '';
    $additionalDataEl = !empty($this->additionalData) ? "<span class=\"authority-additional-data\">{$this->additionalData}</span>" : '';
    $srLabel = $authorityIcon = '';
    if ($isAuthorityLink = $this->authorityLink && $this->authorityType) {
      $srLabel = $this->escapeHtmlAttr($this->translate($this->authorityType));
      $authorityIcon = 'fa-authority-' . $this->escapeHtmlAttr($this->record($this->record)->getFormatClass($this->authorityType));
    }
  ?>
  <a<?=$titleAttr?> href="<?=$this->escapeHtmlAttr($this->url)?>"<?=$linkClassesAttr?>><?php if ($isAuthorityLink): ?><i class="fa <?=$authorityIcon?>"></i><span class="sr-only"><?=$srLabel?></span> <?php endif; ?>
    <span class="authority-label"><?=$this->escapeHtml($this->label)?></span>
  </a><?= $additionalDataEl?><?php if ($this->showInlineInfo): ?> <a href="#" class="show-info"><?=$this->translate('authority_show_info')?></a>
  <div class="authority-info">
    <div class="content"><i class="fa fa-spin fa-spinner"></i></div>
    <div class="content-btn-holder"><a href="#" class="hide-info btn btn-primary"><?=$this->translate('authority_hide_info')?></a></div>
  </div>
</div>
<?php endif; ?>
