<!-- START of: finna - RecordDriver/DefaultRecord/core-fields.phtml -->
<?php foreach ($coreFields as $key => $current): ?>
  <?php $header = $this->transEsc($current['context']['title'] ?? $current['label']); ?>
  <?php if ($header): ?>
    <tr class="<?=$current['context']['class'];?>"><th><?=$header?></th><td><?=$current['value']?></td></tr>
  <?php else: ?>
    <?=$current['value']?>
  <?php endif; ?>
<?php endforeach; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/core-fields.phtml -->
