<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php
    $containerSource = $this->driver->getSourceIdentifier();
    $containerID = $this->driver->getContainerRecordID();
  ?>
  <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $data))?>"><?=$this->escapeHtml($data)?></a>
  <?php $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
<?php endif; ?>
