<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
<div class="truncate-field">
  <?php
    $result = '';
    $i = 0;
    foreach ($data as $class => $field) {
      $field = array_unique($field);
      foreach ($field as $j => $subfield) {
        $result = $class . ' ' . $subfield;
        $classForTranslation = 'classification::' . str_replace('::', ' ', $result);
        ?>
        <a title="<?=$this->escapeHtmlAttr($result)?>" href="<?=$this->record($this->driver)->getLink('classification', $result)?>"><?php if (!$this->translationEmpty($classForTranslation)): ?><?=$this->transEsc($classForTranslation) . '<span class="classification-detail"> (' . $this->escapeHtml($result) . ')</span>';?><?php else: ?><?=$this->escapeHtml($result); ?><?php endif; ?></a><br/>
      <?php
      }
    }
  ?>
</div>
<?php endif; ?>
