<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php
    $allLinks = [];
    foreach ($data as $link) {
      $allLinks[$link['title']][] = $link;
    }
  ?>
  <?php foreach ($allLinks as $title => $links): ?>
    <tr class="recordLinks">
      <th><?=$this->transEsc($title);?></th>
      <td>
        <?php foreach ($links as $link): ?>
          <a href="<?=$this->recordLink()->related($link['link'], true, $this->driver->getSourceIdentifier());?>"><?=$this->escapeHtml($link['value'] ?: $this->translate($title));?></a>
          <br />
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>
<?php endif; ?>
