<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php foreach ($data as $fields => $keys): ?>
    <?php if (!empty($keys['name'])): ?>
      <?=$this->escapeHtml($keys['name'])?><?php if (!empty($keys['region'])): ?>, <?=$this->escapeHtml($keys['region'])?><?php endif; ?>
      <?php if (!empty($keys['date'])): ?>
        <?=$this->escapeHtml($keys['date'])?>
      <?php endif; ?><br/>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>