<?php //Don't add START and END comments ?>
<?php if(!empty($data)): ?>
<div class="truncate-field">
  <?php if (!empty($data['credited']['presenters'])): ?>
      <?php foreach($data['credited']['presenters'] as $index => $author): ?>
        <?=($index > 0 ? '<br/> ' : '')?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null, 'showInlineInfo' => true])?>
      <?php endforeach; ?>
  <?php endif; ?>
  <?php if (!empty($data['uncredited']['presenters'])): ?>
    <div class="subheading"><?=$this->translate("Uncredited")?></div>
      <?php foreach($data['uncredited']['presenters'] as $index => $author): ?>
          <?=($index > 0 ? '<br/> ' : '')?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null, 'showInlineInfo' => true])?>
      <?php endforeach; ?>
  <?php endif; ?>
</div>
<?php endif; ?>

