<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <?php foreach ($data as $field): ?>
    <span property="publisher" typeof="Organization">
      <?php $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
         <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
      <?php endif; ?>
        <?php $pubName = $field->getName(); if (!empty($pubName)): ?>
      <span property="name"><?=$this->escapeHtml($pubName)?></span>
        <?php endif; ?>
      <?php $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
        <span property="datePublished"><?=$this->escapeHtml($pubDate)?></span>
      <?php endif; ?>
    </span>
  <?php endforeach; ?>
<?php endif; ?>
