<?php //Don't add START and END comments ?>
<?php if (!empty($data)): ?>
  <div class="truncate-field">
    <?php foreach ($data as $program): ?>
      <div class="program-line">
        <a class="backlink" title="<?=$this->escapeHtmlAttr($program)?>" href="<?=$this->record($this->driver)->getLink('program', $program)?>"><?=$this->escapeHtml($program) ?></a>
      </div>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
