<!-- START of: finna - RecordDriver/DefaultRecord/encapsulated-records.phtml -->
<?php if ($this->results->getResultTotal() > 0): ?>
  <div class="encapsulated-records public-list-embed<?= $this->showAllLink ? ' show-all' : ''?>">
    <div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->view)?>">
      <?php
        $viewParams = [
          'results' => $this->results,
          'params' => $this->params,
          'indexStart' => $this->indexStart,
          'hideCartControls' => true,
        ];
        if (!isset($this->layout()->templateDir)) {
          // This needs to be set so that list notes are shown
          $this->layout()->templateDir = 'record';
        }
      ?>
      <?=$this->partial('search/list-' . $this->view . '.phtml', $viewParams)?>
      <?php if ($this->showAllLink): ?>
        <?php $limit = $this->params->getLimit(); ?>
        <div class="show-more">
          <div>
            <?php
              $transParams = [
                '%%start%%' => 1,
                '%%end%%' => $limit,
                '%%total%%' => $this->localizedNumber($this->total),
              ];
            ?>
            <?=$this->translate('showing_results_of_html', $transParams)?>
          </div>
          <button class="btn btn-outline-primary load-more" aria-label="<?= $this->transEscAttr('See all')?>" data-id="<?= $this->escapeHtmlAttr($this->id)?>" data-start-index="<?= $this->escapeHtmlAttr($this->indexStart + $limit)?>" data-offset="<?= $this->escapeHtmlAttr($limit + 1)?>" data-view="<?= $this->escapeHtmlAttr($this->view)?>"<?= $this->sort ? (' data-sort="' . $this->escapeHtmlAttr($this->sort) . '"') : ''?>><?= $this->transEsc('See all'); ?></button>
          <?= $this->icon('spinner', 'js-spinner-icon hide') ?>
        </div>
      <?php endif; ?>
    </div>
  </div>
  <?php
    $this->assetManager()->appendScriptLink('finna-encapsulated-records.js');
    $js = <<<JS
        $(document).ready(function(){
          finna.encapsulatedRecords.init();
        });
        JS;
    $this->assetManager()->appendScriptString($js);
  ?>
<?php endif; ?>
<!-- END of: finna - RecordDriver/DefaultRecord/encapsulated-records.phtml -->
