<?php // this is used so often that it would pollute the results: <!-- START of: finna - RecordDriver/DefaultRecord/format-list.phtml --> ?>
<?php
  $formatMap = [];
  $formats = (array)$this->driver->tryMethod('getFormats');
  if ($formats) {
    // Take last level of each format main type
    foreach ($formats as $format) {
      $parts = explode('/', $format);
      if (isset($parts[1])) {
        $formatMap[$parts[1]] = $format;
      } else {
        $formatMap['-'] = $format;
      }
    }
  }
?>
<?php foreach ($formatMap as $format): ?>
  <span class="label label-info format-<?=$this->record($this->driver)->getFormatClass($format)?>"><?=$this->transEsc($format)?></span>
<?php endforeach; ?>
<?php // <!-- END of: finna - RecordDriver/DefaultRecord/format-list.phtml --> ?>
