<!-- START of Finna - RecordDriver/DefaultRecord/model-download.phtml -->
<div class="model-link">
    <?php if (count($models) > 1 && !$this->userAgent()->isBot()): ?>
        <div class="dropdown">
            <button class="btn btn-default dropdown-toggle download" type="button" id="downloadMenu-<?=$index?>" data-bs-toggle="dropdown" aria-expanded="false">
                <?=$this->transEsc('Download the file')?> <span class="caret"></span>
            </button>
            <ul class="dropdown-menu download" aria-labelledby="downloadMenu-<?=$index?>">
                <?php foreach ($models as $model): ?>
                    <li>
                        <?php
                            $url = $model['type'] === 'preview' ?
                                $this->url(
                                    'record-downloadmodel',
                                    [],
                                    [
                                        'query' => [
                                            'id' => $this->driver->getUniqueID(),
                                            'index' => $index,
                                            'format' => $model['format'],
                                            'type' => $model['type'],
                                        ],
                                    ]
                                ) : $this->escapeHtmlAttr($model['url']);
                        ?>
                        <a class="dropdown-item" download href="<?=$url?>" rel="nofollow">
                            <?=$this->transEscWithPrefix('model_type_', $model['type'])?>
                            <span><?=$this->transEscWithPrefix('model_format_', $model['format'])?></span>
                        </a>
                    </li>
                <?php endforeach; ?>
            </ul>
        </div>
    <?php else: ?>
        <div class="download-link">
            <?php
                $model = reset($models);
                $url = $model['type'] === 'preview' ?
                    $this->url(
                        'record-downloadmodel',
                        [],
                        [
                            'query' => [
                                'id' => $this->driver->getUniqueID(),
                                'index' => $index,
                                'format' => $model['format'],
                                'type' => $model['type'],
                            ],
                        ]
                    ) : $this->escapeHtmlAttr($model['url']);
            ?>
            <a download href="<?=$url?>" rel="nofollow">
                <?=$this->icon('download') ?>
                <span><?=$this->transEsc('Download the file')?></span>
            </a>
        </div>
    <?php endif; ?>
</div>
<!-- END of Finna - RecordDriver/DefaultRecord/model-download.phtml -->
