<!-- START of: finna - RecordDriver/DefaultRecord/record-image.phtml -->
<?php
  $formats = $this->driver->tryMethod('getFormats');
  $enableImagePopupZoom = $this->record($this->driver)->getImagePopupZoom();
?>
<div class="record-image-container <?= empty($images[0]['urls']['large']) && empty($images[0]['urls']['medium']) ? 'hide-image' : ''?>">
  <div class="recordcover-holder paginate" aria-hidden="true" data-format="<?=$this->transEsc(end($formats))?>" data-noimage="<?=$this->transEsc('no_image')?>">
  <?= $this->record($this->driver)->renderTemplate(
    'record-image-paginator.phtml',
    ['images' => $images, 'type' => $type, 'formats' => $formats, 'enableImagePopupZoom' => $enableImagePopupZoom,
     'numOfImages' => $numOfImages ?? null, 'displayIcon' => $displayIcon ?? false
    ]
  ); ?>
  </div>
  <?php if ($type != 'list' && $type != 'list grid'): ?>
    <?php $ind = 0; ?>
    <?php foreach ($images as $image): ?>
      <?php $rights = $image['rights']; ?>
      <div class="image-details-container<?=$ind > 0 ? ' hidden' : '' ?> text-left" data-img-index="<?=$ind ?>">
        <?php if ($this->record($this->driver)->allowRecordImageDownload()): ?>
          <?= $this->record($this->driver)->renderTemplate('image-download.phtml', ['index' => $ind, 'rights' => $rights, 'image' => $image, 'hiRes' => $image['highResolution'] ?? false]) ?>
        <?php endif; ?>
      <?= $this->record($this->driver)->renderTemplate('image-rights.phtml', ['imageRightsLabel' => $imageRightsLabel, 'rights' => $rights, 'truncateLicense' => $ind === 0]); ?>
      </div>
      <?php $ind++; ?>
    <?php endforeach; ?>
  <?php endif; ?>
</div>

<!-- END of: finna - RecordDriver/DefaultRecord/record-image.phtml -->
