<?php // Do not output this: <!-- START of: finna - RecordDriver/DefaultRecord/record-image-popup.phtml --> ?>
<?php
  $recordImage = $this->recordImage($this->record($this->driver));
  $largeImage = $recordImage->getLargeImage($this->index, ['w' => 1200, 'h' => 1200]);
  $originalImage = $recordImage->getMasterImage($this->index);
  $currentImage = $this->index + 1;
  $numOfImages = $this->record($this->driver)->getNumOfRecordImages('large');
  $imageDescription = $this->driver->tryMethod('getImageDescription', [$this->index]);
  $rights = $recordImage->getImageRights($this->index);
  $formats = $this->driver->tryMethod('getFormats');
  $translatedFormat = $this->transEsc(end($formats));
  $recordType = $this->driver->tryMethod('getRecordType');
  $largeImageLayout = in_array($this->driver->tryMethod('getRecordType'), ['lido', 'forward', 'ead', 'qdc']);
  $videoScripts = $this->partial('Helpers/videojs-urls.phtml');
?>
<div class="imagepopup-holder <?=$this->escapeHtmlAttr($recordType) ?>" data-type="<?=$this->escapeHtmlAttr($recordType) ?>" data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueID()) ?>">
  <div class="imagepopup-container">
    <div class="image iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>">
      <div id="leaflet-map-image" class="image-wrapper" data-large-image-layout="<?=$largeImageLayout?>" data-enable-image-popup-zoom="<?=$enableImagePopupZoom?>" >
      <?php if (! $enableImagePopupZoom || ! $largeImageLayout): ?>
        <img src="<?=$largeImage?>" />
      <?php endif; ?>
      <?php if ($largeImageLayout && $enableImagePopupZoom): ?>
        <div class="imagepopup-zoom-container">
          <div class="zoom-in zoom-button"><i class="fa fa-zoom-in" aria-hidden="true"></i><span class="sr-only">Zoom in</span></div>
          <div class="zoom-out zoom-button"><i class="fa fa-zoom-out" aria-hidden="true"></i><span class="sr-only">Zoom out</span></div>
          <div class="zoom-reset zoom-button"><i class="fa fa-zoom-100" aria-hidden="true"></i><span class="sr-only">Reset</span></div>
        </div>
      <?php endif; ?>
        </div>
    </div>
    <div class="content">
      <h3 id="popup-image-title" class="title"><?=$this->escapeHtml($this->driver->getTitle()) ?></h3>
      <div class="author-and-dates">
        <?php if ($recordType != 'lido'): ?>
          <p>
          <?php if ($author = $this->driver->getPrimaryAuthor()): ?>
            <?=$this->escapeHtml($author) ?>
            <?php endif; ?>
            <?php if ($dates = $this->driver->trymethod('getResultDateRange')): ?>
              <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
          <?php else: ?>
            <?php foreach ($this->driver->getPublicationDates() as $date): ?>
            <?=$this->escapeHtml($date) ?>
            <?php endforeach ?>
          <?php endif; ?>
          </p>
        <?php else: ?>
            <?php if ($results = $this->driver->getNonPresenterAuthors()): ?>
              <div class="truncate-field">
              <?php foreach($results as $index => $author): ?>
                <?=($index > 0 ? '; ' : '')?><?=$this->escapeHtml($author['name'])?><?php if (!empty($author['role'])): ?>, <?=$this->escapeHtml($author['role'])?><?php endif; ?>
              <?php endforeach; ?>
              <?php if ($dates = $this->driver->getResultDateRange()): ?>
                <?=$this->escapeHtml($dates[0]);?><?php if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><?php endif; ?>
              <?php endif; ?>
              <?php if ($results = $this->driver->getSubjectDates() && !isset($dates[0])): ?>
                <?=implode('<br/>', array_map([$this, 'escapeHtml'], $results))?>
              <?php endif; ?>
              </div>
            <?php endif; ?>
          <?php if ($photo = $this->driver->getPhotoInfo()): ?>
            <?=$this->transEsc('Photo Info') ?>: <?=$this->escapeHtml($photo) ?>
          <?php endif; ?>
        <?php endif; ?>
      </div>
      <div class="building">
        <?=$this->escapeHtml($this->organisationDisplayName($this->driver)) ?>
      </div>
      <div class="summary loading">
        <div data-rows="6" class="truncate-field">
        <?php if ($recordType == 'marc'): ?>
          <p></p>
        <?php else: ?>
          <?php if ($imageDescription): ?>
            <div id="popup-image-description" class="image-description">
              <p><strong><?=$this->transEsc('Image') ?>:</strong> <?=$this->escapeHtml($imageDescription) ?></p>
            </div>
          <?php endif; ?>
          <?php if ($summary = $this->driver->getSummary()): ?>
            <?php foreach ($this->driver->getSummary() as $item): ?>
              <p><?=$recordType == 'forward' ? $item : preg_replace('/&lt;br\/?&gt;/', '<br>', $this->escapeHtml($item)) /* Allow <br> tag */ ?></p>
            <?php endforeach ?>
          <?php endif ?>
        <?php endif ?>
        </div>
      </div>
      <?php if ($listNotes): ?>
        <div class="list-notes">
          <strong><?=$this->transEsc('Description') ?></strong><?php if ($listUser): ?><span class="notes-user"> (<?=$this->escapeHtml(trim($this->userPublicName($this->listUser)))?>)</span><?php endif; ?>:
          <ul>
          <?php foreach ($listNotes as $note): ?>
            <li><?=$this->markdown()->toHtml($note) ?></li>
          <?php endforeach; ?>
          </ul>
        </div>
      <?php endif; ?>
          <div class="popup-link-buttons">
          <?php
            $urls = $this->driver->getURLs();
            $onlineURLs = $this->driver->getOnlineURLs();
            $mergedData = $this->driver->tryMethod('getMergedRecordData');
            $images = $this->record($this->driver)->getAllRecordImageUrls();
          ?>
          <?php if (!empty($urls) || !empty($onlineURLs) || !empty($mergedData['urls'])): ?>
            <?php $index = 0; ?>
            <?php $renderedURLs = []; ?>
            <?php if (!empty($urls)): ?>
              <?php foreach ($urls as $url): ?>
                <?php
                  $renderedURLs[] = $url['url'];
                  $desc = $url['desc'] ?? $this->truncateUrl($url['url']);
                ?>

                <div class="record-online-link">
                  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>"
                      <?php if (!empty($url['videoSources'])): ?> data-video-sources="<?=$this->escapeHtmlAttr(json_encode($url['videoSources'])) ?>" data-scripts="<?=$this->escapeHtmlAttr($videoScripts)?>"<?php endif; ?>
                      <?=!empty($url['embed']) && $url['embed'] == 'video' ? ' data-embed-video' : '' ?>
                      <?=$this->recordLink()->getEmbeddedVideo($url['url']) ?>
                      target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('external_online_link'))?>">
                    <i class="fa fa-external-link"></i> <?php if (count($urls) == 1): ?><?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><?php else: ?><?=$this->transEsc('default::link_' . $desc, null, $desc) ?><?php endif; ?></a>
                </div>
                <?php if (++$index > 4): ?>
                  <div>...</div>
                <?php break; ?>
              <?php endif; ?>
              <?php endforeach; ?>
            <?php endif; ?>
            <?php if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
              <?php foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                <?php if (isset($images[$url['url']]) || in_array($url['url'], $renderedURLs)) { continue; } ?>
                <div class="record-online-link"><a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>"<?=!empty($url['embed']) && $url['embed'] == 'iframe' ? ' data-embed-iframe' : '' ?> target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('external_online_link'))?>"><i class="fa fa-external-link"></i><?php if (count($onlineURLs) == 1 || count($mergedData['urls']) == 1): ?> <?=$this->transEsc('open_online_link', ['%%format%%' => $translatedFormat])?><?php else: ?><?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?><?php endif; ?></a>
                <?php if ($url['source']): ?>
                  <span class="online-source"><?=is_array($url['source']) ? '(' . $this->transEsc('Multiple Organisations') . ')' : '';?></span>
                <?php endif; ?>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>
          <div class="record-link"><a href="<?=$this->recordLink()->getUrl($this->driver) ?>"><i class="fa fa-arrow-circle-right"></i><span><?=$this->transEsc('To the record') ?></span></a></div>
          <?php if ($this->userlist()->getMode() !== 'disabled'): ?><div class="save-record-link"><a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" class="save-record" data-lightbox data-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa fa-heart"></i><span><?=$this->transEsc('Add to favorites')?></span></a></div><?php endif; ?>
          <?php if (isset($rights['copyright']) && $rights['copyright'] !== $this->transEsc('usage_F')): ?>
            <div class="open-link"><a target="_blank" class="original-image-url" href="<?=$this->escapeHtmlAttr($originalImage) ?>" download="<?=$this->escapeHtmlAttr($originalImage) ?>"><i class="fa fa-download"></i><span><?=$this->transEsc('Download the image') ?></span></a> <span class="image-dimensions"></span></div>
          <?php else: ?>
            <a class="original-image-url hidden" href="<?=$originalImage ?>">Hidden</a>
          <?php endif ?>
        </div>
        <div class="image-rights">
          <div class="rights">
            <?php $hasLink = isset($rights['link']); ?>
            <span><?=$this->transEsc('Image Rights') ?>:</span>
            <?php if (!empty($rights['copyright'])): ?>
              <?php if ($hasLink): ?><a target="_blank" href="<?=$rights['link'] ?>"><?php endif; ?><?php if ($this->transEsc($rights['copyright']) === "Luvanvarainen käyttö / ei tiedossa"): ?><?= $this->transEsc('usage_F') ?><?php else: ?><?=$this->transEsc($rights['copyright']) ?><?php endif; ?><?php if ($hasLink): ?></a><?php endif; ?>
            <?php else: ?>
              <?php if (in_array('usage_F', $this->driver->tryMethod('getUsageRights', [], []))): ?>
                <?=$this->transEsc('usage_F') ?><br>
              <?php endif; ?>
            <?php endif; ?>
          </div>
          <?php if (!empty($rights['copyright']) && (isset($rights['description']))): ?>
            <div class="more-link copyright-link"><a data-mode="1" href=""><?=$this->transEsc('show_more') ?><i class="fa fa-arrow-down"></i></a></div>
            <div class="copyright">
          <?php endif; ?>
          <?php if (isset($rights['description'])): ?>
            <?php foreach ($rights['description'] as $item): ?>
              <p><?=$this->transEsc($item) ?></p>
            <?php endforeach; ?>
          <?php endif; ?>
          <?php if (!isset($rights['copyright']) && !isset($rights['description'])): ?>
            <p><?=$this->transEsc('Image Rights Default') ?>
            <p><a href="<?=$this->url('content-page', ['page' => 'terms']) . '#image_rights' ?>"><i class="fa fa-arrow-right"></i><?=$this->transEsc('See terms and conditions') ?></a>
          <?php endif; ?>
          <?php if (!empty($rights['copyright']) && (isset($rights['description']))): ?>
            </div>
            <div class="less-link copyright-link"><a data-mode="0" href=""><?=$this->transEsc('show_less') ?><i class="fa fa-arrow-up"></i></a></div>
          <?php endif; ?>
          <?php if ($this->resolver('record/record-organisation-menu.phtml')): ?>
            <?=$this->render('record/record-organisation-menu.phtml') ?>
          <?php endif; ?>
        </div>
      <div style="clear: both;"></div>
    </div>
    <div class="image-info">
      <?php if ($numOfImages > 1): ?>
        <div class="image-index"><?=$this->transEsc('Image') . " $currentImage / $numOfImages" ?></div>
      <?php endif; ?>
      <div class="record-index"><span class="index"></span> / <span class="total"></span></div>
    </div>
    <div style="clear: both;"></div>
  </div>
  <?php
    // NOTE: Piwik js-script must be inserted inside an element (not at the template root).
    // Otherwise Magnific popup close button gets appended to the script tag which causes a js-error...
  ?>
  <?=
  $this->piwik([
    'lightbox' => true, 'record' => $this->driver, 'action' => 'imagePopup',
    'recordUrl' => $this->recordLink()->getUrl($this->driver)
  ]);
  ?>
  <script>
    finna.layout.initOrganisationPageLinks();
    finna.layout.initTruncate($('.imagepopup-holder'));
  </script>
</div>
<?php // Do not output this: <!-- END of: finna - RecordDriver/DefaultRecord/record-image-popup.phtml --> ?>
