<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  $isList = ($type === 'list' || $type === 'list grid');
  $enableImageZoom = (isset($enableImagePopupZoom) && $enableImagePopupZoom) && in_array($this->driver->tryMethod('getRecordType'), ['lido', 'forward', 'ead', 'qdc']);
?>
<?php if ($type === 'record' || !$this->userAgent()->isBot()): ?>
  <?php
    $ind = 0;
    $paginatedLinks = [];
    $recordImage = $this->recordImage($this->record($this->driver));
  ?>
  <?php foreach ($images as $img): ?>
    <?php
      $originalImageData = $recordImage->getMasterImageWithInfo($ind);
      $originalImage = $originalImageData['url'] ?? false;
      $desc = isset($img['description']) && !empty($img['description']) ? $img['description'] : $this->transEsc('Cover Image');
      $obj = [
        'small' => $img['urls']['small'],
        'medium' => $img['urls']['medium'],
        'largest' => $enableImageZoom && $originalImage !== false ? $originalImage : $img['urls']['large'] ?? $img['urls']['medium'],
        'index' => $ind++,
        'alt' => $desc,
        'description' => $img['description'],
        'title' => $this->transEsc('Image') . ' ' . $ind
      ];
      $paginatedLinks[] = $obj;
    ?>
  <?php endforeach; ?>
  <?php if (!$this->userAgent()->isBot()): ?>
    <?php if (!empty($images[0]['urls']['medium']) || !empty($images[0]['urls']['large'])): ?>
      <div class="recordcover-container">
        <button class="next-image left" type="button"><i class="fa fa-chevron-left"></i><span class="sr-only"><?= $this->transEsc('previous_image') ?></span></button>
        <?php if (!$this->disableModal): ?>
          <a class="image-popup-trigger" href="<?=$this->recordLink()->getUrl($this->driver) ?>#image">
        <?php else: ?>
          <span class="image-popup-trigger" data-disable-modal="1">
        <?php endif; ?>
        <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
        <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>"/>
        <div class="paginator-info"><span class="image-index"></span></div>
        <?php if (!$this->disableModal): ?>
          </a>
        <?php else: ?>
          </span>
        <?php endif; ?>
        <span class="hidden-trigger" hidden></span>
        <button class="next-image right" type="button"><i class="fa fa-chevron-right"></i><span class="sr-only"><?= $this->transEsc('next_image') ?></span></button>
      </div>
    <?php endif; ?>
  <?php else: ?>
    <a href="<?=$this->escapeHtmlAttr($img['urls']['large'] ?? $img['urls']['medium']) ?>"><?=($ind + 1) ?></a>
  <?php endif; ?>
  <div class="recordcover-image-detail">
    <p class="image-description">
    </p>
  </div>
  <div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
    <button class="left-button" type="button" title="<?= $this->transEsc('previous_images') ?>"><i class="fa fa-handle-left"></i><span class="sr-only"><?= $this->transEsc('previous_images') ?></span></button>
    <div class="track-holder paginator-mask">
      <div class="finna-element-track"></div>
    </div>
    <button class="right-button" type="button" title="<?= $this->transEsc('next_images') ?>"><i class="fa fa-handle-right"><span class="sr-only"><?= $this->transEsc('next_images') ?></span></i></button>
    <div class="paginator-info"><span class="image-index"></span></div>
  </div>
  <div class="recordcovers-more more-area">
    <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <i class="fa fa-arrow-down"></i></button>
    <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <i class="fa fa-arrow-up"></i></button>
  </div>
  <?php if (count($paginatedLinks) > 0): ?>
    <?php
      $settings = [
        'recordId' => $this->driver->getUniqueId(),
        'recordType' => $this->driver->tryMethod('getRecordType'),
        'imagesPerPage' => 8,
        'imagesOnMobile' => $numOfImages['mobile'] ?? 4,
        'imagesOnNormal' => $numOfImages['mobile'] ?? 8,
        'imagesOnPopup' => $numOfImages['mobile'] ?? 8,
        'enableImageZoom' => $enableImageZoom,
        'maxRows' => 3,
        'iconlabelClass' => "format-" . $this->record($this->driver)->getFormatClass(end($formats)),
        'isList' => $type === 'list' || $type === 'list grid'
      ];
      $script = 'finna.imagePaginator.initPaginator(' . json_encode($paginatedLinks) . ', ' . json_encode($settings) . ');';
      echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
    ?>
  <?php endif; ?>
<?php endif;?>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
