<!-- START of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
<?php
  $videoElementBase = [
    'class' => 'videourl fulltext btn btn-primary',
    'type' => 'button'
  ];
  $this->htmlElement()->addAttributeTemplate('video-base', $videoElementBase);
?>
<div class="video-accordion">
  <?php foreach ($videoUrls as $url): ?>
    <?php
    $embeddedVideo = $this->recordLink()->getEmbeddedVideo($url['url']);
    $desc = $url['desc'] ?? $this->truncateUrl($url['url']);

    if (isset($type) && $type === 'SolrEad') {
      $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $this->translate('link_' . $url['desc'], null, $url['desc']);
    } elseif (isset($type) && $type === 'SolrForward') {
      $desc = $this->translate('default::link_' . $desc, null, $desc);
    } else {
      $desc = $embeddedVideo === 'data-embed-iframe' ? $this->translate('format_Video') : $desc;
    }
    $description = $this->escapeHtml($desc);

    $currentVideo = [
      'data-link' => $this->proxyUrl($url['url']),
      'title' => $url['url'],
    ];

    if (!empty($embeddedVideo)) {
      $currentVideo[$embeddedVideo] = '';
    }

    if (!empty($url['videoSources'])) {
      $currentVideo['data-video-sources'] = json_encode($url['videoSources']);
      $currentVideo['data-scripts'] = json_encode([
        'js-videojs' => $this->headScript()->itemToString(
          $this->headScript()->createData('text/javascript', ['src' => 'vendor/video.min.js', 'id' => 'js-videojs']),
          '', '', ''
        ),
        'js-videojs-hotkeys' => $this->headScript()->itemToString(
          $this->headScript()->createData('text/javascript', ['src' => 'vendor/videojs.hotkeys.min.js', 'id' => 'js-videojs-hotkeys']),
          '', '', ''
        ),
        'js-videojs-quality' => $this->headScript()->itemToString(
          $this->headScript()->createData('text/javascript', ['src' => 'vendor/videojs-contrib-quality-levels.js', 'id' => 'js-videojs-quality']),
          '', '', ''
        )
      ]);
    }

    if (!empty($url['embed']) && $url['embed'] === 'video') {
      $currentVideo['data-embed-video'] = '';
    }
    ?>
    <div class="video-link-container">
      <button <?=$this->htmlElement()->getAttributes($currentVideo, 'video-base');?>>
        <i class="fa fa-play-circle"></i>
        <?=$description?>
      </button>
    </div>
  <?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-video-player.phtml -->
