<!-- START of: finna - RecordDriver/DefaultRecord/record-audio-player.phtml -->
<?php
  $this->partial('Helpers/videojs-translations.phtml');
?>
<div class="audio-accordion">
<?php foreach ($audioUrls as $ind => $url):
    $format = $this->driver->tryMethod('getRecordFormat', [], '');
    $showDetails = $showFormat = false;
    if ($format === 'lido') {
      $showDetails = true;
      $showFormat = $url['desc'] === $url['url'];
    }
  ?>
  <div class="audio-item-wrapper">
    <div class="audio-title-wrapper">
      <div class="audio-title">
      <?php if (!empty($url['desc']) && !$showFormat): ?>
        <strong><?= $this->escapeHtml($this->translate('link_' . $url['desc'], null, $url['desc'])); ?></strong>
      <?php else: ?>
        <strong><?=$this->transEsc('format_Sound')?></strong>
      <?php endif ?>
      </div>
    </div>
    <div class="audio-accordion-item">
      <a class="play" tabindex="0" aria-label="<?=$this->transEsc('Play recording')?>">
        <?=$this->icon('audio-play') ?>
      </a>
      <div class="audio-player-wrapper hide">
        <audio id="audio-<?=$ind?>" class="vjs-default-skin hide" autoplay controls preload="auto">
          <source data-src="<?=$url['url']?>" type="audio/<?= $url['codec'] ?>">
        </audio>
      </div>
      <?php if (!$showDetails): ?>
        <div class="open-link"><a target="_blank" href="<?=$url['url'] ?>"><?=$this->icon('download') ?> <?=$this->transEsc('Download recording') ?></a></div>
      </div>
      <?php else: ?>
        </div>
        <?=$this->record($this->driver)->renderTemplate('audio-information.phtml', ['ind' => $ind, 'url' => $url]);?>
      <?php endif; ?>
  </div>
<?php endforeach; ?>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-audio-player.phtml -->
