<?php //Don't add start and end tags ?>
<?php if ($this->driver->isRatingAllowed()): ?>
  <?php if (!$this->translationEmpty('finna rating')): ?>
    <div><?=$this->transEsc('finna rating') ?></div>
  <?php endif; ?>
  <?=$this->record($this->driver)->renderTemplate('rating.phtml')?>
<?php endif; ?>
<?php if ($template = $this->content()->findTemplateForLng('content/Additions/record-post-toolbar')): ?>
  <div>
    <div class="record-post-toolbar">
      <?=$this->render($template)?>
    </div>
  </div>
<?php endif; ?>
<?php
  $script = <<<JS
      $('.rating-link').on('click', function () {
        $('a.usercomments').click();
        $('html, body').animate(
          {
            scrollTop: $('.record-tabs').offset().top
          }, 500
        );
      });
      JS;
  echo $this->assetManager()->outputInlineScriptString($script);
?>
