<!-- START of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
<?php
  if (!$images) {
    return;
  }
  $isList = ($type === 'list' || $type === 'list grid');
  $isBot = $this->userAgent()->isBot();
  if ($isBot && $type !== 'record') {
    return;
  }
?>
<?php if ($isBot): ?>
  <?php foreach ($this->recordImage($this->record($this->driver))->getImagesForBotUser($images) as $image): ?>
    <div>
      <?php if ($image['pdf']): ?>
        <a href="<?=$this->escapeHtmlAttr($image['url'])?>"><?=$this->escapeHtml($image['id']);?></a>
      <?php else: ?>
        <img src="<?=$this->escapeHtmlAttr($image['url'])?>">
      <?php endif;?>
    </div>
    <br>
  <?php
    endforeach;
    // Notice this return statement for bots.
    return;
  ?>
<?php endif; ?>

<?php
  $renderedImagesCount = count($images);
  $totalImagesCount = $this->driver->tryMethod('getTotalAmountOfImages') ?? $renderedImagesCount;
  $settings = [
    'recordId' => $this->driver->getUniqueId(),
    'recordType' => $this->driver->tryMethod('getRecordFormat'),
    'recordSource' => $this->driver->tryMethod('getSourceIdentifier'),
    'enableImageZoom' => $this->record($this->driver)->getImagePopupZoom(),
    'maxRows' => 3,
    'iconlabelClass' => 'format-' . $this->record($this->driver)->getFormatClass(end($formats)),
    'isList' => $type === 'list' || $type === 'list grid',
    'recordCovers' => 'recordcovers',
    'displayIcon' => $displayIcon,
    'triggerClick' => $this->imageClick ?? 'modal',
    'totalImagesCount' => $totalImagesCount,
  ];
  if ($this->driver->tryMethod('getModels')) {
    $modelSettings = $this->driver->tryMethod('getModelSettings', [], []);
    $settings['modelTranslations'] = $this->partial('Helpers/modeljs-translations.phtml');
    $settings['viewerDebug'] = $modelSettings['debug'] ?? false;
  }
?>

<div class="recordcover-container">
  <button class="next-image left" type="button"><?=$this->icon('image-previous') ?><span class="visually-hidden"><?= $this->transEsc('previous_image') ?></span></button>
  <a class="image-popup-trigger init" draggable="false" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver)) ?>" data-images="<?=htmlspecialchars(json_encode($images ?? []), ENT_QUOTES, 'UTF-8');?>" data-settings="<?=htmlspecialchars(json_encode($settings ?? []), ENT_QUOTES, 'UTF-8');?>" tabindex="-1">
    <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
    <div class="paginator-info d-flex align-items-center">
      <span class="image-index"></span>
      <?php if ($renderedImagesCount < $totalImagesCount): ?>
        <?=$this->component('finna-toggletip', [
          'icon' => 'help',
          'contentHtml' => $this->translate('showing_results_of_html', ['%%start%%' => 1, '%%end%%' => $renderedImagesCount, '%%total%%' => $totalImagesCount]),
          'class' => 'partial-images',
        ]);?>
      <?php endif; ?>
    </div>
    <img src="<?=$this->imageSrc()->getDataPixel()?>" data-src="<?=$this->url('cover-unavailable')?>" class="recordcover<?= ($images[0]['pdf'] ?? false) ? ' pdf-cover' : ''?>" alt="<?=$this->transEsc('No Cover Image')?>">
  </a>
  <span class="hidden-trigger" hidden></span>
  <button class="next-image right" type="button"><?=$this->icon('image-next') ?><span class="visually-hidden"><?= $this->transEsc('next_image') ?></span></button>
</div>

<div class="recordcover-image-detail">
  <p class="image-description"></p>
</div>

<div class="recordcovers <?=$this->escapeHtmlAttr($type)?>">
  <button class="left-button" type="button" title="<?= $this->transEsc('previous_images') ?>"><?=$this->icon('image-previous') ?><span class="visually-hidden"><?= $this->transEsc('previous_images') ?></span></button>
  <div class="track-holder paginator-mask">
    <div class="finna-element-track"></div>
  </div>
  <button class="right-button" type="button" title="<?= $this->transEsc('next_images') ?>"><?=$this->icon('image-next') ?><span class="visually-hidden"><?= $this->transEsc('next_images') ?></span></button>
</div>
<div class="recordcovers-more more-area">
  <button type="button" class="show-more-images"><?= $this->transEsc('more') ?> <?=$this->icon('image-more') ?></button>
  <button type="button" class="show-less-images"><?= $this->transEsc('less') ?> <?=$this->icon('image-less') ?></button>
</div>
<!-- END of: finna - RecordDriver/DefaultRecord/record-image-paginator.phtml -->
