<?php //Don't add start and end tags ?>
<div class="record-rating text-left">
  <div class="rating-stars">
    <div class="rating-link">
        <?=$this->record($this->driver)->getRating()?>
    </div>
  </div>
</div>
<?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-toolbar")): ?>
  <div>
    <div class="record-post-toolbar">
      <?=$this->render($template)?>
    </div>
  </div>
<?php endif; ?>
<?php
  $script = <<<JS
$('.rating-link').click(function () {
  $('a.usercomments').click();
  $('html, body').animate(
    {
      scrollTop: $('.record-tabs').offset().top
    }, 500
  );
});
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
