<h1>O que estou vendo?</h1>

<p>Este é um <a href="http://www.cs.umd.edu/hcil/treemap/">treemap</a>, um tipo de visualização comumente usado para dados com categorias hierárquicas.</p >

<h1>O que isso pode me dizer?</h1>

<p>Este mapa em árvore ajuda você a ver como os livros e outros itens que correspondem à sua busca estão distribuídos em áreas de assunto amplas (conforme indicado pelas primeiras letras dos números de chamada) e os tópicos específicos cobertos pelos itens de cada área.</p>

<p>Observe que cada item geralmente possui vários tópicos, portanto o número de tópicos cobertos pelos itens em uma determinada área será maior que o número total de itens nessa área.
</p>

<h1>Como posso interagir com ele?</h1>

<p>Você pode clicar em uma área de assunto ampla para ampliar e examinar os tópicos dessa área ou pode clicar em um tópico para ver os livros e outros itens sobre esse tópico naquela área de assunto. Você também pode usar qualquer uma das facetas na barra lateral direita para restringir sua busca e ver rapidamente como, por exemplo, limitar sua busca por ano ou por formato altera os assuntos e tópicos incluídos em seus resultados.</p>

<p>Se algum texto estiver cortado, você pode passar o mouse sobre essa caixa para ver o texto completo em um pop-up.</p>
