<? $data = $this->recommend->getResults(); if (is_array($data)): ?>
  <div class="sidegroup rssResults">
    <div class="suggestionHeader">
    <a href="http://www.europeana.eu/portal/" title="Europeana.eu" target="_blank">
      <img src="<?=$this->imageLink(strtolower($data['feedTitle']) . '.png')?>"/>
    </a>
    </div>
    <div>
      <ul class="list-group">
        <? $i = 0; foreach ($data['worksArray'] as $workKey => $work): ?>
          <li class="list-group-item suggestedResult <? (++$i % 2) ? 'alt ' : ''?>record<?=$i?>">
            <div class="resultitem clearfix">
              <? if (isset($work['enclosure'])): ?>
                <span class="europeanaImg"><img src="<?=$this->escapeHtmlAttr($work['enclosure'])?>" id="europeanaImage<?=$this->escapeHtmlAttr($workKey)?>"/></span>
              <? endif; ?>
              <a href="<?=$this->escapeHtmlAttr($work['link'])?>" target="_blank">
                <span><?=$this->escapeHtml($this->truncate($work['title'], 90))?></span>
              </a>
            </div>
          </li>
        <? endforeach; ?>
      </ul>
      <p class="olSubjectMore">
        <a href="<?=$this->escapeHtmlAttr($data['sourceLink'])?>" title="<?=$this->escapeHtmlAttr($data['feedTitle'])?>" target="_blank">
          <?=$this->transEsc('more')?>...
        </a>
      </p>
    </div>
  </div>
  <div class="clearfix"></div>
<? endif; ?>