<?
    // Set up Javascript for use below:
    $loadJs = 'var url = VuFind.getPath() + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
        . "\$('#openLibraryDeferredRecommend').load(url);";
?>
<div id="openLibraryDeferredRecommend">
    <p><?=$this->transEsc("Loading")?>&nbsp;... <img src="<?=$this->imageLink('ajax_loading.gif')?>" /></p>
    <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>