<?
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.getPath() + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "\$('#SummonDeferredDatabases').load(url);";
?>
<div id="SummonDeferredDatabases">
  <p><?=$this->transEsc("Loading")?>&nbsp;... <i class="fa fa-spinner"></i></p>
  <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>