<!-- recommend - topfacets.phtml -->
<?
  // TODO: This file needs love
  $topFacetSet = $this->recommend->getTopFacetSet();
  $topFacetSettings = $this->recommend->getTopFacetSettings();
?>
<? if (isset($topFacetSet)): ?>
  <? $row=0; foreach($topFacetSet as $title => $cluster): ?>
    <? $moreClass = ' NarrowGroupHidden_'.$this->escapeHtml($title).' hide'; ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <strong><?=$this->transEsc($cluster['label'])?></strong><?=$this->transEsc("top_facet_suffix") ?>
    <div class="row top-row">
    <? $iter=1;$corner=$topFacetSettings['rows']*$topFacetSettings['cols']; ?>
    <? foreach($cluster['list'] as $thisFacet): ?>
      <? /* More link */ ?>
      <? if ($iter == $corner+1): ?>
        </div><div id="more-NarrowGroupHidden_<?=$this->escapeHtml($title)?>" class="row top-row">
          <span class="medium-12 columns"><a href="#" onclick="moreFacets('NarrowGroupHidden_<?=$this->escapeHtml($title)?>'); return false;"><?=$this->transEsc('more') ?> ...</a></span>
        </div><div class="row top-row <?=$moreClass ?>">
      <? endif; ?>
      <? /* Columns */ ?>
      <span class="medium-<?=floor(12/$topFacetSettings['cols'])?> columns <? if ($iter == $corner+1) echo $moreClass ?>">
        <? if ($thisFacet['isApplied']):
          if (isset($thisFacet['specialType']) && $thisFacet['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($thisFacet['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']);
          } ?>
          <a href="<?=$removeLink ?>" class="applied">
          <?=$this->escapeHtml($thisFacet['displayText'])?> <i class="fa fa-check"></i>
          </a>
        <? else: ?>
          <a href="<?=$this->currentPath().$this->recommend->getResults()->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator'])?>"><?=$this->escapeHtml($thisFacet['displayText'])?></a> <span class="label"><?=$this->localizedNumber($thisFacet['count']) ?>
          <? if ($allowExclude): ?>
            <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT')?>" title="<?=$this->transEsc('exclude_facet')?>"><i class="fa fa-times"></i></a>
          <? endif; ?>
          </span>
        <? endif; ?>
      </span>
      <? /* Close rows */ ?>
      <? if ($iter%$topFacetSettings['cols'] == 0 && $iter > 0): ?></div><div class="row top-row<? if(++$row > $topFacetSettings['rows']) echo $moreClass ?>"><? endif; ?>
      <? /* Less link */ ?>
      <? if (count($cluster['list']) > $corner && $iter == count($cluster['list'])): ?>
        <a class="medium-12 columns" href="#" onclick="lessFacets('NarrowGroupHidden_<?=$title ?>'); return false;"><?=$this->transEsc('less') ?> ...</a>
      <? endif; ?>
      <? $iter++; ?>
    <? endforeach; ?>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!-- recommend - topfacets.phtml - END -->