<?php
/* BEACON (Findbuch) references over API proxy
 *
 * Filter entries from BEACON references if they are already listed in Bibliographical References.
 * Because the labels dont match, we can filter only due to a given map, else we would lose entries we want to keep
 * e.g. 'GND' => 'REGESTA IMPERII RI OPAC GND'.
 */
$filterLabelMap = ['Wikipedia' => 'Wikipedia-Artikel'];
$bibliographicalReferences = $this->driver->getBibliographicalReferences();
$bibliographicalReferenceTitles = [];
foreach ($bibliographicalReferences as $bibliographicalReference) {
  if (isset($filterLabelMap[$bibliographicalReference['title']]))
    $bibliographicalReferenceTitles[] = $filterLabelMap[$bibliographicalReference['title']];
}
$filterLabelPattern = implode('|', $bibliographicalReferenceTitles);
$sortBottomPattern = 'B3Kat|Bayerische Staatsbibliothek|HBZ-Verbundkatalog|HeBIS|Nordrhein-Westfälische Bibliographie|SWB-Verbundkatalog|Universitätsbibliothek Heidelberg';
?>

<div class="tf-findbuch-references" data-url="<?=$this->url('findbuchproxy-load')?>?gnd=<?=$this->driver->getGNDNumber()?>" data-filter-unique-pattern="<?=$this->driver->getGNDNumber()?>" data-headline="<?=$this->transEsc('External Resources')?>" data-sort-bottom-pattern="<?=htmlspecialchars($sortBottomPattern)?>" data-filter-label-pattern="<?=htmlspecialchars($filterLabelPattern)?>"></div>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'TueFind.GetBeaconReferencesFromFindbuch();', 'SET')?>
