<table class="table table-striped">
  <tbody>
    <?php $birth = $this->authority()->getBirth($this->driver); ?>
    <?php if ($birth != ''): ?>
      <tr>
        <th><?=$this->transEsc('Born')?>:</th>
        <td><?=$birth?></td>
      </tr>
    <?php endif; ?>

    <?php $death = $this->authority()->getDeath($this->driver); ?>
    <?php if ($death != ''): ?>
      <tr>
        <th><?=$this->transEsc('Died')?>:</th>
        <td><?=$death?></td>
      </tr>
    <?php endif; ?>

    <?php $occupations = $this->authority()->getOccupations($this->driver);?>
    <?php if ($occupations != ''): ?>
      <tr>
        <th><?=$this->transEsc('Occupation')?>:</th>
        <td><?=$occupations?></td>
      </tr>
    <?php endif; ?>

    <?php $relations = $this->authority()->getPersonalRelations($this->driver); ?>
    <?php if ($relations != ''): ?>
      <tr>
        <th><?=$this->transEsc('Personal Relations')?>:</th>
        <td><?=$relations?></td>
      </tr>
    <?php endif; ?>

    <?php $relations = $this->authority()->getCorporateRelations($this->driver); ?>
    <?php if ($relations != ''): ?>
      <tr>
        <th><?=$this->transEsc('Corporate Relations')?>:</th>
        <td><?=$relations?></td>
      </tr>
    <?php endif; ?>

    <?php if ($driver->getType() == 'meeting'): ?>
      <?php $timespans = $driver->getTimespans(); ?>
      <?php if (count($timespans) != ''): ?>
        <tr>
          <th><?=$this->transEsc('Time')?></th>
          <td>
            <?php foreach ($timespans as $timespan): ?>
              <?=$timespan . '<br>'?>
            <?php endforeach; ?>
          </td>
        </tr>
      <?php endif; ?>

      <?php $places = $this->authority()->getGeographicalRelations($this->driver); ?>
      <?php if ($places != ''): ?>
        <tr>
          <th><?=$this->transEsc('Geographical Relations')?>:</th>
          <td><?=$places?></td>
        </tr>
      <?php endif; ?>
    <?php endif; ?>

    <?php $bibliographicalReferences = $this->authority()->getBibliographicalReferences($this->driver); ?>
    <?php if ($bibliographicalReferences != ''): ?>
      <tr>
        <th><?=$this->transEsc('Biographical References')?>:</th>
        <td><?=$bibliographicalReferences?></td>
      </tr>
    <?php endif; ?>

    <?php $archivedMaterial = $this->authority()->getArchivedMaterial($this->driver); ?>
    <?php if ($archivedMaterial != ''): ?>
      <tr>
        <th><?=$this->transEsc('Archived Material')?>:</th>
        <td><?=$archivedMaterial?></td>
      </tr>
    <?php endif; ?>

    <?php $externalSubsystems = $this->authority()->getExternalSubsystems($this->driver, $this->tuefind()->getTueFindSubtype()); ?>
    <?php if ($externalSubsystems != ''): ?>
      <tr>
        <th><?=$this->transEsc('Subsystems')?>:</th>
        <td><?=$externalSubsystems?></td>
      </tr>
    <?php endif; ?>
  </tbody>
</table>
