<?php if ($this->pageCount): ?>
  <div class="col-12 pt-3">
    <nav aria-label="pagination">
      <ul class="pagination">
        <?php if (isset($this->previous)): ?>
          <?php if (!isset($this->options['disableFirst']) || !$this->options['disableFirst']): ?>
            <li class="page-item"><a class="page-link" href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage(1)?>">[1]</a></li>
          <?php endif; ?>
          <li><a class="page-link" href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>">&laquo; <?=$this->transEsc('Prev')?></a></li>
        <?php endif; ?>

        <?php if (count($this->pagesInRange) > 1): ?>
          <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
              <li class="page-item"><a class="page-link" href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($page)?>"><?=$page?></a></li>
            <?php else: ?>
              <li class="page-item active"><span class="page-link"><?=$page?></span></li>
            <?php endif; ?>
          <?php endforeach; ?>
        <?php endif; ?>

        <?php if (isset($this->next)): ?>
          <li class="page-item"><a class="page-link" href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><?=$this->transEsc('Next');?> &raquo;</a></li>
          <?php if (!isset($this->options['disableLast']) || !$this->options['disableLast']): ?>
            <li class="page-item"><a class="page-link" href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->pageCount)?>">[<?=$this->pageCount?>]</a></li>
          <?php endif; ?>
        <?php endif; ?>
      </ul>
    </nav>
  </div>
<?php endif; ?>