<div class="col-xs-12 col-sm-6 col-md-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/librarians.jpg') ?>" alt="Bild Bibliothekare" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>For Librarians</h4>
        <p>What does IxTheo offer for librarians?</p>
        <a href="#" class="btn btn-default" role="button">Read more</a>
    </div>
</div>
