<? if (isset($list)): ?>
  <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($list->id)?>" />
  <input type="hidden" name="listName" value="<?=$this->escapeHtmlAttr($list->title)?>" />
<? endif; ?>
<? $user = $this->auth()->isLoggedIn(); ?>
<div class="row bulk-action-buttons-row">
  <div class="col-xs-12 bulk-action-buttons-col">
  <div class="checkboxFilter mylist-select-all">
    <label class="checkbox">
      <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
      <?=$this->transEsc('select_page')?>
    </label>
  </div>
    <span class="hidden-xs"> | <?=$this->transEsc('with_selected');?></span>
  <div class="btn-group mylist-functions">
    <input class="btn btn-primary" type="submit" name="email" value="<?=$this->transEsc('Email')?>" title="<?=$this->transEsc('email_selected')?>"/>
    <? $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
      <input class="btn btn-primary" type="submit" name="export" value="<?=$this->transEsc('Export')?>" title="<?=$this->transEsc('export_selected')?>"/>
    <? endif; ?>
    <? if ((!is_null($this->list) && $this->list->editAllowed($user)) || is_null($this->list) && $user): ?>
      <input class="btn btn-primary" id="<?=$this->idPrefix?>delete_list_items_<?=!is_null($this->list) ? $this->escapeHtmlAttr($this->list->id) : ''?>" type="submit" name="delete" value="<?=$this->transEsc('Delete')?>" title="<?=$this->transEsc('delete_selected')?>"/>
    <? endif; ?>
    <input class="btn btn-primary" type="submit" name="" value="<?=$this->transEsc('Add to list')?> (TODO)" title="<?=$this->transEsc('Add to list')?>"/>
    <? if ($this->cart()->isActive()): ?>
      <input class="btn btn-default" id="<?=$this->idPrefix?>updateCart" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
    <? endif; ?>
  </div>
  </div>
</div>