<!-- START of: finna - myresearch/change-messaging-settings.phtml -->
<?=$this->flashmessages()?>
<? if (empty($profile['email'])): ?>
<div class="alert alert-danger">
  <?=$this->transEsc('no_email_address')?>
  <?=$this->transEsc('no_email_address_text')?>
</div>
<? else: ?>
<form method="post" action="<?=$this->url('home') . ('MyResearch/ChangeMessagingSettings')?>" class="messaging-settings-form profile-form">
  <table class="table useraccount-table">
    <? foreach ($this->services as $service=>$data): ?>
    <tr>
      <th><?=$data['type'] ?></th>
      <td>
        <select name="<?=$service ?>">
          <? foreach ($data['sendMethods'] as $method=>$methodData): ?>
            <? if (!($service == 'dueDateAlert' && $method == 'email')): ?>
              <option value="<?=$methodData['type'] ?>"<? if ($methodData['active']): ?> selected<? endif; ?>><?=$methodData['method'] ?></option>
            <? endif; ?>
          <? endforeach; ?>
          <? if ($service == 'dueDateAlert'): ?>
            <? foreach ($this->emailDays as $day=>$label): ?>
              <option value="<? $day+1 ?>"<? if ($data['numOfDays'] == $day+1): ?> selected<? endif; ?>><?=$label ?></option>
            <? endforeach; ?>
          <? endif; ?>
        </select>
      </td>
    </tr>
    <? endforeach; ?>
    <tr>
      <th>
        <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('Send') ?>" name="messaging_update_request" />
      </th>
    </tr>
  </table>
</form>
<span class="messaging-settings-change-description">
  <?=$this->transEsc('request_change_description') ?>
</span>
<?endif;?>

<!-- END of: finna - myresearch/change-messaging-settings.phtml -->
