<!-- START of: finna - myresearch/change-messaging-settings-driver.phtml -->
<?
    // Set up page title:
    $this->headTitle($this->translate('request_messaging_settings_change'));

    // Set up myresearch menu
    $this->layout()->finnaMainTabs = $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'profile']);
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';
?>
<h2><?=$this->transEsc('request_messaging_settings_change'); ?></h2>
<?=$this->flashmessages()?>
<? if (empty($profile['email'])): ?>
  <div class="alert alert-danger">
    <?=$this->transEsc('no_email_address')?>
    <?=$this->transEsc('no_email_address_text')?>
  </div>
<? endif; ?>
  <? if (!isset($this->requestCompleted) || !$this->requestCompleted): ?>
    <form name="changeMessagingSettings" method="post" action="<?=$this->url('myresearch-changemessagingsettings') ?>" class="form-horizontal messaging-settings-form profile-form">
      <? foreach ($this->services as $serviceId => $service): ?>
        <div class="form-group">
          <div class="col-sm-12">
            <h3><?=$this->transEsc('messaging_settings_type_' . $service['type'], null, $service['type'])?></h3>
          </div>
        </div>
        <? foreach ($service['settings'] as $settingId => $setting): ?>
          <? if (!empty($setting['readonly'])) { continue; } ?>
          <div class="form-group">
            <? $name = !empty($setting['name']) ? $setting['name'] : $settingId; ?>
            <div class="col-sm-4">
              <label<?='select' == $setting['type'] ? ' class="control-label"' : ''?>><?=$this->transEsc("messaging_settings_setting_$name", null, $name) ?>:</label>
            </div>
            <div class="col-sm-8">
              <? if ('boolean' == $setting['type']): ?>
                <input type="checkbox" name="<?=$this->escapeHtmlAttr($serviceId . '_' . $settingId)?>" value="1"<? if ($setting['active']): ?> checked<? endif; ?><? if (!empty($setting['readonly'])): ?> disabled<? endif; ?>>
              <? elseif ('multiselect' == $setting['type']): ?>
                <? foreach($setting['options'] as $optionId => $option): ?>
                  <? $fullId = $serviceId . '_' . $settingId . '_' . $optionId; ?>
                  <input type="checkbox" id="<?=$this->escapeHtmlAttr($fullId)?>" name="<?=$this->escapeHtmlAttr($fullId)?>" value="1"<? if ($option['active']): ?> checked<? endif; ?><? if (!empty($setting['readonly'])): ?> disabled<? endif; ?>>
                  <? $name = isset($option['name']) ? $option['name'] : $optionId; ?>
                  <label for="<?=$this->escapeHtmlAttr($fullId)?>" class="checkbox-label">
                    <?=$this->transEsc("messaging_settings_option_$name", null, $name) ?>
                  </label>
                  <br>
                <? endforeach; ?>
              <? elseif ('select' == $setting['type']): ?>
                <select name="<?=$this->escapeHtmlAttr($serviceId . '_' . $settingId)?>" class="form-control" <? if (!empty($setting['readonly'])): ?> readonly<? endif; ?>>
                  <? foreach($setting['options'] as $optionId => $option): ?>
                    <? $name = isset($option['name']) ? $option['name'] : $optionId; ?>
                    <option value="<?=$this->escapeHtmlAttr($optionId)?>"<? if ($optionId == $setting['value']): ?> selected<? endif; ?>><?=$this->transEsc("messaging_settings_option_$name", null, $name)?></option>
                  <? endforeach; ?>
                </select>
              <? endif; ?>
            </div>
          </div>
        <? endforeach; ?>
      <? endforeach; ?>
      <div class="form-group">
        <div class="col-sm-offset-4 col-sm-8">
          <input name="messaging_update_request" class="btn btn-primary" type="submit" value="<?=$this->transEsc('Send') ?>" />
        </div>
      </div>
    </form>
  <? endif; ?>
  <? if ($this->approvalRequired): ?>
    <span class="messaging-settings-change-description">
      <?=$this->transEsc('request_change_description_html') ?>
    </span>
  <? endif; ?>
<!-- END of: finna - myresearch/change-messaging-settings-driver.phtml -->
