<!-- START of: finna - myresearch/list-visibility.phtml -->
<div class="list-visibility">
  <?= $this->translate('Public List Visibility'); ?>
  <div>
    <span><input id="visibility-public" type="radio" name="visibility" value="1"<?= $public ? ' checked="checked"' : '' ?>> <label for="visibility-public"><?= $this->translate('Public'); ?></label></span>
    <span class="list-visibility-hidden"><input id="visibility-hidden" type="radio" name="visibility" value="0"<?= !$public ? ' checked="checked"' : '' ?>> <label for="visibility-hidden"><?= $this->translate('Private'); ?></label></span>
  </div>
  <? if ($public): ?>
  <div class="list-url">
    <?= $this->translate('Public List URL'); ?>
    <div><a href="<?= $this->listUrl; ?>"><?= $this->listUrl; ?></a></div>
   </div>
   <? endif; ?>
</div>
<!-- END of: finna - myresearch/list-visibility.phtml -->
