<!-- START of: finna - myresearch/menu.phtml -->
<?
    $this->layout()->finnaMainHeader = '<h1><i class="fa fa-user"></i> ' . $this->transEsc('Your Account') . '</h1>';
    if (!$this->translationEmpty('tooltip_myaccount_html')) {
        $this->layout()->finnaMainHeader .= '<span class="tooltip-myaccount" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="' . $this->transesc("tooltip_myaccount_html") . '"><i class="fa fa-info-big"></i></span>';
    }
    $capabilityParams = [];
    $user = $this->auth()->isLoggedIn();
    $patron = $user ? $this->auth()->getILSPatron() : false;
    $capabilityParams = $patron ? ['patron' => $patron] : [];
    if ($user) {
        $this->layout()->finnaMainHeader .= '<a class="btn btn-primary pull-right" href="' . $this->url('myresearch-logout') . '" title="' . $this->transEsc('Log Out') . '"><i class="fa fa-sign-out"></i> ' . $this->transEsc('Log Out') . '</a>';
        $this->layout()->finnaMainHeader .= $this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card']);
    }
    $this->layout()->finnaMainHeader;

    $showLibraryTabs = $this->ils()->loginAvailable();
?>
<? ob_start(); ?>
<? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
  <? if ($this->ils()->checkCapability('getMyProfile')): ?>
    <li class="menu-profile">
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
        <?=$this->transEsc('Profile')?>
      </a>
    </li>
  <? endif; ?>
  <? if ($showLibraryTabs): ?>
    <li class="menu-loans">
      <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
        <?=$this->transEsc('Checked Out Items')?>
      </a>
    </li>
    <? if ($this->ils()->checkCapability('getMyTransactionHistory', $capabilityParams)): ?>
      <li class="menu-historic-loans">
        <a href="<?=$this->url('myresearch-historicloans')?>" class="list-group-item<?=$this->active == 'historicloans' ? ' active' : ''?>">
          <?=$this->transEsc('Loan History')?>
        </a
      ></li>
    <? endif; ?>
    <li class="menu-holds">
      <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
        <?=$this->transEsc('Holds and Recalls')?>
      </a>
    </li>
    <? if ($this->ils()->checkCapability('getMyStorageRetrievalRequests', $capabilityParams)): ?>
      <li class="menu-storage-retrieval-requests">
        <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
          <?=$this->transEsc('Storage Retrieval Requests')?>
        </a>
      </li>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyILLRequests', $capabilityParams)): ?>
      <li class="menu-ill-requests">
        <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
          <?=$this->transEsc('Interlibrary Loan Requests')?>
        </a>
      </li>
    <? endif; ?>
    <li class="menu-fines">
      <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
        <?=$this->transEsc('Fines')?>
      </a>
    </li>
    <? if ($user && $user->libraryCardsEnabled()): ?>
      <li class="menu-library-cards">
        <a href="<?=$this->url('librarycards-home')?>" class="list-group-item<?=$this->active == 'librarycards' ? ' active' : ''?>">
          <?=$this->transEsc('Library Cards')?>
        </a>
      </li>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled'): ?>
  <li class="menu-favorites">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' || substr($this->active, 0, 4) == 'list' ? ' active' : ''?>">
      <?=$this->transEsc('Favorites')?>
    </a>
  </li>
<? endif; ?>
<li class="menu-history">
  <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
    <?=$this->transEsc('history_saved_searches')?>
  </a>
</li>
<? $menuEntries = ob_get_clean(); ?>

  <div>
    <div class="dropdown visible-xs useraccount-nav-mobile">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
      <?
        switch ($this->active) {
        case 'profile': echo $this->transEsc('Profile'); break;
        case 'checkedout': echo $this->transEsc('Checked Out Items'); break;
        case 'historicloans': echo $this->transEsc('Loan History'); break;
        case 'holds': echo $this->transEsc('Holds and Recalls'); break;
        case 'storageRetrievalRequests': echo $this->transEsc('Storage Retrieval Requests'); break;
        case 'ILLRequests': echo $this->transEsc('Interlibrary Loan Requests'); break;
        case 'fines': echo $this->transEsc('Fines'); break;
        case 'librarycards': echo $this->transEsc('Library Cards'); break;
        case 'favorites': echo $this->transEsc('Favorites'); break;
        case 'history': echo $this->transEsc('history_saved_searches'); break;
        default:
            if (substr($this->active, 0, 4) == 'list') {
                echo $this->transEsc('Favorites');
                break;
            }
            echo $this->transEsc('Your Account');
            break;
        }
      ?>
      <i class="fa fa-arrow-down"></i></a>
      <ul class="dropdown-menu">
        <?=$menuEntries?>
      </ul>
    </div>
  </div>
  <ul class="list-group useraccount-nav hidden-xs">
    <?=$menuEntries?>
  </ul>

<!-- END of: finna - myresearch/menu.phtml -->
