<?
  $this->layout()->finnaMainHeader = '<div class="col-xs-12"><h1><i class="fa fa-user"></i> ' . $this->transEsc('Your Account') . '</h1></div>';
?>

<div class="col-xs-12">
  <div class="row">
    <div class="dropdown visible-xs myresearch-nav-mobile">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <i class="fa fa-arrow-down"></i></a>
      <ul class="dropdown-menu">
        <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
          <? if ($this->ils()->checkCapability('getMyProfile')): ?>
          <li><a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
          <?=$this->transEsc('Profile')?>
          </a></li>
           <? endif; ?>
           <? if ($this->ils()->checkCapability('getMyTransactions')): ?>
           <li><a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
           <?=$this->transEsc('Checked Out Items')?>
           </a></li>
           <? endif; ?>
           <? if ($this->ils()->checkCapability('getMyHolds')): ?>
           <li><a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
           <?=$this->transEsc('Holds and Recalls')?>
           </a></li>
           <? endif; ?>
           <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
           <li><a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
           <?=$this->transEsc('Storage Retrieval Requests')?>
           </a></li>
           <? endif; ?>
           <? if ($this->ils()->checkFunction('ILLRequests')): ?>
           <li><a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
           <?=$this->transEsc('Interlibrary Loan Requests')?>
           </a></li>
           <? endif; ?>
           <? if ($this->ils()->checkCapability('getMyFines')): ?>
           <li><a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
           <?=$this->transEsc('Fines')?>
           </a></li>
           <? endif; ?>
        <? endif; ?>
        <? if ($this->userlist()->getMode() !== 'disabled'): ?>
           <li><a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
           <?=$this->transEsc('Favorites')?>
           </a></li>
        <? endif; ?>
           <li><a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
           <?=$this->transEsc('history_saved_searches')?>
           </a></li>
      </ul>
    </div>
  </div>
  <ul class="list-group myresearch-nav hidden-xs">
    <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
      <? if ($this->ils()->checkCapability('getMyProfile')): ?>
      <li><a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
      <?=$this->transEsc('Profile')?>
      </a></li>
      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyTransactions')): ?>
      <li><a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
      <?=$this->transEsc('Checked Out Items')?>
      </a></li>
      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyHolds')): ?>
      <li><a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
      <?=$this->transEsc('Holds and Recalls')?>
      </a></li>
      <? endif; ?>
      <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
      <li><a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
      <?=$this->transEsc('Storage Retrieval Requests')?>
      </a></li>
      <? endif; ?>
      <? if ($this->ils()->checkFunction('ILLRequests')): ?>
      <li><a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <?=$this->transEsc('Interlibrary Loan Requests')?>
      </a></li>
      <? endif; ?>
      <? if ($this->ils()->checkCapability('getMyFines')): ?>
      <li><a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
      <?=$this->transEsc('Fines')?>
      </a></li>
      <? endif; ?>
    <? endif; ?>
    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <li><a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <?=$this->transEsc('Favorites')?>
      </a></li>
    <? endif; ?>
      <li><a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
      <?=$this->transEsc('history_saved_searches')?>
      </a></li>
  </ul>
</div>



