  <h4><?=$this->transEsc('Your Lists')?></h4>
  <ul class="list-group mylist-nav">
    <li>
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=!$activeId ? ' active' : ''?>">
      <?=$this->transEsc('All')?>
      <? $count = 0 ;?>
      <? foreach ($lists as $list): ?>
        <? $count += $list->cnt;?>
      <? endforeach; ?>
      <span> (<?=$count; ?>)</span>
    </a>
    <? foreach ($lists as $list): ?>
    <? $active = ($list->id === $activeId); ?>
    <li>
        <a href="<?= $active ? '#' : $this->url('userList', array('id' => $list['id']))?>" class="list-group-item<?=$list && $active ? ' active' : ''?>">
          <? if ($list['public']): ?>
          <i class="fa fa-user"></i>
          <? endif; ?>
          <?=$this->escapeHtml($list['title'])?>
          <span> (<?=$list->cnt?>)</span>
          <? if ($active): ?>
          <span class="pull-right"><i data-src="<?=$this->url('myresearch-deletelist') ?>?listID=<?=urlencode($list->id)?>" class="fa fa-times remove"></i></span>
          <? endif; ?>
        </a>
        <? if ($active): ?>
        <? $url = $this->serverUrl() . $this->url('home') . 'List/' . $list['id']; ?>
        <?= $this->partial('myresearch/list-visibility.phtml', array('listUrl' => $url, 'public' => $list['public'])); ?>
        <? endif; ?>
    </li>
    <? endforeach; ?>
    <li>
    <div class="list-group-item add-new-list">
      <span class="name"><?=$this->transEsc('Create a List') ?></span>
      <span class="pull-right"><i class="fa fa-plus-small icon"></i></span>
    </div>
    </li>
  </ul>
