<!-- START of: finna - myresearch/mylist-navi.phtml -->
<?
  $numOfResources = $user->getNumOfResources();
  $limitList = $this->results->getParams()->getLimitList();
  $currentLimit = 20; // default limit for favorites
  foreach ($limitList as $limitVal => $limitData) {
    if ($limitData['selected']) {
      $currentLimit = $limitVal;
      break;
    }
  }
?>

  <h4><?=$this->transEsc('Your Lists')?></h4>
  <ul class="list-group mylist-nav">
    <li>
      <a href="<?=$this->url('myresearch-favorites')?>?limit=<?=$currentLimit;?>" class="list-group-item<?=!$activeId ? ' active' : ''?>">
        <?=$this->transEsc('All Favourites')?>
        <span> (<?=$numOfResources; ?>)</span>
      </a>
    </li>
    <? foreach ($lists as $list): ?>
    <? $active = ($list->id === $activeId); ?>
    <li>
      <a href="<?= $active ? '#' : $this->url('userList', array('id' => $list['id']))?>?limit=<?=$currentLimit;?>" class="list-group-item<?=$list && $active ? ' active' : ''?>">
        <? if ($list['public']): ?>
        <i class="fa fa-public public-favorite-list pull-left"></i>
        <? endif; ?>
        <div class="favorite-list-name">
          <?=$this->escapeHtml($list['title'])?>
          <span> (<?=$list->cnt?>)</span>
        </div>
        <? if ($active): ?>
        <span class="pull-right remove-favorite-list"><i class="fa fa-button fa-times remove"></i></span>
        <? endif; ?>
      </a>
      <? if ($active): ?>
      <? $url = $this->serverUrl() . $this->url('home') . 'List/' . $list['id']; ?>
      <?= $this->partial('myresearch/list-visibility.phtml', array('listUrl' => $url, 'public' => $list['public'])); ?>
      <? endif; ?>
    </li>
    <? endforeach; ?>
    <li>
      <div class="list-group-item add-new-list">
        <div class="name"><?=$this->transEsc('Create a List') ?></div>
        <span class="pull-right"><i class="fa fa-plus-small icon"></i></span>
      </div>
    </li>
  </ul>
<!-- END of: finna - myresearch/mylist-navi.phtml -->
