<?
    // Set up page title:
    $this->headTitle($this->translate('My Profile'));
    $this->headScript()->appendFile("finna-myprofile.js");
    // Set up myresearch menu
    $this->layout()->finnaMainTabs = $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'profile'));
    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Profile') . '</li>';

    // Only display home library form if we have multiple pickup locations:
    $showHomeLibForm = (isset($this->pickup) && count($this->pickup) > 1);

    // Template for use by the renderArray helper:
    $arrTitlePart = '<div class="col-xs-4 col-sm-4 profile-title">%%LABEL%%:</div>';
    $arrTemplate = $arrTitlePart . '<div class="col-xs-8 col-sm-8 profile-text-value"> %%VALUE%%</div>';
    $arrTelTemplate = $arrTitlePart . '<div class="col-xs-8 col-sm-8"><input class="form-control" type="tel" name="profile_tel" value="%%VALUE%%"/></div>';
    $arrMailTemplate = $arrTitlePart . '<div class="col-xs-8 col-sm-8"><input class="form-control" type="email" name="profile_email" value="%%VALUE%%"/></div>';
    $arrNoticeTemplate = '<div class="col-xs-4 col-sm-4 profile-title profile-long">%%LABEL%%:</div><div class="col-xs-8 col-sm-4 profile-text-value profile-long"> %%VALUE%%</div><div class="clearfix visible-xs profile-xs"></div><div class="col-sm-4 profile-long">%%NOTICE%%</div><div class="clearfix visible-xs  profile-xs"><br/></div>';
    $arrZipTemplate = '<div class="col-xs-4 col-sm-4 profile-title library-profile-after-long">%%LABEL%%:</div><div class="col-xs-8 col-sm-8 profile-text-value library-profile-after-long"> %%VALUE%%</div>';

    $user = $this->auth()->isLoggedIn();
    $cards = $user->getLibraryCards();
    $profileInstructions = trim($this->transEsc('profile_instructions'));
    // Remove zero-width non-joiner character, so blank line is not displayed.
    $profileInstructions = str_replace("\xE2\x80\x8C", "", $profileInstructions);

    // Todo: get actual value for Axiell web services functions.
    $axiellWebServices = false;
?>
<div class="row">
  <div class="col-md-10 col-lg-9">
    <?=$this->flashmessages();?>
    <? if (!empty($profileInstructions)): ?>
      <div class="no-content-message"><?=$profileInstructions ?></div>
    <? endif; ?>
    <?= $this->partial('myresearch/profile-my-information.phtml', array('user' => $user, 'cards' => $cards)); ?>
    <? if (isset($this->profile)): ?>
    <div class="myresearch-profile-header"><?=$this->transEsc('Library Card Settings');?> <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $user))?></div>
    <div class="col-xs-12 myresearch-profile-list library-profile">
      <? if ($showHomeLibForm): ?>
        <form id="profile_form" class="inline" method="post">
          <div class="col-xs-4 col-sm-4 profile-title"><?=$this->transEsc('Preferred Library')?>:</div>
          <div class="col-xs-8 col-sm-8">
              <?
                $selected = (isset($this->profile['home_library']) && $this->profile['home_library'] != "")
                  ? $this->profile['home_library'] : $this->defaultPickupLocation
              ?>
              <select id="home_library" name="home_library" class="form-control">
                <? foreach ($this->pickup as $lib): ?>
                  <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID'])?' selected="selected"':''?>><?=$this->escapeHtml($lib['locationDisplay'])?></option>
                <? endforeach; ?>
              </select>
          </div>
          <div class="col-xs-12 col-sm-12">
            <input class="btn btn-primary" type="submit" value="<?=$this->transEsc('Save')?>" name="save_home_library" />
          </div>
        </form>
      <? endif; ?>

      <? if (isset($profile['messagingServices']) && !empty($profile['messagingServices'])): ?>
        <?= $this->partial('myresearch/profile-messaging.phtml', array('profile' => $profile)); ?>
      <? endif; ?>
      <? if ($this->changePassword): ?>
        <?= $this->partial('myresearch/profile-change-password.phtml', array('user' => $user)); ?>
      <? endif; ?>

      <form id="profile_libary_form" class="inline" method="post">
        <div class="col-xs-12 col-sm-12">
          <span class="myresearch-profile-middle-header"><?= $this->transEsc('Personal details maintained by the library') ?></span>
        </div>
        <?
            echo $this->renderArray(
              $arrTemplate, $this->profile,
              array(
                $this->transEsc('First Name') => 'firstname',
                $this->transEsc('Last Name') => 'lastname'
              )
            );
            if ($axiellWebServices) {
              echo str_replace(
                ['%%LABEL%%', '%%VALUE%%', '%%NOTICE%%'],
                [
                  $this->transEsc('Address'),
                  $this->profile['address1'],
                  '<i class="fa fa-info-big"></i> ' . $this->transEsc('request_address_change_title') . '<a class="modal-link controller:MyResearch profile-library-info-address-update" href="'. $this->url() . '">' . $this->transEsc('request_address_change') . '</a>'
                ],
                $arrNoticeTemplate
              );
            } else {
              echo $this->renderArray(
                $arrTemplate, $this->profile,
                array(
                  $this->transEsc('Address') . ' 1' => 'address1',
                  $this->transEsc('Address') . ' 2' => 'address2',
                )
              );
            }
            echo $this->renderArray(
              $arrZipTemplate, $this->profile,
              array(
                $this->transEsc('Zip') => 'zip',
              )
            );
            if (!$axiellWebServices) {
              $arrTelTemplate = $arrTemplate;
            }
            echo $this->renderArray(
              $arrTelTemplate, $this->profile,
              array(
                $this->transEsc('Phone Number') => 'phone',
              )
            );
            if (!$axiellWebServices) {
                $arrMailTemplate = $arrTemplate;
            }
            echo $this->renderArray(
              $arrMailTemplate, $this->profile,
              array(
                $this->transEsc('Email') => 'email',
              )
            );
            echo $this->renderArray(
              $arrTemplate, $this->profile,
              array(
                $this->transEsc('Group') => 'group'
              )
            );
          ?>
          <? if ($axiellWebServices): ?>
          <div class="col-xs-12 col-sm-12">
            <input id="save-libary-profile" name="save_libary_profile" type="submit" value="<?=$this->transEsc("save_my_profile") ?>" class="btn btn-primary" />
          </div>
          <div class="col-xs-12 col-sm-12">
              <i class="fa fa-pen"></i> <a class="modal-link controller:MyResearch profile-library-info-address-update" href="<?=$this->url() ?>"><?=$this->transEsc('request_address_change') ?></a>
          </div>
          <? endif; ?>
         </form>
    </div>
    <? endif; ?>
  </div>
</div>
<div class="row">
  <div class="col-md-10 col-lg-9">
    <div id="delete-account" class="text-right">
      <button class="btn btn-primary modal-link controller:MyResearch"><i class="fa fa-times"></i> <?=$this->transEsc('delete_account_title') ?></button>
    </div>
  </div>
</div>
