<form method="post" class="inline" id="password-form">
    <tr>
      <th colspan="3"><span class="myresearch-profile-middle-header"><?= $this->transEsc('change_password_title') ?></span></th>
    <tr>
      <th><?= $this->transEsc('change_password_old_password') ?>:</th>
      <td><input type="password" id="old-password" name="old_password" value="" class="form-control"></td>
      <td><i class="fa fa-info-big"></i> <?=$this->transEsc('change_password_instructions') ?></td>
    </tr>
    <tr>
      <th><?= $this->transEsc('change_password_new_password') ?>:</th>
      <td><input type="password" id="new-password" name="new_password" value="" required="required" class="form-control"></td>
      <td></td>
    </tr>
    <tr>
      <th><?= $this->transEsc('change_password_new_password_again') ?>:</th>
      <td><input type="password" id="new-password-2" name="new_password_2" value="" required="required" class="form-control"></td>
      <td></td>
    </tr>
    <tr>
        <th><input class="btn btn-primary" type="submit" value="<?= $this->transEsc('change_password_submit') ?>" name="profile_password_change" /></th>
      <td colspan="2"></td>
    </tr>
</form>
