<!-- START of: finna - myresearch/purgehistoricloans.phtml -->
<?
    // Set up page title:
    $this->headTitle($this->translate('loan_history_purge'));

    // Set up myresearch menu
    $this->layout()->finnaMainTabs = $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'purgehistoricloans']);

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('loan_history_purge') . '</li>';

    $user = $this->auth()->isLoggedIn();
?>
<h2><?=$this->transEsc('loan_history_purge')?></h2>

<div>
  <div class="my-research-content">
    <?=$this->flashmessages()?>
    <form id="purgecheckouthistory" action="<?=$this->url('myresearch-purgehistoricloans')?>" method="post" role="form">
      <p><?=$this->translate('loan_history_purge_prompt_html')?></p>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->csrf)?>" name="csrf"/>
      <div class="form-group">
        <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('confirm_dialog_yes')?>" data-lightbox-ignore/>
        <input class="btn btn-primary" name="cancel" type="submit" value="<?=$this->transEsc('confirm_dialog_no')?>" data-lightbox-ignore/>
      </div>
    </form>
  </div>
</div>
<!-- END of: finna - myresearch/purgehistoricloans.phtml -->
