<?
    $this->layout()->searchbox = false;
    $language = $this->layout()->userLang;
    $titles = [
       'fi' => 'Asiakastietojen käsittely',
       'sv' => 'Behandling av kunduppgifter',
       'en-gb' => 'Privacy policy'
    ];
    if (!isset($titles[$language])) {
       $language = 'en-gb';
    }
    $title = $titles[$language];
    $this->headTitle($title);
?>
<!-- START of: finna - myresearch/terms.phtml -->
<h2 class="lightbox-header"><?=$title?></h2>
<div class="terms-of-service">
  <form name="termsForm" method="post" data-toggle="validator" action="<?=$this->escapeHtmlAttr($this->url('myresearch-userlogin')) ?>">
    <?=$this->partial("terms_$language.phtml") ?>
  </form>
</div>
<?
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$js = <<<JS
  if ($.isReady) {
    $('.terms-of-service form').validator();
  } else {
    $(document).ready(function(){
      $('.terms-of-service form').validator();
    });
  }
JS;

echo $this->inlineScript()->appendScript($js);
?>
<!-- END of: finna - myresearch/terms.phtml -->
