<!-- finc: myresearch - checkedout -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * does not use 'Your Account' offcanvas-toggler here #22293
 * uses offcanvas-toggler-myresearch #22293
 * uses h1 here, #13547
 * adds aria-label to nav
 * uses <p> and aria for alerts
 * adds aria-label and -describedby #18019, #19676
 * adds aria-hidden
 * adds h2-element for title author #24265; forward compatibility with VuFind10 PR2958
 * adds span for authors #24265
 * adds empty lang (='undefined') tag
 * uses section for sidebar #23430, adds aria-label
configured in: {}
 */
?>
<?php
  // Set up page title:
  $this->headTitle($this->translate('Checked Out Items'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Checked Out Items') . '</li>';

  // Check if "Renew All" button can be displayed:
  $renewAll = !$this->ilsPaging || !$paginator;
?>

<?php /* finc: DOES NOT use 'Your Account' offcanvas-toggler here #22293
<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>
*/ ?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?php /* finc: uses offcanvas-toggler-myresearch #22293 */ ?>
  <?=$this->render('RecordDriver/DefaultRecord/offcanvas-toggler-myresearch'); ?>

  <?php /* finc: uses h1 here, #13547 */ ?>
  <h1><?=$this->transEsc('Your Checked Out Items')?></h1>
  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (!empty($this->transactions)): ?>
    <?php /* finc: adds aria-label to nav */ ?>
    <nav class="search-header hidden-print" aria-label="<?=$this->transEscAttr('aria_search_header')?>">
      <?php if ($paginator): ?>
        <div class="search-stats">
          <?php
            $abs = $paginator->getAbsoluteItemNumber($paginator->getItemCountPerPage());
            $end = min($abs, $paginator->getTotalItemCount());
            $transParams = [
              '%%start%%' => $this->localizedNumber($paginator->getAbsoluteItemNumber(1)),
              '%%end%%' => $this->localizedNumber($end),
              '%%total%%' => $this->localizedNumber($paginator->getTotalItemCount())
            ];
          ?>
          <?=$this->translate('showing_items_of_html', $transParams); ?>
        </div>
      <?php endif; ?>
      <?php if ($this->sortList): ?>
        <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
      <?php endif; ?>
    </nav>
    <?php if ($this->renewForm): ?>
    <form name="renewals" method="post" id="renewals" data-clear-account-cache="checkedOut" data-disable-on-submit>
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
      <div class="toolbar">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="selectAll" class="checkbox-select-all">
            <?=$this->transEsc('select_page')?>
          </label>
          <input type="submit" class="btn btn-default" id="renewSelected" name="renewSelected" value="<?=$this->transEscAttr("renew_selected")?>">
          <?php if ($renewAll): ?>
            <input type="submit" class="btn btn-default" id="renewAll" name="renewAll" value="<?=$this->transEscAttr('renew_all')?>">
          <?php endif; ?>
        </div>
      </div>
    <?php endif; ?>


    <?php foreach ($hiddenTransactions as $ilsDetails): ?>
      <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
        <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
        <?php $prefix = $ilsDetails['title'] ?? $ilsDetails['item_id']; ?>
        <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
          <?php /* finc: uses <p> and aria for alerts */ ?>
          <p class="alert alert-success" aria-live="polite"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_success')?></p>
        <?php else: ?>
          <p class="alert alert-danger" aria-live="polite"><?=$this->escapeHtml($prefix . ': ') . $this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></p>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
        <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
        <input class="pull-left flip" type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>">
      <?php endif; ?>
    <?php endforeach; ?>

    <ul class="record-list">
      <?php $i = 0; foreach ($this->transactions as $resource): ?>
        <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <?php /* finc: adds aria-label and -describedby #18019, #19676 */ ?>
        <?php $describedById = $this->record($resource)->getTitleDescribedById(); ?>
        <li id="record<?=$this->escapeHtmlAttr($resource->getUniqueId())?>" class="result">
          <?php if ($this->renewForm): ?>
            <div class="checkbox">
              <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_details'])): ?>
                <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $ilsDetails['renew_details']); ?>
                <label>
                  <?php /* finc: adds aria-label and -describedby #18019, #19676 */ ?>
                  <input class="checkbox-select-item" type="checkbox" name="renewSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>" id="checkbox_<?=$safeId?>" aria-describedby="<?=$describedById?>" aria-label="<?=$this->transEscAttr('select_item_checked_out_renew')?>">
                </label>
                <input type="hidden" name="selectAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>">
                <input type="hidden" name="renewAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['renew_details'])?>">
              <?php else: ?>
                <label> </label>
              <?php endif; ?>
            </div>
          <?php endif; ?>

          <?php
            $coverDetails = $this->record($resource)->getCoverDetails('checkedout', 'small', $this->recordLinker()->getUrl($resource));
            $cover = $coverDetails['html'];
            $thumbnail = false;
            $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
            if ($cover):
              ob_start(); ?>
              <?php /* finc: adds aria-hidden */ ?>
              <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>" aria-hidden="true">
                <?=$cover ?>
              </div>
              <?php $thumbnail = ob_get_contents(); ?>
            <?php ob_end_clean(); ?>
          <?php endif; ?>
          <div class="media">
            <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
            <div class="media-body">
              <?php /* finc: adds h2-element for title author #24265
                forward compatibility with VuFind10 PR2958 */ ?>
              <h2>
                <?php
                  // If this is a non-missing Solr record, we should display a link:
                  if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    // finc: adds $describedById #18019
                    // finc: adds empty lang (='undefined') tag
                    echo '<a id="' . $describedById . '" href="' . $this->escapeHtmlAttr($this->recordLinker()->getUrl($resource)) .
                      '" class="title" lang="">' . $title . '</a>';
                  } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])) {
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    echo '<span class="title" id="' . $describedById . '" lang="">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
                  } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                  }
                ?>
                <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
                  <?php /* finc: adds span for authors #24265 */ ?>
                  <span class="authors">
                    <?=$this->transEsc('by')?>:
                    <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?><br>
                  </span>
                <?php endif; ?>
              </h2>

              <?php if (count($resource->getFormats()) > 0): ?>
                <?=$this->record($resource)->getFormatList() ?>
                <br>
              <?php endif; ?>
              <?php if (!empty($ilsDetails['volume'])): ?>
                <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['publication_year'])): ?>
                <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
                <br>
              <?php endif; ?>
              <?php if ($this->displayItemBarcode && !empty($ilsDetails['barcode'])): ?>
                <strong><?=$this->transEsc('Barcode')?>:</strong> <?=$this->escapeHtml($ilsDetails['barcode'])?>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['institution_name']) && (empty($ilsDetails['borrowingLocation']) || $ilsDetails['institution_name'] != $ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEscWithPrefix('location_', $ilsDetails['institution_name'])?></strong>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['borrowingLocation'])): ?>
                <strong><?=$this->transEsc('Borrowing Location')?>:</strong> <?=$this->transEscWithPrefix('location_', $ilsDetails['borrowingLocation'])?>
                <br>
              <?php endif; ?>

              <?php if (isset($ilsDetails['renew'])): ?>
                <strong><?=$this->transEsc('Renewed')?>:</strong> <?=$this->transEsc($ilsDetails['renew'])?>
                <?php if (isset($ilsDetails['renewLimit'])): ?>
                  / <?=$this->transEsc($ilsDetails['renewLimit'])?>
                <?php endif; ?>
                <br>
              <?php endif; ?>

              <?php $showStatus = true; ?>

              <?php if (isset($this->renewResult[$ilsDetails['item_id']])): ?>
                <?php $renewDetails = $this->renewResult[$ilsDetails['item_id']]; ?>
                <?php if (isset($renewDetails['success']) && $renewDetails['success']): ?>
                  <?php $showStatus = false; ?>
                  <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($renewDetails['new_date'])?> <?php if (isset($renewDetails['new_time'])): ?><?=$this->escapeHtml($renewDetails['new_time'])?><?php endif; ?></strong>
                  <?php /* finc: uses <p> and aria for alerts */ ?>
                  <p class="alert alert-success" aria-live="polite"><?=$this->transEsc('renew_success')?></p>
                <?php else: ?>
                  <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
                  <p class="alert alert-danger" aria-live="polite"><?=$this->transEsc('renew_fail')?><?php if (isset($renewDetails['sysMessage'])): ?>: <?=$this->escapeHtml($renewDetails['sysMessage'])?><?php endif; ?></p>
                <?php endif; ?>
              <?php else: ?>
                <strong><?=$this->transEsc('Due Date')?>: <?=$this->escapeHtml($ilsDetails['duedate'])?><?php if (isset($ilsDetails['dueTime'])): ?> <?=$this->escapeHtml($ilsDetails['dueTime'])?><?php endif; ?></strong>
                <?php if ($showStatus): ?>
                  <?php if (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "overdue"): ?>
                    <p class="alert alert-danger" aria-live="polite"><?=$this->transEsc("renew_item_overdue")?></p>
                  <?php elseif (isset($ilsDetails['dueStatus']) && $ilsDetails['dueStatus'] == "due"): ?>
                    <p class="alert alert-info" aria-live="polite"><?=$this->transEsc("renew_item_due")?></p>
                  <?php endif; ?>
                <?php endif; ?>
              <?php endif; ?>

              <?php if ($showStatus && isset($ilsDetails['message']) && !empty($ilsDetails['message'])): ?>
                <p class="alert alert-info" aria-live="polite"><?=$this->transEsc($ilsDetails['message'])?></p>
              <?php endif; ?>
              <?php if (isset($ilsDetails['renewable']) && $ilsDetails['renewable'] && isset($ilsDetails['renew_link'])): ?>
                <a href="<?=$this->escapeHtmlAttr($ilsDetails['renew_link'])?>"><?=$this->transEsc('renew_item')?></a>
              <?php endif; ?>
            </div>
            <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
          </div>
          <?php /* finc: adds aria-hidden */ ?>
          <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>':''?>
        </li>
      <?php endforeach; ?>
    </ul>
    <?php if ($this->renewForm): ?></form><?php endif; ?>
    <?=$paginator ? $this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', compact('params')) : ''?>
  <?php else: ?>
    <?=$this->transEsc('You do not have any items checked out')?>.
  <?php endif; ?>
</div>

<?php /* finc: uses section for sidebar #23430, adds aria-label */ ?>
<section class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" aria-label="<?=$this->transEscAttr('MyAccountSidebar') ?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'checkedout'])?>
</section>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'checkedOut', 'accountStatus' => $this->accountStatus]); ?>
<!-- finc: myresearch - checkedout - END -->
