<!-- finc: myresearch - delete -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * uses h1 and h2 for headings hierarchy #18535
 * uses <p> #17950, adds role #18790, adds  aria-live #21622
 * FIXME: remove file in finc, if the changes are available in VuFind; create PR if not yet done
configured in: {}
 */
?>

<?php /* finc: uses h1 for headings hierarchy #18535 */ ?>
<h1><?=$this->transEsc('delete_selected_favorites')?></h1>
 <form action="<?=$this->url('myresearch-delete')?>" method="post" name="bulkDelete" data-lightbox-onclose="VuFind.refreshPage">
  <div id="popupMessages"><?=$this->flashmessages()?></div>
  <div id="popupDetails">
    <?php if (!$this->list): ?>
      <?php /* finc: uses <p> #17950, adds role #18790, adds aria-live #21622 */ ?>
      <p class="alert alert-info" role="alert" aria-live="assertive"><?=$this->transEsc("fav_delete_warn") ?></p>
    <?php else: ?>
      <?php /* finc: uses h2 for headings hierarchy #18535 */ ?>
      <h2><?=$this->transEsc("List") ?>: <?=$this->escapeHtml($this->list->title) ?></h2>
    <?php endif; ?>

    <ul class="record-list">
      <?php foreach ($this->records as $favorite): ?>
        <li>
          <strong><?=$this->transEsc('Title') ?>:</strong>
          <?=$this->escapeHtml($favorite->getBreadcrumb())?>
        </li>
      <?php endforeach; ?>
    </ul>
    <br>
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Delete')?>">
    <?php foreach ($this->deleteIDS as $deleteID): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($deleteID)?>">
    <?php endforeach; ?>
      <input type="hidden" name="listID" value="<?=$this->list?$this->escapeHtmlAttr($this->list->id):''?>">
  </div>
</form>
<!-- finc: myresearch - delete - END -->
