<!-- finc: myresearch - illrequests -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * does not use 'Your Account' offcanvas-toggler here #22293
 * uses offcanvas-toggler-myresearch #22293
 * uses h1 instead of h2
 * adds aria-label and -describedby #18019, #19676
 * adds h2-element for title and author #24265; forward compatibility with VuFind10 PR2958
 * adds span for authors #24265
 * adds empty lang (='undefined') tag #18535
 * removes break
 * uses <p> and role for alerts
 * adds aria-hidden
 * uses section for sidebar #23430, adds aria-label
configured in: {}
 */
?>
<?php
    // Set up page title:
    $this->headTitle($this->translate('Interlibrary Loan Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Interlibrary Loan Requests') . '</li>';

    $this->headScript()->appendFile('requests.js');
?>

<?php /* finc: DOES NOT use 'Your Account' offcanvas-toggler here #22293
<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>
*/ ?>

<div class="<?=$this->layoutClass('mainbody')?>">

  <?php /* finc: uses offcanvas-toggler-myresearch #22293 */ ?>
  <?=$this->render('RecordDriver/DefaultRecord/offcanvas-toggler-myresearch'); ?>

  <?php /* finc: uses h1 instead of h2 */ ?>
  <h1><?=$this->transEsc('Interlibrary Loan Requests') ?></h1>

  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <?php if (!empty($this->recordList)): ?>
    <?php if ($this->cancelForm): ?>
      <form name="updateForm" class="inline" method="post" id="cancelILLRequest" data-clear-account-cache="illRequests">
        <input type="hidden" id="submitType" name="cancelSelected" value="1">
        <input type="hidden" id="cancelConfirm" name="confirm" value="0">
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEscAttr("ill_request_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_ill_request_cancel_selected_text") ?></a></li>
            <li><a href="#" id="confirm_cancel_selected_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEscAttr("ill_request_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown">
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_ill_request_cancel_all_text") ?></a></li>
            <li><a href="#" id="confirm_cancel_all_yes"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" class="confirm_cancel_no"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
    <?php endif; ?>

    <ul class="record-list">
      <?php $iteration = 0; ?>
      <?php foreach ($this->recordList as $resource): ?>
        <?php $iteration++; ?>
        <?php $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
        <?php /* finc: adds $describedById */ ?>
        <?php $describedById = $this->record($resource)->getTitleDescribedById(); ?>
        <li id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result">
          <?php if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
            <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
            <div class="checkbox">
              <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>">
              <label>
                <?php /* finc: adds aria-label and -describedby #18019, #19676 */ ?>
                <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" aria-describedby="<?=$describedById?>" aria-label="<?=$this->transEscAttr('select_item_ill_request_cancel')?>">
              </label>
            </div>
          <?php endif; ?>

          <?php
            $coverDetails = $this->record($resource)->getCoverDetails('illrequests', 'small', $this->recordLinker()->getUrl($resource));
            $cover = $coverDetails['html'];
            $thumbnail = false;
            $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
            if ($cover):
              ob_start(); ?>
              <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
                <?=$cover ?>
              </div>
              <?php $thumbnail = ob_get_contents(); ?>
            <?php ob_end_clean(); ?>
          <?php endif; ?>
          <div class="media">
            <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
            <div class="media-body">
              <?php /* finc: adds h2-element for title and author #24265
                forward compatibility with VuFind10 PR2958 */ ?>
              <h2>
                <?php
                  // If this is a non-missing Solr record, we should display a link:
                  if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    // finc: adds $describedById
                    echo '<a id="' . $describedById . '" href="' . $this->escapeHtmlAttr($this->recordLinker()->getUrl($resource))
                      // finc: adds empty lang (='undefined') tag #18535
                      . '" class="title" lang="">' . $title . '</a>';
                  } elseif (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    // finc: adds $describedById
                    // finc: adds empty lang (='undefined') tag #18535
                    echo '<span class="title" id="' . $describedById . '" lang="">' . $this->escapeHtml($ilsDetails['title']) . '</span>';
                  } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                  }
                ?><?php /* finc: removes break */ ?>
                <?php $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
                  <?php /* finc: adds span for authors #24265 */ ?>
                  <span class="authors">
                    <?=$this->transEsc('by')?>:
                    <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><?php if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?><br>
                  </span>
                <?php endif; ?>
              </h2>

              <?php if (count($resource->getFormats()) > 0): ?>
                <?=$this->record($resource)->getFormatList() ?>
                <br>
              <?php endif; ?>
              <?php if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
                <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
                <br>
              <?php endif; ?>

              <?php if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
                <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
                <br>
              <?php endif; ?>

              <?php /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
                value to display... */ ?>
              <?php $pickupDisplay = ''; ?>
              <?php $pickupTranslate = false; ?>
              <?php if (isset($ilsDetails['location'])): ?>
                <?php if ($this->pickup): ?>
                  <?php foreach ($this->pickup as $library): ?>
                    <?php if ($library['locationID'] == $ilsDetails['location']): ?>
                      <?php $pickupDisplay = $library['locationDisplay']; ?>
                      <?php $pickupTranslate = true; ?>
                    <?php endif; ?>
                  <?php endforeach; ?>
                <?php endif; ?>
                <?php if (empty($pickupDisplay)): ?>
                  <?php $pickupDisplay = $ilsDetails['location']; ?>
                <?php endif; ?>
              <?php endif; ?>
              <?php if (!empty($pickupDisplay)): ?>
                <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
                <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
                <br>
              <?php endif; ?>

              <?php if (!empty($ilsDetails['create'])): ?>
                <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
                <?php if (!empty($ilsDetails['expire'])): ?>|<?php endif; ?>
              <?php endif; ?>
              <?php if (!empty($ilsDetails['expire'])): ?>
                <strong><?=$this->transEsc('ill_request_expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
              <?php endif; ?>
              <br>

              <?php if (isset($this->cancelResults['items'])): ?>
                <?php foreach ($this->cancelResults['items'] as $itemId => $cancelResult): ?>
                  <?php if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                    <?php /* finc: uses <p> and role for alerts */ ?>
                    <p class="alert alert-danger" role="alert"><?=$this->transEsc($cancelResult['status']) ?><?php if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></p>
                  <?php endif; ?>
                <?php endforeach; ?>
              <?php endif; ?>

              <?php if (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
                <p class="text-success"><?=$this->transEsc("request_in_transit") . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], [], $ilsDetails['in_transit']) : '') ?></p>
              <?php endif; ?>
              <?php if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
                <p class="text-success"><?=$this->transEsc("ill_request_processed") . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></p>
              <?php endif; ?>
              <?php if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
                <p class="text-success"><?=$this->transEsc("ill_request_available") ?></p>
              <?php endif; ?>
              <?php if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
                <p class="text-success"><?=$this->transEsc("ill_request_canceled") . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></p>
              <?php endif; ?>
              <?php if (isset($ilsDetails['cancel_link'])): ?>
                <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("ill_request_cancel") ?></a></p>
              <?php endif; ?>
            </div>
            <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
              <?=$thumbnail ?>
            <?php endif ?>
          </div>
          <?php /* finc: adds aria-hidden */ ?>
          <?=$resource->tryMethod('supportsCoinsOpenUrl')?'<span class="Z3988" aria-hidden="true" title="' . $this->escapeHtmlAttr($resource->getCoinsOpenUrl()) . '"></span>':''?>
        </li>
      <?php endforeach; ?>
    </ul>
    <?php if ($this->cancelForm): ?></form><?php endif; ?>
  <?php else: ?>
    <?=$this->transEsc('You do not have any interlibrary loan requests placed') ?>.
  <?php endif; ?>
</div>

<?php /* finc: uses section for sidebar #23430, adds aria-label */ ?>
<section class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" aria-label="<?=$this->transEscAttr('MyAccountSidebar') ?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'ILLRequests'])?>
</section>

<?=$this->render('myresearch/notify-account-status.phtml', ['method' => 'illRequests', 'accountStatus' => $this->accountStatus]); ?>
<!-- finc: myresearch - illrequests - END -->
