<!-- finc: myresearch - setpin -->
<?php
/**
origin: vufind/finc/newpassword
called by view helper/controller:
usage:
 * allows users to set custom pin under My Account
modified for finc:
 * template does not exist in BS, compare during updates with finc/newpassword.phtml
 * uses specific labels or ids for pin in this template
 * uses getCsrfHash(true) #20733
 * removes redundant role=form
 * specific setpin form elements #20733
configured in: {}
 */
?>
<?php
    // Set up page title:
    $this->headTitle($this->translate('LiberoAccount::change_user_pin'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('LiberoAccount::change_user_pin') . '</li>';
?>
<?php if ($this->auth()->isLoggedIn()): ?>
  <div class="<?=$this->layoutClass('mainbody')?>">
    <?php /* finc: uses offcanvas-toggler-myresearch #22293 */ ?>
    <?=$this->render('RecordDriver/DefaultRecord/offcanvas-toggler-myresearch'); ?>
    
<?php endif; ?>

<?php /* finc: uses h1 instead of h2  */ ?>
<?php /* finc: uses specific labels or ids for pin in this template #20733 */ ?>
<h1><?=$this->transEsc('LiberoAccount::change_user_pin') ?></h1>
<p class="alert alert-info" aria-live="polite"><?=$this->transEsc('LiberoAccount::set_pin_note')?></p>
<?=$this->flashmessages() ?>

<?php if (!$this->auth()->getManager()->supportsPasswordChange($this->auth_method)): ?>
  <div class="error"><?=$this->transEsc('recovery_new_disabled') ?></div>
<?php elseif (!isset($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<?php else: ?>
  <?php /* finc: removes redundant role=form */ ?>
  <form id="setpin" class="form-set-pin" action="<?=$this->url('myresearch-setpin') ?>" method="post" data-toggle="validator">
    <?php /* finc: uses getCsrfHash(true) #20733 */ ?>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash(true))?>" name="csrf">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->hash) ?>" name="hash">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->username) ?>" name="username">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth_method) ?>" name="auth_method">

    <?php /* finc-specific setpin form elements #20733 */ ?>
    <?php if (isset($this->cat_username)): ?>
      <div class="form-group">
        <label class="control-label"><?=$this->transEsc('Username')?>:</label>
        <p class="form-control"><?=$this->cat_username?></p>
      </div>
    <?php endif; ?>

    <div class="form-group">
      <label for="pin" class="control-label"><?=$this->transEsc('LiberoAccount::new_pin')?>:</label>
      <input type="password" id="pin" name="pin" class="form-control" required aria-required="true" aria-describedby="pin-policy-error"
          pattern="[0-9]{4}" title="<?=$this->escapeHtmlAttr($this->translate('LiberoAccount::set_pin_note'))?>">
      <div id="pin-policy-error" class="help-block with-errors"></div>
    </div>

    <div class="form-group">
      <label for="confirm-pin" class="control-label"><?=$this->transEsc('LiberoAccount::confirm_new_pin')?>:</label>
      <input type="password" id="confirm-pin" name="pin2" class="form-control" required aria-required="true" data-match="#pin" data-match-error="<?=$this->escapeHtmlAttr($this->translate('LiberoAccount::new_pin_missmatch'))?>" aria-describedby="pin-confirmation-error">
      <div id="pin-confirmation-error" class="help-block with-errors"></div>
    </div>
    <?php /* finc-specific setpin form elements #20733 - END */ ?>
    <div class="form-group">
      <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEscAttr('LiberoAccount::change_user_pin')?>">
    </div>
  </form>
<?php endif; ?>

<?php if ($this->auth()->isLoggedIn()): ?>
  </div>
  <?php /* finc: adds id and aria-label to sidebar; uses section for sidebar #23430 */ ?>
  <section class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" aria-label="<?=$this->transEscAttr('MyAccountSidebar') ?>">
    <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'setpin'])?>
  </section>
<?php endif; ?>
<!-- finc: myresearch - setpin - END -->
