<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>

<div>
  <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />

    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
<!--
    <?=$this->record($this->driver)->getCoreMetadata()?>
-->
  </div>
  <div class="panel-group" id="accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" href="#title-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>">
            <?=$this->translate('information') ?>
          </a>
        </h4>
      </div>
      <div id="title-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse in">
        <div class="panel-body">
      <?=$this->record($this->driver)->getCoreMetadata()?>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" href="#tools-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>">
  Tools
          </a>
        </h4>
      </div>
      <div id="tools-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse">
        <div class="panel-body">
    <?=$this->record($this->driver)->getToolbar()?>
        </div>
      </div>
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" href="#similar-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>">
  <?=$this->transEsc("Similar Items")?>
          </a>
        </h4>
      </div>
      <div id="similar-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse">
        <div class="panel-body">
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
        </div>
      </div>
    </div>

    <? if (count($this->tabs) > 0): ?>
      <? foreach ($this->tabs as $tab => $obj): ?>
        <? if ($tab == 'HierarchyTree') continue; ?>
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a data-toggle="collapse" data-parent="#accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>" href="#<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>">
                <?=$this->transEsc($tab)?>
              </a>
            </h4>
          </div>
          <div id="<?=(strtolower($tab))?>-collapse_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="panel-collapse collapse">
            <div class="panel-body">
              <?=$this->record($this->driver)->getTab($obj) ?>
            </div>
          </div>
        </div>
      <? endforeach; ?>
    <? endif; ?>
  </div>

  <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
</div>
<!--
<div class="<?=$this->layoutClass('sidebar')?>">
  <? foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <? endforeach; ?>
</div>
-->
