<?
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  $this->defaultTab = strtolower($this->defaultTab);

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>
<div class="search_tabs record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="tabs_<?=escapeJSAttr($this->driver->getUniqueId())?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
  <?=$this->flashmessages()?>

  <a name="tabnav"></a>
  <ul class="recordTabs nav nav-tabs">
    <li<? if($this->defaultTab === 'information'): ?> class="active"<? endif; ?>>
      <a id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toggle="tab" data-target="#information-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="noajax">
        <?=$this->translate('ajaxview_label_information') ?>
      </a>
    </li>
    <? foreach ($this->tabs as $tab => $obj): ?>
      <? // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $tab_classes = array();
        if ($this->defaultTab === strtolower($tab)) {
          if (!$this->ajaxTabs || !$obj->supportsAjax()) {
            $tab_classes[] = 'active';
          }
          $tab_classes[] = 'initiallyActive';
          $activeTabObj = $obj;
        }
        if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
        if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
      ?>
      <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
        <a id="<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav" data-toggle="tab" data-target="#<?=strtolower($tab)?>-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>"><?=$this->transEsc($desc)?></a>
      </li>
    <? endforeach; ?>
    <li<? if($this->defaultTab === 'tools'): ?> class="active"<? endif; ?>>
      <a id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toggle="tab" data-target="#tools-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="noajax">
      <?=$this->translate('ajaxview_label_tools') ?>
      </a>
    </li>
    <? if ($this->related()->getList($this->driver) != null ): ?>
    <li<? if($this->defaultTab === 'related'): ?> class="active"<? endif; ?>>
      <a id="related_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toggle="tab" data-target="#related-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>" class="noajax">
        <?=$this->transEsc("Related Items")?>
      </a>
    </li>
      <? endif; ?>
  </ul>
  <div class="tab-content">
    <div class="tab-pane<? if($this->defaultTab === 'information'): ?> active<? endif; ?>" id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>
    <? foreach ($this->tabs as $tab => $obj): ?>
      <div class="tab-pane<? if($this->defaultTab === strtolower($tab)): ?> active<? endif; ?>" id="<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab"></div>
    <? endforeach; ?>
    <div class="tab-pane<? if($this->defaultTab === 'tools'): ?> active<? endif; ?>" id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
      <?=$this->record($this->driver)->getToolbar()?>
    </div>
    <? if ($this->related()->getList($this->driver) != null): ?>
      <div class="tab-pane<? if($this->defaultTab === 'related'): ?> active<? endif; ?>" id="related_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
        <? foreach ($this->related()->getList($this->driver) as $current): ?>
          <?=$this->related()->render($current)?>
        <? endforeach; ?>
      </div>
     <? endif; ?>
  </div>
</div>
<span class="Z3988" title="<?=escapeJSAttr($this->driver->getOpenURL())?>"></span>
