<?php $cart = $this->cart(); ?>
<?php if ($cart->isActive()): ?>
  <?php $cartId = $this->source . '|' . $this->id; ?>
  <span class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a href="#" class="cart-add hidden<?php if(!$cart->contains($cartId)): ?> correct<?php endif ?>">
      <span class="cart-link-label btn-type-add"><?=$this->transEsc('Add to Book Bag') ?></span>
    </a>
    <a href="#" class="cart-remove hidden<?php if($cart->contains($cartId)): ?> correct<?php endif ?>">
      <span class="cart-link-label btn-type-minus"><?=$this->transEsc('Remove from Book Bag') ?></span>
    </a>
    <noscript>
      <?php if (!$cart->contains($cartId)): ?>
        <a href="<?=$this->url('cart-processor', [], ['query' => ['ids[]' => $cartId, 'add' => '1']])?>" class="cart-add">
          <span class="cart-link-label btn-type-add"><?=$this->transEsc('Add to Book Bag') ?></span>
        </a>
      <?php else: ?>
        <a href="<?=$this->url('cart-processor', [], ['query' => ['ids[]' => $cartId, 'delete' => '1']])?>" class="cart-remove">
          <span class="cart-link-label btn-type-minus"><?=$this->transEsc('Remove from Book Bag') ?></span>
        </a>
      <?php endif; ?>
    </noscript>
  </span>
<?php endif; ?>
