<?php $comments = $this->driver->getComments(); ?>
<?php if (empty($comments) || count($comments) == 0): ?>
  <div class="alert alert-info"><?=$this->transEsc('Be the first to leave a comment')?>!</div>
<?php else: ?>
  <?php foreach ($comments as $commentRow): ?>
    <?php [0 => $comment, 'firstname' => $firstname, 'lastname' => $lastname] = $commentRow; ?>
    <div class="comment">
      <div class="comment-name">
        <strong><?=null === $comment->getUser()->getId() ? $this->transEsc('comment_anonymous_user') : $this->escapeHtml(trim($firstname . ' ' . $lastname))?></strong><br>
        <small>
          <?=$this->escapeHtml($comment->getCreated()->format('Y-m-d H:i:s'))?>
          <?php if (($user = $this->auth()->isLoggedIn()) && $comment->getUser()->getId() == $user->id): ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'DeleteComment', ['delete' => $comment->getId()]))?>" id="recordComment<?=$this->escapeHtml($comment->getId())?>" class="delete"><?=$this->transEsc('Delete')?></a>
          <?php endif; ?>
        </small>
      </div>
      <div class="comment-text">
        <?=$this->escapeHtml($comment->getComment())?>
      </div>
      <?php if ($this->driver->isRatingAllowed()): ?>
        <div class="comment-rating">
          <?php $ratingData = $this->driver->getRatingData($comment->getUser()->getId()); ?>
          <?php if ($ratingData['count']): ?>
            <?=$this->render('Helpers/star-rating.phtml', ['readonly' => true, 'ratingData' => $ratingData]);?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
