<?php /* Display thumbnail if appropriate: */ ?>
<?php if ($cover): ?>
  <?php if ($this->link): ?><a href="<?=$this->escapeHtmlAttr($this->link)?>" data-lightbox-image><?php endif; ?>
  <img alt="<?=$this->transEsc($this->link ? 'View Record Cover' : '') ?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" src="<?=$this->escapeHtmlAttr($cover); ?>"/>
  <?php if ($this->link): ?></a><?php endif; ?>
<?php else: ?>
  <img src="<?=$this->url('cover-unavailable')?>" <?php if ($linkPreview): ?>data-linkpreview="true" <?php endif; ?>class="recordcover" alt=""/>
<?php endif; ?>
