<?php
  // Set page title.
  $this->headTitle($this->translate('Email Record'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
    . '<li>' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Email Record') . '</li>';
?>
<h2><?=$this->transEsc('Email Record') ?>: <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span></h2>
<form class="form-record-email" method="post" action="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Email')) ?>" name="emailRecord">
  <?=$this->flashmessages()?>
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
  <?=$this->render('Helpers/email-form-fields.phtml')?>
</form>
