<?php
  // Set page title.
  $this->headTitle($this->translate('permanent_link'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('permanent_link') . '</li>';

  // Collect permalink data:
  $link = $this->serverUrl() . $this->recordLink()->getUrl($this->driver);
?>
<h2><?=$this->transEsc('permanent_link') ?></h2>
<p>
  <pre id="permalink"><?=$link?></pre>
</p>
<p>
  <button type="button" id="copyPermalink" class="btn btn-primary hidden"><?=$this->translate("copy_to_clipboard_button_label")?></button>
  <span id="copySuccessMessage" class="copyMessage hidden text-success"><small><?=$this->translate("copy_to_clipboard_success_message");?></small></span>
  <span id="copyFailureMessage" class="copyMessage hidden text-danger"><small><?=$this->translate("copy_to_clipboard_failure_message");?></small></span>
</p>
<?php
$script = <<<JS
  $(document).ready(function copyPermalink() {
    if (navigator.clipboard) {
      const button = $("#copyPermalink");
      button.removeClass('hidden');
      button.click(function copyToClipboard() {
        navigator.clipboard.writeText($("#permalink").text()).then(
            function copySuccess() {
                $("#copyFailureMessage").addClass("hidden");
                $("#copySuccessMessage").removeClass("hidden");
            },
            function copyFailure() {
                $("#copySuccessMessage").addClass("hidden");
                $("#copyFailureMessage").removeClass("hidden");
            }
        );
      });
    }
  });
JS;
// Inline the script for lightbox compatibility
echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
