<?php
  // Set page title.
  $this->headTitle($this->translate('permanent_link'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('permanent_link') . '</li>';

  // Collect permalink data:
  $link = $this->serverUrl() . $this->recordLink()->getUrl($this->driver);
?>
<h2><?=$this->transEsc('permanent_link') ?></h2>
<p>
  <pre id="permalink"><?=$link?></pre>
</p>
<?=$this->copyToClipboardButton('#permalink');?>
