<?
  // Set page title.
  $this->headTitle($this->translate('Text this'));
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'vendor/libphonenumber.js', 'SET');

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Text this') . '</li>';
?>
<?=$this->flashmessages()?>
<form method="post" name="smsRecord" class="form-horizontal">
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" />
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" />
  <div class="form-group">
    <label class="col-sm-3 control-label" for="sms_to"><?=$this->transEsc('Number')?>:</label>
    <div class="col-sm-9">
      <input id="sms_to" type="tel" name="to" placeholder="<?=$this->transEsc('sms_phone_number')?>" class="form-control"/>
      <div class="help-block with-errors"></div>
    </div>
  </div>
  <? if (is_array($this->carriers) && count($this->carriers) > 1): ?>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="sms_provider"><?=$this->transEsc('Provider')?>:</label>
      <div class="col-sm-9">
        <select id="sms_provider" name="provider" class="form-control">
          <option selected="selected" value=""><?=$this->transEsc('Select your carrier')?></option>
          <? foreach ($this->carriers as $val => $details): ?>
            <option value="<?=$this->escapeHtmlAttr($val)?>"><?=$this->escapeHtml($details['name'])?></option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
  <? else: ?>
    <? $keys = is_array($this->carriers) ? array_keys($this->carriers) : array(); ?>
    <input type="hidden" name="provider" value="<?=isset($keys[0]) ? $keys[0] : ''?>" />
  <? endif; ?>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <?=$this->recaptcha()->html($this->useRecaptcha) ?>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Send Text')?>"<? if(isset($this->validation) && !empty($this->validation)):?> onClick="return phoneNumberFormHandler('sms_to', '<?=$this->validation ?>')"<? endif; ?>/>
    </div>
  </div>
</form>
