<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>
  <div class="search_tabs record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="tabs_<?=escapeJSAttr($this->driver->getUniqueId())?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />

    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
<!--   <?=$this->record($this->driver)->getCoreMetadata()?> -->

    <a name="tabnav"></a>
    <ul class="recordTabs nav nav-tabs">
	<li class="active">
	<a id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>" onclick='ajaxLoadTab("information_<?=escapeJSAttr($this->driver->getUniqueId())?>")' data-toggle="tab" data-target="#information_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
	<?=$this->translate('information') ?>
        </a>
	</li>
	<? foreach ($this->tabs as $tab => $obj): ?>
      <?
        $desc = $obj->getDescription();
      ?>
      <li>
        <a id="<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>" onclick='ajaxLoadTab("<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>")' data-toolge="tab" data-target="#<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
        <li class="hidden">
        <a id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>" onclick='ajaxLoadTab("tools_<?=escapeJSAttr($this->driver->getUniqueId())?>")' data-toggle="tab" data-target="#tools_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
Tools
        </a>
        </li>
        <li>
        <a id="similar_<?=escapeJSAttr($this->driver->getUniqueId())?>" onclick='ajaxLoadTab("similar_<?=escapeJSAttr($this->driver->getUniqueId())?>")' data-toggle="tab" data-target="#similar_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
<?=$this->transEsc("Similar Items")?>
        </a>
        </li>
    </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
<?=$this->record($this->driver)->getCoreMetadata()?>
    </div>
    <? foreach ($this->tabs as $tab => $obj): ?>
      <div class="tab-pane" id="<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab"></div>
    <? endforeach; ?>
    <div class="tab-pane" id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
  <?=$this->record($this->driver)->getToolbar()?>
    </div>
      <div class="tab-pane" id="similar_<?=escapeJSAttr($this->driver->getUniqueId())?>-tab">
  <? foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <? endforeach; ?>
      </div>
  </div>
</div>
  <span class="Z3988" title="<?=escapeJSAttr($this->driver->getOpenURL())?>"></span>
