<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>
<div style="padding: 5px">
  <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="tabs_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />

    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
<!--   <?=$this->record($this->driver)->getCoreMetadata()?> -->

    <a name="tabnav"></a>
    <ul class="recordTabs nav nav-tabs">
	<li class="active">
	<a id="information_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" onclick='showhideTabs("information_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>")' data-toogle="tab" data-target="#information-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
	<?=$this->translate('information') ?>
        </a>
	</li>
	<? foreach ($this->tabs as $tab => $obj): ?>
      <? 
        $desc = $obj->getDescription();
      ?>
      <li>
        <a id="<?=strtolower($tab)?>_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" onclick='showhideTabs("<?=strtolower($tab)?>_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>")' data-toolge="tab" data-target="#<?=strtolower($tab)?>-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
        <li class="hidden">
        <a id="tools_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" onclick='showhideTabs("tools_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>")' data-toogle="tab" data-target="#tools-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
Tools
        </a>
        </li>
        <li>
        <a id="similar_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" onclick='showhideTabs("similar_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>")' data-toogle="tab" data-target="#similar-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
<?=$this->transEsc("Similar Items")?>
        </a>
        </li>
    </ul>
  <div class="tab-content">
    <div class="tab-pane active" id="information-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
<?=$this->record($this->driver)->getCoreMetadata()?>	
    </div>
       <? foreach ($this->tabs as $tab => $obj): ?>
     <div class="tab-pane" id="<?=strtolower($tab)?>-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
      <?=$this->record($this->driver)->getTab($obj)?>
	</div>
     <? endforeach; ?>
    <div class="tab-pane" id="tools-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
  <?=$this->record($this->driver)->getToolbar()?>
    </div>
      <div class="tab-pane" id="similar-tab_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
  <? foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <? endforeach; ?>
      </div>
  </div>
</div>
  <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
</div>
