<div id="tagList"<?=$loggedin ? ' class="loggedin"' : ''?>>
  <? if (count($tagList) > 0): ?>
    <? foreach ($tagList as $tag): ?>
      <? $is_me = isset($tag['is_me']) && !is_null($tag['is_me']) ? $tag['is_me'] : false; ?>
      <div class="tag<?=$is_me ? ' selected' : ''?>">
        <a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag['tag'])?>"><?=$this->escapeHtml($tag['tag'])?></a>
        <? if($loggedin): ?>
          <? $updateHref = $is_me
            ? $this->recordLink()->getActionUrl($this->driver, 'DeleteTag') . '?tag='.urlencode($tag['tag'])
            : $this->recordLink()->getActionUrl($this->driver, 'AddTag') . '?tag='.urlencode('"'.$tag['tag'].'"'); ?>
          <a class="badge" onClick="ajaxTagUpdate('<?=urlencode($tag['tag'])?>', <?=$is_me ? 'true' : 'false' ?>);return false;" href="<?=$updateHref ?>"><?=$this->escapeHtml($tag['cnt']) ?>
          <? if($is_me): ?>
            <i class="fa fa-close"></i></a>
          <? else: ?>
            <i class="fa fa-plus"></i></a>
          <? endif; ?>
        <? else: ?>
          <span class="badge"><?=$this->escapeHtml($tag['cnt'])?></span>
        <? endif; ?>
      </div>
    <? endforeach; ?>
  <? else: ?>
    <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
  <? endif; ?>
</div>