<div class="tagList<?=$loggedin ? ' loggedin' : ''?>">
  <?php if (count($tagList) > 0): ?>
    <?php foreach ($tagList as $tag): ?>
      <?php $is_me = isset($tag['is_me']) && null !== $tag['is_me'] ? $tag['is_me'] : false; ?>
      <div class="tag<?=$is_me ? ' selected' : ''?>">
        <a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag['tag'])?>"><?=$this->escapeHtml($tag['tag'])?></a>
        <?php if($loggedin): ?>
          <form method="POST" action="<?=$this->recordLink()->getActionUrl($this->driver, $is_me ? 'DeleteTag' : 'AddTag') ?>" class="tag-form">
            <input type="hidden" name="tag" value="<?=$this->escapeHtmlAttr($tag['tag'])?>"/>
            <button type="submit" class="badge" onClick="ajaxTagUpdate(this, '<?=$this->escapeHtmlAttr($tag['tag'])?>', <?=$is_me ? 'true' : 'false' ?>);return false;"><?=$this->escapeHtml($tag['cnt']) ?>
            <?php if($is_me): ?>
              <i class="fa fa-close" title="<?=$this->transEsc('delete_tag') ?>"></i>
            <?php else: ?>
              <i class="fa fa-plus" title="<?=$this->transEsc('Add Tag') ?>"></i>
            <?php endif; ?>
            </button>
          </form>
        <?php else: ?>
          <span class="badge"><?=$this->escapeHtml($tag['cnt'])?></span>
        <?php endif; ?>
      </div>
    <?php endforeach; ?>
  <?php else: ?>
    <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
  <?php endif; ?>
</div>
