<!-- devtools LANGUAGE.phtml -->
<?
$this->headTitle($this->translate('Language'));
?>

<h2>Comparing Languages Against <?= $this->escapeHtml($mainName) ?></h2>

<h3>Summary</h3>

<table class="table">
  <tr>
    <th>Language</th>
    <th>Missing Lines</th>
    <th>Extra Lines</th>
    <th>Percent Translated</th>
    <th>Extra Help Files</th>
  </tr>
  <? foreach ($details as $langCode => $diffs): ?>
    <tr>
      <td><?= $this->escapeHtml($langCode . ' (' . $diffs['name'] . ')') ?></td>
      <td><?= count($diffs['notInL2']) ?></td>
      <td><?= count($diffs['notInL1']) ?></td>
      <td><?= $this->escapeHtml($diffs['l2Percent']) ?></td>
      <td><?= count($diffs['helpFiles']) ?></td>
    </tr>
  <? endforeach; ?>
</table>
<ul class="small-block-grid-1 medium-block-grid-2">
  <li>
    <? foreach ($details as $langCode => $diffs): ?>
      <? if (count($diffs['notInL1']) > 0): ?>
        <ul class="accordion" id="accordion1" data-accordion="AccordionGroup">
          <li class="accordion-navigation">
            <a href="#extra_<?= $langCode ?>">
              Extra Lines In <?= $this->escapeHtml($diffs['name']) ?> (<?= $this->escapeHtml($langCode) ?>.ini)
            </a>

            <div id="extra_<?= $langCode ?>" class="content">
              <div class="accordion-inner">
                <? foreach ($diffs['notInL1'] as $key): ?>
                  <?= $this->escapeHtml($key) ?> = "<?= $this->escapeHtml($diffs['object'][$key]) ?>"<br/>
                <? endforeach; ?>
              </div>
            </div>
          </li>
        </ul>
      <? endif; ?>
      <? if (count($diffs['notInL2']) > 0): ?>
        <ul class="accordion" id="accordion2" data-accordion="AccordionGroup">
          <li class="accordion-navigation">
            <a href="#missing_<?= $langCode ?>">
              Missing From <?= $this->escapeHtml($diffs['name']) ?> (<?= $this->escapeHtml($langCode) ?>.ini)
              <span class="pull-right"></span>
            </a>

            <div id="missing_<?= $langCode ?>" class="content">
              <div class="accordion-inner">
                <textarea class="auto" rows="15"><? foreach ($diffs['notInL2'] as $key): ?><?= $this->escapeHtml($key) ?> = "<?= $this->escapeHtml($main[$key]) ?>"
                  <? endforeach; ?></textarea>
              </div>
            </div>
          </li>
        </ul>
      <? endif; ?>
    <? endforeach; ?>
  </li>
</ul>
<!-- devtools LANGUAGE.phtml end -->