<? if (!empty($this->expanderList)): ?>
  <fieldset class="span-5">
    <legend><?=$this->transEsc('eds_modes_and_expanders')?></legend>
    <? foreach ($this->expanderList as $field => $expander):
       $value = $expander['Value'] ?>
       <label class="displayBlock" for="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>"><?=$this->transEsc('eds_expander_' . $value, array(), $expander['Label'])?></label>
       <input id="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($expander['selected']) && $expander['selected'])?'checked="checked"':''?> name="filter[]" value="EXPAND:<?=$this->escapeHtmlAttr($value)?>">
    <? endforeach; ?>

    <label class="displayBlock" for="searchModes"><?=$this->transEsc('Search Mode')?></label>
    <select id="searchMode_<?=$this->escapeHtmlAttr($field)?>" name="filter[]">
      <? foreach ($this->searchModes as $field => $searchMode):
         $value = $searchMode['Value'] ?>
         <option <?=(isset($searchMode['selected']) && $searchMode['selected'])?'selected="selected"':''?>  value="SEARCHMODE:<?=$this->escapeHtmlAttr($value)?>">
           <?= /* 'Label' comes from API and is always in English; try to translate structured value before using it: */ $this->transEsc('eds_mode_' . $value, array(), $searchMode['Label']) ?>
         </option>
      <? endforeach; ?>
    </select>
  </fieldset>
  <div class="clear"></div>
<? endif; ?>

<? if (!empty($this->limiterList)): ?>
    <fieldset class="span-5">
        <legend><?=$this->transEsc('Limit To')?></legend>
  <? foreach ($this->limiterList as $field => $facet): ?>
    <? switch($facet['Type']){
        case 'multiselectvalue': ?>
            <label class="displayBlock" for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>"><?=$this->transEsc($facet['Label'])?></label>
            <select id="limit_<?=$this->escapeHtmlAttr($field)?>" name="filter[]" multiple="multiple" size="10">
                <? foreach ($facet['LimiterValues'] as $id => $facetValue): ?>
                    <? $value = $facetValue['Value']; ?>
                    <option value="<?='LIMIT|'.$this->escapeHtmlAttr($field . ':' . $facetValue['Value'])?>"<?=(isset($facetValue['selected']) && $facetValue['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($facetValue['Value'])?></option>
                <? endforeach; ?>
            </select>
            <!-- <br/> -->
            <? break;
        case 'select':
            $value = $facet['LimiterValues'][0]['Value'] ?>
            <label class="displayBlock" for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>">
              <?=$this->transEsc('eds_limiter_' . $field, array(), $facet['Label'])?>
            </label>
            <input id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($facet['LimiterValues'][0]['selected']) && $facet['LimiterValues'][0]['selected'])?'checked="checked"':''?> name="filter[]" value="<?=$this->escapeHtmlAttr('LIMIT|'.$field . ':' . $value)?>">
                        <!-- <br/> -->
            <? break;
        case 'text': ?>
            <!-- not implemented -->
            <? break;
        case 'numeric':?>
            <!--  not implemented -->
            <? break;
        case 'numericrange':?>
            <!--  not implemented -->
            <? break;
        case 'ymrange': ?>
            <!--  not implemented -->
            <? break;
        case 'yrange': ?>
            <!--  not implemented -->
            <? break;
        case 'historicalrange':?>
            <!--  not implemented -->
            <? break;
        case 'singleselectvalue':?>
            <!--  not implemented -->
            <? break;
        }; ?>
  <? endforeach; ?>
  <div class="clear"></div>
  <? if (isset($this->dateRangeLimit)): ?>
  <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
  <input type="hidden" name="daterange[]" value="PublicationDate"/>
  <fieldset class="publishDateLimit span-5" id="PublicationDate">
    <legend><?=$this->transEsc('adv_search_year')?></legend>
    <label for="PublicationDatefrom"><?=$this->transEsc('date_from')?>:</label>
    <input type="text" size="4" maxlength="4" class="yearbox" name="PublicationDatefrom" id="PublicationDatefrom" value="<?=$this->escapeHtmlAttr($this->dateRangeLimit[0])?>" />
    <label for="PublicationDateto"><?=$this->transEsc('date_to')?>:</label>
    <input type="text" size="4" maxlength="4" class="yearbox" name="PublicationDateto" id="PublicationDateto" value="<?=$this->escapeHtmlAttr($this->dateRangeLimit[1])?>" />
    <div id="PublicationDateSlider" class="dateSlider"></div>
  </fieldset>
<? endif; ?>
  </fieldset>

 <div class="clear"></div>
<? endif; ?>
<div class="clear"></div>
