<?
    // Set page title.
    $this->headTitle($this->translate('Advanced Search'));

    // Disable top search box -- this page has a special layout.
    $this->layout()->searchbox = false;

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Advanced') . '</em>';

    // Set up saved search details:
    if (isset($this->saved) && is_object($this->saved)) {
        $searchDetails = $this->saved->getSearchTerms();
        $searchFilters = $this->saved->getFilterList();
    } else {
        $searchDetails = $searchFilters = false;
    }

    // Set up Javascript:
    // Step 1: Define our search arrays so they are usuable in the javascript
    $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
    // Step 2: Call the javascript to make use of the above
    $this->headScript()->appendFile('advanced_search.js');
    // Step 3: Build the page
    $this->headScript()->appendScript($this->partial('search/advanced/build_page.phtml', array('searchDetails' => $searchDetails)));
?>
<form method="get" action="<?=$this->url($this->options->getSearchAction())?>" id="advSearchForm" name="searchForm" class="search">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h3><?=$this->transEsc('Advanced Search')?></h3>
    <div class="advSearchContent">
      <?=$this->flashmessages()?>
      <div id="groupJoin" class="searchGroups">
        <div class="searchGroupDetails">
          <label for="groupJoinOptions"><?=$this->transEsc("search_match")?>:</label>
          <select id="groupJoinOptions" name="join">
            <option value="AND"><?=$this->transEsc("group_AND")?></option>
            <option value="OR"<?=(isset($searchDetails[0]['join']) && $searchDetails[0]['join'] == 'OR') ? ' selected="selected"' : ''?>><?=$this->transEsc("group_OR")?></option>
          </select>
        </div>
        <strong><?=$this->transEsc("search_groups")?></strong>:
      </div>

      <? /* An empty div. This is the target for the javascript that builds this screen */ ?>
      <div id="searchHolder">
        <? /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
        <noscript>
        <? if ($searchDetails !== false) {
               $numGroups = count($searchDetails);
           }
           if (!isset($numGroups) || $numGroups < 3) {
               $numGroups = 3;
           }
        ?>
        <? for ($i = 0; $i < $numGroups; $i++): ?>
          <div class="group group<?=$i%2?>" id="group<?=$i?>">
            <div class="groupSearchDetails">
              <div class="join">
                <label for="search_bool<?=$i?>"><?=$this->transEsc("search_match")?>:</label>
                <select id="search_bool<?=$i?>" name="bool<?=$i?>[]">
                  <?
                    $options = array('AND', 'OR', 'NOT');
                    foreach ($options as $option) {
                        echo '<option value="' . $this->escape($option) . '"';
                        if ($searchDetails && isset($searchDetails[$i]['group'][0]['bool'])
                            && $searchDetails[$i]['group'][0]['bool'] == $option
                        ) {
                            echo ' selected="selected"';
                        }
                        echo '>' . $this->transEsc('search_' . $option) . '</option>';
                    }
                  ?>
                </select>
              </div>
            </div>
            <div class="groupSearchHolder" id="group<?=$i?>SearchHolder">
            <?
              if (isset($searchDetails[$i]['group'])) {
                  $numRows = count($searchDetails[$i]['group']);
              }
              if (!isset($numRows) || $numRows < 3) {
                  $numRows = 3;
              }
            ?>
            <? for ($j = 0; $j < $numRows; $j++): ?>
              <? $currRow = isset($searchDetails[$i]['group'][$j]) ? $searchDetails[$i]['group'][$j] : false; ?>
              <div class="advRow">
                <div class="label">
                  <label <?=($j > 0)?'class="offscreen" ':''?>for="search_lookfor<?=$i?>_<?=$j?>"><?=$this->transEsc("adv_search_label")?>:</label>&nbsp;
                </div>
                <div class="terms">
                  <input id="search_lookfor<?=$i?>_<?=$j?>" type="text" value="<?=isset($currRow['lookfor'])?$this->escape($currRow['lookfor']):''?>" size="50" name="lookfor<?=$i?>[]"/>
                </div>
                <div class="field">
                  <label for="search_type<?=$i?>_<?=$j?>"><?=$this->transEsc("in")?></label>
                  <select id="search_type<?=$i?>_<?=$j?>" name="type<?=$i?>[]">
                  <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                    <option value="<?=$this->escape($searchVal)?>"<?=(isset($currRow['field']) && $currRow['field'] == $searchVal)?' selected="selected"':''?>><?=$this->transEsc($searchDesc)?></option>
                  <? endforeach; ?>
                  </select>
                </div>
                <span class="clearer"></span>
              </div>
            <? endfor; ?>
            </div>
          </div>
        <? endfor; ?>
        </noscript>
      </div>

      <a id="addGroupLink" href="#" class="add offscreen" onclick="addGroup(); return false;"><?=$this->transEsc("add_search_group")?></a>

      <br/><br/>

      <? $lastSort = $this->options->getLastSort(); if (!empty($lastSort)): ?>
        <input type="hidden" name="sort" value="<?=$this->escape($lastSort)?>" />
      <? endif; ?>
      <input type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
      <? if (isset($this->extraAdvancedControls)): ?>
        <?=$this->extraAdvancedControls?>
        <input type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
      <? endif; ?>
    </div>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <? if (!empty($searchFilters)): ?>
      <div class="filterList">
        <h3><?=$this->transEsc("adv_search_filters")?><br/><span>(<?=$this->transEsc("adv_search_select_all")?> <input type="checkbox" checked="checked" onclick="filterAll(this, 'advSearchForm');" />)</span></h3>
        <? foreach ($searchFilters as $field => $data): ?>
          <div>
            <h4><?=$this->transEsc($field)?></h4>
            <ul>
              <? foreach ($data as $value): ?>
                <li><input type="checkbox" checked="checked" name="filter[]" value='<?=$this->escape($value['field'])?>:"<?=$this->escape($value['value'])?>"' /> <?=$this->escape($value['displayText'])?></li>
              <? endforeach; ?>
            </ul>
          </div>
        <? endforeach; ?>
      </div>
    <? endif; ?>
    <div class="sidegroup">
      <h4><?=$this->transEsc("Search Tips")?></h4>
      <a href="<?=$this->url('help-home')?>?topic=searchadv" class="advsearchHelp"><?=$this->transEsc("Help with Advanced Search")?></a><br />
      <a href="<?=$this->url('help-home')?>?topic=search" class="searchHelp"><?=$this->transEsc("Help with Search Operators")?></a>
    </div>
  </div>

  <div class="clear"></div>
</form>