<?
    // Set up convenience variables:
    $limitList = $this->options->getLimitOptions();

    // If a previous limit was used, make that the default; otherwise, use the "default default"
    $lastLimit = $this->options->getLastLimit();
    $defaultLimit = empty($lastLimit) ? $this->options->getDefaultLimit() : $lastLimit;
?>
<? if (count($limitList) > 1): ?>
  <fieldset class="span-4">
    <legend><?=$this->transEsc('Results per page')?></legend>
    <select id="limit" name="limit">
      <? foreach ($limitList as $limitVal): ?>
        <option value="<?=$this->escape($limitVal)?>"<?=($limitVal == $defaultLimit) ? 'selected="selected"' : ''?>><?=$this->escape($limitVal)?></option>
      <? endforeach; ?>
    </select>
  </fieldset>
<? endif; ?>