<? if (isset($this->ranges) && !empty($this->ranges)): ?>
  <? $params = $this->searchParams($this->searchClassId); $params->activateAllFacets(); ?>
  <? foreach ($this->ranges as $current): $escField = $this->escapeHtmlAttr($current['field']); ?>
    <? if ($current['type'] == 'date'): ?>
      <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
    <? endif; ?>
    <input type="hidden" name="<?=$this->escapeHtmlAttr($current['type'])?>range[]" value="<?=$escField?>"/>
    <fieldset class="publishDateLimit span-5" id="<?=$escField?>">
      <legend><?=$this->transEsc($params->getFacetLabel($current['field']))?></legend>
      <label for="<?=$escField?>from"><?=$this->transEsc('date_from')?>:</label>
      <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$escField?>from" id="<?=$escField?>from" value="<?=$this->escapeHtmlAttr($current['values'][0])?>" />
      <label for="<?=$escField?>to"><?=$this->transEsc('date_to')?>:</label>
      <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$escField?>to" id="<?=$escField?>to" value="<?=$this->escapeHtmlAttr($current['values'][1])?>" />
      <div id="<?=$escField?>Slider" class="<?=$this->escapeHtmlAttr($current['type'])?>Slider"></div>
    </fieldset>
  <? endforeach; ?>
<? endif; ?>
