<?
    // Set up Javascript for use below:
    $loadJs = 'var url = path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
        . "\$('#openLibraryDeferredRecommend').load(url);";
?>
<div id="openLibraryDeferredRecommend">
    <p><?=$this->transEsc("Loading")?>... <img src="<?=$this->imageLink('ajax_loading.gif')?>" /></p>
    <?=$this->inlineScript(Zend_View_Helper_HeadScript::SCRIPT, $loadJs)?>
</div>