<h1>Helpful Searching Tips</h1>

<ul class="HelpMenu">
  <li><a href="#boolean_operators">Boolean Operators</a>
    <ul>
      <li><a href="#boolean_and">AND</a></li>
      <li><a href="#boolean_or">OR</a></li>
      <li><a href="#boolean_not">NOT</a></li>
    </ul>
  </li>
</ul>

<dl class="Content">
  <dt><a id="boolean_operators"></a>Boolean Operators</dt>
  <dd>
    <p>
      Boolean operators allow terms to be combined with logic operators.
      The following operators are allowed: <strong>AND</strong>, <strong>OR</strong> and <strong>NOT</strong>.
    </p>
    <p>Note: Boolean operators must be ALL CAPS</p>
    <dl>
      <dt><a id="boolean_and"></a>AND</dt>
      <dd>
        <p>The <strong>AND</strong> operator is the default conjunction operator. This means that if there is no Boolean operator between two terms, the AND operator is used. The AND operator matches records where both terms exist anywhere in the field of a record.</p>
        <p>To search for records that contain "economics" and "Keynes" use the query: </p>
        <pre class="code">economics Keynes</pre>
        <p>or</p>
        <pre class="code">economics AND Keynes</pre>
      </dd>
      <dt><a id="boolean_or"></a>OR</dt>
      <dd>
        <p>The OR operator links two terms and finds a matching record if either of the terms exist in a record.</p>
        <p>To search for documents that contain either "economics Keynes" or just "Keynes" use the query:</p>
        <pre class="code">"economics Keynes" OR Keynes</pre>
      </dd>
      <dt><a id="boolean_not"></a>NOT</dt>
      <dd>
        <p>The NOT operator excludes records that contain the term after NOT.</p>
        <p>To search for documents that contain "economics" but not "Keynes" use the query: </p>
        <pre class="code">economics NOT Keynes</pre>
        <p>Note: The NOT operator cannot be used with just one term. For example, the following search will return no results:</p>
        <pre class="code">NOT economics</pre>
      </dd>
    </dl>
  </dd>
</dl>
