<?php $userAccess = $this->tuefind()->getUserAccessState($this->driver->getUniqueId(), $this->user->id ?? null);?>
<div>
  <?php if ($userAccess['availability'] == 'free'): ?>
    <a class="save-record toolbar-btn btn-type-save" rel="nofollow" href="<?=$this->url('authority-request-access', ['authority_id' => $this->driver->getUniqueId()])?>" data-lightbox="">Request access rights (This is me!)</a>
  <?php elseif ($userAccess['availability'] == 'mine' && $userAccess['access_state'] == 'requested'): ?>
    You have requested permission on this authority record. Our team has been informed, please wait for the approval.
  <?php elseif ($userAccess['availability'] == 'mine' && $userAccess['access_state'] == 'granted'): ?>
    This authority record is linked to your user account.
    <?php if ($this->user != false && $this->accountCapabilities()->getPublicationSetting() === 'enabled'): ?>
      <br><a href="<?=$this->url('myresearch-publications')?>">Would you like to publish something?</a>
    <?php endif; ?>
  <?php elseif ($this->user != false && $this->accountCapabilities()->getPublicationSetting() === 'enabled'): ?>
    <span class="save-record toolbar-btn btn-type-save">Another user already has rights to this authority record</span>
  <?php endif; ?>
</div>