<?php $titlePreviewOffset = 0; $titlePreviewLimit = 5; ?>
<?php $response = $this->authority()->getNewestTitlesFrom($this->driver, $titlePreviewOffset, $titlePreviewLimit); ?>
<?php if ($response->getTotal() > 0): ?>
  <h4>Newest titles (from)</h4>
  <ul class="list-group">
    <?php foreach ($response as $record): ?>
      <li class="list-group-item"><a href="<?=$this->recordLink()->getUrl($record)?>"><?=$record->getTitle()?></a></li>
    <?php endforeach; ?>
  </ul>
  <?php if ($response->getTotal() > $titlePreviewLimit): ?>
    <p>
      <a href="<?=$this->record($this->driver)->getLink('titles-from', $this->driver)?>">Show all titles (<?=$response->getTotal()?>)</a>
    </p>
  <?php endif; ?>
<?php endif; ?>
