<?php $titlePreviewOffset = 0; $titlePreviewLimit = 5; ?>
<?php $response = $this->authority()->getTitles($this->driver, $titlePreviewOffset, $titlePreviewLimit); ?>
<?php if ($response->getTotal() > 0): ?>
  <h4>Selected titles</h4>
  <ul class="list-group">
    <?php foreach ($response as $record): ?>
      <li class="list-group-item"><a href="<?=$this->recordLink()->getUrl($record)?>"><?=$record->getTitle()?></a></li>
    <?php endforeach; ?>
  </ul>
  <?php if ($response->getTotal() > $titlePreviewLimit): ?>
    <p>
      <a href="<?=$this->url('search-results', [], ['query' => ['lookfor' => 'author_id:' . $this->driver->getUniqueID()]])?>">Show all titles (<?=$response->getTotal()?>)</a>
    </p>
  <?php endif; ?>
<?php endif; ?>
