<?php $previewLimit = 5; ?>
<?php $response = $this->authority()->getRelatedAuthors($this->driver); ?>
<?php if (count($response) > 0): ?>
  <h4>Related authors</h4>
  <ul class="list-group">
    <?php $i=0; ?>
    <?php foreach ($response as $authorTitle => $authorDetails): ?>
      <?php if (++$i > $previewLimit) break;?>
      <li class="list-group-item">
        <?=$authorTitle?>
        <?php if (($authorityId = $authorDetails['id'] ?? null) && ($authorityDriver = $this->authority()->recordExists($authorityId))): ?>
          <a href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($this->authority()->getRelatedJointQueryParams($this->driver, $authorityDriver))?>"><i class="fa fa-link" aria-hidden="true" title="Show joint titles for this author"></i></a>
          <a href="<?=$this->record($authorityDriver)->getLink('titles-from', $authorityDriver)?>"><i class="fa fa-book" aria-hidden="true" title="Show all titles for this author"></i></a>
          <a href="<?=$this->record($authorityDriver)->getLink('authority', $authorityId)?>"><i class="fa fa-user-circle" aria-hidden="true" title="Show more details for this author"></i></a>
        <?php else: ?>
          <a href="<?=$this->url('search-results')?>?lookfor=<?=urlencode($this->authority()->getRelatedJointQueryParams($this->driver, $authorTitle))?>"><i class="fa fa-link" aria-hidden="true" title="Show joint titles for this author"></i></a>
          <a href="<?=$this->record($this->driver)->getLink('author', $authorTitle)?>"><i class="fa fa-book" aria-hidden="true" title="Show all titles for this author"></i></a>
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
  <?php if (count($response) > $previewLimit): ?>
    <p>
      <a href="<?=$this->url('author-search')?>?lookfor=<?=urlencode($this->driver->getTitle())?>">Show all related authors (<?=count($response)?>)</a>
    </p>
  <?php endif; ?>
<?php endif; ?>
