<?php
    $this->headScript()->appendFile("vendor/chart-loader.js");

    $responseChartData = $this->authority()->getChartData($this->driver); if(!empty($responseChartData)) :
    $googleChartData = '';
    $chartJSDates = '';
    $chartJSby = '';
    $chartJSabout = '';
    foreach($responseChartData as $chartData) {
        $googleChartData .= "['".$chartData[0]."', ".$chartData[1].", 0, ".$chartData[2].", ''],";
        $chartJSDates .= $chartData[0].',';
        $chartJSby .= $chartData[1].',';
        $chartJSabout .= $chartData[2].',';
    }
?>
<!-- google chart -->
<?php
$jsSnippet = <<<EOD
$(function () {
    google.charts.load('upcoming', {packages: ['corechart']});
        google.charts.setOnLoadCallback(drawChart);
        function drawChart() {
            var options = {
                isStacked:  true,
                title:      'Publication Timeline',
                height:     200,
                legend:     { position: 'top', maxLines: 3 },
                bar:        { groupWidth: '75%' },
                isStacked:  true,
                colors:     ['#FF7600', '#FFFFFF', '#2178b5'],
                vAxis:      {
                                baselineColor: '#fff',
                                gridlineColor: '#fff',
                                textPosition: 'none'
                            }
            };
            var data = google.visualization.arrayToDataTable([

                ['', 'By', ' ', 'About', { role: 'annotation' } ],

                {$googleChartData}

            ]);
            var chart = new google.visualization.ColumnChart(document.getElementById('publication_timeline_chart'),1);
            chart.draw(data, options);
        };

});
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
<div class="col-md-12" style="padding:20px; margin-bottom: 20px;  border: 1px solid #ddd; border-radius: 4px;">
    <div id="publication_timeline_chart" style="width: 100%; height: 250px; margin: 0 auto"></div>
    <!-- end google chart -->
    <!-- chart JS-->
    <canvas id="myChart" width="" height=""></canvas>
</div>
<?php
$this->headScript()->appendFile("vendor/chart-JS.js");

$jsSnippet2 = <<<EOD
$(function () {
        var ctx = document.getElementById('myChart').getContext('2d');

        const labels = [{$chartJSDates}];

        const byData = [{$chartJSby}];

        const aboutData = [{$chartJSabout}];

        const data = {
          labels: labels,
          datasets: [
            {
              label: 'By',
              data: byData,
              backgroundColor: '#265680',
            },
            {
              label: 'About',
              data: aboutData,
              backgroundColor: '#089de3',
            }
          ]
        };

        const config = {
            type: 'bar',
            data: data,
            options: {
              plugins: {
                title: {
                  display: true,
                  text: 'Publication Timeline'
                },
              },
              responsive: true,
              scales: {
                x: {
                  stacked: true,
                },
                y: {
                  stacked: true
                }
              }
            }
          };

   var myChart = new Chart(ctx, config);

});
EOD;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet2, 'SET')?>
<?php endif;?>
