<?
    $this->headTitle($this->translate('Collection Browse'));
    $this->layout()->breadcrumbs = '<a href="' . $this->url('collections-home') . '">' . $this->transEsc('Collections') . '</a>';
    $filterList = array();
    $filterString = '';
    foreach (isset($filters['Other']) ? $filters['Other'] : array() as $filter) {
        $filter['urlPart'] = $filter['field'] . ':' . $filter['value'];
        $filterList[] = $filter;
        $filterString .= '&' . urlencode('filter[]') .  '=' . urlencode($filter['urlPart']);
    }
?>
<? ob_start(); ?>
  <div class="alphaBrowsePageLinks">
    <? if (isset($prevpage)): ?>
      <div class="alphaBrowsePrevLink"><a href="<?=$this->url('collections-home')?>?from=<?=urlencode($from)?>&amp;page=<?=urlencode($prevpage)?><?=$this->escapeHtml($filterString)?>">&laquo; <?=$this->transEsc('Prev')?></a></div>
    <? endif; ?>
    <? if (isset($nextpage)): ?>
      <div class="alphaBrowseNextLink"><a href="<?=$this->url('collections-home')?>?from=<?=urlencode($from)?>&amp;page=<?=urlencode($nextpage)?><?=$this->escapeHtml($filterString)?>"><?=$this->transEsc('Next')?> &raquo;</a></div>
    <? endif; ?>
    <div class="clear"></div>
  </div>
<? $pageLinks = ob_get_contents(); ?>
<? ob_end_clean(); ?>
<? if (!empty($filterList)): ?>
    <strong><?=$this->transEsc('Remove Filters')?></strong>
    <ul class="filters">
    <? foreach ($filterList as $filter): ?>
      <li>
        <?
            $removalUrl = $this->url('collections-home') . '?from=' . urlencode($from);
            foreach ($filterList as $current) {
                if ($current['urlPart'] != $filter['urlPart']) {
                    $removalUrl .= '&' . urlencode('filter[]') .  '=' . urlencode($current['urlPart']);
                }
            }
        ?>
        <a href="<?=$this->escapeHtml($removalUrl)?>"><img src="<?=$this->imageLink('silk/delete.png')?>" alt="Delete"/></a>
        <a href="<?=$this->escapeHtml($removalUrl)?>"><?=$this->escapeHtml($filter['displayText'])?></a>
      </li>
    <? endforeach; ?>
    </ul>
<? endif; ?>
<div class="browseAlphabetSelector">
  <? foreach ($letters as $letter): ?>
   <div class="browseAlphabetSelectorItem"><a href="<?=$this->url('collections-home')?>?from=<?=urlencode($letter)?><?=$this->escapeHtml($filterString)?>"><?=$this->escapeHtml($letter)?></a></div>
  <? endforeach; ?>
</div>

<div class="browseJumpTo">
<form method="GET" action="<?=$this->url('collections-home')?>" class="browseForm">
  <input type="submit" value="<?=$this->transEsc('Jump to')?>" />
  <input type="text" name="from" value="<?=$this->escapeHtml($from)?>" />
</form>
</div>

<div class="clear">&nbsp;</div>

<h2><?=$this->transEsc('Collection Browse')?></h2>

<div class="collectionBrowseResult">
  <?=$pageLinks?>
  <?=$this->render('collections/list.phtml')?>
  <div class="clearer"></div>
  <?=$pageLinks?>
</div>