<? foreach ($result as $i => $item): ?>
  <div class="collectionBrowseEntry listBrowse<?=($i % 2 == 0) ? ' alt' : ''?>">
    <div class="collectionBrowseHeading">
      <a href="<?=$this->url('collection', array('id' => $item['value']))?>"><?=$this->escapeHtml($item['displayText'])?></a>
    </div>
    <? /* subtract one from the number of items to exclude the record representing the collection itself. */ ?>
    <div class="collectionBrowseCount"><b><?=$item['count'] - 1?></b> <?=$this->transEsc('items')?></div>
    <div class="clearer"><!-- empty --></div>
  </div>
<? endforeach; ?>