<?php
return [
    'icons' => [
        'sets' => [
            /**
             * Define icon sets here.
             *
             * All sets need:
             * - 'template': which template the icon renders with
             * - 'src': the location of the relevant resource (font, css, images)
             * - 'prefix': prefix to place before each icon name for convenience
             *             (ie. fa fa- for FontAwesome, default "")
             */
            'FontAwesome4' => [
                'template' => 'font',
                'prefix' => 'fa fa-',
                'src' => 'vendor/font-awesome-4.7.0/css/font-awesome.min.css',
            ],
        ],
        'aliases' => [
            /**
             * Icons can be assigned or overridden here
             *
             * Format: 'icon' => [set:]icon[:extra_classes]
             * Icons assigned without set will use the defaultSet.
             * In order to specify extra CSS classes, you must also specify a set.
             *
             * All of the items below have been specified with FontAwesome to allow
             * for a strong inheritance safety net but this is not required.
             */
            'addthis-bookmark' => 'FontAwesome4:bookmark-o',
            'barcode' => 'FontAwesome4:barcode',
            'browzine-issue' => 'Alias:format-serial',
            'browzine-pdf' => 'FontAwesome4:file-pdf-o',
            'browzine-retraction' => 'FontAwesome4:exclamation',
            'cart' => 'FontAwesome4:suitcase',
            'cart-add' => 'FontAwesome4:plus',
            'cart-empty' => 'FontAwesome4:times',
            'cart-remove' => 'FontAwesome4:minus-circle',
            'cite' => 'FontAwesome4:asterisk',
            'cites' => 'FontAwesome4:asterisk',
            'cited-by' => 'FontAwesome4:asterisk',
            'collapse' => 'Collapse:_', // uses the icons below
            'collapse-close' => 'FontAwesome4:chevron-up',
            'collapse-open' => 'FontAwesome4:chevron-down',
            'cover-replacement' => 'FontAwesome4:question',
            'currency-eur' => 'FontAwesome4:eur',
            'currency-gbp' => 'FontAwesome4:gbp',
            'currency-inr' => 'FontAwesome4:inr',
            'currency-jpy' => 'FontAwesome4:jpy',
            'currency-krw' => 'FontAwesome4:krw',
            'currency-rmb' => 'FontAwesome4:rmb',
            'currency-rub' => 'FontAwesome4:rub',
            'currency-try' => 'FontAwesome4:try',
            'currency-usd' => 'FontAwesome4:usd',
            'currency-won' => 'FontAwesome4:won',
            'currency-yen' => 'FontAwesome4:yen',
            'dropdown-caret' => 'FontAwesome4:caret-down',
            'export' => 'FontAwesome4:external-link',
            'external-link' => 'FontAwesome4:link',
            'facet-applied' => 'FontAwesome4:check',
            'facet-checked' => 'FontAwesome4:check-square-o',
            'facet-collapse' => 'FontAwesome4:caret-down',
            'facet-exclude' => 'FontAwesome4:times',
            'facet-expand' => 'FontAwesome4:caret-right',
            'facet-noncollapsible' => 'FontAwesome4:none',
            'facet-unchecked' => 'FontAwesome4:square-o',
            'feedback' => 'FontAwesome4:envelope',
            'format-atlas' => 'FontAwesome4:compass',
            'format-book' => 'FontAwesome4:book',
            'format-braille' => 'FontAwesome4:hand-o-up',
            'format-cdrom' => 'FontAwesome4:laptop',
            'format-chart' => 'FontAwesome4:signal',
            'format-chipcartridge' => 'FontAwesome4:laptop',
            'format-collage' => 'FontAwesome4:picture-o',
            'format-default' => 'FontAwesome4:book',
            'format-disccartridge' => 'FontAwesome4:laptop',
            'format-drawing' => 'FontAwesome4:picture-o',
            'format-ebook' => 'FontAwesome4:file-text-o',
            'format-electronic' => 'FontAwesome4:file-archive-o',
            'format-file' => 'FontAwesome4:file-o',
            'format-filmstrip' => 'FontAwesome4:film',
            'format-flashcard' => 'FontAwesome4:bolt',
            'format-floppydisk' => 'FontAwesome4:save',
            'format-folder' => 'FontAwesome4:folder',
            'format-globe' => 'FontAwesome4:globe',
            'format-journal' => 'FontAwesome4:file-text-o',
            'format-kit' => 'FontAwesome4:briefcase',
            'format-manuscript' => 'FontAwesome4:file-text-o',
            'format-map' => 'FontAwesome4:compass',
            'format-microfilm' => 'FontAwesome4:film',
            'format-motionpicture' => 'FontAwesome4:video-camera',
            'format-musicalscore' => 'FontAwesome4:music',
            'format-musicrecording' => 'FontAwesome4:music',
            'format-newspaper' => 'FontAwesome4:file-text-o',
            'format-online' => 'FontAwesome4:laptop',
            'format-painting' => 'FontAwesome4:picture-o',
            'format-photo' => 'FontAwesome4:picture-o',
            'format-photonegative' => 'FontAwesome4:picture-o',
            'format-physicalobject' => 'FontAwesome4:archive',
            'format-print' => 'FontAwesome4:picture-o',
            'format-sensorimage' => 'FontAwesome4:picture-o',
            'format-serial' => 'FontAwesome4:file-text-o',
            'format-slide' => 'FontAwesome4:film',
            'format-software' => 'FontAwesome4:laptop',
            'format-soundcassette' => 'FontAwesome4:headphones',
            'format-sounddisc' => 'FontAwesome4:laptop',
            'format-soundrecording' => 'FontAwesome4:headphones',
            'format-tapecartridge' => 'FontAwesome4:laptop',
            'format-tapecassette' => 'FontAwesome4:headphones',
            'format-tapereel' => 'FontAwesome4:film',
            'format-transparency' => 'FontAwesome4:film',
            'format-unknown' => 'FontAwesome4:question',
            'format-video' => 'FontAwesome4:video-camera',
            'format-videocartridge' => 'FontAwesome4:video-camera',
            'format-videocassette' => 'FontAwesome4:video-camera',
            'format-videodisc' => 'FontAwesome4:laptop',
            'format-videoreel' => 'FontAwesome4:video-camera',
            'hierarchy-collapse' => 'Alias:facet-collapse',
            'hierarchy-collection' => 'FontAwesome4:folder-open-o',
            'hierarchy-expand' => 'Alias:facet-expand',
            'hierarchy-noncollapsible' => 'Alias:facet-noncollapsible',
            'hierarchy-record' => 'FontAwesome4:file-o',
            'hierarchy-tree' => 'FontAwesome4:sitemap',
            'lightbox-close' => 'FontAwesome4:times',
            'more' => 'FontAwesome4:chevron-circle-right',
            'more-rtl' => 'FontAwesome4:chevron-circle-left',
            'my-account' => 'FontAwesome4:user-circle-o',
            'my-account-notification' => 'Alias:notification',
            'my-account-warning' => 'Alias:warning',
            'notification' => 'FontAwesome4:bell',
            'offcanvas-hide-left' => 'FontAwesome4:angle-right',
            'offcanvas-hide-right' => 'FontAwesome4:angle-left',
            'offcanvas-show-left' => 'FontAwesome4:angle-double-left',
            'offcanvas-show-right' => 'FontAwesome4:angle-double-right',
            'options' => 'FontAwesome4:gear',
            'overdrive' => 'FontAwesome4:download',
            'overdrive-cancel-hold' => 'Alias:ui-cancel',
            'overdrive-checkout' => 'FontAwesome4:arrow-left',
            'overdrive-checkout-rtl' => 'FontAwesome4:arrow-right',
            'overdrive-download' => 'FontAwesome4:download',
            'overdrive-edit-hold' => 'Alias:ui-edit',
            'overdrive-edit-hold-suspension' => 'FontAwesome4:calendar',
            'overdrive-help' => 'FontAwesome4:question-circle',
            'overdrive-place-hold' => 'Alias:place-hold',
            'overdrive-return' => 'FontAwesome4:undo',
            'overdrive-return-rtl' => 'FontAwesome4:undo',
            'overdrive-sign-in' => 'FontAwesome4:sign-in',
            'overdrive-success' => 'FontAwesome4:check',
            'overdrive-suspend-hold' => 'Alias:place-hold',
            'overdrive-warning' => 'Alias:warning',
            'page-first' => 'FontAwesome4:angle-double-left',
            'page-first-rtl' => 'FontAwesome4:angle-double-right',
            'page-last' => 'FontAwesome4:angle-double-right',
            'page-last-rtl' => 'FontAwesome4:angle-double-left',
            'page-next' => 'FontAwesome4:angle-right',
            'page-next-rtl' => 'FontAwesome4:angle-left',
            'page-prev' => 'FontAwesome4:angle-left',
            'page-prev-rtl' => 'FontAwesome4:angle-right',
            'place-hold' => 'FontAwesome4:flag',
            'place-ill-request' => 'FontAwesome4:exchange',
            'place-recall' => 'FontAwesome4:flag',
            'place-storage-retrieval' => 'FontAwesome4:truck',
            'print' => 'FontAwesome4:print',
            'profile' => 'FontAwesome4:user',
            'profile-card-delete' => 'Alias:ui-delete',
            'profile-card-edit' => 'Alias:ui-edit',
            'profile-change-password' => 'FontAwesome4:key',
            'profile-delete' => 'Alias:ui-delete',
            'profile-edit' => 'Alias:ui-edit',
            'profile-email' => 'FontAwesome4:envelope',
            'profile-sms' => 'FontAwesome4:phone',
            'qrcode' => 'FontAwesome4:qrcode',
            'rating-half' => 'FontAwesome4:star-half',
            'rating-full' => 'FontAwesome4:star',
            'search' => 'FontAwesome4:search',
            'search-delete' => 'Alias:ui-delete',
            'search-filter-remove' => 'FontAwesome4:times',
            'search-rss' => 'FontAwesome4:rss',
            'search-save' => 'Alias:ui-save',
            'search-schedule-alert' => 'FontAwesome4:exclamation-circle',
            'send-email' => 'FontAwesome4:envelope',
            'send-sms' => 'FontAwesome4:phone',
            'sign-in' => 'FontAwesome4:sign-in',
            'sign-out' => 'FontAwesome4:sign-out',
            'spinner' => 'FontAwesome4:spinner:icon--spin',
            'status-available' => 'FontAwesome4:check',
            'status-pending' => 'FontAwesome4:clock-o',
            'status-ready' => 'FontAwesome4:bell',
            'status-unavailable' => 'FontAwesome4:times',
            'status-unknown' => 'FontAwesome4:circle',
            'tag-add' => 'Alias:ui-add',
            'tag-remove' => 'Alias:ui-remove',
            'tree-context' => 'FontAwesome4:sitemap',
            'truncate-less' => 'FontAwesome4:arrow-up',
            'truncate-more' => 'FontAwesome4:arrow-down',
            'ui-add' => 'FontAwesome4:plus-circle',
            'ui-cancel' => 'FontAwesome4:ban',
            'ui-close' => 'FontAwesome4:times',
            'ui-delete' => 'FontAwesome4:trash-o',
            'ui-dots-menu' => 'FontAwesome4:ellipsis-h',
            'ui-edit' => 'FontAwesome4:edit',
            'ui-failure' => 'FontAwesome4:times',
            'ui-menu' => 'FontAwesome4:bars',
            'ui-remove' => 'FontAwesome4:times',
            'ui-reset-search' => 'Alias:ui-remove',
            'ui-save' => 'FontAwesome4:floppy-o',
            'ui-success' => 'FontAwesome4:check',
            'user-checked-out' => 'FontAwesome4:book',
            'user-favorites' => 'FontAwesome4:star',
            'user-holds' => 'FontAwesome4:flag',
            'user-ill-requests' => 'FontAwesome4:exchange',
            'user-list' => 'FontAwesome4:list',
            'user-list-add' => 'FontAwesome4:bookmark-o',
            'user-list-delete' => 'Alias:ui-delete',
            'user-list-edit' => 'Alias:ui-edit',
            'user-list-entry-edit' => 'Alias:ui-edit',
            'user-list-remove' => 'Alias:ui-remove',
            'user-loan-history' => 'FontAwesome4:history',
            'user-public-list-indicator' => 'FontAwesome4:globe',
            'user-storage-retrievals' => 'FontAwesome4:archive',
            'view-grid' => 'FontAwesome4:th',
            'view-list' => 'FontAwesome4:list',
            'view-visual' => 'FontAwesome4:th-large',
            'warning' => 'FontAwesome4:exclamation-triangle',
        ],
    ],
];
