<?php
return [
    'icons' => [
        'defaultSet' => 'FontAwesome4',
        'sets' => [
            /**
             * Define icon sets here.
             *
             * All sets need:
             * - 'template': which template the icon renders with
             * - 'src': the location of the relevant resource (font, css, images)
             * - 'prefix': prefix to place before each icon name for convenience
             *             (ie. fa fa- for FontAwesome, default "")
             */
            'FontAwesome4' => [
                'template' => 'font',
                'prefix' => 'fa fa-',
                'src' => 'vendor/font-awesome-4.7.0/css/font-awesome.min.css',
            ],
        ],
        'aliases' => [
            /**
             * Icons can be assigned or overridden here
             *
             * Format: 'icon' => [set:]icon[:extra_classes]
             * Icons assigned without set will use the defaultSet.
             * In order to specify extra CSS classes, you must also specify a set.
             *
             * All of the items below have been specified with FontAwesome to allow
             * for a strong inheritance safety net but this is not required.
             */
            'addthis-bookmark' => 'bookmark-o',
            'barcode' => 'barcode',
            'browzine-issue' => 'Alias:format-serial',
            'browzine-pdf' => 'file-pdf-o',
            'browzine-retraction' => 'exclamation',
            'cart' => 'suitcase',
            'cart-add' => 'plus',
            'cart-empty' => 'times',
            'cart-remove' => 'minus-circle',
            'cite' => 'asterisk',
            'cites' => 'asterisk',
            'cited-by' => 'asterisk',
            'collapse' => 'Collapse:_', // uses the icons below
            'collapse-close' => 'chevron-up',
            'collapse-open' => 'chevron-down',
            'cover-replacement' => 'question',
            'currency-eur' => 'eur',
            'currency-gbp' => 'gbp',
            'currency-inr' => 'inr',
            'currency-jpy' => 'jpy',
            'currency-krw' => 'krw',
            'currency-rmb' => 'rmb',
            'currency-rub' => 'rub',
            'currency-try' => 'try',
            'currency-usd' => 'usd',
            'currency-won' => 'won',
            'currency-yen' => 'yen',
            'dropdown-caret' => 'caret-down',
            'export' => 'external-link',
            'external-link' => 'link',
            'facet-applied' => 'check',
            'facet-checked' => 'check-square-o',
            'facet-collapse' => 'caret-down',
            'facet-exclude' => 'times',
            'facet-expand' => 'caret-right',
            'facet-noncollapsible' => 'none',
            'facet-unchecked' => 'square-o',
            'feedback' => 'envelope',
            'format-atlas' => 'compass',
            'format-book' => 'book',
            'format-braille' => 'hand-o-up',
            'format-cdrom' => 'laptop',
            'format-chart' => 'signal',
            'format-chipcartridge' => 'laptop',
            'format-collage' => 'picture-o',
            'format-default' => 'book',
            'format-disccartridge' => 'laptop',
            'format-drawing' => 'picture-o',
            'format-ebook' => 'file-text-o',
            'format-electronic' => 'file-archive-o',
            'format-file' => 'file-o',
            'format-filmstrip' => 'film',
            'format-flashcard' => 'bolt',
            'format-floppydisk' => 'save',
            'format-folder' => 'folder',
            'format-globe' => 'globe',
            'format-journal' => 'file-text-o',
            'format-kit' => 'briefcase',
            'format-manuscript' => 'file-text-o',
            'format-map' => 'compass',
            'format-microfilm' => 'film',
            'format-motionpicture' => 'video-camera',
            'format-musicalscore' => 'music',
            'format-musicrecording' => 'music',
            'format-newspaper' => 'file-text-o',
            'format-online' => 'laptop',
            'format-painting' => 'picture-o',
            'format-photo' => 'picture-o',
            'format-photonegative' => 'picture-o',
            'format-physicalobject' => 'archive',
            'format-print' => 'picture-o',
            'format-sensorimage' => 'picture-o',
            'format-serial' => 'file-text-o',
            'format-slide' => 'film',
            'format-software' => 'laptop',
            'format-soundcassette' => 'headphones',
            'format-sounddisc' => 'laptop',
            'format-soundrecording' => 'headphones',
            'format-tapecartridge' => 'laptop',
            'format-tapecassette' => 'headphones',
            'format-tapereel' => 'film',
            'format-transparency' => 'film',
            'format-unknown' => 'question',
            'format-video' => 'video-camera',
            'format-videocartridge' => 'video-camera',
            'format-videocassette' => 'video-camera',
            'format-videodisc' => 'laptop',
            'format-videoreel' => 'video-camera',
            'hierarchy-collapse' => 'Alias:facet-collapse',
            'hierarchy-collection' => 'folder-open-o',
            'hierarchy-expand' => 'Alias:facet-expand',
            'hierarchy-noncollapsible' => 'Alias:facet-noncollapsible',
            'hierarchy-record' => 'file-o',
            'hierarchy-tree' => 'sitemap',
            'lightbox-close' => 'times',
            'more' => 'chevron-circle-right',
            'more-rtl' => 'chevron-circle-left',
            'my-account' => 'user-circle-o',
            'my-account-notification' => 'Alias:notification',
            'my-account-warning' => 'Alias:warning',
            'notification' => 'bell',
            'offcanvas-hide-left' => 'angle-right',
            'offcanvas-hide-right' => 'angle-left',
            'offcanvas-show-left' => 'angle-double-left',
            'offcanvas-show-right' => 'angle-double-right',
            'options' => 'gear',
            'overdrive' => 'download',
            'overdrive-cancel-hold' => 'Alias:ui-cancel',
            'overdrive-checkout' => 'arrow-left',
            'overdrive-checkout-rtl' => 'arrow-right',
            'overdrive-download' => 'download',
            'overdrive-edit-hold' => 'Alias:ui-edit',
            'overdrive-edit-hold-suspension' => 'calendar',
            'overdrive-help' => 'question-circle',
            'overdrive-place-hold' => 'Alias:place-hold',
            'overdrive-return' => 'undo',
            'overdrive-return-rtl' => 'undo',
            'overdrive-sign-in' => 'sign-in',
            'overdrive-success' => 'check',
            'overdrive-suspend-hold' => 'Alias:place-hold',
            'overdrive-warning' => 'Alias:warning',
            'page-first' => 'angle-double-left',
            'page-first-rtl' => 'angle-double-right',
            'page-last' => 'angle-double-right',
            'page-last-rtl' => 'angle-double-left',
            'page-next' => 'angle-right',
            'page-next-rtl' => 'angle-left',
            'page-prev' => 'angle-left',
            'page-prev-rtl' => 'angle-right',
            'place-hold' => 'flag',
            'place-ill-request' => 'exchange',
            'place-recall' => 'flag',
            'place-storage-retrieval' => 'truck',
            'print' => 'print',
            'profile' => 'user',
            'profile-card-delete' => 'Alias:ui-delete',
            'profile-card-edit' => 'Alias:ui-edit',
            'profile-change-password' => 'key',
            'profile-delete' => 'Alias:ui-delete',
            'profile-edit' => 'Alias:ui-edit',
            'profile-email' => 'envelope',
            'profile-sms' => 'phone',
            'qrcode' => 'qrcode',
            'rating-half' => 'star-half',
            'rating-full' => 'star',
            'search' => 'search',
            'search-delete' => 'Alias:ui-delete',
            'search-filter-remove' => 'times',
            'search-rss' => 'rss',
            'search-save' => 'Alias:ui-save',
            'search-schedule-alert' => 'exclamation-circle',
            'send-email' => 'envelope',
            'send-sms' => 'phone',
            'sign-in' => 'sign-in',
            'sign-out' => 'sign-out',
            'spinner' => 'spinner:icon--spin',
            'status-available' => 'check',
            'status-pending' => 'clock-o',
            'status-ready' => 'bell',
            'status-unavailable' => 'times',
            'status-unknown' => 'circle',
            'tag-add' => 'Alias:ui-add',
            'tag-remove' => 'Alias:ui-remove',
            'tree-context' => 'sitemap',
            'truncate-less' => 'arrow-up',
            'truncate-more' => 'arrow-down',
            'ui-add' => 'plus-circle',
            'ui-cancel' => 'ban',
            'ui-close' => 'times',
            'ui-delete' => 'trash-o',
            'ui-dots-menu' => 'ellipsis-h',
            'ui-edit' => 'edit',
            'ui-failure' => 'times',
            'ui-menu' => 'bars',
            'ui-remove' => 'times',
            'ui-reset-search' => 'Alias:ui-remove',
            'ui-save' => 'floppy-o',
            'ui-success' => 'check',
            'user-checked-out' => 'book',
            'user-favorites' => 'star',
            'user-holds' => 'flag',
            'user-ill-requests' => 'exchange',
            'user-list' => 'list',
            'user-list-add' => 'bookmark-o',
            'user-list-delete' => 'Alias:ui-delete',
            'user-list-edit' => 'Alias:ui-edit',
            'user-list-entry-edit' => 'Alias:ui-edit',
            'user-list-remove' => 'Alias:ui-remove',
            'user-loan-history' => 'history',
            'user-public-list-indicator' => 'globe',
            'user-storage-retrievals' => 'archive',
            'view-grid' => 'th',
            'view-list' => 'list',
            'view-visual' => 'th-large',
            'warning' => 'exclamation-triangle',
        ],
    ],
];
