<?
    // Hide the total result count -- because of limitations in the way facet
    // paging works, we can't actually determine an accurate total count.  (Note
    // that this setting simply modifies the behavior of search/results.phtml below).
    $this->skipTotalCount = true;

    // Hide cart controls; they don't make sense in this context:
    $this->hideCartControls = true;

    // Load standard settings from the default search results screen:
    echo $this->render('search/results.phtml');

    // Override some details...

    // Set up page title:
    $this->headTitle($this->translate('Author Browse'));

    // Set up empty search box:
    $this->layout()->searchbox = $this->render('search/searchbox.phtml');

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->translate('Author Results for') . ' ' . $this->results->getDisplayQuery() . '</em>';
?>