<? $editions = $this->related->getResults(); if (!empty($editions)): ?>
  <div class="sidegroup">
    <h4><?=$this->transEsc('Other Editions')?></h4>
    <ul class="similar">
      <? foreach ($editions as $data): ?>
        <li>
          <? $formats = $data->getFormats(); if (count($formats) > 0): ?>
            <span class="<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>">
          <? else: ?>
            <span>
          <? endif; ?>
          <a href="<?=$this->recordLink()->getUrl($data)?>"><?=$this->escape($data->getTitle())?></a>
          </span>
          <? $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
            <br/><?=$this->transEsc('By')?>: <?=$this->escape($author);?>
          <? endif; ?>
          <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
            <?=$this->transEsc('Published')?>: (<?=$this->escape($pubDates[0])?>)
          <? endif; ?>
        </li>
      <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>