<?php
$ilsStatusScript = <<<JS
$(document).ready(function() {
  $.ajax({
      dataType: 'json',
      method: 'GET',
      data: {'offlineModeMsg':'ils_offline_home_message'},
      url: VuFind.path + '/AJAX/JSON?method=getIlsStatus',
      success: function(response) {
          $('{$target}').prepend(response.data.html);
      }
  });
});
JS;
echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $ilsStatusScript, 'SET');
?>
