<?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
  <nav class="bulkActionButtons">
    <div class="bulk-checkbox">
      <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/>
      <label for="<?=$this->idPrefix?>addFormCheckboxSelectAll">
        <?=$this->transEsc('select_page')?>
        &#124; <?=$this->transEsc('with_selected')?>:
      </label>
    </div>
    <ul class="action-toolbar">
      <?php if (isset($this->showBulkOptions) && $this->showBulkOptions): ?>
        <li><input id="ribbon-email" class="toolbar-btn" type="submit" name="email" title="<?=$this->transEsc('bookbag_email_selected')?>" value="<?=$this->transEsc('Email')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/></li>
        <?php $exportOptions = $this->export()->getActiveFormats('bulk'); if (count($exportOptions) > 0): ?>
          <li><input id="ribbon-export" class="toolbar-btn" type="submit" name="export" title="<?=$this->transEsc('bookbag_export_selected')?>" value="<?=$this->transEsc('Export')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/></li>
        <?php endif; ?>
        <li><input id="ribbon-print" class="toolbar-btn" type="submit" name="print" title="<?=$this->transEsc('bookbag_print_selected')?>" value="<?=$this->transEsc('Print')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/></li>
        <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
          <li><input id="ribbon-save" class="toolbar-btn" type="submit" name="saveCart" title="<?=$this->transEsc('bookbag_save_selected')?>" value="<?=$this->transEsc('Save')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/></li>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (isset($this->showCartControls) && $this->showCartControls): ?>
        <li><input id="<?=$this->idPrefix?>updateCart" type="submit" class="toolbar-btn" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"<?php if ($this->formAttr): ?> form="<?=$this->escapeHtmlAttr($this->formAttr) ?>"<?php endif; ?>/></li>
      <?php endif; ?>
    </ul>
  </nav>
<?php endif; ?>
