<? if(!isset($this->hideCartControls) || !$this->hideCartControls): ?>
  <div class="bulkActionButtons hidden-print">
    <label class="checkbox">
      <input type="checkbox" class="checkbox-select-all" name="selectAll" id="<?=$this->idPrefix?>addFormCheckboxSelectAll"/> <?=$this->transEsc('select_page')?>
        | <?=$this->transEsc('with_selected')?>:
    </label>
    <input id="ribbon-email" class="btn btn-default modal-link" type="submit" name="email" title="<?=$this->transEsc('bookbag_email_selected')?>" value="<?=$this->transEsc('Email')?>"/>
    <? $exportOptions = $this->export()->getBulkOptions(); if (count($exportOptions) > 0): ?>
      <input id="ribbon-export" class="btn btn-default modal-link" type="submit" name="export" title="<?=$this->transEsc('bookbag_export_selected')?>" value="<?=$this->transEsc('Export')?>"/>
    <? endif; ?>
    <input id="ribbon-print" class="btn btn-default modal-link" type="submit" name="print" title="<?=$this->transEsc('bookbag_print_selected')?>" value="<?=$this->transEsc('Print')?>"/>
    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <input id="ribbon-save" class="btn btn-default modal-link" type="submit" name="saveCart" title="<?=$this->transEsc('bookbag_save_selected')?>" value="<?=$this->transEsc('Save')?>"/>
    <? endif; ?>
    <? if ($this->cart()->isActive()): ?>
      <input id="<?=$this->idPrefix?>updateCart" type="submit" class="btn btn-default" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
    <? endif; ?>
  </div>
<? endif; ?>