<?
  // Set page title.
  $this->headTitle($this->translate('Email this Search'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->transEsc('Email this Search') . '</li>';
?>
<?=$this->flashmessages()?>
<form class="form-horizontal" action="" method="post"  name="emailSearch">
  <input type="hidden" name="url" value="<?=$this->escapeHtmlAttr($this->url)?>" />
  <div class="form-group">
    <label class="col-sm-3 control-label" for="email_to"><?=$this->transEsc('To')?>:</label>
    <div class="col-sm-9">
      <input class="form-control" id="email_to" type="email" name="to" value="<?=isset($this->to) ? $this->to : ''?>"/>
    </div>
  </div>
  <? if (!$this->disableFrom): ?>
    <div class="form-group">
      <label class="col-sm-3 control-label" for="email_from"><?=$this->transEsc('From')?>:</label>
      <div class="col-sm-9">
        <input class="form-control" id="email_from" type="email" name="from" value="<?=isset($this->from) ? $this->from : ''?>"/>
      </div>
    </div>
  <? endif; ?>
  <div class="form-group">
    <label class="col-sm-3 control-label" for="email_message"><?=$this->transEsc('Message')?>:</label>
    <div class="col-sm-9">
      <textarea class="form-control" id="email_message" name="message" rows="3"><?=isset($this->message) ? $this->message : ''?></textarea>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-9 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Send Email')?>"/>
    </div>
  </div>
</form>
