<?php
  $options = $this->results->getParams()->getOptions();
  $facetLightbox = $options->getFacetListAction();
  $facetLightboxParams = http_build_query(
      [
          'facet' => $this->facet,
          'facetop' => $this->operator,
          'facetexclude' => $this->exclude,
      ],
      '',
      '&amp;'
  );
  if (empty($this->sortOptions)) {
    $this->sort = 'default';
    $this->sortOptions = [ 'default' => 'default' ];
  }
  $urlBase = $this->url($facetLightbox) . $results->getUrlQuery()->getParams() . "&amp;$facetLightboxParams";
  $searchAction = $this->url($options->getSearchAction());
  if (!empty($this->baseUriExtra)) {
    $searchAction .= urlencode($this->baseUriExtra);
    $urlBase .= '&amp;baseUriExtra=' . urlencode($this->baseUriExtra);
  }
  $this->headTitle($this->translate('facet_list_for', ['%%field%%' => $this->facetLabel]));
?>
<h2><?=$this->transEsc($this->facetLabel) ?></h2>
<?php if (count($this->sortOptions) > 1): ?>
  <div class="full-facet-sort-options">
    <label><?=$this->translate('Sort') ?></label>
    <div class="btn-group">
      <?php foreach ($this->sortOptions as $key => $sort): ?>
        <a href="<?=$urlBase . '&amp;facetpage=1&amp;facetsort=' . urlencode($key) ?>" class="btn btn-default js-facet-sort<?php if($this->sort == $key): ?> active<?php endif; ?>" data-sort="<?=$key ?>"><?=$this->translate($sort) ?></a>
      <?php endforeach; ?>
    </div>
  </div>
<?php endif; ?>

<!-- Hopefully we can find a better way for passthrough of these variables -->
<?php if (method_exists($this->results->getParams(), 'setFacetContains')): ?>
  <input class="ajax_param" data-name="contains" placeholder="<?=$this->transEscAttr('Filter')?>" class="form-control" type="text">
<?php endif; ?>
<input class="ajax_param" data-name="facet" type="hidden" value="<?=$this->facet?>">
<input class="ajax_param" data-name="exclude" type="hidden" value="<?=$this->exclude?>">
<input class="ajax_param" data-name="operator" type="hidden" value="<?=$this->operator?>">
<input class="ajax_param" data-name="page" type="hidden" value="<?=$this->page?>">
<input class="ajax_param" data-name="sort" type="hidden" value="<?=$this->sort?>">
<input class="ajax_param" data-name="searchAction" type="hidden" value="<?=$searchAction?>">
<input class="ajax_param" data-name="urlBase" type="hidden" value="<?=$urlBase?>">


<div id="facet-info-result" class="lightbox-scroll full-facets">
  <?php foreach ($this->sortOptions as $key => $sort): ?>
    <?php $active = $this->sort == $key; ?>
    <div class="full-facet-list facet-group<?php if(!$active): ?> hidden<?php endif; ?>" id="facet-list-<?=$this->escapeHtmlAttr($key) ?>">
      <!-- The content of this list will be generated dynamically, see facet-list-content.phtml -->
    </div>
  <?php endforeach; ?>
</div>
<button class="btn btn-default lightbox-only" data-dismiss="modal"><?=$this->translate('close') ?></button>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '(typeof VuFind.lightbox_facets !== "undefined") && VuFind.lightbox_facets.setup();', 'SET'); ?>

<?php
    // Set up ajax script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('facet_list.js');

    $js = <<<JS
        getFacetListContent();

        if ($.isReady) {
            setupFacetList();
        } else {
            $(document).ready(function() {
                setupFacetList();
            });
        }
        JS;

    echo $this->inlineScript()->appendScript($js);
?>
