<?php
  $options = $this->results->getParams()->getOptions();
  $facetLightbox = $options->getFacetListAction();
  $facetLightboxParams = http_build_query(
      [
          'facet' => $this->facet,
          'facetop' => $this->operator,
          'facetexclude' => $this->exclude,
      ],
      '',
      '&amp;'
  );
  if (empty($this->sortOptions)) {
    $this->sort = 'default';
    $this->sortOptions = [ 'default' => 'default' ];
  }
  $urlBase = $this->url($facetLightbox) . $results->getUrlQuery()->getParams() . "&amp;$facetLightboxParams";
  $searchAction = $this->url($options->getSearchAction());
  if (!empty($this->baseUriExtra)) {
    $searchAction .= urlencode($this->baseUriExtra);
    $urlBase .= '&amp;baseUriExtra=' . urlencode($this->baseUriExtra);
  }
  $this->headTitle($this->translate('facet_list_for', ['%%field%%' => $this->facetLabel]));
?>
<h2><?=$this->transEsc($this->facetLabel) ?></h2>
<?php if (count($this->sortOptions) > 1): ?>
  <div class="full-facet-sort-options">
    <label><?=$this->translate('Sort') ?></label>
    <div class="btn-group">
      <?php foreach ($this->sortOptions as $key => $sort): ?>
        <a href="<?=$urlBase . '&amp;facetpage=1&amp;facetsort=' . urlencode($key) . '&amp;contains=' . urlencode($contains) ?>" class="btn btn-default js-facet-sort<?php if($this->sort == $key): ?> active<?php endif; ?>" data-sort="<?=$key ?>"><?=$this->translate($sort) ?></a>
      <?php endforeach; ?>
    </div>
  </div>
<?php endif; ?>

<form>
  <?php if (method_exists($this->results->getParams(), 'setFacetContains')): ?>
    <input class="ajax_param" data-name="contains" placeholder="<?=$this->transEscAttr('Filter')?>" class="form-control" type="text" value="<?=htmlspecialchars($this->contains)?>">
  <?php endif; ?>
  <?php $ajaxParams = ['facet' => $this->facet, 'facetexclude' => $this->exclude, 'facetop' => $this->operator, 'facetpage' => $this->page, 'facetsort' => $this->sort, 'urlBase' => $urlBase, 'searchAction' => $searchAction, 'ajaxLightbox' => $this->ajaxLightbox ? intval($this->ajaxLightbox) : intval($this->inLightbox)]; ?>
  <input class="ajax_params" type="hidden" data-params="<?=$this->htmlSafeJsonEncode($ajaxParams)?>">
</form>

<?php $this->headScript()->appendFile('facets.js'); ?>

<div id="facet-info-result" class="lightbox-scroll full-facets">
  <?php foreach ($this->sortOptions as $key => $sort): ?>
    <?php $active = $this->sort == $key; ?>
    <div class="full-facet-list facet-group<?php if(!$active): ?> hidden<?php endif; ?>" id="facet-list-<?=$this->escapeHtmlAttr($key) ?>">
      <!-- The content of this list will later be updated via AJAX, see facet-list-content.phtml -->
      <?php $params = $this->delegateParams; ?>
      <?php $params['urlBase'] = $urlBase; ?>
      <?php $params['searchAction'] = $searchAction; ?>
      <?php $params['inLightbox'] = $this->inLightbox; ?>
      <?=$this->render('search/facet-list-content.phtml', $params) ?>
    </div>
  <?php endforeach; ?>
</div>
<button class="btn btn-default lightbox-only" data-dismiss="modal"><?=$this->translate('close') ?></button>

<?php if ($this->inLightbox || $this->ajaxLightbox): ?>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'VuFind.lightbox_facets.setup();', 'SET')?>
<?php endif; ?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'VuFind.facetList.setup();', 'SET')?>
