<?php
  if (!isset($this->params)) {
    // No current search, use last search in memory
    $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  } else {
    // clone params so that the manipulation doesn't cause trouble e.g. for facets
    $params = clone $this->params;
  }

  $filterList = $params->getFilterList(true);
  $checkboxFilters = $params->getCheckboxFacets();
  $lastSort = $this->searchMemory()->getLastSort($params->getSearchClassId());
  $options = $this->searchOptions($params->getSearchClassId());
  $hasDefaultsApplied = $params->hasDefaultsApplied();
  $filterCount = $this->searchbox()->getFilterCount($checkboxFilters, $filterList);
  $defaultFilterState = $hasDefaultsApplied || $options->getRetainFilterSetting() ? ' checked="checked"' : '';
  $advancedSearch = $params->getSearchType() === 'advanced';
?>
<?php ob_start(); ?>
  <?php foreach ($checkboxFilters as $filter): ?>
    <?php if ($filter['selected']): ?>
      <span class="filter-value">
        <?php
          $removeLink = isset($urlQuery) ? $urlQuery->removeFilter($filter['filter']) : '';
          $desc = $this->translate($filter['desc']);
          $ariaLabel = $this->translate('Remove filter') . ' ' . $this->escapeHtmlAttr($desc);
        ?>
        <?=$desc?>
        <?php if($removeLink): ?>
          <a class="search-filter-remove" aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>"><!--icon from css --></a>
        <?php endif; ?>
      </span>
    <?php endif ?>
  <?php endforeach; ?>

  <?php foreach ($filterList as $field => $data): ?>
    <div class="title-value-pair">
      <span class="filters-title"><?=$this->transEsc($field)?>:</span>
      <?php if (count($data) > 3): ?>
        <div class="search-filter-dropdown dropdown">
          <?php $dropdown = true; ?>
          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $field); ?>
          <button id="dropdown-toggle-<?=$safeId?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <?=$this->transEsc('filter_toggle_entries', ['%%count%%' => count($data)])?>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-toggle-<?=$safeId?>">
      <?php else: ?>
        <?php $dropdown = false; ?>
      <?php endif; ?>
      <?php foreach ($data as $index => $value): ?>
        <?php if ($dropdown): ?>
          <li>
        <?php endif; ?>
        <?php
          switch ($value['operator']) {
          case 'NOT':
            $operatorChar = '-';
            $join = $this->transEsc('NOT');
            break;
          case 'OR':
            $operatorChar = '~';
            $join = $this->transEsc('OR');
            break;
          case 'AND':
            $operatorChar = '';
            $join = $this->transEsc('AND');
            break;
          default:
            $operatorChar = $join = '';
          }
          $operatorClass = $this->escapeHtmlAttr(strtolower($value['operator']));
        ?>
        <span class="filters-term filters-<?=$operatorClass?>">
          <?=($index > 0 || 'NOT' === $value['operator']) ? $join : '' ?>
        </span>
        <span class="filter-value filters-<?=$operatorClass?>">
          <span class="text">
            <?=$this->escapeHtml($value['displayText'])?>
          </span>
          <?php if (isset($this->urlQuery)): ?>
            <?php $removeLink = $urlQuery->removeFacet($value['field'], $value['value'], $value['operator'])?>
            <a class="search-filter-remove" aria-label="<?=$this->translate('Remove filter') ?>" href="<?=$removeLink?>"><!--icon from css --></a>
          <?php endif; ?>
        </span>
        <?php if ($dropdown): ?>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>
      <?php if ($dropdown): ?>
          </ul>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php $filters = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?php if ($filterCount > 0): ?>
  <?php // Normal view ?>
  <div class="active-filters hidden-xs">
    <?php if (empty($disableRetainFilterControls)): ?>
      <?php if ($advancedSearch): ?>
        <p class="adv_search_filters"><?=$this->transEsc('adv_search_filters')?>:</p>
      <?php else: ?>
        <div class="checkbox">
          <label>
            <input type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
            <?=$this->transEsc("basic_search_keep_filters")?>
          </label>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <div class="filters">
      <?=$filters ?>
    </div>
    <div class="clearfix"></div>
  </div>
  <?php // Narrow view ?>
  <div class="active-filters visible-xs">
    <div class="filters-toggle-bar">
      <div class="filters-toggle collapsed" data-toggle="collapse" data-target="#active-filters-mobile">
        <?=$this->transEsc('show_filters_html', ['%%count%%' => $filterCount])?>
      </div>
      <?php if (empty($disableRetainFilterControls)): ?>
        <div class="retain-filters">
          <div class="checkbox">
            <label>
              <input type="checkbox"<?=$defaultFilterState?> class="searchFormKeepFilters"/>
              <?=$this->transEsc("basic_search_keep_filters")?>
            </label>
          </div>
        </div>
      <?php endif; ?>
      <div class="clearfix"></div>
    </div>
    <div id="active-filters-mobile" class="filters filters-bar collapse">
      <?=$filters ?>
    </div>
    <div class="clearfix"></div>
  </div>
<?php endif; ?>
