<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
?>
  <div class="searchHomeContent col-sm-12">
    <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
      <div class="alert alert-warning">
        <h2><?=$this->transEsc('ils_offline_title')?></h2>
        <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
        <p><?=$this->transEsc('ils_offline_home_message')?></p>
        <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
        <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
      </div>
    <? endif; ?>
    <div class="well well-lg clearfix">
      <?=$this->render("search/searchbox.phtml")?>
    </div>
  </div>

<? $facetList = is_object($this->results) ? $this->results->getFacetList() : array(); if (isset($facetList) && is_array($facetList)): ?>
</div> <!-- close row from layout.phtml -->
<div class="row">
  <? foreach ($facetList as $field => $details): ?>
    <? $sortedList = $this->sortFacetList($this->results, $field, $details['list'], $basicSearch); ?>
    <div class="<?=$field=='callnumber-first' ? 'col-sm-6' : 'col-sm-3' ?>">
      <p class="lead"><?=$this->transEsc('home_browse') . ' ' . $this->transEsc($details['label'])?></p>
      <div class="row">
        <ul class="list-unstyled <?=$field == "callnumber-first" ? 'col-sm-6' : 'col-sm-12' ?>">
        <? /* Special case: two columns for LC call numbers... */ ?>
        <? if ($field == "callnumber-first"): ?>
          <? $i = 0; foreach ($sortedList as $url => $value): ?>
            <? if (!empty($value)): ?>
              <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
            <? else: $i--; ?>
            <? endif; ?>
            <? if (++$i == 10): ?>
              </ul><ul class="list-unstyled col-sm-6">
            <? endif; ?>
          <? endforeach; ?>
        <? /* Special case: collections */ ?>
        <? elseif ($field == 'hierarchy_top_title'): ?>
          <? $i = 0; foreach ($sortedList as $url => $value): ?>
            <? if (++$i > 10): ?>
              <li><a href="<?=$this->url('collections-home')?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
              <? break; ?>
            <? else: ?>
              <li><a href="<?=$this->url('collections-bytitle')?>?title=<?=urlencode($value)?>"><?=$this->escapeHtml($value)?></a></li>
            <? endif; ?>
          <? endforeach; ?>
        <? else: ?>
          <? $i = 0; foreach ($sortedList as $url => $value): ?>
            <? if (++$i > 10): ?>
              <li><a href="<?=$this->url($advSearch)?>"><strong><?=$this->transEsc("More options")?>...</strong></a></li>
              <? break; ?>
            <? elseif (!empty($value)): ?>
              <li><a href="<?=$url?>"><?=$this->escapeHtml($value)?></a></li>
            <? else: $i--; ?>
            <? endif; ?>
          <? endforeach; ?>
        <? endif; ?>
        </ul>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>