<?
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('New Items') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Find New Items')?></h2>
  <form method="get" action="" class="form-horizontal">
    <div class="form-group">
      <label class="col-sm-3 control-label"><?=$this->transEsc('Range')?>:</label>
      <div class="col-sm-9">
        <? foreach ($this->ranges as $key => $range): ?>
          <div class="radio">
            <label>
              <input type="radio" name="range" id="newitem_range_<?=$this->escapeHtmlAttr($key)?>" value="<?=$this->escapeHtmlAttr($range)?>"<?= ($key == 0) ? ' checked="checked"' : ''?>/>
              <?=($range == 1) ? $this->transEsc('Yesterday') : $this->transEsc('Past') . ' ' . $this->escapeHtml($range) . ' ' . $this->transEsc('Days')?>
            </label>
          </div>
        <? endforeach; ?>
      </div>
    </div>
    <? if (is_array($this->fundList) && !empty($this->fundList)): ?>
      <div class="form-group">
        <label class="col-sm-3 control-label" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
        <div class="col-sm-9">
          <select id="newitem_department" name="department" size="10" class="form-control">
          <? foreach ($this->fundList as $fundId => $fund): ?>
            <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
          <? endforeach; ?>
          </select>
        </div>
      </div>
    <? endif; ?>
    <div class="form-group">
      <div class="col-sm-9 col-sm-offset-3">
        <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Find')?>"/>
      </div>
    </div>
  </form>
</div>
<div class="clear"></div>