<?php
  $classes = array_merge(['page-item'], $this->liClasses ?? []);
  $aAttrs = $this->htmlAttributes([
    'class' => 'page-link',
    'aria-label' => $this->label,
  ]);
  if ($this->page == $this->current) {
    $classes[] = 'active';
    $aAttrs['aria-current'] = 'page';
  }
?>
<li class="<?=implode(' ', $classes)?>">
  <a<?=$aAttrs?> href="<?=$this->results->getUrlQuery()->setPage($this->page)?>">
    <?=$contentHtml?>
  </a>
</li>
