<?
    // Set up page title:
    $this->headTitle($this->translate('Reserves Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Reserves') . '</li>';

    // Convenience variables:
    $reservesLookfor = $this->params->getDisplayQuery();
?>

<div class="row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <h3><?=$this->transEsc('Search For Items on Reserve')?></h3>
    <form class="form-inline" method="get" name="reservesSearchForm">
      <label for="reservesSearchForm_lookfor"><?=$this->transEsc("Your search terms")?></label>
      <input id="reservesSearchForm_lookfor" type="text" name="lookfor" size="40" value="<?=$this->escapeHtmlAttr($reservesLookfor)?>" <?=$this->searchOptions('SolrReserves')->autocompleteEnabled() ? ' class="autocomplete searcher:SolrReserves type:Reserves"' : ''?> />
      <input class="btn btn-default" type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
    </form>
    <script type="text/javascript">$("#reservesSearchForm_lookfor").focus()</script>

    <div class="resulthead">
      <div class="pull-left flip">
        <? if (($recordTotal = $this->results->getResultTotal()) > 0): ?>
          <?=$this->transEsc("Showing")?>
          <strong><?=$this->localizedNumber($this->results->getStartRecord())?></strong> - <strong><?=$this->localizedNumber($this->results->getEndRecord())?></strong>
          <?=$this->transEsc('of')?> <strong><?=$this->localizedNumber($recordTotal)?></strong>
          <?=$this->transEsc('for search')?>: <strong>'<?=$this->escapeHtml($reservesLookfor)?>'</strong>,
        <? endif; ?>
        <? if ($qtime = $this->results->getQuerySpeed()): ?>
          <?=$this->transEsc('query time')?>: <?=$this->localizedNumber($qtime, 2).$this->transEsc('seconds_abbrev')?>
        <? endif; ?>
      </div>

      <div class="pull-right flip">
        <?=$this->render('search/controls/sort.phtml')?>
      </div>
    </div>
    <? if ($recordTotal < 1): ?>
      <p class="error"><?=$this->transEsc('nohit_prefix')?> - <strong><?=$this->escapeHtml($reservesLookfor)?></strong> - <?=$this->transEsc('nohit_suffix')?></p>
      <? if (isset($this->parseError)): ?>
        <p class="error"><?=$this->transEsc('nohit_parse_error')?></p>
      <? endif; ?>
    <? else: ?>
      <table class="table table-striped">
      <tr>
        <th class="department"><?=$this->transEsc('Department')?></th>
        <th class="course"><?=$this->transEsc('Course')?></th>
        <th class="instructor"><?=$this->transEsc('Instructor')?></th>
        <th class="items"><?=$this->transEsc('Items')?></th>
      </tr>
      <? foreach ($this->results->getResults() as $record): ?>
        <?
            $url = $this->currentPath() . $this->escapeHtmlAttr(
                '?inst=' . urlencode($record->getInstructorId())
                . '&course=' . urlencode($record->getCourseId())
                . '&dept=' . urlencode($record->getDepartmentId())
            );
        ?>
        <tr>
          <td class="department"><a href="<?=$url?>"><?=$this->escapeHtml($record->getDepartment())?></a></td>
          <td class="course"><a href="<?=$url?>"><?=$this->escapeHtml($record->getCourse())?></a></td>
          <td class="instructor"><a href="<?=$url?>"><?=$this->escapeHtml($record->getInstructor())?></a></td>
          <td class="items"><?=$this->escapeHtml($record->getItemCount())?></td>
        </tr>
      <? endforeach; ?>
      </table>
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $this->results))?>
    <? endif; ?>
  </div>

  <? /* Narrow Search Options */ ?>
  <div class="<?=$this->layoutClass('sidebar')?>">
    <? foreach ($this->results->getRecommendations('side') as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>
  </div>
  <? /* End Narrow Search Options */ ?>
</div>
