<? $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $this->hiddenFilters); ?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
        <? $block = $this->linkdisplay()->getDisplayBlock('access.'.$tab['id'], $this); ?>
        <? if ($block !== false): ?>
            <?=$block?>
        <? else: ?>
          <li<?=$tab['selected'] ? ' class="active"' : ''?>>
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
          </li>
        <? endif; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
