<? $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $this->hiddenFilters); ?>
<? if (count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs">
    <? foreach ($searchTabs as $tab): ?>
        <? $localBlock = $this->linkdisplay()->showLocalBlock($tab['permission']); ?>
        <? if ($localBlock): ?>
          <li<?=$tab['selected'] ? ' class="active"' : ''?>>
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
          </li>
        <? else: ?>
            <? $block = $this->linkdisplay()->getDisplayBlock($tab['permission']); ?>
            <? if ($block): ?>
                <?=$block?>
            <? endif; ?>
        <? endif; ?>
    <? endforeach; ?>
  </ul>
<? endif; ?>
