<?
$this->headScript()->appendFile('vendor/validator.min.js');

$script = <<<JS
$(document).ready(function() {
  $('#newpassword').validator({
    errors: {
      match: '{$this->escapeJs($this->translate('Passwords do not match'))}',
      minlength: '{$this->escapeJs($this->translate('password_minimum_length',
          array('%%minlength%%' => isset($this->passwordPolicy['minLength']) ? $this->passwordPolicy['minLength'] : 0)))}'
    }
  });
});
JS;
echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
<? if (isset($this->username)): ?>
  <div class="form-group">
    <label class="col-sm-3 control-label"><?=$this->transEsc('Username') ?>:</label>
    <div class="col-sm-9">
      <p class="form-control-static"><?=$this->username ?></p>
    </div>
  </div>
<? endif; ?>
<? if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <div class="form-group">
    <label class="col-sm-3 control-label"><?=$this->transEsc('old_password') ?>:</label>
    <div class="col-sm-9">
      <input type="password" name="oldpwd" class="form-control"/>
      <div class="help-block with-errors"></div>
    </div>
  </div>
<? endif; ?>
<div class="form-group">
  <label class="col-sm-3 control-label"><?=$this->transEsc('new_password') ?>:</label>
  <div class="col-sm-9">
    <input type="password" id="password" name="password" class="form-control" required aria-required="true"<?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '"' : ''?><?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>/>
    <div class="help-block with-errors"></div>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-3 control-label"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <div class="col-sm-9">
    <input type="password" name="password2" class="form-control" required aria-required="true" data-match="#password"/>
    <div class="help-block with-errors"></div>
  </div>
</div>
