<?php $this->headTitle($this->translate('FAQs')); ?>

<h1><?=$this->transEsc('FAQs') ?></h1>

<?php if ($this->auth()->getManager()->supportsRecovery()): ?>
  <p>
    Q: How do I reset my password?<br/>
    A: Go to the login screen and click the "Forgot password" link. Enter either your user name or email address, and you will get an email containing a link to reset your password.
  </p>
<?php endif; ?>
<p>
  Q: Why does the service use cookies?<br/>
  A: Cookies are used to manage sessions, which include selected language, last search, book bag contents, any login information, etc.
</p>
<p>
  Q: What kinds of services have been built on top of VuFind?<br>
  A: See the following video for a quick look:
  <?php if ($this->plugin('cookieConsent')->isEnabled()): ?>
    <div style="width: 560px; height: 315px" class="iframemanager" data-service="youtube" data-id="5q70TokaSrw"></div>
  <?php else: ?>
    <iframe width="560" height="315" src="https://www.youtube.com/embed/5q70TokaSrw" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  <?php endif; ?>
</p>
