<? $list = $this->params->getSortList(); if (!empty($list)): ?>
  <form class="form-inline" action="<?=$this->currentPath()?>" method="get" name="sort" style="display: inline;">
    <?=$this->results->getUrlQuery()->asHiddenFields(array('sort' => '/.*/'));?>
    <label for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu form-control"
      <? $default_sort = $this->params->getOptions()->getDefaultSortByHandler();?>
      <? if ($default_sort != null): ?>
      data-default_sort="<?=$default_sort?>"
      <? endif; ?>
      <?= $this->params->getOptions() instanceof \IxTheo\Search\Solr\Options && $this->params->getQuery() instanceof \VuFindSearch\Query\Query && in_array($this->params->getQuery()->getHandler(), $this->params->getOptions()->getForceDefaultSortSearches()) ? 'disabled' : '' ?>>
      <? foreach ($list as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected']?' selected="selected"':''?>><?=$this->transEsc($sortData['desc'])?></option>
      <? endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </form>
<? endif; ?>
