<?php
  $this->treeContext = 'Collection';
  $this->treePreviewElement = '#tree-preview';

  $previewAttrs = [
    'id' => 'tree-preview',
  ];
  if ($this->tab->hidePreviewInNarrowDisplays()) {
    $previewAttrs['class'] = 'hidden-narrow';
  }
?>

<div class="collection-hierarchytree">
  <div class="tree-panel">
    <?=$this->render('RecordTab/hierarchytree.phtml')?>
  </div>
  <div<?=$this->htmlAttributes($previewAttrs)?>>
    <?php if (($collectionRecord = $this->tab->getActiveRecord()) !== false): ?>
      <?php if ($collectionRecord === null): ?>
        <?=$this->render('collection/collection-record-error.phtml')?>
      <?php else: ?>
        <?=$this->record($collectionRecord)->getCollectionBriefRecord()?>
      <?php endif; ?>
    <?php endif; ?>
  </div>
</div>
