<?php
  $holdings = $this->tab->getHoldings();
  $institutions = (array)($holdings['briefRecords'][0]['institutionHolding']['briefHoldings'] ?? []);
  $formatAddress = function ($holding) {
    $fields = [$holding['institutionName']];
    // Strip country code off state code:
    if (isset($holding['address']['state'])) {
        $stateParts = explode('-', $holding['address']['state']);
        $holding['address']['state'] = array_pop($stateParts);
    }
    foreach (['street1', 'city', 'state', 'postalCode', 'country'] as $field) {
        if (!empty($holding['address'][$field])) {
            $fields[] = $holding['address'][$field];
        }
    }
    return implode(', ', $fields);
  }
?>
<?php if (count($institutions) > 0): ?>
  <h3><?=$this->transEsc('Holdings at Other Libraries')?></h3>
  <ul>
    <?php foreach ($institutions as $holding): ?>
      <li>
        <?=$this->escapeHtml($formatAddress($holding))?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php elseif (isset($holdings['detail'])): ?>
  <p><?=$this->escapeHtml($holdings['detail'])?>
<?php endif; ?>
