<?php

/**
 * Cloudflare Turnstile service.
 *
 * PHP version 8
 *
 * Copyright (C) Villanova University 2024.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2,
 * as published by the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 * @category VuFind
 * @package  RateLimiter
 * @author   Maccabee Levine <msl321@lehigh.edu>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://vufind.org Main Page
 */

namespace VuFind\RateLimiter\Turnstile;

use Laminas\Log\LoggerAwareInterface;
use VuFind\Log\LoggerAwareTrait;
use VuFind\RateLimiter\RateLimiterManager;
use VuFindHttp\HttpServiceAwareInterface;
use VuFindHttp\HttpServiceAwareTrait;

/**
 * Rate limiter manager.
 *
 * @category VuFind
 * @package  Cache
 * @author   Maccabee Levine <msl321@lehigh.edu>
 * @license  http://opensource.org/licenses/gpl-2.0.php GNU General Public License
 * @link     https://vufind.org Main Page
 */
class Turnstile implements HttpServiceAwareInterface, LoggerAwareInterface
{
    use HttpServiceAwareTrait;
    use LoggerAwareTrait;

    /**
     * Constructor
     *
     * @param array              $config             Rate Limiter config
     * @param RateLimiterManager $rateLimiterManager Rate limiter manager
     */
    public function __construct(
        protected array $config,
        protected RateLimiterManager $rateLimiterManager
    ) {
    }

    /**
     * Validate a token against the Turnstile API
     *
     * @param string $token The token generated by the Turnstile widget
     *
     * @return bool Whether validation was successful
     */
    public function validateToken($token)
    {
        // Call the Turnstile verify API to validate the token
        $secretKey = $this->config['Turnstile']['secretKey'];
        $url = $this->config['Turnstile']['verifyUrl'] ??
            'https://challenges.cloudflare.com/turnstile/v0/siteverify';
        $body = [
            'secret' => $secretKey,
            'response' => $token,
        ];
        $response = $this->httpService->post(
            $url,
            json_encode($body),
            'application/json'
        );

        if ($response->isOk()) {
            $responseData = json_decode($response->getBody(), true);
            $success = $responseData['success'];
        } else {
            // Unexpected error.  Treat as a positive result, since it's not the user's fault.
            $this->logWarning('Verification process failed, allowing traffic: '
                . $response->getStatusCode() . $response->getBody());
            $success = true;
        }

        return $success;
    }
}
