<?
$queryHandler = 'AllFields';
if ($results->getParams()->getSearchType() == 'basic') {
    $queryHandler = $results->getParams()->getQuery()->getHandler();
}
$customQueryHandler = $queryHandler != 'AllFields';
if ($this->browse) {
    $customQueryHandler = $customQueryHandler && $queryHandler != $this->defaultBrowseHandler;
}
?>
<? if (!empty($filterList) || $customQueryHandler): ?>
    <div class="list-group filters">
        <? // Finna query handler (type) remove link ?>
        <? if ($customQueryHandler): ?>
            <? $removeLink = $results->getUrlQuery()->setHandler('AllFields'); ?>
            <a class="list-group-item active" href="<?=$removeLink?>">
                <span class="pull-right"><i class="fa fa-times"></i></span>
                <?=$this->transEsc('search_in_field'); ?>:
                <?=$this->transEsc($queryHandler); ?>
            </a>
        <? endif; ?>
        <? foreach ($filterList as $field => $filters): ?>
            <? foreach ($filters as $i => $filter): ?>
                <?
                $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
                if ($index !== false) {
                    unset($collapsedFacets[$index]); // Open if we have a match
                }
                if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
                    $removeLink = $results->getUrlQuery()->replaceTerm($filter['value'], '');
                } else {
                    $removeLink = $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
                }
                if ($filter['displayText'] == '[* TO *]') {
                    $filter['displayText'] = $this->translate('filter_wildcard');
                }
                ?>
                <a class="list-group-item active" href="<?=$removeLink?>">
                    <span class="pull-right"><i class="fa fa-times" aria-hidden="true"></i></span>
                    <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><span class="sr-only"><?=$this->transEsc('Remove filter')?>: </span><?=$this->transEsc($field)?><? if (!empty($filter['displayText'])): ?>: <?=$this->escapeHtml($filter['displayText'])?><? endif; ?>
                </a>
            <? endforeach; ?>
        <? endforeach; ?>
    </div>
<? endif; ?>