<?php
  $pattern = '';
  if (isset($this->passwordPolicy['pattern'])) {
    if ($this->passwordPolicy['pattern'] == 'numeric') {
      $pattern = '\d+';
    } elseif ($this->passwordPolicy['pattern'] == 'alphanumeric') {
      $pattern = '[\da-zA-Z]+';
    } else {
      $pattern = $this->passwordPolicy['pattern'];
    }
  }
?>
<div class="form-group">
  <label class="control-label" for="account_firstname"><?=$this->transEsc('First Name')?>:</label>
  <input id="account_firstname" type="text" name="firstname" value="<?=$this->escapeHtmlAttr($this->request->get('firstname'))?>" class="form-control"/>
</div>
<div class="form-group">
  <label class="control-label" for="account_lastname"><?=$this->transEsc('Last Name')?>:</label>
  <input id="account_lastname" type="text" name="lastname" value="<?=$this->escapeHtmlAttr($this->request->get('lastname'))?>" class="form-control"/>
</div>
<div class="form-group">
  <label class="control-label" for="account_email"><?=$this->transEsc('Email Address')?>:</label>
  <input id="account_email" type="email" name="email" required aria-required="true" value="<?=$this->escapeHtmlAttr($this->request->get('email'))?>" class="form-control"/>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="account_username"><?=$this->transEsc('Desired Username')?>:</label>
  <input id="account_username" type="text" name="username" required aria-required="true" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="account_password"><?=$this->transEsc('Password')?>:</label>
  <input id="account_password" type="password" name="password" required aria-required="true" class="form-control"
    <?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->transEscAttr('password_minimum_length', ['%%minlength%%' => $this->passwordPolicy['minLength']]) . '"' : ''?>
    <?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>
    <?=$pattern ? ' pattern="' . $pattern . '"' : '' ?>
  />
  <?php if ($this->passwordPolicy['hint']): ?>
    <div class="help-block"><?=$this->transEsc($this->passwordPolicy['hint']) ?></div>
  <?php endif; ?>
  <div class="help-block with-errors"></div>
</div>
<div class="form-group">
  <label class="control-label" for="account_password2"><?=$this->transEsc('Password Again')?>:</label>
  <input id="account_password2" type="password" name="password2" required aria-required="true" class="form-control" data-match="#account_password" data-match-error="<?=$this->transEscAttr('Passwords do not match')?>"/>
  <div class="help-block with-errors"></div>
</div>
