<div class="form-group">
  <label class="col-sm-3 control-label"><?=$this->transEsc('recovery_by_username') ?>:</label>
  <div class="col-sm-9 col-md-5">
    <input type="text" name="username" class="form-control"/>
  </div>
</div>
<div class="form-group">
  <label class="col-sm-3 control-label"><?=$this->transEsc('recovery_by_email') ?>:</label>
  <div class="col-sm-9 col-md-5">
    <input type="email" name="email" class="form-control"/>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-9 col-sm-offset-3">
    <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-9 col-sm-offset-3">
  <input class="btn btn-default" name="submit" type="submit" value="<?=$this->transEsc('Recover Account') ?>"/>
</div>