<?php
    $this->headTitle('Deminifier');
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('devtools-home') . '">Development Tools</a>'
      . '<li class="active">Deminifier</li>';
?>

<h1>Deminifier</h1>

<?php if (empty($min)): ?>
  <form method='POST'>
    <div class="form-group">
      <label for="min-text">Minified text:</label>
      <textarea class="form-control" id="min-text" name="min" rows="6"></textarea>
    </div>
    <input class="btn btn-primary" type="submit">
  </form>
<?php else: ?>
  <h3>Minified Object</h3>
  <pre><?php print_r($min) ?></pre>
<?php endif; ?>

<?php if (isset($results)): ?>
  <h3>Results Object</h3>
  <p>Class: <?=$results::class?></p>
<?php endif; ?>

<?php if (isset($query)): ?>
  <h3>Query Object</h3>
  <pre><?php print_r($query) ?></pre>
<?php endif; ?>

<?php if (isset($backendParams) || isset($queryParams)): ?>
  <h3>Backend Parameters</h3>
  <?php if (isset($queryParams)): ?>
    <h4>Query Parameters</h4>
    <pre><?php print_r($queryParams) ?></pre>
  <?php endif; ?>
  <?php if (isset($backendParams)): ?>
    <h4>Non-query Parameters</h4>
    <pre><?php print_r($backendParams) ?></pre>
  <?php endif; ?>
<?php endif; ?>

