<?php
  $liAttrs = ['class' => 'breadcrumb-item'];
  if ($this->active) {
    $liAttrs['class'] .= ' active';
    $liAttrs['aria-current'] = 'page';
  }
  $linkAttrs = ['href' => $this->href];
  if ($this->title !== null) {
    $linkAttrs['title'] = $this->title;
  }
  $aStart = $this->href ? '<a ' . $this->htmlAttributes($linkAttrs) . '>' : '';
  $aEnd = $this->href ? '</a>' : '';
?>
<li<?=$this->htmlAttributes($liAttrs)?>><?=$aStart . $this->escapeHtml($this->text) . $aEnd ?></li>
