<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate('Comments'), active: true);

  $this->assetManager()->appendScriptLink('requests.js');
  $tabs = $this->accountCapabilities()->getUserContentTabs();
  $user = $this->auth()->getUserObject();
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'usercontent']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <?=$this->component('page-title', ['title' => $this->translate('Comments')]);?>
  <ul class="nav nav-tabs" role="tablist">
    <?php foreach ($tabs as $tab => $title): ?>
      <li class="nav-item" role="presentation" id="user-content-<?=$this->escapeHtmlAttr($tab)?>" data-tab="<?=$this->escapeHtmlAttr($tab)?>"><a class="<?='comments' === $tab ? 'active' : ''?> nav-link" href="<?=$this->url($tab . '-' . 'userlist')?>"><?=$this->transEsc($title)?></a></li>
    <?php endforeach; ?>
  </ul>
  <?php if (count($this->comments) !== 0): ?>
    <div><?=$this->transEsc('finna_nickname')?>: <?=$this->userPublicName($user);?></div>
    <nav class="search-header hidden-print">
      <?php
        $abs = $this->comments->getAbsoluteItemNumber($this->comments->getItemCountPerPage());
        $end = min($abs, $this->comments->getTotalItemCount());
        $transParams = [
          '%%start%%' => $this->localizedNumber($this->comments->getAbsoluteItemNumber(1)),
          '%%end%%' => $this->localizedNumber($end),
          '%%total%%' => $this->localizedNumber($this->comments->getTotalItemCount()),
        ];
      ?>
      <div class="search-stats">
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      </div>
      <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
    </nav>
    <form action="<?=$this->url('comments-deletecomments')?>" name="updateForm" id="select_all_comments" method="post">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
      <label>
        <div class="checkbox-container">
          <div class="checkbox">
            <input type="checkbox" name="selectAll" class="checkbox-select-all">
            <?=$this->transEsc('select_all_on_page')?>
          </div>
        </div>
      </label>
      <?=
        $this->component(
            'confirm-button',
            [
                'buttonId' => 'cancelSelected',
                'buttonName' => 'cancelSelected',
                'buttonLabel' => 'delete_selected',
                'header' => 'confirm_usercomment_delete_selected_text',
                'confirmId' => 'confirm_cancel_selected_yes',
                'cancelClass' => 'confirm_cancel_no',
                'ignoreLightbox' => true,
            ]
        )
      ?>
      <table class="usercontent-table table-striped table table-responsive">
        <thead>
          <tr>
            <th></th>
            <th></th>
            <th><?=$this->transEsc('Created')?></th>
            <th><?=$this->transEsc('Title')?></th>
            <th><?=$this->transEsc('Comment')?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->comments as $comment):?>
            <tr>
              <td class="checkbox-col user-account-table-select">
                <div class="checkbox-container result">
                  <div class="checkbox">
                    <label class="record-checkbox">
                      <span class="sr-only"><?=$this->transEsc('Select');?></span>
                      <input class="checkbox-select-item" type="checkbox" name="deleteSelectedcomment[]" value="<?=$this->escapeHtmlAttr(($comment['id']))?>" id="checkbox_comment_<?=$comment['id']?>">
                    </label>
                  </div>
                </div>
              </td>
              <td class="mycomments-table-hidden">
                  <?php if ($comment['finna_visible'] === 0): ?>
                    <?php
                      $tooltipBtn = [
                        'label' => $this->transEsc('comment_hidden'),
                        'aria-label' => $this->transEscAttr('comment_hidden'),
                        'content' => '<h4>' . $this->transEsc('comment_hidden') . '</h4>' . $this->translate('comment_hidden_by_admin_html'),
                      ];
                    ?>
                    <?=$this->component('finna-tooltip-btn', $tooltipBtn)?>
                  <?php endif; ?>
              </td>
              <td data-label="<?=$this->transEscAttr('Created')?>"><?=$this->dateTime()->convertToDisplayDateAndTime('Y-m-d H:i:s', $comment['created'])?></td>
              <td data-label="<?=$this->transEscAttr('Title')?>">
                <?php if (empty($comment['mergedData'])): ?>
                  <a href="<?=$this->url('record', ['id' => $comment['record_id']])?>"><?=$this->escapeHtml($comment['recordTitle'])?></a>
                <?php else: ?>
                  <div>
                    <p><?=$this->escapeHtml($comment['recordTitle'])?></p>
                    <div class="truncate-field other-organisation-links" data-rows="-1" data-label="<?=$this->transEscAttr('show_instances')?>">
                      <?php foreach ($comment['mergedData']['records'] ?? [] as $current): ?>
                        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($current['id'])) ?>" title="<?=$this->transEscAttr("source_{$current['source']}", null, $current['source']) ?>">
                          <?=$this->transEsc("source_{$current['source']}", null, $current['source']) ?>
                        </a>
                        <br>
                      <?php endforeach; ?>
                    </div>
                  </div>
                <?php endif; ?>
              </td>
              <td class="user-comment" data-label="<?=$this->transEscAttr('Comment')?>">
                <?php $truncateSettings = ['rows' => 5]?>
                <div class="user-comment-truncate" data-truncate="<?=$this->htmlSafeJsonEncode($truncateSettings)?>"><?=$this->escapeHtml($comment['comment'] ?? '')?></div>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </form>
  <?php else: ?>
    <?=$this->transEsc('No Comments')?>
  <?php endif; ?>
  <?=$this->paginationControl($this->comments, 'Sliding', 'Helpers/pagination.phtml', ['params' => $this->params])?>
</div>

<?php
  $script = <<<JS
      VuFind.truncate.initTruncate('.user-comment-truncate');
      JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
