<!-- finc: librarycards - home -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * adds VF5 offcanvas reference to myaccount pages
 * uses h1 instead of h2 - #13547
 * table works without further responsiveness code inserted
 * adds id 'myresearch-sidebar' and aria-label 'MyAccountSidebar'; uses section for sidebar #23430
configured in: {}
 */
?>
<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">

  <?php /* finc: adds VF5 offcanvas reference to myaccount pages */ ?>
  <?=$this->render('RecordDriver/DefaultRecord/offcanvas-toggler-myresearch'); ?>

  <?=$this->flashmessages()?>

  <?php /* finc: uses h1 instead of h2 - #13547 */ ?>
  <h1><?=$this->transEsc('Library Cards')?></h1>
  <?php if ($this->libraryCards->count() == 0): ?>
    <div><?=$this->transEsc('You do not have any library cards')?></div>
  <?php else: ?>
    <?php /* finc: this table works without further responsiveness code inserted - CK */ ?>
    <table class="table table-striped table-resp-data">
      <caption class="sr-only"><?=$this->transEsc('Library Cards')?></caption>
    <tr>
      <th><?=$this->transEsc('Library Card Name')?></th>
      <?php if ($this->multipleTargets): ?>
      <th><?=$this->transEsc('login_target')?></th>
      <?php endif; ?>
      <th><?=$this->transEsc('Username')?></th>
      <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->libraryCards as $record): ?>
      <tr>
        <td data-title="<?=$this->transEsc('Library Card Name')?>:"><?=$this->escapeHtml($record['card_name'])?></td>
        <?php $username = $record['cat_username']; if ($this->multipleTargets): ?>
          <?php $target = ''; ?>
          <?php if (strstr($username, '.')): ?>
            <?php [$target, $username] = explode('.', $username, 2); ?>
          <?php endif; ?>
          <td data-title="<?=$this->transEsc('login_target')?>:"><?=$target ? $this->transEsc("source_$target", null, $target) : '&nbsp;' ?></td>
        <?php endif; ?>
      <td data-title="<?=$this->transEsc('Username')?>:"><?=$this->escapeHtml($username)?></td>
        <td>
          <div class="btn-group">
            <a class="btn btn-link" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) ?>" title="<?=$this->transEscAttr('Edit Library Card')?>"><i class="fa fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Edit')?></a>
            <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>">
              <i class="fa fa-trash-o" aria-hidden="true"></i> <?=$this->transEsc('Delete')?>
            </a>
            <ul class="dropdown-menu">
              <li><a href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>&amp;confirm=1" data-clear-account-cache><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
              <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
            </ul>
          </div>
        </td>
      </tr>
    <?php endforeach; ?>
    </table>
  <?php endif; ?>

  <div class="btn-group">
    <?php if ($this->allowConnectingCards): ?>
      <a href="<?=$this->url('librarycards-connectcardlogin') ?>" class="btn btn-link"><i class="fa fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Add a Library Card using login')?></a>
    <?php endif;?>
    <a href="<?=$this->url('editLibraryCard') ?>NEW" class="btn btn-link"><i class="fa fa-edit" aria-hidden="true"></i> <?=$this->transEsc('Add a Library Card')?></a>
  </div>
</div>

<?php /* finc: adds id 'myresearch-sidebar' and aria-label 'MyAccountSidebar'; uses section for sidebar #23430 */ ?>
<section class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" aria-label="<?=$this->transEsc('MyAccountSidebar') ?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'librarycards'])?>
</section>
<!-- finc: librarycards - home - END -->
