<h1>Markdown und Emojis</h1>

<ul class="HelpMenu">
  <li><a href="#markdown">Markdown</a></li>
  <li><a href="#emojis">Emojis</a></li>
</ul>

<dl class="Content">
  <dt><a id="markdown"></a>Markdown</dt>
  <dd>
    <p>
      Markdown ist eine einfache Methode zur Formatierung von Text mithilfe von Symbolen. Sie können Ihrem
      Text Formatierungen hinzufügen, ohne komplizierte Kodierung lernen zu müssen.
      <b>In <a href="https://www.markdownguide.org/basic-syntax/" target="_blank">diesem Markdown Leitfaden</a>
        finden Sie eine ausführliche Erklärung aller Markdown-Funktionen.</b> Im Folgenden finden Sie einige Beispiele.
    </p>
    <p>
      Wenn Sie ein Wort oder einen Satz hervorheben möchten, können Sie es mit Sternchen (*) oder Unterstrichen (_)
      kennzeichnen. Ein Sternchen oder Unterstrich auf jeder Seite macht den Text <i>kursiv</i>, während zwei ihn <b>fett</b> machen.
    </p>
    <pre class="code">
      _kursiver text_
      **fetter text**</pre>
    <p>
      Für Überschriften setzen Sie ein Hashtag (#) vor eine Zeile, um sie zu einer Überschrift zu machen. Je mehr Hashtags Sie verwenden, desto
      kleiner wird die Überschrift. Ein Hashtag ist also eine große Überschrift, während drei Hashtags eine kleine Überschrift sind.
    </p>
    <pre class="code">
      #Überschrift1
      ##Überschrift2
      ###Überschrift3</pre>
    <p>
      Für eine Aufzählung beginnen Sie jede Zeile mit einem Bindestrich (-) oder einem Sternchen (*).
      Wenn Sie eine nummerierte Liste wünschen, beginnen Sie jede Zeile mit einer Zahl, gefolgt von einem Punkt.
    </p>
    <pre class="code">
      1. Erster Eintrag
      2. Zweiter Eintrag
      3. Dritter Eintrag
      4. Vierter Eintrag</pre>
    <p>
      Wenn Sie einen Link zu einer Website herstellen möchten, setzen Sie den anzuzeigenden Text in eckige Klammern ([]), gefolgt von der
      Adresse der Website in Klammern ().
    </p>
    <pre class="code">
      [VuFind&reg;](https://vufind.org)</pre>
  </dd>
  <dt><a id="emojis"></a>Emojis</dt>
  <dd>
    <p>
      Emojis können mit dieser allgemeinen Syntax in den Text eingefügt werden:
    </p>
    <pre class="code">
        :BEZEICHNUUNG:</pre>
    <p>
      Also zum Beispiel:
    </p>
    <pre class="code">
        :smile:
        :+1:
        :heart:</pre>
    <p>
      <b>Eine detaillierte Liste der unterstützten Emojis finden Sie in <a href="https://packagist.org/packages/elgigi/commonmark-emoji#user-content-emoji-list" target="_blank">der commonmark-emoji Dokumentation.</a></b>
    </p>
  </dd>
</dl>

