<h1>Hilfe zu den Suchoperatoren</h1>

<ul class="HelpMenu">
  <li><a href="#Wildcard Searches">Suche mit Platzhaltern</a></li>
  <li><a href="#Fuzzy Searches">Unscharfe Suche</a></li>
  <li><a href="#Proximity Searches">Suche nach ähnlichen Wörtern</a></li>
  <li><a href="#Range Searches">Bereichssuche</a></li>
  <li><a href="#Boosting a Term">Wort gewichten</a></li>
  <li><a href="#Boolean operators">Boolesche Operatoren</a>
    <ul>
      <li><a href="#AND">AND</a></li>
      <li><a href="#+">+</a></li>
      <li><a href="#OR">OR</a></li>
      <li><a href="#NOT">NOT</a></li>
      <li><a href="#-">-</a></li>
    </ul>
  </li>
</ul>

<dl class="Content">
  <dt><a name="Wildcard Searches"></a>Suche mit Platzhaltern</dt>
  <dd>
    <p>Als Platzhalter für ein beliebiges Zeichen verwenden Sie das Fragezeichen <strong>(?)</strong>.</p>
    <p>Beispiel: Wenn Sie nach "Text" oder "Test" suchen wollen geben Sie </p>
    <pre class="code">Te?t</pre>
    <p>ein.</p>
    <p>Als Platzhalter für 0 oder mehrere beliebige Zeichen verwenden Sie ein Sternchen 
       <strong>(*)</strong>.</p>
    <p>Beispiel: Sie wollen nach "Test", "Tests" oder "Tester" suchen, dann geben
       Sie:</p>
    <pre class="code">Test*</pre>
    <p>ein.</p>
    <p>Sie können Platzhalter irgendwo platzieren:</p>
    <pre class="code">Te*t</pre>
  </dd>
  
  <dt><a name="Fuzzy Searches"></a>Unscharfe Suche</dt>
  <dd>
    <p>Verwenden Sie für die unscharfe Suche die Tilde <strong>(~)</strong> am
       Ende eines Wortes.
       Beispiel: Sie wollen ähnlich geschriebene Wörter zu "Raum" erhalten:</p>
    <pre class="code">Raum~</pre>
    <p>In diese Suche werden Wörter, wie "Baum" oder "Rahm" aufgenommen.</p>
    <p>Sie können die Anzahl der Wörter erhöhen oder verringern, indem Sie 
       einen Wert zwischen 0 und 1 hinter der Tilde setzen.
       Je kleiner der Wert, desto unschärfer ist die Suche. Wird der Wert auf 1
       gesetzt, wird nur nach identisch geschriebenen Wörtern gesucht.
       Beispiel:</p>
    <pre class="code">Raum~0.8</pre>
    <p>Wenn Sie nichts angeben, wird der Wert automatisch auf 0.5 gesetzt.</p>
  </dd>
  
  <dt><a name="Proximity Searches"></a>Bereichssuche</dt>
  <dd>
    <p>
      Für die Bereichssuche verwenden Sie die Tilde <strong>(~)</strong>, die
      Sie hinter eine Gruppe von Wörter setzen.
      Beispiel: Um nach Ökonomie und Keynes, welche maximal 10 Wörter voneinander entfernt sind, zu
      suchen, geben Sie Folgendes ein:
    </p>
    <pre class="code">"Ökonomie Keynes"~10</pre>
  </dd>
  
  <dt><a name="Range Searches"></a>Bereichssuche</dt>
  <dd>
    <p>
      Für die Bereichssuche verwenden Sie geschweifte Klammern <strong>({ })</strong>.
      Beispiel: Sie wollen ein Wort, welches mit A, B oder C anfängt suchen:
    </p>
    <pre class="code">{A TO C}</pre>
    <p>
      Das gleiche können Sie mit Zahlen, wie z.B. Jahreszahlen machen:
    </p>
    <pre class="code">[2002 TO 2003]</pre>
  </dd>
  
  <dt><a name="Boosting a Term"></a>Worte unterschiedlich gewichten</dt>
  <dd>
    <p>
      Sie können Wörtern mehr Bedeutung zuweisen, indem Sie diese mit einer
      Zahl gewichten. Verwenden Sie hierzu ein Dächchen <strong>(^)</strong>. Beispiel:
    </p>
    <pre class="code">Ökonomie Keynes^5</pre>
    <p>Dadurch wird das Wort "Keynes" stärker gewichtet und dadurch bei der Suche
       stärker beachtet.
    </p>
  </dd>

  <dt><a name="Boolean operators"></a>Boolesche Operatoren</dt>
  <dd>
    <p>
      Boolesche Operatoren erlauben es, Wörter logisch miteinander zu verknüpfen.
      Folgende Operatoren sind erlaubt:
      <strong>AND</strong>, <strong>+</strong>, <strong>OR</strong>,
      <strong>NOT</strong> und <strong>-</strong>.
    </p>
    <p>Hinweis: Boolesche Operatoren müssen großgeschrieben werden!</p>
    <dl>
      <dt><a name="AND"></a>AND</dt>
      <dd>
        <p>Die Und-Verknüpfung <strong>(AND)</strong> ist der Standardoperator. Das
            bedeutet, dass wenn zwischen zwei Wörtern kein Operator gesetzt wird,
            die Und-Verknüpfung verwendet wird. Wenn Sie zwei Wörter mit AND verbinden,
            erhalten Sie Treffer, in denen beide Wörter vorhanden sind.
        </p>
        <p>Beispiel: Sie suchen nach Titeln, in denen die Wörter
           "Ökonomie" und "Keynes" enthalten sind:</p>
        <pre class="code">Ökonomie Keynes</pre>
        <p>oder</p>
        <pre class="code">Ökonomie AND Keynes</pre>
      </dd>      
      <dt><a name="+"></a>+</dt>
      <dd>
        <p>Indem Sie den <strong>+</strong>-Operator vor ein Wort setzen, erhalten Sie
           nur Treffer, in denen dieses Wort vorkommt.
        </p>
        <p>Beispiel:</p>
        <pre class="code">+Ökonomie +Keynes</pre>
      </dd>
      <dt><a name="OR"></a>OR</dt>
      <dd>
        <p>Steht eine Oder-Verknüpfung <strong>(OR)</strong> zwischen zwei Wörtern, so
           erhalten Sie Treffer, in denen eines oder beide Wörter gefunden wurden.
        </p>
        <p>Beispiel: Sie suchen nach Titeln, in denen die Phrasen "Ökonomie Keynes" oder
           "Keynes" enthalten sind:</p>
        <pre class="code">"Ökonomie Keynes" OR Keynes</pre>
      </dd>
      <dt><a name="NOT"></a>NOT</dt>
      <dd>
        <p>Indem Sie <strong>NOT</strong> vor ein Wort setzen, schließen Sie Treffer aus,
           die dieses Wort enthalten.</p>
        <p>Beispiel: Sie wollen nach Titeln suchen, welche das Wort "Ökonomie"
           enthalten, aber nicht das Wort "Keynes":</p>
        <pre class="code">Ökonomie NOT Keynes</pre>
        <p>Hinweis: NOT muss mit mindestens zwei Wörtern verwendet werden.
           Beispielsweise liefert folgende Suche keine Treffer:</p>
        <pre class="code">NOT Ökonomie</pre>
      </dd>
      <dt><a name="-"></a>-</dt>
      <dd>
        <p>Wird der Operator <strong>(-)</strong> vor ein Wort gesetzt, so
           werden alle Treffer ausgefiltert, die dieses Wort enthalten.</p>
        <p>Beispiel:</p>
        <pre class="code">Ökonomie -Keynes</pre>
      </dd>
    </dl>
  </dd>
</dl>
