<h1>Was sehe ich hier?</h1>

<p>Sie sehen hier eine sogenannte <a href="https://www.cs.umd.edu/hcil/treemap/">Tree Map (Baumkarte)</a>,
      eine Visualisierungsform, die häufig für Daten mit hierarchichen Kategorien verwendet wird.</p>

<h1>Was kann ich daraus ablesen?</h1>

<p>Anhand der Baumkarte können Sie sehen, wie sich die Bücher und anderen Einträge, die Ihrer Suche entsprechen,
      auf die verschiedenen Fachgebiete verteilen und welche Themen die Einträge in den einzelnen Gebieten behandeln.
      Fachgebiete werden auf der Basis des Anfangsbuchstaben der Signatur vergeben.</p>

<p>Beachten Sie bitte, dass jeder Eintrag in der Regel mehrere Themen umfasst, so dass die Anzahl der Themen,
      die von den Artikeln in einem bestimmten Bereich abgedeckt werden, größer ist als die Gesamtzahl der Artikel
      in diesem Bereich.</p>

<h1>Wie kann ich diese Funktion nutzen?</h1>

<p>Sie können auf einen breiten Themenbereich klicken, um die Themen in diesem Bereich zu vergrößern und zu betrachten,
      oder Sie können auf ein Thema klicken, um die Bücher und anderen Einträge zu diesem Thema in diesem Themenbereich
      zu sehen. Weiterhin können Sie eine der Facetten in der rechten Seitenleiste verwenden, um Ihre Suche einzugrenzen.
      So können sie schnell sehen, wie sich die in den Ergebnissen enthaltenen Themen und Einträge ändern, wenn Sie Ihre
      Suche beispielsweise auf ein Jahr oder ein Format beschränken.</p>

<p>Wenn ein Teil des Textes abgeschnitten ist, können Sie mit dem Mauszeiger über das Feld fahren, um den vollständigen
      Text in einem Pop-up-Fenster anzuzeigen.</p>
