<?php
return array(
    'extends' => 'bootstrap3',
    'helpers' => array(
        'factories' => array(
            'authorizationNote' => 'Finna\View\Helper\Root\Factory::getAuthorizationNote',
            'browse' => 'Finna\View\Helper\Root\Factory::getBrowse',
            'combined' => 'Finna\View\Helper\Root\Factory::getCombined',
            'content' => 'Finna\View\Helper\Root\Factory::getContent',
            'feed' => 'Finna\View\Helper\Root\Factory::getFeed',
            'fileSrc' => 'Finna\View\Helper\Root\Factory::getFileSrc',
            'header' => 'Finna\View\Helper\Root\Factory::getHeader',
            'headTitle' => 'Finna\View\Helper\Root\Factory::getHeadTitle',
            'holdingsDetailsMode' => 'Finna\View\Helper\Root\Factory::getHoldingsDetailsMode',
            'imageSrc' => 'Finna\View\Helper\Root\Factory::getImageSrc',
            'indexedTotal' => 'Finna\View\Helper\Root\Factory::getTotalIndexed',
            'layoutclass' => 'Finna\View\Helper\Root\Factory::getLayoutClass',
            'metalib' => 'Finna\View\Helper\Root\Factory::getMetaLib',
            'navibar' => 'Finna\View\Helper\Root\Factory::getNavibar',
            'onlinePayment' => 'Finna\View\Helper\Root\Factory::getOnlinePayment',
            'openUrl' => 'Finna\View\Helper\Root\Factory::getOpenUrl',
            'organisationsList'
                => 'Finna\View\Helper\Root\Factory::getOrganisationsList',
            'personaAuth' => 'Finna\View\Helper\Root\Factory::getPersonaAuth',
            'piwik' => 'Finna\View\Helper\Root\Factory::getPiwik',
            'primo' => 'Finna\View\Helper\Root\Factory::getPrimo',
            'record' => 'Finna\View\Helper\Root\Factory::getRecord',
            'recordImage' => 'Finna\View\Helper\Root\Factory::getRecordImage',
            'recordLink' => 'Finna\View\Helper\Root\Factory::getRecordLink',
            'scriptSrc' => 'Finna\View\Helper\Root\Factory::getScriptSrc',
            'searchbox' => 'Finna\View\Helper\Root\Factory::getSearchBox',
            'searchTabs' => 'Finna\View\Helper\Root\Factory::getSearchTabs',
            'searchTabsRecommendations' => 'Finna\View\Helper\Root\Factory::getSearchTabsRecommendations',
            'proxyurl' => 'Finna\View\Helper\Root\Factory::getProxyUrl',
        ),
        'invokables' => array(
            'checkboxFacetCounts' =>
                'Finna\View\Helper\Root\CheckboxFacetCounts',
            'resultfeed' => 'Finna\View\Helper\Root\ResultFeed',
            'search' => 'Finna\View\Helper\Root\Search',
            'translationEmpty' => 'Finna\View\Helper\Root\TranslationEmpty',
            'truncateUrl' => 'Finna\View\Helper\Root\TruncateUrl',
            'userPublicName' => 'Finna\View\Helper\Root\UserPublicName',
        )
    ),
    'css' => array(
        'vendor/dataTables.bootstrap.css',
        'vendor/magnific-popup.css',
        'dataTables.bootstrap.custom.css',
        'vendor/slick.css',
        'vendor/bootstrap-multiselect.css',
        'vendor/bootstrap-datepicker3.min.css',
        'finna.css'
    ),
    'js' => array(
        'finna.js',
        'finna-combined-results.js',
        'image-popup.js',
        'finna-adv-search.js',
        'finna-daterange-vis.js',
        'finna-feed.js',
        'finna-layout.js',
        'finna-openurl.js',
        'finna-persona.js',
        'finna-common.js',
        'finna-user-profile.js',
        'vendor/jquery.dataTables.js',
        'vendor/dataTables.bootstrap.js',
        'vendor/jquery.inview.min.js',
        'vendor/jquery.magnific-popup.min.js',
        'vendor/jquery.cookie-1.4.1.min.js',
        'vendor/slick.min.js',
        'vendor/jquery.touchSwipe.min.js',
        'vendor/bootstrap-multiselect.min.js'
    ),
    'less' => array(
        'active' => false
    ),
    'favicon' => 'favicon.ico',
);
