<?php if ($this->user): ?>
  <?php $cards = $this->libraryCards()->getCardsForUser($this->user); ?>
  <?php if (count($cards) > 1): ?>
    <form class="form-inline form-select-card" action="<?=$this->url('librarycards-selectcard')?>" method="get" data-clear-account-cache>
      <label for="library_card"><?=$this->transEsc('Library Card')?></label>
      <select id="library_card" name="cardID" class="jumpMenu form-control">
        <?php if (null === $this->user->getCatUsername()): ?>
          <option value="" selected="selected">-</option>
        <?php endif; ?>
        <?php foreach ($cards as $card): ?>
          <?php
            $target = '';
            $username = $card->getCatUsername();
            if (strstr($username, '.')) {
              [$target, $username] = explode('.', $username, 2);
            }
            $display = $this->escapeHtml($card->getCardName() ? $card->getCardName() : $card->getCatUsername());
            if ($target) {
              $display .= ' (' . $this->transEsc("source_$target", null, $target) . ')';
            }
          ?>
          <option value="<?=$this->escapeHtmlAttr($card->getId())?>"<?=strcasecmp($card->getCatUsername(), $this->user->getCatUsername() ?? '') == 0 ? ' selected="selected"' : ''?>><?=$display ?></option>
        <?php endforeach; ?>
      </select>
      <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEscAttr('Set')?>"></noscript>
    </form>
  <?php endif; ?>
<?php endif; ?>
