<?php if (!empty($this->expanderList)): ?>
  <h4><?=$this->transEsc('eds_modes_and_expanders')?></h4>
  <fieldset class="eds well">
    <?php foreach ($this->expanderList as $field => $expander):
      $value = $expander['Value'] ?>
      <div>
        <label for="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" class="checkbox-label">
          <input id="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($expander['selected']) && $expander['selected'])?'checked="checked"':''?> name="filter[]" value="EXPAND:<?=$this->escapeHtmlAttr($value)?>">
          <?=$this->transEsc('eds_expander_' . $value, [], $expander['Label'])?>
        </label>
      </div>
    <?php endforeach; ?>

    <label for="searchMode_<?=$this->escapeHtmlAttr($field)?>"><?=$this->transEsc('Search Mode')?></label>
    <select id="searchMode_<?=$this->escapeHtmlAttr($field)?>" name="filter[]" class="form-control">
      <?php foreach ($this->searchModes as $field => $searchMode):
        $value = $searchMode['Value'] ?>
        <option <?=(isset($searchMode['selected']) && $searchMode['selected'])?'selected="selected"':''?> value="SEARCHMODE:<?=$this->escapeHtmlAttr($value)?>">
          <?= /* 'Label' comes from API and is always in English; try to translate structured value before using it: */ $this->transEsc('eds_mode_' . $value, [], $searchMode['Label']) ?>
        </option>
      <?php endforeach; ?>
    </select>
  </fieldset>
<?php endif; ?>

<?php if (!empty($this->limiterList)): ?>
  <h4><?=$this->transEsc('Limit To')?></h4>
  <fieldset class="eds well limit-to">
    <?php foreach ($this->limiterList as $field => $facet): ?>
      <?php switch($facet['Type']){
          case 'multiselectvalue': ?>
            <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>"><?=$this->transEsc($facet['Label'])?></label>
            <select id="limit_<?=$this->escapeHtmlAttr($field)?>" name="filter[]" multiple="multiple" size="10" class="form-control">
              <?php foreach ($facet['LimiterValues'] as $id => $facetValue): ?>
                <?php $value = $facetValue['Value']; ?>
                <option value="<?='LIMIT|' . $this->escapeHtmlAttr($field . ':' . $facetValue['Value'])?>"<?=(isset($facetValue['selected']) && $facetValue['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($facetValue['Value'])?></option>
              <?php endforeach; ?>
            </select>
            <!-- <br/> -->
            <?php break;
          case 'select':
            $value = $facet['LimiterValues'][0]['Value'] ?>
            <div>
              <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" class="checkbox-label">
                <input id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($facet['LimiterValues'][0]['selected']) && $facet['LimiterValues'][0]['selected'])?'checked="checked"':''?> name="filter[]" value="<?=$this->escapeHtmlAttr('LIMIT|' . $field . ':' . $value)?>">
                <?=$this->transEsc('eds_limiter_' . $field, [], $facet['Label'])?>
              </label>
            </div>
            <?php break;
        } ?>
    <?php endforeach; ?>
<?php endif; ?>
<?php if (isset($this->dateRangeLimit)): ?>
<div class="ranges-container">
  <div>
    <label><?=$this->transEsc('adv_search_year')?></label>
  </div>
  <div>
      <input type="hidden" name="daterange[]" value="PublicationDate"/>
        <div class="slider-container">
          <input type="text" id="PublicationDateSlider">
        </div>
        <div class="year-input-container text-center">
            <input type="text" name="PublicationDatefrom" id="PublicationDatefrom" value="<?=$this->escapeHtmlAttr($this->dateRangeLimit[0])?>" class="form-control form-inline input-year"/>
            <input type="text" name="PublicationDateto" id="PublicationDateto" value="<?=$this->escapeHtmlAttr($this->dateRangeLimit[1])?>" class="form-control form-inline input-year"/>
        </div>
    </div>
      <?php
        $current = $this->daterange;
        $this->headScript()->appendFile('vendor/bootstrap-slider.min.js');
        $this->headLink()->appendStylesheet('vendor/bootstrap-slider.min.css');
        $min = $current['ticks'][0];
        $max = end($current['ticks']);
        $low = !empty($current['values'][0]) ? $current['values'][0] : $min;
        $high = !empty($current['values'][1]) ? $current['values'][1] : $max;
        $min = intval($min);
        $max = intval($max);
        $low = intval($low);
        $high = intval($high);
        $init = !empty($current['values'][0]) ? 'fillTexts()' : '';
        $ticks = $ticks_labels = '[' . implode(', ', $current['ticks']) . ']';
        $ticks_positions = '[' . implode(', ', $current['ticks_positions']) . ']';
        $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
    var v = PublicationDateSlider.getValue();
    $('#PublicationDatefrom').val(v[0]);
    $('#PublicationDateto').val(v[1]);
  };
  var PublicationDateSlider = $('#PublicationDateSlider')
    .slider({
       'min':{$min},
       'max':{$max},
       'handle':"square",
       'tooltip':"hide",
       'value':[{$low},{$high}],
       'ticks':{$ticks},
       'ticks_labels':{$ticks_labels},
       'ticks_positions':{$ticks_positions}
    })
    .change(fillTexts)
    .data('slider');
  {$init}
});
JS;
    ?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
    </div>
  </fieldset>
<?php endif; ?>
