<div>
  <?php if (isset($usedCheckboxFilters)): ?>
  <?php foreach ($usedCheckboxFilters as $filter): ?>
    <?php if ($filter['selected']): ?>
    <div>
      <label>
        <input type="checkbox" class="checkbox-select-item" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($filter['filter'])?>' />
        <?=$this->transEsc($filter['desc'])?>
      </label>
    </div>
    <?php endif; ?>
  <?php endforeach; ?>
  <?php endif; ?>
  <?php foreach ($searchFilters as $field => $data): ?>
    <?php foreach ($data as $index => $value): ?>
      <div>
        <label>
          <?php $operatorChar = ($value['operator'] == 'NOT') ? '-' : ($value['operator'] == 'OR' ? '~' : ''); ?>
          <input type="checkbox" class="checkbox-select-item" checked="checked" name="filter[]" value='<?=$operatorChar . $this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' />
          <?php if ($value['operator'] == 'NOT') echo $this->transEsc('NOT'); if ($value['operator'] == 'OR' && $index > 0) echo $this->transEsc('OR'); ?>
          <?=$this->transEsc($field)?>: <?=$this->escapeHtml($value['displayText'])?>
        </label>
      </div>
    <?php endforeach; ?>
  <?php endforeach; ?>
</div>
