<!-- START of: finna - search/advanced/layout.phtml -->
<?php
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>';
  $lastSearchLink = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'));
  $this->layout()->breadcrumbs .= !empty($lastSearchLink)
    ? $lastSearchLink : $this->transEsc('Search');
  $this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();

    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, true);
  }

  // Search type and tabs
  $this->searchType = 'advanced';
  $this->layout()->finnaMainHeader = '<div><h1 class="content-header">' . $this->translate('Advanced Search') . '</h1></div>';
  $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters, []);
  $this->layout()->finnaMainTabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchTabs['tabs'], 'hiddenFilters' => $hiddenFilters]);

  // Step 1: Load the javascript
  $this->headScript()->appendFile(
    isset($this->advancedSearchJsOverride) ? $this->advancedSearchJsOverride : 'advanced_search.js'
  );
  $this->headScript()->appendFile('finna-daterange-vis.js');

  // Step 2: Build the page
  $this->headScript()->appendScript(
    $this->partial(
      isset($this->buildPageOverride) ? $this->buildPageOverride : 'search/advanced/build_page.phtml',
      ['options' => $this->options, 'searchDetails' => $searchDetails]
    )
  );

  // Collect previous search queries
  $setSearchGroups = [];
  $setGroupCount = 0;
  $setQueries = [];
  if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group => $searchGroup) {
      $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
      if ($setGroupCount < $group) {
        $setGroupCount = $group;
      }
      if (!isset($setQueries[$group])) {
        $setQueries[$group] = [];
      }
      foreach ($searchGroup->getQueries() as $search) {
        $setQueries[$group][] = $search;
      }
    }
  }

  $tooltipSource = 'local';
  if ('EDS' == $this->searchClassId) {
    $tooltipSource = 'eds';
  } elseif ('Summon' == $this->searchClassId) {
    $tooltipSource = 'summon';
  }
?>

<?=$this->flashmessages()?>
<form role="search" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
  <?php foreach ($hiddenFilters as $key => $filter): ?>
    <?php foreach ($filter as $value): ?>
      <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
    <?php endforeach; ?>
  <?php endforeach; ?>
  <div class="advanced-search">
    <div class="">
      <h4><?=$this->transEsc("adv_search_label")?><?php if (!$this->translationEmpty("tooltip_{$tooltipSource}_advanced_html")): ?><span class="tooltip-<?=$tooltipSource?>-advanced" data-toggle="tooltip" data-placement="bottom" data-html="true" data-original-title='<?=$this->transesc("tooltip_{$tooltipSource}_advanced_html") ?>'><i class="fa fa-info-big" aria-hidden="true"></i> <?=$this->transEsc("Help with Advanced Search")?></span><?php endif; ?></h4>
      <input type="hidden" name="sort" value="relevance">

      <?php /* An empty div. This is the target for the javascript that builds this screen */ ?>
      <span id="groupPlaceHolder" class="hidden btn btn-primary pull-right">
        <a href="#" onClick="addGroup()"> <i class="fa fa-plus-small" aria-hidden="true"></i> <?= $this->transEsc('add_search_group') ?></a>
      </span>
      <?php /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
      <div class="no-js">
        <?php if (!empty($this->formOverride)): ?>
          <?=$this->formOverride ?>
        <?php else: ?>
          <?php for ($group = 0; $group < 3 || $group <= $setGroupCount; $group++): ?>
            <?php if ($group == 0): ?>
              <div id="new_group_template">
            <?php endif; ?>
            <div id="group<?=$group ?>" class="adv-group well">
              <a href="#" class="adv-group-close hidden" title="<?=$this->transEsc("del_search")?>"><i class="fa fa-times" aria-hidden="true"></i> <?=$this->transEsc("del_search")?></a>
              <div class="adv-search-group">
                <div class="adv-group-match match">
                  <label class="search_bool"><?=$this->transEsc("search_match")?>:</label>
                  <select name="bool<?=$group ?>[]" id="search_bool<?=$group ?>" class="form-control form-inline">
                    <option value="AND"<?php if(isset($setSearchGroups[$group]) && 'AND' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$this->transEsc("search_AND")?></option>
                    <option value="OR"<?php if(isset($setSearchGroups[$group]) && 'OR' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$this->transEsc("search_OR")?></option>
                    <option value="NOT"<?php if(isset($setSearchGroups[$group]) && 'NOT' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$this->transEsc("search_NOT")?></option>
                  </select>
                </div>
                <div class="adv-group-terms">
                  <?php for ($search = 0; $search < 3 || (isset($setQueries[$group]) && $search < count($setQueries[$group])); $search++): ?>
                    <?php if ($group == 0 && $search == 0): ?>
                      <div id="new_search_template">
                    <?php endif; ?>
                    <div id="search<?=$group . '_' . $search ?>" class="adv-search search">
                      <input name="lookfor<?=$group ?>[]" id="search_lookfor<?=$group . '_' . $search ?>" title="<?=$this->transEsc("Search words");?>" aria-label="<?=$this->transEsc("Search words");?>" class="adv-term-input form-control form-inline responsive-field search-text" placeholder="<?=$this->transEsc("Search words")?>..." type="text"<?php if(isset($setQueries[$group][$search])):?> value="<?=$this->escapeHtml($setQueries[$group][$search]->getString())?>"<?php endif;?>>
                      <select class="adv-term-type form-control form-inline responsive-field search-select" name="type<?=$group ?>[]" title="<?=$this->transEsc("search_in_field");?>" aria-label="<?=$this->transEsc("search_in_field");?>">
                        <?php foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                          <option value="<?=$this->escapeHtml($searchVal)?>"<?php if(isset($setQueries[$group][$search]) && $searchVal == $setQueries[$group][$search]->getHandler()):?> selected<?php endif;?>><?=$this->transEsc($searchDesc)?></option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                    <?php if ($group == 0 && $search == 0): ?>
                      </div>
                      <span class="search_place_holder hidden"></span> <a href="#" class="add_search_link btn btn-primary hidden"><i class="fa fa-plus-small" aria-hidden="true"></i> <?=$this->transEsc("add_search")?></a>
                    <?php endif; ?>
                  <?php endfor; ?>
                </div>
              </div>
              <?php if($group == 0): ?>
                </div>
              <?php endif; ?>
            </div>
          <?php endfor; ?>
        <?php endif; ?>
      </div>
      <div class="group-join-container">
        <div id="groupJoin" class="form text-center">
          <label for="groupJoinOptions"><?=$this->transEsc("adv_search_group_join")?>:</label>
          <select id="groupJoinOptions" name="join" class="form-control form-inline">
            <option value="AND"<?php if($searchDetails && $searchDetails->getOperator() == 'ALL'):?> selected<?php endif?>><?= $this->transEsc('group_AND') ?></option>
            <option value="OR"<?php if($searchDetails && $searchDetails->getOperator() == 'OR'):?> selected<?php endif?>><?= $this->transEsc('group_OR') ?></option>
          </select>
        </div>
      </div>
      <span class="clearfix"></span>
      <?php if (isset($this->extraAdvancedControls)): ?>
        <?=$this->extraAdvancedControls ?>
      <?php endif; ?>
      <div class="adv-search-bar">
       <span class="limit-container">
          <?=$this->render('search/advanced/limit.phtml')?>
        </span>
        <button class="btn btn-lg btn-primary pull-right" type="submit" value="<?= $this->transEsc('Find')?>"><i class="fa fa-search-adv"></i> <?= $this->transEsc('Find')?></button>
      </div>
    </div>
    <?php if ($hasDefaultsApplied): ?>
      <input type="hidden" name="dfApplied" value="1" />
    <?php endif ?>
  </div>
  <?php if ($template = $this->content()->findTemplateForLng("content/Additions/solr-advanced-post")): ?>
    <?=$this->render($template)?>
  <?php endif; ?>
</form>
<!-- END of: finna - search/advanced/layout.phtml -->
