<!-- START of: finna - search/advanced/layout.phtml -->
<?php
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Search'), $this->searchMemory()->getLastSearchUrl())
    ->add($this->translate('Advanced'), active: true);

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    if ($searchDetails instanceof \VuFindSearch\Query\Query) {
        // Not an advanced query -- ignore it.
        $searchDetails = $groups = false;
    } else {
        $groups = $searchDetails->getQueries();
    }
    $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();

    $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
  } else {
    $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, true);
  }

  // Search type and tabs
  $this->searchType = 'advanced';
  $this->layout()->finnaMainHeader = '<div><h1 class="content-header">' . $this->translate('Advanced Search') . '</h1></div>';
  $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters, []);
  $this->layout()->finnaMainTabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchTabs['tabs'], 'hiddenFilters' => $hiddenFilters]);

  // Step 1: Load the javascript
  $this->assetManager()->appendScriptLink(
      $this->advancedSearchJsOverride ?? 'advanced_search.js'
  );
  $this->assetManager()->appendScriptLink('finna-daterange-vis.js');

  // Step 2: Build the page
  $this->assetManager()->appendScriptString(
      $this->partial(
          $this->buildPageOverride ?? 'search/advanced/build_page.phtml',
          ['options' => $this->options, 'searchDetails' => $searchDetails]
      )
  );

  // Collect previous search queries
  $setSearchGroups = [];
  $setGroupCount = 0;
  $setQueries = [];
  if (isset($searchDetails) && is_object($searchDetails)) {
    foreach ($searchDetails->getQueries() as $group => $searchGroup) {
      $setSearchGroups[$group] = $searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator();
      if ($setGroupCount < $group) {
        $setGroupCount = $group;
      }
      if (!isset($setQueries[$group])) {
        $setQueries[$group] = [];
      }
      foreach ($searchGroup->getQueries() as $search) {
        $setQueries[$group][] = $search;
      }
    }
  }

  $tooltipSource = 'local';
  if ('EDS' == $this->searchClassId) {
    $tooltipSource = 'eds';
  } elseif ('Summon' == $this->searchClassId) {
    $tooltipSource = 'summon';
  } elseif ('Blender' == $this->searchClassId) {
    $tooltipSource = 'blended';
  }
?>

<?=$this->flashmessages()?>
<form role="search" aria-label="<?=$this->transEscAttr('Advanced Search')?>" name="searchForm" id="advSearchForm" method="get" action="<?=$this->url($this->options->getSearchAction())?>">
  <?php foreach ($hiddenFilters as $key => $filter): ?>
    <?php foreach ($filter as $value): ?>
      <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>">
    <?php endforeach; ?>
  <?php endforeach; ?>
  <div class="advanced-search">
    <div class="">
      <div class="header-container">
        <h2><?=$this->transEsc('adv_search_label')?></h2>
        <?php if (!$this->translationEmpty("tooltip_{$tooltipSource}_advanced_html")): ?>
          <?=$this->component('finna-toggletip', [
            'icon' => 'help',
            'contentHtml' => $this->translate("tooltip_{$tooltipSource}_advanced_html"),
            'labelHtml' => $this->transEsc('Help with Advanced Search'),
            'class' => 'tooltip-pci-advanced float-end',
          ])?>
        <?php endif; ?>
      </div>
      <input type="hidden" name="sort" value="relevance">

      <?php /* An empty div. This is the target for the javascript that builds this screen */ ?>
      <h3 id="adv-search-groups-header" class="visually-hidden"><?=$this->transEsc('search_groups')?></h3>
      <div id="groupPlaceHolder" class="hidden float-start">
        <button type="button" class="btn btn-primary"><?=$this->icon('adv-search-group-add') ?> <?= $this->transEsc('add_search_group') ?></button>
      </div>
      <?php /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
      <div class="no-js">
        <?php if (!empty($this->formOverride)): ?>
          <?=$this->formOverride ?>
        <?php else: ?>
          <?php
          //Escaped translations, multiusage
          $msgSearchGroup = $this->transEsc('adv_search_group');
          $msgDeleteSearch = $this->transEsc('del_search');
          $msgSearchMatch = $this->transEsc('search_match');
          $msgSearchWords = $this->translate('Search words');
          $msgSearchInField = $this->translate('search_in_field');
          $msgSearchAnd = $this->transEsc('search_AND');
          $msgSearchOr = $this->transEsc('search_OR');
          $msgSearchNot = $this->transEsc('search_NOT');
          ?>
          <?php for ($group = 0; $group < 3 || $group <= $setGroupCount; $group++): ?>
            <?php if ($group == 0): ?>
              <div id="new_group_template">
            <?php endif; ?>
            <div id="group<?=$group ?>" class="adv-group well">
              <h4><?=$msgSearchGroup?></h4>
              <div class="adv-search-group">
                <div class="adv-group-match match">
                  <label class="search_bool"><?=$msgSearchMatch?>:</label>
                  <select name="bool<?=$group ?>[]" id="search_bool<?=$group ?>" class="form-select form-inline">
                    <option value="AND"<?php if (isset($setSearchGroups[$group]) && 'AND' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$msgSearchAnd?></option>
                    <option value="OR"<?php if (isset($setSearchGroups[$group]) && 'OR' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$msgSearchOr?></option>
                    <option value="NOT"<?php if (isset($setSearchGroups[$group]) && 'NOT' == $setSearchGroups[$group]):?> selected<?php endif;?>><?=$msgSearchNot?></option>
                  </select>
                </div>
                <div class="adv-group-terms">
                  <?php
                  $loopLimit = (isset($setQueries[$group])) ? count($setQueries[$group]) : 3;

                  $this->htmlElement()->addAttributeTemplate('input-text', [
                    'placeholder' => $msgSearchWords . $this->translate('eol_ellipsis'),
                    'title' => $msgSearchWords,
                    'type' => 'text',
                    'aria-label' => $msgSearchWords,
                    'class' => 'adv-term-input form-control form-inline responsive-field search-text',
                  ]);

                  $this->htmlElement()->addAttributeTemplate('select-field', [
                    'aria-label' => $msgSearchInField,
                    'class' => 'adv-term-type form-control form-inline responsive-field search-select',
                    'title' => $msgSearchInField,
                  ]);
                  ?>
                  <?php for ($search = 0; $search < $loopLimit; $search++): ?>
                    <?php if ($group == 0 && $search == 0): ?>
                      <div id="new_search_template">
                    <?php endif; ?>
                    <?php
                    $isQuerySearchSet = isset($setQueries[$group][$search]);

                    $inputElement = [
                      'id' => 'search_lookfor' . $group . '_' . $search,
                      'name' => 'lookfor' . $group . '[]',
                      'value' => $isQuerySearchSet ? $setQueries[$group][$search]->getString() : '',
                    ];

                    $selectElement = [
                      'name' => 'type' . $group . '[]',
                    ];
                    ?>
                    <div id="search<?=$group . '_' . $search ?>" class="adv-search search">
                      <input <?= $this->htmlElement()->getAttributes($inputElement, 'input-text') ?>>
                      <select <?= $this->htmlElement()->getAttributes($selectElement, 'select-field') ?>>
                        <?php foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                          <?php
                          $optionElement = [
                            'value' => $this->escapeHtml($searchVal),
                            'selected' => ($isQuerySearchSet && $searchVal == $setQueries[$group][$search]->getHandler()) ? 'selected' : '',
                          ];
                          ?>
                          <option <?= $this->htmlElement()->getAttributes($optionElement) ?>>
                            <?= $this->transEsc($searchDesc) ?>
                          </option>
                        <?php endforeach; ?>
                      </select>
                    </div>
                    <?php if ($group == 0 && $search == 0): ?>
                      </div>
                      <span class="search_place_holder hidden"></span>
                      <div>
                        <button type="button" class="add_search_link btn btn-primary hidden">
                        <?=$this->icon('adv-search-group-add') ?> <?=$this->transEsc('add_search')?>
                        </button>
                        <button type="button" class="adv-group-close hidden" title="<?=$msgDeleteSearch?>">
                          <?=$this->icon('adv-search-group-remove') ?> <?=$msgDeleteSearch?>
                        </button>
                        <div class="clearfix"></div>
                      </div>
                    <?php endif; ?>
                  <?php endfor; ?>
                </div>
              </div>
              <?php if ($group == 0): ?>
                </div>
              <?php endif; ?>
            </div>
          <?php endfor; ?>
        <?php endif; ?>
      </div>
      <div class="group-join-container">
        <div id="groupJoin" class="form text-center">
          <label for="groupJoinOptions"><?=$this->transEsc('adv_search_group_join')?>:</label>
          <select id="groupJoinOptions" name="join" class="form-select form-inline">
            <option value="AND"<?php if ($searchDetails && $searchDetails->getOperator() == 'ALL'):?> selected<?php endif?>><?= $this->transEsc('group_AND') ?></option>
            <option value="OR"<?php if ($searchDetails && $searchDetails->getOperator() == 'OR'):?> selected<?php endif?>><?= $this->transEsc('group_OR') ?></option>
          </select>
        </div>
      </div>
      <span class="clearfix"></span>
      <?php if (isset($this->extraAdvancedControls)): ?>
        <?=$this->extraAdvancedControls ?>
      <?php endif; ?>
      <div class="adv-search-bar">
       <span class="limit-container">
          <?=$this->render('search/advanced/limit.phtml')?>
        </span>
        <button class="btn btn-lg btn-primary float-end" type="submit" value="<?= $this->transEscAttr('Find')?>"><?=$this->icon('search-advanced') ?> <?= $this->transEsc('Find')?></button>
      </div>
    </div>
    <?php if ($hasDefaultsApplied): ?>
      <input type="hidden" name="dfApplied" value="1">
    <?php endif ?>
  </div>
  <?php if ($template = $this->content()->findTemplateForLng('content/Additions/solr-advanced-post')): ?>
    <?=$this->render($template)?>
  <?php endif; ?>
</form>
<?php
$script = <<<JS
                              $('#groupPlaceHolder button').on('click', function(e) {
                                addGroup(null, null, null, true);
                                return false;
                              });
                              JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script);?>
<!-- END of: finna - search/advanced/layout.phtml -->
