<!-- START of: finna - search/advanced/limit.phtml -->
<?php
    // Set up convenience variables:
    $limitList = $this->options->getLimitOptions();

    // If a previous limit was used, make that the default; otherwise, use the "default default"
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $defaultLimit = empty($lastLimit) ? $this->options->getDefaultLimit() : $lastLimit;
?>
<?php if (count($limitList) > 1): ?>
  <label for="limit" class="form-inline"><?=$this->transEsc('Results per page')?></label>
  <select id="limit" name="limit" class="form-control form-inline">
    <?php foreach ($limitList as $limitVal): ?>
      <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=($limitVal == $defaultLimit) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($limitVal)?></option>
    <?php endforeach; ?>
  </select>
<?php endif; ?>
<!-- END of: finna - search/advanced/limit.phtml -->
