<!-- START of: finna - search/advanced/map.phtml -->
<?php
  $this->jsTranslations()->addStrings(
    [
      'radiusPrefix' => 'Radius',
      'circleCaption' => 'Select Area',
      'clearCaption' => 'Clear Selections',
      'removeCaption' => 'Clear',
      'map_zoom_in' => 'map_zoom_in',
      'map_zoom_out' => 'map_zoom_out'
  ]);
?>
<div class="selection-map-canvas"></div>

<script>
$(document).ready(function() {
    var options = {
      items: []
    };
    <?php if ($saved && ($filters = $saved->getParams()->getGeographicFilters($saved->getParams()->getFilterList()))): ?>
      <?php foreach ($filters as $filter): ?>
        <?php foreach (preg_split('/\s+OR\s+/', $filter) as $item): ?>
          options.items.push('<?=$this->escapeJs($item) ?>');
        <?php endforeach; ?>
      <?php endforeach; ?>
    <?php endif; ?>
    finna.advSearch.initMap(options);
});
</script>

<!-- END of: finna - search/advanced/map.phtml -->
