<!-- START of: finna - search/advanced/solr.phtml -->
<?php if (!empty($this->facetList) || !empty($this->checkboxFacets)): ?>
<?php
    if (isset($this->saved) && is_object($this->saved)) {
      $searchFilters = $this->saved->getParams()->getFilterList(true);
      $checkboxFilters = $this->saved->getParams()->getCheckboxFacets();
      $usedCheckboxFilters = [];
      foreach ($checkboxFilters as $filter) {
          if ($filter['selected']) {
              array_push($usedCheckboxFilters, $filter);
          }
      }
      // Remove date range filter (search_daterange_mv) and geographic filters so that
      // they don't get included in the list of active filters
      $searchFilters = $this->saved->getParams()->removeDateRangeFilter($searchFilters);
      $searchFilters = $this->saved->getParams()->removeGeographicFilters($searchFilters);
      $hiddenFilters = $this->saved->getParams()->getHiddenFilters();
    }
?>
  <div>
    <h4><?=$this->transEsc('Limit To')?></h4>
  </div>
  <div>
    <div class="option-container">
      <?php if (!empty($this->checkboxFacets)): ?>
        <div class="checkboxFilter">
          <?=$this->render('search/advanced/checkbox-filters.phtml')?>
        </div>
      <?php endif; ?>
      <fieldset class="well limit-to facets">
        <legend class="sr-only"><?=$this->transEsc('Limit To')?></legend>
        <div class="facet-container">
          <?php foreach ($this->facetList as $field => $list): ?>
            <div class="facet">
              <div class="solr-adv-filter <?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>-container">
                <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
                <select class="form-control multi-select" id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '', $field))?>" name="filter[]"  multiple="multiple" >
                  <?php if (is_array($this->hierarchicalFacets) && in_array($field, $this->hierarchicalFacets)): ?>
                    <?php foreach ($list['list'] as $value): ?>
                      <?php $display = str_pad('', 4 * $value['level'] * 6, '&nbsp;', STR_PAD_LEFT) . $this->escapeHtml($value['displayText']); ?>
                      <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$display?></option>
                    <?php endforeach; ?>
                  <?php else: ?>
                    <?php
                    // Sort the current facet list alphabetically; we'll use this data
                    // along with the foreach below to display facet options in the
                    // correct order.
                    $sorted = [];
                    foreach ($list['list'] as $i => $value) {
                      if (!empty($value['displayText'])) {
                        $sorted[$i] = $value['displayText'];
                      }
                    }
                    natcasesort($sorted);
                    ?>
                    <?php foreach ($sorted as $i => $display): ?>
                      <?php $value = $list['list'][$i]; ?>
                      <option value="<?=$this->escapeHtmlAttr(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
                    <?php endforeach; ?>
                  <?php endif; ?>
                </select>
              </div>
            </div>
          <?php endforeach; ?>
        </div>
        <div class="information"><p class="information-text"><?=$this->transEsc('advanced_search_information_text_facets')?></p></div>
      </fieldset>
      <?php if (!empty($this->daterange)): ?>
        <div class="ranges-container well limit-to">
          <?=$this->render('search/advanced/ranges.phtml', ['searchClassId' => $this->searchClassId, 'ranges' => $this->daterange])?>
        </div>
      <?php endif; ?>
    </div>
    <?php if (!empty($searchFilters) || !empty($usedCheckboxFilters)): ?>
      <h4><?=$this->transEsc("adv_search_filters")?></h4>
      <fieldset class="well limit-to">
        <?=$this->render('search/advanced/filters.phtml', ['usedCheckboxFilters' => $usedCheckboxFilters, 'searchFilters' => $searchFilters])?>
      </fieldset>
    <?php endif; ?>
  </div>
<?php endif; ?>
<div class="search-map-container">
  <div>
    <h4><?=$this->transEsc('Geographical Area') ?></h4>
  </div>
  <div class="map-container">
    <fieldset class="well map">
      <legend class="sr-only"><?=$this->transEsc('Geographical Area') ?></legend>
      <?=$this->render('search/advanced/map.phtml', ['searchClassId' => $this->searchClassId, 'saved' => $this->saved])?>
      <div class="information"><p class="information-text"><?=$this->transEsc('advanced_search_information_text_map')?></p></div>
    </fieldset>
  </div>
</div>
<?php if (isset($this->illustratedLimit)): ?>
  <fieldset>
    <legend><?=$this->transEsc("Illustrated")?>:</legend>
    <?php foreach ($this->illustratedLimit as $current): ?>
      <input id="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>" type="radio" name="illustration" value="<?=$this->escapeHtmlAttr($current['value'])?>"<?=$current['selected']?' checked="checked"':''?>/>
      <label for="illustrated_<?=$this->escapeHtmlAttr($current['value'])?>"><?=$this->transEsc($current['text'])?></label><br/>
    <?php endforeach; ?>
  </fieldset>
<?php endif; ?>
<!-- END of: finna - search/advanced/solr.phtml -->
