<!-- START of: finna - RecordDriver/EDS/online-url-list.phtml -->
<? foreach ($this->urls as $current): ?>
  <?
    $url = $current['url'];
    $target = ' target="_blank"';
    if ('#' === $url[0]) {
      $url = $this->recordlink()->getUrl($this->driver) . $url;
      $target = '';
    }
  ?>
  <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($url))?>" class="fulltext<?=!empty($current['citation']) ? ' citation' : ''?>"<?=$target?>><i class="fa fa-external-link"></i> <?=$this->transEsc($current['desc'])?></a>
<? endforeach; ?>
<!-- END of: finna - RecordDriver/EDS/online-url-list.phtml -->
