<?php // This template is a text fragment of a complete OpenAPI specification ?>
Search the index with given terms and filters. POST method may also be used if sending a long request.

The URL syntax here is the same as the one used in Finna user interface. It is possible to make a search in Finna and copy the query parameters here to make the same search via the API.

See https://www.kiwi.fi/display/Finna/Finna+API+Terms+of+Use for Finna API Terms of Use.

Notes:
  - The CC0 metadata licence does not pertain to the resources linked to the metadata, such as images relating to the entries.
  - Only first <?=$this->maxImagesInSearch?> images are returned per record when using the search API.

See https://www.kiwi.fi/pages/viewpage.action?pageId=53839221 for more information and examples.
