<!-- START of: finna - search/advanced/ranges.phtml -->
<? if (isset($this->ranges) && !empty($this->ranges)): ?>
  <? $params = $this->searchParams($this->searchClassId); $params->activateAllFacets(); ?>
  <? foreach ($this->ranges as $current): $escField = $this->escapeHtmlAttr($current['field']); ?>
    <? $extraInputAttribs = ($current['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
    <fieldset>
      <div class="row">
        <div class="col-md-2">
          <label class="form-inline"><?=$this->transEsc($params->getFacetLabel($current['field']))?>:</label>
        </div>
        <? if ($current['type'] == 'date'): ?>
        <div class="col-md-10">
          <div class="slider-container">
            <input type="text" id="<?=$escField?><?=$this->escapeHtmlAttr($current['type'])?>Slider">
          </div>
          <? endif; ?>
          <div class="year-input-container text-center">
            <input type="hidden" name="<?=$this->escapeHtmlAttr($current['type'])?>range[]" value="<?=$escField?>"/>
            <? if (isset($current['rangeType'])): ?>
               <input type="hidden" name="<?= $current['field'] ?>_type" value="<?= $current['rangeType'] ?>"/>
            <? endif ?>
            <input type="number" class="form-control form-inline input-year" pattern="-?\d{0,4}" name="<?=$escField?>from" id="<?=$escField?>from" value="<?=isset($current['values'][0])?$this->escapeHtmlAttr($current['values'][0]):''?>" size="5" class="form-control form-inline" <?=$extraInputAttribs?>/>
            <span class="divider"> - </span>
            <input type="number" class="form-control form-inline input-year" pattern="-?\d{0,4}" name="<?=$escField?>to" id="<?=$escField?>to" value="<?=isset($current['values'][1])?$this->escapeHtmlAttr($current['values'][1]):''?>" size="5" class="form-control form-inline" <?=$extraInputAttribs?>/>
          </div>
        </div>
        <? if ($current['type'] == 'date'): ?>
        <?
          $this->headScript()->appendFile('vendor/bootstrap-slider.js');
          $min = !empty($current['values'][0]) ? min($current['values'][0], 1400) : 1400;
          $future = date('Y', time()+31536000);
          $max = !empty($current['values'][1]) ? max($future, $current['values'][1]) : $future;
          $low  = !empty($current['values'][0]) ? $current['values'][0] : $min;
          $high = !empty($current['values'][1]) ? $current['values'][1] : $max;
          $min = intval($min);
          $max = intval($max);
          $low = intval($low);
          $high = intval($high);
          $init = !empty($current['values'][0]) ? 'fillTexts()' : '';
          $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
    var v = {$escField}dateSlider.getValue();
    $('#${escField}from').val(v[0]);
    $('#${escField}to').val(v[1]);
  };
  var {$escField}dateSlider = $('#{$escField}dateSlider')
    .slider({
       'min':{$min},
       'max':{$max},
       'handle':"square",
       'value':[{$low},{$high}],
       'formatter': function(value) {
		     return value[0]+' - '+value[1];
	     },
    })
    .on('slide', fillTexts)
    .data('slider');
  {$init}
});
JS;
        ?>
        <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
      <? endif; ?>
    </div>
    </fieldset>
  <? endforeach; ?>
<? endif; ?>
<!-- END of: finna - search/advanced/ranges.phtml -->
