<br/>
<section class="cw-hero cw-py-6 cw-py-lg-7 cw-text-white cw-dark-overlay">
  <img src="<?=$this->imageLink('cw/photo-1467987506553-8f3916508521.jpg')?>" alt="Text page" class="cw-bg-image">
  <div class="cw-container cw-overlay-content">
    <!-- Breadcrumbs -->
    <!--
    <ol class="cw-breadcrumb cw-text-white cw-justify-content-center cw-no-border cw-mb-0">
      <li class="cw-breadcrumb-item"><a href="index.html">Home</a></li>
      <li class="cw-breadcrumb-item active">Text page</li>
    </ol>
    -->
    <h1 class="cw-hero-heading">About us</h1>
  </div>
</section>
<section class="cw-py-6">
<div class="container">
  <div class="row">
    <div class="col-xl-8 col-lg-10 mx-auto">
      <p class="lead cw-mb-5">As am hastily invited <strong>settled at limited</strong> civilly fortune me. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xl-10 mx-auto"><img src="<?=$this->imageLink('cw/photo-1471189641895-16c58a695bcb.jpg')?>" alt="" class="img-fluid cw-mb-5"></div>
  </div>
  <div class="row">
    <div class="col-xl-8 col-lg-10 mx-auto">
      <div class="cw-text-content">
        <p><strong>Pellentesque habitant morbi tristique</strong> senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. <em>Aenean ultricies mi vitae est.</em> Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, <code>commodo vitae</code>, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. <a href="#">Donec non enim</a> in turpis pulvinar facilisis. Ut felis.</p>
        <figure class="figure cw-mb-3"><img src="<?=$this->imageLink('cw/photo-1482463084673-98272196658a.jpg')?>" alt="Example blog post alt." class="figure-img img-fluid">
          <figcaption class="figure-caption text-center">Photo by Jack Tran, New York                     </figcaption>
        </figure>
        <h2>Header Level 2</h2>
        <ol>
          <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
          <li>Aliquam tincidunt mauris eu risus.</li>
        </ol>
        <blockquote class="cw-blockquote cw-blockquote-primary cw-bg-gray-100 cw-p-5">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vivamus magna. Cras in mi at felis aliquet congue. Ut a est eget ligula molestie gravida. Curabitur massa. Donec eleifend, libero at sagittis mollis, tellus est malesuada tellus, at luctus turpis elit sit amet quam. Vivamus pretium ornare est.</blockquote>
        <h3>Header Level 3</h3>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus</p>
        <ul>
          <li>Lorem ipsum dolor sit amet, consectetuer adipiscing elit.</li>
          <li>Aliquam tincidunt mauris eu risus.</li>
        </ul>
        <p><img src="<?=$this->imageLink('cw/photo-1499695867787-121ffb7950bf.jpg')?>" alt="Example blog post alt" class="img-fluid"></p>
        <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. </p>
        <p>Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis. Praesent dapibus, neque id cursus faucibus, tortor neque egestas augue, eu vulputate magna eros eu erat. Aliquam erat volutpat. Nam dui mi, tincidunt quis, accumsan porttitor, facilisis luctus, metus          </p>
      </div>
    </div>
  </div>
</div>
</section>