<section class="cw-hero cw-py-5 cw-py-lg-7">
  <div class="container position-relative">
    <h1 class="cw-hero-heading cw-mb-5">FAQ</h1>
    <div class="row">
      <div class="col-xl-8 mx-auto"><p class="lead mb-0">As am hastily invited settled at limited civilly fortune me. Really spring in extent an by. Judge but built party world. Of so am he remember although required. Bachelor unpacked be advanced at. Confined in declared marianne is vicinity. </p></div>
    </div>
  </div>
</section>

<section class="cw-py-6">
  <div class="container">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Shopping</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">What shipping method does Sell use?</h5>
          <p class="text-muted cw-mb-4">The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream.</p>
          <h5 class="cw-h5">What countries do you to?</h5>
          <p class="text-muted cw-mb-4">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">One of my items is missing</h5>
          <p class="text-muted cw-mb-4">Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
          <h5 class="cw-h5">Remote areas - delivery</h5>
          <p class="text-muted cw-mb-4">He must have tried it a hundred times, shut his eyes so that he wouldn't have to look at the floundering legs, and only stopped when he began to feel a mild, dull pain there that he had never felt before.</p>
        </div>
      </div>
    </div>
    <hr class="cw-hr">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Payment</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">Can I pay COD - cash on delivery?</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
          <h5 class="cw-h5">Payment methods accepted</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">What is Paypal?</h5>
          <p class="text-muted cw-mb-4">The bedding was hardly able to cover it and seemed ready to slide off any moment. His many legs, pitifully thin compared with the size of the rest of him, waved about helplessly as he looked. "What's happened to me?" he thought. It wasn't a dream.</p>
          <h5 class="cw-h5">How do the conversion rates work</h5>
          <p class="text-muted cw-mb-4">His room, a proper human room although a little too small, lay peacefully between its four familiar walls. A collection of textile samples lay spread out on the table.</p>
        </div>
      </div>
    </div>
    <hr class="cw-hr">
    <div class="cw-py-4">
      <h2 class="cw-h2 cw-mb-5 cw-text-primary">Warranty and return</h2>
      <div class="cw-row">
        <div class="cw-col-md-6">
          <h5 class="cw-h5">My product has a problem what should I do?</h5>
          <p class="text-muted cw-mb-4">Samsa was a travelling salesman - and above it there hung a picture that he had recently cut out of an illustrated magazine and housed in a nice, gilded frame.</p>
          <h5 class="cw-h5">What if the product is broken?</h5>
          <p class="text-muted cw-mb-4">He must have tried it a hundred times, shut his eyes so that he wouldn't have to look at the floundering legs, and only stopped when he began to feel a mild, dull pain there that he had never felt before.</p>
        </div>
        <div class="cw-col-md-6">
          <h5 class="cw-h5">Why should I buy insurance at the checkout?</h5>
          <p class="text-muted cw-mb-4">One morning, when Gregor Samsa woke from troubled dreams, he found himself transformed in his bed into a horrible vermin. He lay on his armour-like back, and if he lifted his head a little he could see his brown belly, slightly domed and divided by arches into stiff sections</p>
        </div>
      </div>
    </div>
  </div>
</section>

<h1>TODO: add contents from old IxTheo A-Z page</h1>
<ul>
    <li><a href="/Feedback/Form/AcquisitionRequest" target="_blank">Acquisition Request</a></li>
    <li><a href="docs/ixtheo-beacon.txt" target="_blank">BEACON</a><br/>Die mit der GND-Nummer ausgezeichneten Katalogisate des IxTheo stehen im BEACON-Format zur Verfügung und können in andere Datenbanken verlinkt werden.<br/>Weitere Infos siehe: <a href="https://de.wikipedia.org/wiki/Wikipedia:BEACON" target="_blank">Wikipedia</a> oder <a href="http://gbv.github.io/beaconspec/beacon.html" target="_blank">Github</a></li>
    <li><a href="docs/ixtheo-bible-search_de.pdf" target="_blank">Bibelstellensuche</a></li>
    <li><a href="docs/Bible_abbreviation.pdf" target="_blank">Bibelstellen: Abkürzungen</a></li>
    <li><a href="docs/ixtheo-pda.pdf" target="_blank">Benutzergesteuerte Erwerbung</a>
        <br/>c.f. PDA
        <br/>c.f. Acquisition Request
    </li>
    <li><a href="docs/ixtheo-serials.pdf" target="_blank">Erwerbung von Reihen</a><br/>Liste der Reihen und Fortsetzungen, die im Rahmen des FID Theologie dauerhaft und vollständig von der UB Tübingen gekauft werden.</li>
    <li><a href="docs/ixtheo-erschliessungskonzept.pdf" target="_blank">Erschließungskonzept</a><br/>Inhaltliches Erschließungskonzept für Monographien, Aufsätze etc.</li>
    <li><a href="/IxTheoClassification" target="_blank">IxTheo Classifikation</li>
    <li><a href="docs/ixtheo-journals.pdf" target="_blank">IxTheo-Zeitschriften</a><br/>Liste der momentan und zukünftig im IxTheo ausgewerteten Zeitschriften.</li>
    <li><a href="docs/ixtheo-pda.pdf" target="_blank">PDA</a><br/>NutzerInnen können den Kauf von Einzelmonographien, die an ihren Standorten nicht vorhanden bzw. nicht über Fernleihe beschaffbar sind, direkt im IxTheo veranlassen.</li>
    <li><a href="docs/TAD.pdf" target="_blank">TAD</a><br/>Lokaler Aufsatzlieferdienst (nur für WissenschaftlerInnen der Universität Tübingen).</li>
    <li><a href="docs/Zweitveroeffentlichung_Service.pdf" target="_blank">Zweitveröffentlichung</a><br><a href="docs/Zweitveroeffentlichung_FAQ.pdf" target="_blank">Frequently Asked Questions (FAQ) zu urheberrechtlichen Fragen bei der Zweitveröffentlichung.</li>
    <li><a href="docs/ZoteroGroup_Instruction_en.pdf" target="_blank">Instructions for cooperative cataloging using Zotero-Group.</a></li>
</ul>
