<div class="cw-row">
  <div class="cw-col-lg-8 cw-ml-lg-4">
    <div class="cw-text-block">
      <h1 class="cw-h1">Multilinguale Volltextsuche</h1>

      <p>Mit der IxTheo-Volltextsuche können theologisch relevante Volltexte aus verschiedenen Verlagen und aus Open Access-Quellen gleichzeitig durchsucht werden. Damit bietet IxTheo die Möglichkeit, <b>in einem großen Textkorpus nach bestimmten Stichwörtern und Phrasen</b> zu recherchieren.</p>

      <h3><b>Durchsuchbare Inhalte</b></h3>

      <p>Momentan können Publikationen der Verlage <b>Brill</b>, <b>Mohr Siebeck</b> und <b>Aschendorff</b> im Volltext durchsucht werden. Eine Integration der Monographien, Sammelbände, Lexika und Zeitschriften weiterer wichtiger theologischer Verlage ist geplant.</p>
      <p>Zugleich kann in umfangreichen Open Access -Inhalten recherchiert werden: Bei Werken aus den Digitalisierungsprojekten des IxTheo wird ebenfalls der gesamte Text durchsucht.</p>
      <p>Für zahlreiche weitere Publikationen stehen Inhaltsverzeichnisse, Literaturverzeichnisse und Zusammenfassungen zur Verfügung.</p>
      <p>Das durchsuchbare <b>Textkorpus</b> besteht zurzeit aus <b>ca. 300.000 Digitalisate</b>:</p>
      <ul>
        <li>Volltexte</li>
        <li>Abstracts</li>
        <li>Inhaltsverzeichnisse</li>
        <li>Literaturverzeichnisse</li>
      </ul>

      <h3><b>Suchoptionen</b></h3>

      <p>Die IxTheo-Volltextsuche bietet die Möglichkeit, nicht nur nach den konkret eingegebenen Begriffen, sondern auch nach <b>Synonyma</b> und deren <b>Übersetzungen</b> in mehrere Sprachen zu suchen.<br />Folgende Suchmodi stehen zur Verfügung:</p>
      <ol>
        <li>Volltexte ohne Synonyme</li>
        <li>Volltexte + Synonyme</li>
        <li>Volltexte + mehrsprachige Synonyme</li>
      </ol>
      <p>Die Suche kann auf einzelne <b>Texttypen</b> (Volltext, Inhaltsverzeichnis, Literaturverzeichnis, Zusammenfassung) eingeschränkt und mit den bekannten <b>IxTheo-Facetten</b> kombiniert werden.</p>
      <p>Neben der gleichzeitigen Recherche in allen vorhandenen Titeln ist es auch möglich, den Volltext eines ausgewählten Einzeltitels zu durchsuchen.</p>
    </div>
  </div>
</div>