<div class="cw-row">
  <div class="cw-col-lg-8 cw-ml-lg-4">
    <div class="cw-text-block"><br>
      <h1 class="cw-h1">IxTheo Open Journals</h1>

      <h3><b>Open Access-Zeitschriften Service</b></h3>

      <p>Wir bieten Herausgeber*innen die Möglichkeit ihre theologisch-wissenschaftlichen Zeitschriften oder Reihen <b>dauerhaft in Open Access zu hosten</b>. Neben der <b>Gründung neuer OA-Zeitschriften</b> begleiten wir auch die <b>Transformation</b> bisher gedruckter Publikationsorgane zu <b>Open Access</b>. <br> Hierfür stellen wir das Publikationsmanagementsystem <a href="https://pkp.sfu.ca/ojs/"> Open Journal Systems (OJS)</a> zur Verfügung, mit dem die Verwaltung des gesamten redaktionellen Prozesses bis hin zur Publikation bewerkstelligt werden kann.</p>
      <p>Die Zusammenarbeit mit „IxTheo Open Journals“ bietet folgende Vorteile:</p>
      <ul>
        <li>der FID Theologie / die Universitätsbibliothek Tübingen stellt die Software OJS <b>kostenlos</b> zur Verfügung, richtet die Zeitschrift bzw. Reihe ein, bietet <b>Schulung</b> und fortlaufenden <b>Support</b> an</li>
        <li>mit OJS können alle <b>Arbeitsschritte</b> von der <b>Einreichung</b> der Aufsätze, über <b>Peer-Review</b> bis hin zur <b>Publikation</b> mit einem System umgesetzt werden</li>
        <li><b>Layout</b> und <b>Design</b> einer OJS-Zeitschrift sind <b>individuell</b> anpassbar</li>
        <li>alle Zeitschriftenaufsätze erhalten einen Persistent Identifier (DOI), der eine <b>dauerhafte Auffindbarkeit weltweit</b> garantiert</li>
        <li>alle Zeitschriftenaufsätze werden in <b>IxTheo</b> nachgewiesen</li>
      </ul>
      <p>Dieses Angebot steht allen Herausgeber*innen von Zeitschriften und Reihen zur Verfügung. <br> Bei Interesse wenden Sie sich bitte an das <a href="mailto:ixtheo@ub.uni-tuebingen.de">IxTheo-Team</a>.</p>

      <h3><b>Open Access-Zeitschriften</b></h3>

      <!--<p>Sortierung nach Veröffentlichungsdatum | alphabetische Sortierung</p>-->

      <table class="ix-journals-table">
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/aabner.png" alt=""/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Advances in Ancient Biblical and Near Eastern Research</h3>
                  <p>
                    The journal is the first open-access and forum-peer-reviewed journal that covers the entire field of biblical studies and cognate fields in its diversity, and it is committed to the principles of the EABS in terms of equal opportunity, non-discrimination, and academic rigor. The journal will encompass all fields touching on and relevant for the study of both the Hebrew Bible and the New Testament, early Jewish and Christian studies, from ancient times to reception in the present. This journal innovates the way humanities scholarship is published, by utilizing an open peer-review system  known as "forum review."
                  </p>
                  <p><a href="https://aabner.org/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2748-6419&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2021-<br>ISSN: 2748-6419</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3 class="journals-title">Journal of European Baptist Studies</h3>
                  <p>
                    The Journal of European Baptist Studies (JEBS) was founded in 2000 by the International Baptist Theological Seminary (IBTS) in Prague, Czech Republic, to provide a means for promising new Baptist researchers to publish the results of their reflections on theology. The primary focus of the journal is on the implementation and application of research and reflection. Most of the contributions are from new or established researchers from within the European Baptist Federation region.
                  </p>
                  <p><a href="https://jebs.eu/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A1804-6444&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/ibtscentre.png" alt=""/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2019-<br>ISSN: 1804-6444</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/akademie.png" alt=""/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Im Dialog. Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart</h3>
                  <p>
                    Die Zeitschrift „Im Dialog“ versammelt Beiträge aus Diskussionen und Projekten der Akademie der Diözese Rottenburg-Stuttgart. Die Akademie arbeitet als Plattform für Gegenwarts- und Zukunftsfragen. Sie organisiert und moderiert Netzwerke und fachliche Diskurse als ein interdisziplinäres Dialogforum mit Partnern aus Wissenschaft und unterschiedlichsten Praxisfeldern. Sie positioniert Themen mit nachhaltiger Relevanz, auch quer zum Mainstream.
                  </p>
                  <p><a href="https://imdialog.akademie-rs.de/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2698-5446&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2019-<br>ISSN: 2698-5446</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3>Journal of Ethics in Antiquity and Christianity (JEAC)</h3>
                  <p>
                    Die Open Access Zeitschrift „Journal of Ethics in Antiquity and Christianity (JEAC)“ etabliert einen Dialog zwischen exegetischen, judaistischen und patristischen Beiträgen mit philosophischen und systematisch-theologischen Ansätzen zu gegenwartsrelevanten ethischen Fragestellungen und bringt damit die ethischen Dimensionen antiker Texte in die gegenwärtigen Ethikdiskurse ein.
                  </p>
                  <p><a href="https://jeac.de/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2627-6062&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/jeac.png" alt=""/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2019-<br>ISSN: 2627-6062</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/iapt.png" alt=""/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>International Academy of Practical Theology. Conference Series (IAPT.CS)</h3>
                  <p>
                    The “International Academy of Practical Theology. Conference Series” (IAPT.CS) provides documentation of the bi-annual conferences of the Academy for scholars and interested readers around the world.
                  </p>
                  <p>
                    This way, the Conference Series shares the values and goals of the International Academy of Practical Theology to promote the study of and critical reflection on practical theological thought and action – bearing in mind the various historical and cultural contexts in which practical theology is done.
                  </p>
                  <p><a href="https://iapt-cs.org/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2628-0000&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2019-<br>ISSN: 2628-0000</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td colspan="2" rowspan="2" class="text-td">
                  <h3>Vulgata in Dialogue. A biblical online review</h3>
                  <p>
                    Vulgata in Dialogue wurde 2016 gegründet. Der inhaltliche Schwerpunkt liegt auf der Veröffentlichung von Artikeln zur Bibelexegese oder über theologische, sprachwissenschaftliche, historische und interdisziplinäre Themen, die einen direkten oder indirekten Bezug zur Biblia Sacra Vulgata haben.
                  </p>
                  <p><a href="https://vulgata-dialog.ch/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2504-5156&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/vulgata.png" alt=""/>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2017-<br>ISSN: 2504-5156</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
        <tr>
          <td>
            <table border="1">
              <tr>
                <td class="img-td">
                  <img src="/themes/ixtheo2/images/journals/eug.png" alt=""/>
                </td>
                <td rowspan="2" class="text-td">
                  <h3>Ethik und Gesellschaft (EuG)</h3>
                  <p>
                    Ethik und Gesellschaft publiziert zweimal im Jahr zu Themen der theologischen Sozialethik. Die Beiträge erscheinen in Themenheften  und beleuchten den jeweiligen Themenschwerpunkt aus unterschiedlicher Perspektive und tragen so zu dessen umfassenden und interdisziplinären Bearbeitung bei.
                  </p>
                  <p><a href="https://www.ethik-und-gesellschaft.de/">Link zur Zeitschrift</a> | <a href="<?=$this->url('search-results')?>?lookfor=issn%3A2628-0000&type=AllFields&sort=year+desc%2C+volume_sort+desc%2C+issue_sort+desc%2C+start_page+asc%2C+first_indexed+desc&botprotect=">Alle Artikel im IxTheo</a></p>
                </td>
              </tr>
              <tr>
                <td class="text-td">
                  <p>Publikation: 2007-<br>ISSN: 2628-0000</p>
                </td>
              </tr>
            </table>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>
