; This file is equivalent to EDS.ini, but is applied to EPF records instead.
; See EDS.ini for more info.

[Field_Items]
overrideContext['core'] = CoreItems
overrideContext['result-list'] = ResultListItems

[CoreItems]
extraLineOptions[] = 'GlobalAuthors'
extraLineOptions[] = 'GlobalSubjects'
separator = '<br>'

[ResultListItems]
extraLineOptions[] = 'GlobalAuthors'
extraLineOptions[] = 'ResultListAuthors'
extraLineOptions[] = 'GlobalSubjects'

[GlobalAuthors]
lineIdentifierKey = 'Group'
lineIdentifierValue = 'Au'
useSearchLink = true
searchLinkType = 'author'
elementPrefix = '<span class="author">'
elementSuffix = '</span>'
separator = '; '
abbreviation = 'more_authors_abbrev'
abbreviationPrefix = ' '

[GlobalSubjects]
lineIdentifierKey = 'Group'
lineIdentifierValue = 'Su'
useSearchLink = true

[ResultListAuthors]
lineIdentifierKey = 'Group'
lineIdentifierValue = 'Au'
multiAltDataMethod = 'getPrimaryAuthorsWithHighlighting'
limit = 3
