<?php
return [
    'extends' => 'bootstrap3',
    'helpers' => [
        'factories' => [
            'Finna\View\Helper\Root\AuthorizationNote' => 'Finna\View\Helper\Root\Factory::getAuthorizationNote',
            'Finna\View\Helper\Root\Autocomplete' => 'Finna\View\Helper\Root\Factory::getAutocomplete',
            'Finna\View\Helper\Root\Browse' => 'Finna\View\Helper\Root\Factory::getBrowse',
            'Finna\View\Helper\Root\Callnumber' => 'Finna\View\Helper\Root\Factory::getCallnumber',
            'Finna\View\Helper\Root\Citation' => 'Finna\View\Helper\Root\Factory::getCitation',
            'Finna\View\Helper\Root\CheckboxFacetCounts' => 'Finna\View\Helper\Root\Factory::getCheckboxFacetCounts',
            'Finna\View\Helper\Root\Combined' => 'Finna\View\Helper\Root\Factory::getCombined',
            'Finna\View\Helper\Root\Content' => 'Finna\View\Helper\Root\Factory::getContent',
            'Finna\View\Helper\Root\EDS' => 'Finna\View\Helper\Root\Factory::getEDS',
            'Finna\View\Helper\Root\Feed' => 'Finna\View\Helper\Root\Factory::getFeed',
            'Finna\View\Helper\Root\FileSrc' => 'Finna\View\Helper\Root\Factory::getFileSrc',
            'Finna\View\Helper\Root\FinnaSurvey' => 'Finna\View\Helper\Root\Factory::getFinnaSurvey',
            'Finna\View\Helper\Root\Header' => 'Finna\View\Helper\Root\Factory::getHeader',
            'FinnaTheme\View\Helper\HeadLink' => 'FinnaTheme\View\Helper\Factory::getHeadLink',
            'FinnaTheme\View\Helper\HeadScript' => 'FinnaTheme\View\Helper\Factory::getHeadScript',
            'Finna\View\Helper\Root\HeadTitle' => 'Finna\View\Helper\Root\Factory::getHeadTitle',
            'Finna\View\Helper\Root\HoldingsSettings' => 'Finna\View\Helper\Root\Factory::getHoldingsSettings',
            'Finna\View\Helper\Root\ImageSrc' => 'Finna\View\Helper\Root\Factory::getImageSrc',
            'Finna\View\Helper\Root\TotalIndexed' => 'Finna\View\Helper\Root\Factory::getTotalIndexed',
            'Finna\View\Helper\Root\LayoutClass' => 'Finna\View\Helper\Root\Factory::getLayoutClass',
            'Finna\View\Helper\Root\MetaLib' => 'Finna\View\Helper\Root\Factory::getMetaLib',
            'Finna\View\Helper\Root\Navibar' => 'Finna\View\Helper\Root\Factory::getNavibar',
            'Finna\View\Helper\Root\OnlinePayment' => 'Finna\View\Helper\Root\Factory::getOnlinePayment',
            'Finna\View\Helper\Root\OpenUrl' => 'Finna\View\Helper\Root\Factory::getOpenUrl',
            'Finna\View\Helper\Root\OrganisationInfo' => 'Finna\View\Helper\Root\Factory::getOrganisationInfo',
            'Finna\View\Helper\Root\OrganisationsList' => 'Finna\View\Helper\Root\Factory::getOrganisationsList',
            'Finna\View\Helper\Root\Piwik' => 'Finna\View\Helper\Root\Factory::getPiwik',
            'Finna\View\Helper\Root\Primo' => 'Finna\View\Helper\Root\Factory::getPrimo',
            'Finna\View\Helper\Root\ProxyUrl' => 'Finna\View\Helper\Root\Factory::getProxyUrl',
            'Finna\View\Helper\Root\Recaptcha' => 'Finna\View\Helper\Root\Factory::getRecaptcha',
            'Finna\View\Helper\Root\Record' => 'Finna\View\Helper\Root\Factory::getRecord',
            'Finna\View\Helper\Root\RecordDataFormatter' => 'Finna\View\Helper\Root\RecordDataFormatterFactory',
            'Finna\View\Helper\Root\RecordImage' => 'Finna\View\Helper\Root\Factory::getRecordImage',
            'Finna\View\Helper\Root\RecordLink' => 'Finna\View\Helper\Root\Factory::getRecordLink',
            'Finna\View\Helper\Root\ScriptSrc' => 'Finna\View\Helper\Root\Factory::getScriptSrc',
            'Finna\View\Helper\Root\SearchBox' => 'Finna\View\Helper\Root\Factory::getSearchBox',
            'Finna\View\Helper\Root\SearchMemory' => 'Finna\View\Helper\Root\Factory::getSearchMemory',
            'Finna\View\Helper\Root\SearchTabs' => 'Finna\View\Helper\Root\Factory::getSearchTabs',
            'Finna\View\Helper\Root\SearchTabsRecommendations' => 'Finna\View\Helper\Root\Factory::getSearchTabsRecommendations',
            'Finna\View\Helper\Root\Summon' => 'Finna\View\Helper\Root\Factory::getSummon',
            'Finna\View\Helper\Root\SystemMessages' => 'Finna\View\Helper\Root\Factory::getSystemMessages',
            'Finna\View\Helper\Root\Translation' => 'Finna\View\Helper\Root\Factory::getTranslation',

            'Finna\View\Helper\Root\Barcode' => 'Finna\View\Helper\Root\Factory::getBarcode',
            'Finna\View\Helper\Root\Markdown' => 'Finna\View\Helper\Root\Factory::getMarkdown',
            'Finna\View\Helper\Root\OrganisationDisplayName' => 'Finna\View\Helper\Root\Factory::getOrganisationDisplayName',
            'Finna\View\Helper\Root\PersonaAuth' => 'Finna\View\Helper\Root\Factory::getPersonaAuth',
            'Finna\View\Helper\Root\ResultFeed' => 'Finna\View\Helper\Root\Factory::getResultFeed',
            'Finna\View\Helper\Root\Search' => 'Finna\View\Helper\Root\Factory::getSearch',
            'Finna\View\Helper\Root\StreetSearch' => 'Finna\View\Helper\Root\Factory::getStreetSearch',
            'Finna\View\Helper\Root\TranslationEmpty' => 'Finna\View\Helper\Root\Factory::getTranslationEmpty',
            'Finna\View\Helper\Root\TruncateUrl' => 'Finna\View\Helper\Root\Factory::getTruncateUrl',
            'Finna\View\Helper\Root\UserPublicName' => 'Finna\View\Helper\Root\Factory::getUserPublicName',
        ],
        'aliases' => [
            'authorizationNote' => 'Finna\View\Helper\Root\AuthorizationNote',
            'autocomplete' => 'Finna\View\Helper\Root\Autocomplete',
            'barcode' => 'Finna\View\Helper\Root\Barcode',
            'callnumber' => 'Finna\View\Helper\Root\Callnumber',
            'checkboxFacetCounts' => 'Finna\View\Helper\Root\CheckboxFacetCounts',
            'combined' => 'Finna\View\Helper\Root\Combined',
            'content' => 'Finna\View\Helper\Root\Content',
            'eds' => 'Finna\View\Helper\Root\EDS',
            'feed' => 'Finna\View\Helper\Root\Feed',
            'fileSrc' => 'Finna\View\Helper\Root\FileSrc',
            'finnaSurvey' => 'Finna\View\Helper\Root\FinnaSurvey',
            'header' => 'Finna\View\Helper\Root\Header',
            'headLink' => 'FinnaTheme\View\Helper\HeadLink',
            'headScript' => 'FinnaTheme\View\Helper\HeadScript',
            'headTitle' => 'Finna\View\Helper\Root\HeadTitle',
            'holdingsSettings' => 'Finna\View\Helper\Root\HoldingsSettings',
            'imageSrc' => 'Finna\View\Helper\Root\ImageSrc',
            'indexedTotal' => 'Finna\View\Helper\Root\TotalIndexed',
            'markdown' => 'Finna\View\Helper\Root\Markdown',
            'metaLib' => 'Finna\View\Helper\Root\MetaLib',
            'navibar' => 'Finna\View\Helper\Root\Navibar',
            'onlinePayment' => 'Finna\View\Helper\Root\OnlinePayment',
            'organisationInfo' => 'Finna\View\Helper\Root\OrganisationInfo',
            'organisationDisplayName' => 'Finna\View\Helper\Root\OrganisationDisplayName',
            'organisationsList' => 'Finna\View\Helper\Root\OrganisationsList',
            'personaAuth' => 'Finna\View\Helper\Root\PersonaAuth',
            'primo' => 'Finna\View\Helper\Root\Primo',
            'recordImage' => 'Finna\View\Helper\Root\RecordImage',
            'resultfeed' => 'Finna\View\Helper\Root\ResultFeed',
            'scriptSrc' => 'Finna\View\Helper\Root\ScriptSrc',
            'search' => 'Finna\View\Helper\Root\Search',
            'searchbox' => 'Finna\View\Helper\Root\SearchBox',
            'searchMemory' => 'Finna\View\Helper\Root\SearchMemory',
            'searchTabsRecommendations' => 'Finna\View\Helper\Root\SearchTabsRecommendations',
            'streetSearch' => 'Finna\View\Helper\Root\StreetSearch',
            'systemMessages' => 'Finna\View\Helper\Root\SystemMessages',
            'translation' => 'Finna\View\Helper\Root\Translation',
            'translationEmpty' => 'Finna\View\Helper\Root\TranslationEmpty',
            'truncateUrl' => 'Finna\View\Helper\Root\TruncateUrl',
            'userPublicName' => 'Finna\View\Helper\Root\UserPublicName',

            // Overrides
            'VuFind\View\Helper\Root\Browse' => 'Finna\View\Helper\Root\Browse',
            'VuFind\View\Helper\Root\Citation' => 'Finna\View\Helper\Root\Citation',
            'VuFind\View\Helper\Root\OpenUrl' => 'Finna\View\Helper\Root\OpenUrl',
            'VuFind\View\Helper\Root\Piwik' => 'Finna\View\Helper\Root\Piwik',
            'VuFind\View\Helper\Root\ProxyUrl' => 'Finna\View\Helper\Root\ProxyUrl',
            'VuFind\View\Helper\Root\Recaptcha' => 'Finna\View\Helper\Root\Recaptcha',
            'VuFind\View\Helper\Root\Record' => 'Finna\View\Helper\Root\Record',
            'VuFind\View\Helper\Root\RecordDataFormatter' => 'Finna\View\Helper\Root\RecordDataFormatter',
            'VuFind\View\Helper\Root\RecordLink' => 'Finna\View\Helper\Root\RecordLink',
            'VuFind\View\Helper\Root\SearchTabs' => 'Finna\View\Helper\Root\SearchTabs',
            'VuFind\View\Helper\Root\Summon' => 'Finna\View\Helper\Root\Summon',
            'VuFind\View\Helper\Bootstrap3\LayoutClass' => 'Finna\View\Helper\Root\LayoutClass',
            'VuFind\View\Helper\Bootstrap3\Recaptcha' => 'Finna\View\Helper\Root\Recaptcha',

            // Aliases for non-standard cases
            'Combined' => 'combined',
            'KeepAlive' => 'keepAlive',
            'MetaLib' => 'metaLib',
            'Primo' => 'primo',
            'proxyurl' => 'proxyUrl',
            'searchtabs' => 'searchTabs',
            'transesc' => 'transEsc',
        ]
    ],
    'css' => [
        'vendor/dataTables.bootstrap.min.css',
        'vendor/magnific-popup.min.css',
        'dataTables.bootstrap.custom.css',
        'vendor/slick.css',
        'vendor/slick-theme.css',
        'vendor/bootstrap-multiselect.min.css',
        'vendor/bootstrap-datepicker3.min.css',
        'vendor/video-js.min.css',
        'vendor/bootstrap-slider.min.css',
        'finna.css',
        'vendor/priority-nav-core.css',
        'finna-flex-fallback.css::lt IE 10', // flex polyfill
        'vendor/leaflet.css',
        'vendor/leaflet.draw.css'
    ],
    'js' => [
        'vendor/event-stub.js:lt IE 9',
        'finna.js',
        'finna-autocomplete.js',
        'finna-combined-results.js',
        'finna-image-popup.js',
        'finna-adv-search.js',
        'finna-daterange-vis.js',
        'finna-feed.js',
        'finna-layout.js',
        'finna-openurl.js',
        'finna-common.js',
        'finna-map.js',
        'finna-map-facet.js',
        'vendor/jquery.dataTables.min.js',
        'vendor/dataTables.bootstrap.min.js',
        'vendor/jquery.inview.min.js',
        'vendor/jquery.magnific-popup.min.js',
        'vendor/jquery.cookie-1.4.1.min.js',
        'vendor/slick.min.js',
        'vendor/video.min.js',
        'vendor/dash.all.min.js',
        'vendor/videojs-dash.min.js',
        'vendor/videojs-contrib-hls.min.js',
        'vendor/videojs.hotkeys.min.js',
        'vendor/jquery.touchSwipe.min.js',
        'vendor/bootstrap-multiselect.min.js',
        'vendor/bootstrap-slider.min.js',
        'vendor/gauge.min.js',
        'vendor/priority-nav.min.js',
        'vendor/leaflet.min.js',
        'vendor/leaflet.draw.min.js',
    ],
    'less' => [
        'active' => false
    ],
    'favicon' => 'favicon.ico',
];
