<!-- START of: finna - RecordDriver/Primo/core.phtml -->
<div vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">

  <?php // if you have a preview tab but want to move or remove the preview link
      // from this area of the record view, this can be split into
      // getPreviewData() (should stay here) and
      // getPreviewLink() (can go in your desired tab) ?>
  <?=$this->record($this->driver)->getPreviews()?>

  <div>
    <div class="visible-print inline-block">
      <?php /* Display qrcode if appropriate: */ ?>
      <?php $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>
    </div>
    <h1 property="name" class="record-title"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>

    <?=$this->render('record/labels.phtml', ['labels' => $this->driver->getRecordLabels()]); ?>

    <?php
      $openUrl = $this->openUrl($this->driver, 'record');
      $openUrlActive = $openUrl->isActive();
      // Account for replace_other_urls setting
      $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    ?>

    <?php if (!empty($urls) || $openUrlActive): ?>
      <div class="recordURLs primo-available-online-record">
        <?=$this->partial('RecordDriver/Primo/online-url-list.phtml', ['driver' => $this->driver, 'urls' => $urls])?>
        <?php if ($openUrlActive): ?>
          <?=$openUrl->renderTemplate()?>
        <?php endif; ?>
      </div>
    <?php endif; ?>
    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <div class="truncate-field wide">
        <p class="summary"><?=$summary;?></p>
      </div>
    <?php endif; ?>

    <div class="record-core-metadata">
      <?php $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <div><?=$this->record($this->driver)->getFormatList()?></div>
      <?php endif; ?>
      <?php if ($authors = $this->driver->getCreators()): ?>
        <?php foreach ($authors as $i => $field): ?><?=($i > 0) ? ' ; ' : ''?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><?php endforeach; ?>
      <?php endif; ?>
      <?php
        $journalTitle = $this->driver->getContainerTitle();
        $summDate = $this->driver->getPublicationDates();
      ?>
      <?php if (!empty($journalTitle)): ?>
        <?=$this->transEsc('Published in')?>:
          <?php
            $containerSource = $this->driver->getSourceIdentifier();
            $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <?php $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
      <?php elseif (!empty($summDate)): ?>
        <?=$this->escapeHtml($summDate[0])?>
      <?php endif; ?>
    </div>

    <?/* Display Main Details */?>
    <div class="record-details">
      <?php
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->getData(
            $driver, $formatter->filterPrimoFields($formatter->getDefaults('core'))
        );
      ?>
      <?php if (!empty($coreFields)): ?>
        <table class="table table-finna-record record-details">
          <?=$this->record($this->driver)->renderTemplate('core-fields.phtml', ['coreFields' => $coreFields]);?>
        </table>
      <?php endif; ?>
      <?=$openUrl ? $openUrl->renderMoreOptions() : '' ?>
    </div>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>
    <?/* End Main Details */?>

    <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
    <div>
      <?=$this->render($template)?>
    </div>
    <?php endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/Primo/core.phtml -->
