<?php
  $broadcasts = $this->notifications()->getBroadcasts(true);
?>
<div class="container">
  <div class="broadcast_wrapper_global">
    <?php foreach($broadcasts as $broadcast_id => $broadcast): ?>
      <span class="broadcast" style="background-color:<?=$broadcast['background_color_value']?>; border-color:<?=$broadcast['border_color_value']?>;">
        <?=$broadcast['content']?>
      </span>
    <?php endforeach; ?>
  </div>
</div>