<?php
  $pages = $this->notifications()->getPages();
?>
<ul class="nav navbar-nav navbar-left flip">
  <?php foreach($pages as $page): ?>
    <?php if($page['is_external_url']): ?>
      <li class="nav-item"><a class="nav-link" href="<?=$page['external_url']?>" target="_blank"><?=strip_tags($page['nav_title'])?></a></li>
    <?php else: ?>
      <li class="nav-item"><a class="nav-link" href="<?=$this->url('notifications-page')?>?page_id=<?=$page['page_id']?>"><?=strip_tags($page['nav_title'])?></a></li>
    <?php endif; ?>
  <?php endforeach; ?>
</ul>