<?php
  if ($data) {
    $helper = $this->record($this->driver);
    $additional = $helper->getAuthorityLinkAdditionalData(['date', 'role']);
  }
?>
<?php foreach ($data as $relation): ?>
  <?=$helper->getAuthorityLinkElement('author', $relation['name'], $relation, ['authorityType' => $relation['type'] ?? null, 'additional' => $additional, 'searchAction' => 'search-results'])?>
<?php endforeach; ?>
