<?=$this->doctype('XHTML1_TRANSITIONAL')?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="<?=$this->layout()->userLang?>" xml:lang="en">
  <head>
    <?$this->headThemeResources()?>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?
      // Set global path for Javascript code:
      $this->headScript()->prependScript("path = '" . rtrim($this->url('home'), '/') . "';");
    ?>        
    <?=$this->headScript()?>
  </head>
  <body>
    <div class="container">
      <div class="header clearfix">
        <?=$this->render('header.phtml')?>
        <? // Set up the search box -- there are three possible cases:
          // 1. No search box was set; we should default to the normal box
          // 2. It was set to false; we should display nothing
          // 3. It is set to a custom string; we should display the provided version
          // Set up default search box if no data was provided from the template;
          // this covers case 1.  Cases 2 and 3 are then covered by logic below.
          if (!isset($this->layout()->searchbox)) {
            $this->layout()->searchbox = $this->render('search/searchbox.phtml');
          }
        ?>
      </div>
      <? if ($this->layout()->searchbox !== false): ?>
        <div class="searchbox">
          <?=$this->layout()->searchbox?>
        </div>
      <? endif; ?>
      <? if((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true) && $this->layout()->breadcrumbs !== false): ?>
        <ul class="breadcrumb">
        <? if(is_array($this->layout()->breadcrumbs)): ?>
          <? if(count($this->layout()->breadcrumbs) > 1): ?>
            <?=$this->render('breadcrumbs/multi.phtml', array(
                'parents' => $this->layout()->breadcrumbs,
                'title'   => $this->layout()->title,
                'end'     => $this->layout()->breadcrumbEnd,
                'from'    => $this->layout()->from
              )) ?>
          <? else: ?>
            <li><a href="<?=$this->url('home')?>"><?=$this->transEsc('Home')?></a> <span class="divider">&gt;</span></li>
            <li><?=$this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span></li>') ?>
            <li><a href="<?=$this->url('vudl-default-collection')?>"><?=$this->transEsc('Collections') ?></a> <span class="divider">&gt;</span></li>
            <? $current = $this->layout()->breadcrumbs; ?>
            <? $current = current($current); ?>
            <? if($current): ?>
              <? foreach(array_reverse($current) as $id=>$parent): ?>
                <li><a href="<?=$this->url('collection', array('id'=>$id)) ?>"><?=$parent ?></a> <span class="divider">&gt;</span></li>
              <? endforeach; ?>
            <? endif; ?>
            <li class="active"><?=$this->layout()->title ?></li>
          <? endif; ?>
        <? else: ?>
          <li class="active"><a href="<?=$this->url('vudl-home') ?>"><?=$this->transEsc('Home')?></a> <span class="divider">&gt;</span></li>
          <?=$this->layout()->breadcrumbs ?>
        <? endif; ?>
        </ul>
      <? endif; ?>
      <div class="main row-fluid">
        <?=$this->layout()->content?>
      </div>
      <div class="footer">
        <?=$this->render('footer.phtml')?>
        <?=$this->layout()->poweredBy?>
      </div>
    </div>
    <!-- MODAL IN CASE WE NEED ONE -->
    <div id="modal" class="modal hide fade">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h3></h3>
      </div>
      <div class="modal-body">
        <p>Loading...</p>
      </div>
    </div>
    <script type="text/javascript">
      // Reset Content
      $('#modal').on('hidden', function() {
        $(this).removeData('modal');
      });
    </script>
    <?=$this->googleanalytics()?>
  </body>
</html>