<!-- START of: finna - record/view.phtml -->
<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  $this->headScript()->appendFile("finna-comments.js");
  if ($this->record($this->driver)->ratingAllowed()) {
     $this->headScript()->appendFile('vendor/bootstrap-rating.min.js');
     $this->headLink()->appendStylesheet('vendor/bootstrap-rating.min.css');
  }
  if (in_array($this->driver->getSourceIdentifier(), ['MetaLib', 'Primo'])) {
    $this->headScript()->appendFile("finna-bx.js");
  }
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';

  $this->layout()->title = $this->driver->getShortTitle();

  $this->headMeta()->appendName('format-detection', 'telephone=no');

  // Set page title.
  $dataSource = $this->driver->tryMethod('getDataSource');
  $headText = $this->driver->getBreadcrumb() . (isset($dataSource) ? ' | ' . $this->transEsc('default::source_'. $dataSource, null, $dataSource) : '');
  $this->headTitle($headText);
?>
</div>
<div class="container-fluid record-view-header">
 <div class="container">
  <div class="row">
    <div class="col-xs-4 col-sm-5 hidden-print">
    <?
      $html = '<span class="btn btn-primary"><i class="fa fa-arrow-left"></i> <i class="fa fa-search"></i></span>';
      $html .= '<span class="back-to-search-text hidden-xs">'.$this->transEsc('Back to search results').'</span>';
      $previousSearch = $this->searchMemory()->getLastSearchLink($html);
      if ($previousSearch !== ''):
    ?>
      <div class="back-to-search"><?=$previousSearch?></div>
    <? endif; ?>
    </div>
    <div class="col-xs-8 col-sm-7">
    <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
      <ul class="pager hidden-print" id="view-pager">
      <? if ($this->scrollData['previousRecord']): ?>
        <li class="pager-previous-record">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Record')?>" rel="nofollow"><i class="fa fa-arrow-left"></i></a>
        </li>
        <? else: ?>
        <li class="disabled" title="<?=$this->transEsc('First Record')?>"><a href=""><i class="fa fa-arrow-left"></i></a></li>
      <? endif; ?>
        <li class="pager-text"><?=$this->localizedNumber($this->scrollData['currentPosition']) . ' / ' . $this->localizedNumber($this->scrollData['resultTotal']) ?></li>
      <? if ($this->scrollData['nextRecord']): ?>
        <li class="pager-next-record">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Record')?>" rel="nofollow"><i class="fa fa-arrow-right"></i></a>
        </li>
      <? else: ?>
        <li class="disabled" title="<?=$this->transEsc('Last Record')?>"><a href="#"><i class="fa fa-arrow-right"></i></a></li>
      <? endif; ?>
      </ul>
      <? endif; ?>
    </div>
  </div>
 </div>
</div>
<div class="container">
<div class="row record-row">
  <div class="col-xs-12">
      <?=$this->record($this->driver)->getToolbar()?>
  </div>
  <div class="col-sm-9">
    <div class="record source<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getMetaTags();?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>

    <? // N.B. The element/class structure here is important for the ajax tabs to work properly ?>
    <div class="record-tabs">
      <? if (count($this->tabs) > 0): ?>
        <a name="tabnav"></a>
        <? if (count($this->tabs) > 3): ?>
          <div class="tabs-responsive">
        <? endif; ?>
        <ul class="recordTabs nav nav-tabs">
          <? foreach ($this->tabs as $tab => $obj): ?>
            <? // add current tab to breadcrumbs if applicable:
              $desc = $obj->getDescription();
              $tab_classes = array();
              if (0 === strcasecmp($this->activeTab, $tab)) {
                if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                  $tab_classes[] = 'active';
                }
                $tab_classes[] = 'initiallyActive';
                $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
                $activeTabObj = $obj;
              }
              if (!$obj->isVisible()) { $tab_classes[] = 'hidden'; }
              if (!$obj->supportsAjax()) { $tab_classes[] = 'noajax'; }
              if (strtolower($tab) == 'details') { $tab_classes[] = 'hidden-xs'; }
            ?>
            <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
            <a class="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><i class="fa fa-<?=$this->escapeHtmlAttr($tab)?>"></i> <?=$this->transEsc($desc)?><? if (strtolower($tab) == 'usercomments') : ?>(<span class="count"><?= count($this->driver->getComments()) ?></span>)<? endif; ?></a>
          </li>
          <? endforeach; ?>
        </ul>
        <? if (count($this->tabs) > 3): ?>
          </div>
        <? endif; ?>
      <? endif; ?>

      <div class="tab-content">
        <? if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
          <div class="tab-pane active <?=$this->activeTab ?>-tab">
            <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
          </div>
        <? endif; ?>
      </div>
    </div>

    <?=$this->driver->supportsCoinsOpenURL()?'<span class="Z3988" title="'.$this->escapeHtmlAttr($this->driver->getCoinsOpenURL()).'"></span>':''?>
  </div>

  <div class="col-sm-3 sidebar">
    <? if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr' && $this->driver->getRecordType() != 'lido' && $this->driver->getRecordType() != 'ead'): ?>
      <?=$this->render('record/record-organisation-menu.phtml') ?>
    <? endif; ?>
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
    <? if (in_array($this->driver->getSourceIdentifier(), ['MetaLib', 'Primo'])): ?>
      <div id="bx-recommendations-holder">
      </div>
    <? endif; ?>
    <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-recommendations")): ?>
      <div class="row">
        <div class="col-xs-12">
          <?=$this->render($template)?>
        </div>
      </div>
    <? endif; ?>
  </div>
 </div>
</div>
<?=$this->partial('RecordDriver/SolrDefault/toolbar_mobile.phtml') ?>
<div>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET') ?>
<!-- END of: finna - record/view.phtml -->
