<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
    '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> ';

  $this->layout()->title = $this->driver->getShortTitle();
?>

</div>
<div class="container-fluid record-view-header">
 <div class="container">
  <div class="row">
    <div class="col-xs-5">
    <?
      $html = '<span class="btn btn-primary"><i class="fa fa-arrow-left"></i> <i class="fa fa-search"></i></span>';
      $html .= '<span class="back-to-search-text hidden-xs">'.$this->transEsc('Back to search results').'</span>';
      $previousSearch = $this->getLastSearchLink($html);
      if ($previousSearch !== ''):
    ?>
      <div class="back-to-search"><?=$previousSearch?></div>
    <? endif; ?>
    </div>
    <div class="col-xs-7">
    <? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
      <ul class="pager hidden-print" id="view-pager">
      <? if ($this->scrollData['previousRecord']): ?>
        <li class="pager-previous-record">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>#searchForm" title="<?=$this->transEsc('Previous Record')?>"><i class="fa fa-arrow-left"></i></a>
        </li>
        <? else: ?>
        <li class="disabled" title="<?=$this->transEsc('First Record')?>"><a href="#searchform"><i class="fa fa-arrow-left"></i></a></li>
      <? endif; ?>
        <li class="pager-text"><?=$this->localizedNumber($this->scrollData['currentPosition']) . ' / ' . $this->localizedNumber($this->scrollData['resultTotal']) ?></li>
      <? if ($this->scrollData['nextRecord']): ?>
        <li class="pager-next-record">
          <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>#searchForm" title="<?=$this->transEsc('Next Record')?>"><i class="fa fa-arrow-right"></i></a>
        </li>
      <? else: ?>
        <li class="disabled" title="<?=$this->transEsc('Last Record')?>"><a href="#"><i class="fa fa-arrow-right"></i></a></li>
      <? endif; ?>
      </ul>
      <? endif; ?>
    </div>
  </div>
 </div>
</div>
<div class="container">
<div class="row record-row">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
      <?=$this->flashmessages()?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
      <?=$this->record($this->driver)->getToolbar()?>
    </div>

    <? if (count($this->tabs) > 0): ?>
      <a name="tabnav"></a>
      <ul class="recordTabs nav nav-tabs">
        <? foreach ($this->tabs as $tab => $obj): ?>
        <? // add current tab to breadcrumbs if applicable:
          $desc = $obj->getDescription();
          $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
          if ($isCurrent) {
            $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
            $activeTabObj = $obj;
          }
          $tab_classes = array();
          if ($isCurrent) $tab_classes[] = 'active';
          if (!$obj->isVisible()) $tab_classes[] = 'hidden';
        ?>
        <li<?=count($tab_classes) > 0 ? ' class="' . implode(' ', $tab_classes) . '"' : ''?>>
          <a id="<?=strtolower($tab) ?>" href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><i class="fa fa-<?=$this->escapeHtmlAttr($tab)?>"></i> <?=$this->transEsc($desc)?></a>
        </li>
        <? endforeach; ?>
      </ul>
    <? endif; ?>

    <div class="tab-content" id="record-tabs">
      <div class="tab-pane active" id="<?=$this->activeTab ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    </div>

    <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
  </div>

  <div class="<?=$this->layoutClass('sidebar')?>">
    <? if ($this->resolver('record/record-organisation-menu.phtml') && $this->escapeHtmlAttr($this->driver->getResourceSource()) == 'VuFind' ): ?>
      <?=$this->render('record/record-organisation-menu.phtml') ?>
    <? endif; ?>
    <? foreach ($this->related()->getList($this->driver) as $current): ?>
      <?=$this->related()->render($current)?>
    <? endforeach; ?>
  </div>
 </div>
</div>
<div>

