<?php
  $this->headTitle($this->translate('Add Notice'));

  $this->breadcrumbs()->set($this->translate('Admin'), $this->url('admin'))
    ->add($this->translate('Notices'), $this->url('admin/notices'));
    ->add($this->translate('Add'), active: true);
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h1><?=$this->transEsc('Add Notice')?></h1>
  <?=$this->flashmessages()?>
  <?=$this->partial('form', ['formData' => $this->formData])?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->section('AdminMenu', template: 'admin/menu.phtml')->render()?>
</div>
