<?=$this->layout()->content?>
<?=$this->piwik(['lightbox' => true])?>
<?=$this->matomo(['context' => $this->layoutContext ?? 'lightbox'])?>
<?=$this->googleanalytics($this->serverUrl(true))?>
<?php if ($this->session()->put('reset_account_status', null) && $this->auth()->getManager()->ajaxEnabled()) {
  $this->inlineScript()->setAllowArbitraryAttributes(true);
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'VuFind.account.clearAllCaches();', 'SET', ['data-lightbox-run' => 'always']);
}
