<?php
  $__attributes = $this->htmlAttributes($attributes ?? []);
  if (isset($ariaLabel)) {
    $__attributes['aria-label'] = $ariaLabel;
  }
?>
<nav<?= $__attributes->add('class', ['finna-navbar-component', 'navbar', 'navbar-expand-md']) ?>>
  <div class="container-fluid">
    <div class="navbar-header">
      <?php if (isset($brandContent)): ?>
        <span class="navbar-brand">
          <?php if (isset($brandLink)): ?><a href="<?= $brandLink ?>"><?php endif; ?>
          <?php if (isset($brandSrOnly)): ?><span class="visually-hidden"><?= $brandSrOnly ?></span><?php endif; ?>
          <?= $brandContent ?>
          <?php if (isset($brandLink)): ?></a><?php endif; ?>
        </span>
      <?php endif; ?>
      <button type="button" class="navbar-toggler navbar-toggle collapsed" data-bs-toggle="collapse" data-bs-target="#<?= $collapseId ?? '' ?>" aria-expanded="false">
        <?php if (isset($toggleBtnSrOnly)): ?><span class="visually-hidden"><?= $toggleBtnSrOnly ?></span><?php endif; ?>
        <?php if (isset($toggleBtnLabel)): ?><?= $toggleBtnLabel ?><?php endif; ?>
        <?php if (isset($toggleBtnIconClass)): ?><i class="<?= $toggleBtnIconClass ?>"></i><?php endif; ?>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="<?= $collapseId ?? '' ?>">
      <?= $collapseContent ?? '' ?>
    </div>
  </div>
</nav>
