<?php
/**
 * Accessible button with an icon and/or label.
 *
 * @param ?string   ariaLabel  Value for aria-label attribute. Not used if there is a
 *                             label.
 * @param ?iterable attributes Additional attributes
 * @param ?string   icon       Icon name
 * @param ?string   iconClass  Icon class
 * @param ?string   label      Label
 */
$__attributes = $this->htmlAttributes($attributes ?? []);
if (!isset($__attributes['type'])) {
  $__attributes['type'] = 'button';
}
if (!isset($label) && isset($ariaLabel)) {
  $__attributes['aria-label'] = $ariaLabel;
}
// Avoid unwanted whitespace in all possible variations with echo statements
echo '<button' . $__attributes->add('class', 'finna-btn') . '>';
if (isset($icon) || isset($iconClass) || isset($label)) {
  if (isset($icon)) {
    echo $this->icon($icon, $iconClass ?? null);
  } elseif (isset($iconClass)) {
    // Back-compatibility with iconClass specifying the whole style:
    echo '<i class="' . $iconClass . '" aria-hidden="true"></i>';
  }
  if ((isset($icon) || isset($iconClass)) && isset($label)) {
    echo ' ';
  }
  echo $label ?? '';
}
echo '</button>';
