<?php
/**
 * Component for displaying educational level data processed by the Aipa view helper.
 *
 * @param ?iterable attributes           Additional attributes
 * @param ?array    educationalLevelData Educational level data array
 * @param ?int      sectionHeadingLevel  Heading level for sections. Defaults to 3.
 */
?>
<?php if (!empty($educationalLeveData)): ?>
  <?php
    $__attributes = $this->htmlAttributes($attributes ?? []);
    $__headingLevel = $sectionHeadingLevel ?? 3;
    $__titleStartTagName = "h$__headingLevel";
    $__titleEndTag = "</h$__headingLevel>";

    $__renderItems = function (array $__items) use (&$__renderItems) {
      $__levelHtml = '<ul>';
      foreach ($__items as $__item) {
        $__levelHtml .= '<li>' . $this->transEsc(strip_tags($__item['title']));
        if (!empty($__item['items'])) {
          $__levelHtml .= $__renderItems($__item['items']);
        }
        $__levelHtml .= '</li>';
      }
      $__levelHtml .= '</ul>';
      return $__levelHtml;
    };
  ?>
  <div<?= $__attributes->add('class', 'finna-educational-level-data') ?>>
    <?php foreach ($educationalLeveData as $__section): ?>
      <section<?= $this->htmlAttributes($__section['attributes'] ?? []) ?>>
        <?php $__titleAttributes = $this->htmlAttributes($__section['titleAttributes'] ?? []); ?>
        <<?= $__titleStartTagName ?><?= $__titleAttributes->add('class', 'level-data-section-title') ?>>
          <?= $this->transEsc($__section['title']) ?>
        <?= $__titleEndTag ?>
        <?= $__renderItems($__section['items']) ?>
      </section>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
