<?php
  /**
   * Basic list of navigation items that supports displaying the active item's
   * children.
   *
   * Uses the following components:
   * - finna-nav-item
   *
   * @param ?string   ariaCurrent    If this parameter is set it will override the
   *                                 same parameter in all provided items
   * @param ?iterable attributes     Additional attributes
   * @param ?array    items          Array of finna-nav-item parameter arrays
   * @param ?string   renderChildren If this parameter is set it will override the
   *                                 same parameter in all provided items
   *
   * Supported variations using CSS classes:
   * - finna-nav-lg
   *     Larger variation
   * - finna-nav-navbar
   *     Variation for finna-navbar
   * - finna-nav-tabs
   *     Variation for finna-tabs-nav
   */
  $__attributes = $this->htmlAttributes($attributes ?? []);

  // Internally use Bootstrap styles as a base.
  if ($__attributes->hasValue('class', 'finna-nav-navbar')) {
    $__attributes->add('class', 'navbar-nav');
  }
  if ($__attributes->hasValue('class', 'finna-nav-tabs')) {
    $__attributes->add('class', 'nav-tabs');
  }

  // Items are processed at this point so that the active-multi-level class
  // can be added to the parent's attributes.
  $__activeMultiLevel = false;
  $__items = [];
  foreach ($items ?? [] as $__i => $__item) {
    if (!empty($__item['children'])) {
      if (!empty($__item['active'])) {
        $__activeMultiLevel = true;
      } else {
        foreach ($__item['children'] as $__child) {
          if (!empty($__child['active'])) {
            $__activeMultiLevel = true;
            break;
          }
        }
      }
    }
    if (isset($ariaCurrent)) {
      $__item['ariaCurrent'] = $ariaCurrent;
    }
    if (isset($renderChildren)) {
      $__item['renderChildren'] = $renderChildren;
    }
    $__items[$__i] = $__item;
  }
  if ($__activeMultiLevel) {
    $__attributes->add('class', 'active-multi-level');
  }
?>
<ul<?= $__attributes->add('class', ['finna-nav', 'nav']) ?>>
  <?php foreach ($__items as $__item): ?>
    <?= $this->component('finna-nav-item', $__item); ?>
  <?php endforeach; ?>
</ul>
