<? $this->headLink()->appendStylesheet('EDS.css'); ?>
<?
  $items = $this->driver->getItems();
  $dbLabel = $this->driver->getDbLabel();
  $thumb = $this->driver->getThumbnail('medium');
  $customLinks = $this->driver->getCustomLinks();
  $accessLevel = $this->driver->getAccessLevel();
  $restrictedView = empty($accessLevel) ? false : true;
?>
<? /* Display thumbnail if appropriate: */ ?>
<? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
<? if ($largeThumb): ?><a rel="external" href="<?=$this->escapeHtmlAttr($largeThumb)?>"><? endif; ?>
  <div class="recordcover">
    <? if ($mediumThumb): ?>
      <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumThumb);?>"/>
    <? else: ?>
      <span class="recordcover pt-icon pt-<?=$this->driver->getPubTypeId()?>" style="float:none"></span>
    <? endif; ?>
    <? $pLink = $this->driver->getPLink();
        if($pLink): ?>
        <br/><a href="<?=$this->escapeHtmlAttr($pLink)?>">
          <?=$this->transEsc('View in EDS')?>
        </a>
    <? endif; ?>
    <? $pdfLink = $this->driver->getPdfLink();
        if ($pdfLink): ?>
        <br/><a href="<?=$pdfLink?>" class="icon pdf fulltext">
          <?=$this->transEsc('PDF Full Text')?>
        </a>
    <? endif; ?>
    <? if ($this->driver->hasHTMLFullTextAvailable()): ?>
      <br/><a href="<?=$this->recordLink()->getUrl($this->driver, 'fulltext')?>#html" class="icon html fulltext">
          <?=$this->transEsc('HTML Full Text')?>
        </a>
    <? endif; ?>
    <? if (!empty($customLinks)): ?>
      <div class="custom-links">
        <? foreach ($customLinks as $customLink): ?>
          <? $url = isset($customLink['Url']) ? $customLink['Url'] : '';
              $mot = isset($customLink['MouseOverText'])? $customLink['MouseOverText'] : '';
              $icon = isset ($customLink['Icon']) ? $customLink['Icon'] : '';
              $name = isset($customLink['Name']) ? $customLink['Name'] : '';?>
          <a href="<?=$this->escapeHtmlAttr($url)?>" target="_blank" title="<?=$mot?>" class="custom-link">
            <? if ($icon): ?><img src="<?=$icon?>" /> <? endif; ?><?=$name?>
          </a><br/>
        <? endforeach; ?>
      </div>
    <? endif; ?>
  </div>
<? if ($largeThumb): ?></a><? endif; ?>

<br/><h3><?=$this->driver->getTitle()?></h3>

<dl class="biblio" summary="<?=$this->transEsc('Bibliographic Details')?>">
  <? foreach ($items as $key => $item): ?>
    <? if (!empty($item['Data'])): ?>
      <dt><?=$this->transEsc($item['Label'])?>:</dt>
      <dd><?=$this->driver->linkUrls($item['Data'])?></dd>
    <? endif; ?>
  <? endforeach; ?>

  <? if ($dbLabel): ?>
    <dt><?=$this->transEsc('Database')?>:</dt>
    <dd><?=$this->escapeHtml($dbLabel)?></dd>
  <? endif; ?>

  <?if ($this->driver->hasHTMLFullTextAvailable() && !$restrictedView):
      $fullText = $this->driver->getHtmlFullText();?>
    <dt><?=$this->transEsc('Full Text')?>:</dt>
    <dd>
      <?=$fullText?>
    </dd>
  <? elseif ($this->driver->hasHTMLFullTextAvailable() && $restrictedView): ?>
    <dd>
      <?=$this->transEsc('Full text is not displayed to guests')?>
    </dd>
    <dd>
      <a class="login" href="<?=$this->url('myresearch-home')?>">
        <strong><?=$this->transEsc('Login for full access')?></strong>
      </a>
    </dd>
  <? endif; ?>
</dl>
