<!-- START of: finna - search/filters.phtml -->
<?php
  $hasDefaultsApplied = $params->hasDefaultsApplied();
  $filterCount = $this->searchbox()->getFilterCount($checkboxFilters, $filterList);

  // Determine whether the only filters applied are the default ones; this controls
  // when we display or hide the reset button:
  $defaultFilters = $options->getDefaultFilters();
  $onlyDefaultsApplied = count($defaultFilters) == $filterCount;
  foreach ($defaultFilters as $currentDefault) {
    if (!$params->hasFilter($currentDefault)) {
      $onlyDefaultsApplied = false;
      break;
    }
  }
?>
<?php $filterCount = $this->search()->getFilterCount($checkboxFilters, $filterList); ?>
<?php ob_start(); ?>
  <?php foreach ($checkboxFilters as $filter): ?>
    <?php if ($filter['selected']): ?>
      <span class="filter-value">
        <?php
          $removeLink = isset($urlQuery) ? $urlQuery->removeFilter($filter['filter']) : '';
          $desc = $this->translate($filter['desc']);
          $ariaLabel = $this->translate('Remove filter') . ' ' . $this->escapeHtmlAttr($desc);
        ?>
        <?=$desc?>
        <?php if($removeLink): ?>
          <a aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>"><i class="fa fa-window-close" aria-hidden="true"></i></a>
        <?php endif; ?>
      </span>
    <?php endif ?>
  <?php endforeach; ?>

  <?php foreach ($filterList as $field => $data): ?>
      <?php if (is_callable([$params, 'isGeographicFilter']) && $params->isGeographicFilter($data)): ?>
        <span class="filter-value">
          <?php
            $removeLink = isset($urlQuery) ? $urlQuery->removeFacet($data[0]['field'], $data[0]['value'], $data[0]['operator']) : '';
            $desc = $this->transEsc($field);
            $ariaLabel = $this->translate('Remove filter') . ' ' . $desc;
          ?>
          <?=$this->transEsc($field)?>
          <?php if($removeLink): ?><a aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>"><i class="fa fa-window-close" aria-hidden="true"></i></a><?php endif; ?>
        </span>
      <?php else: ?>
        <div class="filter-title-group">
          <span class="filters-title"><?=$this->transEsc($field)?>:</span>
        <?php foreach ($data as $index => $value): ?>
        <?php
          $operatorLabel = '';
          $operatorClass = "filters-" . $this->escapeHtmlAttr(strtolower($value['operator']));
          $removeLink = isset($urlQuery) ? $urlQuery->removeFacet($value['field'], $value['value'], $value['operator']) : '';
          $desc = $this->escapeHtml($value['displayText']);
          $ariaLabel = $this->translate('Remove filter') . ' ' . $desc;

          if ($value['operator'] === 'NOT') {
            $operatorLabel = $this->transEsc('NOT');
          } elseif ($value['operator'] === 'OR' && $index > 0) {
            $operatorLabel = $this->transEsc('OR');
          }

          $isOnlineFacet = ('unrecognized_facet_label' === $field && in_array($value['field'], ['online_boolean', 'free_online_boolean']));
        ?>
          <?php if ($index !== 0 || $operatorLabel === 'NOT'): ?>
            <span class="filters-term <?= $operatorClass ?>"><?= $operatorLabel ?></span>
          <?php endif; ?>
          <span class="filter-value <?= $operatorClass ?>">
            <span class="filter-text">
              <?php // Always handle online_boolean and free_online_boolean even if not configured ?>
              <?php if ($isOnlineFacet): ?>
                <?=$this->translate('online_boolean' === $value['field'] ? 'online_material_facet_html' : 'free_online_material_facet_html') ?>
              <?php else: ?>
                <?=$desc?>
              <?php endif; ?>
            </span>
            <?php if($removeLink): ?>
              <a aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>"><i class="fa fa-window-close" aria-hidden="true"></i></a>
            <?php endif; ?>
          </span>
          <?php if ($index === 0): ?>
            </div>
          <?php endif; ?>
        <?php endforeach; ?>
        <div class="clearfix"></div>
      <?php endif; ?>

  <?php endforeach; ?>
<?php $filters = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<div class="finna-filters">
  <?php if (!isset($isCollectionTab) || !$isCollectionTab): ?>
    <?php $defaultFilterState = $hasDefaultsApplied || $options->getRetainFilterSetting() || !$defaultSortApplied ? ' checked="checked"' : ''; ?>
    <?php
      $resetLink = !$onlyDefaultsApplied && isset($urlQuery)
        ? $urlQuery->removeAllFilters()->resetDefaultFilters() : false;
    ?>
    <div class="filter-options">
      <button type="button" class="btn-unstyled filters-toggle visible-xs visible-sm">
        <?=$this->transEsc("show_filters")?>
        <span class="active-filter-count">(<?=$filterCount?>)</span><i class="fa fa-arrow-down"></i>
      </button>
      <?php if ($resetLink && $options->getRetainFilterSetting()): ?>
        <a class="btn btn-default reset-filters-btn" href="<?=$resetLink?>"><?=$this->transEsc('reset_filters_button')?></a>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="filters">
    <?=$filters ?>
  </div>
  <div class="clearfix"></div>
</div>
<!-- END of: finna - search/filters.phtml -->
