<!-- START of: finna - search/home.phtml -->
<?
  // Set page title.
  $this->headTitle($this->translate('Search Home'));

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->layout()->breadcrumbs = false;
  $this->layout()->introduction = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>
<!--  Begin home.phtml and close page container for extra styling  -->
</div>
<div class="container-fluid">
  <div class="container">
    <div>
      <?=($this->ils()->getOfflineMode() == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_home_message']) : ''?>
    </div>
  </div>
</div>
<!-- Create different sections for home page (home-1 - home-10) -->
<? for ($i = 1; $i <= 10; $i++): ?>
<? if ($template = $this->content()->findTemplateForLng("search/home/home-$i")): ?>
<div class="container-fluid home-<?=$i; ?>">
  <div class="container">
    <?=$this->render($template)?>
  </div>
</div>
<? endif; ?>
<? endfor; ?>
<!-- reopen container -->
<div class="container">
<!-- END of: finna - search/home.phtml -->
