<!-- START of: finna - search/introductiontext.phtml -->
<div>
    <?php if (!$this->translationEmpty('site_header_slogan')): ?><h1 class="introductionText"><?=$this->translate('site_header_slogan')?></h1><?php endif; ?>
    <?php if (!$this->translationEmpty('site_header_slogan_small')): ?><h3 class="introductionText"><?=$this->translate('site_header_slogan_small')?></h3><?php endif; ?>
</div>
<!-- END of: finna - search/introductiontext.phtml -->
