<!-- START of: finna - search/list-condensed.phtml -->
<?php if (!isset($this->indexStart)) $this->indexStart = 0; ?>
<?php $showCheckboxes = !isset($this->hideCartControls) && $this->cart()->isActive() ?>
<?php $i = $this->indexStart; foreach ($this->results->getResults() as $current):
  $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="result condensed-list-view clearfix">
    <div class="hidden-print<?php if ($showCheckboxes): ?> checkbox<?php endif; ?> sr-only">
      <label>
        <?php if ($showCheckboxes): ?>
          <?=$this->record($current)->getCheckbox()?>
        <?php endif; ?>
        <?=$recordNumber?>
      </label>
    </div>
    <?=$this->record($current)->getSearchResult('condensed')?>
  </div>
<?php endforeach; ?>
<!-- END of: finna - search/list-condensed.phtml -->
