<!-- START of: finna - search/list-list.phtml -->
<?php
  $browse = $browse ?? false;

  if (!isset($this->indexStart)) {
    $this->indexStart = 0;
  }
  $resultCount = $this->results->getResults();
  $recommendationConfig = $this->searchTabsRecommendations()->getConfig();
  $needRecommendationHolder = !$browse && $this->results->getStartRecord() == 1 && !empty($recommendationConfig['recommendations'][$this->results->getParams()->getSearchClassId()]);
  $haveRecommendationHolder = false;
?>
<?php $i = $this->indexStart; ?>
<?php foreach ($this->results->getResults() as $current): ?>
  <?php $recordNumber = $this->results->getStartRecord() + $i - $this->indexStart; ?>
  <?php if ($needRecommendationHolder && ($recordNumber == ($recommendationConfig['position'] ?? 4) || $recordNumber == $resultCount)): ?>
    <div id="search-tabs-recommendations-holder" data-search-id="<?=$this->escapeHtmlAttr($this->results->getSearchId())?>" data-limit="<?=$this->results->getParams()->getLimit() ?>"></div>
    <?php // Make sure OpenURL resolution support is loaded, since recommendations may include OpenURL even if main search results don't ?>
    <?php $this->headScript()->appendFile("openurl.js"); ?>
    <?php $haveRecommendationHolder = true; ?>
  <?php endif; ?>
  <div id="result<?=$i++ ?>" class="result clearfix<?=$current->supportsAjaxStatus()?' ajaxItem':''?>">
      <?php if (isset($this->showCheckboxes) && $this->showCheckboxes): ?>
        <div class="record-checkbox">
          <?=$this->record($current)->getCheckbox('', 'search-cart-form')?>
        </div>
      <?php endif; ?>
      <span class="sr-only"><?=$this->transEsc('Search Result');?> <?=$recordNumber ?></span>
    <?=$this->record($current)->getSearchResult('list')?>
  </div>
<?php endforeach; ?>
<?php if ($needRecommendationHolder && !$haveRecommendationHolder): ?>
  <div id="search-tabs-recommendations-holder" data-search-id="<?=$this->escapeHtmlAttr($this->results->getSearchId())?>" data-limit="<?=$this->results->getParams()->getLimit() ?>"></div>
  <?php // Make sure OpenURL resolution support is loaded, since recommendations may include OpenURL even if main search results don't ?>
  <?php $this->headScript()->appendFile("openurl.js"); ?>
<?php endif; ?>
<!-- END of: finna - search/list-list.phtml -->
