<!-- START of: finna - search/modals.phtml -->
<?php // BASIC MODAL IN CASE WE NEED ONE ?>
<div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <button type="button" class="close" data-bs-dismiss="modal" aria-label="<?= $this->transEsc('close') ?>"></button>
      <div class="modal-body">
      </div>
    </div>
  </div>
</div>

<?php // IMAGEPOPUP MODAL ?>
<div id="imagepopup-modal" hidden>
  <div class="imagepopup-holder" aria-hidden="true">
    <div class="imagepopup-container">
      <div class="popup-canvas paginator-canvas">
        <button class="next-image left" title="<?= $this->transEsc('previous_image'); ?>" type="button"><?=$this->icon('image-previous') ?><span class="visually-hidden"><?= $this->transEsc('previous_image'); ?></span></button>
        <div class="popup-nonzoom non-zoomable">
          <div class="iconlabel"></div>
          <img src="<?= $this->imageSrc()->getDataPixel() ?>" alt="">
        </div>
        <div class="leaflet-map-image image-wrapper">
          <img src="<?=$this->imageSrc()->getDataPixel()?>" alt="">
          <div class="imagepopup-zoom-container">
            <button class="zoom-in zoom-button" title="<?= $this->transEsc('zoom_in'); ?>"><?=$this->icon('image-zoom-in') ?><span class="visually-hidden"><?= $this->transEsc('zoom_in'); ?></span></button>
            <button class="zoom-out zoom-button" title="<?= $this->transEsc('zoom_out'); ?>"><?=$this->icon('image-zoom-out') ?><span class="visually-hidden"><?= $this->transEsc('zoom_out'); ?></span></button>
            <button class="zoom-reset zoom-button" title="<?= $this->transEsc('zoom_center'); ?>"><?=$this->icon('image-zoom-reset') ?><span class="visually-hidden"><?= $this->transEsc('zoom_center'); ?></span></button>
          </div>
          <div class="leaflet-image-loading">
          </div>
        </div>
        <div class="popup-video video-popup"></div>
        <button class="next-image right" title="<?= $this->transEsc('next_image'); ?>" type="button"><?=$this->icon('image-next') ?><span class="visually-hidden"><?= $this->transEsc('next_image'); ?></span></button>
      </div>
      <div class="finna-image-pagination">
      </div>
    </div>
    <div class="image-information-holder">
      <div class="collapse-content-holder">
      </div>
      <div class="record-informations">
        <div class="record-index">
          <span class="total"></span>
        </div>
        <div class="paginator-info">
          <span class="image-index"></span>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- END of: finna - search/modals.phtml -->
