<!-- START of: finna - search/pagination_simple.phtml -->
<?php if ($this->pageCount): ?>
  <ul class="paginationSimple">
    <li>
    <?php if (isset($this->previous)): ?>
      <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->previous)?>"><span class="sr-only"><?=$this->transEsc('page_prev')?></span><i class="fa fa-arrow-alt-left"></i></a></li>
    <?php endif; ?>
    <li class="pagination-text">
      <?=$this->label ?: $this->translate(
        'showing_results_of_html', [
          '%%start%%' => $this->results->getStartRecord(),
          '%%end%%' => $this->results->getEndRecord(),
          '%%total%%' => $this->localizedNumber($this->results->getResultTotal())
        ]
      );?>
    </li>
    <?php if (isset($this->next)): ?>
      <li><a href="<?=$this->currentPath() . $this->results->getUrlQuery()->setPage($this->next)?>"><span class="sr-only"><?=$this->transEsc('page_next')?></span><i class="fa fa-arrow-alt-right"></i></a></li>
    <?php endif; ?>
  </ul>
<?php endif; ?>
<!-- END of: finna - search/pagination_simple.phtml -->
