<!-- START of: finna - search/street-search-header.phtml -->
<?php
$this->assetManager()->appendScriptLink('finna-street-search.js');
$this->layout()->infoMessage = '<div class="street-search-progress hidden">' . $this->icon('spinner') . '<div class="infoBox"><div class="info"></div><button class="street-search-terminate">' . $this->transEsc('street_search_abort') . '</button></div></div>';
?>
<div class="street-search-header">
  <div class="street-search-info">
    <div class="street-search-introduction">
      <?=$this->translate('street_search_introduction_results_html')?>
    </div>
    <div class="street-search-feedback text-right">
      <a class="btn btn-primary btn-uppercase" href="<?=$this->url('feedback-home', [], ['query' => ['comments' => $this->transEsc('street_search_feedback'), 'url' => $this->serverUrl(true)]])?>"><span><?=$this->transEsc('Feedback')?></span></a>
    </div>
    <div class="clearfix"></div>
  </div>
  <div class="street-search-action-links hidden-sm hidden-md hidden-lg">
    <a class="update-location" href="">
      <?=$this->icon('map-marker') ?> <?=$this->translate('use_my_location')?>
    </a>
    <a class="select-from-map" href="<?=$this->url('search-mapfacet') . $urlParams?>" data-lightbox>
      <?=$this->icon('map') ?> <?=$this->translate('select_area_from_map') ?>
    </a>
  </div>
</div>

<?php
  $script = <<<JS
      $(document).ready(function() {
        finna.StreetSearch.initStreetHeader();
      });
      JS;
  echo $this->assetManager()->outputInlineScriptString($script);
?>
<!-- END of: finna - search/street-search-header.phtml -->
