<?
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('New Items') . '</em>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h3><?=$this->transEsc('Find New Items')?></h3>
  <form method="get" action="" class="search">
    <div class="span-5">
      <fieldset>
        <legend><?=$this->transEsc('Range')?>:</legend>
        <? foreach ($this->ranges as $key => $range): ?>
          <input id="newitem_range_<?=$this->escape($key)?>" type="radio" name="range" value="<?=$this->escape($range)?>"<?= ($key == 0) ? ' checked="checked"' : ''?>/>
          <label for="newitem_range_<?=$this->escape($key)?>">
            <?=($range == 1) ? $this->transEsc('Yesterday') : $this->transEsc('Past') . ' ' . $this->escape($range) . ' ' . $this->transEsc('Days')?>
          </label>
          <br/>
        <? endforeach; ?>
      </fieldset>
    </div>
    <? if (is_array($this->fundList) && !empty($this->fundList)): ?>
      <div class="span-5">
        <label class="displayBlock" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
        <select id="newitem_department" name="department" size="10">
        <? foreach ($this->fundList as $fundId => $fund): ?>
          <option value="<?=$this->escape($fundId)?>"><?=$this->transEsc($fund)?></option>
        <? endforeach; ?>
        </select>
      </div>
    <? endif; ?>
    <div class="clear"></div>
    <input type="submit" name="submit" value="<?=$this->transEsc('Find')?>"/>
  </form>
</div>
<div class="clear"></div>