<?
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $this->searchClassId = 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $basicSearch = $options->getSearchAction();
    $searchHome = $basicSearch;
    $searchHome['action'] = 'Home';
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $options->getLastSort();
    $lastLimit = $options->getLastLimit();
?>
<div class="searchform">
  <? if ($this->searchType == 'advanced'): ?>
    <a href="<?=$this->url($advSearch, 'default', true)?>?edit=<?=$this->escape($this->searchId)?>" class="small"><?=$this->transEsc("Edit this Advanced Search")?></a> |
    <a href="<?=$this->url($advSearch, 'default', true)?>" class="small"><?=$this->transEsc("Start a new Advanced Search")?></a> |
    <a href="<?=$this->url($searchHome, 'default', true)?>" class="small"><?=$this->transEsc("Start a new Basic Search")?></a>
    <br/><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escape($this->lookfor)?></strong>"
  <? else: ?>
    <form method="get" action="<?=$this->url($basicSearch, 'default', true)?>" name="searchForm" id="searchForm" class="search">
      <label for="searchForm_lookfor" class="offscreen"><?=$this->transEsc("Your search terms")?></label>
      <input id="searchForm_lookfor" type="text" name="lookfor" size="40" value="<?=$this->escape($this->lookfor)?>"<?=$options->autocompleteEnabled() ? ' class="autocomplete searcher:' . $this->escape($this->searchClassId) . ' typeSelector:searchForm_type"' : ''?>/>
      <label for="searchForm_type" class="offscreen"><?=$this->transEsc("Search Type")?></label>
      <select id="searchForm_type" name="type">
      <? foreach ($options->getBasicHandlers() as $searchVal => $searchDesc): ?>
        <option value="<?=$this->escape($searchVal)?>"<?=$this->searchIndex == $searchVal ? ' selected="selected"' : ''?>><?=$this->transEsc($searchDesc)?></option>
      <? endforeach; ?>
      </select>
      <input type="submit" name="submit" value="<?=$this->transEsc("Find")?>"/>
      <? if ($advSearch): ?>
        <a href="<?=$this->url($advSearch, 'default', true)?>" class="small"><?=$this->transEsc("Advanced")?></a>
      <? endif; ?>

      <?
      /* Do we have any checkbox filters? */
      $hasCheckboxFilters = false;
      if (isset($this->checkboxFilters) && count($this->checkboxFilters) > 0) {
        foreach ($this->checkboxFilters as $current) {
          if ($current['selected']) {
            $hasCheckboxFilters = true;
            break;
          }
        }
      }
      ?>

      <? $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
        <?
        $selectedShards = isset($this->selectedShards)
            ? $this->selectedShards : $options->getDefaultSelectedShards();
        ?>
        <br />
        <? foreach ($shards as $shard => $val): ?>
          <? $isSelected = in_array($shard, $selectedShards); ?>
          <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escape($shard)?>' /> <?=$this->transEsc($shard)?>
        <? endforeach; ?>
      <? endif; ?>
      <? if ((isset($this->filterList) && is_array($this->filterList) && count($this->filterList) > 0) || $hasCheckboxFilters): ?>
        <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
        <div class="keepFilters">
          <input type="checkbox"<?=$defaultFilterState?> id="searchFormKeepFilters"/> <label for="searchFormKeepFilters"><?=$this->transEsc("basic_search_keep_filters")?></label>
          <div class="offscreen">
            <? if (isset($this->filterList) && is_array($this->filterList)): ?>
              <? $i = 0; foreach ($this->filterList as $field => $data): ?>
                <? foreach ($data as $value): ?>
                  <input id="applied_filter_<?=++$i?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escape($field)?>:&quot;<?=$this->escape($value)?>&quot;" />
                  <label for="applied_filter_<?=$i?>"><?=$this->escape($field)?>:&quot;<?=$this->escape($value)?>&quot;</label>
                <? endforeach; ?>
              <? endforeach; ?>
            <? endif; ?>
            <? if ($hasCheckboxFilters): ?>
              <? $i = 0; foreach ($checkboxFilters as $current): ?>
                <? if ($current['selected']): ?>
                  <input id="applied_checkbox_filter_<?=++$i?>" type="checkbox"<?=$defaultFilterState?> name="filter[]" value="<?=$this->escape($current['filter'])?>" />
                  <label for="applied_checkbox_filter_<?=$i?>"><?=$this->escape($current['filter'])?></label>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>
          </div>
        </div>
      <? endif; ?>
      <?
      /* Load hidden limit preference from Session */
      if (!empty($lastLimit)) {
        echo '<input type="hidden" name="limit" value="' . $this->escape($lastLimit) . '" />';
      }
      if (!empty($lastSort)) {
        echo '<input type="hidden" name="sort" value="' . $this->escape($lastSort) . '" />';
      }
      ?>
    </form>
    <script type="text/javascript">$("#searchForm_lookfor").focus()</script>
  <? endif; ?>
</div>
