<!-- START of: finna - primo/advanced.phtml -->
<?
    $this->headScript()->appendFile("finna-primo-adv-search.js");

    // Set page title.
    $this->headTitle($this->translate('Advanced Search'));

    // Disable top search box -- this page has a special layout.
    $this->layout()->searchbox = false;

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Advanced Search') . '</li>';

    // Set up saved search details:
    if (isset($this->saved) && is_object($this->saved)) {
        $searchDetails = $this->saved->getParams()->getQuery();
        if ($searchDetails instanceof \VuFindSearch\Query\Query) {
            // Not an advanced query -- ignore it.
            $searchDetails = $groups = false;
        } else {
            $groups = $searchDetails->getQueries();
        }
        $hasDefaultsApplied = $this->saved->getParams()->hasDefaultsApplied();
        $searchFilters = $this->saved->getParams()->getFilterList();
    } else {
        $hasDefaultsApplied = $searchDetails = $searchFilters = $groups = false;
    }

    $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, true);
?>
<form id="advSearchForm" name="searchForm"  method="get" action="<?=$this->url($this->options->getSearchAction())?>" class="form-horizontal">
  <input type="hidden" name="join" value="AND" />
      <?
        $this->searchType = 'advanced';
        $searchTabs = $this->searchtabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters, []);
        $this->layout()->finnaMainTabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $searchTabs, 'hiddenFilters' => $hiddenFilters]);
        $this->layout()->finnaMainHeader = '<div class="col-xs-12"><h3>' . $this->transEsc('Advanced Search from Primo') . '</h3></div>';
      ?>
      <? /* fallback to a fixed set of search groups/fields if JavaScript is turned off */ ?>
      <? if ($groups !== false) {
          $numGroups = count($groups);
        }
        if (!isset($numGroups) || $numGroups < 3) {
          $numGroups = 1;
        }
      ?>
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-9" id="group1SearchHolder"><h4><?=$this->transEsc("adv_search_label")?><? if (!$this->translationEmpty('tooltip_pci_advanced_html')): ?><span class="tooltip-pci-advanced pull-right" data-toggle="tooltip" data-placement="bottom" data-html="true" data-original-title='<?=$this->transesc("tooltip_pci_advanced_html") ?>'><i class="fa fa-info-big"></i> <?=$this->transEsc("Help with Advanced Search")?></span><? endif; ?></h4></div>
        </div>
      <? for ($i = 0; $i < $numGroups; $i++):
              $operator = 'AND';
              if (isset($groups[$i])) {
                $operator = $groups[$i]->getOperator();
                $currentGroup = $groups[$i]->getQueries();
                $numRows = count($currentGroup);
              } else {
                $currentGroup = false;
              }
              if (!isset($numRows) || $numRows < 3) {
                $numRows = 3;
              }
            ?>

        <div class="group well col-sm-7 col-md-10 col-lg-9" id="group<?=$i?>">
          <div class="row">
            <div class="col-sm-5 col-sm-push-7 match">
              <label class="search_bool"><?=$this->transEsc("search_match")?>:</label>
              <select name="bool<?=$i ?>[]" id="search_bool<?=$i ?>" class="form-control form-inline">
                <option value="AND"<? if('AND' == $operator):?> selected<?endif;?>><?=$this->transEsc("search_AND")?></option>
                <option value="OR"<? if('OR' == $operator):?> selected<?endif;?>><?=$this->transEsc("search_OR")?></option>
              </select>
            </div>
            <div class="col-sm-7 col-sm-pull-5">
            <? for ($j = 0; $j < $numRows; $j++): ?>
              <? $currRow = isset($currentGroup[$j]) ? $currentGroup[$j] : false; ?>
              <div class="primo-advanced-search-fields">
                  <input id="search_lookfor<?=$i?>_<?=$j?>" type="text" value="<?=$currRow?$this->escapeHtmlAttr($currRow->getString()):''?>" size="30" name="lookfor<?=$i?>[]" class="form-control form-inline responsive-field" placeholder="<?=$this->transEsc('Search words')?>..." />
                  <select id="search_type<?=$i?>_<?=$j?>" name="type<?=$i?>[]" class="form-control form-inline responsive-field">
                  <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
                    <option value="<?=$this->escapeHtmlAttr($searchVal)?>"<?=($currRow && $currRow->getHandler() == $searchVal)?' selected="selected"':''?>><?=$this->transEsc($searchDesc)?></option>
                  <? endforeach; ?>
                  </select>
              </div>
            <? endfor; ?>
              <a href="#" class="primo-add-search">
                <i class="fa fa-plus-small"></i> Lisää hakukenttä
              </a>
            </div>
          </div>
        </div>
      <? endfor; ?>
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-9"><button type="submit" class="btn btn-primary pull-right" name="submit" value="<?=$this->transEsc("Find")?>"><i class="fa fa-search-adv"></i> <?=$this->transEsc("Find")?></button></div>
      </div>
      <? $lastSort = $this->searchMemory()->getLastSort($this->options->getSearchClassId()); ?>
      <? if (!empty($lastSort)): ?>
        <input type="hidden" name="sort" value="<?=$this->escapeHtmlAttr($lastSort)?>" />
      <? endif; ?>

      <? if ($hasDefaultsApplied): ?>
        <input type="hidden" name="dfApplied" value="1" />
      <? endif ?>
      <? if (!empty($searchFilters)): ?>
        <h4><?=$this->transEsc("adv_search_filters")?></h4>
        <ul class="list-group">
          <li class="list-group-item">
            <div class="checkbox">
              <label>
                <?=$this->transEsc("adv_search_select_all")?>
                <input type="checkbox" checked="checked" class="checkbox-select-all" />
              </label>
            </div>
          </li>
        </ul>
        <? foreach ($searchFilters as $field => $data): ?>
          <div>
            <ul class="list-group">
              <li class="list-group-item title"><?=$this->transEsc($field)?></li>
              <? foreach ($data as $value): ?>
                <li class="list-group-item">
                  <div class="checkbox">
                    <label>
                      <input type="checkbox" class="checkbox-select-item" checked="checked" name="filter[]" value='<?=$this->escapeHtmlAttr($value['field'])?>:"<?=$this->escapeHtmlAttr($value['value'])?>"' /> <?=$this->escapeHtml($value['displayText'])?>
                    </label>
                  </div>
                </li>
              <? endforeach; ?>
            </ul>
          </div>
        <? endforeach; ?>
      <? endif; ?>
</form>
<!-- END of: finna - primo/advanced.phtml -->
