<!-- START of: finna - primo/home-1_en-gb.phtml -->
<?
    $this->layout()->finnaMainHeader = '<div class="col-xs-12"><h1 class="content-header">Foreign content search</h1></div>';
?>
<div class="row">
  <div class="col-sm-5">
    <div class="infobox">
      <p>International e-material search includes <strong>online links </strong>to e.g. numerous peer-reviewed scientific studies, articles and ebooks from many different faculties and publishers!</p>
      <p>International e-material search is an useful addition e.g. for researchers or thesis working students beside with other search services.</p>
    </div>
  </div>
    <div class="col-sm-7">
      <p>&nbsp;</p
      <p>Access to full texts may require logging in with university credentials.</p>
      <p>Resources are updated to the index regularly. Depending on source collection update cycle may vary from one week to one year.</p>
      <p>The service is provided by Ex Libris in co-operation with providers.</p>
      <p>&nbsp;</p>
      <img src="<?=$this->imageLink('primo-central-logo.jpg')?>" alt="primo central logo" />
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </div>
</div>
<!-- END of: finna - primo/home-1_en-gb.phtml -->
