<?
    $this->layout()->finnaMainHeader = '<div class="col-xs-12"><h1 class="content-header">Overseas content search</h1></div>';
?>
<div class="row">
<div class="col-sm-4">
</div>
<div class="col-sm-8">
<p>Ulkomaisten aineistojen indeksiin on kerätty tieteellisiä artikkeleita, e-kirjoja ja muita viitteitä eri kustantajilta.</p>
<p>Pääsy kokoteksteihin voi vaatia kirjautumisen korkeakoulun käyttäjätunnuksilla.</p>
<p>Viitteet päivittyvät indeksiin viiveellä, joka riippuu lähdekokoelmasta: harvoin päivittyvien kokoelmien viitteet noudetaan kerran vuodessa mutta usein päivittyviä kokoelmia haravoidaan jopa viikoittain.</p>
<p>Palvelun tuottaa Ex Libris yhteistyössä välittäjien kanssa.</p>
</div>
</div>