<?
    // Set page title.
    $this->headTitle($this->translate('Install VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Install VuFind') . '</em>';
?>
<style>
    .pre {
        width:90%;
        overflow-y:visible;
        padding:8px;
        margin:1em 2em;
        background:#EEE;
        border:1px dashed #CCC;
        white-space:pre-wrap;
    }
</style>
<h1><?=$this->transEsc('Install VuFind')?></h1>
<?=$this->flashmessages()?>
<p>Save this SQL somewhere safe:</p>

<textarea class="pre" rows="20" readonly onClick="this.select()"><?=trim($this->sql) ?></textarea>

<form method="POST" action="<?=$this->url('install-showsql')?>">
    <input type="submit" name="continue" value="Next">
</form>