<span class="relaisLink"><?=$this->icon('spinner') ?> <?=$this->transEsc('relais_checking')?></span>
<?php
  // Only activate Relais code once, even if there are multiple items:
  if (empty($this->layout()->relaisActive)) {
    // We need a record driver in $driver for this to work right!
    if (!isset($driver)) {
        throw new \Exception('Record driver missing!');
    }
    $this->layout()->relaisActive = true;
    $this->jsTranslations()->addStrings(
        [
          'confirm_dialog_no' => 'confirm_dialog_no',
          'confirm_dialog_yes' => 'confirm_dialog_yes',
          'relais_available' => 'relais_available',
          'relais_checking' => 'relais_checking',
          'relais_error_html' => 'relais_error_html',
          'relais_request' => 'relais_request',
          'relais_requesting' => 'relais_requesting',
          'relais_search' => 'relais_search',
          'relais_success_label' => 'relais_success_label',
          'relais_success_message' => 'relais_success_message',
        ]
    );
    $this->headScript()->appendFile('relais.js');
    $addLink = $this->escapeJs($this->url('relais-request'));
    $oclc = $this->escapeJs($driver->tryMethod('getCleanOCLCNum'));
    $failLink = $this->escapeJs($this->relais()->getSearchLink($driver));
    $activateRelais = "$(document).ready(function() { VuFind.relais.checkAvailability('$addLink', '$oclc', '$failLink') });";
    echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $activateRelais, 'SET');
  }
?>