<h2><?=$this->transEsc('relais_request')?></h2>

<div id="requestMessage">
  <?=$this->icon('spinner') ?>
  <?=$this->transEsc('relais_checking')?>
</div>

<div id="requestButton"></div>

<?php
  $this->headScript()->appendFile('relais.js');
  $activateRelais = "$(document).ready(function () { VuFind.relais.addItem('$oclc', '$failLink'); });\n";
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $activateRelais, 'SET')
?>
