<div class="row">
  <div class="col-md-12">
    <div class="form-group" id="relaisResults">
      <i class="fa fa-spinner fa-spin"></i>
      <?=$this->transEsc('Checking availability...')?>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12" id="requestMessage">
  </div>
</div>

<div class="row">
   <div class="col-md-6">
   </div>
   <div class="col-md-6" id="requestButton">
   </div>
</div>

<?php
  $this->headScript()->appendFile('relais.js');
  $activateRelais = "$(document).ready(function () { relaisAddItem('$oclc'); });\n";
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $activateRelais, 'SET')
?>
