<?
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Upgrade VuFind') . '</em>';
?>
<style>
    pre {
        padding:8px;
        margin:1em 2em;
        background:#EEE;
        border:1px dashed #CCC;
    }
</style>
<h1><?=$this->transEsc('Upgrade VuFind')?></h1>
<?=$this->flashmessages()?>
<p>Save this SQL somewhere safe:</p>

<pre><?=trim($this->sql) ?></pre>

<form method="POST" action="<?=$this->url('upgrade-showsql')?>">
    <input type="submit" name="continue" value="Next">
</form>