<?
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<em>' . $this->transEsc('Upgrade VuFind') . '</em>';

    // Set up styles:
    $this->headstyle()->appendStyle(
        "pre {\n"
        . "  white-space:pre-line; width:90%; overflow-y:visible; padding:8px; margin:1em 2em; background:#EEE; border:1px dashed #CCC;\n"
        . "}\n"
    );
?>
<h1><?=$this->transEsc('Upgrade VuFind')?></h1>
<?=$this->flashmessages()?>
<p>These SQL statements can be used to manually upgrade your database:</p>

<textarea class="pre" rows="20" readonly onClick="this.select()"><?=trim($this->sql) ?></textarea>

<form method="post" action="<?=$this->url('upgrade-showsql')?>">
  <input type="submit" name="continue" value="Next" />
</form>