<?
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up menu
    $this->layout()->finnaMainTabs = $this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'librarycards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';
?>
<div class="row">
  <div class="col-md-10 col-lg-9">
    <?=$this->flashmessages()?>
    <h2><?=$this->transEsc('Library Cards Connected To My Account')?></h2>
    <? if ($this->libraryCards->count() == 0): ?>
      <h4><?=$this->transEsc('You do not have any library cards')?></h4>
    <? else: ?>
      <table class="table table-striped useraccount-table">
      <tr class="headers">
        <th><?=$this->transEsc('Library Card Name')?></th>
        <? if ($this->multipleTargets): ?>
        <th><?=$this->transEsc('login_target')?></th>
        <? endif; ?>
        <th><?=$this->transEsc('Username')?></th>
        <th class="text-right actions"><?=$this->transEsc('Actions')?></th>
      </tr>
      <? foreach ($this->libraryCards as $record): ?>
        <? $username = $record['cat_username']; ?>
        <? $target = ''; ?>
        <? if ($this->multipleTargets): ?>
          <? if (strstr($username, '.')): ?>
            <? list($target, $username) = explode('.', $username, 2); ?>
          <? endif; ?>
        <? endif; ?>
        <tr>
          <td><?=$record['card_name'] == "$target.$username" ? $this->escapeHtml($username) : $this->escapeHtml($record['card_name'])?></td>
          <? if ($this->multipleTargets): ?>
            <td><?=$target ? $this->transEsc("source_$target", null, $target) : '&nbsp;' ?></td>
          <? endif; ?>
          <td><?=$this->escapeHtml($username)?></td>
          <td class="text-right actions">
            <div class="btn-group">
              <a class="btn btn-link" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) ?>" title="<?=$this->transEsc('Edit Library Card')?>"><i class="fa fa-pen bigger gray"></i> <span class="sr-only"><?=$this->transEsc('Edit')?></span></a>
              <a class="btn btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>">
                <i class="fa fa-remove fa-button"></i> <span class="sr-only"><?=$this->transEsc('Delete')?></span>
              </a>
              <ul class="dropdown-menu useraccount-cancel">
                <li class="disabled"><a><?=$this->transEsc('Disconnect Library Card')?>?</a></li>
                <li><a href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>&amp;confirm=1"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
              </ul>
            </div>
          </td>
        </tr>
      <? endforeach; ?>
      </table>
    <? endif; ?>

    <div>
      <a href="<?=$this->url('editLibraryCard') ?>NEW" class="btn btn-primary" title="<?=$this->transEsc('Connect Library Card')?>"><?=$this->transEsc('Connect Library Card')?>...</a>
      <br>
      <br>
    </div>
  </div>

</div>
