<!-- START of: finna - librarycards/selectcard.phtml -->
<? if ($this->user): ?>
  <? $cards = $this->user->getLibraryCards(); if ($cards->count() > 1): ?>
    <? $targetCount = $this->ils()->checkCapability('getLoginDrivers') ? count($this->ils()->getLoginDrivers()) : 1; ?>
    <? if (isset($loginMenu) && $loginMenu): ?>
        <li role="menuitem" class="logoutOptions card-selection">
            <h5><?=$this->transEsc(isset($this->label) ? $this->label : 'Kirjastokortti');?></h5>
            <? foreach ($cards as $card): ?>
              <?
                $target = '';
                $username = $card->cat_username;
                if (strstr($username, '.')) {
                  list($target, $username) = explode('.', $username, 2);
                }
                $display = $this->transEsc($card->card_name ? $card->card_name : $username);
                if ($display == "$target.$username") {
                  $display = $username;
                }
                if ($target && $targetCount > 1) {
                  $display .= ' (' . $this->transEsc("source_$target", null, $target) . ')';
                }
              ?>
              <? $selectedCard = (!isset($this->displaySelected) || $this->displaySelected) && ($card->cat_username == $this->user->cat_username) ;?>
              <a href="<?=$this->url('librarycards-selectcard')?>?cardID=<?=$this->escapeHtmlAttr($card->id)?>";?><?=$selectedCard ? '<i class="fa fa-check"></i><span class="sr-only">(' . $this->transEsc("selected") . ')</span> ' : '' ;?><?=$display ?></a>
            <? endforeach; ?>
        </li>

    <? else: ?>
    <div class="select-card-wrapper">
        <span class="select-card-label"><?=$this->transEsc(isset($this->label) ? $this->label :''); ?></span>
        <div class="dropdown select-card">
            <? foreach ($cards as $card): ?>
              <?
                $target = '';
                $username = $card->cat_username;
                if (strstr($username, '.')) {
                  list($target, $username) = explode('.', $username, 2);
                }
                $display = $this->transEsc($card->card_name ? $card->card_name : $username);
                if ($display == "$target.$username") {
                  $display = $username;
                }
                if ($target && $targetCount > 1) {
                  $display .= ' (' . $this->transEsc("source_$target", null, $target) . ')';
                }
              ?>
              <? if ((!isset($this->displaySelected) || $this->displaySelected) && ($card->cat_username == $this->user->cat_username)) : ?>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><span><?=$display ;?></span> <i class="fa fa-arrow-down"></i></a>
              <? endif;?>

              <? if (isset($this->displaySelected) && !$displaySelected): ?>
              <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc('select_library_card');?> <i class="fa fa-arrow-down"></i></a>
              <? endif; ?>
            <? endforeach; ?>
            <ul id="library_card" name="cardID" class="dropdown-menu" role="menu">
            <? foreach ($cards as $card): ?>
                <?
                  $target = '';
                  $username = $card->cat_username;
                  if (strstr($username, '.')) {
                    list($target, $username) = explode('.', $username, 2);
                  }
                  $display = $this->transEsc($card->card_name ? $card->card_name : $username);
                  if ($display == "$target.$username") {
                    $display = $username;
                  }
                  if ($target && $targetCount > 1) {
                    $display .= ' (' . $this->transEsc("source_$target", null, $target) . ')';
                  }
                ?>
                <li role="menuitem">
                    <a href="<?=$this->url('librarycards-selectcard')?>?cardID=<?=$this->escapeHtmlAttr($card->id);?>"><?=$display ;?></a>
                </li>
            <? endforeach; ?>
            </ul>
        </div>
    </div>
    <? endif; ?>
  <? endif; ?>
<? endif; ?>
<!-- END of: finna - librarycards/selectcard.phtml -->
