<div data-role="page" id="MyResearch-login">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <h3><?=$this->transEsc($this->title) ?></h3>

    <?=$this->flashmessages();?>

    <p><?=$this->transEsc($this->message) ?></p>

    <form action="<?=$this->escape($this->confirm)?>" method="post" data-ajax="false">
      <? foreach ($this->extras as $extra=>$value): ?>
        <input type="hidden" name="<?=$this->escape($extra) ?>" value="<?=$this->escape($value) ?>" />
      <? endforeach; ?>
      <input type="submit" name="confirm" value="<?=$this->transEsc('confirm_dialog_yes') ?>" />
    </form>
    <form action="<?=$this->escape($this->cancel) ?>" method="post" data-ajax="false">
      <input type="submit" name="cancel" value="<?=$this->transEsc('confirm_dialog_no') ?>" />
    </form>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>