<li><a href="<?=$this->url('home')?>"><?=$this->transEsc('Home')?></a></li>
<? $current = $this->layout()->breadcrumbs; $current = current($current); ?>
<? foreach($current as $id=>$parent): ?>
  <li><a href="<?=$this->url('collection', ['id'=>$id]) ?>"><?=$parent ?></a></li>
<? endforeach; ?>
<? if(isset($this->layout()->end)): ?>
  <li title="<?=$this->layout()->title ?>"><?=$this->truncate($this->layout()->title, 100) ?></li>
  <li class="active"><?=$this->layout()->end ?></li>
<? else: ?>
  <li class="active" title="<?=$this->layout()->title ?>"><?=$this->truncate($this->layout()->title, 100) ?></li>
<? endif; ?>