<!-- finc: record - comments-list -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * uses <p> and aria-live for alerts #17950, #21622
 * FIXME: remove file in finc, if the changes are available in VuFind; create PR if not yet done
configured in: {}
 */
?>
<?php $comments = $this->driver->getComments(); ?>
<?php if (empty($comments) || count($comments) == 0): ?>
  <?php /* finc: uses <p> and aria-live for alerts #17950, #21622 */ ?>
  <p class="alert alert-info" aria-live="polite"><?=$this->transEsc('Be the first to leave a comment')?>!</p>
<?php else: ?>
  <?php foreach ($comments as $comment): ?>
    <div class="comment">
      <div class="comment-name">
        <strong><?=null === $comment->user_id ? $this->transEsc('comment_anonymous_user') : $this->escapeHtml(trim($comment->firstname . ' ' . $comment->lastname))?></strong><br>
        <small>
          <?=$this->escapeHtml($comment->created)?>
          <?php if (($user = $this->auth()->isLoggedIn()) && $comment->user_id == $user->id): ?>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'DeleteComment'))?>?delete=<?=urlencode($comment->id)?>" id="recordComment<?=$this->escapeHtml($comment->id)?>" class="delete"><?=$this->transEsc('Delete')?></a>
          <?php endif; ?>
        </small>
      </div>
      <div class="comment-text">
        <?=$this->escapeHtml($comment->comment)?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<!-- finc: record - comments-list - END -->
