<!-- finc: record - reporterrorsform -->
<?php
/**
origin: finc
called by view helper/controller:
usage:
modified for finc:
 * finc-specific template, few similarities with finc/emailhold.phtml
configured in: {}
 */
?>
<?php
    // Set page title.
    $this->headTitle($this->translate('ReportErrors'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '<li>', '</li> ')
        . '<li>' . $this->recordLinker()->getBreadcrumbHtml($this->driver) . '</li> '
        . '<li class="active">' . $this->transEsc('ReportErrors') . '</li>';
?>
<?php /* finc: uses h1 instead of h2 #13547 */ ?>
<h1><?=$this->transEsc('ReportErrors') ?>: <?=$this->escapeHtml($this->truncate($this->driver->getShortTitle() . ' ' . $this->driver->getSubTitle(), 90))?></h1>
<form name="reporterrors" method="post" action="<?=$this->recordLinker()->getActionUrl($this->driver, 'ReportErrors')?>">
  <?=$this->flashmessages()?>
  <div class="form-group">
    <label class="control-label" for="reporterrors_email"><?=$this->transEsc("Email")?>:</label>
    <input type="email" id="reporterrors_email" name="reporterrors_email" class="form-control"<?php if (!empty($this->email)): ?> value="<?=$this->email?>"<?php endif; ?>>
    <div class="gutter-top gutter-btm <?php if (empty($this->email)): ?>hidden<?php endif; ?>" id="replyCheckbox">
      <label for="reporterrors_checkbox" class="control-label"><?=$this->transEsc("reporterrors_response_requested")?></label>
      <input type="checkbox" id="reporterrors_checkbox" name="reporterrors_checkbox"<?=($this->reply_requested) ? ' checked' : ''?>>
    </div>
  </div>
  <div class="form-group">
    <label class="control-label" for="comment"><?=$this->transEsc("Note")?>:</label>
    <textarea id="comment" name="comment" class="form-control" required><?=(!empty($this->comment)) ? $this->comment : ''?></textarea>
  </div>
  <div class="form-group">
    <input type="submit" class="btn btn-primary" role="button" name="submit" value="<?=$this->transEscAttr('Send')?>">
  </div>
</form>
<?php $script = <<<JS
$(document).ready(function () {
  // show response email checkbox ReportErrors
  $('input#reporterrors_email').on('keyup change', function () {
    var emailcheck = /^[a-zA-Z0-9_-]+([.][a-zA-Z0-9_-]+)*[@][a-zA-Z0-9_-]+([.][a-zA-Z0-9_-]+)*[.][a-zA-Z]{2,}$/;
    if (($(this).val().length > 0) && emailcheck.test($(this).val())) {
      $('div#replyCheckbox').removeClass('hidden');
    } else {
      $('div#replyCheckbox').addClass('hidden');
      $('input#reporterrors_checkbox').prop("checked", false);
    }
  });
});
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- finc: record - reporterrorsform - End -->
