<!-- START of: national - footer.phtml -->
<div class="row">
  <div class="col-sm-3">
    <h5><strong><?=$this->transEsc('About')?></strong></h5>
    <ul>
      <li><a href="<?=$this->url('content-page', ['page' => 'organisations'])?>"><?=$this->transEsc('Who participates in Finna')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'About'])?>"><?=$this->transEsc('What is Finna')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'terms_conditions'])?>"><?=$this->transEsc('Privacy & Terms')?></a></li>
      <li><a href="<?=$this->url('content-page', ['page' => 'register_details'])?>"><?=$this->transEsc('Register Details')?></a></li>
    </ul>
  </div>
  <div class="col-sm-3">
    <h5><strong><?=$this->transEsc('Find More')?></strong></h5>
    <ul>
      <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
      <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
      <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
    </ul>
  </div>
  <div class="col-sm-3">
    <h5><strong><?=$this->transEsc('Need Help?')?></strong></h5>
    <ul>
      <li><a href="<?=$this->url('content-page', ['page' => 'Help'])?>" title="<?=$this->transEsc('Help')?>"><?=$this->transEsc('Help')?></a></li>
      <li><a class="modal-link" href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc('Feedback')?></a></li>
    </ul>
  </div>
  <div class="col-sm-3">
  </div>
</div>
<hr>
<div class="row">
  <div class="col-sm-3">
    <a href="<?=$this->url('home')?>"><img src="<?=$this->imageLink('finna-logo.png')?>" alt="Finna-logo" /></a><br><br>
  </div>
  <div class="col-sm-3">
     <a href="http://www.kdk.fi/"><img src="<?=$this->imageLink('kdk_logo_' . $this->layout()->userLang . '.png')?>" alt="KDK-logo" /></a><br><br>
  </div>
  <div class="col-sm-3">
    <a href="http://www.vufind.org/" title=""><img src="<?=$this->imageLink('vufind-logo.png')?>" alt="Vufind-logo" /></a>
  </div>
  <div class="col-sm-3">
  </div>
</div>
<!-- END of: national - footer.phtml -->
