<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    // Grab clean ISBN for convenience:
    $isbn = $this->driver->getCleanISBN();
?>
<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">

  <!-- original vufind fields -->
  <?php $summ = $this->driver->getSummary(); if (!empty($summ)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Summary')?>: </th>
      <td>
        <?php foreach ($summ as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <? endif; ?>

  <?php $dateSpan = $this->driver->getDateSpan(); if (!empty($dateSpan)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Published')?>: </th>
      <td>
        <?php foreach ($dateSpan as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $notes = $this->driver->getGeneralNotes(); if (!empty($notes)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Item Description')?>: </th>
      <td>
        <?php foreach ($notes as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $physical = $this->driver->getPhysicalDescriptions(); if (!empty($physical)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Physical Description')?>: </th>
      <td>
        <?php foreach ($physical as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $freq = $this->driver->getPublicationFrequency(); if (!empty($freq)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication Frequency')?>: </th>
      <td>
        <?php foreach ($freq as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $playTime = $this->driver->getPlayingTimes(); if (!empty($playTime)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Playing Time')?>: </th>
      <td>
        <?php foreach ($playTime as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $system = $this->driver->getSystemDetails(); if (!empty($system)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Format')?>: </th>
      <td>
        <?php foreach ($system as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $audience = $this->driver->getTargetAudienceNotes(); if (!empty($audience)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Audience')?>: </th>
      <td>
        <?php foreach ($audience as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $awards = $this->driver->getAwards(); if (!empty($awards)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Awards')?>: </th>
      <td>
        <?php foreach ($awards as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $credits = $this->driver->getProductionCredits(); if (!empty($credits)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Production Credits')?>: </th>
      <td>
        <?php foreach ($credits as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $bib = $this->driver->getBibliographyNotes(); if (!empty($bib)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Bibliography')?>: </th>
      <td>
        <?php foreach ($bib as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $isbns = $this->driver->getISBNs(); if (!empty($isbns)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('ISBN')?>: </th>
      <td>
        <?php foreach ($isbns as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $issns = $this->driver->getISSNs(); if (!empty($issns)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('ISSN')?>: </th>
      <td>
        <?php foreach ($issns as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $doi = $this->driver->tryMethod('getCleanDOI'); if (!empty($doi)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('DOI')?>: </th>
      <td><?=$this->escapeHtml($doi)?></td>
    </tr>
  <?php endif; ?>

  <?php $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Related Items')?>: </th>
      <td>
        <?php foreach ($related as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Access')?>: </th>
      <td>
        <?php foreach ($access as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $findingAids = $this->driver->getFindingAids(); if (!empty($findingAids)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Finding Aid')?>: </th>
      <td>
        <?php foreach ($findingAids as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $publicationPlaces = $this->driver->getHierarchicalPlaceNames(); if (!empty($publicationPlaces)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Publication_Place')?>: </th>
      <td>
        <?php foreach ($publicationPlaces as $field): ?>
          <?=$this->escapeHtml($field)?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <?php $authorNotes = empty($isbn) ? array() : $this->authorNotes($isbn); if (!empty($authorNotes)): ?>
    <?php $contentDisplayed = true; ?>
    <tr>
      <th><?=$this->transEsc('Author Notes')?>: </th>
      <td>
        <?php foreach ($authorNotes as $provider => $list): ?>
          <?php foreach ($list as $field): ?>
            <?=$field['Content']?><br/>
          <?php endforeach; ?>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>

  <!-- custom ixtheo fields -->
  <?php $references = $this->driver->getReferenceInformation() ?>
  <?php if (!empty($references)): ?>
       <tr>
          <th><?=$this->transEsc('Reference')?>: </th>
          <td>
            <?php foreach($references as $reference): ?>
              <?php if (!empty($reference['id'])): ?>
                <a href="<?=$this->recordLink()->getUrl($reference['id'])?>"><?=$reference['description']?></a>
              <?php else: ?>
                <?=$reference['description']?>
              <?php endif; ?>
              <br>
            <?php endforeach; ?>
          </td>
        </tr>
  <?php endif; ?>

  <?php $contains = $this->driver->getContainsInformation() ?>
  <?php if (!empty($contains)): ?>
       <tr>
          <th><?=$this->transEsc('Contains')?>: </th>
          <td>
            <?php foreach($contains as $contain): ?>
              <?php if (!empty($contain['id'])): ?>
                <a href="<?=$this->recordLink()->getUrl($contain['id'])?>"><?=$contain['description']?></a>
              <?php else: ?>
                <?=$contain['description']?>
              <?php endif; ?>
              <br>
            <?php endforeach; ?>
          </td>
        </tr>
  <?php endif; ?>



  <?php $types_and_persistent_identifiers = $this->driver->getTypesAndPersistentIdentifiers(); if (!empty($types_and_persistent_identifiers)): ?>
    <tr>
        <th>Persistent identifiers: </th>
        <td>
            <?php foreach ($types_and_persistent_identifiers as $type => $persistent_identifiers): ?>
                <?php foreach ($persistent_identifiers as $persistent_identifier): ?>
                    <?=$type . ' &quot;' . $persistent_identifier . '&quot;'?><br/>
                <?php endforeach; ?>
            <?php endforeach; ?>
        </td>
    </tr>
  <?php endif; ?>


  <!-- vufind: message if no data -->
  <?php if (!isset($contentDisplayed) || !$contentDisplayed): // Avoid errors if there were no rows above ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <?php endif; ?>
</table>
