<?
  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
      $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $handlers = $this->searchbox()->getHandlers(
      $this->searchClassId,
      isset($this->searchIndex) ? $this->searchIndex : null
  );
  $handlerCount = count($handlers);
  $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
  $lastSort = $options->getLastSort();
  $lastLimit = $options->getLastLimit();
?>
<form method="get" action="<?=$this->url($basicSearch)?>" data-ajax="false">
  <label class="offscreen" for="searchForm_lookfor">
    <?=$this->transEsc("Search")?>
  </label>
  <input type="search" placeholder="<?=$this->transEsc("Search")?>" name="lookfor" id="searchForm_lookfor" value="<?=$this->escapeHtmlAttr($this->lookfor)?>"/>
  
  <label class="offscreen" for="searchForm_type"><?=$this->transEsc("Search Type")?></label>
  <? if ($handlerCount > 1): ?>
    <select id="searchForm_type" name="type" data-native-menu="false">
      <? foreach ($handlers as $handler): ?>
        <option value="<?=$this->escapeHtmlAttr($handler['value'])?>"<?=$handler['selected'] ? ' selected="selected"' : ''?>><?=$handler['indent'] ? '-- ' : ''?><?=$this->transEsc($handler['label'])?></option>
      <? endforeach; ?>
    </select>
  <? elseif ($handlerCount == 1): ?>
    <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
  <? endif; ?>
  <div data-role="fieldcontain">
    <input type="submit" data-theme="b" name="submit" value="<?=$this->transEsc("Find")?>"/>
  </div>
  <?
    /* Show hidden field for active search class when in combined handler mode. */
    if ($this->searchbox()->combinedHandlersActive()) {
      echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
    }
    /* Load hidden limit preference from Session */
    if (!empty($lastLimit)) {
      echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
    }
    if (!empty($lastSort)) {
      echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
    }
  ?>
</form>
