<table class="table table-striped">
  <tbody>
    <tr>
      <th><?=$this->transEsc("Author")?></th><th><?=$this->transEsc("sort_author_relevance")?></th>
    </tr>
    <?php foreach ($this->results->getResults() as $record): ?>
      <tr>
        <td>
          <?php if ($this->tuefind()->isSearchTabEnabled('SolrAuth')): ?>
            <?php if (stripos($record['value'], ":") !== false): $nameAndId = explode(":", $record['value']); $authorityId = $nameAndId[0]; $authorName = $nameAndId[1]; ?>
              <?=$this->escapeHtml($authorName)?>
              <a href="<?=$this->authority()->getTitlesByUrlNameOrID($authorName,$authorityId)?>"><i class="fa fa-book" aria-hidden="true" title="Show more titles for this author"></i></a>
              <?php if(!empty($authorityId)):?>
                <a href="/Authority/<?=$authorityId?>"><i class="fa fa-user-circle" aria-hidden="true" title="Show more details for this author"></i></a>    
              <?php endif; ?>    
            <?php endif; ?>
          <?php else: ?>
            <a href="<?=$this->url('author-home')?>?author=<?=urlencode($record['value'])?>"><?=$this->escapeHtml($record['value'])?></a>
          <?php endif; ?>
        </td>
        <td><?=$this->escapeHtml($record['count'])?></td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
