<?php
  $routeParams = $this->tuefind()->getRouteParams();
  if($routeParams['controller'] == "Authority" && $routeParams['action'] == "Home") {
    foreach($searchTabs as &$sTabs) {
      if(empty($sTabs['url'])) {
        $sTabs['url'] = '/';
      }
      if($sTabs['url'] == "/Authority/Home") {
        $sTabs['selected'] = 1;
      }else{
        $sTabs['selected'] = '';
      }
    }
  }
  if (isset($searchTabs) && count($searchTabs) > 0): ?>
  <ul class="nav nav-tabs tuefind-event-resetsearchhandlers" >
    <?php foreach ($searchTabs as $tab): ?>
        <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
          <li<?=$tab['selected'] ? ' class="active"' : ''?>>
            <a <?=$tab['selected'] ? '' : 'href="' . $this->escapeHtmlAttr($tab['url']) . '"' ?>><?=$this->transEsc($tab['label']); ?></a>
          </li>
        <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
            <?=$block?>
        <?php endif; ?>
    <?php endforeach; ?>
  </ul>
<?php endif; ?>
