<div class="sidegroup">
  <h4 class="account"><?=$this->transEsc('Your Account')?></h4>
  <ul class="bulleted">
    <li<?=$this->active == 'favorites' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'MyResearch', 'action' => 'Favorites'), 'default', true)?>"><?=$this->transEsc('Favorites')?></a></li>
    <li<?=$this->active == 'checkedout' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'MyResearch', 'action' => 'CheckedOut'), 'default', true)?>"><?=$this->transEsc('Checked Out Items')?></a></li>
    <li<?=$this->active == 'holds' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'MyResearch', 'action' => 'Holds'), 'default', true)?>"><?=$this->transEsc('Holds and Recalls')?></a></li>
    <li<?=$this->active == 'fines' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'MyResearch', 'action' => 'Fines'), 'default', true)?>"><?=$this->transEsc('Fines')?></a></li>
    <li<?=$this->active == 'profile' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'MyResearch', 'action' => 'Profile'), 'default', true)?>"><?=$this->transEsc('Profile')?></a></li>
    <li<?=$this->active == 'history' ? ' class="active"' : ''?>><a href="<?=$this->url(array('controller' => 'Search', 'action' => 'History'), 'default', true)?>?require_login"><?=$this->transEsc('history_saved_searches')?></a></li>
  </ul>
</div>
