<?php foreach ($checkboxFilters as $current): ?>
  <?php
    $isHidden = !($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible']);
    $href = $current['selected']
      ? $results->getUrlQuery()->removeFilter($current['filter'])
      : $results->getUrlQuery()->addFilter($current['filter']);
  ?>
  <div class="facet<?=$current['selected'] ? ' active' : ''?>" data-facet="<?=$this->escapeHtmlAttr($current['filter'])?>">
    <a class="checkbox-filter icon-link<?=$isHidden ? ' hidden' : '' ?>" href="<?=$href ?>">
      <?php if ($current['selected']): ?>
        <span class="visually-hidden"><?=$this->transEsc('clear_tag_filter') ?></span>
      <?php endif; ?>

      <?= $this->icon($current['selected'] ? 'facet-checked' : 'facet-unchecked', [
          'class' => 'icon-link__icon',
          'data-checked' => $current['selected'] ? 'true' : 'false',
      ]) ?>
      <span class="text">
        <span class="icon-link__label"><?=$this->transEsc($current['desc']) ?></span>
      </span>
      <?php if (!$current['selected']): ?>
        <?php
          // Note: we need to ensure the element exists (for deferred side facets) but is empty if count is not
          // available:
          $countEsc = isset($current['count']) ? $this->localizedNumber($current['count']) : '';
        ?>
        <span class="badge avail-count"><?=$countEsc?></span>
      <?php endif; ?>
    </a>
  </div>
<?php endforeach; ?>
