<!-- START of: finna - RecordTab/collectionlist.phtml -->
<?
  // Get search results
  $results = $this->tab->getResults();
  $params = $this->tab->getParams();
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1, 'isCollection' => $this->driver->isCollection()];
?>
<? if (($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <? foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <? endforeach; ?>

  <div class="collection-list-controls">
    <div class="filter-input">
      <span class="hidden-xs"><?=$this->transEsc('Search from collection')?></span>
      <form class="form-inline" role="form" method="get" name="keywordFilterForm" id="keywordFilterForm">
        <div class="input-group">
          <input id="keywordFilter_lookfor" type="text" name="lookfor" placeholder="<?=$this->transEsc('Search from collection')?>" value="<?=$params->getDisplayQuery()?>" class="form-control"/>
            <? foreach ($params->getFilterList(true) as $field => $filters): ?>
              <? foreach ($filters as $filter): ?>
                <input type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($filter['field'])?>:&quot;<?=$this->escapeHtmlAttr($filter['value'])?>&quot;" />
              <? endforeach; ?>
            <? endforeach; ?>
            <input type="hidden" name="view" value="<?=$params->getView() ?>" />
            <input type="hidden" name="sort" value="<?=$params->getSort() ?>" />
          <span class="input-group-btn"><button class="btn btn-primary btn-default" type="submit" name="submit"><span class="sr-only"><?=$this->transEsc('Search')?></span><i class="fa fa-search"></i></button></span>
        </div>
      </form>
    </div>
    <?=$this->render('search/controls/view.phtml', $searchDetails)?>
    <?=$this->render('search/controls/sort.phtml', $searchDetails)?>
  </div>
  <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $results])?>

  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>">
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', $searchDetails + ['idPrefix' => ''])?>
  </form>
  <div class="results result-view-<?=$this->escapeHtmlAttr($params->getView()) == 'grid' ? 'grid' : $this->escapeHtmlAttr($params->getView());?>">
    <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
  </div>
    <div class="text-center">
    <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results])?>
    </div>

<? else: ?>
  <h4><?=$this->transEsc('collection_empty')?></h4><br><br>
<? endif; ?>
<!-- END of: finna - RecordTab/collectionlist.phtml -->
