<!-- START of: finna - RecordTab/componentparts.phtml -->
<?php
    $componentParts = $this->driver->tryMethod('getEmbeddedComponentParts');

    $havePresenters = false;
    $haveDuration = false;
    foreach ($componentParts as $part) {
        if ($part['presenters']) {
            $havePresenters = true;
        }
        if ($part['duration']) {
            $haveDuration = true;
        }
    }
?>
<table id="componentparts" class="display table">
  <thead>
    <tr>
      <th><?=$this->translate('No.') ?></th>
      <th><?=$this->translate('Title and Authors') ?></th>
      <?php if ($havePresenters): ?>
        <th><?=$this->translate('Presenters') ?></th>
      <?php endif; ?>
      <?php if ($haveDuration): ?>
        <th><?=$this->translate('Playing Time') ?></th>
      <?php endif; ?>
    </tr>
  </thead>
  <tbody>
  <?php foreach ($componentParts as $part): ?>
    <tr>
      <td style="width: 10%"><?=$this->escapeHtml($part['number']) ?></td>
      <td>
        <?php if (!empty($part['id'])): ?>
          <a href="<?=$this->recordLink()->getUrl($part['id']) ?>"><?=$this->escapeHtml($part['title']) ?></a>
        <?php else: ?>
          <?=$this->escapeHtml($part['title']) ?>
        <?php endif; ?>
        <br/>
        <?php if (!empty($part['uniformTitle'])): ?>
          <?=$this->escapeHtml($part['uniformTitle']) ?>
          <br/>
        <?php endif; ?>
        <div class="part-authors<?=empty($part['id']) || !empty($part['uniformTitle']) ? '-padded' : '' ?>" title="<?=$this->escapeHtmlAttr(implode(' ; ', $part['otherAuthors'])) ?>">
	        <?=$this->escapeHtml(implode(' ; ', array_slice($part['otherAuthors'], 0, 3)) . (count($part['otherAuthors']) > 3 ? '...' : '')) ?>
	      </div>
	    </td>
	    <?php if ($havePresenters): ?>
        <td title="<?=$this->escapeHtmlAttr(implode(' ; ', $part['presenters'])) ?>">
	        <?=$this->escapeHtml(implode(' ; ', array_slice($part['presenters'], 0, 3)) . (count($part['presenters']) > 3 ? '...' : '')) ?>
        </td>
      <?php endif; ?>
      <?php if ($haveDuration): ?>
        <td><?=$this->escapeHtml($part['duration']) ?></td>
      <?php endif; ?>
    </tr>
  <?php endforeach; ?>
  </tbody>
</table>

<?php
$translations = '{'
    . '"sSearch": "' . $this->transEsc('component_parts_filter') . '",'
    . '"sLengthMenu": "' . $this->transEsc('component_parts_show_entries') . '",'
    . '"sInfoFiltered": "' . $this->transEsc('component_parts_filtered') . '",'
    . '"sInfo": "' . $this->transEsc('component_parts_entries_on_page') . '",'
    . '"oPaginate": {'
    . '"sNext": "<i class=\"fa fa-arrow-right\"></i> <span class=\"sr-only\">' . $this->transEsc('component_parts_next') . '</span>",'
    . '"sPrevious": "<span class=\"sr-only\">' . $this->transEsc('component_parts_previous') . '</span> <i class=\"fa fa-arrow-left\"></i>",'
    . '},'
    . '"sThousands": VuFind.translate("number_thousands_separator")'
    . '}';

$script = <<<JS
$(document).ready(function() {
  $('table#componentparts').dataTable({
    "iDisplayLength": 50,
    "oLanguage": {$translations},
  });
});
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- END of: finna - RecordTab/componentparts.phtml -->
