<!-- START of: finna - RecordTab/holdingsils.phtml -->
<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0
        ];
        $offlineMode = 'ils-offline';
    }
    $holdsAllowed = $this->driver->tryMethod('getHoldsAllowed');
    if (!isset($holdings['holdings'])) {
        $holdings['holdings'] = [];
        $holdings['total'] = 0;
        $holdings['page'] = 1;
        $holdings['itemLimit'] = 10;
    }

    $illRequestLink = false;
    $holdLinks = $journal = $summary = false;

    // Use location-specific hold links only if we have branches
    $first = reset($holdings['holdings']);
    $useLocationHoldLinks = isset($first['items'][0]['branch']);

    if (!empty($holdings['holdings'])) {
      $location = reset($holdings['holdings']);
      $item = $location['items'][0];
      $journal = isset($item['journalInfo']);

      $last = array_pop($holdings['holdings']);
      if (isset($last['items']) && is_array($last['items'])) {
          $summary = $last['items'][0];
          if (($summary['location'] ?? '') !== '__HOLDINGSSUMMARYLOCATION__') {
             $summary = false;
          }
      }
      if (!$summary) {
         $holdings['holdings'][] = $last;
      }
    }

    $disableTitleHold = empty($holdings['holdings']) || (isset($summary['holdable']) && !$summary['holdable']);
    $showSummary = !$journal && $this->holdingsSettings()->showRecordPageSummary();
    if ($summary && $showSummary) {
      $itemsTotal
        = $summary['total'] ?? null;
      $reservationsTotal
        = $summary['reservations'] ?? null;
    }

    foreach ($holdings['holdings'] as $holding) {
       foreach ($holding['items'] as $row) {
          if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']) {
             $illRequestLink = $row['ILLRequestLink'];
          }
          if (isset($row['link']) && $row['link']) {
             $holdLinks = true;
             if ($useLocationHoldLinks && (!$journal || !empty($row['item_id']))) {
                $holdLinksLocation[$row['location']] = $row['link'];
             }
          }
       }
    }
    $ilsLoginAvailable = $this->ils()->loginAvailable();
?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if ($holdsAllowed && !$disableTitleHold && (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver')): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline' && $ilsLoginAvailable): ?>
    <?php if (!$user): ?>
      <div class="pull-right">
        <a href="?login=true&amp;catalogLogin=true" class="btn btn-primary login-link" data-lightbox><?=$this->transEsc("title_hold_login")?></a>
      </div>
      <div class="clearfix"></div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->recordLink()->getTabUrl($this->driver, 'Holdings', ['catalogLogin' => 'true'])])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
<div class="table record-holdings-url-table">
  <div class="headers">
    <span class="holdings-url-title"><?=$this->transEsc("Links")?></span>
  </div>
  <div class="holdings-urls">
    <?php if (!empty($urls)): ?>
      <?php foreach ($urls as $current): ?>
        <a class="holdings-url-link" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>" target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('external_online_link'))?>"><i class="fa fa-external-link"></i> <?=$this->transEsc('default::link_' . $current['desc'], null, $current['desc'])?></a>
      <?php endforeach; ?>
    <?php endif; ?>
    <?php if ($openUrlActive): ?>
      <?=$openUrl->renderTemplate()?>
      <?php
        $loadOpenURLs = "finna.openUrl.initLinks($('.holdings-urls'));";
        echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $loadOpenURLs, 'SET')
      ?>
    <?php endif; ?>
    <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
  </div>
</div>
<?php endif; ?>

<?php if ($holdsAllowed): ?>
  <div class="place-hold-wrapper text-right hidden-print">
  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn(), 'label' => 'Library Card']); ?>
  <?php if ($illRequestLink): ?>
    <a class="expandedCheckILLRequest placeILLRequest btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($illRequestLink)?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('ill_request_place_text') . ': ' . $this->driver->getTitle()) ?>"><?=$this->transEsc("ill_request_check_text")?></a>
  <?php endif; ?>
  <?php if (!$disableTitleHold): ?>
    <?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
      <a class="placehold btn btn-primary hidden-print" data-lightbox data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('title_hold_place') . ': ' . $this->driver->getTitle()) ?>" href="<?=$this->recordLink()->getRequestUrl($holdingTitleHold)?>"> <?=$this->transEsc('title_hold_place')?></a>
    <?php elseif ($user): ?>
      <?php
        $blocks = [];
        if (!empty($holdings['blocks'])) {
          $blocks = $holdings['blocks'];
          $blocks[] = $this->translate('hold_error_blocked');
        } elseif (!$illRequestLink && !$holdLinks) {
          $blocks[] = $this->translate('title_cant_place_hold');
        }
        if ($blocks):
      ?>
        <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $blocks]) ?>
      <?php endif; ?>
    <?php endif; ?>
  <?php endif; ?>
  </div>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=$this->context($this)->renderInContext(
      'RecordTab/holdingsils/electronic.phtml',
      ['holdings' => $holdings['electronic_holdings']]
  );?>
<?php endif; ?>

<div class="table record-holdings-table">
  <div class="headers">
    <?php $currentSource = $this->driver->tryMethod('getDataSource'); ?>
    <?php $mergedData = $this->driver->tryMethod('getMergedRecordData'); ?>
    <?php $recordSourceId = $this->driver->getSourceIdentifier(); ?>
    <div class="dedup-information">
      <span class="holdings-title"><?=$this->transEsc("source_$currentSource", null, $currentSource) ?></span>
      <?php if ($mergedData && count($mergedData['records']) > 1): ?>
        <select class="dedup-select form-control jumpMenuUrl hidden-print" role="listbox" aria-haspopup="true" title="<?=$this->transEsc('select_dedup_organisation');?>">
          <option value="#" role="option" selected="selected"><?=$this->transEsc('Other Libraries'); ?></option>
          <?php foreach ($mergedData['records'] as $current): ?>
            <?php if ($currentSource != $current['source']): ?>
              <option value="<?=$this->recordLink()->getUrl($recordSourceId . '|' . $current['id']) ?>" role="option"><?=$this->transEsc("source_{$current['source']}", null, $current['source']) ?></option>
            <?php endif; ?>
          <?php endforeach; ?>
        </select>
      <?php endif; ?>
      </div>
    <?php if (!empty($holdings['holdings'])): ?>
      <div class="reservations-container">
        <?php if ($showSummary): ?>
          <?php if (!empty($reservationsTotal)): ?>
            <span class="reservations"><?=$this->translate('status_requests_html', ['%%count%%' => $reservationsTotal]);?></span>
          <?php endif; ?>
          <?php if (!empty($itemsTotal)): ?>
            <span class="total"><?=$this->translate('status_items_total_html', ['%%count%%' => $itemsTotal]);?></span>
          <?php endif; ?>
        <?php endif; ?>
      </div>
      <div class="total-container hidden-xs text-right">
        <?=$this->transEsc("shelf_location"); ?>
      </div>
    <?php endif; ?>
  </div>
<?php $holdingsGroup = 0; ?>
<?php foreach ($holdings['holdings'] as $holdingId => $holding): ?>
  <?php
    ++$holdingsGroup;

    $available = 0;
    $firstDueDate = '';
    $firstDueStr = '';
    $statuses = [];
    $requests = 0;
    $branches = false;
    foreach ($holding['items'] as $row) {
      if ($row['availability']) {
        ++$available;
      }
      if ($row['duedate'] && empty($row['ignoreDueDate'])) {
        $date = strtotime($row['duedate']);
        if ((!$firstDueDate || abs(time() - $date) < abs(time() - $firstDueDate))) {
          $firstDueDate = $date;
          $firstDueStr = $row['duedate'];
        }
      }
      $statuses[$this->translate('status_' . $row['status'], null, $this->translate($row['status']))] = 1;
      if (isset($row['branch'])) {
        $branches = true;
      } else {
        if (isset($row['requests_placed']) && $row['requests_placed'] > $requests) {
          $requests = $row['requests_placed'];
        }
      }
    }
    if ($available) {
      $holdingSummary = '<span class="text-success"><i class="fa fa-ok" aria-hidden="true"></i> ' . $this->translate('status_items_available_html', ['%%count%%' => $available]) . '</span>';
    } elseif ($firstDueStr) {
      $holdingSummary = '<span class="text-danger"><i class="fa fa-remove" aria-hidden="true"></i> ' . $this->transEsc('closest_due_date', ['%%date%%' => $firstDueStr]) . '</span>';
    } elseif ($statuses) {
      $holdingSummary = '<span class="text-danger"> ' . $this->escapeHtml(implode(' ', array_flip($statuses))) . '</span>';
    } else {
      $holdingSummary = '<span class="text-success"><i class="fa fa-ok" aria-hidden="true"></i> ' . $this->transEsc('Available') . '</span>';
    }

    $additionalSummary = [];
    if ($requests) {
      $additionalSummary[] = $this->translate('status_requests_html', ['%%count%%' => $requests]);
    }
    foreach ($additionalSummary as $i => $summaryItem) {
      $holdingSummary .= '<span class="small"> &ndash;&nbsp;' . $summaryItem . '</span>';
    }

    // N.B. $holdingsDetails also affects request checks in finna-record
    switch ($this->holdingsSettings()->getDetailsMode())
    {
    case 'collapse':
        $holdingsDetails = 'collapsed';
        break;
    case 'expand-all':
        $holdingsDetails = 'expanded';
        break;
    default:
        $holdingsDetails = $holdingsGroup == 1 ? 'expanded' : 'collapsed';
        break;
    }
  ?>
  <?php
    $callnumbers = [];
    foreach ($this->tab->getUniqueCallNumbers($holding['items']) as $callNo) {
       $collection = null;
       $location = null;
       foreach ($holding['items'] as $item) {
          if ($item['callnumber'] === $callNo) {
             if (!$collection && isset($item['collection'])) {
                $collection = $item['collection'];
             }
             if (!$location && isset($item['location'])) {
                $location = $item['location'];
             }
             if ($collection && $location) {
                break;
             }
          }
       }
       $callnumbers[] = ['callNo' => $callNo, 'collection' => $collection, 'location' => $location];
    }
    $dialogTitle = ': ' . $this->driver->getTitle();
    $titleLocation = $this->transEscWithPrefix('location_', $holding['location']);
    if ($titleLocation) {
        $dialogTitle .= " - $titleLocation";
    }
  ?>
  <?php if ($holdingsGroup == 1 && $holdingsConfig = $this->ils()->getConfig('Holdings', [$this->driver->getUniqueId()])): ?>
    <?php if (!empty($holdingsConfig['extra_texts'])): ?>
      <div class="holdings-container-heading">
        <div>
          <?php foreach ($holdingsConfig['extra_texts'] as $extraText): ?>
            <div class="holdings-extra-text"><?=$this->translate($extraText, ['%%recordId%%' => $this->driver->getUniqueId()])?></div>
          <?php endforeach; ?>
        </div>
      </div>
    <?php endif; ?>
  <?php endif; ?>
  <div class="holdings-container-heading">
    <div class="location">
      <i class="fa fa-arrow-<?=$holdingsDetails == 'collapsed' ? 'right' : 'down'?>" aria-hidden="true"></i> <?=$this->transEscWithPrefix('location_', $holding['location'])?>
      <?php if ($this->holdingsSettings()->showDetailsAfterLocationGroup()): ?>
        <div class="details"><?=$this->partial('RecordTab/holdings-details.phtml', ['holdingId' => $holdingId, 'holding' => $holding, 'heading' => true]);?></div>
      <?php endif; ?>
    </div>
    <div class="holdings-details"><?=$holdingSummary ?></div>
    <div class="location-link text-right">
      <?php foreach ($callnumbers as $data): ?>
        <?=$this->callnumber()->callnumber($currentSource, $this->driver->getFullTitle(), $data['callNo'], $data['collection'], $data['location'], $this->layout()->userLang)?>
      <?php endforeach; ?>
      <?php if ($holdsAllowed && isset($holdLinksLocation[$holding['location']])): ?>
        <a class="expandedCheckRequest inlineblock placehold btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($holdLinksLocation[$holding['location']])?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('request_place_text') . $dialogTitle); ?>"><?=$this->transEsc("request_place_text")?></a>
      <?php endif; ?>
    </div>
  </div>
  <div class="clearfix"></div>
  <?php if (!$this->holdingsSettings()->showDetailsAfterLocationGroup()): ?>
    <?=$this->partial('RecordTab/holdings-details.phtml', ['holdingId' => $holdingId, 'holding' => $holding, 'mode' => $holdingsDetails]);?>
  <?php endif; ?>
  <?php $formats = $this->driver->getFormats(); ?>
  <?php if (!empty($holding['items'][0]['order_statuses']) && !in_array(end($formats), ['1/Book/eBook/', '1/Journal/eJournal/', '1/Journal/eArticle/'])): ?>
    <div class="copy-details <?=$holdingsDetails?>">
      <div><?=$this->transEsc("Order Information") ?>:</div>
      <div>
        <?php foreach ($holding['items'][0]['order_statuses'] as $orderStatus): ?>
          <?=$this->transEsc('order_status_' . $orderStatus['status'], null, $orderStatus['status']) ?> <?=$this->escapeHtml($orderStatus['order_update_date']) ?>
        <?php endforeach; ?>
      </div>
    </div>
  <?php endif; ?>
  <?php foreach ($holding['items'] as $rowNum => $row): ?>
    <?php
      // AJAX Check record?
      $check = isset($row['check']) && $row['check'];
      $checkStorageRetrievalRequest = isset($row['checkStorageRetrievalRequest']) && $row['checkStorageRetrievalRequest'];
      $checkILLRequest = isset($row['checkILLRequest']) && $row['checkILLRequest'];
      // AJAX block record?
      $block = !$check && isset($row['addLink']) && $row['addLink'] === 'block';
      $blockStorageRetrievalRequest = !$checkStorageRetrievalRequest && isset($row['addStorageRetrievalRequestLink']) && $row['addStorageRetrievalRequestLink'] === 'block';
      $blockILLRequest = !$checkILLRequest && isset($row['addILLRequestLink']) && $row['addILLRequestLink'] === 'block';
      $currentDepartment = '';
    ?>
    <div vocab="http://schema.org/" typeof="Offer" class="copy-details <?=$holdingsDetails?>">
      <?php if (isset($row['branch']) || isset($row['department'])): ?>
        <?php
          $parts = [];
          if (!empty($row['branch'])) {
            $parts[] = '<span class="branch">' . $this->escapeHtml($row['branch']) . '</span>';
          }
          if (!empty($row['department'])) {
            $parts[] = '<span class="department">' . $this->escapeHtml($row['department']) . '</span>';
          }
          if (!empty($row['callnumber']) && count($callnumbers) > 1) {
            $parts[] = '<span class="callnumber">' . $this->escapeHtml($row['callnumber']) . '</span>';
          }
        ?>
        <div class="copy-title">
          <?php if (!$branches): ?>
            <span class="copy-number"><?=!empty($row['number']) ? $this->escapeHtml($row['number']) : $this->transEsc("Copy") ?></span>
          <?php endif; ?>
          <?=implode(', ', $parts);?>
        </div>
      <?php else: ?>
        <div class="copy-title">
          <span class="copy-number"><?=!empty($row['number']) ? $this->escapeHtml($row['number']) : $this->transEsc("Copy") ?></span>
        </div>
      <?php endif; ?>
      <div class="copy-info">
        <?php if (isset($row['reserve']) && $row['reserve'] == "Y"): ?>
          <link property="availability" href="http://schema.org/InStoreOnly" />
          <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
        <?php endif; ?>
        <?php if (isset($row['use_unknown_message']) && $row['use_unknown_message']): ?>
          <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
        <?php else: ?>
          <?php if ($row['availability']): ?>
            <?php /* Begin Available Items (Holds) */ ?>
            <span class="text-success"><i class="fa fa-ok" aria-hidden="true"></i> <?=$this->transEsc(isset($row['availabilityInfo']['displayText']) ? 'status_' . $row['availabilityInfo']['displayText'] : 'Available')?><link property="availability" href="http://schema.org/InStock" /></span>
            <?php if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
              &ndash;&nbsp;<span class="small"><?=$this->translate('status_requests_html', ['%%count%%' => $this->escapeHtml($row['requests_placed'])])?></span>
            <?php endif; ?>
            <div class="pull-right">
            <?php if (!$journal): ?>
              <?php if (!$block && isset($row['link']) && $row['link'] && $holdsAllowed): ?>
                <a class="<?=$check ? "{$holdingsDetails}CheckRequest " : ''?>inlineblock placehold btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate("Place a Hold") . $dialogTitle); ?>"><?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
              <?php endif; ?>
              <?php if (!$blockStorageRetrievalRequest && isset($row['storageRetrievalRequestLink']) && $row['storageRetrievalRequestLink']): ?>
                <a class="<?=$checkStorageRetrievalRequest ? "{$holdingsDetails}CheckStorageRetrievalRequest " : ''?>inlineblock placeStorageRetrievalRequest btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['storageRetrievalRequestLink'])?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate("storage_retrieval_request_place_text") . $dialogTitle); ?>"><?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
              <?php endif; ?>
              <?php if (!$blockILLRequest && isset($row['ILLRequestLink']) && $row['ILLRequestLink']): ?>
                <a class="<?=$checkILLRequest ? "{$holdingsDetails}CheckILLRequest " : ''?>inlineblock placeILLRequest btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['ILLRequestLink'])?>"  data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate("ill_request_place_text") . $dialogTitle); ?>"><?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
              <?php endif; ?>
            <?php endif; ?>
            </div>
          <?php else: ?>
            <?php /* Begin Unavailable Items (Recalls) */ ?>
            <span class="text-danger"><?=$row['status'] == 'Ordered' ? '' : '<i class="fa fa-remove" aria-hidden="true"></i>';?> <?=$this->transEsc('status_' . $row['status'], null, $this->translate($row['status']))?><link property="availability" href="http://schema.org/OutOfStock" /> </span>
            <?php if (isset($row['returnDate']) && $row['returnDate']): ?>&ndash; <span class="small"><?=$this->escapeHtml($row['returnDate'])?></span><?php endif; ?>
            <?php if (isset($row['duedate']) && $row['duedate']): ?>
              &ndash;&nbsp;<span class="small"><?=$this->transEsc('Due')?>:&nbsp;<?=$this->escapeHtml($row['duedate'])?></span>
            <?php endif; ?>
            <?php if (isset($row['requests_placed']) && $row['requests_placed'] > 0): ?>
              &ndash;&nbsp;<span class="small"><?=$this->translate('status_requests_html', ['%%count%%' => $this->escapeHtml($row['requests_placed'])])?></span>
            <?php endif; ?>
            <?php if (!$journal && !$block && isset($row['link']) && $row['link'] && $holdsAllowed): ?>
              <div class="pull-right">
                <a class="<?=$check ? "{$holdingsDetails}CheckRequest " : ''?>inlineblock placehold btn btn-primary hidden-print" data-lightbox href="<?=$this->recordLink()->getRequestUrl($row['link'])?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate("Recall This") . $dialogTitle); ?>"><?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
              </div>
            <?php endif; ?>
          <?php endif; ?>
          <?php if (isset($row['item_notes'])): ?>
            <div class="item-notes">
              <ul>
                <?php foreach ($row['item_notes'] as $item_note): ?>
                  <li><?=$this->escapeHtml($item_note) ?></li>
                <?php endforeach; ?>
              </ul>
            </div>
          <?php endif; ?>
        <?php endif; ?>
        <?php /* Embed item structured data: library, barcode, call number */ ?>
        <?php if ($row['location']): ?>
          <meta property="seller" content="<?=$this->escapeHtmlAttr($row['location'])?>" />
        <?php endif; ?>
        <?php if ($row['barcode']): ?>
          <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($row['barcode'])?>" />
        <?php endif; ?>
        <?php if ($row['callnumber']): ?>
          <meta property="sku" content="<?=$this->escapeHtmlAttr($row['callnumber'])?>" />
        <?php endif; ?>
        <?php /* Declare that the item is to be borrowed, not for sale */ ?>
          <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
          <link property="itemOffered" href="#record" />
        <?php if (isset($row['availabilityInfo'])): ?>
          <div class="copy-available">
            <?php if (!empty($row['availabilityInfo']['ordered'])): ?>
              <div class="ordered">
                <?=$this->translate('status_Ordered')?>: <?=$row['availabilityInfo']['ordered']?>
              </div>
            <?php endif; ?>
            <?php if (!empty($row['availabilityInfo']['available'])): ?>
              <div class="available"><?=$this->translate('Available items')?>: <?=$row['availabilityInfo']['available']?> / <?=$row['availabilityInfo']['total']?></div>
            <?php endif; ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endforeach; ?>
  <?php if (!empty($holding['purchase_history'])): ?>
    <div class="ils-purchase-history">
      <div class="title"><?=$this->transEsc("Most Recent Received Issues")?>:</div>
      <div class="history">
        <?php foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <?php endforeach; ?>
      </div>
    </div>
  <?php endif; ?>
  <div class="clearfix"></div>
<?php endforeach; ?>
<?php if (empty($holdings['holdings'])): ?>
  <div>
    <h5><?=$this->transEsc('No Holdings Available'); ?></h5>
  </div>
<?php endif; ?>
</div>

<?php if ($paginator = $this->tab->getPaginator($holdings['total'], $holdings['page'], $holdings['itemLimit'])): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
<table class="table record-holdings-table">
  <tr>
    <th class="headers"><span class="holdings-title"><?=$this->transEsc("Most Recent Received Issues")?></span></th>
  </tr>
  <?php foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <?php endforeach; ?>
</table>
<?php endif; ?>

<?php
  $this->inlineScript(
    \Zend\View\Helper\HeadScript::SCRIPT,
    'finna.record.setupHoldingsTab();',
    'SET'
  );
  echo $this->inlineScript();
?>
<!-- END of: finna - RecordTab/holdingsils.phtml -->
