<!-- START of: finna - RecordTab/holdings-details.phtml -->
<?php if (isset($holding['items'][0]['detailsGroupKey'])): ?>
  <div class="holdings-details-ajax <?=$this->escapeHtmlAttr($this->mode)?> hidden"></div>
<?php endif; ?>
<?php if (isset($holding['textfields'])): ?>
  <?php foreach ($holding['textfields'] as $textFieldName => $textFields): ?>
    <?php
    // For purchase history, check if there's something for this holding
    if ($textFieldName == 'purchase_history') {
        $found = false;
        // Account for grouping with item location etc. also
        list($hId) = explode('|', $holdingId, 2);
        foreach ($textFields as $current) {
            if ($current['holdings_id'] == $hId) {
                $found[] = $current['issue'];
            }
        }
        if (!$found) {
            continue;
        }
        $textFields = $found;
    }
    ?>
  <div class="copy-details <?=isset($heading) ? 'group-heading' : "$mode"?>">
    <?php // Translation for summary is a special case for backwards-compatibility and purchase_history a special case ?>
    <?php
    if ($textFieldName == 'summary') {
        $title = 'Volume Holdings';
    } elseif ($textFieldName == 'purchase_history') {
        $title = 'Most Recent Received Issues';
    } else {
        $title = ucfirst($textFieldName);
    }
    ?>
    <?php if (isset($mode)): ?>
      <div class="details-title"><?=$this->transEsc($title)?>:</div>
    <?php endif;?>
    <div <?= !isset($heading) ? ' class="details-info"' : ''?>>
    <?php foreach ($textFields as $current): ?>
      <?=$this->linkify($this->escapeHtml($current))?><br/>
    <?php endforeach; ?>
    </div>
  </div>
  <?php endforeach; ?>
<?php endif; ?>
<!-- END of: finna - RecordTab/holdings-details.phtml -->
