<!-- START of: finna - RecordTab/holdingsils.phtml -->
<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->getUserObject();
    $offlineMode = $this->ils()->getOfflineMode();
    $recordSource = $this->driver->tryMethod('getDataSource');
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0,
        ];
        $offlineMode = 'ils-offline';
    }
    $holdsAllowed = $this->driver->tryMethod('getHoldsAllowed');
    if (!isset($holdings['holdings'])) {
        $holdings['holdings'] = [];
        $holdings['total'] = 0;
        $holdings['page'] = 1;
        $holdings['itemLimit'] = 10;
    }

    $illRequestLink = false;
    $holdLinks = $journal = $summary = false;

    // Use location-specific hold links only if we have branches
    $first = reset($holdings['holdings']);
    $branchesActive = isset($first['items'][0]['branch']);

    $summary = [];
    if (!empty($holdings['holdings'])) {
      $location = reset($holdings['holdings']);
      $item = $location['items'][0];
      $journal = isset($item['journalInfo']);

      $last = array_pop($holdings['holdings']);
      if (isset($last['items']) && is_array($last['items'])) {
          $summary = $last['items'][0];
          if (($summary['location'] ?? '') !== '__HOLDINGSSUMMARYLOCATION__') {
             $summary = [];
          }
      }
      if (!$summary) {
         $holdings['holdings'][] = $last;
      }
    }

    if (!isset($holdings['total'])) {
      $holdings['total'] = count($holdings['holdings']);
    }
    if (!isset($holdings['page'])) {
      $holdings['page'] = 1;
    }
    if (!isset($holdings['itemLimit'])) {
      $holdings['itemLimit'] = $holdings['total'];
    }

    $disableTitleHold = empty($holdings['holdings']) || (isset($summary['holdable']) && !$summary['holdable']);
    $showSummary = $summary && !$journal && $this->holdings()->showRecordPageSummary();
    $itemsTotal = $summary['total'] ?? null;
    $availableTotal = $summary['available'] ?? null;
    $reservationsTotal = $summary['reservations'] ?? null;
    $orderedTotal = $summary['ordered'] ?? null;

    foreach ($holdings['holdings'] as $holding) {
       foreach ($holding['items'] as $row) {
          if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']) {
             $illRequestLink = $row['ILLRequestLink'];
          }
          if (isset($row['link']) && $row['link']) {
             $holdLinks = true;
             if ($branchesActive && (!$journal || !empty($row['item_id']))) {
                $holdLinksLocation[$row['location']] = $row['link'];
             }
          }
       }
    }
    $ilsLoginAvailable = $this->ils()->loginAvailable();
    $externalInterfaceUrl = $summary ? ($summary['externalInterfaceUrl'] ?? '') : '';
    try {
      $holdingsConfig = $this->ils()->getConfig('Holdings', [$this->driver->getUniqueId()]);
    } catch (\Exception $e) {
      $holdingsConfig = [];
    }
    if (isset($holdingsConfig['display_title_hold_in_holdings']) && !$holdingsConfig['display_title_hold_in_holdings']) {
      $disableTitleHold = true;
    }
    $repositoryLibraryRequestAllowed = $this->record($this->driver)->repositoryLibraryRequestEnabled('holdings');
?>

<?=($offlineMode == 'ils-offline') ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if ($this->driver && $recordSource && $externalInterfaceUrl):?>
  <?=$this->record($driver)->renderTemplate('external-interface-link.phtml', ['driver' => $driver, 'source' => $recordSource, 'link' => $externalInterfaceUrl ?? ''])?>
<?php endif;?>

<?php if ($holdsAllowed && !$disableTitleHold && (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver')): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline' && $ilsLoginAvailable): ?>
    <?php if (!$user): ?>
      <?php if (!$repositoryLibraryRequestAllowed): ?>
        <div class="float-end">
          <a href="<?=$this->serverUrl($this->url('myresearch-completelogin', [], ['query' => ['target' => $recordSource ?? '']]))?>" class="btn btn-primary login-link" data-lightbox><?=$this->transEsc('title_hold_login')?></a>
        </div>
        <div class="clearfix"></div>
      <?php endif; ?>
    <?php elseif (!$user->getCatUsername()): ?>
      <div class="alert alert-info">
        <?php
          // Add a data-lightbox attribute to the link in the translation; we do this here to keep
          // the HTML in the language files as simple/generic/future-proof as possible.
          $catalogLoginUrl = $this->recordLinker()
            ->getTabUrl($this->driver, 'Holdings', ['catalogLogin' => 'true']);
          $tokens = ['%%url%%' => $this->escapeHtmlAttr($catalogLoginUrl)];
          echo str_replace('<a ', '<a data-lightbox ', $this->translate('hold_profile_html', $tokens));
        ?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>

<?= $this->render('RecordTab/holdings-record-urls'); ?>

<?php if ($holdsAllowed || $repositoryLibraryRequestAllowed): ?>
  <div class="place-hold-wrapper text-right hidden-print">
    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $user, 'label' => 'Library Card']); ?>
    <?php if ($illRequestLink): ?>
      <a class="expandedCheckILLRequest placeILLRequest btn btn-primary hidden-print" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($illRequestLink))?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('ill_request_place_text') . ': ' . $this->driver->getTitle()) ?>"><?=$this->transEsc('ill_request_check_text')?></a>
    <?php endif; ?>
    <?php if ($holdsAllowed && !$disableTitleHold): ?>
      <?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold');
      if (!empty($holdingTitleHold)): ?>
        <a class="placehold btn btn-primary hidden-print" data-lightbox data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('title_hold_place') . ': ' . $this->driver->getTitle()) ?>" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holdingTitleHold))?>"> <?=$this->transEsc('title_hold_place')?></a>
      <?php elseif ($user): ?>
        <?php
          $blocks = [];
          if (!empty($holdings['blocks'])) {
            $blocks = $holdings['blocks'];
            // Check if we have hold-specific blocks. Add the general hold_error_blocked only if no other hold blocks to avoid repetition.
            $holdBlocks = false;
            foreach ($blocks as $block) {
              if (mb_substr((string)$block, 0, 11, 'UTF-8') === 'hold_error_') {
                $holdBlocks = true;
              }
            }
            if (!$holdBlocks) {
                $blocks[] = 'hold_error_blocked';
            }
          } elseif (!$illRequestLink && !$holdLinks && !$repositoryLibraryRequestAllowed) {
            $blocks[] = 'title_cant_place_hold';
          }
          if ($blocks):
        ?>
          <?=$this->partial('myresearch/borrowing-block.phtml', ['blocks' => $blocks]) ?>
        <?php endif; ?>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($repositoryLibraryRequestAllowed): ?>
      <?php if ($user): ?>
        <?php if ($this->libraryCards()->getCardsForUser($user)): ?>
          <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'RepositoryLibraryRequest'))?>" data-lightbox class="btn btn-primary repository-library-request-order"><?=$this->transEsc('repository_library_request_order')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
        <?php else: ?>
          <a href="<?=$this->url('editLibraryCard', ['id' => 'NEW'])?>" class="btn btn-primary login-link hidden-print"><?=$this->transEsc('repository_library_request_add_library_card')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
        <?php endif; ?>
      <?php else: ?>
        <a href="?login=true&catalogLogin=true" class="btn btn-primary login-link hidden-print" data-lightbox><?=$this->transEsc('repository_library_request_login')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
      <?php endif; ?>
    <?php endif; ?>
  </div>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=
    $this->context($this)->renderInContext(
        'RecordTab/holdingsils/electronic.phtml',
        ['holdings' => $holdings['electronic_holdings']]
    )
  ?>
<?php endif; ?>

<div class="record-holdings-table">
  <div class="headers">
    <?php $mergedData = $this->driver->tryMethod('getMergedRecordData'); ?>
    <?php $recordSourceId = $this->driver->getSourceIdentifier(); ?>
    <div class="dedup-information">
      <span class="holdings-title"><?=$this->transEsc("source_$recordSource", null, $recordSource) ?></span>
      <?php if ($mergedData && count($mergedData['records']) > 1): ?>
        <select class="dedup-select form-select jumpMenuUrl hidden-print" role="listbox" aria-haspopup="true" title="<?=$this->transEsc('select_dedup_organisation');?>">
          <option value="#" role="option" selected="selected"><?=$this->transEsc('Other Libraries'); ?></option>
          <?php foreach ($mergedData['records'] as $current): ?>
            <?php if ($recordSource != $current['source']): ?>
              <option value="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($recordSourceId . '|' . $current['id'])) ?>" role="option"><?=$this->transEsc("source_{$current['source']}", null, $current['source']) ?></option>
            <?php endif; ?>
          <?php endforeach; ?>
        </select>
      <?php endif; ?>
    </div>
    <?php if (!empty($holdings['holdings'])): ?>
      <div class="totals-container">
        <?php if ($showSummary): ?>
          <?php if ($reservationsTotal): ?>
            <span class="reservations"><?=$this->translate('status_requests_html', ['%%count%%' => $reservationsTotal]);?></span>
          <?php endif; ?>
          <?php if (null !== $itemsTotal): ?>
            <span class="total">
              <?php $translationKey = ($itemsTotal && null !== $availableTotal) ? 'status_available_items_total_html' : 'status_items_total_html'; ?>
              <?=$this->translate($translationKey, ['%%count%%' => $itemsTotal, '%%available%%' => $availableTotal ?? '-']);?>
            </span>
          <?php endif; ?>
          <?php if ($orderedTotal): ?>
            <span class="ordered"><?=$this->translate('status_items_ordered_html', ['%%count%%' => $orderedTotal]);?></span>
          <?php endif; ?>
        <?php endif; ?>
      </div>
      <div class="shelf-location text-right">
        <?=$this->transEsc('shelf_location'); ?>
      </div>
    <?php endif; ?>
  </div>

<?php if ($containerLinksHtml = trim($this->record($this->driver)->renderTemplate('container-links.phtml'))): ?>
  <div class="holdings-group">
    <div class="copy-details">
      <?=$containerLinksHtml?>
    </div>
  </div>
<?php endif; ?>

<?php $holdingsGroup = 0; ?>
<?php foreach ($holdings['holdings'] as $holdingId => $holding): ?>
  <?php
    ++$holdingsGroup;

    $available = 0;
    $uncertain = false;
    $firstDueDate = '';
    $firstDueStr = '';
    $statuses = [];
    $requests = 0;
    foreach ($holding['items'] as $row) {
      if ($row['availability']->is(\VuFind\ILS\Logic\AvailabilityStatusInterface::STATUS_AVAILABLE)) {
        $available += $row['availabilityInfo']['available'] ?? 1;
      } elseif ($row['availability']->is(\VuFind\ILS\Logic\AvailabilityStatusInterface::STATUS_UNCERTAIN)) {
        $uncertain = true;
      }
      if (!empty($row['duedate']) && empty($row['ignoreDueDate'])) {
        $date = strtotime($row['duedate']);
        if ((!$firstDueDate || abs(time() - $date) < abs(time() - $firstDueDate))) {
          $firstDueDate = $date;
          $firstDueStr = $row['duedate'];
        }
      }
      $statusDesc = $row['availability']->getStatusDescription();
      $statusDescriptionTokens = $row['availability']->getStatusDescriptionTokens();
      $statuses[$this->translate("status_$statusDesc", $statusDescriptionTokens, $this->translate($statusDesc, $statusDescriptionTokens))] = 1;
      if (!isset($row['branch'])) {
        if (isset($row['requests_placed']) && $row['requests_placed'] > $requests) {
          $requests = $row['requests_placed'];
        }
      }
    }
    if ($available) {
      $holdingSummary = '<span class="status-available">' . $this->icon('status-available') . ' ' . $this->translate('status_items_available_html', ['%%count%%' => $available]) . '</span>';
    } elseif ($firstDueStr) {
      $holdingSummary = '<span class="status-unavailable">' . $this->icon('status-unavailable') . ' ' . $this->transEsc('closest_due_date', ['%%date%%' => $firstDueStr]) . '</span>';
    } elseif ($statuses) {
      if (count($statuses) === 1) {
        if ($uncertain) {
          $holdingSummary = '<span class="status-uncertain">' . $this->icon('status-unknown') . ' ' . $this->escapeHtml(implode(' ', array_flip($statuses))) . '</span>';
        } else {
          $holdingSummary = '<span class="status-unavailable"> ' . implode('<br>', array_map([$this, 'escapeHtml'], array_keys($statuses))) . '</span>';
        }
      } else {
        // Don't try to show multiple statuses, it causes confusion!
        $holdingSummary = '';
      }
    } else {
      $holdingSummary = '<span class="status-available">' . $this->icon('status-available') . ' ' . $this->transEsc('Available') . '</span>';
    }

    $additionalSummary = [];
    if ($requests) {
      $additionalSummary[] = $this->translate('status_requests_html', ['%%count%%' => $requests]);
    }
    foreach ($additionalSummary as $i => $summaryItem) {
      $holdingSummary .= '<span class="small"> &ndash;&nbsp;' . $summaryItem . '</span>';
    }

    // N.B. $holdingsDetails also affects request checks in finna-record
    $holdingsDetails = $holdingsGroup == 1 ? 'expanded' : 'collapsed';
    $detailsModes = array_map('trim', explode(',', $this->holdings()->getDetailsMode()));
    foreach ($detailsModes as $mode) {
      switch ($mode) {
      case 'collapse':
        $holdingsDetails = 'collapsed';
        break;
      case 'expand-all':
        $holdingsDetails = 'expanded';
        break;
      case 'collapse-journals':
        if ($journal || in_array('0/Journal/', $this->driver->getFormats())) {
            $holdingsDetails = 'collapsed';
        }
        break;
      }
    }

    $callnumbers = $this->holdings()->getGroupedCallNumbers($holding['items']);
    $dialogTitle = ': ' . $this->driver->getTitle();
    $titleLocation = $this->transEscWithPrefix('location_', $holding['location']);
    if ($titleLocation) {
        $dialogTitle .= " - $titleLocation";
    }
  ?>
  <div class="holdings-group">
    <?php if ($holdingsGroup == 1 && $holdingsConfig): ?>
      <?php if (!empty($holdingsConfig['extra_texts'])): ?>
        <div class="holdings-container-heading">
          <div>
            <?php foreach ($holdingsConfig['extra_texts'] as $extraText): ?>
              <div class="holdings-extra-text"><?=$this->translate($extraText, ['%%recordId%%' => $this->driver->getUniqueId()])?></div>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endif; ?>
    <?php endif; ?>
    <div class="holdings-container-heading <?=$holdingsDetails == 'collapsed' ? '' : 'open'?>" tabindex="0" role="button" aria-expanded="<?=$holdingsDetails == 'collapsed' ? 'false' : 'true'?>">
      <div class="location">
        <?=$this->icon('holdings-expand', 'expand') ?><?=$this->icon('holdings-collapse', 'collapse') ?>
        <?php $locationText = $this->transEscWithPrefix('location_', $holding['location']); ?>
        <?php if (($holding['locationhref'] ?? false) && !$this->driver->tryMethod('urlBlocked', [$holding['locationhref'], $locationText])): ?>
          <a href="<?=$holding['locationhref']?>" target="_blank"><?=$locationText?></a>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
        <?php if ($this->holdings()->showDetailsAfterLocationGroup()): ?>
          <div class="details"><?=$this->partial('RecordTab/holdings-details.phtml', ['holdingId' => $holdingId, 'holding' => $holding, 'heading' => true]);?></div>
        <?php endif; ?>
      </div>
      <div class="holdings-details"><?=$holdingSummary ?></div>
      <div class="location-link text-right">
        <?php foreach ($callnumbers as $data): ?>
          <?=$this->callnumber()->callnumber($recordSource, $this->driver->getFullTitle(), $data['callnumber'], $data['collection'], $data['location'], $this->layout()->userLang, 'record', $data, !$branchesActive)?>
        <?php endforeach; ?>
        <?php if ($holdsAllowed && isset($holdLinksLocation[$holding['location']])): ?>
          <a class="expandedCheckRequest inlineblock placehold btn btn-primary hidden-print" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holdLinksLocation[$holding['location']]))?>" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('request_place_text') . $dialogTitle); ?>"><?=$this->transEsc('request_place_text')?></a>
        <?php endif; ?>
      </div>
    </div>
    <div class="clearfix"></div>
    <?php if (isset($holding['items'][0]['detailsGroupKey'])): ?>
      <div class="<?=$this->escapeHtmlAttr($holdingsDetails)?>GetDetails <?=$this->escapeHtmlAttr($holdingsDetails)?> copy-details hidden" data-key="<?=$this->escapeHtmlAttr($holding['items'][0]['detailsGroupKey'])?>" data-record-id="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" data-record-source="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>">
        <?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?>
      </div>
    <?php endif; ?>
    <?php if (!$this->holdings()->showDetailsAfterLocationGroup()): ?>
      <?=$this->partial('RecordTab/holdings-details.phtml', ['holdingId' => $holdingId, 'holding' => $holding, 'mode' => $holdingsDetails]);?>
    <?php endif; ?>
    <?php if (isset($holding['items'][0]['detailsGroupKey'])): ?>
      <div class="holdings-items-ajax <?=$this->escapeHtmlAttr($holdingsDetails)?> hidden"></div>
    <?php endif; ?>
    <?php if (empty($holding['items'][0]['skipItemsList'])): ?>
      <?=$this->render('RecordTab/holdings-items.phtml', ['holding' => $holding, 'driver' => $driver, 'mode' => $holdingsDetails, 'holdsAllowed' => $holdsAllowed])?>
    <?php endif; ?>
    <?php if (!empty($holding['purchase_history'])): ?>
      <div class="ils-purchase-history <?=$holdingsDetails?>">
        <div class="title"><?=$this->transEsc('Most Recent Received Issues')?>:</div>
        <div class="history">
          <?php foreach ($holding['purchase_history'] as $current): ?>
            <?=$this->escapeHtml($current['issue'])?><br>
          <?php endforeach; ?>
        </div>
        <div class="clearfix"></div>
      </div>
    <?php endif; ?>
    <div class="clearfix"></div>
  </div>
<?php endforeach; ?>
<?php if (empty($holdings['holdings'])): ?>
  <div>
    <h5><?=$this->transEsc('No Holdings Available'); ?></h5>
  </div>
<?php endif; ?>
</div>

<?php // $holdings['total'] may be off due to summary and grouped holdings, so use count for paginator: ?>
<?php if (!isset($holding['items'][0]['detailsGroupKey']) && ($paginator = $this->tab->getPaginator(count($holdings['holdings']), $holdings['page'], $holdings['itemLimit']))): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>

<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
<table class="table record-holdings-table">
  <tr>
    <th class="headers"><span class="holdings-title"><?=$this->transEsc('Most Recent Received Issues')?></span></th>
  </tr>
  <?php foreach ($history as $row): ?>
    <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
  <?php endforeach; ?>
</table>
<?php endif; ?>

<?php
  echo $this->assetManager()->outputInlineScriptString('finna.record.setupHoldingsTab();');
?>
<!-- END of: finna - RecordTab/holdingsils.phtml -->
