<?php
$locations = $this->driver->getLocations();
?>

<?php if ($links = $this->driver->getURLS()): ?>
    <div class="table record-locationsead3-links">
        <div class="headers">
            <p class="holdings-title">Linkit</p>
        </div>
        <div class="links-container">
            <?php foreach ($links as $link): ?>
                <div class="copy-details">
                    <span class="branch"><a href="<?=$this->escapeHtmlAttr($link['url'])?>"><i class="fa fa-external-link" aria-hidden="true"></i> <?=$link['desc']?></a></span>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php endif; ?>

<div class="table record-locationsead3-table">
  <div class="headers"><p class="holdings-title">Säilyttävät toimipisteet</p></div>

  <?php foreach ($locations as $branch => $branchData): ?>
      <div class="holdings-container-heading">
          <div class="location">
              <i class="fa fa-arrow-down" aria-hidden="true"></i> <?=$this->escapeHtml($branch)?></div>
              <div class="holdings-details">Aineistotunnus</div>
              <div class="location-link text-right">
                  <?php if (!empty($branchData['providesService'])): ?>
                      <div class="location-link-text"><?= $this->transEsc($branchData['providesService'] === true ? 'Tarjoaa tietopalvelua' : $branchData['providesService'])?></div>
                  <?php endif; ?>
              </div>
      </div>
      <div class="clearfix collapsed"></div>
      <?php foreach ($branchData['items'] as $item): ?>
          <div vocab="http://schema.org/" typeof="Offer" class="copy-details">
              <div class="copy-title">
                  <span class="branch"><?=$this->transEsc($item['label'])?>
              </div>
              <div class="copy-info">
                  <span><?=$this->transEsc($item['id'])?></span>
                  <div class="pull-right">
                  </div>
              </div>
          </div>
      <?php endforeach; ?>
  <?php endforeach; ?>
</div>

<?php
  $this->inlineScript(
    \Zend\View\Helper\HeadScript::SCRIPT,
    'finna.record.setupLocationsEad3Tab();',
    'SET'
  );
  echo $this->inlineScript();
?>
