<!-- START of: finna - RecordTab/staffviewarray.phtml -->
<?php $rawFieldData = $this->driver->getRawData(); ?>
<?php if (!empty($rawFieldData['fullrecord']) && is_string($rawFieldData['fullrecord']) && strncmp($rawFieldData['fullrecord'], '<', 1) == 0): ?>
  <?php
    $recordClass = get_class($this->driver);
    if ($p = strrpos($recordClass, '\\')) {
      $recordClass = substr($recordClass, $p + 1);
    }
    if ('Primo' === $recordClass) {
      $format = 'Primo';
    } elseif ('Eds' === $recordClass) {
      $format = 'EDS';
    } else {
        $format = mb_strtoupper($this->driver->tryMethod('getRecordFormat'), 'UTF-8');
    }
  ?>
  <h2><?=$this->transEsc('Metadata')?> (<?=$this->escapeHtml($format)?>)</h2>
  <?php
    $dom = new DOMDocument('1.0');
    $dom->preserveWhiteSpace = false;
    $dom->formatOutput = true;
    if ($dom->loadXML($rawFieldData['fullrecord'])) {
      echo '<pre id="record-data" data-double-click-select-all>' . $this->escapeHtml($dom->saveXML()) . '</pre>';
      $script = <<<JS
            $(document).ready(function() {
              const recordData = document.getElementById('record-data');
              if (recordData) {
                finna.scriptLoader.load(
                  {'vendor-highlight': 'vendor/highlight.pack.js'},
                  () => {
                    hljs.highlightBlock(recordData);
                  }
                );
              }
            });
          JS;
      echo $this->assetManager()->outputInlineScriptString($script);
    } else {
      echo '<pre id="record-data" data-double-click-select-all>' . $this->escapeHtml($rawFieldData['fullrecord']) . '</pre>';
    }
  ?>
<h2><?=$this->transEsc('staff_view_finna_index')?></h2>
<?php endif; ?>
<table class="staff-view table table-striped">
  <?php $rawData = $this->driver->getRawData();
  ksort($rawData);
  foreach ($rawData as $field => $values): ?>
    <tr>
      <th scope="row"><?=$this->escapeHtml($field)?></th>
      <td><?=$this->printArrayHtml($values)?></td>
    </tr>
  <?php endforeach; ?>
</table>
<!-- END of: finna - RecordTab/staffviewarray.phtml -->
