<!-- START of: finna - RecordTab/versions.phtml -->
<?php
  $results = $this->driver->tryMethod('getVersions', [false, 20]);
  $view = 'list';
  $this->render(
      'search/results-scripts.phtml',
      [
          'displayVersions' => true,
          'jsResults' => false,
      ]
  );
?>
<div class="results result-view-<?=$this->escapeHtmlAttr($view)?>">
  <nav class="search-header hidden-print">
    <div class="search-stats">
      <?=
        $this->translate(
            'showing_results_of_html',
            [
                '%%start%%' => 1,
                '%%end%%' => count($results),
                '%%total%%' => $this->localizedNumber($results->getTotal()),
            ]
        )
      ?>
    </div>
    <div class="search-controls">
      <a class="more-link" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getVersionsSearchUrl($this->driver))?>" rel="nofollow">
        <?=$this->icon('full-results-link') ?> <?=$this->transEsc('other_versions_search_link_tab', ['%%count%%' => $results->getTotal() + 1])?>
      </a>
    </div>
  </nav>
  <?php $recordNumber = $results->getOffset(); ?>
  <?php foreach ($results as $current): ?>
    <div id="result<?=++$recordNumber ?>" class="result clearfix <?=$this->record($this->driver)->getContainerJsClasses()?>">
      <span class="visually-hidden"><?=$this->transEsc('Search Result');?> <?=$recordNumber ?></span>
      <?=$this->record($current)->getSearchResult($view)?>
    </div>
  <?php endforeach; ?>
  <div class="search-tools hidden-print">
    <div class="search-controls">
      <a class="more-link" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getVersionsSearchUrl($this->driver))?>" rel="nofollow">
        <?=$this->icon('full-results-link') ?> <?=$this->transEsc('other_versions_search_link_tab', ['%%count%%' => $results->getTotal() + 1])?>
      </a>
    </div>
  </div>
</div>

<?php
// Add any translations added when processing the search results:
$translations = $this->jsTranslations()->getJSON();
$script = <<<JS
    VuFind.addTranslations($translations);
    finna.common.initResultScripts('.results');
    JS;
?>
<?=$this->assetManager()->outputInlineScriptString($script); ?>
<!-- END of: finna - RecordTab/versions.phtml -->
