<!-- START of: finna - browse/home.phtml -->
<?php
  $this->layout()->finnaMainHeader = $this->component('page-title', ['title' => $this->translate('Browse the Catalog'), 'level' => 1, 'class' => 'h3']);
  $this->breadcrumbs()->set($this->translate('Browse'), $this->url('browse-home'));

  $BROWSE_BASE = $this->url('browse-' . strtolower($this->currentAction));
  $SEARCH_BASE = $this->url($this->currentAction == 'Tag' ? 'tag-home' : 'search-results');
?>

<?php if (!isset($this->currentAction)): ?>
  <h2><?=$this->transEsc('Choose a Category to Begin Browsing') ?>:</h2>
<?php endif; ?>

<div class="page-content">
  <div class="browse list-group<?php if (!empty($this->categoryList)): ?> hidden-xs<?php endif ?>" id="list1">
    <?php foreach ($this->browseOptions as $item => $currentOption): ?>
      <a href="<?=$this->url('browse-' . strtolower($currentOption['action'])); ?>" class="list-group-item<?php if ($currentOption['action'] == $this->currentAction): ?> active<?php endif; ?>">
        <?=$this->transEsc($currentOption['description']) ?>
        <?php if ($currentOption['action'] == $this->currentAction): ?><?=$this->icon('browse-selected') ?><?php else: ?><?=$this->icon('browse-unselected') ?><?php endif; ?>
      </a>
    <?php endforeach; ?>
  </div>

  <?php if (!empty($this->categoryList)): ?>
    <div class="browse list-group<?php if (!empty($this->secondaryList) || !empty($this->resultList)): ?> hidden-xs<?php endif ?>" id="list2">
      <?php foreach ($this->categoryList as $findby => $category): ?>
        <a href="<?=$BROWSE_BASE ?>?findby=<?=urlencode($findby) ?>&amp;query_field=<?=$this->browse()->getSolrField($findby, $this->currentAction) ?>" class="list-group-item clearfix<?php if ($this->findby == $findby): ?> active<?php endif; ?>">
          <?php if (is_string($category)): ?>
            <?=$this->transEsc($category)?>
            <?php if ($this->findby == $findby): ?><?=$this->icon('browse-selected') ?><?php else: ?><?=$this->icon('browse-unselected') ?><?php endif; ?>
          <?php else: ?>
            <?=$this->transEsc($category['text'])?>
            <span class="badge"><?=$this->localizedNumber($category['count'])?></span>
          <?php endif; ?>
        </a>
      <?php endforeach; ?>
    </div>
  <?php endif; ?>

  <?php if (!empty($this->secondaryList)): ?>
    <div class="browse list-group<?php if (!empty($this->resultList)): ?> hidden-xs<?php endif ?>" id="list3">
    <?php foreach ($this->secondaryList as $secondary): ?>
      <?php
        $url = $BROWSE_BASE . '?findby=' . urlencode($this->findby)
          . '&amp;query=' . urlencode($secondary['value']);
        if (isset($this->category)) {
          $url .= '&amp;category=' . urlencode($this->category);
        }
        if ($this->facetPrefix) {
          $url .= '&amp;facet_prefix=' . urlencode($secondary['displayText']);
        }
        if ($this->secondaryParams) {
          foreach ($this->secondaryParams as $var => $val) {
            $url .= '&amp;' . $var . '=' . urlencode($val);
          }
        }
        $viewRecord = !empty($this->categoryList) && $this->currentAction != 'Tag' && $this->findby != 'alphabetical';
      ?>
      <?php if ($this->findby != 'alphabetical'):?> <div class="widen"><?php endif; ?>
      <a href="<?=$url ?>" class="list-group-item clearfix<?php if ($this->query == $secondary['value'] . '' || $this->query == $secondary['value'] . '*'): ?> active<?php endif; ?>">
        <?=$this->escapeHtml($secondary['displayText']) ?>
        <?php if ($this->findby != 'alphabetical' && isset($secondary['count'])): ?>
          <span> (<?=$this->localizedNumber($secondary['count']) ?>)</span>
        <?php endif; ?>
      </a>
      <?php if ($viewRecord): ?>
        <a class="list-group-item view-record float-end" href="<?=$SEARCH_BASE ?>?lookfor=<?php if ($this->filter): ?>&amp;filter[]=<?=urlencode($this->filter) ?>%3A<?=str_replace('+AND+', '&filter[]=', urlencode($secondary['value'])) ?><?php endif; ?>&amp;filter[]=<?=$this->browse()->getSolrField($this->currentAction) ?>%3A[* TO *]<?php if ($this->dewey_flag):?>&amp;sort=dewey-sort<?php endif;?>"><?=$this->transEsc('View Records') ?></a>
      <?php endif; ?>
       <?php if ($this->findby != 'alphabetical'):?> </div><?php endif; ?>
    <?php endforeach; ?>
    </div>
  <?php endif; ?>

  <?php if (!empty($this->resultList)): ?>
    <div class="browse list-group" id="list4">
    <?php foreach ($this->resultList as $result): ?>
        <a class="list-group-item clearfix" href="<?=$SEARCH_BASE ?>?<?=$this->paramTitle ?><?=urlencode($result['value']) ?><?php if ($this->searchParams): foreach ($this->searchParams as $var => $val): ?>&amp;<?=$var ?>=<?=urlencode($val) ?><?php endforeach;endif; ?>">
          <?=$this->escapeHtml($result['displayText'])?>
          <span> (<?=$this->localizedNumber($result['count']) ?>)</span>
        </a>
    <?php endforeach; ?>
    </div>
  <?php elseif (isset($this->query)): ?>
    <ul class="browse list-group" id="list4">
      <li class="list-group-item"><?=$this->transEsc('nohit_heading') ?></li>
    </ul>
  <?php endif; ?>
</div>
<!-- END of: finna - browse/home.phtml -->
