<?=$this->doctype()?>
<?php
  $globals = $this->globals();
?>
<html lang="<?=$globals['userLang']?>"<?php if ($globals['rtl']): ?> dir="rtl"<?php endif; ?>>
  <head>
    <?php
      $this->setupThemeResources();
      $this->assetManager()->clearScriptList()->clearStyleList()->appendStyleLink('help.css');
    ?>
    <?=$this->headMeta()?>
    <?=$this->headTitle()?>
    <?=$this->assetManager()->outputHeaderAssets()?>
  </head>
  <body>
    <?=$this->layout()->content?>
  </body>
</html>
