<?
    // Set page title.
    $this->headTitle($this->translate('Email Record'));
?>
<div data-role="page" id="Record-view">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <?=$this->flashmessages()?>
    <form method="post" name="emailRecord" data-ajax="false">
      <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" />
      <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" />
      <?=$this->render('Helpers/email-form-fields.phtml')?>
    </form>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
