<?
    // Set page title.
    $this->headTitle($this->translate('Save'));
?>
<div data-role="page" id="Record-view">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <h3><?=$this->transEsc("add_favorite_prefix") ?> <?=$this->escapeHtml($this->driver->getBreadcrumb())?> <?=$this->transEsc("add_favorite_suffix") ?></h3>
    <form method="post" name="saveRecord" data-ajax="false">
      <input type="hidden" name="submit" value="1" />
      <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" />
      <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" />
      <? if (!empty($this->containingLists)): ?>
        <ul data-role="listview" data-dividertheme="e" data-inset="true">
          <li data-role="list-divider"><?=$this->transEsc('This item is already part of the following list/lists') ?>:</li>
          <? foreach ($this->containingLists as $list): ?>
            <li><a rel="external" href="<?=$this->url('userList', array('id' => $list['id'])) ?>"><?=$this->escapeHtml($list['title'])?></a></li>
          <? endforeach; ?>
        </ul>
      <? endif; ?>

      <?/* Only display the list drop-down if the user has lists that do not contain
      this item OR if they have no lists at all and need to create a default list */?>
      <? $showLists = (!empty($this->nonContainingLists) || (empty($this->containingLists) && empty($this->nonContainingLists))); ?>

      <div data-role="fieldcontain">
        <? if ($showLists): ?>
          <label class="displayBlock" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
          <select id="save_list" name="list">
            <? if ($this->nonContainingLists): ?>
              <? foreach ($this->nonContainingLists as $list): ?>
                <option value="<?=$list['id'] ?>"<? if ($list['id']==$this->userList()->lastUsed()): ?> selected="selected"<? endif; ?>><?=$this->escapeHtml($list['title'])?></option>
              <? endforeach; ?>
            <? else: ?>
              <option value=""><?=$this->transEsc('My Favorites') ?></option>
            <? endif; ?>
          </select>
        <? endif; ?>

        <a rel="external" data-role="button" data-rel="dialog" href="<?=$this->url('editList', array('id' => 'NEW')) ?>?recordId=<?=urlencode($this->driver->getUniqueId())?>&amp;recordSource=<?=urlencode($this->driver->getResourceSource())?>" class="listEdit controller<?=$this->record($this->driver)->getController()?>" title="<?=$this->transEsc('Create a List') ?>"><? if ($showLists) echo $this->transEsc('or create a new list'); else echo $this->transEsc('Create a List'); ?></a>

        <? if ($showLists): ?>
          <? if ($this->usertags()->getMode() !== 'disabled'): ?>
            <label class="displayBlock" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
            <input class="mainFocus" id="add_mytags" type="text" name="mytags" value="" size="50"/>
            <p><?=$this->transEsc("add_tag_note") ?></p>
          <? endif; ?>
          <label class="displayBlock" for="add_notes"><?=$this->transEsc('Add a Note') ?></label>
          <textarea id="add_notes" name="notes"></textarea>
          </div><div data-role="fieldcontain">
          <input class="button" type="submit" value="<?=$this->transEsc('Save') ?>"/>
        <? endif; ?>
      </div>
    </form>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
