<?
    // Set page title.
    $this->headTitle($this->translate('Text this'));
?>
<div data-role="page" id="Record-view">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <?=$this->flashmessages()?>
    <form method="post" name="smsRecord" data-ajax="false">
      <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" />
      <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" />
      <div data-role="fieldcontain">
        <label for="sms_to"><?=$this->transEsc('Number')?>:</label>
        <input id="sms_to" type="text" name="to" value="<?=isset($this->to) ? $this->to : ''?>" />
        <? if (is_array($this->carriers) && count($this->carriers) > 1): ?>
          <label for="sms_provider"><?=$this->transEsc('Provider')?>:</label>
          <select id="sms_provider" name="provider" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>">
            <option selected="selected" value=""><?=$this->transEsc('Select your carrier')?></option>
            <? foreach ($this->carriers as $val => $details): ?>
              <option<?=(isset($this->provider) && $val == $this->provider) ? ' selected="selected"' : ''?> value="<?=$this->escapeHtmlAttr($val)?>"><?=$this->escapeHtml($details['name'])?></option>
            <? endforeach; ?>
          </select>
        <? else: ?>
          <? $keys = is_array($this->carriers) ? array_keys($this->carriers) : array(); ?>
          <input type="hidden" name="provider" value="<?=isset($keys[0]) ? $keys[0] : ''?>" />
        <? endif; ?>
      </div>
      <?=$this->recaptcha()->html($this->useRecaptcha) ?>
      <div data-role="fieldcontain">
        <input class="button" type="submit" name="submit" value="<?=$this->transEsc('Send')?>"/>
      </div>
    </form>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
