<?
    // Grab tab contents up front -- this will set the page title, which we need to
    // do before we display the page header below.
    $tab = $this->record($this->driver)->getTab($this->activeTab);
?>
<div data-role="page" id="Record-view">
  <?=$this->mobileMenu()->header(array('searchLink' => $this->searchOptions($this->searchClassId)->getSearchHomeAction()))?>
  <div class="record" data-role="content" data-record-id="<?=$this->escapeHtml($this->driver->getUniqueId())?>">
    <?=$this->flashmessages()?>
    <? if ($this->activeTab == $this->defaultTab): ?>
      <?=$this->record($this->driver)->getCoreMetadata()?>
    <? else: ?>
      <h3><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h3>
    <? endif; ?>
    <?=$tab?>
    <div data-role="controlgroup">
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" data-role="button" rel="external"><?=$this->transEsc("Add to favorites")?></a>
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" data-role="button" rel="external"><?=$this->transEsc("Add Tag")?></a>
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Cite')?>" data-role="button" rel="external"><?=$this->transEsc("Cite this")?></a>
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'Email')?>" data-role="button" rel="external"><?=$this->transEsc("Email this")?></a>
      <a href="<?=$this->recordLink()->getActionUrl($this->driver, 'SMS')?>" data-role="button" rel="external"><?=$this->transEsc("Text this")?></a>
    </div>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
