; This configuration file can be used to set up a secondary Blender, i.e. to
; combine a different set of backends. This instance is accessible under /Blender2
; URLs within VuFind. See also Blender2Mappings.yaml.
;
; All of the settings are copied from Blender.ini. To ease maintenance of
; documentation, comments from that file are not duplicated here. See Blender.ini
; for more details of how all settings work. Look for section marker comments
; within this file to see where groups of settings come from.

[Backends]
;Solr = "Items in Library"
;SolrAuth = "Authors"
;Primo = "CDI"
;EDS = "EDS"

[Blending]
initialResults[] = Solr
initialResults[] = Solr
initialResults[] = SolrAuth
initialResults[] = SolrAuth
initialResults[] = Primo
initialResults[] = EDS
initialResults[] = Primo
initialResults[] = EDS

blockSize = 7

;adaptiveBlockSizes[] = "0-20:3"
;adaptiveBlockSizes[] = "21-10000:5"

; ---------- config.ini settings ----------

[Record]
next_prev_navigation = false

; ---------- searches.ini settings ----------

[General]
default_handler = AllFields
default_sort = "relevance,id asc"
default_view = list
default_limit = 20
;limit_options        = 10,20,40,60,80,100
case_sensitive_bools = true
case_sensitive_ranges = true

default_top_recommend[] = SpellingSuggestions
;default_top_recommend[] = VisualFacets:Visual_Settings
default_side_recommend[] = SideFacets:Results:CheckboxFacets:Blender
;default_noresults_recommend[] = SwitchTab
default_noresults_recommend[] = SwitchType
default_noresults_recommend[] = SwitchQuery:::fuzzy
default_noresults_recommend[] = SpellingSuggestions
default_noresults_recommend[] = RemoveFilters

highlighting = true

;highlighting_fields = *
snippets = true
retain_filters_by_default = true
always_display_reset_filters = false
;default_filters[] = "format:Book"
;default_filters[] = "institution:MyInstitution"
; OR filter:
;default_filters[] = "~format:Book"
;default_filters[] = "~format:Journal"

;display_versions = true

result_limit = 400

load_results_with_js = true

;top_paginator = simple

[Basic_Searches]
AllFields = "All Fields"
Title = Title
Author = Author
Subject = Subject

[Advanced_Searches]
AllFields = adv_search_all
Title = adv_search_title
Author = adv_search_author
Subject = adv_search_subject

[Sorting]
relevance = sort_relevance
year = sort_year
year asc = sort_year_asc

[HiddenSorting]
;pattern[] = .*

; ---------- facets.ini settings ----------

[Results]
;blender_backend    = Source
institution        = Institution
building           = Library
format             = Format
author_facet       = Author
language           = Language
genre_facet        = Genre
era_facet          = Era
geographic_facet   = Region
publish_date       = adv_search_year  ; share year string w/advanced search page
; Authority facets:
occupation         = Occupation
gender             = Gender

[FacetLabels]
labelSections[] = Advanced_Facets
labelSections[] = HomePage_Facets
labelSections[] = ResultsTop
labelSections[] = Results
labelSections[] = ExtraFacetLabels
checkboxSections[] = CheckboxFacets

checkboxSections[] = CheckboxFacets

[SpecialFacets]
dateRange[] = publish_date
;fullDateRange[] = example_field_date
;numericRange[] = example_field_str
;genericRange[] = example_field_str
;hierarchical[] = building
;hierarchical[] = format
hierarchicalFacetSortOptions[building] = top
;hierarchicalFacetDisplayStyles[format] = full
;hierarchicalFacetSeparators[format] = " > "

[CheckboxFacets]
;blender_backend:Solr = "Items in Library"
;blender_backend:SolrAuth = "Authors"
;blender_backend:Primo = "Electronic Material (Ex Libris CDI)"
;blender_backend:EDS = "Electronic Material (EBSCO EDS)"
peer_reviewed:1 = peer_reviewed
fulltext:1 = online_resources

[Results_Settings]
showMore[*] = 6
;showMore['format'] = 10

top_rows = 2
exclude = blender_backend
;orFacets = *
;collapsedFacets = *

;multiFacetsSelection = unchecked

[Advanced_Settings]
delimiter = "{{{_:::_}}}"

special_facets   = "daterange"

translated_facets[] = blender_backend
translated_facets[] = format
translated_facets[] = language

;delimited_facets[] = author_id_str
;delimited_facets[] = "author_id_str|:::"
delimited_facets[] = "blender_backend|{{{_:::_}}}"

[Facet_publish_date]
;slider_min_value = "1400"

;slider_max_value = "+1 year"
