; If you want to add fields that are not included in the driver's getItems method
; you can copy RecordDataFormatter.ini into this file and adapt the settings for EDS.

; To add filters as in [ItemGlobalFilter] of EDS.ini for single contexts (e.g. core, result-list)
; a section [<context>_ItemFilter] can be used.
[core_ItemFilter]
;excludeLabel[] = 'Availability'
;includeLabel[] = 'Availability'
;excludeGroup[] = 'URL'
;includeGroup[] = 'URL'

[result-list_ItemFilter]
;excludeLabel[] = 'Availability'
;includeLabel[] = 'Availability'
;excludeGroup[] = 'URL'
;includeGroup[] = 'URL'

; This section is used to set global default options for items.
[GlobalItemDefaultOptions]
; If a search link should set on the elements of items (default is false)
;useSearchLink = true
; Element limit for each item (default is no limit)
;limit = 3
; Abbreviation that is displayed after the elements if the limit is exceeded (default is '...')
;abbreviation = " etc."
; Prefix for elements of items (default is '')
;itemPrefix = "<span class="myItem">"
; Suffix for elements of items (default is '')
;itemSuffix = "</span>"
; Separator displayed between the elements of items (default is ', ')
;separator = "; "

; With [<context>_ItemDefaultOptions] the default options can be changed only for the context (e.g. core, result-list).
; To limit all items to three elements in the results list for example use
;[result-list_ItemDefaultOptions]
;limit = 3

; To change the options for single items you have to add a section with those options and
; add the section to either global[] or <context>[].
; The following comes from the default configuration of the [AuthorDisplay] section in EDS.ini that was added
; in VuFind Version 10.1 and replaced by this in 11.0
[ItemOptions]
;global[] =
core[] = 'core_Authors'
result-list[] = 'result-list_Authors'

[core_Authors]
itemKey = 'Group'
itemValue = 'Au'
; Use author names from 'BibRecord/BibRelationships/HasContributorRelationships/*PersonEntity/Name/NameFull'
;dataMethod = 'getPrimaryAuthorsWithHighlighting'
;limit = 3
separator = '; '

[result-list_Authors]
itemKey = 'Group'
itemValue = 'Au'
; Use author names from 'BibRecord/BibRelationships/HasContributorRelationships/*PersonEntity/Name/NameFull'
dataMethod = 'getPrimaryAuthorsWithHighlighting'
limit = 3
separator = '; '
