; Copy from RecordDataFormatter.ini and adapt if you want to adjust the settings for EDS via this file.

; The following comes from the default configuration of the [AuthorDisplay] section in EDS.ini that was added
; in VuFind Version 10.1 and replaced by using the RecordDataFormatter in 11.0
[Field_Items]
overrideContext['core'] = CoreItems
overrideContext['result-list'] = ResultListItems

[CoreItems]
; If a search link should be set on the elements of items (default is false)
;useSearchLink = true
; Element limit for each item (default is no limit)
;limit = 3
; Abbreviation that is displayed after the elements if the limit is exceeded (default is '...')
;abbreviation = " etc."
; Similar to [ItemGlobalFilter] of EDS.ini filters can also be used for lines by adding
; '<lineIdentifierKey>:<lineIdentifierValue>' to either filterExclude or filterInclude
;filterExclude[] = 'Label:Availability'
;filterInclude[] = 'Label:Availability'
;filterExclude[] = 'Group:Au'
;filterInclude[] = 'Group:Au'
; To change the options for single lines add the section with those options to extraLineOptions
extraLineOptions[] = 'CoreAuthors'

[ResultListItems]
; If a search link should be set on the elements of items (default is false)
;useSearchLink = true
; Element limit for each item (default is no limit)
;limit = 3
; Abbreviation that is displayed after the elements if the limit is exceeded (default is '...')
;abbreviation = " etc."
; Similar to [ItemGlobalFilter] of EDS.ini filters can also be used for lines by adding
; '<lineIdentifierKey>:<lineIdentifierValue>' to either filterExclude or filterInclude
;filterExclude[] = 'Label:Availability'
;filterInclude[] = 'Label:Availability'
;filterExclude[] = 'Group:URL'
;filterInclude[] = 'Group:URL'
; To change the options for single lines add the section with those options to extraLineOptions
extraLineOptions[] = 'ResultListAuthors'

[CoreAuthors]
lineIdentifierKey = 'Group'
lineIdentifierValue = 'Au'
; Use author names from 'BibRecord/BibRelationships/HasContributorRelationships/*PersonEntity/Name/NameFull'
;multiAltDataMethod = 'getPrimaryAuthorsWithHighlighting'
;limit = 3
separator = '; '

[ResultListAuthors]
lineIdentifierKey = 'Group'
lineIdentifierValue = 'Au'
; Use author names from 'BibRecord/BibRelationships/HasContributorRelationships/*PersonEntity/Name/NameFull'
multiAltDataMethod = 'getPrimaryAuthorsWithHighlighting'
limit = 3
separator = '; '
