# This file configures the HeaderBar section plugin, which renders menus and other
# controls at the top of every page. If this file is empty or missing, default
# settings will be used, matching the examples provided below.
#
# The format of this configuration is as follows:
#
# Array keys for every group are:
#   - label: text shown as group header, will be translated. Only shown on the
#     site map page.
#   - MenuItems: items shown in the menu - required
#   - checkMethod: the name of a HeaderBar section plugin method to perform
#     a check whether to show the group. If omitted, group will always display.
#
# Array keys for every menu item could be:
#   - checkMethod: the name of a HeaderBar section plugin method to perform
#     a check whether to show the item. If omitted, item will always display.
#   - template: template to render the item with. Templates do not support the keys
#     documented below.
#   - name: name of an item, used as a CSS class for the menu item's <li> tag
#   - icon: icon used for the item, has to be defined in theme config
#   - attributes: additional attributes for the menu item's <a> tag
#   - submenuItems: items to be shown in a dropdown menu. Submenu items support only
#     the keys documented below.
#   - label: the text shown as link, will be translated - required
#   - route: route name used to generate link target - required unless url, template
#     or submenuItems is set
#   - routeParams: parameters for dynamic routes
#   - url: target url, alternative to route - required unless route, template or
#     submenuItems is set
#   - siteMapPageTemplate: template to render the item with on the site map page if
#     the regular item is not suitable for use in the site map
#   - excludeFromSiteMapPage: set true to exclude item from the site map page
#
# You can use checkMethod: alwaysFail to disable specific inherited groups or items
# in local configuration. If you wish to completely override the default
# configuration you can disable configuration inheritance by adding a
# "@parent_yaml": false entry at the very top of your local configuration file.

Header:
  MenuItems:
    - label: 'Feedback'
      route: feedback-home
      icon: feedback
      checkMethod: checkFeedback
      attributes:
        id: feedbackLink
        data-lightbox: data-lightbox
      siteMapPageTemplate: Section/SiteMap/SiteMap-feedback.phtml

    - template: Section/HeaderBar/HeaderBar-cart.phtml
      checkMethod: checkCart
      siteMapPageTemplate: Section/SiteMap/SiteMap-cart.phtml

    - template: Section/HeaderBar/HeaderBar-account.phtml
      checkMethod: checkAccount
      siteMapPageTemplate: Section/SiteMap/SiteMap-account.phtml

    - template: Section/HeaderBar/HeaderBar-themeOptions.phtml
      checkMethod: checkThemeOptions
      excludeFromSiteMapPage: true

    - template: Section/HeaderBar/HeaderBar-allLangs.phtml
      checkMethod: checkAllLangs
      excludeFromSiteMapPage: true
