# If this file is empty or missing, default settings will be used, matching
# the examples provided below. The format of this configuration is as follows:
# array keys for every group are:
#   - MenuItems: items shown in the menu - required
#   - checkMethod: the name of a Header section plugin method to perform
#     a check whether to show the group. If omitted, group will always display.
# array keys for every menu item could be:
#   - name: name of an item
#   - label: the text shown as link, will be translated - required
#   - route: route name used to generate link target - route, url or template required
#   - routeParams: parameters for dynamic routes
#   - url: target url, alternative to route - route, url or template required
#   - template: template to render the item with
#   - icon: icon used for the item, has to be defined in theme config
#   - checkMethod: the name of a Header section plugin method to perform
#     a check whether to show the item. If omitted, item will always display.
#   - attributes: additional attributes for the menu item's <a> tag
#   - submenuItems: items to be shown in a dropdown menu. Example:
#       - label: 'Main item label'
#         url: '#'
#         submenuItems:
#           - label: 'Dropdown item 1'
#             route: item-1-route
#             description: 'Optional item description'
#           - label: 'Dropdown item 2'
#             route: item-2-route

Header:
  MenuItems:
    - label: 'Feedback'
      route: feedback-home
      icon: feedback
      checkMethod: checkFeedback
      attributes:
        id: feedbackLink
        data-lightbox: data-lightbox

    - template: Navigation/header-cart.phtml
      checkMethod: checkCart

    - template: Navigation/header-account.phtml
      checkMethod: checkAccount

    - template: Navigation/header-themeOptions.phtml
      checkMethod: checkThemeOptions

    - template: Navigation/header-allLangs.phtml
      checkMethod: checkAllLangs
