# Available styles. Keys are style names. Values are options.
# The following options are available:
# - classes: CSS classes to be added to the notices. If omitted, defaults will be applied by the Notices view helper.
styles:
  success:
  info:
  warning:
  danger:
#  my-custom-style-name:
#    classes: my-custom-css-class my-other-custom-css-class

# The following options configure the form for creating notices in the admin module.
adminForm:
# Uncomment to override the default languages from config.ini [Languages]
#  languages:
#    - "de"
#    - "en"
# Content types available in admin forms. See below for explanation of values.
  contentTypes:
    - text
    # To allow completely unescaped HTML uncomment the following option.
    # Everyone who can edit the content must be trusted and know what they are doing!
    #  - html
    - clean_html
    - markdown
# Notices can be configured here. You can use the following options:
# - content: The message to be displayed. It can be translated using the language files.
# - translations: To configure multiple languages in this file use this option instead of content.
#                 This is an associative array. Keys are language codes and values are
#                 the translated messages. The notices will only be displayed if the selected language
#                 is included in the keys. If the value is left empty the translation will be chosen
#                 based on the language fallback configuration in config.ini.
# - contentType: Specifies how the messages should be displayed. The default is "text". The options are
#                - "text": The message will be display as is. HTML will be escaped.
#                - "html": HTML in messages will not be escaped.
#                - "clean_html": Unsafe HTML will be escaped. See also \VuFind\View\Helper\Root\CleanHtmlFactory
#                                for additional information.
#                - "markdown": Messages will be rendered using Markdown.
# - style: Specifies one of the styles above.
# - position: Specifies the position of the notice. By default, the notices are displayed above the main content.
#             Currently, the only other option that is available is "header", but you can add more possible position
#             by adding <?=$this->notices()->renderNoticesForPosition('<position>')?> to your templates.
# - conditions: Optional array of conditions. For more details
#               see https://vufind.org/wiki/development:plugins:condition_handlers
notices:
# Example 1
#  - style: warning
#    content: The library is closed today!
# Example 2 (Notices will only be displayed for languages de, es and en. For es it will fall back to en)
#  - style: success
#    position: header
#    translations:
#      de: Willkommen in unserem Katalog!
#      es:
#      en: Welcome to our catalog!
# Example 3
#  - style: info
#    content: >
#      ## This is the catalog of our library
#
#      -------------------------------------
#
#      You can
#
#      * **search** for books
#
#      * **request** books
#
#      * create **favorite** lists
#    contentType: markdown
#  - style: success
#    content: Merry Christmas!
#    conditions:
#      - type: date
#        checkedValues: "/-12-2[4-6]/"
#        comparator: "regex"
