<!-- START of: finna - Helpers/cookie-consent.phtml -->
<div class="container-fluid cookie-consent">
  <div class="cookie-consent-text">
    <?=$this->translate('cookie_consent_html', ['%%link%%' => $this->url('content-page', ['page' => 'privacy']) . '#cookies'])?>
  </div>
  <div class="nav navbar-nav nav-absolute cookie-consent-button">
    <a class="btn btn-primary cookie-consent-dismiss"><?=$this->transEsc('OK')?></a>
  </div>
</div>
<!-- END of: finna - Helpers/cookie-consent.phtml -->
