<!-- START of: finna - Helpers/copyright-icons.phtml -->
<?php
  $displayIcons = [
    'CCBY' => ['cc', 'by'],
    'CCBYSA' => ['cc', 'by', 'sa'],
    'CCBYND' => ['cc', 'by', 'nd'],
    'CCBYNC' => ['cc', 'by', 'nc-eu'],
    'CCBYNCSA' => ['cc', 'by', 'nc-eu', 'sa'],
    'CCBYNCND' => ['cc', 'by','nc-eu', 'nd']
  ];
  $key = strtoupper(preg_replace('/[^A-Za-z]/', '', $this->copyright));
?>
<?php if (isset($displayIcons[$key])): ?>
  <?php foreach ($displayIcons[$key] as $icon): ?>
    <i class="iconlabel cc-<?=$icon ?>" aria-hidden="true"></i>
  <?php endforeach; ?>
<?php endif; ?>
<!-- END of: finna - Helpers/copyright-icons.phtml -->
