<?php $this->assetManager()->appendScriptLink('finna-survey.js'); ?>
<div id="finna-survey">
  <div class="icon-background">
    <a href="#" class="close-survey"><?=$this->icon('survey-close') ?><span class="visually-hidden"><?=$this->transEsc('close');?></span></a>
  </div>
  <h2><?=$this->transEsc('finna_survey_title') ?></h2>
  <h3><?=$this->transEsc('finna_survey_text') ?></h3>
  <a target="_blank" href="<?=$this->escapeHtmlAttr($this->url) ?>" class="btn btn-primary"><?=$this->transEsc('finna_survey_btn_ok') ?></a>
  <p><a href="#" class="close-survey"><?=$this->transEsc('finna_survey_btn_cancel') ?></a></p>
</div>
