<table class="opening-times-week info-element" data-period-start="<?=$this->escapeHtmlAttr($this->periodStart)?>">
  <tbody>
    <?php foreach ($this->schedules as $day): ?>
      <?php
        $openNow = false;
        $staffTimes = false;
        $selfServiceTimes = [];

        foreach ($day['times'] as $time) {
           $selfServiceTime = $time['selfservice'];
           $selfServiceTimes[] = $selfServiceTime;
           if ($selfServiceTime) {
              $staffTimes = true;
           }
           if (!empty($time['openNow'])) {
              $openNow = true;
           }
        }
        array_shift($selfServiceTimes);
        $classes = [];
        if ($day['today']) {
           $classes[] = 'today';
           $classes[] = $openNow ? 'open' : '';
      }
    ?>
    <tr<?= !empty($classes) ? (' class="' . implode(' ', $classes) . '"') : ''?>>
      <td><?= date('d.m', $day['date'])?></td>
      <td>
        <ul>
        <?php
        if (empty($day['times'])): ?>
          <li>
            <span class="day"><?=$this->translate('day-name-short-' . $day['dayName'])?></span>
            <span class="time"><?=$this->translate('organisation_info_is_closed')?></span>
          </li>
        <?php else:
          $cnt = 0;
          foreach ($day['times'] as $time):
        ?>
        <?php $selfServiceTime = $time['selfservice']; ?>
          <li<?=$staffTimes && !$selfServiceTime ? ' class="staff"' : ''?>>
            <span class="day">
            <?php if ($cnt++ == 0): ?>
               <?= $this->translate(!$staffTimes || $selfServiceTime ? ('day-name-short-' . $day['dayName']) : 'organisation_info_schedule_staff');?>
            <?php elseif (!$selfServiceTime && $staffTimes): ?>
                <?= $this->translate('organisation_info-schedule_staff');?>
            <?php else: ?>
               &nbsp;
            <?php endif; ?>
            </span>
            <span class="time"><?= $time['opens']?> - <?= $time['closes']?></span>
          </li>
          <?php endforeach; ?>
        <?php endif; ?>
        </ul>
      </td>
    </tr>
    <?php endforeach ?>
  </tbody>
</table>
