<?php
  if ($this->params['results'] ?? null) {
    echo $this->render('Helpers/pagination-simple-search.phtml');
    return;
  }
?>
<!-- START of: finna - Helpers/pagination-simple.phtml -->
<?php if ($this->pageCount): ?>
  <ul class="pagination-simple">
    <li><?php if (isset($this->previous)): ?>
      <?php $newParams = $this->params;
      $newParams['page'] = $this->previous; ?>
      <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
        <span class="visually-hidden"><?=$this->transEsc('page_prev')?></span><?=$this->icon('page-simple-prev') ?>
      </a>
    <?php endif; ?>
    </li>
    <li>
      <?php
        $transParams = [
          '%%start%%' => $this->firstItemNumber,
          '%%end%%' => $this->lastItemNumber,
          '%%total%%' => $this->localizedNumber($this->totalItemCount),
        ];
      ?>
      <?=$this->label ?: $this->translate('showing_results_of_html', $transParams)?>
    </li>
    <li><?php if (isset($this->next)): ?>
      <?php $newParams = $this->params;
      $newParams['page'] = $this->next; ?>
      <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
        <span class="visually-hidden"><?=$this->transEsc('page_next')?></span><?=$this->icon('page-simple-next') ?>
      </a>
    <?php endif; ?>
    </li>
  </ul>
<?php endif; ?>
<!-- END of: finna - Helpers/pagination-simple.phtml -->
