<div class="public-list-embed<?= $this->showAllLink ? ' show-all' : ''?>">
  <div class="clearfix hidden-print">
    <div class="public-list-row">
      <?php if ($this->title): ?><h<?=$this->headingLevel?>><?= $this->title ?></h<?=$this->headingLevel?>><?php endif ?>
      <?php if ($this->description): ?><div class="public-list-desc"><?= $this->markdown()->toHtml($this->description) ?></div><?php endif ?>
      <?php if ($this->listTags): ?>
        <div class="public-list-tags">
          <?php foreach ($this->listTags as $tag): ?>
            <div class="tag"><?= $this->escapeHtml($tag->tag) ?></div>
          <?php endforeach ?>
        </div>
      <?php endif ?>
      <?php if ($this->date): ?>
        <div class="public-list-info">
          <div><?= $this->transEsc("modified"); ?>: <?=$this->dateTime()->convertToDisplayDate('Y-m-d H:i:s', $this->date); ?></div>
        </div>
      <?php endif ?>
    </div>
  </div>
  <?php if ($this->allowCopy): ?>
    <div class="hidden-print controls">
      <div>
        <a class="btn btn-primary btn-sm btn-block" data-lightbox role="button" href="<?= $this->url('list-save', [ 'id' => $this->id ]) ?>">
          <?=$this->transEsc('import_favorites_from_list')?>
        </a>
      </div>
    </div>
  <?php endif; ?>
  <div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->view)?>">
    <?= $this->partial('search/list-' . $this->view . '.phtml',
    [
      'results' => $this->results,
      'params' => $this->params,
      'indexStart' => $this->indexStart,
      'hideCartControls' => true
    ])
    ?>
    <?php if ($this->showAllLink): ?>
      <?php $limit = $this->params->getLimit(); ?>  
      <div class="show-more">
        <div><?= $this->translate(
             'showing_results_of_html', [
               '%%start%%' => 1,
               '%%end%%' => $limit,
               '%%total%%' => $this->localizedNumber($this->total)
             ]
        ); ?>
        </div>
        <button class="btn btn-outline-primary load-more" aria-label="<?= $this->transEsc('See all')?>" data-id="<?= $this->escapeHtmlAttr($this->id)?>" data-start-index="<?= $this->escapeHtmlAttr($this->indexStart + $limit)?>" data-offset="<?= $this->escapeHtmlAttr($limit + 1)?>" data-view="<?= $this->escapeHtmlAttr($this->view)?>"<?= $this->sort ? (' data-sort="' . $this->escapeHtmlAttr($this->sort) . '"') : ''?>><?= $this->transEsc('See all'); ?></button>
        <i class="fa fa-spinner fa-spin hide"></i>
      </div>
    <?php endif; ?>
  </div>
</div>
<?php
$this->headScript()->appendFile("finna-userlist-embed.js");
$js = <<<JS
$(document).ready(function(){
  finna.userListEmbed.init();
});
JS;
$this->headScript()->appendScript($js);
?>
