<!-- START of: finna - Auth/MultiILS/login.phtml -->
<?php $account = $this->auth()->getManager(); ?>
<?php $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<?php if (!$sessionInitiator): // display default login form if no login URL provided ?>
<div class="login-col">
  <form method="post" class="form-vertical" action="<?=$this->url('myresearch-home')?>" name="loginForm" id="loginForm">
    <?=$this->auth()->getLoginFields()?>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash())?>" />
    <div class="clearfix"></div>
    <div class="form-group">
        <?php if ($account->supportsCreation()): ?>
          <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
        <?php endif; ?>
        <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">
        <?php if ($account->supportsRecovery()): ?>
          <br/>
          <a class="btn btn-link" href="<?=$this->url('myresearch-recover') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Forgot Password')?></a>
        <?php endif; ?>
        <p>
          <a id="login_library_card_register" class="btn btn-link" href="<?=$this->url('librarycards-register') ?>"><?=$this->transEsc('new_ils_account')?></a>
        </p>
        <p>
          <a id="login_library_card_recovery" class="btn btn-link" href="<?=$this->url('librarycards-recover') ?>"><?=$this->transEsc('Forgot Password')?></a>
        </p>
    </div>
  </form>
</div>
<div class="login-col">
  <i class="fa fa-info3" aria-hidden="true"></i>
  <div class="login-description">
    <p class="login-info">
      <?=$this->translate('login_desc_library_card_html') ?>
    </p>
  </div>
  <div class="clearfix"></div>
  <?php
    $language = $this->layout()->userLang;
    if (!in_array($language, ['fi', 'sv', 'en-gb'])) {
      $language = 'en-gb';
    }
  ?>
  <?=$this->partial("Auth/MultiILS/terms_$language.phtml") ?>
</div>
  <div class="clearfix"></div>
<?php else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>" data-lightbox-ignore><?=$this->transEsc("Institutional Login")?></a>
<?php endif; ?>

<?php
  $recovery = [];
  $register = [];
  foreach ($account->getLoginTargets() as $target) {
    $recovery[$target] = $account->ilsSupportsPasswordRecovery($target)
      ? $this->url('librarycards-recover') . "?target=$target" : false;
    $register[$target] = $account->ilsSupportsSelfRegistration($target)
      ? $this->url('librarycards-register') . "?target=$target" : false;
  }

  $recovery = json_encode($recovery);
  $register = json_encode($register);
  $script = <<<EOT
  finna.layout.initILSPasswordRecoveryLink($recovery, 'login_{$topClass}_');
  finna.layout.initILSSelfRegistrationLink($register, 'login_{$topClass}_');
EOT;

  // Inline the script for lightbox compatibility
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
<!-- END of: finna - Auth/MultiILS/login.phtml -->
