<!-- START of: finna - Auth/MultiILS/loginfields.phtml -->
<?php
  $authManager = $this->auth()->getManager();
?>
<div>
  <div class="form-group">
    <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
    <?php if (count($authManager->getLoginTargets()) > 1): ?>
      <label class="control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
      <select id="login_target" name="target" class="form-control">
        <?php foreach ($authManager->getLoginTargets() as $target):?>
          <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
        <?php endforeach ?>
      </select>
    <?php else: ?>
      <input type="hidden" id="login_target" name="target" value="<?=$this->escapeHtmlAttr($currentTarget)?>">
      <div><strong><?=$this->transEsc("source_$currentTarget", null, $currentTarget)?></strong></div>
    <?php endif; ?>
  </div>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_secondary_username"></label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_secondary_username" type="text" name="secondary_username" value="<?=$this->escapeHtmlAttr($this->request->get('secondary_username'))?>" class="form-control"/>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" type="password" name="password" class="form-control"/>
  </div>
</div>

<?php
  $labels = [];
  foreach ($authManager->getLoginTargets() as $target) {
    $label = $authManager->getSecondaryLoginFieldLabel($target);
    $labels[$target] = $label ? addslashes($this->translate($label)) : '';
  }

  $labels = json_encode($labels);
  $script = <<<EOT
  finna.layout.initSecondaryLoginField($labels, '{$topClass}');
EOT;

  // Inline the script for lightbox compatibility
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>

<!-- END of: finna - Auth/MultiILS/loginfields.phtml -->
