<div class="login-description-terms">
  <p>Kirjastokortin numerolla kirjauduttaessa tallennetaan verkkopalveluun kirjastokortin tunnus, PIN-koodi, kirjautujan nimi, sähköpostiosoite ja kotikirjasto.</p>
  <p>Sähköpostiosoitteella kirjauduttaessa tallennetaan kirjautujan nimi, sähköpostiosoite ja kotikirjasto.</p>
  <p>Lisätietoa henkilötietojen käsittelystä <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?>-sivulla</a>.</p>
</div>
