<?php
  if (!isset($this->label)) {
    throw new \Exception('label undefined for confirm-menu component.');
  }

  $toggleLabel = $this->transEsc($this->label);
  $toggleClass = trim('confirm__toggle ' . $this->escapeHtmlAttr(($this->toggleClass ?? 'btn')));

  $actionType = $this->action->type ?? 'submit';

  $confirmLabel = $this->transEsc($this->confirm ?? 'confirm_dialog_yes');
  $cancelLabel = $this->transEsc($this->cancel ?? 'confirm_dialog_no');
?>

<div class="confirm-menu">
  <button class="<?=$toggleClass ?>"><?=$toggleLabel ?></button>

  <div class="confirm__options">
    <?php if ($this->description): ?>
      <p class="confirm__desc"><?=$this->transEsc($this->description) ?></p>
    <?php endif; ?>

    <ul role="menu" class="confirm__menu">
      <li role="none">
        <?php if ($actionType == 'link'): ?>
          <a role="menuitem" class="confirm__confirm" href="<?=$this->escapeHtmlAttr($this->action->value) ?>">
            <?=$this->icon('ui-success', 'confirm__icon') ?>
            <?=$confirmLabel ?>
          </a>
        <?php else: ?>
          <button role="menuitem" type="submit" class="confirm__confirm">
            <?=$this->icon('ui-success', 'confirm__icon') ?>
            <?=$confirmLabel ?>
          </button>
        <?php endif; ?>
      </li>

      <li role="none">
        <button type="button" role="menuitem" class="confirm__cancel">
          <?=$this->icon('ui-failure', 'confirm__icon') ?>
          <?=$cancelLabel ?>
        </button>
      </li>
    </ul>
  </div>
</div>
