<?php
  $wrapperTag = $this->wrapperTag ?? 'div';
  $wrapperClass = 'dropdown'; // Bootstrap class

  if ($this->wrapperClass ?? false) {
    $wrapperClass = $this->wrapperClass . ' dropdown'; // Bootstrap class
  }

  $toggleTag = 'button';
  $toggleAttrs = $this->toggleAttrs ?? [];
  $toggleAttrs['type'] = 'button'; // Accessible default
  $toggleAttrs['class'] = 'dropdown-toggle'; // Bootstrap class
  $toggleAttrs['data-toggle'] = 'dropdown'; // Bootstrap data-attr
  $toggleAttrs['aria-expanded'] = 'false';
  $toggleAttrs['aria-haspopup'] = 'true';

  // An anchor tag with an href should only be used as
  // a non-js fallback to open the menu on another page
  if ($this->href ?? false) {
    $toggleTag = 'a';
    $toggleAttrs['href'] = $this->href;
    $toggleAttrs['type'] = null;
  }
?>

<?php ob_start(); ?>
  <ul class="dropdown-menu">
    <?php foreach ($this->menuItems as $current): ?>
      <li class="dropdown__item <?php if ($current['selected'] ?? false): ?> active<?php endif ?>">
        <a class="dropdown__link" href="<?=$this->escapeHtmlAttr($current['url']) ?>" rel="nofollow">
          <?=$this->transEsc($current['label']) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>

  <?=$this->makeTag(
    $toggleTag,
    $this->transEsc($this->toggleLabel) . $this->icon('dropdown-caret'),
    $toggleAttrs,
    ['escapeContent' => false]
) ?>
<?php $menuContents = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?=$this->makeTag($wrapperTag, $menuContents, $wrapperClass, ['escapeContent' => false]); ?>
