<?php
  $wrapperTag = $this->wrapperTag ?? 'div';
  $showSelectedValue = $this->showSelectedValue ?? false;
  $wrapperClass = 'dropdown'; // Bootstrap class

  if ($this->wrapperClass ?? false) {
    $wrapperClass = $this->wrapperClass . ' dropdown'; // Bootstrap class
  }

  // defaults
  $toggleAttrs = [
    'id' => uniqid('toggle-'),
    'type' => 'button', // Accessible default
    'data-toggle' => 'dropdown', // Bootstrap data-attr
    'aria-expanded' => 'false',
    'aria-haspopup' => 'true',
  ];

  $toggleTag = $this->toggleTag ?? 'button';
  $toggleAttrs = $toggleAttrs + ($this->toggleAttrs ?? []);
  // Bootstrap class
  $toggleAttrs['class'] = trim('dropdown-toggle ' . ($toggleAttrs['class'] ?? ''));

  // An anchor tag with an href should only be used as
  // a non-js fallback to open the menu on another page
  if ($this->href ?? false) {
    $toggleTag = 'a';
    $toggleAttrs['href'] = $this->href;
    $toggleAttrs['type'] = null;
  }
  $selected = $this->defaultSelectedValue ?? '';
?>
<?php ob_start(); ?>
  <ul class="dropdown-menu">
    <?php foreach ($this->menuItems as $current): ?>
      <?php
        if ($current['selected'] ?? false) {
          $selected = $this->transEsc($current['label']);
          $extraClasses = ' active';
        } else {
          $extraClasses = '';
        }
      ?>
      <li class="dropdown__item-container<?=$extraClasses?>">
        <?php
          $extra = $current['extraLinkAttributes'] ?? [];
          $standard = ['class' => 'dropdown-item', 'href' => $current['url'], 'rel' => 'nofollow'];
          $linkAttributes = array_merge($extra, $standard);
        ?>
        <a<?=$this->htmlAttributes($linkAttributes)?>>
          <?=$this->transEsc($current['label']) ?>
        </a>
      </li>
    <?php endforeach; ?>
  </ul>
  <?php
    $label = empty($this->toggleLabel) ? '' : $this->transEsc($this->toggleLabel);
    $buttonText = $showSelectedValue ? $selected : $label;
  ?>
  <?php if ($showSelectedValue && '' !== $label): ?>
    <label for="<?=$this->escapeHtmlAttr($toggleAttrs['id'])?>"><?=$this->escapeHtml($label)?></label>
  <?php endif; ?>
  <?=
    $this->makeTag(
        $toggleTag,
        $buttonText . $this->icon('dropdown-caret'),
        $toggleAttrs,
        ['escapeContent' => false]
    )
  ?>
<?php $menuContents = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?=$this->makeTag($wrapperTag, $menuContents, $wrapperClass, ['escapeContent' => false]) ?>
