<?php
    if (null === ($side = $this->config()->offcanvasSide())) {
        return '';
    }
?>
<a class="search-filter-toggle icon-link" href="#search-sidebar" data-toggle="vufind-offcanvas" title="<?=$this->transEscAttr('sidebar_expand') ?>">
    <?='left' === $side ? $this->icon('offcanvas-show-left', 'icon-link__icon') : ''?>
    <span class="icon-link__label"><?=$this->transEsc('Refine Results') ?></span>
    <?='right' === $side ? $this->icon('offcanvas-show-right', 'icon-link__icon') : ''?>
</a>
