<?php if (null === ($side = $this->config()->offcanvasSide())): ?>
    <a class="search-filter-toggle" href="#myresearch-sidebar" title="<?=$this->transEscAttr('sidebar_expand')?>">
        <?=$this->transEsc('Your Account') ?>
    </a>
<?php else: ?>
    <a class="search-filter-toggle icon-link" href="#myresearch-sidebar" data-toggle="vufind-offcanvas" title="<?=$this->transEscAttr('sidebar_expand')?>">
        <?='left' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-show-right' : 'offcanvas-show-left', 'icon-link__icon') : ''?>
        <span class="icon-link__label"><?=$this->transEsc('Your Account') ?></span>
        <?='right' === $side ? $this->icon($this->layout()->rtl ? 'offcanvas-show-left' : 'offcanvas-show-right', 'icon-link__icon') : ''?>
    </a>
<?php endif; ?>
