<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");

  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
      $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  // Set flag for special cases relating to full-width hierarchy tree tab:
  $tree = (strtolower($this->activeTab) == 'hierarchytree');
  
  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', ' <span class="divider">&gt;</span> </li>')
     . '<li><a href="' . $this->url('collections-home') . '">' . $this->transEsc('Collections') . '</a> <span class="divider">&gt;</span> </li>'
     . '<li class="active">' . $this->recordLink()->getBreadcrumb($this->driver) . '</li>';
?>

<? if (isset($this->scrollData) && ($this->scrollData['previousRecord'] || $this->scrollData['nextRecord'])): ?>
  <ul class="pager">
    <? if ($this->scrollData['previousRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['previousRecord'])?>" title="<?=$this->transEsc('Previous Search Result')?>">&laquo; <?=$this->transEsc('Prev')?></a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#">&laquo; <?=$this->transEsc('Prev')?></a></li>
    <? endif; ?>
    #<?=$this->escapeHtml($this->scrollData['currentPosition']) . ' ' . $this->transEsc('of') . ' ' . number_format($this->escapeHtml($this->scrollData['resultTotal'])) . ' ' . $this->transEsc('results') ?>
    <? if ($this->scrollData['nextRecord']): ?>
      <li>
        <a href="<?=$this->recordLink()->getUrl($this->scrollData['nextRecord'])?>" title="<?=$this->transEsc('Next Search Result')?>"><?=$this->transEsc('Next')?> &raquo;</a>
      </li>
    <? else: ?>
      <li class="disabled"><a href="#"><?=$this->transEsc('Next')?> &raquo;</a></li>
    <? endif; ?>
  </ul>
<? endif; ?>

<?=$this->record($this->driver)->getToolbar()?>

<div class="<?=isset($activeTabObj) && is_callable(array($activeTabObj, 'getSideRecommendations')) ? $this->layoutClass('mainbody') : 'span11' ?>">
  <div class="record recordId source<?=$this->escapeHtml($this->driver->getResourceSource())?>" id="record">
    <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenId" id="record_id" />
    <?=$this->flashmessages()?>
    <?=$this->record($this->driver)->getCollectionMetadata()?>
  </div>

  <? if (count($this->tabs) > 0): ?>
    <a name="tabnav"></a>
    <ul class="nav nav-tabs">
      <? foreach ($this->tabs as $tab => $obj): ?>
      <? // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $isCurrent = (strtolower($this->activeTab) == strtolower($tab));
        if ($isCurrent) {
          $this->layout()->breadcrumbs .= '<li class="active"><span class="divider">&gt;</span> ' . $this->transEsc($desc) . '</li>';
          $activeTabObj = $obj;
        }
      ?>
      <li<?=$isCurrent ? ' class="active"' : ''?>>
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
      </li>
      <? endforeach; ?>
    </ul>
  <? endif; ?>


  <div class="collectionDetails<?=$tree ? 'Tree' : ''?>">
    <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
  </div>

  <span class="Z3988" title="<?=$this->escapeHtml($this->driver->getOpenURL())?>"></span>
</div>

<? if (isset($activeTabObj) && is_callable(array($activeTabObj, 'getSideRecommendations'))): ?>
  <div class="<?=$this->layoutClass('sidebar')?>">
    <? foreach ($activeTabObj->getSideRecommendations() as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>
  </div>
<? endif; ?>
