<!-- START of: finna - feedcontent/content.phtml -->
<?
  $this->headScript()->appendFile('finna-content-feed.js');
  $this->headTitle($this->translate(''));
  $this->content()->setHeading($this->translate(''));
  $this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
     'content/header.phtml', ['heading' => $this->content()->getHeading()]
  );

  if ($this->modal) {
     $setupJS = <<<JS
$(document).ready(function() {
   finna.contentFeed.loadFeed($('#modal .feed-content'), true);
});
JS;
    $this->headScript()->appendScript($setupJS);
  }
?>

<?=$this->headScript()?>
<div class="row">
  <div class="col-<?= $this->modal ? 'xs-12' : 'sm-9'?> feed-content" data-feed="<?=$this->escapeHtmlAttr($this->feed)?>" data-num="<?=$this->escapeHtmlAttr($this->element)?>">

  <? if ($this->modal): ?>
    <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
    <div class="holder"></div>
  </div>

  <? else: ?>
    <div class="row">
      <div class="col-xs-12 col-md-11 col-lg-10">
        <div class="date"><?=$this->transEsc('Published');?>: <span></span></div>
        <div class="holder"></div>
      </div>
    </div>
  </div>
  <div class="col-sm-3 sidebar">
    <div><h3 class="article-navigation-header"><?=$this->translate('content-feed-navigation')?></h3></div>
    <div class="article-navigation-wrapper"></div>
  </div>
  <? endif; ?>

</div>
<!-- END of: finna - feedcontent/content.phtml -->
