<div class="facet-group">
  <a href="<?=$this->url('admin')?>" class="facet<?=strtolower($this->layout()->templateName) == "home" ? ' active' : ''?>"><?=$this->transEsc('Home')?></a>
  <a href="<?=$this->url('admin/social')?>" class="facet<?=strtolower($this->layout()->templateName) == "socialstats" ? ' active' : ''?>"><?=$this->transEsc('Social Statistics')?></a>
  <a href="<?=$this->url('admin/config')?>" class="facet<?=strtolower($this->layout()->templateName) == "config" ? ' active' : ''?>"><?=$this->transEsc('Configuration')?></a>
  <a href="<?=$this->url('admin/maintenance')?>" class="facet<?=strtolower($this->layout()->templateName) == "maintenance" ? ' active' : ''?>"><?=$this->transEsc('System Maintenance')?></a>
  <a href="<?=$this->url('admin/tags')?>" class="facet<?=strtolower($this->layout()->templateName) == "tags" ? ' active' : ''?>"><?=$this->transEsc('Tag Maintenance')?></a>
</div>
