<!-- templates - vudl - views - AUDIO.phtml -->
<script>
  var mobile = /Android|webOS|iPhone|iPad|iPod|BlackBerry/i.test(navigator.userAgent);
  var audioSupported = document.createElement('audio').canPlayType('audio/mpeg')
    || document.createElement('audio').canPlayType('audio/ogg')
    || document.createElement('audio').canPlayType(data['mimetype']);
  updateFunction = mobile ? false : function(data, tab) {
    if (audioSupported) {
      var html = '<source src="'+data['ogg']+'?download=true"/>'
      + '<source src="'+data['mp3']+'?download=true"/>'
      + '<source src="'+data[data['master']]+'?download=true"/>';
      var audio = $('audio');
      audio.trigger('pause').html(html).removeClass('hide');
      audio[0].load();
    }
  };
  $(document).ready(function() {
    currentTab = "master-tab";
    $('#view .tabs li.opener a').addClass('hide');
  });
</script>
<dl class="tabs" data-tab>
  <dd class="static opener">
    <a onClick="toggleSideNav()">
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
      <i class="fa fa-caret-right"></i>
    </a>
  </dd>
  <dd class="active"><a>Player and Downloads</a></dd>
</dl>
<div class="tab-container text-center tabs-content">
		<audio controls preload="auto">
			<? if(isset($this->ogg)): ?><source src="<?=$this->ogg ?>?download=true"/><?endif?>
			<? if(isset($this->mp3)): ?><source src="<?=$this->mp3 ?>?download=true"/><?endif?>
			<? if(!isset($this->mp3) && !isset($this->ogg)): ?><source src="<?=$this->master ?>?download=true"/><?endif?>
		</audio>
		<br/><br/>
		<?=$this->context($this)->renderInContext('vudl/master-tab.phtml', array())?>
</div>
<!-- templates - vudl - views - AUDIO.phtml end -->