<!--<div class="container-fluid bg-white">-->
    <div class="row">
        <div class="col-12">
            <? $account = $this->auth()->getManager(); ?>

            <!-- Begin section Navbar -->
            <nav class="navbar navbar-expand-lg navbar-light justify-content-between">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="sr-only">Toggle navigation</span>
                    <i class="fa fa-bars" aria-hidden="true"></i>
                </button>

                <? if (!isset($this->layout()->renderingError)): ?>
                <div class="collapse navbar-collapse" id="header-collapse">
                    <nav>
                        <div class="row">
                            <!-- Images for supporters (TueFind extension template)   -->
                            <div id="tuefind_logos" class="col-xs-12 col-md-8">
                            <?=$this->render('header/logo');?>
                            </div>

                            <div class="col-xs-12 col-md-4">
                                <ul class="nav navbar-nav navbar-right flip ml-auto">

                                    <!-- Begin section Main Menu -->
                                    <!-- Home -->
                                    <li class="nav-item active">
                                        <a class="nav-link" href="<?=$this->url('home')?>" >
                                            <i class="fa fa-home" aria-hidden="true"> </i>
                                            <?=$this->transEsc('Home');?>
                                        </a>
                                    </li>

                                    <!-- TueFind extension template -->
                                    <?=$this->render('header/extensions');?>

                                    <!-- Begin section user account -->
                                    <? if (is_object($account) && $account->loginEnabled()): //FIXME: hide login/logout if unavailable ?>
                                        <li class="nav-item logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                            <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" class="nav-link" title="<?=$this->transEsc("Your Account")?>"><i class="fa fa-home"></i> <?=$this->transEsc("Your Account")?></a>
                                        </li>
                                        <li class="nav-item logoutOptions<? if(!$account->isLoggedIn()): ?> hidden<? endif ?>">
                                            <a href="<?=$this->url('myresearch-logout')?>" class="nav-link" title="<?=$this->transEsc("Log Out")?>"><i class="fa fa-sign-out"></i> <?=$this->transEsc("Log Out")?></a>
                                        </li>
                                        <li id="nav-item loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
                                            <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
                                                <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Institutional Login")?></a>
                                            <? else: ?>
                                                <a href="<?=$this->url('myresearch-userlogin')?>" class="nav-link" data-lightbox title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in"></i> <?=$this->transEsc("Login")?></a>
                                            <? endif; ?>
                                        </li>
                                    <? endif; ?>
                                    <!-- End section user account -->

                                    <!-- Begin section language   -->
                                    <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
                                    <li class="nav-item dropdown">
                                        <form method="post" name="langForm" id="langForm">
                                            <input type="hidden" name="mylang"/>
                                        </form>
                                        <a href="#" class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                            <i class="fa fa-globe" aria-hidden="true"></i>
                                            <?=$this->transEsc("Language")?> <b class="caret"></b>
                                        </a>
                                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" >
                                            <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
                                                <li>
                                                    <a class="dropdown-item <? if ($this->layout()->userLang == $langCode) {
                                                    echo 'active'; } ?>" href="#" onClick="document.langForm.mylang.value='<?=$langCode?>';document.langForm.submit()">
                                                    <?=$this->displayLanguageOption($langName)?>
                                                    </a>
                                                </li>
                                            <? endforeach; ?>
                                        </ul>
                                    </li>
                                    <? endif; ?>
                                    <!-- End section language  -->

                                <!-- End section Main Menu -->
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
            <? endif; ?>
            <!-- End section Navbar -->
        </nav>
    </div><!-- close col's -->
</div><!-- close row -->
<!--</div>--><!-- close container -->

<!--  Begin seachbox -->
<?=$this->layout()->searchbox ?>
<!--  End seachbox -->

<!-- Begin header image -->
<? //Set up the header image. It comes up instead of the search box.
   //Accepts:
   //1. false; nothing will be displayed, this is default.
   //2. A string; the header image in the string will be displayed. JavaScript will not applied.
if(isset($this->layout()->headerImage)) {
    echo '<img src="'.$this->imageLink($this->layout()->headerImage).'" class="img-fluid header-image" alt="header image"/>';
}
?>
<!-- End header image -->
