<!-- cart - CART.phtml -->
<?
// Set page title.
$this->headTitle($this->translate('Book Bag'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
?>
<h2><?=$this->transEsc('Book Bag') ?></h2>
<?=$this->flashmessages()?>
<form action="<?=$this->url('cart-processor')?>" method="post"  name="cartForm" data-lightbox-onsubmit="cartFormHandler">
  <input type="hidden" id="dropdown_value"/>
  <? if (!$this->cart()->isEmpty()): ?>
    <div class="cart-controls clearfix hide-for-print">
      <div class="checkbox left select-all">
        <label>
          <input type="checkbox" name="selectAll" class="checkbox-select-all"/>
          <?=$this->transEsc('select_page')?>
        </label>
      </div>
      <? if ($this->userlist()->getMode() !== 'disabled'): ?>
        <button type="submit" class="button secondary small" aria-label="submit form" name="saveCart" title="<?=$this->transEsc('bookbag_save')?>" value="1">
          <i class="fa fa-save"></i>
          <?=$this->transEsc('Save')?>
        </button>
      <? endif; ?>
      <button type="submit" class="button secondary small" aria-label="submit form" name="email" title="<?=$this->transEsc('bookbag_email')?>" value="1">
        <i class="fa fa-envelope-o"></i>
        <?=$this->transEsc('Email')?>
      </button>
      <? $exportOptions = $this->export()->getActiveFormats('bulk');
      if (count($exportOptions) > 0): ?>
        <button type="submit" class="button secondary small" aria-label="submit form" name="export" title="<?=$this->transEsc('bookbag_export')?>" value="1">
          <i class="fa fa-list-alt"></i>
          <?=$this->transEsc('Export')?>
        </button>
      <? endif; ?>
      <button type="submit" class="button secondary small" aria-label="submit form" name="print" title="<?=$this->transEsc('print_selected')?>" value="1">
        <i class="fa fa-print"></i>
        <?=$this->transEsc('Print')?>
      </button>
      <? /* We dont need another div here, CK */ ?>
      <button type="submit" class="button secondary small" aria-label="submit form" name="delete" id="cart-delete-label" value="1">
        <i class="fa fa-trash"></i>
        <?=$this->transEsc('Delete')?>
      </button>
      <ul id="cart-delete-label-dd" class="f-dropdown" data-dropdown-content role="menu" aria-labelledby="cart-delete-label" aria-hidden="true" tabindex="-1">
        <li><a id="cart-confirm-delete" onClick="submitFormWithButton(this, 'delete')" title="<?=$this->transEsc('confirm_delete')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
      <? /* We dont need another div here, CK */ ?>
      <button type="submit" class="button secondary small" name="empty" id="cart-empty-label" value="1">
        <i class="fa fa-close"></i>
        <?=$this->transEsc('Empty Book Bag')?>
      </button>
      <ul id="cart-empty-label-dd" class="f-dropdown" data-dropdown-content role="menu" aria-labelledby="cart-empty-label" aria-hidden="true" tabindex="-1">
        <li><a id="cart-confirm-empty" onClick="submitFormWithButton(this, 'empty')" title="<?=$this->transEsc('bookbag_confirm_empty')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a onClick="$('.fa.fa-spinner').remove()"><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>
  <? endif; ?>
  <?=$this->render('cart/contents.phtml')?>
</form>
<?
$script = <<<JS
  function submitFormWithButton(link, name) {
    $('#dropdown_value').attr('name', name).val(1);
    $(link).closest('form').submit();
  }
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET')?>
<!-- cart - CART.phtml end -->