<!-- cart - EXPORT.phtml -->
<?
// Set page title.
$this->headTitle($this->translate('Export Favorites'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li><a href="' .$this->url('cart-home'). '">' .$this->transEsc('Cart'). '</a></li> '
    . '<li class="active">' . $this->transEsc('Export Favorites') . '</li>';
?>
<h2><?=$this->transEsc('Export Favorites')?></h2>

<?=$this->flashmessages()?>

<? if (!empty($this->exportOptions)): ?>
  <form class="form-horizontal" method="post" action="<?=$this->url('cart-export')?>" name="exportForm" title="<?=$this->transEsc('Export Items')?>">
    <? foreach ($this->records as $current): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($current->getResourceSource() . '|' . $current->getUniqueId())?>" />
    <? endforeach; ?>
    <div class="form-group">
      <label class="medium-3 columns control-label"><?=$this->transEsc('Title')?></label>
      <div class="medium-9 columns">
        <? if(count($this->records) > 1): ?>
          <button type="button" class="button secondary tiny hide" data-dropdown="itemhide" role="button" aria-controls="itemhide" aria-expanded="false">
            <?=count($this->records).' '.$this->transEsc('items') ?>
          </button>
          <ul id="itemhide" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
            <? foreach ($this->records as $current): ?>
              <li><?=$this->escapeHtml($current->getBreadcrumb())?></li>
            <? endforeach; ?>
          </ul>
        <? else: ?>
          <p class="form-control-static"><?=$this->records[0]->getBreadcrumb() ?></p>
        <? endif; ?>
      </div>
    </div>
    <div class="form-group">
      <label for="format" class="medium-3 columns control-label"><?=$this->transEsc('Format')?>:</label>
      <div class="medium-9 columns">
        <select name="format" id="format" class="form-control">
          <? foreach ($this->exportOptions as $exportOption): ?>
            <option value="<?=$this->escapeHtmlAttr($exportOption)?>"><?=$this->transEsc($this->export()->getLabelForFormat($exportOption))?></option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
    <div class="form-group">
      <div class="medium-9 columns medium-offset-3">
        <input class="button secondary tiny" role="button" type="submit" name="submit" value="<?=$this->transEsc('Export')?>"/>
      </div>
    </div>
  </form>
<? endif; ?>
<?
$script = <<<JS
  $('button.button.hide').removeClass('hide');
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
<!-- cart - EXPORT.phtml - END -->