<!-- cart - SAVE.phtml -->
<?
    // Set page title.
    $this->headTitle($this->translate('bookbag_save_selected'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ') .
        '<li class="active">' . $this->transEsc('bookbag_save_selected') . '</li>';
?>
<h2><?=$this->transEsc('bookbag_save_selected')?></h2>

<?=$this->flashmessages()?>

<form method="post" action="<?=$this->url('cart-save')?>" name="bulkSave">
  <? $idParams = array(); ?>
  <? foreach ($this->records as $current): ?>
    <? $idParams[] = urlencode('ids[]') . '=' . urlencode($current->getSourceIdentifier() . '|' . $current->getUniqueId()) ?>
    <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($current->getSourceIdentifier() . '|' . $current->getUniqueId())?>" />
  <? endforeach; ?>
  <div class="row">
    <label class="medium-3 columns"><?=$this->transEsc('Title')?></label>
    <div class="medium-9 columns">
    <? if(count($this->records) > 1): ?>
      <button type="button" class="button secondary small hide" data-dropdown="itemhide" aria-controls="itemhide" aria-expanded="false">
        <?=count($this->records).' '.$this->transEsc('items') ?>
      </button>
      <ul id="itemhide" class="f-dropdown" data-dropdown-content aria-hidden="true" tabindex="-1">
          <? foreach ($this->records as $current): ?>
            <li><?=$this->escapeHtml($current->getBreadcrumb())?></li>
          <? endforeach; ?>
      </ul>
    <? else: ?>
      <p><?=$this->records[0]->getBreadcrumb() ?></p>
    <? endif; ?>
    </div>
  </div>

  <div class="row">
    <label class="medium-3 columns" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <div class="medium-9 columns">
      <select id="save_list" name="list" class="auto-width">
        <? if (count($this->lists) > 0): ?>
          <? foreach ($this->lists as $list): ?>
            <option value="<?=$list['id'] ?>"<? if ($list['id']==$this->userList()->lastUsed()): ?> selected="selected"<? endif; ?>><?=$this->escapeHtml($list['title'])?></option>
          <? endforeach; ?>
        <? else: ?>
          <option value=""><?=$this->transEsc('My Favorites') ?></option>
        <? endif; ?>
      </select>
      <a class="button small secondary" id="make-list" role="button" href="<?=$this->url('editList', array('id' => 'NEW')) . '?' . implode('&', $idParams) ?>" title="<?=$this->transEsc('Create a List') ?>"><?=$this->transEsc('or create a new list'); ?></a>
    </div>
  </div>

  <? if ($this->usertags()->getMode() !== 'disabled'): ?>
    <div class="row">
      <label class="medium-3 columns" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
      <div class="medium-9 columns">
        <input id="add_mytags" type="text" name="mytags" value="" class="auto-width"/>
        <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
      </div>
    </div>
  <? endif; ?>
  <div class="row">
    <div class="medium-9 medium-offset-3 columns">
      <input class="button secondary small" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
    </div>
  </div>
</form>

<?
  $script = <<<JS
  $('button.button.hide').removeClass('hide');
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
<!-- cart - SAVE.phtml end -->