<!-- START of: finna - ajax/feed-carousel-item.phtml -->
<?php
  $clickableElement = !$this->touchDevice && !$this->$hasLinkText;
  $clickableLink = !$clickableElement;
  $hasIcon = !empty($item['icon']['name']);
  $hasImg = !empty($item['image']['url']);
  $noText = empty($item['text']);
  $displayFormatHeader = $item['displayFormatHeader'];
  $titleBottom = ($item['titlePosition'] === 'bottom');
?>
<?php if ($hasIcon && $hasImg): ?>
  <?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon'], 'wrapper' => true]);?>
<?php endif; ?>
<div aria-hidden="true" class="carousel-text <?php if ($noText): ?>no-text<?php endif; ?>" tabindex="-1">
  <div class="carousel-more carousel-close hidden" aria-hidden="true"><?=$this->icon('carousel-close', 'js-carousel-close')?></div>
  <div class="carousel-more show-link" aria-hidden="true"><?=$this->icon('carousel-follow-link')?></div>
  <?php if (isset($item['title'])): ?>
    <div class="carousel-hover-title">
      <span><?=$this->escapeHtml($this->truncate($item['title'], $item['titleTruncateSize']))?></span>
    </div>
  <?php endif; ?>
  <?php if (isset($item['dateFull'])): ?>
    <span class="carousel-date carousel-hover-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
  <?php endif; ?>
  <div class="text">
    <?php if ($xcal = $item['xcal'] ?? []): ?>
      <?php if (!empty($xcal['startDate'])): ?>
        <?php if ($xcal['singleDay']): ?>
          <p class="xcal"><?=$this->icon('feed-xcal-date') ?><span class="visually-hidden"><?=$this->transEscAttr('xcal_date') ?></span> <?=$this->escapeHtml($xcal['startDate']) ?></div>
          <?php if (!empty($xcal['startTime'])): ?>
            <p class="xcal"><?=$this->icon('feed-xcal-time') ?><span class="visually-hidden"><?=$this->transEscAttr('xcal_time') ?></span> <?=$this->escapeHtml($xcal['startTime']) ?>&nbsp;&ndash;&nbsp;<?=$this->escapeHtml($xcal['endTime'] ?? '') ?></p>
          <?php endif; ?>
        <?php else: ?>
          <p class="xcal"><?=$this->icon('feed-xcal-date') ?><span class="visually-hidden"><?=$this->transEscAttr('xcal_date') ?></span> <?=$this->escapeHtml($xcal['startDate']) ?> &ndash;&nbsp;<?=$this->escapeHtml($xcal['endDate'])?></p>
        <?php endif; ?>
      <?php endif; ?>
      <?php if (!empty($xcal['location'])): ?>
        <p class="xcal"><?=$this->icon('feed-xcal-location') ?><span class="visually-hidden"><?=$this->transEscAttr('Location') ?></span> <?=$this->escapeHtml($xcal['location']) ?></p>
      <?php endif; ?>
    <?php endif; ?>
    <span><?=$this->escapeHtml($item['text'] ?? '') ?></span>
    <?php if ($clickableLink): ?>
      <span class="carousel-description"><?= $linkTextEsc ?></span>
    <?php endif; ?>
  </div>
  <div class="carousel-text-shadow"></div>
</div>
<?php if ($hasImg): ?>
  <div class="wrapper <?= isset($item['format']) ? 'iconlabel format-feed-' . preg_replace('/[^a-z0-9]/', '', strtolower($item['format'])) : ''; ?>" aria-hidden="true">
    <img data-src="<?=$this->escapeHtmlAttr($item['image']['url']) ?>" alt="">
  </div>
<?php endif; ?>
<?php if (isset($item['title']) || isset($item['dateFull'])): ?>
  <div class="carousel-slide-header<?php if ($titleBottom): ?> carousel-slide-header-bottom<?php endif; ?>">
    <span>
      <?php if ($hasIcon && !$hasImg): ?><?=$this->partial('Helpers/feed-icon.phtml', ['icon' => $item['icon']]);?><?php endif; ?>
      <?php if (isset($item['title'])): ?>
        <span class="carousel-header-title"><?=$this->escapeHtml($this->truncate($item['title'], $item['titleTruncateSize']));?></span>
      <?php endif; ?>
      <?php if (isset($item['format']) && $displayFormatHeader): ?>
          <span class="carousel-header-format"><?=$this->transEscWithPrefix('format_', $item['format']);?></span>
      <?php endif; ?>
      <?php if (isset($item['dateFull'])): ?>
        <span class="carousel-header-date carousel-date"><?=$this->transEsc('Published')?> <?=$this->escapeHtml($item['dateFull'])?></span>
      <?php endif; ?>
      <span class="carousel-slide-more carousel-show hidden"><?=$this->icon('carousel-show')?></span>
      <span class="carousel-slide-more carousel-close hidden"><?=$this->icon('carousel-close')?></span>
    </span>
  </div>
<?php endif; ?>
<!-- END of: finna - ajax/feed-carousel-item.phtml -->
