<!-- START of: finna - ajax/feed-grid.phtml -->
<div class="feed-grid<?= $this->images ? ' with-image' : ''; ?>">
  <?php
    $itemCount = 0;
  ?>
  <?php foreach($items as $item): ?>
    <?php
      $linkElement = [
      'href' => $item['link'] . ($this->feedUrl ? '?feedUrl=' . urlencode($this->feedUrl) : '')
      ];
      if ($this->linkTarget) {
        $linkElement['target'] = $this->linkTarget;
      }
      if ($item['modal']) {
        $linkElement['data-lightbox'] = '';
        $linkElement['data-lightbox-title'] = $item['title'];
      }
    ?>
    <div class="grid-item <?= isset($this->visualItems) ? ($itemCount++ >= $this->visualItems ? 'hidden truncate' : '') : ''; ?> ">
      <a class="grid-link" <?= $this->htmlElement()->getAttributes($linkElement);?>>
        <?php if (isset($item['image']) && isset($item['image']['url'])): ?>
          <span class="grid-image <?= empty($item['image']['url']) ? 'no-image' : ''; ?>">
            <?php if (!empty($item['image']['url'])): ?>
              <img src="<?= $item['image']['url']; ?>" alt="" />
            <?php else: ?>
              <i class="fa fa-calendar-o image-placeholder"></i>
            <?php endif; ?>
          </span>
        <?php endif; ?>
        <span class="grid-info">
          <?php if (isset($item['dateFull'])): ?>
            <div><?= $item['dateFull'] ?></div>
          <?php endif; ?>
          <div class="title"><?= $this->truncate($item['title'], 40); ?></div>
          <?php if (isset($item['xcal']['startDate'])): ?>
            <div class="xcal"><i class="fa fa-calendar" aria-label="<?= $this->transEsc('xcal_date') ?>"></i><?= $item['xcal']['startDate']; ?><?php if (isset($item['xcal']['endDate']) && $item['xcal']['endDate'] !== $item['xcal']['startDate']): ?>&nbsp;&ndash;&nbsp;<?= $item['xcal']['endDate']; endif; ?></div>
          <?php endif; ?>
          <?php if (isset($item['xcal']['startTime']) && ((isset($item['xcal']['startDate']) && isset($item['xcal']['endDate']) && $item['xcal']['startDate'] === $item['xcal']['endDate']) || empty($item['xcal']['endDate']))): ?>
            <div class="xcal"><i class="fa fa-clock-o" aria-label="<?= $this->transEsc('xcal_time') ?>"></i><?= $item['xcal']['startTime'] ?><?php if (isset($item['xcal']['endTime'])): ?>&nbsp;&ndash;&nbsp;<?= $item['xcal']['endTime'] ?><?php endif; ?></div>
          <?php endif; ?>
          <?php if (isset($item['xcal']['location']) && !empty($item['xcal']['location'])): ?>
            <div class="xcal"><i class="fa fa-map-marker" aria-label="<?= $this->transEsc('Location') ?>"></i><?= $item['xcal']['location'] ?></div>
          <?php endif; ?>
          <?php if (isset($item['text'])): ?>
            <div class="feed-text"><?= $this->truncate($item['text'], 80); ?></div>
          <?php endif; ?>
        </span>
      </a>
    </div>
  <?php endforeach; ?>
</div>
<button class="btn btn-primary show-more-feeds hidden"><?= $this->translate('show_more') ?></button>
<button class="btn btn-primary show-less-feeds hidden"><?= $this->translate('show_less') ?></button>
<!-- END of: finna - ajax/feed-grid.phtml -->
