<!-- START of: finna - ajax/resolverLinks.phtml -->
<div>
  <?php if (!empty($this->electronic)): ?>
    <div class="openurls">
      <ul>
        <?php foreach ($this->electronic as $link): ?>
          <li>
            <?php if (!empty($link['href'])): ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-' . $link['access'] . '"':''?> target="_blank"><i class="fa fa-external-link"></i> <?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            <?php else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?>
            <?php endif; ?>
            <?=$this->context($this)->renderInContext('ajax/resolverLinksCoverage.phtml', ['link' => $link]); ?>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif; ?>
  <?php if (!empty($this->print) && $this->searchClassId != 'Primo'): ?>
    <div class="openurls">
      <ul>
        <?php foreach ($this->print as $link): ?>
          <li>
            <?php if (!empty($link['href'])): ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-' . $link['access'] . '"':''?> target="_blank"><i class="fa fa-external-link"></i> <?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            <?php else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?>
            <?php endif; ?>
            <?=$this->context($this)->renderInContext('ajax/resolverLinksCoverage.phtml', ['link' => $link]); ?>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  <?php endif; ?>
  <div class="openurls more-options hidden-print">
    <?php if (!empty($this->moreOptionsLink)): ?><a href="<?=$this->escapeHtmlAttr($this->moreOptionsLink)?>" target="_blank"><?=$this->transEsc('More options')?></a> <i class="fa fa-new-window" aria-hidden="true"></i><?php endif; ?>
  </div>
</div>
<!-- END of: finna - ajax/resolverLinks.phtml -->
