<!-- START of: finna - ajax/status-full.phtml -->
<?php
$id = $this->statusItems[0]['id'];
$driver = $this->record($id)->getDriver();
$source = $driver ? $driver->tryMethod('getDataSource') : '';
$locations = false;
$holdings = $this->statusItems;
$summary = array_pop($holdings);
$onlyUnknownStatuses = true;
$holdingsConfig = $this->ils()->getConfig('Holdings', [$id]);
if (($summary['location'] ?? '') === '__HOLDINGSSUMMARYLOCATION__') {
  $itemsTotal = $summary['total'];
  $availableTotal = $summary['available'];
  $reservationsTotal
     = $summary['reservations'] ?? null;
  $orderedTotal
     = $summary['ordered'] ?? null;
  $locations = $summary['locations'] ?? null;
} else {
  $holdings[] = $summary;
}

foreach ($holdings as &$holding) {
  if (!empty($holding['availability']) || empty($holding['use_unknown_message'])) {
    $onlyUnknownStatuses = false;
  }
}
$this->statusItems = $holdings;

$groupBranches = $summary['groupBranches'] ?? isset($this->statusItems[0]['branch']);
$journal = isset($this->statusItems[0]['journalInfo']);

if ($groupBranches) {
  $availableLocations = $closestDueDateInLocation = [];
  $illRequestLink = false;

  foreach ($this->statusItems as $item) {
    if (isset($row['ILLRequestLink']) && $row['ILLRequestLink']) {
      $illRequestLink = $row['ILLRequestLink'];
    }

    if (!empty($item['availability'])) {
      if (empty($availableLocations[$item['location']])) {
        $availableLocations[$item['location']] = 0;
      }
      $availableLocations[$item['location']]++;
    }
    if (!empty($item['duedate'])) {
      $duedate = strtotime($item['duedate']);
      if (empty($closestDueDateInLocation[$item['location']])
      || $duedate < $closestDueDateInLocation[$item['location']]
    ) {
        $closestDueDateInLocation[$item['location']] = $duedate;
      }
    }
  }

  if (!empty($closestDueDateInLocation)) {
    $closestDueDate = date('j.n.Y', min(array_values($closestDueDateInLocation)));
    foreach ($closestDueDateInLocation as &$duedate) {
      $duedate = date('j.n.Y', $duedate);
    }
  }

  $collapseThreshold = $this->holdings()->getCollapseThreshold();
  $collapseLocations = isset($collapseThreshold['location'])
    ? $locations > $collapseThreshold['location'] : null;
  $collapseBranches = isset($collapseThreshold['branch'])
    ? count($this->statusItems) > $collapseThreshold['branch'] : null;
} else {
  // Group holdings by location
  $statusItemsFiltered = [];
  foreach ($this->statusItems as $item) {
    $location = $item['location'];
    if (!isset($statusItemsFiltered[$location])) {
      $statusItemsFiltered[$location] = $item;
    } else {
      if (!empty($item['callnumber'])
        && !empty($statusItemsFiltered[$location]['callnumber'])
        && $item['callnumber'] != $statusItemsFiltered[$location]['callnumber']
      ) {
        $statusItemsFiltered[$location]['callnumbers'] = 'Multiple Locations';
      }
      if ($item['availability'] > $statusItemsFiltered[$location]['availability']) {
        // Copy keys one by one so as to not overwrite callnumbers or any other existing field
        foreach (array_keys($item) as $key) {
          $statusItemsFiltered[$location][$key] = $item[$key];
        }
      }
    }
  }
  $this->statusItems = array_values($statusItemsFiltered);
  if ($this->holdings()->overrideSortOrder()) {
    $items = $this->statusItems;
    usort($items, function ($a, $b) {
      if ($a['availability'] != $b['availability']) {
        return $a['availability'] ? -1 : 1;
      } else {
        return strcasecmp($a['location'], $b['location']);
      }
    });
    $this->statusItems = $items;
  }
}
?>

<?php if ($groupBranches): ?>
  <div class="holdings-container root <?=$collapseLocations ? ' collapsible' : ''?>">
    <div class="header<?=!empty($availableTotal) ? ' available' : ''?> clearfix">
      <i class="fa fa-<?=!empty($availableTotal) ? 'ok' : 'remove'?>"></i>
      <span>
        <?php if (!empty($availableTotal)): ?>
          <?=sprintf('%s %d %s', $this->transEsc('axiell_available'), $availableTotal, $this->transEsc($journal ? 'axiell_issues' : 'axiell_branches'));?>
        <?php elseif (!empty($closestDueDate)): ?>
          <?=sprintf('%s %s %s', $this->transEsc('status_Charged'), $this->transEsc('Due Date'), $closestDueDate);?>
        <?php elseif ($orderedTotal): ?>
          <?=$this->transEsc('status_Ordered')?>
        <?php else: ?>
          <?=$this->transEsc('status_Charged')?>
        <?php endif; ?>
      </span>
      <?php if ($collapseLocations): ?><i class="fa fa-arrow-down arrow down"></i><?php endif; ?>
      <?php if (!$journal): ?>
        <span class="info">
          <?php if (!empty($reservationsTotal)): ?>
            <span class="reservations"><?=$this->translate('status_requests_html', ['%%count%%' => $reservationsTotal]);?></span>
          <?php endif; ?>
          <?php if (!empty($itemsTotal) && (!isset($holdingsConfig['display_total_item_count_in_results']) || $holdingsConfig['display_total_item_count_in_results'])): ?>
            <span class="total"><?=$this->translate('status_items_total_html', ['%%count%%' => $itemsTotal]);?></span>
          <?php endif; ?>
        </span>
      <?php endif; ?>
    </div>
    <div class="holdings<?=$collapseLocations ? ' collapsed' : ''?> root">
<?php else: ?>
  <div class="header holdings<?=!empty($availableTotal) ? ' available' : ''?> clearfix">
    <div>
    <?php if (!empty($availableTotal)): ?>
      <span class="available-total">
        <i class="fa fa-ok"></i> <span><?=$this->translate('status_items_available_html', ['%%count%%' => $availableTotal])?></span>
      </span>
    <?php endif; ?>
    <span class="info">
      <?php if (!empty($reservationsTotal)): ?>
        <span class="reservations"><?=$this->translate('status_requests_html', ['%%count%%' => $reservationsTotal]);?></span>
      <?php endif; ?>
      <?php if (!empty($itemsTotal) && !empty($holdingsConfig['display_total_item_count_in_results'])): ?>
        <span class="total"><?=$this->translate('status_items_total_html', ['%%count%%' => $itemsTotal]);?></span>
      <?php endif; ?>
    </span>
    </div>
  </div>
  <?php $truncateLimit = $this->holdings()->getTruncateLimit(); ?>
  <div class="holdings<?=!empty($truncateLimit) ? (' truncate-field" data-rows="' . $truncateLimit) : ''?>">
<?php endif; ?>

<?php
$currentLocation = $prevLocation = $currentOrganisation = $prevOrganisation = null;
$currentRow = 0;
foreach ($this->statusItems as $item):
  ++$currentRow;
  $newLocation = false;
  $newOrganisation = false;
  if ($currentLocation != $item['location']) {
    $prevLocation = $currentLocation;
    $currentLocation = $item['location'];
    $newLocation = true;
    if ($groupBranches) {
      $currentRow = 0;
    }
  } elseif ($journal && $currentOrganisation != $item['journalInfo']['location']) {
    $prevOrganisation = $currentOrganisation;
    $currentOrganisation = $item['journalInfo']['location'];
    $newOrganisation = true;
    $currentRow = 0;
  }

  if ($groupBranches && $newLocation && $prevLocation): ?>
    </div></div>
  <?php endif; ?>
  <?php if ($groupBranches && $newLocation): ?>
    <div class="holdings-container<?=$collapseBranches ? ' collapsible' : ''?> clearfix">
      <div class="header">
        <?php if ($collapseBranches): ?><i class="fa fa-arrow-right arrow right"></i><?php endif; ?>
        <?php $locationText = $this->transEscWithPrefix('location_', $item['location']); ?>
        <?php if ($item['locationhref'] ?? false): ?>
          <span class="available-online-links">
            <a href="<?=$this->escapeHtmlAttr($item['locationhref'])?>" target="_blank"><?=$locationText?></a>
          </span>
        <?php else: ?>
          <?=$locationText?>
        <?php endif; ?>
        <?php if ($collapseBranches): ?>
          <span>
            <?php if (!empty($availableLocations[$item['location']])): ?>
              <?=sprintf('(%s %d %s)', $this->transEsc('axiell_available'), $availableLocations[$item['location']], $this->transEsc($journal ? 'axiell_issues' : 'axiell_branches'));?>
            <?php elseif (!empty($closestDueDateInLocation[$item['location']])): ?>
              (<?= str_replace('%%date%%', $closestDueDateInLocation[$item['location']], $this->transEsc('closest_due_date')); ?>)
            <?php else: ?>
              (<?=$this->transEsc('status_' . $item['status'])?>)
            <?php endif; ?>
          </span>
        <?php endif; ?>
        <span class="info text-right"><?=$this->callnumber()->callnumber($source, $driver->getFullTitle(), $item['callnumber'], $item['collection'] ?? null, $item['location'] ?? null, $this->layout()->userLang, 'results')?></span>
      </div>
    <div class="holdings<?=$collapseBranches ? ' collapsible collapsed' : ''?>">
  <?php endif; ?>
  <?php
    $classes = null;
    if (!empty($item['availability'])) {
      $classes = ['ok', 'success'];
    }
    if (!$classes && ($item['use_unknown_message'] ?? false)) {
      $classes = $onlyUnknownStatuses ? ['status-unknown-no-icon warning'] : ['status-unknown', 'warning'];
    }
    if (!$classes) {
      $classes = ['remove', 'error'];
    }
    $locationText = $this->transEscWithPrefix('location_', $item['location']);
    if ($item['locationhref'] ?? false) {
      $locationText = '<span class="available-online-links"><a href="' . $this->escapeHtmlAttr($item['locationhref']) . '" target="_blank">'
        . $locationText . '</a></span>';
    }
    if (!empty($item['department']) && !$groupBranches) {
      $location = '<span class="branch">' . $locationText . '</span>, <span class="department">' . $this->transEsc($item['department']) . '</span>';
    } elseif ($groupBranches) {
      $location = '<span class="branch">' . ($this->transEsc($item['branch']) . '</span>, <span class="department">' . $this->transEsc($item['department']) . '</span>');
    } else {
      $location = '<span class="branch">' . $locationText . '</span>';
    }
  ?>
    <div class="<?=$currentRow % 2 == 0 ? 'even' : 'odd'?> clearfix">
      <div class="<?=$groupBranches ? 'group-location-col' : 'no-branches'?>">
        <div class="groupLocation <?= $prevOrganisation && $newOrganisation ? ' new-organisation' : ''; ?>">
          <i class="fa fa-<?=$classes[0]?> text-<?=$classes[1]?>"></i> <span class="text-<?=$classes[0]?>"><?=$location?></span>
        </div>
      <?php if ($groupBranches): ?>
      </div>
      <div class="group-branches">
          <span class="branchInfo">
          <?php if ($item['availability'] && !empty($item['availabilityInfo']['available'])): ?>
            <?= sprintf('%s: %d', $this->transEsc('Available items'), $item['availabilityInfo']['available']); ?>
          <?php elseif (!empty($item['duedate']) && !$item['availability']): ?>
            <?= str_replace('%%date%%', $item['duedate'], $this->transEsc('closest_due_date')); ?>
          <?php elseif ($item['availabilityInfo']['ordered'] > 0): ?>
            <?= sprintf('%s: %d', $this->transEsc('status_Ordered'), $item['availabilityInfo']['ordered']); ?>
          <?php else: ?>
            <?= $this->transEsc('status_' . $item['availabilityInfo']['displayText']); ?></span>
          <?php endif; ?>
        <?php else: ?>
          <div class="groupCallnumber">
            <?php if (!empty($item['callnumbers'])): ?>
              (<?=$this->transEsc($item['callnumbers'])?>)
            <?php elseif (!empty($item['callnumber'])): ?>
              <?=$this->callnumber()->callnumber($source, $driver->getFullTitle(), $item['callnumber'], $item['collection'] ?? null, $item['location'] ?? null, $this->layout()->userLang, 'results')?>
            <?php endif; ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
<?php endforeach; ?>
  </div>

<?php if ($groupBranches): ?>
</div>
<?php endif; ?>
</div>

<div class="actions">
<?php
$holdingsLink = $this->recordLink()->getUrl($driver);
$disableTitleHold = isset($summary['holdable']) && !$summary['holdable'];

if (!$disableTitleHold
  && ($this->holdings()->showSearchResultsTitleHold() || !empty($holdingsConfig['display_title_hold_in_results']))
  && $driver && $driver->tryMethod('getHoldsAllowed')
) {
    $account = $this->auth()->getManager();
    $offlineMode = $this->ils()->getOfflineMode();
    $ilsLoginAvailable = $this->ils()->loginAvailable();
?>
    <div class="title-hold">
<?php
    if ($account->loginEnabled() && $offlineMode != 'ils-offline' && $ilsLoginAvailable) {
      $logged = $account->isLoggedIn();
      $link = null;
      if (!$logged) {
        $link = $this->escapeHtmlAttr($holdingsLink . '?login=true&catalogLogin=true&target=' . $source);
      } elseif ($journal) {
        $link = $this->escapeHtmlAttr($holdingsLink);
      } else {
        $holdingTitleHold = $driver ? $driver->tryMethod('getRealTimeTitleHold') : false;
        if (!empty($holdingTitleHold)) {
          $link = $this->recordLink()->getRequestUrl($holdingTitleHold);
        }
      }
      if ($link) {
        if ($logged) {
?>
      <a href="<?=$link?>" class="placehold btn btn-primary hidden-print" data-lightbox-title="<?=$this->escapeHtmlAttr($this->translate('title_hold_place') . ': ' . $driver->getTitle()) ?>" data-lightbox><?=$this->transEsc('title_hold_place')?></a>
<?php
        } else {
?>
      <a href="<?=$link?>" class="login btn btn-primary hidden-print" data-lightbox><?=$this->transEsc('title_hold_login')?></a>
<?php
        }
      }
    }
?>
    </div>
<?php
}
?>
<?php if ($this->holdings()->showLinkToRecordPage()): ?>
  <div class="all-holdings">
    <a href="<?=$this->escapeHtmlAttr($holdingsLink)?>"><?=$this->transEsc('See all holdings')?></a>
  </div>
<?php endif; ?>
</div>

<?php if ($driver && $source && $externalInterfaceUrl = $summary['externalInterfaceUrl'] ?? ''):?>
  <?=$this->record($driver)->renderTemplate('external-interface-link.phtml', ['driver' => $driver, 'source' => $source, 'link' => $externalInterfaceUrl ?? ''])?>
<?php endif;?>

<?php
  $js = <<<JS
finna.layout.initTruncate($('.holding-details'));
VuFind.lightbox.bind($('.holding-details'));
JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $js, 'SET');
?>

<!-- END of: finna - ajax/status-full.phtml -->
