<?
  // Set up some convenience variables:
  $id = $this->driver->getUniqueId();
  $source = $this->driver->getResourceSource();
  if (isset($this->list) && is_object($this->list)) {
    $list_id = $this->list->id;
    $user_id = $this->list->user_id;
  } else {
    $list_id = null;
    $user_id = $this->user ? $this->user->id : null;
  }
?>
<div class="row-fluid result<? if($this->driver->supportsAjaxStatus()): ?> ajaxItem<? endif ?>">
  <input type="hidden" value="<?=$id ?>" class="hiddenId"/>
  <div class="span2 text-center">
    <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
      <? if ($summThumb = $this->record($this->driver)->getThumbnail()): ?>
        <img src="<?=$this->escapeHtml($summThumb)?>" class="img-polaroid" alt="<?=$this->transEsc('Cover Image')?>"/>
      <? else: ?>
        <img src="<?=$this->url('cover-unavailable')?>" class="img-polaroid" alt="<?=$this->transEsc('No Cover Image')?>"/>
      <? endif; ?>
    </a>
  </div>
  <div class="span7">
    <div class="resultItemLine1">
      <a href="<?=$this->recordLink()->getUrl($this->driver)?>">
      <?
        $summHighlightedTitle = $this->driver->getHighlightedTitle();
        $summTitle = $this->driver->getTitle();
        if (!empty($summHighlightedTitle)) {
            echo $this->highlight($this->addEllipsis($summHighlightedTitle, $summTitle));
        } else if (!empty($summTitle)) {
            echo $this->escapeHtml($this->truncate($summTitle, 180));
        } else {
            echo $this->transEsc('Title not available');
        }
      ?></a>
    </div>

    <div class="resultItemLine2">
      <? if($this->driver->isCollection()): ?>
        <?=implode('<br/>', $this->driver->getSummary()); ?>
      <? else: ?>
        <? $summAuthor = $this->driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
        <?=$this->transEsc('by')?>
        <a href="<?=$this->record($this->driver)->getLink('author', $summAuthor)?>"><?
          $summHighlightedAuthor = $this->driver->getHighlightedAuthor();
          echo !empty($summHighlightedAuthor)
              ? $this->highlight($summHighlightedAuthor)
              : $this->escapeHtml($summAuthor);
        ?></a>
        <? endif; ?>

        <? $journalTitle = $this->driver->getContainerTitle(); $summDate = $this->driver->getPublicationDates(); ?>
        <? if (!empty($journalTitle)): ?>
          <?=!empty($summAuthor) ? '<br/>' : ''?>
          <?=/* TODO: handle highlighting more elegantly here */ $this->transEsc('Published in') . ' <a href="' . $this->record($this->driver)->getLink('journaltitle', str_replace(array('{{{{START_HILITE}}}}', '{{{{END_HILITE}}}}'), '', $journalTitle)) . '">' . $this->highlight($journalTitle) . '</a>';?>
          <?=!empty($summDate) ? ' (' . $this->escapeHtml($summDate[0]) . ')' : ''?>
        <? elseif (!empty($summDate)): ?>
          <?=!empty($summAuthor) ? '<br/>' : ''?>
          <?=$this->transEsc('Published') . ' ' . $this->escapeHtml($summDate[0])?>
        <? endif; ?>
        <? $summInCollection = $this->driver->getContainingCollections(); if (false && !empty($summInCollection)): ?>
          <? foreach ($summInCollection as $collId => $collText): ?>
            <div>
              <b><?=$this->transEsc("in_collection_label")?></b>
              <a class="collectionLinkText" href="<?=$this->url('collection', array('id' => $collId))?>?recordID=<?=urlencode($this->driver->getUniqueID())?>">
                <?=$this->escapeHtml($collText)?>
              </a>
            </div>
          <? endforeach; ?>
        <? endif; ?>
      <? endif; ?>
    </div>

    <div class="last">
    <? if(!$this->driver->isCollection()) {
        if ($snippet = $this->driver->getHighlightedSnippet()) {
          if (!empty($snippet['caption'])) {
            echo '<strong>' . $this->transEsc($snippet['caption']) . ':</strong> ';
          }
          if (!empty($snippet['snippet'])) {
            echo '<span class="quotestart">&#8220;</span>...' . $this->highlight($snippet['snippet']) . '...<span class="quoteend">&#8221;</span><br/>';
          }
        }
      } ?>
        
    <? $listTags = $this->driver->getTags(
        $list_id, // get tags for all lists if no single list is selected
        $user_id, 'tag'
       );
    ?>
    <? if (count($listTags) > 0): ?>
      <strong><?=$this->transEsc('Your Tags')?>:</strong>
      <? $i = 0; foreach ($listTags as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a><? endforeach; ?>
      <br/>
    <? endif; ?>
    <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
    <? if (count($listNotes) > 0): ?>
      <strong><?=$this->transEsc('Notes')?>:</strong>
      <? if (count($listNotes) > 1): ?><br/><? endif; ?>
      <? foreach ($listNotes as $note): ?>
        <?=$this->escapeHtml($note)?><br/>
      <? endforeach; ?>
    <? endif; ?>
    
    <? if (count($this->lists) > 0): ?>
        <strong><?=$this->transEsc('Saved in')?>:</strong>
        <? $i=0;foreach($this->lists as $current): ?>
            <a href="<?=$this->url('userList', array('id' => $current->id))?>"><?=$current->title?></a><? if($i++ < count($this->lists)-1): ?>,<? endif; ?>
        <? endforeach; ?>
        <br/>
    <? endif; ?>
      <div class="callnumAndLocation">
        <? if ($this->driver->supportsAjaxStatus()): ?>
          <strong class="hideIfDetailed"><?=$this->transEsc('Call Number')?>:</strong>
          <span class="callnumber ajax-availability hide">
            <?=$this->transEsc('Loading')?>...
          </span><br class="hideIfDetailed"/>
          <strong><?=$this->transEsc('Located')?>:</strong>
          <span class="location ajax-availability hide">
            <?=$this->transEsc('Loading')?>...
          </span>
          <div class="locationDetails hide"></div>
        <? else: ?>
          <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
            <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
          <? endif; ?>
        <? endif; ?>
      </div>

      <? /* We need to find out if we're supposed to display an OpenURL link ($openUrlActive),
            but even if we don't plan to display the link, we still want to get the $openUrl
            value for use in generating a COinS (Z3988) tag -- see bottom of file.
          */
        $openUrl = $this->driver->getOpenURL();
        $openUrlActive = $this->driver->openURLActive('results');
        $urls = $this->record($this->driver)->getLinkDetails();
        if ($openUrlActive || !empty($urls)): ?>
        <? if ($openUrlActive): ?>
          <br/>
          <?=$this->openUrl($openUrl)?>
          <? if ($this->driver->replaceURLsWithOpenURL()) $urls = array(); // clear URL list if replace setting is active ?>
        <? endif; ?>
        <? if (!is_array($urls)) $urls = array();
          if(!$this->driver->isCollection()):
            foreach ($urls as $current): ?>
          <? endforeach; ?>
        <? endif; ?>
      <? endif; ?>
      <br/>
      <?=str_replace('class="', 'class="label label-info ', $this->record($this->driver)->getFormatList())?>

      <? if (!$openUrlActive && empty($urls) && $this->driver->supportsAjaxStatus()): ?>
      <span class="status ajax-availability hide"><?=$this->transEsc('Loading')?>...</span>
      <br/><br/>
      <? endif; ?>
      <?=$this->record($this->driver)->getPreviews()?>
    </div>
  </div>

  <div class="span2">
    <i class="icon-edit"></i> <a href="<?=$this->url('myresearch-edit')?>?id=<?=urlencode($id)?>&amp;source=<?=urlencode($source)?><? if (!is_null($list_id)):?>&amp;list_id=<?=urlencode($list_id)?><? endif; ?>" class="edit tool"><?=$this->transEsc('Edit')?></a><br/>
    <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */ 
      $deleteUrl = is_null($list_id)
          ? $this->url('myresearch-favorites')
          : $this->url('userList', array('id' => $list_id));
      $deleteUrl .= '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
    ?>
    <div class="dropdown">
      <i class="icon-trash"></i> <a class="dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="<?=$deleteUrl ?>">
        <?=$this->transEsc('Delete') ?>
      </a>
      <ul class="dropdown-menu" role="menu" aria-labelledby="dLabel">
        <li><a href="<?=$deleteUrl?>&amp;confirm=true" title="<?=$this->transEsc('confirm_delete_brief')?>"><?=$this->transEsc('confirm_dialog_yes')?></a></li>
        <li><a><?=$this->transEsc('confirm_dialog_no')?></a></li>
      </ul>
    </div>
    
  </div>
</div>
<?=$openUrl?'<span class="Z3988" title="'.$this->escapeHtml($openUrl).'"></span>':''?>
