<!-- myresearch - NEWPASSWORD.phtml -->
<?
    // Set up page title:
    $this->headTitle($this->translate('Create New Password'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Create New Password') . '</li>';
?>
<? if ($this->auth()->isLoggedIn()): ?>
  <div class="row">
    <div class="<?=$this->layoutClass('mainbody')?>">
<? endif; ?>

<h2><?=$this->transEsc('Create New Password') ?></h2>
<?=$this->flashmessages() ?>

<? if (!$this->auth()->getManager()->supportsPasswordChange($this->auth_method)): ?>
  <div class="error"><?=$this->transEsc('recovery_new_disabled') ?></div>
<? elseif (!isset($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<? else: ?>
  <form id="newpassword" action="<?=$this->url('myresearch-newpassword') ?>" method="post" data-abide role="form">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->hash) ?>" name="hash"/>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->username) ?>" name="username"/>
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth_method) ?>" name="auth_method"/>
    <?=$this->auth()->getNewPasswordForm() ?>
    <div class="row">
      <div class="medium-9 columns medium-offset-3">
        <?=$this->recaptcha()->html($this->useRecaptcha) ?>
     </div>
      <div class="medium-9 columns medium-offset-3">
        <input class="button small" name="submit" type="submit" role="button" value="<?=$this->transEsc('Submit')?>" />
      </div>
    </div>
  </form>
<? endif; ?>

<? if ($this->auth()->isLoggedIn()): ?>
    </div>
    <div class="<?=$this->layoutClass('sidebar')?>">
      <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'newpassword'))?>
    </div>
  </div>
<? endif; ?>
<!-- myresearch - NEWPASSWORD.phtml end -->