<h1>Որոնման օգտակար խորհուրդներ</h1>

<ul class="HelpMenu">
  <li><a href="#wildcard_searches">Ներդրված նիշերով Որոնումներ</a></li>
  <li><a href="#fuzzy_searches">Անորոշ որոնումներ</a></li>
  <li><a href="#proximity_searches">Հարևանության որոնումներ</a></li>
  <li><a href="#range_searches">Միջակայքի որոնումներ</a></li>
  <li><a href="#boosting_a_term">Տերմինի ակտիվացում</a></li>
  <li><a href="#boolean_operators">Բուլյան օպերատորներ</a>
    <ul>
      <li><a href="#boolean_and">AND</a></li>
      <li><a href="#boolean_plus">+</a></li>
      <li><a href="#boolean_or">OR</a></li>
      <li><a href="#boolean_not">NOT</a></li>
      <li><a href="#boolean_minus">-</a></li>
    </ul>
  </li>
</ul>

<dl class="Content">
  <dt><a id="wildcard_searches"></a>Ներդրված նիշերով Որոնումներ</dt>
  <dd>
    <p>Ըստ մեկ ներդրված նիշի նիշերի որոնում կատարելու համար օգտագործեք <strong>?</strong> նշանը։</p>
    <p>Օրինակ, փնտրելու համար "woman" կամ "women" կարող եք օգտագործել որոնումը:</p>
    <pre class="code">wom?n</pre>
    <p>Բազմանիշ, 0 կամ ավելի, ներդրված նիշերի որոնում կատարելու համար օգտագործեք <strong>*</strong> նշանը։</p>
    <p>Օրինակ, փնտրելու համար test, tests կամ tester, կարող եք օգտագործել որոնումը: </p>
    <pre class="code">test*</pre>
    <p>Դուք կարող եք նաև օգտագործել նիշերի որոնումները տերմինի մեջտեղում:</p>
    <pre class="code">te*t</pre>
    <p>Նշում: Չեք կարող օգտագործել * կամ ? նիշը որպես որոնման առաջին նիշ:</p>
  </dd>

  <dt><a id="fuzzy_searches"></a>Անորոշ որոնումներ</dt>
  <dd>
    <p>Օգտագորխեք տիլդան <strong>~</strong> այս բառի վերջում <strong>Միայնակ</strong>։ Օրինակ, որոնել տարբեր ուղղագրությունները "Tchaikovsky," օգտագործեք անորոշ որոնումը։ </p>
    <pre class="code">Tchaikovsky~</pre>
    <p>Լրացուցիչ պարամետրը կարող է սահմանել պահանջվող նմանությունը: Արժեքը 0-ի և 1-ի միջև է, իսկ 1-ին մոտ արժեքի դեպքում կհամընկնեն միայն ավելի մեծ նմանությամբ տերմինները: Օրինակ:</p>
    <pre class="code">Tchaikovsky~0.8</pre>
    <p>Լռելյայն, որն օգտագործվում է, եթե պարամետրը տրված չէ, 0.5 է:</p>
  </dd>

  <dt><a id="proximity_searches"></a>Հարևանության որոնումներ</dt>
  <dd>
    <p>
      Օգտագորխեք տիլդան <strong>~</strong> այս բառի վերջում <strong>Բազմաթիվ</strong>։
      Օրինակ, որոնել economics և keynes որոնց միջև հեռավորությունը 10 բառի սահմաններում է:
    </p>
    <pre class="code">"economics Keynes"~10</pre>
  </dd>

  <dt><a id="range_searches"></a>Միջակայքի որոնումներ</dt>
  <dd>
    <p>
      Միջակայքի որոնում կատարելու համար կարող եք օգտագործել <strong>{ }</strong> նիշերը։
      Օրինակ՝ A, B կամ C-ով սկսվող տերմին փնտրելու համար:
    </p>
    <pre class="code">{A ՄԻՆՉԵՒ C}</pre>
    <p>
     Նույնը կարելի է անել թվային դաշտերի հետ, ինչպիսիք է Տարին.
    </p>
    <pre class="code">[2002 ՄԻՆՉԵՒ 2003]</pre>
  </dd>

  <dt><a id="boosting_a_term"></a>Տերմինի ակտիվացում</dt>
  <dd>
    <p>
      Տերմինին ավելի մեծ արժեք տալու համար կարող եք օգտագործել <strong>^</strong> նիշը։
      Օրինակ, կարող եք փորձել հետևյալ որոնումը.
    </p>
    <pre class="code">economics Keynes^5</pre>
    <p>Ինչն ավելի մեծ արժեք կտա "Keynes" տերմինին</p>
  </dd>

  <dt><a id="boolean_operators"></a>Բուլյան օպերատորներ</dt>
  <dd>
    <p>
      Բուլյան օպերատորները թույլ են տալիս տերմինները զուգակցել տրամաբանական օպերատորների հետ:
      Թույլատրվում են հետևյալ օպերատորները. <strong>AND</strong>, <strong>+</strong>, <strong>OR</strong>, <strong>NOT</strong> և <strong>-</strong>.
    </p>
    <p>Նշում. Բուլյան օպերատորները պետք է լինեն ԲՈԼՈՐԸ ՄԵԾԱՏԱՌ</p>
    <dl>
      <dt><a id="boolean_and"></a>AND</dt>
      <dd>
        <p>Այս <strong>AND</strong> օպերատորը լռելյայն կապի օպերատորն է: Սա նշանակում է, որ եթե երկու տերմինների միջև չկա բուլյան օպերատոր, ապա օգտագործվում է AND օպերատորը: AND օպերատորը համընկնում է այն գրառումներին, որտեղ երկու տերմիններն էլ առկա են գրառման դաշտի ցանկացած վայրում:</p>
        <p>Այն գրառումները փնտրելու համար, որոնք պարունակում են "economics" և "Keynes" օգտագործեք հարցումը: </p>
        <pre class="code">economics Keynes</pre>
        <p>or</p>
        <pre class="code">economics AND Keynes</pre>
      </dd>
      <dt><a id="boolean_plus"></a>+</dt>
      <dd>
        <p>«+» կամ պահանջվող օպերատորը պահանջում է, որ «+» նիշից հետո տերմինը լինի ինչ-որ տեղ գրառման դաշտում:</p>
        <p>Այն գրառումները փնտրելու համար, որոնք պարունակում են "economics" և կարող է պարունակել "Keynes" օգտագործեք հարցումը:</p>
        <pre class="code">+economics Keynes</pre>
      </dd>
      <dt><a id="boolean_or"></a>OR</dt>
      <dd>
        <p>OR օպերատորը կապում է երկու տերմին և գտնում է համապատասխան գրառում, եթե տերմիններից որևէ մեկը գոյություն ունի գրառումում:</p>
        <p>"economics Keynes" կամ պարզապես "Keynes" պարունակող փաստաթղթեր որոնելու համար օգտագործեք հարցումը.</p>
        <pre class="code">"economics Keynes" OR Keynes</pre>
      </dd>
      <dt><a id="boolean_not"></a>NOT</dt>
      <dd>
        <p>NOT օպերատորը բացառում է այն գրառումները, որոնք պարունակում են NOT-ից հետո տերմինը:</p>
        <p>"economics" պարունակող, բայց "Keynes" չպարունակող փաստաթղթեր փնտրելու համար օգտագործեք հարցումը. </p>
        <pre class="code">economics NOT Keynes</pre>
        <p>Նշում: NOT օպերատորը չի կարող օգտագործվել միայն մեկ տերմինով: Օրինակ, հետևյալ որոնումը արդյունք չի տա.</p>
        <pre class="code">NOT economics</pre>
      </dd>
      <dt><a id="boolean_minus"></a>-</dt>
      <dd>
        <p>Այս <strong>-</strong> կամ արգելել օպերատորի դեպքում, բացառվում են փաստաթղթերը, որոնք պարունակում են «-» նշանից հետո տերմինը:</p>
        <p>"economics" պարունակող, բայց "Keynes" չպարունակող փաստաթղթեր փնտրելու համար օգտագործեք հարցումը. </p>
        <pre class="code">economics -Keynes</pre>
      </dd>
    </dl>
  </dd>
</dl>
