<!-- START of: finna - ajax/resolverLinks.phtml -->
<div>
  <? if (!empty($this->electronic)): ?>
    <div class="openurls">
      <ul>
        <? foreach ($this->electronic as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?> target="_blank"><i class="fa fa-external-link"></i> <?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?>
            <? endif; ?>
            <?=$this->context($this)->renderInContext('ajax/resolverLinksCoverage.phtml', ['link' => $link]); ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>
  <? if (!empty($this->print) && $this->searchClassId != 'Primo'): ?>
    <div class="openurls">
      <ul>
        <? foreach ($this->print as $link): ?>
          <li>
            <? if (!empty($link['href'])): ?>
              <a href="<?=$this->escapeHtmlAttr($link['href'])?>" title="<?=isset($link['service_type'])?$this->escapeHtmlAttr($link['service_type']):''?>"<?=!empty($link['access'])?' class="access-'.$link['access'].'"':''?> target="_blank"><i class="fa fa-external-link"></i> <?=isset($link['title'])?$this->escapeHtml($link['title']):''?></a>
            <? else: ?>
              <?=isset($link['title'])?$this->escapeHtml($link['title']):''?>
            <? endif; ?>
            <?=$this->context($this)->renderInContext('ajax/resolverLinksCoverage.phtml', ['link' => $link]); ?>
          </li>
        <? endforeach; ?>
      </ul>
    </div>
  <? endif; ?>
  <? if (empty($this->electronic) || $this->searchClassId != 'Primo'): ?>
    <div class="openurls more-options hidden-print">
      <a href="<?=$this->escapeHtmlAttr($this->openUrlBase)?>?<?=$this->escapeHtmlAttr($this->openUrl)?>" target="_blank"><?=$this->transEsc('More options')?> <i class="fa fa-new-window"></i></a>
    </div>
 <? endif; ?>
</div>
<!-- END of: finna - ajax/resolverLinks.phtml -->
