<?php $rssItems = $this->tuefind()->getRssNewsEntries();?>
<?php if (count($rssItems) == 0):?>
<h1><?=$this->translate('rss_news_missing')?></h1>
<?php else:?>
    <?php $redirectGroup = 'tuefind-rss-full'; ?>
    <div id="tf-rss-full">
        <?php foreach ($rssItems as $rssItem):?>
            <div class="tf-rss-full-item">
                <h1>
                    <a href="<?=$this->tuefind()->getRedirectUrl($rssItem['link'], $redirectGroup)?>" target="_blank"><img src="<?=$this->tuefind()->getRssFeedIcon($rssItem['tuefind:rss_title'])?>">&nbsp;<?=$rssItem['title']?></a>
                </h1>
                <p>
                    <a href="<?=$this->tuefind()->getRedirectUrl($rssItem['tuefind:rss_url'], $redirectGroup)?>" target="_blank"><?=$rssItem['tuefind:rss_title']?></a>: <?=date('d.m.Y H:i:s', strtotime($rssItem['pubDate']))?>
                </p>
                <?php if (!empty($rssItem['description'])):?>
                    <p>
                        <?=$rssItem['description']?>
                    </p>
                <?php endif;?>
            </div>
        <?php endforeach;?>
    </div>
<?php endif;?>
