<?php $rssItems = $this->tuefind()->getRssNewsEntries($this->rssMaxItems);?>
<?php if (count($rssItems) == 0):?>
    <?=$this->getView()->translate('rss_news_missing')?>
<?php else:?>
    <ul id="tf-rss-short">
        <?php foreach ($rssItems as $rssItem):?>
            <li>
                <a class="tf-rss-short-link-icon" target="_blank" href="<?=$rssItem['tuefind:rss_url']?>" title="<?=$rssItem['tuefind:rss_title']?>"><img src="<?=$this->tuefind()->getRssFeedIcon($rssItem['tuefind:rss_title'])?>" height="16" title="<?=$rssItem['title']?>"/></a>
                <a class="tf-rss-short-link-title" target="_blank" href="<?=$rssItem['link']?>" title="<?=str_replace('"', '&quot;', strip_tags($rssItem['description']))?>"><?=$rssItem['title']?></a>
            </li>
        <?php endforeach;?>
    </ul>
<?php endif;?>