<h1>URL (ID) wurde geändert</h1>
<p>Die von Ihnen angeforderte ID (<?=$this->originalId?>) ist nicht länger gültig, bitte verwenden Sie stattdessen die folgende ID: <a href="<?=$this->recordLinker()->getUrl($this->driver->getUniqueID())?>"><?=$this->driver->getUniqueID()?></a></p>
<p>Diese Benachrichtigung wird voraussichtlich am 1. Januar 2020 deaktiviert. Bitte ändern Sie Ihre alten angepassten ID-Referenzen (z.B. Bookmarks in Ihrem Browser) möglichst zeitnah.</p>
<p>Im Idealfall sollten Sie jedoch gar keine Bookmarks auf IDs erstellen. Stattdessen können Sie sich einloggen und die Datensätze Ihrer Favoritenliste hinzufügen. So wird garantiert, dass Sie von zukünftigen Änderungen nicht betroffen sein werden.</p>
