<!-- START of: finna - navibar.phtml -->
<? $account = $this->auth()->getManager(); ?>
<div class="navbar-header">
  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#header-collapse">
    <span class="sr-only"><?=$this->transEsc('Toggle navigation');?></span>
    <i class="fa fa-bars" aria-hidden="true"></i>
  </button>
  <? if ($this->resolver('navibar-logo.phtml')): ?><a class="navbar-brand" href="<?=$this->url('home')?>"><?=$this->render('navibar-logo.phtml')?><span class="sr-only"><?=$this->transEsc("Home")?></span></a><? endif ?>
</div>
<? if (!isset($this->layout()->renderingError)): ?>
  <div class="collapse navbar-collapse" id="header-collapse">
    <ul role="menubar" class="nav navbar-nav">
      <? foreach ($this->navibar()->getMenuItems($this->layout()->userLang) as $key => $val): ?>
      <? if (count($val['items']) > 1): ?>
      <li role="menuitem" class="dropdown" id="<?= $val['label'] ?>">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-nav-<?=$val['label'] ?>" aria-hidden="true"></i><?= $this->transEsc($val['label']) ?> <b class="caret"></b></a>
        <ul role="presentation" class="dropdown-menu">
          <? foreach ($val['items'] as $itemKey => $itemVal): ?>
          <?
          if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
             continue;
          }
          $url = $itemUrl['url'];
          $target = !empty($itemUrl['target']) ? $itemUrl['target'] : null;
          $label = $itemVal['label'];
          $desc = !empty($itemVal['desc']) ? $itemVal['desc'] : null;
          ?>
          <li role="menuitem">
            <a<?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?=$url?>">
              <div><?= $this->transEsc($label) ?></div>
              <? if ($desc): ?>
              <div class="description" role="note"><?= $this->transEsc($desc) ?></div>
              <? endif; ?>
            </a>
          </li>
          <? endforeach; ?>
        </ul>
      </li>
      <? else:
        $itemVal = $val['items'][0];
        if (!($itemUrl = $this->navibar()->getMenuItemUrl($itemVal))) {
           continue;
        }
        $url = $itemUrl['url'];
        $target = isset($itemUrl['target']) ? $itemUrl['target'] : null;
        $label = $itemVal['label'];
      ?>
      <li><a<?= $target ? ' target="' . $this->escapeHtmlAttr($target) . '"' : ''?> href="<?= $url ?>"><i class="fa fa-nav-<?=$label ?>" aria-hidden="true"></i><?= $this->transEsc($label) ?></a></li>
      <? endif; ?>
      <? endforeach; ?>
    </ul>
    <ul role="menubar" class="nav navbar-nav">
      <? $cart = $this->cart(); if ($cart->isActive()): ?>
        <li id="cartSummary" role="menuitem">
          <a id="cartItems" data-lightbox title="<?=$this->transEsc('View Book Bag')?>" href="<?=$this->url('cart-processor')?>"><i class="fa fa-suitcase" aria-hidden="true"></i> <strong><?=count($cart->getItems())?></strong> <?=$this->transEsc('items')?><?=$cart->isFull() ? ' (' .  $this->transEsc('bookbag_full') . ')' : ''?></a>
        </li>
      <? endif; ?>

      <? if ($this->feedback()->tabEnabled()): ?>
        <li role="menuitem">
        <a id="feedback-link" href="<?=$this->url('feedback-home') ?>"><?=$this->transEsc("Feedback")?></a>
      </li>
      <? endif; ?>

      <? if (isset($this->layout()->themeOptions) && count($this->layout()->themeOptions) > 1): ?>
      <li role="presentation" class="dropdown">
          <form method="post" name="themeForm" id="themeForm">
            <input type="hidden" name="ui"/>
          </form>
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><?=$this->transEsc("Theme")?> <b class="caret"></b></a>
          <ul role="menu" class="dropdown-menu">
            <? foreach ($this->layout()->themeOptions as $current): ?>
              <li role="menuitem"<?=$current['selected'] ? ' class="active"' : ''?>><a href="#" onClick="document.themeForm.ui.value='<?=$this->escapeHtmlAttr($current['name'])?>';document.themeForm.submit()"><?=$this->transEsc($current['desc'])?></a></li>
            <? endforeach; ?>
          </ul>
        </li>
      <? endif; ?>
    </ul>

    <? if (isset($this->layout()->allLangs) && count($this->layout()->allLangs) > 1): ?>
      <? $i = 1;?>
      <? foreach ($this->layout()->allLangs as $langCode => $langName): ?>
      <? if ($this->layout()->userLang != $langCode): ?>
      <ul role="menubar" class="nav navbar-nav language lang-<?=$i;?>">
        <li role="menuitem">
          <a class="preserve-anchor" href="<?=$this->escapeHtmlAttr($this->navibar()->getLanguageUrl($langCode))?>"><?=$this->displayLanguageOption($langName)?></a>
        </li>
      </ul>
      <? $i++; ?>
      <? endif ?>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($template = $this->content()->findTemplateForLng("content/Additions/header-navibar")): ?>
    <ul role="menubar" class="nav navbar-nav">
      <?=$this->render($template)?>
    </ul>
    <? endif; ?>

  </div>
  <? //hide login/logout if unavailable ?>
  <? if (is_object($account) && $account->loginEnabled()): ?>
  <ul role="menu" class="nav navbar-nav nav-absolute">
    <? $user = $account->isLoggedIn(); ?>
    <li role="menuitem" class="logoutOptions<? if (!$user): ?> hidden<? endif ?>">
      <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i> <span class="username"><?=$user ? $this->escapeHtml($this->truncate($user->getDisplayName(), 20)) : $this->transEsc("Your Account")?></span> <b class="caret"></b></a>
      <ul role="menu" class="dropdown-menu">
        <li role="menuitem" class="logoutOptions<? if (!$user): ?> hidden<? endif ?>">
          <a href="<?=$this->url('myresearch-home', array(), array('query' => array('redirect' => 0)))?>" title="<?=$this->transEsc("Your Account")?>"><strong><i class="fa fa-user" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></strong><div class="description"><?=$this->transEsc("your_account_info")?></div></a>
        </li>
        <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $user, 'loginMenu' => 'true'));?>
        <li role="menuitem" class="logoutOptions<? if (!$user): ?> hidden<? endif ?>">
          <? $logoutClass = $this->personaAuth()->getUser() === null ? '' : ' persona-logout' ?>
          <a href="<?=$this->url('myresearch-logout')?>" class="logout<?=$logoutClass?>" title="<?=$this->transEsc("Log Out")?>"><strong><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></strong></a>
        </li>
      </ul>
    </li>
    <li role="menuitem" id="loginOptions"<? if($account->isLoggedIn()): ?> class="hidden"<? endif ?>>
      <? if ($sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
      <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
      <? else: ?>
        <? if ($this->templateDir === 'myresearch' && $this->templateName === 'login'): ?>
            <a title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
        <? else: ?>
            <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox data-lightbox-onclose="window.location.href='<?=$this->escapeHtmlAttr($this->url('myresearch-home')) ?>'" title="<?=$this->transEsc("Login")?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
        <? endif; ?>
      <? endif; ?>
    </li>
  </ul>
  <? endif; ?>
<? endif; ?>
<!-- END of: finna - navibar.phtml -->
