<!-- START of: finna - navibar-logo.phtml -->
<? if ($srcUrl = $this->imageSrc('finna-logo_' . $this->layout()->userLang)): ?>
  <div class="navbar-lang-logo">
    <div class="logo-wrapper">
      <img src="<?=$srcUrl; ?>" alt="Logo" />
    </div>
  </div>
<? else: ?>
  <!--<i class="fa fa-finnalogo navbar-logo"></i>-->
  <i class="fa fa-home"></i>
<? endif; ?>
<!-- END of: finna - navibar-logo.phtml -->
