<?php
  $this->parentNodeId ??= '';
  $nodeId = 0;

  // Set things up for faster iteration:
  $icons = [
    'hierarchy-collection' => $this->icon('hierarchy-collection'),
    'hierarchy-record' => $this->icon('hierarchy-record'),
    'hierarchy-expand' => $this->icon('hierarchy-expand', 'hierarchy-tree__expand'),
    'hierarchy-collapse' => $this->icon('hierarchy-collapse', 'hierarchy-tree__collapse'),
  ];
  $buttonAttrs = $this->htmlAttributes([
    'class' => 'hierarchy-tree__toggle-expanded js-toggle-expanded',
  ]);

  $aAttrs = $this->htmlAttributes([
    'class' => 'js-record-link',
    'data-lightbox-ignore' => null,
  ]);

?>
<?php foreach ($nodes as $node): ?>
  <?php
    $hasChildren = !empty($node->children);
    $liClasses = [];
    if ($hasChildren) {
      $liClasses[] = 'hierarchy-tree__parent';
    }
    if ('collection' === $node->type) {
      $liClasses[] = 'hierarchy-tree__collection';
      $icon = 'hierarchy-collection';
    } else {
      $liClasses[] = 'hierarchy-tree__record';
      $icon = 'hierarchy-record';
    }
    if ($selectedID === $node->id) {
      $liClasses[] = 'hierarchy-tree__selected';
    }
    $liAttrs = $liClasses ? ' class="' . implode(' ', $liClasses) . '"' : '';

    // Use node title as button label so that a screen reader can read it as
    // "Expanded <text>" or "Collapsed <text>":
    $buttonLabel = $this->escapeHtml($node->title);
  ?>

  <?php ob_start(); ?>
    <?php
      // Render the item first so that we can use it in two alternative cases:
      $aAttrs->set([
        'name' => 'tree-' . preg_replace('/\W/', '-', $node->id),
        'href' => $node->href,
        'title' => $node->title,
        'data-record-id' => $node->id,
      ]);
    ?>
    <span class="hierarchy-tree__item-container">
      <?=$icons[$icon]?>
      <a<?=$aAttrs?>>
        <?=$this->truncate($node->title, 100)?>
      </a>
    </span>
  <?php $itemHtml = ob_get_clean(); ?>

  <?php if ($hasChildren): ?>
    <li<?=$liAttrs?>>
      <?php
        ++$nodeId;
        $childUlId = 'hierarchy_' . $context . '_' . $this->parentNodeId . '_' . $nodeId;
        $buttonAttrs->set([
            'class' => 'hierarchy-tree__toggle-expanded js-toggle-expanded',
            'aria-expanded' => $node->hasSelectedChild ? 'true' : 'false',
            'aria-controls' => $childUlId,
            'aria-label' => $buttonLabel,
            'data-toggle-aria-expanded' => '',
            'data-default-expanded' => $node->hasSelectedChild ? 'true' : 'false',
        ]);
      ?>
      <button<?=$buttonAttrs?>>
        <?=$icons['hierarchy-expand']?>
        <?=$icons['hierarchy-collapse']?>
      </button>

      <?=$itemHtml?>
      <?php
        $params = compact('context', 'hierarchyID', 'driver', 'selectedID');
        $params['nodes'] = $node->children;
      ?>
      <ul class="hierarchy-tree__children">
        <?=$this->render('hierarchy/tree-level.phtml', $params)?>
      </ul>
    </li>
  <?php else: ?>
    <li<?=$liAttrs?>>
      <button class="hierarchy-tree__toggle-expanded" disabled aria-label="<?=$this->transEscAttr($buttonLabel)?>"></button>
      <?=$itemHtml?>
    </li>
  <?php endif; ?>
<?php endforeach; ?>
