<?php
  $this->parentNodeId ??= '';
  $nodeId = 0;
?>
<?php foreach ($nodes as $node): ?>
  <?php
    $hasChildren = !empty($node->children);
    $liAttrs = $this->htmlAttributes();
    if ($hasChildren) {
      $liAttrs->add('class', 'hierarchy-tree__parent');
    }
    if ('collection' === $node->type) {
      $liAttrs->add('class', 'hierarchy-tree__collection');
      $icon = 'hierarchy-collection';
    } else {
      $liAttrs->add('class', 'hierarchy-tree__record');
      $icon = 'hierarchy-record';
    }
    if ($selectedID === $node->id) {
      $liAttrs->add('class', 'hierarchy-tree__selected');
    }

    // Use node title as button label so that a screen reader can read it as
    // "Expanded <text>" or "Collapsed <text>":
    $buttonLabel = $this->escapeHtml($node->title);
  ?>

  <?php ob_start(); ?>
    <?php
      // Render the item first so that we can use it in two alternative cases:
      $aAttrs = $this->htmlAttributes([
        'class' => 'js-record-link',
        'name' => 'tree-' . preg_replace('/\W/', '-', $node->id),
        'href' => $node->href,
        'title' => $node->title,
        'data-lightbox-ignore' => null,
        'data-record-id' => $node->id,
      ]);
    ?>
    <span class="hierarchy-tree__item-container">
      <?=$this->icon($icon)?>
      <a<?=$aAttrs?>>
        <?=$this->truncate($node->title, 100)?>
      </a>
    </span>
  <?php $itemHtml = ob_get_clean(); ?>

  <?php if ($hasChildren): ?>
    <li<?=$liAttrs?>>
      <?php
        ++$nodeId;
        $childUlId = 'hierarchy_' . $context . '_' . $this->parentNodeId . '_' . $nodeId;
        $buttonAttrs = $this->htmlAttributes(
            [
                'class' => 'hierarchy-tree__toggle-expanded js-toggle-expanded',
                'aria-expanded' => $node->hasSelectedChild ? 'true' : 'false',
                'aria-controls' => $childUlId,
                'aria-label' => $buttonLabel,
                'data-toggle-aria-expanded' => '',
                'data-default-expanded' => $node->hasSelectedChild ? 'true' : 'false',
            ]
        );
      ?>
      <button<?=$buttonAttrs?>>
        <?=$this->icon('hierarchy-expand', 'hierarchy-tree__expand')?>
        <?=$this->icon('hierarchy-collapse', 'hierarchy-tree__collapse')?>
      </button>

      <?=$itemHtml?>
      <?php
        $params = compact('context', 'hierarchyID', 'driver', 'selectedID');
        $params['nodes'] = $node->children;
      ?>
      <ul class="hierarchy-tree__children">
        <?=$this->render('hierarchy/tree-level.phtml', $params)?>
      </ul>
    </li>
  <?php else: ?>
    <li<?=$liAttrs?>>
      <button class="hierarchy-tree__toggle-expanded" disabled aria-label="<?=$this->transEscAttr($buttonLabel)?>"></button>
      <?=$itemHtml?>
    </li>
  <?php endif; ?>
<?php endforeach; ?>
