<h2><?=$this->transEsc('Similar Items')?></h2>
<?php $similarRecords = $this->related->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <ul class="list-group">
    <?php foreach ($similarRecords as $data): ?>
      <li class="list-group-item">
        <?php $formats = $data->getFormats(); ?>
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($data))?>" class="related__title">
          <i class="related__icon fa fa-x<?php if (count($formats) > 0): ?> fa-<?=preg_replace('/[^a-z0-9]/', '', strtolower($formats[0]))?>" title="<?=$formats[0] ?><?php endif; ?>"></i>
          <?=$this->escapeHtml($data->getTitle())?>
        </a>
        <?php $authors = $data->getPrimaryAuthors(); if (!empty($authors)): ?>
          <br/><?=$this->transEsc('by')?>: <?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
        <?php endif; ?>
        <?php $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
        <?php endif; ?>
      </li>
    <?php endforeach; ?>
  </ul>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
