<!-- TueFind extension template -->
<!-- About -->
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown"  href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-info-circle"> </i>
        <?=$this->transEsc('Infos');?> <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="<?=$this->url('help-home')?>?topic=search" data-lightbox><?= $this->transEsc('Search Tips') ?></a></li>
        <li><a class="dropdown-item" href="<?=$this->url('help-faq')?>"><?= $this->transEsc('FAQs') ?></a></li>
    </ul>
</li>
