<!-- TueFind extension template -->
<div class="row">
    <div class="col-xs-12 col-md-6">
        <a target="blank" href="http://www.uni-tuebingen.de"><img src="<?=$this->imageLink('Logo_Universitaet_Tuebingen.svg') ?>" alt="Universit&auml;t T&uuml;bingen" width="269" height="85" style="padding-top: 15px;"/></a>
    </div>
    <div class="col-xs-12 col-md-6">
        <div align="center" style="padding-top: 10px;">
            <a target="_blank" href="http://www.ub.uni-tuebingen.de/"><img src="<?=$this->imageLink('Logo_Universitaetsbibliothek_Tuebingen.svg') ?>" alt="Universitätsbibliothek" width="320" height="30" /></a><br/>
            <a href="/"><img src="<?=$this->imageLink('krimdok.png') ?>" alt="KrimDok" width="195" height="40"/></a><br/>
            <a target="_blank" href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk"><img src="<?=$this->imageLink('ifk.png') ?>" alt="Institut für Kriminologie" width="380" height="27"/></a>
        </div>
    </div>
</div>
