<!-- START of: finna - Recommend/DateRangeVisAjax.phtml -->
<div class="daterange-vis">
  <form action="<?= $this->formAction; ?>" class="year-form">
    <div class="form-ui">
	  <div class="year-range">
      <label for="year-from" class="sr-only"><?=$this->transEsc('year_from');?></label>
	    <input id="year-from" class="form-control form-inline input-year year-from" type="number" value="<?= $this->from; ?>">
	    <span class="year-separator">&ndash;</span>
      <label for="year-to" class="sr-only"><?=$this->transEsc('year_to');?></label>
	    <input id="year-to" class="form-control form-inline input-year year-to" type="number" value="<?= $this->to; ?>">
	  </div>
	  <button class="btn btn-primary submit" type="submit">
      <i class="fa fa-search"></i><span><?= $this->translate($this->submitLabel); ?></span>
    </button>
    </div>
    <div class="content">
      <?php $this->headScript()->appendFile('vendor/jquery.colorhelpers.min.js'); ?>
      <?php $this->headScript()->appendFile('vendor/jquery.flot.min.js'); ?>
      <?php $this->headScript()->appendFile('vendor/jquery.flot.selection.min.js'); ?>
      <?php $this->headScript()->appendFile('finna-daterange-vis.js'); ?>
      <div class="date-vis"></div>
      <i class="fa fa-spinner fa-spin"></i>
    </div>
    <div class="navigation">
      <div class="zoom-in"><i class="fa fa-zoom-in"></i></div>
      <div class="zoom-out"><i class="fa fa-zoom-out"></i></div>
      <div class="prev"><i class="fa fa-arrow-left"></i></div>
      <div class="next"><i class="fa fa-arrow-right"></i></div>
      <div class="expand-modal"><i class="fa fa-expand"></i></div>
    </div>
    <?php if ($backend != 'primo' && (!isset($hideType) || !$hideType)): ?>
    <div class="range-type">
      <label class="radiobutton" for="radio_overlap">
        <input class="timeline_overlap" type="radio" name="type" id="radio_overlap" value="overlap"<?= !$this->type || $this->type == 'overlap' ? ' checked="checked"' : ''; ?>/><?= $this->translate('Timeline overlap'); ?>
      </label>
      <label class="radiobutton" for="radio_within">
        <input class="timeline_within" type="radio" name="type" id="radio_within" value="within"<?= $this->type == 'within' ? ' checked="checked"' : ''; ?>/><?= $this->translate('Timeline within'); ?>
      </label>
    </div>
    <?php endif; ?>
  </form>
</div>
<?php
$script = <<<JS
$(document).ready(function() {
  finna.dateRangeVis.initVis(
      '{$backend}',
      '{$daterangeFacet}',
      '{$searchParams}',
      '{$baseParams}',
      $('.daterange-vis'),
JS;

$script .= isset($this->plotFrom) ? "{$this->plotFrom}," : 'false,';
$script .= isset($this->plotTo) ? "{$this->plotTo}," : 'false,';
$script .= isset($this->plotImmediately) ? "{$this->plotImmediately}" : "false";
$script .= '
  );
});';
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- END of: finna - Recommend/DateRangeVisAjax.phtml -->
