<!-- START of: finna - Recommend/FinnaSuggestionsDeferred.phtml -->
<?php if ($urlParams = $this->recommend->getUrlParams()): ?>
  <?php
    // Set up Javascript for use below:
    $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $urlParams . '";'
      . "VuFind.loadHtml(\$('#finna-suggestions-deferred'), url);";
  ?>
  <div id="finna-suggestions-deferred">
    <p><?=$this->icon('spinner') ?> <?=$this->transEsc('loading_ellipsis')?></p>
    <?=$this->assetManager()->outputInlineScriptString($loadJs)?>
  </div>
<?php endif ?>
<!-- END of: finna - Recommend/FinnaSuggestionsDeferred.phtml -->
