<!-- START of: finna - Recommend/OntologyDeferred.phtml -->
<?php
  $this->headScript()->appendFile('finna-recommendation-memory.js');
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "var deferred = \$('#ontology-recommendations-deferred');"
    . "deferred.load(url, function() {"
    . "finna.layout.initTruncate(deferred);"
    . "});"
?>
<div id="ontology-recommendations-deferred">
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
<!-- END of: finna - Recommend/OntologyDeferred.phtml -->
