<!-- START of: finna - Recommend/SideFacetsDeferred.phtml -->
<?php
  $this->headScript()->appendFile('vendor/jsTree/jstree.min.js');
  $this->headScript()->appendFile('facets.js');
  $this->headScript()->appendFile('vendor/jquery.colorhelpers.min.js');
  $this->headScript()->appendFile('vendor/jquery.flot.min.js');
  $this->headScript()->appendFile('vendor/jquery.flot.selection.min.js');
  $this->headScript()->appendFile('finna-daterange-vis.js');

  $results = $this->recommend->getResults();

  $language = $this->layout()->userLang;

  $this->headScript()->appendFile('vendor/bootstrap-datepicker.min.js');
  $datePickerLang = 'en';

  $datepickerLanguages = ['en-gb' => 'en-GB', 'fi' => 'fi', 'sv' => 'sv'];

  if (array_key_exists($language, $datepickerLanguages)) {
    $datePickerLang = $datepickerLanguages[$language];
    $this->headScript()->appendFile('vendor/bootstrap-datepicker.' . $datePickerLang . '.min.js');
  }

  $resultsTotal = $results->getResultTotal();
?>
<?php if ($resultsTotal > 0): ?>
<div class="side-facets-container-ajax" data-search-class-id="<?=$this->escapeHtmlAttr($this->searchClassId) ?>" data-location="<?=$this->escapeHtmlAttr($this->location) ?>" data-config-index="<?=$this->escapeHtmlAttr($this->configIndex) ?>">
  <h1><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')) ?><?php if (null === $this->slot('side-facet-caption')->get() && !$this->translationEmpty('tooltip_facet_html')): ?><span class="tooltip-facet pull-right" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?=$this->transEsc('tooltip_facet_html')?>"><i class="fa fa-info-big"></i></span><?php endif; ?></h1>
<?php endif; ?>
<?php $checkboxFilters = $results->getParams()->getCheckboxFacets(); ?>
<?php $checkboxesShown = false; ?>
<?php if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($resultsTotal > 0 || $current['selected'] || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?php if ($checkboxesShown): ?>
    <fieldset>
      <legend class="sr-only"><?=$this->transEsc('checkbox_filter')?></legend>
      <div class="checkboxFilter">
        <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results, 'counts' => false]); ?>
      </div>
    </fieldset>
  <?php endif; ?>
<?php endif; ?>
<?php $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets(); ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions(); ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets(); ?>
<?php $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<?php $module = $this->layout()->templateDir; ?>
<?php
  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    $dateRangeFilter = $params->getDateRangeFilter();
  }
?>
<?=$this->context($this)->renderInContext('Recommend/SideFacets/filter-list.phtml', [
    'collapsedFacets' => $collapsedFacets,
    'extraFilters' => $extraFilters,
    'filterList' => $filterList,
    'results' => $results,
    'browse' => !empty($browse),
    'defaultBrowseHandler' => $defaultBrowseHandler ?? ''
]); ?>
<?php
if ($this->fromStreetSearch) {
  if (($key = array_search('geographic_facet', $collapsedFacets)) !== false) {
    unset($collapsedFacets[$key]);
  }
}
?>
<?=isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<?php $activeFacets = $this->recommend->getActiveFacets();
$rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<?php if (!empty($activeFacets) && $resultsTotal > 0): ?>
  <?php
    $msgLoading = $this->transEsc('Loading');
    $msgFailed = $this->transEsc('ajax_load_interrupted');
    $msgExcludeFacet = $this->transEsc('exclude_facet');
  ?>
  <?php foreach ($activeFacets as $title => $facetName): ?>
    <?php
      $allowExclude = $this->recommend->excludeAllowed($title);
      $daterangeFacet = $title == $daterangeFacetField;
      $escTitle = $this->escapeHtml($title);
      $escAttrTitle = $this->escapeHtmlAttr($title);
      $isCollapsed = in_array($title, $collapsedFacets);
      $dataTarget = 'side-collapse-' . $escAttrTitle;
    ?>
    <div class="list-group facet<?= $daterangeFacet ? ' daterange-facet' : '' ?> facet-group" id="side-panel-<?=$escAttrTitle?>">
      <button class="list-group-item title<?= $isCollapsed ? ' collapsed' : '' ?>" data-toggle="collapse" data-target="#<?=$dataTarget?>" aria-owns="<?=$dataTarget?>" aria-expanded="<?= !$isCollapsed ? 'true' : 'false';?>"><?=$this->transEsc($facetName)?></button>
      <div id="<?=$dataTarget?>" class="collapse<?= !$isCollapsed ? ' in' : '';?>" data-facet="<?=$escAttrTitle?>" role="tree" tabindex="0">
        <span class="facet-load-indicator"><i class="fa fa-spinner fa-spin"></i> <?=$msgLoading?>...</span>
        <span class="facet-load-failed hidden"><?=$msgFailed?></span>
        <?php if (in_array($title, $hierarchicalFacets)): ?>
          <div id="facet_<?=$escTitle?>" class="jstree-facet"
            data-facet="<?=$escAttrTitle?>"
            data-path=""
            data-exclude="<?=$allowExclude?>"
            data-operator="<?=$this->recommend->getFacetOperator($title)?>"
            data-exclude-title="<?=$msgExcludeFacet?>"
            data-sort="<?=$hierarchicalFacetSortOptions[$title] ?? ''?>">
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<?php if ($resultsTotal > 0): ?>
  </div>
<?php endif; ?>
<!-- END of: finna - Recommend/SideFacetsDeferred.phtml -->
