<hr/>
<footer class="hidden-print">
  <div class="footer-container">
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Search Options')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
        <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Find More')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('keywordchainsearch-home')?>"><?=$this->transEsc('Browse Keywordchains')?></a></li>
        <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
        <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
        <li><a href="<?=$this->url('search-newitem')?>"><?=$this->transEsc('New Items')?></a></li>
      </ul>
    </div>
    <div class="footer-column">
      <p><strong><?=$this->transEsc('Need Help?')?></strong></p>
      <ul>
        <li><a href="<?=$this->url('help-home')?>?topic=search" data-lightbox class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
        <li><a href="<?=$this->url('acquisitionrequest-create')?>"><?=$this->transEsc('Acquisition Request')?></a></li>
      </ul>
    </div>
  </div>
</footer>
