<div class="background-lightblue">
    <div class="container">
        <div class="row">
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example_externals', null, 'static'); ?>
        </div>
    </div>
</div>

<br />

<div class="background-lightblue">
    <div class="container">
        <div class="row">
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
            <?=$this->HelpText()->render('partials/example', null, 'static'); ?>
        </div>
    </div>
</div>
