<?php
  $transParams = [
    '%%start%%' => $this->localizedNumber($this->results->getStartRecord()),
    '%%end%%'   => $this->localizedNumber($this->results->getEndRecord()),
    '%%total%%' => $this->localizedNumber($this->recordTotal),
    '%%lookfor%%' => $this->escapeHtml($this->lookfor)
  ];
?>
<?php $showingResults = $this->translate('showing_results_of_html', $transParams); ?>
<?php $this->layout()->srmessage = $showingResults; ?>
<?=$showingResults; ?>
