<!-- finc: recordDriver - DefaultRecord - collection-record -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * adds code for responsive data table
configured in: {}
 */
?>
<h2><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h2>
<a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($this->driver))?>"><?=$this->transEsc('View Full ' . ($this->driver->isCollection() ? 'Collection' : 'Record'))?></a>

<?php
  $formatter = $this->recordDataFormatter();
  $fields = $formatter->getData($driver, $formatter->getDefaults('collection-record'));
?>
<?php if (!empty($fields)): ?>
  <?php /* finc: adds code for responsive data table here - CK */ ?>
  <table class="table table-striped table-resp-data">
    <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
    <?php foreach ($fields as $current): ?>
      <tr><th><?=$this->transEsc($current['label'])?>:</th><td data-title="<?= $this->transEscAttr($current['label']) ?>:"><?=$current['value']?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
<!-- finc: recordDriver - DefaultRecord - collection-record - END -->
