<!-- finc: RecordDriver - DefaultRecord - data-hierarchyParentTitle -->
<?php
/**
origin: finc
called by view helper/controller:
usage:
 * Shows parent collection title in RECORD VIEW (left-hand side) under 'Teil von:'
 * Linking to parent title (default by parent-id, if missing by title-string itself)
modified for finc: --
configured in: --
**/
?>
<?php if (!empty($data)): ?>
  <?php $hierarchyParentId = $this->driver->tryMethod('getHierarchyParentID'); ?>
  <?php foreach ($data as $key => $title): ?>
    <?php if (isset($hierarchyParentId[$key])): ?>
      <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($hierarchyParentId[$key], $hierarchyParentId[$key], 'ParentID'));?>"><?=$this->escapeHtml($title)?></a>
    <?php else: ?>
      <?php /* #24409 fallback: if record has no hierarchyParentId start new Series-search on title */ ?>
      <?php $url = $this->url('search-results', [], ['query'=>['type' => 'Series','lookfor' => $title]])?>
      <a href="<?=$url?>"><?=$this->escapeHtml($title)?></a>
    <?php endif; ?>
    <br>
  <?php endforeach; ?>
<?php endif; ?>
<!-- finc: RecordDriver - DefaultRecord - data-hierarchyParentTitle - END -->
