<!-- finc: RecordDriver - DefaultRecord - data-localSignature -->
<?php
/**
origin: finc
called by view helper/controller:
usage:
modified for finc:
configured in: {}
 */
?>
<?php if (!empty($data)): ?>
  <?php foreach ($data as $field): ?>
    <?php if (!empty($field)): ?>
      <?php foreach ($field as $subfield): ?>
        <?=trim($this->escapeHtml($subfield))?>
      <?php endforeach; ?>
    <?php endif; ?>
  <?php endforeach; ?>
<?php endif; ?>
<!-- finc: RecordDriver - DefaultRecord - data-localSignature - END -->
