<!-- finc: RecordDriver - DefaultRecord - format-list -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * most of the template is finc specific
configured in: {}
 */ ?>
<?php
  $formats = $this->driver->getFormats();
  $translated_formats = []; ?>
<?php foreach ($formats as $format): ?>
  <?php
    $translated_formats[] = $translated_format = $this->transEsc($format);
    $formatClass = $this->record($this->driver)->getFormatClass($format);
  ?>
  <?php /* @deprecated: use SideFacets Helper to style language tags, remove when there's a VuFind core solution */ ?>
  <?=$this->sideFacet()->getLanguageTag($translated_format, 'span', $this->layout()->userLang, ["class" => "format $formatClass"]);?>
<?php endforeach; ?>
<!-- finc: RecordDriver - DefaultRecord - format-list - END -->
