<?php
/* use advanced search if we have multiple issns */
if (is_array($this->lookfor) && count($this->lookfor) > 1) {
  $query = '?join=AND&amp;bool0%5B%5D=OR';
  foreach ($this->lookfor as $issn) {
    $query .= '&amp;lookfor0%5B%5D=' . urlencode($issn) . '&amp;type0%5B%5D=ISN';
  }
} elseif (count($this->lookfor) == 1) {
  $query = '?lookfor=%22' . urlencode($this->lookfor[0]) . '%22&amp;type=ISN';
} else {
  $query = '?lookfor=%22' . urlencode($this->lookfor) . '%22&amp;type=ISN';
}
?>
<?=$this->url('search-results') . $query?>
