<?php
return array(
    'extends' => false,
    'helpers' => array(
        'invokables' => array(
            'addellipsis' => 'VuFind\Theme\Root\Helper\AddEllipsis',
            'addthis' => 'VuFind\Theme\Root\Helper\AddThis',
            'auth' => 'VuFind\Theme\Root\Helper\Auth',
            'authornotes' => 'VuFind\Theme\Root\Helper\AuthorNotes',
            'browse' => 'VuFind\Theme\Root\Helper\Browse',
            'cart' => 'VuFind\Theme\Root\Helper\Cart',
            'citation' => 'VuFind\Theme\Root\Helper\Citation',
            'context' => 'VuFind\Theme\Root\Helper\Context',
            'currentpath' => 'VuFind\Theme\Root\Helper\CurrentPath',
            'datetime' => 'VuFind\Theme\Root\Helper\DateTime',
            'displaylanguageoption' => 'VuFind\Theme\Root\Helper\DisplayLanguageOption',
            'excerpt' => 'VuFind\Theme\Root\Helper\Excerpt',
            'flashmessages' => 'VuFind\Theme\Root\Helper\Flashmessages',
            'getlastsearchlink' => 'VuFind\Theme\Root\Helper\GetLastSearchLink',
            'headlink' => 'VuFind\Theme\Root\Helper\HeadLink',
            'headscript' => 'VuFind\Theme\Root\Helper\HeadScript',
            'headthemeresources' => 'VuFind\Theme\Root\Helper\HeadThemeResources',
            'highlight' => 'VuFind\Theme\Root\Helper\Highlight',
            'ils' => 'VuFind\Theme\Root\Helper\Ils',
            'imagelink' => 'VuFind\Theme\Root\Helper\ImageLink',
            'inlinescript' => 'VuFind\Theme\Root\Helper\InlineScript',
            'jqueryvalidation' => 'VuFind\Theme\Root\Helper\JqueryValidation',
            'mobileurl' => 'VuFind\Theme\Root\Helper\MobileUrl',
            'openurl' => 'VuFind\Theme\Root\Helper\OpenUrl',
            'printms' => 'VuFind\Theme\Root\Helper\Printms',
            'proxyurl' => 'VuFind\Theme\Root\Helper\ProxyUrl',
            'recommend' => 'VuFind\Theme\Root\Helper\Recommend',
            'record' => 'VuFind\Theme\Root\Helper\Record',
            'recordlink' => 'VuFind\Theme\Root\Helper\RecordLink',
            'related' => 'VuFind\Theme\Root\Helper\Related',
            'renderarray' => 'VuFind\Theme\Root\Helper\RenderArray',
            'resultfeed' => 'VuFind\Theme\Root\Helper\ResultFeed',
            'reviews' => 'VuFind\Theme\Root\Helper\Reviews',
            'searchoptions' => 'VuFind\Theme\Root\Helper\SearchOptions',
            'safemoneyformat' => 'VuFind\Theme\Root\Helper\SafeMoneyFormat',
            'sortfacetlist' => 'VuFind\Theme\Root\Helper\SortFacetList',
            'summon' => 'VuFind\Theme\Root\Helper\Summon',
            'syndeticsplus' => 'VuFind\Theme\Root\Helper\SyndeticsPlus',
            'systememail' => 'VuFind\Theme\Root\Helper\SystemEmail',
            'transesc' => 'VuFind\Theme\Root\Helper\TransEsc',
            'translate' => 'VuFind\Theme\Root\Helper\Translate',
            'truncate' => 'VuFind\Theme\Root\Helper\Truncate',
            'userlist' => 'VuFind\Theme\Root\Helper\UserList',
            'videoclips' => 'VuFind\Theme\Root\Helper\VideoClips',
        )
    ),
);
