<?=$this->doctype()?>

<html lang="<?=$this->layout()->userLang?>"<?php if ($this->layout()->rtl): ?> dir="rtl"<?php endif; ?>>
<head>
  <?php $this->setupThemeResources(); ?>
  <?php /* finc: removes meta because of W3C Validator error - CK */
  /*  <meta charset="utf-8">  */
  ?>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width,initial-scale=1.0">
  <?=$this->headMeta()?>
  <?php /* finc: translates header title - CK */
  /*
  <?=$this->headTitle()?>
  */ ?>
  <?php
  // finc: Pullrequest 2157 Ticket #20826
  // finc: formats the page title using the translation system:
  $siteConfig = $this->config()->get('config')->Site;
  // finc: disables escaping of title temporarily so that we get it unescaped first:
  $this->headTitle()->setAutoEscape(false);
  $fullTitle = $this->translate(
    'title_wrapper',
    [
      '%%pageTitle%%' => $this->headTitle()->renderTitle(),
      '%%siteTitle%%' => $siteConfig->title,
      '%%titleSeparator%%' => $siteConfig->titleSeparator ?? '::'
    ]
  );
   // finc: enables escaping again for proper output:
  $this->headTitle()->setAutoEscape(true);
  echo $this->headTitle($fullTitle, \Laminas\View\Helper\Placeholder\Container\AbstractContainer::SET);

      // Set up OpenSearch link:
      $this->headLink(
          [
            'href' => $this->url('search-opensearch') . '?method=describe',
            'type' => 'application/opensearchdescription+xml',
            // finc: uses transEscAttr()
            'title' => $this->transEscAttr('Library Catalog Search'),
            'rel' => 'search'
          ]
      );
      // We need to generate the icons early, because they may add some stylesheets;
      // if we render them after the headLink / headStyle calls, some dependencies
      // may not load correctly. Thus, we render early, but use this later.
      $icons = !isset($this->renderingError) ? $this->render('js-icons.phtml') : '{}';
    ?>
    <?php if ($this->layout()->rtl) {
      // RTL styling
      $this->headLink()->appendStylesheet('vendor/bootstrap-rtl.min.css');
    } ?>
    <?php /* finc: adds plugin localization #17850 */ ?>
    <?php
      if (strcmp($this->layout()->userLang, 'de') == 0) {
        $this->headScript()->appendFile('vendor/bootstrap-accessibility-de.min.js');
      } else {
        $this->headScript()->appendFile('vendor/bootstrap-accessibility-en.min.js');
      }
    ?>
    <?=$this->headLink()?>
    <?=$this->headStyle()?>
    <?php
      // Collect small scripts together and append as one block:
      $appendScripts = [];

      if (!isset($this->renderingError)) {
        // Deal with cart stuff:
        $cart = $this->cart();
        if ($cart->isActive()) {
          $this->headScript()->appendFile("vendor/js.cookie.js");
          $this->headScript()->appendFile("cart.js");
          $domain = $cart->getCookieDomain();
          if (!empty($domain)) {
            $appendScripts[] = 'VuFind.cart.setDomain("' . $domain . '");';
          }
          $cookiePath = $cart->getCookiePath();
          if (!empty($cookiePath)) {
            $appendScripts[] = 'VuFind.cart.setCookiePath("' . $cookiePath . '");';
          }
          $cookieSameSite = $cart->getCookieSameSite();
          if (null !== $cookieSameSite) {
            $appendScripts[] = 'VuFind.cart.setCookieSameSite("' . $cookieSameSite . '");';
          }
        }
        $this->headScript()->prependScript(
            'var userIsLoggedIn = ' . ($this->auth()->isLoggedIn() ? 'true' : 'false') . ';'
        );
      }

      // Session keep-alive
      if ($this->keepAlive()) {
          $appendScripts[] = 'var keepAliveInterval = ' . $this->keepAlive() . ';';
          $this->headScript()->appendFile("keep_alive.js");
      }

      // If account ajax is active, load script and add language strings
      $account = $this->auth()->getManager();
      if ($account->ajaxEnabled()) {
        $this->headScript()->appendFile("account_ajax.js");
      }

      $root = rtrim($this->url('home'), '/');
      $translations = !isset($this->renderingError) ? $this->render('js-translations.phtml') : '{}';
      $dsb = DEFAULT_SEARCH_BACKEND;
      $cspNonce = $this->cspNonce();
      $appendScripts[] = <<<JS
VuFind.path = '{$root}';
VuFind.defaultSearchBackend = '{$dsb}';
VuFind.addTranslations({$translations});
VuFind.addIcons({$icons});
VuFind.setCspNonce('{$cspNonce}');
JS;
      $this->headScript()->appendScript(implode("\n", $appendScripts));

    if ($this->config()->ajaxCoversEnabled()) {
        $this->headScript()->appendFile("covers.js");
    }
  ?>
  <?=$this->headScript()?>
</head>
<?php /* finc: accessibility fixes #17720 */ ?>
<?php
$searchType = '';
// finc: to determine the searchtype it is necessary to ask the child model for its searchType
if ($this->layout()->templateName === 'results' && $this->layout()->hasChildren()) {
  try {
      $searchType
          = current($this->layout()->getChildren())->params->getSearchType();
  } catch (\Throwable $t) {
    // ignore all errors
  }
}
?>
<body class="template-dir-<?=$this->templateDir?> template-name-<?=$this->templateName?> <?=$this->layoutClass('offcanvas-row')?><?php if ($this->layout()->rtl): ?> rtl<?php endif; ?><?php if ($searchType == 'advanced'): ?> result-advanced<?php endif; ?>">
<?php // Set up the search box -- there are three possible cases:
// 1. No search box was set; we should default to the normal box
// 2. It was set to false; we should display nothing
// 3. It is set to a custom string; we should display the provided version
// Set up default search box if no data was provided from the template;
// this covers case 1.  Cases 2 and 3 are then covered by logic below.
if (!isset($this->layout()->searchbox)) {
  $this->layout()->searchbox = $this->render('search/searchbox.phtml');
}
?>

<?php /* finc: moves skip links inside header landmark;
         starts header here, not above, custom finc, CK */ ?>
<header class="hidden-print">
  <?php if (isset($this->layout()->srmessage)): // message for benefit of screen-reader users ?>
    <span class="sr-only" role="heading" aria-level="1"><?=$this->layout()->srmessage?></span>
  <?php endif; ?>
  
  <?php /* finc: adds landmark role to avoid 'all content must be inside landmarks error', CK */ ?>
  <div role="navigation" aria-label="<?=$this->transEscAttr('Skip_navigation_links')?>">
    <?php /* finc: shows 'skip to search' link only when page is not an 'advanced' search page, CK */ ?>
    <?php if (strtolower($this->layout()->templateName) !== 'advanced'): ?>
      <a class="sr-only" href="#searchForm_lookfor"><?=$this->transEsc('Skip to search')?></a>
    <?php endif; ?>
    <a class="sr-only" href="#content"><?=$this->transEsc('Skip to content')?></a>
    <?php /* finc: When facets have been selected (in results lists),
           1. show skip links to each selected facet in the side facets area +
           2. show the skip link to facets for selecting more facets +
           3. HIDE skip link to facets on XS because it would point to _inside_ off-canvas;
           for XS, there is a skip link to the 'active filters' box; CK */ ?>

    <?php if (substr_count(strtolower($this->layout()->templateName), 'results') > 0): ?>
      <?php $applied = $this->sideFacet()->getAppliedFacets(); ?>
      <?php if (!empty($applied)): ?>
        <?php foreach ($applied as $appliedId => $appliedText): ?>
          <?php if ($appliedId && $appliedText): ?>
            <?php /* uses css class 'skip-to' to jump to landmark - RL */?>
            <a class="sr-only skip-to hidden-xs" href="#<?=$appliedId?>"><?=$appliedText?></a>
          <?php endif; ?>
        <?php endforeach; ?>
        <a class="sr-only skip-to hidden-sm-up" href="#filters-toggle-items"><?=$this->transEsc('adv_search_filters')?></a>
        
        <?php if (strcmp($this->layout()->userLang, 'de') == 0): ?>
        <a class="sr-only skip-to hidden-xs" href="#control-for-side-collapse-facet_avail"><?=$this->transEsc($this->overrideSideFacetCaption ?? 'Refine Results')?></a>
      <?php else: ?>
        <a class="sr-only skip-to hidden-xs" href="#control-for-side-collapse-facet_avail"><?=$this->transEsc('skip-to')?><?=strtolower($this->transEsc($this->slot('side-facet-caption')->get('Refine Results')))?></a>
      <?php endif; ?>
        
        <?php /* finc: When NO facets have been selected,
                 show skip link to facets but HIDE it on XS because it would point to inside off-canvas;
                 for XS, there is the 'narrow search' button that opens off-canvas, CK */ ?>
      <?php elseif (strcmp($this->layout()->userLang, 'de') == 0): ?>
        <a class="sr-only skip-to hidden-xs" href="#control-for-side-collapse-facet_avail"><?=$this->transEsc($this->overrideSideFacetCaption ?? 'Narrow Search')?></a>
      <?php else: ?>
        <a class="sr-only skip-to hidden-xs" href="#control-for-side-collapse-facet_avail"><?=$this->transEsc('skip-to')?><?=strtolower($this->transEsc($this->slot('side-facet-caption')->get('Narrow Search')))?></a>
      <?php endif; ?>
    <?php endif; ?>
  </div>
  
  <?=$this->render('header.phtml')?>
</header>
<nav class="breadcrumbs" aria-label="<?=$this->transEscAttr('Breadcrumbs')?>">
  <?php /* finc: DOES NOT use '.container' here or the breadcrumbs will get a left+right padding - CK */ ?>
  <?php if ((!isset($this->layout()->showBreadcrumbs) || $this->layout()->showBreadcrumbs == true)
    && !empty($this->layout()->breadcrumbs)
    && $this->layout()->breadcrumbs !== false
  ): ?>
    <?php /* finc: The breadcrumb for the result list after advanced search will also be shown for XS but not with the Start link - #17720 - HR */ ?>
    <ul class="breadcrumb large-centered hidden-xs hidden-print">
      <?php /* finc: adds Home link - #17603 - HR */
            /* Fixme: Home link is already in breadcrumbs/multi.phtml - check functionality - CK */
      ?>
      <li><a href="<?=$this->url('home')?>"><?=$this->transEsc('Home')?></a></li>
      <?php if (is_array($this->layout()->breadcrumbs)): ?>
        <?php if (count($this->layout()->breadcrumbs) > 1): ?>
          <?=$this->render('breadcrumbs/multi.phtml', [
            'parents' => $this->layout()->breadcrumbs,
            'title' => $this->layout()->title,
            'from' => $this->layout()->from
          ])?>
        <?php else: ?>
          <?=$this->render('breadcrumbs/default.phtml', [
            'parents' => $this->layout()->breadcrumbs,
            'title' => $this->layout()->title
          ])?>
        <?php endif; ?>
      <?php else: ?>
        <?=$this->layout()->breadcrumbs?>
      <?php endif; ?>
    </ul>
  <?php endif; ?>
</nav>
<div role="main" class="main">
  <div id="content" class="container">
      <?=$this->layout()->content?>
  </div>
</div>

<?=$this->render('footer.phtml')?>

<!-- MODAL IN CASE WE NEED ONE -->
  <section>
  <?php /* finc: moves X button to logical pos. in structure + uses 'aria-describedby' instead of 'aria-labelledby - CK */ ?>
    <div id="modal" class="modal fade hidden-print" tabindex="-1" role="dialog" aria-modal="true" aria-hidden="true" aria-describedby="modal-description">
      <div class="modal-dialog">
        <div class="modal-content">
          <button type="button" class="close" data-dismiss="modal">
            <svg aria-label="<?=$this->transEscAttr('Close') ?>" viewBox="0 0 24 24"><path d="M6 18L18 6M6 6l12 12"></path></svg>
          </button>
          <?php /* finc: adds div with Modal_description for screenreader #13547 */ ?>
          <div class="sr-only" id="modal-description"><?=$this->transEsc('Modal_description')?></div>
          <div class="modal-body"></div>
        </div>
      </div>
    </div>
  </section>

    <div class="offcanvas-overlay" data-toggle="offcanvas"></div>
    <?=$this->googleanalytics()?>
    <?=$this->piwik()?>
    <?=$this->matomo()?>
    <?php foreach ($this->captcha()->js() as $jsInclude):?>
      <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, $jsInclude, 'SET')?>
    <?php endforeach; ?>
    <?php /* finc: enables tooltips, CK #9844 */ ?>
    <?php
        $tooltipScript = <<<JS
          $(document).ready(function () {
            $("body").tooltip({selector: '[data-toggle=tooltip]'});
          });
    JS;
    ?>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $tooltipScript, 'SET'); ?>
    <?=$this->footScript() ?>
  </body>
</html>
