<h1>Suggerimenti per la ricerca avanzata</h1>

<ul class="HelpMenu">
  <li><a href="#search_fields">Campi di ricerca</a></li>
  <li><a href="#search_groups">Gruppi di ricerca</a></li>
</ul>

<dl class="Content">
  <dt><a id="search_fields"></a>Campi di ricerca</dt>
  <dd>
    <p>La prima volta che vai alla pagina della ricerca avanzata ti si presentano una serie di campi di ricerca.
	In ciascuno di questi puoi digitare le parole chiave della ricerca che ti interessa fare.
	Puoi utilizzare gli <a href="<?=$this->url('help', ['topic' => 'search'])?>">operatori</a>
       di ricerca.</p>
    <p>Ciascun campo &egrave; accompagnato da un menu a tendina che ti permette di specificare il tipo di dato
	(titolo, autore, etc.) che stai cercando. Puoi combinare la ricerca nel modo che preferisci.</p>
    <p>L'opzione "Contiene" ti consente di specificare la gestione dei diversi campi, ad esempio:</p>
    <ul>
      <li>TUTTI i termini -- restituisce solamente i record che corrispondono a tutti i campi di ricerca impostato.</li>
      <li>QUALSIASI termine -- restituisce qualsiasi record che corrisponde almeno a un campo di ricerca.</li>
      <li>NESSUN termine -- restituisce tutti i record fatta eccezione per quelli che corrispondono ai campi impostati.</li>
    </ul>
    <p>La funzionalit&agrave; "Aggiungi campo di ricerca" va utilizzata per aggiungere un ulteriore campo di ricerca.
	Puoi utilizzare quanti campi vuoi.</p>
  </dd>

  <dt><a id="search_groups"></a>Gruppi di ricerca</dt>
  <dd>
    <p>Per alcune ricerche pi&ugrave; complesse potrebbe non bastare un solo set di campi di ricerca.
	Ad esempio, immagina di voler trovare libri sulla storia della Cina o dell'India.
	Utilizzando una ricerca TUTTI i termini per Cina, India e Storia, i risultati saranno solo sulla Cina e sull'India.
	Utilizzando una ricerca QUALSIASI termine, troverai risultati che riguardano la storia, ma non la Cina o l'India.</p>
    <p>I gruppi di ricerca consentono di costruire ricerche a partire da gruppi multipli di campi di ricerca.
	Ogni volta che clicchi su "Aggiungi gruppo" viene aggiunto un gruppo di campi di ricerca.
	Con i gruppi multipli puoi rimuovere iquelli che non utilizzi con la funzione "Rimuovi gruppo di ricerca",
	e puoi speficare se vuoi che la corrispondenza sia con UNO o TUTTI i gruppi.</p>
    <p>Nell'esempio descritto sopra, il problema si risolve utilizzando gruppi di ricerca come questi:</p>
    <ul>
      <li>Nel primo gruppo, inserisci "India" e "Cina" e assicurati che il "Coincide" sia impostato su "QUALSIASI termine".</li>
      <li>Aggiungi un secondo gruppo e inserisci "storia".</li>
      <li>Assicurati che il "Contiene" relativo ai gruppi sia impostato su "ALL Groups". </li>
    </ul>
  </dd>
</dl>
