<?php
  // Set page title.
  $this->headTitle($this->translate('RelBib'));

  // RelBib: Searchbox will always be shown, so do not override it (Part 1)
  // $this->layout()->searchbox = false;

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  $this->layout()->breadcrumbs = false;
?>

<!-- RelBib: Searchbox will always be shown, so do not override it (Part 2) -->

<?=implode('', array_map([$this, 'contentBlock'], $blocks ?? []))?>
