<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#BInL">
            <h4 class="panel-title">
              What does it mean when you find "In:" in a reference?
            </h4>
        </A>
    </div>
    <div id="BInL" class="panel-collapse collapse">
        <div class="panel-body">
          <p> "In:" means that the work is a non-stand-alone article, essay or paper and is to be found "in"
              a larger volume (such as a journal, edited edition or series).
          </p>
        </div>
    </div>
</div>