<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#FS2015">
            <h4 class="panel-title">
              Why do non-German keywords only appear starting in 2015?
            </h4>
        </A>
    </div>
    <div id="FS2015" class="panel-collapse collapse">
        <div class="panel-body">
          <p> No additional keywords are assigned to journal articles which already have authors’ keywords;
            these are adopted in our system. That is why you also find English-language keywords starting in 2015.
          </p>
        </div>
    </div>
</div>