<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#KeineNotationen">
            <h4 class="panel-title">
              Why can’t I find any notation in the new KrimDok?
            </h4>
        </A>
    </div>
    <div id="KeineNotationen" class="panel-collapse collapse">
      <div class="panel-body">
        <p>
          That system came to an end in 2014. There is no more notation as of January 2015. Works published in
          or after 2015 cannot be found using that system. Works published before 2015 can only be found via
          the system if they were purchased by the Criminology information service by the end of 2014
        </p>
      </div>
    </div>
</div>