<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#KWKB">
            <h4 class="panel-title">
                What do I do when I cannot receive a criminological work from any library? 
            </h4>
        </A>
    </div>
    <div id="KWKB" class="panel-collapse collapse">
        <div class="panel-body">
            <p> You can make a purchase request to the Criminology information service. The required form is
                <a href="http://www.ub.uni-tuebingen.de/formulare/av/anschaffungsvorschlag-an-markowsky.html">here</a>.
                The acquisitions profile is
                <a href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk/fidkrim/erwerbungsprofil">here</a>.
            </p>
        </div>
    </div>
</div>