<div class="panel <?=$panelClass;?>">
    <div class="panel-heading">
        <a data-toggle="collapse" href="#SigLN">
            <h4 class="panel-title">
              What do the call numbers mean on each reference?
            </h4>
        </A>
    </div>
    <div id="SigLN" class="panel-collapse collapse">
        <div class="panel-body">
            <p>
              Call numbers starting with “KB” are from the collection of the Criminology information service housed
              in the Tübingen University Library. All other call numbers indicate the Institute of Criminology collection
              at the University of Tübingen. If no call number is indicated, the work referenced is listed in the KrimDok
              database, which is not physically present in Tübingen
            </p>
        </div>
    </div>
</div>