<p>Liebe RelBib Nutzerin, lieber RelBib Nutzer</p>

<p>im Patron Driven Acquisition (PDA) Programm des Fachinformationsdienstes (FID) Religionswissenschaften können Sie die Beschaffung von Büchern veranlassen, die Sie für Ihre Forschung benötigen und bisher noch nicht für die Ausleihe zur Verfügung stehen.</p>

<p>Was sind die nächsten Schritte?</p>
<ol>
    <li>Wir werden nun versuchen, das gewünschte Buch zu erwerben
    <li>Wenn das Buch nicht erworben werden kann, informieren wir Sie per Mail
    <li>Wenn das Buch erworben werden kann, informieren wir Sie über den Eingang des Buches in der UB Tübingen. Sie können dann unmittelbar eine Fernleihbestellung aufgeben.
</ol>
<p>Sie sind nun im Begriff, eine Beschaffung für folgendes Buch auszulösen:</p>
