<h1>RelBib Newsfeed-Aggregator</h1>
<p>Mit dem Newsfeed-Aggregator bieten wir Ihnen eine komfortable Möglichkeit, sich über neue Beiträge aus verschiedenen religionswissenschaftlich relevanten Blogs zu informieren und diese en bloc zu abonnieren.</p>
<p>Kennen Sie weitere interessante und relevante Blogs, die Sie hier vermissen? Gerne dürfen Sie uns diese melden unter: relbib(at)ub.uni-tuebingen.de!</p>
