<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#03_2021"><b>Online-Workshop des FID Religionswissenschaft: Nachlese und Freischaltung der Präsentationen</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#01_2021"><b>FID-Lizenzen: Tester*innen für Datenbank "Jewish Life in America" gesucht!</b></a></li>
		<li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2020"><b>Save the date! Online-Workshop des FID Religionswissenschaft am 20.11.2020</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
