<div id="searchbox_news">
    <h2><?=$this->transEsc('RelBib News')?></h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#12_2021"><b>Neu in RelBib: Normdatensuche und Personenseiten</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#11_2021"><b>RelBib Alerting-Service: Jetzt neu auch Zeitschriftenpakete abonnieren!</b></a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2021"><b>Aufsätze aus Sammelschriften in RelBib</b></a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
