<div id="searchbox_news">
    <h2>Aktuelles in eigener Sache</h2>
    <ul>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#03_2019">03/2019 <b>K10plus</b> – ein Gewinn auch für RelBib</a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#01_2019">01/2019 Weiterförderung des FID Religionswissenschaft</a></li>
        <li><a href="<?=$this->url('content-page', ['page' => 'news'])?>#07_2018">07/2018 Zotero Group: So gelangen Zeitschriftenaufsätze in RelBib</a></li>
    </ul>
    <a href="<?=$this->url('content-page', ['page' => 'news'])?>#archive">Archiv</a>
</div>
