<div class="row">
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//www.uni-tuebingen.de"><img src="<?=$this->imageLink('logo-uni-tuebingen.png') ?>" alt="Universität T&uuml;bingen" width="260"/></a>
    </div>
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//ub.uni-tuebingen.de"><img src="<?=$this->imageLink('unibibliothek.png') ?>" alt="UB" /></a><br/><br/>
        <!-- RelBib: skip theology references-->
    </div>
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//dfg.de"><img src="<?=$this->imageLink('dfg_logo.gif') ?>" alt="DFG" width="250" height="31" /></a>
        <br/>
        <br/>
        <a target="_blank" href="//www.dvrw.uni-hannover.de"><img src="<?=$this->imageLink('dvrw_logo.png') ?>" alt="DVRW" width="250" height="31" /></a>
    </div>
</div>

<br />
