<div class="alert alert-info">
  <div class="text-center">
    <? if ('post' === $this->exportType): ?>
      <form method="POST" action="<?=$this->escapeHtmlAttr($this->url)?>" target="<?=$this->escapeHtmlAttr($this->targetWindow)?>">
        <input type="hidden" name="<?=$this->escapeHtmlAttr($this->postField)?>" value="<?=$this->escapeHtmlAttr($this->postData)?>">
        <?=$this->transEsc('export_success'); ?>&nbsp;&mdash;&nbsp;
        <input class="btn btn-primary" type="submit" name="submit"
          value="<?=$this->escapeHtmlAttr($this->translate('export_redirect', ['%%service%%' => $this->translate($this->export()->getLabelForFormat($this->format))]))?>"
        >
      </form>
    <? else: ?>
      <?=$this->transEsc('export_success'); ?>&nbsp;&mdash;&nbsp;
      <a class="btn btn-primary" href="<?=$this->escapeHtmlAttr($this->url)?>"<?=$this->export()->needsRedirect($this->format) ? ' target="_blank"' : ''?>><?=
          $this->export()->needsRedirect($this->format)
              ? $this->transEsc('export_redirect', ['%%service%%' => $this->translate($this->export()->getLabelForFormat($this->format))])
              : $this->transEsc('export_download')
      ?></a>
    <? endif; ?>
  </div>
</div>
