<div class="list-group">
  <? foreach ($this->data as $item): ?>
    <? $addURL = $this->url('search-results').$this->results->getUrlQuery()->addFacet($this->facet, $item['value'], $item['operator']); ?>
    <a href="<?=$addURL ?>" data-lightbox-ignore class="list-group-item">
      <?=$this->escapeHtml($item['displayText'])?>
      <span class="badge">
        <?=$this->localizedNumber($item['count'])?>
      </span>
    </a>
  <? endforeach; ?>
</div>
<button class="btn btn-default" data-dismiss="modal"><?=$this->translate('close') ?></button>
