<? foreach ($this->driver->getSummary() as $summary): ?>
  <?=$this->escapeHtml($summary) ?><br />
<? endforeach; ?>
<? $isbn = $this->driver->getCleanISBN(); ?>
<? foreach ($this->summaries($isbn) as $provider => $content): ?>
  <? foreach ($content as $summary): ?>
    <? $htmlContent = substr($summary, 0, 1) == '<' && substr($summary, -1) == '>'; ?>
    <?=$htmlContent ? $summary : ($this->escapeHtml($summary) . '<br />')?>
  <? endforeach; ?>
<? endforeach; ?>
