<?php
  $truncateSettings = [
    'rows' => $this->config()->getRecordSubjectLimit(),
    'top-toggle' => 30,
  ];
?>
<div class="truncate-subjects" data-truncate="<?=$this->escapeHtmlAttr(json_encode($truncateSettings))?>">
  <?php foreach ($data as $field): ?>
    <div class="subject-line" property="keywords">
      <?php $subject = ''; ?>
      <?php if(count($field) == 1) $field = explode('--', $field[0]); ?>
      <?php $i = 0; foreach ($field as $subfield): ?>
        <?=($i++ == 0) ? '' : ' &gt; '?>
        <?php $subject = trim($subject . ' ' . $subfield); ?>
        <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow"><?=trim($this->escapeHtml($subfield))?></a>
      <?php endforeach; ?>
    </div>
  <?php endforeach; ?>
</div>
