<?php
$this->headScript()->appendFile('vendor/chart.js');
$this->headScript()->appendFile('explain.js');

$explanation = $this->explanation;
$recordId = $explanation->getRecordId();
$decimalPlaces = $explanation->getDecimalPlaces();
$maxScore = $explanation->getMaxScore();
$totalScore = $explanation->getTotalScore();
$boost = $explanation->getBoost();
$coord = $explanation->getCoord();
$rest = $explanation->getRest();
$restExplanation = $explanation->getExplanationForRest();

$link = $this->recordLinker()->getUrl($this->driver);
?>
<div class="explain">
  <p><?= $this->transEsc('Top Result Relevance')?>: <?= $this->localizedNumber($maxScore, $decimalPlaces) ?></p>
  <h3><?= $this->transEsc('Explanation for search')?>: <?= $explanation->getLookfor() ?></h3>
  <p>
    <?=
      $this->translate('explain_relevance', [
      '%%recordId%%' => '<a href="' . $this->escapeHtmlAttr($link) . '">' . $recordId . '</a>',
      '%%relevanceValue%%' => $this->localizedNumber($totalScore, $decimalPlaces)])
    ?>
    <?php if (isset($coord) || isset($boost)): ?>
      <br>
      <?=
        $this->transEsc('explain_modified_value', [
          '%%relevanceValue%%' => $this->localizedNumber($explanation->getBaseScore(), $decimalPlaces),
        ])
      ?>
    <?php endif;?>

    <?php if (isset($coord)): ?>
      <?=
        $this->transEsc('explain_coord', [
          '%%relevanceValue%%' => $this->localizedNumber($explanation->getBaseScore(), $decimalPlaces),
          '%%coord%%' => $this->localizedNumber($coord['value'], $decimalPlaces),
        ])
      ?>
    <?php endif; ?>

    <?php if (isset($boost)): ?>
      <?=
        $this->transEsc('explain_boost', [
          '%%boost%%' => $this->localizedNumber($boost['value'], $decimalPlaces),
        ])
      ?>
      <br>
      <?=
        $this->transEsc(
            'explain_boost_description',
            [
              '%%boost_description%%' => $boost['description'],
            ]
        )
      ?>
    <?php endif; ?>
  </p>

  <?php
    $shortExplain = [];
    $shortExplainLabels = [];
  ?>
  <table>
  <?php foreach ($explanation->getExplanation() as $explainElement): ?>
    <tr>
      <?php
        $fieldModifier = $explainElement['fieldModifier'] ?? false;
        $shortExplainLabels[] = $explainElement['fieldName']
          . ($fieldModifier ? ('^' . $this->localizedNumber($fieldModifier, $decimalPlaces)) : '')
          . ' (' . $explainElement['fieldValue'] . ')';
        $shortExplain[] = $explainElement['value'];
        $fieldNameKey = $explainElement['fieldName'];
        $fieldName = $this->transEsc('ExplainFieldName::' . $fieldNameKey);
      ?>
      <td class="percentage">
        <?= $this->localizedNumber($explainElement['percent'], $decimalPlaces)?>%
      </td>
      <td>
        <span class="<?= $explainElement['exactMatch'] ? 'exact-match' : 'inexact-match' ?>"><?= $explainElement['fieldValue'] ?>"</span>
        <?= $this->transEsc('in') ?>: <?= $explainElement['fieldName'] ?>
        <?php if ($fieldNameKey !== $fieldName): ?>
          (<?= $fieldName ?>)
        <?php endif; ?>
        <?php if (isset($explainElement['fieldModifier'])): ?>
          , <?= $this->transEsc('explain_modifier', ['%%modifier%%' => $this->localizedNumber($explainElement['fieldModifier'], $decimalPlaces)]) ?>
        <?php endif; ?>
      </td>
    </tr>
    <?php endforeach; ?>
  </table>
  <?php if (!empty($rest) and $rest['percent'] < 99): ?>
    <div class="explain-rest">
      <?php
        $shortExplainLabels[] = 'rest';
        $shortExplain[] = $rest['value'];
      ?>
      <b><?= $this->transEsc('rest') ?></b>
      <table>
        <?php foreach ($restExplanation as $explainElement): ?>
          <tr>
            <?php
              $shortExplainRest[] = [
                $explainElement['fieldName'] . ($explainElement['fieldModifier'] ?? '') . ' (' . $explainElement['fieldValue'] . ')',
                $explainElement['value'],
              ];
              $fieldValueColor = $explainElement['exactMatch'] ? 'black' : '#436c71';
              $fieldNameKey = $explainElement['fieldName'];
              $fieldName = $this->transEsc('ExplainFieldName::' . $fieldNameKey);
            ?>
            <td class="percentage rest-value">
              <?= $this->localizedNumber($explainElement['percent'], $decimalPlaces)?>%
            </td>
            <td>
              <span class="<?= $explainElement['exactMatch'] ? 'exact-match' : 'inexact-match' ?>">"<?= $explainElement['fieldValue'] ?>"</span>
              <?= $this->transEsc('in') ?>: <?= $explainElement['fieldName'] ?>
              <?php if ($fieldNameKey !== $fieldName): ?>
                (<?= $fieldName ?>)
              <?php endif; ?>
            </td>
          </tr>
        <?php endforeach; ?>
        <tr>
          <td class="percentage rest-value sum-rest">
            <?= $this->localizedNumber($rest['percent'], $decimalPlaces) ?>%
          </td>
          <td>
            <?= $this->transEsc('explain_sum') ?>
          </td>
        </tr>
      </table>
      <br>
    </div>
  <?php endif; ?>
  <?php if ($totalScore > 0): ?>
    <?php
      $values = implode(', ', $shortExplain);
      $labels = implode(', ', $shortExplainLabels);
    ?>
    <div class="charts" >
      <?php if(!empty($values) && !empty($labels)): ?>
        <div class="pie-chart-container">
          <canvas id="explain-pie-chart"
             class="explain-chart"
             data-chart-title="<?= $recordId ?>"
             data-chart-labels="<?= $labels ?>"
             data-chart-data="<?= $values ?>"
          ></canvas>
        </div>
      <?php endif; ?>
      <?php if($maxScore > 0): ?>
        <?php
          $data = [
            ['item'],
            [$this->transEsc('Relevance')],
          ];
        ?>
        <br>
        <div class="explain-column-container">
          <canvas id="explain-column-chart"
               class="explain-chart"
               data-chart-title="<?= $this->transEsc('explain_compared', ['%%recordId%%' => $recordId]) ?>"
               data-chart-data="<?= $this->escapeHtmlAttr(json_encode($data)) ?>"
               data-max-score="<?= $maxScore ?>"
               data-score="<?= $totalScore ?>"
          ></canvas>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
</div>
