<tr>
  <td class="percentage">
    <?=$this->localizedNumber($explainElement['percent'], $decimalPlaces)?>%
  </td>
  <td>
    <?php if (!is_array($fieldName)): ?>
    <?php
      $fieldName = [$fieldName];
      $fieldValue = [$fieldValue];
      $explainElement['exactMatch'] = [$explainElement['exactMatch']];
    ?>
    <?php endif; ?>
    <?php if (count($fieldName) > 1):
      echo $this->transEsc('Synonym') . ': [';
    endif;
    for ($i = 0; $i < count($fieldName); $i++):
      $name = $fieldName[$i];
      $value = $fieldValue[$i] ?? '';
      $exactMatch = $explainElement['exactMatch'][$i] ?? '';
      if (!empty($name)) {
        $description = $this->transEsc('IndexFieldDescription::' . $name);
        $description = $name !== $description ? $description : '';
      } else {
        $description = '';
      }
      $exactMatchClass = ($exactMatch ?? 'unkown') . '-match';
      echo '<span class="' . $exactMatchClass . '">"' . $value . '"</span>' . ' ' . $this->transEsc('in');
      echo ' <span class="field-name" title="' . $this->escapeHtmlAttr($description) . '">' . $name . '</span>';
      echo ($i < count($fieldName) - 1) ? ', ' : '';
    endfor;
    $modifier = isset($explainElement['fieldModifier'])
      ? ', ' . $this->transEsc(
          'explain_modifier',
          ['%%modifier%%' => $this->localizedNumber($explainElement['fieldModifier'], $decimalPlaces)]
      )
      : '';
    echo(count($fieldName) > 1 ? ']' : '') . $modifier
    ?>
  </td>
</tr>
