<?php
  $ratingData = $this->driver->getRatingData();
  $translationParams = [
    '%%rating%%' => $this->localizedNumber($ratingData['rating']),
    '%%count%%' => $this->localizedNumber($ratingData['count'])
  ];
?>
<div class="rating">
  <div class="rating-average">
    <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'AddRating'))?>" data-lightbox title="<?=$this->transEscAttr('rating_add_or_update')?>">
      <?=$this->transEsc('rating_heading', $translationParams)?>:
    </a>
    <?=$this->render('Helpers/star-rating.phtml', ['readonly' => true, 'rating' => $ratingData['rating'], 'labelAttrs' => ['data-click-callback="addRecordRating"']]);?>
    <span class="rating-summary">
      <?=$this->transEsc('rating_summary', $translationParams)?>
    </span>
  </div>
</div>
