<!-- START of: finna - list/list.phtml -->
<?
$list = $this->results->getListObject();
// Set up page title:
$this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));
// Set up Finna Main Header:
$this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
    'list/header.phtml', array(
    'lookfor' => $list->title,
    )
);
$this->headScript()->appendFile("finna-item-status.js");
$this->headScript()->prependScript("var listId = {$list->id}; var publicList = 1");
?>
<?= $this->flashmessages() ?>
<div class="clearfix hidden-print">
    <div class="row public-list-row">
      <div class="row">
        <div class="col-sm-12 col-md-10 col-lg-9">
          <div class="public-list-desc col-xs-7 col-sm-8">
            <div class="truncate-field" data-rows="5"><p><?= $this->escapeHtml($list->description) ?></p></div>
          </div>
          <div class="public-list-info col-xs-5 col-sm-4">
            <div>
              <?= $this->transEsc("collection_author"); ?>:
              <span class="public-list-username"><?=$this->escapeHtml(trim($this->userPublicName($this->list_username)))?></span>
            </div>
            <div><?= $this->transEsc("modified"); ?>: <?= $this->DateTime()->convertToDisplayDate('Y-m-d H:i:s', $list->finna_updated ? $list->finna_updated : $list->created); ?></div>
          </div>
        </div>
      </div>
    </div>
</div>
<div class="row">
    <div class="col-sm-12 col-md-10 col-lg-9 search-controls">
        <div class="pull-left">
            <?= $this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', array('results' => $this->results)) ?>
        </div>
        <div class="pull-right hidden-print">
          <?=$this->render('search/controls/view.phtml')?>
          <?=$this->render('search/controls/sort.phtml')?>
          <?=$this->render('search/controls/limit.phtml')?>
        </div>
    </div>
</div>
<div class="row public-list-view">
    <form class="form-inline col-sm-12 col-md-10 col-lg-9" method="post" name="bulkActionForm" action="<?= $this->url('cart-home') ?>">
        <?= $this->context($this)->renderInContext('search/bulk-action-buttons.phtml', array('idPrefix' => '')) ?>
        <?= $this->render('search/list-' . $this->params->getView() . '.phtml') ?>
        <?= $this->context($this)->renderInContext('search/bulk-action-buttons.phtml', array('idPrefix' => 'bottom_')) ?>
    </form>
</div>
</div>
<div class="container-fluid pagination-background">
  <div class="container">
    <div class="col-xs-12 text-center">
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $this->results))?>
    </div>
</div>
<!-- END of: finna - list/list.phtml -->
