<!-- START of: finna - list/list.phtml -->
<?
$list = $this->results->getListObject();
// Set up page title:
$this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));
// Set up Finna Main Header:
$this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
    'list/header.phtml',
    [
        'lookfor' => $list->title,
    ]
);

$this->hideCartControls = true;

$this->headScript()->appendFile("finna-item-status.js");
$this->headScript()->prependScript("var listId = {$list->id}; var publicList = 1");
?>
<?=$this->flashmessages() ?>
<div class="clearfix hidden-print">
    <div class="public-list-row">
      <div class="public-list-desc">
        <?=$this->markdown()->toHtml($list->description) ?>
      </div>
      <div class="public-list-info">
        <div>
          <?= $this->transEsc("collection_author"); ?>:
          <span class="public-list-username"><?=$this->escapeHtml(trim($this->userPublicName($this->list_username)))?></span>
        </div>
        <div><?= $this->transEsc("modified"); ?>: <?=$this->DateTime()->convertToDisplayDate('Y-m-d H:i:s', $list->finna_updated ? $list->finna_updated : $list->created); ?></div>
      </div>
    </div>
</div>
<div class="search-controls">
    <div class="control-container text-right hidden-print">
        <?=$this->render('search/controls/view.phtml')?>
        <?=$this->render('search/controls/sort.phtml')?>
        <?=$this->render('search/controls/limit.phtml')?>
    </div>
    <div class="pagination-container">
        <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results]) ?>
    </div>
</div>
<div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->params->getView())?>">
    <form class="form-inline" method="post" name="bulkActionForm" action="<?= $this->url('cart-home') ?>">
    </form>
      <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => '']) ?>
      <?=$this->render('search/list-' . $this->params->getView() . '.phtml') ?>
      <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => 'bottom_']) ?>
</div>
<div class="container-fluid pagination-background">
  <div class="container">
    <div class="text-center">
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results])?>
    </div>
  </div>
</div>
<? // NOTE: insert extra closing div here to make the RSS-link container 100% wide ?> 
</div>

<div class="container-fluid searchtools-background">
  <div class="container">
    <div class="searchtools hidden-print">
      <? $this->results->getParams()->setPage(1); ?>
      <a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>"><i class="fa fa-bell"></i> <?=$this->transEsc('Get RSS Feed')?></a>
    </div>
  </div>
<? // NOTE: leave out a closing div to compensate for the one added above ?>
<!-- END of: finna - list/list.phtml -->
