<!-- START of: finna - list/list-notes.phtml -->
<? 
  $list = $this->results->getListObject();
  $notes = $this->driver->getListNotes($list->id); if (!empty($notes)): ?>
  <div class="notes">
    <p class="note-heading">
      <span class="heading"><?=$this->transEsc('Description')?></span>
      (<?=$this->escapeHtml(trim($this->userPublicName($this->list_username)))?>):
    </p>
    <p class="note-rows">
      <?
      $note = implode('', $notes);
      if ($this->params->getView() == 'list') {
        $note = preg_replace("/\r\n|\r|\n/",'<br />', $this->escapeHtml($note));
      }
      echo $note
      ?>
    </p>
  </div>
<? endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
