<!-- START of: national - content/about_fi.phtml -->
<? $this->headTitle('Mikä Finna on?'); $this->content()->setHeading('Mikä Finna on?');  ?>
<div class="row">
  <div class="col-xs-12">
    <h2>Finna.fi</h2>
  </div>
</div>
<div class="row">
  <div class="col-sm-5 col-md-4">
    <a href="https://www.finna.fi"><img src="<?=$this->imageLink('finnafi.jpg')?>" alt="finna.fi kuvakaappaus" /></a>
    <p>&nbsp;</p>
  </div>
  <div class="col-sm-7 col-md-6">
    <p><a href="https://www.finna.fi">Finna.fi</a> tuo <a href="https://www.finna.fi/Content/Organisations">Suomen museoiden, kirjastojen ja arkistojen</a> aineistot kaikkien saataville.</p>
    <p>Pääset selaamaan ja lukemaan <a href="https://www.finna.fi/Search/Results?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=online_boolean%3A1')?>">verkossa saatavilla</a> olevia aineistoja.</p>
    <p>Voit myös mm. <a href="https://www.finna.fi/MyResearch/Home">uusia lainoja ja tehdä varauksia</a> eri kirjastojen aineistoihin yhdestä ja samasta paikasta.</p>
    <p>Löydät finna.fi:stä samalla haulla kaikille avoimet aineistot, jotka mukana olevat organisaatiot tarjoavat.</p>
  </div>
</div>
</div>
</div>
</div>
<div class="container-fluid odd-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Muut Finna-hakupalvelut</h2>
        <p>Finna on hakupalvelujen kokonaisuus, johon kuuluu monia sivustoja valtakunnallisen finna.fi:n lisäksi. Organisaatiokohtaiset sivustot ovat rajattuja pääasiassa yhden organisaation aineistoihin.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>Yleiset kirjastot</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://vaski.finna.fi"><img src="<?=$this->imageLink('vaski.jpg')?>" alt="vaski.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Vaski-kirjastot</p><p class="organisation-list-url"><a href="https://vaski.finna.fi">vaski.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>Museot</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://hkm.finna.fi"><img src="<?=$this->imageLink('hkm.jpg')?>" alt="hkm.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Helsingin kaupunginmuseo</p><p class="organisation-list-url"><a href="https://hkm.finna.fi">hkm.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hrm.finna.fi"><img src="<?=$this->imageLink('hrm.jpg')?>" alt="hrm.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Hotelli- ja ravintolamuseo</p><p class="organisation-list-url"><a href="https://hrm.finna.fi">hrm.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://lelumuseohevosenkenka.finna.fi/"><img src="<?=$this->imageLink('lelumuseohevosenkenka.jpg')?>" alt="lelumuseohevosenkenka.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Suomen Lelumuseo Hevosenkenkä</p><p class="organisation-list-url"><a href="https://lelumuseohevosenkenka.finna.fi/">lelumuseohevosenkenka.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://museot.finna.fi/"><img src="<?=$this->imageLink('museot.jpg')?>" alt="museot.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Museot (Museovirasto)</p><p class="organisation-list-url"><a href="https://museot.finna.fi/">museot.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>AMK-kirjastot</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://masto.finna.fi"><img src="<?=$this->imageLink('masto.jpg')?>" alt="masto.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Lahden AMK</p><p class="organisation-list-url"><a href="https://masto.finna.fi">masto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://samk.finna.fi"><img src="<?=$this->imageLink('samk.jpg')?>" alt="samk.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Satakunnan AMK</p><p class="organisation-list-url"><a href="https://samk.finna.fi">samk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://oamk.finna.fi"><img src="<?=$this->imageLink('oamk.jpg')?>" alt="oamk.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Oulun AMK</p><p class="organisation-list-url"><a href="https://oamk.finna.fi">oamk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hamk.finna.fi"><img src="<?=$this->imageLink('hamk.jpg')?>" alt="hamk.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Hämeen AMK</p><p class="organisation-list-url"><a href="https://hamk.finna.fi">hamk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://janet.finna.fi"><img src="<?=$this->imageLink('janet.jpg')?>" alt="janet.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Jyväskylän AMK</p><p class="organisation-list-url"><a href="https://janet.finna.fi">janet.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://kaakkuri.finna.fi"><img src="<?=$this->imageLink('kaakkuri.jpg')?>" alt="kaakkuri.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Kaakkois-Suomen AMK</p><p class="organisation-list-url"><a href="https://kaakkuri.finna.fi">kaakkuri.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://laurea.finna.fi"><img src="<?=$this->imageLink('laurea.jpg')?>" alt="laurea.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Laurea-kirjasto</p><p class="organisation-list-url"><a href="https://laurea.finna.fi">laurea.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://metropolia.finna.fi"><img src="<?=$this->imageLink('metropolia.jpg')?>" alt="metropolia.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Metropolia AMK</p><p class="organisation-list-url"><a href="https://metropolia.finna.fi">metropolia.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://seamk.finna.fi"><img src="<?=$this->imageLink('seamk.jpg')?>" alt="seamk.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">SeAMK Korkeakoulukirjasto</p><p class="organisation-list-url"><a href="https://seamk.finna.fi">seamk.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>Yliopistokirjastot</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://jyu.finna.fi"><img src="<?=$this->imageLink('jyu.jpg')?>" alt="jyu.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Jyväskylän yliopisto</p><p class="organisation-list-url"><a href="https://jyu.finna.fi">jyu.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://kansalliskirjasto.finna.fi"><img src="<?=$this->imageLink('kansalliskirjasto.jpg')?>" alt="kansalliskirjasto.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Kansalliskirjasto</p><p class="organisation-list-url"><a href="https://kansalliskirjasto.finna.fi">kansalliskirjasto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://aalto.finna.fi"><img src="<?=$this->imageLink('aalto.jpg')?>" alt="aalto.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Aalto-yliopiston kirjasto</p><p class="organisation-list-url"><a href="https://aalto.finna.fi">aalto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hanken.finna.fi"><img src="<?=$this->imageLink('hanken.jpg')?>" alt="hanken.finna.fi kuvakaappaus" /></a>
            <p class="organisation-list-header">Svenska handelshögskolan</p><p class="organisation-list-url"><a href="https://hanken.finna.fi">hanken.finna.fi</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-11">
            <p><strong>AMK- ja yliopistokirjastojen Finna-sivustot</strong> sisältävät kansainvälisiä, tieteellisiä, sähköisiä aineistoja, jotka ulkopuolinen toimija koostaa ja tarjoaa ja jotka ovat maksullisia kirjastoille. Valtaosa näistä on rajattu korkeakoulun opiskelijoiden ja henkilökunnan käyttöön.</p>
            <p>&nbsp;</p>
          </div>
        </div>
      </div>
    </div>
    
  </div> <!-- close container -->
</div>  <!-- close container-fluid -->
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Finna on muutakin kuin hakupalvelu</h2>
        <p>Finnan avulla voit paitsi löytää, myös käyttää aineistoja. Tällä hetkellä seuraavat <strong>kirjastot</strong> tarjoavat Finnassa varaus-, lainan uusimis- ja muita toiminnallisuuksia:</p>
        <p>Voit käyttää näitä toiminnallisuuksia, kun olet <a href="https://www.finna.fi/MyResearch/Home">kirjautunut Finnaan</a> ja sinulla on kyseisen kirjaston kirjastokortti.</p>
        <p>Joihinkin <strong>arkistoaineistoihin</strong> voi tehdä käyttölupahakemuksen Finnan aineistotietojen yhteydestä löytyvillä linkeillä.</p>
        <p>Tulevaisuudessa Finnassa on mahdollista käyttää myös <strong>museoiden</strong> digitaalisia palveluja.</p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid odd-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Tietoa Finnasta</h2>
        <h4>Käyttöoikeudet</h4>
        <p>Finnan luettelointitieto on vapaasti kaikkien käytössä, mutta Finnassa näkyviin digitaalisiin kuviin, takakansiteksteihin ja Finnasta linkattuihin digitaalisiin sisältöihin ja kuvailutietoihin voi liittyä lakiin tai sopimuksiin perustuvia rajoituksia. <a href="https://www.finna.fi/Content/terms_conditions#terms">Lue lisätietoa käyttöoikeuksista.</a></p>
        <h4>Finnan kehittäminen</h4>
        <p>Finna on palvelu, jota kehitetään vaiheittain sitä mukaa, kun uusia organisaatioita liittyy mukaan. Finnan beta-versio avattiin joulukuussa 2012 ja ensimmäinen versio lokakuussa 2013. Vaikka et siis ehkä vielä löydä hakemaasi tietoa Finnasta, se saattaa tulla sinne tulevaisuudessa.</p>
        <h4>Finnan vastuutahot</h4>
        <p>Kansalliskirjasto vastaa Finnan kehittämisestä ja ylläpidosta, mutta palvelua kehitetään yhdessä Finnan yhteistyökumppanien kanssa. Finnan sisällöistä vastaavat palveluun osallistuvat <a href="https://www.finna.fi/Content/Organisations">arkistot, kirjastot ja museot.</a> Finna on osa opetus- ja kulttuuriministeriön <a href="http://www.kdk.fi/fi/tietoa-hankkeesta">Kansallinen digitaalinen kirjasto</a> -hanketta.</p>
        <h4>Finnan ohjelmisto</h4>
        <p>Finna on toteutettu VuFind- ja muilla avoimen lähdekoodin ohjelmistoilla, ja sen lähdekoodi on kaikkien halukkaiden hyödynnettävissä. <a href="http://www.kdk.fi/fi/asiakasliittyma/ohjelmiston-kehittaeminen">Lue lisätietoa ohjelmiston kehittämisestä.</a></p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="container">
    <div class="row">
    <!-- open closed divs for valid HTML -->
<!-- END of: national - content/about_fi.phtml -->
