<!-- START of: national - content/headertexts_en-gb.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Information about the picture:</p>
    <p class="header-info-title">Helsingin olympialaiset 1952. Maantiepyöräily. -- dia, filmi, väri</p>
    <p>Photographer: Olympia-kuva Oy<br/>
       Location: Helsingin kaupunginmuseo</p>
    <p><a href="<?=$this->url('home'); ?>Record/hkm.HKMS000005%3Akm0000mrfs">To the record »</a></p>
</div>
<!-- END of: national - content/headertexts_en-gb.phtml -->
