<!-- START of: national - content/headertexts_sv.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Information om bildet:</p>
    <p class="header-info-title">Helsingin olympialaiset 1952. Maantiepyöräily. -- dia, filmi, väri</p>
    <p>Fotograf: Olympia-kuva Oy<br/>
       Belägenhet: Helsingin kaupunginmuseo</p>
    <p><a href="<?=$this->url('home'); ?>Record/hkm.HKMS000005%3Akm0000mrfs">Till posten »</a></p>
</div>
<!-- END of: national - content/headertexts_sv.phtml -->
