<!-- START of: national - content/headertexts_fi.phtml -->
<div class="info-box-text">
    <div class="info-text-close"><i class="fa fa-times close-btn"></i></div>
    <p class="header-info-light">Kuvan tiedot:</p>
    <p class="header-info-title">Helsingin olympialaiset 1952. Maantiepyöräily. -- dia, filmi, väri</p>
    <p>Kuvaaja: Olympia-kuva Oy<br/>
       Sijainti: Helsingin kaupunginmuseo</p>
    <p><a href="<?=$this->url('home'); ?>Record/hkm.HKMS000005%3Akm0000mrfs">Aineistotietoon »</a></p>
</div>
<!-- END of: national - content/headertexts_fi.phtml -->
