<!-- START of: national - content/organisations_fi.phtml -->
<?
  $this->headTitle('Ketkä ovat mukana?');
  $this->content()->setHeading('Ketkä ovat mukana?');
  $organisationList = $this->organisationsList();
?>

<div class="row">
  <div class="col-md-10 col-lg-8">
    <h2>Osallistuvat organisaatiot</h2>
    <p>Tähän mennessä seuraavat organisaatiot ovat tuoneet Finnaan aineistoja</p>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_archives', ['%%cnt%%' => count($organisationList['arc'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['arc'])); ?>
  </div>
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_libraries', ['%%cnt%%' => count($organisationList['lib'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['lib'])); ?>
  </div>
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_museums', ['%%cnt%%' => count($organisationList['mus'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['mus'])); ?>
  </div>
</div>
</div>
</div>
</div>
<div class="container-fluid odd-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Voinko käyttää aineistoja?</h2>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-4">
        <h4>Arkistot</h4>
        <p>Voit tutustua suurimpaan osaan arkistojen aineistoista paikan päällä arkiston tiloissa. Tutkijat, opiskelijat ja kansalaiset voivat hakea käyttörajoitettuihin aineistoihin tutkimuslupaa, joka yleensä pyritään myöntämään.</p>
        <p>Kaikki mukana olevat arkistot ovat tuoneet Finnaan verkossa saatavilla olevia aineistojaan, joihin kenellä tahansa on pääsy.</p>
        <p><a href="<?=$this->url('search-results')?>?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=~sector_str_mv%3A%220%2Farc%2F%22')?>">Arkistojen aineistot finna.fi:ssä <i class="fa fa-search"></i></a></p>
        <p>&nbsp;</p>
      </div>
      <div class="col-sm-4">
        <h4>Yliopistojen ja ammattikorkeakoulujen kirjastot</h4>
        <p>Kuka tahansa voi lainata useimpien yliopisto- ja ammattikorkeakoulukirjastojen aineistoja.</p>
        <p>Lainausoikeuden hankkiminen uuteen kirjastoon ei aina edellytä edes uuden kirjastokortin hankintaa, koska joissakin tapauksissa lainausoikeus voidaan lisätä olemassaolevaan kirjastokorttiin. Lainausoikeuksia myönnetään yleensä kirjastojen palvelupisteissä.</p>
        <p><a href="<?=$this->url('search-results')?>?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=~sector_str_mv%3A%221%2Flib%2Funi%2F%22&filter%5B%5D=~sector_str_mv%3A%221%2Flib%2Fpoly%2F%22')?>">Yliopisto- ja ammattikorkeakoulukirjastojen aineistot finna.fi:ssä <i class="fa fa-search"></i></a></p>
        <h4>Kaupungin- ja maakuntakirjastot</h4>
        <p>Kuka tahansa voi lainata kirjoja ja muita aineistoja Suomen yleisistä kirjastoista. Kirjastokortin myöntämiseksi saatetaan vaatia suomalainen postiosoite.</p>
        <p><a href="<?=$this->url('search-results')?>?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=~sector_str_mv%3A%221%2Flib%2Fpub%2F%22')?>">Yleisten kirjastojen aineistot finna.fi:ssä <i class="fa fa-search"></i></a></p>
        <p>&nbsp;</p>
      </div>
      <div class="col-sm-4">
        <h4>Museot</h4>
        <p>Finnassa pääset katselemaan verkossa saatavilla olevia aineistoja, jotka eivät ole näytteillä museon tiloissa, ja joihin esimerkiksi vain tutkijat ovat päässeet aiemmin käsiksi.</p>
        <p>Voit tilata painokelpoisia kuvia tai käyttöoikeuksia kuviin monista museoista maksullisena lisäpalveluna.</p>
        <a href="<?=$this->url('search-results')?>?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=~sector_str_mv%3A%220%2Fmus%2F%22')?>">Museoiden aineistot finna.fi:ssä <i class="fa fa-search"></i></a>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Aiheesta muualla</h2>
        <p>Sivulla  <a href="<?=$this->url('content-page', ['page' => 'terms_conditions'])?>">Tietosuoja ja käyttöehdot</a> kerrotaan tarkemmin Finnassa olevien aineistojen käyttöoikeuksista.</p>
        <p>Sivu  <a href="<?=$this->url('content-page', ['page' => 'about'])?>">Mikä Finna on?</a> sisältää tietoa Finnaan kuuluvista sivustoista ja Finnassa tarjottavista toiminnallisuuksista.</p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="container">
    <div class="row">
    <!-- open closed divs for valid HTML -->
<!-- END of: national - content/organisations_fi.phtml -->
