<!-- START of: national - content/organisation-list.phtml -->
<ul class="organisations">
  <? foreach($list as $item): ?>
    <li>
        <? $name = $this->escapeHtml($item['name'])?>
        <div class="name">
            <?=$name; ?>
        </div>
        <div class="link">
            <a title="<?=$this->TransEsc('Find')?>: <?=$name; ?>" href="<?=$this->url('home'); ?>Search/Results<?=$this->escapeHtmlAttr($item['link']) ?>"><span class="sr-only"><?=$this->TransEsc('Find')?>: <?=$name; ?></span><i class="fa fa-search"></i></a>
        </div>
    </li>
  <? endforeach; ?>
</ul>
<!-- END of: national - content/organisation-list.phtml -->
