<?
  $this->headTitle('Organisaatiot');
  $this->content()->setHeading('Organisaatiot');
  $organisationList = $this->organisationsList();
?>

<div class="row">
  <div class="col-md-10 col-lg-8">
    <p><?=$this->TransEsc('organisations_text') ?></p>
  </div>
</div>
<div class="row">
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_archives', ['%%cnt%%' => count($organisationList['arc'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['arc'])); ?>
  </div>
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_libraries', ['%%cnt%%' => count($organisationList['lib'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['lib'])); ?>
  </div>
  <div class="col-sm-4">
    <h4><?=$this->TransEsc('organisation_museums', ['%%cnt%%' => count($organisationList['mus'])]) ?></h4>
    <?= $this->partial('content/organisation-list.phtml', array('list' => $organisationList['mus'])); ?>
  </div>
</div>
