<?php
  // Set page title.
  $this->headTitle($this->translate('VuFind Administration - Overdrive API'));
?>
<div class="<?=$this->layoutClass('mainbody')?>">

  <?=$this->flashmessages()?>

  <?php if ($this->overdrive()->showOverdriveAdminLink()): // Hide output if disabled ?>
    <h2><?=$this->transEsc('Overdrive Status')?></h2>
    <ul class="list-group">
        <li class="list-group-item"> <?php echo '<strong>Current API Token:</strong> ' . $this->token;?></li>
    </ul>

    <h2><?=$this->transEsc('Overdrive Library Information')?></h2>
    <ul class="list-group">
        <li class="list-group-item"><?php echo '<strong>Product Key:</strong> ' . $this->productsKey;?></li>
    </ul>

    <h2><?=$this->transEsc('Overdrive Configuration')?></h2>

    <ul class="list-group">
        <li class="list-group-item"><?php echo '<strong>Mode: </strong>';
            echo $this->overdriveConfig->productionMode ? 'Production' : 'Integration';?></li>
        <li class="list-group-item"> <?php echo '<strong>Client Key:</strong> ' . $this->overdriveConfig->clientKey;?></li>
        <li class="list-group-item"> <?php echo '<strong>Library ID:</strong> ' . $this->overdriveConfig->libraryID;?></li>
        <li class="list-group-item"> <?php echo '<strong>Website ID:</strong> ' . $this->overdriveConfig->websiteID;?></li>
        <li class="list-group-item"> <?php echo '<strong>ILS Name:</strong> ' . $this->overdriveConfig->ILSname;?></li>
        <li class="list-group-item"> <?php echo '<strong>Records in Marc Format: </strong>' . ($this->overdriveConfig->isMarc ? 'Yes' : 'No'); ?></li>
    </ul>

    <h2><?=$this->transEsc('User Access')?></h2>
    <ul class="list-group">
        <?php if ($this->hasAccess->status):?>
        <li class="list-group-item"><?php echo '<strong>Current User Has Access?:</strong> Yes'?></li>
        <li class="list-group-item"><?php echo '<strong>Current User API Token?:</strong> ' . $this->hasAccess->status;?></li>
        <?php else:?>
        <li class="list-group-item"><?php echo '<strong>Current User Has Access?:</strong> No'?></li>
        <?php endif;?>
        <li class="list-group-item"><?php echo '<strong>Test User:</strong>'?>
            <div class="alert alert-info">
                <?=$this->icon('warning') ?> Feature not ready yet
            </div>
        </li>
    </ul>
  <?php endif; ?>
</div>
<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->render('admin/menu.phtml')?>
</div>
