<!-- START of: finna - Auth/ChoiceAuth/login.phtml -->
<div id="authcontainer">
<?php
  $methods = $this->auth()->getManager()->getSelectableAuthOptions();
  $activeMethod = $this->auth()->getRequestedAuthMethod();
  if (empty($activeMethod) || 'ChoiceAuth' === $activeMethod) {
    $activeMethod = reset($methods);
  }
?>
<?php if (count($methods) > 1): ?>
  <div class="login-tabs login-accordion">
    <ul class="loginTabs nav nav-tabs visible-md visible-lg">
      <?php foreach ($methods as $loop => $method):?>
        <?php $this->auth()->getManager()->setAuthMethod($method) ?>
        <li class="<?=$this->escapeHtmlAttr($method)?><?=$method === $activeMethod ? ' active' : ''?>">
          <a href="#" class="<?=$this->escapeHtmlAttr($method)?>"><?=$this->transEsc('login_method_tab_' . strtolower($method)) ?></a>
        </li>
      <?php endforeach ?>
    </ul>

    <?php foreach ($methods as $loop => $method):?>
      <div class="accordion accordion-heading<?=$method === $activeMethod ? ' initiallyActive' : ''?>">
        <?php $this->auth()->getManager()->setAuthMethod($method) ?>
        <div class="accordion-toggle">
          <a href="#" data-tab="<?=$this->escapeHtmlAttr($method)?>" class="accordion-title">
            <span class="title"><?=$this->transEsc('login_method_tab_' . strtolower($method))?></span>
            <i class="icon" aria-hidden="true"></i>
          </a>
        </div>
      </div>
    <?php endforeach; ?>

    <div class="tab-content">
      <?php foreach ($methods as $loop => $method):?>
        <?php $this->auth()->getManager()->setAuthMethod($method) ?>
        <div class="tab-pane <?=$this->escapeHtmlAttr($method)?>-tab<?=$loop === 0 ? ' active' : ''?>">
          <?=$this->auth()->getLogin() ?>
        </div>
      <?php endforeach ?>
    </div>
  </div>
<?php else: ?>
  <?php foreach ($methods as $loop => $method):?>
    <div class="authmethod<?=$loop?>?>">
      <?php $this->auth()->getManager()->setAuthMethod($method) ?>
      <?=$this->auth()->getLoginDesc() ?>
      <?=$this->auth()->getLogin() ?>
    </div>
  <?php endforeach ?>
<?php endif; ?>
</div>
<?php $this->auth()->getManager()->setAuthMethod('ChoiceAuth') ?>

<?php
  // Init with inline script to make it lightbox compatible
  $script = "finna.layout.initLoginTabs();";
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- END of: finna - Auth/ChoiceAuth/login.phtml -->
