<div class="alignleft" style="text-align:center">
  <h3><?=$this->transEsc($this->title) ?></h3>

  <?=$this->flashmessages();?>

  <?=$this->transEsc($this->message) ?>
  <div id="popupDetails" class="confirmDialog" style="margin-top:.5em">
    <form action="<?=$this->escapeHtml($this->confirm)?>" method="post">
      <? foreach ($this->extras as $extra=>$value): ?>
        <input type="hidden" name="<?=$this->escapeHtml($extra) ?>" value="<?=$this->escapeHtml($value) ?>" />
      <? endforeach; ?>
      <input type="submit" name="confirm" value="<?=$this->transEsc('confirm_dialog_yes') ?>" />
    </form>
    <form action="<?=$this->escapeHtml($this->cancel) ?>" method="post">
      <input type="submit" name="cancel" value="<?=$this->transEsc('confirm_dialog_no') ?>" />
    </form>
    <div class="clearer"></div>
  </div>
</div>