<?
    // Set up page title:
    $this->headTitle($this->translate('ILL Requests'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('ILL Requests') . '</em>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  <h3><?=$this->transEsc('ILL Requests') ?></h3>

  <?=$this->flashmessages()?>

  <? if (!empty($this->recordList)): ?>
    <? if ($this->cancelForm): ?>
      <form name="cancelForm" action="" method="post" id="cancelILLRequest">
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="toolbar">
          <ul>
            <li><input type="submit" class="button ILLRequestCancel" name="cancelSelected" value="<?=$this->transEsc("ill_request_cancel_selected") ?>"/></li>
            <li><input type="submit" class="button ILLRequestCancelAll" name="cancelAll" value="<?=$this->transEsc("ill_request_cancel_all") ?>"/></li>
          </ul>
        </div>
      <div class="clearer"></div>
    <? endif; ?>

    <ul class="recordSet">
    <? $iteration = 0; ?>
    <? foreach ($this->recordList as $resource): ?>
      <? $iteration++; ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <li class="result<? if (($iteration % 2) == 0): ?> alt<? endif; ?>">
        <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <label for="checkbox_<?=$safeId?>" class="offscreen"><?=$this->transEsc("Select this record")?></label>
          <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
          <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" class="checkbox" style="margin-left:0;" id="checkbox_<?=$safeId?>" />
        <? endif; ?>
        <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>">
          <div class="span-2">
            <? if ($summThumb = $this->record($resource)->getThumbnail()): ?>
              <img src="<?=$this->escapeHtmlAttr($summThumb)?>" class="summcover" alt="<?=$this->transEsc('Cover Image')?>"/>
            <? else: ?>
              <img src="<?=$this->url('cover-unavailable')?>" class="summcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
            <? endif; ?>
          </div>
          <div class="span-10">
            <?
                // If this is a non-missing Solr record, we should display a link:
                if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                    $title = $resource->getTitle();
                    $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                    echo '<a href="' . $this->recordLink()->getUrl($resource) .
                        '" class="title">' . $title . '</a>';
                } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                    // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                    echo $this->escapeHtml($ilsDetails['title']);
                } else {
                    // Last resort -- indicate that no title could be found.
                    echo $this->transEsc('Title not available');
                }
            ?><br/>
            <? $listAuthor = $resource->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthor)?>"><?=$this->escapeHtml($listAuthor)?></a><br/>
            <? endif; ?>

            <? $formats = $resource->getFormats(); if (count($formats) > 0): ?>
              <?=$this->record($resource)->getFormatList()?>
              <br/>
            <? endif; ?>
            <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['institution_name']) && !empty($ilsDetails['institution_name'])): ?>
              <strong><?=$this->transEsc('institution_' . $ilsDetails['institution_name'], array(), $ilsDetails['institution_name']) ?></strong>
              <br />
            <? endif; ?> 
                
            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($this->pickup): ?>
                <? foreach ($this->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br />
            <? endif; ?>

            <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
            <? if (!empty($ilsDetails['expire'])): ?>
             | <strong><?=$this->transEsc('Expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
            <? endif; ?>
            <br />

            <? if (isset($this->cancelResults['items'])): ?>
              <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
                <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                  <div class="error"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['in_transit']) && $ilsDetails['in_transit']): ?>
              <div class="info"><?=$this->transEsc("ill_request_in_transit") . (is_string($ilsDetails['in_transit']) ? ': ' . $this->transEsc('institution_' . $ilsDetails['in_transit'], array(), $ilsDetails['in_transit']) : '') ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
              <div class="info"><?=$this->transEsc("ill_request_processed") . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
              <div class="info"><?=$this->transEsc("ill_request_available") ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
              <div class="info"><?=$this->transEsc("ill_request_canceled") . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['cancel_link'])): ?>
              <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("ill_request_cancel") ?></a></p>
            <? endif; ?>

          </div>
          <div class="clear"></div>
        </div>
      </li>
    <? endforeach; ?>
    </ul>
    <? if ($this->cancelForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any interlibrary loan requests placed') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", array('active' => 'ILLRequests'))?>
</div>

<div class="clear"></div>
