<?
    // Set up page title:
    $this->headTitle($this->translate('Login'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<a href="' . $this->url('myresearch-home') . '">'
        . $this->transEsc('Your Account') . '</a>' . '<span>&gt;</span><em>'
        . $this->transEsc('Login') . '</em>';

    // If we're in AJAX mode, load some extra Javascript inline:
    if ($this->layout()->getTemplate() == 'layout/lightbox') {
        echo $this->inlineScript(\Zend\View\Helper\HeadScript::FILE, 'rc4.js', 'SET');
    }

    // Convenience variables:
    $account = $this->auth()->getManager();
    $hideLogin = !(is_object($account) && $account->loginEnabled());
    $offlineMode = $this->ils()->getOfflineMode();
?>

<? if ($offlineMode == "ils-offline"): ?>
  <div class="sysInfo">
    <h2><?=$this->transEsc('ils_offline_title')?></h2>
    <p><strong><?=$this->transEsc('ils_offline_status')?></strong></p>
    <p><?=$this->transEsc('ils_offline_login_message')?></p>
    <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <p><a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a></p>
  </div>
<? endif; ?>

<h2><?=$this->transEsc('Login')?></h2>
<?=$this->flashmessages()?>

<? if ($hideLogin): ?>
  <div class="error"><?=$this->transEsc('login_disabled')?></div>
<? else: ?>
  <?=$this->auth()->getLogin()?>
<? endif; ?>
