<h2><?=$this->transEsc('Create New Password') ?></h2>
<?=$this->flashmessages() ?>
<? if (!$this->auth()->getManager()->supportsPasswordChange()): ?>
  <div class="error"><?=$this->transEsc('recovery_new_disabled') ?></div>
<? elseif (!isset($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<? else: ?>
  <form action="<?=$this->url('myresearch-newpassword') ?>" method="post">
    <?=$this->auth()->getNewPasswordForm() ?>
    <input type="hidden" value="<?=$this->hash ?>" name="hash"/>
    <input name="submit" type="submit"/>
  </form>
<? endif; ?>