<?
    // Set page title.
    $this->headTitle($this->translate('Add Tag'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('Add Tag') . '</em>';
?>
<div class="record">
  <h1 class="hideinlightbox"><?=$this->transEsc('Add Tag')?></h1>
  <form action="" method="post" name="tagRecord">
    <input type="hidden" name="submit" value="1" />
    <input type="hidden" name="id" value="<?=$this->escape($this->driver->getUniqueId())?>" />
    <input type="hidden" name="source" value="<?=$this->escape($this->driver->getResourceSource())?>" />
    <label for="addtag_tag"><?=$this->transEsc("Tags")?>:</label>
    <input id="addtag_tag" type="text" name="tag" value="" size="40"  class="mainFocus <?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
    <p><?=$this->transEsc("add_tag_note")?></p>
    <input type="submit" value="<?=$this->transEsc('Save')?>"/>
  </form>
</div>