<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>
<div class="search_tabs source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="tabs_<?=escapeJSAttr($this->driver->getUniqueId())?>">
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />

  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
  <?=$this->flashmessages()?>
<!--   <?=$this->record($this->driver)->getCoreMetadata()?> -->

  <div id="<?=escapeJSAttr($this->driver->getUniqueId()) ?>_tabs" class="recordTabs tabnav">
    <ul>
      <li class="active">
        <a id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toogle="tab" data-target="#information-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>">
          <?=$this->translate('ajaxview_label_information') ?>
        </a>
      </li>
      <? foreach ($this->tabs as $tab => $obj): ?>
        <?
          $desc = $obj->getDescription();
        ?>
        <li>
          <a id="<?=strtolower($tab)?>_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toolge="tab" data-target="#<?=strtolower($tab)?>-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>"><?=$this->transEsc($desc)?></a>
        </li>
      <? endforeach; ?>
      <li class="hidden">
        <a id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toogle="tab" data-target="#tools-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>">
          <?=$this->translate('ajaxview_label_tools') ?>
        </a>
      </li>
      <? if ($this->related()->getList($this->driver) != null ): ?>
      <li>
        <a id="similar_<?=escapeJSAttr($this->driver->getUniqueId())?>" data-toogle="tab" data-target="#similar-tab_<?=escapeJSAttr($this->driver->getUniqueId())?>">
          <?=$this->transEsc("Related Items")?>
        </a>
      </li>
      <? endif; ?>
    </ul>
    <div class="clear"></div>
  </div>
  <div class="recordsubcontent">
    <div id="information_<?=escapeJSAttr($this->driver->getUniqueId())?>-content">
      <?=$this->record($this->driver)->getCoreMetadata()?>
    </div>
    <div id="tools_<?=escapeJSAttr($this->driver->getUniqueId())?>-content">
      <?=$this->record($this->driver)->getToolbar()?>
    </div>
    <? if ($this->related()->getList($this->driver) != null): ?>
      <div id="similar_<?=escapeJSAttr($this->driver->getUniqueId())?>-content">
        <? foreach ($this->related()->getList($this->driver) as $current): ?>
          <?=$this->related()->render($current)?>
        <? endforeach; ?>
      </div>
     <? endif; ?>
  </div>
</div>
<span class="Z3988" title="<?=escapeJSAttr($this->driver->getOpenURL())?>"></span>
