<?
  // Set up standard record scripts:
  $this->headScript()->appendFile("record.js");
  $this->headScript()->appendFile("check_save_statuses.js");
  // Activate Syndetics Plus if necessary:
  if ($this->syndeticsPlus()->isActive()) {
    echo $this->headScript()->appendFile($this->syndeticsPlus()->getScript());
  }
  // Add RDF header link if applicable:
  if ($this->export()->recordSupportsFormat($this->driver, 'RDF')) {
    $this->headLink()->appendAlternate($this->recordLink()->getActionUrl($this->driver, 'RDF'), 'application/rdf+xml', 'RDF Representation');
  }

  function escapeJSAttr($op) {
    return preg_replace("/\W/", "_", $op);
  }
?>

<div>
  <div class="record recordId source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>" id="record_<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>" class="hiddenId" id="record_id_<?=escapeJSAttr($this->driver->getUniqueId())?>" />

    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource()) ?>" class="hiddenSource" />
    <?=$this->flashmessages()?>
  </div>
<div class="accordion_group" id="accordion_<?=escapeJSAttr($this->driver->getUniqueId())?>">
  <div class="navmenu open">
    <dt><?=$this->translate('ajaxview_label_information') ?></dt>
    <dd><?=$this->record($this->driver)->getCoreMetadata()?></dd>
  </div>

  <div class="navmenu">
    <dt><?=$this->translate('ajaxview_label_tools') ?></dt>
    <dd><?=$this->record($this->driver)->getToolbar()?></dd>
  </div>

    <? if ($this->related()->getList($this->driver) != null ): ?>
  <div class="navmenu">
    <dt><?=$this->transEsc("Related Items")?></dt>
    <dd>
      <? foreach ($this->related()->getList($this->driver) as $current): ?>
        <?=$this->related()->render($current)?>
      <? endforeach; ?>
    </dd>
  </div>
  <? endif; ?>

  <? if (count($this->tabs) > 0): ?>
    <? foreach ($this->tabs as $tab => $obj): ?>
      <? if ($tab == 'HierarchyTree') continue; ?>
      <div class="navmenu">
        <dt><?=$this->transEsc($obj->getDescription())?></dt>
        <dd><?=$this->record($this->driver)->getTab($obj) ?></dd>
      </div>
    <? endforeach; ?>
  <? endif; ?>
</div>

  <span class="Z3988" title="<?=$this->escapeHtmlAttr($this->driver->getOpenURL())?>"></span>
</div>
<!--
<div class="<?=$this->layoutClass('sidebar')?>">
  <? foreach ($this->related()->getList($this->driver) as $current): ?>
    <?=$this->related()->render($current)?>
  <? endforeach; ?>
</div>
-->
