<? $comments = $this->driver->getComments(); if (empty($comments) || count($comments) == 0): ?>
  <li><?=$this->transEsc('Be the first to leave a comment')?>!</li>
<? endif; ?>
<? foreach ($comments as $comment): ?>
  <li>
    <?=$this->escapeHtml($comment->comment)?>
    <div class="posted">
      <?=$this->transEsc('Posted by')?> <strong><?=$this->escapeHtml(trim($comment->firstname . ' ' . $comment->lastname))?></strong>
      <?=$this->transEsc('posted_on')?> <?=$this->escapeHtml($comment->created)?>
      <? if (($user = $this->layout()->account->isLoggedIn()) && $comment->user_id == $user->id): ?>
        <a href="<?=$this->recordLink()->getUrl($this->driver, 'DeleteComment')?>?delete=<?=urlencode($comment->id)?>" id="recordComment<?=$this->escapeHtml($comment->id)?>" class="delete tool deleteRecordComment source<?=$this->escapeHtml($this->driver->getResourceSource())?>"><?=$this->transEsc('Delete')?></a>
      <? endif; ?>
    </div>
  </li>
<? endforeach; ?>
