<?
    // Set up ill script:
    $this->headScript()->appendFile("ill.js");

    // Set page title.
    $this->headTitle($this->translate('ill_request_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('ill_request_place_text') . '</em>';
?>
<h2><?=$this->transEsc('ill_request_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>
<div id="ILLRequestForm" class="ILLRequestForm">

  <form action="" method="post">

    <? if (in_array("itemId", $this->extraFields)): ?>
      <div>
        <strong><?=$this->transEsc('ill_request_item')?>:</strong><br/>
        <select name="gatheredDetails[itemId]">
          <? foreach ($this->items as $item): ?>
          <option value="<?=$this->escapeHtmlAttr($item['id'])?>"<?=($this->gatheredDetails['itemId'] == $item['id']) ? ' selected="selected"' : ''?>><?=$this->escapeHtml($item['name'])?></option>
          <? endforeach; ?>
        </select>
      </div>
    <? endif; ?>
    
    <? if (in_array("pickUpLibrary", $this->extraFields)): ?>
      <div>
      <? if (count($this->pickupLibraries) > 1): ?>
        <?
          if (isset($this->gatheredDetails['pickUpLibrary']) && $this->gatheredDetails['pickUpLibrary'] !== "") {
              $selected = $this->gatheredDetails['pickUpLibrary'];
          } else {
              $selected = false;
          }
        ?>
        <strong><?=$this->transEsc("ill_request_pick_up_library")?>:</strong><br/>
        <select id="pickupLibrary" name="gatheredDetails[pickUpLibrary]">
        <? foreach ($this->pickupLibraries as $lib): ?>
          <option value="<?=$this->escapeHtmlAttr($lib['id'])?>"<?=(($selected === false && isset($lib['isDefault']) && $lib['isDefault']) || $selected === $lib['id']) ? ' selected="selected"' : ''?>>
            <?=$this->transEsc('library_' . $lib['name'], null, $lib['name'])?>
          </option>
        <? endforeach; ?>
        </select>
      <? endif; ?>
      </div>
    <? endif; ?>

    <? if (in_array("pickUpLibraryLocation", $this->extraFields)): ?>
      <div>
        <span id="pickupLibraryLocationLabel"><strong><?=$this->transEsc("ill_request_pick_up_location")?>:</strong></span>
        <noscript>
          <label class="error" for="pickupLibraryLocation"><?=$this->transEsc("Please enable JavaScript.")?></label>
          <br />
        </noscript>
        <br/>
        <select id="pickupLibraryLocation" name="gatheredDetails[pickUpLibraryLocation]">
        </select>
      </div>
    <? endif; ?>
    
    <? if (in_array("pickUpLocation", $this->extraFields)): ?>
      <div>
      <? if (count($this->pickupLocations) > 1): ?>
        <?
          if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
              $selected = $this->gatheredDetails['pickUpLocation'];
          } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
              $selected = $this->homeLibrary;
          } else {
              $selected = false;
          }
        ?>
        <strong><?=$this->transEsc("pick_up_location")?>:</strong><br/>
        <select id="pickupLocation" name="gatheredDetails[pickUpLocation]">
        <? foreach ($this->pickupLocations as $loc): ?>
          <option value="<?=$this->escapeHtmlAttr($loc['id'])?>"<?=(($selected === false && isset($loc['isDefault']) && $loc['isDefault']) || $selected === $loc['id']) ? ' selected="selected"' : ''?>>
            <?=$this->escapeHtml($loc['name'])?>
          </option>
        <? endforeach; ?>
        </select>
      <? endif; ?>
      </div>
    <? endif; ?>
    
    <? if (in_array("requiredByDate", $this->extraFields)): ?>
      <div>
      <strong><?=$this->transEsc("hold_required_by")?>: </strong>
      <div id="requiredByHolder"><input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" /> <strong>(<?=$this->dateTime()->getDisplayDateFormat()?>)</strong></div>
      </div>
    <? endif; ?>

    <? if (in_array("comments", $this->extraFields)): ?>
      <div>
      <strong><?=$this->transEsc("Comments")?>:</strong><br/>
      <textarea rows="3" cols="20" name="gatheredDetails[comment]"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
      </div>
    <? endif; ?>

    <input type="submit" name="placeILLRequest" value="<?=$this->transEsc('ill_request_submit_text')?>"/>

  </form>

</div>

<script type="text/javascript">
$(document).ready(function(){
    setUpILLRequestForm('<?=$this->escapeHtml($this->driver->getUniqueId()) ?>');
});
</script>
