<?
    // Set page title.
    $this->headTitle($this->translate('Save'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('Save') . '</em>';
?>
<h2><?=$this->transEsc("add_favorite_prefix") ?> <?=$this->escape($this->driver->getBreadcrumb())?> <?=$this->transEsc("add_favorite_suffix") ?></h2>
<form method="get" action="" name="saveRecord">
  <input type="hidden" name="submit" value="1" />
  <input type="hidden" name="id" value="<?=$this->escape($this->driver->getUniqueId()) ?>" />
  <input type="hidden" name="source" value="<?=$this->escape($this->driver->getResourceSource())?>" />
  <? if (!empty($this->containingLists)): ?>
    <p><?=$this->transEsc('This item is already part of the following list/lists') ?>:</p>
    <ul>
    <? foreach ($this->containingLists as $list): ?>
      <li><a href="<?=$this->url('userList', array('id' => $list['id'])) ?>"><?=$this->escape($list['title'])?></a></li>
    <? endforeach; ?>
    </ul>
  <? endif; ?>

  <?/* Only display the list drop-down if the user has lists that do not contain
  this item OR if they have no lists at all and need to create a default list */?>
  <? $showLists = (!empty($this->nonContainingLists) || (empty($this->containingLists) && empty($this->nonContainingLists))); ?>

  <? if ($showLists): ?>
    <label class="displayBlock" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <select id="save_list" name="list">
      <? if ($this->nonContainingLists): ?>
        <? foreach ($this->nonContainingLists as $list): ?>
          <option value="<?=$list['id'] ?>"<? if ($list['id']==$this->userList()->lastUsed()): ?> selected="selected"<? endif; ?>><?=$this->escape($list['title'])?></option>
        <? endforeach; ?>
      <? else: ?>
        <option value=""><?=$this->transEsc('My Favorites') ?></option>
      <? endif; ?>
    </select>
  <? endif; ?>
  <a href="<?=$this->url('editList', array('id' => 'NEW'))?>?recordId=<?=urlencode($this->driver->getUniqueId())?>&amp;recordController=<?=urlencode($this->record($this->driver)->getController())?>" class="listEdit controller<?=$this->record($this->driver)->getController()?>" title="<?=$this->transEsc('Create a List') ?>"><? if ($showLists) echo $this->transEsc('or create a new list'); else echo $this->transEsc('Create a List'); ?></a>

  <? if ($showLists): ?>
    <label class="displayBlock" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
    <input class="mainFocus" id="add_mytags" type="text" name="mytags" value="" size="50"/>
    <p><?=$this->transEsc("add_tag_note") ?></p>
    <label class="displayBlock" for="add_notes"><?=$this->transEsc('Add a Note') ?></label>
    <textarea id="add_notes" name="notes" rows="3" cols="50"></textarea>
    <br/>
    <input class="button" type="submit" value="<?=$this->transEsc('Save') ?>"/>
  <? endif; ?>
</form>