<?
    // Set page title.
    $this->headTitle($this->translate('storage_retrieval_request_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = $this->getLastSearchLink($this->transEsc('Search'), '', '<span>&gt;</span>') .
        $this->recordLink()->getBreadcrumb($this->driver) . '<span>&gt;</span><em>' . $this->transEsc('storage_retrieval_request_place_text') . '</em>';
?>
<h2><?=$this->transEsc('storage_retrieval_request_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<?=$this->flashmessages()?>
<div class="storageRetrievalRequestForm">

  <form action="" method="post">

    <? if (in_array("item-issue", $this->extraFields)): ?>
      <div>
        <input type="radio" id="storageRetrievalRequestItem" name="gatheredDetails[level]" value="copy"<?=!isset($this->gatheredDetails['level']) || $this->gatheredDetails['level'] != 'title' ? ' checked="checked"' : ''?>>
        <strong><label for="storageRetrievalRequestItem"><?=$this->transEsc('storage_retrieval_request_selected_item')?></label></strong><br/>
        <input type="radio" id="storageRetrievalRequestTitle" name="gatheredDetails[level]" value="title"<?=isset($this->gatheredDetails['level']) && $this->gatheredDetails['level'] == 'title' ? ' checked="checked"' : ''?>>
        <strong><label for="storageRetrievalRequestTitle"><?=$this->transEsc('storage_retrieval_request_reference')?></label></strong><br/>
        <div id="storageRetrievalRequestReference" class="storageRetrievalRequestReference">
          <span class="label"><?=$this->transEsc('storage_retrieval_request_volume')?>:</span> <input type="text" name="gatheredDetails[volume]" value="<?=isset($this->gatheredDetails['volume']) ? $this->escapeHtmlAttr($this->gatheredDetails['volume']) : ''?>"></input><br/>
          <span class="label"><?=$this->transEsc('storage_retrieval_request_issue')?>:</span> <input type="text" name="gatheredDetails[issue]" value="<?=isset($this->gatheredDetails['issue']) ? $this->escapeHtmlAttr($this->gatheredDetails['issue']) : ''?>"></input><br/>
          <span class="label"><?=$this->transEsc('storage_retrieval_request_year')?>:</span> <input type="text" name="gatheredDetails[year]" value="<?=isset($this->gatheredDetails['year']) ? $this->escapeHtmlAttr($this->gatheredDetails['year']) : ''?>"></input><br/>
        </div>
      </div>
    <? endif; ?>

    <? if (in_array("requiredByDate", $this->extraFields)): ?>
      <div>
      <strong><?=$this->transEsc("hold_required_by")?>: </strong>
      <div id="requiredByHolder"><input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" /> <strong>(<?=$this->dateTime()->getDisplayDateFormat()?>)</strong></div>
      </div>
    <? endif; ?>

    <? if (in_array("pickUpLocation", $this->extraFields)): ?>
      <div>
      <? if (count($this->pickup) > 1): ?>
        <?
          if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
              $selected = $this->gatheredDetails['pickUpLocation'];
          } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
              $selected = $this->homeLibrary;
          } else {
              $selected = $this->defaultPickup;
          }
        ?>
        <strong><?=$this->transEsc("pick_up_location")?>:</strong><br/>
        <select name="gatheredDetails[pickUpLocation]">
        <? if ($selected === false): ?>
          <option value="" selected="selected">
            <?=$this->transEsc('select_pickup_location')?>
          </option>
        <? endif; ?>
        <? foreach ($this->pickup as $lib): ?>
          <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
            <?=$this->escapeHtml($lib['locationDisplay'])?>
          </option>
        <? endforeach; ?>
        </select>
      <? else: ?>
        <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
      <? endif; ?>
      </div>
    <? endif; ?>

    <? if (in_array("comments", $this->extraFields)): ?>
      <div>
      <strong><?=$this->transEsc("Comments")?>:</strong><br/>
      <textarea rows="3" cols="20" name="gatheredDetails[comment]"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
      </div>
    <? endif; ?>

    <input type="submit" name="placeStorageRetrievalRequest" value="<?=$this->transEsc('storage_retrieval_request_submit_text')?>"/>

  </form>

</div>

<script type="text/javascript">
$(document).ready(function() {
  $("input[type='radio']").change(function() {
    if ($('#storageRetrievalRequestItem').is(':checked')) {
      $('#storageRetrievalRequestReference input').attr('disabled', 'disabled');
    } else {
      $('#storageRetrievalRequestReference input').removeAttr('disabled');
    }
  });
  $('#storageRetrievalRequestItem').trigger('change');
});
</script>
