<?php
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="breadcrumb-item"><a href="' . $this->url('upgrade-home') . '">' . $this->transEsc('Upgrade') . '</a></li> <li class="breadcrumb-item active" aria-current="page">' . $this->transEsc('Upgrade VuFind') . '</li>';
?>
<h2><?=$this->transEsc('Upgrade VuFind')?></h2>
<?=$this->flashmessages()?>
<p><?=$this->transEsc('vufind_upgrade_fail') ?>.  You can try <a href="<?=$this->url('upgrade-reset')?>">starting over</a>.</p>
