<?php
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('upgrade-home') . '">' . $this->transEsc('Upgrade') . '</a></li> <li class="active">' . $this->transEsc('Upgrade VuFind') . '</li>';
?>
<h2><?=$this->transEsc('Upgrade VuFind')?></h2>
<?=$this->flashmessages()?>

<p>VuFind's database structure needs to be updated for the new version.  Please enter a database username and password
with permission to alter and create tables.</p>

<form method="post" action="<?=$this->url('upgrade-getdbcredentials')?>">
  <table>
    <tbody>
      <tr><td>MySQL Root User: </td><td><input type="text" name="dbrootuser" value="<?=$this->escapeHtmlAttr($this->dbrootuser)?>"></td></tr>
      <tr><td>MySQL Root Password: </td><td><input type="password" name="dbrootpass" value=""></td></tr>
      <tr><td></td><td><input type="submit" name="submitButton" value="<?=$this->transEscAttr('Submit') ?>"></td></tr>
    </tbody>
  </table>
  If you don't have the credentials or you wish to print the SQL out : Click here to <input type="submit" name="printsql" value="Skip"> credentials.
</form>
