<?php
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Upgrade'), $this->url('upgrade-home'))
      ->add($this->translate('Upgrade VuFind'), active: true);
?>
<h2><?=$this->transEsc('Upgrade VuFind')?></h2>
<?=$this->flashmessages()?>
<form class="form-inline" method="post" action="<?=$this->url('upgrade-getsourceversion')?>">
  <p>
    Please enter the version number you are upgrading from (e.g. 10.1.1):
    <input type="text" name="sourceversion">
  </p>
  <p>Options:<br>
  <?php foreach (['config' => 'Configuration', 'database' => 'Database Structure', 'metadata' => 'Stored Metadata'] as $key => $value): ?>
    <input type="checkbox" name="skip[]" id="skip-<?=$this->escapeHtmlAttr($key)?>" value="<?=$this->escapeHtmlAttr($key)?>">
    <label for="skip-<?=$this->escapeHtmlAttr($key)?>">Skip <?=$this->escapeHtml($value); ?> Upgrade</label><br>
  <?php endforeach; ?>
  </p>
  <input class="btn btn-primary" type="submit">
</form>
