<?php
    // Set page title.
    $this->headTitle($this->translate('Upgrade VuFind'));

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Upgrade'), $this->url('upgrade-home'))
      ->add($this->translate('Upgrade VuFind'), active: true);

    // Set up styles:
    $this->assetManager()->appendStyleString(
        ".pre {\n"
        . "  white-space:pre-wrap; width:90%; overflow-y:visible; padding:8px; margin:1em 2em; background:#EEE; border:1px dashed #CCC;\n"
        . "}\n"
    );
?>
<h2><?=$this->transEsc('Upgrade VuFind')?></h2>
<?=$this->flashmessages()?>
<p>These SQL statements can be used to manually upgrade your database:</p>

<textarea class="pre" rows="20"><?=trim($this->sql) ?></textarea>

<p>Please apply these changes to your database before continuing to the next step.</p>
<form method="post" action="<?=$this->url('upgrade-showsql')?>">
  <input class="btn btn-default" type="submit" name="continue" value="Continue to Next Step">
</form>
