<?php
  // Standalone page
  $this->layout()->setTemplate('layout/standalone');
  $this->headTitle($this->translate('show_barcode_title'));
?>
<?=$this->doctype('HTML5')?>
<html lang="<?=$this->layout()->userLang?>">
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=yes">
  <?php // Turn off automatic telephone number detection on iOS ?>
  <meta name="format-detection" content="telephone=no">
  <?php if ($appleTouchIcon = $this->imageSrc()->getSourceAddress('webapp-icon-180.png')): ?>
    <link rel="apple-touch-icon" sizes="180x180" href="<?=$this->escapeHtmlAttr($appleTouchIcon)?>">
  <?php endif ?>
  <?php if ($webAppManifest = $this->imageSrc()->getSourceAddress('manifest.json')): ?>
    <link rel="manifest" href="<?=$webAppManifest?>">
  <?php endif ?>
  <?=$this->headTitle()?>
  <style>
    /* Prevent dark mode */
    :root {
      color-scheme: light only;
    }
    /* Baseline styles */
    html {
      line-height: 1.15;
      -webkit-text-size-adjust: 100%;
      font-family: sans-serif;
    }
    body {
      color: black;
      background-color: white;
    }
    /* Barcode */
    .rotate {
      display: none;
      position: absolute;
      z-index: 1;
      top: 10px;
      left: 10px;
    }
    @media (orientation: portrait) {
      .rotate {
        display: block;
      }
    }
    #rotateButton {
      background: none;
      border: none;
      outline: none;
      cursor: pointer;
    }
    #rotateButton.rotated {
      transform: scaleX(-1)
    }
    #barcode {
      display: flex;
      position: absolute;
      left: 0;
      top: 0;
      flex-wrap: wrap;
      transform: translatex(calc(50vw - 50%)) translatey(calc(20vh)); /* Fallback */
      transform: translatex(calc(50svw - 50%)) translatey(calc(20svh));
      max-width: 90vw; /* Fallback */
      max-width: 90svw;
    }
    @media (orientation: portrait) {
      #barcode.rotated {
        transform: translatex(calc(50vw - 50%)) translatey(calc(50vh - 50%)) rotate(90deg); /* Fallback */
        transform: translatex(calc(50svw - 50%)) translatey(calc(50svh - 50%)) rotate(90deg);
        max-width: 90vh; /* Fallback */
        max-width: 90svh;
      }
    }
    #barcode svg {
      margin: auto;
      max-width: 380px; /* Prevent the barcode from being too big */
      background-color: white;
      padding: .5em;
    }
    .barcode-instructions {
      text-align: center;
      flex-basis: 100%;
      margin-top: 40px;
    }
  </style>
  <?php
    $script = <<<JS
          document.addEventListener('DOMContentLoaded', () => {
            const rotateButton = document.getElementById('rotateButton');
            const rotateBarcode = document.getElementById('barcode');

            rotateButton.addEventListener('click', () => {
              toggleRotateClass(rotateBarcode);
              toggleRotateClass(rotateButton);
            });

            function toggleRotateClass(e) {
              e.classList.toggle('rotated');
            };
          });
        JS;
    echo $this->assetManager()->outputInlineScriptString($script);
  ?>
  </head>
  <body>
    <div class="rotate"><button id="rotateButton"><svg xmlns="http://www.w3.org/2000/svg" height="24" width="24" viewBox="0 0 512 512"><!--!Font Awesome Free 6.5.1 by @fontawesome - https://fontawesome.com License - https://fontawesome.com/license/free Copyright 2024 Fonticons, Inc.--><path opacity="1" fill="#1E3050" d="M463.5 224H472c13.3 0 24-10.7 24-24V72c0-9.7-5.8-18.5-14.8-22.2s-19.3-1.7-26.2 5.2L413.4 96.6c-87.6-86.5-228.7-86.2-315.8 1c-87.5 87.5-87.5 229.3 0 316.8s229.3 87.5 316.8 0c12.5-12.5 12.5-32.8 0-45.3s-32.8-12.5-45.3 0c-62.5 62.5-163.8 62.5-226.3 0s-62.5-163.8 0-226.3c62.2-62.2 162.7-62.5 225.3-1L327 183c-6.9 6.9-8.9 17.2-5.2 26.2s12.5 14.8 22.2 14.8H463.5z"/></svg></button></div>
    <div id="barcode">
      <?php if (!($barcodeSvg = $this->barcode()->createCode39SVG($this->code, 2, 80))): ?>
        <?=$this->transEsc('An error has occurred')?>
      <?php else: ?>
        <?=$barcodeSvg?>
        <div class="barcode-instructions">
          <?=$this->translate('show_barcode_instructions_html', null, '')?>
        </div>
      <?php endif; ?>
    </div>
  </body>
</html>
