<!-- START of: finna - librarycards/home.phtml -->
<?php
    $this->layout()->finnaUserAccountHeading = 'useraccount-content-heading';

    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))->add($this->translate('Library Cards'), active: true);

    // Additional translations
    $this->jsTranslations()->addStrings(['new_password_success' => 'new_password_success']);

    $user = $this->auth()->getUserObject();
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext('myresearch/menu.phtml', ['active' => 'librarycards']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
      <?=$this->flashmessages()?>
      <?php if (!$this->translationEmpty('library_cards_instructions_html')): ?><p class="no-content-message"><?=$this->translate('library_cards_instructions_html')?></p><?php endif; ?>
      <div id="useraccount-content-heading" class="useraccount-header">
        <?=$this->component('page-title', ['title' => $this->translate('Library Cards Connected To My Account'), 'headTitle' => $this->translate('Library Cards')]);?>
      </div>
      <?php if (empty($this->libraryCards)): ?>
        <h4><?=$this->transEsc('You do not have any library cards')?></h4>
      <?php else: ?>
        <table class="table finna-table-striped useraccount-table library-cards mobile-table" tabindex="0">
          <thead>
            <tr class="headers">
              <th class="card-name" scope="col"><?=$this->transEsc('Library Card Name')?></th>
              <?php if ($this->multipleTargets): ?>
              <th scope="col"><?=$this->transEsc('login_target')?></th>
              <?php endif; ?>
              <th scope="col"><?=$this->transEsc('Username')?></th>
              <th class="library-card-actions" scope="col"><?=$this->transEsc('Actions')?></th>
            </tr>
          </thead>
          <tbody>
            <?php foreach ($this->libraryCards as $record): ?>
              <?php $username = $record->getCatUsername(); ?>
              <?php $target = ''; ?>
              <?php if ($this->multipleTargets): ?>
                <?php if (strstr($username, '.')): ?>
                  <?php [$target, $username] = explode('.', $username, 2); ?>
                <?php endif; ?>
              <?php endif; ?>
              <tr>
                <td data-label="<?=$this->transEsc('Library Card Name')?>" class="card-name">
                  <?php $libraryCardName = $record->getCardName() == "$target.$username" ? $this->escapeHtml($username) : $this->escapeHtml($record->getCardName()) ?>
                  <?php if ($libraryCardName): ?>
                    <span><?=$libraryCardName?></span>
                  <?php else: ?>
                    <span>
                      <?=$this->transEsc('Library Card name missing')?>
                      <?php if ($this->auth()->getManager()->allowsUserIlsLogin()): ?>
                        <a href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record->getId()) ?>" title="<?=$this->transEscAttr('Edit Library Card')?>"> <?=$this->transEsc('Add name')?></a>
                      <?php endif; ?>
                    </span>
                  <?php endif; ?>
                </td>
                <?php if ($this->multipleTargets): ?>
                  <td data-label="<?=$this->transEsc('login_target')?>"><span><?=$target ? $this->transEsc("source_$target", null, $target) : '&nbsp;' ?></span></td>
                <?php endif; ?>
                <td data-label="<?=$this->transEsc('Username')?>">
                  <?php $barcode = $record->getBarcode() ?? $username;?>
                  <?php if ($barcode !== $username): ?>
                    <p><?=$this->escapeHtml($username)?></p>
                  <?php endif; ?>
                  <a href="<?=$this->url('librarycards-displaybarcode', ['id' => $record->getId()])?>" title="<?=$this->transEscAttr('show_barcode_title')?>">
                    <?php if (strcasecmp($record->getCatUsername(), $user->getCatUsername()) === 0 && ($barcodeSvg = $this->barcode()->createCode39SVG($barcode, 1.3, 50))): ?>
                      <div class="librarycard-barcode">
                        <?=$barcodeSvg?>
                      </div>
                    <?php endif; ?>
                    <span><?=$this->escapeHtml($barcode)?></span>
                  </a>
                </td>
                <td data-label="<?=$this->transEsc('Actions')?>" class="library-card-actions">
                  <div>
                    <?php if ($this->ils()->checkFunction('changePassword', ['patron' => $record])): ?>
                      <a class="icon-link change-library-card-password" href="<?=$this->url('newLibraryCardPassword') ?>?id=<?=$this->escapeHtmlAttr($record->getId()) ?>" data-lightbox title="<?=$this->transEscAttr('Change Password')?>">
                        <?=$this->icon('library-card-password', 'icon-link__icon') ?>
                        <span class="icon-link__label">
                          <?=$this->transEsc('Change Password')?>
                        </span>
                      </a>
                    <?php endif; ?>
                    <?php if ($this->auth()->getManager()->allowsUserIlsLogin()): ?>
                      <a class="icon-link edit-library-card" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record->getId()) ?>" title="<?=$this->transEscAttr('Edit Library Card')?>">
                        <?=$this->icon('library-card-edit', 'icon-link__icon') ?>
                        <span class="icon-link__label">
                          <?=$this->transEsc('Update Card Details')?>
                        </span>
                      </a>
                    <?php endif; ?>
                    <?=
                      $this->component(
                          'confirm-button',
                          [
                            'buttonLink' => $this->url('librarycards-deletecard', [], ['query' => ['cardID' => $record->getId()]]),
                            'buttonLabelHtml' => $this->icon('library-card-disconnect') . ' ' . $this->translate('Disconnect Library Card'),
                            'buttonClass' => 'btn-unstyled',
                            'confirmLink' => $this->url('librarycards-deletecard', [], ['query' => ['cardID' => $record->getId(), 'confirm' => 1]]),
                            'header' => 'confirm_delete_library_card_brief',
                            'clearAccountCache' => true,
                            'align' => 'right',
                          ]
                      );
                    ?>
                  </div>
                </td>
              </tr>
            <?php endforeach; ?>
          </tbody>
        </table>
      <?php endif; ?>

      <div>
        <?php if ($this->auth()->getManager()->allowsUserIlsLogin()): ?>
          <a href="<?=$this->url('editLibraryCard') ?>NEW" class="btn btn-primary add-library-card" title="<?=$this->transEsc('Connect Library Card')?>"><?=$this->icon('library-card-connect') ?> <?=$this->transEsc('Connect Library Card')?><?=$this->transEsc('eol_ellipsis')?></a>
        <?php endif; ?>
        <br>
        <br>
      </div>
  </div>
</div>
<!-- END of: finna - librarycards/home.phtml -->
