<!-- START of: finna - librarycards/home.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';

    // Additional translations
    $this->jsTranslations()->addStrings(['new_password_success' => 'new_password_success']);

    $user = $this->auth()->isLoggedIn();
?>

<!-- Leftside navigationbar -->
<?= $this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'librarycards']); ?>

<div class="<?=$this->layoutClass('mainbody-myresearch')?>">
  <div class="my-research-content">
      <?=$this->flashmessages()?>
      <?php if (!$this->translationEmpty('library_cards_instructions_html')): ?><p class="no-content-message"><?=$this->translate('library_cards_instructions_html')?></p><?php endif; ?>
      <h2><?=$this->transEsc('Library Cards Connected To My Account')?></h2>
      <?php if ($this->libraryCards->count() == 0): ?>
        <h4><?=$this->transEsc('You do not have any library cards')?></h4>
      <?php else: ?>
        <table class="table table-striped useraccount-table library-cards mobile-table">
          <tr class="headers">
            <th><?=$this->transEsc('Library Card Name')?></th>
            <?php if ($this->multipleTargets): ?>
            <th><?=$this->transEsc('login_target')?></th>
            <?php endif; ?>
            <th><?=$this->transEsc('Username')?></th>
            <th class="library-card-actions"><?=$this->transEsc('Actions')?></th>
          </tr>
          <?php foreach ($this->libraryCards as $record): ?>
            <?php $username = $record['cat_username']; ?>
            <?php $target = ''; ?>
            <?php if ($this->multipleTargets): ?>
              <?php if (strstr($username, '.')): ?>
                <?php list($target, $username) = explode('.', $username, 2); ?>
              <?php endif; ?>
            <?php endif; ?>
            <tr>
              <td data-label="<?=$this->transEsc('Library Card Name')?>">
                <?php $libraryCardName = $record['card_name'] == "$target.$username" ? $this->escapeHtml($username) : $this->escapeHtml($record['card_name']) ?>
                <?php if ($libraryCardName): ?>
                  <span><?=$libraryCardName?></span>
                <?php else: ?>
                  <span>
                    <?=$this->transEsc("Library Card name missing")?>
                    <a class="btn-link" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) ?>" title="<?=$this->transEsc('Edit Library Card')?>"> <?=$this->transEsc("Add name")?></a>
                  </span>
                <?php endif; ?>
              </td>
              <?php if ($this->multipleTargets): ?>
                <td data-label="<?=$this->transEsc('login_target')?>"><span><?=$target ? $this->transEsc("source_$target", null, $target) : '&nbsp;' ?></span></td>
              <?php endif; ?>
              <td data-label="<?=$this->transEsc('Username')?>">
                <a href="<?=$this->url('barcode-show') ?>?code=<?=$this->escapeHtmlAttr($username) ?>" title="<?=$this->escapeHtmlAttr($this->translate('show_barcode_title'))?>">
                  <?php if (strcasecmp($record['cat_username'], $user->cat_username) === 0 && ($barcode = $this->barcode()->createPng($username, 2, 60))): ?>
                    <div class="librarycard-barcode">
                      <img src="data:image/png;base64,<?=$barcode?>" alt="">
                    </div>
                  <?php endif; ?>
                  <span><?=$this->escapeHtml($username)?></span>
                </a>
              </td>
              <td data-label="<?=$this->transEsc('Actions')?>" class="library-card-actions">
                <div>
                  <a class="btn-link" href="<?=$this->url('newLibraryCardPassword') ?>?id=<?=$this->escapeHtmlAttr($record['id']) ?>" data-lightbox title="<?=$this->transEsc('Change Password')?>"><i class="fa fa-lock bigger gray"></i> <?=$this->transEsc('Change Password')?></a>
                  <a class="btn-link" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record['id']) ?>" title="<?=$this->transEsc('Edit Library Card')?>"><i class="fa fa-pen gray" aria-hidden="true"></i> <?=$this->transEsc('Update Card Details')?></a>
                  <div class="dropdown">
                    <a class="btn-link dropdown-toggle" data-toggle="dropdown" href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>">
                      <i class="fa fa-unlink gray" aria-hidden="true"></i> <?=$this->transEsc('Disconnect Library Card')?>
                    </a>
                    <ul class="dropdown-menu useraccount-cancel">
                      <li class="disabled"><a><?=$this->transEsc('Disconnect Library Card')?>?</a></li>
                      <li><a href="<?=$this->url('librarycards-deletecard') ?>?cardID=<?=urlencode($record['id'])?>&amp;confirm=1"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
                      <li><a href="#"><?=$this->transEsc('confirm_dialog_no')?></a></li>
                    </ul>
                  </div>
                </div>
              </td>
            </tr>
          <?php endforeach; ?>
        </table>
      <?php endif; ?>

      <div>
        <a href="<?=$this->url('editLibraryCard') ?>NEW" class="btn btn-primary" title="<?=$this->transEsc('Connect Library Card')?>"><i class="fa fa-link" aria-hidden="true"></i> <?=$this->transEsc('Connect Library Card')?>...</a>
        <br>
        <br>
      </div>
  </div>
</div>
<!-- END of: finna - librarycards/home.phtml -->
