<div class="library-card-terms">
  When you add a library card to your account, the service will store the library card number, PIN code, name, email address and home library. If you are a legal guardian, you must remove the library cards of your ward(s) from your account once they turn fifteen.
  Read more about management of personal information on the <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?> page</a>.
</div>
