<div class="library-card-terms">
  När du registrerar ett bibliotekskort på ditt konto, sparas kortets nummer och PIN-kod, ditt namn, din e-postadress och ditt hembibliotek i tjänsten. Om du är vårdnadshavare för barn ska du radera deras kort från ditt konto när barnen har fyllt 15 år.
  Läs mer om hanteringen av personuppgifter på sidan <a href="<?=$this->url('content-page', ['page' => 'privacy'])?>" data-lightbox-ignore target="_blank"><?=$this->transEsc('Privacy')?></a>.
</div>
