<!-- START of: finna - librarycards/newpassword.phtml -->
<?php
  // Set up page title:
  $this->headTitle($this->translate('Change Password'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    . '<li><a href="' . $this->url('librarycards-home') . '">' . $this->transEsc('Library Cards') . '</a></li>'
    . '<li>' . $this->transEsc('Change Password') . '</li>';
?>

<h2 class="lightbox-header"><?=$this->transEsc('Change Password'); ?></h2>

<?=$this->flashmessages()?>

<form class="new-password-form" method="post" id="newPasswordForm" name="newPasswordForm">
  <input type="hidden" name="id" value="<?=$this->card->id?>"/>
  <input type="hidden" name="hash" id="hash" value="<?=$this->escapeHtmlAttr($this->hash) ?>"/>
  <?php $username = $card->cat_username; ?>
  <?php $target = ''; ?>
  <?php if (strstr($username, '.')): ?>
    <?php list($target, $username) = explode('.', $username, 2); ?>
  <?php endif; ?>
  <?php if ($target): ?>
    <div class="form-group">
      <label class="control-label"><?=$this->transEsc('login_target') ?>:</label>
      <p><?=$this->transEsc("source_$target", null, $target) ?></p>
    </div>
  <?php endif; ?>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('Username') ?>:</label>
    <p><?=$this->escapeHtml(username) ?></p>
  </div>
  <?php if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
    <div class="form-group">
      <label class="control-label"><?=$this->transEsc('old_password') ?>:</label>
      <input type="password" name="oldpwd" class="form-control"/>
      <div class="help-block with-errors"></div>
      <?php if (!$this->translationEmpty('change_password_instructions')): ?>
        <div class="help-block"><?=$this->transEsc('change_password_instructions') ?></div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <?php
    $pattern = '';
    if (isset($this->passwordPolicy['pattern'])) {
      if ($this->passwordPolicy['pattern'] == 'numeric') {
        $pattern = '\d+';
      } elseif ($this->passwordPolicy['pattern'] == 'alphanumeric') {
        $pattern = '[\da-zA-Z]+';
      } else {
        $pattern = $this->passwordPolicy['pattern'];
      }
    }
  ?>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('new_password') ?>:</label>
    <input type="password" id="password" name="password" class="form-control" required aria-required="true"
      <?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->escapeHtmlAttr($this->translate('password_minimum_length', ['%%minlength%%' => $this->passwordPolicy['minLength']])) . '"' : ''?>
      <?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>
      <?=$pattern ? ' pattern="' . $pattern . '"' : '' ?>
    />
    <?php if (!empty($this->passwordPolicy['hint'])): ?>
      <div class="help-block"><?=$this->transEsc($this->passwordPolicy['hint']) ?></div>
    <?php endif; ?>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <label class="control-label"><?=$this->transEsc('confirm_new_password') ?>:</label>
    <input type="password" name="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->escapeHtmlAttr($this->translate('Passwords do not match'))?>"/>
    <div class="help-block with-errors"></div>
  </div>
  <div class="form-group">
    <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Submit')?>" />
  </div>
</form>

<?php
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$js = <<<JS
  if ($.isReady) {
    $('#newPasswordForm').validator();
  } else {
    $(document).ready(function(){
      $('#newPasswordForm').validator();
    });
  }
JS;

echo $this->inlineScript()->appendScript($js);
?>

<!-- END of: finna - librarycards/newpassword.phtml -->
