<!-- START of: finna - librarycards/recover.phtml -->
<?
    // Set up page title:
    $this->headTitle($this->translate('recovery_title'));
    $this->layout()->finnaMainHeader = '<div><h3 class="finna-main-header">' . $this->transEsc('recovery_title') . '</h3></div>';

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('recovery_title') . '</li>';

?>
<h2 class="ligthbox-header"><?=$this->transEsc('recovery_title') ?></h2>
<?=$this->flashmessages()?>
<? if ($this->recoveryDisabled): ?>
  <div class="error"><?=$this->transEsc('recovery_disabled') ?></div>
<? elseif (!$this->emailSent): ?>
  <form id="recover_password" method="post" autocomplete="off">
    <? if (!$this->translationEmpty('library_card_recovery_help_html')): ?>
      <p><?=$this->translate('library_card_recovery_help_html') ?></p>
    <? endif; ?>
    <div class="form-group">
      <label class="control-label" for="login_username"><?=$this->transEsc('Username')?>:</label>
      <input id="login_username" type="text" name="username" class="form-control"/>
    </div>
    <div class="form-group">
      <label class="control-label" for="username"><?=$this->transEsc('Email') ?>:</label>
      <input type="email" name="email" id="email" class="form-control"/>
    </div>
    <div class="form-group">
      <?=$this->recaptcha()->html($this->useRecaptcha) ?>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Recover Account') ?>"/>
    </div>
  </form>
<? endif; ?>
<!-- END of: finna - librarycards/recover.phtml -->
