<!-- START of: finna - librarycards/resetpassword.phtml -->
<?php
    // Set up page title:
    $this->headTitle($this->translate('Create New Password'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
        . '<li class="active">' . $this->transEsc('Create New Password') . '</li>';
?>
<h2><?=$this->transEsc('Create New Password') ?></h2>

<?=$this->flashmessages() ?>

<?php if (empty($this->hash)): ?>
  <div class="error"><?=$this->transEsc('recovery_user_not_found') ?></div>
<?php else: ?>
  <?php if (!$this->translationEmpty('reset_password_instructions')): ?>
    <div class="help-block"><?=$this->transEsc('reset_password_instructions') ?></div>
  <?php endif; ?>
  <form id="reset_password" action="<?=$this->url('librarycards-resetpassword') ?>" method="post" data-toggle="validator" autocomplete="off">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->hash) ?>" name="hash"/>
    <?php
      $pattern = '';
      if (isset($this->passwordPolicy['pattern'])) {
        if ($this->passwordPolicy['pattern'] == 'numeric') {
          $pattern = '\d+';
        } elseif ($this->passwordPolicy['pattern'] == 'alphanumeric') {
          $pattern = '[\da-zA-Z]+';
        } else {
          $pattern = $this->passwordPolicy['pattern'];
        }
      }
    ?>
    <div class="form-group">
      <div class="form-group">
        <label class="control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
        <p style="padding-top:7px;"><?=$this->transEsc('source_' . $this->target, null, $this->target)?></p>
      </div>
      <label class="control-label"><?=$this->transEsc('new_password') ?>:</label>
      <input type="password" id="password" name="password" class="form-control" required aria-required="true" value=""
        <?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->escapeHtmlAttr($this->translate('password_minimum_length', ['%%minlength%%' => $this->passwordPolicy['minLength']])) . '"' : ''?>
        <?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>
        <?=$pattern ? ' pattern="' . $pattern . '"' : '' ?>
      />
      <?php if (!empty($this->passwordPolicy['hint'])): ?>
        <div class="help-block"><?=$this->transEsc($this->passwordPolicy['hint']) ?></div>
      <?php endif; ?>
      <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
      <label class="control-label"><?=$this->transEsc('confirm_new_password') ?>:</label>
      <input type="password" name="password2" class="form-control" required aria-required="true" data-match="#password" data-match-error="<?=$this->escapeHtmlAttr($this->translate('Passwords do not match'))?>"/>
      <div class="help-block with-errors"></div>
    </div>
    <div class="form-group">
      <?=$this->captcha()->html($this->useCaptcha) ?>
    </div>
    <div class="form-group">
      <input class="btn btn-primary" name="submit" type="submit" value="<?=$this->transEsc('Submit')?>" />
    </div>
  </form>
<?php endif; ?>

<?php
// Set up validation; we do this inline instead of in the header for lightbox compatibility:
$js = <<<JS
  if ($.isReady) {
    $('#newPasswordForm').validator();
  } else {
    $(document).ready(function(){
      $('#newPasswordForm').validator();
    });
  }
JS;

echo $this->inlineScript()->appendScript($js);
?>
<!-- END of: finna - librarycards/resetpassword.phtml -->
