<?php // This can be used as a permission denied behavior; see example in permissionBehavior.ini... ?>
<?php $isLoggedin = $this->auth()->getUserObject() !== null; ?>
<?php if (!$isLoggedin): ?>
  <a class="login" href="<?=$this->url('myresearch-userlogin')?>">
    <strong><?=$this->transEsc('Login for full access')?></strong>
  </a>
<?php else: ?>
  <?=$this->transEsc('Your account only has guest access');?>
<?php endif; ?>
