<footer class="hidden-print">
  <div class="container">
    <?=$this->tuefind()->renderStaticTemplate('footer')?>
  </div>
  <a href="<?=$this->url('feedback-home')?>" data-lightbox="">
    <button id="tf-button-footer-feedback" class="btn float-left btn-outline-primary mx-1">
      <?=$this->transEsc('Feedback')?>
    </button>
  </a>
  <button id="tf-button-footer-back-to-top" class="btn float-right btn-outline-primary mx-5"
          data-toggle="tooltip" data-placement="left" title="Go to top">
    <i class="fa fa-chevron-up"> </i>
  </button>
</footer>