<!-- START of: finna - Recommend/CollectionSideFacets.phtml -->
<?
    $this->overrideSideFacetCaption = 'Filter Collection';
?>
<? if ($this->recommend->keywordFilterEnabled()): ?>
  <?
    $keywordFilter = $this->recommend->getKeywordFilter();
    if (!empty($keywordFilter)) {
      $this->extraSideFacetFilters = array(
        'Keyword' => array(
            array(
              'value' => $keywordFilter,
              'displayText' => $keywordFilter,
              'specialType' => 'keyword',
              'operator' => 'OR'
            )
        )
      );
    }
  ?>
  <? ob_start() ?>
  <div class="list-group filters">
    <div class="list-group-item">
      <h5>
        <?=$this->transEsc('Search from collection')?>
      </h5>
      <form class="form-inline" role="form" method="get" name="keywordFilterForm" id="keywordFilterForm">
        <input id="keywordFilter_lookfor" type="text" name="lookfor" value="<?=$this->escapeHtmlAttr($keywordFilter)?>" class="form-control"/>
        <? foreach ($this->recommend->getResults()->getParams()->getFilterList(true) as $field => $filters): ?>
          <? foreach ($filters as $filter): ?>
            <input type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($filter['field'])?>:&quot;<?=$this->escapeHtmlAttr($filter['value'])?>&quot;" />
          <? endforeach; ?>
        <? endforeach; ?>
        <button class="btn btn-primary btn-default" type="submit" name="submit"><span class="sr-only"><?=$this->transEsc('Search')?></span><i class="fa fa-search"></i></button>
      </form>
    </div>
  </div>
  <? $this->sideFacetExtraControls = ob_get_contents(); ?>
  <? ob_end_clean(); ?>
<? endif; ?>
<?=$this->render('Recommend/SideFacets.phtml')?>
<!-- END of: finna - Recommend/CollectionSideFacets.phtml -->
