<!-- START of: finna - Recommend/SearchTabs.phtml -->
<? if ($this->results->getResultTotal() > 0): ?>
  <div class="search-tabs-recommendations">
    <div class="row">
      <div class="col-sm-10 col-sm-push-2">
        <a class="title" href="<?=$this->escapeHtmlAttr($this->tab['url'])?>">
          <?=$this->translate('search_tabs_recommendation_title_html', ['%%lookfor%%' => $this->lookfor, '%%handler%%' => $this->handler, '%%tab%%' => $this->transEsc($this->tab['label']), '%%count%%' => $this->results->getResultTotal()]) ?>
        </a>
        <span class="count"><?=$this->transEsc('search_tabs_recommendation_count', ['%%count%%' => $this->localizedNumber($this->results->getResultTotal())]) ?></span>
        <? foreach ($this->results->getResults() as $current): ?>
          <div class="row result clearfix">
            <?=$this->record($current)->getSearchResult('list')?>
          </div>
        <? endforeach; ?>
      </div>
    </div>
  </div>
<? endif; ?>
<!-- END of: finna - Recommend/SearchTabs.phtml -->
