<!-- START of: finna - Recommend/SideFacets.phtml -->
<?
  $this->headScript()->appendFile('vendor/bootstrap-datepicker.min.js');
  $datePickerLang = 'en';
  switch ($this->layout()->userLang) {
    case 'en-gb':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.en-GB.min.js');
        $datePickerLang = 'en-GB';
        break;
    case 'fi':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.fi.min.js');
        $datePickerLang = 'fi';
        break;
    case 'sv':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.sv.min.js');
        $datePickerLang = 'sv';
        break;
  }
?>
<? $results = $this->recommend->getResults(); ?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?><? if (!$this->translationEmpty('tooltip_facet_html')): ?><span class="tooltip-facet pull-right" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?=$this->transesc('tooltip_facet_html')?>"><i class="fa fa-info-big"></i></span><? endif; ?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $availCount = $this->checkboxFacetCounts($current, $results);
    $availableRecords = $availCount < 0 ? '' : $this->localizedNumber($availCount);
    $html .= '<div class="checkbox';
    if ($current['selected']) {
      $html .= ' checked">';
    }
    else {
      $html .= '">';
    }
    $html .= '<label class="';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><span class="badge cb-facet">'.$availableRecords.'</span><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''. ($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label></div>';
  }
?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<? endif; ?>"><?=$html ?></div>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<? $newItemsFacets = $this->recommend->getNewItemsFacets(); ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<? $module = $this->layout()->templateDir; ?>
<?
   $daterangeFacetField = null;
   if (null === $module || in_array($module, ['search', 'primo'])) {
     $params = $results->getParams();
     $daterangeFacetField = $params->getSpatialDateRangeField();
     $plotFrom = null;
   }
?>
<?
    $queryHandler = 'AllFields';
    if ($results->getParams()->getSearchType() == 'basic') {
        $queryHandler = $results->getParams()->getQuery()->getHandler();
    }
    ?>
<?
  $customQueryHandler = $queryHandler != 'AllFields';
  if (isset($browse) && $browse) {
    $customQueryHandler = $customQueryHandler && $queryHandler != $defaultBrowseHandler;
  }
?>
<? if (!empty($filterList) || $customQueryHandler): ?>
  <div class="list-group filters">

      <? // Finna query handler (type) remove link ?>
      <? if ($customQueryHandler): ?>
        <? $removeLink = $results->getUrlQuery()->setHandler('AllFields'); ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <?=$this->transEsc('search_in_field'); ?>:
          <?=$this->transEsc($queryHandler); ?>
        </a>
      <? endif; ?>
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>">
          <span class="pull-right"><i class="fa fa-times"></i></span>
          <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <? endforeach; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
  <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <? $daterangeFacet = $title == $daterangeFacetField; ?>
    <div class="list-group facet<?= $daterangeFacet ? ' daterange-facet' : '' ?>" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <div class="list-group-item title<? if(in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" data-target="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
        <?=$this->transEsc($cluster['label'])?>
        <?
          if ($daterangeFacet) {
            $fromVal = $toVal = $type = null;
            $queryHelper = $results->getUrlQuery();
            $paramArray = $queryHelper->getParamArray();
            unset($paramArray["{$daterangeFacetField}_type"]);
            $searchParams = $formParams = '?' . $queryHelper->buildQueryString($paramArray, false);
            if ($spatialFilter = $params->getSpatialDateRangeFilter()) {
              if (isset($spatialFilter['val'])) {
                $formParams = $queryHelper->removeFacet($spatialFilter['field'], $spatialFilter['val'], false, 'AND', $paramArray);
              }
              $from = isset($spatialFilter['from']) ? $spatialFilter['from'] : null;
              $to = isset($spatialFilter['to']) ? $spatialFilter['to'] : null;
              $fromVal = $from != '*' ? $from : '';
              $toVal = $to != '*' ? $to : '';
              if (isset($spatialFilter['type'])) {
                $type =$spatialFilter['type'];
              }
              if ($params->getSearchType() != 'advanced') {
                $lookfor = $params->getQuery()->getString();
                if ($lookfor == '' && $fromVal === null && $toVal === null) {
                  $plotFrom = 0;
                }
              }
            }
          }
         ?>
      </div>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>">
        <? if (isset($newItemsFacets[$title])): ?>
          <?
            $newItemValues = [
              '7DAYS',
              '1MONTHS',
              '3MONTHS',
              '6MONTHS',
              '1YEAR'
            ];
          ?>
          <? foreach ($newItemValues as $newItemValue): ?>
            <? $addURL = $results->getUrlQuery()->replaceFacet($title, "[NOW-$newItemValue/DAY TO *]"); ?>
            <a href="<?=$addURL ?>" class="list-group-item facetAND"><?=$this->transEsc('new_items_' . strtolower($newItemValue), null, $newItemValue)?></a>
          <? endforeach; ?>
          <div class="list-group-item">
            <div class="row">
              <div class="col-sm-12">
                <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter" class="form-inline">
                  <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
                  <label for="<?=$this->escapeHtmlAttr($title)?>from"><?=$this->transEsc('new_items_from')?></label>
                  <input type="text" class="form-control form-inline date-picker-field" autocomplete="off" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" maxlength="10" size="10" value="<?=$this->escapeHtmlAttr($this->dateTime()->convertToDisplayDate('Y-m-d', $newItemsFacets[$title]['date'])) ?>" placeholder="<?=$this->dateTime()->getDisplayDateFormat() ?>">
                  <button class="btn btn-primary btn-default date-picker-button" type="submit" value=""><i class="fa fa-search"></i></button>
                </form>
<?
  $component = $this->escapeHtmlAttr($title) . 'from';
  $endDate = $this->dateTime()->convertToDisplayDate('U', time());
  $this->headScript()->appendScript(<<<EOT
$(document).ready(function() {
  $('#$component').datepicker({
    'language': '$datePickerLang',
    'format': 'd.m.yyyy',
    'weekStart': 1,
    'endDate': '$endDate',
    'autoclose': true
  });
});
EOT
  );
?>
              </div>
            </div>
          </div>

        <? elseif ($daterangeFacet): ?>
            <div class="list-group-item daterange">
              <?= $this->partial('Recommend/DateRangeVisAjax.phtml', [
              'submitLabel' => 'Update',
              'from' => $fromVal,
              'to' => $toVal,
              'formAction' => $formParams,
              'searchParams' => $searchParams,
              'baseParams' => $formParams,
              'facetField' => 'search_sdaterange_mv',
              'filterField' => 'main_date_str',
              'type' => $type,
              'backend' => (null === $module || $module == 'search') ? 'solr' : $module,
              'daterangeFacet' => $daterangeFacetField,
              'plotFrom' => $plotFrom
              ]);
              ?>
            </div>
        <? elseif (isset($rangeFacets[$title])): ?>
          <div class="list-group-item">
            <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
              <?=$results->getUrlQuery()->asHiddenFields(array('page' => "/./", 'filter' => "/^{$title}:.*/"))?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
              <div class="row">
                <? $extraInputAttribs = ($rangeFacets[$title]['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
                <div class="col-sm-12">
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][0]):''?>" <?=$extraInputAttribs?>/>
                  <span class="spacer"> - </span>
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][1]):''?>" <?=$extraInputAttribs?>/>
                </div>
              </div>
              <? if ($rangeFacets[$title]['type'] == 'date'): ?>
                <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
              <? endif; ?>
              <button class="btn btn-primary btn-default" type="submit" value=""><i class="fa fa-search"></i> <?=$this->transEsc('Update')?></button>
            </form>
          </div>
          <? if ($rangeFacets[$title]['type'] == 'date'): ?>
            <? $this->headScript()->appendFile('vendor/bootstrap-slider.js'); ?>
            <?
              $min = !empty($rangeFacets[$title]['values'][0]) ? min($rangeFacets[$title]['values'][0], 1400) : 1400;
              $future = date('Y', time()+31536000);
              $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, $rangeFacets[$title]['values'][1]) : $future;
              $low  = !empty($rangeFacets[$title]['values'][0]) ? $rangeFacets[$title]['values'][0] : $min;
              $high = !empty($rangeFacets[$title]['values'][1]) ? $rangeFacets[$title]['values'][1] : $max;
              $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
  .slider({
     'min':{$min},
     'max':{$max},
     'handle':"square",
     'tooltip':"hide",
     'value':[{$low},{$high}]
  })
  .on('slide', fillTexts)
  .data('slider');
});
JS;
            ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <? endif; ?>
        <? else: ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          <? $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
          <? $this->headScript()->appendFile('facets.js'); ?>
          <? $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
          <? if (!in_array($title, $collapsedFacets)): ?>
            <?
            $script = <<<JS
$(document).ready(function() {
  finna.layout.initHierarchicalFacet($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
            ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <? else: ?>
            <?
            $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  finna.layout.initHierarchicalFacet($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
            ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <? endif; ?>
          <div id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
                data-facet="<?=$this->escapeHtmlAttr($title)?>"
                data-path=""
                data-exclude="<?=$allowExclude?>"
                data-operator="<?=$this->recommend->getFacetOperator($title)?>"
                data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
                data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
          </div>
          <noscript>
        <? endif; ?>
        <? foreach ($cluster['list'] as $i=>$thisFacet): ?>
            <?
              if(strlen($thisFacet['displayText']) == 0) {
                $thisFacet['displayText'] = "-";
              }
            ?>
            <? $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
          <? if ($i == 6): ?>
            <a id="more-narrowGroupHidden-<?=$this->escapeHtmlAttr($title)?>" class="list-group-item more-narrow-toggle" href="javascript:moreFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('more')?>...<i class="fa fa-handle-open"></i></a>
          <? endif; ?>
          <? if ($thisFacet['isApplied']): ?>
            <a class="list-group-item active<? if ($i>5): ?><?=$moreClass ?><?endif ?><? if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<? endif ?>" href="<?=$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>">
              <? if ($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-check-square-o"></i>
              <? else: ?>
                <span class="pull-right"><i class="fa fa-check"></i></span>
              <? endif; ?>
              <?=$this->escapeHtml($thisFacet['displayText'])?>
            </a>
          <? else: ?>
            <? $addURL = $results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
            <? if ($allowExclude): ?>
              <div class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>5): ?> <?=$moreClass ?><?endif ?>">
            <? else: ?>
              <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><? if ($i>5): ?> <?=$moreClass ?><?endif ?>">
            <? endif; ?>
            <span class="badge">
              <?=$this->localizedNumber($thisFacet['count'])?>
              <? if ($allowExclude): ?>
                <a href="<?=$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times"></i></a>
              <? endif; ?>
            </span>
            <? if ($allowExclude): ?>
              <a href="<?=$addURL ?>">
            <? endif; ?>
            <? if($thisFacet['operator'] == 'OR'): ?>
              <i class="fa fa-square-o"></i>
            <? endif; ?>
            <?=$this->escapeHtml($thisFacet['displayText'])?>
            <? if ($allowExclude): ?>
                </a>
              </div>
            <? else: ?>
              </a>
            <? endif; ?>
          <? endif; ?>
        <? endforeach; ?>
          <? if ($i > 5): ?><a class="list-group-item <?=$moreClass ?> less-narrow-toggle" href="javascript:lessFacets('narrowGroupHidden-<?=$title ?>')"><?=$this->transEsc('less')?>...<i class="fa fa-handle-close"></i></a><? endif; ?>
        <? endif; ?>
        <? if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <? endif; ?>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!-- END of: finna - Recommend/SideFacets.phtml -->
