<!-- START of: finna - Recommend/SideFacets.phtml -->
<?
  $this->headScript()->appendFile('facets.js');

  // Save results/options to $this so they are available to sub-templates:
  $this->results = $results = $this->recommend->getResults();
  $this->options = $options = $results->getOptions();

  $this->headScript()->appendFile('vendor/bootstrap-datepicker.min.js');
  $datePickerLang = 'en';
  switch ($this->layout()->userLang) {
    case 'en-gb':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.en-GB.min.js');
        $datePickerLang = 'en-GB';
        break;
    case 'fi':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.fi.min.js');
        $datePickerLang = 'fi';
        break;
    case 'sv':
        $this->headScript()->appendFile('vendor/bootstrap-datepicker.sv.min.js');
        $datePickerLang = 'sv';
        break;
  }
?>
<? if ($results->getResultTotal() > 0): ?>
  <h4><i class="fa fa-arrow-down visible-xs pull-left"></i> <?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?><? if (!isset($this->overrideSideFacetCaption) && !$this->translationEmpty('tooltip_facet_html')): ?><span class="tooltip-facet pull-right" data-toggle="tooltip" data-placement="auto" data-html="true" data-original-title="<?=$this->transesc('tooltip_facet_html')?>"><i class="fa fa-info-big"></i></span><? endif; ?></h4>
<? endif; ?>
<? $checkboxFilters = $results->getParams()->getCheckboxFacets(); ?>
<? $checkboxesShown = false; ?>
<? if (count($checkboxFilters) > 0):
    foreach ($checkboxFilters as $current) {
      if ($results->getResultTotal() > 0 || $current['selected'] || $current['alwaysVisible']) {
        $checkboxesShown = true;
        break;
      }
    }
  ?>
  <?if ($checkboxesShown):?>
    <div class="checkboxFilter">
      <?=$this->context($this)->renderInContext('Recommend/SideFacets/checkbox-filters.phtml', ['checkboxFilters' => $checkboxFilters, 'results' => $results]); ?>
    </div>
  <? endif; ?>
<? endif; ?>
<? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<? $collapsedFacets = $this->recommend->getCollapsedFacets(); ?>
<? $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions(); ?>
<? $hierarchicalFacets = $this->recommend->getHierarchicalFacets(); ?>
<? $newItemsFacets = $this->recommend->getNewItemsFacets(); ?>
<? $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); ?>
<? $module = $this->layout()->templateDir; ?>
<?
  $plotFrom = null;
  $daterangeFacetField = null;
  if (null === $module || in_array($module, ['search', 'primo'])) {
    $options = $results->getOptions();
    if (is_callable([$options, 'getDateRangeSearchField'])) {
        $daterangeFacetField = $options->getDateRangeSearchField();
    }
    $dateRangeFilter = $params->getDateRangeFilter();
  }
?>
<?=$this->context($this)->renderInContext('Recommend/SideFacets/filter-list.phtml', [
    'collapsedFacets' => $collapsedFacets,
    'extraFilters' => $extraFilters,
    'filterList' => $filterList,
    'results' => $results,
    'browse' => !empty($browse),
    'defaultBrowseHandler' => isset($defaultBrowseHandler) ? $defaultBrowseHandler : ''
]); ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<? $sideFacetSet = $this->recommend->getFacetSet(); ?>
<? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <? foreach ($sideFacetSet as $title => $cluster): ?>
    <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <? $daterangeFacet = $title == $daterangeFacetField; ?>
    <div class="list-group facet<?= $daterangeFacet ? ' daterange-facet' : '' ?> facet-group" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <button class="list-group-item title<? if (in_array($title, $collapsedFacets)): ?> collapsed<? endif ?>" data-toggle="collapse" data-target="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" onclick="return false;"><?=$this->transEsc($cluster['label'])?></button>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<? if(!in_array($title, $collapsedFacets)): ?> in<? endif ?>" data-facet="<?=$this->escapeHtmlAttr($title) ?>">
        <?=$this->context($this)->renderInContext(
          'Recommend/SideFacets/facet.phtml',
          [
            'facet' => $title,
            'cluster' => $cluster,
            'collapsedFacets' => $collapsedFacets,
            'datePickerLang' => $datePickerLang
          ]
        ); ?>
      </div>
    </div>
  <? endforeach; ?>
<? endif; ?>
<!-- END of: finna - Recommend/SideFacets.phtml -->
