<!-- search - NEWITEM.phtml -->
<?
    // Set up page title:
    $this->headTitle($this->translate('New Item Search'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('New Items') . '</li>';
?>
<div class="row">
    <h2><?=$this->transEsc('Find New Items')?></h2>
    <form method="get">
      <div class="row">
        <label class="medium-3 columns"><?=$this->transEsc('Range')?>:</label>
    <div class="medium-9 columns">
      <div class="button-group">
          <? foreach ($this->ranges as $key => $range): ?>
          <label class="button small<? if($key == 0): ?> active<? endif ?>">
                <input type="radio" name="range" id="newitem_range_<?=$this->escapeHtmlAttr($key)?>" value="<?=$this->escapeHtmlAttr($range)?>"<?= ($key == 0) ? ' checked="checked"' : ''?>/>
                <?=($range == 1) ? $this->transEsc('Yesterday') : $this->transEsc('Past') . ' ' . $this->escapeHtml($range) . ' ' . $this->transEsc('Days')?>
          </label>
          <? endforeach; ?>
        </div>
      </div>
  </div>
      <? if (is_array($this->fundList) && !empty($this->fundList)): ?>
        <div class="row">
          <label class="medium-3 columns" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
          <div class="medium-9 columns">
            <select id="newitem_department" name="department" size="10" class="auto-width">
            <? foreach ($this->fundList as $fundId => $fund): ?>
              <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
            <? endforeach; ?>
            </select>
          </div>
        </div>
      <? endif; ?>
      <div class="row">
        <div class="medium-9 medium-offset-3 columns">
          <input class="button small" type="submit" name="submit" value="<?=$this->transEsc('Find')?>"/>
        </div>
      </div>
    </form>
</div>
<!-- search - NEWITEM.phtml end -->