<footer class="hidden-print ix-footer">
  <?php $routeParams = $this->tuefind()->getRouteParams();
        if($routeParams['controller'] == "index" && $routeParams['action'] == "Home"): ?>
          <section class="ix-footer-section">
            <div class="container">
              <?=$this->HelpText()->render('supporters', null, 'static')?>
            </div>
          </section>
  <?php endif;?>
  <section class="ix-footer-section ix-footer-background-block">
    <div class="container">
      <?=$this->HelpText()->render('footer', null, 'static')?>
    </div>
  </section>
  <a href="<?=$this->url('feedback-home')?>" data-lightbox="">
    <button id="tf-button-footer-feedback" class="btn float-left btn-outline-primary mx-1">
      <?=$this->transEsc('Feedback')?>
    </button>
  </a>
  <button id="tf-button-footer-back-to-top" class="btn float-right btn-outline-primary mx-5"
          data-toggle="tooltip" data-placement="left" title="Go to top">
    <i class="fa fa-chevron-up"> </i>
  </button>
</footer>