<? if (isset($this->username)): ?>
  <label class="span-4"><?=$this->transEsc('Username') ?>:</label>
  <input type="text" disabled value="<?=$this->username ?>"/><br/>
<? endif; ?>
<? if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <label class="span-4"><?=$this->transEsc('old_password') ?>:</label>
  <input type="password" name="oldpwd"/><br/>
<? endif; ?>
<label class="span-4"><?=$this->transEsc('new_password') ?>:</label>
<input type="password" name="password"/><br/>
<label class="span-4"><?=$this->transEsc('confirm_new_password') ?>:</label>
<input type="password" name="password2"/><br/>