<?php

function OnlyOrdered($signatures) {
  foreach ($signatures as $signature) {
    if (StartsWith("IFK: bestellt", $signature)) {
      return true;
    }
  }
  return false;
}

function StartsWith($prefix, $str) {
 return (substr($str, 0, strlen($prefix)) === $prefix);
}

$signatures = $this->driver->getLocalSignatures();

if (!OnlyOrdered($signatures)) {
  echo $this->transEsc('Available in Tubingen') . ".<br>";
}
foreach ($signatures as $signature) {
  echo $this->escapeHtml($signature) . "<br>";
}
?>
