<?
    // Set up page title:
    $this->headTitle($this->translate('Channels') . ' - ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('channels-home') . '">' . $this->transEsc('Channels') . '</a></li> <li class="active">' . $this->escapeHtml($this->driver->getBreadcrumb()) . '</li>';
?>
<?=$this->render('channels/channelList.phtml')?>
