<? $this->headScript()->appendFile('channels.js'); ?>
<? $this->headScript()->appendFile('vendor/flickity.pkgd.min.js'); ?>
<? $this->headLink()->appendStylesheet('vendor/flickity.min.css'); ?>
<? foreach ($channels as $key=>$channel): ?>
  <div class="channel-title">
    <? if (isset($channel['searchUrl'])): ?>
      <a href="<?=$channel['searchUrl'] ?>" class="pull-left"><i class="fa fa-fw fa-search" title="<?=$this->transEsc('Back to Search Results') ?>"></i></a>
    <? else: ?>
      <span class="placeholder pull-left">&nbsp;</span>
    <? endif; ?>
    <? if (isset($channel['channelsUrl'])): ?>
      <a href="<?=$channel['channelsUrl'] ?>" class="pull-left"><i class="fa fa-fw fa-plus-circle" title="<?=$this->transEsc('More Topics') ?>"></i></a>
    <? else: ?>
      <span class="placeholder pull-left">&nbsp;</span>
    <? endif; ?>
    <h2 class="pull-left"><?=$this->escapeHtml($channel['title'])?></h2>
  </div>
  <? $channelID = 'channel-' . $key; ?>
  <div id="<?=$channelID ?>" class="channel" style="clear:both">
    <!-- Wrapper for slides -->
    <? foreach ($channel['contents'] as $item): ?>
      <a href="<?=$this->recordLink()->getUrl("{$item['source']}|{$item['id']}")?>" class="channel-record" data-record-id="<?=$this->escapeHtmlAttr($item['id']) ?>" data-record-source="<?=$item['source'] ?>">
        <div class="img" style="background-image:url(<?=$this->escapeHtmlAttr($item['thumbnail'] ? $item['thumbnail'] : $this->url('cover-unavailable'))?>)"></div>
        <?=$this->escapeHtml($item['title'])?>
      </a>
    <? endforeach; ?>
  </div>
<? endforeach; ?>
