<? $this->headScript()->appendFile('channels.js'); ?>
<? $this->headScript()->appendFile('vendor/flickity.pkgd.min.js'); ?>
<? $this->headLink()->appendStylesheet('vendor/flickity.min.css'); ?>
<? foreach ($channels as $key=>$channel): ?>
  <h2><?=$this->escapeHtml($channel['title'])?></h2>
  <? $channelID = 'channel-' . $key; ?>
  <div id="<?=$channelID ?>" class="channel">
    <!-- Wrapper for slides -->
    <? foreach ($channel['contents'] as $item): ?>
      <a href="<?=$this->recordLink()->getUrl("{$item['source']}|{$item['id']}")?>" class="channel-record" data-record-id="<?=$this->escapeHtmlAttr($item['id']) ?>" data-record-source="<?=$item['source'] ?>">
        <div class="img" style="background-image:url(http://placehold.it/<?=rand(100, 150) ?>x<?=rand(150, 200) ?>)"></div>
        <?=$this->escapeHtml($item['title'])?>
      </a>
    <? endforeach; ?>
  </div>
<? endforeach; ?>
