<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'acquisition']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/librarians.jpg') ?>);"></div>
    </a>
    <div class="panel-content">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'acquisition']) ?>">
            <h4>Erwerbungsprofil</h4>
            <p></p>
        </a>
        <a href="/Feedback/Form/AcquisitionRequest" class="btn btn-default btn-panel-more" role="button"><?=$this->transEsc('Acquisition Request')?></a>
    </div>
</div>
