<div class="panel panel-top panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/research_data.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Forschungsdatenmanagement</h4>
            <p>Informationen zum Forschungsdatenmanagement</p>
        </div>
    </a>
</div>