<!-- two even columns
<div class="col-sm-6 left-column">
</div>
<div class="col-sm-6 right-column">
  <div class="introduction">
  </div>
</div>
<!-- end of two even columns -->

<!-- wider left column -->
<div class="col-sm-8 left-column">
</div>
<div class="col-sm-4 right-column">
  <div class="introduction">
  </div>
</div>
<!-- end of wider left column -->

<!-- one column -->
<div class="col-xs-12">
</div>
<!-- end of one column -->
