<!-- finc: search - filters -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * uses entire text + icon as link for larger interaction area, span moved into link
 * adds more detailed aria-label
 * removes normal view #22869
 * shows  for all sizes by default: removes 'visible-xs' #22869
 * adds class 'active' #22127
 * adds verbose reload warning via aria-label #22127
 * makes toggler accessible for tabbing: uses <a> and href instead of <div> and data-target #22869
configured in: {}
 */
?>
<?php
  if (!isset($this->params)) {
    // No current search, use last search in memory
    $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  } else {
    // clone params so that the manipulation doesn't cause trouble e.g. for facets
    $params = clone $this->params;
  }

  $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
  $options = $this->searchOptions($this->searchClassId);
  $hasDefaultsApplied = $params->hasDefaultsApplied();
  $filterCount = $this->searchbox()->getFilterCount($this->checkboxFilters, $this->filterList);

  // Determine whether the only filters applied are the default ones; this controls
  // when we display or hide the reset button:
  $defaultFilters = $options->getDefaultFilters();
  $onlyDefaultsApplied = count($defaultFilters) == $filterCount;
  foreach ($defaultFilters as $currentDefault) {
    if (!$params->hasFilter($currentDefault)) {
      $onlyDefaultsApplied = false;
      break;
    }
  }

  $advancedSearch = $this->searchType === 'advanced';
?>
<?php ob_start(); ?>
  <?php foreach ($this->checkboxFilters as $filter): ?>
    <?php if ($filter['selected']): ?>
      <span class="filter-value">
        <?php
          $removeLink = isset($urlQuery)
            ? $urlQuery->removeFilter($filter['filter'])
            : $this->searchMemory()->getEditLink(
                $this->searchClassId,
                'removeFilter',
                $filter['filter']
            );
          $desc = $this->translate($filter['desc']);
          $ariaLabel = $this->translate('Remove filter') . ' ' . $this->escapeHtmlAttr($desc);
        ?>
        <?=$desc?>
        <?php if($removeLink): ?>
          <a class="search-filter-remove" aria-label="<?=$ariaLabel?>" href="<?=$removeLink?>"><!--icon from css --></a>
        <?php endif; ?>
      </span>
    <?php endif ?>
  <?php endforeach; ?>

  <?php foreach ($filterList as $field => $data): ?>
    <div class="title-value-pair">
      <span class="filters-title"><?=$this->transEsc($field)?>:</span>
      <?php /* finc: sets number of filters visible (i.e. not displayed in dropdown to '> 5'
               so 5 and more filters from one group will be shown in a dropdown rather
               than as a long chain of terms -
               bootstrap3 has the default setting: '<?php if (count($data) > 3): ?>'
               CK */ ?>
      <?php if (count($data) > 5): ?>
        <div class="search-filter-dropdown dropdown">
          <?php $dropdown = true; ?>
          <?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $field); ?>
          <button id="dropdown-toggle-<?=$safeId?>" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            <?=$this->transEsc('filter_toggle_entries', ['%%count%%' => count($data)])?>
          </button>
          <ul class="dropdown-menu" role="menu" aria-labelledby="dropdown-toggle-<?=$safeId?>">
      <?php else: ?>
        <?php $dropdown = false; ?>
      <?php endif; ?>
      <?php foreach ($data as $index => $value): ?>
        <?php if ($dropdown): ?>
          <li>
        <?php endif; ?>
        <?php
          switch ($value['operator']) {
          case 'NOT':
            $operatorChar = '-';
            $join = $this->transEsc('NOT');
            break;
          case 'OR':
            $operatorChar = '~';
            $join = $this->transEsc('OR');
            break;
          case 'AND':
            $operatorChar = '';
            $join = $this->transEsc('AND');
            break;
          default:
            $operatorChar = $join = '';
          }
          $operatorClass = $this->escapeHtmlAttr(strtolower($value['operator']));
        ?>
        <span class="filters-term filters-<?=$operatorClass?>">
          <?=($index > 0 || 'NOT' === $value['operator']) ? $join : '' ?>
        </span>
        <span class="filter-value filters-<?=$operatorClass?>">
          <?php /* finc: uses entire text + icon as link for larger interaction area, span moved down into link */ ?>
          <?php
            $removeLink = isset($this->urlQuery)
              ? $urlQuery->removeFacet($value['field'], $value['value'], $value['operator'])
              : $this->searchMemory()->getEditLink($this->searchClassId, 'removeFacet', $value);
          ?>
            <?php /* finc: adds more detailed aria-label */ ?>
          <a class="search-filter-remove" aria-label="<?=$this->transEscAttr('clear_tag_filter') ?> &ndash; <?=$this->transEscAttr('page_reload_on_deselect_hint', ['%%filter_name%%' => $value['displayText']])?>"
             href="<?=$removeLink?>">
            <?php /* finc: moves <span> inside link */ ?>
            <span class="text">
              <?=$this->escapeHtml($value['displayText'])?>
            </span>
          </a>
        </span>
        <?php if ($dropdown): ?>
          </li>
        <?php endif; ?>
      <?php endforeach; ?>
      <?php if ($dropdown): ?>
          </ul>
        </div>
      <?php endif; ?>
    </div>
  <?php endforeach; ?>
<?php $filters = ob_get_contents(); ?>
<?php ob_end_clean(); ?>

<?php if ($hasDefaultsApplied || $filterCount > 0): ?>
  <?php
    $resetLink = null;
    if (!$onlyDefaultsApplied) {
      $resetLink = isset($urlQuery)
        ? $urlQuery->removeAllFilters()->resetDefaultFilters()
        : $this->searchMemory()->getEditLink($this->searchClassId, 'removeAllFilters', 1);
    }
  ?>
  <?php /* finc: removes normal view #22869 */ /*
  <?php // Normal view ?>
  <div class="active-filters hidden-xs">
    <?php if ($resetLink && $options->getRetainFilterSetting()): ?>
      <a class="reset-filters-btn" href="<?=$resetLink?>"><?=$this->transEsc('reset_filters_button')?></a>
    <?php elseif ($advancedSearch): ?>
      <p class="adv_search_filters"><?=$this->transEsc('adv_search_filters')?>:</p>
    <?php endif; ?>
    <div class="filters">
      <?=$filters ?>
    </div>
    <div class="clearfix"></div>
  </div>
  */ ?>
  <?php /* finc: Narrow view ?>
  <?php /* finc: shows this for all sizes by default: removes 'visible-xs' #22869 */
        /* adds ID and tabindex="0" for skip link on XS */ ?>
  <div id="filters-toggle-items" class="active-filters" tabindex="0">
    <h2 class="visible-xs-sr-only"><?=$this->transEscAttr('adv_search_filters') ?></h2>
    <div class="filters-toggle-bar">
      <?php if ($resetLink && $options->getRetainFilterSetting()): ?>
        <?php /* finc: adds class 'active' #22127 */ ?>
        <?php /* finc: adds verbose reload warning via aria-label #22127 */ ?>
        <a class="reset-filters-btn active" href="<?=$resetLink?>"
           aria-label="<?=$this->transEscAttr('clear_tag_filter') ?> &ndash; <?=$this->transEscAttr('page_reload_on_deselect_all_hint', ['%%filter_name%%' => $value['displayText']])?>">
          <?=$this->transEsc('reset_filters_button')?>
        </a>
      <?php endif; ?>
      <?php /* finc: makes toggler accessible for tabbing: uses <a> and href instead of <div> and data-target #22869 */ ?>
      <a class="filters-toggle collapsed hidden-xs" data-toggle="collapse" href="#active-filters-mobile">
        <?=$this->transEsc('show_filters_html', ['%%count%%' => $filterCount])?>
      </a>
      <div class="clearfix"></div>
    </div>
    <div id="active-filters-mobile" class="filters filters-bar collapse">
      <?=$filters ?>
    </div>
    <div class="clearfix"></div>
  </div>
<?php endif; ?>
<!-- finc: search - filters - END -->
