<!-- finc: templates - search - history -->
<?php
/**
* origin: vufind/BS3
* called by view helper/controller:  --
* usage: (saved) search history
* modified for finc:
 * special finc behavior:
   * not logged in:
   ** does not show offcancas-toggler and profile menu
   ** breadcrumb like: Home -> History
   * logged in:
   ** shows offcancas-toggler and profile menu
   ** breadcrumb like: Home -> My Account -> History
 * DOES NOT use 'Your Account' offcanvas-toggler here
 * adds h1 here for correct headings' hierarchy
* configured in: --
 */
?>
<?php
  // Set page title.
  $this->headTitle($this->translate('Search History'));

  $saveSupported = $this->accountCapabilities()->getSavedSearchSetting() === 'enabled';
  // finc: adds $isLoggedIn
  $isLoggedIn = $this->auth()->isLoggedIn();

  // Set up breadcrumbs:
  // finc: adapts breadcrumbs depending on $isLoggedIn
  $this->layout()->breadcrumbs = (
      $isLoggedIn ? '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li>'
    : '') . '<li class="active">' . $this->transEsc('History') . '</li>';
?>

<?php /* finc: DOES NOT use 'Your Account' offcanvas-toggler here
<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
  <?=$this->transEsc('Your Account') ?>
</a>
*/ ?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <?php /* finc: shows  offcanvas-toggler and profile-menu only when if $isLoggedIn */ ?>
  <?php if ($isLoggedIn): ?>
    <?=$this->render('RecordDriver/DefaultRecord/offcanvas-toggler-myresearch'); ?>
  <?php endif; ?>

  <?php /* finc: adds h1 here for correct headings' hierarchy */ ?>
  <h1><?=$this->transEsc('Search History')?></h1>

  <?php if (!empty($this->alertemail)): ?>
    <div class="alert alert-info alert-email-notification">
      <?=$this->transEsc("alert_email_address") . ': ' . $this->escapeHtml($this->alertemail) ?>
      <?php if ($this->auth()->getManager()->supportsEmailChange()): ?>
        (<a href="<?=$this->url('myresearch-profile');?>"><?=$this->transEsc("edit");?></a>)
      <?php endif; ?>
    </div>
  <?php elseif (!empty($this->schedule) && $isLoggedIn): ?>
    <div class="alert alert-danger alert-email-notification">
      <?=$this->transEsc("no_email_address") . ' ';?><a href="<?=$this->url('myresearch-profile');?>"><?=$this->transEsc("check_profile");?></a>
    </div>
  <?php endif; ?>
  <?=$this->flashmessages()?>
  <?php if ($saveSupported && !empty($this->saved)): ?>
    <h2><?=$this->transEsc("history_saved_searches")?></h2>
    <?=$this->context()->renderInContext('search/history-table.phtml', ['showSaved' => true]);?>
  <?php endif; ?>

  <h2><?=$this->transEsc("history_recent_searches")?></h2>
  <?php if (!empty($this->unsaved)): ?>
    <?=$this->context()->renderInContext('search/history-table.phtml', ['showSaved' => false]);?>
    <a href="?purge=true"><i class="fa fa-remove" aria-hidden="true"></i> <?=$this->transEsc("history_purge")?></a>
  <?php else: ?>
    <?=$this->transEsc("history_no_searches")?>
  <?php endif; ?>
</div>

<?php /* finc: shows  offcanvas-toggler and profile-menu only if $isLoggedIn #22938 */ ?>
<?php if ($isLoggedIn): ?>
  <?php /* finc: uses section for sidebar #23430; adds aria-label */ ?>
  <section class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" aria-label="<?=$this->transEscAttr('MyAccountSidebar') ?>">
    <?=
      $this->context($this)->renderInContext(
          "myresearch/menu.phtml",
          // apply active highlighting in profile-menu; check for $isLoggedIn is alread above
          ['active' => 'history']
      );
    ?>
  </section>
<?php endif; ?>

<?php
    $explanation = $this->transEsc('schedule_explanation');
    $script = <<<JS
$(".search-schedule-header").popover({
    content: "$explanation",
    placement: "top",
    trigger: "hover",
    container: "body",
})
JS;
?>
<?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>
<!-- finc: templates - search - history - END -->
