<h2>Acquisition profile</h2>
<p>The Criminological Information Service (Fachinformationsdienst Kriminologie – FID) acquires literature relevant to criminology. This applies to strictly criminological literature, but also other literature relevant to criminology in the further sense and literature of relating fields such as sociology, psychology, pedagogy and law.</p>

<h3>I. Core area</h3>
<ul>
    <li>Criminology and criminalization</li>
    <li>Politics and criminology</li>
    <li>Prevention of crime</li>
    <li>Prognosis and treatments in criminology</li>
    <li>Predator identities, predator categories and predator groups</li>
    <li>Victimology</li>
    <li>Prosecution ad informal sanctioning</li>
    <li>Punishments and reprimands as well as execution of sentence</li>
    <li>Penal system, juvenile penal system and forensic psychiatry</li>
    <li>Monitoring of predators and predator treatment in freedom</li>
    <li>Alternatives to classic criminal justice (transitional justice, restorative justice, predator-victim-agreements etc)</li>
</ul>

<h3>II. Peripheral areas</h3>
Criminological aspects
<ul>
    <li>of social problems</li>
    <li>of law, economy and society</li>
    <li>socialization and informal social control</li>
    <li>institutions and methods of formal social control</li>
    <li>normativity of society (formation of norms, setting standards, breaking standards and social reaction)</li>
</ul>
