<h2>Weitere Kataloge und Datenbanken</h2>

<h3>Nationale Rechercheangebote</h3>
<ul>
    <li><a target="_blank" href="http://www.dpt-map.de">DPT-Map</a> – Suchportal Kriminalprävention</li>
    <li><a target="_blank" href="http://rzblx1.uni-regensburg.de/ezeit/fl.phtml?bibid=UBTUE&amp;colors=7&amp;lang=de&amp;notation=P">EZB</a> – Elektronische Zeitschriftenbibliothek</li>
    <li><a target="_blank" href="http://staatsbibliothek-berlin.de/recherche/fachgebiete/rechtswissenschaft/">FID Recht</a> – Fachinformationsdienst Internationale und interdisziplinäre Rechtsforschung</li>
    <li><a target="_blank" href="https://www.praeventionstag.de/nano.cms/forschungsprojekte">Krimdex</a> – DPT-Datenbank zu Forschungsprojekten der Kriminalprävention und Kriminologie</li>
    <li><a target="_blank" href="https://www.krimz.de/literaturdokumentation.html">KrimLit</a> – Literaturdokumentation der Kriminologischen Zentrale</li>
    <li><a target="_blank" href="https://kvk.bibliothek.kit.edu/index.html">KVK</a> – Karlsruher Virtueller Katalog (nationale und internationale Meta-Suchmaschine)</li>
    <li><a target="_blank" href="https://www.mpicc.de/de/bibliothek.html">MPI-Freiburg</a> – Elektronischer Katalog des MPI für ausländisches und internationales Strafrecht</li>
    <li><a target="_blank" href="http://sunrise.rg.mpg.de/webOPAC/">MPI-Frankfurt/Main</a> – OPAC des MPI für Europäische Rechtsgeschichte</li>
    <li><a target="_blank" href="http://rvk.uni-regensburg.de/index.php/regensburger-verbundklassifikation-online">RVK-Online</a> – Systematische Katalogsuche zu ca. 30 Fachdisziplinen</li>
    <li><a target="_blank" href="http://swb.bsz-bw.de/?COOKIE=U998,Pbszgast,I17,B0728+,SY,NRecherche-DB,D2.1,Ef6c6c7ad-3ac,A,H,R193.197.31.15,FY">SWB-Online</a> – Katalog-Suchmaschine des Südwestdeutschen Bibliotheksverbundes</li>
    <li><a target="_blank" href="http://dispatch.opac.dnb.de/DB=1.1/">ZDB</a> – Zeitschriftendatenbank</li>
</ul>

<h3>Internationale Rechercheangebote (auch von Verlagen)</h3>
<ul>
    <li><a target="_blank" href="https://dialnet.unirioja.es/">Dialnet</a> – spanische Datenbank (z.T. mit Volltexten)</li>
    <li><a target="_blank" href="http://njlaw.rutgers.edu/cj/gray/index.php">Gray-Literature Database</a> – Datenbank zu grauer Literatur im Bereich „Criminal Justice“ (Rutgers University Newark/NJ)</li>
    <li><a target="_blank" href="http://www.iisj.net/en/library/about-library">IISL Library Catalogue</a> – Online-Katalog des Oñati International Institute for the Sociology of Law</li>
    <li><a target="_blank" href="https://www.ncjrs.gov/App/AbstractDB/AbstractDBSearch.aspx">NCJRS-Abstracts</a> – Database National Criminal Justice Reference Service, NIJ-USA</li>
    <li><a target="_blank" href="https://www.ncjrs.gov/library.html">NCJRS-Virtual Library</a> – Meta-Suchmaschine zu Bibliotheken und Datenbanken</li>
    <li><a target="_blank" href="http://online.sagepub.com/">Sage-Journals Online</a> – Systematische Recherchen im Zeitschriftenbestand. (Abstracts frei)</li>
    <li><a target="_blank" href="http://link.springer.com/">SpringerLink</a> – Systematische Recherchen im Dokumentenbestand (Abstracts frei)</li>
    <li><a target="_blank" href="http://www.unicri.it/services/library_documentation/catalogue_thesaurus/catalogue.php">UNICRI Library Catalogue</a> – Crime and Criminal Justice Research Documents</li>
    <li><a target="_blank" href="https://www.questia.com/library/criminal-justice/criminology-and-crime/victimology">Victimology Database</a> – Nachweise von Artikeln und Büchern</li>
    <li><a target="_blank" href="http://www.worldsocietyofvictimology.org/resources/publications/un-wsv-documents/">Victimology United Nations + WSV</a> – Dokumente der UNO und der WSV</li>
</ul>

<h3>IfK-Linksammlung Kriminologie</h3>
<ul>
    <li><a target="_blank" href="https://uni-tuebingen.de/fakultaeten/juristische-fakultaet/forschung/institute-und-forschungsstellen/institut-fuer-kriminologie/institutsstartseite/linksammlung-kriminologie/">Verzeichnis nationaler, europäischer und internationaler Einrichtungen</a></li>
</ul>
