<h1>Habilitationen und Berufungen</h1>
<p>
    Neuigkeiten zu Habilitationen und Berufungen werden wörtlich aus der Zeitschrift "Forschung und Lehre" übernommen und mittels Zuschriften durch Nutzer des FID Kriminologie um den Bereich der Hochschulen für Angewandte Wissenschaften ergänzt.
</p>

<h2>November 2017</h2>
<ul>
    <li>Prof. Dr. Bettina <b>Noltenius</b>, Ruhr-Universität Bochum, hat einen Ruf an die Universität Passau auf eine W3-Professur für Strafrecht, Strafprozessrecht, Rechtsphilosophie und Kriminologie angenommen.</li>
</ul>

<h2>Juni 2017</h2>
<ul>
    <li>Prof. Dr. Wolfgang <b>Knöbl</b>, Hamburger Institut für Sozialforschung, hat einen Ruf an die Leuphana Universität Lüneburg auf die nebenberufliche W3-Professur für Politische Soziologie und Gewaltforschung angenommen.</li>
</ul>

<h2>März 2017</h2>
<ul>
    <li>Dr. Alexander <b>Baur</b>, Stuttgart, hat einen Ruf an die Universität Hamburg auf eine W1-Juniorprofessur für Strafrecht zum 1. April 2017 angenommen.</li>
</ul>

<h2>November 2016</h2>
<ul>
    <li>PD Dr. Jens <b>Puschke</b>, LL.M (King's College), Albert-Ludwigs-Universität Freiburg, hat einen Ruf an die Philipps-Universität Marburg auf eine W3-Professur für Strafrecht und Strafprozessrecht angenommen.</li>
    <li>Prof. Dr. Tobias Singelnstein, Freie Universität Berlin, hat einen Ruf an die Ruhr-Universität Bochum auf eine W3-Professur für Kriminologie erhalten.</li>
</ul>

<h2>August 2016</h2>
<ul>
    <li>Prof. Dr. Tobias <b>Singelnstein</b>, Freie Universität Berlin, habilitierte sich, und es wurde ihm die Lehrbefähigung für die Fächer Strafrecht, Strafprozessrecht, Kriminologie, Wirtschaftsstrafrecht und Rechtstheorie zuerkannt.</li>
</ul>

<h2>April 2016</h2>
<ul>
    <li>Dr. Christine <b>Hentschel</b>, Universität Hamburg, hat einen Ruf an die Universität Hamburg auf eine W2-Professur für Kriminologie, insbesondere Sicherheit und Resilienz, angenommen.
</ul>
