<h2>Konferenzen, Tagungen und Veranstaltungen</h2>

<h2>2020</h2>

<h3>Februar</h3>
<ul>
    <li>10.-11.2.2020, Meißen: <a target="_blank" href="https://www.hammerweg.eu/pages/projekte/meissener-tagung.php">Auf dem Weg zu freien Formen des Justizvollzugs. Resozialisierung mit Haftvermeidung realisieren</a></li>
    <li>11.2.2020, Tübingen: <a target="_blank" href="https://www.jura.uni-tuebingen.de/professoren_und_dozenten/haverkamp/aktuelles/wissenschaftliches-symposium-11-02.2020">Symposium: Auf den Spuren der kommunalen Kriminalprävention in Deutschland</a></li>
    <li>14.-15.2.2020, Bad Boll: <a target="_blank" href="https://www.ev-akademie-boll.de/tagung/520620.html">Alles neu im Jugendstrafverfahren? Die Umsetzung der EU-Richtlinie über Verfahrensgarantien in Strafverfahren für Kinder</a></li>
    <li>28.2-1.3.2020, Chennai (Indien): <a target="_blank" href="https://isvindia.webs.com/ISV%20Conference%202020_University%20of%20Madras_India.pdf">Seventh International and Eleventh Biennial Conference of the Indian Society of Victimology</a></li>
</ul>

<h3>März</h3>
<ul>
    <li>4.-6.3.2020, Heidelberg: <a target="_blank" href="https://www.jura.uni-heidelberg.de/krimi/Conference.html">Conference on Crime and Punishment: Eastern and Western Perspectives on Recent and Fundamental Criminological Questions</a></li>
    <li>4.-6.3.2020, Interlaken (Schweiz): <a target="_blank" href="http://kriminologie.ch/programm_d.html">Tagung: Strafjustiz zwischen künstlicher Intelligenz und prädiktiven Algorithmen</a></li>
    <li>12.-13.3.2020, Berlin: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/ausschreibung_und_programm_0.pdf">6. Bewährungshilfetag in der Schleswig-Holsteinischen Landesvertretung in Berlin</a></li>
    <li>12.-13.3.2020, Frankfurt / Oder: <a target="_blank" href="https://rechtssoziologie.info/aktivitaeten/tagungen-workshops/">Workshop: Socio-Legal Perspectives on the Rule of Law</a></li>
    <li>13.3.2020, Tübingen: <a target="_blank" href="https://www.medizin.uni-tuebingen.de/uktmedia/EINRICHTUNGEN/Kliniken/Klinik+fuer+Psychiatrie+und+Psychotherapie/Abt_+Allgemeine+Psychiatrie/PDF_Archiv/Veranstaltungen/FPG2020.pdf">15. Forensisch-psychiatrisches Gespräch</a></li>
    <li>25.-26.3.2020, Bielefeld: <a target="_blank" href="https://uni-bielefeld.com/(de)/ZiF/AG/2020/03-25-Althoff.html">Tagung: Krimmigration. Zur Verschmelzung von Kriminalitätskontrolle und Migrationskontrolle</a></li>
    <li>26.-27.3.2020, Münster: <a target="_blank" href="https://www.kriminologie-nrw.de/Programm.html">2. Tagung des Netzwerks Kriminologie in NRW</a></li>
    <li>31.3-1.4.2020, Oxford (UK): <a target="_blank" href="https://howardleague.org/events/crime-justice-and-social-harms/">Tagung: Crime, Justice and Social Harms</a></li>
</ul>

<h3>April</h3>
<ul>
    <li>2.-3.4.2020, Ingolstadt: <a target="_blank" href="https://soziologie.de/kalender/c/e/2020/4/2/148">Tagung: Sicherheit und sozialer Zusammenhalt. Disorder-Phänomene in Stadt und Land</a></li>
    <li>22.-23.4.2020, Duisburg: <a target="_blank" href="https://www.awo-ha-mk.de/Fachtagung-Sucht">4. Fachtagung Maßregelvollzug und Sucht: Recht, Sucht, Gesellschaft im Wandel</a></li>
    <li>24.4.2020, Münster: <a target="_blank" href="https://kripoz.de/kripoz-tagung-darknet/">KriPoZ-Tagung: Darknet</a></li>
    <li>27.-28.4.2020, Kassel: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/jahreskongress">25. Deutscher Präventionstag</a></li>
</ul>

<h3>Mai</h3>
<ul>
    <li>8.-9.5.2020, Leipzig: <a target="_blank" href="https://medienstrafrecht.jura.uni-leipzig.de/institut-fuer-medienrecht-und-digitalisierung/tagung-digitalisierung-und-strafrecht-89-mai-2020/">Tagung: Strafrecht und Digitalisierung</a></li>
    <li>18.-19.5.2020, Fulda: <a target="_blank" href="https://www.dbh-online.de/bildungswerk/fachtagung/save-date-fachtagung-fuehrungsaufsicht-2020">DBH Fachtagung Führungsaufsicht</a></li>
    <li>18.-30.5.2020, Dubrovnik (Kroatien): <a target="_blank" href="https://www.iuc.hr/course-details.php?id=1199">XXXVI Postgraduate Course of Victimology, Victim Assistance and Criminal Justice</a></li>
</ul>

<h3>Juni</h3>
<ul>
    <li>2.-4.6.2020, Augsburg: 56. Kolloquium der Südwestdeutschen und Schweizerischen Kriminologischen Institute und Lehrstühle (noch kein Online-Auftritt vorhanden)</li>
    <li>5.-7.6.2020, Greifswald: NORDKRIM-Tagung 2020 (noch kein Online-Auftritt vorhanden)</li>
    <li>9.-11.6.2020, Stockholm: <a target="_blank" href="https://www.criminologysymposium.com/">The Stockholm Criminology Symposium: Recognizing  Knowledge  to  Reduce  Crime  and  Injustice</a></li>
    <li>11.-13.6.2020, Genua (Italien): <a target="_blank" href="https://www.narrcrimgenoa2020.info/">Third Narrative Criminology Symposium: Fiction and Nonfiction in Narrative Criminology</a></li>
</ul>

<h3>Juli</h3>
<ul>
    <li>6.-7.7.2020, Frankfurt (Main): <a target="_blank" href="https://www.dbh-online.de/">13. DBH Fachtagung Übergangsmanagement</a></li>    
    <li>8.-10.7.2020, Liverpool (GB): <a target="_blank" href="https://www.liverpool.ac.uk/sociology-social-policy-and-criminology/events/bsc-2020/">British Society of Criminology Annual Conference: Criminology in an Age of Global Injustice(s)</a></li>
    <li>27.-31.7.2020, Kochel am See: <a target="_blank" href="https://www.sifo-dialog.de/graduiertennetz/sommerakademie-2">Sommerakademie 2020: Zivile Sicherheit im Digitalzeitalter</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>1.-4.9.2020, Frankfurt/M: <a target="_blank" href="https://www.iatso.org/index.php/iatso-conferences/frankfurt-2020">16th conference of the International Association for the Treatment of Sexual Offenders (IATSO): Current Developments in Etiology, Assessment, and Prevention of Sexual Offending</a></li>
    <li>3.-6.9.2020, Bonn: <a target="_blank" href="https://www.dvjj.de/jugendgerichtstage/31-jugendgerichtstag-2020/">31. Deutscher Jugendgerichtstag: Jugend, Recht und Öffentlichkeit - Selbstbilder, Fremdbilder, Zerrbilder</a></li>
    <li>9.-12.9.2020, Bukarest (Rumänien): <a target="_blank" href="http://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">20th Annual Conference of the European Society of Criminology</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>1.-10.11.2020 (voraussichtlich), bundesweit: <a target="_blank" href="https://www.aktionstage-gefaengnis.de/">Aktionstage Gefängnis</a></li>
    <li>4.-5.11.2020, Hannover: <a target="_blank" href="https://soziologie.de/fileadmin/user_upload/calls/2020/20-01_Call_Qualitative_Kriminologie.pdf">Tagung: Quo vadis Qualitative Kriminologie?</a></li>
    <li>17.-18.11.2020, Bonn: Bundestagung der BAG-S: Drogenpolitik – Einfallstor in die Straffälligkeit? (noch kein Online-Auftritt vorhanden)</li>
    <li>18.-21.11.2020, Washington D.C. (USA): <a target="_blank" href="https://www.asc41.com/annualmeeting.html">Annual Conference of the American Society of Criminology: Crime and Justice Theory and Research: Thinking Outside the Box</a></li>
    <li>23.-24.11.2020, Berlin: <a target="_blank" href="https://www.dbh-online.de/">Fachtagung "Straffälligkeiten & Digitalisierung - Chancen, Grenzen, Perspektiven"</a></li>
</ul>
