<h2>Konferenzen, Tagungen und Veranstaltungen</h2>

<h2>2022</h2>

<h3>September</h3>
<ul>
    <li>19.-20.9.2022, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-nuernberg-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
    <li>21.-24.9.2022, Málaga (Spanien): <a target="_blank" href="http://esc-eurocrim.org/">EUROCRIM 2022: 22. Annual Conference of the European Society of Criminology</a></li>
    <li>22.-23.9.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/8-praxistagung-jugendstrafvollzug-online/">DVJJ-Fachtagung: 8. Praxistagung Jugendstrafvollzug</a></li>
    <li>22.-23.9.2022, ONLINE: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/g-0122_web-seminar_ausschreibung.pdf">Web-Seminar: Desistance from crime - Ausstieg aus kriminellen Karrieren</a></li>
    <li>26.9.2022, Leonberg: <a target="_blank" href="https://seehaus-ev.de/sh/fachtag-straffaelligenhilfe/">Fachtag Straffälligenhilfe: Alternativen im Strafvollzugssystem - unterschiedliche Formen des Wohngruppenvollzugs</a></li>
</ul>

<h3>Oktober</h3>
<ul>
    <li>4.-5.10.2022, Hannover: <a target="_blank" href="https://www.praeventionstag.de/nano.cms/jahreskongress">27. Deutscher Präventionstag: Kinder im Fokus der Prävention</a></li>
    <li>4.-6.10.2022, Hofgeismar: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-hofgeismar-3/">Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
    <li>13.10.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/entkriminalisierung-von-cannabis-fakten-herausforderungen-offene-fragen-online/">Entkriminalisierung von Cannabis – Fakten, Herausforderungen, offene Fragen | Online (für DVJJ-Mitglieder)</a></li>
    <li>26.-28.10.2022, Essen: <a target="_blank" href="https://www.dhs-fachkonferenz.de/">61. DHS Fachkonferenz SUCHT: Die Sucht- und Drogenpolitik der Gegenwart und Zukunft.</a></li>
    <li>28.10.2022, Kiel: <a target="_blank" href="https://www.soziale-strafrechtspflege.de/attachments/article/456/Save%20the%20date.pdf">SAVE THE DATE: 30. Fachtagung des Schleswig-Holsteinischen Verbandes für soziale Strafrechtspflege</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>7.-8.11.2022, Bonn: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/b-2322_ausschreibung_grundlagenseminar.pdf">Grundlagenseminar: Umgang mit Sexualstraftätern – professionelle Haltung, Menschenbild, Unterstützungsangebote</a></li>
    <li>7.-9.11.2022, Köln: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-koeln/">DVJJ-Seminar: Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
    <li>14.-15.11.2022, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-nuernberg-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
    <li>18.11.2022, Aschaffenburg: <a target="_blank" href="https://www.dbh-online.de/aktuelles/restorative-justice-fachtag-am-18112022-aschaffenburg-jetzt-anmelden">Restorative Justice-Fachtag: „Ich möchte keine Entschuldigung, ich möchte mein Leben zurück!“: Von Chancen und Grenzen einer Restorative Justice bei sexualisierter Gewalt.</a></li>
    <li>24.-25.11.2022, ONLINE: <a target="_blank" href="https://kfn.de/wp-content/uploads/2022/03/Call%20for%20Papers_final.pdf">Gender & Crime - Sexuelle Selbstbestimmung und geschlechtsspezifische Gewalt</a></li>
</ul>

<h2>2023</h2>

<h3>Februar</h3>
<ul>
    <li>13.-14.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter StraftäterInnen I</a></li>
    <li>23.-24.2.2023, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten I</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>6.-9.9.2023, Florenz (Italien): <a target="_blank" href="https://www.esc-eurocrim.org/index.php/conferences/upcoming-conferences">EUROCRIM 2023: 23. Annual Conference of the European Society of Criminology</a></li>
    <li>15.-18.9.2023, Berlin: <a target="_blank" href="https://www.dvjj.de/veranstaltung/32-deutscher-jugendgerichtstag-2023/">DVJJ Fachtagung: 32. Deutscher Jugendgerichtstag 2023</a></li>
</ul>
