<h2>Congresses and conferences</h2>

<h2>2021</h2>

<h3>November</h3>
<ul>
    <li>12.-13.11.2021, Leipzig: <a target="_blank" href="https://www.ag-strafrecht.de/herbstkolloquium/38-herbstkolloquium-2021/">38.Herbstkolloquium 2021: Kommunikation im Strafverfahren</a></li>
    <li>12.11.-3.12.2021, ONLINE: <a target="_blank" href="https://www.toa-servicebuero.de/sites/default/files/seminare/attachments/2021-11_onlineseminar_interkulturelle_kompetenz_in_der_mediation.pdf">Lebendige, praxisorientierte Onlineveranstaltungsreihe zu interkultureller Konfliktlösung und Mediation: Interkulturelle Kompetenz in der Mediation</a></li>
    <li>15.-16.11.2021, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-nuernberg/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
    <li>15.-17.11.2021, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/frei-sprechen-souveraen-auftreten-als-jugendhilfe-im-strafverfahren-online/">DVJJ-Seminar: Frei sprechen, souverän auftreten & locker präsentieren – Ein Präsentationstraining für Pädagog*innen</a></li>
    <li>24.-25.11.2021, Lausanne/ONLINE: <a target="_blank" href="https://www.skjv.ch/en/austausch/forum-detention-and-probation">Fourth Forum on Detention and Probation 2021: Education- a driver for change</a></li>
    <li>25.-26.11.2021, ONLINE: <a target="_blank" href="https://kfn.de/wp-content/uploads/2021/03/Call_for_Papers_Gender_and_Crime.pdf">Gender & Crime - Geschlechteraspekte in Kriminologie und Strafrechtswissenschaft</a></li>
    <li>29.11.-1.12.2021, Erfurt: <a target="_blank" href="https://www.fachwoche.de/">Fachwoche Straffälligenhilfe 2021: Gefangen - bis der Tod uns scheidet.</a></li>
</ul>

<h3>December</h3>
<ul>
    <li>08.12.2021, Münster: <a target="_blank" href="https://www.dvjj.de/veranstaltung/haeuser-des-jugendrechts-chancen-risiken-und-nebenwirkungen-aus-perspektive-der-jugendhilfe/">DVJJ-Fachtagung: Häuser des Jugendrechts – Chancen, Risiken und (Neben)wirkungen aus Perspektive der Jugendhilfe</a></li>
    <li>13.-14.12.2021, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/ich-packe-auch-online-meinen-methodenkoffer-und-nehme-mit-online-2/">Ich packe – auch online – meinen Methodenkoffer und nehme mit…</a></li>
</ul>

<h2>2022</h2>

<h3>January</h3>
<ul>
    <li>24.-25.1.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/sexualisierte-uebergriffe-an-kindern-und-jugendlichen-umgang-und-arbeit-mit-sexualisiert-gewalttaetigen-jugendlichen-und-jungen-maennern-nuernberg-2/">Sexualisierte Übergriffe an Kindern und Jugendlichen: Umgang und Arbeit mit sexualisiert gewalttätigen Jugendlichen und jungen Männern</a></li>
</ul>

<h3>February</h3>
<ul>
    <li>21.2.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/restorative-justice-mit-jugendlichen-taeter-opfer-ausgleich-im-jgg/">DVJJ-Seminar: Restorative Justice mit Jugendlichen – Täter-Opfer-Ausgleich im JGG </a></li>
    <li>21.-22.2.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
</ul>

<h3>March</h3>
<ul>
    <li>7.-8.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
    <li>8.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/das-gesetz-zur-staerkung-der-verfahrensrechte-von-beschuldigten-im-jugendstrafverfahren-auswirkungen-fuer-die-praxis-online-2/">DVJJ-Seminar: Das Gesetz zur Stärkung der Verfahrensrechte von Beschuldigten im Jugendstrafverfahren – Auswirkungen für die Praxis</a></li>
    <li>31.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/oertliche-zustaendigkeit-fuer-die-mitwirkung-des-jugendamts-in-jugendgerichtlichen-verfahren-online-5/">DVJJ-Seminar: Örtliche Zuständigkeit für die Mitwirkung des Jugendamts in jugendgerichtlichen Verfahren</a></li>
</ul>

<h3>June</h3>
<ul>
    <li>5.-9.6.2022, Basque Country (Spain): <a target="_blank" href="https://www.symposiumvictimology.com/">17th International Symposium of the World Society of Victimology. Victimisation in a digital world: responding to and connecting with victims</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>8.-10.9.2022, Hanover: <a target="_blank" href="https://kfn.de/krimg21/">17. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: Kriminalität und Digitalisierung - Digitalisierung und Kriminalität</a></li>
    <li>14.-16.9.2022, Gotha: <a target="_blank" href="https://www.dbh-online.de/aktuelles/save-date-24-dbh-bundestagung-vom-14-16092022">24. DBH-Bundestagung: "Bewährungs- und Straffälligenhilfe in Zeiten von Populismus"</a></li>
    <li>19.-20.9.2022, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-nuernberg-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
    <li>22.-23.9.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/8-praxistagung-jugendstrafvollzug-online/">DVJJ-Fachtagung: 8. Praxistagung Jugendstrafvollzug</a></li>
</ul>

<h3>October</h3>
<ul>
    <li>4.-6.10.2022, Hofgeismar: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-hofgeismar-3/">Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>7.-9.11.2022, Cologne: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-koeln/">DVJJ-Seminar: Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
    <li>14.-15.11.2022, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-nuernberg-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>
