<h2>Konferenzen, Tagungen und Veranstaltungen</h2>

<h2>2022</h2>

<h3>Februar</h3>
<ul>
    <li>21.2.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/restorative-justice-mit-jugendlichen-taeter-opfer-ausgleich-im-jgg/">DVJJ-Seminar: Restorative Justice mit Jugendlichen – Täter-Opfer-Ausgleich im JGG </a></li>
    <li>21.-22.2.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-online/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
</ul>

<h3>März</h3>
<ul>
    <li>7.-8.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-online/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
    <li>8.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/das-gesetz-zur-staerkung-der-verfahrensrechte-von-beschuldigten-im-jugendstrafverfahren-auswirkungen-fuer-die-praxis-online-2/">DVJJ-Seminar: Das Gesetz zur Stärkung der Verfahrensrechte von Beschuldigten im Jugendstrafverfahren – Auswirkungen für die Praxis </a></li>
    <li>18.-20.3.2022, Gold Coast (Australien): <a target="_blank" href="https://www.ranzcp.org/practice-education/events/faculty-of-forensic-psychiatry-conference-2022">Faculty of Forensic Psychiatry 2022 Conference: Forensic Frontiers: Forensic disability and emerging challenges in forensic psychiatry</a></li>
    <li>31.3.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/oertliche-zustaendigkeit-fuer-die-mitwirkung-des-jugendamts-in-jugendgerichtlichen-verfahren-online-5/">DVJJ-Seminar: Örtliche Zuständigkeit für die Mitwirkung des Jugendamts in jugendgerichtlichen Verfahren</a></li>
</ul>

<h3>April</h3>
<ul>
    <li>1.4.2022, Berlin: <a target="_blank" href="https://www.rechtspsychologie-bdp.de/">8. Tag der Rechtspsychologie (BDP Sektion Rechtspsychologie)</a></li>
    <li>25.-26.4.2022, Frankfurt a. M.: <a target="_blank" href="https://www.dbh-online.de/veranstaltungen/fachtagungen/fachtagung-uebergangsmanagement">Die Fachtagung zum Entlassungs- und Übergangsmanagement</a></li>
</ul>

<h3>Mai</h3>
<ul>
    <li>16.-17.5.2022, Bonn: <a target="_blank" href="https://www.dbh-online.de/veranstaltungen/fachtagungen/fachtagung-fuehrungsaufsicht">Fachtagung Führungsaufsicht</a></li>
    <li>18.-20.5.2022, Eindhoven (Niederlande): <a target="_blank" href="https://efcap2022.com/">7th EFCAP Congress</a></li>
</ul>

<h3>Juni</h3>
<ul>
    <li>5.-9.6.2022, Baskenland (Spanien): <a target="_blank" href="https://www.symposiumvictimology.com/">17th International Symposium of the World Society of Victimology. Victimisation in a digital world: responding to and connecting with victims</a></li>
    <li>28.6.-1.7.2022, Guildford (England): <a target="_blank" target="https://bsc2022.co.uk/">British Society of Criminology Annual Conference: Reimagining Criminological Futures: New Criminologies in a Changing World</a></li>
</ul>

<h3>August</h3>
<ul>
    <li>24.-25.8.2022, Interlaken (Schweiz): <a target="_blank" href="http://www.kriminologie.ch/programm_d.html">Kongress der Schweizerischen Arbeitsgruppe für Kriminologie (SAK) : ALTERNATIVEN: Von der alternativen Sanktion zur alternativen Kriminologie</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>8.-10.9.2022, Hannover: <a target="_blank" href="https://kfn.de/krimg21/">17. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: Kriminalität und Digitalisierung - Digitalisierung und Kriminalität</a></li>
    <li>14.-16.9.2022, Gotha: <a target="_blank" href="https://www.dbh-online.de/aktuelles/save-date-24-dbh-bundestagung-vom-14-16092022">24. DBH-Bundestagung: "Bewährungs- und Straffälligenhilfe in Zeiten von Populismus"</a></li>
    <li>19.-20.9.2022, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/psychische-stoerungen-in-haft-bzw-unter-straftaeterinnen-nuernberg-2/">DVJJ-Seminar: Psychische Störungen in Haft bzw. unter Straftäter*innen</a></li>
    <li>21.-24.9.2022, Málaga (Spanien): <a target="_blank" href="http://esc-eurocrim.org/">22. Annual Conference of the European Society of Criminology</a></li>
    <li>22.-23.9.2022, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/8-praxistagung-jugendstrafvollzug-online/">DVJJ-Fachtagung: 8. Praxistagung Jugendstrafvollzug</a></li>
</ul>

<h3>Oktober</h3>
<ul>
    <li>4.-6.10.2022, Hofgeismar: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-hofgeismar-3/">Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
</ul>

<h3>November</h3>
<ul>
    <li>7.-9.11.2022, Köln: <a target="_blank" href="https://www.dvjj.de/veranstaltung/systemsprenger-schwierigste-jugendliche-hoffnungslose-faelle-kompetenzen-fuer-den-umgang-mit-besonders-herausfordernden-klienten-koeln/">DVJJ-Seminar: Systemsprenger, schwierigste Jugendliche, hoffnungslose Fälle? Kompetenzen für den Umgang mit besonders herausfordernden Klienten</a></li>
    <li>14.-15.11.2022, Nürnberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/zusammenhaenge-zwischen-entwicklungstraumatisierungen-und-gewaltstraftaten-nuernberg-2/">DVJJ-Seminar: Zusammenhänge zwischen Entwicklungstraumatisierungen und Gewaltstraftaten</a></li>
</ul>
