<h2>Congresses and conferences</h2>

<h2>2021</h2>

<h3>June</h3>
<ul>
    <li>17.6.-2.11.2021, ONLINE: <a target="_blank" href="https://www.dbh-online.de/sites/default/files/seminare/attachments/2021-07-05-programm.pdf">Rechtsextremismus: Herausforderungen und Strategien im Umgang mit (De-)Radikalisierung in der Bewährungs- und Straffälligenhilfe</a></li>
</ul>

<h3>August</h3>
<ul>
    <li>25.-26.8.2021, Interlaken (possibly ONLINE): <a target="_blank" href="http://www.kriminologie.ch/media/files/programm_sak_web-2021_2.pdf">SAK Kongress 2021: Von Repression zu Prävention: Antagonistische oder komplementäre Logiken?</a></li>
    <li>25.-27.8.2021, Frankfurt am Main: <a target="_blank" href="https://www.iatso.org/index.php/frankfurt-2021">16th conference of the International Association for the Treatment of Sexual Offenders (IATSO): Current Developments in Etiology, Assessment, and Prevention of Sexual Offending</a></li>
    <li>30.8.-1.9.2021, Zurich: <a target="_blank" href="https://www.forensiktagung.ch/">Internationales Symposium: Forensische Psychologie und Psychiatrie</a></li>
    <li>31.8.-1.9.2021, ONLINE via Zoom: <a target="_blank" href="https://www.dvjj.de/veranstaltung/25-tagung-der-mitarbeiterinnen-und-mitarbeiter-im-jugendarrest-tagung-der-arbeitsgemeinschaft-der-arrestleiter-und-arrestbediensteten-in-der-dvjj-online/">25. Tagung der Mitarbeiterinnen und Mitarbeiter im Jugendarrest. Tagung der Arbeitsgemeinschaft der Arrestleiter und Arrestbediensteten in der DVJJ</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>2.-3.9.2021, Berlin: <a target="_blank" href="https://gesundinhaft.eu/wp-content/uploads/Konferenzprogramm310521.pdf">11. Europäische Konferenz zur Gesundheitsförderung in Haft: "Freiheitsentzug in Zeiten von COVID-19, Herausforderungen und Chancen"</a></li>
    <li>2.-4.9.2021, Hanover: <a target="_blank" href="https://kfn.de/krimG21/">17. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: Kriminalität und Digitalisierung - Digitalisierung und Kriminalität</a> (RESCEDULED TO 08.-10.09.2022) </li>
    <li>6.9.-4.10.2021, ONLINE: <a target="_blank" href="https://www.toa-servicebuero.de/sites/default/files/seminare/attachments/2021-09_onlineseminar_kreisverfahren.pdf">Restorative Justice-Praktiken: Kreisverfahren</a></li>
    <li>8.-11.9.2021, Bucharest (Romania): <a target="_blank" href="https://www.eurocrim2020.com/">20th Annual Conference of the European Society of Criminology</a> (RESCEDULED!)</li>
    <li>9.9.2021, Berlin: <a target="_blank" href="https://www.eltern-sucht.de/event/70jaehriges-jubilaeum-der-baj-in-berlin/">Europäischer Jugendmedienschutz – Ideal oder Utopie? Chancen und Grenzen eines Jugendmedienschutzes in Europa</a></li>
    <li>9.-11.9.2021, Marburg: <a target="_blank" href="https://www.uni-marburg.de/de/fb06/hessische-landesgeschichte/media/cfp_kolloquium-polizeigeschichte2021.pdf">30. Kolloquium zur Polizeigeschichte: Polizei und Sicherheit in urbanen Räumen vom 18. bis 21. Jahrhundert</a></li>
    <li>13.-14.9.2021, Schwäbisch-Gmünd: <a target="_blank" href="https://www.skfbayern.de/veranstaltungen/aktuelle-fortbildungen-veranstaltungen/ausgewaehlte-aspekte-weiblicher-delinquenz-31d03f90-6a60-4adc-8edb-9853421ff486">Bundesfachkonferenz: Ausgewählte Aspekte weiblicher Delinquenz. Gewalt ist nicht (allein) männlich</a></li>
    <li>16.-18.9.2021, ONLINE: <a target="_blank" href="https://www.dvjj.de/veranstaltung/31-deutscher-jugendgerichtstag-online/">31. Deutscher Jugendgerichtstag</a></li>
    <li>20.-22.9.2021, ONLINE: <a target="_blank" href="https://bundeskongress-kja.de/">3. Bundeskongress Kinder- und Jugendarbeit</a></li>
    <li>21.-23.9.2021, ONLINE via Zoom: <a target="_blank" href="https://www.birmingham.ac.uk/schools/business/news/2021/bbs-responsible-business-academic-symposium-call-for-papers.aspx">Responsible Business Symposium 2021: Encouraging responsible policing and credible criminal justice interventions during a pandemic</a></li>
</ul>

<h3>October</h3>
<ul>
    <li>8.-9.10.2021, Berlin and online: <a target="_blank" href="https://liga-kind.de/jahrestagung/">Jahrestagung Deutsche Liga für das Kind: Spielräume für Kinder. Die Rechte des Kindes auf Beteiligung, Bildung und Spiel</a></li>
    <li>20.-21.10.2021, ONLINE: <a target="_blank" href="https://soziologie.de/fileadmin/user_upload/calls/2021/04/Call_for_Papers_institutionelle_Raumproduktion.pdf">Abschlusskonferenz des von der DFG geförderten Projektes „Die Konstruktion von Räumen im Kontext von Sicherheit - Raumwissen bei der Polizei (KORSIT)": Die institutionelle Raumproduktion des Städtischen</a></li>
    <li>20.-22.10.2021, Nuremberg: <a target="_blank" href="https://www.dvjj.de/veranstaltung/mit-feuer-unterm-hintern-die-soziale-kompetenz-trainieren-erlebnisaktivierende-und-theaterpaedagogische-methoden-fuer-die-paedagogische-arbeit-nuernberg-2/">Mit Feuer unterm Hintern die soziale Kompetenz trainieren. Erlebnisaktivierende und theaterpädagogische Methoden für die pädagogische Arbeit</a></li>
    <li>20.-22.10.2021, Nice: <a target="_blank" href="https://efus.eu/efusconference2021/">Efus’ seventh international Security, Democracy and Cities Conference </a></li>
</ul>

<h3>November</h3>
<ul>
    <li>1.-10.11.2021, ONLINE: <a target="_blank" href="https://www.aktionstage-gefaengnis.de/">Aktionstage Gefängnis 2021: Kontakt | Einsamkeit | Isolation</a></li>
    <li>3.-4.11.2021, Münster: <a target="_blank" href="https://www.agj.de/fileadmin/files/Transferkonferenz_Sozialberichterstattung2021/Programm_Transferkonferenz_Sozialberichterstattung.pdf">Was es alles gibt - Kinder- und Jugendhilfe im Dickicht des Berichtwesens?! Aktuelle Befunde der Bildungs- und Sozialberichterstattung</a></li>
    <li>4.-6.11.2021, Turku (Finland): <a target="_blank" href="https://woa2020.utu.fi/">25th Workshop on Aggression: Prevention of aggression and violence among and against youth</a></li>
    <li>12.-13.11.2021, Leipzig: <a target="_blank" href="https://www.ag-strafrecht.de/herbstkolloquium/38-herbstkolloquium-2021/">38.Herbstkolloquium 2021: Kommunikation im Strafverfahren</a></li>
    <li>12.11.-3.12.2021, ONLINE: <a target="_blank" href="https://www.toa-servicebuero.de/sites/default/files/seminare/attachments/2021-11_onlineseminar_interkulturelle_kompetenz_in_der_mediation.pdf">Lebendige, praxisorientierte Onlineveranstaltungsreihe zu interkultureller Konfliktlösung und Mediation: Interkulturelle Kompetenz in der Mediation</a></li>
    <li>24.-25.11.2021, Lausanne/ONLINE: <a target="_blank" href="https://www.skjv.ch/en/austausch/forum-detention-and-probation">Fourth Forum on Detention and Probation 2021: Education- a driver for change</a></li>
    <li>25.-26.11.2021, ONLINE: <a target="_blank" href="https://kfn.de/wp-content/uploads/2021/03/Call_for_Papers_Gender_and_Crime.pdf">Gender & Crime - Geschlechteraspekte in Kriminologie und Strafrechtswissenschaft</a></li>
    <li>29.11.-1.12.2021, Erfurt: <a target="_blank" href="https://www.fachwoche.de/">Fachwoche Straffälligenhilfe 2021: Gefangen - bis der Tod uns scheidet.</a></li>
</ul>

<h2>2022</h2>

<h3>June</h3>
<ul>
    <li>5.-9.6.2022, Basque Country (Spain): <a target="_blank" href="https://www.symposiumvictimology.com/">17th International Symposium of the World Society of Victimology. Victimisation in a digital world: responding to and connecting with victims</a></li>
</ul>

<h3>September</h3>
<ul>
    <li>8.-10.9.2022, Hanover: <a target="_blank" href="https://kfn.de/krimg21/">17. Wissenschaftliche Fachtagung der Kriminologischen Gesellschaft: Kriminalität und Digitalisierung - Digitalisierung und Kriminalität</a></li>
</ul>
