<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#NKrimDok">
        <div class="tf-panel-collapse-heading">
            Which references will I find in KrimDok?
        </div>
    </a>
    <div id="NKrimDok" class="collapse tf-panel-collapse-body">
        <p> KrimDok is a bibliographical reference system of criminology literature. The database brings
           together various collections of literature and catalogues which were originally arranged according
           to different aspects. You can now search the titles listed via a search mask.
        </p>
        <p> The collection of the
            <a href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk">Instituts für Kriminologie in Tübingen</a>
            is largely based on German-language titles; however the collection of the
            <a href="https://uni-tuebingen.de/einrichtungen/universitaetsbibliothek/ueber-uns/bibliotheksbestand/fachgebiete/kriminologie-fid/">
              Fachinformationsdiensts Kriminologie</a> in the Tübingen University Library has a large proportion
            of non-German literature (largely monographs).  Non-stand-alone works (e.g. articles) are included in
            KrimDok via an assortment of key international serial publications.
        </p>
        <p> Apart from criminology, basic related disciplines are included as far as possible, above all in the
          broadest sense of criminologically-relevant publications and legal publications of general interest
          in criminology due to their parallel nature (criminal law, criminal procedure, sentencing, penal law),
          law in action, crime detection and police investigation, psychology (particularly forensic and legal
          psychology as well as social psychology), psychiatry (particularly forensic psychiatry, involuntary
          treatment), sociology (particularly sociology of law, criminal sociology) and pedagogy (and social work).
        </p>
        <p>
          The collection of the Institute of Criminology in Tübingen, both monographies and a selection of journals
          (mostly German-language publications) to the end of 2014 are incorporated via local (non-standardized)
          keywords (generally speaking, from 1990, and selectively before that). Additionally, monographies are
          ordered by keywords according to Germany’s RSWK (Regeln für den Schlagwortkatalog) system.
        </p>
        <p>
          Items in the collection of the Institute of Criminology information service (Fachinformationsdienst) - which
          largely includes non-German-language publications but also has some German-language publications, have
          keywords according to RSWK.  Or search the German Research Foundation-backed project
          <a href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a>.  Entries here also have
          standardized keywords according to RSWK. A large part of the Heidelberg essay archive was included, thanks
          to German Research Foundation sponsorship. The essays/papers here also have standardized keywords according to RSWK.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#FS2015">
        <div class="tf-panel-collapse-heading">
            Why do non-German keywords only appear starting in 2015?
        </div>
    </a>
    <div id="FS2015" class="collapse tf-panel-collapse-body">
        <p> No additional keywords are assigned to journal articles which already have authors’ keywords;
          these are adopted in our system. That is why you also find English-language keywords starting in 2015.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#SigLN">
        <div class="tf-panel-collapse-heading">
            What do the call numbers mean on each reference?
        </div>
    </a>
    <div id="SigLN" class="collapse tf-panel-collapse-body">
        <p>
          Call numbers starting with “KB” are from the collection of the Criminology information service housed
          in the Tübingen University Library. All other call numbers indicate the Institute of Criminology collection
          at the University of Tübingen. If no call number is indicated, the work referenced is listed in the KrimDok
          database, which is not physically present in Tübingen
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#BInL">
        <div class="tf-panel-collapse-heading">
            What does it mean when you find "In:" in a reference?
        </div>
    </a>
    <div id="BInL" class="collapse tf-panel-collapse-body">
        <p> "In:" means that the work is a non-stand-alone article, essay or paper and is to be found "in"
            a larger volume (such as a journal, edited edition or series).
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WasIstSubito">
        <div class="tf-panel-collapse-heading">
            What is Subito?
        </div>
    </a>
    <div id="WasIstSubito" class="collapse tf-panel-collapse-body">
        <p> <a href="http://www.subito-doc.de/index.php?lang=de&mod=page&pid=Dokumentlieferung">Subito</a> is a
          document delivery service via which you can order copies of articles from printed journals or books.
          You must pay a small fee to use this service.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WTueB">
        <div class="tf-panel-collapse-heading">
            How do I view or check out a work from the Tübingen collections?
        </div>
    </a>
    <div id="WTueB" class="collapse tf-panel-collapse-body">
        <p>
          You can usually receive books and journals which are not available at your closest library via
          long-distance loan or via the <a href="http://www.subito-doc.de/index.php?lang=de&mod=page&pid=Dokumentlieferung">
          Subito</a> service.
        </p>
        <p>
         Long-distance loans are covered by an agreement between the libraries to exchange academic literature
         (e.g., monographies and articles) amongst their users as required.  The legal basis for this are the provisions
         of the "Ordnung des Leihverkehrs in der Bundesrepublik Deutschland"
         (<a href="https://wiki.bsz-bw.de/lib/exe/fetch.php?media=fl-team:leihverkehrsordnung.pdf">Leihverkehrsordnung</a>).
        </p>
        <p>
         What cannot be checked out under this system:
        </p>
        <ul>
            <li>
              Books and articles which are available in your closest library (this includes books currently on loan as well
              as books available in a reading room or departmental library),
            </li>
            <li>
              Works which you yourself can purchase for a low price (approx. €10),
            </li>
            <li>
              Recent journals and recent bound journals.
            </li>
        </ul>
        <p>
          You can order a work on long-distance loan via the library system in your library - if you cannot find what
          you are looking for in your library. The work you need can be ordered by long-distance loan from another
          library. You have the option of ordering an article out of a journal.
        </p>
        <p>
          A processing fee of €1.50 will be charged for each long-distance order - regardless of whether the work can
          be delivered or not. The process usually takes about 1-3 weeks.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#KWKB">
        <div class="tf-panel-collapse-heading">
            What do I do when I cannot receive a criminological work from any library?
        </div>
    </a>
    <div id="KWKB" class="collapse tf-panel-collapse-body">
        <p> You can make a purchase request to the Criminology information service. The required form is
            <a href="/Feedback/Form/AcquisitionRequest">here</a>.
            The acquisitions profile is
            <a href="<?=$this->url('content-page', ['page' => 'acquisition'])?>">here</a>.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#KeineNotationen">
        <div class="tf-panel-collapse-heading">
            Why can’t I find any notation in the new KrimDok?
        </div>
    </a>
    <div id="KeineNotationen" class="collapse tf-panel-collapse-body">
        <p>
          That system came to an end in 2014. There is no more notation as of January 2015. Works published in
          or after 2015 cannot be found using that system. Works published before 2015 can only be found via
          the system if they were purchased by the Criminology information service by the end of 2014
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#WNMono">
        <div class="tf-panel-collapse-heading">
            Why are there so few references to monographs from related disciplines?
        </div>
    </a>
    <div id="WNMono" class="collapse tf-panel-collapse-body">
        <p>
          As far as monographs go, KrimDok is first and foremost a collection for the Criminology information service
          and the Institute of Criminology at the University of Tübingen. In categories of general and for criminology
          only marginally relevant areas (e.g., drugs, sexuality, alcohol, etc.), we have only been able to expand our
          collection by limiting acquisitions to the most relevant literature, due to financial constraints.
        </p>
    </div>
</div>
