<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'fulltexts']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/fulltexts.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Criminological Full texts</h4>
                <p>Access to Criminological Full texts</p>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'journals']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/journals.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Criminological Journals</h4>
                <p>Journals at the FID Criminology</p>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/research_data.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Research Data Management</h4>
                <p>Informations on Research Data Management</p>
            </div>
        </a>
    </div>
</div>
