<h2>About the FID Criminology</h2>
<p>The Criminological Information Service (Fachinformationsdienst Kriminologie, FID) is mainly focused on the task to provide the scientific community with literature and other subject-relevant information on criminology as comprehensively as possible. Currently, around
    <ul>
        <li>125,000 monographs</li>
        <li>240 active journal subscriptions</li>
        <li>320 digital documents in <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDoc</a> as well as</li>
        <li>1,500 digital documents in the criminological <a target="_blank" href="https://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358?locale-attribute=en">repository</a> </li>
    </ul>
    are part of the FID.<br/>
    The most important research tool for the literature inventory as well as for bibliographical references, is the database KrimDok. In this database are currently about 265,600 references (status: July 2021).
</p>
<p>
    In case you are missing any literature, feel free to visit the <a href="<?=$this->url('content-page', ['page' => 'acquisition'])?>">acquisition profile</a> of the FID Criminology in order to place an <a href="/Feedback/Form/AcquisitionRequest">acquisition request</a>.<br/>
</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#history">
        <div class="tf-panel-collapse-heading">
            Historical development
        </div>
    </a>
    <div id="history" class="collapse tf-panel-collapse-body">
        <p>
            Since 1969 the acquisition and collection of criminological special literature at the University of Tübingen was intensified. This has always been achieved with a cooperation between the Institute for Criminology and the university library at the University of Tübingen and sponsoring by the German Research Foundation (Deutsche Forschungsgemeinschaft – DFG).<br/>
            Since 2014 the acquisition of new literature – following a new structure after changes in the <a target="_blank" href="https://www.dfg.de/foerderung/programme/infrastruktur/lis/lis_foerderangebote/fachinfodienste_wissenschaft/index.html">DFG guidelines</a> for supra-regional literature and information supply in sciences – is sponsored in the scope of the “Criminological Information Service” (Fachinformationsdienst Kriminologie – FID).
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#concepts">
        <div class="tf-panel-collapse-heading">
            Current concept
        </div>
    </a>
    <div id="concepts" class="collapse tf-panel-collapse-body">
        <p>
            The FID Criminology continues to focus on the task to supply the supra-regional scientific community with literature in the field of criminology. However, this task has been redefined: In the past, the main focus was to acquire foreign language literature (mainly in English) as well as literature of other relevant fields as thoroughly as possible and to make it available to the scientific community. According to this new concept, the goal is to build an information structure following the principle of “interest of research”, which means, the focus is to acquire literature that research is specifically interested in and meets the scientific community’s wants and needs. The most important research tool to all formats of criminological literature (books, journal essays, documents etc.) is the KrimDok database.
        </p>
        <p>
            The new focus includes efforts to extend full text offers, and to provide more digital media. With the DFG funded project <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">“DigiKrimDoc”</a>, publications relevant to criminology are being digitalized and made available online to the scientific community. The criminological <a target="_blank" href="https://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358?locale-attribute=en">repository</a> of the university library contains digitally published research and subject relevant documents (for example reports of ministries and official statics etc).
        </p>
    </div>
</div>

<div class="tf-panel-collapse">

    <a data-toggle="collapse" href="#2014-2016">
        <div class="tf-panel-collapse-heading">
            Funding period 2014 - 2016
        </div>
    </a>
    <div id="2014-2016" class="collapse tf-panel-collapse-body">
        <p>
            Aside from the constant expansion of the literature inventory in Tübingen and the registration of single contributions from a selection of field specific journals, publication series and compilations, in the first funding period of the FID mainly technical projects were targeted to lay a foundation for future project components. As one example, the database was migrated from an Allegro based system to a VuFind-system and now offers more faceted search options. In addition, the environment for the repository as well as DigiKrimDok were established and supplied with the initial documents. The focus of attention, however, was supplying full texts and digitalizing literature which is now in the public domain or to acquire permission for secondary publication.
        </p>
        <p>
            Regarding the expansion of content from a reference system of hard copies to a general bibliographic reference system, cooperation with other institutions was sought. To improve networking between institutions relevant to criminology as well as to create (potential) cooperation with the FID, a colloquium was held in March 2015 with about thirty representatives of various institutions in Tübingen.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#2017-2019">
        <div class="tf-panel-collapse-heading">
            Funding period 2017 - 2019
        </div>
    </a>
    <div id="2017-2019" class="collapse tf-panel-collapse-body">
        <p>
            Within the current funding period, further specialist literature will be acquired, processed and referenced. The database will be supplemented with even more references due to cooperation with other relevant institutions. This approach will be gradually extended with the goal to create a comprehensive documentation of primarily German, but also foreign language criminological literature. Special attention will be paid to improve the accessibility of complete electronic text sources, for example by providing further documents in the repository, by listing sources to e-books relevant to criminology or to provide a list of interesting <a href="<?=$this->url('content-page', ['page' => 'journals']) ?>">open-access journals</a>.
        </p>
        <p>
            In addition, the <a href="<?=$this->url('content-page', ['page' => 'krimdok'])?>#development">technical development</a> of KrimDok is advanced regarding full text indexing and the extension of faceting. The current home page of KrimDok will be changed into a platform for key information about the FID. News from different institutions (such as conference or congress announcements or job openings, etc.) for example can now be announced in the <a href="<?=$this->url('content-page', ['page' => 'news'])?>">notifications and dates</a> section of the KrimDok welcome page. If you have any suggestions that should be added, please do not hesitate to contact us: <a href="mailto:fidkrim@ifk.uni-tuebingen.de">fidkrim@ifk.uni-tuebingen.de</a>.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#2020">
        <div class="tf-panel-collapse-heading">
            Funding period 2020
        </div>
    </a>
    <div id="2020" class="collapse tf-panel-collapse-body">
        <p>
            Due to the DFG's internal considerations regarding the future of subject information services, applications for funding in 2019 could only be submitted for one year (2020). The application of the FID Criminology was approved in full, so that the core services can be continued without interruption (e.g. the expansion of the inventory, the journal indexing at article level and the technical updating of the KrimDok). In addition, a working basis will be created and tests carried out for larger work packages that are applied for the 2021-23 funding period.
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#2021-2023">
        <div class="tf-panel-collapse-heading">
            Funding period 2021 - 2023
        </div>
    </a>
    <div id="2021-2023" class="collapse tf-panel-collapse-body">
        <p>
            In the funding period 2021-2023 the collection of criminological literature as well as the references of statistics and research data get expanded on KrimDok. Among others, 24 further journals that have not been indexed on KrimDok yet are evaluated at article level. Additionally, meta data from the „Albert-Krebs-Bibliothek“ in Wiesbaden are migrated to KrimDok in the context of a collaborative project.
        </p>
        <p>
            Furthermore, direct access to digital full texts is significantly improved: criminologically relevant meta data on open access full texts are loaded from „<a href="https://core.ac.uk/" target="_blank" >CORE</a>“ into KrimDok and a criminological self-archiving service for researchers is established.  Moreover, a collection of digital materials supporting research and teaching is created under the heading "Classics of Criminology" on the cover page of KrimDok.
        </p>
        <p>The continuous technical optimisation includes without limitation updating the VuFind-base to version 7, key word adjustment as well as the translation of key words into English and Spanisch in order to strengthen the international visibility of KrimDok. </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#info">
        <div class="tf-panel-collapse-heading">
            Further information about the FID Criminology
        </div>
    </a>
    <div id="info" class="collapse tf-panel-collapse-body">
        <p>
            <ul>
                <!--<li><a target="_blank" href="https://wikis.sub.uni-hamburg.de/webis/index.php/Kriminologie">Webis</a></li>-->
                <li><a href="/krimdok_docs/Flyer_FID_engl.pdf">Flyer</a></li>
                <li><a href="/krimdok_docs/Poster_FID_engl.pdf">Poster</a></li>
            </ul>
        </p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a id="contact_toggle" data-toggle="collapse" href="#contact">
        <div class="tf-panel-collapse-heading">
            Contact and person in charge at the FID Criminology
        </div>
    </a>
    <div id="contact" class="collapse tf-panel-collapse-body">
        <p>
            <ul>
                <li><a href="mailto:janina.meister@uni-tuebingen.de">General <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
                <li>Supervisory librarian: <a href="mailto:janina.meister@uni-tuebingen.de">Janina Meister <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
                <li>Specialist supervision: <a href="mailto:katharina.stelzel@uni-tuebingen.de">Dr. Katharina Stelzel <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
                <li>Technical supervision: <a href="mailto:olaf.brandt@uni-tuebingen.de">Olaf Brandt <span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></li>
            </ul>
        </p>
    </div>
    <script>
        // auto-expand if anchor is given, e.g. if linked from footer
        if (window.location.href.includes("#contact"))
            $('#contact_toggle').click();
    </script>
</div>
