<h1>Criminological Information Service</h1>
<p>Goal and task of the Criminological Information Service (FID Kriminologie) is to supply the supra-regional scientific community with criminological special literature, as well as with other information relevant to research and the subject of criminology as a whole. This is a project established in cooperation between the Institute for Criminology and the university library of the University of Tübingen and sponsored by the German research foundation.</p>

<h1>About the FID Criminology</h1>
<p>The FID is mainly focused on the task to provide the scientific community with literature and other subject-relevant Information about criminology.</p>

<h2>Current state – February 2017</h2>
<ul>
    <li>120,000 monographs</li>
    <li>240 active <a target="_blank" href="https://www.jura.uni-tuebingen.de/forschung/fid/zeitschriftenliste">journal subscriptions</a></li>
    <li>230 digitalized in <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">DigiKrimDok</a> as well as</li>
    <li>360 documents in the <a target="_blank" href="http://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358?locale-attribute=en">repository</a>.</li>
Currently there are 235,000 references in the KrimDok system.
</ul>

<h2>History</h2>

<p>Since 1969 the collection of criminological special literature at the University of Tübingen was intensified. This has always been achieved with a cooperation between the Institute for Criminology, the university library and the University of Tübingen and sponsoring by the German research foundation (Deutsche Forschungsgemeinschaft – DFG). The first special inventory called “collection focus criminology” was evaluated by the German research foundation between 2011 and 2013 and afterwards transferred to a supra-regional funding program of the DFG and continued as the “special collection criminology”.</p>
<p>Since 2014 the acquisition of new literature follows a new structure according to the guidelines of the DFG supra-regional literature and information supply in sciences within the “Criminological Information Service” (Fachinformationsdienst Kriminologie – FID).</p>

<h2>Concept</h2>
<p>The FID Criminology continues to focus on the task to supply the supra-regional scientific community with literature in the field of criminology, just like the predecessor program. However, this task has been newly defined: In the past, the main focus was to acquire foreign language literature as well as literature of other relevant fields as thoroughly as possible and to make it available to the scientific community. According to the new definition, the goal is to build an information structure following the principle of “interest of research”, which means, the focus is to acquire literature that research is specifically interested in and meets the scientific communities wants and needs. The most important research tool to all formats of criminological literature (books, journal essays, documents etc) is the KrimDok database provided the Institute of Criminology and the university library of the University of Tübingen.</p>
<p>The new focus of the supra-regional literature supply includes efforts to extend full text offers, and to provide more digital documents. With the DFG sponsored project <a target="_blank" href="http://idb.ub.uni-tuebingen.de/digitue/krimdok/">“DigiKrimDoc”</a>, publications relevant to criminology are being digitalized and made available to the scientific community. The criminological <a target="_blank" href="http://publikationen.uni-tuebingen.de/xmlui/handle/10900/56358?locale-attribute=en">repository</a> of the university library contains research and subject relevant “grey literature” (reports of ministries and official statics etc).</p>
<p>Within the funding period 2017 till 2019 it will be continued to acquire literature relevant to criminology. So far, the KrimDok database mainly contains Tübingen stock. In the future, more cooperation with other relevant institutes is planned and the KrimDok database will contain an increasing amount of foreign references. The goal is to create a thorough reference system of the already existing, mainly German but also international criminological literature. New technical developments are also planned. In addition, the information structure will be supplemented with current subject relevant information (conferences and congresses, job offers etc), which will be made public in the <a href="<?=$this->url('content-page', ['page' => 'news']) ?>">“notifications and dates”</a> section. To fit the services of the FID Criminology as good as possible to the needs of the scientific community, a scientific council was established, with the task to accompany the project as advisors.</p>

<p>If you’re missing literature, please see the <a href="<?=$this->url('content-page', ['page' => 'acquisition']) ?>">acquisition profile</a> of the FID Criminology. Under this section you have the opportunity to send an <a href="http://krimdok.uni-tuebingen.de/AcquisitionRequest/Create">acquisition request</a>.</p>
