<h2>Stellenausschreibungen</h2>
<ul>
    <li>Bundeskriminalamt Wiesbaden: <a target="_blank" href="https://bewerbung.bka.de/?7&235">Wissenschaftliche/-r Mitarbeiter/-in</a> (Kriminologie), 100%, befristet (Deadline: 05.11.2020)</li>
    <li>Landeskriminalamt NRW, Düsseldorf: <a target="_blank" href="https://lka.polizei.nrw/artikel/soziologe-soziologin-oder-sozialwissenschaftler-sozialwissenschaftlerin">Sozialwissenschaftler/-in</a> (Kriminologie), 100% (Deadline: 30.11.2020)</li>
</ul>
