<h2>Stellenausschreibungen</h2>
<ul>
<li>Institut für Kriminologie, Uni Tübingen: <a target="_blank" href="https://uni-tuebingen.de/universitaet/stellenangebote/newsfullview-stellenangebote/article/akademische-mitarbeiterinakademischer-mitarbeiter-psychologinpsychologe/">Akademische/-r Mitarbeiter/-in</a> (Psychologie), 50 % (Deadline: 10.2.2019)</li>
<li>Bundesarbeitsgemeinschaft Straffälligenhilfe e.V.: <a target="_blank" href="https://bag-s.de/nc/aktuelles/aktuelles0/article/in-eigener-sache-stellenangebot/">Referent/-in, E 11, 75 %, befristet</a> (Sozialwissenschaft, Journalismus) (Deadline: 18.2.2019)</li>
</ul>
