<h2>Stellenausschreibungen</h2>
<ul>
    <li>Bundeskriminalamt: <a target="_blank" href="https://www.stepstone.de/stellenangebote--Sozialwissenschaftlerin-Sozialwissenschaftler-m-w-d-Berlin-Bundeskriminalamt--8618397-inline.html?lang=de&rewrite=1&cid=msearche_kimeta___5-6_openlisting">Sozialwissenschaftler*in (m/w/d)</a> Vollzeit oder Teilzeit (Deadline: 18.09.2022)</li>
    <li>Bundeskriminalamt: <a target="_blank" href="https://www.stepstone.de/stellenangebote--Analystin-Analyst-fuer-kriminalpolizeiliche-Aufgaben-m-w-d-Wiesbaden-Berlin-Meckenheim-Bundeskriminalamt--8643513-inline.html">Analyst*in für kriminalpolizeiliche Aufgaben (m/w/d)</a> Vollzeit oder Teilzeit (Deadline: 02.10.2022)</li>
</ul>