<h1>Journals</h1>
<p>
    KrimDok contains about 4.700 references to German and foreign language criminological journals, which are available in either print, electronic, hybrid or (totally or partially) retro-digitalized format. Most of the references are of journals, which now changed their titles to a new name or stopped publishing new issues completely.<br/>
    To facilitate access to open-access documents relevant to criminological research, field specific and non-licensed journals are summarized in a list. Further information to current journals is available in the following lists:
</p>
<ul>
    <li><a href="/krimdok_docs/Journals_engl.pdf">List of criminological open-access journals (pdf)</a></li>
    <li><a href="/krimdok_docs/Journals_OA.pdf">List of currently processed journals in KrimDok (pdf)</a></li>
    <li><a href="/krimdok_docs/Journals_Nationallizenz.pdf">List of criminological journals with a national licence (pdf)</a></li>
</ul>
