<h1>Zeitschriften</h1>
<p>
    In KrimDok finden sich rund 4.500 Nachweise zu deutsch- und fremdsprachigen kriminologischen Zeitschriftentiteln, die wahlweise gedruckt, elektronisch, hybrid oder (ganz oder teilweise) retrodigitalisiert publiziert und käuflich oder lizenzfrei von den Verlagen zur Verfügung gestellt werden oder wurden. Bei einem Großteil der Nachweise handelt es sich um Zeitschriften, die mittlerweile ihren Titel geändert oder ihr Erscheinen ganz eingestellt haben.<br/>
    Um den Zugang zu laufenden, kriminologisch relevanten Open-Access-Volltexten zu vereinfachen, wurden thematisch passende lizenzfreie Zeitschriften in einer Übersicht zusammengefasst. Weitere Informationen zu gegenwärtig erscheinenden Zeitschriften sowie zu der Auswertung von Einzelbeiträgen für KrimDok finden Sie in den Listen, die nach bestimmten Merkmalen und für unterschiedliche Verwendungszwecke erstellt wurden.
</p>
<ul>
    <li><a href="/krimdok_docs/Journals_OA.pdf">Liste kriminologisch relevante Open-Access-Zeitschriften</a></li>
    <li><a href="/krimdok_docs/Journals.pdf">Liste der derzeit für KrimDok ausgewerteten Zeitschriften</a></li>
</ul>
