<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'krimdok']) ?>">
            <div class="panel-image-wrapper"><img src="<?=$this->imageLink('krim_dok.jpg') ?>" alt="Bild KrimDok" class="img-responsive panel-image" /></div>
            <div class="panel-content">
                <h4>KrimDok</h4>
                <p>Einzelheiten zu KrimDok</p>
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'fid']) ?>">
            <div class="panel-image-wrapper"><img src="<?=$this->imageLink('fid_krim_s.jpg') ?>" alt="Bild FID" class="img-responsive panel-image" /></div>
            <div class="panel-content">
                <h4>FID Kriminologie</h4>
                <p>Über den FID</p>
            </div>
        </a>
    </div>
</div>
