<h1>Collaborating partners</h1>
<br/>
<div class="row">
    <div class="col-xs-12 col-sm-6">
        Institut für Kriminologie der Universität Heidelberg, Mitgründer von KrimDok<br/>
        <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html">
            <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6">
        Max-Planck-Institut für ausländisches und internationales Strafrecht (Freiburg i. Br.)<br/>
        <a target="_blank" href="https://www.mpicc.de/de/home.cfm">
            <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>"/>
        </a>
    </div>
</div>
