<h1>Kooperationspartner bei KrimDok</h1>

<p>
    <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html">Institut für Kriminologie der Universität Heidelberg</a><br/>
    (Direktor: Prof. Dr. Dieter Dölling)<br/>
    <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>"/>
</p>
<hr/>
<p>
    <a target="_blank" href="https://www.mpicc.de/de/home.cfm">Max-Planck-Institut für ausländisches und internationales Strafrecht (Freiburg i. Br.)</a><br/>
    <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>"/>
</p>
