<h2>Collaborating partners</h2>
<div class="row">
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Institut für Kriminologie der Universität Heidelberg<br/>(Mitgründer von KrimDok)</h3>
        <a target="_blank" href="http://www.uni-heidelberg.de/institute/fak2/krimi/index.html">
            <img src="<?=$this->imageLink('partners/heidelberg.jpg') ?>" height="100"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Max-Planck-Institut zur Erforschung von Kriminalität, Sicherheit und Recht<br/>(Freiburg i. Br.)</h3>
        <a target="_blank" href="https://www.mpicc.de/de/home.cfm">
            <img src="<?=$this->imageLink('partners/max_planck_institut.png') ?>"/>
        </a>
    </div>
</div>
<div class="row">
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Kriminologische Zentralstelle e.V.<br/>(Wiesbaden)</h3>
        <a target="_blank" href="https://www.krimz.de/">
            <img src="<?=$this->imageLink('partners/krimz.png') ?>"/>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 partner">
        <h3>Oñati International Institute for the Sociology of Law</h3>
        <a target="_blank" href="http://www.iisj.net/en/library/about-library">
            <img src="<?=$this->imageLink('partners/onati.jpg') ?>" height="100"/>
        </a>
    </div>
</div>
