<?php ?>
<input type="hidden" name="pow-captcha-challenge" value="<?=$this->captcha->getChallenge() ?>">
<input type="hidden" name="pow-captcha-difficulty" value="<?=$this->captcha->getDifficulty() ?>">
<input type="hidden" name="pow-captcha-hash-algo" value="<?=$this->captcha->getHashAlgo() ?>">
<input type="hidden" name="pow-captcha-start" value="<?=$this->captcha->getStart() ?>">
<input type="hidden" name="pow-captcha-nonce" value="">
<p class="pow-captcha-status">PoW Captcha not initiated.</p>
