<h3><?=$this->transEsc('Electronic')?></h3>
<table class="table table-striped">
  <?php foreach ($this->holdings as $item): ?>
    <tr>
      <td class="fullLocation">
        <?php foreach ((array)$item['location'] as $index => $location): ?>
          <?php $locationTextEsc = $this->transEscWithPrefix('location_', $location); ?>
            <p>
          <?php if ($item['locationhref'][$index] ?? false): ?>
              <a href="<?=$item['locationhref'][$index]?>" target="_blank"><?=$locationTextEsc?></a>
          <?php else: ?>
              <?=$locationTextEsc?>
          <?php endif; ?>
            </p>
        <?php endforeach; ?>
      </td>
      <td class="fullAvailability">
        <?php if ($item['use_unknown_message'] ?? false): ?>
          <span><?=$this->transEsc('status_unknown_message')?></span>
        <?php elseif ($item['availability']): ?>
          <span class="text-success"><?=!empty($item['status']) ? $this->transEsc($item['status']) : $this->transEsc('Available')?></span>
        <?php else: ?>
          <span class="text-danger"><?=$this->transEsc($item['status'])?></span>
        <?php endif; ?>
        <?php if (!empty($item['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc("Item Notes")?>:</b>
            <ul>
              <?php foreach ($item['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
