<h2><?=$this->transEsc('Electronic')?></h2>
<table class="table table-striped">
  <?php foreach ($this->holdings as $item): ?>
    <tr>
      <td class="fullLocation">
        <?php $locationTextEsc = $this->transEscWithPrefix('location_', $item['location']); ?>
        <?php if ($item['locationhref'] ?? false): ?>
          <a href="<?=$this->escapeHtmlAttr($item['locationhref'])?>" target="_blank"><?=$locationTextEsc?></a>
        <?php else: ?>
          <?=$locationTextEsc?>
        <?php endif; ?>
      </td>
      <td class="fullAvailability">
        <?php
          $availabilityStatus = $item['availability'];
        ?>
        <?php if ($availabilityStatus->useUnknownMessage()): ?>
          <span><?=$this->transEsc('status_unknown_message')?></span>
        <?php else: ?>
          <?php
            $statusClassEsc = $this->availabilityStatus()->getClass($availabilityStatus);
            $statusDescription = $availabilityStatus->getStatusDescription();
          ?>
          <span class="<?=$statusClassEsc?>"><?=$this->transEsc($statusDescription)?></span>
        <?php endif; ?>
        <?php if (isset($item['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc('Item Notes')?>:</b>
            <ul>
              <?php foreach ($item['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      </td>
    </tr>
  <?php endforeach; ?>
</table>
