<td colspan="2" class="holding-<?=$this->holding['availability'] ? "available" : "unavailable" ?>">
  <div class="holding-details">
    <span class="holding-field copy-number">
      <?=$this->transEsc("Copy")?> <?=$this->escapeHtml($this->holding['number'])?>
    </span>
    <span class="holding-field barcode">
      <?=$this->escapeHtml($this->holding['barcode'])?>
    </span>
    <span class="holding-field availability">
      <?php if ($this->holding['reserve'] == "Y"): ?>
        <link property="availability" href="http://schema.org/InStoreOnly" />
        <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
      <?php endif; ?>

      <?php if (isset($this->holding['use_unknown_message']) && $this->holding['use_unknown_message']): ?>
        <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
      <?php else: ?>
        <?php if ($this->holding['availability']): ?>
          <?php /* Begin Available Items (Holds) */ ?>
          <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>
        <?php else: ?>
          <?php /* Begin Unavailable Items (Recalls) */ ?>
          <span class="text-danger"><?=$this->transEsc($this->holding['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
          <?php if (isset($this->holding['returnDate']) && $this->holding['returnDate']): ?>
            <span class="small return-date"><?=$this->escapeHtml($this->holding['returnDate'])?></span>
          <?php endif; ?>
          <?php if (isset($this->holding['duedate']) && $this->holding['duedate']): ?>
            <span class="small due-date"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($this->holding['duedate'])?></span>
          <?php endif; ?>
          <?php if (isset($this->holding['requests_placed']) && $this->holding['requests_placed'] > 0): ?>
            <span class="request-count"><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($this->holding['requests_placed'])?></span>
          <?php endif; ?>
        <?php endif; ?>
      <?php endif; ?>
    </span>
    <span class="holding-field storage-retrieval">
      <?php if (isset($this->holding['storageRetrievalRequestLink']) && $this->holding['storageRetrievalRequestLink']): ?>
        <a class="<?=$this->checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($this->holding['storageRetrievalRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($this->checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
      <?php endif; ?>
    </span>
    <span class="holding-field ill-request">
      <?php if (isset($this->holding['ILLRequestLink']) && $this->holding['ILLRequestLink']): ?>
        <a class="<?=$this->checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->recordLink()->getRequestUrl($this->holding['ILLRequestLink'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($this->checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
      <?php endif; ?>
    </span>
    <?php if ($this->holding['availability']): ?>
      <span class="holding-field place-hold">
        <?php if (isset($this->holding['link']) && $this->holding['link']): ?>
          <a class="<?=$this->check ? 'checkRequest ' : ''?>placehold" <?php if (!empty($this->holding['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($this->holding['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($this->check ? "Check Hold" : "Place a Hold")?></a>
        <?php endif; ?>
      </span>
    <?php else: ?>
      <span class="holding-field recall">
        <?php if (isset($this->holding['link']) && $this->holding['link']): ?>
          <a class="<?=$this->check ? 'checkRequest' : ''?> placehold" <?php if (!empty($this->holding['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->recordLink()->getRequestUrl($this->holding['link'])?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($this->check ? "Check Recall" : "Recall This")?></a>
        <?php endif; ?>
      </span>
    <?php endif; ?>
  </div>

  <?php if (isset($this->holding['item_notes'])): ?>
  <div class="holding-notes">
    <div class="item-notes">
      <b><?=$this->transEsc("Item Notes")?>:</b>
      <ul>
        <?php foreach ($this->holding['item_notes'] as $item_note): ?>
          <li><?=$this->escapeHtml($item_note) ?></li>
        <?php endforeach; ?>
      </ul>
    </div>
  </div>
  <?php endif; ?>
  <?php /* Embed item structured data: library, barcode, call number */ ?>
  <?php if ($this->holding['location']): ?>
    <meta property="seller" content="<?=$this->escapeHtmlAttr($this->holding['location'])?>" />
  <?php endif; ?>
  <?php if ($this->holding['barcode']): ?>
    <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($this->holding['barcode'])?>" />
  <?php endif; ?>
  <?php if ($this->holding['callnumber']): ?>
    <meta property="sku" content="<?=$this->escapeHtmlAttr($this->holding['callnumber'])?>" />
  <?php endif; ?>
  <?php /* Declare that the item is to be borrowed, not for sale */ ?>
    <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
    <link property="itemOffered" href="#record" />
</td>
