<!-- START of: finna - RecordDriver/Primo/core.phtml -->
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">

  <? // if you have a preview tab but want to move or remove the preview link
      // from this area of the record view, this can be split into
      // getPreviewData() (should stay here) and
      // getPreviewLink() (can go in your desired tab) ?>
  <?=$this->record($this->driver)->getPreviews()?>

  <div class="col-sm-12">
    <div class="visible-print inline-block">
      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>
    <h1 property="name" class="record-title"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>

    <?
      $openUrl = $this->openUrl($this->driver, 'record');
      $openUrlActive = $openUrl->isActive();
      // Account for replace_other_urls setting
      $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    ?>

    <? if (!empty($urls) || $openUrlActive): ?>
      <div class="primo-available-online-record">
        <?=$this->partial('RecordDriver/Primo/online-url-list.phtml', ['driver' => $this->driver, 'urls' => $urls])?>
        <? if ($openUrlActive): ?>
          <?=$openUrl->renderTemplate()?>
        <? endif; ?>
      </div>
    <? endif; ?>
    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <div class="truncate-field wide">
        <p class="summary"><?=$summary;?></p>
      </div>
    <? endif; ?>

    <div class="record-authors">
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <div><?=$this->record($this->driver)->getFormatList()?></div>
      <? endif; ?>
      <? if ($authors = $this->driver->getCreators()): ?>
        <? foreach ($authors as $i => $field): ?><?=($i > 0) ? ' ; ' : ''?><span property="author"><a href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a></span><? endforeach; ?>
      <? endif; ?>
      <?
        $journalTitle = $this->driver->getContainerTitle();
        $summDate = $this->driver->getPublicationDates();
      ?>
      <? if (!empty($journalTitle)): ?>
        <?=$this->transEsc('Published in')?>:
          <?
            $containerSource = $this->driver->getSourceIdentifier();
            $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
      <? elseif (!empty($summDate)): ?>
        <?=$this->escapeHtml($summDate[0])?>
      <? endif; ?>
    </div>

    <?/* Display Main Details */?>
    <div class="record-details">
      <?
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->getData(
            $driver, $formatter->filterPrimoFields($formatter->getDefaults('core'))
        );
      ?>
      <? if (!empty($coreFields)): ?>
      <table class="table table-condensed table-finna-record" summary="<?=$this->transEsc('Bibliographic Details')?>">
          <? foreach ($coreFields as $key => $current): ?>
            <tr class="<?=$current['context']['class'];?>"><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
          <? endforeach; ?>
      </table>
      <? endif; ?>
      <?=$openUrl ? $openUrl->renderMoreOptions() : '' ?>
    </div>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>
    <?/* End Main Details */?>

    <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
    <div class="row">
      <div class="col-xs-12">
        <?=$this->render($template)?>
      </div>
    </div>
    <? endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/Primo/core.phtml -->
