<p>
    <button type="button" id="copyToClipboard" class="btn btn-primary hidden" role="button" tabindex="0"><?=$this->translate("copy_to_clipboard_button_label")?></button>
    <span id="copySuccessMessage" class="copyMessage hidden text-success"><small><?=$this->translate("copy_to_clipboard_success_message");?></small></span>
    <span id="copyFailureMessage" class="copyMessage hidden text-danger"><small><?=$this->translate("copy_to_clipboard_failure_message");?></small></span>
</p>
<?php
$script = <<<JS
  $(document).ready(function copyToClipboard() {
    if (navigator.clipboard) {
      const button = $("#copyToClipboard");
      button.removeClass('hidden');
      button.click(function copyToClipboard() {
        navigator.clipboard.writeText($('${selector}').text()).then(
            function copySuccess() {
                $("#copyFailureMessage").addClass("hidden");
                $("#copySuccessMessage").removeClass("hidden");
            },
            function copyFailure() {
                $("#copySuccessMessage").addClass("hidden");
                $("#copyFailureMessage").removeClass("hidden");
            }
        );
      });
    }
  });
JS;
// Inline the script for lightbox compatibility
echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
