<?php if ($this->pageCount): ?>
  <?php
    $results = $this->params['results'] ?? null;
    $showFirstLast = $this->pageCount > 3;
    $navAttrs = $this->htmlAttributes(['aria-label' => $this->translate('pagination_label')]);
    if ($results !== null) {
      $showFirstLast = $showFirstLast && $results->getOptions()->firstLastNavigationSupported();
      if ($results->getOptions()->loadResultsWithJsEnabled()) {
        $navAttrs->add('class', 'js-pagination');
        if ($this->top) {
          $navAttrs->add('class', 'js-pagination__top');
        }
      }
    }
  ?>
  <nav<?=$navAttrs?>>
    <?php
      $ulAttrs = $this->htmlAttributes(['class' => 'pagination']);
      if ($this->top) {
        $ulAttrs->add('class', 'pagination-top');
      }
      if ($className = $this->options['className'] ?? '') {
        $ulAttrs->add('class', $className);
      }
    ?>
    <ul<?=$ulAttrs?>>
      <?php if (isset($this->previous)): ?>
        <?php if ($showFirstLast && isset($this->first)): ?>
          <?=
            $this->render(
                'Helpers/pagination-item.phtml',
                [
                  'params' => $this->params,
                  'current' => $this->current,
                  'page' => $this->first,
                  'liClasses' => ['page-first'],
                  'label' => $this->translate('page_first'),
                  'contentHtml' => '[1]',
              ]
            )
          ?>
        <?php endif; ?>

        <?=
          $this->render(
              'Helpers/pagination-item.phtml',
              [
                'params' => $this->params,
                'current' => $this->current,
                'page' => $this->previous,
                'liClasses' => ['page-prev'],
                'label' => $this->translate('page_prev'),
                'contentHtml' => $this->icon('page-prev') . ' <span class="page-item-text">' . $this->transEsc('Prev') . '</span>',
            ]
          )
        ?>
      <?php endif; ?>

      <?php if (count($this->pagesInRange) > 1): ?>
        <?php foreach ($this->pagesInRange as $page): ?>
          <?=
            $this->render(
                'Helpers/pagination-item.phtml',
                [
                  'params' => $this->params,
                  'current' => $this->current,
                  'page' => $page,
                  'liClasses' => ['page-num'],
                  'label' => $this->translate('page_num', ['%%page%%' => $page]),
                  'contentHtml' => $this->escapeHtml($page),
              ]
            )
          ?>
        <?php endforeach; ?>
      <?php endif; ?>

      <?php if (isset($this->next)): ?>
        <?=
          $this->render(
              'Helpers/pagination-item.phtml',
              [
                'params' => $this->params,
                'current' => $this->current,
                'page' => $this->next,
                'liClasses' => ['page-next'],
                'label' => $this->translate('page_next'),
                'contentHtml' => '<span class="page-item-text">' . $this->transEsc('Next') . '</span> ' . $this->icon('page-next'),
            ]
          )
        ?>

        <?php if ($showFirstLast && isset($this->last)): ?>
          <?=
            $this->render(
                'Helpers/pagination-item.phtml',
                [
                  'params' => $this->params,
                  'current' => $this->current,
                  'page' => $this->last,
                  'liClasses' => ['page-last'],
                  'label' => $this->translate('page_last'),
                  'contentHtml' => '[' . $this->escapeHtml($this->pageCount) . ']',
              ]
            )
          ?>
        <?php endif; ?>
      <?php endif; ?>
    </ul>
  </nav>
<?php endif; ?>
