<?php if ($this->pageCount): ?>
  <nav aria-label="<?=$this->transEscAttr('pagination_label')?>">
    <ul class="pagination">
      <?=
        $this->render(
            'Helpers/pagination-item.phtml',
            [
              'params' => $this->params,
              'current' => $this->current,
              'page' => $this->first ?? null,
              'label' => $this->translate('page_first'),
              'contentHtml' => '[1]',
          ]
        )
      ?>

      <?=
        $this->render(
            'Helpers/pagination-item.phtml',
            [
              'params' => $this->params,
              'current' => $this->current,
              'page' => $this->previous ?? null,
              'liClasses' => ['page-prev'],
              'label' => $this->translate('page_prev'),
              'contentHtml' => $this->icon('page-prev') . ' ' . $this->transEsc('Prev'),
          ]
        )
      ?>

      <?php foreach ($this->pagesInRange as $page): ?>
        <?=
          $this->render(
              'Helpers/pagination-item.phtml',
              [
                'params' => $this->params,
                'current' => $this->current,
                'currentActive' => true,
                'page' => $page,
                'label' => $this->translate('page_num', ['%%page%%' => $page]),
                'contentHtml' => $this->escapeHtml($page),
            ]
          )
        ?>
      <?php endforeach; ?>

      <?=
        $this->render(
            'Helpers/pagination-item.phtml',
            [
              'params' => $this->params,
              'current' => $this->current,
              'page' => $this->next ?? null,
              'liClasses' => ['page-next'],
              'label' => $this->translate('page_next'),
              'contentHtml' => $this->transEsc('Next') . ' ' . $this->icon('page-next'),
          ]
        )
      ?>

      <?=
        $this->render(
            'Helpers/pagination-item.phtml',
            [
              'params' => $this->params,
              'current' => $this->current,
              'page' => $this->last ?? null,
              'label' => $this->translate('page_last'),
              'contentHtml' => $this->escapeHtml('[' . $this->pageCount . ']'),
          ]
        )
      ?>
    </ul>
  </nav>
<?php endif; ?>
