<!-- About -->
<li class="nav-item">
    <a class="nav-link" href="<?=$this->url('content-page', ['page' => 'about_us']) ?>"><i class="fa fa-info-circle"></i> <?=$this->transEsc('About us');?></a>
</li>
<!-- A-Z -->
<li class="nav-item">
    <a class="nav-link" href="<?=$this->url('content-page', ['page' => 'A-Z']) ?>"><i class="fa fa-question-circle"></i> <?=$this->transEsc('IxTheo A-Z');?></a>
</li>
