<!-- About -->
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown"  href="#" role="button" aria-haspopup="true" aria-expanded="false">
        <i class="fa fa-info-circle"> </i>
        <?=$this->transEsc('About');?> <span class="caret"></span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
        <li><a class="dropdown-item" href="<?=$this->url('help-home')?>?topic=search" data-lightbox><?= $this->transEsc('Search Tips') ?></a></li>
        <li><a class="dropdown-item" href="/team"><?=$this->transEsc('Team');?></a></li>
        <li><a class="dropdown-item">about us</a></li>
        <li><a class="dropdown-item" href="A-Z"> IxTheo A-Z</a></li>
    </ul>
</li>
