<?php $account = $this->auth()->getManager();
  if (is_object($account) && $account->loginEnabled()): // hide login/logout if unavailable ?>
  <li class="logoutOptions<?php if($account->dropdownEnabled()): ?> with-dropdown<?php endif ?><?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
    <a href="<?=$this->url('myresearch-home', [], ['query' => ['redirect' => 0]])?>"><i id="account-icon" class="fa fa-user-circle" aria-hidden="true"></i> <?=$this->transEsc("Your Account")?></a>
  </li>
  <?php if($account->dropdownEnabled()): ?>
    <li id="login-dropdown" class="dropdown<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
      <a href="#" data-toggle="dropdown"><i class="fa fa-caret-down"></i></a>
      <div class="dropdown-menu">
        <?=$this->render('myresearch/menu'); ?>
      </div>
    </li>
  <?php endif; ?>
  <li class="logoutOptions<?php if(!$account->isLoggedIn()): ?> hidden<?php endif ?>">
    <a href="<?=$this->url('myresearch-logout')?>" class="logout"><i class="fa fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?></a>
  </li>
  <li id="loginOptions"<?php if($account->isLoggedIn()): ?> class="hidden"<?php endif ?>>
    <?php if ($account->getSessionInitiator($this->serverUrl($this->url('myresearch-home')))): ?>
      <a href="<?=$this->url('myresearch-userlogin')?>"><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Institutional Login")?></a>
    <?php else: ?>
      <a href="<?=$this->url('myresearch-userlogin')?>" data-lightbox><i class="fa fa-sign-in" aria-hidden="true"></i> <?=$this->transEsc("Login")?></a>
    <?php endif; ?>
  </li>
<?php endif; ?>