<?php if (strlen($item['barcode'] ?? '') > 0 || str_contains($item['location_code'], 'cush')): ?>
  <?php
    $check = $item['check'] ?? false;
    $checkStorageRetrievalRequest = $item['checkStorageRetrievalRequest'] ?? false;
    $checkILLRequest = $item['checkILLRequest'] ?? false;
    if ($i == 0) {
  ?>
  <tr>
    <th>Call Number</th>
    <th>Status</th>
    <th>Get It</th>
  </tr>
  <?php
    }
  ?>
  <tr vocab="http://schema.org/" typeof="Offer">
      <td class="copy-number">
        <?=$this->escapeHtmlAttr($item['call_number_formatted'])?> <?=$this->escapeHtml($item['enumeration'])?>
      <?php if ($item['enumchron'] ?? false): ?>
        <span class="enumchron">(<?=$this->escapeHtml($item['enumchron'])?>)</span>
      <?php endif; ?>
      <?php if ($item['item_chronology'] ?? false): ?>
        <?=$this->escapeHtml($item['item_chronology'])?>
      <?php endif; ?>
    </td>
    <td>
      <?php if ($item['reserve'] == "Y"): ?>
        <link property="availability" href="http://schema.org/InStoreOnly" />
        <?=$this->transEsc("On Reserve - Ask at Circulation Desk")?><br />
      <?php endif; ?>
      <?php if ($item['use_unknown_message'] ?? false): ?>
        <span class="text-muted"><?=$this->transEsc("status_unknown_message")?></span>
      <?php else: ?>
        <?php if ($item['availability'] ?? false): ?>
          <?php /* Begin Available Items (Holds) */ ?>
           <span class="text-success"><?=$this->transEsc("Available")?><link property="availability" href="http://schema.org/InStock" /></span>

      <?php if (1 == 2) { ?>

          <?php if ($item['link'] ?? false): ?>
            <a class="<?=$check ? 'checkRequest ' : ''?>placehold" <?php if (!empty($item['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($item['link']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Hold" : "Place a Hold")?></a>
          <?php endif; ?>

      <?php } ?>

          <?php if ($item['storageRetrievalRequestLink'] ?? false): ?>
            <a class="<?=$checkStorageRetrievalRequest ? 'checkStorageRetrievalRequest ' : ''?> placeStorageRetrievalRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($item['storageRetrievalRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkStorageRetrievalRequest ? "storage_retrieval_request_check_text" : "storage_retrieval_request_place_text")?></a>
          <?php endif; ?>

      <?php if (1 == 2) { ?>

          <?php if ($item['ILLRequestLink'] ?? false): ?>
            <a class="<?=$checkILLRequest ? 'checkILLRequest ' : ''?>placeILLRequest" data-lightbox href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($item['ILLRequestLink']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($checkILLRequest ? "ill_request_check_text" : "ill_request_place_text")?></a>
          <?php endif; ?>

      <?php } ?>

        <?php else: ?>
          <?php /* Begin Unavailable Items (Recalls) */ ?>
          <span class="text-danger"><?=$this->transEsc($item['status'])?><link property="availability" href="http://schema.org/OutOfStock" /></span>
          <?php if ($item['returnDate'] ?? false): ?>&ndash; <span class="small"><?=$this->escapeHtml($item['returnDate'])?></span><?php endif; ?>
          <?php if ($item['duedate'] ?? false): ?>
            &ndash; <span class="small"><?=$this->transEsc("Due")?>: <?=$this->escapeHtml($item['duedate'])?></span>
          <?php endif; ?>
          <?php if (($item['requests_placed'] ?? 0) > 0): ?>
            <span><?=$this->transEsc("Requests")?>: <?=$this->escapeHtml($item['requests_placed'])?></span>
          <?php endif; ?>

      <?php if (1 == 2) { ?>

          <?php if ($item['link'] ?? false): ?>
            <a class="<?=$check ? 'checkRequest' : ''?> placehold" <?php if (!empty($item['linkLightbox'])): ?>data-lightbox <?php endif; ?>href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($item['link']))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc($check ? "Check Recall" : "Recall This")?></a>
          <?php endif; ?>

      <?php } ?>

          <?=$this->relais()->renderButtonIfActive($this->driver ?? null)?>
        <?php endif; ?>
        <?php if (isset($item['item_notes'])): ?>
          <div class="item-notes">
            <b><?=$this->transEsc("Item Notes")?>:</b>
            <ul>
              <?php foreach ($item['item_notes'] as $item_note): ?>
                <li><?=$this->escapeHtml($item_note) ?></li>
              <?php endforeach; ?>
            </ul>
          </div>
        <?php endif; ?>
      <?php endif; ?>
      <?php /* Embed item structured data: library, barcode, call number */ ?>
      <?php if ($item['location'] ?? false): ?>
        <meta property="seller" content="<?=$this->escapeHtmlAttr($item['location'])?>" />
      <?php endif; ?>
      <?php if ($item['barcode'] ?? false): ?>
        <meta property="serialNumber" content="<?=$this->escapeHtmlAttr($item['barcode'])?>" />
      <?php endif; ?>
      <?php if ($item['callnumber'] ?? false): ?>
        <meta property="sku" content="<?=$this->escapeHtmlAttr($item['callnumber'])?>" />
      <?php endif; ?>
      <?php /* Declare that the item is to be borrowed, not for sale */ ?>
      <link property="businessFunction" href="http://purl.org/goodrelations/v1#LeaseOut" />
      <link property="itemOffered" href="#record" />
    </td>
    <td class="getit" id="getit_<?php echo $item['item_hrid'];?>"></td>
  </tr>
<?php endif; ?>
