<?php
    $this->mainTreeClass = 'col-sm-6';
    $this->treeContext = 'Collection';
?>
<div class="row">
  <div class="col-sm-6">
    <?=$this->render('RecordTab/hierarchytree.phtml')?>
  </div>
  <div class="col-sm-6">
    <div id="hierarchyRecordHolder">
      <div id="hierarchyRecord">
        <?php if (($collectionRecord = $this->tab->getActiveRecord()) !== false): ?>
          <?php if ($collectionRecord === null): ?>
            <?=$this->render('collection/collection-record-error.phtml')?>
          <?php else: ?>
            <?=html_entity_decode($this->record($collectionRecord)->getCollectionBriefRecord())?>
          <?php endif; ?>
        <?php endif; ?>
      </div>
    </div>
  </div>
</div>
