<?php
  // Set page title.
  $this->headTitle($this->translate('Collection Items') . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  $results = $this->tab->getResults();
  $params = $this->tab->getParams();
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];
?>
<?php if (($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
  <?php foreach ($results->getRecommendations('top') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
  <div class="clearfix hidden-print">
    <div class="pull-left flip">
      <?php
        $transParams = [
          '%%start%%' => $this->localizedNumber($results->getStartRecord()),
          '%%end%%' => $this->localizedNumber($results->getEndRecord()),
          '%%total%%' => $this->localizedNumber($recordTotal)
        ];
      ?>
      <?php if (!isset($this->skipTotalCount)): ?>
        <?=$this->translate('showing_items_of_html', $transParams); ?>
      <?php else: ?>
        <?=$this->translate('showing_items_html', $transParams); ?>
      <?php endif; ?>
    </div>
    <div class="pull-right flip">
      <?=$this->render('search/controls/limit.phtml', $searchDetails)?>
      <?=$this->render('search/controls/sort.phtml', $searchDetails)?>
    </div>
  </div>
  <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>">
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', $searchDetails + ['idPrefix' => ''])?>
    <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
    <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results])?>
  </form>
<?php else: ?>
  <?=$this->transEsc('collection_empty')?>
<?php endif; ?>
