<?
    $this->mainTreeClass = 'col-sm-6';
    $this->treeContext = 'Collection';
?>
<div class="row">
  <?=$this->render('RecordTab/hierarchytree.phtml')?>
  <div class="col-sm-6">
    <div id="hierarchyRecordHolder">
      <div id="hierarchyRecord">
        <? if (($collectionRecord = $this->tab->getActiveRecord()) !== false): ?>
          <? if ($collectionRecord === null): ?>
            <?=$this->render('collection/collection-record-error.phtml')?>
          <? else: ?>
            <?=html_entity_decode($this->record($collectionRecord)->getCollectionBriefRecord())?>
          <? endif; ?>
        <? endif; ?>
      </div>
    </div>
  </div>
</div>
