<?php $max = $this->tab->getMaxResults(); $showMore = false; ?>
<?php foreach ($this->tab->getResults() as $i => $current): ?>
  <?php
    if ($max == $i) {
      $showMore = true;
      break;
    }
  ?>
  <div>
    <?=($i + 1)?>.
    <a href="<?=$this->recordLink()->getUrl($current)?>">
      <?=$this->record($current)->getTitleHtml()?>
    </a>
  </div>
<?php endforeach; ?>
<?php if ($showMore): ?>
  <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>">
    <?=$this->transEsc('see all')?>
  </a>
<?php endif; ?>
