<?
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter();
    $mainFields = $formatter->getData($driver, $formatter->getDefaults('description'));
?>

<?
    $description = $this->Description($this->driver)->getItems();
?>
<? if (!empty($description)): ?>
    <? foreach ($description as $itemName => $itemValue): ?>
      <div class='col-xs-12 rds-dl'>
         <div class="col-xs-12 col-md-5 col-lg-4 rds-dl-head <?=$itemName?>">
            <?=$this->translate($itemName) ?>
         </div>
         <div class="col-xs-12 col-md-7 col-lg-8 rds-dl-panel">
            <?= $itemValue ?>
         </div>
      </div>
    <? endforeach; /* end foreach description */ ?>
<? endif; ?>


<table class="table table-striped" summary="<?=$this->transEsc('Description')?>">
  <? if (!empty($mainFields)): ?>
    <? foreach ($mainFields as $key => $current): ?>
      <tr><th><?=$this->transEsc($key)?>:</th><td><?=$current['value']?></td></tr>
    <? endforeach; ?>
  <? else: ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <? endif; ?>
</table>
