<?php
  // Set page title.
  $this->headTitle('Formats' . ': ' . $this->driver->getBreadcrumb());
?>
<table class="table table-striped">
  <?php foreach ($this->driver->getFormattedDigitalFormats() as $formatkey => $format): ?>
    <tr>
      <th colspan="2"><?=  $this->translate($formatkey)?></th>
    </tr>
        <?php foreach ((array)$format as $key => $value): ?>
        <tr>
          <td><?=$key ?></td><td><?=$value ?></td>
        </tr>
        <?php endforeach; ?>
  <?php endforeach; ?>
</table>
<?php  ?>