<?php
  // Set page title.
  $this->headTitle($this->translate('hierarchy_tree') . ': ' . $this->driver->getBreadcrumb());
  $hierarchyTreeList = $this->tab->getTreeList();
  $activeTree = $this->tab->getActiveTree();

  $this->inlineScript(
     \Laminas\View\Helper\HeadScript::SCRIPT,
     "var hierarchySettings = {\n"
     . "    lightboxMode: " . ($this->layout()->getTemplate() == 'layout/lightbox' ? 'true' : 'false') . ",\n"
     . "    fullHierarchy: " . ($this->tab->isFullHierarchyVisible() ? 'true' : 'false') . "\n"
     . "};\n"
     . "VuFind.addTranslations({\n"
     . "    'showTree': '" . $this->transEsc('hierarchy_show_tree') . "',\n"
     . "    'hideTree': '" . $this->transEsc('hierarchy_hide_tree') . "'}\n"
     . ");\n",
     'SET'
  );
  $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'vendor/jsTree/jstree.min.js');
  $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'hierarchyTree.js');
  echo $this->inlineScript();
?>
<?php if (count($hierarchyTreeList) > 1): ?>
  <div id="treeSelector">
    <?php foreach ($hierarchyTreeList as $hierarchy => $hierarchyTitle): ?>
      <?php if($activeTree == $hierarchy): ?>
        <i class="fa fa-sitemap" aria-hidden="true"></i> <?=$this->escapeHtml($hierarchyTitle)?>
      <?php else: ?>
        <i class="fa fa-sitemap text-muted" aria-hidden="true"></i> <a href="<?=$this->recordLink()->getTabUrl($this->driver, 'HierarchyTree', ['hierarchy' => $hierarchy])?>"><?=$this->escapeHtml($hierarchyTitle)?></a>
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<?php if ($activeTree): ?>
  <div id="hierarchyTreeHolder">
    <?php if ($this->tab->searchActive()): ?>
      <div id="treeSearch" class="form-inline hidden">
        <input type="text" id="treeSearchText" class="form-control search-query" value="">
        <select class="form-control" id="treeSearchType" name="type">
          <option value="AllFields"><?=$this->transEsc('All Fields')?></option>
          <option value="Title"><?=$this->transEsc('Title')?></option>
        </select>
        <input type="submit" class="btn btn-default" value="<?=$this->transEscAttr('Search') ?>"/>
        <i id="treeSearchLoadingImg" class="fa fa-spinner fa-spin hidden" aria-hidden="true"></i>
      </div>
      <div id="treeSearchNoResults" class="alert alert-danger hidden"><?=$this->translate('nohit_heading')?></div>
      <div id="treeSearchLimitReached" class="alert alert-danger hidden"><?=$this->translate('tree_search_limit_reached_html', ['%%url%%' => $this->url('search-results'), '%%limit%%' => $this->tab->getSearchLimit()])?></div>
    <?php endif; ?>
    <div id="hierarchyLoading" class="hide"><i class="fa fa-spinner fa-spin" aria-hidden="true"></i> <?=$this->transEsc("Loading")?>...</div>
    <div id="hierarchyTree" class="hierarchy-tree">
      <input type="hidden" value="<?=$this->escapeHtml($this->driver->getUniqueId())?>" class="hiddenRecordId" />
      <input type="hidden" value="<?=$this->escapeHtml($activeTree)?>" class="hiddenHierarchyId" />
      <input type="hidden" value="<?=$this->escapeHtml($this->driver->getSourceIdentifier())?>" class="hiddenHierarchySource" />
      <input type="hidden" value="<?=$this->treeContext ?? 'Record'?>" class="hiddenContext" />
      <?php if ($this->layout()->getTemplate() != 'layout/lightbox'): ?>
        <noscript>
          <?php if ($this->config()->nonJavascriptSupportEnabled()): ?>
            <ul class="fa-ul">
              <?=$this->tab->renderTree($this->url('home'))?>
            </ul>
          <?php else: ?>
            <?=$this->transEsc('Please enable JavaScript.')?>
          <?php endif; ?>
        </noscript>
      <?php endif; ?>
    </div>
  </div>
<?php endif; ?>
