<h2><?=$this->transEsc('Similar Items')?></h2>
<?php $similarRecords = $this->tab->getResults(); ?>
<?php if (!empty($similarRecords)): ?>
  <div id="similar-items-carousel" class="carousel splide" role="group" data-carousel aria-label="<?=$this->transEsc('Similar Items')?>">
    <div class="splide__track">
      <ul class="splide__list">
        <?php foreach ($similarRecords as $index => $data): ?>
          <li class="carousel-item splide__slide">
            <a class="hover-overlay record-cover-link" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($data))?>">
              <?=$this->record($data)->getCoverDetails('similar-items', 'large')['html']?>
              <div class="content">
                <?php
                  $formats = $data->getFormats();
                  $format = $formats[0] ?? null;
                  $icon = $format
                    ? preg_replace('/[^a-z0-9]/', '', strtolower($format))
                    : 'default';
                ?>
                <?=$this->icon('format-' . $icon, $format ? ['title' => $format] : []) ?>
                <b><?=$this->escapeHtml($data->getTitle())?></b>
                <?php $authors = $data->getPrimaryAuthors(); ?>
                <?php if (!empty($authors)): ?>
                  <br><?=$this->transEsc('by')?>: <?=$this->escapeHtml($authors[0]);?><?php if (count($authors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><?php endif; ?>
                <?php endif; ?>
                <?php $pubDates = $data->getPublicationDates(); ?>
                <?php if (!empty($pubDates)): ?>
                  <br><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
                <?php endif; ?>
              </div>
            </a>
          </li>
        <?php endforeach; ?>
      </ul>
    </div>
  </div>
<?php else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<?php endif; ?>
