<?
    // Set page title.
    $this->headTitle($this->translate('Table of Contents') . ': ' . $this->driver->getBreadcrumb());

    $toc_content = $this->tab->getContent();
    $toc = [];
    if (empty($toc_content)) {
        $toc = $this->driver->getTOC();
    } else {
        $toc = reset($toc_content);
    }
?>
<? if (!empty($toc)): ?>
  <strong><?=$this->transEsc('Table of Contents')?>: </strong>
  <ul class="toc">
    <? foreach ($toc as $line): ?>
      <li><?=$this->escapeHtml($line)?></li>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <?=$this->transEsc("Table of Contents unavailable")?>.
<? endif; ?>
