<?
  // Set page title.
  $this->headTitle($this->translate('Comments') . ': ' . $this->driver->getBreadcrumb());
?>

<div id="commentList">
  <?=$this->render('record/comments-list.phtml')?>
</div>
<form class="comment row" name="commentRecord" id="commentRecord" action="<?=$this->recordLink()->getActionUrl($this->driver, 'AddComment')?>" method="post">
  <div class="col-sm-3 name">
    <strong><?=$this->transEsc("Your Comment")?></strong>
  </div>
  <div class="col-sm-9">
    <textarea id="comment" name="comment" class="form-control" rows="3" required></textarea><br/>
    <input class="btn" data-loading-text="<?=$this->transEsc('Submitting') ?>..." type="submit" value="<?=$this->transEsc("Add your comment")?>"/>
  </div>
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId())?>"/>
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?>"/>
</form>
