<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'catalogs']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Catalogues and databases</h4>
            <p>Research options</p>
        </div>
    </a>
</div>
