<div class="col-xs-12 col-sm-6 col-md-3 panel-buttons">
    <div class="panel-button">
        <a href="<?=$this->url('content-page', ['page' => 'fulltexts']) ?>" class="btn btn-primary">
            Criminological<br/>full texts
        </a>
    </div>
    <div class="panel-button">
        <a href="<?=$this->url('content-page', ['page' => 'journals']) ?>" class="btn btn-primary">
            Criminological<br/>journals
        </a>
    </div>
</div>
