<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-inverse">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'news']) ?>"><div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/news.jpg') ?>" alt="" class="img-responsive panel-image" /></div></a>
    <div class="panel-content">
        <h4>Notifications &amp; dates</h4>
        <p>
        <ul>
            <li><a href="<?=$this->url('content-page', ['page' => 'call_for_papers']) ?>">Call for Papers</a></li>
            <li><a href="<?=$this->url('content-page', ['page' => 'events']) ?>">Congresses &amp; conferences</a></li>
        </ul>
        </p>
    </div>
</div>
