<div class="panel panel-bottom panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'partners'])?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/coffee.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>Cooperations</h4>
            <p>Who are we collaborating with?</p>
        </div>
    </a>
</div>
