<div id="contact_form">
  <form method="post" action="<?=$this->url('feedback-email')?>">
    <p class="feedbackHeader"><b><?=$this->transEsc("Send us your feedback!")?></b></p>
    <label for="name" style="line-height: 2.5;">
      <?=$this->transEsc("feedback_name")?></label>
    <label class="error" for="name">
      <?=$this->transEsc("Please enable JavaScript.")?></label><br />
    <input type="text" id="name" size="30" class="text-input <?=$this->jqueryValidation(array('required'=>'This field is required'))?>" /><br />
    <label for="email" style="line-height: 2.5;">
      <?=$this->transEsc("Email")?></label><br />
    <input type="text" id="email" size="30" class="text-input <?=$this->jqueryValidation(array('required'=>'This field is required', 'email'=>'Email address is invalid'))?>" /><br />
    <label for="comments" style="line-height: 2.5;">
      <?=$this->transEsc("Comments")?></label><br />
    <textarea id="comments" style="width:250px;height:130px" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"></textarea><br />
    <input type="submit" class="button" value="<?=$this->transEsc("Send")?>" />
    <input type="hidden" id="formSuccess" value="<?=$this->transEsc("Form Submitted!")?>"/>
    <input type="hidden" id="feedbackSuccess" value="<?=$this->transEsc("Thank you for your feedback.")?>"/>
    <input type="hidden" id="feedbackFailure" value="<?=$this->transEsc("An error has occurred")?>"/>
  </form>
</div>
