<label class="displayBlock" for="email_to"><?=$this->transEsc('To')?>:</label>
<input id="email_to" type="text" name="to" value="<?=isset($this->to) ? $this->to : ''?>" size="40" class="mainFocus <?=$this->jqueryValidation(array('required'=>'This field is required', 'email'=>'Email address is invalid'))?>"/>
<? if (!$this->disableFrom): ?>
  <label class="displayBlock" for="email_from"><?=$this->transEsc('From')?>:</label>
  <input id="email_from" type="text" name="from" value="<?=isset($this->from) ? $this->from : ''?>" size="40" class="<?=$this->jqueryValidation(array('required'=>'This field is required', 'email'=>'Email address is invalid'))?>"/>
<? endif; ?>
<? if ($this->editableSubject): ?>
  <label class="displayBlock" for="email_subject"><?=$this->transEsc('email_subject')?>:</label>
  <input id="email_subject" type="text" name="subject" value="<?=isset($this->subject) ? $this->subject : ''?>" size="40" class="<?=$this->jqueryValidation(array('required'=>'This field is required'))?>"/>
<? endif; ?>
<label class="displayBlock" for="email_message"><?=$this->transEsc('Message')?>:</label>
<textarea id="email_message" name="message" rows="3" cols="40"><?=isset($this->message) ? $this->message : ''?></textarea>
<br/>
<?=$this->recaptcha()->html($this->useRecaptcha) ?>
<input class="button" type="submit" name="submit" value="<?=$this->transEsc('Send')?>"/>
<? if ($this->disableFrom && $this->userEmailInFrom): ?>
  <input type="checkbox" id="ccme" name="ccself"/><label for="ccme"><?=$this->translate('send_email_copy_to_me'); ?></label>
<? endif; ?>
