<!--
See http://developer.yahoo.com/ypatterns/pattern.php?pattern=searchpagination
-->
<?php if ($this->pageCount): ?>
<div class="paginationControl">

<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <? $newParams = $this->params; $newParams['page'] = $this->previous; ?>
  <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
    < <?=$this->translate('Previous')?>
  </a> |
<?php else: ?>
  <span class="disabled">< <?=$this->translate('Previous')?></span> |
<?php endif; ?>

<!-- First page link -->
<?php if (isset($this->first) && $this->first != $this->current): ?>
  <? $newParams = $this->params; $newParams['page'] = $this->first; ?>
  <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
    <?=$this->translate('First')?>
  </a>|
<?php else: ?>
  <span class="disabled"><?=$this->translate('First')?> </span>|
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <? $newParams = $this->params; $newParams['page'] = $page; ?>
    <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
        <?php echo $page; ?>
    </a> |
  <?php else: ?>
    <?php echo $page; ?> |
  <?php endif; ?>
<?php endforeach; ?>

<!-- Last page link -->
<?php if (isset($this->last)  && $this->last != $this->current): ?>
  <? $newParams = $this->params; $newParams['page'] = $this->last; ?>
  <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
    <?=$this->translate('Last')?>
  </a>
  |
<?php else: ?>
  <span class="disabled"><?=$this->translate('Last')?> </span>|
<?php endif; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <? $newParams = $this->params; $newParams['page'] = $this->next; ?>
  <a href="<?= $this->currentPath() . '?' . http_build_query($newParams); ?>">
    <?=$this->translate('Next')?> >
  </a>
<?php else: ?>
  <span class="disabled"><?=$this->translate('Next')?> ></span>
<?php endif; ?>

</div>
<?php endif; ?>
