<!-- START of: finna - Auth/MultiILS/login.phtml -->
<? $account = $this->auth()->getManager(); ?>
<? $sessionInitiator = $account->getSessionInitiator($this->serverUrl($this->url('myresearch-home'))); ?>
<? if (!$sessionInitiator): // display default login form if no login URL provided ?>
<div class="row">
  <form method="post" class="form-vertical" action="<?=$this->url('myresearch-home')?>" name="loginForm" id="loginForm">
    <?=$this->auth()->getLoginFields()?>
    <input type="hidden" name="auth_method" value="<?=$account->getAuthMethod()?>">
    <input type="hidden" name="csrf" value="<?=$this->escapeHtmlAttr($account->getCsrfHash(true))?>" />
    <div class="form-group">
      <div class="col-sm-9">
        <? if ($account->supportsCreation()): ?>
          <a class="btn btn-link createAccountLink" href="<?=$this->url('myresearch-account') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Create New Account')?></a>
        <? endif; ?>
        <input class="btn btn-primary" type="submit" name="processLogin" value="<?=$this->transEsc('Login')?>">
        <? if ($account->supportsRecovery()): ?>
          <br/>
          <a class="btn btn-link" href="<?=$this->url('myresearch-recover') ?>?auth_method=<?=$account->getAuthMethod()?>"><?=$this->transEsc('Forgot Password')?></a>
        <? endif; ?>
      </div>
    </div>
  </form>
</div>
<? else: ?>
  <a href="<?=$this->escapeHtmlAttr($sessionInitiator)?>"><?=$this->transEsc("Institutional Login")?></a>
<? endif; ?>
<!-- END of: finna - Auth/MultiILS/login.phtml -->
