<!-- START of: finna - Auth/MultiILS/loginfields.phtml -->
<div class="col-sm-6">
  <div class="form-group">
    <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
    <? if (count($this->auth()->getManager()->getLoginTargets()) > 1): ?>
      <label class="control-label" for="login_target"><?=$this->transEsc('login_target')?>:</label>
      <select id="login_target" name="target" class="form-control">
        <?foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
        <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
        <? endforeach ?>
      </select>
    <? else: ?>
      <input type="hidden" id="login_target" name="target" value="<?=$this->escapeHtmlAttr($currentTarget)?>">
      <div><strong><?=$this->transEsc("source_$currentTarget", null, $currentTarget)?></strong></div>
    <? endif; ?>
  </div>
  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="form-control"/>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_secondary_username"></label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_secondary_username" type="text" name="secondary_username" value="<?=$this->escapeHtmlAttr($this->request->get('secondary_username'))?>" class="form-control"/>
  </div>

  <div class="form-group">
    <label class="control-label" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" type="password" name="password" class="form-control"/>
  </div>
</div>
<div class="col-sm-6 hidden-xs">
  <div class="login-description">
    <p class="login-info">
      <?=$this->translate('login_desc_library_card_html') ?>
    </p>
  </div>
</div>

<?
  $labels = [];
  foreach ($this->auth()->getManager()->getLoginTargets() as $target) {
    $label = $this->auth()->getManager()->getSecondaryLoginFieldLabel($target);
    $labels[] = '"' . addslashes($target) . '": "' . ($label ? addslashes($this->translate($label)) : '') . '"';
  }

  $labels = implode(', ', $labels);
  $script = <<<EOT
  finna.layout.initSecondaryLoginField({{$labels}}, '{$topClass}');
EOT;

  // Inline the script for lightbox compatibility
  echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>

<!-- END of: finna - Auth/MultiILS/loginfields.phtml -->
