<script>
  $(document).ready(function() {
    <? if (isset($this->searchDetails) && is_object($this->searchDetails)): ?>
      <? foreach ($this->searchDetails->getQueries() as $searchGroup): ?>
        <? $i = 0; foreach ($searchGroup->getQueries() as $search): ?>
          <? if (++$i == 1): ?>
            var new_group = addGroup(
              '<?=addslashes($search->getString())?>',
              '<?=addslashes($search->getHandler())?>',
              '<?=$searchGroup->isNegated() ? 'NOT' : $searchGroup->getOperator()?>'
            );
          <? else: ?>
            addSearch(new_group,
              '<?=addslashes($search->getString())?>',
              '<?=addslashes($search->getHandler())?>',
              '<?=addslashes($search->getOperator())?>'
            );
          <? endif; ?>
        <? endforeach; ?>
      <? endforeach; ?>
    <? else: ?>
      var new_group = addGroup();
      addSearch(new_group);
      addSearch(new_group);
    <? endif; ?>
  });
</script>

<script type="text/template" id="new_search_template">
  <div class="search row">
    <div class="col-sm-3">
      <input type="hidden" value="AND" class="first-join"/>
      <label class="help-block"><?=$this->transEsc("adv_search_label")?>:</label>
      <select class="join col-sm-9 form-control">
        <option value="AND"><?=$this->transEsc("AND")?></option>
        <option value="OR"><?=$this->transEsc("OR")?></option>
        <option value="NOT"><?=$this->transEsc("NOT")?></option>
      </select>
    </div>
    <div class="col-sm-9">
      <div class="col-sm-6">
        <input class="form-control" type="text"/>
      </div>
      <span class="col-sm-1 help-block"><?=$this->transEsc("in")?></span>
      <div class="col-sm-4">
        <select class="type form-control">
          <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
            <option value="<?=$this->escapeHtml($searchVal)?>"><?=$this->transEsc($searchDesc)?></option>
          <? endforeach; ?>
        </select>
      </div>
      <a href="#" class="col-sm-1 help-block delete hidden">&times;</a>
    </div>
  </div>
</script>