<? if (isset($this->checkboxFacets) && count($this->checkboxFacets) > 0): ?>
  <div class="checkbox-filters">
    <? foreach ($this->checkboxFacets as $current): ?>
      <div class="checkbox">
        <label>
          <input type="checkbox" name="filter[]" value="<?=$this->escapeHtmlAttr($current['filter'])?>" id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"<? if ($current['selected']): ?> checked="checked"<? endif; ?>/>
          <?=$this->transEsc($current['desc'])?>
        </label>
      </div>
    <? endforeach; ?>
  </div>
<?endif;?>
