<div class="row">
  <? if (!empty($this->expanderList)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc('eds_modes_and_expanders')?></legend>
      <? foreach ($this->expanderList as $field => $expander):
        $value = $expander['Value'] ?>
        <div class="checkbox">
          <label for="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>">
            <input id="expand_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($expander['selected']) && $expander['selected'])?'checked="checked"':''?> name="filter[]" value="EXPAND:<?=$this->escapeHtmlAttr($value)?>">
            <?=$this->transEsc('eds_expander_' . $value, array(), $expander['Label'])?>
          </label>
        </div>
      <? endforeach; ?>

      <label class="displayBlock" for="searchModes"><?=$this->transEsc('Search Mode')?></label>
      <select id="searchMode_<?=$this->escapeHtmlAttr($field)?>" name="filter[]" class="form-control">
        <? foreach ($this->searchModes as $field => $searchMode):
          $value = $searchMode['Value'] ?>
          <option <?=(isset($searchMode['selected']) && $searchMode['selected'])?'selected="selected"':''?> value="SEARCHMODE:<?=$this->escapeHtmlAttr($value)?>">
            <?= /* 'Label' comes from API and is always in English; try to translate structured value before using it: */ $this->transEsc('eds_mode_' . $value, array(), $searchMode['Label']) ?>
          </option>
        <? endforeach; ?>
      </select>
    </fieldset>
  <? endif; ?>

  <? if (!empty($this->limiterList)): ?>
    <fieldset class="col-sm-4">
      <legend><?=$this->transEsc('Limit To')?></legend>
      <? foreach ($this->limiterList as $field => $facet): ?>
        <? switch($facet['Type']){
            case 'multiselectvalue': ?>
              <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>"><?=$this->transEsc($facet['Label'])?></label><br/>
              <select id="limit_<?=$this->escapeHtmlAttr($field)?>" name="filter[]" multiple="multiple" size="10" class="form-control">
                <? foreach ($facet['LimiterValues'] as $id => $facetValue): ?>
                  <? $value = $facetValue['Value']; ?>
                  <option value="<?='LIMIT|'.$this->escapeHtmlAttr($field . ':' . $facetValue['Value'])?>"<?=(isset($facetValue['selected']) && $facetValue['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($facetValue['Value'])?></option>
                <? endforeach; ?>
              </select>
              <!-- <br/> -->
              <? break;
            case 'select':
              $value = $facet['LimiterValues'][0]['Value'] ?>
              <div class="checkbox">
                <label for="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>">
                  <input id="limit_<?=$this->escapeHtmlAttr(str_replace(' ', '+', $field))?>" type="checkbox" <?=(isset($facet['LimiterValues'][0]['selected']) && $facet['LimiterValues'][0]['selected'])?'checked="checked"':''?> name="filter[]" value="<?=$this->escapeHtmlAttr('LIMIT|'.$field . ':' . $value)?>">
                  <?=$this->transEsc('eds_limiter_' . $field, array(), $facet['Label'])?>
                </label>
              </div>
              <? break;
            case 'text': ?>
              <!-- not implemented -->
              <? break;
            case 'numeric':?>
              <!-- not implemented -->
              <? break;
            case 'numericrange':?>
              <!-- not implemented -->
              <? break;
            case 'ymrange': ?>
              <!-- not implemented -->
              <? break;
            case 'yrange': ?>
              <!-- not implemented -->
              <? break;
            case 'historicalrange':?>
              <!-- not implemented -->
              <? break;
            case 'singleselectvalue':?>
              <!-- not implemented -->
              <? break;
          }; ?>
      <? endforeach; ?>
    </fieldset>
  <? endif; ?>
</div>