<?php $this->metadata()->generateMetatags($this->driver);?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <?php
    $QRCode = $this->record($this->driver)->getQRCode("core");
    $coverDetails = $this->record($this->driver)->getCoverDetails('core', 'medium', $this->record($this->driver)->getThumbnail('large'));
    $cover = $coverDetails['html'];
    $preview = ($this->previewOverride ?? false)
      ? $this->previewOverride : $this->record($this->driver)->getPreviews();
  ?>
  <?php if ($QRCode || $cover || $preview): ?>
    <div class="media-left <?=$this->escapeHtmlAttr($coverDetails['size'])?> img-col">
      <?php /* Display thumbnail if appropriate: */ ?>
      <?php if($cover): ?>
        <?=$cover?>
      <?php endif; ?>

      <?php /* Display qrcode if appropriate: */ ?>
      <?php if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEscAttr('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <?php endif; ?>

      <?php // if you have a preview tab but want to move or remove the preview link
         // from this area of the record view, this can be split into
         // getPreviewData() (should stay here) and
         // getPreviewLink() (can go in your desired tab) ?>
      <?php if ($preview): ?>
        <div class="record-previews">
          <?=$preview?>
        </div>
      <?php endif; ?>
    </div>
  <?php endif; ?>
  <div class="media-body">

    <h1 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h1>
    <?php foreach ($this->driver->tryMethod('getFullTitlesAltScript', [], []) as $altTitle): ?>
      <div class="title-alt">
        <?=$this->escapeHtml($altTitle)?>
      </div>
    <?php endforeach; ?>

    <?php if(!empty($this->extraControls)): ?>
      <?=$this->extraControls['actionControls'] ?? ''?>
      <?=$this->extraControls['availabilityInfo'] ?? ''?>
    <?php endif; ?>

    <?php if ($this->searchOptions($this->driver->getSourceIdentifier())->getVersionsAction()): ?>
      <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
    <?php endif; ?>

    <?php $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <?php if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <?php if(strlen($summary) > 300): ?>
        <p><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Description'))?>#tabnav"><?=$this->transEsc('Full description')?></a></p>
      <?php endif; ?>
    <?php endif; ?>

    <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
      <?php /* Display the lists that this record is saved to */ ?>
      <div class="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <?php endif; ?>

    <?php /* Display Main Details */ ?>
    <?php
      $formatter = $this->recordDataFormatter();
      $coreFields = $formatter->getData($driver, $formatter->getDefaults('core'));
    ?>
    <?php if (!empty($coreFields)): ?>
      <?php
      $issnParent = $this->driver->getMarcRecord()->getFields("22");
      $sfxData = new stdClass();
      $sfxData->issn = null;
      $sfxData->title = null;
      $sfxData->isValid = false;
      if ($issnParent) {
        $issnSubField = $issnParent[0]->getSubField("a") ? $issnParent[0]->getSubField("a"):$issnParent[0]->getSubField("y");
        if ($issnSubField) {
          $sfxData->issn = $issnSubField->getData();
          $sfxData->title = $this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection());
        }
      }
      ?>
      <table class="table table-striped">
        <caption class="sr-only"><?=$this->transEsc('Bibliographic Details')?></caption>
        <?php foreach ($coreFields as $current): ?>
          <?php
          if ($current['label'] == 'Format' && (str_contains($current['value'], 'Journal') || str_contains($current['value'], 'Serial'))) {
            $sfxData->isValid = true;
          }
          ?>
          <tr><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
        <?php endforeach; ?>
        <?php
          if ($sfxData->isValid && $sfxData->issn && $sfxData->title) {
        ?>
          <tr id="sfxRow"><th><?=$this->transEsc("Available Online")?>:</th><td><a class="hidden" href="http://proxy.library.tamu.edu/login?url=http://linkresolver.tamu.edu/tamu?sid=Endeavor:CitationServer&amp;rft.jtitle=<?=$sfxData->title?>&amp;issn=<?=$sfxData->issn?>" style=""><img alt="Full Text @ TAMU" src="<?php echo $this->imageLink("sfx.gif");?>" id="SFXButton"></a></td></tr>
        <?php
          }
        ?>
    </table>
    <?php endif; ?>
    <?php /* End Main Details */ ?>
  </div>
</div>
