<h1>RelBib A-Z</h1>
<ul>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#alerting">Alerting</a></li>
    <li><a href="<?=$this->url('search-results')?>?filter[]=~format%3ASubscription+Bundle&filter[]=~language%3AGerman&type=AllFields">Alertpakete</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'autocomplete']) ?>">Autocomplete / Automatische Textergänzung</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'beacon']) ?>">BEACON</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#alerting">Benachrichtigung über neue Inhalte (=Alerting)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#pda">Benutzergesteuerte Erwerbung (=PDA)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'browse']) ?>">Browsen / Browsing</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'ddc']) ?>" target="_blank">Dewey Decimal Classification (DDC)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'delivery']) ?>" target="_blank">Dokumentlieferung</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#print">Drucken</a></li>
    <!--<li>Erschließungskonzept</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'acquisition_profile']) ?>">Erwerbungsprofil</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#export">Exportieren</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'search']) ?>">Facetten / Filter</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#save_favorites">Favoriten exportieren, speichern, weiterleiten</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#feedback">Feedback</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'interlibrary_loan']) ?>">Fernleihe</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">Forschungsdatenmanagement (FDM)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#availability">HBZ Gateway</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'contents']) ?>">Inhalt in RelBib</a></li>
    <!--<li>Internformat</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperations_institutions']) ?>">Kooperationen</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperative_cataloguing']) ?>">Kooperative Erschließung -&gt; ZoteroGroup</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">Login -&gt; RelBib Konto</a></li>
    <!--<li>Medienart</li>-->
    <!--<li>Medientyp</li>-->
    <li><a href="<?=$this->url('search-newitem') ?>">Neuzugänge</a></li>
    <!--<li>Normdaten</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#pda">Nutzergesteuerte Erwerbung</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'ojs']) ?>">Open Journals (OJS)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#pda">PDA (Nutzergesteuerte Erwerbung)</a></li>
    <li><a href="/relbib_docs/DDC.pdf" target="_blank">RelBib-Klassifikation</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">RelBib-Konto</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#rss">RSS feed</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'keywords']) ?>">Schlagwort</a></li>
    <!--<li>Schlagwortfolge</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'languages']) ?>">Sprache</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#subito">Subito</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'search']) ?>">Suchen</a></li>
    <li><a href="/relbib_docs/TAD.pdf" target="_blank">TAD</a> (nur für Wissenschaftler*innen der Universität Tübingen).</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'about_relbib']) ?>">Über RelBib</a></li>
    <!--<li>Verfasser -&gt; Facetten: Verfasser</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#availability">Verfügbarkeitsanzeige</a></li>
    <!--<li>Verlag</li>-->
    <li><a href="<?=$this->url('content-page', ['page' => 'search']) ?>#fulltext">Volltextsuche</a></li>
    <li><a target="_blank" href="//vufind.org">VuFind</a></li>
    <li><a href="/relbib_docs/relbib_journals_de.pdf" target="_blank">Zeitschriften</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#citation">Zitieren</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperative_cataloguing']) ?>">Zotero-Group</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">Zweitveröffentlichung</a></li>
</ul>
