<h1 id="anchor">Alerting</h1>
<p>The alerting function lets you know when new articles from certain journals and new volumes from certain series are available. You may decide in which cases you would like to get a corresponding message.</p>
<ul>
    <li>In order to receive alerts for a journal or a series, you first have to select the entry for the journal or series as a whole.</li>
    <li>You then click on the “Bell” symbol (icon) which you will find on the right side of the corresponding entry. By now you have to sign in or create a user account.</li>
    <li>You can manage the list of publications marked for an alert in your account under the heading “My alerts”.</li>
</ul>