<h1 id="anchor">Browsen</h1>
<p>Neben einfacher und erweiterter Suche stellt RelBib drei verschiedene Arten des Browsens zur Verfügung: Damit können Sie die Bibliographie nach
   RelBib-spezifischen Schlagwortfolgen („Thema Browsen“), bestimmten Kategorien („Browsen / nach Kategorien“) oder alphabetisch („Alphabetisch Browsen“)
   durchblättern. </p>
<h2>Thema Browsen</h2>
<p>Beim <a href="<?=$this->url('keywordchainsearch-home')?>" target="_blank"><?=$this->transEsc('Browse Keywordchains')?></a>
   können Sie sich durch Eingabe eines oder mehrerer Suchbegriffe Schlagwörter und normierte Schlagwortfolgen anzeigen
   lassen, die gegebenen Suchbegriffen „ähnlich“ sind. Dies eignet sich insbesondere, um Hinweise auf thematisch verwandte Schlagwortketten
   und dazugehörige Titel zu bekommen. Aus der Volltitelanzeige gelangen Sie über den Button
   <span class="iconlabel label label-info">B</span> ebenfalls in den Modus „Thema Browsen“: Auf diese Weise werden Sie zu weiteren Titeln mit
   derselben oder einer ähnlichen Schlagwortfolge in der Datenbank geführt.</p>
<h2>Browsen / nach Kategorien</h2>
<p>Das <a href="<?=$this->url('browse-home')?>" target="_blank"><?=$this->transEsc('Browse by Category')?></a> bietet Ihnen die Möglichkeit,
   ausgehend von Oberkategorien nach bestimmten Aspekten zu einer Ergebnismenge zu kommen,
   ohne dass im Vorfeld Suchbegriffe bekannt sein müssen. Sie wählen Ihren Einstieg aus einem der folgenden Felder aus: DDC,
   RelBib-Klassifikation, Thema (Schlagwort), Verfasser oder Verlag. Über eine Baumstruktur mit vier Ebenen haben Sie die Möglichkeit,
   Ihr Suchergebnis durch Auswahl weiterer Unterfelder einzuschränken.</p>
<h2>Alphabetisch Browsen</h2>
<p>Im Modus <a href="<?=$this->url('alphabrowse-home')?>" target="_blank"><?=$this->transEsc('Browse Alphabetically')?></a> steht eine umfassende,
   alphabetisch sortierte Liste der Inhalte der jeweiligen Kategorien zur Verfügung. Dies
   ist zu z.B. für eine Überblicksrecherche von Vorteil. So wählen Sie einen der Aspekte Thema, Verfasser, Titel oder DDC aus und können
   nach Eingabe eines Wortes oder Wortanfangs bestimmen, an welcher Stelle des Alphabets Sie in das Browsen einsteigen wollen.
   Das alphabetische Browsen kann auch dann hilfreich sein, wenn Sie sich bei der Schreibweise eines Autorennamen oder Begriffs nicht
   sicher sind: Hier reicht die Eingabe eines Wortanfangs aus.</p>