<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'cooperations_cataloguing']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Cooperative cataloguing</h4>
                <!--<p>Untertitel</p>-->
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'cooperations_institutions']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Cooperations with institutions</h4>
                <!--<p>Untertitel</p>-->
            </div>
        </a>
    </div>
</div>
