<h1 id="anchor">Document delivery</h1>
<p>After checking the availability of a title that is not freely accessible, you have the option of either using the fee-based document delivery service
<ul>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#subito">Subito</a>, which sends the title directly to your workplace, or you can start a </li>
    <li><a href="<?=$this->url('content-page', ['page' => 'interlibrary_loan']) ?>">Interlibrary loan</a> request via a participating library.</li>
</ul>
</p>
