<h1 id="anchor">Features</h1>
<p> Ein besonderes Feature von RelBib stellt die Verfügbarkeitsanzeige dar: Damit lässt sich schnell prüfen, ob und an welchem
    Standort eine Zeitschrift, ein Aufsatz oder ein Buch vorhanden ist. Wenn es lizenzrechtlich möglich ist, kann direkt auf
    elektronisch vorliegende Volltexte zugegriffen werden.</p>
<p> RelBib wird als kostenloses Open-Access-Angebot an die weltweite Fachcommunity der Religionswissenschaft von der
    <a href="http://www.uni-tuebingen.de/nc/einrichtungen/universitaetsbibliothek/home.html" target="_blank">Universitätsbibliothek Tübingen</a>
    herausgegeben und entsteht in Zusammenarbeit mit <a href="https://ixtheo.de" target="_blank">IxTheo</a>. Die Betreuung der Datenbank erfolgt
    im Rahmen des Fachinformationsdienstes (FID) „Religionswissenschaft“.</p>
<p> Wir bitten um Verständnis, dass in einer Alpha-Version noch nicht alles fehlerfrei funktioniert. Und jetzt wünschen wir Ihnen viel Freude
    beim Entdecken von RelBib und sind dankbar für Ihr Feedback!</p>

<h1 id="anchor">Weitere Features</h1>
<h2>Patron-Driven-Acquisition (PDA)</h2>
<p>Zur überregionalen Versorgung des Spitzenbedarfs an religionswissenschaftlicher Fachliteratur in Deutschland bietet RelBib ein
   <a href="/relbib_docs/relbib-pda.pdf" target="_blank">benutzergesteuertes Erwerbungsprogramm (PDA</a>) an.</p>
<p>Benötigte Bücher werden bei Bedarf von der UB Tübingen gekauft.</p>
<p>Sie können den Kauf von Einzelmonographien, die weder an Ihrem Standort vorhanden noch über Fernleihe beschaffbar sind, direkt in RelBib veranlassen.</p>
<h2>Verfügbarkeitsanzeige</h2>
<p>Ein besonderes Highlight für die Nutzer_innen von RelBib stellt die Verfügbarkeitsanzeige dar. Hier ist zu unterscheiden zwischen HBZ Gateway und
   Journals Online & Print (JOP).</p>

<p>Über den Link „HBZ Gateway“ in der Volltitelanzeige können Sie hauptsächlich die Verfügbarkeit von Monografien in teilnehmenden Bibliotheken prüfen.</p>
<p>JOP bietet einen entsprechenden Service für Zeitschriften und Aufsätze: Hier geben zusätzlich Icons in der Volltitelanzeige mit Hilfe der Ampelfarben
   auf einen Blick Auskunft über die Verfügbarkeit eines Aufsatzes / einer Zeitschrift im Print- und Online-Bestand der lokalen Bibliothek.</p>
<p>In beiden Fällen wird automatisch die Verfügbarkeit des gesuchten Titels an Ihrem jeweiligen Bibliotheksstandort angezeigt. Über HBZ Gateway besteht
   zudem die Möglichkeit, manuell andere Standorte einzustellen.</p>
<h2>Subito</h2>
<p>Ist ein Titel nicht vor Ort verfügbar oder online kostenfrei zugänglich, können Sie eine kostenpflichtige Bestellung bei Subito veranlassen.
   Über den entsprechenden Link in der Volltitelanzeige gelangen Sie auf die Website des Bestelldienstes.</p>
<h2>RSS-Feed abonnieren</h2>
<p>Sie haben die Möglichkeit, eine Suchanfrage als RSS-Feed zu abonnieren. Dadurch können Sie sich schnell über neu in RelBib aufgenommene
  Titel mit den von Ihnen eingegebenen Suchkriterien informieren. Klicken Sie in der Leiste „Suchwerkzeuge“ unterhalb der Trefferliste auf den
  entsprechenden Link, um das Abonnement einzurichten.</p>
<h2>Zitieren</h2>
<p>In der Volltitelanzeige können Sie sich über den Link „Zitieren“ den gewählten Titel derzeit in drei verschiedenen Zitierstilen
   anzeigen lassen: APA, Chicago und MLA. Mit „copy & paste“ gelangt das passende Zitat direkt in ihre wissenschaftliche Arbeit.</p>
<p>Wir arbeiten momentan noch an der Verbesserung und Erweiterung der Zitierfunktion.</p>
<h2>Exportieren</h2>
<p>Einzelne Treffer und Trefferlisten können Sie für die Verwendung in Literaturverwaltungsprogrammen exportieren: Von RelBib unterstützt werden
   derzeit die Formate EndNote, BibTex und RIS.</p>
<h2>Drucken</h2>
<p>Ihre Trefferliste können Sie direkt aus RelBib heraus ausdrucken: Nach Auswahl der zu druckenden Titel klicken Sie auf „Drucken“ in der Leiste
   oberhalb der Trefferliste und es öffnet sich das Drucker-Dialogfenster. Auch hier lohnt es sich gegebenenfalls, die angezeigte
   Trefferzahl pro Seite im Auswahlmenü zu erhöhen.</p>
<h2>Feedback</h2>
<p>Zu guter Letzt wollen wir Ihnen noch eine sehr wichtige Funktion von RelBib vorstellen: den Feedback-Button am rechten unteren Rand.
   Sie haben die Möglichkeit, von jedem Punkt Ihrer Recheche aus uns eine Feedback-E-Mail zu schicken, die die URL der aktuellen Seite enthält.
   Im Kommentarfeld können Sie zusätzlich kurz das aufgetretene Problem schildern. Dies erleichtert uns die Fehleranalyse, da wir die
   betreffende Suchanfrage sofort rekapitulieren können.</p>
</div>
