<h1>RelBib A-Z</h1>
<ul>
    <li><a href="<?=$this->url('content-page', ['page' => 'about_relbib']) ?>">About RelBib</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'acquisition_profile']) ?>">Acquisition profile</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#alerting">Alerting</a></li>
    <li>Author -&gt; Facets/Filter</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'autocomplete']) ?>">Autocomplete / Automatische Textergänzung</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#availability">Availability check</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'beacon']) ?>">BEACON</a></li>
    <li>Browsen / Browsing</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#citation">Citation</a></li>
    <li>Content in RelBib</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperations_institutions']) ?>">Cooperations</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperative_cataloguing']) ?>Cooperative cataloging using ZoteroGroup</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'ddc']) ?>" target="_blank">Dewey Decimal Classification (DDC)</a></li>
    <li>Document delivery</li>
    <li>Electronic full texts</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#export">Exporting records (Endnote, RIS, Bibtex.)</a></li>
    <li>Facets / Filter</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#save_favorites">Favourites -&gt; Exporting records</a></li>
    <li>Format</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#availability">HBZ Gateway</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'interlibrary_loan']) ?>">Inter library loan</a></li>
    <li>Key words</li>
    <li>Key word string</li>
    <li>Language</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">Login -&gt; RelBib account</a></li>
    <li>Media type</li>
    <li>New items</li>
    <li><a href="/?subpage=open_access_services">Open Access</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'ojs']) ?>">Open Journals (OJS)</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>?expand#pda">PDA - patron driven acquisition</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#print">Printing</a></li>
    <li>Publisher</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">RelBib account</a></li>
    <li><a href="/relbib_docs/DDC.pdf" target="_blank">RelBib-classification</a></li>
    <li><a href="/relbib_docs/relbib_journals.pdf" target="_blank">RelBib periodicals</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">Research data management</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">Self-archiving service</a></li>
    <li>Searching</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#rss">Standing order by RSS</a></li>
    <li>Staff's view</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#subito">Subito</a></li>
    <li><a href="/relbib_docs/TAD.pdf" target="_blank">TAD</a> Document delivery for researchers of Tübingen University.</li>
    <li><a target="_blank" href="//vufind.org">VuFind</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'cooperative_cataloguing']) ?>">Zotero-Groups: Instructions for cooperative cataloging</a></li>
</ul>
