<h1>RelBib A-Z</h1>
<ul>
    <li><a href="<?=$this->url('content-page', ['page' => 'alerting']) ?>">Alerting</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'autocomplete']) ?>">Autocomplete / Automatische Textergänzung</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'beacon']) ?>">BEACON</a></li>
    <li><a href="/relbib_docs/relbib-pda.pdf" target="_blank">Benutzergesteuerte Erwerbung (=PDA)</a></li>
    <li>Browsen / Browsing</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'ddc']) ?>" target="_blank">Dewey Decimal Classification (DDC)</a></li>
    <li>Dokumentlieferung</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'print']) ?>">Drucken</a></li>
    <li>Erschließungskonzept</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'acquisition_profile']) ?>">Erwerbungsprofil</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'export']) ?>">Exportieren</a></li>
    <li>Facetten / Filter</li>
    <li><a href="<?=$this->url('content-page', ['page' => 'favorites']) ?>">Favoriten exportieren, speichern, weiterleiten</a></li>
    <li>Fernleihe</li>
    <li>Forschungsdatenmanagement (FDM)</li>
    <li>HBZ Gateway</li>
    <li>Inhalt in RelBib</li>
    <li>Internformat</li>
    <li>Kooperationen</li>
    <li><a href="/docs/ZoteroGroup_Instruction_de.pdf" target="_blank">Kooperative Erschließung -&gt; ZoteroGroup</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">Login -&gt; RelBib Konto</a></li>
    <li>Medienart</li>
    <li>Medientyp</li>
    <li>Neuerscheinungen abonnieren (=Alerting)</li>
    <li>Neuzugänge</li>
    <li>Normdaten</li>
    <li><a href="/relbib_docs/relbib-pda.pdf" target="_blank">Nutzergesteuerte Erwerbung</a></li>
    <li>Open Access</li>
    <li>Open Journals (OJS)</li>
    <li><a href="/relbib_docs/relbib-pda.pdf" target="_blank">PDA (Nutzergesteuerte Erwerbung)</a></li>
    <li><a href="/relbib_docs/DDC.pdf" target="_blank">RelBib-Klassifikation</a></li>
    <li><a href="<?=$this->url('content-page', ['page' => 'my_relbib']) ?>">RelBib-Konto</a></li>
    <li>RSS feed</li>
    <li>Schlagwort</li>
    <li>Schlagwortfolge</li>
    <li>Sprache</li>
    <li>Subito</li>
    <li>Suchen</li>
    <li><a href="/relbib_docs/TAD.pdf" target="_blank">TAD</a> (nur für Wissenschaftler*innen der Universität Tübingen).</li>
    <li>Über RelBib</li>
    <li>Verfasser -&gt; Facetten: Verfasser</li>
    <li>Verfügbarkeitsanzeige</li>
    <li>Verlag</li>
    <li>Volltexte</li>
    <li>VuFind</li>
    <li><a href="/relbib_docs/relbib_journals.pdf" target="_blank">Zeitschriften</a></li>
    <li>Zitieren</li>
    <li><a href="/docs/ZoteroGroup_Instruction_de.pdf" target="_blank">Zotero-Group</a></li>
    <li><a href="/docs/Zweitveroeffentlichung_FAQ.pdf" target="_blank">Zweitveröffentlichung</a></li>
</ul>
