<h1 id="anchor">Features</h1>
 <p>One particular feature of RelBib is the availability display: with that, you can quickly find out whether and where an article,
    periodical or book is available. Links to online texts can be accessed directly if the publishers’ licenses allow it.</p>
 <p>RelBib constitutes a free and open access service to the worldwide scholarly community of Religious Studies. The editor of RelBib is the
    <a href="http://www.uni-tuebingen.de/nc/einrichtungen/universitaetsbibliothek/home.html" target="_blank">Universitätsbibliothek Tübingen</a>
    (central library of the University of Tübingen). RelBib is being produced in close cooperation with
    <a href="https://ixtheo.de" target="_blank">IxTheo</a> by the Fachinformationsdienst “Religionswissenschaft”
    (Specialized Information Service of Religious Studies).</p>
 <p>We apologize in advance for any errors which might come up at this early stage of development. We wish you an enjoyable experience as
    you explore RelBib and we would be glad to get your feedback!</p>

<h1 id="anchor">More Features</h1>
<h2>Patron-Driven-Acquisition (PDA)</h2>
<p>We are now offering a <a href="/relbib_docs/relbib-pda.pdf" target="_blank"> Patron Driven Acquisition (PDA)</a>
   system which enables us to respond to special demands for Religious Studies’ literature in
   Germany. When necessary, the required books are purchased by the University Library in Tübingen. At the RelBib website, users may directly
   trigger the purchase of monographs which are not available at their current location and cannot be obtained through an inter-library loan.</p>
<p>
<h2>Availability checking</h2>
<p>A special highlight for users of RelBib is the checking of availablity of a title found during a search.</p>
<p>The link “HBZ Gateway” gets you to the checking of the availability of books in connection with your university.</p>
<p>The display "Journals Online & Print" (JOP) offers the same service for articles and periodicals. The JOP icons show you at one glance whether a periodical is available in your own university.</p>
<h2>Subito</h2>
<p>Instead of the inter-library loan you can order a title to be delivered directly to you via SUBITO, a service liable to costs. The link on your search
   result display gets you to the website of this delivery service.</p>
<h2>Standing order by RSS feed</h2>
<p>You can book your search string which you would like to be repeated at certain intervals by RSS feed. Thus, you will get a notice whenever something
   new has been added to RelBib. Please click on "Search Tools: Get RSS Feed" below the list of your search results to establish this service.</p>
<h2>Citation</h2>
<p>Under the link “Citation“  you can see your chosen title in three different citation styles (APA, MLA and Chicago). Please note that we are still working
   on this: we plan to add more citation styles eventually.</p>
<h2>Exporting your search results</h2>
<p>You can export single search results as well as lists of search results into EndNote, BibTex and RIS.</p>
<h2>Printing your search results</h2>
<p>You can print the list of your search results directly from RelBib. For this you choose the titles you would like to have on the list, then click
   “Print” above the research results. If necessary, you can adjust  the number of results per page.</p>
<h2>Feedback</h2>
<p>Finally, we would like to present a very important feature of RelBib to you: it is the "Feedback" button on the lower right corner.
   You can send a feedback email from each point of your search, which then includes the URL of the present page. It is possible to
   leave a comment describing the current problem. This will enable us to analyse it more easily.</p>
