<h1 id="anchor">Personalisierte Features</h1>
<p>Die folgenden Features können Sie nach einem Login in Ihr RelBib Konto nutzen:</p>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#alerting">
        <div class="tf-panel-collapse-heading">
            Benachrichtigungen über neue Inhalte
        </div>
    </a>
    <div id="alerting" class="collapse tf-panel-collapse-body">
        <p>In RelBib gibt es zwei Möglichkeiten sich über neu in der Bibliografie aufgenommene Zeitschriftenaufsätze oder Bände von Reihen per E-Mail benachrichtigen zu lassen.</p>
        <p><b>Alerting für einzelne Zeitschriften oder Reihen</b></p>
        <p>Um diese Alerting-Funktion auszulösen, müssen Sie zunächst den Titel der gewünschten Zeitschrift oder Reihe aufrufen. Klicken Sie dann auf das Glocke-Symbol <i class="result-link-icon fa fa-fw fa-bell"></i> in der Trefferliste oder benutzen Sie den „Abonnieren“-Button in der oberen Zeile der Titelanzeige. In Ihrem Konto können Sie die Alerts verwalten.</p>
        <p><b>Alertpakete für Zeitschriften</b></p>
        <p>Wenn Sie zu einem bestimmten Themenbereich laufend auf dem neuesten Stand bleiben wollen, empfiehlt es sich ein Alertpaket zu wählen. In den Alertpaketen haben wir bereits im Vorfeld Zeitschriften, die einem Thema bzw. einer Kategorie angehören, gruppiert. Sie erhalten immer dann eine E-Mail-Benachrichtigung, wenn Aufsätze aus mindestens einer der im gewählten Alertpaket enthaltenen Zeitschriften neu in RelBib aufgenommen wurden.</p>
        <p><a href="<?=$this->url('search-results')?>?type=AllFields&filter[]=~format%3A%22Subscription+Bundle%22&filter[]=~language%3AGerman">Übersicht der verfügbaren Alertpakete</a></p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#save_send">
        <div class="tf-panel-collapse-heading">
            Suchanfragen speichern oder als E-Mail versenden
        </div>
    </a>
    <div id="save_send" class="collapse tf-panel-collapse-body">
        <p>Ihre aktuellen Suchanfragen werden in der Suchhistorie temporär gespeichert. Wenn Sie Ihre Suchanfragen dauerhaft verwenden wollen, können Sie sie in Ihrem Konto abspeichern. Diese haben Sie dann unter „Gespeicherte Suche“ in Ihrem Konto jederzeit zur Hand und können sie durch Anklicken erneut ausführen. Das lohnt sich für komplexe Abfragen oder für Themen, an denen Sie kontinuierlich interessiert sind. Auf diese Weise entdecken Sie leicht die neu erschienene Literatur zu einem bestimmten Thema oder Themengebiet. Ebenso lässt sich eine Suchanfrage von Ihrem Konto aus an eine andere Person per E-Mail verschicken.</p>
        <p>Die entsprechenden Funktionen bzw. Suchwerkzeuge wählen Sie unterhalb der Trefferliste aus.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#email">
        <div class="tf-panel-collapse-heading">
            Trefferliste als E-Mail versenden
        </div>
    </a>
    <div id="email" class="collapse tf-panel-collapse-body">
        <p>Auch Trefferlisten oder einzelne Treffer können per E-Mail an eine andere Person verschickt werden. In der Trefferliste wählen Sie dafür zunächst die gewünschten Treffer einzeln aus oder klicken oberhalb der Liste „Alles auswählen“. Danach können Sie Ihre Auswahl über den Button „E-Mail“ unter Eingabe der Zieladresse versenden.</p>
        <p>Bitte beachten: Sie können nur die auf einer Seite angezeigten Treffer gleichzeitig versenden. Standardmäßig ist die angezeigte Trefferzahl pro Seite auf 20 eingestellt. Diese lässt sich im Auswahlmenü oberhalb der Liste auf bis zu 100 angezeigte Treffer pro Seite erhöhen.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#save_favorites">
        <div class="tf-panel-collapse-heading">
            Favoriten speichern
        </div>
    </a>
    <div id="save_favorites" class="collapse tf-panel-collapse-body">
        <p>Speichern Sie interessante Titel direkt in Ihrem Konto ab. Klicken Sie dafür auf das Stern-Symbol <i class="result-link-icon fa fa-fw fa-star" aria-hidden="true"></i> in der Trefferliste oder Volltitelanzeige. Damit stehen diese Ihnen dauerhaft zur Verfügung und Sie verlieren keine Zeit mit dem Wiederfinden. Ihre Favoriten können Sie in verschiedenen Listen speichern, die Sie selbst definieren. Auf diese Weise lassen sich interessante Titel beispielsweise bestimmten Forschungsprojekten oder Themen zuordnen. Diese Listen können Sie aus Ihrem Konto heraus auch exportieren, per Mail verschicken oder ausdrucken.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#share_favorites">
        <div class="tf-panel-collapse-heading">
            Favoritenlisten mit anderen Personen teilen
        </div>
    </a>
    <div id="share_favorites" class="collapse tf-panel-collapse-body">
        <p>Indem Sie den Status einer Titelliste in Ihrem eigenen Konto auf „öffentlich“ setzen, können Sie auch Ihren Kolleg*innen den Zugriff auf diese Liste ermöglichen. Dazu kopieren Sie einfach den URL auf die gewünschte Liste aus Ihrem Browserschlitz und versenden diesen per E-Mail.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#pda">
        <div class="tf-panel-collapse-heading">
            Patron-Driven-Acquisition (PDA)
        </div>
    </a>
    <div id="pda" class="collapse tf-panel-collapse-body">
        <p>Zur überregionalen Versorgung des Spitzenbedarfs an religionswissenschaftlicher Fachliteratur in Deutschland bietet RelBib ein <a href="/relbib_docs/relbib-pda.pdf">benutzergesteuertes Erwerbungsprogramm (PDA)</a> an.</p>
        <p>Benötigte Bücher werden, falls sie nirgends in Deutschland ausleihbar vorhanden sind, bei Bedarf von der UB Tübingen gekauft.</p>
        <p>Sie können den Kauf von Einzelmonographien, die weder an Ihrem Standort vorhanden noch über Fernleihe beschaffbar sind, direkt in RelBib veranlassen.</p>
    </div>
</div>
