<div class="row">
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'features_common']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Features without login</h4>
                <!--<p>Einzelheiten zu KrimDok</p>-->
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'features_personalised']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Features with login</h4>
                <!--<p>Über den FID</p>-->
            </div>
        </a>
    </div>
</div>
