<h1 id="anchor">Features without a personal account</h1>
<p>Without a personal login you can see / use the following features in RelBib:</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#availability">
        <div class="tf-panel-collapse-heading">
            Availability checking
        </div>
    </a>
    <div id="availability" class="collapse tf-panel-collapse-body">
        <p>A special highlight for users of RelBib is the checking of availablity of a title found during a search.</p>
        <p>The link <b>HBZ Gateway</b> gets you to the checking of the availability of books in connection with your university.</p>
        <p>The display <b>Journals Online &amp; Print</b> (JOP) offers the same service for articles and periodicals. The JOP icons show you at one glance whether a periodical is available in your own university.</p>
        <p>In beiden Fällen wird automatisch die Verfügbarkeit des gesuchten Titels an Ihrem jeweiligen Bibliotheksstandort angezeigt. Über HBZ Gateway besteht zudem die Möglichkeit, manuell andere Standorte einzustellen.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#subito">
        <div class="tf-panel-collapse-heading">
            Subito
        </div>
    </a>
    <div id="subito" class="collapse tf-panel-collapse-body">
        <p>Instead of the inter-library loan you can order a title to be delivered directly to you via SUBITO, a service liable to costs. The link on your search result display gets you to the website of this delivery service.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#rss">
        <div class="tf-panel-collapse-heading">
            Standing order by RSS feed
        </div>
    </a>
    <div id="rss" class="collapse tf-panel-collapse-body">
        <p>You can book your search string which you would like to be repeated at certain intervals by RSS feed. Thus, you will get a notice whenever something new has been added to RelBib. Please click on "Search Tools: Get RSS Feed" below the list of your search results to establish this service.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#citation">
        <div class="tf-panel-collapse-heading">
            Citation
        </div>
    </a>
    <div id="citation" class="collapse tf-panel-collapse-body">
        <p>Under the link “Citation“ you can see your chosen title in three different citation styles (APA, MLA and Chicago). Please note that we are still working on this: we plan to add more citation styles eventually.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#export">
        <div class="tf-panel-collapse-heading">
            Exporting your search results
        </div>
    </a>
    <div id="export" class="collapse tf-panel-collapse-body">
        <p>You can export single search results as well as lists of search results into EndNote, BibTex and RIS.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#print">
        <div class="tf-panel-collapse-heading">
            Printing your search results
        </div>
    </a>
    <div id="print" class="collapse tf-panel-collapse-body">
        <p>You can print the list of your search results directly from RelBib. For this you choose the titles you would like to have on the list, then click “Print” above the research results. If necessary, you can adjust the number of results per page.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#feedback">
        <div class="tf-panel-collapse-heading">
            Feedback
        </div>
    </a>
    <div id="feedback" class="collapse tf-panel-collapse-body">
        <p>Finally, we would like to present a very important feature of RelBib to you: it is the "Feedback" button on the lower right corner. You can send a feedback email from each point of your search, which then includes the URL of the present page. It is possible to leave a comment describing the current problem. This will enable us to analyse it more easily.</p>
    </div>
</div>
