<h1 id="anchor">Features without a personal account</h1>
<p>Without a personal login you can see / use the following features in RelBib:</p>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#availability">
        <div class="tf-panel-collapse-heading">
            Availability checking
        </div>
    </a>
    <div id="availability" class="collapse tf-panel-collapse-body">
        <p>A special highlight for users of RelBib is the checking of availablity of a title found during a search.</p>
        <p>Click the link <b>HBZ Gateway</b> in the detailed view in order to find out about whether a book or journal is available at your university library.<br/>
           The link leads you to the website of the gateway where it is possible to choose a library location.<br/>
           If you are using a campus network of a registered library, you will be automatically assigned to this library location. Once you have clicked on the chosen library location the availability of the searched title is displayed.<br/>
           If your (university) library is not selectable it means, that it is not yet registered for the gateway. You can make a request to your library yourself or we will do it for you if you write to us. The process of registration is uncomplicated and free of charge for libraries running a link resolver. A more <a href="https://openurlgw.hbz-nrw.de/about" target="_blank">detailed description</a> can be found on the website of the Hochschulbibliothekszentrums (HBZ) des Landes Nordrhein-Westfalen. This service can be used worldwide.</p>
        <p>The display <b>Journals Online &amp; Print</b> (JOP) offers the same service for articles and periodicals. The JOP icons show you at one glance whether a periodical is available in your own university. This service only applies to libraries in Germany and Austria.</p>
        <p>In both cases, the availability of the title you are looking for is by default displayed at your library location. HBZ Gateway also allows you to manually set other library locations.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#subito">
        <div class="tf-panel-collapse-heading">
            Subito
        </div>
    </a>
    <div id="subito" class="collapse tf-panel-collapse-body">
        <p>Instead of the inter-library loan you can order a title to be delivered directly to you via SUBITO, a service liable to costs. The link on your search result display gets you to the website of this delivery service.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#rss">
        <div class="tf-panel-collapse-heading">
            Standing order by RSS feed
        </div>
    </a>
    <div id="rss" class="collapse tf-panel-collapse-body">
        <p>You can book your search string which you would like to be repeated at certain intervals by RSS feed. Thus, you will get a notice whenever something new has been added to RelBib. Please click on "Search Tools: Get RSS Feed" below the list of your search results to establish this service.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#citation">
        <div class="tf-panel-collapse-heading">
            Citation
        </div>
    </a>
    <div id="citation" class="collapse tf-panel-collapse-body">
        <p>Under the link “Citation“ you can see your chosen title in three different citation styles (APA, MLA and Chicago). Please note that we are still working on this: we plan to add more citation styles eventually.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#export">
        <div class="tf-panel-collapse-heading">
            Exporting your search results
        </div>
    </a>
    <div id="export" class="collapse tf-panel-collapse-body">
        <p>You can export single search results as well as lists of search results into your personal reference management system. RelBib supports data export to EndNote, BibTex and RIS (for Citavi, Zotero etc.).</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#print">
        <div class="tf-panel-collapse-heading">
            Printing your search results
        </div>
    </a>
    <div id="print" class="collapse tf-panel-collapse-body">
        <p>You can print the list of your search results directly from RelBib. For this you choose the titles you would like to have on the list, then click “Print” above the research results. If necessary, you can adjust the number of results per page.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#feedback">
        <div class="tf-panel-collapse-heading">
            Feedback
        </div>
    </a>
    <div id="feedback" class="collapse tf-panel-collapse-body">
        <p>Finally, we would like to present a very important feature of RelBib to you: it is the "Feedback" button on the lower right corner. You can send a feedback email from each point of your search, which then includes the URL of the present page. It is possible to leave a comment describing the current problem. This will enable us to analyse it more easily.</p>
    </div>
</div>
