<h1 id="anchor">Features with login</h1>
<p>Many useful functions are at your disposal when you create a personal account.</p>
<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#alerting">
        <div class="tf-panel-collapse-heading">
            Alerting
        </div>
    </a>
    <div id="alerting" class="collapse tf-panel-collapse-body">
        <p>The alerting function lets you know when new articles from certain journals and new volumes from certain series are available. You may decide in which cases you would like to get a corresponding message.</p>
        <p>In order to receive alerts for a journal or a series, you first have to select the entry for the journal or series as a whole. You then click on the bell symbol <i class="result-link-icon fa fa-fw fa-bell"></i> which you will find on the right side of the corresponding entry. You can manage the list of publications marked for an alert in your account under the heading “New Issue Alerting”.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#save_send">
        <div class="tf-panel-collapse-heading">
            Saving and mailing search requests
        </div>
    </a>
    <div id="save_send" class="collapse tf-panel-collapse-body">
        <p>Your current search requests are temporarily stored in the search history. If you would like to have permanent access to certain search requests, you can save them permanently in your account. You will find them under “Saved Searches” and may use them again through a simple mouse click. This feature might be useful for complex requests or for subjects in which you have a continuing interest. In this way, you will find the latest literature on a given subject or area of knowledge. Likewise, you can send your search request to another person via e-mail.</p>
        <p>Select the corresponding search tool underneath the list of search results.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#email">
        <div class="tf-panel-collapse-heading">
            Sending your search result list per e-mail
        </div>
    </a>
    <div id="email" class="collapse tf-panel-collapse-body">
        <p>You can also send your search result list or single entries to another person per e-mail. Choose individual entries or tick “Select Page” above the list. Click the “E-Mail” button and enter the destination address.</p>
        <p>Please notice: You can only send the entries of a single result page. The results set can be increased using the “Results per page” drop-down menu above the list.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#save_favorites">
        <div class="tf-panel-collapse-heading">
            Saving items
        </div>
    </a>
    <div id="save_favorites" class="collapse tf-panel-collapse-body">
        <p>You can save interesting titles directly in your account. Click on the star symbol <i class="result-link-icon fa fa-fw fa-star" aria-hidden="true"></i> in the result list or in the detailed view. They are then permanently accessible, and you do not have to waste any time searching for them again. You may save selected items in different lists, which you define yourself. In this way, you can assign interesting titles to specific research projects or subjects. In your account, you can also export saved items, send them per e-mail or print them.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#share_favorites">
        <div class="tf-panel-collapse-heading">
            Sharing lists with other people
        </div>
    </a>
    <div id="share_favorites" class="collapse tf-panel-collapse-body">
        <p>If you want to allow your research colleagues access to one of your title lists, you have to select the status “public” when you create a list or change the status accordingly. Then simply copy the URL to the desired list from your browser slot and email it to your colleagues.</p>
    </div>
</div>

<div class="tf-panel-collapse">
    <a data-toggle="collapse" href="#pda">
        <div class="tf-panel-collapse-heading">
            Patron-Driven-Acquisition (PDA)
        </div>
    </a>
    <div id="pda" class="collapse tf-panel-collapse-body">
        <p>We are offering a <a href="/relbib_docs/relbib-pda.pdf">Patron Driven Acquisition (PDA)</a> system which enables us to respond to special demands for Religious Studies’ literature in Germany. When necessary, the required books are purchased by the University Library in Tübingen. At the RelBib website, users may directly trigger the purchase of monographs which are not available at their current location and cannot be obtained through an inter-library loan.</p>
    </div>
</div>
