<h1 id="anchor">Fernleihe</h1>
<p>Mit der Verfügbarkeitsprüfung in RelBib erfahren Sie, ob ein Aufsatz oder ein Buch an der Bibliothek Ihrer Wahl vorhanden ist. Wenn das nicht der Fall ist, können Sie über Ihre Bibliothek eine Fernleihe aufgeben und werden benachrichtigt, sobald der Aufsatz oder das Buch für Sie bereitliegt.</p>
<ul>
    <li>Siehe auch -&gt <a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#subito">Subito</a></li>
    <li>Siehe auch -&gt <a href="<?=$this->url('content-page', ['page' => 'delivery']) ?>">Dokumentenlieferung</a></li>
</ul>
