<h1 id="anchor">Interlibrary loan</h1>
<p>The availability check tells you whether an article or book is present at your library. If this is not the case, you can place an order via interlibrary loan at your local university library. You will then be notified when the article or book has arrived.</p>
<ul>
    <li>See also -&gt <a href="<?=$this->url('content-page', ['page' => 'features_common']) ?>?expand#subito">Subito</a></li>
    <li>See also -&gt <a href="<?=$this->url('content-page', ['page' => 'delivery']) ?>">Document delivery</a></li>
</ul>