<h1 id="anchor">Languages</h1>
<h2>User interface (template)</h2>
<p>The user interface of RelBib currently supports German and English, French will follow shortly (last update June 2019). You can set your preferred search language at the top right. The default language is selected automatically based on your IP address or operating system.</p>

<h2>Help texts</h2>
<p>Likewise the help and information texts for RelBib and for the services of the FID Study of Religion are available in German and English, soon also in French.</p>

<h2>Literature in RelBib</h2>
<p>In RelBib you will find literature relevant to the study of religion in basically all languages - with the restriction that literature in non-Latin scripts is hardly represented due to capacity reasons.</p>

<h2>Subject headings</h2>
<p>A special feature of our database is the fact that the standardized subject headings have been translated into different languages. This means that you can start a subject search by using keywords in English, French, Italian, Spanish, Russian and Chinese and you will always get the same number of references, regardless of the language in which the literature itself is written.</p>
