<h1>RelBib Open Journals</h1>
<p>
    Der Fachinformationsdienst (FID) Religionswissenschaft unterstützt und fördert Open-Access-Zeitschriften. Wir bieten Herausgeber*innen mit der Plattform „RelBib Open Journals“ die Möglichkeit ihre religionswissenschaftlichen Zeitschriften oder Reihen dauerhaft open access zu hosten. Neben der Aufnahme neuer OA-Zeitschriften begleiten wir gerne auch Ihren Wechsel von einer anderen Plattform zu Open Access. Wir stellen Ihnen dafür das Managementsystem Open Journal Systems (OJS) zur Verfügung, mit dem die Verwaltung des gesamten redaktionellen Prozesses bis hin zur Publikation bewerkstelligt werden kann.
</p>
<p>
    Folgende Vorteile bietet der Wechsel zu „RelBib Open Journals“:
    <ul>
        <li>der FID Religionswissenschaft / Universitätsbibliothek Tübingen stellt die Software OJS kostenlos zur Verfügung, richtet Ihre Zeitschrift bzw. Reihe ein, bietet eine Schulung und fortlaufenden Support an</li>
        <li>mit OJS können alle Arbeitsschritte von der Einreichung der Aufsätze, über Peer-Review bis hin zur Publikation mit einem System umgesetzt werden</li>
        <li>Layout und Design einer OJS-Zeitschrift sind individuell anpassbar</li>
        <li>alle Zeitschriftenaufsätze erhalten einen persistent identifier (DOI), der eine dauerhafte Auffindbarkeit garantiert</li>
        <li>alle Zeitschriftenaufsätze werden automatisch in RelBib nachgewiesen</li>
    </ul>
</p>

<p>
    Dieses Angebot steht allen Herausgeber*innen von Zeitschriften und Reihen zur Verfügung. Bei Interesse wenden Sie sich bitte an das <a href="mailto:relbib@ub.uni-tuebingen.de">RelBib-Team</a>.
</p>

