<div class="row">
    <div class="col-xs-12 col-sm-4 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'self_archiving_service']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Self archiving service</h4>
                <!--<p>Einzelheiten zu KrimDok</p>-->
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'ojs']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Publication platform OJS</h4>
                <!--<p>Über den FID</p>-->
            </div>
        </a>
    </div>
    <div class="col-xs-12 col-sm-4 col-md-4 panel panel-top panel-default">
        <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'research_data_management']) ?>">
            <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg') ?>);"></div>
            <div class="panel-content">
                <h4>Research data management</h4>
                <!--<p>Über den FID</p>-->
            </div>
        </a>
    </div>
</div>
