<h1 id="anchor">Search</h1>
<p>You can choose between three different search modes in RelBib: “Simple Search”, “Advanced Search” and „Full Text Search“.</p>

<h2 id="simple">Simple Search</h2>
<p>Enter a term in the search field and leave the search category on “All Fields”. The system will then search for this term in all
   possible search fields. The drop-down menu allows you to narrow the search down to one specific category: title, author, call number (DDC),
   subject or ISBN / ISSN.</p>

<p>You may specify your results by means of the filter settings in the right column of the search result list according to the
   following criteria:</p>
<ul>
    <li>time: year of publication</li>
    <li>medium: open access, mediatype, format</li>
    <li>classification: call number (DDC), RelBib classification</li>
    <li>content: topic, genre, era, region</li>
    <li>form: language, author, publisher</li>
  </ul>
<p>Some of the filters allow multiple selection.</p>

<h2 id="advanced">Advanced Search</h2>
<p>You can start an “Advanced Search” if you click on the link underneath the search field. Compared to “Simple Search”, here it is possible to
   start a search in several fields at the same time and thus to render your search more precisely. The "Match" setting lets you specify how
   multiple search fields should be handled. For certain complex searches it might be more useful to operate with search groups.</p>
<p>In addition to that, in the advanced search mode you can narrow your search down <i>a priori</i> according to the following facets: RelBib classification;
   format; language. Moreover, it is possible beforehand to set a publication period as well as the number of results listed per page.</p>

<h2 id="fulltext">Full Text Search</h2>
<p>The full text search significantly expands and modernises the search strategy in RelBib. It offers the possibility of a direct and precise search for individual words and phrases in a large digital text corpus. Activate the full-text search by clicking on the "Full texts" tab above the RelBib search slot. Alternatively, you can also search the full text of an individual title by selecting the lower tab "Search full text" in the page view of the selected result.</p>
<p>In addition to a free text search, synonyms of a search term and their translations in several languages are also available. The selection is made simply by using the selection menu to the right of the search bar. The search can be limited to individual text types (table of contents, full text, summary) and combined with the RelBib facets.</p>
<p>The full text search is offered for commercial and Open Access content relevant to the study of religion. One of the benefits of the RelBib full text search lies in the fact that – for the first time in an Open Access environment – resources from different publishers, which are subject to subscription, can be searched simultaneously and legally. The publishers Brill and Mohr Siebeck have been won as pilot partners. Please note that the full text search is therefore currently only possible for a limited part of the titles indexed in RelBib.</p>
<p><a href="/relbib_docs/Volltextsuche_RelBib_englisch_aktuell.pdf" target="_blank">Leaflet Full Text Search</a></p>
