<h1 id="anchor">Search</h1>
<p>You can choose between two different search modes in RelBib: “Simple Search” and “Advanced Search”.</p>
<h2>Simple Search</h2>
<p>Enter a term in the search field and leave the search category on “All Fields”. The system will then search for this term in all
   possible search fields. The drop-down menu allows you to narrow the search down to one specific category: title, author, call number (DDC),
   subject or ISBN / ISSN.</p>

<p>You may specify your results by means of the filter settings in the right column of the search result list according to the
   following criteria:</p>
<ul>
    <li>time: year of publication</li>
    <li>medium: open access, mediatype, format</li>
    <li>classification: call number (DDC), RelBib classification</li>
    <li>content: topic, genre, era, region</li>
    <li>form: language, author, publisher</li>
  </ul>
<p>Some of the filters allow multiple selection.</p>
<h2>Advanced Search</h2>
<p>You can start an “Advanced Search” if you click on the link underneath the search field. Compared to “Simple Search”, here it is possible to
   start a search in several fields at the same time and thus to render your search more precisely. The "Match" setting lets you specify how
   multiple search fields should be handled. For certain complex searches it might be more useful to operate with search groups.</p>
<p>In addition to that, in the advanced search mode you can narrow your search down <i>a priori</i> according to the following facets: RelBib classification;
   format; language. Moreover, it is possible beforehand to set a publication period as well as the number of results listed per page.</p>