<h1>Self-archiving service</h1>
<p>
    Section 38 of the German Copyright Act (UrhG) grants authors special rights for the secondary publication of their articles and reviews in open access.
</p>
<p>
    The FID Religionswissenschaft offers scholars a self-archiving service in order to increase online accessibility to literature of the study of religion. Our service includes the cataloguing, reviewing of the copyright and related rights, digitising and long-term archiving of secondary publications in the subject-based repository for the study of religion at Tübingen University Library. As a special benefit of this service, all self-archived titles are then searchable and accessible in <a href="https://relbib.de/">RelBib</a>.
</p>
<p>
    Our service is run in close contact with the authors:
    <ol>
        <li>Interested scholars submit their current and complete list of publications to us (no PDF file, please). All titles from this list are recorded in RelBib, if not already done. As a result, your <u>entire bibliography</u> is indexed in RelBib.</li>
        <li>
            We verify which titles of your publication list may be republished. <u>Section 38 of the German Copyright Act</u> lays down clear rules according to which you are allowed to self-archive and provide open access for:
            <ol type="a">
                <li>articles and reviews from journals, even <u>if you have received a fee</u></li>
                <li>essays, reviews, contributions and encyclopaedic articles from collective works (e.g. anthologies, commemorative publications, congress papers, encyclopaedias, handbooks...) <u>if you have not received a fee</u></li>
            </ol>
            <p>
                In both cases a so-called <u>embargo period of one year</u> applies. This essentially means that a title may only be reublished one year after its primary publication.
            </p>
            <p>
                <b><u>Monographs, i.e. entire books that you have written, may not be self-archived per se.</u></b> This does not affect individual agreements with the first publishers (e.g. in the case of out-of-print dissertations).
            </p>
            <p>
                See also the list of FAQs on the subject of self-archiving: <a href="/docs/Zweitveroeffentlichung_FAQ.pdf" target="_blank">https://relbib.de/docs/Zweitveroeffentlichung_FAQ.pdf</a>
            </p>
            <p>
                In the case of titles published by a foreign publisher, we will review the individual national copyright laws as well as publishers‘ policies.
            </p>
        </li>
        <li>A contract regulates the transfer of non-exclusive rights to the Tübingen University Library so that the articles and reviews can be provided open access in the subject-based repository for the study of religion.</li>
        <li>Already available digital copies will be placed directly in the repository. The remaining print contributions will be digitised at the expense of the FID at Tübingen University Library.</li>
        <li>All publications which have been eligible for secondary publication will be archived in the subject-based repository and connected to RelBib. Users of RelBib will then have direct access to the full text worldwide. If not yet available, we add standardised subject headings to each title, which reflect its content in a short and precise form. These subject headings allow a thematic search for your publications.</li>
    </ol>
</p>

<h2>Contact</h2>
<p>
    Mareike Heinritz, M. A.<br/>
    Staff member of the FID Religionswissenschaft/<br/>
    Bibliography of the Study of Religion (RelBib)<br/>
    Tübingen University Library
</p>
<p>
    Tel: +49 / (0)7071 / 29-74030<br/>
    E-Mail: <a href="mailto:m.heinritz@uni-tuebingen.de">m.heinritz@uni-tuebingen.de</a>
</p>
