<?
    // Set up page title:
    $this->headTitle($this->translate('My Fines'));
?>
<div data-role="page" id="MyResearch-checkedout">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <h3><?=$this->transEsc('Your Fines')?></h3>

    <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', array('user' => $this->auth()->isLoggedIn())); ?>

    <? if (empty($this->fines)): ?>
      <p><?=$this->transEsc('You do not have any fines')?></p>
    <? else: ?>
      <ul class="results fines" data-role="listview">
        <? foreach ($this->fines as $record): ?>
          <li>
            <? if ($showLink = (!empty($record['title']) && is_object($record['driver']))): ?>
              <a rel="external" href="<?=$this->recordLink()->getUrl($record['driver'])?>">
            <? endif; ?>
            <div class="result">
              <h3>
                <? if (empty($record['title'])): ?>
                  <?=$this->transEsc('not_applicable')?>
                <? else: ?>
                  <?=$this->escapeHtml(trim($record['title'], '/:'))?>
                <? endif; ?>
              </h3>
              <span class="ui-li-aside"><?=isset($record['balance']) ? $this->safeMoneyFormat($record['balance']/100.00) : ''?></span>
              <p><strong><?=$this->transEsc('Due Date')?></strong>: <?=isset($record['duedate']) ? $this->escapeHtml($record['duedate']) : ''?></p>
              <p><strong><?=$this->transEsc('Checked Out')?></strong>: <?=isset($record['checkout']) ? $this->escapeHtml($record['checkout']) : ''?></p>
              <p><strong><?=$this->transEsc('Fine')?></strong>: <?=isset($record['fine']) ? $this->escapeHtml($record['fine']) : ''?></p>
              <p><strong><?=$this->transEsc('Fee')?></strong>: <?=isset($record['amount']) ? $this->safeMoneyFormat($record['amount']/100.00) : ''?></p>
            </div>
            <? if ($showLink): ?>
              </a>
            <? endif; ?>
          </li>
        <? endforeach; ?>
      </ul>
    <? endif; ?>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
