<?
    // Grab list object from search results (if applicable):
    $list = $this->results->getListObject();

    // Set up page title:
    $this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));

    // Set up extra button for header:
    $extraButton = isset($list)
        ? '<a rel="external" href="'
            . $this->url('editList', array('id' => $list->id))
            . '" data-icon="gear" class="ui-btn-left">'
            . $this->transEsc("edit_list")
            . '</a>'
        : '';
?>

<div data-role="page" id="MyResearch-list">
  <?=$this->mobileMenu()->header(array('extraButtons'=>array($extraButton)))?>
  <div data-role="content">
    <? foreach ($this->results->getRecommendations('side') as $current): ?>
      <?=$this->recommend($current)?>
    <? endforeach; ?>

    <? if (isset($list)): ?>
      <h3><?=$this->escapeHtml($list->title)?></h3>
      <? if (!empty($list->description)): ?><p><?=$this->escapeHtml($list->description)?></p><? endif; ?>
    <? else: ?>
      <h3><?=$this->transEsc("Your Favorites")?></h3>
    <? endif; ?>

    <?=$this->flashmessages();?>

    <? if (($recordTotal = $this->results->getResultTotal()) > 0): ?>
      <p>
        <strong><?=$this->escapeHtml($this->results->getStartRecord())?></strong> - <strong><?=$this->escapeHtml($this->results->getEndRecord())?></strong>
        <?=$this->transEsc('of')?> <strong><?=$this->escapeHtml($recordTotal)?></strong>
      </p>

      <ul class="results mylist" data-role="listview" data-split-icon="minus" data-split-theme="d" data-inset="false">
        <? $i = 0; foreach ($this->results->getResults() as $current): ?>
          <li>
            <?=$this->record($current)->getListEntry($list, $this->layout()->account->isLoggedIn())?>
          </li>
        <? endforeach; ?>
      </ul>

      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', array('results' => $this->results))?>
    <? else: ?>
      <p><?=$this->transEsc('You do not have any saved resources')?></p>
    <? endif; ?>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>
