<?
  // Set up page title:
  $this->headTitle(isset($list) ? $list->title : $this->translate('recovery_title'));

  // Set up extra button for header:
  $extraButton = '<a rel="external" href="'
    . $this->url('myresearch-home')
    . '" data-icon="back" class="ui-btn-left">';
  $extraButton .= $this->auth()->isLoggedIn()
    ? $this->transEsc('My Profile')
    : $this->transEsc('Login');
  $extraButton .= '</a>';
?>
<div data-role="page" id="MyResearch-recover" class="results-page">
  <?=$this->mobileMenu()->header(array('extraButtons'=>array($extraButton))) ?>
  <div data-role="content">
    <?=$this->flashmessages()?>
    <? if (!$this->auth()->getManager()->supportsRecovery()): ?>
      <div class="error"><?=$this->transEsc('recovery_disabled') ?></div>
    <? else: ?>
      <form class="form-horizontal" action="" method="post">
        <?=$this->auth()->getPasswordRecoveryForm() ?>
      </form>
    <? endif; ?>
  </div>
  <?=$this->mobileMenu()->footer() ?>
</div>