<?php
    $this->headLink()->appendStylesheet('vendor/jquery.dataTables.min.css');
    $this->headScript()->appendFile('vendor/jquery.dataTables.min.js');
    $this->headScript()->appendFile('vendor/dataTables.rowReorder.min.js');

    // Set up page title:
    $this->headTitle($this->translate('Broadcasts'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('admin/notifications-broadcasts', ['action' => 'Broadcasts']) . '">' . $this->transEsc('Notifications Broadcasts') . '</a></li>';
?>

<a class="search-filter-toggle visible-xs" href="#myresearch-sidebar" data-toggle="offcanvas" title="Expand Sidebar">
    <?=$this->transEsc('Home') ?>
</a>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Broadcasts')?></h2>
    <?=$this->flashmessages()?>

  <table id="notifications-list" class="table table-striped">
    <thead>
    <tr>
      <th style="width:100px;"><?=$this->transEsc('Edit')?></th>
      <th><?=$this->transEsc('Broadcast')?></th>
    </tr>
    </thead>
    <tbody>
      <?php foreach($this->broadcastsList as $broadcast): ?>
        <tr data-broadcast-id="<?=$broadcast['broadcast_id']?>">
          <td>
            <span class="reorder">
              <?=$this->icon('notifications-order') ?>
            </span>
            <?php if ($broadcast['visibility']): ?>
              <a href="" class="notifications-visibility" data-visibility="0"><?=$this->icon('notifications-visible') ?></a>
            <?php else: ?>
              <a href="" class="notifications-visibility" data-visibility="1"><?=$this->icon('notifications-invisible') ?></a>
            <?php endif; ?>
            <?php if ($broadcast['visibility_global']): ?>
              <a href="" class="notifications-visibility-global" data-visibility-global="0"><?=$this->icon('notifications-visible-global') ?></a>
            <?php else: ?>
              <a href="" class="notifications-visibility-global" data-visibility-global="1"><?=$this->icon('notifications-invisible-global') ?></a>
            <?php endif; ?>
            <a href="<?=$this->url('admin/notifications-broadcasts', ['action' => 'EditBroadcast'])?>?broadcast_id=<?=$broadcast['broadcast_id']?>" title="<?=$this->transEsc('Edit')?>"><?=$this->icon('notifications-edit') ?></a>
            <a href="<?=$this->url('admin/notifications-broadcasts', ['action' => 'DeleteBroadcast'])?>?broadcast_id=<?=$broadcast['broadcast_id']?>" title="<?=$this->transEsc('Delete')?>"><?=$this->icon('notifications-delete') ?></a>
          </td>
          <td>
            <span class="broadcast-<?=$this->notifications()->isBroadcastActive($broadcast) ? 'active' : 'inactive' ?>"><?=date_format(date_create($broadcast['startdate']), 'd.m.Y') ?> - <?=date_format(date_create($broadcast['enddate']), 'd.m.Y')?></span><br/>
            <span class="broadcast" style="background-color:<?=$broadcast['background_color_value']?>; border-color:<?=$broadcast['border_color_value']?>;"><?=$broadcast['content']?></span>
          </td>
        </tr>
      <?php endforeach; ?>
    </tbody>
  </table>

  <a href="<?=$this->url('admin/notifications-broadcasts', ['action' => 'EditBroadcast'])?>?broadcast_id=NEW"><?=$this->transEsc('Add New Notification')?></a>

</div>

<div class="<?=$this->layoutClass('sidebar')?>">
    <?=$this->render('admin/menu.phtml')?>
</div>