<!-- finc: RuntimeException -->
<?php /* largely copied from /bootstrap3/templates/error/index.phtml #17035 - RL */?>
<?php
  // Set page title.
  $this->headTitle($this->translate('Missing Record'));

  $this->layout()->breadcrumbs = '<li class="active">Error</li>';
?>
<div class="alert alert-danger">
  <p><?=$this->transEsc('An error has occurred')?></p>
      <p><?=$this->transEsc(
              'missing_record_exception',
              ['%%id%%' => $this->exception->getMessage()]
              )
        ?></p>
</div>
<form>
    <input type="button" class="btn" value="<?=$this->translate('navigate_back')?>" onclick="history.back()">
</form>

<?php if (isset($this->display_exceptions) && $this->display_exceptions): ?>
  <h2><?=$this->transEsc('Exception')?>:</h2>
  <p>
    <b><?=$this->transEsc('Message')?>:</b> <?=$this->escapeHtml($this->exception->getMessage())?>
  </p>

  <h2><?=$this->transEsc('Backtrace')?>:</h2>
  <pre><?=$this->exception->getTraceAsString()?>
  </pre>

  <?php if ($e = $this->exception->getPrevious()): ?>
    <h3>Previous exceptions:</h3>
    <?php while ($e): ?>
        <h4><?php echo get_class($e); ?></h4>
        <p><?=$e->getMessage()?></p>
        <pre><?=$e->getTraceAsString()?></pre>
        <?php $e = $e->getPrevious(); ?>
    <?php endwhile; ?>
  <?php endif; ?>

  <?php if (isset($this->request)): ?>
    <h2><?=$this->transEsc('error_page_parameter_list_heading')?>:</h2>
    <pre><?=$this->escapeHtml(var_export($this->request->getParams(), true))?></pre>
  <?php endif; ?>
<?php endif ?>
<!-- finc: RuntimeException - END -->
