<style>
    .read-more-state ~ .read-more-trigger:before {
        content: 'Plus';
    }

    .read-more-state:checked ~ .read-more-trigger:before {
        content: 'Moins';
    }
</style>
<?=$this->content()->renderTranslated('snippets/BreakingNews'); ?>
<?php
    $panelId = 0;
    $panelClass = "panel-default";
    $panelWidth = "col-md-6";
?>
<div class="col-md-12" style="margin-top: 30px;"></div>

<?=$this->render('content/snippets/RSSFeedAggregator'); ?>

<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-bell-o"></i> Bienvenue!
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Le nouvel IxTheo est une bibliographie exhaustive de théologie et de science des religions. On peut maintenant y faire des recherches non seulement sur des articles, mais également sur des monographies, des banques de données et des liens Internet. </p>
                    <div class="read-more-target">
                        <p>Il inclut aussi les données de certaines revues de critique choisies. Lorsque les licences le permettent, il est possible d’accéder directement au texte complet des articles, des critiques et des livres concernés.</p>
                        <p>Le nouvel IxTheo demeure un service à libre accès et gratuit offert à la communauté mondiale de recherche. Les éditeurs de l’IxTheo sont la bibliothèque de l’Université de Tübingen (Universitätsbibliothek Tübingen) de même que les facultés catholique et protestante de théologie de l’Université de Tübingen (Katholisch-Theologische / Evangelisch-Theologische Fakultät Tübingen).</p>
                        <p>Nous vous souhaitons une expérience agréable d’utilisation de l’IxTheo et serions reconnaissants pour tout commentaire nous aidant à l’améliorer.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-users"></i> Page d’information sur les personnes<div class="new">nouveau</div>
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Une nouvelle étape a été franchie avec l’introduction de la page d’information sur les personnes et les sociétés dans IxTheo et RelBib. Le troisième onglet nommé « Personnes / Sociétés » et situé à côté de « IxTheo » et de « Texte intégral » en donne l’accès.</p>
                    <div class="read-more-target">
                        <p>La page d’information sur les personnes et sociétés permet de faire une recherche sur des auteurs, des sociétés et des actes de colloque.</p>

                        <p>Saisissez d’abord le nom de la personne, de la société ou du colloque et appuyez sur le bouton « Rechercher ». Vous pouvez ensuite affiner la recherche en sélectionnant une ou plusieurs des facettes :</p>
                        <ul>
                            <li>Type de notice: Personne / Société / Colloque (actes)</li>
                            <li>Références externes: fichiers d’autorité / liens à Wikipedia, liens à des archives etc.</li>
                            <li>Activité: théologien / historien / prêtre etc.</li>
                            <li>Langue: allemand / anglais / français etc. </li>
                            <li>Localisation: Berlin / London / New York etc.</li>
                        </ul>

                        <p>La page d’information sur les personnes offre des informations biographiques et des liens donnant accès à des informations supplémentaires sur Wikipedia, des archives et d’autres ressources externes.</p>

                        <p>Les informations dont IxTheo dispose sont préparées et présentées d’une façon claire :</p>
                        <ul>
                            <li>Littérature <b>de</b> l’auteur</li>
                            <li>Littérature <b>sur</b> l’auteur</li>
                            <li>Liens avec d’<b>autres</b> personnes</li>
                            <li><b>Thèmes</b> (mots-clés) sur lequel l’auteur a publié</li>
                            <li>Une <b>chronologie</b> des publications</li>
                        </ul>

                        <p>Voici quelques exemples d’auteurs connus:</p>
                        <ul>
                            <li><a href="<?=$this->url('solrauthrecord')?>080038956">Judith Butler</a></li>
                            <li><a href="<?=$this->url('solrauthrecord')?>079908942">Luise Abramowski</a></li>
                            <li><a href="<?=$this->url('solrauthrecord')?>079319769">Rudolf Bultmann</a></li>
                            <li><a href="<?=$this->url('solrauthrecord')?>035286210">Martin Luther King</a></li>
                            <li><a href="<?=$this->url('solrauthrecord')?>133801128">Paul Claudel</a></li>
                            <li><a href="<?=$this->url('solrauthrecord')?>198371527">Pierre Bourdieu</a></li>
                        </ul>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12"></div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search-plus"></i> Recherche en texte intégral
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body flex-col">
                La nouvelle <a href="/Search2/Home?hiddenFilters[]=has_fulltext%3A1">recherche en texte intégral</a> permet de chercher dans des textes intégrals autant commercials que libres, des des sommaires et des résumés.<br/> Trouvez des informations detaillés dans la <a href="/docs/Recherche_en_texte_Description.pdf" target="_blank">description</a>.
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-desktop"></i> Publications en libre accès sur IxTheo
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>IxTheo offre un soutien pour les revues électroniques en libre accès: <a href="/Content/OpenJournals" data-lightbox>Liste des revues en libre accès publiées en collaboration avec IxTheo</a></p>
                    <div class="read-more-target">
                        <p><b><?=$this->transEsc('IxTheo Open Journals')?></b></p>
                        <ul>
                            <li><a target="_blank" href="https://aabner.org">Advances in Ancient Biblical and Near Eastern Research [2021-]</a></li>
                            <li><a target="_blank" href="https://jebs.eu">Journal of European Baptist Studies [2019-]</a></li>
                            <li><a target="_blank" href="https://imdialog.akademie-rs.de">Im Dialog. Beiträge aus der Akademie der Diözese Rottenburg-Stuttgart [2019-]</a></li>
                            <li><a target="_blank" href="https://jeac.de">Journal of Ethics in Antiquity and Christianity (JEAC) [2019-]</a></li>
                            <li><a target="_blank" href="https://iapt-cs.org">International Academy of Practical Theology. Conference Series (IAPT.CS) [2019-]</a></li>
                            <li><a target="_blank" href="https://vulgata-dialog.ch">Vulgata in Dialogue. A biblical online review [2017-]</a></li>
                            <li><a target="_blank" href="http://www.ethik-und-gesellschaft.de">Ethik und Gesellschaft (EuG) [2007-]</a></li>
                        </ul>
                        <p><b><?=$this->transEsc('IxTheo Open Journals (with moving wall)')?></b></p>
                        <ul>
                            <li><a target="_blank" href="https://zfbeg.org/">Zeitschrift für christlich-jüdische Begegnung im Kontext [2017-]</a></li>
                        </ul>
                        <p>
                            Avec la plate-forme « IxTheo Open Journals », nous offrons aux éditeurs la possibilité d'héberger en permanence leurs revues académiques ou séries monographiques de théologie en libre accès.<br/>
                            Nous vous permettons non seulement de fonder une nouvelle revue en libre accès, mais également de transformer une revue imprimée en revue électronique en libre accès. Pour ce faire, nous mettons à votre disposition le système de gestion de publications « Open Journal Systems » (OJS) qui permet de gérer la totalité du processus de rédaction, d'édition et de publication de votre revue.
                        </p>
                        <p>
                            La collaboration avec « IxTheo Open Journals » vous offre les avantages suivants :
                            <ul>
                                <li>IxTheo / la bibliothèque de l'Université de Tübingen met gratuitement à votre disposition le logiciel OJS, met votre revue (ou votre série) sur pied, offre une formation et un soutien technique continu</li>
                                <li>Avec OJS, toutes les étapes, de la réception des articles à la publication en passant par l'évaluation (« peer review »), sont gérées par un seul et unique système</li>
                                <li>La mise en page et le graphisme de votre revue OJS peuvent être personnalisés</li>
                                <li>Un identifiant pérenne (DOI) est attribué à tous les articles de la revue, ce qui garantit la capacité de les rechercher en permanence</li>
                                <li>Tous les articles de la revue sont indexés dans la bibliographie IxTheo</li>
                            </ul>
                        </p>
                        <p>
                            Cette offre est ouverte à tous les éditeurs de revues et de séries monographiques. Si elle vous intéresse, n'hésitez pas à contacter <a href="mailto:ixtheo@ub.uni-tuebingen.de">l'équipe IxTheo</a>.
                        </p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-puzzle-piece"></i> Collaboration IxTheo - <a target="_blank" href="https://www.uibk.ac.at/bildi/"><img src="<?=$this->imageLink('bildi.jpg')?>" width="50" alt="BILDI"></a> / <a target="_blank" href="https://www.uibk.ac.at/praktheol/kaldi/"><img src="<?=$this->imageLink('kaldi.png')?>" width="50" alt="KALDI"></a>
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>IxTheo collabore avec la Faculté de Théologique Catholique de l'Université d'Innsbruck (Autriche) dans la production d'une bibliographie spécialisée en exégèse biblique et en droit canonique.</p>
                    <div class="read-more-target">
                        <p>La migration complète des métadonnées de la bibliographie <a target="_blank" href="https://www.uibk.ac.at/bildi/">BILDI</a> dans IxTheo a déjà été effectuée. Plus de 200 000 titres indexés avec soin ont ainsi enrichit notre bibliographie dans le domaine de l'exégèse biblique. Un accès indépendant à la littérature exégétique, géré conjointement par BILDI et IxTheo, sera offert vers la fin de 2019.</p>
                        <p>La migration des métadonnées de la bibliographie <a target="_blank" href="https://www.uibk.ac.at/praktheol/kaldi/">KALDI</a> est également terminée, ajoutant de ce fait plus de 34 000 titres de droit canonique avec une indexation de haut niveau à IxTheo. Un accès indépendant à la littérature sur le droit canonique, géré conjointement par KALDI, DaKaR (bibliographie basée à Münster) et IxTheo, sera offert vers la fin de 2019.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-book"></i> Patron-Driven-Acquisition (PDA)
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Afin de fournir un accès maximum à la littérature théologique en Allemagne, nous offrons maintenant un service d’acquisition de livres sur demande («patron driven acquisition», PDA).</p>
                    <div class="read-more-target">
                        <p>Les livres requis sont achetés par la bibliothèque (UB) de l’université de Tübingen.</p>
                        <p>Les usagers peuvent donc demander directement sur le site web d’IxTheo l’acquisition de monographies qui ne sont pas disponibles à leur bibliothèque locale, ni accessibles par prêt interbibliothèques.</p>
                        <p><a href="docs/ixtheo-pda.pdf" target="_blank">Explication en détail de notre service PDA</a></p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<h2 class="col-md-12 panel-group">Découvrir l’IxTheo</h2>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Rechercher
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Vous pouvez amorcer une recherche sur tous les titres catalogués dans l’IxTheo en appuyant sur le bouton &laquo;Rechercher&raquo;. Vous trouverez alors plus de 2 millions de titres.</p>
                    <div class="read-more-target">
                        <p>Vous pouvez ensuite affiner la recherche selon certains critères en choisissant les facettes correspondantes. Par exemple, vous pouvez choisir &laquo;Électronique&raquo; comme type de médium, &laquo;Article&raquo; comme format et &laquo;Allemand&raquo; comme langue. Cela réduit alors le nombre de titres trouvés à environ 3000.</p>

                        <h3>Rechercher selon le contenu</h3>
                        <h4>Classification IxTheo</h4>
                        <p>Si vous cliquez sur &laquo;Recherche avancée&raquo;, vous y trouverez, entre autres, les classifications IxTheo. Vous pouvez choisir les facettes correspondantes par un simple clic de la souris. Il est possible de choisir un bloc de plusieurs facettes en tenant la touche majuscule appuyée (sur Windows) tout en cliquant sur les éléments au début et à la fin du bloc. Pour choisir plusieurs facettes séparément, il suffit de tenir la touche contrôle appuyée en cliquant sur les éléments désirés.</p>
                        <p>Vous pouvez ensuite amorcer la recherche de classifications IxTheo en appuyant sur le bouton &laquo;Rechercher&raquo;.</p>

                        <h4>Termes de recherche</h4>
                        <p>Saisissez le terme de recherche dans le champ approprié et utilisez &laquo;Tous les champs&raquo; comme facette de recherche. Le terme saisi est alors recherché dans tous les champs comme le nom l’indique.</p>
                        <p>Pour une recherche thématique, la facette &laquo;Sujet&raquo; s’avère très utile. Les différents sujets pour un article ou une publication ne sont pas déterminés par un procédé mécanique, mais plutôt à travers une évaluation faite par notre personnel.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> La Navigation
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Le nouvel IxTheo offre trois façons différentes de naviguer à travers les données :<br/><br/></p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <h3>Naviguer à partir d’un sujet</h3>
                        <p>Lorsque vous choisissez cette option, vous accédez à un nouveau champ où vous pouvez saisir le terme de recherche qui servira de point de départ à la navigation.</p>
                        <p>1<sup>er</sup> exemple : saisissez le terme &laquo;Dieu&raquo;. Une liste apparaît alors avec les chaînes de termes contenant le mot &laquo;Dieu&raquo;.</p>
                        <p>2<sup>e</sup> exemple : saisissez les termes &laquo;Dieu&raquo; et &laquo;Bible&raquo;. Une liste apparaît alors avec les chaînes de termes contenant les mots &laquo;Dieu&raquo; et &laquo;Bible&raquo;.</p>
                        <p>Si vous changez la langue de la page web à l’anglais, les termes sont traduits automatiquement en anglais si cette traduction est disponible dans le dictionnaire du système.</p>

                        <h3>Naviguer dans le catalogue</h3>
                        <p>La fonction standard de navigation de l’IxTheo (VuFind) permet la navigation avec des facettes diverses : la classification DDC, la classification IxTheo, le sujet, l’auteur et l’éditeur. À l’étape suivante, vous pouvez affiner la navigation en spécifiant des facettes supplémentaires.</p>
                        <p>Par exemple, si vous choisissez &laquo;Auteur&raquo;, &laquo;Par classification IxTheo&raquo; puis &laquo;HB Ancien Testament&raquo;, vous obtiendrez une liste d’auteurs ayant publié des œuvres dans le domaine de la recherche vétéro-testamentaire en ordre décroissant du nombre de publications des auteurs en question.</p>

                        <h3>Naviguer dans l’ordre alphabétique</h3>
                        <p>Cette option vous permet de naviguer à partir d’une lettre de l’alphabet de votre choix. Choisissez d’abord avec quelle facette vous voulez naviguer (soit le sujet, l’auteur, le titre ou la classification DDC), puis saisissez la lettre où la navigation doit commencer.</p>
                        <p>1<sup>er</sup> exemple : Choisissez &laquo;par Auteur&raquo; et saisissez à partir de &laquo;Z&raquo;. Vous obtiendrez une liste d’auteurs dont le nom commence par la lettre Z.</p>
                        <p>2<sup>e</sup> exemple : Choisissez &laquo;Par Titre&raquo; et saisissez à partir de &laquo;Tr&raquo;. Vous obtiendrez une liste de titres dont les deux premières lettres sont &laquo;Tr&raquo; .</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-12"></div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Personnaliser l’utilisation du service
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Plusieurs fonctions utiles sont offertes aux détenteurs d’un compte IxTheo. Une fois inscrit, vous pouvez accéder à votre compte en cliquant sur le lien &laquo;Connexion&raquo; au coin supérieur droit. Un clic sur &laquo;Votre compte&raquo; vous amène à la page de gestion de vos données. Vous avez alors accès aux fonctions suivantes :</p>
                    <div class="read-more-target">
                        <h3>Fonction d’alerte</h3>
                        <p>Cette fonction vous tient au courant de la publication de nouveaux articles dans les revues et de nouveaux volumes dans les séries de monographies de votre choix.</p>
                        <p>Pour activer cette fonction pour une publication, vous devez d’abord trouver l’enregistrement pour cette publication, puis cliquer sur le symbole en forme de cloche situé à droite de l’entrée. Vous pouvez gérer vos alertes dans votre compte sous la rubrique &laquo;liste d’alertes&raquo;.</p>

                        <p>1<sup>er</sup> exemple : Afin d’activer la fonction d’alerte pour la revue &laquo;Theologische Quartalschrift&raquo;, saisissez d’abord ce titre ou son abréviation &laquo;ThQ&raquo; dans le champ de recherche. Ensuite, choisissez &laquo;Périodique&raquo; dans la facette &laquo;Format&raquo;. Vous trouverez alors 2 titres : un pour la version imprimée, et un pour la version électronique de cette revue. Dans un cas semblable, il est plus sûr d’activer la fonction pour les deux versions.</p>

                        <p>2<sup>e</sup> exemple : Afin d’activer la fonction pour la série &laquo;Wissenschaftliche Untersuchungen zum Neuen Testament&raquo;, saisissez d’abord ce titre ou son abréviation &laquo;WUNT&raquo; dans le champ de recherche. Vous trouverez alors plusieurs titres. Activez la série en cliquant sur le symbole correspondant en forme de cloche.</p>

                        <p>Éventuellement, nous espérons rendre la sélection de revues et de séries plus facile pour cette fonction. En particulier, nous aimerions offrir l’option de choisir un bloc de revues consacrées à un domaine de recherche quelconque.</p>

                        <h3>Sauvegarder les requêtes de recherche</h3>
                        <p>Vos requêtes courantes de recherche sont sauvegardées temporairement dans l’historique de recherche. Si vous voulez les conserver plus longtemps, vous pouvez les sauvegarder dans votre compte. Elles demeurent alors à votre disposition, et vous pouvez les amorcer à nouveau par un simple clic. Cela peut valoir la peine pour des requêtes complexes ou pour des sujets qui vous intéressent toujours. Cela vous permet de découvrir les nouvelles parutions sur un sujet ou un domaine de recherche particulier.</p>

                        <h3>Sauvegarder les Favoris</h3>
                        <p>Vous pouvez sauvegarder les titres qui vous intéressent dans votre compte. Vous y avez alors accès en tout temps sans avoir à les rechercher à nouveau. Vous pouvez les sauvegarder à l’intérieur de listes que vous définissez vous-mêmes, ce qui vous permet de classifier vos titres selon des projets de recherches ou des thèmes précis.</p>
                        <p>À partir de votre compte, vous pouvez également exporter vos favoris, les envoyer par mail ou les imprimer.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6 ix-panel-news">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-binoculars"></i> Rechercher un passage de la Bible
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>La recherche de passages de la Bible a été conçue complètement à neuf et adaptée aux besoins des usagers s’intéressant à la recherche scientifique. Pour rechercher un passage de la Bible, il faut choisir la facette &laquo;Passages bibliques&raquo; à droite du champ de saisie. La liste de titres trouvés doit ensuite être triée selon la pertinence.</p>
                    <div class="read-more-target">
                        <p>On peut spécifier le passage en employant les noms de livres bibliques reconnus internationalement ou les abréviations connues. Outre les abréviations françaises, l’IxTheo reconnaît également les abréviations anglaises, allemandes, italiennes et espagnoles de même que celles employées dans l’édition Nestle-Aland du Nouveau Testament et dans la Vulgate. La possibilité d’employer diverses langues a cependant causé des ambiguïtés pour les noms de certains livres bibliques. Par exemple, l’abréviation &laquo;Es&raquo; pour le livre d’Ésaïe en français désigne le livre de l’Exode en italien. Dans ces cas, nous avons dû décider quelles abréviations nous pouvions accepter pour éviter de tels conflits. Vous pouvez consulter la liste des abréviations reconnues par l’IxTheo au lien suivant :
                            <a href="<?='https://' . $_SERVER['SERVER_NAME'] . '/docs/Bible_abbreviation.pdf'?>" target="_blank"><b>ici</b></a>.</p>
                        <p>Saisissez le passage de la Bible que vous désirez rechercher de la façon suivante :
                            [Abréviation du livre] chapitre,verset(s)</p>
                        <b>Exemples :</b>
                        <ul>
                            <li>Jn 5,1-20 ou Joh 5,1-20</li>
                            <li>1 Co 10 ou 1Cor 10</li>
                            <li>Rm 14,1-15,13 ou Ro 14,1-15,13</li>
                        </ul>
                        <p>Les titres trouvés sont classifiés selon leur proximité au passage recherché :</p>
                        <ol>
                            <li><p>Résultat exact : il y a une correspondance parfaite entre le passage saisi et les titres trouvés.</p>
                                <p>Par exemple, une recherche sur Mc 5,25-34 produit une liste de publications ayant pour sujet ce passage.</p></li>
                            <li><p>Résultat inclusif : le passage saisi se recoupe en partie avec les titres trouvés.</p>
                                <p>Par exemple, une recherche sur Mc 5,25-34 permet de trouver une publication ayant pour sujet Mc 5,24-34.</p></li>
                            <li><p>Résultat indirect : le passage saisi fait partie du chapitre de la Bible dont il est question dans les titres trouvés.</p>
                                <p>Par exemple, une recherche sur Mc 5,25-34 permet de trouver des publications portant sur Mc 5.</p></li>
                        </ol>
                        <p>Dans cet exemple, la recherche permet également de trouver les titres liés à la notice d’autorité &laquo;Blutflüssige Frau&raquo; (&laquo;femme avec une perte de sang&raquo;). Les passages synoptiques Mc 5,25-34 de même que Mt 9,20-22 et Lc 8,43-48 sont associés à cette notice.</p>
                        <p>Néanmoins, il est toujours profitable de mener une recherche sur un passage biblique en utilisant &laquo;Tous les champs&raquo; comme facette de recherche, car ce ne sont pas encore tous les titres qui ont été associés aux notices d’autorité des passages bibliques. Par contre, ce type de recherche plus général ne permet pas de tirer profit des caractéristiques uniques de la recherche IxTheo des passages bibliques.</p>
                        <p>Au niveau technique de la mise en œuvre de la recherche IxTheo des passages bibliques, le  passage saisi en tant que chaîne de caractères est converti en une suite de 7 chiffres, avec laquelle il est possible d’effectuer des opérations. Les deux premiers chiffres correspondent au livre de la Bible, les trois chiffres du milieu au chapitre, et les deux derniers au verset. Ainsi, Mc 5,25-34 est converti comme suit : 0200525_0200534. En vue de déterminer la proximité entre le passage saisi et celui du titre trouvé, un score est attribué à cette paire de passages. Vous trouverez plus d’informations (en allemand) à la page suivante:
                            <a href=https://github.com/ubtue/ixTheo/wiki/Bibelstellensuche---Technischer-%C3%9Cberblick target="_blank"><b>Aper&ccedil;u technique</b></a>
                        <p/>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
