<?php $this->headTitle($this->translate('Impressum'));?>
<h1>Impressum</h1>
<p>Impressum gem. §5 Telemediengesetz und §5 Rundfunkstaatsvertrag</p>
<table class="table table-striped">
    <tr>
        <td>Dienstanbieter</td>
        <td>Universitätsbibliothek der Eberhard Karls Universität Tübingen</td>
    </tr>
    <tr>
        <td>Anschrift</td>
        <td>Universitätsbibliothek<br/>
            Wilhelmstraße 32<br/>
            72074 Tübingen</td>
    </tr>
    <tr>
        <td>Kontakt</td>
        <td>IxTheo-Team der UB Tübingen<br/>
            ixtheo@ub.uni-tuebingen.de<br/>
            +49 (0)7071 2974029</td>
    </tr>
    <tr>
        <td>Rechtsform</td>
        <td>Die Universität Tübingen ist eine Körperschaft des öffentlichen Rechts. Sie wird durch den Rektor Prof. Dr. Bernd Engler (E-Mail: bernd.engler@uni-tuebingen.de) gesetzlich vertreten.</td>
    </tr>
    <tr>
        <td>Umsatzsteuer-Identifikationsnummer</td>
        <td>DE812383453</td>
    </tr>
    <tr>
        <td>Aufsichtsbehörde</td>
        <td>Ministerium für Wissenschaft, Forschung und Kunst Baden Württemberg</td>
    </tr>
    <tr>
        <td>Haftungshinweis</td>
        <td>Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</td>
    </tr>
    <tr>
        <td>Inhaltlich Verantwortliche für das Informationsangebot des Index Theologicus gemäß §55 Abs. 2 RStV</td>
        <td>Dr. Marianne Dörr (Direktorin der Universitätsbibliothek Tübingen)</td>
    </tr>
</table>
