<h1>IxTheo-Klassifikation</h1>
<a rel="license"
   href="http://creativecommons.org/publicdomain/zero/1.0/">
  <img src="http://i.creativecommons.org/p/zero/1.0/88x31.png" style="border-style: none;" alt="CC0" />
</a>
Die Herausgeber des Index Theologicus (IxTheo) stellen die IxTheo-Klassifikation zur freien Nachnutzung unter der Lizenz <a href="http://creativecommons.org/publicdomain/zero/1.0/deed.de" target="_blank">CC0 1.0</a> zur Verfügung.</p>

Die <a href="/classification" target="_blank">IxTheo-Klassifikation</a> ist eine Facettenklassifikation bestehend aus 13 Hauptgruppen und 139 Klassen, die seit 1995 als klassifikatorische Basiserschließung im IxTheo angewandt wird (siehe <a href=/docs/ixtheo-erschliessungskonzept.pdf target="_blank">Erschließungskonzept</a>):</p>

<?php $translator = $this->plugin('translate')->getTranslator();
   $list = $this->ixtheo()->getNestedIxtheoClassificationArray($translator);
   echo $this->htmlList($list, false, false, false);
?>




