<h1>IxTheo Open Journals</h1>
<?php // unfortunately hyperlinks need onclick attribute as well due to lightbox problem ?>
<ul style="list-style-type: none; padding-left: 0px; line-height: 25px;">
    <li><a target="_blank" href="https://jeac.de" onclick="window.location.href='https://jeac.de';"><img src="<?=$this->imageLink('jeac.png')?>" width="16">&nbsp;Journal of Ethics in Antiquity and Christianity (JEAC)</a></li>
    <li><a target="_blank" href="https://iapt-cs.org" onclick="window.location.href='https://iapt-cs.org';"><img src="<?=$this->imageLink('iapt-cs.png')?>" width="16">&nbsp;International Academy of Practical Theology. Conference Series (IAPT.CS)</a></li>
    <li><a target="_blank" href="https://vulgata-dialog.ch" onclick="window.location.href='https://vulgata-dialog.ch';"><img src="<?=$this->imageLink('vulgata.png')?>" width="16">&nbsp;Vulgata in Dialogue. A biblical online review</a></li>
    <li><a target="_blank" href="http://www.ethik-und-gesellschaft.de" onclick="window.location.href='http://www.ethik-und-gesellschaft.de';"><img src="<?=$this->imageLink('eug.ico')?>" width="16">&nbsp;Ethik und Gesellschaft (EuG)</a></li>
</ul>