<h1>IxTheo Open Journals</h1>
<p>
    <?php // unfortunately hyperlinks need onclick attribute as well due to lightbox problem ?>
    <img src="<?=$this->imageLink('jeac.png')?>" width="16"><a target="_blank" href="https://jeac.de" onclick="window.location.href='https://jeac.de';">Journal of Ethics in Antiquity and Christianity (JEAC)</a><br/>
    <img src="<?=$this->imageLink('iapt-cs.png')?>" width="16"><a target="_blank" href="https://iapt-cs.org" onclick="window.location.href='https://iapt-cs.org';">International Academy of Practical Theo gy. Conference Series (IAPT.CS)</a><br/>
    <img src="<?=$this->imageLink('vulgata.png')?>" width="16"><a target="_blank" href="https://vulgata-dialog.ch" onclick="window.location.href='https://vulgata-dialog.ch';">Vulgata in Dialogue. A biblical online review</a><br/>
    <img src="<?=$this->imageLink('eug.ico')?>" width="16"><a target="_blank" href="http://www.ethik-und-gesellschaft.de" onclick="window.location.href='http://www.ethik-und-gesellschaft.de';">Ethik und Gesellschaft (EuG)</a><br/>
</p>