<!-- START of: finna - Helpers/location-service-modal.phtml -->
<div class="location-service">
  <div class="link">
    <a href="<?=$this->url?>" target="location-service" class=""><i class="fa fa-external-link"></i> <?=$this->translate('Open in a new window')?></a>
  </div>
  <iframe class="frame" src="<?=$this->url?>"></iframe>
</div>
<!-- END of: finna - Helpers/location-service-modal.phtml -->
