<!-- START of: finna - content/aboutfinna_sites.phtml -->

<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Public_library_plural')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://vaski.finna.fi"><img src="<?=$this->imageLink('vaski.jpg')?>" alt="vaski.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/Vaski/')?></p>
                <p class="organisation-list-url"><a href="https://vaski.finna.fi">vaski.finna.fi</a></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Museum_plural')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://hkm.finna.fi"><img src="<?=$this->imageLink('hkm.jpg')?>" alt="hkm.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
                <p class="organisation-list-url"><a href="https://hkm.finna.fi">hkm.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hkm.finna.fi/elanto/"><img src="<?=$this->imageLink('hkmelanto.jpg')?>" alt="hkm.finna.fi/elanto/ <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
                <p class="organisation-list-url"><a href="https://hkm.finna.fi/elanto/">hkm.finna.fi/elanto</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hrm.finna.fi"><img src="<?=$this->imageLink('hrm.jpg')?>" alt="hrm.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HOTELLI- JA RAVINTOLAMUSEO/')?></p>
                <p class="organisation-list-url"><a href="https://hrm.finna.fi">hrm.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://lappeenrannanmuseot.finna.fi"><img src="<?=$this->imageLink('lappeenrannanmuseot.jpg')?>" alt="lappeenrannanmuseot.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/LPRMUSEOT/')?></p>
                <p class="organisation-list-url"><a href="https://lappeenrannanmuseot.finna.fi">lappeenrannanmuseot.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://museot.finna.fi/"><img src="<?=$this->imageLink('museot.jpg')?>" alt="museot.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('Museum_plural')?></p>
                <p class="organisation-list-url"><a href="https://museot.finna.fi/">museot.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://lelumuseohevosenkenka.finna.fi/"><img src="<?=$this->imageLink('lelumuseohevosenkenka.jpg')?>" alt="lelumuseohevosenkenka.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HEVOSENKENKA/')?></p>
                <p class="organisation-list-url"><a href="https://lelumuseohevosenkenka.finna.fi/">lelumuseohevosenkenka.finna.fi</a></p>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Polytechnic_library_plural')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://centria.finna.fi"><img src="<?=$this->imageLink('centria.jpg')?>" alt="centria.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/CENTRIA/')?></p>
                <p class="organisation-list-url"><a href="https://centria.finna.fi">centria.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://humak.finna.fi"><img src="<?=$this->imageLink('humak.jpg')?>" alt="humak.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HUMAK/')?></p>
                <p class="organisation-list-url"><a href="https://humak.finna.fi">humak.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hamk.finna.fi"><img src="<?=$this->imageLink('hamk.jpg')?>" alt="hamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HAMK/')?></p>
                <p class="organisation-list-url"><a href="https://hamk.finna.fi">hamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://janet.finna.fi"><img src="<?=$this->imageLink('janet.jpg')?>" alt="janet.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/JAMK/')?></p>
                <p class="organisation-list-url"><a href="https://janet.finna.fi">janet.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi"><img src="<?=$this->imageLink('kaakkuri.jpg')?>" alt="kaakkuri.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url"><a href="https://kaakkuri.finna.fi">kaakkuri.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi/kyamk/"><img src="<?=$this->imageLink('kyamk.jpg')?>" alt="kaakkuri.finna.fi/kyamk/ <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url"><a href="https://kaakkuri.finna.fi/kyamk/">kaakkuri.finna.fi/kyamk</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi/mamk/"><img src="<?=$this->imageLink('mamk.jpg')?>" alt="kaakkuri.finna.fi/mamk/ <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url"><a href="https://kaakkuri.finna.fi/mamk/">kaakkuri.finna.fi/mamk</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kamk.finna.fi"><img src="<?=$this->imageLink('kamk.jpg')?>" alt="kamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/KAMK/')?></p>
                <p class="organisation-list-url"><a href="https://kamk.finna.fi">kamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://karelia.finna.fi"><img src="<?=$this->imageLink('karelia.jpg')?>" alt="karelia.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/KARELIA/')?></p>
                <p class="organisation-list-url"><a href="https://karelia.finna.fi">karelia.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://masto.finna.fi"><img src="<?=$this->imageLink('masto.jpg')?>" alt="masto.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/PHKK/')?></p>
                <p class="organisation-list-url"><a href="https://masto.finna.fi">masto.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://laurea.finna.fi"><img src="<?=$this->imageLink('laurea.jpg')?>" alt="laurea.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/LAUREA/')?></p>
                <p class="organisation-list-url"><a href="https://laurea.finna.fi">laurea.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://metropolia.finna.fi"><img src="<?=$this->imageLink('metropolia.jpg')?>" alt="metropolia.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/METROPOLIA/')?></p>
                <p class="organisation-list-url"><a href="https://metropolia.finna.fi">metropolia.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://oamk.finna.fi"><img src="<?=$this->imageLink('oamk.jpg')?>" alt="oamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/OAMK/')?></p>
                <p class="organisation-list-url"><a href="https://oamk.finna.fi">oamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://samk.finna.fi"><img src="<?=$this->imageLink('samk.jpg')?>" alt="samk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/SAMK/')?></p>
                <p class="organisation-list-url"><a href="https://samk.finna.fi">samk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://seamk.finna.fi"><img src="<?=$this->imageLink('seamk.jpg')?>" alt="seamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/SEAMK/')?></p>
                <p class="organisation-list-url"><a href="https://seamk.finna.fi">seamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tamk.finna.fi"><img src="<?=$this->imageLink('tamk.jpg')?>" alt="tamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/TAMK/')?></p>
                <p class="organisation-list-url"><a href="https://tamk.finna.fi">tamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tuamk.finna.fi"><img src="<?=$this->imageLink('tuamk.jpg')?>" alt="tuamk.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/TUAMK/')?></p>
                <p class="organisation-list-url"><a href="https://tuamk.finna.fi">tuamk.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://haagahelia.finna.fi"><img src="<?=$this->imageLink('haagahelia.jpg')?>" alt="haagahelia.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/HAAGA-HELIA/')?></p>
                <p class="organisation-list-url"><a href="https://haagahelia.finna.fi">haagahelia.finna.fi</a></p>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://luc.finna.fi/lapinamk"><img src="<?=$this->imageLink('luc_lapinamk.jpg')?>" alt="luc.finna.fi/lapinamk <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
                <p class="organisation-list-url"><a href="https://luc.finna.fi/lapinamk">luc.finna.fi/lapinamk</a></p>
                <p class="organisation-list-beta">beta</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('University_library_plural')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://jyu.finna.fi"><img src="<?=$this->imageLink('jyu.jpg')?>" alt="jyu.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/JYU/')?></p>
                <p class="organisation-list-url"><a href="https://jyu.finna.fi">jyu.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://luc.finna.fi/ulapland"><img src="<?=$this->imageLink('luc_ulapland.jpg')?>" alt="luc.finna.fi/ulapland <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
                <p class="organisation-list-url"><a href="https://luc.finna.fi/ulapland">luc.finna.fi/ulapland</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hanken.finna.fi"><img src="<?=$this->imageLink('hanken.jpg')?>" alt="hanken.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/SHH/')?></p>
                <p class="organisation-list-url"><a href="https://hanken.finna.fi">hanken.finna.fi</a></p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://aalto.finna.fi"><img src="<?=$this->imageLink('aalto.jpg')?>" alt="aalto.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/AALTO/')?></p>
                <p class="organisation-list-url"><a href="https://aalto.finna.fi">aalto.finna.fi</a></p>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://uef.finna.fi"><img src="<?=$this->imageLink('uef.jpg')?>" alt="uef.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/UEF/')?></p>
                <p class="organisation-list-url"><a href="https://uef.finna.fi">uef.finna.fi</a></p>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kansalliskirjasto.finna.fi"><img src="<?=$this->imageLink('kansalliskirjasto.jpg')?>" alt="kansalliskirjasto.finna.fi <?=$this->transEsc('smallcaps_screenshot')?>" /></a>
                <p class="organisation-list-header"><?=$this->transEsc('0/NLF/')?></p>
                <p class="organisation-list-url"><a href="https://kansalliskirjasto.finna.fi">kansalliskirjasto.finna.fi</a></p>
                <p class="organisation-list-beta">beta</p>
            </div>
        </div>
    </div>
</div>

<!-- END of: finna - content/aboutfinna_sites.phtml -->