<!-- START of: finna - content/about_finna_sites.phtml -->

<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Public Libraries')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://vaski.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/vaski.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'vaski.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/Vaski/')?></p>
                <p class="organisation-list-url">vaski.finna.fi</p></a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Archives')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://lasipalatsi.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/albumitauki.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lasipalatsi.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/lasipalatsi/')?></p>
                <p class="organisation-list-url">lasipalatsi.finna.fi</p></a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Museums')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://ekm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/ekm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'ekm.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/ESPOO_KAUPMUS/')?></p>
                <p class="organisation-list-url">ekm.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hkm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hkm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hkm.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
                <p class="organisation-list-url">hkm.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hkm.finna.fi/elanto/"><img src="<?=$this->imageLink('finnafrontpages/hkmelanto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hkm.finna.fi/elanto/'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HKM/')?></p>
                <p class="organisation-list-url">hkm.finna.fi/elanto</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hrm.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hrm.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hrm.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HOTELLI- JA RAVINTOLAMUSEO/')?></p>
                <p class="organisation-list-url">hrm.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://lappeenrannanmuseot.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/lappeenrannanmuseot.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lappeenrannanmuseot.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LPRMUSEOT/')?></p>
                <p class="organisation-list-url">lappeenrannanmuseot.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://museot.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/museot.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'museot.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('Museums')?></p>
                <p class="organisation-list-url">museot.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://satakunnanmuseo.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/satakunnanmuseo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'satakunnanmuseo.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/SATMUSEO/')?></p>
                <p class="organisation-list-url">satakunnanmuseo.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://lelumuseohevosenkenka.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/lelumuseohevosenkenka.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'lelumuseohevosenkenka.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HEVOSENKENKA/')?></p>
                <p class="organisation-list-url">lelumuseohevosenkenka.finna.fi</p></a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Polytechnic Libraries')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://arcada.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/arcada.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'arcada.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/ARCADA/')?></p>
                <p class="organisation-list-url">arcada.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://centria.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/centria.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'centria.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/CENTRIA/')?></p>
                <p class="organisation-list-url">centria.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://diak.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/diak.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'diak.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/DIAK/')?></p>
                <p class="organisation-list-url">diak.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://haagahelia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/haagahelia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'haagahelia.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HAAGA-HELIA/')?></p>
                <p class="organisation-list-url">haagahelia.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://humak.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/humak.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'humak.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HUMAK/')?></p>
                <p class="organisation-list-url">humak.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/HAMK/')?></p>
                <p class="organisation-list-url">hamk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://janet.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/janet.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'janet.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/JAMK/')?></p>
                <p class="organisation-list-url">janet.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi/kyamk/"><img src="<?=$this->imageLink('finnafrontpages/kyamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kaakkuri.finna.fi/kyamk/'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url">kaakkuri.finna.fi/kyamk</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi/mamk/"><img src="<?=$this->imageLink('finnafrontpages/mamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kaakkuri.finna.fi/mamk/'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url">kaakkuri.finna.fi/mamk</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/KAMK/')?></p>
                <p class="organisation-list-url">kamk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://karelia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/karelia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'karelia.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/KARELIA/')?></p>
                <p class="organisation-list-url">karelia.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://masto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/masto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'masto.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/PHKK/')?></p>
                <p class="organisation-list-url">masto.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://luc.finna.fi/lapinamk"><img src="<?=$this->imageLink('finnafrontpages/luc_lapinamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi/lapinamk'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
                <p class="organisation-list-url">luc.finna.fi/lapinamk</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://wilma.finna.fi/saimia"><img src="<?=$this->imageLink('finnafrontpages/saimia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'wilma.finna.fi/saimia'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LUT/')?></p>
                <p class="organisation-list-url">wilma.finna.fi/saimia</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://laurea.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/laurea.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'laurea.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LAUREA/')?></p>
                <p class="organisation-list-url">laurea.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://metropolia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/metropolia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'metropolia.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/METROPOLIA/')?></p>
                <p class="organisation-list-url">metropolia.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://oamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/oamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'oamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/OAMK/')?></p>
                <p class="organisation-list-url">oamk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://samk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/samk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'samk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/SAMK/')?></p>
                <p class="organisation-list-url">samk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://savonia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/savonia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'savonia.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/SAVONIA/')?></p>
                <p class="organisation-list-url">savonia.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://seamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/seamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'seamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/SEAMK/')?></p>
                <p class="organisation-list-url">seamk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/tamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TAMK/')?></p>
                <p class="organisation-list-url">tamk.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tritonia.finna.fi/novia/"><img src="<?=$this->imageLink('finnafrontpages/novia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'https://tritonia.finna.fi/novia/'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-NOVIA/')?></p>
                <p class="organisation-list-url">https://tritonia.finna.fi/novia/</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tritonia.finna.fi/vamk/"><img src="<?=$this->imageLink('finnafrontpages/vamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'https://tritonia.finna.fi/vamk/'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-VAMK/')?></p>
                <p class="organisation-list-url">https://tritonia.finna.fi/vamk/</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://turkuamk.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/turkuamk.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'turkuamk.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TUAMK/')?></p>
                <p class="organisation-list-url">turkuamk.finna.fi</p></a>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('University Libraries')?></h4>
        <div class="row organisation-list-inner-row">
            <div class="col-xs-6 col-sm-3"> <a href="https://aalto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/aalto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'aalto.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/AALTO/')?></p>
                <p class="organisation-list-url">aalto.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://uef.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/uef.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'uef.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/UEF/')?></p>
                <p class="organisation-list-url">uef.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://jyu.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/jyu.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'jyu.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/JYU/')?></p>
                <p class="organisation-list-url">jyu.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://kansalliskirjasto.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kansalliskirjasto.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kansalliskirjasto.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/NLF/')?></p>
                <p class="organisation-list-url">kansalliskirjasto.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://luc.finna.fi/ulapland"><img src="<?=$this->imageLink('finnafrontpages/luc_ulapland.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi/ulapland'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
                <p class="organisation-list-url">luc.finna.fi/ulapland</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://wilma.finna.fi/lut"><img src="<?=$this->imageLink('finnafrontpages/lut.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'wilma.finna.fi/lut'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LUT/')?></p>
                <p class="organisation-list-url">wilma.finna.fi/lut</p></a>
            </div> 
            <div class="col-xs-6 col-sm-3"> <a href="https://oula.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/oula.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'oula.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/OY/')?></p>
                <p class="organisation-list-url">oula.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://hanken.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/hanken.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'hanken.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/SHH/')?></p>
                <p class="organisation-list-url">hanken.finna.fi</p></a>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tamcat.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/tay.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tamcat.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TAY/')?></p>
                <p class="organisation-list-url">tamcat.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://tritonia.finna.fi/uva/"><img src="<?=$this->imageLink('finnafrontpages/uva.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tritonia.finna.fi/uva'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA-UVA/')?></p>
                <p class="organisation-list-url">tritonia.finna.fi/uva</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
            <div class="col-xs-6 col-sm-3"> <a href="https://abo.finna.fi/"><img src="<?=$this->imageLink('finnafrontpages/abo.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'abo.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/AA/')?></p>
                <p class="organisation-list-url">abo.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-11 col-lg-9">
        <h4><?=$this->transEsc('Joint libraries')?></h4>
        <div class="row organisation-list-inner-row">
        <div class="col-xs-6 col-sm-3"> <a href="https://kaakkuri.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/kaakkuri.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'kaakkuri.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/XAMK/')?></p>
                <p class="organisation-list-url">kaakkuri.finna.fi</p></a>
        </div>
        <div class="col-xs-6 col-sm-3"> <a href="https://luc.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/luc.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'luc.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/LUC/')?></p>
                <p class="organisation-list-url">luc.finna.fi</p></a>
        </div>
        <div class="col-xs-6 col-sm-3"> <a href="https://tritonia.finna.fi"><img src="<?=$this->imageLink('finnafrontpages/tritonia.jpg')?>" alt="<?=$this->escapeHtmlAttr($this->translate('screenshot_alt_text', ['%%siteurl%%' => 'tritonia.finna.fi'])); ?>" />
                <p class="organisation-list-header"><?=$this->transEsc('0/TRITONIA/')?></p>
                <p class="organisation-list-url">tritonia.finna.fi</p></a>
                <p class="organisation-list-beta">beta</p>
        </div>
        </div>
    </div>
</div>

<!-- END of: finna - content/about_finna_sites.phtml -->
