<!-- START of: finna - content/about_finna_en-gb.phtml -->
<? $this->headTitle($this->translate('What is Finna?')); $this->content()->setHeading($this->translate('What is Finna?'));  ?>
<div class="row">
  <div class="col-xs-12">
    <h2>Finna.fi</h2>
  </div>
</div>
<div class="row">
  <div class="col-sm-5 col-md-4">
    <a href="https://www.finna.fi?lng=en-gb"><img src="<?=$this->imageLink('finnafi.jpg')?>" alt="finna.fi screenshot" /></a>
    <p>&nbsp;</p>
  </div>
  <div class="col-sm-7 col-md-6">
    <p><a href="https://www.finna.fi?lng=en-gb">Finna.fi</a> provides free access to material from <a href="https://www.finna.fi/Content/Organisations?lng=en-gb">Finnish museums, libraries and archives.</a></p>
    <p>You can browse and read material <a href="https://www.finna.fi/Search/Results?<?=$this->escapeHtmlAttr('type=AllFields&filter%5B%5D=online_boolean%3A1&lng=en-gb')?>">available on the web.</a></p>
    <p>You can also <a href="https://www.finna.fi/MyResearch/Home?lng=en-gb">renew loans and reserve material</a> from various libraries in one place.</p>
    <p>Finna.fi is your one stop destination for searching the freely available material provided by the partner organisations.</p>
  </div>
</div>
</div>
</div>
</div>
<div class="container-fluid odd-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Other Finna search services</h2>
        <p>Finna is a search service entity containing several sites in addition to the nationwide finna.fi site. The content of organisation-specific sites is usually limited to the material of those individual organisations.</p>
      </div>
    </div>
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>Public libraries</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://vaski.finna.fi"><img src="<?=$this->imageLink('vaski.jpg')?>" alt="vaski.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Vaski-libraries</p><p class="organisation-list-url"><a href="https://vaski.finna.fi">vaski.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>Museums</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://hkm.finna.fi"><img src="<?=$this->imageLink('hkm.jpg')?>" alt="hkm.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Helsinki City Museum</p><p class="organisation-list-url"><a href="https://hkm.finna.fi">hkm.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hrm.finna.fi"><img src="<?=$this->imageLink('hrm.jpg')?>" alt="hrm.finna.fi screenshot" /></a>
            <p class="organisation-list-header">The Hotel and Restaurant Museum</p><p class="organisation-list-url"><a href="https://hrm.finna.fi">hrm.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://lelumuseohevosenkenka.finna.fi/"><img src="<?=$this->imageLink('lelumuseohevosenkenka.jpg')?>" alt="lelumuseohevosenkenka.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Finnish Toy Museum</p><p class="organisation-list-url"><a href="https://lelumuseohevosenkenka.finna.fi/">lelumuseohevosenkenka.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://museot.finna.fi/"><img src="<?=$this->imageLink('museot.jpg')?>" alt="museot.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Museums (National Board of Antiquities)</p><p class="organisation-list-url"><a href="https://museot.finna.fi/">museot.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>University of applied sciences libraries</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://masto.finna.fi"><img src="<?=$this->imageLink('masto.jpg')?>" alt="masto.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Lahti UAS</p><p class="organisation-list-url"><a href="https://masto.finna.fi">masto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://samk.finna.fi"><img src="<?=$this->imageLink('samk.jpg')?>" alt="samk.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Satakunta UAS</p><p class="organisation-list-url"><a href="https://samk.finna.fi">samk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://oamk.finna.fi"><img src="<?=$this->imageLink('oamk.jpg')?>" alt="oamk.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Oulu UAS</p><p class="organisation-list-url"><a href="https://oamk.finna.fi">oamk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hamk.finna.fi"><img src="<?=$this->imageLink('hamk.jpg')?>" alt="hamk.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Häme UAS</p><p class="organisation-list-url"><a href="https://hamk.finna.fi">hamk.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://janet.finna.fi"><img src="<?=$this->imageLink('janet.jpg')?>" alt="janet.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Jyväskylä UAS</p><p class="organisation-list-url"><a href="https://janet.finna.fi">janet.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://kaakkuri.finna.fi"><img src="<?=$this->imageLink('kaakkuri.jpg')?>" alt="kaakkuri.finna.fi screenshot" /></a>
            <p class="organisation-list-header">South-Eastern Finland UAS</p><p class="organisation-list-url"><a href="https://kaakkuri.finna.fi">kaakkuri.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://laurea.finna.fi"><img src="<?=$this->imageLink('laurea.jpg')?>" alt="laurea.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Laurea Library</p><p class="organisation-list-url"><a href="https://laurea.finna.fi">laurea.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://metropolia.finna.fi"><img src="<?=$this->imageLink('metropolia.jpg')?>" alt="metropolia.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Metropolia UAS</p><p class="organisation-list-url"><a href="https://metropolia.finna.fi">metropolia.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://seamk.finna.fi"><img src="<?=$this->imageLink('seamk.jpg')?>" alt="seamk.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Seinäjoki Academic Library</p><p class="organisation-list-url"><a href="https://seamk.finna.fi">seamk.finna.fi</a></p>
          </div>
        </div>
      </div>
    </div>
    
    <div class="row">
      <div class="col-md-11 col-lg-9">
        <h4>University libraries</h4>
        <div class="row">
          <div class="col-xs-6 col-sm-3">
            <a href="https://jyu.finna.fi"><img src="<?=$this->imageLink('jyu.jpg')?>" alt="jyu.finna.fi screenshot" /></a>
            <p class="organisation-list-header">University of Jyväskylä</p><p class="organisation-list-url"><a href="https://jyu.finna.fi">jyu.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://kansalliskirjasto.finna.fi"><img src="<?=$this->imageLink('kansalliskirjasto.jpg')?>" alt="kansalliskirjasto.finna.fi screenshot" /></a>
            <p class="organisation-list-header">The National Library of Finland</p><p class="organisation-list-url"><a href="https://kansalliskirjasto.finna.fi">kansalliskirjasto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://aalto.finna.fi"><img src="<?=$this->imageLink('aalto.jpg')?>" alt="aalto.finna.fi screenshot" /></a>
            <p class="organisation-list-header">The Aalto University Library</p><p class="organisation-list-url"><a href="https://aalto.finna.fi">aalto.finna.fi</a></p>
          </div>
          <div class="col-xs-6 col-sm-3">
            <a href="https://hanken.finna.fi"><img src="<?=$this->imageLink('hanken.jpg')?>" alt="hanken.finna.fi screenshot" /></a>
            <p class="organisation-list-header">Hanken School of Economics Library</p><p class="organisation-list-url"><a href="https://hanken.finna.fi">hanken.finna.fi</a></p>
          </div>
        </div>
        <div class="row">
          <div class="col-xs-12 col-sm-11">
            <p><strong>The university of applied sciences and university library Finna sites</strong> contain international, scientific and electronic library material compiled and provided by an outsourced party for a fee. Most of this material is limited to students and staff at the institute of higher education in question. ovat maksullisia kirjastoille.</p>
            <p>&nbsp;</p>
          </div>
        </div>
      </div>
    </div>
    
  </div> <!-- close container -->
</div>  <!-- close container-fluid -->
<div class="container-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>Finna is much more than a search service</h2>
        <p>Through Finna, you can not only search for material, but also gain access to it. Currently, the following <strong>libraries</strong> provide functions for reserving material, renewing loans and other activities in Finna:</p>
        <? if (isset($loginTargets)): ?>
        <?= $this->partial('about_finna-login.phtml', ['loginTargets' => $loginTargets]) ?>
        <? endif ?>
        <p>After <a href="https://www.finna.fi/MyResearch/Home?lng=en-gb">logging in to Finna</a> these functions are available to you with a library card for the library in question.</p>
        <p>An application for browsing <strong>archive</strong> material, that requires permission to use, can be made through links found in Finna content data.</p>
        <p>In the future, digital <strong>museum</strong> services will also be available in Finna.</p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid odd-fluid">
  <div class="container">
    <div class="row">
      <div class="col-md-10 col-lg-8">
        <p>&nbsp;</p>
        <h2>About Finna</h2>
        <h4>User rights</h4>
        <p>Finna’s catalogue data are freely available, but statutory or contractual restrictions may apply to the digital images and back cover texts displayed in Finna, as well as to the digital content and metadata linked to in Finna. <a href="https://www.finna.fi/Content/terms_conditions?lng=en-gb#terms">Read more about user rights.</a></p>
        <h4>The Finna API</h4>
        <p>The open interface of the finna.fi service at <a href="https://api.finna.fi/">api.finna.fi</a> brings the metadata produced by participating libraries, archives and museums to the public. This interface also includes links to images and other material that is provided through the <a href="https://www.finna.fi/">finna.fi service</a>, but may be under use restrictions.</p>
        <h4>Development of Finna</h4>
        <p>Finna will be developed gradually as new organisations join the service. The beta version of the service was launched in December 2012 and the first official version in October 2013. If you cannot find the information that you are searching for in Finna, check back later to see if it has been added.</p>
        <h4>Organisations responsible for Finna</h4>
        <p>The National Library of Finland bears the main responsibility for developing and maintaining Finna, but the actual development work is carried out together with Finna partners. The <a href="https://www.finna.fi/Content/Organisations?lng=en-gb">archives, libraries and museums </a> involved in Finna are responsible for its content. Finna is part of the <a href="http://www.kdk.fi/en/information-on-the-project">National Digital Library (NDL) </a> project of the Ministry of Education and Culture.</p>
        <h4>Finna software</h4>
        <p>Finna has been constructed using VuFind and other open-source software, and its source code is freely available to all. <a href="http://www.kdk.fi/en/public-interface/software-development">Read more about the development of the software.</a></p>
        <p>&nbsp;</p>
      </div>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="container">
    <div class="row">
    <!-- open closed divs for valid HTML -->
<!-- END of: finna - content/about_finna_en-gb.phtml -->
