<!-- START of: finna - content/privacy_en-gb.phtml -->
<? $this->headTitle($this->translate('Privacy')); $this->content()->setHeading($this->translate('Privacy')); ?>

<div class="page-content">
  <h2>Management of personal information on Finna</h2>
  <p>When logging into Finna with a Finna ID, your username, name and email address are stored on Finna. When you log in with your library card, the service stores the number and PIN code of the card as well as your first and last name, email address and home library. When logging in using Haka, Finna automatically stores your username, name and email. This information is used for the following purposes:
  </p>
  <table class="content-table">
    <tr>
      <td><strong>Information</strong></td>
      <td><strong>Purpose</strong></td>
    </tr>
    <tr>
      <th>Username</th>
      <td>User authentication</td>
    </tr>
    <tr>
      <th>Email</th>
      <td>Default address for email, can be edited by the user on Finna</td>
    </tr>
    <tr>
      <th>First name</th>
      <td>User authentication and display of information</td>
    </tr>
    <tr>
      <th>Last name</th>
      <td>User authentication and display of information</td>
    </tr>
    <tr>
      <th>Library card number</th>
      <td>User authentication</td>
    </tr>
    <tr>
      <th>PIN code</th>
      <td>User authentication for service interfaces</td>
    </tr>
    <tr>
      <th>Home Library</th>
      <td>Default collection point for reservations, can be edited by the user on Finna</td>
    </tr>
  </table>
  <p>The email address stored on Finna is used only to send emails requested by the user, such as due date reminders and new entry alerts.
  </p>
  <p>In addition to the information mentioned above, Finna may store information about the user’s activities in Finna. Such information can include the language(s) used, the receiving of due date reminders and new entry alerts, records saved in your lists, library cards you have added, and social metadata (comments, reviews, keywords).
  </p>
  <p>Other services that require using personal information (e.g., browsing borrowed and reserved materials, as well as fees, making reservations and renewing loans) use the service interfaces of the library system, and do not store any information on Finna. This user information (including the postal address, phone number, validity period of the user account, borrowing blocks, checked out items, fines, holds and recalls) is retrieved in real-time for that specific action. Optional due date reminders are an exception. When a due date reminder is sent, the ID number and due date of the borrowed item are stored to ensure that the reminder is sent only once.
  </p>
  <p>Finna accounts created using a library card, the Finna ID, or the Haka username are separate from each other, even if they belong to the same person with the same email address.
  </p>
  <p>User information is collected and managed for service production by the National Library of Finland and the CSC – IT Center for Science (the service providers) and by the <a href="organisations">organizations</a> that share their collections on Finna regarding the user information of the organization's own customers. The information will not be disclosed to third parties. User information will be stored in the service until 12 months have passed from the last login.
  </p>
  <p>You can find more information about the management of personal information here: <a href="register_details"><?=$this->translate('Register Details') ?></a>
  </p>
</div>
<!-- END of: finna - content/privacy_en-gb.phtml -->
