<!-- START of: finna - content/privacy_sv.phtml -->
<? $this->headTitle($this->translate('Privacy')); $this->content()->setHeading($this->translate('Privacy')); ?>

<div class="row">
  <div class="col-sm-9 col-md-8 col-lg-6">
    <h2>Hantering av kunduppgifter i Finna</h2>
    <p>När användaren loggar in i Finna med sitt bibliotekskort sparas kortets nummer och pinkod, användarens för- och efternamn, e-postadress och hembibliotek i tjänsten. Vid Haka-inloggning sparas användarnamnet och användarens namn och e-postadress automatiskt i Finna. Om ma loggar in med Finna-konto sparas användarnamnet och användarens namn och e-postadress i Finna. Uppgifterna används för följande ändamål:
    </p>     
    <table class="content-table">
      <tr>
        <td><strong>Uppgift</strong></td>
        <td><strong>Ändamål</strong></td>
      </tr>
      <tr>
        <th>Bibliotekskortets nummer</th>
        <td>Identifierar användaren</td>
      </tr>
      <tr>
        <th>Användarnamnet</th>
        <td>Identifierar användaren</td>
      </tr>
      <tr>
        <th>Pinkoden</th>
        <td>Identifierar användaren i olika tjänstegränssnitt</td>
      </tr>
      <tr>
        <th>Förnamn</th>
        <td>Identifierar användaren och används för att visa information</td>
      </tr>
      <tr>
        <th>Efternamn</th>
        <td>Identifierar användaren och används för att visa information</td>
      </tr>
      <tr>
        <th>E-postaddress</th>
        <td>Den adress som i första hand används, användaren kan ändra uppgiften i Finna</td>
      </tr>
      <tr>
        <th>Hembibliotek</th>
        <td>Det ställe där beställningar i första hand avhämtas, användaren kan ändra uppgiften i Finna</td>
      </tr>
    </table>     
    <p>Till den e-postadress som sparas i Finna skickas bara sådana mejl som användaren själv önskar, t.ex. påminnelser om förfallodag och meddelanden från nyhetsbevakningen.
    </p>     
    <p>Förutom de ovan nämnda uppgifterna kan man också spara information om användarens aktiviteter i Finna. Sådan information är bl.a. språk, aktiverad påminnelse om förfallodag, nyhetsbevakningar, poster som användaren har sparat i egna listor, bibliotekskort som användaren själv lagt till och sociala metadata (kommentarer, recensioner, nyckelord).
    </p>     
    <p>För andra funktioner som hanterar användarnas uppgifter används bibliotekssystemets tjänstegränssnitt, t.ex. för funktioner som gäller reserveringar, lån och avgifter, och uppgifterna sparas inte i Finna, med undantag av de frivilliga påminnelserna om förfallodag. I samband med att en påminnelse om förfallodag skickas till användaren sparas id-numret och förfallodagen för lånet, detta för att varje påminnelse bara ska skickas en gång.
    </p>     
    <p>Finnakonton som skapas med bibliotekskorts-, Finna- eller Haka-koder är separata, även om de innehåller samma identifikationskod. Det finns en registerbeskrivning för hanteringen av användaruppgifter:
    </p>     
    <p>Det finns en <a href="register_details">registerbeskrivning</a> för hanteringen av användaruppgifter.
    </p>
  </div>
</div>
<!-- END of: finna - content/privacy_sv.phtml -->
