<!-- START of: finna - content/register_details_en-gb.phtml -->
<? $this->headTitle($this->translate('Register Details')); $this->content()->setHeading($this->translate('Register Details')); ?>

<div class="page-content">
  <h5>Data controller</h5>
  <ul class="list-plain">
    <li>National Library of Finland</li>
    <li>Library Network Services</li>
    <li>P.O. Box 26 (Kaikukatu 4)</li>
    <li>00014 University of Helsinki</li>
    <li>Phone: 09 1911</li>
  </ul>
  <h5>Data protection officer</h5>
  <ul class="list-plain">
    <li>Erkki Tolonen, Head of Development</li>
    <li>Library Network Services</li>
    <li>National Library of Finland</li>
    <li>P.O. Box 26 (Kaikukatu 4)</li>
    <li>00014 University of Helsinki</li>
    <li>Phone: 050 576 2869</li>
    <li>Email: erkki.tolonen(at)helsinki.fi</li>
  </ul>
  <h5>Data sources</h5>
  <p>Personal information is received from the registers of the users’ home organisations. For personalised functions, the information must be recorded and saved by the users themselves.
  </p>
  <h5>Disclosure of information</h5>
  <p>No information is disclosed to third parties.</p>

  <h5>Name of the register</h5>
  <p>User register for the Finna search portal</p>

  <h5>Purpose of the register</h5>
  <p>This register has been established to maintain the unambiguity of user identities.</p>

  <h5>Use of personal data</h5>
  <p>The register is used to identify users in order to enable personalised services, such as the new alerts service. The new alerts service sends an email to the user whenever new entries relating to any of their searches are added to the database.
  </p>
  <h5>Data types included in a user's file</h5>

  <h5>Basic user information</h5>
  <ul class="list-bullets">
    <li>Username</li>
    <li>Language</li>
    <li>Name</li>
    <li>Relationship to educational institution or other organisation</li>
    <li>Email</li>
    <li>Library card information</li>
  </ul>
  <h5>Data collected for personalised services</h5>
  <ul class="list-bullets">
    <li>Personal settings</li>
    <li>Favourites</li>
    <li>Tags</li>
    <li>Comments</li>
    <li>Reviews</li>
    <li>Reservations</li>
    <li>Loans</li>
    <li>Fees</li>
    <li>References added to bookshelf</li>
    <li>Material added to My materials</li>
    <li>Journal references added to My journals</li>
  </ul>
  <h5>Principles of data security</h5>
  <p>The information is recorded exclusively in an electronic format. Only system administrators, authenticated by username and password, may access the information.
  </p>
  <h5>Length of time personal information is stored</h5>
  <p>Personal information will be stored on the service for 12 months from the date of the last login.
  </p>
  <h5>Right to inspect the data file</h5>
  <p>Users may contact the data protection officer to review their personal information stored on the server.
  </p>
  <h5>Rectifying inaccurate information</h5>
  <p>If the information retrieved from the user’s home organisation is inaccurate, the user should contact the organisation in question. If necessary, the user may also contact the data protection officer.
  </p>
</div>
<!-- END of: finna - content/register_details_en-gb.phtml -->
