<!-- START of: finna - content/register_details_sv.phtml -->
<? $this->headTitle('Registerbeskrivning'); $this->content()->setHeading('Registerbeskrivning'); ?>

<div class="row">
 <div class="col-sm-9 col-md-8 col-lg-6">
     <h2>Registerbeskrivning för sökportalen Finnas kundregister</h2>
     
     <h5>Registeransvarig</h5>
     <ul class="list-plain">
        <li>Nationalbiblioteket</li>
        <li>Biblioteksnättjänster</li>
        <li>PB 26 (Ekogatan 4)</li>
        <li>00014 Helsingfors universitet</li>
        <li>Tfn 09 1911</li>
     </ul>

    <h5>Ansvarsperson för registerärenden</h5>
    <ul class="list-plain">
        <li>Erkki Tolonen, utvecklingschef</li>
        <li>Biblioteksnättjänster</li>
        <li>Nationalbiblioteket</li>
        <li>PB 26 (Ekogatan 4)</li>
        <li>00014 Helsingfors universitet</li>
        <li>Tfn 050 576 2869</li>
        <li>E-post: erkki.tolonen(at)helsinki.fi</li>
    </ul>

    <h5>Regelmässiga informationskällor</h5>
    <p> Personuppgifterna fås från kundernas hemorganisationers kundregister. Användarna sparar själva de uppgifter som behövs 
        för de individualiserade funktionerna. </p>

    <h5>Regelmässigt överlåtande av uppgifter</h5>      
    <p> Uppgifterna lämnas inte ut.</p>

    <h5>Registrets namn</h5>
    <p> Sökportalen Finnas kundregister.</p>

    <h5>Grund för förande av registret</h5>
    <p> Registret har grundats för att upprätthålla kunduppgifternas entydighet.</p>

    <h5>Registrets ändamål</h5>
    <p> Registret används för att identifiera användarna, i syfte att erbjuda dem individualiserade tjänster. Ett exempel på 
        individualiserade tjänster är sökbevakningstjänsten, som skickar kunden e-post om nya sökträffar.
    </p>

    <h5>Typ av uppgifter i registret</h5>
        
    <h5>Användarens basuppgifter</h5>
    <ul class="list-bullets">
        <li>Användarnamn</li>
        <li>Användarspråk</li>
        <li>Namn</li>
        <li>Relation till läroanstalten eller organisationen</li>
        <li>E-postadress</li>
        <li>Bibliotekskortens uppgifter</li>
    </ul> 
    
    <h5>Uppgifter som sparas för de individualiserade funktionerna</h5>
    <ul class="list-bullets">
        <li>Användarens personliga inställningar</li>
        <li>Favoriter</li> 
        <li>Taggar</li>
        <li>Kommentarer</li>
        <li>Recensioner</li>
        <li>Reservationer</li>
        <li>Lån</li>
        <li>Avgifter</li>
        <li>Referenser som sparats bokhyllan</li>
        <li>Material som sparats i Mitt material</li>
        <li>Tidskrifter som sparats i Mina tidskrifter</li>
     </ul>   
        
    <h5>Dataskyddsprinciper</h5>
    <p> Uppgifterna sparas endast i elektronisk form. Endast administratörerna, som identifieras med hjälp 
        av användarnamn och lösenord, har tillgång till uppgifterna.
    </p>

    <h5>Personuppgifternas förvaringstid</h5>
    <p> Personuppgifterna sparas i 12 månader efter den senaste inloggningen.</p>
    
    <h5>Rätt till insyn</h5>
    <p> Om en användare vill kontrollera vilka uppgifter om honom eller henne som har sparats i registret, 
        ska han eller hon ta kontakt med ansvarspersonen för registerärenden.
    </p>

    <h5>Korrigering av felaktiga uppgifter</h5>
    <p> Om de personuppgifter som överförts från hemorganisationen är felaktiga, ska användaren kontakta 
        sin hemorganisation. Vid behov kan användaren också kontakta ansvarspersonen för registerärenden.
    </p>
     
 </div>
 
</div>
<!-- END of: finna - content/register_details_sv.phtml -->
