<!-- START of: finna - content/terms_conditions.phtml -->
<? $this->headTitle($this->translate('Terms') . ' - ' . $this->translate('Privacy')); $this->content()->setHeading($this->translate('Terms') . ' - ' . $this->translate('Privacy')); ?>

<div class="page-content">
  <h3><a href="<?=$this->url('content-page', ['page' => 'terms'])?>"><?=$this->transEsc('Terms')?></a></h3>
  <h3><a href="<?=$this->url('content-page', ['page' => 'privacy'])?>"><?=$this->transEsc('Privacy')?></a></h3>
</div>

