<!-- START of: finna - RecordDriver/SolrLido/core.phtml -->
<? $this->headScript()->appendFile("finna-record.js"); ?>
<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-4">
    <div class="row">
      <div class="col-xs-12">
        <div class="cover-wrapper">
          <? /* Display thumbnail if appropriate: */ ?>
          <? $img = $this->recordImage($this->record($this->driver))?>
          <?= $img->render('record', array('small' => array('w' => 50, 'h' => 50), 'medium' => array('w' => 1200, 'h' => 1200))) ?>
          <? /* Display qrcode if appropriate: */ ?>
          <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
          <? if($QRCode): ?>
            <div class="visible-print inline-block"><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/></div>
          <? endif; ?>
        </div>
        <? // if you have a preview tab but want to move or remove the preview link
           // from this area of the record view, this can be split into
           // getPreviewData() (should stay here) and
           // getPreviewLink() (can go in your desired tab) ?>
        <?=$this->record($this->driver)->getPreviews()?>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12">
      <? $rights = $this->driver->getImageRights($this->layout()->userLang); ?>
        <div class="access-rights">
          <div class="image-rights">
            <? $hasLink = isset($rights['link']); ?>
            <strong><?= $this->translate("Image Rights") ?>:</strong> <? if (isset($rights['copyright'])) : ?><? if ($hasLink): ?><a target="_blank" href="<?= $rights['link'] ?>"><? endif; ?><?= $this->transEsc($rights['copyright']) ?><? if ($hasLink): ?></a><? endif ?><? endif ?>
          </div>
          <div class="copyright truncate-field">
            <? if (isset($rights['description'])): ?>
              <? foreach ($rights['description'] as $item): ?>
              <p><?= $this->transEsc($item) ?></p>
              <? endforeach ?>
            <? endif ?>
            <? if (!isset($rights['copyright']) && !isset($rights['description'])): ?>
              <p><?= $this->translate('Image Rights Default') ?>
              <p><a href="<?= $this->url('content-page', array('page' => 'terms_conditions')) . '#image_rights' ?>"><i class="fa fa-arrow-right"></i><?= $this->translate('See also terms and conditions') ?></a>
            <? endif; ?>
          </div>
        </div>
      </div>
    </div>

    <? if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
      <?=$this->render('record/record-organisation-menu.phtml') ?>
    <? endif; ?>

    <div class="row record-rating">
      <div class="col-xs-12 rating-stars">
        <div onclick="$('a.usercomments').click();">
          <?=$this->record($this->driver)->getRating()?>
        </div>
      </div>
    </div>

    <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-toolbar")): ?>
    <div class="row">
      <div class="col-xs-12">
        <div class="record-post-toolbar">
          <?=$this->render($template)?>
        </div>
      </div>
    </div>
    <? endif; ?>

  </div>

  <div class="col-sm-8 record-information">
    <h3 property="name" class="record-title"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>
    <? if ($results = $this->driver->getAlternativeTitles()): ?>
      <div class="recordAltTitles record-alt-titles">
        <?=implode('<br>', array_map(array($this, 'escapeHtml'), $results))?>
      </div>
    <? endif; ?>

    <div class="record-authors">
      <? if ($results = $this->driver->getNonPresenterAuthors()): ?>
        <div class="truncate-field">
          <? foreach($results as $index => $author): ?>
            <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?></a><? if (!empty($author['date'])): ?><span class="author-date">, <?=$this->escapeHtml($author['date']) ?></span><? endif; ?><? if (!empty($author['role'])): ?><span class="author-role">, <?=$this->escapeHtml($author['role']) ?></span><? endif; ?>
          <? endforeach; ?>
          <? if ($dates = $this->driver->getResultDateRange()): ?>
            <?=$this->escapeHtml($dates[0]);?><? if (isset($dates[1]) && $dates[1] != $dates[0]): ?>&ndash;<?=$this->escapeHtml($dates[1])?><? endif; ?>
          <? endif; ?>
          <? if ($results = $this->driver->getSubjectDates() && !isset($dates[0])): ?>
            <?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?>
          <? endif; ?>
        </div>
      <? endif; ?>
    </div>
    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
    <? if ($summary): ?>
      <div class="truncate-field wide recordSummary">
        <p class="summary"><?=preg_replace('/&lt;br\/?&gt;/', '<br>', $this->escapeHtml($summary)); /* Allow <br> tag */ ?></p>
      </div>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-finna-record record-details">
      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
      <tr class="recordFormat">
        <th><?=$this->transEsc('Format');?>:</th>
        <td><?=$this->record($this->driver)->getFormatList()?></td>
      </tr>
      <? endif; ?>
      <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <tr class="record-container-link">
        <th><?=$this->transEsc('Published in')?>:</th>
        <td>
          <?
            $containerSource = $this->driver->getSourceIdentifier();
            $containerID = $this->driver->getContainerRecordID();
          ?>
          <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
          <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
        </td>
      </tr>
      <? endif; ?>

      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr class="recordNextTitles">
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr class="recordPrevTitles">
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectDetails()): ?>
      <tr class="recordSubjects">
        <th><?=$this->transEsc('Subject Detail')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectPlaces()): ?>
      <tr class="recordSubjects">
        <th><?=$this->transEsc('Subject Place')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectDates()): ?>
      <tr class="recordSubjects">
        <th><?=$this->transEsc('Subject Date')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getSubjectActors()): ?>
      <tr class="recordSubjects">
        <th><?=$this->transEsc('Subject Actor')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getInstitutions()): ?>
      <tr class="recordInstitution">
        <th><?=$this->transEsc('Organisation')?>:</th>
        <td>
        <? foreach($results as $index => $institution): ?>
          <?=($index > 0 ? '<br/>' : '')?><?=$this->transEsc("source_$institution", array(), $this->translate($institution))?>
        <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getCollections()): ?>
      <tr class="recordCollection">
        <th><?=$this->transEsc('Collection')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getIdentifier()): ?>
      <tr class="recordIdentifier">
        <th><?=$this->transEsc('Inventory ID')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getMeasurements()): ?>
      <tr class="recordMeasurements">
        <th><?=$this->transEsc('Measurements')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getInscriptions()): ?>
      <tr class="recordInscriptions">
        <th><?=$this->transEsc('Inscriptions')?>:</th>
        <td><div class="truncate-field"><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></div></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getFormatClassifications()): ?>
      <tr class="recordClassifications">
        <th><?=$this->transEsc('Other Classification')?>:</th>
        <td><div class="truncate-field"><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></div></td>
      </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getLocalIdentifiers()): ?>
      <tr class="recordIdentifiers">
        <th><?=$this->transEsc('Other ID')?>:</th>
        <td><?=implode('<br/>', array_map(array($this, 'escapeHtml'), $results))?></td>
      </tr>
      <? endif; ?>

      <? $mainFormat = $this->driver->getMainFormat(); ?>
      <? foreach ($this->driver->getEvents() as $eventType => $events): ?>
      <tr class="recordEvents">
        <th><?=$this->transEsc("lido_event_type_{$mainFormat}_$eventType")?>:</th>
        <td>
          <div class="truncate-field">
          <? foreach ($events as $event): ?>
            <? if ($event != $events[0]): ?><br/><? endif; ?>
            <? if (!empty($event['name'])): ?><?=$this->escapeHtml($event['name'])?><br/><? endif; ?>
            <? if (!empty($event['date'])): ?><?=$this->escapeHtml($event['date'])?><br/><? elseif ($event['type'] != 'käyttö' && $event['type'] != 'näyttely'): ?> <?=$this->transEsc('undated')?><? endif; ?>
            <? if (!empty($event['method'])): ?><?=$this->escapeHtml($event['method'])?><br/><? endif; ?>
            <? if (!empty($event['materials'])): ?>
              <?=implode('<br/>', array_map(array($this, 'escapeHtml'), $event['materials']))?><br/>
            <? endif; ?>
            <? if (!empty($event['places'])): ?>
              <?=implode('<br/>', array_map(array($this, 'escapeHtml'), $event['places']))?><br/>
            <? endif; ?>
            <? if (!empty($event['culture'])): ?><?=$this->escapeHtml($event['culture'])?><br/><? endif; ?>
            <? if (!empty($event['actors'])): ?>
              <? foreach ($event['actors'] as $actor): ?>
                <?=$this->escapeHtml($actor['name'])?><? if (!empty($actor['role'])): ?>, <?=$this->escapeHtml($actor['role'])?><? endif; ?>
              <? endforeach; ?>
              <br/>
            <? endif; ?>
            <? if (!empty($event['description'])): ?><?=$this->escapeHtml($event['description'])?><br/><? endif; ?>
          <? endforeach; ?>
          </div>
        </td>
      </tr>
      <? endforeach; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr class="recordLanguage">
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->transEsc($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr class="recordEdition">
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr class="recordSeries">
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr class="recordSubjects">
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <div class="truncate-field" data-rows="5">
            <? foreach ($subjects as $field): ?>
            <div class="subjectLine" property="keywords">
              <? $subject = ''; ?>
              <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
              <? $i = 0; foreach ($field as $subfield): ?>
                <?=($i++ == 0) ? '' : ' &gt; '?>
                <? $subject = trim($subject . ' ' . $subfield); ?>
                <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
              <? endforeach; ?>
            </div>
            <? endforeach; ?>
          </div>
        </td>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->openUrl($this->driver, 'record');
        $openUrlActive = $openUrl->isActive();
        // Account for replace_other_urls setting
        $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
      ?>
      <? if (!empty($urls) || $openUrlActive): ?>
      <tr class="webResource">
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if(!empty($recordLinks)): ?>
        <tr class="extendedRelatedItems">
          <th><?=$this->transEsc('Related Items')?>:</th>
          <td>
            <? foreach ($recordLinks as $recordLink): ?>
              <?=$this->transEsc($recordLink['title'])?>:
              <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
            <? endforeach; ?>
            <? /* if we have record links, display relevant explanatory notes */
              $related = $this->driver->getRelationshipNotes();
              if (!empty($related)): ?>
                <? foreach ($related as $field): ?>
                  <?=$this->escapeHtml($field)?><br/>
                <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a class="tag-record" data-lightbox href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>, <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
    <? if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
    <div class="row">
      <div class="col-xs-12">
        <?=$this->render($template)?>
      </div>
    </div>
    <? endif; ?>
  </div>
</div>
<!-- END of: finna - RecordDriver/SolrLido/core.phtml -->
