<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?> <?php endif; ?>
<?php if (!empty($this->date)): ?>(<?=$this->escapeHtml($this->date)?>). <?php endif; ?>
<?=$this->escapeHtml($this->title)?><?php if ($this->periodAfterTitle): ?>.<?php endif ?>
 <i><?=$this->escapeHtml($this->journal)?><?php if (!empty($this->volume) || !empty($this->issue) || !empty($this->pageRange)): ?>, <?php endif; ?>
<?php if (!empty($this->volume)): ?><?=$this->escapeHtml($this->volume)?><?php endif; ?></i><?php if (!empty($this->issue)): ?>(<?=$this->escapeHtml($this->issue)?>)<?php endif; ?>
<?php if (!empty($this->volume) || !empty($this->issue)): ?>, <?php endif; ?>
<?=$this->escapeHtml($this->pageRange)?>. <?php if (isset($this->doi)): ?>https://doi.org/<?=$this->escapeHtml($this->doi)?><?php endif; ?>
