<? if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?> <? endif; ?>
<? if (!empty($this->date)): ?>(<?=$this->escapeHtml($this->date)?>). <? endif; ?>
<?=$this->escapeHtml($this->title)?><? if ($this->periodAfterTitle): ?>.<? endif ?> 
<span style="font-style:italic;"><?=$this->escapeHtml($this->journal)?><? if (!empty($this->volume) || !empty($this->issue) || !empty($this->pageRange)): ?>, <? endif; ?>
<? if (!empty($this->volume)): ?><?=$this->escapeHtml($this->volume)?><? endif; ?></span><? if (!empty($this->issue)): ?>(<?=$this->escapeHtml($this->issue)?>)<? endif; ?>
<? if (!empty($this->volume) || !empty($this->issue)): ?>, <? endif; ?>
<? if (!empty($this->pageRange)) echo strstr($this->pageRange, '-') ? 'pp. ' : 'p. '; ?>
<?=$this->escapeHtml($this->pageRange)?>. <? if (isset($this->doi)): ?>doi:<?=$this->escapeHtml($this->doi)?><? endif; ?>