<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?><?php endif; ?>
<?php if (!empty($this->year)): ?> (<?=$this->escapeHtml($this->year)?>). <?php endif; ?>
<i><?=$this->escapeHtml($this->title)?><?php if ($this->periodAfterTitle): ?>. <?php endif ?></i>
<?php if (!empty($this->edition)): ?>(<?=$this->escapeHtml($this->edition)?>). <?php endif; ?>
<?php if (!empty($this->publisher)): ?><?=$this->escapeHtml($this->publisher)?>. <?php endif; ?>
<?php if (!empty($this->doi)): ?>doi:<?=$this->escapeHtml($this->doi)?><?php endif; ?>
