<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>. <?php endif; ?>
&quot;<?=$this->title?><?php if ($this->periodAfterTitle): ?>.<?php endif ?>&quot;
<span style="font-style:italic;"><?=$this->escapeHtml($this->journal)?></span>
<?php if (!empty($this->numberAndDate)): ?><?=$this->escapeHtml($this->numberAndDate)?><?php if (!empty($this->pageRange)): ?>: <?php endif; ?><?php endif; ?>
<?php if ($this->labelPageRange && !empty($this->pageRange)) echo strstr($this->pageRange, '-') ? 'pp. ' : 'p. '; ?>
<?php if (!empty($this->pageRange)): ?><?=$this->escapeHtml($this->pageRange)?><?php endif; ?>.
<?php if (isset($this->doiPrefix) && !empty($this->doi)): ?> <?=$this->escapeHtml($this->doiPrefix . $this->doi)?>.<?php endif; ?>