<?php $hasDoi = isset($this->doiPrefix) && !empty($this->doi); ?>
<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>. <?php endif; ?>
&quot;<?=$this->title?><?php if ($this->periodAfterTitle): ?>.<?php endif ?>&quot;
<i><?=$this->escapeHtml($this->journal)?></i><?php if (!empty($this->numberAndDate)): ?><?=$this->escapeHtml($this->numberAndDate)?><?php if (!empty($this->pageRange)): ?><?=$this->escapeHtml($this->pageNumberSeparator)?> <?php endif; ?><?php endif; ?>
<?php
  if ($this->labelPageRange && !empty($this->pageRange)) {
    echo strstr($this->pageRange, '-') ? 'pp. ' : 'p. ';
  }
?>
<?php if (!empty($this->pageRange)): ?><?=$this->escapeHtml($this->pageRange)?><?php endif; ?><?=$hasDoi && $this->doiArticleComma ? ',' : '.'?>
<?php if ($hasDoi): ?> <?=$this->escapeHtml($this->doiPrefix . $this->doi)?>.<?php endif; ?>