<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>. <?php endif; ?>
&quot;<?=$this->title?><?php if ($this->periodAfterTitle): ?>.<?php endif ?>&quot;
<i><?=$this->escapeHtml($this->journal)?></i>
<?php if (!empty($this->numberAndDate)): ?>
  <?=$this->escapeHtml($this->numberAndDate)?>
  <?php if (!empty($this->pageRange)): ?>, <?php endif; ?>
<?php endif; ?>
<?php if (!empty($this->pageRange)): ?><?=$this->escapeHtml($this->pageRange)?><?php endif; ?>.
