<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>. <?php endif; ?>
<i><?=$this->escapeHtml($this->title)?></i><?php if ($this->periodAfterTitle): ?>. <?php endif ?>
<?php if (!empty($this->edition)): ?><?=$this->escapeHtml($this->edition)?> <?php endif; ?>
<?php if (!empty($this->publisher)): ?><?=$this->escapeHtml($this->publisher)?><?php endif; ?>
<?php if (!empty($this->year)): ?><?php if (!empty($this->publisher)): ?>, <?php endif; ?>
  <?=$this->escapeHtml($this->year)?>
<?php endif; ?>.
<?php if (!empty($this->doi)): ?>doi:<?=$this->escapeHtml($this->doi)?>.<?php endif; ?>
