<!-- START of: finna - search/controls/sort.phtml -->
<?php $list = $this->sortList ? $this->sortList : $this->params->getSortList(); if (!empty($list)): ?>
<div class="sort-option-container">
  <span class="hidden-sm hidden-xs hidden-md button-label"><?=$this->transEsc('Sort')?></span>
  <span class="sr-only hidden-lg hidden-md"><?=$this->transEsc('Sort')?></span>
  <div class="sort-button">
  <div class="dropdown">
    <?php $selectedFound = false; ?>
    <?php foreach ($list as $sortType => $sortData): ?>
      <?php if ($sortData['selected']): ?>
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <span><?=$this->transEsc($sortData['desc'])?></span> <i class="fa fa-arrow-down"></i>
        </a>
        <?php $selectedFound = true; ?>
      <?php endif; ?>
    <?php endforeach; ?>
    <?php if (!$selectedFound): ?>
      <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <span><?=$this->transEsc('choose_from_list')?></span> <i class="fa fa-arrow-down"></i>
      </a>
    <?php endif; ?>
    <ul class="dropdown-menu" role="menu">
      <?php foreach ($list as $sortType => $sortData): ?>
      <li role="menuitem">
        <a href="<?=isset($sortData['url']) ? $this->escapeHtmlAttr($sortData['url']) : $this->results->getUrlQuery()->setSort($sortType)?>"><?=$this->transEsc($sortData['desc'])?></a>
      <?php endforeach; ?>
      </li>
    </ul>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEsc("Set")?>" /></noscript>
  </div>
  </div>
</div>
<?php endif; ?>
<!-- END of: finna - search/controls/sort.phtml -->
