<!-- START of: finna - myresearch/payment/terms-turkupaymentapi.phtml -->
<img class="terms-of-service-logo" src="<?=$this->imageLink('online-payment-vaski.png')?>" alt="CPU">
<div class="terms-of-service">
  <div class="terms-of-service__text">
    <?= $this->translate('online_payment_terms_TurkuPayment_html', ['%%paymentHandler%%' => $this->escapeHtml($paymentHandler)]) ?>
  </div>
</div>
<!-- END of: finna - myresearch/payment/terms-turkupaymentapi.phtml -->
