<h1>Etiketmele</h1>

<p>
Bir etiket, bir bilgi parçası (resim, yazı veya video klibi gibi) ile ilgili ya da atanmış olan, böylelikle materyali açıklayan ve uygulanan bilgilerin anahtar kelime tabanlı sınıflandırılmasını sağlayan ilişkili bir anahtar kelime ya da terimdir.
</p>

<p>
Etiketler genellikle materyalin yazarı/oluşturucusu tarafından gayri resmi ve şahsen seçilir. Yani genellikle bazen biçimsel olarak tanımlanmış sınıflandırma düzeninin bir parçası olarak değil.  Etiketler genellikle bilgisayar dosyaları, web sayfaları, dijital görüntüler ve internet yer imleri (hem sosyal imleme servisleri hem de yeni nesil tarayıcılar içerisinde bkz. Flock) gibi çevrim içi kaynaklar için dinamik, esnek, otomatik olarak oluşturulan internet sınıflandırmalarında kullanılır. Bu nedenle etiketleme, Web 2.0 buzz ile ilişkili olmuştur.
</p>

<p>
Genellikle, bir materyalin bazı sınıflandırma yazılımı veya sisteminin bir parçası olarak kendisi ile ilişkili birden fazla &quot;etiketlemeleri&quot; olacaktır. Yazılım, anahtar kelime etiketlerini paylaşan diğer materyallere hatta belirtilen bir etiket topluluğuna bağlantı sağlayacaktır. Bu, materyaller içerisinde koleksiyonun yöneticisi tarafından en az çaba ve planlama ile değiştirilmesi ve materyallerin birden fazla tarama yöntemi ile taranması imkânı vermesini sağlar. </p>

<a href="http://en.wikipedia.org/wiki/Tag_%28metadata%29">Wikipedia'dan</a>