<?php if(!empty($uploadInfos)): ?>
  <div class="col-md-12 ix-panel-news tf-rss-block">
    <div class="panel panel-default">
        <div class="panel-heading">
            <h4 class="panel-title color-red">
                 Upload Info
            </h4>
        </div>
        <div class="panel-collapse">
            <div class="panel-body">
              <?php foreach($uploadInfos as $info):?>
                <p class="<?=$info[1];?>" >
                  <?=$info[0];?>
                </p>
              <?php endforeach;?>
            </div>
        </div>
    </div>
  </div>
<?php endif;?>




<h3>Upload new publication</h3>

<h4>Publication title: <?=$this->dublinCore['DC.title'][0]?> </h4>
<?php /* DSpace needs Dublin Core metadata as minimum: https://www.dublincore.org/specifications/dublin-core/dces/ */ ?>

<form method="post" enctype="multipart/form-data">
  <!-- DC.creator -->
  <div class="form-group">
    <label>creator</label>
    <select class="form-control" name="creator" required>
      <?php foreach ($this->userAuthorities as $userAuthority): ?>
        <?php $authorityRecord = $this->authorityRecords[$userAuthority['authority_id']]?>
        <option value="<?=$authorityRecord->getGNDNumber()?>"><?=htmlspecialchars($authorityRecord->getTitle() . ' (GND: ' .  $authorityRecord->getGNDNumber() . ')')?></option>
      <?php endforeach; ?>
    </select>
  </div>

  <!-- File -->
  <div class="form-group">
    <label>file</label>
    <input class="form-control" type="file" name="file" required>
  </div>
  <div>
    <label><a href="/publication_terms/<?=urlencode($termFile['fileName'])?>" target="_blank"><?=htmlspecialchars($termFile['fileName'])?></a></label>
  </div>
  <div class="form-group">
    <label>term agree</label>
    <input type="checkbox" value="term" name="term" required="required">
  </div>
  <button type="submit" class="btn btn-primary" name="action" value="publish">Submit</button>
</form>
