<?php
// Set up page title:
$this->headTitle($this->translate('Publications'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Publications') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>Publications</h2>
  <?php if (count($this->authorityRecords) == 0): ?>
    <p>You do not have access to any authority records yet. Please search for an authority record first and request access there.</p>
  <?php else: ?>
    <p>If you like to publish something, please search for the matching record which is linked to your authority entry and use the "publish" button in the full view.</p>
    <?php if (count($this->publications) == 0): ?>
      <p>You did not upload any publications so far.</p>
    <?php else: ?>
      <p>Details are queried live from our external publication repository:</p>
      <table class="table">
        <tr>
          <th>ID in external repository</th>
          <th>Title</th>
          <th>Dspace file</th>
          <th>Created</th>
          <th>Terms Date</th>
        </tr>
        <?php foreach ($this->publications as $publication): ?>
          <tr>
            <td><?=$publication['external_document_id']?></td>
            <td><a href="<?=$this->recordLink()->getUrl($publication['control_number'])?>"><?=$publication['title'];?></a></td>
            <td><a href="<?=$this->dspaceServer;?>/items/<?=$publication['external_document_guid']?>" target="_blank"><i class="fa fa-external-link"></i> Go to file</a></td>
            <td><?=date("d.m.Y H:i:s",strtotime($publication['publication_datetime']));?></td>
            <td><?=date("d.m.Y",strtotime($publication['terms_date']));?></td>
          </tr>
        <?php endforeach; ?>
      </table>
    <?php endif; ?>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'publications'])?>
</div>
