<?php
    $subscribedFeedIds = [];
    foreach ($rssSubscriptions as $rssSubscription) {
        $subscribedFeedIds[] = $rssSubscription['rss_feeds_id'];
    }
?>

<div class="mainbody left">
  <h2><?=$this->transEsc('RSS feeds')?></h2>
  <table class="search-history-table">
    <tr>
      <th><?=$this->transEsc('RSS feed')?></th>
      <th><?=$this->transEsc('Subscribe')?></th>
    </tr>
    <?php foreach($rssFeeds as $rssFeed): ?>
      <tr>
        <td><a href="<?=$rssFeed['website_url']?>" target="_blank"><?=$rssFeed['feed_name']?></a></td>
        <td>
          <label class="switch">
            <?php if (in_array($rssFeed['id'], $subscribedFeedIds)): ?>
              <input type="checkbox" checked class="rssLabel" data-id="<?=$rssFeed['id']?>">
            <?php else: ?>
              <input type="checkbox" class="rssLabel" data-id="<?=$rssFeed['id']?>">
            <?php endif; ?>
            <span class="slider round"></span>
          </label>
        </td>
      </tr>
    <?php endforeach; ?>
  </table>


  <p><a href="<?=$this->url('myresearch-rssfeedpreview')?>"><?=$this->transEsc('Show personal RSS feed')?></a></p>
  <p>
    <form method="post">
      <?=$this->transEsc('rss_subscribe_email')?>
      <label class="switch" onclick="this.form.submit()">
        <?php if ($this->user->tuefind_rss_feed_send_emails): ?>
          <input type="hidden" name="action" value="unsubscribe_email">
          <input type="checkbox" checked>
        <?php else: ?>
          <input type="hidden" name="action" value="subscribe_email">
          <input type="checkbox">
        <?php endif; ?>
        <span class="slider round"></span>
      </label>

      <?php if ($this->user->tuefind_rss_feed_send_emails): ?>
        <br><?=$this->transEsc('rss_email_min_timestamp')?> <?=$this->user->tuefind_rss_feed_last_notification?>.
      <?php endif; ?>
    </form>
  </p>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext(
       "myresearch/menu.phtml", ['active' => 'rssFeedSettings']
   );?>
</div>
