<?php
    // Set up convenience variables:
    $account = $this->auth()->getManager();
    $user = $account->isLoggedIn();
    $openUrl = $this->openUrl($this->driver, 'holdings');
    $openUrlActive = $openUrl->isActive();
    $doi = $this->doi($this->driver, 'holdings');
    $doiActive = $doi->isActive();
    // Account for replace_other_urls setting
    $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
    $offlineMode = $this->ils()->getOfflineMode();
    try {
        $holdings = $this->driver->getRealTimeHoldings();
    } catch (\VuFind\Exception\ILS $e) {
        $holdings = [
          'holdings' => [],
          'electronic_holdings' => [],
          'total' => 0,
          'page' => 0,
          'itemLimit' => 0
        ];
        $offlineMode = 'ils-offline';
    }
    // Set page title.
    $this->headTitle($this->translate('Holdings') . ': ' . $this->driver->getBreadcrumb());

    $purchaseFields = $this->driver->getMarcRecord()->getFields("852");
    $pFieldCount = count($purchaseFields);
    $purchaseDetails = new stdClass();
    $purchaseDetails->isActive = false;

    if (count($holdings['holdings']) == 0) {
      if ($pFieldCount > 0) {
        $purchaseCode = $purchaseFields[0]->getSubField("b")->getData();
        $purchaseText = $purchaseFields[0]->getSubField("z")->getData();
        if ($purchaseCode && $purchaseText) {
          $purchaseDetails->isActive = true;
          $purchaseDetails->code = $purchaseCode;
          $purchaseDetails->text = $purchaseText;
        }
      }
    }
?>

<?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

<?php if (!empty($holdings['blocks'])):?>
  <div id="account-block-msg" class="alert alert-danger">
    <?=$this->transEsc('account_block_options_missing', ['%%details%%' => implode('; ', $holdings['blocks'])]) ?>
  </div>
<?php endif; ?>

<?=($offlineMode == "ils-offline") ? $this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message']) : ''?>

<?php if (($this->ils()->getHoldsMode() == 'driver' && !empty($holdings['holdings'])) || $this->ils()->getTitleHoldsMode() == 'driver'): ?>
  <?php if ($account->loginEnabled() && $offlineMode != 'ils-offline'): ?>
    <?php if (!$user): ?>
      <div class="alert alert-info">
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Holdings', ['login' => 'true', 'catalogLogin' => 'true']))?>" data-lightbox><?=$this->transEsc("hold_login")?></a>
      </div>
    <?php elseif (!$user->cat_username): ?>
      <div class="alert alert-info">
        <?=$this->translate("hold_profile_html", ['%%url%%' => $this->escapeHtmlAttr($this->recordLinker()->getTabUrl($this->driver, 'Holdings', ['catalogLogin' => 'true']))])?>
      </div>
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<?php $holdingTitleHold = $this->driver->tryMethod('getRealTimeTitleHold'); if (!empty($holdingTitleHold)): ?>
  <a class="placehold" data-lightbox title="<?=$this->transEscAttr('request_place_text')?>" href="<?=$this->escapeHtmlAttr($this->recordLinker()->getRequestUrl($holdingTitleHold))?>"><i class="fa fa-flag" aria-hidden="true"></i>&nbsp;<?=$this->transEsc('title_hold_place')?></a>
<?php endif; ?>
<?php if (!empty($urls) || $openUrlActive || $doiActive): ?>
  <h3><?=$this->transEsc("Internet")?></h3>
  <?php if (!empty($urls)): ?>
    <?php foreach ($urls as $current): ?>
      <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
    <?php endforeach; ?>
  <?php endif; ?>
  <?php if ($openUrlActive): ?><?=$openUrl->renderTemplate()?><?php endif; ?>
  <?php if ($doiActive): ?><?=$doi->renderTemplate()?><?php endif; ?>
<?php endif; ?>

<?php if (!empty($holdings['electronic_holdings'])): ?>
  <?=
    $this->context($this)->renderInContext(
        'RecordTab/holdingsils/electronic.phtml',
        ['holdings' => $holdings['electronic_holdings']]
    );
  ?>
<?php endif; ?>

<?php
  if ($purchaseDetails->isActive) {
?>
  <h3>Purchase Details</h3>
  <table class="table table-striped">
    <caption class="sr-only">Purchase Details</caption>
    <tr>
      <td>
        <?=$purchaseDetails->text?>
      </td>
      <td class="getit" id="getit_purchase"></td>
    </tr>
  </table>
<?php
  }
?>

<?php foreach ($holdings['holdings'] ?? [] as $holding): ?>

<?php
$sort_holding_id = array_column( $holding['items'], "holding_id" );
$sort_enumeration_id = array_column( $holding['items'], "enumeration" );
array_multisort($sort_holding_id, SORT_DESC, $sort_enumeration_id, SORT_ASC, SORT_NATURAL, $holding['items']);

?>
<h3>
  <?php $locationTextEsc = $this->transEscWithPrefix('location_', $holding['location']); ?>
  <?php if ($holding['locationhref'] ?? false): ?>
    <a href="<?=$this->escapeHtmlAttr($holding['locationhref'])?>" target="_blank"><?=$locationTextEsc?></a>
  <?php else: ?>
    <?=$locationTextEsc?>
  <?php endif; ?>
</h3>
<table class="table table-striped">
  <caption class="sr-only"><?=$this->transEsc('holdings_details_from', ['%%location%%' => $this->transEsc($holding['location'])]) ?></caption>
  <?php $callNos = $this->tab->getUniqueCallNumbers($holding['items']); if (!empty($callNos)): ?>
  <tr>
    <th colspan="2"><?=$this->transEsc("Call Number")?>: </th>
    <td width="50%">
      <?php foreach ($callNos as $callNo): ?>
        <?php if ($this->callnumberHandler): ?>
          <a href="<?=$this->url('alphabrowse-home') ?>?source=<?=$this->escapeHtmlAttr($this->callnumberHandler) ?>&amp;from=<?=$this->escapeHtmlAttr($callNo) ?>"><?=$this->escapeHtml($callNo)?></a>
        <?php else: ?>
          <?=$this->escapeHtml($callNo)?>
        <?php endif; ?>
        <br />
      <?php endforeach; ?>
    </td>
  </tr>
  <?php endif; ?>
  <?php foreach ($holding['textfields'] ?? [] as $textFieldName => $textFields): ?>
    <tr>
      <?php // Translation for summary is a special case for backwards-compatibility ?>
      <th><?=$textFieldName == 'summary' ? $this->transEsc("Volume Holdings") : $this->transEsc(ucfirst($textFieldName))?>:</th>
      <td>
        <?php foreach ($textFields as $current): ?>
          <?=$this->linkify($this->escapeHtml($current))?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endforeach; ?>

  <?php
    $hold_id = "";
    $tmp_hold_id = "";
    $hold_count = 0;
    $i = 0;
  ?>

  <?php foreach ($holding['items'] as $item): ?>
  <?php $hold_id = $item['holding_id']; ?>
  <?php

    if ($tmp_hold_id != $hold_id) {
  ?>
        <tr vocab="http://schema.org/" typeof="Offer">
          <th colspan="2">
  <?php
      if ($item['issues'][0] ?? false) {
  ?>
            <span>Library Owns</span>
  <?php
      } else {
  ?>
            <span>&nbsp;</span>
  <?php
      }
  ?>
          </th>
          <td>
  <?php
      if ($item['issues'][0] ?? false) {
  ?>
            <span class="holding_note">&nbsp;&nbsp;(<?=$this->escapeHtml($item['issues'][0])?>)</span>
  <?php
      }
  ?>
          </td>
        </tr>
  <?php
      $tmp_hold_id = $hold_id;
      $hold_count = $hold_count + 1;
    }
   ?>
    <?php
        try {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/' . $this->tab->getTemplate() . '.phtml',
                ['item' => $item, 'i'=>$i]
            );
        } catch (Exception $e) {
            echo $this->context($this)->renderInContext(
                'RecordTab/holdingsils/standard.phtml',
                ['item' => $item, 'i'=>$i]
            );
        }
        $i++;
    ?>





  <?php endforeach; ?>
  <?php if (!empty($holding['purchase_history'])): ?>
    <tr>
      <th><?=$this->transEsc("Most Recent Received Issues")?>:</th>
      <td>
        <?php foreach ($holding['purchase_history'] as $current): ?>
          <?=$this->escapeHtml($current['issue'])?><br/>
        <?php endforeach; ?>
      </td>
    </tr>
  <?php endif; ?>
</table>
<?php endforeach; ?>
<?php if (!empty($holdings['total']) && $paginator = $this->tab->getPaginator($holdings['total'], $holdings['page'], $holdings['itemLimit'])): ?>
  <?=$this->paginationControl($paginator, 'Sliding', 'Helpers/pagination.phtml', ['page' => $holdings['page']])?>
<?php endif; ?>
<?php $history = $this->driver->getRealTimeHistory(); ?>
<?php if (is_array($history) && !empty($history)): ?>
  <h3><?=$this->transEsc("Most Recent Received Issues")?></h3>
  <table class="table table-striped">
    <?php foreach ($history as $row): ?>
      <tr><td><?=$this->escapeHtml($row['issue'])?></td></tr>
    <?php endforeach; ?>
  </table>
<?php endif; ?>
