<?php
    $this->layout()->breadcrumbs = false;
    $this->backgroundTabs = $this->BackgroundTabs ?? [];
    $schemaOrgType = $this->authority()->getSchemaOrgType($this->driver);
?>
<div vocab="http://schema.org/" typeof="<?=$schemaOrgType?>">
  <h3 property="name"><?=$this->authority()->getName($this->driver)?></h3>
  <div class="row">
    <div class="col-sm-8">
      <table class="table table-striped">
        <tbody>
          <?php $occupations = $this->authority()->getOccupations($this->driver);?>
          <?php if ($occupations != ''): ?>
            <tr>
              <th>Occupations:</th>
              <td><?=$occupations?></td>
            </tr>
          <?php endif; ?>

          <?php $birth = $this->authority()->getBirth($this->driver); ?>
          <?php if ($birth != ''): ?>
            <tr>
              <th>Born:</th>
              <td><?=$birth?></td>
            </tr>
          <?php endif; ?>

          <?php $death = $this->authority()->getDeath($this->driver); ?>
          <?php if ($death != ''): ?>
            <tr>
              <th>Died:</th>
              <td><?=$death?></td>
            </tr>
          <?php endif; ?>

          <?php $externalReferences = $this->authority()->getExternalReferences($this->driver); ?>
          <?php if ($externalReferences != ''): ?>
            <tr>
              <th>External references:</th>
              <td><?=$externalReferences?></td>
            </tr>
          <?php endif; ?>

          <?php $relations = $this->authority()->getRelations($this->driver); ?>
          <?php if ($relations != ''): ?>
            <tr>
              <th>Relations:</th>
              <td><?=$relations?></td>
            </tr>
          <?php endif; ?>
        </tbody>
      </table>
      <?=$this->context($this)->renderInContext('related/AuthorityTitles', ['driver' => $this->driver])?>
    </div>
    <div class="col-sm-4">
      <?php
        // Image (partially rendered by JS)
        $imgUrl = '/wikidataproxy/load';
        $wikidataId = $this->driver->getWikidataId();
        if ($wikidataId != null) {
          $imgUrl .= '?id=' . $wikidataId;
        } else {
          $imgUrl .= '?search[]=';
          $names = $this->driver->getNameAliases();
          $encodedNames = [];
          foreach ($names as $name) {
            $encodedNames[] = urlencode($name);
          }
          $imgUrl .= implode('&search[]=', $encodedNames);
          $params = ['birthYear' => $this->driver->getBirthYear(),
                     'deathYear' => $this->driver->getDeathYear()];
          foreach ($params as $key => $value) {
            if ($value)
              $imgUrl .= '&' . urlencode($key) . '=' . urlencode($value);
          }
        }
      ?>
      <!-- onload didn't work, so we use a separate script snippet -->
      <div class="tf-wikidata-image" data-url="<?=htmlspecialchars($imgUrl)?>"></div>
      <script>TueFind.GetImagesFromWikidata();</script>
    </div>
  </div>
</div>

<?php
  // Pick a tab to display -- Details if available, otherwise first option (if any):
  $tab = $this->tabs['Details'] ?? current($this->tabs) ?? null;
?>
<h3><?=$this->escapeHtml($this->driver->getBreadcrumb())?></h3>
<p><?=empty($tab) ? $this->transEsc('no_description') :  $this->record($this->driver)->getTab($tab)?></p>
