<?php
    $this->layout()->breadcrumbs = false;
    $this->backgroundTabs = $this->BackgroundTabs ?? [];
    $schemaOrgType = $this->authority()->getSchemaOrgType($this->driver);

    // TueFind:
    // - record.js is needed for AJAX tab logic
    // - disabled, because we use the non-ajax-version.
    // - see also "recordDocReady" at the bottom of this file.
    //$this->headScript()->appendFile("record.js");
?>

<?php /* User Authority Access */ ?>
<?php if ($this->user != false && $this->accountCapabilities()->getRequestAuthorityRightsSetting() === 'enabled'): ?>
  <div>
    <?php if ($this->user_access['availability'] == 'free'): ?>
      <a class="save-record toolbar-btn btn-type-save rel="nofollow" href="<?=$this->url('authority-request-access', ['authority_id' => $this->driver->getUniqueId()])?>" data-lightbox="">Request access rights (This is me!)</a>
    <?php elseif ($this->user_access['availability'] == 'mine' && $this->user_access['access_state'] == 'requested'): ?>
      You have requested permission on this authority record. Our team has been informed, please wait for the approval.
    <?php elseif ($this->user_access['availability'] == 'mine' && $this->user_access['access_state'] == 'granted'): ?>
      This authority record is linked to your user account.
      <?php if ($this->user != false && $this->accountCapabilities()->getPublicationSetting() === 'enabled'): ?>
        <br><a href="<?=$this->url('myresearch-publish')?>">Would you like to publish something?</a>
      <?php endif; ?>
    <?php endif; ?>
  </div>
<?php endif; ?>

<?php /* Record details */ ?>
<div vocab="http://schema.org/" typeof="<?=$schemaOrgType?>">
  <h3><?=$this->authority()->getName($this->driver)?></h3>
  <div class="row">
    <div class="col-sm-8">
      <table class="table table-striped">
        <tbody>
          <?php $occupations = $this->authority()->getOccupations($this->driver);?>
          <?php if ($occupations != ''): ?>
            <tr>
              <th>Occupations:</th>
              <td><?=$occupations?></td>
            </tr>
          <?php endif; ?>

          <?php $birth = $this->authority()->getBirth($this->driver); ?>
          <?php if ($birth != ''): ?>
            <tr>
              <th>Born:</th>
              <td><?=$birth?></td>
            </tr>
          <?php endif; ?>

          <?php $death = $this->authority()->getDeath($this->driver); ?>
          <?php if ($death != ''): ?>
            <tr>
              <th>Died:</th>
              <td><?=$death?></td>
            </tr>
          <?php endif; ?>

          <?php $relations = $this->authority()->getPersonalRelations($this->driver); ?>
          <?php if ($relations != ''): ?>
            <tr>
              <th>Personal relations:</th>
              <td><?=$relations?></td>
            </tr>
          <?php endif; ?>

          <?php $relations = $this->authority()->getCorporateRelations($this->driver); ?>
          <?php if ($relations != ''): ?>
            <tr>
              <th>Corporate relations:</th>
              <td><?=$relations?></td>
            </tr>
          <?php endif; ?>

          <?php $externalReferences = $this->authority()->getExternalReferences($this->driver); ?>
          <?php if ($externalReferences != ''): ?>
            <tr>
              <th>External references:</th>
              <td><?=$externalReferences?></td>
            </tr>
          <?php endif; ?>
        </tbody>
      </table>
      <?=$this->context($this)->renderInContext('Related/AuthorityTitlesFrom', ['driver' => $this->driver])?>
      <?=$this->context($this)->renderInContext('Related/AuthorityTitlesAbout', ['driver' => $this->driver])?>
      <?=$this->context($this)->renderInContext('Related/AuthorityAuthors', ['driver' => $this->driver])?>
    </div>
    <?php if ($this->driver->getType() == 'person' && !in_array('Familie', $this->driver->getPersonalTitles())): ?>
      <div class="col-sm-4">
        <?php
          // Image (partially rendered by JS)
          $imgUrl = '/wikidataproxy/load';
          $wikidataId = $this->driver->getWikidataId();
          if ($wikidataId != null) {
            $imgUrl .= '?id=' . $wikidataId;
          } else {
            $imgUrl .= '?search[]=';
            $names = $this->driver->getNameAliases();
            $encodedNames = [];
            foreach ($names as $name) {
              $encodedNames[] = urlencode($name);
            }
            $imgUrl .= implode('&search[]=', $encodedNames);
            $params = ['birthYear' => $this->driver->getBirthYear(),
                       'deathYear' => $this->driver->getDeathYear()];
            foreach ($params as $key => $value) {
              if ($value)
                $imgUrl .= '&' . urlencode($key) . '=' . urlencode($value);
            }
          }
        ?>
        <!-- onload didn't work, so we use a separate script snippet -->
        <div class="tf-wikidata-image" data-url="<?=htmlspecialchars($imgUrl)?>"></div>
        <script>TueFind.GetImagesFromWikidata();</script>
      </div>
    <?php endif; ?>
  </div>
</div>

<?php
  // Pick a tab to display -- Details if available, otherwise first option (if any):
  $tab = $this->tabs['Details'] ?? current($this->tabs) ?? null;
?>

<?php /* TueFind: Use similar tab logic as for title data (without AJAX!)*/?>
<div class="record-tabs">
  <ul class="nav nav-tabs">
    <?php foreach ($this->tabs as $tab => $obj): ?>
      <?php // add current tab to breadcrumbs if applicable:
        $desc = $obj->getDescription();
        $tabName = preg_replace("/\W/", "-", strtolower($tab));
        $tabClasses = [ 'record-tab', $tabName ];

        if (!isset($this->activeTab) || !$this->activeTab)
          $this->activeTab = $tab;

        if (0 === strcasecmp($this->activeTab, $tab)) {
          if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
            $tabClasses[] = 'active';
          }
          $tabClasses[] = 'initiallyActive';
          $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
          $activeTabObj = $obj;
        }
        if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
        if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
      ?>
      <li class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$tabName?>"<?php if ($obj->supportsAjax() && in_array($tab, $this->backgroundTabs)):?> data-background<?php endif ?>>
        <a href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
      </li>
    <?php endforeach; ?>
  </ul>

  <div class="tab-content">
    <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
      <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
        <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
      </div>
    <?php endif; ?>
  </div>
</div>

<?php
  // TueFind:
  // - recordDocReady is needed for AJAX tab logic
  // - disabled, because we use the non-ajax-version.
  // - see also "record.js" at the top of this file.
  // print $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(document).ready(recordDocReady);', 'SET');
?>
