<?php
    $this->layout()->breadcrumbs = false;
?>
<div vocab="http://schema.org/">
  <h1><?=$this->authority()->getName($this->driver)?></h1>
  <div class="row">
    <div class="col-sm-8">
      <p>
        <?php $professions = $this->authority()->getProfessions($this->driver);?>
        <?php if ($professions != ''): ?>
          <?=$professions?>
        <?php endif; ?>

        <?php $birth = $this->authority()->getBirth($this->driver); ?>
        <?php if ($birth != ''): ?>
          <br/><?=$birth?>
        <?php endif; ?>

        <?php $death = $this->authority()->getDeath($this->driver); ?>
        <?php if ($death != ''): ?>
          <br/><?=$death?>
        <?php endif; ?>
      </p>
      <?=$this->context($this)->renderInContext('related/AuthorityTitles', ['driver' => $this->driver])?>
    </div>
    <div class="col-sm-4">
      <?php
        // Image (partially rendered by JS)
        $imgUrl = '/wikidataproxy/load?search[]=';
        $names = $this->driver->getNameAliases();
        $encodedNames = [];
        foreach ($names as $name) {
            $encodedNames[] = urlencode($name);
        }
        $imgUrl .= implode('&search[]=', $encodedNames);
        $params = ['birthYear' => $this->driver->getBirthYear(),
                   'deathYear' => $this->driver->getDeathYear()];
        foreach ($params as $key => $value) {
          if ($value)
            $imgUrl .= '&' . urlencode($key) . '=' . urlencode($value);
        }
      ?>
      <!-- onload didn't work, so we use a separate script snippet -->
      <div class="tf-wikidata-image" data-url="<?=htmlspecialchars($imgUrl)?>"></div>
      <script>TueFind.GetImagesFromWikidata();</script>

      <?php
        // External links
        $links = [];

        $orcid = $this->driver->getORCID();
        if ($orcid != null)
            $links['ORCID - Open Researcher and Contributor Identifier'] = '//orcid.org/' . urlencode($orcid);

        $isni = $this->driver->getISNI();
        if ($isni != null)
            $links['ISNI - International Standard Name Identifier'] = '//www.isni.org/' . urlencode($isni);

        $viaf = $this->driver->getVIAF();
        if ($viaf != null)
            $links['VIAF - Virtual International Authority File'] = '//viaf.org/viaf/' . urlencode($viaf);

        $lccn = $this->driver->getLCCN();
        if ($lccn != null)
            $links['LOC - Library Of Congress (NACO)'] = '//lccn.loc.gov/' . urlencode($lccn);

        $gnd_number = $this->driver->getGNDNumber();
        if ($gnd_number != null) {
            $links['DDB - Deutsche Digitale Bibliothek'] = '//www.deutsche-digitale-bibliothek.de/entity/' . urlencode($gnd_number);
            $links['GND - Gemeinsame Normdatei'] = '//swb.bsz-bw.de/DB=2.104/SET=3/TTL=1/CMD?retrace=0&trm_old=&ACT=SRCHA&IKT=2999&SRT=RLV&MATCFILTER=N&MATCSET=N&NOABS=Y&SHRTST=50&TRM=' . urlencode($gnd_number);
        }

        $wikidata_id = $this->driver->getWikidataId();
        if ($wikidata_id != null)
            $links['Wikidata'] = '//www.wikidata.org/wiki/' . urlencode($wikidata_id);

        $beacon_references = $this->driver->getBeaconReferences();
        foreach ($beacon_references as $beacon_reference) {
            $beacon_title = 'Archivmaterial (' . $beacon_reference['title'] . ')';
            $links[$beacon_title] = $beacon_reference['url'];
        }
      ?>
      <?php if (count($links) > 0): ?>
        <p>
          External links:
          <ul>
            <?php foreach ($links as $label => $url): ?>
              <li><a target="_blank" href="<?=$url?>"><i class="fa fa-external-link"></i> <?=$label?></a></li>
            <?php endforeach; ?>
          </ul>
        </p>
      <?php endif; ?>

    </div>
  </div>
  <br>
  <?php
    // the tab logic is taken from non-authority core record driver
    // (authority records normally don't have tabs)
    if (!isset($this->activeTab))
      $this->activeTab = 'Details';
  ?>
  <?php if (count($this->tabs) > 0): ?>
    <div class="record-tabs">
      <ul class="nav nav-tabs">
        <?php foreach ($this->tabs as $tab => $obj): ?>
          <?php // add current tab to breadcrumbs if applicable:
            $desc = $obj->getDescription();
            $tabName = preg_replace("/\W/", "-", strtolower($tab));
            $tabClasses = [ 'record-tab', $tabName ];
            if (0 === strcasecmp($this->activeTab, $tab)) {
              if (!$this->loadInitialTabWithAjax || !$obj->supportsAjax()) {
                $tabClasses[] = 'active';
              }
              $tabClasses[] = 'initiallyActive';
              $this->layout()->breadcrumbs .= '<li class="active">' . $this->transEsc($desc) . '</li>';
              $activeTabObj = $obj;
            }
            if (!$obj->isVisible()) { $tabClasses[] = 'hidden'; }
            if (!$obj->supportsAjax()) { $tabClasses[] = 'noajax'; }
          ?>
          <li class="<?=implode(' ', $tabClasses)?>" data-tab="<?=$tabName?>">
            <a href="<?=$this->recordLink()->getTabUrl($this->driver, $tab)?>#tabnav"><?=$this->transEsc($desc)?></a>
          </li>
        <?php endforeach; ?>
      </ul>

      <div class="tab-content">
        <?php if (!$this->loadInitialTabWithAjax || !isset($activeTabObj) || !$activeTabObj->supportsAjax()): ?>
          <div class="tab-pane active <?=$this->escapeHtmlAttr($this->activeTab) ?>-tab">
            <?=isset($activeTabObj) ? $this->record($this->driver)->getTab($activeTabObj) : '' ?>
          </div>
        <?php endif; ?>
      </div>
    </div>
  <?php endif; ?>
</div>