<style>
    .read-more-state {
        display: none;
    }

    .read-more-target {
        opacity: 0;
        max-height: 0;
        font-size: 0;
        transition: .25s ease;
    }

    .read-more-state:checked ~ .read-more-wrap .read-more-target {
        opacity: 1;
        font-size: inherit;
        max-height: 999em;
    }

    .read-more-state ~ .read-more-trigger:before {
        content: 'Espandi';
    }

    .read-more-state:checked ~ .read-more-trigger:before {
        content: 'Riduci';
    }

    .read-more-trigger {
        cursor: pointer;
        display: inline-block;
        padding: 0 .5em;
        color: #666;
        font-size: .9em;
        line-height: 2;
        border: 1px solid #ddd;
        border-radius: .25em;
    }

    div.new {
        float: right;
        color: red;
    }
</style>
<?
$panelId = 0;
$panelClass = "panel-default";
$panelWidth = "col-md-6";
?>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-bell-o"></i> Benvenuti!
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Il nuovo IxTheo è un'ampia bibliografia di Teologia e Scienze Religiose. In essa è possibile effettuare ricerche non solo di articoli scientifici, ma anche volumi monografici, banche dati ed altri risorse digitali.</p>
                    <div class="read-more-target">
                        <p>In aggiunta è disponibile una selezione di recensioni. Qualora le licenze lo permettano, è disponibile un accesso diretto ai fulltext.</p>
                        <p>Il nuovo IxTheo è un servizio gratuito ed open access per la comunità scientifica internazionale. Editori di IxTheo sono la Biblioteca, le Facoltà Teologiche Protestante e Cattolica dell’Università di Tubinga.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-book"></i> Patron-Driven-Acquisition (PDA) <div class="new">Novità</div>
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Per rispondere al meglio alle esigenze della comunità scientifica in Germania è disponibile un servizio di acquisizione di letteratura teologica Patron-Driven-Acquisition (PDA).</p>
                    <div class="read-more-target">
                        <p>I libri richiesti vengono acquistati dalla Biblioteca dell‘Università di Tubinga.</p>
                        <p>Gli utenti possono inoltrare richieste d’acquisto di singoli volumi monografici direttamente ad IxTheo, qualora questi non fossero disponibili nella loro biblioteca di riferimento o prenotabili mediante il servizio di prestito interbibliotecario.</p>
                        <p><a href="docs/ixtheo-pda.pdf" target="_blank">Maggiori informazioni sul servizio PDA</a></p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<h2 class="col-md-12 panel-group">Scopri IxTheo</h2>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-search"></i> Ricerca
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>L’utente può avviare una ricerca generica su tutti i titoli presenti attualmente in IxTheo (più di 1,6 milioni) cliccando su "Cerca".</p>
                    <div class="read-more-target">
                        <p>La ricerca può essere raffinata attraverso la selezione di appropriate categorie, ad. es. "Tipo di documento" oppure "Lingua".</p>

                        <h3>Accesso Tematico</h3>
                        <h4>Classificazione IxTheo</h4>
                        <p>
                            Una "Ricerca avanzata" è disponibile mediante l’omonimo pulsante collocato sotto la fessura di ricerca,
                            cliccandolo è possibile selezionare specifiche classi della classificazione IxTheo. Per selezionare più
                            classi contemporaneamente tenere premuto il Tasto maiuscolo (Shift) oppure Controllo (Ctrl) per i computer
                            Windows, Comando (⌘) per i computer Apple.
                        </p>
                        <p>Per avviare la ricerca dopo la selezione delle classi è necessario premere il tasto "Cerca".</p>

                        <h4>Ricerca tematica</h4>
                        <p>Inserire il tema desiderato nella fessura di ricerca mantenendo la selezionare preimpostata "Tutti i campi".</p>
                        <p>Per una ricerca tematica ancora più precisa è di grande utilità selezionare la voce "Soggetto" a destra della fessura di ricerca.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-list"></i> Esplora
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse ">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Cliccando sul tasto "Esplora" il nuovo IxTheo mette a disposizione tre diverse possibilità.</p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <h3>Esplora per argomento</h3>
                        <p>Appare una nuova fessura di ricerca nella quale inserire l’argomento ricercato. Questo orienta a sua volta la ricerca successiva.</p>
                        <p>Esempio 1: Inserendo la voce "Dio" appare una lista di records bibliografici nei quali il termine ricorre.</p>
                        <p>Esempio 2: Inserendo la voce "Dio" e "Bibbia" appare una lista di records bibliografici nei quali i due termini ricorrono.</p>
                        <p>Selezionando la lingua inglese in alto a destra appaiono il o i termine/i ricercato/i in altra lingua, qualora esista una concordanza.</p>

                        <h3>Esplora il catalogo</h3>
                        <p>Il discovery tool di IxTheo (VuFind) permette la navigazione secondo i seguenti criteri: classificazione DDC, classificazione IxTheo, autore e casa editrice.
                            In un secondo momento la navigazione può essere raffinata in base ad ulteriori criteri.</p>
                        <p>Esempio: Selezionando in sequenza "Autore", "Classificazione IxTheo" e "HB Antico Testamento" appare una lista, ordinata in base alla frequenza dei titoli
                            presenti in IxTheo, di autori che hanno pubblicato nell’ambito disciplinare dell’Antico Testamento.</p>

                        <h3>Esplora in ordine alfabetico</h3>
                        <p>Dopo la selezione di un aspetto specifico della navigazione tra "Tema", "Autore", "Titolo" e "Classificazione DDC" è possibile inserire una qualsiasi
                            lettera dell’alfabeto che avvii la navigazione.</p>
                        <p>Esempio 1: Selezionando "Autore" ed inserendo "Z" appaiono tutti gli autori il cui nome inizia con la suddetta lettera.</p>
                        <p>Esempio 2: Selezionando "Titolo" ed inserendo le lettere "Tr" appaiono tutti i titoli che iniziano con le suddette lettere.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-child"></i> Ricerca personalizzata
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>Diverse funzionalità sono a disposizione dell’utente mediante la creazione gratuita di un conto privato. Per far questo è necessario registrarsi.</p>
                    <p>Per la registrazione o il Login cliccare in alto a destra su "Entra".</p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <h3>Alerting</h3>
                        <p>La funzione di Alerting informa l’utente su nuovi articoli e nuovi volumi di collane scientifiche di sua scelta.</p>
                        <p>Per attivare la funzione selezionare il record generale della rivista o della collana, quindi cliccare sul simbolo della campanella collocato sulla destra.
                            Nel conto personale è possibile amministrare i titoli selezionati.</p>

                        <p>Esempio 1: Per abbonarsi alla <i>Theologische Quartalschrift</i> inserire o il nome completo della rivista o l’abbreviazione "ThQ" nella fessura di ricerca.
                            Selezionare "Periodico" alla voce "Tipo di documento". Appaiono quindi due risultati: il record bibliografico della versione a stampa e quello della versione elettronica.
                            È consigliabile abbonarsi ad entrambe.</p>

                        <p>Esempio 2: Per abbonarsi a <i>Wissenschaftliche Untersuchungen zum Neuen Testament</i> inserire o il nome completo della collana o l’abbreviazione "WUNT" nella fessura di ricerca.
                            Appaiono moltelici risultati. Abbonarsi alla collana desiderata, cliccando sul simbolo della campanella.</p>

                        <p>È in fase di preparazione una selezione ampia di periodici e collane raggruppate secondo singole discipline teologiche.</p>

                        <h3>Memorizzazione della ricerca</h3>
                        <p>Le ricerche di un utente vengono salvate solo temporanemente. Nel conto personale è possibile salvarle per un lungo periodo e riutilizzarle in un secondo momento,
                            sì da rimanere sempre aggiornati sulla nuova letteratura relativa i propri interessi di ricerca.</p>

                        <h3>Memorizzazione dei risultati di ricerca (Favoriti)</h3>
                        <p>Nel conto personale è oltresì possibile salvare i risultati delle proprie ricerche, sì da averle sempre a disposizione.</p>
                        <p>I risultati posso essere anche organizzati in liste tematiche o di ricerca liberamente definite dall’utente.</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
<div class="col-md-6" style="text-align:justify;">
    <div class="panel <?= $panelClass; ?>">
        <div class="panel-heading">
            <h4 class="panel-title">
                <i class="fa fa-binoculars"></i> Ricerca di passi biblici
            </h4>
        </div>
        <div id="<?= $panelId++; ?>" class="panel-collapse">
            <div class="panel-body">
                <input type="checkbox" class="read-more-state" id="post-<?= $panelId; ?>" />
                <div class="read-more-wrap">
                    <p>La ricerca di passi bibici è stata aggiornata sulla base degli interessi scientici dell’utenza. Per attivare la ricerca selezionare la voce "Passi biblici" a destra della fessura di ricerca.
                        È consigliabile raffinare i risultati in base alla rilevanza specifica della singola ricerca.</p>
                    <div class="read-more-target">
                        <!-- Needed since otherwise the More-Button gets confused immediately before a heading -->
                        <div style="height: 0px;">&emsp;</div>
                        <p>I passi biblici possono essere inseriti tanto nelle forme abbreviate internazionali quanto in quelle specifiche di ogni singola lingua,
                            sia essa inglese, francese, italiana o spagnola. Inoltre è possibile utilizzare le abbreviazioni Nestle-Aland e della Vulgata.
                            Solo in pochi casi è stato necessario sciogliere delle ambiguità. Ad esempio l’abbreviazione "es" in francese corrisponde al libro di Isaia,
                            mentre in italiano all’Esodo. Per evitare risultati ambigui è stato necessario in questo caso decidere quale abbreviazione è accettata.
                            La lista delle abbreviazioni valide per la ricerca di passi biblici si trova
                            <a href="<?='https://' . $_SERVER['SERVER_NAME'] . '/docs/Bible_abbreviation.pdf'?>" target="_blank"><b>qui</b></a>.</p>
                        <p>È consigliabile inserire il passo biblico ricercato nella seguente forma:</p>
                        <p>Abbreviazione_del_libro_biblico Capitolo, Versetto</p>
                        <b>Esempi:</b>
                        <ul>
                            <li>Joh 5,1-20 oppure Jn 5, 1-20</li>
                            <li>1Kor 10 oder 1 Kor 10 oppure 1 K10</li>
                            <li>Röm 14, 1-15, 13 oppure Rm14, 1-15, 13</li>
                        </ul>
                        <p>I risultati vengono da IxTheo selezionati secondo i seguenti criteri:</p>
                        <ol>
                            <li><p>Risultato esatto: il passo biblico cercato concorda perfettamente con quello trovato.</p>
                                <p>Esempio: La ricerca di Mk 5, 25-34 trova Mk 5, 25-34.</p></li>
                            <li><p>Risultato compreso: il passo biblico cercato si incrocia con quello trovato.</p>
                                <p>Esempio: La ricerca di Mk 5, 25-34 trova Mk 24-34.</p></li>
                            <li><p>Risultato indiretto: il passo biblico cercato fa parte del capitolo trovato.</p>
                                <p>Esempio: La ricerca di Mk 5, 25-34 trova Mk 5.</p></li>
                        </ol>
                        <p>Inoltre vengono visualizzati anche records bibliografici collegati ad un linguaggio controllato (GND).
                            Ad esempio "Blutflüssige Frau" (donna emorroissa) è collegato ai passi sinottici Mk 5, 25-34, Mt 9, 20-22 e Lk 8,43-48.</p>
                        <p>Attenzione: Non tutti i records bibliografici sono sono collegati ad un liguaggio controllato (GND),
                            si consiglia perciò una ricerca di passi biblici alla voce "Tutti campi". Così facendo la ricerca non sarà tuttavia specifica .</p>
                        <p>La ricerca di passi biblici in IxTheo avviene attraverso la trasformazione della stringa verbale inserita in una successione numerica
                            di otto cifre. Le prime due corrispondono al libro biblico, le successive tre al capitolo e le ultime due al versetto.
                            Mk5, 25-34 viene strasformato in: 02005025_02005034. Per calcolare la corrispondenza, vicinanza o prossimità tra passo il biblico
                            cercato e quello trovato il sistema informatico elabora un sistema di rilevanza a punti (Scoring). Per maggiori informazioni si veda:
                            <a href="https://github.com/ubtue/ixTheo/wiki/Bibelstellensuche---Technischer-%C3%9Cberblick" target="_blank"><b>Apetti tecnici</b></a> (in tedesco)</p>
                    </div>
                </div>
                <label for="post-<?= $panelId; ?>" class="read-more-trigger"></label>
            </div>
        </div>
    </div>
</div>
