<div style="position:relative">
  <div id="visualResults">
    <p><?=$this->transEsc('Please enable Javascript.')?></p>
    <p><?=$this->transEsc('Please upgrade your browser.')?></p>
  </div>

  <div id="viz-instructions">
    <p><strong><a href="<?=$this->url('help-home', array(), array('query' => array('topic' => 'visualization')))?>" class="visualizationHelp"><?=$this->transEsc('What am I looking at')?></a></strong></p>
  </div>
</div>
