<?
/*********************************************
*
* list-list.phtml
*
* displays the search result as a list.
*
*************************************/
 if (!isset($this->indexStart)) $this->indexStart = 0; ?>

<? $showCheckboxes = (isset($this->showCartControls) && $this->showCartControls)
  || (isset($this->showBulkOptions) && $this->showBulkOptions); ?>

<? $i = $this->indexStart; foreach ($this->results->getResults() as $current):
  $recordNumber = $this->results->getStartRecord()+$i-$this->indexStart; ?>
  <div id="result<?=$i++ ?>" class="row result clearfix <?=$i%2==1?' panel-gray ':' panel-body '?> w-100">
    <div class="col-1 hidden-print pr-0 pl-0">
      <label>
        <? if ($showCheckboxes): ?>
          <?=$this->record($current)->getCheckbox()?>
        <? endif; ?>
        <?=$recordNumber?>
      </label>
    </div>
      <div class="col-11 pl-0">
          <?=$this->record($current)->getSearchResult('list') //see contents in RecordDriver/SolrDefault/result-list.phtml ?>
      </div>
  </div>
<? endforeach; ?>