<?
/*********************************************
 *
 * Searchbox.phtml
 *
 * Shows the block with the search input.
 *
 * Changed 23.1.2017, 15:56
 *
 *************************************/

// Set default value if necessary:
if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
}

// Load search actions and settings (if any):
$options = $this->searchOptions($this->searchClassId);
$handlers = $this->searchbox()->getHandlers(
    $this->searchClassId,
    isset($this->searchIndex) ? $this->searchIndex : null
);
$handlerCount = count($handlers);
$basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
$searchHome = $options->getSearchHomeAction();
$advSearch = $options->getAdvancedSearchAction();
$lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
$lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
$ignoreHiddenFilterMemory = isset($this->ignoreHiddenFilterMemory) && $this->ignoreHiddenFilterMemory;
$ignoreHiddenFiltersInRequest = isset($this->ignoreHiddenFiltersInRequest) && $this->ignoreHiddenFiltersInRequest;
$hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
    $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
    if (empty($hiddenFilters)) {
        $hiddenFilters = $this->searchtabs()->getHiddenFilters($this->searchClassId);
    }
}
$hiddenFilterParams = $this->searchtabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');
?>


<div class="container-fluid">
    <div class="row">
        <div class="col-12 px-0">
            <!--  Begin section searchbar -->
            <section class="visible-lg section-home">
                <div class="panel-home">
                    <img class="searchbox-image" src="/themes/ixtheo2/images/searchbar.jpg" >

                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-10 col-xl-6 mx-auto">

                        <!--  Begin title -->
                        <div class="title">
                            <h1>
                                <a href="<?= $this->url('home') ?>" title="Index Theologicus">Index Theologicus</a>
                            </h1>
                            <small><?= $this->transEsc("ixtheo_subtitle") ?></small>
                        </div>
                        <!-- End title -->

                        <!-- Begin warnings -->
                        <? if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
                            <div class="alert alert-warning">
                                <h2><?= $this->transEsc('ils_offline_title') ?></h2>

                                <p><strong><?= $this->transEsc('ils_offline_status') ?></strong></p>

                                <p><?= $this->transEsc('ils_offline_home_message') ?></p>
                                <? $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
                                <p><a href="mailto:<?= $supportEmail ?>"><?= $supportEmail ?></a></p>
                            </div>
                        <? endif; ?>
                        <!-- End warnings -->


                        <div class="clearfix searchbox_home" role="search">
                            <? if ($this->searchType == 'advanced'): ?>
                                <div class="searchForm navbar-form navbar-left flip">
                                    <? $tabs = $this->context($this)->renderInContext('search/searchTabs', ['hiddenFilters' => $hiddenFilters]); ?>
                                    <? if (!empty($tabs)): ?><?= $tabs ?>
                                    <div class="tab-content clearfix"><? endif; ?>
                                        <p class="adv_search_terms"><?= $this->transEsc("Your search terms") ?> :
                                            "<strong><?= $this->escapeHtml($this->lookfor) ?></strong>"</p>
                                        <p class="adv_search_links">
                                            <a href="<?= $this->url($advSearch) ?>?edit=<?= $this->escapeHtmlAttr($this->searchId) ?>"><?= $this->transEsc("Edit this Advanced Search") ?></a>
                                            |
                                            <a href="<?= $this->url($advSearch) . $hiddenFilterParams ?>"><?= $this->transEsc("Start a new Advanced Search") ?></a>
                                            |
                                            <a href="<?= $this->url($searchHome) . $hiddenFilterParams ?>"><?= $this->transEsc("Start a new Basic Search") ?></a>
                                        </p>
                                        <? if (!empty($tabs)): ?></div><? endif; ?>
                                </div>
                            <? else: ?>
                                <form class="searchForm" method="get" action="<?= $this->url($basicSearch) ?>"
                                      name="searchForm" autocomplete="off">

                                    <div class="form-group row">
                                        <!-- Begin search input field -->
                                        <div class="col-xs-12 col-sm-6 col-md-6 col-lg-4 col-xl-6">
                                            <div class="input-group searchbar">
                                                <input class="form-control form-control-lg searchForm_lookfor form-control search-query<? if ($this->searchbox()->autocompleteEnabled($this->searchClassId)): ?> autocomplete searcher:<?= $this->escapeHtmlAttr($this->searchClassId) ?><? endif ?>"
                                                       type="text" name="lookfor"
                                                       value="<?= $this->escapeHtmlAttr($this->lookfor) ?>"/>
                                                <span class="input-group-text">
                                                <i class="fa fa-search"></i>
                                            </span>
                                            </div>
                                        </div>
                                        <!-- End search input field -->

                                        <!-- Begin search select -->
                                        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4 col-xl-4">
                                            <? if ($handlerCount > 1): ?>
                                                <select class="form-control form-control-lg custom-select" name="type">
                                                    <? foreach ($handlers as $handler): ?>
                                                        <option value="<?= $this->escapeHtmlAttr($handler['value']) ?>"<?= $handler['selected'] ? ' selected="selected"' : '' ?>><?= $handler['indent'] ? '-- ' : '' ?><?= $this->transEsc($handler['label']) ?></option>
                                                    <? endforeach; ?>
                                                </select>
                                            <? elseif ($handlerCount == 1): ?>
                                                <input type="hidden" name="type"
                                                       value="<?= $this->escapeHtmlAttr($handlers[0]['value']) ?>"/>
                                            <? endif; ?>
                                        </div>
                                        <!-- Begin search select -->

                                        <!-- Begin search button -->
                                        <div class="col-xs-12 col-sm-2 col-md-2 col-lg-2 col-xl-2">
                                            <button type="submit" class="btn btn-primary btn-lg search-button "><i
                                                        class="fa fa-search"></i> <?= $this->transEsc("Find") ?></button>
                                        </div>
                                        <!-- Begin search button -->
                                    </div>

                                    <? if ($advSearch): ?>
                                        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-2 col-xl-12">

                                            <div class="row">

                                                <div class="col-xs-12 col-sm-4 col-md-3 col-lg-4 col-xl-3">
                                                    <a href="<?= $this->url($advSearch) . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $hiddenFilterParams) ?>"
                                                       class="btn btn-light" role="button"
                                                       rel="nofollow"><?= $this->transEsc("Advanced Search") ?></a>
                                                </div>

                                                <div class="col-xs-4 col-sm-4 col-md-3 col-lg-4 col-xl-3">
                                                    <div class="dropdown">
                                                        <button class="btn btn-light dropdown-toggle"
                                                                type="button"
                                                                id="dropdownMenuButton"
                                                                data-toggle="dropdown"
                                                                aria-haspopup="true"
                                                                aria-expanded="false">
                                                            <?= $this->transEsc('Browse') ?>
                                                        </button>

                                                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                                            <a class="dropdown-item" href="<?= $this->url('keywordchainsearch-home') ?>"><?= $this->transEsc('Browse Keywordchains') ?></a>
                                                            <a class="dropdown-item" href="<?= $this->url('browse-home') ?>"><?= $this->transEsc('Browse the Catalog') ?></a>
                                                            <a class="dropdown-item" href="<?= $this->url('alphabrowse-home') ?>"><?= $this->transEsc('Browse Alphabetically') ?></a>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-2 col-xl-2">
                                                    <div class="dropdown">
                                                        <button class="btn btn-light dropdown-toggle"
                                                                type="button"
                                                                id="dropdownMenuButton"
                                                                data-toggle="dropdown"
                                                                aria-haspopup="true"
                                                                aria-expanded="false">
                                                            <?= $this->transEsc('Need Help?') ?> <span class="caret"></span>
                                                        </button>
                                                        <div class="dropdown-menu">
                                                            <a class="dropdown-item"
                                                               href="<?= $this->url('help-home') ?>?topic=search"
                                                               data-lightbox class="help-link"
                                                               title="<?= $this->transEsc('Search Tips') ?>"><?= $this->transEsc('Search Tips') ?></a>
                                                        </div>
                                                    </div>
                                                </div>

                                                <div class="col-xs-4 col-sm-4 col-md-4 col-lg-4 col-xl-3">
                                                    <a href="<?=$this->url('search-newitem')?>"
                                                       class="btn btn-light" role="button"
                                                       rel="nofollow"><?=$this->transEsc('New Items')?></a>
                                                </div>

                                            </div>

                                        </div>
                                    <? endif; ?>

                                    <? $shards = $options->getShards();
                                    if ($options->showShardCheckboxes() && !empty($shards)): ?>
                                        <?
                                        $selectedShards = isset($this->selectedShards)
                                            ? $this->selectedShards : $options->getDefaultSelectedShards();
                                        ?>
                                        <br/>
                                        <? foreach ($shards as $shard => $val): ?>
                                            <? $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
                                            <input type="checkbox"
                                                   <?= $isSelected ? 'checked="checked" ' : '' ?>name="shard[]"
                                                   value='<?= $this->escapeHtmlAttr($shard) ?>'/> <?= $this->transEsc($shard) ?>
                                        <? endforeach; ?>
                                    <? endif; ?>
                                    <?
                                    $filterDetails = $this->searchbox()->getFilterDetails(
                                        isset($this->filterList) && is_array($this->filterList) ? $this->filterList : array(),
                                        isset($this->checkboxFilters) && is_array($this->checkboxFilters) ? $this->checkboxFilters : array()
                                    );
                                    ?>
                                    <? if ((isset($hasDefaultsApplied) && $hasDefaultsApplied) || !empty($filterDetails)): ?>
                                        <? $defaultFilterState = $options->getRetainFilterSetting() ? ' checked="checked"' : ''; ?>
                                        <div class="checkbox">
                                            <label>
                                                <input onChange="$('.applied-filter').click()"
                                                       type="checkbox"<?= $defaultFilterState ?>
                                                       class="searchFormKeepFilters"/>
                                                <?= $this->transEsc("basic_search_keep_filters") ?>
                                            </label>
                                        </div>
                                        <div class="hidden">
                                            <? foreach ($filterDetails as $current): ?>
                                                <input class="applied-filter"
                                                       id="<?= $this->escapeHtmlAttr($current['id']) ?>"
                                                       type="checkbox"<?= $defaultFilterState ?> name="filter[]"
                                                       value="<?= $this->escapeHtmlAttr($current['value']) ?>"/>
                                                <label for="<?= $this->escapeHtmlAttr($current['id']) ?>"><?= $this->escapeHtml($current['value']) ?></label>
                                            <? endforeach; ?>
                                            <? if (isset($hasDefaultsApplied) && $hasDefaultsApplied): ?>
                                                <!-- this is a hidden element that flags whether or not default filters have been applied;
                                                     it is intentionally unlabeled, as users are not meant to manipulate it directly. -->
                                                <input class="applied-filter" id="dfApplied" type="checkbox"
                                                       name="dfApplied" value="1"<?= $defaultFilterState ?> />
                                            <? endif; ?>
                                        </div>
                                    <? endif; ?>
                                    <? foreach ($hiddenFilters as $key => $filter): ?>
                                        <? foreach ($filter as $value): ?>
                                            <input type="hidden" name="hiddenFilters[]"
                                                   value="<?= $this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value) ?>"/>
                                        <? endforeach; ?>
                                    <? endforeach; ?>
                                    <?
                                    /* Show hidden field for active search class when in combined handler mode. */
                                    if ($this->searchbox()->combinedHandlersActive()) {
                                        echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
                                    }
                                    /* Load hidden limit preference from Session */
                                    if (!empty($lastLimit)) {
                                        echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
                                    }
                                    if (!empty($lastSort)) {
                                        echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
                                    }
                                    ?>
                                </form>
                                <script type="text/javascript">$(".searchForm_lookfor:visible").focus()</script>
                            <? endif; ?>

                        </div>
                    </div><!-- close container -->
                    <div class="scroll-down" id="scroll-down">
                        <a href="" id="scroll-down-button"><span></span><? $this->transEsc("Scroll"); ?></a>
                    </div>
                </div><!-- close panel-home -->
            </section>
            <!-- End section searchbar -->
        </div><!-- close col's -->
    </div><!-- close row -->
</div><!-- close container -->
