<?php
    // Set default value if necessary:
    if (!isset($this->searchClassId)) {
        $config = $this->config()->get('config');
        $this->searchClassId = $config->Site->defaultSearchBackend ?? 'Solr';
    }

    // Load search actions and settings (if any):
    $options = $this->searchOptions($this->searchClassId);
    $handlers = $this->searchbox()->getHandlers(
        $this->searchClassId, $this->searchIndex ?? null
    );
    $handlerCount = count($handlers);
    $basicSearch = $this->searchbox()->combinedHandlersActive() ? 'combined-searchbox' : $options->getSearchAction();
    $searchHome = $options->getSearchHomeAction();
    $advSearch = $options->getAdvancedSearchAction();
    $lastSort = $this->searchMemory()->getLastSort($this->searchClassId);
    $lastLimit = $this->searchMemory()->getLastLimit($this->searchClassId);
    $ignoreHiddenFilterMemory = $this->ignoreHiddenFilterMemory ?? false;
    $ignoreHiddenFiltersInRequest = $this->ignoreHiddenFiltersInRequest ?? false;
    $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId, $ignoreHiddenFilterMemory, $ignoreHiddenFiltersInRequest);
    if (empty($hiddenFilters) && !$ignoreHiddenFilterMemory) {
        $hiddenFilters = $this->searchMemory()->getLastHiddenFilters($this->searchClassId);
        if (empty($hiddenFilters)) {
            $hiddenFilters = $this->searchTabs()->getHiddenFilters($this->searchClassId);
        }
    }
    $hiddenFilterParams = $this->searchTabs()->getCurrentHiddenFilterParams($this->searchClassId, $ignoreHiddenFilterMemory, '?');

    if (!isset($this->filterList) || !isset($this->checkboxFilters)) {
        $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
        $filterList = $params->getFilterList(true);
        $checkboxFilters = $params->getCheckboxFacets();
    } else {
        $filterList = is_array($this->filterList) ? $this->filterList : [];
        $checkboxFilters = is_array($this->checkboxFilters) ? $this->checkboxFilters : [];
    }
    $filterDetails = $this->searchbox()->getFilterDetails($filterList, $checkboxFilters);
    $showFilters = $filterDetails && (isset($results) || $options->getRetainFilterSetting());
?>
<?php $tabConfig = $this->searchTabs()->getTabConfig($this->searchClassId, $this->lookfor, $this->searchIndex, $this->searchType, $hiddenFilters); ?>

<style>
.panel-home h1 a {
    color: #3586b2;
    text-shadow: none;
    font-family: 'Open Sans',Arial,Helvetica,sans-serif;
}
.panel-home small {
    display: block;
    text-align: center;
    margin: 5px 0 auto;
    padding-bottom: 12px;
    color: #495057;
    text-shadow: none;
}
</style>


<div class="row tf-row-home">
    <!--  Begin section searchbar -->
    <section class="section-home">
        <div class="panel-home">
            <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, 'TueFind2.ChangeSearchboxHeight();', 'SET')?>

            <div class="visible-lg">
                <h1>
                    <a href="<?=$this->url('home')?>" title="Index Theologicus">Index Theologicus</a>
                </h1>
                <small><?=$this->transEsc("ixtheo_subtitle")?></small>
                <br />
            </div>

            <div class="searchbox col-12 mx-auto">

                <?=$this->render('search/searchbox/title');?>
                <!-- Begin warnings -->
                <?php if ($this->ils()->getOfflineMode() == "ils-offline"): ?>
                    <div class="alert alert-warning">
                        <h2><?= $this->transEsc('ils_offline_title') ?></h2>

                        <p><strong><?= $this->transEsc('ils_offline_status') ?></strong></p>

                        <p><?= $this->transEsc('ils_offline_home_message') ?></p>
                        <?php $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
                        <p><a href="mailto:<?= $supportEmail ?>"><?= $supportEmail ?></a></p>
                    </div>
                <?php endif; ?>
                <!-- End warnings -->


                <div class="clearfix searchbox_home" role="search">
                    <?php if ($this->searchType == 'advanced'): ?>
                        <div class="searchForm navbar-form navbar-left flip">
                            <?php $tabs = $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs']]); ?>
                            <?php if (!empty($tabs)): ?><?=$tabs ?><div class="tab-content clearfix"><?php endif; ?>
                                <p class="adv_search_terms"><?=$this->transEsc("Your search terms")?> : "<strong><?=$this->escapeHtml($this->lookfor)?></strong>"</p>
                                <p class="adv_search_links">
                                    <a href="<?=$this->url($advSearch)?>?edit=<?=$this->escapeHtmlAttr($this->searchId)?>"><?=$this->transEsc("Edit this Advanced Search")?></a> |
                                    <a href="<?=$this->url($advSearch) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Advanced Search")?></a> |
                                    <a href="<?=$this->url($searchHome) . $hiddenFilterParams?>"><?=$this->transEsc("Start a new Basic Search")?></a>
                                </p>
                                <?=$this->context($this)->renderInContext(
                                  'search/filters.phtml',
                                  [
                                    'params' => $params ?? null,
                                    'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
                                    'filterList' => $showFilters ? $filterList : [],
                                    'checkboxFilters' => $showFilters ? $checkboxFilters : [],
                                    'searchClassId' => $this->searchClassId,
                                    'searchType' => $this->searchType,
                                  ]
                                );?>
                            <?php if (!empty($tabs)): ?></div><?php endif; ?>
                        </div>
                    <?php else: ?>
                        <!-- ixtheo2: custom form with included dropdown inspired by finna.fi -->
                        <?= $this->context($this)->renderInContext('search/searchTabs', ['searchTabs' => $tabConfig['tabs'], 'hiddenFilters' => $hiddenFilters]); ?>
                        <form id="searchForm" class="searchForm ix2-searchForm tuefind-event-searchForm-on-submit" method="get" action="<?=$this->url($basicSearch)?>" name="searchForm" autocomplete="off" style="display: flex;" >
                            <?php $placeholder = $this->searchbox()->getPlaceholderText($tabConfig['selected']['id'] ?? null); ?>


                            <!-- Begin search input field -->
                            <input id="searchForm_lookfor"
                                   class="searchForm_lookfor form-control search-query<?php if ($this->searchbox()->autocompleteEnabled($this->searchClassId)): ?> autocomplete searcher:<?= $this->escapeHtmlAttr($this->searchClassId) ?><?php endif ?>"
                                   type="text" name="lookfor"
                                   value="<?= $this->escapeHtmlAttr($this->lookfor) ?>"
                                   <?php if ($placeholder): ?> placeholder="<?=$this->transEsc($placeholder) ?>"<?php endif ?>/>

                            <!-- Begin search select -->
                            <?php if ($handlerCount > 1): ?>
                                <div class="dropdown form-control type-dropdown">
                                    <input id="searchForm_type" class="searchForm_type" type="hidden" name="type" value="AllFields">
                                    <a class="dropdown-toggle" href="#" aria-haspopup="true" aria-expaned="false" aria-label="<?=$this->transEsc("Search type")?>" data-toggle="dropdown">
                                        <span id="searchForm_typeCaption"><?=$this->transEsc('All fields')?></span>
                                        <b class="caret"></b>
                                    </a>
                                    <ul class="dropdown-menu cw-mt-0" role="menu">
                                        <?php foreach ($handlers as $handler): ?>
                                            <li role="menuitem">
                                                <input type="hidden" value="<?=$handler['value']?>">
                                                <a class="select-type" href="#" onclick="$('#searchForm_type').attr('value', '<?=$handler['value']?>');$('#searchForm_typeCaption').html('<?=$this->transEsc($handler['label'])?>');"><?=$this->transEsc($handler['label'])?></a>
                                            <li>
                                        <?php endforeach; ?>
                                    </ul>
                                </div>
                            <?php elseif ($handlerCount == 1): ?>
                                <input type="hidden" name="type" value="<?=$this->escapeHtmlAttr($handlers[0]['value'])?>" />
                            <?php endif; ?>

                            <!-- Begin search button -->
                            <button type="submit" class="btn btn-primary search-button"><i class="fa fa-search" aria-hidden="true"></i><!-- IxTheo2: No text <?= $this->transEsc("Find") ?>--></button>

                            <!-- IxTheo 2: Advanced search -->
                            <?php if ($advSearch != ''):?>
                                <div class="ix-searchbox-adv-search">
                                    <a href="<?=$this->url($advSearch) .  ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $this->hiddenFilterParams)?>"
                                       class="btn btn-link" role="button"
                                       rel="nofollow"><?= $this->transEsc("Advanced Search") ?></a>
                                </div>
                            <?php endif;?>

                            <?php if ($geoUrl = $this->geocoords()->getSearchUrl($options)) : ?>
                                <a href="<?=$geoUrl ?>" class="btn btn-link"><?=$this->transEsc('Geographic Search')?></a>
                            <?php endif; ?>

                            <?php $shards = $options->getShards(); if ($options->showShardCheckboxes() && !empty($shards)): ?>
                                <?php
                                $selectedShards = isset($this->selectedShards)
                                    ? $this->selectedShards : $options->getDefaultSelectedShards();
                                ?>
                                <br />
                                <?php foreach ($shards as $shard => $val): ?>
                                    <?php $isSelected = empty($selectedShards) || in_array($shard, $selectedShards); ?>
                                    <input type="checkbox" <?=$isSelected ? 'checked="checked" ' : ''?>name="shard[]" value='<?=$this->escapeHtmlAttr($shard)?>' /> <?=$this->transEsc($shard)?>
                                <?php endforeach; ?>
                            <?php endif; ?>
                            <?php if (($hasDefaultsApplied ?? false) || !empty($filterDetails)): ?>
                              <?php if ($options->getRetainFilterSetting()): ?>
                                <?php foreach ($filterDetails as $current): ?>
                                  <input class="applied-filter" id="<?=$this->escapeHtmlAttr($current['id'])?>" type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($current['value'])?>" />
                                <?php endforeach; ?>
                                <?php if ($hasDefaultsApplied ?? false): ?>
                                  <input class="applied-filter" id="dfApplied" type="hidden" name="dfApplied" value="1" />
                                <?php endif; ?>
                              <?php endif; ?>
                            <?php endif; ?>
                            <?php foreach ($hiddenFilters as $key => $filter): ?>
                                <?php foreach ($filter as $value): ?>
                                    <input type="hidden" name="hiddenFilters[]" value="<?=$this->escapeHtmlAttr($key) . ':' . $this->escapeHtmlAttr($value)?>" />
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                            <?php
                            /* Show hidden field for active search class when in combined handler mode. */
                            if ($this->searchbox()->combinedHandlersActive()) {
                                echo '<input type="hidden" name="activeSearchClassId" value="' . $this->escapeHtmlAttr($this->searchClassId) . '" />';
                            }
                            /* Load hidden limit preference from Session */
                            if (!empty($lastLimit)) {
                                echo '<input type="hidden" name="limit" value="' . $this->escapeHtmlAttr($lastLimit) . '" />';
                            }
                            if (!empty($lastSort)) {
                                echo '<input type="hidden" name="sort" value="' . $this->escapeHtmlAttr($lastSort) . '" />';
                            }
                            ?>
                            <?=$this->context($this)->renderInContext(
                              'search/filters.phtml',
                              [
                                'params' => $params ?? null,
                                'urlQuery' => isset($results) ? $results->getUrlQuery() : null,
                                'filterList' => $showFilters ? $filterList : [],
                                'checkboxFilters' => $showFilters ? $checkboxFilters : [],
                                'searchClassId' => $this->searchClassId,
                                'searchType' => $this->searchType,
                              ]
                            );?>
                        </form>
                        <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, '$(".searchForm_lookfor:visible").focus();', 'SET')?>

                        <?php if ($advSearch): ?>
                            <?=$this->context($this)->renderInContext('search/searchbox/pills.phtml', ['searchId' => $this->searchId,
                                                                                                       'hiddenFilterParams' => $hiddenFilterParams,
                                                                                                       'advSearchUrl' => $this->url($advSearch)])?>
                        <?php endif; ?>

                        <?php //optional extension template, e.g. for RelBib ?>
                        <?=$this->render('search/searchbox/extensions');?>

                    <?php endif; ?>

                </div>
            </div><!-- close container -->
            <!--
            <div class="scroll-down" id="scroll-down">
                <a href="" id="scroll-down-button"><span></span><?php $this->transEsc("Scroll"); ?></a>
            </div>
            -->
        </div><!-- close panel-home -->
        <?php //optional extension template, e.g. for IxTheo2-carousel ?>
        <?=$this->render('search/searchbox/section-home-extensions');?>
    </section>
</div>
<!-- End section searchbar -->
