<!-- START of: finna - Helpers/OnlinePayment/terms-TurkuPaymentAPI.phtml -->
<h2><?=$this->transEsc('online_payment_go_to_pay', ['%%amount%%' => ''])?></h2>
<form id="paytrail-form" class="online-payment-form" action="<?=$this->url('myresearch-fines')?>" method="post" data-lightbox-ignore>
  <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
  <img src="<?=$this->imageLink('online-payment-vaski.png')?>" id="vaski-logo" alt="vaskilogo">
  <div class="terms-of-service terms-of-service-text">
    <div class="terms-of-service-info-box">
      <?= $this->translate('online_payment_terms_TurkuPayment_html', ['%%paymentHandler%%' => $this->escapeHtml($paymentHandler)]) ?>
    </div>
  </div>
  <input name="transactionId" type="hidden" value="<?=$this->escapeHtmlAttr($this->transactionId)?>">
  <?php foreach ($this->selectedIds as $fineId): ?>
    <input name="selectedIDS[]" type="hidden" value="<?=$this->escapeHtmlAttr($fineId)?>">
  <?php endforeach; ?>
  <button type="submit" name="reset" class="btn btn-primary" data-bs-dismiss="modal" value="1">
    <?=$this->transEsc('online_payment_cancel'); ?>
  </button>
  <button type="submit" name="pay-confirm" class="btn btn-primary" value="1">
    <?=$this->transEsc('online_payment_accept_terms')?>
  </button>
</form>

<?php
  $script = <<<JS
      $(document).ready(function() {
        $('.online-payment-form').on('submit', function() {
          $(this).find('input[type=submit]').prop('disabled', 'disabled');
        });
      });
      JS;
  echo $this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $script, 'SET');
?>
<!-- END of: finna - Helpers/OnlinePayment/terms-TurkuPaymentAPI.phtml -->
