<?php
    $rawParams = ['class' => 'facet', 'data-sort' => $this->sort, 'data-lightbox-ignore' => 'data-lightbox-ignore'];
    $rawHrefParams = ['facetsort' => $this->sort, 'contains' => $this->contains];

    $prevParams = $rawParams;
    $prevParams['class'] .= ' js-facet-prev-page';
    $prevParams['data-page'] = ($this->page - 1);
    $prevParams['data-limit'] = count($this->data);
    $prevHrefParams = $rawHrefParams;
    $prevHrefParams['facetpage'] = $this->page - 1;
    $prevParams['href'] = $urlBase . '&' . http_build_query($prevHrefParams);

    $nextParams = $rawParams;
    $nextParams['class'] .= ' js-facet-next-page';
    $nextParams['data-page'] = ($this->page + 1);
    $nextHrefParams = $rawHrefParams;
    $nextHrefParams['facetpage'] = $this->page + 1;
    $nextParams['href'] = $urlBase . '&' . http_build_query($nextHrefParams);
?>
<ul class="full-facet-list facet__list facet-group" id="facet-list-<?=$this->escapeHtmlAttr($key) ?>">
  <?php if ($this->page > 1 && !$this->inLightbox): ?>
    <a<?=$this->htmlAttributes($prevParams)?>><?=$this->transEsc('prev_ellipsis') ?></a>
  <?php endif; ?>
  <?php foreach ($this->data as $item): ?>
    <li class="facet__list__item">
      <?=$this->render('Recommend/SideFacets/single-facet.phtml', [
        'exclude' => $this->exclude,
        'facet' => $item,
        'group' => $this->facet,
        'url' => $this->results->getUrlQuery(),
        'urlBase' => $this->searchAction,
      ]) ?>
    </li>
  <?php endforeach; ?>
  <?php if ($this->anotherPage): ?>
    <li>
      <a<?=$this->htmlAttributes($nextParams)?>>
        <span class="text"><?=$this->transEsc('more_ellipsis') ?></span>
      </a>
    </li>
  <?php endif; ?>
</ul>
