<?php
    // Set up breadcrumbs:
    $this->breadcrumbs()->set($this->translate('New Items'), active: true);

    // Load advanced search Javascript to activate the clear button:
    $this->assetManager()->appendScriptLink('advanced_search.js');

    // Convenience variable:
    $offlineMode = $this->ils()->getOfflineMode();
?>
<?=$this->component('page-title', ['title' => $this->translate('Find New Items'), 'headTitle' => $this->translate('New Item Search')]);?>
<?php if ($offlineMode == 'ils-offline'): ?>
  <?=$this->render('Helpers/ils-offline.phtml', ['offlineModeMsg' => 'ils_offline_holdings_message'])?>
<?php endif; ?>
<form method="get" class="form-search-newitem">
  <?php if (!empty($this->defaultSort)): ?>
    <input type="hidden" name="sort" value="<?=$this->escapeHtmlAttr($this->defaultSort)?>">
  <?php endif; ?>
  <div class="form-group">
    <label class="form-label"><?=$this->transEsc('Range')?>:</label>
    <div class="btn-group" role="group" data-bs-toggle="buttons">
      <?php foreach ($this->ranges as $key => $range): ?>
        <?php
          $inputId = 'newitem_range_' . $key;
          $inputAttrs = [
            'id' => $inputId,
            'type' => 'radio',
            'class' => 'btn-check',
            'name' => 'range',
            'value' => $range,
            'autocomplete' => 'off',
          ];
          if ($key == 0) {
            $inputAttrs['checked'] = 'checked';
            $inputAttrs['data-checked-by-default'] = 'true';
          }
          $labelAttrs = [
            'for' => $inputId,
            'class' => 'btn btn-outline-primary',
          ]
        ?>
        <input<?=$this->htmlAttributes($inputAttrs)?>>
        <label<?=$this->htmlAttributes($labelAttrs)?>>
          <?=$this->transEsc('past_days', ['range' => $this->escapeHtml($range)], null, true)?>
        </label>
      <?php endforeach; ?>
    </div>
  </div>
  <?=$this->render('search/advanced/solr-facets.phtml')?>
  <?php if (is_array($this->fundList) && !empty($this->fundList)): ?>
    <div class="form-group">
      <label class="form-label" for="newitem_department"><?=$this->transEsc('Department')?>:</label>
      <select id="newitem_department" name="department" size="10" class="form-select form-select">
      <?php foreach ($this->fundList as $fundId => $fund): ?>
        <option value="<?=$this->escapeHtmlAttr($fundId)?>"><?=$this->transEsc($fund)?></option>
      <?php endforeach; ?>
      </select>
    </div>
  <?php endif; ?>
  <div class="adv-submit">
    <input class="btn btn-primary" type="submit" name="submitButton" value="<?=$this->transEscAttr('Find')?>">
    <input class="clear-btn btn btn-default" type="button" value="<?= $this->transEscAttr('Clear')?>">
  </div>
</form>
