<?php
    // Set some overrides, then call the standard search results action:
    $this->slot('head-title')->set($this->translate('Reserves Search Results'));
    $this->slot('search-heading')->set($this->transEsc('Reserves'));
    $headingParts = [];
    if (isset($this->instructor)) {
        $headingParts[] = $this->transEsc('Instructor') . ': <strong>' . $this->transEsc('Reserves::' . $this->instructor) . '</strong>';
    }
    if (isset($this->course)) {
        $headingParts[] = $this->transEsc('Course') . ': <strong>' . $this->transEsc('Reserves::' . $this->course) . '</strong>';
    }
    if (!empty($headingParts)) {
        $this->slot('search-heading')->append(' (' . implode(', ', $headingParts) . ')');
    }
    $this->slot('empty-message')->set($this->transEsc('course_reserves_empty_list'));
    $this->breadcrumbs()->set($this->translate('Search For Items on Reserve'), $this->url('search-reserves'));
    // Disable loading of results with JS for now since it doesn't handle the special parameters:
    $this->results->getOptions()->setLoadResultsWithJs(false);
    echo $this->render('search/results.phtml');
