<?php if (count($searchTabs) > 0): ?>
  <?php
    $hasSelectedTab = false;
    $resultTotal = $this->results?->getResultTotal() ?? -1;
  ?>
  <ul class="nav nav-tabs">
    <?php foreach ($searchTabs as $tab): ?>
      <?php if ($this->permission()->allowDisplay($tab['permission'])): ?>
        <?php
          $linkAttributes = [
            'data-source' => $tab['class'],
            'class' => 'nav-link',
          ];
          if ($tab['selected']) {
            $hasSelectedTab = true;
            $linkAttributes['class'] .= ' active';
            $linkAttributes['aria-current'] = 'page';
            if ($this->showCounts && $resultTotal >= 0) {
              $linkAttributes['data-result-total'] = $resultTotal;
            } elseif ($this->showCounts) {
              $linkAttributes['data-search-url'] = $tab['url'];
            }
          } else {
            $linkAttributes['href'] = $tab['url'];
          }
        ?>
        <li class="nav-item"<?=$this->showCounts ? ' data-show-counts' : ''?>>
          <a<?=$this->htmlAttributes($linkAttributes)?>><?=$this->transEsc($tab['label']); ?></a>
        </li>
      <?php elseif ($block = $this->permission()->getAlternateContent($tab['permission'])): ?>
        <?=$block?>
      <?php endif; ?>
    <?php endforeach; ?>
    <?php if (!$hasSelectedTab && !$this->translationEmpty('temporary_search_tab_title')): ?>
      <li class="nav-item">
        <a class="nav-link active" aria-current="page"><?=$this->transEsc('temporary_search_tab_title')?></a>
      </li>
    <?php endif; ?>
  </ul>
  <?php if ($this->showCounts): ?>
    <?php $this->headScript()->appendFile('resultcount.js'); ?>
  <?php endif; ?>
<?php endif; ?>
