<?php
    // Set up page title:
    $this->headTitle($this->translate('Library Cards'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Library Cards') . '</li>';
?>
<div class="<?=$this->layoutClass('mainbody')?>">

  <?=$this->flashmessages()?>

  <h2><?=$this->transEsc('Library Cards')?></h2>
  <?php if (count($this->libraryCards) == 0): ?>
    <div><?=$this->transEsc('You do not have any library cards')?></div>
  <?php else: ?>
    <table class="table table-striped">
      <caption class="sr-only"><?=$this->transEsc('Library Cards')?></caption>
    <tr>
      <th><?=$this->transEsc('Library Card Name')?></th>
      <?php if ($this->multipleTargets): ?>
      <th><?=$this->transEsc('login_target')?></th>
      <?php endif; ?>
      <th><?=$this->transEsc('Username')?></th>
      <th>&nbsp;</th>
    </tr>
    <?php foreach ($this->libraryCards as $record): ?>
      <tr>
        <td><?=$this->escapeHtml($record->getCardName())?></td>
        <?php $username = $record->getCatUsername(); ?>
        <?php if ($this->multipleTargets): ?>
          <?php $target = ''; ?>
          <?php if (strstr($username, '.')): ?>
            <?php [$target, $username] = explode('.', $username, 2); ?>
          <?php endif; ?>
          <td><?=$target ? $this->transEsc("source_$target", null, $target) : '&nbsp;' ?></td>
        <?php endif; ?>
        <td><?=$this->escapeHtml($username)?></td>
        <td>
          <?php if ($this->auth()->getManager()->allowsUserIlsLogin()): ?>
            <a class="btn btn-default icon-link" href="<?=$this->url('editLibraryCard') . $this->escapeHtmlAttr($record->getId()) ?>" title="<?=$this->transEscAttr('Edit Library Card')?>">
              <?=$this->icon('profile-card-edit', 'icon-link__icon') ?>
              <span class="icon-link__label"><?=$this->transEsc('Edit')?></span>
            </a>
          <?php endif; ?>
          <?=
            $this->component(
                'confirm-button',
                [
                    'buttonLink' => $this->url('librarycards-deletecard', [], ['query' => ['cardID' => $record->getId()]]),
                    'buttonIcon' => 'profile-card-delete',
                    'buttonLabel' => 'Delete',
                    'buttonClass' => 'btn btn-default',
                    'confirmLink' => $this->url('librarycards-deletecard', [], ['query' => ['cardID' => $record->getId(), 'confirm' => 1]]),
                    'clearAccountCache' => true,
                    'header' => 'confirm_delete_library_card_brief',
                ]
            )
          ?>
        </td>
      </tr>
    <?php endforeach; ?>
    </table>
  <?php endif; ?>

  <div class="btn-group">
    <?php if ($this->allowConnectingCards): ?>
      <a href="<?=$this->url('librarycards-connectcardlogin') ?>" class="add-card-login btn btn-link">
        <?=$this->icon('ui-add') ?>
        <span class="icon-link__label"><?=$this->transEsc('Add a Library Card using login')?></span>
      </a>
    <?php endif;?>
    <?php if ($this->auth()->getManager()->allowsUserIlsLogin()): ?>
      <a href="<?=$this->url('editLibraryCard') ?>NEW" class="add-card btn btn-link">
        <?=$this->icon('ui-add') ?>
        <span class="icon-link__label"><?=$this->transEsc('Add a Library Card')?></span>
      </a>
    <?php endif; ?>
  </div>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('librarycards')?>
</div>
