<?php $cart = $this->cart(); ?>
<?php $recordView = $this->layout()->templateDir ?>
<?php if ($cart->isActive()): ?>
    <?php $cartId = $this->source . '|' . $this->id; ?>
    <div class="btn-bookbag-toggle" data-cart-id="<?=$this->escapeHtmlAttr($this->id)?>" data-cart-source="<?=$this->escapeHtmlAttr($this->source)?>">
    <a class="cart-add hidden<?php if(!$cart->contains($cartId)): ?> correct<?php endif ?>" title="<?=$this->transEsc('Add to Book Bag') ?>">
        <i class="fa fa-suitcase" aria-hidden="true"></i>
        <span class="hidden-sm hidden-md hidden-lg"><?=$this->transEsc('Add to Book Bag') ?></span>
        <?= $this->layout()->templateDir == 'record' ? $this->transEsc('Add to Book Bag') : ''?>
    </a>
    <a class="cart-remove hidden<?php if($cart->contains($cartId)): ?> correct<?php endif ?>" title="<?=$this->transEsc('Remove from Book Bag') ?>">
        <i class="fa fa-close" aria-hidden="true"></i>
        <span class="hidden-sm hidden-md hidden-lg"><?=$this->transEsc('Remove from Book Bag') ?></span>
        <?= $this->layout()->templateDir == 'record' ? $this->transEsc('Remove from Book Bag') : ''?>
    </a>
    <noscript>
      <form method="post" name="addForm" action="<?=$this->url('cart-processor')?>">
        <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <?php if ($cart->contains($cartId)): ?>
              <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <?php else: ?>
              <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <?php endif; ?>
      </form>
    </noscript>
  </div>
<?php endif; ?>
