<!-- START of: finna - record/checkbox.phtml -->
<?php // autocomplete="off" is needed to uncheck the checkbox after copying to another list ?>
<?php $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $this->id); ?>
<fieldset>
  <legend class="sr-only"><?=$this->transEsc('Select');?></legend>
  <?php if ($this->label): ?>
    <label for="<?=$this->escapeHtmlAttr($safeId) ?>" class="record-checkbox">
    <span class="sr-only"><?=$this->transEsc('Select');?></span>
  <?php endif; ?>
    <input id="<?=$this->escapeHtmlAttr($safeId) ?>" class="checkbox-select-item" type="checkbox" name="ids[]" value="<?=$this->escapeHtmlAttr($this->id) ?>"<?php if(isset($this->formAttr)): ?> form="<?=$this->formAttr ?>"<?php endif; ?> aria-label="<?=$this->transEsc('Select')?>" />
  <?php if ($this->label): ?>
    </label>
  <?php endif; ?>
  <input type="hidden" name="idsAll[]" value="<?=$this->escapeHtmlAttr($this->id) ?>"<?php if(isset($this->formAttr)): ?> form="<?=$this->formAttr ?>"<?php endif; ?>/>
</fieldset>
<!-- END of: finna - record/checkbox.phtml -->
