<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->reset();
  if ($url = $this->searchMemory()->getLastSearchUrl()) {
    $this->breadcrumbs()->add($this->translate('Search'), $url);
  }
  $this->breadcrumbs()->add(...$this->recordLinker()->getBreadcrumbParams($this->driver))
    ->add($this->translate('Record Citations'), active: true);

  // Collect citation data:
  $helper = $this->citation($this->driver);
  $citations = [];
  foreach ($this->driver->getCitationFormats() as $format) {
    $citations[$format . ' Citation'] = $helper->getCitation($format);
  }
?>
<?=$this->component('page-title', ['title' => $this->translate('Record Citations'), 'level' => 1]);?>
<?php if (count($citations) == 0): ?>
  <?=$this->transEsc('No citations are available for this record')?>
<?php else: ?>
  <?php foreach ($citations as $caption => $citation): ?>
    <strong><?=$this->transEsc($caption)?></strong>
    <p class="text-left">
      <?=$citation?>
    </p>
  <?php endforeach; ?>
  <div class="text-muted text-center"><?=$this->transEsc('Warning: These citations may not always be 100% accurate')?>.</div>
<?php endif; ?>
