<!-- START of: finna - record/comments-list.phtml -->
<?php
  $comments = $this->record($this->driver)->getComments();
  $inappropriateComments = [];
  $user = $this->auth()->getUserObject();
  if ($comments) {
     $inappropriateComments = $this->driver->tryMethod('getInappropriateComments', [$user]);
  }
  $ratingAllowed = $this->driver->isRatingAllowed();
?>
<?php if (!$comments): ?>
  <div class="alert alert-info"><?=$this->transEsc('Be the first to leave a comment')?></div>
<?php else: ?>
  <?php
    foreach ($comments as $comment):
      $reported = $inappropriateComments && in_array($comment->getId(), $inappropriateComments);
      $own = $user && $comment->getUser()?->getId() === $user->getId();
  ?>
  <div class="comment-wrapper comment" data-id="<?=$comment->getId()?>">
    <div class="name text-right">
      <?php if ($ratingAllowed): ?>
        <div class="comment-rating">
          <?php $ratingData = $this->ratings()->getRatingData($this->driver, $comment->getUser()?->getId()); ?>
          <?php if ($ratingData['count']): ?>
            <?=$this->component('star-rating', ['readonly' => true, 'ratingData' => $ratingData]);?>
          <?php endif; ?>
        </div>
      <?php endif; ?>
      <div class="comment-info">
        <small>
          <strong><?=null === $comment->getUser() ? $this->transEsc('comment_anonymous_user') : $this->escapeHtml(trim($this->userPublicName($comment->getUser())))?></strong>
          <?=$this->escapeHtml($comment->getCreated()->format($this->config()->dateTimeFormat()))?>
          <?php if ($comment->getFinnaUpdated()): ?>
            <br>
            <?=$this->transEsc('modified')?>
            <?=$this->escapeHtml($comment->getFinnaUpdated()->format($this->config()->dateTimeFormat()))?>
          <?php endif; ?>
          <?php if ($own): ?>
            <br>
            <a href="#" class="edit"><?=$this->transEsc('Edit')?></a>
            <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'DeleteComment', ['delete' => $comment->getId()]))?>" id="recordComment<?=$this->escapeHtml($comment->getId())?>" class="delete text-danger"><?=$this->transEsc('Delete')?></a>
          <?php endif; ?>
        </small>
      </div>
    </div>
    <div class="comment-text"><?=$this->escapeHtml($comment->getComment())?></div>
    <?php if (!$own): ?>
      <div class="comment-inappropriate<?= $reported ? '-reported' : ''?> text-right">
        <small>
          <?php if (!$reported): ?>
            <a title="<?=$this->transEscAttr('Report inappropriate') ?>" href="<?=$this->url('comments-inappropriate', ['id' => $comment->getId()]) ?>" data-lightbox><?=$this->translate('Report inappropriate')?></a>
          <?php else: ?>
            <?=$this->translate('Reported inappropriate'); ?>
          <?php endif; ?>
        </small>
      </div>
    <?php endif; ?>
  </div>
  <?php endforeach; ?>
<?php endif; ?>
<?=
  $this->assetManager()->outputInlineScriptString(
      '$(document).ready(function() { finna.comments.initCommentList('
      . 'true,'
      . ($ratingAllowed ? 'true' : 'false') . ','
      . count($comments)
      . '); });'
  )?>
<!-- END of: finna - record/comments-list.phtml -->
