<?
    // Set page title.
    $this->headTitle($this->translate('request_place_text') . ': ' . $this->driver->getBreadcrumb());

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
        . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
        . '<li class="active">' . $this->transEsc('request_place_text') . '</li>';
?>
<h2><?=$this->transEsc('request_place_text')?></h2>
<? if ($this->helpText): ?>
<p class="helptext"><?=$this->helpText?></p>
<? endif; ?>

<div class="hold-form">
  <form method="post" name="placeHold">
    <?=$this->flashmessages()?>
    <? if (in_array("comments", $this->extraHoldFields)): ?>
      <div class="form-group hold-comment">
        <label class="control-label"><?=$this->transEsc("Comments")?>:</label>
        <textarea rows="3" cols="20" name="gatheredDetails[comment]" class="form-control"><?=isset($this->gatheredDetails['comment']) ? $this->escapeHtml($this->gatheredDetails['comment']) : ''?></textarea>
      </div>
    <? endif; ?>

    <? if (in_array("requiredByDate", $this->extraHoldFields)): ?>
      <div class="form-group hold-required-by">
        <label class="control-label"><?=$this->transEsc("hold_required_by")?>:</label>
        <input id="requiredByDate" type="text" name="gatheredDetails[requiredBy]" value="<?=(isset($this->gatheredDetails['requiredBy']) && !empty($this->gatheredDetails['requiredBy'])) ? $this->escapeHtmlAttr($this->gatheredDetails['requiredBy']) : $this->escapeHtmlAttr($this->defaultRequiredDate)?>" size="8" class="form-control"/>
        <div class="help-block">(<?=$this->dateTime()->getDisplayDateFormat()?>)</div>
      </div>
    <? endif; ?>

    <? if ($this->requestGroupNeeded): ?>
      <div class="form-group hold-request-group">
        <?
          if (isset($this->gatheredDetails['requestGroupId']) && $this->gatheredDetails['requestGroupId'] !== "") {
              $selected = $this->gatheredDetails['requestGroupId'];
          } else {
              $selected = $this->defaultRequestGroup;
          }
       ?>
        <label class="control-label"><?=$this->transEsc("hold_request_group")?>:</label>
        <select id="requestGroupId" name="gatheredDetails[requestGroupId]" class="form-control">
        <? if ($selected === false): ?>
          <option value="" selected="selected">
            <?=$this->transEsc('select_request_group')?>
          </option>
        <? endif; ?>
        <? foreach ($this->requestGroups as $group): ?>
          <option value="<?=$this->escapeHtmlAttr($group['id'])?>"<?=($selected == $group['id']) ? ' selected="selected"' : ''?>>
            <?=$this->transEsc('request_group_' . $group['name'], null, $group['name'])?>
          </option>
        <? endforeach; ?>
        </select>
      </div>
    <? endif; ?>

    <? if (in_array("pickUpLocation", $this->extraHoldFields)): ?>
      <?
        if (isset($this->gatheredDetails['pickUpLocation']) && $this->gatheredDetails['pickUpLocation'] !== "") {
            $selected = $this->gatheredDetails['pickUpLocation'];
        } elseif (isset($this->homeLibrary) && $this->homeLibrary !== "") {
            $selected = $this->homeLibrary;
        } else {
            $selected = $this->defaultPickup;
        }
      ?>
      <? $user = $this->auth()->isLoggedIn(); if ($user->getLibraryCards()->count() > 1): ?>
      <? $cards = $user->getLibraryCards();?>
      <div class="form-group library-card-information">
        <div class="control-label"><strong><?=$this->transEsc("Library Card")?>:</strong></div>
        <? foreach ($cards as $card): ?>
          <?
            $target = '';
            $username = $card->cat_username;
            if (strstr($username, '.')) {
              list($target, $username) = explode('.', $username, 2);
            }
            $display = $this->transEsc($card->card_name ? $card->card_name : $username);
            if ($display == "$target.$username") {
              $display = $username;
            }
            if ($target) {
              $display .= ' (' . $this->transEsc("source_$target", null, $target) . ')';
            }
          ?>
          <? if (strcasecmp($card->cat_username, $user->cat_username) === 0): ?>
            <?=$display ?>
            <? break; ?>
          <? endif; ?>
        <? endforeach; ?>
      </div>
      <? endif; ?>
      <? if ($this->requestGroupNeeded): ?>
        <div class="form-group hold-pickup-location">
          <label id="pickUpLocationLabel" class="control-label"><i></i> <?=$this->transEsc("pick_up_location")?>:
            <? if (in_array("requestGroup", $this->extraHoldFields)): ?>
              <noscript> (<?=$this->transEsc("Please enable JavaScript.")?>)</noscript>
            <? endif; ?>
          </label>
          <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" data-default="<?=$this->escapeHtmlAttr($selected)?>" class="form-control">
            <? if ($selected === false): ?>
            <option value="" selected="selected">
              <?=$this->transEsc('select_pickup_location')?>
            </option>
            <? endif; ?>
          </select>
        </div>
      <? elseif ($this->pickup): ?>
        <div class="form-group hold-pickup-location">
          <label class="control-label"><?=$this->transEsc("pick_up_location")?>:</label>
          <select id="pickUpLocation" name="gatheredDetails[pickUpLocation]" class="form-control">
          <? if ($selected === false && count($this->pickup) > 1): ?>
            <option value="" selected="selected">
              <?=$this->transEsc('select_pickup_location')?>
            </option>
          <? endif; ?>
          <? foreach ($this->pickup as $lib): ?>
            <option value="<?=$this->escapeHtmlAttr($lib['locationID'])?>"<?=($selected == $lib['locationID']) ? ' selected="selected"' : ''?>>
              <?=$this->transEsc('location_' . $lib['locationDisplay'], null, $lib['locationDisplay'])?>
            </option>
          <? endforeach; ?>
          </select>
        </div>
      <? else: ?>
        <input type="hidden" name="gatheredDetails[pickUpLocation]" value="<?=$this->escapeHtmlAttr($this->defaultPickup)?>" />
      <? endif; ?>
    <? endif; ?>
    <? if (in_array("acceptTerms", $this->extraHoldFields)): ?>
      <div class="form-group">
        <input id="acceptTerms" type="checkbox" name="gatheredDetails[acceptTerms]">
        <label for="acceptTerms" class="control-label"><?=$this->translate(empty($this->acceptTermsText) ? "accept_request_terms_html" : $this->acceptTermsText)?></label>
      </div>
    <? endif; ?>
    <div class="form-group">
      <input class="btn btn-primary" type="submit" name="placeHold" value="<?=$this->transEsc('request_submit_text')?>"/>
    </div>
  </form>
</div>

<?
    // Set up hold script; we do this inline instead of in the header for lightbox compatibility:
    $this->inlineScript()->appendFile('hold.js');

    $js = <<<JS
        if ($.isReady) {
            setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
        } else {
            $(document).ready(function(){
                setUpHoldRequestForm("{$this->escapeHtml($this->driver->getUniqueId())}");
            });
        }
JS;

    echo $this->inlineScript()->appendScript($js);
?>
