<!-- START of: finna - record/record-organisation-menu.phtml -->
<?php
  $currentSource = $this->driver->tryMethod('getDataSource');
  $currentSourceTranslated = $this->transEsc("source_$currentSource", null, $currentSource);
  $mergedData = $this->driver->tryMethod('getMergedRecordData');
  $recordType = $this->driver->tryMethod('getRecordFormat');
  $sector = $this->driver->tryMethod('getSector');
  // The final key will be information_provided_by_single, information_provided_by_multiple,
  // material_provided_by_single or material_provided_by_multiple
  $headingType = ($this->driver instanceof \VuFind\RecordDriver\SolrAuthDefault)
    ? 'information' : 'material';

?>
<div class="recordProvidedBy">
  <h2 class="record-organisation-header">
    <?php if ($mergedData && count($mergedData['records']) > 1): ?>
      <?=$this->transEsc($headingType . '_provided_by_multiple', ['%%count%%' => count($mergedData['records'])])?>
    <?php else: ?>
      <?=$this->transEsc($headingType . '_provided_by_single')?>
    <?php endif; ?>
  </h2>
  <div class="record-organisation-box">
     <ul class="<?=(!in_array($recordType, ['ead', 'lido', 'qdc', 'forward'])) ? 'list-group organisations' : 'record-type organisations'?>">
        <?php if ($currentSource === 'narc' && $recordType === 'ead' && $building = $this->driver->tryMethod('getBuildings')): ?>
           <?php ?>
          <li class="record-organisation"><span class="organisation-name"><?=$this->transEsc($building[0])?></span>
        <?php else: ?>
          <li class="record-organisation"><span class="organisation-name"><?=$this->escapeHtml($this->organisationDisplayName($this->driver)) ?></span>
        <?php endif; ?>
        <ul class="record-organisation-info">
        <?php if (isset($currentSource['imageUrl'])): ?>
          <li><img src="<?=$currentSource['imageUrl']?>"></li>
        <?php endif; ?>
        <?php if (isset($currentSource['moreinfoLink'])): ?>
          <li><a href="<?=$currentSource['moreinfoLink']?>"><?=$this->transEsc('More information about organisation')?></a></li>
        <?php endif; ?>
          <?php if ($this->plugin('organisationInfo')->isAvailable() && $organisationInfoId = $this->driver->getOrganisationInfoId()): ?><li class="organisation-page-link" data-organisation="<?=$this->escapeHtmlAttr($organisationInfoId)?>" data-organisation-name="<?=$this->escapeHtmlAttr($currentSourceTranslated)?>" data-organisation-sector="<?=$this->escapeHtmlAttr($sector)?>"></li><?php endif; ?>
          <li class="material-questions-feedback"><?=$this->transEsc('material_questions_feedback')?></li>
          <li><a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'Feedback'))?>" role="button" data-lightbox class="btn btn-primary feedback-record"><?=$this->transEsc('Send feedback on record')?></a></li>
          <?php if ($this->record($this->driver)->repositoryLibraryRequestEnabled('organisation_info')): ?>
            <li class="repository-library-request"><?=$this->transEsc('repository_library_request')?></li>
            <li>
              <?php $user = $this->auth()->getUserObject();
              if ($user): ?>
                <?php if ($this->libraryCards()->getCardsForUser($user)): ?>
                  <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getActionUrl($this->driver, 'RepositoryLibraryRequest'))?>" role="button" data-lightbox class="btn btn-primary repository-library-request-order"><?=$this->transEsc('repository_library_request_order')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
                <?php else: ?>
                  <a href="<?=$this->url('editLibraryCard', ['id' => 'NEW'])?>" class="login hidden-print"><?=$this->transEsc('repository_library_request_add_library_card')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
                <?php endif; ?>
              <?php else: ?>
                <a href="?login=true&catalogLogin=true" class="login hidden-print" role="button" data-lightbox><?=$this->transEsc('repository_library_request_login')?><span class="visually-hidden"> - <?=$this->escapeHtml($this->driver->getTitle())?></span></a>
              <?php endif; ?>
            </li>
          <?php endif; ?>
        </ul>
      </li>
    </ul>
    <?php if ($mergedData && count($mergedData['records']) > 1): ?>
    <ul class="list-group organisations">
      <li>
        <div class="truncate-field other-organisation-links" data-rows="5">
        <?php foreach ($mergedData['records'] as $current): ?>
          <?php if ($current['source'] != $currentSource) : ?>
          <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($current['id'])) ?>" title="<?=$this->transEscAttr("source_{$current['source']}", null, $current['source']) ?>">
            <?=$this->transEsc("source_{$current['source']}", null, $current['source']) ?>
          </a>
          <?php endif; ?>
        <?php endforeach; ?>
        </div>
      </li>
    </ul>
    <?php endif;?>
  </div>
</div>
<!-- END of: finna - record/record-organisation-menu.phtml -->
