<?php // keep old addthis classes as they may have been used to hide these buttons ?>
<li class="share-buttons addthis-share-buttons">
  <div class="share-buttons-toolbox addthis_toolbox addthis_default_style">
    <a
      class="share-button-facebook"
      title="Facebook"
      aria-label="<?=$this->escapeHtmlAttr($this->translate('socialmedia_share_in_facebook') . ' (' . $this->translate('Open in a new window') . ')')?>"
      href="https://www.facebook.com/sharer.php?u=<?=urlencode($shareUrl)?>&amp;title=<?=urlencode($title)?>"
      target="_blank">
        <?=$this->icon('facebook', 'facebook-icon') ?>
    </a>
    <a
      class="share-button-twitter"
      title="Twitter"
      aria-label="<?=$this->escapeHtmlAttr($this->translate('socialmedia_share_in_twitter') . ' (' . $this->translate('Open in a new window') . ')')?>"
      href="https://twitter.com/share?url=<?=urlencode($shareUrl)?>&amp;text=<?=urlencode($title)?>"
      target="_blank">
        <?=$this->icon('twitter', 'twitter-icon') ?>
    </a>
    <a
      class="share-button-pinterest"
      title="Pinterest"
      aria-label="<?=$this->escapeHtmlAttr($this->translate('socialmedia_share_in_pinterest') . ' (' . $this->translate('Open in a new window') . ')')?>"
      href="https://pinterest.com/pin/create/bookmarklet/?url=<?=urlencode($shareUrl)?>&amp;is_video=0&amp;description=<?=urlencode($title)?>"
      target="_blank">
        <?=$this->icon('pinterest', 'pinterest-icon') ?>
    </a>
  </div>
</li>
