<!-- START of: finna - RecordDriver/SolrDefault/core-fields.phtml -->
<? foreach ($coreFields as $key => $current): ?>
  <? $header = $this->transEsc(isset($current['context']['title']) ? $current['context']['title'] : $key); ?>
  <? if ($header): ?>
    <tr class="<?=$current['context']['class'];?>"><th><?=$header?></th><td><?=$current['value']?></td></tr>
  <? else: ?>
    <?=$current['value']?>
  <? endif; ?>
<? endforeach; ?>
<!-- END of: finna - RecordDriver/SolrDefault/core-fields.phtml -->
