<? //Don't add START and END comments ?>
<? if(!empty($data)): ?>
  <div class="truncate-field">
    <? foreach ($data as $index => $item): ?>
      <?
        $additional = [];
        if (!empty($item['method'])) {
          $additional[] = $this->escapeHtml($item['method']);
        }
        if (!empty($item['date'])) {
          $additional[] = $this->escapeHtml($item['date']);
        }
      ?>
      <?=$index > 0 ? '<br/>' : '' ?><?=$this->escapeHtml($item['name']) ?><? if (!empty($additional)): ?>, <?=implode(' ', $additional) ?><? endif; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>
