<?php
  $formatter = $this->recordDataFormatter($this->driver);
  $coreFields = $formatter->getData($formatter->getDefaults($this->defaults ?? 'core'));
  $accessLevel = $this->driver->getAccessLevel();
  $restrictedView = empty($accessLevel) ? false : true;
  $searchOptions = $this->searchOptions($this->driver->getSourceIdentifier());
?>
<?php if ($searchOptions->showRestrictedViewWarning() && $restrictedView): ?>
  <?=$this->render('error/restrictedViewWarning.phtml')?>
<?php endif; ?>
<?php if (!empty($coreFields)): ?>
  <table <?php if (!empty($this->tableId)): ?>id="<?=$this->tableId ?>" <?php endif; ?>class="table table-striped">
    <caption class="visually-hidden"><?=$this->transEsc($this->caption ?? 'Bibliographic Details')?></caption>
    <?php foreach ($coreFields as $current): ?>
      <tr class="record__biblio-value"><th><?=$this->transEsc($current['label'])?>:</th><td><?=$current['value']?></td></tr>
    <?php endforeach; ?>
    <?php $holdings = $this->driver->getFullTextHoldings();
    if (!empty($holdings)): ?>
      <tr>
        <th><?=$this->transEsc('Linked Full Text') . ':'?></th>
        <td>
          <ul>
            <?php
            foreach ($holdings as $holding):
              if (!empty($holding)): ?>
                <li>
                  <a href="<?=$this->escapeHtmlAttr($holding['URL'])?>"><?=$this->escapeHtml($holding['Name'])?></a>
                  <span class="coverage-statement"><?=$this->escapeHtml($holding['CoverageStatement'])?></span>
                  <?php if (!empty($holding['EmbargoDescription'])): ?>
                    <span class="embargo-description">(<?=$this->escapeHtml($holding['EmbargoDescription'])?>)</span>
                  <?php endif; ?>
                </li>
              <?php endif;
            endforeach; ?>
          </ul>
        </td>
      </tr>
    <?php endif; ?>
  </table>
<?php endif; ?>
