<? $records = $this->cart()->getRecordDetails(); if (!empty($records)): ?>
  <hr/>
  <ul class="unstyled">
  <? foreach ($records as $i => $record): ?>
    <li>
      <label class="checkbox">
        <?=$this->record($record)->getCheckbox('cart')?>
        <a title="<?=$this->transEsc('View Record')?>" href="<?=$this->recordLink()->getUrl($record)?>"><?=$this->escapeHtml($record->getBreadcrumb())?></a>
      </label>
    </li>
  <? endforeach; ?>
  </ul>
<? else: ?>
  <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
<? endif; ?>