<?
    // Set page title.
    $this->headTitle($this->translate('Export Favorites'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span></li>')
    . '<li><a href="' .$this->url('cart-home'). '">' .$this->transEsc('Cart'). '</a> <span class="divider">&gt;</span></li>'
    . '<li class="active">' . $this->transEsc('Export Favorites') . '</li>';
?>
<h3 class="hideinlightbox"><?=$this->transEsc('Export Favorites')?></h3>

<?=$this->flashmessages()?>

<? if (!empty($this->exportOptions)): ?>
  <form class="form-inline" method="post" action="<?=$this->url('cart-export')?>" name="exportForm" title="<?=$this->transEsc('Export Items')?>">
    <? foreach ($this->records as $current): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtml($current->getResourceSource() . '|' . $current->getUniqueId())?>" />
    <? endforeach; ?>
    <div class="control-group">
      <label class="control-label"><?=$this->transEsc('Title')?></label>
      <div class="controls">
      <? if(count($this->records) > 1): ?>
        <div class="item-list">
          <ul>
            <? foreach ($this->records as $current): ?>
              <li><?=$this->escapeHtml($current->getBreadcrumb())?></li>
            <? endforeach; ?>
          </ul>
        </div>
      <? else: ?>
        <span class="uneditable-input"><?=$this->records[0]->getBreadcrumb() ?></span>
      <? endif; ?>
      </div>
    </div>
    <div class="control-group">
      <label class="control-label" for="format"><?=$this->transEsc('Format')?>:</label>
      <div class="controls">
        <select name="format" id="format">
          <? foreach ($this->exportOptions as $exportOption): ?>
            <option value="<?=$this->escapeHtml($exportOption)?>"><?=$this->transEsc($exportOption)?></option>
          <? endforeach; ?>
        </select>
      </div>
    </div>
    <div class="control-group">
      <div class="controls">
        <input class="btn" type="submit" name="submit" value="<?=$this->transEsc('Export')?>"/>
      </div>
    </div>
  </form>
<? endif; ?>
<?
  $items = $this->transEsc('items');
  $script = <<<JS
    var list = $('.item-list');
    var items = list.find('li').length;
    var bubble = list.html();
    list.html('<span class="btn">'+items+' {$items}</span>');
    list.find('.btn').popover({html:true,content:bubble,placement:"bottom"});
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>