<?
    // Set page title.
    $this->headTitle($this->translate('bookbag_save_selected'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span> </li>') .
        '<li class="active">' . $this->transEsc('bookbag_save_selected') . '</li>';
?>
<h3 class="hideinlightbox"><?=$this->transEsc('bookbag_save_selected')?></h3>

<?=$this->flashmessages()?>

<form class="form-horizontal" method="post" action="<?=$this->url('cart-save')?>" name="bulkSave">
  <? $idParams = array(); ?>
  <? foreach ($this->records as $current): ?>
    <? $idParams[] = urlencode('ids[]') . '=' . urlencode($current->getResourceSource() . '|' . $current->getUniqueId()) ?>
    <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($current->getResourceSource() . '|' . $current->getUniqueId())?>" />
  <? endforeach; ?>
  <div class="control-group">
    <label class="control-label"><?=$this->transEsc('Title')?></label>
    <div class="controls">
    <? if(count($this->records) > 1): ?>
      <button type="button" class="btn hidden" data-toggle="collapse" data-target="#itemhide">
        <?=count($this->records).' '.$this->transEsc('items') ?>
      </button>
      <div id="itemhide" class="collapse in">
        <ul>
          <? foreach ($this->records as $current): ?>
            <li><?=$this->escapeHtml($current->getBreadcrumb())?></li>
          <? endforeach; ?>
        </ul>
      </div>
    <? else: ?>
      <span class="uneditable-input"><?=$this->records[0]->getBreadcrumb() ?></span>
    <? endif; ?>
    </div>
  </div>

  <div class="control-group">
    <label class="control-label" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <div class="controls">
      <select id="save_list" class="pull-left" name="list">
        <? if (count($this->lists) > 0): ?>
          <? foreach ($this->lists as $list): ?>
            <option value="<?=$list['id'] ?>"<? if ($list['id']==$this->userList()->lastUsed()): ?> selected="selected"<? endif; ?>><?=$this->escapeHtml($list['title'])?></option>
          <? endforeach; ?>
        <? else: ?>
          <option value=""><?=$this->transEsc('My Favorites') ?></option>
        <? endif; ?>
      </select>
      <a class="btn btn-link" id="make-list"  href="<?=$this->url('editList', array('id' => 'NEW')) . '?' . implode('&', $idParams) ?>" title="<?=$this->transEsc('Create a List') ?>"><?=count($this->lists) > 0 ? $this->transEsc('or').' '.$this->transEsc('Create a List') : $this->transEsc('Create a List'); ?></a>
    </div>
  </div>

  <? if ($this->usertags()->getMode() !== 'disabled'): ?>
    <div class="control-group">
      <label class="control-label" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
      <div class="controls">
        <input class="mainFocus" id="add_mytags" type="text" name="mytags" value=""/>
      </div>
    </div>
  <? endif; ?>
  <div class="control-group">
    <div class="controls">
      <input class="btn" type="submit" name="submit" value="<?=$this->transEsc('Save') ?>"/>
    </div>
  </div>
</form>

<?
  $script = <<<JS
    $('button.btn.hidden').removeClass('hidden');
    $('.collapse.in').removeClass('in');
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET') ?>