<!-- finc: RecordDriver - SolrLido - data-accessNote -->
<?php
/**
origin: finc/RecordDriver/SolrLido/
called by view helper/controller:
usage:
modified for finc-SolrLido:
 * finc-SolrLido specific template
configured in: {}
 */
?>
<?php foreach ($data as $field): ?>
  <?php if (!empty($field['uri'])): ?>
    <a href="<?=$this->escapeHtmlAttr($field['uri'])?>"><?=$this->escapeHtml($field['term'])?>
  <?php endif; ?>
  <?php if (!empty($field['uri'])): ?>
    </a>
  <?php endif; ?>
  <br>
<?php endforeach; ?>
<!-- finc: RecordDriver - SolrLido - data-accessNote - END -->
