<?
  // Load the EDS-specific advanced search controls and inject them into the
  // standard advanced search layout:
  $this->extraAdvancedControls = $this->render('search/advanced/eds.phtml');
  $this->buildPageOverride = '/search/advanced/build_page_eds.phtml';

  ob_start();
?>
<div id="new_group_template">
  <div class="adv-group eds-adv well">
    <input type="hidden" name="join" value="AND"/>
    <input type="hidden" name="bool0[]" value="AND"/>
    <label class="adv-group-label"><?=$this->transEsc("adv_search_label")?>:</label>
    <? for ($search = 0; $search < 3; $search++): ?>
      <? if ($search === 0): ?>
        <div id="new_search_template">
      <? endif; ?>
      <div class="adv-search">
        <? if ($search === 0): ?><input type="hidden" value="AND" class="first-op"/><? endif; ?>
        <select id="search_op0_<?=$search ?>" name="op0[]" class="adv-term-op form-control">
          <option value="AND"><?=$this->transEsc("AND")?></option>
          <option value="OR"><?=$this->transEsc("OR")?></option>
          <option value="NOT"><?=$this->transEsc("NOT")?></option>
        </select>
        <input id="search_lookfor0_<?=$search ?>" name="lookfor0[]" class="adv-term-input form-control" type="text" value=""/>
        <span class="help-block hidden-xs"><?=$this->transEsc("in")?></span>
        <select id="search_type0_<?=$search ?>" name="type0[]" class="adv-term-type form-control">
          <? foreach ($this->options->getAdvancedHandlers() as $searchVal => $searchDesc): ?>
            <option value="<?=$this->escapeHtml($searchVal)?>"><?=$this->transEsc($searchDesc)?></option>
          <? endforeach; ?>
        </select>
        <a class="adv-term-remove"><i class="fa fa-times"></i></a>
      </div>
      <? if ($search === 0): ?>
        </div>
      <? endif; ?>
    <? endfor; ?>
    <i class="fa fa-plus-circle search_place_holder hidden" aria-hidden="true"></i> <a href="#" class="add_search_link hidden"><?=$this->transEsc("add_search")?></a>
  </div>
</div>
<?
  $this->formOverride = ob_get_contents();
  ob_end_clean();

  echo $this->render('search/advanced/layout.phtml');
?>
