<?
    // Set up page title:
    $this->headTitle($this->translate('User Account'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Account') . '</li>';
?>
<h2><?=$this->transEsc('User Account')?></h2>
<?=$this->flashmessages()?>

<form method="post" action="" name="accountForm" id="accountForm" class="form-horizontal">
  <?=$this->auth()->getCreateFields()?>
  <?=$this->recaptcha()->html($this->useRecaptcha) ?>
  <div class="form-group">
    <div class="col-sm-10 col-sm-offset-3">
      <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEsc('Submit')?>"/>
    </div>
  </div>
</form>
