<h2><?=$this->transEsc('delete_selected_favorites')?></h2>
 <form action="<?=$this->url('myresearch-delete')?>" method="post" name="bulkDelete" data-lightbox-onclose="VuFind.refreshPage">
  <div id="popupMessages"><?=$this->flashmessages()?></div>
  <div id="popupDetails">
    <?php if (!$this->list): ?>
      <div class="alert alert-info"><?=$this->transEsc("fav_delete_warn") ?></div>
    <?php else: ?>
      <h3><?=$this->transEsc("List") ?>: <?=$this->escapeHtml($this->list->title) ?></h3>
    <?php endif; ?>

    <?php foreach ($this->records as $favorite): ?>
      <strong><?=$this->transEsc('Title') ?>:</strong>
      <?=$this->escapeHtml($favorite->getBreadcrumb())?><br />
    <?php endforeach; ?>
    <br />
    <input class="btn btn-primary" type="submit" name="submit" value="<?=$this->transEscAttr('Delete')?>"/>
    <?php foreach ($this->deleteIDS as $deleteID): ?>
      <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($deleteID)?>" />
    <?php endforeach; ?>
      <input type="hidden" name="listID" value="<?=$this->list?$this->escapeHtmlAttr($this->list->id):''?>" />
  </div>
</form>
