<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
?>
<h4><?=$this->transEsc('Your Account')?></h4>
<div class="myresearch-menu account-menu">
  <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Favorites')?>
    </a>
  <?php endif; ?>
  <?php if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <?php if ($this->ils()->checkCapability('getMyTransactions', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-checkedout')?>" class="checkedout<?=$this->active == 'checkedout' ? ' active' : ''?>">
        <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('Checked Out Items')?>
        <span class="status hidden checkedout-status"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-historicloans')?>"<?=$this->active == 'historicloans' ? ' class="active"' : ''?>">
        <i class="fa fa-fw fa-history" aria-hidden="true"></i> <?=$this->transEsc('Loan History')?>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkCapability('getMyHolds', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-holds')?>"<?=$this->active == 'holds' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-flag" aria-hidden="true"></i> <?=$this->transEsc('Holds and Recalls')?>
        <i class="status hidden holds-status fa fa-spin fa-spinner" aria-hidden="true"></i>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkFunction('StorageRetrievalRequests', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>"<?=$this->active == 'storageRetrievalRequests' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkFunction('ILLRequests', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-illrequests')?>"<?=$this->active == 'ILLRequests' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkCapability('getMyFines', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-fines')?>"<?=$this->active == 'fines' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-usd" aria-hidden="true"></i> <?=$this->transEsc('Fines')?>
        <span class="status hidden fines-status"><i class="fa fa-spin fa-spinner" aria-hidden="true"></i></span>
      </a>
    <?php endif; ?>
    <?php if ($this->ils()->checkCapability('getMyProfile', $capabilityParams)): ?>
      <a href="<?=$this->url('myresearch-profile')?>"<?=$this->active == 'profile' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
      </a>
    <?php endif; ?>
    <?php if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>"<?=$this->active == 'librarycards' ? ' class="active"' : ''?>>
        <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
      </a>
    <?php endif; ?>
  <?php endif; ?>
  <?php if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login"<?=$this->active == 'history' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
  <?php endif; ?>
  <?php if ($user): ?>
    <a href="<?=$this->url('myresearch-logout')?>">
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <?php endif; ?>
</div>
<?php if ($user && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="myresearch-menu">
    <a href="<?=$this->url('myresearch-changepassword') ?>"<?=$this->active == 'newpassword' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
    </a>
  </div>
<?php endif; ?>
<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="myresearch-menu">
    <a href="<?=$this->url('myresearch-favorites')?>"<?=$this->active == 'favorites' ? ' class="active"' : ''?>>
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <?php $lists = $user->getLists() ?>
    <?php foreach ($lists as $list): ?>
      <a href="<?=$this->url('userList', ['id' => $list['id']])?>"<?=$this->active == 'list' . $list['id'] ? ' class="active"' : ''?>>
        <?=$this->escapeHtml($list['title'])?>
        <span class="badge"><?=$list->cnt?></span>
      </a>
    <?php endforeach; ?>
    <a href="<?=$this->url('editList', ['id' => 'NEW'])?>">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<?php endif ?>
