<h4><?=$this->transEsc('Your Account')?></h4>
<div class="list-group">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Favorites')?>
    </a>
  <? endif; ?>
  <? if ('ils-none' !== $this->ils()->getOfflineMode()): ?>
    <? if ($this->ils()->checkCapability('getMyTransactions')): ?>
      <a href="<?=$this->url('myresearch-checkedout')?>" class="list-group-item<?=$this->active == 'checkedout' ? ' active' : ''?>">
        <i class="fa fa-fw fa-book" aria-hidden="true"></i> <?=$this->transEsc('Checked Out Items')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyHolds')): ?>
      <a href="<?=$this->url('myresearch-holds')?>" class="list-group-item<?=$this->active == 'holds' ? ' active' : ''?>">
        <i class="fa fa-fw fa-flag" aria-hidden="true"></i> <?=$this->transEsc('Holds and Recalls')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('StorageRetrievalRequests')): ?>
      <a href="<?=$this->url('myresearch-storageretrievalrequests')?>" class="list-group-item<?=$this->active == 'storageRetrievalRequests' ? ' active' : ''?>">
        <i class="fa fa-fw fa-archive" aria-hidden="true"></i> <?=$this->transEsc('Storage Retrieval Requests')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkFunction('ILLRequests')): ?>
    <a href="<?=$this->url('myresearch-illrequests')?>" class="list-group-item<?=$this->active == 'ILLRequests' ? ' active' : ''?>">
      <i class="fa fa-fw fa-exchange" aria-hidden="true"></i> <?=$this->transEsc('Interlibrary Loan Requests')?>
    </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyFines')): ?>
      <a href="<?=$this->url('myresearch-fines')?>" class="list-group-item<?=$this->active == 'fines' ? ' active' : ''?>">
        <i class="fa fa-fw fa-usd" aria-hidden="true"></i> <?=$this->transEsc('Fines')?>
      </a>
    <? endif; ?>
    <? if ($this->ils()->checkCapability('getMyProfile')): ?>
      <a href="<?=$this->url('myresearch-profile')?>" class="list-group-item<?=$this->active == 'profile' ? ' active' : ''?>">
        <i class="fa fa-fw fa-user" aria-hidden="true"></i> <?=$this->transEsc('Profile')?>
      </a>
    <? endif; ?>
    <? $user = $this->auth()->isLoggedIn(); if ($user && $user->libraryCardsEnabled()): ?>
      <a href="<?=$this->url('librarycards-home')?>" class="list-group-item<?=$this->active == 'librarycards' ? ' active' : ''?>">
        <i class="fa fa-fw fa-barcode" aria-hidden="true"></i> <?=$this->transEsc('Library Cards')?>
      </a>
    <? endif; ?>
  <? endif; ?>
  <? if ($this->accountCapabilities()->getSavedSearchSetting() === 'enabled'): ?>
    <a href="<?=$this->url('search-history')?>?require_login" class="list-group-item<?=$this->active == 'history' ? ' active' : ''?>">
      <i class="fa fa-fw fa-search" aria-hidden="true"></i> <?=$this->transEsc('history_saved_searches')?>
    </a>
  <? endif; ?>
  <? if ($user = $this->auth()->isLoggedIn()): ?>
    <a href="<?=$this->url('myresearch-logout')?>" class="list-group-item">
      <i class="fa fa-fw fa-sign-out" aria-hidden="true"></i> <?=$this->transEsc("Log Out")?>
    </a>
  <? endif; ?>
</div>
<? if ($this->auth()->isLoggedIn() && $this->auth()->getManager()->supportsPasswordChange()): ?>
  <h4><?=$this->transEsc('Preferences')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-changepassword') ?>" class="list-group-item<?=$this->active == 'newpassword' ? ' active' : ''?>">
      <i class="fa fa-fw fa-lock" aria-hidden="true"></i> <?=$this->transEsc('Change Password') ?>
    </a>
  </div>
<? endif; ?>
<? if ($this->userlist()->getMode() !== 'disabled' && $user = $this->auth()->isLoggedIn()): ?>
  <h4><?=$this->transEsc('Your Lists')?></h4>
  <div class="list-group">
    <a href="<?=$this->url('myresearch-favorites')?>" class="list-group-item<?=$this->active == 'favorites' ? ' active' : ''?>">
      <i class="fa fa-fw fa-star" aria-hidden="true"></i> <?=$this->transEsc('Your Favorites')?>
    </a>
    <? $lists = $user->getLists() ?>
    <? foreach ($lists as $list): ?>
        <a href="<?=$this->url('userList', array('id' => $list['id']))?>" class="list-group-item<?=$this->active == 'list' . $list['id'] ? ' active' : ''?>">
          <?=$this->escapeHtml($list['title'])?>
          <span class="badge"><?=$list->cnt?></span>
        </a>
    <? endforeach; ?>
    <a href="<?=$this->url('editList', array('id'=>'NEW'))?>" class="list-group-item">
      <i class="fa fa-fw fa-plus" aria-hidden="true"></i> <?=$this->transEsc('Create a List') ?>
    </a>
  </div>
<? endif ?>
