<?php
  $user = $this->auth()->isLoggedIn();
  $patron = $user ? $this->auth()->getILSPatron() : false;
  $capabilityParams = $patron ? ['patron' => $patron] : [];
  $ilsOnline = ('ils-none' !== $this->ils()->getOfflineMode());
?>
<?php
  $showItem = true;
  if ($this->name === 'favorites') {
      $showItem = $this->userlist()->getMode() !== 'disabled';
  }
  if ($this->name === 'librarycards') {
      $showItem = $ilsOnline && $user && $user->libraryCardsEnabled();
  }
  if ($this->name === 'dgcontent') {
      $showItem = $this->overdrive()->showMyContentLink();
  }
  if ($this->name === 'history') {
      $showItem = $this->accountCapabilities()->getSavedSearchSetting() === 'enabled';
  }
  if ($this->name === 'logout') {
      $showItem = $user;
  }
  if (isset($this->ilsCapability)) {
      $showItem = $ilsOnline && $this->ils()->checkCapability($this->ilsCapability, $capabilityParams);
  }
  if (isset($this->ilsFunction)) {
      $showItem = $ilsOnline && $this->ils()->checkFunction('getMyTransactionHistory', $capabilityParams);
  }
  if ($this->name === 'fines' && !isset($this->icon)) {
      // Use a "fines" icon based on the configured default currency symbol:
      $this->icon = 'currency-' . strtolower($this->config()->get('config')->Site->defaultCurrency ?? 'usd');
  }

?>
<?php if ($showItem): ?>
  <li>
    <a href="<?=$this->url($this->route)?>" class="<?=$this->name?> icon-link<?=$this->active == $this->name ? ' active' : ''?>">
      <?=$this->icon($this->icon, 'icon-link__icon') ?>
      <span class="icon-link__label"><?=$this->transEsc($this->label)?></span>
      <?php if ($this->status ?? false): ?>
        <span class="<?=strtolower($this->name)?>-status status hidden"><?=$this->icon('spinner') ?></span>
      <?php endif; ?>
    </a>
  </li>
<?php endif; ?>
