<?php
  $user = $this->auth()->isLoggedIn();
  $menuItemsConfig = $this->config()->get('MyResearchMenu')?->MenuItems?->toArray() ?? [];
  $menuItemsDefault = [
    'favorites' => [
      'label' => 'Favorites',
      'route' => 'myresearch-favorites',
      'icon' => 'user-favorites',
    ],
    'checkedout' => [
      'label' => 'Checked Out Items',
      'route' => 'myresearch-checkedout',
      'ilsCapability' => 'getMyTransactions',
      'icon' => 'user-checked-out',
      'status' => true,
    ],
    'historicloans' => [
      'label' => 'Loan History',
      'route' => 'checkouts-history',
      'ilsFunction' => 'getMyTransactionHistory',
      'icon' => 'user-loan-history',
    ],
    'holds' => [
      'label' => 'Holds and Recalls',
      'route' => 'holds-list',
      'ilsCapability' => 'getMyHolds',
      'icon' => 'user-holds',
      'status' => true,
    ],
    'storageRetrievalRequests' => [
      'label' => 'Storage Retrieval Requests',
      'route' => 'myresearch-storageretrievalrequests',
      'ilsFunction' => 'StorageRetrievalRequests',
      'icon' => 'user-storage-retrievals',
      'status' => true,
    ],
    'ILLRequests' => [
      'label' => 'Interlibrary Loan Requests',
      'route' => 'myresearch-illrequests',
      'ilsFunction' => 'ILLRequests',
      'icon' => 'user-ill-requests',
      'status' => true,
    ],
    'fines' => [
      'label' => 'Fines',
      'route' => 'myresearch-fines',
      'ilsCapability' => 'getMyFines',
      'status' => true,
    ],
    'profile' => [
      'label' => 'Profile',
      'route' => 'myresearch-profile',
      'icon' => 'profile',
    ],
    'librarycards' => [
      'label' => 'Library Cards',
      'route' => 'librarycards-home',
      'icon' => 'barcode',
    ],
    'dgcontent' => [
      'label' => 'Overdrive Content',
      'route' => 'overdrive-mycontent',
      'icon' => 'overdrive',
    ],
    'history' => [
      'label' => 'Search History',
      'route' => 'search-history',
      'icon' => 'search',
    ],
    'logout' => [
      'label' => 'Log Out',
      'route' => 'myresearch-logout',
      'icon' => 'sign-out',
    ],
  ];
  $menuItems = !empty($menuItemsConfig) ? $menuItemsConfig : $menuItemsDefault;
?>

<button class="close-offcanvas btn btn-link" data-toggle="offcanvas"><?=$this->transEsc('navigate_back') ?></button>
<h3 id="acc-menu-acc-header"><?=$this->transEsc('Your Account')?></h3>
<nav class="myresearch-menu" aria-labelledby="acc-menu-acc-header">
  <ul class="account-menu">
    <?php foreach ($menuItems as $key => $item): ?>
      <?=$this->render('myresearch/menu-item.phtml', ['name' => $key, 'active' => $this->active, ...$item])?>
    <?php endforeach; ?>
  </ul>
</nav>
<?php if ($user && $this->userlist()->getMode() !== 'disabled'): ?>
  <h3 id="acc-menu-lists-header"><?=$this->transEsc('Your Lists')?></h3>
  <nav class="myresearch-menu" aria-labelledby="acc-menu-lists-header">
    <ul>
      <li>
        <a href="<?=$this->url('myresearch-favorites')?>" class="icon-link <?=$this->active == 'favorites' ? 'active' : ''?>">
          <?=$this->icon('user-favorites', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Your Favorites')?></span>
        </a>
      </li>
      <?php
        // Use a variable so that we can output this nicely without whitespace that would get underlined:
        $publicInd = $this->icon(
            'user-public-list-indicator',
            [
              'class' => 'user-list__public-icon',
              'title' => $this->transEscAttr('public_list_indicator'),
            ]
        );
        $publicInd .= '<span class="sr-only">(' . $this->transEsc('public_list_indicator') . ')</span>';
      ?>
  
      <?php $lists = $user->getLists() ?>
      <?php foreach ($lists as $list): ?>
      <li>
        <a class="user-list-link icon-link <?=$this->active == 'list' . $list['id'] ? ' active' : ''?>" href="<?=$this->url('userList', ['id' => $list['id']])?>">
          <?=$this->icon('user-list', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->escapeHtml($list['title'])?></span>
          <?=$list['public'] ? $publicInd : ''?>
          <span class="badge"><?=$list->cnt ?></span>
        </a>
      </li>
      <?php endforeach; ?>
      <li>
        <a href="<?=$this->url('editList', ['id' => 'NEW'])?>" class="icon-link <?=$this->active == 'editlist/NEW' ? ' active' : ''?>">
          <?=$this->icon('ui-add', 'icon-link__icon') ?>
          <span class="icon-link__label"><?=$this->transEsc('Create a List') ?></span>
        </a>
      </li>
    </ul>
  </nav>
<?php endif ?>
