<?
  // Set up page title:
  $this->headTitle($this->translate('Storage Retrieval Requests'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li><a href="' . $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('Storage Retrieval Requests') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2><?=$this->transEsc('Storage Retrieval Requests') ?></h2>

  <?=$this->flashmessages()?>

  <?=$this->context($this)->renderInContext('librarycards/selectcard.phtml', ['user' => $this->auth()->isLoggedIn()]); ?>

  <? if (!empty($this->recordList)): ?>
    <? if ($this->cancelForm): ?>
      <form name="cancelForm" class="inline" method="post" id="cancelStorageRetrievalRequest">
        <input type="hidden" id="submitType" name="cancelSelected" value="1"/>
        <input type="hidden" id="cancelConfirm" name="confirm" value="0"/>
        <div class="btn-group">
          <input id="cancelSelected" name="cancelSelected" type="submit" value="<?=$this->transEsc("storage_retrieval_request_cancel_selected") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_storage_retrieval_request_cancel_selected_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelSelected');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
        <div class="btn-group">
          <input id="cancelAll" name="cancelAll" type="submit" value="<?=$this->transEsc("storage_retrieval_request_cancel_all") ?>" class="btn btn-default dropdown-toggle" data-toggle="dropdown"/>
          <ul class="dropdown-menu">
            <li class="disabled"><a><?=$this->transEsc("confirm_storage_retrieval_request_cancel_all_text") ?></a></li>
            <li><a href="#" onClick="$('#cancelConfirm').val(1);$('#submitType').attr('name','cancelAll');$(this).parents('form').submit(); return false;"><?=$this->transEsc('confirm_dialog_yes') ?></a></li>
            <li><a href="#" onClick="return false;"><?=$this->transEsc('confirm_dialog_no')?></a></li>
          </ul>
        </div>
    <? endif; ?>

    <? $iteration = 0; ?>
    <? foreach ($this->recordList as $resource): ?>
      <? $iteration++; ?>
      <? $ilsDetails = $resource->getExtraDetail('ils_details'); ?>
      <div id="record<?=$this->escapeHtmlAttr($resource->getUniqueId()) ?>" class="result">
        <? if ($this->cancelForm && isset($ilsDetails['cancel_details'])): ?>
          <? $safeId = preg_replace('/[^a-zA-Z0-9]/', '', $resource->getUniqueId()); ?>
          <div class="checkbox">
            <input type="hidden" name="cancelAllIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" />
            <label class="pull-left flip">
              <input type="checkbox" name="cancelSelectedIDS[]" value="<?=$this->escapeHtmlAttr($ilsDetails['cancel_details']) ?>" id="checkbox_<?=$safeId?>" />
            </label>
          </div>
        <? endif; ?>

        <?
          $coverDetails = $this->record($resource)->getCoverDetails('storageretrievalrequests', 'small', $this->recordLink()->getUrl($resource));
          $cover = $coverDetails['html'];
          $thumbnail = false;
          $thumbnailAlignment = $this->record($resource)->getThumbnailAlignment('account');
          if ($cover):
            ob_start(); ?>
            <div class="media-<?=$thumbnailAlignment ?> <?=$this->escapeHtmlAttr($coverDetails['size'])?>">
              <?=$cover ?>
            </div>
            <? $thumbnail = ob_get_contents(); ?>
          <? ob_end_clean(); ?>
        <? endif; ?>
        <div class="media">
          <? if ($thumbnail && $thumbnailAlignment == 'left'): ?>
            <?=$thumbnail ?>
          <? endif ?>
          <div class="media-body">
            <?
              // If this is a non-missing Solr record, we should display a link:
              if (is_a($resource, 'VuFind\\RecordDriver\\SolrDefault') && !is_a($resource, 'VuFind\\RecordDriver\\Missing')) {
                $title = $resource->getTitle();
                $title = empty($title) ? $this->transEsc('Title not available') : $this->escapeHtml($title);
                echo '<a href="' . $this->recordLink()->getUrl($resource)
                  . '" class="title">' . $title . '</a>';
              } else if (isset($ilsDetails['title']) && !empty($ilsDetails['title'])){
                // If the record is not available in Solr, perhaps the ILS driver sent us a title we can show...
                echo $this->escapeHtml($ilsDetails['title']);
              } else {
                // Last resort -- indicate that no title could be found.
                echo $this->transEsc('Title not available');
              }
            ?><br/>
            <? $listAuthors = $resource->getPrimaryAuthors(); if (!empty($listAuthors)): ?>
              <?=$this->transEsc('by')?>:
              <a href="<?=$this->record($resource)->getLink('author', $listAuthors[0])?>"><?=$this->escapeHtml($listAuthors[0])?></a><? if (count($listAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?><br/>
            <? endif; ?>

            <? if (count($resource->getFormats()) > 0): ?>
              <?=$this->record($resource)->getFormatList() ?>
              <br/>
            <? endif; ?>
            <? if (isset($ilsDetails['volume']) && !empty($ilsDetails['volume'])): ?>
              <strong><?=$this->transEsc('Volume')?>:</strong> <?=$this->escapeHtml($ilsDetails['volume'])?>
              <br />
            <? endif; ?>

            <? if (isset($ilsDetails['publication_year']) && !empty($ilsDetails['publication_year'])): ?>
              <strong><?=$this->transEsc('Year of Publication')?>:</strong> <?=$this->escapeHtml($ilsDetails['publication_year'])?>
              <br />
            <? endif; ?>

            <? /* Depending on the ILS driver, the "location" value may be a string or an ID; figure out the best
               value to display... */ ?>
            <? $pickupDisplay = ''; ?>
            <? $pickupTranslate = false; ?>
            <? if (isset($ilsDetails['location'])): ?>
              <? if ($this->pickup): ?>
                <? foreach ($this->pickup as $library): ?>
                  <? if ($library['locationID'] == $ilsDetails['location']): ?>
                    <? $pickupDisplay = $library['locationDisplay']; ?>
                    <? $pickupTranslate = true; ?>
                  <? endif; ?>
                <? endforeach; ?>
              <? endif; ?>
              <? if (empty($pickupDisplay)): ?>
                <? $pickupDisplay = $ilsDetails['location']; ?>
              <? endif; ?>
            <? endif; ?>
            <? if (!empty($pickupDisplay)): ?>
              <strong><?=$this->transEsc('pick_up_location') ?>:</strong>
              <?=$pickupTranslate ? $this->transEsc($pickupDisplay) : $this->escapeHtml($pickupDisplay)?>
              <br />
            <? endif; ?>

            <? if (!empty($ilsDetails['create'])): ?>
              <strong><?=$this->transEsc('Created') ?>:</strong> <?=$this->escapeHtml($ilsDetails['create']) ?>
              <? if (!empty($ilsDetails['expire'])): ?>|<? endif; ?>
            <? endif; ?>
            <? if (!empty($ilsDetails['expire'])): ?>
              <strong><?=$this->transEsc('Expires') ?>:</strong> <?=$this->escapeHtml($ilsDetails['expire']) ?>
            <? endif; ?>
            <br />

            <? if (isset($this->cancelResults['items'])): ?>
              <? foreach ($this->cancelResults['items'] as $itemId=>$cancelResult): ?>
                <? if ($itemId == $ilsDetails['item_id'] && $cancelResult['success'] == false): ?>
                  <div class="alert alert-danger"><?=$this->transEsc($cancelResult['status']) ?><? if ($cancelResult['sysMessage']) echo ' : ' . $this->transEsc($cancelResult['sysMessage']); ?></div>
                <? endif; ?>
              <? endforeach; ?>
            <? endif; ?>

            <? if (isset($ilsDetails['processed']) && $ilsDetails['processed']): ?>
              <div class="text-success"><?=$this->transEsc("storage_retrieval_request_processed") . (is_string($ilsDetails['processed']) ? ': ' . $ilsDetails['processed'] : '') ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['available']) && $ilsDetails['available']): ?>
              <div class="text-success"><?=$this->transEsc("storage_retrieval_request_available") ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['canceled']) && $ilsDetails['canceled']): ?>
              <div class="text-success"><?=$this->transEsc("storage_retrieval_request_canceled") . (is_string($ilsDetails['canceled']) ? ': ' . $ilsDetails['canceled'] : '') ?></div>
            <? endif; ?>
            <? if (isset($ilsDetails['cancel_link'])): ?>
              <p><a href="<?=$this->escapeHtmlAttr($ilsDetails['cancel_link']) ?>"><?=$this->transEsc("storage_retrieval_request_cancel") ?></a></p>
            <? endif; ?>
          </div>
          <? if ($thumbnail && $thumbnailAlignment == 'right'): ?>
            <?=$thumbnail ?>
          <? endif ?>
        </div>
      </div>
    <? endforeach; ?>
    <? if ($this->cancelForm): ?></form><? endif; ?>
  <? else: ?>
    <?=$this->transEsc('You do not have any storage retrieval requests placed') ?>.
  <? endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'storageRetrievalRequests'])?>
</div>
