<!-- record - SAVE.phtml -->
<?
  // Set page title.
  $this->headTitle($this->translate('Save'));

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->searchMemory()->getLastSearchLink($this->transEsc('Search'), '', '</li> ')
    . '<li>' . $this->recordLink()->getBreadcrumb($this->driver) . '</li> '
    . '<li class="active">' . $this->transEsc('Save') . '</li>';
?>
<h2><?=$this->transEsc("add_favorite_prefix") ?> <span class="title-in-heading"><?=$this->escapeHtml($this->driver->getBreadcrumb())?></span> <?=$this->transEsc("add_favorite_suffix") ?></h2>
<form id="edit-save-form" method="post" action="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" name="saveRecord" data-lightbox-onclose="checkSaveStatuses();">
  <input type="hidden" name="submit" value="1" />
  <input type="hidden" name="id" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueId()) ?>" />
  <input type="hidden" name="source" value="<?=$this->escapeHtmlAttr($this->driver->getSourceIdentifier())?>" />
  <? if (!empty($this->containingLists)): ?>
    <p><?=$this->transEsc('This item is already part of the following list/lists') ?>:
    <? foreach ($this->containingLists as $i=>$list): ?>
      <a href="<?=$this->url('userList', array('id' => $list['id'])) ?>"><?=$this->escapeHtml($list['title'])?></a><? if($i<count($this->containingLists)-1): ?>, <? endif; ?>
    <? endforeach; ?>
    </p><hr/>
  <? endif; ?>

  <?/* Only display the list drop-down if the user has lists that do not contain
  this item OR if they have no lists at all and need to create a default list */?>
  <? $showLists = (!empty($this->nonContainingLists) || (empty($this->containingLists) && empty($this->nonContainingLists))); ?>

  <div class="row">
    <? if ($showLists): ?>
      <label class="medium-3 columns" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <? endif; ?>
    <div class="medium-9 columns">
    <? if ($showLists): ?>
      <select class="auto-width" id="save_list" name="list">
      <? if ($this->nonContainingLists): ?>
        <? foreach ($this->nonContainingLists as $list): ?>
          <option value="<?=$list['id'] ?>"<? if ($list['id']==$this->userList()->lastUsed()): ?> selected="selected"<? endif; ?>><?=$this->escapeHtml($list['title'])?></option>
        <? endforeach; ?>
      <? else: ?>
        <option value=""><?=$this->transEsc('My Favorites') ?></option>
      <? endif; ?>
      </select>
    <? endif; ?>
      <a class="button small secondary" id="make-list" role="button" href="<?=$this->url('editList', array('id' => 'NEW'))?>?recordId=<?=urlencode($this->driver->getUniqueId())?>&amp;recordSource=<?=urlencode($this->driver->getSourceIdentifier())?>"><?=$showLists ? $this->transEsc('or create a new list') : $this->transEsc('Create a List'); ?></a>
    </div>
  </div>

  <? if ($showLists): ?>
    <? if ($this->usertags()->getMode() !== 'disabled'): ?>
      <div class="row">
        <label class="medium-3 columns" for="add_mytags"><?=$this->transEsc('Add Tags') ?></label>
        <div class="medium-9 columns">
          <input class="auto-width" id="add_mytags" type="text" name="mytags" value=""/>
          <span class="help-block"><?=$this->transEsc("add_tag_note") ?></span>
        </div>
      </div>
    <? endif; ?>
    <div class="row">
      <label class="medium-3 columns" for="add_notes"><?=$this->transEsc('Add a Note') ?></label>
      <div class="medium-9 columns">
        <textarea class="auto-width" id="add_notes" name="notes" rows="3"></textarea>
      </div>
    </div>
    <div class="row">
      <div class="medium-9 medium-offset-3 columns">
        <input class="button small" type="submit" value="<?=$this->transEsc('Save') ?>"/>
      </div>
    </div>
  <? endif; ?>
</form>
<!-- record - SAVE.phtml end -->