<!-- START of: finna - RecordDriver/SolrForward/core.phtml -->
<?php
  $primaryRoles = ['drt', 'aus'];

  $openUrl = $this->openUrl($this->driver, 'record');
  $openUrlActive = $openUrl->isActive();
  // Account for replace_other_urls setting
  $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
  $onlineURLs = $this->driver->getOnlineURLs();
  $mergedData = $this->driver->tryMethod('getMergedRecordData');
  $renderedURLs = [];

  if (!empty($urls)){
    $videoUrls = [];
    $otherUrls = [];
    foreach ($urls as $url) {
      if(!empty($url['videoSources']) || !empty($url['embed']) && $url['embed'] == 'video' || $this->recordLink()->getEmbeddedVideo($url['url']) == 'data-embed-iframe'){
        array_push($videoUrls, $url);
        $renderedURLs[] = $url['url'];
      }
      else {
        array_push($otherUrls, $url);
      }
    }
  }

  $params = $this->searchMemory()->getLastSearchParams($this->searchClassId);
  $img = $this->recordImage($this->record($this->driver));
  $images = $img->getAllImagesAsCoverLinks(
      $this->layout()->userLang, $params
  );

  $thumbnail = false;
  $thumbnailAlignment = $this->record($this->driver)->getThumbnailAlignment('result');
  ob_start(); ?>
  <div class="media-<?=$thumbnailAlignment ?>">

    <?php if (!empty($videoUrls)): ?>
      <?=$this->record($this->driver)->renderTemplate('record-video-player.phtml', ['videoUrls' => $videoUrls, 'type' => 'SolrForward']);?>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('record-image-information.phtml', ['img' => $img, 'sizes' => ['small' => ['w' => 100, 'h' => 100], 'medium' => ['w' => 1200, 'h' => 1200]]]);?>

    <?php if ($this->resolver('record/record-organisation-menu.phtml') && $this->driver->getSourceIdentifier() == 'Solr'): ?>
      <div class="organisation-menu">
        <?=$this->render('record/record-organisation-menu.phtml') ?>
      </div>
    <?php endif; ?>

    <?=$this->record($this->driver)->renderTemplate('record-post-thumbnail.phtml');?>
  </div>
<?php
  $thumbnail = ob_get_contents();
  ob_end_clean();
  $altTitles = $this->driver->getAlternativeTitles();
  ob_start();
?>
  <div class="recordAltTitles record-alt-titles truncate-field" data-rows="2">
    <?php foreach ($altTitles as $altTitle): ?>
      <div class="record-alt-title">
        <?=$this->escapeHtml($altTitle) ?>
      </div>
    <?php endforeach; ?>
  </div>
<?php
  $altTitlesContent = ob_get_contents();
  ob_end_clean();
?>

<?php $this->headScript()->appendFile("finna-record.js"); ?>
<div class="media" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <h1 property="name" class="record-title visible-xs"><?=$this->escapeHtml($this->driver->getShortTitle())?><?php if ($subtitle = $this->driver->getSubtitle()): ?>&nbsp;: <?=$this->escapeHtml($subtitle) ?><?php endif; ?></h1>
  <?php if ($altTitles): ?>
    <div class="alt-title-wrapper visible-xs">
      <?=$altTitlesContent?>
    </div>
  <?php endif; ?>
  <?php if ($thumbnail && $thumbnailAlignment == 'left'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
  <div class="media-body record-information">
      <h1 property="name" class="record-title hidden-xs"><?=$this->escapeHtml($this->driver->getShortTitle())?><?php if ($subtitle = $this->driver->getSubtitle()): ?>&nbsp;: <?=$this->escapeHtml($subtitle) ?><?php endif; ?></h1>
      <?php if ($altTitles): ?>
        <div class="alt-title-wrapper hidden-xs">
          <?=$altTitlesContent?>
        </div>
      <?php endif; ?>
      <?php if ($uniformTitles = $this->driver->tryMethod('getUniformTitles')): ?>
        <div class="record-uniform-titles">
          <?php foreach ($uniformTitles as $uniformTitle): ?>
            <?php if (!empty($this->config()->get('config')->Record->display_versions)): ?>
              <a href="<?=$this->escapeHtmlAttr($this->recordLink()->getVersionsSearchUrl($this->driver))?>" rel="nofollow">
                <?=$this->escapeHtml($uniformTitle) ?>
              </a>
              <br>
            <?php else: ?>
              <?=$this->escapeHtml($uniformTitle) ?><br>
            <?php endif; ?>
          <?php endforeach; ?>
        </div>
      <?php endif; ?>

      <div class="recordURLs local-available-online-record">
        <div class="truncate-field">
          <?php if(!empty($otherUrls)): ?>
            <?php foreach ($otherUrls as $url): ?>
              <?php
                $renderedURLs[] = $url['url'];
                $desc = $url['desc'] ?? $this->truncateUrl($url['url']);
                if (!empty($url['desc'])) {
                  $map = ['Database Guide' => 'fa-info-database', 'Database Interface' => 'fa-browse-database'];
                  if (isset($map[$url['desc']])) {
                    $icon = $map[$url['desc']];
                  }
                }
              ?>
              <div class="fulltextField">
                <a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url']))?>" aria-label="<?=$this->escapeHtmlAttr($this->translate('external_online_link'))?>"
                  <?php if (!empty($url['posterUrl'])): ?> data-poster-url="<?= $this->escapeHtmlAttr($url['posterUrl']) ?>"<?php endif; ?>
                >
                  <i class="fa <?=$icon?>"></i> <?=$this->transEsc('default::link_' . $desc, null, $desc) ?>
                </a>
              </div>
            <?php endforeach; ?>
            <?php if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
              <?php foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                <?php if (in_array($url['url'], $renderedURLs)) { continue; } ?>
                <div class="fulltextField"><a class="fulltext" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>"<?=!empty($url['embed']) && $url['embed'] == 'iframe' ? ' data-embed-iframe' : '' ?> target="_blank" aria-label="<?=$this->escapeHtmlAttr($this->translate('external_online_link'))?>"><i class="fa fa-external-link"></i> <?=!empty($url['text']) ? $this->transEsc('default::link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?></a>
                <?php if ($url['source']): ?>
                  <span class="online-source">(<?=is_array($url['source']) ? $this->transEsc('Multiple Organisations') : $this->transEsc('default::source_' . $url['source'], null, $url['source']) ?>)</span>
                <?php endif; ?>
                </div>
              <?php endforeach; ?>
            <?php endif; ?>
          <?php endif; ?>

          <?php if ($openUrlActive): ?>
            <?=$openUrl->renderTemplate()?>
          <?php endif; ?>
        </div>
      </div>

      <div class="record-core-metadata" property="author">
        <?php $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
          <span class="recordFormat">
            <?=$this->record($this->driver)->getFormatList() ?>
          </span>
          <?php $type = $this->driver->getType(); ?>
          <?php $country = $this->driver->getCountry(); ?>
          <?php if ($type && $country): ?>
            <?=$this->escapeHtml($type) ?>, <?=$this->escapeHtml($country) ?>
          <?php else: ?>
            <?=$this->escapeHtml($type) ?><?=$this->escapeHtml($country) ?>
          <?php endif; ?>
        <?php endif; ?>
        <?php $containerTitle = $this->driver->getContainerTitle(); ?>
        <?php $primaryAuthors = $this->driver->getNonPresenterPrimaryAuthors(); ?>
        <?php if ($primaryAuthors || $containerTitle): ?>
          <div class="truncate-field">
            <?php if ($primaryAuthors): ?>
              <span class="recordAuthors">
                  <?php foreach ($primaryAuthors as $index => $author): ?>
                  <?=($index > 0 ? '; ' : '')?><?=$this->record($this->driver)->getAuthorityLinkElement('author', $author['name'], $author, ['date' => true, 'role' => true, 'authorityType' => $author['type'] ?? null, 'showInlineInfo' => true])?>
                <?php endforeach; ?>
              </span>
            <?php endif; ?>
            <?php if ($containerTitle): ?>
              <?php
                $containerSource = $this->driver->getSourceIdentifier();
                $containerID = $this->driver->getContainerRecordID();
              ?>
              <span class="recordContainerReference">
                <?=$this->transEsc('Published in')?> <a href="<?=($containerID ? $this->recordLink()->getUrl("$containerSource|$containerID") : $this->record($this->driver)->getLink('title', $containerTitle))?>"><?=$this->escapeHtml($containerTitle)?></a>
                <?php $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
              </span>
            <?php endif; ?>
          </div>
        <?php endif; ?>
        <?php $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
          <span class="recordPublications">
            <?php $publicationDate = ''; ?>
            <?php foreach ($publications as $index => $field): ?>
              <?=$index > 0 ? ' ; ' : '' ?>
              <span property="publisher" typeof="Organization">
              <?php $pubName = $field->getName(); if (!empty($pubName)): ?>
                <span property="name"><?=$this->escapeHtml($pubName)?></span>
              <?php endif; ?>
              </span>
              <?php $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
                <?php $publicationDate = $pubDate; ?>
              <?php endif; ?>
            <?php endforeach; ?>
            <?php if (!empty($publicationDate)): ?>
              <span property="datePublished"><?=$this->escapeHtml($publicationDate)?></span>
            <?php endif; ?>
          </span>
        <?php endif; ?>

        <?php $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
          <span class="recordEdition">
            <span property="bookEdition"><?=$this->escapeHtml($edition)?></span>
          </span>
        <?php endif; ?>

        <?=$this->record($this->driver)->renderTemplate('versions-link.phtml')?>
      </div>

      <?php if ($result = $this->driver->getSummary()): ?>
        <div class="description recordSummary">
          <div class="truncate-field">
            <?php foreach ($result as $item): ?>
              <p><?=$this->cleanHtml($item) ?></p>
            <?php endforeach; ?>
          </div>
        </div>
      <?php endif; ?>

      <?php if ($this->userlist()->getMode() !== 'disabled'): ?>
        <?php /* Display the lists that this record is saved to */ ?>
        <div class="savedLists" id="savedLists">
          <strong><?=$this->transEsc("Saved in")?>:</strong>
        </div>
      <?php endif; ?>

      <?/* Display Main Details */?>
      <?php
        $this->record($this->driver)->setRenderedUrls($renderedURLs);
        $formatter = $this->recordDataFormatter();
        $coreFields = $formatter->filterForwardFields($formatter->getDefaults('core'));
        $coreFields['Distribution']['context']['title'] = 'Distributor';
        $coreFields['Description FWD']['context']['title'] = '';
        $coreFieldGroups = $formatter->getGroupedData($driver, $formatter->getGroupedFields([
          ['lines' => ['Genre', 'Age Limit', 'Actors', 'Secondary Authors']],
          ['label' => 'Production Information',
            'lines' => ['Production', 'Production Costs', 'Funding', 'Published'],
            'options' => ['context' => ['class' => 'field-group-production']]],
          ['label' => 'Distribution Information',
            'lines' => ['Distribution', 'Premiere Night', 'Premiere Theaters',
              'Film Copies', 'Other Screenings', 'Broadcasting Dates'],
            'options' => ['context' => ['class' => 'field-group-distribution']]],
          ['label' => 'Description FWD',
            'lines' => ['Description FWD', 'Subjects'],
            'options' => ['context' => ['class' => 'field-group-content-description']]],
          ['lines' => ['Press Reviews', 'Item Description FWD', 'Music', 'Inspection Details']],
          ['label' => 'Technical Data',
            'lines' => ['Color', 'Sound', 'Aspect Ratio', 'Playing Time'],
            'options' => ['context' => ['class' => 'field-group-rating-technical-data']]],
          ['lines' => ['Access']]
        ], $coreFields));
      ?>
      <?php if (!empty($coreFieldGroups)): ?>
        <table class="table table-finna-record record-details record-details-more record-field-groups">
          <?=$this->record($this->driver)->renderTemplate('core-field-groups.phtml', ['data' => $coreFieldGroups]);?>
        </table>
      <?php endif; ?>
      <button class="btn show-details-button hidden"><?=$this->transEsc('show_more_details');?> <i class="fa fa-arrow-down"></i></button>
      <button class="btn hide-details-button hidden"><?=$this->transEsc('show_less_details');?> <i class="fa fa-arrow-up"></i></button>
      <?/* End Main Details */?>

      <?php if ($template = $this->content()->findTemplateForLng("content/Additions/record-post-metadata")): ?>
      <div>
        <?=$this->render($template)?>
      </div>
      <?php endif; ?>
    </div>
  <?php if ($thumbnail && $thumbnailAlignment == 'right'): ?>
    <?=$thumbnail ?>
  <?php endif; ?>
</div>
<!-- END of: finna - RecordDriver/SolrForward/core.phtml -->
