<?php
echo $this->render(
    'ajax/account/status-badge.phtml',
    [
        'title' => 'account_requests_available',
        'count' => $this->available,
        'class' => 'account-info',
    ]
);
echo $this->render(
    'ajax/account/status-badge.phtml',
    [
        'title' => 'account_requests_in_transit',
        'count' => $this->in_transit,
        'class' => 'account-warning',
    ]
);
echo $this->render(
    'ajax/account/status-badge.phtml',
    [
        'title' => 'account_requests_other',
        'count' => $this->other,
        'class' => 'account-none',
    ]
);
