<? $searchObject = $this->recommend->getResults(); $results = $searchObject->getResults(); if (!empty($results)): ?>
<div class="sidegroup">
  <h4><?=$this->transEsc('Catalog Results')?></h4>

  <ul class="similar">
    <? foreach ($results as $driver): ?>
    <li>
      <? $formats = $driver->getFormats(); $format = isset($formats[0]) ? $formats[0] : ''; ?>
      <span class="<?=$this->record($driver)->getFormatClass($format)?>">
      <a href="<?=$this->recordLink()->getUrl($driver)?>" class="title"><?
        $summHighlightedTitle = $driver->getHighlightedTitle();
        $summTitle = $driver->getTitle();
        if (!empty($summHighlightedTitle)) {
            echo $this->highlight($this->addEllipsis($summHighlightedTitle, $summTitle));
        } else if (!empty($summTitle)) {
            echo $this->escapeHtml($this->truncate($summTitle, 180));
        } else {
            echo $this->transEsc('Title not available');
        }
      ?></a>
      </span>
      <? $summAuthor = $driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
      <br />
      <?=$this->transEsc('By')?>:
      <a href="<?=$this->record($driver)->getLink('author', $summAuthor)?>"><?
        $summHighlightedAuthor = $driver->getHighlightedAuthor();
        echo !empty($summHighlightedAuthor)
            ? $this->highlight($summHighlightedAuthor)
            : $this->escapeHtml($summAuthor);
      ?></a>
      <? endif; ?>
      <? $summDate = $driver->getPublicationDates(); if (!empty($summDate)): ?>
      <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($summDate[0])?>)
      <? endif; ?>
    </li>
    <? endforeach; ?>
  </ul>
  <p><a href="<?=$this->url($searchObject->getOptions()->getSearchAction()) . $searchObject->getUrl()->setLimit($searchObject->getOptions()->getDefaultLimit())?>"><?=$this->transEsc('More catalog results')?>...</a></p>
</div>
<? endif ?>