<? $results = $this->recommend->getResults(); ?>
<? if(!empty($results)): ?>
  <dl class="narrowList navmenu<? if(!$this->recommend->isCollapsed()): ?> open<? endif ?>">
    <dt class="facet_dpla">DPLA</dt>
    <? foreach($results as $item): ?>
      <dd>
        <a href="<?=$item['link'] ?>" target="new"><?=$this->escapeHtml($item['title']) ?></a>
        <? if(!empty($item['desc'])): ?>
          <span title="<?=$item['desc'] ?>"><?=$this->escapeHtml($this->truncate($item['desc'], 50)) ?></span></br>
        <? endif; ?>
        <span style="font-size:85%;font-style:italic">
          (<?=$this->transEsc('Provider') ?>: <?=$this->escapeHtml($item['provider']) ?>)
        </span>
      </dd>
    <? endforeach; ?>
  </ul>
<? endif; ?>
