<div class="sidegroup">
  <? if ($this->results->getResultTotal() > 0): ?><h4><?=$this->transEsc('Narrow Search')?></h4><? endif; ?>
  <? $checkboxFilters = $this->results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
    <? foreach ($checkboxFilters as $current): ?>
        <div class="checkboxFilter<?=($this->results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) ? ' hide' : ''?>">
          <input type="checkbox" name="filter[]" value="<?=$this->escapeHtml($current['filter'])?>"
            <?=$current['selected'] ? 'checked="checked"' : ''?> id="<?=$this->escapeHtml(str_replace(' ', '', $current['desc']))?>"
            onclick="document.location.href='<?=$current['selected'] ? $this->results->getUrl()->removeFilter($current['filter']) : $this->results->getUrl()->addFilter($current['filter'])?>';" />
          <label for="<?=$this->escapeHtml(str_replace(' ', '', $current['desc']))?>"><?=$this->transEsc($current['desc'])?></label>
        </div>
    <? endforeach; ?>
  <? endif; ?>
  <? $filterList = $this->results->getParams()->getFilterList(true); if (!empty($filterList)): ?>
    <strong><?=$this->transEsc('Remove Filters')?></strong>
    <ul class="filters">
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $filter): ?>
        <?
            $removeLink = $this->currentPath().$this->results->getUrl()->removeFacet($filter['field'], $filter['value']);
            if ($filter['displayText'] == '[* TO *]') $filter['displayText'] = $this->translate('filter_wildcard');
        ?>
        <li>
          <a href="<?=$removeLink?>"><img src="<?=$this->imageLink('silk/delete.png')?>" alt="Delete"/></a>
          <a href="<?=$removeLink?>"><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?></a>
        </li>
      <? endforeach; ?>
    <? endforeach; ?>
    </ul>
  <? endif; ?>
  <? $sideFacetSet = $this->recommend->getFacetSet(); $dateFacets = $this->recommend->getDateFacets(); ?>
  <? if (!empty($sideFacetSet) && $this->results->getResultTotal() > 0): ?>
    <? foreach ($sideFacetSet as $title => $cluster): ?>
      <? if (isset($dateFacets[$title])): ?>
        <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
        <form action="" name="<?=$this->escapeHtml($title)?>Filter" id="<?=$this->escapeHtml($title)?>Filter">
          <?=$this->results->getUrl()->asHiddenFields(array('filter' => "/^{$title}:.*/"))?>
          <input type="hidden" name="daterange[]" value="<?=$this->escapeHtml($title)?>"/>
          <fieldset class="publishDateLimit" id="<?=$this->escapeHtml($title)?>">
            <legend><?=$this->transEsc($cluster['label'])?></legend>
            <label for="<?=$this->escapeHtml($title)?>from"><?=$this->transEsc('date_from')?>:</label>
            <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtml($title)?>from" id="<?=$this->escapeHtml($title)?>from" value="<?=isset($dateFacets[$title][0])?$this->escapeHtml($dateFacets[$title][0]):''?>" />
            <label for="<?=$this->escapeHtml($title)?>to"><?=$this->transEsc('date_to')?>:</label>
            <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtml($title)?>to" id="<?=$this->escapeHtml($title)?>to" value="<?=isset($dateFacets[$title][1])?$this->escapeHtml($dateFacets[$title][1]):''?>" />
            <div id="<?=$this->escapeHtml($title)?>Slider" class="dateSlider"></div>
            <input type="submit" value="<?=$this->transEsc('Set')?>" id="<?=$this->escapeHtml($title)?>goButton"/>
          </fieldset>
        </form>
      <? else: ?>
        <dl class="narrowList navmenu">
          <dt><?=$this->transEsc($cluster['label'])?></dt>
          <? $i = 0; foreach ($cluster['list'] as $thisFacet): ?>
            <? if (++$i == 6): ?>
            <dd id="more<?=$this->escapeHtml($title)?>"><a href="#" onclick="moreFacets('<?=$this->escapeHtml($title)?>'); return false;"><?=$this->transEsc('more')?> ...</a></dd>
          </dl>
          <dl class="narrowList navmenu offscreen" id="narrowGroupHidden_<?=$this->escapeHtml($title)?>">
            <? endif; ?>
            <? if ($thisFacet['isApplied']): ?>
              <dd><?=$this->escapeHtml($thisFacet['displayText'])?> <img src="<?=$this->imageLink('silk/tick.png')?>" alt="Selected"/></dd>
            <? else: ?>
              <dd><a href="<?=$this->currentPath().$this->results->getUrl()->addFacet($title, $thisFacet['value'])?>"><?=$this->escapeHtml($thisFacet['displayText'])?></a> (<?=$this->escapeHtml($thisFacet['count'])?>)</dd>
            <? endif; ?>
          <? endforeach; ?>
          <? if ($i > 5): ?><dd><a href="#" onclick="lessFacets('<?=$this->escapeHtml($title)?>'); return false;"><?=$this->transEsc('less')?> ...</a></dd><? endif; ?>
        </dl>
      <? endif; ?>
    <? endforeach; ?>
  <? endif; ?>
</div>
