<? $results = $this->recommend->getResults(); ?>
<div class="sidegroup">
  <? if ($results->getResultTotal() > 0): ?><h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4><? endif; ?>
  <? $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
    <? foreach ($checkboxFilters as $current): ?>
        <div class="checkboxFilter<?=($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) ? ' hide' : ''?>">
          <input type="checkbox" name="filter[]" value="<?=$this->escapeHtmlAttr($current['filter'])?>"
            <?=$current['selected'] ? 'checked="checked"' : ''?> id="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"
            onclick="document.location.href='<?=$current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])?>';" />
          <label for="<?=$this->escapeHtmlAttr(str_replace(' ', '', $current['desc']))?>"><?=$this->transEsc($current['desc'])?></label>
        </div>
    <? endforeach; ?>
  <? endif; ?>
  <? $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
  <? $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : array(); ?>
  <? $filterList = $this->recommend->getVisibleFilters($extraFilters); if (!empty($filterList)): ?>
    <strong><?=$this->transEsc('Remove Filters')?></strong>
    <ul class="filters">
    <? foreach ($filterList as $field => $filters): ?>
      <? foreach ($filters as $i => $filter): ?>
        <?
            $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
            if ($index !== false) {
                unset($collapsedFacets[$index]); // Open if we have a match
            }
            if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
                $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
            } else {
                $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], true, $filter['operator']);
            }
            if ($filter['displayText'] == '[* TO *]') $filter['displayText'] = $this->translate('filter_wildcard');
        ?>
        <li>
          <a href="<?=$removeLink?>"><img src="<?=$this->imageLink('silk/delete.png')?>" alt="Delete"/></a>
          <a href="<?=$removeLink?>"><? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?></a>
        </li>
      <? endforeach; ?>
    <? endforeach; ?>
    </ul>
  <? endif; ?>
  <?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
  <? $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
  <? if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
    <? foreach ($sideFacetSet as $title => $cluster): ?>
      <? $allowExclude = $this->recommend->excludeAllowed($title); ?>
      <? if (isset($rangeFacets[$title])): ?>
        <? if ($rangeFacets[$title]['type'] == 'date'): ?>
          <? /* Load the publication date slider UI widget */ $this->headScript()->appendFile('pubdate_slider.js'); ?>
        <? endif; ?>
        <form action="" name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
          <?=$results->getUrlQuery()->asHiddenFields(array('page' => '/./', 'filter' => "/^{$title}:.*/"))?>
          <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
          <fieldset class="publishDateLimit" id="<?=$this->escapeHtmlAttr($title)?>">
            <legend><?=$this->transEsc($cluster['label'])?></legend>
            <label for="<?=$this->escapeHtmlAttr($title)?>from"><?=$this->transEsc('date_from')?>:</label>
            <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][0]):''?>" />
            <label for="<?=$this->escapeHtmlAttr($title)?>to"><?=$this->transEsc('date_to')?>:</label>
            <input type="text" size="4" maxlength="4" class="yearbox" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][1]):''?>" />
            <div id="<?=$this->escapeHtmlAttr($title)?>Slider" class="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>Slider"></div>
            <input type="submit" value="<?=$this->transEsc('Set')?>" id="<?=$this->escapeHtmlAttr($title)?>goButton"/>
          </fieldset>
        </form>
      <? else: ?>
        <dl class="narrowList navmenu<? if(!in_array($title, $collapsedFacets)): ?> open<? endif ?>">
          <dt class="facet_<?=$this->escapeHtmlAttr($title)?>"><?=$this->transEsc($cluster['label'])?></dt>
          <? $i = 0; foreach ($cluster['list'] as $thisFacet): ?>
            <? if (++$i == 6): ?>
            <dd id="more<?=$this->escapeHtmlAttr($title)?>"><a href="#" onclick="moreFacets('<?=$this->escapeHtmlAttr($title)?>'); return false;"><?=$this->transEsc('more')?> ...</a></dd>
          </dl>
          <dl class="narrowList navmenu offscreen<? if(!in_array($title, $collapsedFacets)): ?> open<? endif ?>" id="narrowGroupHidden_<?=$this->escapeHtmlAttr($title)?>">
            <? endif; ?>
            <? if ($thisFacet['isApplied']): ?>
              <dd class="facet<?=$thisFacet['operator'] ?> applied"<? if($thisFacet['operator'] == 'OR'): ?> href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], true, $thisFacet['operator']) ?>"<? endif ?>><?=$this->escapeHtml($thisFacet['displayText'])?> <img src="<?=$this->imageLink('silk/tick.png')?>" alt="Selected"/></dd>
            <? else: ?>
              <dd>
                <a class="facet<?=$thisFacet['operator'] ?>" href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator'])?>"><?=$this->escapeHtml($thisFacet['displayText'])?></a> (<?=$this->escapeHtml($thisFacet['count'])?>)
                <? if ($allowExclude): ?>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT')?>" title="<?=$this->transEsc('exclude_facet')?>"><img src="<?=$this->imageLink('fugue/cross-small.png')?>" alt="Delete"/></a>
                <? endif; ?>
              </dd>
            <? endif; ?>
          <? endforeach; ?>
          <? if ($i > 5): ?><dd><a href="#" onclick="lessFacets('<?=$this->escapeHtmlAttr($title)?>'); return false;"><?=$this->transEsc('less')?> ...</a></dd><? endif; ?>
        </dl>
      <? endif; ?>
    <? endforeach; ?>
  <? endif; ?>
</div>
