<? $searchObject = $this->recommend->getResults(); $results = $searchObject->getResults(); if (!empty($results)): ?>
<div class="sidegroup">
  <h4><?=$this->transEsc('Summon Results')?></h4>
  
  <ul class="similar">
    <? foreach ($results as $driver): ?>
    <li>
      <? $formats = $driver->getFormats(); $format = isset($formats[0]) ? $formats[0] : ''; ?>
      <span class="<?=$this->record($driver)->getFormatClass($format)?>">
      <a href="<?=$this->recordLink()->getUrl($driver)?>" class="title"><?
        $summHighlightedTitle = $driver->getHighlightedTitle();
        $summTitle = $driver->getTitle();
        if (!empty($summHighlightedTitle)) {
            echo $this->highlight($this->addEllipsis($summHighlightedTitle, $summTitle));
        } else if (!empty($summTitle)) {
            echo $this->escape($this->truncate($summTitle, 180));
        } else {
            echo $this->transEsc('Title not available');
        }
      ?></a>
      </span>
      <span style="font-size: .8em">
      <? $summAuthor = $driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
      <br />
      <?=$this->transEsc('by')?>
      <a href="<?=$this->record($driver)->getLink('author', $summAuthor)?>"><?
        $summHighlightedAuthor = $driver->getHighlightedAuthor();
        echo !empty($summHighlightedAuthor)
            ? $this->highlight($summHighlightedAuthor)
            : $this->escape($summAuthor);
      ?></a>
      <? endif; ?>
      </span>
    </li>
    <? endforeach; ?>
  </ul>
  <p><a href="<?=$this->url($searchObject->getSearchAction()) . $searchObject->getUrl()->setLimit($searchObject->getDefaultLimit())?>"><?=$this->transEsc('More Summon results')?>...</a></p>
</div>
<? endif ?>