<? $searchObject = $this->recommend->getResults(); $results = $searchObject->getResults(); if (!empty($results)): ?>
<div class="sidegroup">
  <h4><?=$this->transEsc('Summon Results')?></h4>
  
  <ul class="similar">
    <? foreach ($results as $driver): ?>
    <li>
      <? $formats = $driver->getFormats(); $format = isset($formats[0]) ? $formats[0] : ''; ?>
      <span class="<?=$this->record($driver)->getFormatClass($format)?>">
      <a href="<?=$this->recordLink()->getUrl($driver)?>" class="title">
        <?=$this->record($driver)->getTitleHtml()?>
      </a>
      </span>
      <span style="font-size: .8em">
      <? $summAuthors = $driver->getPrimaryAuthorsWithHighlighting(); if (!empty($summAuthors)): ?>
      <br />
      <?=$this->transEsc('By')?>:
      <a href="<?=$this->record($driver)->getLink('author', $this->highlight($summAuthors[0], null, true, false))?>"><?=$this->highlight($summAuthors[0])?></a><? if (count($summAuthors) > 1): ?>, <?=$this->transEsc('more_authors_abbrev')?><? endif; ?>
      <? endif; ?>
      </span>
    </li>
    <? endforeach; ?>
  </ul>
  <p><a href="<?=$this->url($searchObject->getOptions()->getSearchAction()) . $searchObject->getUrlQuery()->setLimit($searchObject->getOptions()->getDefaultLimit())?>"><?=$this->transEsc('More Summon results')?>...</a></p>
</div>
<? endif ?>