<h3><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>
<p><a rel="external" href="<?=$this->recordLink()->getUrl($this->driver)?>"><?=$this->transEsc('View Full ' . ($this->driver->isCollection() ? 'Collection' : 'Record'))?></a></p>

<dl class="biblio" title="<?=$this->transEsc('Bibliographic Details')?>">
  <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
  <? if ($summary): ?>
    <dt><?=$this->transEsc('Description')?>: </dt>
    <dd><?=$this->escapeHtml($summary)?></dd>
  <? endif; ?>

  <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
  <? if (isset($authors['main']) && !empty($authors['main'])): ?>
    <dt><?=$this->transEsc(count($authors['main']) > 1 ? 'Main Authors' : 'Main Author')?>: </dt>
    <dd>
      <p><? $i = 0; foreach ($authors['main'] as $author => $roles): ?><?=($i++ == 0)?'':', '?><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $author)?>"><?=$this->escapeHtml($author)?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?><? endforeach; ?></p>
    </dd>
  <? endif; ?>

  <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
    <dt><?=$this->transEsc(count($authors['corporate']) > 1 ? 'Corporate Author' : 'Corporate Authors')?>: </dt>
    <dd>
      <p><? $i = 0; foreach ($authors['corporate'] as $corporate => $roles): ?><?=($i++ == 0)?'':', '?><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $corporate)?>"><?=$this->escapeHtml($corporate)?></a><? if (count($roles) > 0): ?> (<? $j = 0; foreach ($roles as $role): ?><?=($j++ == 0)?'':', '?><?=$this->transEsc("CreatorRoles::" . $role)?><? endforeach; ?>)<? endif; ?><? endforeach; ?></p>
    </dd>
  <? endif; ?>

  <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
    <dt><?=$this->transEsc('Language')?>: </dt>
    <dd><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?> <? endforeach; ?></dd>
  <? endif; ?>

  <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
    <dt><?=$this->transEsc('Format')?>: </dt>
    <dd><?=$this->record($this->driver)->getFormatList()?></dd>
  <? endif; ?>

  <? $access = $this->driver->getAccessRestrictions(); if (!empty($access)): ?>
    <? $contentDisplayed = true; ?>
    <dt><?=$this->transEsc('Access')?>: </dt>
    <dd>
      <? foreach ($access as $field): ?>
        <p><?=$this->escapeHtml($field)?></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? $related = $this->driver->getRelationshipNotes(); if (!empty($related)): ?>
    <? $contentDisplayed = true; ?>
    <dt><?=$this->transEsc('Related Items')?>: </dt>
    <dd>
      <? foreach ($related as $field): ?>
        <p><?=$this->escapeHtml($field)?></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>
</dl>