<?
  if($loggedin = $this->auth()->isLoggedIn()) {
    $user_id = $loggedin->id;
    $loggedin = true;
  } else {
    $user_id = false;
  }
?>
<? /* Display thumbnail if appropriate: */ ?>
<?=$this->record($this->driver)->getCover('core', 'medium', $this->record($this->driver)->getThumbnail('large')); ?>

<h3><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

<? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
<? if ($summary): ?><p><?=$this->escapeHtml($this->truncate($summary, 200))?></p><? endif; ?>

<dl class="biblio" title="<?=$this->transEsc('Bibliographic Details')?>">
  <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
    <dt><?=$this->transEsc('Published in')?>:</dt>
      <dd>
      <? $containerID = $this->driver->getContainerRecordID(); ?>
      <a rel="external" href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
      <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
    </dd>
  <? endif; ?>

  <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
  <? if (!empty($nextTitles)): ?>
    <dt><?=$this->transEsc('New Title')?>: </dt>
    <dd>
      <? foreach($nextTitles as $field): ?>
        <p><a rel="external" href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? if (!empty($prevTitles)): ?>
    <dt><?=$this->transEsc('Previous Title')?>: </dt>
    <dd>
      <? foreach($prevTitles as $field): ?>
        <p><a rel="external" href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? $authors = $this->driver->getDeduplicatedAuthors(); ?>
  <? if (isset($authors['main']) && !empty($authors['main'])): ?>
    <dt><?=$this->transEsc('Main Author')?>: </dt>
    <dd><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $authors['main'])?>"><?=$this->escapeHtml($authors['main'])?></a></dd>
  <? endif; ?>

  <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
    <dt><?=$this->transEsc('Format')?>: </dt>
    <dd><?=$this->record($this->driver)->getFormatList()?></dd>
  <? endif; ?>

  <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
    <dt><?=$this->transEsc('Language')?>: </dt>
    <dd><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?> <? endforeach; ?></dd>
  <? endif; ?>

  <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
    <dt><?=$this->transEsc('Published')?>: </dt>
    <dd>
      <? foreach ($publications as $field): ?>
        <p><?=$this->escapeHtml($field)?></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
    <dt><?=$this->transEsc('Edition')?>: </dt>
    <dd><?=$this->escapeHtml($edition)?></dd>
  <? endif; ?>

  <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
  <tr valign="top">
    <dt><?=$this->transEsc('Subjects')?>: </dt>
    <dd>
      <? foreach ($subjects as $field): ?>
      <p>
        <? $subject = ''; ?>
        <? $i = 0; foreach ($field as $subfield): ?>
          <?=($i++ == 0) ? '' : ' -- '?>
          <? $subject = trim($subject . ' ' . $subfield); ?>
          <a rel="external" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" class="subjectHeading"><?=$this->escapeHtml($subfield)?></a>
        <? endforeach; ?>
      </p>
      <? endforeach; ?>
    </dd>
  </tr>
  <? endif; ?>

  <? if (isset($authors['corporate']) && !empty($authors['corporate'])): ?>
    <dt><?=$this->transEsc('Corporate Author')?>: </dt>
    <dd><p><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $authors['corporate'])?>"><?=$this->escapeHtml($authors['corporate'])?></a></p></dd>
  <? endif; ?>

  <? if (isset($authors['secondary']) && !empty($authors['secondary'])): ?>
    <dt><?=$this->transEsc('Other Authors')?>: </dt>
    <dd>
      <p><? $i = 0; foreach ($authors['secondary'] as $field): ?><?=($i++ == 0)?'':', '?><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a><? endforeach; ?></p>
    </dd>
  <? endif; ?>

  <?/* Display series section if at least one series exists. */?>
  <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
    <dt><?=$this->transEsc('Series')?>: </dt>
    <dd>
      <? foreach ($series as $field): ?>
        <?/* Depending on the record driver, $field may either be an array with
           "name" and "number" keys or a flat string containing only the series
           name.  We should account for both cases to maximize compatibility. */?>
        <? if (is_array($field)): ?>
          <? if (!empty($field['name'])): ?>
            <p>
            <a rel="external" href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
            <? if (!empty($field['number'])): ?>
              <?=$this->escapeHtml($field['number'])?>
            <? endif; ?>
            </p>
          <? endif; ?>
        <? else: ?>
          <p><a rel="external" href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a></p>
        <? endif; ?>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
    <dt><?=$this->transEsc('child_records')?>: </dt>
    <dd><a rel="external" href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a></dd>
  <? endif; ?>

  <?
      $openUrl = $this->openUrl($this->driver, 'record');
      $openUrlActive = $openUrl->isActive();
      // Account for replace_other_urls setting
      $urls = $this->record($this->driver)->getLinkDetails($openUrlActive);
  ?>
  <? if (!empty($urls) || $openUrlActive): ?>
    <dt><?=$this->transEsc('Online Access')?>: </dt>
    <dd>
      <? foreach ($urls as $current): ?>
        <p><a rel="external" href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a></p>
      <? endforeach; ?>
      <? if ($openUrlActive): ?>
        <?=$openUrl->renderTemplate()?><br/>
      <? endif; ?>
    </dd>
  <? endif; ?>

  <? $recordLinks = $this->driver->getAllRecordLinks(); if (!empty($recordLinks)): ?>
    <dt><?=$this->transEsc('Related Items')?>:</dt>
    <dd>
      <? foreach ($recordLinks as $recordLink): ?>
        <p>
          <?=$this->transEsc($recordLink['title'])?>:
          <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a>
        </p>
      <? endforeach; ?>
      <? /* if we have record links, display relevant explanatory notes */
        $related = $this->driver->getRelationshipNotes();
        if (!empty($related)): ?>
          <? foreach ($related as $field): ?>
            <p><?=$this->escapeHtml($field)?></p>
          <? endforeach; ?>
      <? endif; ?>
    </dd>
  <? endif; ?>

  <? $tagList = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(null, null, 'count', $user_id) : array(); ?>
  <? if (count($tagList) > 0): ?>
    <dt><?=$this->transEsc('Tags')?>: </dt>
    <dd id="tagList">
      <? $i=0; foreach ($tagList as $tag): ?>
        <? if($loggedin): ?>
          <? $is_me = isset($tag['is_me']) && !is_null($tag['is_me']) ? $tag['is_me'] : false; ?>
          <span class="tag ui-btn ui-btn-inline ui-mini ui-btn-corner-all ui-btn-up-<?=$is_me ? 'b' : 'c' ?>">
            <a rel="external" href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>" class="text ui-btn-text">
              <?=$this->escapeHtml($tag->tag)?> (<?=$this->escapeHtml($tag->cnt)?>)
            </a>
            <form method="POST" action="<?=$this->recordLink()->getActionUrl($this->driver, $is_me ? 'DeleteTag' : 'AddTag') ?>" class="tag-form">
              <input type="hidden" name="tag" value="<?=$this->escapeHtmlAttr($tag['tag'])?>"/>
              <button type="submit" onClick="ajaxTagUpdate('<?=$this->escapeHtmlAttr($tag['tag'])?>', <?=$is_me ? 'true' : 'false' ?>);return false;" data-theme="<?=$is_me ? 'c' : 'b' ?>" data-icon="<?=$is_me ? 'minus' : 'plus' ?>" data-iconpos="notext" data-inline="true" data-mini="true">&nbsp;</button>
            </form>
          </span>
        <? else: ?>
          <a rel="external" href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<?=(++$i < count($tagList)) ? ', ' : '' ?>
        <? endif; ?>
      <? endforeach; ?>
    </dd>
  <? endif; ?>
</dl>
