<? /* Display thumbnail if appropriate: */ ?>
<? $mediumThumb = $this->record($this->driver)->getThumbnail('medium'); $largeThumb = $this->record($this->driver)->getThumbnail('large'); ?>
<? if ($mediumThumb): ?>
  <? if ($largeThumb): ?><a rel="external" href="<?=$this->escapeHtml($largeThumb)?>"><? endif; ?>
    <div class="recordcover">
      <img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtml($mediumThumb);?>"/>
    </div>
  <? if ($largeThumb): ?></a><? endif; ?>
<? endif; ?>

<h3><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle() . ' ' . $this->driver->getTitleSection())?></h3>

<? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $summary[0] : false; ?>
<? if ($summary): ?><p><?=$this->escapeHtml($this->truncate($summary, 200))?></p><? endif; ?>

<dl class="biblio" title="<?=$this->transEsc('Bibliographic Details')?>">
  <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
    <dt><?=$this->transEsc('Journal Title')?>:</dt>
      <dd>
      <a rel="external" href="<?=$this->record($this->driver)->getLink('journaltitle', $journalTitle)?>"><?=$this->escapeHtml($journalTitle)?></a>
      <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
    </dd>
  <? endif; ?>

  <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
  <? if (!empty($nextTitles)): ?>
    <dt><?=$this->transEsc('New Title')?>: </dt>
    <dd>
      <? foreach($nextTitles as $field): ?>
        <p><a rel="external" href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? if (!empty($prevTitles)): ?>
    <dt><?=$this->transEsc('Previous Title')?>: </dt>
    <dd>
      <? foreach($prevTitles as $field): ?>
        <p><a rel="external" href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <?
      // The secondary author array may contain a corporate or primary author;
      // let's be sure we filter out duplicate values.
      $mainAuthor = $this->driver->getPrimaryAuthor();
      $corpAuthor = $this->driver->getCorporateAuthor();
      $secondaryAuthors = $this->driver->getSecondaryAuthors();
      $duplicates = array();
      if (!empty($mainAuthor)) {
          $duplicates[] = $mainAuthor;
      }
      if (!empty($corpAuthor)) {
          $duplicates[] = $corpAuthor;
      }
      if (!empty($duplicates)) {
          $secondaryAuthors = array_diff($secondaryAuthors, $duplicates);
      }
  ?>
  <? if (!empty($mainAuthor)): ?>
    <dt><?=$this->transEsc('Main Author')?>: </dt>
    <dd><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $mainAuthor)?>"><?=$this->escapeHtml($mainAuthor)?></a></dd>
  <? endif; ?>

  <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
    <dt><?=$this->transEsc('Format')?>: </dt>
    <dd><?=$this->record($this->driver)->getFormatList()?></dd>
  <? endif; ?>

  <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
    <dt><?=$this->transEsc('Language')?>: </dt>
    <dd><? foreach ($langs as $lang): ?><?= $this->escapeHtml($lang)?> <? endforeach; ?></dd>
  <? endif; ?>

  <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
    <dt><?=$this->transEsc('Published')?>: </dt>
    <dd>
      <? foreach ($publications as $field): ?>
        <p><?=$this->escapeHtml($field)?></p>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
    <dt><?=$this->transEsc('Edition')?>: </dt>
    <dd><?=$this->escapeHtml($edition)?></dd>
  <? endif; ?>

  <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
  <tr valign="top">
    <dt><?=$this->transEsc('Subjects')?>: </dt>
    <dd>
      <? foreach ($subjects as $field): ?>
      <p>
        <? $subject = ''; ?>
        <? $i = 0; foreach ($field as $subfield): ?>
          <?=($i++ == 0) ? '' : ' -- '?>
          <? $subject = trim($subject . ' ' . $subfield); ?>
          <a rel="external" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" class="subjectHeading"><?=$this->escapeHtml($subfield)?></a>
        <? endforeach; ?>
      </p>
      <? endforeach; ?>
    </dd>
  </tr>
  <? endif; ?>

  <? if (!empty($corpAuthor)): ?>
    <dt><?=$this->transEsc('Corporate Author')?>: </dt>
    <dd><p><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $corpAuthor)?>"><?=$this->escapeHtml($corpAuthor)?></a></p></dd>
  <? endif; ?>

  <? if (!empty($secondaryAuthors)): ?>
    <dt><?=$this->transEsc('Other Authors')?>: </dt>
    <dd>
      <p><? $i = 0; foreach ($secondaryAuthors as $field): ?><?=($i++ == 0)?'':', '?><a rel="external" href="<?=$this->record($this->driver)->getLink('author', $field)?>"><?=$this->escapeHtml($field)?></a><? endforeach; ?></p>
    </dd>
  <? endif; ?>

  <?/* Display series section if at least one series exists. */?>
  <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
    <dt><?=$this->transEsc('Series')?>: </dt>
    <dd>
      <? foreach ($series as $field): ?>
        <?/* Depending on the record driver, $field may either be an array with
           "name" and "number" keys or a flat string containing only the series
           name.  We should account for both cases to maximize compatibility. */?>
        <? if (is_array($field)): ?>
          <? if (!empty($field['name'])): ?>
            <p>
            <a rel="external" href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
            <? if (!empty($field['number'])): ?>
              <?=$this->escapeHtml($field['number'])?>
            <? endif; ?>
            </p>
          <? endif; ?>
        <? else: ?>
          <p><a rel="external" href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a></p>
        <? endif; ?>
      <? endforeach; ?>
    </dd>
  <? endif; ?>

  <?
      $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
      // Account for replace_other_urls setting
      $urls = ($openUrl && $this->driver->replaceURLsWithOpenURL()) ? array() : $this->driver->getURLs();
  ?>
  <? if (!empty($urls) || $openUrl): ?>
    <dt><?=$this->transEsc('Online Access')?>: </dt>
    <dd>
      <? foreach ($urls as $currentUrl => $desc): ?>
        <p><a rel="external" href="<?=$this->escapeHtml($this->proxyUrl($currentUrl))?>"><?=$this->escapeHtml($desc)?></a></p>
      <? endforeach; ?>
      <? if ($openUrl): ?>
        <?=$this->openUrl($openUrl)?><br/>
      <? endif; ?>
    </dd>
  <? endif; ?>

  <? $tagList = $this->driver->getTags(); ?>
  <? if (count($tagList) > 0): ?>
    <dt><?=$this->transEsc('Tags')?>: </dt>
    <dd>
      <span style="float:right;">
        <a rel="external" href="<?=$this->recordLink()->getUrl($this->driver, 'AddTag')?>" class="tool add tagRecord controller<?=$this->record($this->driver)->getController()?>" title="<?=$this->transEsc('Add Tag')?>" id="tagRecord"><?=$this->transEsc('Add Tag')?></a>
      </span>
      <div id="tagList">
        <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a rel="external" href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
      </div>
    </dd>
  <? endif; ?>
</dl>