<?
    // Set up some convenience variables:
    $id = $this->driver->getUniqueId();
    $source = $this->driver->getResourceSource();
    if (isset($this->list) && is_object($this->list)) {
        $list_id = $this->list->id;
        $user_id = $this->list->user_id;
    } else {
        $list_id = null;
        $user_id = $this->user ? $this->user->id : null;
    }
?>
<a rel="external" href="<?=$this->recordLink()->getUrl($this->driver)?>">
  <div class="result source<?=$this->escapeHtmlAttr($this->driver->getResourceSource())?> recordId<?=$this->driver->supportsAjaxStatus()?' ajaxItemId':''?>">
    <input type="hidden" value="<?=$this->escapeHtmlAttr($this->driver->getUniqueID())?>" class="hiddenId" />
    <h3><?=$this->record($this->driver)->getTitleHtml()?></h3>
    <? $listAuthor = $this->driver->getPrimaryAuthor(); if (!empty($listAuthor)): ?>
      <p><?=$this->transEsc('by')?> <?=$this->escapeHtml($listAuthor)?></p>
    <? endif; ?>
    <? $listTags = ($this->usertags()->getMode() !== 'disabled') ? $this->driver->getTags(
        $list_id, // get tags for all lists if no single list is selected
        $user_id, 'tag'
       ) : array();
    ?>
    <? if (count($listTags) > 0): ?>
      <p>
        <strong><?=$this->transEsc('Your Tags')?>:</strong>
        <? $i = 0; foreach ($listTags as $tag): ?><?=($i++ == 0)?'':', '?><?=$this->escapeHtml($tag->tag)?><? endforeach; ?>
      </p>
    <? endif; ?>
    <? $listNotes = $this->driver->getListNotes($list_id, $user_id); ?>
    <? if (count($listNotes) > 0): ?>
      <p><strong><?=$this->transEsc('Notes')?>:</strong></p>
      <? foreach ($listNotes as $note): ?>
        <p><?=$this->escapeHtml($note)?></p>
      <? endforeach; ?>
    <? endif; ?>

    <? if ($this->driver->supportsAjaxStatus()): ?>
      <p class="callnumAndLocation">
        <strong><?=$this->transEsc('Call Number')?>:</strong>
        <span class="callnumber ajax_availability hide"><?=$this->transEsc('Loading')?>...</span><br />
        <strong><?=$this->transEsc('Located')?>:</strong>
        <span class="location ajax_availability hide"><?=$this->transEsc('Loading')?>...</span>
      </p>
    <? else: ?>
      <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <p><strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?></p>
      <? endif; ?>
    <? endif; ?>
    <?=$this->record($this->driver)->getFormatList()?>
    <? if ($this->driver->supportsAjaxStatus()): ?>
      <p><span class="ajax_availability hide status"><?=$this->transEsc('Loading')?>...</span></p>
    <? endif; ?>
  </div>
</a>
<? // Allow editing if a list is selected and edit is allowed OR if no list is selected
   // and a user is logged in (which means we are viewing all of the user's favorites)
   if ((isset($list) && $list->editAllowed($this->user)) || (!isset($list) && $this->user)): ?>
     <? /* Use a different delete URL if we're removing from a specific list or the overall favorites: */
       $deleteUrl = is_null($list_id)
           ? $this->url('myresearch-favorites')
           : $this->url('userList', array('id' => $list_id));
       $deleteUrl .= '?delete=' . urlencode($id) . '&amp;source=' . urlencode($source);
     ?>
     <a class="delete_from_mylist" href="<?=$deleteUrl?>" rel="external"><?=$this->transEsc('Delete')?></a>
<? endif; ?>