<h3>Admins</h3>
<p>Additional admins must be unlocked manually in the database by the development team.</p>

<table class="table">
  <tr>
    <th><?=$this->transEsc('Username')?></th>
    <th><?=$this->transEsc('First Name')?></th>
    <th><?=$this->transEsc('Last Name')?></th>
    <th><?=$this->transEsc('Email Address')?></th>
  </tr>
  <?php foreach ($this->admins as $user): ?>
    <tr>
      <td><?=$user->username?></td>
      <td><?=$user->firstname?></td>
      <td><?=$user->lastname?></td>
      <td><?=$user->email?></td>
    </tr>
  <?php endforeach; ?>
</table>
