<?php
// Set up page title:
$this->headTitle($this->translate('User Authorities'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs = '<li><a href="' .  $this->url('myresearch-home') . '">' . $this->transEsc('Your Account') . '</a></li> <li class="active">' . $this->transEsc('User Authorities') . '</li>';
?>

<div class="<?=$this->layoutClass('mainbody')?>">
  <h2>User Authorities</h2>
  <?php if (count($this->users) == 0): ?>
    <p>No user has requested access to any authority record so far.</p>
  <?php else: ?>
    <table class="table">
      <tr>
        <th><?=$this->transEsc('Username')?></th>
        <th><?=$this->transEsc('First Name')?></th>
        <th><?=$this->transEsc('Last Name')?></th>
        <th><?=$this->transEsc('Email Address')?></th>
        <th><?=$this->transEsc('Author')?></th>
        <th><?=$this->transEsc('Status')?></th>
        <th><?=$this->transEsc('Created')?></th>
        <th><?=$this->transEsc('Granted')?></th>
        <th><?=$this->transEsc('Actions')?></th>
      </tr>
      <?php foreach ($this->users as $user): ?>
        <tr>
          <td><?=$user->username?></td>
          <td><?=$user->firstname?></td>
          <td><?=$user->lastname?></td>
          <td><?=$user->email?></td>
          <td><a href="/Authority/<?=urlencode($user->authority_id)?>"><?=$user->authority_id?></a></td>
          <td><?=$user->access_state?></td>
          <td><?=date("d.m.Y H:i:s",strtotime($user->requested_datetime));?></td>
          <td><?=($user->granted_datetime)?date("d.m.Y H:i:s",strtotime($user->granted_datetime)):"";?></td>
          <td>
            <?php if ($user->access_state == 'requested'): ?>
              <a href="<?=$this->url('authority-process-request', ['user_id' => $user->user_id, 'authority_id' => $user->authority_id])?>" data-lightbox="">process request</a>
            <?php endif; ?>
          </td>
        </tr>
      <?php endforeach; ?>
    </table>
  <?php endif; ?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar">
  <?=$this->context($this)->renderInContext("myresearch/menu.phtml", ['active' => 'showuserauthorities'])?>
</div>
