<?php
  // Set page title.
  $this->headTitle($this->translate('permission_denied_title'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  $this->breadcrumbs()->set($this->translate('An error has occurred'), active: true);
?>
<div>
  <h2><?=$this->transEsc('permission_denied_title')?></h2>
  <p><?=$this->flashmessages()?></p>
  <p>
    <?=$this->transEsc('permission_denied')?>
    <?php if (!empty($msg)): ?>
      <div class="alert alert-danger"><?=$this->transEsc($msg)?></div>
    <?php endif; ?>
  </p>
  <?=$this->render('error/contact.phtml')?>
</div>
