<?php
  // Set page title.
  $this->headTitle($this->translate('permission_denied_title'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  $this->layout()->breadcrumbs = '<li class="active">Error</li>';
?>
<div>
  <h2><?=$this->transEsc('permission_denied_title')?></h2>
  <p><?=$this->flashmessages()?></p>
  <p>
    <?=$this->transEsc('permission_denied')?>
    <?php if (!empty($msg)): ?>
      <div class="alert alert-danger"><?=$this->transEsc($msg)?></div>
    <?php endif; ?>
  </p>
  <p>
    <?=$this->transEsc('Please contact the Library Reference Department for assistance')?>
    <br>
    <?php $supportEmail = $this->escapeHtmlAttr($this->systemEmail()); ?>
    <a href="mailto:<?=$supportEmail?>"><?=$supportEmail?></a>
  </p>
</div>
