<?php
  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  $this->breadcrumbs()->set($this->translate('An error has occurred'), active: true);
?>
<div class="alert alert-warning">
  <?=$this->component('page-title', ['title' => $this->translate('System Unavailable')]);?>
  <p>
    <?=$this->transEsc('The system is currently unavailable due to system maintenance')?>.
    <?=$this->transEsc('Please check back soon')?>.
  </p>
  <?=$this->render('error/contact.phtml')?>
</div>
