<div class="background-lightblue">
    <div class="container">
        <div class="row">
            <?=$this->render('partials/krimdok.phtml'); ?>
            <?=$this->render('partials/news.phtml'); ?>
            <?=$this->render('partials/fid.phtml'); ?>
            <?=$this->render('partials/externals.phtml'); ?>
        </div>
        <div class="row">
            <?=$this->render('partials/acquisition.phtml'); ?>
            <?=$this->render('partials/partners.phtml'); ?>
            <?=$this->render('partials/catalogs.phtml'); ?>
        </div>
    </div>
</div>
