<ul class="nav nav-pills">
    <li>
        <a href="<?=$this->advSearchUrl . ((isset($this->searchId) && $this->searchId) ? '?edit=' . $this->escapeHtmlAttr($this->searchId) : $this->hiddenFilterParams)?>"
           class="btn btn-link" role="button"
           rel="nofollow"><?= $this->transEsc("Advanced Search") ?></a>
    </li>

    <!-- IxTheo2: hide sevaral pills which have been moved to separate bar -->

    <!-- IxTheo only: virtual keyboard -->
    <li class="dropdown">
        <a class="btn btn-light dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
              <?=$this->transEsc('Virtual Keyboard')?> <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
            <li><a class="dropdown-item virtual-keyboard-greek"><?=$this->transEsc('Greek')?></a></li>
            <li><a class="dropdown-item virtual-keyboard-hebrew"><?=$this->transEsc('Hebrew')?></a></li>
            <script>$(triggerVirtualKeyboard('<?=$this->transEsc("Accept") . ':' . $this->transEsc("Accept")?>',
                                             '<?=$this->transEsc("Enter") . ':' . $this->transEsc("Enter")?>'));
            </script>
        </ul>
    </li>
</ul>
