<?php if (!empty($this->authors)): ?><?=$this->escapeHtml($this->authors)?>
  <?php if (!empty($this->year)): ?>
    <?php if (!preg_match("/^\[\d+\]/", $this->year)): ?>
      (<?=$this->escapeHtml($this->year)?>).
    <?php else: ?>
      <?=$this->escapeHtml($this->year)?>.
    <?php endif; ?>
  <?php endif; ?>
<?php endif; ?>
<i><?=$this->escapeHtml($this->title)?></i><?php if ($this->periodAfterTitle): ?>. <?php endif ?>
<?php if (empty($this->authors)): ?>
  <?php if (!empty($this->year)): ?> (<?=$this->escapeHtml($this->year)?>). <?php endif; ?>
<?php endif; ?>
<?php if (!empty($this->edition)): ?>(<?=$this->escapeHtml($this->edition)?>). <?php endif; ?>
<?php if (!empty($this->publisher)): ?><?=$this->escapeHtml($this->publisher)?>.<?php endif; ?>
