<?php
  // Set up breadcrumbs:
  $this->breadcrumbs()->set($this->translate('Your Account'), $this->url('myresearch-home'))
    ->add($this->translate('Tags'), active: true);

  $this->assetManager()->appendScriptLink('requests.js');
  $tabs = $this->accountCapabilities()->getUserReviewTabs();
?>
<?php $this->headTitle($this->translate('Tags'));?>
<?=$this->component('show-account-menu-button')?>

<div class="<?=$this->layoutClass('mainbody')?>">
<ul class="nav nav-tabs" role="tablist">
    <?php foreach ($tabs as $tab): ?>
      <li class="nav-item" role="presentation" id="user-review-<?=$tab?>" data-tab="<?=$this->escapeHtmlAttr($tab)?>"><a class="<?='tag' === $tab ? 'active' : ''?> nav-link" href="<?=$this->url($tab . '-' . 'user' . $tab)?>"><?=$this->transEsc(ucfirst($tab))?></a></li>
    <?php endforeach; ?>
  </ul>
  <div class="userreviews-header">
  <h2><?=$this->transEsc('Your Tags')?></h2>
    <?php if ($this->sortList): ?>
      <?=$this->context($this)->renderInContext('myresearch/controls/sort.phtml', ['sortList' => $this->sortList]); ?>
    <?php endif; ?>
  </div>
  <?php if (count($this->tags) !== 0): ?>
    <form action="<?=$this->url('tag-deletetags')?>" name="updateForm" id="select_all_tags" method="post">
      <input type="hidden" value="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash())?>" name="csrf">
      <label>
        <div class="checkbox">
          <input type="checkbox" name="selectAll" class="checkbox-select-all">
          <?=$this->transEsc('select_all_on_page')?>
        </div>
      </label>
      <?=
        $this->component(
            'confirm-button',
            [
                'buttonId' => 'cancelSelected',
                'buttonName' => 'cancelSelected',
                'buttonLabel' => 'delete_selected',
                'header' => 'confirm_usertag_delete_selected_text',
                'confirmId' => 'confirm_cancel_selected_yes',
                'cancelClass' => 'confirm_cancel_no',
                'ignoreLightbox' => true,
            ]
        )
      ?>
      <table class="userreviews-table table-striped table table-responsive">
        <thead>
          <tr>
            <th></th>
            <th><?=$this->transEsc('Created')?></th>
            <th><?=$this->transEsc('Title')?></th>
            <th><?=$this->transEsc('Tag')?></th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($this->tags as $tag):?>
            <tr>
              <td class="checkbox-col">
                <div class="checkbox-container result">
                  <div class="checkbox">
                    <label>
                    <span class="sr-only"><?=$this->transEsc('Select');?></span>
                    <input class="checkbox-select-item" type="checkbox" name="deleteSelectedtag[]" value="<?=$this->escapeHtmlAttr(($tag['id'] ?? ''))?>" id="checkbox_tag_<?=$tag['id']?>">
                    </label>
                  </div>
                </div>
              </td>
              <td><?=$this->dateTime()->convertToDisplayDateAndTime('Y-m-d H:i:s', $tag['posted'])?></td>
              <td>
                <a href="<?=$this->url('record', ['id' => $tag['record_id']])?>"><?=$tag['recordTitle']?></a>
              </td>
              <td class="user-tag">
                <div><?=$this->escapeHtml($tag['tag'])?></div>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </form>
  <?php endif;?>
  <?=$this->paginationControl($this->tags, 'Sliding', 'Helpers/pagination.phtml', ['params' => $this->params])?>
</div>

<div class="<?=$this->layoutClass('sidebar')?>" id="myresearch-sidebar" role="navigation" aria-label="<?=$this->transEsc('account_menu_label')?>">
  <?=$this->accountMenu()->render('userreviews')?>
</div>
