<!-- auth - ils - newpassword.phtml -->
<? if (isset($this->username)): ?>
  <div class="row">
    <label class="medium-3 columns"><?=$this->transEsc('Username') ?>:</label>
    <div class="medium-9 columns">
      <p class="auto"><?=$this->username ?></p>
    </div>
  </div>
<? endif; ?>
<? if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <div class="row">
    <label class="medium-3 columns"><?=$this->transEsc('old_password') ?>:</label>
    <div class="medium-9 columns">
      <input type="password" name="oldpwd" class="auto"/>
      <div class="help-block with-errors"></div>
    </div>
  </div>
<? endif; ?>
<div class="row">
  <label class="medium-3 columns"><?=$this->transEsc('new_password') ?>:</label>
  <div class="medium-9 columns">
    <input type="password" id="password" name="password" class="auto" required aria-required="true"<?=isset($this->passwordPolicy['minLength']) ? ' data-minlength="' . $this->passwordPolicy['minLength'] . '" data-minlength-error="' . $this->escapeHtmlAttr($this->translate('password_minimum_length', array('%%minlength%%' => $this->passwordPolicy['minLength']))) . '"' : ''?><?=isset($this->passwordPolicy['maxLength']) ? ' maxlength="' . $this->passwordPolicy['maxLength'] . '"' : ''?>/>
    <div class="help-block with-errors"></div>
  </div>
</div>
<div class="row">
  <label class="medium-3 columns"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <div class="medium-9 columns">
    <input type="password" name="password2" class="auto" required aria-required="true" data-match="#password" data-match-error="<?=$this->escapeHtmlAttr($this->translate('Passwords do not match'))?>"/>
    <div class="help-block with-errors"></div>
  </div>
</div>
<!-- auth - ils - newpassword.phtml - END -->