<?
    // Get available tabs; disable "staff view" in mobile UI:
    $tabs = isset($this->driver) ? $this->driver->getTabs() : array();
    unset($tabs['Details']);
?>
<? if (!empty($tabs)): ?>
  <div data-role="navbar">
    <ul>
      <? foreach ($tabs as $action => $desc): ?>
        <li>
          <a rel="external"<?=(strtolower(isset($this->tab) ? $this->tab : '') == strtolower($action)) ? ' class="ui-btn-active"' : ''?> href="<?=$this->recordLink()->getUrl($this->driver, $action)?>"><?=$this->transEsc($desc)?></a>
        </li>
      <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>