<div class="limitSelect text-right">
  <? $limitList = $this->params->getLimitList(); if (count($limitList) > 1): ?>
    <form action="<?=$this->currentPath() . $this->results->getUrlQuery()->setLimit(null)?>" class="form-inline" method="post">
      <label for="limit" class="help-inline"><?=$this->transEsc('Results per page')?></label>
      <select id="limit" name="limit" class="jumpMenu">
        <? foreach ($limitList as $limitVal => $limitData): ?>
          <option value="<?=$this->escapeHtmlAttr($limitVal)?>"<?=$limitData['selected']?' selected="selected"':''?>><?=$this->escapeHtml($limitData['desc'])?></option>
        <? endforeach; ?>
      </select>
      <noscript><input type="submit" value="<?=$this->transEsc("Set")?>" /></noscript>
    </form>
  <? endif; ?>
</div>
