<?php
    $index = $this->recommend->getIndex();
    $from = $this->recommend->getQuery();
    $link = $this->translate(
        'alphabrowselink_html',
        [
            '%%index%%' => $this->transEsc('browse_' . $index),
            '%%from%%' => $this->escapeHtml($from),
            '%%url%%' => $this->url('alphabrowse-home')
              . '?from=' . urlencode($from) . '&amp;source=' . urlencode($index),
        ]
    );
?>
<div class="alert alert-info"><?=$link?></div>
