<? if ($this->recommend->getResults()->getResultTotal() > 0): ?>
  <? $similarAuthors = $this->recommend->getSimilarAuthors(); ?>
  <? if (!empty($similarAuthors['list'])): ?>
    <div class="row">
      <p><?=$this->transEsc('Author Results for')?> <strong><?=$this->escapeHtml($this->recommend->getSearchTerm()) ?></strong></p>
      <div class="col-sm-4">
      <? foreach($similarAuthors['list'] as $i => $author): ?>
        <? if ($i == 5): ?>
        <a href="<?=$this->url('author-search') . '?lookfor=' . urlencode($this->recommend->getSearchTerm()) ?>"><strong><?=$this->transEsc("see all") ?> <?=(isset($similarAuthors['count']) && $similarAuthors['count']) ? $similarAuthors['count'] : ''?> &raquo;</strong></a>
      </div>
      <div class="col-sm-4">
        <? endif; ?>
        <a href="<?=$this->url('author-home') . '?author=' . urlencode($author['value'])?>"><?=$author['value'] ?><? /* count disabled -- uncomment to add: echo ' - ' . $author['count']; */ ?></a>
        <? if ($i+1<count($similarAuthors['list'])): ?>
          <br/>
        <? endif; ?>
      <? endforeach; ?>
      </div>
    </div>
    <br/>
  <? endif; ?>
<? endif; ?>
