<?php $this->info = $this->recommend->getAuthorInfo() ?>
<?php if (!(empty($this->info['description']) || empty($this->info))): ?>
<div class="wikipedia well clearfix">
  <h2><?=$this->info['name'] ?></h2>

  <?php if (isset($this->info['image'])): ?>
    <img class="pull-left flip" src="<?=$this->escapeHtmlAttr($this->info['image']) ?>" alt="<?=$this->escapeHtmlAttr($this->info['altimage']) ?>" width="150px">
  <?php endif; ?>

  <?=preg_replace('/___baseurl___/', $this->url('search-results'), $this->info['description']) ?>

  <a href="http://<?=$this->info['wiki_lang'] ?>.wikipedia.org/wiki/<?=$this->escapeHtmlAttr($this->info['name']/*url*/) ?>" target="new"><?=$this->transEsc('wiki_link') ?></a>
</div>
<?php endif; ?>
