<? $searchObject = $this->recommend->getResults(); $results = $searchObject->getResults(); if (!empty($results)): ?>
  <h4><?=$this->transEsc('Catalog Results')?></h4>
  <ul class="list-group">
    <? foreach ($results as $driver): ?>
      <li class="list-group-item catalog-result">
        <? $formats = $driver->getFormats(); $format = isset($formats[0]) ? $formats[0] : ''; ?>
        <a href="<?=$this->recordLink()->getUrl($driver)?>" class="title <?=$this->record($driver)->getFormatClass($format)?>">
          <?=$this->record($driver)->getTitleHtml()?>
        </a>
        <? $summDate = $driver->getPublicationDates(); ?>
        <? $summAuthors = $driver->getPrimaryAuthorsWithHighlighting(); ?>
        <? if (!empty($summDate) || !empty($summAuthors)): ?>
          <? if (!empty($summDate)): ?>
            <br/>
            <span class="small author">
              <?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($summDate[0])?>)
            </span>
          <? endif; ?>
          <? if (!empty($summAuthors)): ?>
            <br/>
            <span class="small"><?=$this->transEsc('By')?></span>
            <a class="small date" href="<?=$this->record($driver)->getLink('author', $this->highlight($summAuthors[0], null, true, false))?>"><?=$this->highlight($summAuthors[0])?></a><? if (count($summAuthors) > 1): ?><span class="small">, <?=$this->transEsc('more_authors_abbrev')?></span><? endif; ?>
          <? endif; ?>
        <? endif; ?>
      </li>
    <? endforeach; ?>
    <a class="list-group-item" href="<?=$this->url($searchObject->getOptions()->getSearchAction()) . $searchObject->getUrlQuery()->setLimit($searchObject->getOptions()->getDefaultLimit())?>"><?=$this->transEsc('More catalog results')?>...</a>
  </ul>
<? endif ?>