<?php
    // Set up Javascript for use below:
    $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
        . "\$('#edsResultsDeferredRecommend').load(url);";
?>
<div id="edsResultsDeferredRecommend">
    <p><?=$this->transEsc("Loading")?>... <img src="<?=$this->imageLink('ajax_loading.gif')?>" /></p>
    <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
