<?php $results = $this->recommend->getResults(); ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); ?>

<?php if (isset($sideFacetSet['tags']) && !empty($sideFacetSet['tags']['list'])): ?>
  <h3 id="acc-menu-favs-header" class="tag"><?=$this->transEsc($sideFacetSet['tags']['label'])?></h3>
  <nav aria-labelledby="acc-menu-favs-header">
    <ul class="list-group">
      <?php $filterList = $results->getParams()->getFilterList(true);
         $tagFilterList = $filterList[$sideFacetSet['tags']['label']] ?? null; ?>
      <?php if (!empty($tagFilterList)): ?>
        <?php $field = $sideFacetSet['tags']['label']; ?>
        <?php foreach ($tagFilterList as $filter): ?>
          <li>
            <?php $removeLink = $this->currentPath() . $results->getUrlQuery()->removeFacet($filter['field'], $filter['value']); ?>
            <a class="list-group-item active" href="<?=$removeLink?>">
              <span class="text"><?=$this->escapeHtml($filter['displayText'])?></span>
              <span class="pull-right flip"><?=$this->icon('ui-remove') ?></span>
            </a>
          </li>
        <?php endforeach; ?>
      <?php endif; ?>
      <?php foreach ($sideFacetSet['tags']['list'] as $thisFacet): ?>
        <?php if (!$thisFacet['isApplied']): ?>
          <li>
            <a class="list-group-item" href="<?=$this->currentPath() . $results->getUrlQuery()->addFacet('tags', $thisFacet['value'])?>">
              <span class="text"><?=$this->escapeHtml($thisFacet['displayText'])?></span>
              <span class="badge pull-right flip"><?=$this->escapeHtml($thisFacet['count'])?></span>
            </a>
          </li>
        <?php endif ?>
      <?php endforeach; ?>
    </ul>
  </nav>
<?php endif; ?>
