<? $visFacets = $this->recommend->getVisFacets(); ?>
<? if ($visFacets): ?>

  <? /* load jQuery flot */ ?>
<?$this->headScript()->appendFile('vendor/flot/excanvas.min.js', null, array('conditional' => 'IE'));
  $this->headScript()->appendFile('vendor/flot/jquery.flot.min.js');
  $this->headScript()->appendFile('vendor/flot/jquery.flot.resize.min.js');
  $this->headScript()->appendFile('vendor/flot/jquery.flot.selection.min.js');
  $this->headScript()->appendFile('pubdate_vis.js'); ?>

  <? foreach ($visFacets as $facetField=>$facetRange): ?>
    <div class="authorbox">
      <div id="datevis<?=$this->escapeHtml($facetField)?>xWrapper" class="hidden">
        <strong><?=$this->transEsc($facetRange['label']) ?></strong>
        <? /* space the flot visualisation */ ?>
        <div id="datevis<?=$facetField ?>x" style="margin:0 10px;width:auto;height:80px;cursor:crosshair;"></div>
        <div id="clearButtonText" style="display: none"><?=$this->transEsc('Clear') ?></div>
      </div>
    </div>
  <? endforeach; ?>
  <div id="dateVisColorSettings"><!-- do not delete! used for passing CSS to Javascript --></div>
  <?
    $js = "loadVis('" . $this->recommend->getFacetFields() . "', '"
        . $this->recommend->getSearchParams() . "', path, "
        . $this->recommend->getZooming() . ");";
    echo $this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $js, 'SET');
  ?>

<? endif; ?>
