<?php
  $this->headScript()->appendFile('facets.js');

  $results = $this->recommend->getResults();
  $options = $this->searchOptions($this->searchClassId);
?>
<?php if ($results->getResultTotal() > 0): ?>
  <h4><?=$this->transEsc(isset($this->overrideSideFacetCaption) ? $this->overrideSideFacetCaption : 'Narrow Search')?></h4>
<?php endif; ?>
<?php $checkboxFilters = $results->getParams()->getCheckboxFacets(); if (count($checkboxFilters) > 0): ?>
<?php
  $html = '';
  $shown = 0;
  foreach ($checkboxFilters as $current) {
    $html .= '<label class="checkbox';
    if($results->getResultTotal() < 1 && !$current['selected'] && !$current['alwaysVisible']) {
      $html .= ' hidden';
    } else {
      $shown ++;
    }
    $html .= '"><input type="checkbox" name="filter[]" value="'.$this->escapeHtmlAttr($current['filter']).'"
      '. ($current['selected'] ? 'checked="checked"' : '') .' id="'.$this->escapeHtmlAttr(str_replace(' ', '', $current['desc'])).'"
      onclick="document.location.href=\''.($current['selected'] ? $results->getUrlQuery()->removeFilter($current['filter']) : $results->getUrlQuery()->addFilter($current['filter'])).'\';" />'.$this->transEsc($current['desc']).'</label>';
  }
?>
  <div class="checkboxFilter<?if($shown == 0):?> hidden<?php endif; ?>"><?=$html ?></div>
<?php endif; ?>
<?php $extraFilters = isset($this->extraSideFacetFilters) ? $this->extraSideFacetFilters : []; ?>
<?php $collapsedFacets = $this->recommend->getCollapsedFacets() ?>
<?php $hierarchicalFacetSortOptions = $this->recommend->getHierarchicalFacetSortOptions() ?>
<?php $hierarchicalFacets = $this->recommend->getHierarchicalFacets() ?>
<?php $filterList = array_merge($results->getParams()->getFilterList(true), $extraFilters); if (!empty($filterList)): ?>
  <div class="list-group filters">
    <div class="list-group-item title"><?=$this->transEsc('Remove Filters')?></div>
    <?php foreach ($filterList as $field => $filters): ?>
      <?php foreach ($filters as $i => $filter): ?>
        <?php
          $index = isset($filter['field']) ? array_search($filter['field'], $collapsedFacets) : false;
          if ($index !== false) {
              unset($collapsedFacets[$index]); // Open if we have a match
          }
          if (isset($filter['specialType']) && $filter['specialType'] == 'keyword') {
            $removeLink = $this->currentPath().$results->getUrlQuery()->replaceTerm($filter['value'], '');
          } else {
            $removeLink = $this->currentPath().$results->getUrlQuery()->removeFacet($filter['field'], $filter['value'], $filter['operator']);
          }
          if ($filter['displayText'] == '[* TO *]') {
            $filter['displayText'] = $this->translate('filter_wildcard');
          }
        ?>
        <a class="list-group-item active" href="<?=$removeLink?>" title="<?=$this->transEsc('clear_tag_filter') ?>">
          <span class="pull-right flip"><i class="fa fa-times" aria-hidden="true"></i></span>
          <?php if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?><?=$this->transEsc($field)?>: <?=$this->escapeHtml($filter['displayText'])?>
        </a>
      <?php endforeach; ?>
    <?php endforeach; ?>
  </div>
<?php endif; ?>
<?= isset($this->sideFacetExtraControls) ? $this->sideFacetExtraControls : '' ?>
<?php $sideFacetSet = $this->recommend->getFacetSet(); $rangeFacets = $this->recommend->getAllRangeFacets(); ?>
<?php if (!empty($sideFacetSet) && $results->getResultTotal() > 0): ?>
  <?php foreach ($sideFacetSet as $title => $cluster): ?>
    <?php $allowExclude = $this->recommend->excludeAllowed($title); ?>
    <?php $facets_before_more = $this->recommend->getShowMoreSetting($title); ?>
    <?php $showMoreInLightbox = $this->recommend->getShowInLightboxSetting($title); ?>
    <div class="list-group facet" id="side-panel-<?=$this->escapeHtmlAttr($title) ?>">
      <div class="list-group-item title<?php if(in_array($title, $collapsedFacets)): ?> collapsed<?php endif ?>" data-toggle="collapse" href="#side-collapse-<?=$this->escapeHtmlAttr($title) ?>" >
        <?=$this->transEsc($cluster['label'])?>
      </div>
      <div id="side-collapse-<?=$this->escapeHtmlAttr($title) ?>" class="collapse<?php if(!in_array($title, $collapsedFacets)): ?> in<?php endif ?>">
        <?php if (isset($rangeFacets[$title])): ?>
          <div class="list-group-item">
            <form name="<?=$this->escapeHtmlAttr($title)?>Filter" id="<?=$this->escapeHtmlAttr($title)?>Filter">
              <?=$results->getUrlQuery()->asHiddenFields(['page' => "/./", 'filter' => "/^{$title}:.*/"])?>
              <input type="hidden" name="<?=$this->escapeHtmlAttr($rangeFacets[$title]['type'])?>range[]" value="<?=$this->escapeHtmlAttr($title)?>"/>
              <div class="row">
                <?php $extraInputAttribs = ($rangeFacets[$title]['type'] == 'date') ? 'maxlength="4" ' : ''; ?>
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>from">
                    <?=$this->transEsc('date_from')?>:
                  </label>
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>from" id="<?=$this->escapeHtmlAttr($title)?>from" value="<?=isset($rangeFacets[$title]['values'][0])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][0]):''?>" <?=$extraInputAttribs?>/>
                </div>
                <div class="col-sm-6">
                  <label for="<?=$this->escapeHtmlAttr($title)?>to">
                    <?=$this->transEsc('date_to')?>:
                  </label>
                  <input type="text" class="form-control" name="<?=$this->escapeHtmlAttr($title)?>to" id="<?=$this->escapeHtmlAttr($title)?>to" value="<?=isset($rangeFacets[$title]['values'][1])?$this->escapeHtmlAttr($rangeFacets[$title]['values'][1]):''?>" <?=$extraInputAttribs?>/>
                </div>
              </div>
              <?php if ($rangeFacets[$title]['type'] == 'date'): ?>
                <div class="slider-container"><input type="text" class="hidden" id="<?=$this->escapeHtmlAttr($title)?><?=$this->escapeHtml($rangeFacets[$title]['type'])?>Slider"/></div>
              <?php endif; ?>
              <input class="btn btn-default" type="submit" value="<?=$this->transEsc('Set')?>"/>
            </form>
          </div>
          <?php if ($rangeFacets[$title]['type'] == 'date'): ?>
            <?php $this->headScript()->appendFile('vendor/bootstrap-slider.min.js'); ?>
            <?php $this->headLink()->appendStylesheet('vendor/bootstrap-slider.min.css'); ?>
            <?php
              $min = !empty($rangeFacets[$title]['values'][0]) ? min($rangeFacets[$title]['values'][0], 1400) : 1400;
              $future = date('Y', time()+31536000);
              $max = !empty($rangeFacets[$title]['values'][1]) ? max($future, $rangeFacets[$title]['values'][1]) : $future;
              $low  = !empty($rangeFacets[$title]['values'][0]) ? $rangeFacets[$title]['values'][0] : $min;
              $high = !empty($rangeFacets[$title]['values'][1]) ? $rangeFacets[$title]['values'][1] : $max;
              $reversed = $this->layout()->rtl ? 'true' : 'false';
              $script = <<<JS
$(document).ready(function() {
  var fillTexts = function() {
  var v = {$this->escapeHtmlAttr($title)}dateSlider.getValue();
  $('#{$this->escapeHtmlAttr($title)}from').val(v[0]);
  $('#{$this->escapeHtmlAttr($title)}to').val(v[1]);
  };
  var {$this->escapeHtmlAttr($title)}dateSlider = $('#{$this->escapeHtmlAttr($title)}dateSlider')
  .slider({
    'min':{$min},
    'max':{$max},
    'handle':"square",
    'tooltip':"hide",
    'value':[{$low},{$high}],
    'reversed': {$reversed}
  })
  .on('change', fillTexts)
  .data('slider');
});

$('#{$this->escapeHtmlAttr($title)}from, #{$this->escapeHtmlAttr($title)}to').change(function () {
  var fromValue = Number($('#{$this->escapeHtmlAttr($title)}from').val());
  var toValue = Number($('#{$this->escapeHtmlAttr($title)}to').val());
  $('#{$this->escapeHtmlAttr($title)}dateSlider').slider(
    'setValue',
    [
      isNaN(fromValue) || fromValue <= 0 ? {$min} : fromValue,
      isNaN(toValue) || toValue <= 0 ? {$max} : toValue
    ],
    true
  );
});
JS;
            ?>
            <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
          <?php endif; ?>
        <?php else: ?>
          <?php if (in_array($title, $hierarchicalFacets)): ?>
            <?php $this->headScript()->appendFile('vendor/jsTree/jstree.min.js'); ?>
            <?php $sort = isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''; ?>
            <?php if (!in_array($title, $collapsedFacets)): ?>
              <?php
              $script = <<<JS
$(document).ready(function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <?php else: ?>
              <?php
              $script = <<<JS
$('#side-collapse-{$this->escapeHtmlAttr($title)}').on('show.bs.collapse', function() {
  initFacetTree($('#facet_{$this->escapeHtml($title)}'), true);
});
JS;
              ?>
              <?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
            <?php endif; ?>
            <li id="facet_<?=$this->escapeHtml($title)?>" class="jstree-facet"
                  data-facet="<?=$this->escapeHtmlAttr($title)?>"
                  data-path="<?=$this->currentPath()?>"
                  data-exclude="<?=$allowExclude?>"
                  data-operator="<?=$this->recommend->getFacetOperator($title)?>"
                  data-exclude-title="<?=$this->transEsc('exclude_facet')?>"
                  data-sort="<?=isset($hierarchicalFacetSortOptions[$title]) ? $hierarchicalFacetSortOptions[$title] : ''?>">
            </li>
            <noscript>
          <?php endif; ?>
          <?php foreach ($cluster['list'] as $i=>$thisFacet): ?>
              <?php
                if(strlen($thisFacet['displayText']) == 0) {
                  $thisFacet['displayText'] = "-";
                }
              ?>
              <?php $moreClass = 'narrowGroupHidden-'.$this->escapeHtmlAttr($title).' hidden'; ?>
            <?php if ($i == $facets_before_more): ?>
              <?php $idAndClass = 'id="more-narrowGroupHidden-'.$this->escapeHtmlAttr($title).'" class="list-group-item narrow-toggle"'; ?>
              <?php if ($facetLightbox = $options->getFacetListAction()): ?>
                <?php $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams().'&amp;facet='.$title.'&amp;facetop='.$thisFacet['operator'].'&amp;facetexclude='.($allowExclude ? 1 : 0); ?>
              <?php else: ?>
                <?php $moreUrl = '#'; ?>
              <?php endif; ?>
              <?php if (($showMoreInLightbox && $showMoreInLightbox !== 'more') && $facetLightbox): ?>
                <a <?=$idAndClass ?> data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('more')?> ...</a>
                <?php break; ?>
              <?php else: ?>
                <a <?=$idAndClass ?> href="<?=$moreUrl ?>" onclick="return moreFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')" rel="nofollow"><?=$this->transEsc('more')?> ...</a>
              <?php endif; ?>
            <?php endif; ?>
            <?php if ($thisFacet['isApplied']): ?>
              <a class="list-group-item active<?php if ($i >= $facets_before_more): ?><?=$moreClass ?><?endif ?><?php if ($thisFacet['operator'] == 'OR'): ?> facetOR applied<?php endif ?>" href="<?=$this->currentPath().$results->getUrlQuery()->removeFacet($title, $thisFacet['value'], $thisFacet['operator']) ?>" title="<?=$this->transEsc('applied_filter') ?>">
                <?php if ($thisFacet['operator'] == 'OR'): ?>
                  <i class="fa fa-check-square-o" aria-hidden="true"></i>
                <?php else: ?>
                  <span class="pull-right flip"><i class="fa fa-check" aria-hidden="true"></i></span>
                <?php endif; ?>
                <?=$this->escapeHtml($thisFacet['displayText'])?>
              </a>
            <?php else: ?>
              <?php $addURL = $this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], $thisFacet['operator']); ?>
              <?php if ($allowExclude): ?>
                <div class="list-group-item facet<?=$thisFacet['operator'] ?><?php if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <?php else: ?>
                <a href="<?=$addURL ?>" class="list-group-item facet<?=$thisFacet['operator'] ?><?php if ($i >= $facets_before_more): ?> <?=$moreClass ?><?endif ?>">
              <?php endif; ?>
              <span class="badge">
                <?=$this->localizedNumber($thisFacet['count'])?>
                <?php if ($allowExclude): ?>
                  <a href="<?=$this->currentPath().$results->getUrlQuery()->addFacet($title, $thisFacet['value'], 'NOT') ?>" title="<?=$this->transEsc('exclude_facet') ?>"><i class="fa fa-times" aria-hidden="true"></i></a>
                <?php endif; ?>
              </span>
              <?php if ($allowExclude): ?>
                <a href="<?=$addURL ?>">
              <?php endif; ?>
              <?php if($thisFacet['operator'] == 'OR'): ?>
                <i class="fa fa-square-o" aria-hidden="true"></i>
              <?php endif; ?>
              <?=$this->escapeHtml($thisFacet['displayText'])?>
              <?php if ($allowExclude): ?>
                  </a>
                </div>
              <?php else: ?>
                </a>
              <?php endif; ?>
            <?php endif; ?>
          <?php endforeach; ?>
          <?php if ($showMoreInLightbox === 'more' && $facetLightbox = $options->getFacetListAction()): ?>
            <?php $moreUrl = $this->url($facetLightbox) . $results->getUrlQuery()->getParams().'&amp;facet='.$title.'&amp;facetop='.$thisFacet['operator'].'&amp;facetexclude='.($allowExclude ? 1 : 0); ?>
            <a class="list-group-item narrow-toggle <?=$moreClass ?>" data-lightbox href="<?=$moreUrl ?>" rel="nofollow"><?=$this->transEsc('see all')?> ...</a>
          <?php endif; ?>
          <?php if ($i >= $facets_before_more): ?><a class="list-group-item narrow-toggle <?=$moreClass ?>" href="#" onclick="return lessFacets('narrowGroupHidden-<?=$this->escapeHtmlAttr($title) ?>')"><?=$this->transEsc('less')?> ...</a><?php endif; ?>
        <?php endif; ?>
        <?php if (in_array($title, $hierarchicalFacets)): ?>
          </noscript>
        <?php endif; ?>
      </div>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
