<?php
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "\$('#SummonDeferredBestBets').load(url);";
?>
<div id="SummonDeferredBestBets">
  <p><?=$this->transEsc("Loading")?>... <i class="fa fa-spinner" aria-hidden="true"></i></p>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
