<?php
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "VuFind.loadHtml(\$('#SummonDeferredDatabases'), url);";
?>
<div id="SummonDeferredDatabases">
  <p><?=$this->icon('spinner') ?> <?=$this->transEsc("Loading")?>...</p>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
