<?php
  // Set up Javascript for use below:
  $loadJs = 'var url = VuFind.path + "/AJAX/Recommend?' . $this->recommend->getUrlParams() . '";'
    . "\$('#SummonDeferredRecommend').load(url);";
?>
<div id="SummonDeferredRecommend">
  <h3><?=$this->transEsc("Summon Results")?></h3>
  <p><?=$this->transEsc("Loading")?>... <?=$this->icon('spinner', 'icon--spin') ?></p>
  <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $loadJs, 'SET')?>
</div>
