<?
  $searchTabs = is_object($this->params)
    ? $this->searchtabs()->getTabConfigForParams($this->params) : [];
?>
<? if (count($searchTabs) > 0): ?>
  <div class="alert alert-info">
    <?=$this->transEsc('nohit_change_tab', ['%%activeTab%%' => $this->translate($this->recommend->getActiveTab($searchTabs)['label'])])?>
    <ul>
    <? $inactiveTabs = $this->recommend->getInactiveTabs($searchTabs); ?>
    <? foreach ($inactiveTabs as $tab): ?>
      <li>
        <? if (!$tab['selected']): ?><a href="<?=$this->escapeHtmlAttr($tab['url'])?>"><? endif; ?>
          <?=$this->transEsc($tab['label']); ?>
        <? if (!$tab['selected']): ?></a><? endif; ?>
      </li>
    <? endforeach; ?>
    </ul>
  </div>
<? endif; ?>
