<?php $worldCatIdentities = $this->recommend->getIdentities(); if (!empty($worldCatIdentities)): ?>
  <div>
    <h3><?=$this->transEsc('Authors Related to Your Search')?></h3>
    <dl>
      <?php $i = 0; foreach ($worldCatIdentities as $author => $subjects): ?>
        <?php if (++$i == 4): ?>
          <dd id="more-WCIdents"><a href="#" onclick="moreFacets('WCIdents'); return false;"><?=$this->transEsc('more')?> ...</a></dd>
          <span class="hidden WCIdents">
        <?php endif; ?>
        <dd>
        <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($author)?>%22&amp;type=Author"><?=$this->escapeHtml($author)?></a>
        <?php if (count($subjects) > 0): ?>
          <dl>
          <dd><?=$this->transEsc('Related Subjects')?>:</dd>
          <?php $j = 0; foreach ($subjects as $subj): ?>
            <?php if (++$j == 3): ?>
              <dd id="more-WCIdents<?=$i?>"><a href="#" onclick="moreFacets('WCIdents<?=$i?>'); return false;"><?=$this->transEsc('more')?> ...</a></dd>
              <span class="hidden WCIdents<?=$i?>">
            <?php endif; ?>
            <dd>&bull; <a href="<?=$this->url('search-results')?>?lookfor=%22<?=urlencode($subj)?>%22&amp;type=Subject"><?=$this->escapeHtml($subj)?></a></dd>
          <?php endforeach; ?>
          <?php if ($j > 2): ?><dd><a href="#" onclick="lessFacets('WCIdents<?=$i?>'); return false;"><?=$this->transEsc('less')?> ...</a></dd></span><?php endif; ?>
          </dl>
        <?php endif; ?>
        </dd>
      <?php endforeach; ?>
      <?php if ($i > 3): ?><dd><a href="#" onclick="lessFacets('WCIdents'); return false;"><?=$this->transEsc('less')?> ...</a></dd></span><?php endif; ?>
    </dl>
  </div>
<?php endif; ?>
