<?php $records = $this->cart()->getRecordDetails(); ?>
<?php if (!empty($records)): ?>
  <ul class="cart-list">
  <?php foreach ($records as $i => $record): ?>
    <li class="cart-item">
      <label>
        <?=$this->record($record)->getCheckbox('cart')?>
        <a href="<?=$this->escapeHtmlAttr($this->recordLinker()->getUrl($record))?>" data-lightbox-ignore><?=$this->escapeHtml($record->getBreadcrumb())?></a>
      </label>
    </li>
  <?php endforeach; ?>
  </ul>
<?php else: ?>
  <p class="alert alert-info"><?=$this->transEsc('bookbag_is_empty')?>.</p>
<?php endif; ?>
