<!-- author - HOME.phtml -->
<?
    // Set page title.
    $this->headTitle($this->translate('Author'));

    // Set up breadcrumbs:
    $this->layout()->breadcrumbs = '<li class="active">' . $this->transEsc('Author') . '</li>';
?>
<form method="get" action="<?=$this->url('author-search')?>">
   <label for="author_lookfor"><?=$this->transEsc('Author Results for')?>:</label></br>
   <input class="auto-width" type="text" id="author_lookfor" name="lookfor" />
   <input class="button secondary small" type="submit" value="<?=$this->transEsc('Find')?>" aria-label="submit form" />
</form>
<!-- author - HOME.phtml - end -->