<?php // This template is a JSON Swagger specification base.
      // Fragments from other controllers will get merged with this one.
?>
<?php $basePath = rtrim($this->url('home'), '/') . '/api/v1'; ?>
{
    "swagger": "2.0",
    "info": {
        "title": "<?=$this->config->Site->title ?>",
        "version": "<?=$this->version ?>"
    },
    "basePath": "<?=$basePath ?>",
    "produces": [
        "application/json"
    ],
    "definitions": {
        "Success": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status code",
                    "type": "string",
                    "enum": ["OK"]
                },
                "statusMessage": {
                    "description": "A descriptive error message",
                    "type": "string"
                }
            },
            "required": ["status"]
        },
        "Error": {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Status code",
                    "type": "string",
                    "enum": ["ERROR"]
                },
                "statusMessage": {
                    "description": "A descriptive error message",
                    "type": "string"
                }
            },
            "required": ["status", "statusMessage"]
        }
    }
}
