<h1>Aide sur la recherche avancée</h1>

<ul class="HelpMenu">
  <li><a href="#search_fields">Champ de recherche</a></li>
  <li><a href="#search_groups">Groupe de recherche</a></li>
</ul>

<dl class="Content">
  <dt><a id="search_fields"></a>Champ de recherche</dt>
  <dd>
    <p>Dans chaque champ de recherche, vous pouvez saisir les mots pour lesquels vous désirez trouver un résultat. Certaines
       chaînes de caractères, ou <a href="<?=$this->url('help', ['topic' => 'search'])?>">« opérateurs »</a>
       , modifient le comportement de la recherche.
    </p>
    <p>Pour chaque champ de recherche, un menu déroulant permet de
       préciser la fonction du terme recherché (titre, auteur etc.).
       Vous pouvez ainsi combiner plusieurs critères.
    </p>
    <p>Le paramètre "correspond à" permet de modifier le comportement de recherche
       avec plusieur champs de recherche:
    </p>
    <ul>
      <li>TOUS les termes - Pour afficher les notices qui correspondent
        à l'ensemble des mots saisis (ET).</li>
      <li>UN des termes - Pour afficher les notices qui correspondent
          à au moins l'un ou l'autre des mots saisis (OU).</li>
      <li>AUCUN terme - À utiliser seul dans un groupe de recherche pour exclure les notices
          qui ne correspondent pas aux mots saisis.</li>
    </ul>
    <p>Vous pouvez ajouter tant de champ de recherche que nécessaire, en
       cliquant sur "Ajouter un champ de recherche".
    </p>
  </dd>

  <dt><a id="search_groups"></a>Groupe de recherche</dt>
  <dd>
    <p>Un groupe de recherche permet de formuler une recherche plus complexe, en
       combinant plusieurs groupes de champs de recherche. Il est possible d'ajouter
       un nouveau groupe en cliquant sur "Ajouter un groupe de recherche",
       ou d'en effacer un en cliquant sur "Effacer un groupe de
       recherche". Pour combiner les critères définis par chaque groupe, vous pouvez
       choisir "TOUS les groupes" ou "UN des groupes".
    </p>
    <p>Exemple : pour trouver des ressources sur l'histoire de Chine ou de l'Inde
       vous pouvez faire une recherche de la manière suivante:
    </p>
    <ul>
      <li>Dans le premier groupe, saisir "Inde" dans le premier champ, "Chine" dans le deuxième,
          et choisir la correspondance "UN des termes".
      </li>
      <li>Ajouter un second groupe de recherche et saisir "histoire".</li>
      <li>Choisir la correspondance sur "TOUS les groupes de recherche".
      </li>
    </ul>
  </dd>
</dl>
