<div id="breaking_news">
  <h4 style="color: #ffb30f; margin-top: 12px; margin-bottom: 2px">Attention:</h4>
  <p>The Index for Canon Law is a partial extract from the IxTheo. It offers a subject selection for Catholic, Protestant and Orthodox canon law. The selection of titles is already up to date. See the selection criteria <a href="https://github.com/ubtue/tuefind/wiki/Daten-Abzugs--und-Selektionskriterien#selektionskriterium-f%C3%BCr-das-subsystem-kirchenrecht" target="_blank">here</a>. Layout and texts still have to be adapted, we ask for your patience!</p>
</div>
