<form action="<?=$this->url() ?>/MyResearch/Export" method="post" name="bulkExport">
  <? if ($errorMsg): ?><div class="error"><?=$this->transEsc($errorMsg) ?></div><? endif; ?>
  <? if ($infoMsg): ?><div class="info"><?=$this->transEsc($infoMsg) ?></div><? endif; ?>

  <div id="popupMessages"></div>
  <div id="popupDetails"> 
    <? if (empty($exportOptions)): ?>
      <div class="error"><?=$this->transEsc("bulk_export_not_supported") ?></div>
    <? else: ?>
      <? foreach ($exportList as $favorite): ?>
        <strong><?=$this->transEsc('Title') ?>:</strong>
        <?=$this->escapeHtml(favorite['title']) ?><br />
      <? endforeach; ?>
      <label for="format"><?=$this->transEsc('Format') ?>:</label>
      <select id="format" name="format">
        <? foreach ($exportOptions as $exportOption): ?>
          <option value="<?=$this->escapeHtmlAttr($exportOption) ?>"><?=$this->transEsc($exportOption) ?></option>
        <? endforeach; ?>
      </select>
      <br />
      <input class="button" type="submit" name="submit" value="<?=$this->transEsc('Export') ?>" />
      <? foreach ($exportIDS as $exportID): ?>
        <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($exportID) ?>" />
      <? endforeach; ?>
      <? if ($listID): ?>
        <input type="hidden" name="listID" value="<?=$this->escapeHtmlAttr($listID) ?>" />
      <? endif; ?>
      <? if ($followupModule): ?>
        <input type="hidden" name="followupModule" value="<?=$this->escapeHtmlAttr($followupModule) ?>" />
      <? endif; ?>
      <? if ($followupAction): ?>
        <input type="hidden" name="followupAction" value="<?=$this->escapeHtmlAttr($followupAction) ?>" />
      <? endif; ?>
    <? endif; ?>
  </div>
</form>