<?php
    $this->headLink()->appendStylesheet($this->src);
    $this->headLink()->appendStylesheet('icon-helper.css');

    // Append extra classes
    if (isset($this->extra['class'])) {
        $this->icon .= ' ' . $this->extra['class'];
        $this->attrs = preg_replace('/ class="[^"]+"/', '', $this->attrs);
    }
?>
<span class="icon--font <?=$this->icon ?>"<?=$this->attrs ?> role="img" aria-hidden="true"></span>
