<? $this->info = $this->recommend->getAuthorInfo() ?>
<? if (!(empty($this->info['description']) || empty($this->info))): ?>
<div class="well">
  <p class="lead"><?=$this->info['name'] ?></p>

  <? if (isset($this->info['image'])): ?>
    <img class="pull-left pad" src="<?=$this->info['image'] ?>" alt="<?=$this->escapeHtml($this->info['altimage']) ?>" width="150px"/>
  <? endif; ?>

  <?=preg_replace('/___baseurl___/', $this->url('search-results'), $this->info['description']) ?>

  <a class="wikipedia" href="http://<?=$this->info['wiki_lang'] ?>.wikipedia.org/wiki/<?=$this->escapeHtml($this->info['name']/*url*/) ?>" target="new"><?=$this->translate('wiki_link') ?></a>
</div>
<? endif; ?>