<? $recommend = $this->recommend->getResults(); if (count($recommend)> 0): ?>
  <h4><?=$this->transEsc("random_recommendation_title")?></h4>
  <ul class="random <?=$this->recommend->getDisplayMode()?>">
    <? foreach ($recommend as $driver): ?>
      <li>

      <?if($this->recommend->getDisplayMode() === "images" || $this->recommend->getDisplayMode() === "mixed"):?>

        <? /* Display thumbnail if appropriate: */ ?>
        <? $smallThumb = $this->record($driver)->getThumbnail('small'); $mediumThumb = $this->record($driver)->getThumbnail('medium'); ?>
        <? if ($smallThumb): ?>
          <a href="<?=$this->recordLink()->getUrl($driver)?>">
           <img alt="<?=$this->transEsc('Cover Image')?>" src="<?=$this->escapeHtml($smallThumb);?>"/><br />
          </a>
        <?elseif($mediumThumb):?>
          <a href="<?=$this->recordLink()->getUrl($driver)?>">
            <img alt="<?=$this->transEsc('Cover Image')?>" src="<?=$this->escapeHtml($mediumThumb);?>"/><br />
          </a>
        <? else: ?>
          <img src="<?=$this->url('cover-unavailable')?>" alt="<?=$this->transEsc('No Cover Image')?>"/><br />
        <? endif; ?>

      <?endif;?>

     <?if($this->recommend->getDisplayMode() === "standard" || $this->recommend->getDisplayMode() === "mixed"):?>
          <? $formats = $driver->getFormats(); $format = isset($formats[0]) ? $formats[0] : ''; ?>
          <a href="<?=$this->recordLink()->getUrl($driver)?>" class="title <?=$this->record($driver)->getFormatClass($format)?>"><?
            $summTitle = $driver->getTitle();
            if (!empty($summTitle)) {
                echo $this->escapeHtml($this->truncate($summTitle, 180));
            } else {
                echo $this->transEsc('Title not available');
            }
          ?></a>
          <? $summAuthor = $driver->getPrimaryAuthor(); if (!empty($summAuthor)): ?>
          <br />
          <?=$this->transEsc('By')?>:
          <a href="<?=$this->record($driver)->getLink('author', $summAuthor)?>">
            <?=$this->escapeHtml($summAuthor)?>
          </a>
          <? endif; ?>
          <? $summDate = $driver->getPublicationDates(); if (!empty($summDate)): ?>
          <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($summDate[0])?>)
          <? endif; ?>
       <?endif;?>
      </li>
    <? endforeach; ?>
  </ul>
<?endif;?>
