<div class="col-xs-12 col-sm-6 col-md-3 panel-buttons">
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">Example</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">Example</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">Example</a>
    </div>
    <div class="row panel-button">
        <a href="#" class="btn btn-primary">Example</a>
    </div>
</div>
