<div class="col-xs-12 col-sm-6 col-md-3 panel panel-top panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/discover.jpg') ?>" alt="" class="img-responsive panel-image"></div>
    <div class="panel-content">
        <h4>Example</h4>
        <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr...</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
