<div data-role="navbar">
  <ul>
    <li><a data-rel="dialog" href="#Language-dialog" data-transition="pop"><?=$this->transEsc('Language')?></a></li>
    <? if (is_object($this->account) && $this->account->loginEnabled()): // hide login/logout if unavailable ?>
      <li><a rel="external" href="<?=$this->url('myresearch-home')?>"><?=$this->transEsc('Account')?></a></li>
    <? endif; ?>
    <? if ($this->account->isLoggedIn()): ?>
      <li><a rel="external" href="<?=$this->url('myresearch-logout')?>"><?=$this->transEsc("Log Out")?></a></li>
    <? endif; ?>
  </ul>
</div>
