<!-- finc: recordtab - acquistionpda -->
<?php
/**
origin: finc
called by view helper/controller:
usage:
modified for finc:
 * finc specific template
configured in: {}
 */
?>
<?php
  // Set page title.
  $this->headTitle(
    $this->translate('PDA::Acquisition') . ': ' .
    $this->driver->getBreadcrumb()
  );
  // Get some variables
  $id = $this->driver->getUniqueId();
  // $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $controllerClass = 'controller:SolrMarcFincPDA';
?>
<h2><?=$this->transEsc('PDA::Acquisition')?></h2>
<p><?=$this->transEsc('PDA::pda_initial_text')?></p>
<p class="alert alert-info" aria-live="polite"><?=$this->transEsc('PDA::pda_restriction_text')?></p>
<div class="btn-group">
  <?php /* finc: leaves title in here - it is used for the tooltip! - CK */ ?>
  <?= $this->externalLink(
        $this->interlibraryloan()->getSwbLink($this->driver),
        $this->translate('PDA::pda_tab_interlibrary_button'),
        [ 'class' => 'btn btn-primary',
          'data-toggle' => 'tooltip',
          'title' => $this->translate('PDA::pda_open_new_window')]
      ) ?>
  <a class="btn btn-primary pda-button <?=$controllerClass?>" data-lightbox href="<?=$this->url('record-pda', array('id' => $id))?>" rel="nofollow">
    <?=$this->transEsc('PDA::pda_tab_order_button')?>
  </a>
</div>
<!-- finc: recordtab - acquistionpda - END -->
