<!-- finc: RecordTab - collectionlist -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * adds SECOND offcanvas-toggler
 * removes div with classname 'collection-list-controls'
 * We're NEITHER showing the found xxx of yyy number NOR the query time
 * do NOT render search/list-list into the <form>-element, it is causing W3C errors #19697
 * changes h4 to h3
 * keeps '.bottom' to differentiate top and bottom sidebars
 * uses section for sidebar #23430
 * uses search in sidebar, not in mainbody
 * removes div with 'collection-control'
 * adds h2 to sidebar
 * uses 'Search Collection Items' instead of 'Search'
 * adds aria-hidden to icon
configured in: {}
 */
?>
<?php
  // Set page title.
  $this->headTitle($this->translate('Collection Items') . ': ' . $this->driver->getBreadcrumb());

  // Get search results
  $results = $this->tab->getResults();
  $params = $this->tab->getParams();
  $searchDetails = ['results' => $results, 'params' => $params, 'indexStart' => 1];

  $filterList = $params->getFilterList(true);
  $checkboxFilters = $params->getCheckboxFacets();
?>
<div class="<?=$this->layoutClass('mainbody')?>">
  
  <?php /* finc: adds SECOND offcanvas-toggler here,
       this one should hide the '.icon-bar' of the Record View and
       shows  only the Facets Sidebar for the collection - CK */ ?>
  <span class="offcanvas-toggler">
    <a class="search-filter-toggle collections visible-xs" href="javascript:" data-toggle="offcanvas" title="<?= $this->transEscAttr('sidebar_expand_collections') ?>">
      <?=$this->transEsc('sidebar_expand_collections')?>
    </a>
  </span>

  <?php if (($recordTotal = $results->getResultTotal()) > 0): // only display these at very top if we have results ?>
    <?php foreach ($results->getRecommendations('top') as $current): ?>
      <?=$this->recommend($current)?>
    <?php endforeach; ?>
  <?php endif; ?>

  <?php /* finc: removes div with classname 'collection-list-controls' here */ /*
  <div class="collection-list-controls"> */ ?>
    <?php /* finc: uses search in sidebar, see  'Recommend/CollectionSideFacets.phtml' */ /*
    <div class="collection-control">
      <form class="form-inline" role="form" method="get" name="keywordFilterForm" id="keywordFilterForm">
        <div class="input-group">
          <input id="keywordFilter_lookfor" type="text" name="lookfor" placeholder="<?=$this->transEscAttr('Search within collection')?>" value="<?=$this->escapeHtmlAttr($params->getDisplayQuery())?>" class="form-control">
          <?php foreach ($filterList as $field => $filters): ?>
            <?php foreach ($filters as $filter): ?>
              <input type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($filter['field'])?>:&quot;<?=$this->escapeHtmlAttr($filter['value'])?>&quot;">
            <?php endforeach; ?>
          <?php endforeach; ?>
          <input type="hidden" name="limit" value="<?=$this->escapeHtmlAttr($params->getLimit()) ?>">
          <input type="hidden" name="sort" value="<?=$this->escapeHtmlAttr($params->getSort()) ?>">
          <span class="input-group-btn">
            <button class="btn btn-primary" type="submit" name="submit">
              <span class="sr-only"><?=$this->transEsc('Search')?></span><i class="fa fa-search"></i>
            </button>
          </span>
        </div>
      </form>
    </div>
    */?>
    <div class="collection-control">
      <?=$this->render('search/controls/limit.phtml', $searchDetails)?>
    </div>
    <div class="collection-control">
      <?=$this->render('search/controls/sort.phtml', $searchDetails)?>
    </div>
  <?php /*
  </div>
  */?>


  <?php if ($filterList || $checkboxFilters): ?>
    <?=
      $this->render(
          'search/filters.phtml',
          [
            'urlQuery' => $results->getUrlQuery(),
            'filterList' => $filterList,
            'checkboxFilters' => $checkboxFilters,
            'searchClassId' => $this->searchClassId,
            'searchType' => 'basic',
          ]
      );
    ?>
  <?php endif; ?>

  <div class="collection-list-results">
    <?php if ($recordTotal > 0): ?>
      <div class="clearfix hidden-print">
        <?php /* finc: We're NEITHER showing the found xxx of yyy number NOR the query time */ /*
        <div class="pull-left flip">
          <?php
            $transParams = [
              '%%start%%' => $this->localizedNumber($results->getStartRecord()),
              '%%end%%' => $this->localizedNumber($results->getEndRecord()),
              '%%total%%' => $this->localizedNumber($recordTotal)
            ];
          ?>
          <?php if (!isset($this->skipTotalCount)): ?>
            <?=$this->translate('showing_items_of_html', $transParams); ?>
          <?php else: ?>
            <?=$this->translate('showing_items_html', $transParams); ?>
          <?php endif; ?>
      */ ?>
      </div>
      <?php /* finc: do NOT render search/list-list into the <form>-element, it is causing W3C errors #19697 */ ?>
      <?php /* <form class="form-inline" method="post" name="bulkActionForm" action="<?=$this->url('cart-searchresultsbulk')?>"> */ ?>
        <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', $searchDetails + ['idPrefix' => ''])?>
        <?=$this->render('search/list-' . $results->getParams()->getView() . '.phtml', $searchDetails)?>
        <?=$this->paginationControl($results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $results])?>
      <?php /* </form> */ ?>
    <?php else: ?>
      <?php /* finc: changes h4 to h3 */ ?>
      <h3><?=$this->transEsc($params->getDisplayQuery() || ($filterCount ?? 0) > 0 ? 'nohit_heading' : 'collection_empty')?></h3>
      <div class="clearfix">
      </div>
    <?php endif; ?>
  </div>
</div>

<?php /* finc: keeps '.bottom' to differentiate top and bottom sidebars, CK */ ?>
<?php /* finc: uses section for sidebar #23430 */ ?>
<section class="bottom <?=$this->layoutClass('sidebar')?>">
  <?php /* finc: uses search in sidebar, not in mainbody above, CK */ ?>
  <?php /* finc: removes div with 'collection-control' */ ?>
  <?php /* <div class="collection-control"> */ ?>
  <?php /* finc: adds h2 to sidebar */ ?>
  <h2><?=$this->transEsc('Search Collection Items')?></h2>
  <form class="form-inline" method="get" name="keywordFilterForm" id="keywordFilterForm">
    <div class="input-group">
      <input id="keywordFilter_lookfor" type="text" name="lookfor" placeholder="<?=$this->transEscAttr('Search within collection')?>" value="<?=$this->escapeHtmlAttr($params->getDisplayQuery())?>" class="form-control">
      <?php foreach ($filterList as $field => $filters): ?>
        <?php foreach ($filters as $filter): ?>
          <input type="hidden" name="filter[]" value="<?=$this->escapeHtmlAttr($filter['field'])?>:&quot;<?=$this->escapeHtmlAttr($filter['value'])?>&quot;">
        <?php endforeach; ?>
      <?php endforeach; ?>
      <input type="hidden" name="limit" value="<?=$this->escapeHtmlAttr($params->getLimit()) ?>">
      <input type="hidden" name="sort" value="<?=$this->escapeHtmlAttr($params->getSort()) ?>">
      <span class="input-group-btn">
        <button class="btn btn-primary" type="submit" name="submit">
          <?php /* finc: uses 'Search Collection Items' instead of 'Search' */ ?>
          <?php /* finc: adds aria-hidden to icon */ ?>
          <span class="sr-only"><?=$this->transEsc('Search Collection Items')?></span><i class="fa fa-search" aria-hidden="true"></i>
        </button>
      </span>
    </div>
  </form>
  <?php /* </div> */ ?>

  <?php foreach ($results->getRecommendations('side') as $current): ?>
    <?=$this->recommend($current)?>
  <?php endforeach; ?>
</section>
<!-- finc: RecordTab - collectionlist - END -->
