<!-- finc: recordtab - description -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
 * this table gets filled via recordDriver/.../data-... templates as referenced in RecordDataFormatterFactory
modified for finc:
 * adds code for responsive data table, adds span to caption
 * handles missing label #17434
 * adds empty lang (='undefined') tag
configured in: {}
 */
?>
<?php
    // Set page title.
    $this->headTitle($this->translate('Description') . ': ' . $this->driver->getBreadcrumb());

    $formatter = $this->recordDataFormatter();
    $mainFields = $formatter->getData($driver, $formatter->getDefaults('description'));
?>
<?php /* finc: adds code for responsive data table, adds span to caption */ ?>
<table class="table table-striped table-resp-data">
  <caption><span class="sr-only"><?=$this->transEsc('Description')?></span></caption>
  <?php if (!empty($mainFields)): ?>
    <?php foreach ($mainFields as $current): ?>
      <tr>
        <?php /* finc: handel missing label #17434 */ ?>
        <?php if (!empty($current['label'])): ?>
          <th><?=$this->transEsc($current['label'])?>:</th>
          <?php /* finc: adds empty lang (='undefined') tag */ ?>
          <td lang="" data-title="<?= $this->transEscAttr($current['label']) ?>:">
        <?php else: ?>
          <td lang="" colspan="2">
        <?php endif; ?>
        <?=$current['value']?></td>
        <?php /* finc: handel missing label #17434 - END */ ?>
      </tr>
    <?php endforeach; ?>
  <?php else: ?>
    <tr><td><?=$this->transEsc('no_description')?></td></tr>
  <?php endif; ?>
</table>
<!-- finc: recordtab - description - END -->
