<!-- finc: recordtab - staffviewmarc -->
<?php
/**
origin: vufind/BS3
called by view helper/controller:
usage:
modified for finc:
 * adds 'openURL', 'SOLR', 'fullrecord' #9934
configured in: {}
 */
?>
<?php
    // Set page title.
    $this->headTitle($this->translate('Staff View') . ': ' . $this->driver->getBreadcrumb());
?>
<?=\VuFind\XSLT\Processor::process('record-marc.xsl', $this->driver->getXML('marc21'))?>
<?php /* finc: adds 'openURL', 'SOLR', 'fullrecord' #9934 */ ?>
<?php if ($openURL = $this->driver->getOpenUrl()): ?>
  <table>
    <tr>
      <th><?=$this->escapeHtml('openURL')?></th>
      <td data-title="<?= $this->escapeHtml('openURL') ?>:">
        <?=$this->escapeHtml($openURL)?><br>
      </td>
    </tr>
  </table>
<?php endif; ?>
<?php $fields = $this->driver->getRawData();
if (!empty($fields)): ?>
  <?php /* finc: adds code for responsive data table here - CK */ ?>
  <table class="citation table table-striped table-resp-data">
    <caption><?=$this->translate('SOLR')?></caption>
    <?php ksort($fields);
    foreach ($fields as $key => $values): ?>
      <?php if ($key === 'fullrecord') continue; ?>
      <tr>
        <th><?=$this->escapeHtml($key)?></th>
        <td data-title="<?= $this->escapeHtml($key) ?>:"><?=$this->escapeHtml(is_array($values) ? implode(', ', $values) : $values)?></td>
      </tr>
    <?php endforeach ?>
  </table>
<?php endif; ?>
<?php /* finc: adds 'openURL', 'SOLR', 'fullrecord' #9934 - END */ ?>
<!-- finc: recordtab - staffviewmarc - END -->
