<? if (!empty($this->facetList)): ?>
  <h3><?=$this->transEsc('Limit To')?></h3>
  <div class="row-fluid">
    <? foreach ($this->facetList as $field => $list): ?>
      <div class="span<?=floor(12/count($this->facetList)) ?>">
        <label class="displayBlock" for="limit_<?=$this->escapeHtml(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
        <select class="span12" id="limit_<?=$this->escapeHtml(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
          <?
              // Sort the current facet list alphabetically; we'll use this data
              // along with the foreach below to display facet options in the
              // correct order.
              $sorted = array();
              foreach ($list['list'] as $i => $value) {
                  $sorted[$i] = $value['displayText'];
              }
              natcasesort($sorted);
          ?>
          <? foreach ($sorted as $i => $display): ?>
            <? $value = $list['list'][$i]; ?>
            <option value="<?=$this->escapeHtml(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
          <? endforeach; ?>
        </select>
      </div>
    <? endforeach; ?>
  </div>
<? endif; ?>
<?=$this->render('search/advanced/limit.phtml')?>
<? if (isset($this->dateRangeLimit)): ?>
  <fieldset class="span4 text-center">
    <legend class="text-left"><?=$this->transEsc('adv_search_year')?></legend>
    <input type="hidden" name="daterange[]" value="publishDate"/>
    <label for="publishDatefrom"><?=$this->transEsc('date_from')?>:</label>
    <input type="text" maxlength="4" class="yearbox span4" name="publishDatefrom" id="publishDatefrom" value="<?=isset($dateFacets['publishDate'][0])?$this->escapeHtml($dateFacets['publishDate'][0]):''?>" />
    <label for="publishDateto"><?=$this->transEsc('date_to')?>:</label>
    <input type="text" maxlength="4" class="yearbox span4" name="publishDateto" id="publishDateto" value="<?=isset($dateFacets['publishDate'][1])?$this->escapeHtml($dateFacets['publishDate'][1]):''?>" />
    <div class="pad"><input type="text" id="dateSlider"></div>
  </fieldset>
<? endif; ?>
<div class="clear"></div>
