<!-- START of: finna - Related/RecordDriverRelated.phtml -->
<?php if ($this->related->hasRelatedRecords()): ?>
<div class="record-driver-related-records" data-id="<?=$this->escapeHtmlAttr($this->related->getRecordId())?>" data-source="<?=$this->escapeHtmlAttr($this->related->getRecordSource())?>">
  <i class="fa fa-spinner fa-spin hide"></i>
</div>
<?php endif; ?>
<!-- END of: finna - Related/RecordDriverRelated.phtml -->
