<!-- START of: finna - Auth/MozillaPersona/loginfields.phtml -->
<div class="row persona-auth-login">
  <div class="col-sm-6 persona-auth-fields">
    <a class="persona-auth-link persona-login" data-lightbox-ignore href="" data-csrf="<?=$this->escapeHtmlAttr($this->auth()->getManager()->getCsrfHash(true))?>"><span class="persona-caption"><?=$this->transEsc('Mozilla Persona')?></span><i class="fa"></i></a>
  </div>
  <div class="col-sm-6">
    <div class="login-description">
      <p class="login-info"><?=$this->translate('login_desc_mozilla_persona_html')?></p>
      <p class="login-info"><?=$this->translate('login_desc_connect_card_html')?></p>
    </div>
  </div>
</div>
<!-- END of: finna - Auth/MozillaPersona/loginfields.phtml -->
