
<footer class="hidden-print">
    <div class="container-fluid tamuFooter">
  <div class="footer-container text-center">
    
   <nav>
   <ul aria-label="University policies and service status links">
<li><a href="https://howdy.tamu.edu/uPortal/normal/render.uP">howdy.tamu.edu</a></li>
<li><a href="https://library.tamu.edu/services/tech_troubleshooting.html">Off-Campus Access</a></li>
<li><a href="http://tamu.edu/">Texas A&amp;M University</a></li>
<li><a href="http://library.tamu.edu/about/compliance.html">Site Policies</a></li>
<li><a href="https://library.tamu.edu/services/accessibility.html">Accessibility</a></li>
<li><a href="http://www.thecb.state.tx.us/apps/txcrews/">Texas CREWS</a></li>
<li><a href="https://askus.library.tamu.edu/contact/index">Comments</a></li>
<li><a href="https://library.tamu.edu/status/">Services Status</a></li>
<li><div class="poweredby">
    <?=$this->layout()->poweredBy ?>
  </div></li>
</ul>
</nav>
</div>
</div>
   
  
</footer>
