Osoitteenmuutospyyntö, <?=$this->library ?>


Käyttäjätunnus: <?=$this->username ?>

Nimi: <?=$this->name ?>

Sähköpostiosoite: <?=$this->email ?>



Uudet tiedot:

<? foreach ($this->fields as $field => $fieldData): ?>
<?=$this->translate($fieldData['label']) ?>: <?=isset($this->data[$field]) ? $this->data[$field] : ''; ?>

<? endforeach; ?>


Vanhat tiedot:

<? foreach ($this->fields as $field => $fieldData): ?>
<? if (isset($this->profile[$field])): ?>
<?=$this->translate($fieldData['label']) ?>: <?=$this->profile[$field]; ?>

<? endif; ?>
<? endforeach; ?>
