<div class="col-xs-6 col-sm-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/publishers.jpg') ?>" alt="Bild Herausgeber" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Erwerbungsprofil</h4>
        <p></p>
        <a href="<?=$this->url('content-page', ['page' => 'acquisition']) ?>" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
