<div class="col-xs-12 col-sm-6 col-md-3 panel-buttons">
    <div class="panel-button panel-button-top">
        <a href="<?=$this->url('content-page', ['page' => 'fulltexts']) ?>" class="btn btn-primary">
            <p>Volltexte<br/><br/><font class="sublabel">E-books,<br/>digitalisierte Werke<br/>und Online-Publikationen</font></p>
        </a>
    </div>
    <div class="panel-button panel-button-bottom">
        <a href="<?=$this->url('content-page', ['page' => 'journals']) ?>" class="btn btn-primary">
            <p>Zeitschriften<br/><br/><font class="sublabel">Informationen</font></p>
        </a>
    </div>
</div>
