<div class="col-xs-6 col-sm-3 panel panel-top panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('background_fid.jpg') ?>" alt="Bild Bibliothekare" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>FID Kriminologie</h4>
        <p>Über den FID Kriminologie</p>
        <a href="<?=$this->url('content-page', ['page' => 'fid']) ?>" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
