<div class="panel panel-top panel-default tf-panel-home-3">
    <a class="panel-default-link" href="<?=$this->url('content-page', ['page' => 'krimdok_and_fid']) ?>">
        <div class="panel-image" style="background-image: url(<?=$this->imageLink('background_fid.jpg') ?>);"></div>
        <div class="panel-content">
            <h4>KrimDok und FID</h4>
            <p>Informationen und Einzelheiten</p>
            <a href="<?=$this->url('content-page', ['page' => 'news_fid']) ?>" class="btn btn-default btn-panel-more" role="button"><?=$this->transEsc('FID-News')?></a>
        </div>
    </a>
</div>
