<div class="col-xs-6 col-sm-3 panel panel-top panel-inverse">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/news.jpg') ?>" alt="" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Mitteilungen &amp; Termine</h4>
        <p>
        <ul>
            <li>Call for Papers</li>
            <li>Tagungen &amp; Konferenzen</li>
            <li>Stellenausschreibungen</li>
            <li>Habilitationen &amp; Berufungen</li>
        </ul>
        </p>
        <a href="<?=$this->url('content-page', ['page' => 'news']) ?>" class="btn btn-inverse" role="button">Weiterlesen</a>
    </div>
</div>
