<div class="col-xs-6 col-sm-3 panel panel-top panel-inverse">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/news.jpg') ?>" alt="" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Mitteilungen &amp; Termine</h4>
        <p>
        <ul>
            <li><a href="<?=$this->url('content-page', ['page' => 'call_for_papers']) ?>">Call for Papers</a></li>
            <li><a href="<?=$this->url('content-page', ['page' => 'events']) ?>">Tagungen &amp; Konferenzen</a></li>
            <li><a href="<?=$this->url('content-page', ['page' => 'jobs']) ?>">Stellenausschreibungen</a></li>
            <li><a href="<?=$this->url('content-page', ['page' => 'employments']) ?>">Habilitationen &amp; Berufungen</a></li>
        </ul>
        </p>
    </div>
</div>
