<div class="col-xs-12 col-sm-6 col-md-4 panel panel-top panel-inverse">
    <div class="panel-image" style="background-image: url(<?=$this->imageLink('frontpage/news.jpg') ?>);"></div>
    <div class="panel-content">
        <h4>Mitteilungen &amp; Termine</h4>
        <p>
        <ul>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'call_for_papers']) ?>">Call for Papers</a></li>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'events']) ?>">Tagungen &amp; Konferenzen</a></li>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'jobs']) ?>">Stellenausschreibungen</a></li>
            <li><a class="panel-inverse-link" href="<?=$this->url('content-page', ['page' => 'employments']) ?>">Habilitationen &amp; Berufungen</a></li>
        </ul>
        </p>
    </div>
</div>
