<div class="col-xs-6 col-sm-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/repositories.jpg') ?>" alt="Bild Verlage" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Kooperationspartner</h4>
        <p>Mit wem arbeiten wir zusammen?</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
