<div class="col-xs-6 col-sm-3 panel panel-bottom panel-default">
    <div class="panel-image-wrapper"><img src="<?=$this->imageLink('frontpage/user_account.jpg') ?>" alt="Bild Verlage" class="img-responsive panel-image" /></div>
    <div class="panel-content">
        <h4>Nutzeraccount</h4>
        <p>Infos zum Nutzeraccount</p>
        <a href="#" class="btn btn-default" role="button">Mehr erfahren</a>
    </div>
</div>
