<div class="tf-background-body">
    <div class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example_externals'); ?>
        </div>
    </div>
</div>

<br />

<div class="tf-background-body">
    <div class="container">
        <div class="row">
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example'); ?>
            <?=$this->content()->renderTranslated('panels/example'); ?>
        </div>
    </div>
</div>
