<?php
  /* cache fully rendered HTML of THIS template result in AmslController at the first call */
  if (isset($this->rendered_html)) {
    echo $this->rendered_html;
    return;
  }
?>
<!-- finc: amsl/sources-list - home -->
<?php
// Set up page title:
$this->headTitle($this->translate('List of available Sources'));

// Set up breadcrumbs:
$this->layout()->breadcrumbs .= '</li> <li class="active">' . $this->transEsc('List of available Sources') . '</li>';
?>

<br>
<h1><?=$this->transEsc('List of available Sources');?></h1>

<?=$this->flashmessages()?>

<?php if (isset($this->sources)): ?>
  <p><?=$this->transEsc('sources_explanatory_line');?></p>
  <form>
    <div class="form-group">
      <label for="sources-filter"><?=$this->transEsc('Filter list')?></label>
      <input type="text" id="sources-filter" class="form-control" placeholder="<?=$this->transEscAttr('Please enter filter term')?>">
    </div>
  </form>

  <p>
    <button id="collapse-all-toggler" class="btn btn-default">
      <span class="text-collapsed"><?=$this->transEsc('Expand all')?></span>
      <span class="text-expanded"><?=$this->transEsc('Collapse all')?></span>
    </button>
  </p>

  <ul id="sources-list">
    <?php foreach ($this->sources as $label => $source): ?>
      <?php if (!empty($source)): ?>
        <li>
          <a data-toggle="collapse" class="collapse-toggler" href="javascript:void(0)">
            <?=$label?>
            <i class="fa fa-chevron-down" aria-hidden="true"></i>
            <span class="sr-only"><?=$this->transEsc('Expand')?></span>
          </a>
          <ul class="panel-collapse collapse" aria-expanded="false">
            <?php foreach ($source as $sub_label => $collection): ?>
              <li>
                <?php if (!empty($collection['href'])): ?>
                <a
                  title="<?=$this->transEscAttr("Search For") . ' ' . $this->escapeHtml($sub_label)?>"
                  href="<?=$this->escapeHtml($collection['href'])?>"
                  target="_blank"
                >
                  <?=$sub_label?>
                </a>
                <?php else: ?>
                  <div tabindex="0" aria-label="<?=$this->transEscAttr("Source Title")?>">
                      <?=$sub_label?>
                  </div>
                <?php endif; ?>
                <?php if (!empty($collection['desc'])): ?>
                  <div class="margin-t" tabindex="0" aria-label="<?=$this->transEscAttr("Description")?>">
                    <i class="fa fa-info-circle" aria-hidden="true"></i>
                    <?=$collection['desc']?>
                  </div>
                <br>
                <?php endif; ?>
            </li>
            <?php endforeach; ?>
          </ul>
        </li>
      <?php endif; ?>
    <?php endforeach; ?>
  </ul>

  <div class="panel panel-primary">
    <div class="panel-body">
      <span>
        <?=$this->transEsc('support_by_dfg');?>
      </span>
      <?= $this->externalLink(
            'https://www.dfg.de',
            "<img src='{$this->imageLink('dfg_logo_text.png')}' alt='Deutsche Forschungsgemeinschaft, DFG'>",
            [],
            true
          ) ?>
    </div>
  </div>
<?php endif; ?>

<?php /* run collapse togglers + introduce a case-insensitive filter that is capable of filtering multiple filtering terms */
echo $this->inlineScript(\Laminas\View\Helper\HeadScript::FILE, 'sources-display.js', 'SET');
?>
<!-- finc: amsl/sources-list - home - END -->