<!-- START of: finna - summon/home.phtml -->
<?php
  $this->layout()->finnaMainHeader = $this->component('page-title', ['title' => $this->translate('Summon Search'), 'level' => 1, 'class' => 'content-header']);
  // Disable top search box -- this page has a special layout.

  // Set default value if necessary:
  if (!isset($this->searchClassId)) {
    $this->searchClassId = 'Solr';
  }

  // Load search actions and settings (if any):
  $options = $this->searchOptions($this->searchClassId);
  $basicSearch = $options->getSearchAction();
  $advSearch = $options->getAdvancedSearchAction();

  $this->breadcrumbs()->disable();
  $this->layout()->logosection = true;
  $this->layout()->ignoreHiddenFilterMemory = true;
?>
<!--  Begin home.phtml and close page container for extra styling  -->
</div>
<div class="container-fluid summon-home">
  <div class="container">
     <div>
        <?php if ($template = $this->content()->findTemplateForLng('summon/home-1')): ?>
        <?=$this->render($template)?>
        <?php endif; ?>
      </div>
  </div>
</div>
<!-- reopen container -->
<div class="container">
<!-- END of: finna - summon/home.phtml -->
