<div class="search-controls">
  <form class="search-sort" action="<?=$this->currentPath()?>" method="get" name="sort">
    <label for="sort_options_1"><?=$this->transEsc('Sort')?></label>
    <select id="sort_options_1" name="sort" class="jumpMenu form-control">
      <?php foreach ($this->sortList as $sortType => $sortData): ?>
        <option value="<?=$this->escapeHtmlAttr($sortType)?>"<?=$sortData['selected'] ? ' selected="selected"' : ''?>><?=$this->transEsc($sortData['desc'])?></option>
      <?php endforeach; ?>
    </select>
    <noscript><input type="submit" class="btn btn-default" value="<?=$this->transEscAttr('Set')?>"></noscript>
  </form>
</div>
