<h4><?=$this->transEsc('Similar Items')?></h4>
<? $similarRecords = $this->related->getResults(); ?>
<? if (!empty($similarRecords)): ?>
  <ul class="list-group">
    <? foreach ($similarRecords as $data): ?>
      <li class="list-group-item">
        <? $formats = $data->getFormats(); if ($formats): ?>
        <i class="iconlabel format-<?=$this->record($data)->getFormatClass(end($formats)) ?>" title="<?=$this->escapeHtmlAttr($this->translate(end($formats), null, $format)) ?>"></i>
        <? endif; ?>
        <a href="<?=$this->recordLink()->getUrl($data)?>">
          <?=$this->escapeHtml($data->getTitle())?>
        </a>
        <? $author = $data->getPrimaryAuthor(); if (!empty($author)): ?>
          <br/><?=$this->transEsc('by')?>: <?=$this->escapeHtml($author);?>
        <? endif; ?>
        <? $pubDates = $data->getPublicationDates(); if (!empty($pubDates)): ?>
          <br/><?=$this->transEsc('Published')?>: (<?=$this->escapeHtml($pubDates[0])?>)
        <? endif; ?>
      </li>
    <? endforeach; ?>
  </ul>
<? else: ?>
  <p><?=$this->transEsc('Cannot find similar records')?></p>
<? endif; ?>