<!-- START of: finna - Related/SimilarDeferred.phtml -->
<div id="similar-records" data-id="<?=$this->escapeHtmlAttr($this->related->getRecordId()) ?>">
  <i class="fa fa-spinner fa-spin"></i>
</div>
<?
$script = <<<JS
$(document).ready(function() {
  $('#similar-records').load(path +'/AJAX/SimilarRecords', { id: $('#similar-records').data('id') });
});
JS;
?>
<?=$this->inlineScript(\Zend\View\Helper\HeadScript::SCRIPT, $script, 'SET'); ?>
<!-- END of: finna - Related/SimilarDeferred.phtml -->
