<div class="combined-search-container">
  <?php $columnIndex = 0; ?>
  <div class="combined-column">
    <?php foreach ($this->combinedResults as $searchClassId => $currentSearch): ?>
      <?php
        $viewParams = [
          'searchClassId' => $searchClassId,
          'currentSearch' => $currentSearch,
        ];
      ?>
      <?php
        if (
          !($currentSearch['ajax'] ?? false)                        // AJAX column
          && ($currentSearch['hide_if_empty'] ?? false)             // set to hide when empty
          && $currentSearch['view']->results->getResultTotal() <= 0 // and empty
        ) {
          continue;
        }
      ?>
      <div id="<?=$this->escapeHtmlAttr($currentSearch['domId'])?>" class="combined-list">
        <?php $templateSuffix = ($currentSearch['ajax'] ?? false) ? 'ajax' : 'list'; ?>
        <?=$this->render('combined/results-' . $templateSuffix . '.phtml', $viewParams)?>
      </div>
      <?php $columnIndex++; ?>
      <?php if ($columnIndex < $columns): ?>
    </div>
    <div class="combined-column">
      <?php endif; ?>
    <?php endforeach; ?>
  </div>
</div>
