<!-- auth - multiils - loginfields.phtml -->
<div class="row">
  <label class="medium-3 columns" for="login_target"><?=$this->transEsc('login_target')?>:</label>
  <div class="medium-9 columns">
    <?$currentTarget = $this->request->get('target'); if (!$currentTarget) $currentTarget = $this->auth()->getManager()->getDefaultLoginTarget();?>
    <select id="login_target" name="target" class="auto">
    <?foreach ($this->auth()->getManager()->getLoginTargets() as $target):?>
      <option value="<?=$this->escapeHtmlAttr($target)?>"<?=($target == $currentTarget ? ' selected="selected"' : '')?>><?=$this->transEsc("source_$target", null, $target)?></option>
    <? endforeach ?>
    </select>
  </div>
</div>
<div class="row">
  <label class="medium-3 columns" for="login_<?=$this->escapeHtmlAttr($topClass)?>_username"><?=$this->transEsc('Username')?>:</label>
  <div class="medium-9 columns">
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_username" type="text" name="username" value="<?=$this->escapeHtmlAttr($this->request->get('username'))?>" class="auto"/>
  </div>
</div>
<div class="row">
  <label class="medium-3 columns" for="login_<?=$this->escapeHtmlAttr($topClass)?>_password"><?=$this->transEsc('Password')?>:</label>
  <div class="medium-9 columns">
    <input id="login_<?=$this->escapeHtmlAttr($topClass)?>_password" type="password" name="password" class="auto"/>
  </div>
</div>
<!-- auth - multiils - loginfields.phtml - END -->