<? if (!empty($this->facetList)): ?>
  <h3><?=$this->transEsc('Limit To')?></h3>
  <? foreach ($this->facetList as $field => $list): ?>
  <div class="span-5">
    <label class="displayBlock" for="limit_<?=$this->escapeHtml(str_replace(' ', '', $field))?>"><?=$this->transEsc($list['label'])?>:</label>
    <select id="limit_<?=$this->escapeHtml(str_replace(' ', '', $field))?>" name="filter[]" multiple="multiple" size="10">
      <?
          // Sort the current facet list alphabetically; we'll use this data
          // along with the foreach below to display facet options in the
          // correct order.
          $sorted = array();
          foreach ($list['list'] as $i => $value) {
              $sorted[$i] = $value['displayText'];
          }
          natcasesort($sorted);
      ?>
      <? foreach ($sorted as $i => $display): ?>
        <? $value = $list['list'][$i]; ?>
        <option value="<?=$this->escapeHtml(($value['operator'] == 'OR' ? '~' : '') . $field . ':"' . $value['value'] . '"')?>"<?=(isset($value['selected']) && $value['selected'])?' selected="selected"':''?>><?=$this->escapeHtml($display)?></option>
      <? endforeach; ?>
    </select>
  </div>
  <? endforeach; ?>
  <div class="clear"></div>
<? endif; ?>
<div class="clear"></div>
