<?
  // Set page title.
  $this->headTitle($this->translate('Advanced Search'));

  // Disable top search box -- this page has a special layout.
  $this->layout()->searchbox = false;

  // Set up breadcrumbs:
  $this->layout()->breadcrumbs = '<li>' . $this->getLastSearchLink($this->transEsc('Search'), '', '<span class="divider">&gt;</span>') . '</li>'
    . '<li class="active">' . $this->transEsc('Advanced') . '</li>';

  // Set up saved search details:
  if (isset($this->saved) && is_object($this->saved)) {
    $searchDetails = $this->saved->getParams()->getQuery();
    $groups = $searchDetails->getQueries();
    $searchFilters = $this->saved->getParams()->getFilterList();
  } else {
    $searchDetails = $searchFilters = $groups = false;
  }

  // Set up Javascript:
  // Step 1: Define our search arrays so they are usuable in the javascript
  $this->headScript()->appendScript($this->render('search/advanced/globals.phtml'));
  // Step 2: Call the javascript to make use of the above
  $this->headScript()->appendFile('advanced_search.js');
  // Step 3: Build the page
  $this->headScript()->appendScript($this->partial('search/advanced/build_page.phtml', array('searchDetails' => $searchDetails)));
?>

<?=$this->flashmessages()?>
<form class="form-inline" method="get" action="<?=$this->url($this->options->getSearchAction())?>" id="advSearchForm" name="searchForm">
  <div class="<?=$this->layoutClass('mainbody')?>">
    <input type="hidden" name="sort" value="relevance">
    <div class="clearfix">
      <p class="lead pull-left"><?=$this->transEsc('Advanced Search')?></p>
    </div>
    <div class="pad"><input class="btn btn-primary pull-right" type="submit" value="Find"></div>
    <?=$this->render('search/advanced/rdsindex.phtml')?>
  </div>
</form>
