<!-- TueFind extension template -->
<div class="row title">
    <div class="col-xs-0">
        <div align="center" style="padding-top: 10px;">
            <a target="_blank" href="http://www.ub.uni-tuebingen.de/"><img src="<?=$this->imageLink('unibibliothek.png') ?>" alt="Universitätsbibliothek" /></a><br/>
            <a href="/"><img src="<?=$this->imageLink('krimdok.png') ?>" alt="KrimDok" height="40"/></a><br/>
            <a target="_blank" href="http://www.jura.uni-tuebingen.de/einrichtungen/ifk"><img src="<?=$this->imageLink('ifk.png') ?>" alt="Institut für Kriminologie"/></a>
        </div>
    </div>
</div>
