<?php
    // This is a text-only email template; do not include HTML!

    // If this record supports real-time status, we'll assume it's a local
    // resource and display call number/location/title before URL; otherwise,
    // we'll just show URL and title.  This prioritization is important,
    // since text messages can be short, and we want the most important stuff
    // at the top!
    $recordUrl = $this->shortenUrl(
        $this->serverUrl($this->recordLinker()->getUrl($this->driver))
    );
    if ($this->driver->supportsAjaxStatus()) {
        $holdings = $this->driver->getRealTimeHoldings();

        // Figure out which call number/location to display.  We'll try to find
        // a location with an available item that has a call number.  Failing that,
        // we'll take a location with an available item.  Failing that, we'll use
        // the last location encountered.
        $callno = $location = $backupLocation = false;
        $useBackupLocation = true;
        foreach ($holdings['holdings'] as $details) {
            $location = $details['location'];
            foreach ($details['items'] as $item) {
                $callno = $item['callnumber'] ?? false;
                if ($item['availability']->isAvailable()) {
                    if ($callno) {
                        // Best case scenario -- available item with call number!
                        // Exit loop in this situation.
                        $useBackupLocation = false;
                        break 2;
                    } elseif (!$backupLocation) {
                        // Save first "available" location without call # as backup
                        // (better than an unavailable location if no call #'s found)
                        $backupLocation = $location;
                    }
                }
            }
        }
        // Use backup location if no available call number was found:
        if ($useBackupLocation && $backupLocation) {
            $location = $backupLocation;
            $callno = false;
        }

        if ($callno) {
            echo $this->translate('callnumber_abbrev') . ': ' . trim($callno) . "\n";
        }
        if ($location) {
            echo $this->translate('Location') . ': ' . trim($location) . "\n";
        }
        echo $this->driver->getBreadcrumb() . "\n";
        echo $recordUrl . "\n";
    } else {
        echo $recordUrl . "\n";
        echo $this->driver->getBreadcrumb() . "\n";
    }
