<?php // This is a text-only email template; do not include HTML! ?>
<?=$this->translate('This email was sent from')?>: <?=$this->from?>

------------------------------------------------------------
<?php if (!empty($this->message)): ?><?=$this->translate('Message From Sender')?>:
<?=$this->message?>


<?php endif; ?>
  <?=$this->translate('email_link')?>: <<?=$this->shortenUrl($this->msgUrl)?>>

------------------------------------------------------------

