<div class="row" vocab="http://schema.org/" resource="#record" typeof="<?=$this->driver->getSchemaOrgFormats()?> Product">
  <div class="col-sm-3">
    <div class="text-center">
      <? /* Display thumbnail if appropriate: */ ?>
      <? $img = $this->recordImage($this->record($this->driver)) ?>
      <?= $img->render('record', array('small' => array('w' => 100, 'h' => 100, 'maxh' => 200), 'medium' => array('w' => 300, 'h' => 300, 'maxh' => 400))) ?>
      <? /* Display qrcode if appropriate: */ ?>
      <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
      <? if($QRCode): ?>
        <span class="hidden-xs">
          <br/><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/>
        </span>
      <? endif; ?>
    </div>

    <? // if you have a preview tab but want to move or remove the preview link
       // from this area of the record view, this can be split into
       // getPreviewData() (should stay here) and
       // getPreviewLink() (can go in your desired tab) ?>
    <?=$this->record($this->driver)->getPreviews()?>
  </div>

  <div class="col-sm-9">
    <h3 property="name"><?=$this->escapeHtml($this->driver->getShortTitle() . ' ' . $this->driver->getSubtitle())?></h3>

    <? $journalTitle = $this->driver->getContainerTitle(); if (!empty($journalTitle)): ?>
      <?=$this->transEsc('Published in')?>
      <? $containerID = $this->driver->getContainerRecordID(); ?>
      <a href="<?=($containerID ? $this->recordLink()->getUrl("VuFind|$containerID") : $this->record($this->driver)->getLink('journaltitle', $journalTitle))?>"><?=$this->escapeHtml($journalTitle)?></a>
      <? $ref = $this->driver->getContainerReference(); if (!empty($ref)) { echo $this->escapeHtml($ref); } ?>
    <? endif; ?>

    <? $summary = $this->driver->getSummary(); $summary = isset($summary[0]) ? $this->escapeHtml($summary[0]) : false; ?>
    <? if ($summary): ?>
      <p><?=$this->truncate($summary, 300)?></p>

      <? if(strlen($summary) > 300): ?>
        <p><a href='<?=$this->recordLink()->getTabUrl($this->driver, 'Description')?>#tabnav'><?=$this->transEsc('Full description')?></a></p>
      <? endif; ?>
    <? endif; ?>

    <? if ($this->userlist()->getMode() !== 'disabled'): ?>
      <? /* Display the lists that this record is saved to */ ?>
      <div class="savedLists hidden alert alert-info" id="savedLists">
        <strong><?=$this->transEsc("Saved in")?>:</strong>
      </div>
    <? endif; ?>

    <?/* Display Main Details */?>
    <table class="table table-striped" summary="<?=$this->transEsc('Bibliographic Details')?>">
      <? $nextTitles = $this->driver->getNewerTitles(); $prevTitles = $this->driver->getPreviousTitles(); ?>
      <? if (!empty($nextTitles)): ?>
      <tr>
        <th><?=$this->transEsc('New Title')?>: </th>
        <td>
          <? foreach($nextTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (!empty($prevTitles)): ?>
      <tr>
        <th><?=$this->transEsc('Previous Title')?>: </th>
        <td>
          <? foreach($prevTitles as $field): ?>
            <a href="<?=$this->record($this->driver)->getLink('title', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $urls = $this->driver->getURLs(); $onlineURLs = $this->driver->getOnlineURLs(); $mergedData = $this->driver->getMergedRecordData(); ?>
      <? if (!empty($urls) || !empty($onlineURLs) || !empty($mergedData['urls']) || strncmp($this->driver->getUniqueID(), 'metalib_', 8) == 0): ?>
        <tr>
          <td colspan="2">
            <div class="truncateField">
              <? if (!empty($onlineURLs) || !empty($mergedData['urls'])): ?>
                <? foreach (!empty($mergedData['urls']) ? $mergedData['urls'] : $onlineURLs as $url): ?>
                  <div class="fulltextField"><a class="fulltext availableLocWWW" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><?=!empty($url['text']) ? $this->transEsc('link_' . $url['text'], null, $url['text']) : $this->escapeHtml($this->truncateUrl($url['url'])) ?></a>
                  <? if ($url['source']): ?>
                    (<?=is_array($url['source']) ? $this->transEsc('Multiple Organisations') : $this->transEsc('source_' . $url['source'], null, $url['source']) ?>)
                  <? endif; ?>
                  </div>
                <? endforeach; ?>
        <? elseif (!empty($urls)): ?>
          <? foreach ($urls as $url): ?>
            <div class="fulltextField"><a class="fulltext availableLocWWW" href="<?=$this->escapeHtmlAttr($this->proxyUrl($url['url'])) ?>" target="_blank" title="<?=$this->escapeHtmlAttr($url['url']) ?>"><?=$this->transEsc('link_' . $url['desc'], null, $url['desc']) ?></a></div>
          <? endforeach; ?>
        <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>

      <? if ($results = $this->driver->getOtherLinks()): ?>
        <? $prevOtherLinkHeading = ''; ?>
        <? foreach ($results as $result): ?>
        <tr>
         <th><?=$prevOtherLinkHeading != $result['heading'] ? $this->transEsc('link_' . $result['heading'], null, $result['heading']) : '&nbsp;' ?></th>
           <td>
           <? if (!empty($result['isn'])): ?>
             <? $otherLinkTitle = !empty($result['title']) ? $result['title'] : $result['isn']; ?>
              <a title="<?=$this->escapeHtmlAttr($otherLinkTitle) ?>" href="<?=$this->record($this->driver)->getLink('isn', $result['isn']) ?>">
                <?=$this->escapeHtml($otherLinkTitle); ?>
              </a>
            <? elseif (!empty($result['title'])): ?>
              <a title="<?=$this->escapeHtmlAttr($result['title']) ?>" href="<?=$this->record($this->driver)->getLink('title', $result['title']) ?>">
                <?=$this->escapeHtml($result['title']); ?>
              </a>
            <? endif; ?>
            <? if (!empty($result['author'])): ?>
              (<?=$this->escapeHtml($result['author']); ?>)
            <? endif; ?>
          </td>
        <? endforeach; ?>
      <? endif; ?>

      <? if ($results = $this->driver->getNonPresenterAuthors()): ?>
      <tr>
        <th><?=$this->transEsc('Authors')?>:</th>
        <td property="author">
          <div class="truncate-field">
          <? foreach($results as $index => $author): ?>
            <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?><? if (!empty($author['role'])): ?>, <?=$this->escapeHtml($author['role'])?><? endif; ?></a>
          <? endforeach; ?>
          </div>

          <? if ($results = $this->driver->getTitleStatement()): ?>
            <a class="info-more" id="titleStatement"><?=$this->transEsc('Additional Information') ?></a>
            <div class="additional-information TODO:hide"><?=$this->escapeHtml($results) ?></div>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if (($results = $this->driver->getPresenters()) && (!empty($results['presenters']) || !empty($results['details']))): ?>
      <tr>
        <th><?=$this->transEsc('Presenters')?>:</th>
        <td property="author">
          <div class="truncate-field">
          <? if (!empty($results['presenters'])): ?>
            <? foreach($results as $index => $author): ?>
              <?=($index > 0 ? '; ' : '')?><a href="<?=$this->record($this->driver)->getLink('author', $author['name'])?>"><?=$this->escapeHtml($author['name'])?><? if (!empty($author['role'])): ?>, <?=$this->escapeHtml($author['role'])?><? endif; ?></a>
            <? endforeach; ?>
          <? endif; ?>
          <? if (!empty($results['details'])): ?>
            <? foreach($results['details'] as $detail): ?>
              <?=($index > 0 || !empty($results['presenters']) ? '<br/>' : '')?><?=$this->escapeHtml($detail)?>
            <? endforeach; ?>
          <? endif; ?>
          </div>
        </td>
      </tr>
      <? endif; ?>

      <? $altTitles = $this->driver->getAlternativeTitles(); if (!empty($altTitles)): ?>
        <tr>
          <th><?=$this->transEsc('Other Titles')?>: </th>
          <td>
          <? foreach ($altTitles as $i => $altTitle): ?>
            <?=$i > 0 ? ';' : '' ?><?=$this->escapeHtml($altTitle) ?>
          <? endforeach; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $formats = $this->driver->getFormats(); if (!empty($formats)): ?>
        <tr>
          <th><?=$this->transEsc('Format')?>: </th>
          <td>
            <?=$this->record($this->driver)->getFormatList()?>
            <? if ($physicalDescriptions = $this->driver->getPhysicalDescriptions()): ?>
              <? foreach ($physicalDescriptions as $description): ?>
                <br/>
                <?=$this->escapeHtml($description) ?>
              <? endforeach; ?>
            <? endif; ?>
          </td>
        </tr>
      <? endif; ?>

      <? $publications = $this->driver->getPublicationDetails(); if (!empty($publications)): ?>
      <tr>
        <th><?=$this->transEsc('Published')?>: </th>
        <td>
          <? foreach ($publications as $field): ?>
            <span property="publisher" typeof="Organization">
            <? $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
              <span property="location"><?=$this->escapeHtml($pubPlace)?></span>
            <? endif; ?>
            <? $pubName = $field->getName(); if (!empty($pubName)): ?>
              <span property="name"><?=$this->escapeHtml($pubName)?></span>
            <? endif; ?>
            </span>
            <? $pubDate = $field->getDate(); if (!empty($pubDate)): ?>
              <span property="publicationDate"><?=$this->escapeHtml($pubDate)?></span>
            <? endif; ?>
            <br/>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $langs = $this->driver->getLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('Language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->transEsc($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $langs = $this->driver->getOriginalLanguages(); if (!empty($langs)): ?>
        <tr>
          <th><?=$this->transEsc('original_work_language')?>: </th>
          <td><? foreach ($langs as $lang): ?><?= $this->transEsc($lang)?><br/><? endforeach; ?></td>
        </tr>
      <? endif; ?>

      <? $projectedDate = $this->driver->tryMethod('getProjectedPublicationDate'); if (!empty($projectedDate)): ?>
        <tr>
          <th><?=$this->transEsc('Projected Publication Date')?>: </th>
          <td><?=$this->transEsc($projectedDate)?></td>
        </tr>
      <? endif; ?>

      <? $dissertationNote = $this->driver->tryMethod('getDissertationNote'); if (!empty($dissertationNote)): ?>
      <tr>
        <th><?=$this->transEsc('Dissertation Note')?>: </th>
        <td><?=$this->escapeHtml($dissertationNote)?></td>
      </tr>
      <? endif; ?>

      <? $manufacturer = $this->driver->tryMethod('getManufacturer'); if (!empty($manufacturer)): ?>
      <tr>
        <th><?=$this->transEsc('Manufacturer')?>: </th>
        <td><?=$this->escapeHtml($manufacturer)?></td>
      </tr>
      <? endif; ?>

      <? $edition = $this->driver->getEdition(); if (!empty($edition)): ?>
      <tr>
        <th><?=$this->transEsc('Edition')?>: </th>
        <td property="bookEdition"><?=$this->escapeHtml($edition)?></td>
      </tr>
      <? endif; ?>

      <?/* Display series section if at least one series exists. */?>
      <? $series = $this->driver->getSeries(); if (!empty($series)): ?>
      <tr>
        <th><?=$this->transEsc('Series')?>: </th>
        <td>
          <? foreach ($series as $field): ?>
            <?/* Depending on the record driver, $field may either be an array with
               "name" and "number" keys or a flat string containing only the series
               name.  We should account for both cases to maximize compatibility. */?>
            <? if (is_array($field)): ?>
              <? if (!empty($field['name'])): ?>
                <a href="<?=$this->record($this->driver)->getLink('series', $field['name'])?>"><?=$this->escapeHtml($field['name'])?></a>
                <? if (!empty($field['number'])): ?>
                  <?=$this->escapeHtml($field['number'])?>
                <? endif; ?>
                <br/>
              <? endif; ?>
            <? else: ?>
              <a href="<?=$this->record($this->driver)->getLink('series', $field)?>"><?=$this->escapeHtml($field)?></a><br/>
            <? endif; ?>
          <? endforeach; ?>
        </td>
      </tr>
      <? endif; ?>

      <? $subjects = $this->driver->getAllSubjectHeadings(); if (!empty($subjects)): ?>
      <tr>
        <th><?=$this->transEsc('Subjects')?>: </th>
        <td>
          <div class="truncateField">
            <? foreach ($subjects as $field): ?>
            <div class="subjectLine" property="keywords">
              <? $subject = ''; ?>
              <? if(count($field) == 1) $field = explode('--', $field[0]); ?>
              <? $i = 0; foreach ($field as $subfield): ?>
                <?=($i++ == 0) ? '' : ' &&#8594; '?>
                <? $subject = trim($subject . ' ' . $subfield); ?>
                <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
              <? endforeach; ?>
            </div>
            <? endforeach; ?>
          </div>
        </td>
      </tr>
      <? endif; ?>

      <? $genres = $this->driver->tryMethod('getGenres'); if (!empty($genres)): ?>
      <tr>
        <th><?=$this->transEsc('Genre')?>: </th>
        <td>
          <div class="truncateField">
            <? foreach ($genres as $field): ?>
            <div class="subjectLine" property="keywords">
              <? $subject = ''; ?>
              <? if(count($field) == 1) $field = explode('--', $field); ?>
              <? $i = 0; foreach ($field as $subfield): ?>
                <?=($i++ == 0) ? '' : ' &&#8594; '?>
                <? $subject = trim($subject . ' ' . $subfield); ?>
                <a class="backlink" title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>"><?=trim($this->escapeHtml($subfield))?></a>
              <? endforeach; ?>
            </div>
            <? endforeach; ?>
          </div>
        </td>
      </tr>
      <? endif; ?>

      <? $classifications = $this->driver->tryMethod('getClassifications'); if (!empty($classifications)): ?>
      <tr>
        <th><?=$this->transEsc('Classification')?>: </th>
        <td>
          <div class="truncateField">
            <?
              $result = '';
              $i = 0;
              foreach ($classifications as $class => $field) {
                $result .= $i++ > 0 ? ', ' : '';
                foreach ($field as $j => $subfield) {
                  $result .= $j++ > 0 ? ', ' : '';
                  $result .= $this->escapeHtml($class) . ' ' . $this->escapeHtml($subfield);
                }
              }
            ?>
            <?=$result ?>
          </div>
        </td>
      </tr>
      <? endif; ?>

      <? $childRecordCount = $this->driver->tryMethod('getChildRecordCount'); if ($childRecordCount): ?>
      <tr>
        <th><?=$this->transEsc('child_records')?>: </th>
        <td>
          <a href="<?=$this->recordLink()->getChildRecordSearchUrl($this->driver)?>"><?=$this->transEsc('child_record_count', array('%%count%%' => $childRecordCount))?></a>
        </td>
      </tr>
      <? endif; ?>

      <? $recordLinks = $this->driver->getAllRecordLinks(); ?>
      <? if (!empty($recordLinks)): ?>
        <? $prevRecordLinkTitle = null; ?>
        <? foreach ($recordLinks as $recordLink): ?>
          <? if ($recordLink['title'] !== $prevRecordLinkTitle): ?>
            <?
              if ($prevRecordLinkTitle) {
                echo '</td></tr>';
              }
              echo '<tr><th>' . $this->transEsc($recordLink['title']) . ':</th><td>';
              $prevRecordLinkTitle = $recordLink['title'];
            ?>
          <? endif; ?>
          <a href="<?=$this->recordLink()->related($recordLink['link'])?>"><?=$this->escapeHtml($recordLink['value'])?></a><br />
        <? endforeach; ?>
        <? echo '</td>'; ?>
      </tr>
      <? endif; ?>

      <?
        $openUrl = $this->driver->openURLActive('record') ? $this->driver->getOpenURL() : false;
      ?>
      <? if ($openUrl): ?>
      <tr>
        <th><?=$this->transEsc('Online Access')?>: </th>
        <td>
          <? foreach ($urls as $current): ?>
            <a href="<?=$this->escapeHtmlAttr($this->proxyUrl($current['url']))?>"><?=$this->escapeHtml($current['desc'])?></a><br/>
          <? endforeach; ?>
          <? if ($openUrl): ?>
            <?=$this->openUrl($openUrl)?><br/>
          <? endif; ?>
        </td>
      </tr>
      <? endif; ?>

      <? if ($this->usertags()->getMode() !== 'disabled'): ?>
        <? $tagList = $this->driver->getTags(); ?>
        <tr>
          <th><?=$this->transEsc('Tags')?>: </th>
          <td>
            <span class="pull-right">
              <i class="fa fa-plus"></i> <a id="tagRecord" class="modal-link" href="<?=$this->recordLink()->getActionUrl($this->driver, 'AddTag')?>" title="<?=$this->transEsc('Add Tag')?>"><?=$this->transEsc('Add Tag')?></a>
            </span>
            <div id="tagList">
              <? if (count($tagList) > 0): ?>
                <? $i = 0; foreach ($tagList as $tag): ?><?=($i++ == 0)?'':', '?><a href="<?=$this->url('tag-home')?>?lookfor=<?=urlencode($tag->tag)?>"><?=$this->escapeHtml($tag->tag)?></a> (<?=$this->escapeHtml($tag->cnt)?>)<? endforeach; ?>
              <? else: ?>
                <?=$this->transEsc('No Tags')?>. <?=$this->transEsc('Be the first to tag this record')?>!
              <? endif; ?>
            </div>
          </td>
        </tr>
      <? endif; ?>
    </table>
    <?/* End Main Details */?>
  </div>
</div>
