<? //Don't add START and END comments ?>
<? if (!(in_array('Document/ArchiveFonds', $this->driver->getFormats()) || in_array('Document/ArchiveCollection', $this->driver->getFormats()))): ?>
  <? $parentSource = $this->driver->getSourceIdentifier(); ?>
  <? if ($this->driver->isPartOfArchiveSeries()): ?>
    <? $topIds = $this->driver->getHierarchyTopId(); $topTitles = $this->driver->getHierarchyTopTitle(); ?>
  <? else: ?>
    <? $topIds = $this->driver->getHierarchyParentId(); $topTitles = $this->driver->getHierarchyParentTitle(); ?>
  <? endif; ?>
  <? if ($topIds): ?>
      <? foreach ($topIds as $index => $parentId): ?>
        <?
          try {
            $parentUrl = $this->recordLink()->getUrl("$parentSource|$parentId");
          } catch (\Exception $e) {
            $parentUrl = '';
          }
        ?>
        <?=($index > 0 ? ', ' : '')?><a href="<?=$parentUrl?>"><?=isset($topTitles[$index]) ? $this->truncate($topTitles[$index], 180) : ''?></a>
      <? endforeach; ?>
  <? endif; ?>
<? endif; ?>
