<? //Don't add START and END comments ?>
<? if(!empty($data)): ?>
<div class="truncate-field" data-rows="3">
  <? foreach($data as $index => $author): ?>
    <?=($index > 0 ? ', ' : '')?><?=$this->escapeHtml($author['name'])?></a>
    <? if (!empty($author['roleName'])): ?><span class="author-rolename">, <?=$this->escapeHtml($author['roleName']) ?></span>
    <? endif; ?>
    <? if (!empty($author['uncredited']) && $author['uncredited']): ?> (<?=$this->transEsc('uncredited') ?>)<? endif; ?>
    <br/>
  <? endforeach; ?>
</div>
<? endif; ?>
