<? //Don't add START and END comments ?>
<? if(!empty($data)): ?>
  <div class="truncate-field">
    <? foreach ($data as $index => $item): ?>
      <?
        $additional = [];
        if (!empty($item['method'])) {
          $additional[] = $this->escapeHtml($item['method']);
        }
        if (!empty($item['date'])) {
          $additional[] = $this->escapeHtml($item['date']);
        }
      ?>
      <?=$index > 0 ? '<br/>' : '' ?><?=$this->escapeHtml($item['name']) ?><? if (!empty($additional)): ?>, <?=implode(' ', $additional) ?><? endif; ?>
    <? endforeach; ?>
  </div>
<? endif; ?>

  <? $time = $this->driver->getPremiereTime(); if (!empty($time)): ?>
    <tr>
      <th><?=$this->transEsc('Premiere Night') ?>:</th>
      <td><?=$this->escapeHtml($time);?></td>
    </tr>
  <? endif; ?>

  <? $theater= $this->driver->getPremiereTheaters(); if (!empty($theater)): ?>
    <tr>
      <th><?=$this->transEsc('Premiere Theaters') ?>:</th>
      <td>
        <div class="truncate-field">
          <?=implode('<br/>', $theater); ?>
        </div>
      </td>
    </tr>
  <? endif; ?>

  <? $brInfo = $this->driver->getBroadcastingInfo(); if (!empty($brInfo)): ?>
    <tr>
      <th><?=$this->transEsc('Broadcasting Dates') ?>:</th>
      <td>
        <div class="truncate-field">
          <? foreach($brInfo as $fields => $keys): ?>
            <? if (!empty($keys['time'])): ?>
              <?=$this->escapeHtml($keys['place'])?>, <?=$this->escapeHtml($keys['time'])?><? if (!empty($keys['viewers'])): ?>, <?=$this->transEsc('Amount of Viewers') ?>: <?=$this->escapeHtml($keys['viewers']);?> <? endif;?><br/>
            <? endif; ?>
          <? endforeach; ?>
        </div>
      </td>
    </tr>
  <? endif; ?>

  <? $fvInfo = $this->driver->getFestivalInfo(); if (!empty($fvInfo)): ?>
    <tr>
      <th><?=$this->transEsc('Film Festivals') ?>:</th>
      <td>
        <div class="truncate-field">
          <? foreach($fvInfo as $fields => $keys): ?>
            <? if (!empty($keys['name'])): ?>
                <?=$this->escapeHtml($keys['name'])?>
              <? if (!empty($keys['region'])): ?>
                <?=$this->escapeHtml($keys['region'])?>
              <? endif; ?>
              <? if (!empty($keys['date'])): ?>
                <?=$this->escapeHtml($keys['date'])?>
              <? endif; ?><br/>
            <? endif; ?>
          <? endforeach; ?>
        </div>
      </td>
    </tr>
  <? endif; ?>

  <? $foreignDist = $this->driver->getForeignDistribution(); if (!empty($foreignDist)): ?>
    <tr>
      <th><?=$this->transEsc('Foreign Distribution') ?>:</th>
      <td>
        <div class="truncate-field">
          <? foreach($foreignDist as $fields => $keys): ?>
            <? if (!empty($keys['name'])): ?>
                <?=$this->escapeHtml($keys['name'])?><? if (!empty($keys['region'])): ?>,
                <?=$this->escapeHtml($keys['region'])?>
              <? endif; ?><br/>
            <? endif; ?>
          <? endforeach; ?>
        </div>
      </td>
    </tr>
  <? endif; ?>

  <? $copies = $this->driver->getNumberOfCopies(); if (!empty($copies)): ?>
    <tr>
      <th><?=$this->transEsc('Film Copies') ?>:</th>
      <td><?=$this->escapeHtml($copies);?></td>
    </tr>
  <? endif; ?>

  <? $screenings = $this->driver->getOtherScreenings(); if (!empty($screenings)): ?>
    <tr>
      <th><?=$this->transEsc('Other Screenings') ?>:</th>
      <td>
        <div class="truncate-field">
          <? foreach($screenings as $fields => $keys): ?>
            <? if (!empty($keys['name'])): ?>
                <?=$this->escapeHtml($keys['name'])?><? if (!empty($keys['region'])): ?>, <?=$this->escapeHtml($keys['region'])?>
              <? endif; ?>
              <? if (!empty($keys['date'])): ?>
                <?=$this->escapeHtml($keys['date'])?>
              <? endif; ?><br/>
            <? endif; ?>
          <? endforeach; ?>
        </div>
      </td>
    </tr>
  <? endif; ?>
