<? //Don't add START and END comments ?>
<? if ($data == true && !$fondsOrCollection = in_array('Document/ArchiveFonds', $this->driver->getFormats()) || in_array('Document/ArchiveCollection', $this->driver->getFormats())
): ?>
    <? $parentSource = $this->driver->getSourceIdentifier(); ?>
    <? $parentIds = $this->driver->getHierarchyParentId(); $parentTitles = $this->driver->getHierarchyParentTitle(); ?>
    <? foreach ($parentIds as $index => $parentId): ?>
      <?
        try {
          $parentUrl = $this->recordLink()->getUrl("$parentSource|$parentId");
        } catch (\Exception $e) {
          $parentUrl = '';
        }
      ?>
      <?=($index > 0 ? ', ' : '')?><a href="<?=$parentUrl?>"><?=isset($parentTitles[$index]) ? $this->truncate($parentTitles[$index], 180) : ''?></a>
    <? endforeach; ?>
<? endif; ?>
