<!-- START of: finna - RecordDriver/SolrDefault/holdings.phtml -->
<div class="holding-details">
  <?
  /* Display information on duplicate records if available */
  $dedupData = $this->driver->getDedupData();
  if (count($dedupData) > 1): ?>
    <div class="dedupInformation">
        <select class="dedup-select form-control" role="listbox" aria-haspopup="true">
          <?
            if ($user = $this->auth()->getManager()->isLoggedIn()) {
              $catUsername = $user->cat_username;
            }
            $sourceOptions = array();
            foreach ($dedupData as $source => $current) {
              $optionHtml = "<option value=".$this->escapeHtmlAttr($current['id'])." class='dedup-data-id' data-source=".$this->escapeHtmlAttr($source)." role='option'>".$this->transEsc("source_$source", null, $source)." </option>";
              // see if logged in and no organisations selected in facets
              if ($user && !strpos(urlDecode($_SERVER['REQUEST_URI']), "0/", 0)) {
                // see if source and the users's organisation match, if so move to first  
                if (strstr($catUsername, $source)) {
                  array_unshift($sourceOptions, $optionHtml);
                } else {
                  $sourceOptions[] = $optionHtml;
                }
              } else {
                $sourceOptions[] = $optionHtml;
              }
            }
            echo implode('', $sourceOptions);
          ?>
        </select>
    </div>
  <? else: ?>
    <?
      if (!empty($dedupData)) {
        reset($dedupData);
        $source = key($dedupData);
      } else {
        $source = $this->driver->tryMethod('getDataSource');
      }
    ?>
    <? if ($source): ?>
      <div class="dedupInformation">
        <strong><?=$this->transEsc("source_$source", null, $source) ?></strong>
      </div>
    <? endif; ?>
  <? endif; ?>

  <div class="callnumAndLocation ajax-availability<?=$this->driver->supportsAjaxStatus() ? ' hidden' : ''?>">
    <span class="availability-load-indicator hidden"><i class="fa fa-spinner fa-spin"></i> <?=$this->transEsc('Loading')?>...<br/></span>
    <? if ($this->driver->supportsAjaxStatus()): ?>
      <strong class="hideIfDetailed"></strong>
      <span class="callnumber ajax-availability hidden">
      </span>
      <span class="location ajax-availability hidden">
      </span>
      <div class="locationDetails clearfix"></div>
    <? else: ?>
      <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
      <? endif; ?>
    <? endif; ?>
    <div class="no-holdings<?=$this->driver->supportsAjaxStatus() ? ' hidden' : ''?>">
      <?=$this->transEsc('No Holdings Available')?>
    </div>
  </div>
</div>
<!-- END of: finna - RecordDriver/SolrDefault/holdings.phtml -->
