<!-- START of: finna - RecordDriver/SolrDefault/holdings.phtml -->
<?
  $dedupData = $this->driver->getDedupData();
  $deduplicated = count($dedupData) > 1;
?>

<div class="holding-details<?= $deduplicated ? ' deduplicated' : ''?>">
  <?
  /* Display information on duplicate records if available */
  if ($deduplicated): ?>
    <div class="dedupInformation">
        <select class="dedup-select form-control" role="listbox" aria-haspopup="true">
          <? foreach ($dedupData as $source => $current): ?>
            <option value="<?=$this->escapeHtmlAttr($current['id']) ?>" class="dedup-data-id" data-source="<?=$this->escapeHtmlAttr($source) ?>" role="option"><?=$this->transEsc("source_$source", null, $source) ?></option>
          <? endforeach; ?>
        </select>
    </div>
  <? else: ?>
    <?
      if (!empty($dedupData)) {
        reset($dedupData);
        $source = key($dedupData);
      } else {
        $source = $this->driver->tryMethod('getDataSource');
      }
    ?>
    <? if ($source): ?>
      <div class="dedupInformation">
        <strong><?=$this->transEsc("source_$source", null, $source) ?></strong>
      </div>
    <? endif; ?>
  <? endif; ?>

  <div class="callnumAndLocation ajax-availability<?=$this->driver->supportsAjaxStatus() ? ' hidden' : ''?>">
    <div class="availability-load-indicator hidden"><i class="fa fa-spinner fa-spin"></i> <?=$this->transEsc('Loading')?>...<br/></div>
    <? if ($this->driver->supportsAjaxStatus()): ?>
      <strong class="hideIfDetailed"></strong>
      <span class="callnumber ajax-availability hidden">
      </span>
      <span class="location ajax-availability hidden">
      </span>
      <div class="locationDetails clearfix"></div>
    <? else: ?>
      <? $summCallNo = $this->driver->getCallNumber(); if (!empty($summCallNo)): ?>
        <strong><?=$this->transEsc('Call Number')?>:</strong> <?=$this->escapeHtml($summCallNo)?>
      <? endif; ?>
    <? endif; ?>
    <div class="no-holdings<?=$this->driver->supportsAjaxStatus() ? ' hidden' : ''?>">
      <?=$this->transEsc('No Holdings Available')?>
    </div>
  </div>
</div>
<!-- END of: finna - RecordDriver/SolrDefault/holdings.phtml -->
