<div class="recordcovers <?= $type ?><?= count($images) == 1 ? ' hidden ' : ''?>">
<? $ind = 0; ?>
<? foreach ($images as $img): ?>
<?
  $content = null;
  if ($type === 'list') {
     $content = $ind === 4 ? '&hellip;' : $ind+1;
  } else {
     $content = '<img src="' . $img['small'] . '" />';
  }
?>
<a href="<?= $img['medium'] ?>" class="image-popup image-popup-navi<?= ($type === 'list' && $ind++ > 4) ? ' hide ' : '' ?>"><?= $content ?></a>
<a href="<?= $img['large'] ?>" class="hide"><?= $content ?></a>
<? endforeach; ?>
</div>
