<!-- START of: finna - RecordDriver/SolrDefault/record-image.phtml -->
<div class="recordcover-holder">
<?
$images = null;
if (count($allImages)) {
  $images = $allImages;
} else if ($largeImage) {
  $images = array(array('small' => $smallImage, 'medium' => $mediumImage, 'large' => $largeImage));
}
$imageData = array('images' => $images, 'type' => $type);
?>

<?= $this->partial('RecordDriver/SolrDefault/record-image-navi.phtml', $imageData) ?>

<? if ($mediumImage): ?>
<a class="image-popup-trigger" href="<?= $this->recordLink()->getUrl($this->driver) ?>#image">
<? $formats = $this->driver->tryMethod('getFormats'); ?>
<? if (count($allImages) <= 1): ?>
  <div class="iconlabel format-<?=$this->record($this->driver)->getFormatClass(end($formats))?>"></div>
<? endif; ?>
<img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumImage);?>"/>
<i class="fa fa-magnify hidden-print"></i>
</a>
<? else: ?>
  <img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
<? endif; ?>

</div>
<!-- END of: finna - RecordDriver/SolrDefault/record-image.phtml -->
