<div class="recordcover-holder">
<?
$images = null;
if (count($allImages)) {
  $images = $allImages;
} else if ($largeImage) {
  $images = array(array('small' => $smallImage, 'medium' => $mediumImage, 'large' => $largeImage));
}
$imageData = array('images' => $images, 'type' => $type);
?>

<?= $this->partial('RecordDriver/SolrDefault/record-image-navi.phtml', $imageData) ?>

<? if ($mediumImage): ?>
<i class="fa fa-zoom-in magnify"></i>
<a class="image-popup-trigger" href="<?= $this->recordLink()->getUrl($this->driver) ?>#image">
<img alt="<?=$this->transEsc('Cover Image')?>" class="recordcover" src="<?=$this->escapeHtmlAttr($mediumImage);?>"/>
</a>
<? else: ?>
<img src="<?=$this->url('cover-unavailable')?>" class="recordcover" alt="<?=$this->transEsc('No Cover Image')?>"/>
<? endif; ?>

</div>
