<?
  $addThis = $this->addThis();
  if (!empty($addThis)) {
    $this->headScript()->appendFile('https://s7.addthis.com/js/250/addthis_widget.js?pub=' . urlencode($addThis));
  }

  // Set up some variables for convenience:
  $id = $this->driver->getUniqueId();
  $controllerClass = 'controller:' . $this->record($this->driver)->getController();
  $cart = $this->cart();
  $cartId = $this->driver->getResourceSource() . '|' . $id;
  $mediumThumb = $this->record($this->driver)->getThumbnail('medium');
  $largeThumb = $this->record($this->driver)->getThumbnail('large');
  $summary = $this->driver->getSummary();
  $authors = $this->driver->getNonPresenterAuthors();
  $publisher = $this->driver->getPublicationDetails();
?>
<div class="row hidden-xs">
<div class="col-xs-12">
  <ul class="nav nav-pills hidden-print">
  <? if ($this->userlist()->getMode() !== 'disabled'): ?>
    <li><a id="save-record" class="modal-link <?=$controllerClass?>" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Save')?>" title="<?=$this->transEsc('Add to favorites')?>"><i class="fa fa-plus"></i><span class="hidden-xs"> <?=$this->transEsc('Add to favorites')?></span></a></li>
  <? endif; ?>
    <li><a id="mail-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-email', array('id'=>$id)) ?>" title="<?=$this->transEsc('Email this')?>"><i class="fa fa-envelope"></i><span class="hidden-xs"> <?=$this->transEsc('Email this')?></span></a></li>
  <? $exportFormats = $this->export()->getFormatsForRecord($this->driver); ?>
  <? if(count($exportFormats) > 0): ?>
    <li class="dropdown">
      <a class="export-toggle dropdown-toggle" data-toggle="dropdown" href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>"><i class="fa fa-list-alt"></i><span class="hidden-xs"> <?=$this->transEsc('Export Record') ?></span></a>
      <ul class="dropdown-menu" role="menu">
        <? foreach ($exportFormats as $exportFormat): ?>
          <li><a <? if ($this->export()->needsRedirect($exportFormat)): ?>target="<?=$this->escapeHtmlAttr($exportFormat)?>Main" <? endif; ?>href="<?=$this->recordLink()->getActionUrl($this->driver, 'Export')?>?style=<?=$this->escapeHtmlAttr($exportFormat)?>"><?=$this->transEsc('Export to')?> <?=$this->transEsc($exportFormat)?></a></li>
        <? endforeach; ?>
      </ul>
    </li>
  <? endif; ?>
  <? if (count($this->driver->getCitationFormats()) > 0): ?>
    <li><a id="cite-record" class="modal-link <?=$controllerClass?>" href="<?=$this->url('record-cite', array('id'=>$id)) ?>" title="<?=$this->transEsc('Cite this')?>"><i class="fa fa-asterisk"></i><span class="hidden-xs"> <?=$this->transEsc('Cite this')?></span></a></li>
  <? endif; ?>
  <li class="hidden-xs hidden-sm"><span><a href="javascript:window.print()"><i class="fa fa-print"></i> <?=$this->transEsc('Print')?></a></span></li>
  <? $QRCode = $this->record($this->driver)->getQRCode("core"); ?>
  <? if($QRCode): ?>
  <li class="dropdown">
    <a class="dropdown-toggle" data-toggle="dropdown" href="<?=$this->escapeHtmlAttr($QRCode);?>"><i class="fa fa-qr-code"></i><span class="hidden-xs"> <?=$this->transEsc('QR Code') ?></span></a>
      <ul class="dropdown-menu" role="menu">
        <li class="text-center"><img alt="<?=$this->transEsc('QR Code')?>" class="qrcode" src="<?=$this->escapeHtmlAttr($QRCode);?>"/></li>
      </ul>
  </li>
  <? endif; ?>
  <? if (!empty($addThis)): ?>
    <li class="addthis-share-buttons">
      <div class="addthis_toolbox addthis_default_style">
        <a class="addthis_button_facebook"><i class="fa fa-facebook"></i></a>
        <a class="addthis_button_twitter"><i class="fa fa-twitter"></i></a>
        <a class="addthis_button_pinterest_share"><i class="fa fa-pinterest"></i></a>
        <!-- <a class="addthis_button_google_plusone_share"><i class="fa fa-google-plus"></i></a> -->
      </div>
      <? // Fetch correct image link and metadata here for Facebook, Pinterest and Twitter ?>
      <? $this->doctype(Zend\View\Helper\Doctype::XHTML1_RDFA); ?> <? // See: http://framework.zend.com/manual/current/en/modules/zend.view.helpers.head-meta.html ?>
      <? $this->headMeta()->setProperty('og:title', $this->escapeHtml($this->driver->getShortTitle())); ?>
      <? if ($summary): ?>
        <? if (iconv_strlen($summary[0]) < 157): ?> <? // max 156 chr ?>
          <? $ogDesc = $summary[0]; ?>
        <? else: ?>
          <? $ogDesc = ($this->truncate($summary[0], 153)); ?> <? // max 156 - '3 dots'(...) = 153 ?>
        <? endif; ?>
        <? $this->headMeta()->setProperty('og:description', $ogDesc); ?>
      <? endif; ?>
      <? if (($authors) && !($authNames = isset($_SESSION['authNames']))): ?>
        <? foreach($authors as $index => $author): ?>
          <? $authNames .= ($index > 0 ? '; ' : ''); ?>
          <? $authNames .= ($this->escapeHtml($author['name'])); ?>
          <? if (!empty($author['role'])): ?>
            <? $authNames .= ", "; ?>
            <? $authNames .= ($this->escapeHtml($author['role'])); ?>
          <? endif; ?>
        <? endforeach; ?>
        <? $this->headMeta()->setProperty('article:author', $authNames); ?>
      <? endif; ?>
      <? if (($publisher) && !($publisherName = isset($_SESSION['publisherName']))): ?>
        <? foreach ($publisher as $field): ?>
          <? $pubName = $field->getName(); if (!empty($pubName)): ?>
            <? $publisherName .= ($this->escapeHtml($pubName)); ?>
          <? else: $pubPlace = $field->getPlace(); if (!empty($pubPlace)): ?>
            <? $publisherName .= ($this->escapeHtml($pubPlace)); ?>
            <? endif; ?>
          <? endif; ?>
        <? endforeach; ?>
        <? $this->headMeta()->setProperty('article:publisher', $publisherName); ?>
      <? endif; ?>
      <? $this->headMeta()->setProperty('og:image', $this->escapeHtmlAttr($mediumThumb)); ?>
      <? $this->headMeta()->appendName('twitter:card', 'summary'); ?>
      <? $this->headMeta()->appendName('twitter:site', '@finnafi'); ?>
      <? $this->headMeta()->appendName('twitter:title', ($this->escapeHtml($this->driver->getShortTitle()))); ?>
      <? if ($summary): ?>
        <? if (iconv_strlen($summary[0]) < 201): ?> <? // max 200 chr ?>
          <? $twDesc = $summary[0]; ?>
        <? else: ?>
          <? $twDesc = truncate($summary[0], 197); ?> <? // max 200 - '3 dots'(...) = 197 ?>
        <? endif; ?>
        <? $this->headMeta()->appendName('twitter:description', $twDesc); ?>
      <? endif; ?>
      <? $this->headMeta()->appendName('twitter:image', ($this->escapeHtmlAttr($mediumThumb))); ?>
    </li>
  <? endif; ?>
  <? if ($cart->isActive()): ?>
    <li id="bookbag-menu">
      <input id="cartId" type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
      <a id="cart-add" class="<? if(!$cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-plus"></i> <?=$this->transEsc('Add to Book Bag') ?></a>
      <a id="cart-remove" class="<? if($cart->contains($cartId)): ?>correct <? endif ?>hidden" href="#"><i class="fa fa-minus-circle"></i> <?=$this->transEsc('Remove from Book Bag') ?></a>
      <noscript>
        <form method="post" name="addForm" action="<?=$this->url('cart-home')?>">
          <input type="hidden" name="ids[]" value="<?=$this->escapeHtmlAttr($cartId)?>" />
          <? if ($cart->contains($cartId)): ?>
            <input class="btn btn-default" type="submit" name="delete" value="<?=$this->transEsc('Remove from Book Bag')?>"/>
          <? else: ?>
            <input class="btn btn-default" type="submit" name="add" value="<?=$this->transEsc('Add to Book Bag')?>"/>
          <? endif; ?>
        </form>
      </noscript>
    </li>
  <? endif; ?>
  </ul>
</div>
</div>

