<?php foreach ($data as $review): ?>
  <?php $linked_ppn = $review['id']; ?>
  <?php $label = $this->escapeHtml($review['title']); ?>
  <?php if (!empty($review['author'])): $label .= ' (' . $this->escapeHtml($review['author']) . ')'; endif; ?>
  <?php if ($linked_ppn != ''): ?>
    <a href="<?=$this->recordLinker()->getUrl($review['id'])?>"><?=$label?></a>
  <?php else: ?>
    <?=$label?>
  <?php endif; ?>
  <br/>
<?php endforeach; ?>