<?php foreach ($data as $reviewed): ?>
  <?php $linked_ppn = $reviewed['id']; ?>
  <?php if (empty($reviewed['reviewer'])): $author = ''; else: $author = ' ('.$this->escapeHtml($reviewed['author']) . ')'; endif; ?>
  <?php if ($linked_ppn != ''): ?>
    <a href="<?=$this->recordLink()->getUrl($linked_ppn)?>"><?=$this->escapeHtml($reviewed['title']) . $author?></a>
  <?php else: ?>
    <?=$this->escapeHtml($reviewed['title']) . $author?>
  <?php endif; ?>
  <br/>
<?php endforeach; ?>