<?php foreach ($this->driver->getReviewedRecords() as $title => $title_properties): ?>
  <?php $linked_ppn = $title_properties[1]; ?>
  <?php if (empty($title_properties[0])): $reviewer = ""; else: $reviewer = " (".$this->escapeHtml($title_properties[0]).")"; endif; ?>
  <?php if ($linked_ppn != "000000000"): ?>
    <a href="<?=$linked_ppn?>"><?=$this->escapeHtml($title) . $reviewer?></a>
  <?php else: ?>
    <?=$this->escapeHtml($title) . $reviewer?>
  <?php endif; ?>
  <br/>
<?php endforeach; ?>