<h1>Tagi / etykiety</h1>

<p>
    <em>tagi</em> (wymawia sie teg) oraz <em>etykiety</em> sa to hasla dla obiektów takich jak obrazy, artykuly, wideoklipy.
    Taging jest wolna forma haslowania.
</p>

<p>
    Przydzial <em>tagów</em> wykonuje sie bez regul klasyfikacyjnych.
    <em>Tagi</em> uzywa sie do klasyfikacji zródel internetowych, takich jak plików, stron internetowych i cyfrowych obrazów, czy zakladek.
    <em>Tagging</em> zostal poznany przede wszystkim w kontekscie pojecia WEB 2.0.
</p>

<p>
    Objekt laczy sie z jednym albo wiecej <em>tagami</em> i jest zarzadzany przez program klasyfikujacy.
    Ten program oferuje linki na inne objekty, które dziela to samo haslo, albo do listy dalszych <em>tagów</em>.
    Przez to objekty te moga byc za pomoca nawigatora w prosty sposób wywolywane.
</p>
