<?
    // Set up page title:
    $this->headTitle($this->translate('external_auth_heading'));
?>
<div data-role="page" id="EzProxy-login">
  <?=$this->mobileMenu()->header()?>
  <div data-role="content">
    <?=$this->flashmessages()?>
    <? if ($this->unauthorized): ?>
      <div class="unauthorized-description">
        <p><?=$this->transEsc('external_auth_unauthorized_desc'); ?></p>
      </div>
      <div>
        <a href="<?=$this->url('myresearch-logout')?>" data-role="button" title="<?=$this->transEsc("Log Out")?>"><strong><?=$this->transEsc("Log Out")?></strong></a>
      </div>
    <? endif; ?>
  </div>
  <?=$this->mobileMenu()->footer()?>
</div>