<!-- finc: RecordDriver - SolrMarc - data-licence -->
<?php
/**
origin: finc/RecordDriver/SolrMarc/
called by view helper/controller:
usage:
modified for finc-SolrMarc:
 * finc-SolrMarc specific template
configured in: {}
 */
?>
<?php if (is_array($data) && count($data)): ?>
  <?php foreach ($data as $license) : ?>
    <div>
      <?php $text = ($license['code'] ?? '') . (isset($license['text']) ? " ({$license['text']})" : '') ?>
      <?php if (isset($license['url'])): ?>
          <?= $this->externalLink($license['url'], $text ?? $license['url']) ?>
      <?php else: ?>
          <?= $text ?>
      <?php endif;?>
    </div>
  <?php endforeach; ?>
<?php endif; ?>
<!-- finc: RecordDriver - SolrMarc - data-licence - END -->
