<!-- finc: RecordDriver - solrMarc - data-localSubjects -->
<?php
/**
origin: finc/RecordDriver/SolrMarc/
called by view helper/controller:
usage:
modified for finc-SolrMarc:
 * finc-SolrMarc specific template
configured in: {}
 */
?>
<?php if (!(empty($data))): ?>
  <?php $i = 0; ?>
  <?php foreach ($data as $subject): ?>
    <?=($i++ == 0) ? '' : ', ';?>
    <a title="<?=$this->escapeHtmlAttr($subject)?>" href="<?=$this->record($this->driver)->getLink('subject', $subject)?>" rel="nofollow">
      <?=trim($this->escapeHtml($subject))?>
    </a>
  <?php endforeach; ?>
<?php endif; ?>
<!-- finc: RecordDriver - solrMarc - data-localSubjects - END -->
