<!-- START of: finna - list/header.phtml -->
<div>
  <h1 class="public-list-header">

    <?php if (isset($this->overrideSearchHeading)): ?>
      <?=$this->overrideSearchHeading?>
    <?php elseif (!empty($this->params) && $this->params->getSearchType() == 'basic'): ?>
      <strong><?=$this->escapeHtml($this->lookfor)?></strong>
    <?php endif; ?>

  </h1>
</div>
<!-- END of: finna - list/header.phtml -->
