<!-- START of: finna - list/list-notes.phtml -->
<?php
  $list = $this->results->getListObject();
  $notes = $this->driver->getListNotes($list->id); if (!empty($notes)): ?>
  <div class="notes">
    <p class="note-heading">
      <span class="heading"><?=$this->transEsc('Description')?>:</span>
    </p>
    <div class="note-rows">
      <?php
      $note = implode('', $notes);
      if ($this->params->getView() == 'list') {
        $note = $this->markdown()->toHtml($note);
      }
      echo $note
      ?>
    </div>
  </div>
<?php endif; ?>
<!-- END of: finna - list/list-notes.phtml -->
