<!-- START of: finna - list/list.phtml -->
<?php
$list = $this->results->getListObject();
// Set up page title:
$this->headTitle(isset($list) ? $list->getTitle() : $this->translate('saved_items'));
// Set up Finna Main Header:
$this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
    'list/header.phtml',
    [
        'lookfor' => $list->getTitle(),
    ]
);

$this->hideCartControls = true;

$this->assetManager()->appendScriptLink('check_item_statuses.js');
$this->assetManager()->appendScriptLink('finna-item-status.js');
$this->assetManager()->prependScriptString("var listId = {$list->getId()}; var publicList = 1;");
?>
<?=$this->flashmessages() ?>
<div class="clearfix hidden-print">
    <div class="public-list-row">
      <div class="public-list-desc">
        <?=$this->markdown()->toHtml($list->getDescription() ?? '') ?>
      </div>
      <?php if ($this->listTags): ?>
        <div class="public-list-tags">
          <?php foreach ($this->listTags as $tag): ?>
            <div class="tag"><?= $this->escapeHtml($tag['tag']) ?></div>
          <?php endforeach ?>
        </div>
      <?php endif ?>
      <div class="public-list-info">
        <div><?= $this->transEsc('modified'); ?>: <?=($list->getFinnaUpdated() ?? $list->getCreated())->format($this->config()->dateFormat()); ?></div>
      </div>
    </div>
</div>
<div class="mylist-controls search-controls">
    <div class="pagination-container">
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results]) ?>
    </div>
    <div class="save-list-wrapper">
      <a class="btn btn-primary btn-sm btn-block" data-lightbox role="button" href="<?= $this->url('list-save', [ 'id' => $list->getId() ]) ?>" aria-label="<?=$this->transEsc('import_favorites_from_list')?>"><?=$this->icon('list-save') ?> <span class="hidden-xs hidden-sm"><?=$this->transEsc('import_favorites_from_list')?></span></a>
    </div>
    <div class="control-container text-right hidden-print">
      <?=$this->render('search/controls/sort.phtml')?>
      <?=$this->render('search/controls/limit.phtml')?>
      <?=$this->render('search/controls/view.phtml')?>
    </div>
</div>
<div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->params->getView())?>">
    <form id="search-cart-form" class="form-inline" method="post" name="bulkActionForm" action="<?= $this->url('cart-home') ?>" autocomplete="off">
    </form>
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => '', 'formAttr' => 'search-cart-form']) ?>
    <?=$this->render('search/list-' . $this->params->getView() . '.phtml') ?>
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => 'bottom_', 'formAttr' => 'search-cart-form']) ?>
</div>
<div class="container-fluid pagination-background">
  <div class="container">
    <div class="text-center">
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'Helpers/pagination.phtml', ['params' => ['results' => $this->results]])?>
    </div>
  </div>
</div>
<?php // NOTE: insert extra closing div here to make the RSS-link container 100% wide ?>
</div>

<div class="container-fluid searchtools-background">
  <div class="container">
    <div class="searchtools hidden-print">
      <?php $this->results->getParams()->setPage(1); ?>
      <a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>"><?=$this->icon('rss-feed') ?> <?=$this->transEsc('Get RSS Feed')?></a>
    </div>
  </div>
<?php // NOTE: leave out a closing div to compensate for the one added above ?>
<!-- END of: finna - list/list.phtml -->
