<!-- START of: finna - list/list.phtml -->
<?php
$list = $this->results->getListObject();
// Set up page title:
$this->headTitle(isset($list) ? $list->title : $this->translate('Favorites'));
// Set up Finna Main Header:
$this->layout()->finnaMainHeader = $this->context($this)->renderInContext(
    'list/header.phtml',
    [
        'lookfor' => $list->title,
    ]
);

$this->hideCartControls = true;

$this->headScript()->appendFile("check_item_statuses.js");
$this->headScript()->appendFile("finna-item-status.js");
$this->headScript()->prependScript("var listId = {$list->id}; var publicList = 1");
?>
<?=$this->flashmessages() ?>
<div class="clearfix hidden-print">
    <div class="public-list-row">
      <div class="public-list-desc">
        <?=$this->markdown()->toHtml($list->description) ?>
      </div>
      <div class="public-list-info">
        <div><?= $this->transEsc("modified"); ?>: <?=$this->dateTime()->convertToDisplayDate('Y-m-d H:i:s', $list->finna_updated ? $list->finna_updated : $list->created); ?></div>
      </div>
    </div>
</div>
<div class="search-controls">
    <div class="control-container text-right hidden-print mylist-controls">
      <div>
        <?=$this->render('search/controls/view.phtml')?>
        <?=$this->render('search/controls/sort.phtml')?>
        <?=$this->render('search/controls/limit.phtml')?>
      </div>
      <div>
        <a class="btn btn-primary btn-sm btn-block" data-lightbox role="button" href="<?= $this->url('list-save', [ 'id' => $list->id ]) ?>"><?=$this->transEsc('import_favorites_from_list')?></a>
      </div>
    </div>
    <div class="pagination-container">
        <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination_simple.phtml', ['results' => $this->results]) ?>
    </div>
</div>
<div class="public-list-view results result-view-<?=$this->escapeHtmlAttr($this->params->getView())?>">
    <form id="search-cart-form" class="form-inline" method="post" name="bulkActionForm" action="<?= $this->url('cart-home') ?>" autocomplete="off">
    </form>
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => '', 'formAttr' => 'search-cart-form']) ?>
    <?=$this->render('search/list-' . $this->params->getView() . '.phtml') ?>
    <?=$this->context($this)->renderInContext('search/bulk-action-buttons.phtml', ['idPrefix' => 'bottom_', 'formAttr' => 'search-cart-form']) ?>
</div>
<div class="container-fluid pagination-background">
  <div class="container">
    <div class="text-center">
      <?=$this->paginationControl($this->results->getPaginator(), 'Sliding', 'search/pagination.phtml', ['results' => $this->results])?>
    </div>
  </div>
</div>
<?php // NOTE: insert extra closing div here to make the RSS-link container 100% wide ?>
</div>

<div class="container-fluid searchtools-background">
  <div class="container">
    <div class="searchtools hidden-print">
      <?php $this->results->getParams()->setPage(1); ?>
      <a href="<?=$this->results->getUrlQuery()->setViewParam('rss')?>"><i class="fa fa-bell"></i> <?=$this->transEsc('Get RSS Feed')?></a>
    </div>
  </div>
<?php // NOTE: leave out a closing div to compensate for the one added above ?>
<!-- END of: finna - list/list.phtml -->
