<?=$this->component('page-title', ['title' => $this->translate('import_favorites_from_list')]);?>
<form class="form-record-save" method="post" action="<?=$this->url('list-save', ['id' => $this->listId])?>" name="cloneList" data-lightbox-onclose="VuFind.saveStatuses.refresh">
  <input type="hidden" name="submitButton" value="1">
  <input type="hidden" name="list" value="<?=$this->escapeHtmlAttr($this->listId) ?>">

  <div class="form-group">
    <label class="form-label" for="save_list"><?=$this->transEsc('Choose a List') ?></label>
    <select class="form-select" id="save_list" name="list">
    <?php if ($this->lists): ?>
      <?php foreach ($this->lists as $list): ?>
        <option value="<?=$this->escapeHtmlAttr($list->getId()) ?>"<?php if ($list->getId() == $this->userlist()->lastUsed()): ?> selected="selected"<?php endif; ?>>
          <?=$this->escapeHtml($list->getTitle())?><?php if ($list->isPublic()):?> (<?=mb_strtolower($this->transEsc('public_list_indicator'), 'utf-8')?>)<?php endif; ?>
        </option>
      <?php endforeach; ?>
    <?php else: ?>
      <option value=""><?=$this->transEsc('saved_items') ?></option>
    <?php endif; ?>
    </select>
    <a class="btn btn-link" id="make-list" href="<?=$this->url('editList', ['id' => 'NEW'], ['query' => ['saveListId' => $this->listId]]) ?>"><?=$this->transEsc('or create a new list'); ?></a>
  </div>

  <div class="form-group">
    <input class="btn btn-primary" type="submit" value="<?=$this->transEscAttr('Save') ?>">
  </div>
</form>
