<?
    // Set page title
    $this->headTitle($this->translate('external_auth_heading'));
?>

<div class="row external-content-access">
  <div class="col-sm-12">
    <?=$this->flashmessages()?>
    <? if ($this->unauthorized): ?>
      <div class="unauthorized-description">
        <p><?=$this->transEsc('external_auth_unauthorized_desc'); ?></p>
      </div>
      <div>
        <a href="<?=$this->url('myresearch-logout')?>" class="logout btn btn-primary" title="<?=$this->transEsc("Log Out")?>"><strong><?=$this->transEsc("Log Out")?></strong></a>
      </div>
    <? endif; ?>
  </div>
</div>
