<div class="row footer">
    <div class="col-sm-4">
        <ul class="bottom-menu">
            <li><a href="<?=$this->url('home')?>"><?=$this->transEsc('Search')?></a></li>
            <li><a href="<?=$this->url('search-history')?>"><?=$this->transEsc('Search History')?></a></li>
            <li><a href="<?=$this->url('search-advanced')?>"><?=$this->transEsc('Advanced Search')?></a></li>
            <li><a href="<?=$this->url('help-home')?>?topic=search" data-lightbox class="help-link" title="<?=$this->transEsc('Search Tips')?>"><?=$this->transEsc('Search Tips')?></a></li>
            <!-- IxTheo: add keywordchainsearch -->
            <li><a href="<?=$this->url('keywordchainsearch-home')?>"><?=$this->transEsc('Browse Keywordchains')?></a></li>
            <li><a href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
            <li><a href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
            <li><a href="<?=$this->url('myresearch-home')?>"><?=$this->transEsc('Account')?></a></li>
        </ul>
    </div>
    <div class="col-sm-4">
        <ul class="bottom-menu">
            <li><a href="/about">Über uns</a></li>
            <li><a href="/press">Presse</></li>
            <li><a href="/team">Team</a></li>
            <li><a href="/publishers">Für Verleger</a></li>
            <li><a href="/supporters">Unterstützer</a></li>
        </ul>
    </div>
    <div class="col-sm-4">
        <h6 class="font-weight-bold">Kontakt</h6>
        <p class="text-muted">Index Theologicus <br />
            Dr. Martin Faßnacht <br />
            <i class="fa fa-phone"></i> +49 (0)7071 2974029 <br />
            <br />
            Department Media Processing II<br />
            IxTheo / Cataloging<br />
            <i class="fa fa-phone"></i> +49 (0)7071 2972847<br />
            <i class="fa fa-envelope"></i> ixtheo@ub.uni-tuebingen.de<br /><br />
            <a href="/Feedback/home" class="">Kontakt</a>
        </p>
    </div>
</div>
