
<style>
.cw-card.three-links {
    background-color: #e0e0e0;
}
.cw-card.three-links img{
    border-radius: 0.4rem;
}
.cw-card.three-links a{
    display: block !important;
    width: 100% !important;
    position: relative;
    z-index: 20;
    opacity: 0.7;
    margin: 22px 0;
    background-color: #000;
    text-decoration: none;
}
.cw-card.three-links a h6{
    color:#fff;
    margin-bottom: 42px;
}
.three-links .cw-overlay-content {
    opacity: 1;
}
.ix-slick-slider-item {
    border-radius: 7px;
}
.ix-news-panel-1 {
    background-color: #EEEEEE;
}
.ix-news-panel {
    border-radius: 12px;
}
.ix-news-container-footer {
    margin-top: -24px;
    border-radius: 5px;
}
.ix-slick-slider-item-title {
    border-radius:0 0 5px 5px;
}
</style>

<div class="navbar navbar-default" style="background-color: #3586b2; border-radius: 0px; border: 0; margin-bottom: 0px;">
    <div class="container">
        <!--<div class="navbar-header"><a class="navbar-brand">Weitere Funktionen</a></div>-->
        <div class="navbar-collapse collapse" style="padding-left: 0px;">
            <ul class="nav navbar-nav">
                <li class="dropdown">
                    <a class="dropdown-toggle"><?=$this->transEsc('Browse')?>&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="<?=$this->url('keywordchainsearch-home')?>"><?=$this->transEsc('Browse Keywordchains')?></a></li>
                        <li><a class="dropdown-item" href="<?=$this->url('browse-home')?>"><?=$this->transEsc('Browse the Catalog')?></a></li>
                        <li><a class="dropdown-item" href="<?=$this->url('alphabrowse-home')?>"><?=$this->transEsc('Browse Alphabetically')?></a></li>
                    </ul>
                </li>
                <li><a href="<?=$this->url('search-results')?>?lookfor=4+esra+1-2&type=BibleRangeSearch" role="button" rel="nofollow">Bibelstellensuche</a></li>
                <li><a href="<?=$this->url('search-newitem')?>" role="button" rel="nofollow"><?=$this->transEsc('New Items')?></a></li>
                <li><a href="<?=$this->url('search-history')?>" role="button" rel="nofollow"><?=$this->transEsc('Search History')?></a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle"><?=$this->transEsc('Virtual Keyboard')?>&nbsp;<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item virtual-keyboard-greek"><?=$this->transEsc('Greek')?></a></li>
                        <li><a class="dropdown-item virtual-keyboard-hebrew"><?=$this->transEsc('Hebrew')?></a></li>
                        <?php $virtualKeyboardSnippet = '$(triggerVirtualKeyboard(\'' . $this->transEsc("Accept") . ':' . $this->transEsc("Accept") . '\', \'' . $this->transEsc("Enter") . ':' . $this->transEsc("Enter") . '\'));'; ?>
                        <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $virtualKeyboardSnippet, 'SET')?>
		    </ul>
                </li>
            </ul>
        </div>
    </div>
</div>

<?php $this->headLink()->appendStylesheet('vendor/slick/slick.css');?>
<?php $this->headLink()->appendStylesheet('vendor/slick/slick-theme.css');?>
<?php $this->headLink()->appendStylesheet('vendor/cw/swiper.css');?>

<?php $this->headScript()->appendFile('vendor/slick/slick.min.js');?>
<?php $this->headScript()->appendFile('vendor/cw/ofi.js');?>
<?php $this->headScript()->appendFile('vendor/cw/smooth-scroll.js');?>
<?php $this->headScript()->appendFile('vendor/cw/swiper.js');?>
<?php $this->headScript()->appendFile('vendor/cw/theme.js');?>

<section class="cw-py-5">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary">Aktuelles</p>
                    <h2 class="cw-h2 cw-mb-5">IxTheo News</h2>
                </div>

                <style>
                .slick-prev:before, .slick-next:before {
                    color:grey !important;
                }
                .ix-slick-slider-item {
                    height:400px;
                    color: white;
                    vertical-align: bottom;
                    background-size: cover;
                }
                .ix-slick-slider-item-title {
                    position: absolute;
                    bottom: 0;
                    width: 100%;
                    background-color: #707070;
                }
                .slick-arrow {
                    display: none !important;
                }
                </style>

                <div class="slick-slider-single-item" align="center">
                    <a href="<?=$this->url('content-page', ['page' => 'news']) ?>">
                        <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/authors.jpg')?>);">
                            <div class="ix-slick-slider-item-title">Aktuelles</div>
                        </div>
                    </a>
                    <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/discover.jpg')?>);">
                        <div class="ix-slick-slider-item-title">Blog-Aggregator</div>
                    </div>
                    <div class="ix-slick-slider-item" style="background-image: url(<?=$this->imageLink('frontpage/publishers.jpg')?>);">
                        <div class="ix-slick-slider-item-title">Workshop 2.-3.12.19</div>
                    </div>
                </div>

                <?php
                  $jsSnippet = <<< 'EOD'
                    $(document).ready(function(){
                        $('.slick-slider-single-item').slick({
                            dots: true,
                            infinite: true,
                            speed: 300,
                            fade: true,
                            cssEase: 'linear',
                            arrows: true
                        });
                    });
EOD;
              ?>
              <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
            </div>
            <div class="col-md-6">
                <div class="cw-text-center">
                    <p class="cw-subtitle cw-text-primary">Highlights</p>
                    <h2 class="cw-h2 cw-mb-5">IxTheo Services</h2>
                    <div class="ix-news-right">
                        <div class="ix-news-container">
                            <div class="ix-news-panel ix-news-panel-1">
                                <a href="<?=$this->url('content-page', ['page' => 'open_access_journals'])?>">
                                    <div><b>IxTheo Open Journals</b></div>
                                    <div><small>Open Access Zeitschriften Service</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-2">
                                <a href="<?=$this->url('content-page', ['page' => 'open_text'])?>">
                                    <div><b>IxTheo Open Text</b></div>
                                    <div><small>Zweitveröffentlichung von Aufsätzen</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-3">
                                <a href="<?=$this->url('content-page', ['page' => 'full_text_search'])?>">
                                    <div><b>Volltextsuche</b></div>
                                    <div><small>Theologica durchsuchen</small></div>
                                </a>
                            </div>
                            <div class="ix-news-panel ix-news-panel-4">
                                <a href="<?=$this->url('content-page', ['page' => 'lexicon_search'])?>">
                                    <div><b>Lexikonrecherche</b></div>
                                    <div><small>Theologische Lexika durchsuchen</small></div>
                                </a>
			    </div>
                            <div style="clear:both;">&nbsp;</div>
			    <div class="ix-news-container-footer">Alle Services</div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!-- IxTheo entdecken -->

<section class="cw-py-5 cw-bg-gray-100">
    <div class="container">
        <div class="text-center cw-pb-lg-4">
            <p class="cw-subtitle cw-text-primary">Finden | Suchen | Nutzen</p>
            <h2 class="cw-h2 cw-mb-5">IxTheo entdecken</h2>
        </div>
        <div class="row">
            <a href="<?=$this->url('content-page', ['page' => 'discover']) ?>">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-search"></i>
                        </div>
                        <h3 class="cw-h5">Suchen und Browsen</h3>
                        <div><small>Bibelstellen | CIC | Zeiträume | VerfasserInnen</small></div>
                    </div>
                </div>
            </a>
            <a href="<?=$this->url('content-page', ['page' => 'ixtheo_account']) ?>">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-user-plus"></i>
                        </div>
                        <h3 class="cw-h5">IxTheo Account</h3>
                        <div><small>Suchanfragen speichern | Favoriten speichern</small></div>
                    </div>
                </div>
            </a>
            <a href="<?=$this->url('content-page', ['page' => 'alerting']) ?>">
                <div class="col-lg-4 cw-mb-3 cw-mb-lg-0 text-center">
                    <div class="cw-px-0 cw-px-lg-3">
                        <div class="cw-icon-rounded cw-bg-primary-light cw-mb-3">
                            <i class="fa fa-bell"></i>
                        </div>
                        <h3 class="cw-h5">Alerting</h3>
                        <div><small>Benachrichtigungen über Neuerscheinungen</small></div>
                    </div>
                </div>
            </a>
        </div>
    </div>
</section>



<style>
.cw-card.three-links img{
    border-radius: 0.4rem;
}
.cw-card.three-links a{
    display: block !important;
    width: 100% !important;
    position: relative;
    z-index: 20;
    opacity: 0.7;
    margin: 22px 0;
    background-color: #000;
    text-decoration: none;
}
.cw-card.three-links a h6{
    color:#fff;
    margin-bottom: 42px;
}
.three-links .cw-overlay-content {
    opacity: 1;
}
</style>


<section class="cw-py-5">
    <div class="container">
        <div class="row cw-mb-5">
            <div class="col-md-12">
                <p class="cw-subtitle cw-text-primary">Bibliografien</p>
                <h2 class="cw-h2">Ressourcen</h2>
            </div>
        </div>
        <div class="swiper-container cw-guides-slider mx-n2 cw-pt-3 swiper-container-horizontal">
            <!-- Additional required wrapper-->
                <div class="swiper-wrapper">
                    <!-- Slides-->
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                            <a href="<?=$this->url('content-page', ['page' => 'ixtheo_content']) ?>" class="cw-tile-link"></a>
                            <img src="<?=$this->imageLink('slider/fid_content.jpg')?>" alt="Card image" class="cw-bg-image">
                            <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">FID-Content</h6>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                            <a href="<?=$this->url('content-page', ['page' => 'index_biblicus']) ?>" class="cw-tile-link"></a>
                            <img src="<?=$this->imageLink('slider/digitale_quellen.jpg')?>" alt="Card image" class="cw-bg-image">
                            <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">Digitale Quellen</h6>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                            <a href="<?=$this->url('content-page', ['page' => 'theology_digital']) ?>" class="cw-tile-link"></a>
                            <img src="<?=$this->imageLink('slider/theologie_digital.jpg')?>" alt="Card image" class="cw-bg-image">
                            <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">Theologie digital</h6>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <div class="cw-card cw-card-poster cw-gradient-overlay cw-hover-animate cw-mb-4 cw-mb-lg-0">
                            <a href="<?=$this->url('content-page', ['page' => 'canon_law']) ?>" class="cw-tile-link"></a>
                            <img src="<?=$this->imageLink('slider/historische_drucke.jpg')?>" alt="Card image" class="cw-bg-image">
                            <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">Historische Drucke</h6>
                            </div>
                        </div>
                    </div>
                    <div class="swiper-slide cw-h-auto cw-px-2">
                        <div class="cw-card cw-hover-animate cw-mb-4 cw-mb-lg-0 three-links">
                            <img src="<?=$this->imageLink('cw/prague.jpg')?>" alt="Card image" class="cw-bg-image">
                            <a href="https://relbib.de" class="">
                                <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">RelBib</h6>
                                <!--<p class="card-text text-sm">&nbsp;</p>-->
                            </div>
                            </a>
                            <a href="https://bible.ixtheo.de/" class="">
                               <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">Index Biblicus</h6>
                                <!--<p class="card-text text-sm">&nbsp;</p>-->
                            </div>
                            </a>
                            <a href="https://churchlaw.ixtheo.de/" class="">
                                <div class="cw-card-body cw-overlay-content">
                                <h6 class="cw-card-title text-cw-shadow text-uppercase">Kirchenrecht</h6>
                                <!--<p class="card-text text-sm">&nbsp;</p>-->
                            </div>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="swiper-pagination cw-mt-3"></div>
            </div>
        </div>
    </div>

    <?php
      $jsSnippet = <<< 'EOD'
        var guidesSlider = new Swiper('.cw-guides-slider', {
            slidesPerView: 5,
            spaceBetween: 15,
            /*loop: true,*/
            roundLengths: true,
            breakpoints: {
                1200: {
                    slidesPerView: 4
                },
                991: {
                    slidesPerView: 3
                },
                768: {
                    slidesPerView: 2
                },
                400: {
                    slidesPerView: 1
                }
            },
            pagination: {
                el: '.swiper-pagination',
                clickable: true,
                dynamicBullets: true
            },
        });
EOD;
      ?>
      <?=$this->inlineScript(\Laminas\View\Helper\HeadScript::SCRIPT, $jsSnippet, 'SET')?>
</section>

<section class="cw-position-relative cw-dark-overlay ix-networking-block">
    <a href="<?=$this->url('content-page', ['page' => 'networking']) ?>">
        <?php /* <img src="<?=$this->imageLink('cw/photo-1497436072909-60f360e1d4b1.jpg')?>" alt="" class="cw-bg-image"> */ ?>
        <img src="<?=$this->imageLink('searchbar.jpg')?>" alt="" class="cw-bg-image">
        <div class="container">
            <div class="cw-overlay-content cw-text-white cw-py-lg-5">
                <h3 class="cw-display-3 cw-font-weight-bold cw-text-serif cw-text-shadow cw-mb-5">Networking</h3>
            </div>
        </div>
    </a>
</section>

<div class="tf-background-body" style="display: none;">
    <div id="content" class="container">
        <div class="row">
            <?=$this->HelpText()->render('partials/discover', null, 'static');?>
            <?=$this->HelpText()->render('partials/services', null, 'static');?>
            <?=$this->HelpText()->render('partials/derivatives', null, 'static');?>
        </div>
    </div>
</div>
