<div class="background-lightblue">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row">

            <?=$this->render('partials/news.phtml'); ?>
            <?=$this->render('partials/discover.phtml'); ?>
            <?=$this->render('partials/repositories.phtml'); ?>

            <div class="col-xs-6 col-sm-3 col-md-3 col-lg-3 panel-buttons">
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">IxTheo Journals</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">IxTheo Bible</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">KirchenRecht</a>
                </div>
                <div class="row panel-button">
                    <a href="#" class="btn btn-primary">Augustinus</a>
                </div>
            </div>
        </div>

</div>
</div>

<br />

<div class="background-lightblue">
    <div class="container">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 row">

            <?=$this->render('partials/printing.phtml'); ?>
            <?=$this->render('partials/authors.phtml'); ?>
            <?=$this->render('partials/publishers.phtml'); ?>
            <?=$this->render('partials/librarians.phtml'); ?>

        </div>
    </div>
</div>