<div class="background-lightblue">
    <div class="container">
        <div class="row">
            <?=$this->render('partials/news.phtml'); ?>
            <?=$this->render('partials/discover.phtml'); ?>
            <?=$this->render('partials/repositories.phtml'); ?>
            <?=$this->render('partials/externals.phtml'); ?>
        </div>
    </div>
</div>

<br />

<div class="background-lightblue">
    <div class="container">
        <div class="row">
            <?=$this->render('partials/printing.phtml'); ?>
            <?=$this->render('partials/authors.phtml'); ?>
            <?=$this->render('partials/publishers.phtml'); ?>
            <?=$this->render('partials/librarians.phtml'); ?>
        </div>
    </div>
</div>
