<?
/*********************************************
 *
 * Impressum.phtml
 *
 * by Benjamin Schnabel, benjamin.schnabel@uni-tuebingen.de
 *
 * The imprint part of the main page.
 *
 *************************************/
?>

<div class="container">
    <?$this->headTitle($this->translate('Impressum'));?>
    <h1>Impressum</h1>
    <div class="col-md-6">
        <h2>Dr. Martin Faßnacht</h2>
        <p>
            <br/>
            <i class="fa fa-phone"></i> +49 (0)7071 2974029 <br/>
            <i class="fa fa-envelope"></i> <a href="mailto:ixtheo&#64;ub.uni-tuebingen.de">ixtheo&#64;ub.uni-tuebingen.de</a>
        </p>
    </div>
    <div class="col-md-6">
        <h2>Abteilung Medienbearbeitung II</h2>
        <p>
            IxTheo / Sacherschließung<br/>
            <i class="fa fa-phone"></i> +49 (0)7071 2972847 <br/>
            <i class="fa fa-envelope"></i> <a href="mailto:ixtheo&#64;ub.uni-tuebingen.de">ixtheo&#64;ub.uni-tuebingen.de</a>
        </p>
    </div>
</div>