<div class="row">
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//www.uni-tuebingen.de"><img src="<?=$this->imageLink('Logo_Universitaet_Tuebingen.svg') ?>" alt="Universität T&uuml;bingen" width="260"/></a>
    </div>
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//ub.uni-tuebingen.de"><img src="<?=$this->imageLink('Logo_Universitaetsbibliothek_Tuebingen.svg') ?>" alt="UB" /></a><br/><br/>
        <a target="_blank" href="//uni-tuebingen.de/fakultaeten/katholisch-theologische-fakultaet/fakultaet/"><img src="<?=$this->imageLink('k-theologische-fak.gif') ?>" alt="Katholisch-Theologische Fakult&auml;t" width="320"/></a><br/><br/>
        <a target="_blank" href="//uni-tuebingen.de/fakultaeten/evangelisch-theologische-fakultaet/fakultaet/"><img src="<?=$this->imageLink('e-theologische-fak.gif') ?>" alt="Evangelisch-Theologische Fakult&auml;t" width="320"/></a>
    </div>
    <div class="col-xs-12 col-sm-4">
        <a target="_blank" href="//dfg.de"><img src="<?=$this->imageLink('dfg_logo_schriftzug.svg') ?>" alt="DFG" width="250" height="31" /></a>
    </div>
</div>

<br />
