<h1>Unterstützer</h1>
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <img src="/themes/ixtheo2/images/logo-uni-tuebingen.png" alt="Universität T&uuml;bingen" width="260"
             height="100"/>
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <img src="/themes/ixtheo2/images/k-theologische-fak.gif" alt="Katholisch-Theologische Fakult&auml;t"
             width="460" height="71"/>
    </div>
</div>
<br />
<div class="row">
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <img src="/themes/ixtheo2/images/dfg_logo.gif" alt="DFG" width="250" height="31" />
    </div>
    <div class="col-xs-6 col-sm-6 col-md-6 col-lg-6">
        <img src="/themes/ixtheo2/images/e-theologische-fak.gif" alt="Evangelisch-Theologische Fakult&auml;t" width="460" height="71" />
    </div>
</div>

<br />