<input type="hidden" value="<?=$this->hash ?>" name="hash"/>
<input type="hidden" value="<?=$this->username ?>" name="username"/>
<? if (isset($this->username)): ?>
  <div class="control-group">
    <label class="control-label"><?=$this->transEsc('Username') ?>:</label>
    <div class="controls">
      <span class="input-xlarge uneditable-input"><?=$this->username ?></span>
    </div>
  </div>
<? endif; ?>
<? if (isset($this->verifyold) && $this->verifyold || isset($this->oldpwd)): ?>
  <div class="control-group">
    <label class="control-label"><?=$this->transEsc('old_password') ?>:</label>
    <div class="controls">
      <input type="password" name="oldpwd"/>
    </div>
  </div>
<? endif; ?>
<div class="control-group">
  <label class="control-label"><?=$this->transEsc('new_password') ?>:</label>
  <div class="controls">
    <input type="password" name="password"/>
  </div>
</div>
<div class="control-group">
  <label class="control-label"><?=$this->transEsc('confirm_new_password') ?>:</label>
  <div class="controls">
    <input type="password" name="password2"/>
  </div>
</div>
<div class="control-group">
  <div class="controls">
    <input class="btn" name="submit" type="submit"/>
  </div>
</div>