<div class="control-group">
  <label class="control-label"><?=$this->transEsc('recovery_by_username') ?>:</label>
  <div class="controls">
    <input type="text" name="username"/>
    <input class="btn" type="submit"/>
  </div>
</div>
<div class="control-group">
  <label class="control-label"><?=$this->transEsc('recovery_by_email') ?>:</label>
  <div class="controls">
    <input type="email" name="email"/>
    <input class="btn" type="submit"/>
  </div>
</div>