<div class="control-group">
  <label class="control-label"><?=$this->transEsc('recovery_by_username') ?>:</label>
  <div class="controls">
    <input type="text" name="username"/> <?=$this->translate('conjunction_or') ?>
  </div>
</div>
<div class="control-group">
  <label class="control-label"><?=$this->transEsc('recovery_by_email') ?>:</label>
  <div class="controls">
    <input type="email" name="email"/>
  </div>
</div>
<?=$this->recaptcha()->html($this->useRecaptcha) ?>
<div class="control-group">
  <div class="controls">
    <input class="btn" name="submit" type="submit" value="<?=$this->transEsc('Recover Account') ?>"/>
  </div>
</div>