    <div class="row"> 
      <div class="col-sm-9">
      <h3>
      <? if ($this->results->getResultTotal() > 0): ?>
        <? if (isset($this->overrideSearchHeading)): ?>
          <?=$this->overrideSearchHeading?>
        <? elseif ($this->params->getsearchType() == 'basic'): ?>
          <?=$this->transEsc('Search results')?>: <strong><?=$this->escapeHtml($this->lookfor)?></strong>
        <? endif; ?>
      <? else: ?>
        <p class="lead"><?=$this->transEsc('nohit_heading')?></p>
      <? endif; ?>
      </h3>
      </div>
    </div>
