    <div class="row"> 
      <div class="col-sm-9">
      <h4 class="search-result-header">
      <? if ($this->results->getResultTotal() > 0): ?>
        <? if (isset($this->overrideSearchHeading)): ?>
          <?=$this->overrideSearchHeading?>
        <? elseif ($this->params->getsearchType() == 'basic'): ?>
          <?=$this->transEsc('Search')?>: <strong><?=$this->escapeHtml($this->lookfor)?></strong>
        <? endif; ?>
      <? else: ?>
        <?=$this->transEsc('nohit_heading')?>
      <? endif; ?>
      </h4>
      </div>
    </div>
