<table class="table table-striped useraccount-table">
  <tr class="headers">
    <th class="history-time"><?=$this->transEsc("history_time")?></th>
    <th class="history-search"><?=$this->transEsc("history_search")?></th>
    <th class="history-limits"><?=$this->transEsc("history_limits")?></th>
    <th class="history-results"><?=$this->transEsc("history_results")?></th>
    <th class="history-schedule"><?=$this->transEsc($this->showSaved ? "history_schedule" : "")?></th>
    <th class="history-save"><?=$this->transEsc($this->showSaved ? "history_delete" : "history_save")?></th>
  </tr>
  <? foreach (($this->showSaved ? array_reverse($this->saved) : array_reverse($this->unsaved)) as $iteration => $info): ?>
    <tr class="<?=$iteration % 2 == 1 ? 'even' : 'odd'?>row">
      <td><?=$this->escapeHtml($this->dateTime()->convertToDisplayDateAndTime("U", $info->getStartTime()))?></td>
      <td>
        <?=$this->historylabel($info->getParams()->getSearchClassId())?>
        <a href="<?=$this->url($info->getOptions()->getSearchAction()) . $info->getUrlQuery()->getParams()?>"><?
          $desc = $info->getParams()->getDisplayQuery();
          echo empty($desc) ? $this->transEsc("history_empty_search") : $this->escapeHtml($desc);
        ?></a>
      </td>
      <td>
        <? $info->getParams()->activateAllFacets(); foreach ($info->getParams()->getFilterList() as $field => $filters): ?>
          <? foreach ($filters as $i => $filter): ?>
            <? if ($filter['operator'] == 'NOT') echo $this->transEsc('NOT') . ' '; if ($filter['operator'] == 'OR' && $i > 0) echo $this->transEsc('OR') . ' '; ?>
            <strong><?=$this->transEsc($field)?></strong>: <?=$this->escapeHtml($filter['displayText'])?><br/>
          <? endforeach; ?>
        <? endforeach; ?>
      </td>
      <td><?=$this->escapeHtml($this->localizedNumber($info->getResultTotal()))?></td>
      <td class="history-schedule">
        <? if ($this->showSaved && isset($this->schedule[$info->getSearchId()])): ?>
          <? $schedule = $this->schedule[$info->getSearchId()]; ?>
          <form class="form-inline jumpMenuForm" action="<?= $this->url('myresearch-savesearch')?>" method="get" name="schedule">
            <select name="schedule" class="jumpMenu form-control">
              <option value="0"<?=($schedule == 0) ? (' selected') : ('')?>><?=$this->transEsc("schedule_none")?></option>
              <option value="1"<?=($schedule == 1) ? (' selected') : ('')?>><?=$this->transEsc("schedule_daily")?></option>
              <option value="2"<?=($schedule == 2) ? (' selected') : ('')?>><?=$this->transEsc("schedule_weekly")?></option>
            </select>
            <input type="hidden" name="searchid" value="<?= $info->getSearchId(); ?>"/>
          </form>
        <? endif; ?>
      </td>
      <td class="history-save">
        <? if ($this->showSaved): ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?delete=<?=urlencode($info->getSearchId())?>&amp;mode=history"><i class="fa fa-remove fa-button"></i></a>
        <? else: ?>
          <a href="<?=$this->url('myresearch-savesearch')?>?save=<?=urlencode($info->getSearchId())?>&amp;mode=history"><i class="fa fa-plus-big"></i></a>
        <? endif; ?>
      </td>
    </tr>
  <? endforeach; ?>
</table>
