<!-- START of: finna - search/introductiontext.phtml -->
<div class="">
    <? if (!$this->translationEmpty('site_header_slogan')): ?><h1 class="introductionText"><?=$this->translate('site_header_slogan')?></h1><? endif; ?>
    <? if (!$this->translationEmpty('site_header_slogan_small')): ?><h3 class="introductionText"><?=$this->translate('site_header_slogan_small')?></h3><? endif; ?>
</div>
<!-- END of: finna - search/introductiontext.phtml -->
