<!-- START of: finna - search/introductiontext.phtml -->
<div class="row">
  <div class="col-md-10 col-lg-7">
    <? if (!$this->translationEmpty('site_header_slogan')): ?><h1 class="introductionText"><?=$this->translate('site_header_slogan')?></h1><? endif; ?>
    <? if (!$this->translationEmpty('site_header_slogan_small')): ?><h3 class="introductionText"><?=$this->translate('site_header_slogan_small')?></h3><? endif; ?>
  </div>
</div>
<!-- END of: finna - search/introductiontext.phtml -->
