<!-- START of: finna - search/list-grid.phtml -->
<div class="row">
  <div class="masonry-wrapper">
    <? $i = 0; foreach ($this->results->getResults() as $current): ?>
    <div id="result<?=$i++ ?>" class="col-lg-3 col-md-4 col-sm-4 col-xs-6 result grid">
      <?=$this->record($current)->getSearchResult('grid')?>
    </div>
    <? endforeach; ?>
  </div>
</div>
<!-- END of: finna - search/list-grid.phtml -->
