<? if (($srcUrl = $this->imageSrc('finna-logo_' . $this->layout()->userLang)) || ($srcUrl = $this->imageSrc('finna-logo'))): ?>
  <a href="<?=$this->url('home');?>"><span class="sr-only"><?=$this->transEsc('Home');?></span>
    <img src="<?=$srcUrl; ?>" alt="Logo" />
  </a>
<? else: ?>
  <a href="<?=$this->url('home');?>" class="finnalogo"><span class="sr-only"><?=$this->transEsc('Home');?></span></a>
<? endif; ?>
<? if ($this->layout()->templateName === 'home') : ?>
<hr>
<? endif; ?>
