<?
    // Set page title.
    $this->headTitle($this->translate('VuFind Administration - System Maintenance'));
?>
<div class="span-5">
  <?=$this->render("admin/menu.phtml")?>
</div>

<div class="span-18 last">
  <h1><?=$this->transEsc('System Maintenance')?></h1>

  <h2>Utilities</h2>
  <?=$this->flashmessages()?>
  <form method="get" action="<?=$this->url(array('controller' => 'Admin', 'action' => 'DeleteExpiredSearches'), 'default', true)?>">
    <label for="del_daysOld" style="font-weight: normal;">Delete unsaved user search histories older than</label>
    <input id="del_daysOld" type="text" name="daysOld" size="5" value="2"/> days.
    <input type="submit" name="submit" value="<?=$this->transEsc('Submit')?>"/>
  </form>
</div>

<div class="clear"></div>
