<?php
// TODO: fold this logic into record driver methods at some point:
$marc = $this->driver->tryMethod('getMarcReader');
if (is_object($marc)) {
    $marcPhdField = $marc->getField('502');
    $marcProceedingsField = $marc->getField('711');
} else {
    $marcPhdField = $marcProceedingsField = false;
}
$journalTitle = $this->driver->tryMethod('getContainerTitle');
$formats = $this->driver->tryMethod('getFormats');
if ($marcProceedingsField) {
    $format = 'CONF';
} elseif ($marcPhdField) {
    $format = 'THES';
} elseif (!empty($journalTitle) || (is_array($formats) && in_array('Article', $formats))) {
    $format = 'JOUR';
} elseif (is_array($formats) && in_array('Journal', $formats)) {
    $format = 'JFULL';
} else {
    $format = 'BOOK';
}

// Type
echo 'TY  - ' . $format . "\r\n";

$title = rtrim($this->driver->getTitle(), ' /');
if (!empty($title)) {
    echo 'TI  - ' . "$title\r\n";
}

$shortTitle = $this->driver->getShortTitle();
if (!empty($shortTitle)) {
    $shortTitle = rtrim(rtrim($shortTitle, ' /'), ' :');
    echo 'ST  - ' . "$shortTitle\r\n";
}

if (!empty($journalTitle)) {
    if (empty($title)) {
        echo 'TI  - ' . "$journalTitle\r\n";
    } else {
        echo 'T2  - ' . "$journalTitle\r\n";
    }
    $volume = $this->driver->tryMethod('getContainerVolume');
    if (!empty($volume)) {
        echo 'VL  - ' . "$volume\r\n";
    }
    $number = $this->driver->tryMethod('getContainerIssue');
    if (!empty($number)) {
        echo 'IS  - ' . "$number\r\n";
    }
    $start = $this->driver->tryMethod('getContainerStartPage');
    $end = $this->driver->tryMethod('getContainerEndPage');
    if (!empty($start)) {
        // use page range if possible
        if (!empty($end)) {
            echo 'EP  - ' . "$end\r\n";
        } else {
            // use only start page
            echo 'SP  - ' . "$start\r\n";
        }
    }
}

$series = $this->driver->tryMethod('getSeries');
if (is_array($series)) {
    foreach ($series as $current) {
        echo 'T3  - ' . (is_array($current) ? $current['name'] : $current) . "\r\n";
    }
}

foreach ($this->driver->tryMethod('getPrimaryAuthors', [], []) as $current) {
    echo 'AU  - ' . "$current\r\n";
}

foreach ($this->driver->tryMethod('getSecondaryAuthors', [], []) as $current) {
    echo 'A2  - ' . "$current\r\n";
}

$pubPlaces = $this->driver->tryMethod('getPlacesOfPublication');
$pubDates = $this->driver->tryMethod('getPublicationDates');
$pubNames = $this->driver->tryMethod('getPublishers');
if (is_array($pubPlaces) && is_array($pubDates) && is_array($pubNames)) {
    $total = min(count($pubPlaces), count($pubDates), count($pubNames));
    // if we have pub dates but no other details, we still want to export the year:
    if ($total == 0 && count($pubDates) > 0) {
        $total = 1;
    }
    for ($i = 0; $i < $total; $i++) {
        if (isset($pubPlaces[$i])) {
            echo 'CY  - ' . rtrim(str_replace(['[', ']'], '', $pubPlaces[$i]), ': ') . "\r\n";
        }
        if (isset($pubNames[$i])) {
            echo 'PB  - ' . rtrim($pubNames[$i], ', ') . "\r\n";
        }
        $date = trim($pubDates[$i], '[]. ');
        if (strlen($date) > 4) {
            $date = $this->dateTime()->extractYear($date);
        }
        if ($date) {
            echo 'PY  - ' . "$date\r\n";
        }
    }
}

$languages = $this->driver->tryMethod('getLanguages');
if (is_array($languages)) {
    foreach ($languages as $lang) {
        echo 'LA  - ' . "$lang\r\n";
    }
}

$genres = $this->driver->tryMethod('getGenres');
if (is_array($genres)) {
    foreach ($genres as $genre) {
        echo 'M3  - ' . "$genre\r\n";
    }
}

$topics = $this->driver->tryMethod('getAllSubjectHeadingsFlattened');
if (is_array($topics)) {
    foreach ($topics as $topic) {
        echo 'KW  - ' . "$topic\r\n";
    }
}

$start_page = $this->driver->tryMethod('getContainerStartPage');
if (!empty($start_page)) {
    echo 'SP  - ' . "$start_page\r\n";
}

$isbns = $this->driver->tryMethod('getISBNs');
if (is_array($isbns)) {
    foreach ($isbns as $isbn) {
        echo 'SN  - ' . "$isbn\r\n";
    }
}

$issns = $this->driver->tryMethod('getISSNs');
if (is_array($issns)) {
    foreach ($issns as $issn) {
        echo 'SN  - ' . "$issn\r\n";
    }
}

$edition = $this->driver->tryMethod('getEdition');
if (!empty($edition)) {
    echo 'ET  - ' . "$edition\r\n";
}

$notes = $this->driver->tryMethod('getGeneralNotes');
if (is_array($notes)) {
    foreach ($notes as $note) {
        echo 'N1  - ' . "$note\r\n";
    }
}

echo 'L4  - ' . $this->serverUrl($this->recordLinker()->getUrl($this->driver)) . "\r\n";

foreach ($this->record($this->driver)->getUrlList() as $url) {
    echo 'UR  - ' . "$url\r\n";
}

if ($doi = $this->driver->tryMethod('getCleanDOI')) {
    echo 'DO  - ' . "$doi\r\n";
}

$summary = $this->driver->tryMethod('getSummaryNotes');
if (is_array($summary)) {
    foreach ($summary as $note) {
        echo 'AB  - ' . "$note\r\n";
    }
}

$abstract = $this->driver->tryMethod('getAbstractNotes');
if (is_array($abstract)) {
    foreach ($abstract as $note) {
        echo 'AB  - ' . "$note\r\n";
    }
}

$notes = $this->driver->tryMethod('getLocationOfArchivalMaterialsNotes');
if (is_array($notes)) {
    foreach ($notes as $note) {
        echo 'AV  - ' . "$note\r\n";
    }
}

$call_numbers = $this->driver->tryMethod('getCallNumbers');
if (is_array($call_numbers)) {
    foreach ($call_numbers as $call_number) {
        echo 'CN  - ' . "$call_number\r\n";
    }
}

$results = $this->driver->tryMethod('getFullTitlesAltScript');
if (is_array($results)) {
    foreach ($results as $result) {
        echo 'J2  - ' . "$result\r\n";
    }
}

// End of Record:
echo "ER  -\r\n\r\n";
